MOA: moa.classifiers.multilabel.meta.MLOzaBagAdwin Class Reference
moa.classifiers.multilabel.meta.MLOzaBagAdwin Class Reference
MLOzaBagAdwin: Changes the way to compute accuracy as an input for Adwin.
Public Member Functions
void setModelContext (InstancesHeader raw_header)
Sets the reference to the header of the data stream.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance x)
Predicts the class memberships for a given instance.
Protected Attributes
int m_L = -1
Detailed Description
MLOzaBagAdwin: Changes the way to compute accuracy as an input for Adwin.
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
Revision
1
Definition at line 35 of file MLOzaBagAdwin.java.
Member Function Documentation
double [] moa.classifiers.multilabel.meta.MLOzaBagAdwin.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Reimplemented from moa.classifiers.meta.OzaBagAdwin.
Definition at line 133 of file MLOzaBagAdwin.java.
References moa.classifiers.meta.OzaBagAdwin.ensemble, moa.classifiers.Classifier.getVotesForInstance(), and moa.classifiers.multilabel.meta.MLOzaBagAdwin.m_L.
{
        int L = x.classIndex() + 1;
        if (m_L != L) {
            m_L = L;
        }
        double y[] = new double[m_L];
        for (int i = 0; i < this.ensemble.length; i++) {
            double w[] = this.ensemble[i].getVotesForInstance(x);
            for (int j = 0; j < w.length; j++) {
                y[j] += w[j];
            }
        }
        return y;
    }
void moa.classifiers.multilabel.meta.MLOzaBagAdwin.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 40 of file MLOzaBagAdwin.java.
References moa.classifiers.meta.OzaBagAdwin.ensemble, moa.classifiers.multilabel.meta.MLOzaBagAdwin.m_L, moa.classifiers.AbstractClassifier.modelContext, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OzaBagAdwin.resetLearningImpl(), and moa.classifiers.Classifier.setModelContext().
{
        //set the multilabel model context
        this.modelContext = raw_header;
        m_L = raw_header.classIndex() + 1;
        // reset ensemble
        this.resetLearningImpl();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i].setModelContext(raw_header);
            this.ensemble[i].resetLearning();
        }
    }
void moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Reimplemented from moa.classifiers.meta.OzaBagAdwin.
Definition at line 56 of file MLOzaBagAdwin.java.
References moa.classifiers.meta.OzaBagAdwin.ADError, moa.classifiers.meta.OzaBagAdwin.baseLearnerOption, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.meta.OzaBagAdwin.ensemble, moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.AbstractClassifier.modelContext, moa.classifiers.Classifier.setModelContext(), and moa.classifiers.Classifier.trainOnInstance().
{
        boolean Change = false;
        for (int i = 0; i < this.ensemble.length; i++) {
            int k = MiscUtils.poisson(1.0, this.classifierRandom);
            if (k > 0) {
                Instance weightedInst = (Instance) inst.copy();
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
            double[] prediction = this.ensemble[i].getVotesForInstance(inst);
            //Compute accuracy
            double actual[] = new double[prediction.length];
            for (short j = 0; j < prediction.length; j++) {
                actual[j] = inst.value(j);
            }
            // calculate
            int p_sum = 0, r_sum = 0;
            int set_union = 0;
            int set_inter = 0;
            double t = 0.01;
            for (int j = 0; j < prediction.length; j++) {
                int p = (prediction[j] >= t) ? 1 : 0;
                int R = (int) actual[j];
                if (p == 1) {
                    p_sum++;
                    // predt 1, real 1
                    if (R == 1) {
                        set_inter++;
                        set_union++;
                    } // predt 1, real 0
                    else {
                        set_union++;
                    }
                } else {
                    // predt 0, real 1
                    if (R == 1) {
                        set_union++;
                    } // predt 0, real 0
                    else {
                    }
                }
            }
            double accuracy = 0.0;
            if (set_union > 0) //avoid NaN
            {
                accuracy = ((double) set_inter / (double) set_union);
            }
            double ErrEstim = this.ADError[i].getEstimation();
            if (this.ADError[i].setInput(1.0 - accuracy)) {
                if (this.ADError[i].getEstimation() > ErrEstim) {
                    Change = true;
                }
            }
        }
        if (Change) {
            System.err.println("change!");
            double max = 0.0;
            int imax = -1;
            for (int i = 0; i < this.ensemble.length; i++) {
                if (max < this.ADError[i].getEstimation()) {
                    max = this.ADError[i].getEstimation();
                    imax = i;
                }
            }
            if (imax != -1) {
                this.ensemble[imax] = null;
                this.ensemble[imax] = (Classifier) getPreparedClassOption(this.baseLearnerOption);
                this.ensemble[imax].setModelContext(this.modelContext);
                this.ensemble[imax].trainOnInstance(inst);
                this.ADError[imax] = new ADWIN();
            }
        }
    }
Member Data Documentation
int moa.classifiers.multilabel.meta.MLOzaBagAdwin.m_L = -1 [protected]
Definition at line 37 of file MLOzaBagAdwin.java.
Referenced by moa.classifiers.multilabel.meta.MLOzaBagAdwin.getVotesForInstance(), and moa.classifiers.multilabel.meta.MLOzaBagAdwin.setModelContext().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/meta/MLOzaBagAdwin.java