MOA: moa.clusterers.clustream.WithKmeans Class Reference
moa.clusterers.clustream.WithKmeans Class Reference
Public Member Functions
WithKmeans ()
void resetLearningImpl ()
void trainOnInstanceImpl (Instance instance)
Clustering getMicroClusteringResult ()
Clustering getClusteringResult ()
Clustering getClusteringResult (Clustering gtClustering)
String getName ()
boolean implementsMicroClusterer ()
Miscellaneous.
boolean isRandomizable ()
double[] getVotesForInstance (Instance inst)
void getModelDescription (StringBuilder out, int indent)
Static Public Member Functions
static Clustering kMeans_gta (int k, Clustering clustering, Clustering gtClustering)
k-means of (micro)clusters, with ground-truth-aided initialization.
static Clustering kMeans_rand (int k, Clustering clustering)
k-means of (micro)clusters, with randomized initialization.
Public Attributes
IntOption timeWindowOption
IntOption maxNumKernelsOption
IntOption kernelRadiFactorOption
IntOption kOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Static Protected Member Functions
static Clustering kMeans (int k, Cluster[] centers, List<?extends Cluster > data)
(The Actual Algorithm) k-means of (micro)clusters, with specified initialization points.
static Clustering cleanUpKMeans (Clustering kMeansResult, ArrayList< CFCluster > microclusters)
Rearrange the k-means result into a set of CFClusters, cleaning up the redundancies.
Static Private Member Functions
static double distance (double[] pointA, double[] pointB)
Distance between two vectors.
static SphereCluster calculateCenter (ArrayList< Cluster > assigned, int dimensions)
k-means helper: Calculate a wrapping cluster of assigned points[microclusters].
Private Attributes
int timeWindow
long timestamp = -1
ClustreamKernel[] kernels
boolean initialized
List< ClustreamKernel > buffer
int bufferSize
double t
int m
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 45 of file WithKmeans.java.
Constructor & Destructor Documentation
moa.clusterers.clustream.WithKmeans.WithKmeans ()
Definition at line 73 of file WithKmeans.java.
{
    }
Member Function Documentation
static SphereCluster moa.clusterers.clustream.WithKmeans.calculateCenter (ArrayList< Cluster > assigned, int dimensions) [static, private]
k-means helper: Calculate a wrapping cluster of assigned points[microclusters].
Parameters:
assigned
dimensions
Returns:
SphereCluster (with center and radius)
Definition at line 416 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.distance(), and moa.cluster.SphereCluster.setWeight().
Referenced by moa.clusterers.clustream.WithKmeans.kMeans().
{
        double[] result = new double[dimensions];
        for (int i = 0; i < result.length; i++) {
            result[i] = 0.0;
        }
        if (assigned.size() == 0) {
            return new SphereCluster(result, 0.0);
        }
        for (Cluster point : assigned) {
            double[] center = point.getCenter();
            for (int i = 0; i < result.length; i++) {
                result[i] += center[i];
            }
        }
        // Normalize
        for (int i = 0; i < result.length; i++) {
            result[i] /= assigned.size();
        }
        // Calculate radius: biggest wrapping distance from center
        double radius = 0.0;
        for (Cluster point : assigned) {
            double dist = distance(result, point.getCenter());
            if (dist > radius) {
                radius = dist;
            }
        }
        SphereCluster sc = new SphereCluster(result, radius);
        sc.setWeight(assigned.size());
        return sc;
    }
static Clustering moa.clusterers.clustream.WithKmeans.cleanUpKMeans (Clustering kMeansResult, ArrayList< CFCluster > microclusters) [static, protected]
Rearrange the k-means result into a set of CFClusters, cleaning up the redundancies.
Parameters:
kMeansResult
microclusters
Returns:
Definition at line 365 of file WithKmeans.java.
References moa.cluster.CFCluster.add(), moa.AbstractMOAObject.copy(), moa.clusterers.clustream.WithKmeans.distance(), moa.cluster.Clustering.get(), moa.cluster.Cluster.getCenter(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.clustream.WithKmeans.kMeans_gta(), and moa.clusterers.clustream.WithKmeans.kMeans_rand().
{
        /* Convert k-means result to CFClusters */
        int k = kMeansResult.size();
        CFCluster[] converted = new CFCluster[k];
        for (CFCluster mc : microclusters) {
            // Find closest kMeans cluster
            double minDistance = Double.MAX_VALUE;
            int closestCluster = 0;
            for (int i = 0; i < k; i++) {
                double distance = distance(kMeansResult.get(i).getCenter(), mc.getCenter());
                if (distance < minDistance) {
                    closestCluster = i;
                    minDistance = distance;
                }
            }
            // Add to cluster
            if ( converted[closestCluster] == null ) {
                converted[closestCluster] = (CFCluster)mc.copy();
            } else {
                converted[closestCluster].add(mc);
            }
        }
        // Clean up
        int count = 0;
        for (int i = 0; i < converted.length; i++) {
            if (converted[i] != null)
            count++;
        }
        CFCluster[] cleaned = new CFCluster[count];
        count = 0;
        for (int i = 0; i < converted.length; i++) {
            if (converted[i] != null)
            cleaned[count++] = converted[i];
        }
        return new Clustering(cleaned);
    }
static double moa.clusterers.clustream.WithKmeans.distance (double[] pointA, double[] pointB) [static, private]
Distance between two vectors.
Parameters:
pointA
pointB
Returns:
dist
Definition at line 216 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.calculateCenter(), moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.clusterers.clustream.WithKmeans.kMeans(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
{
        double distance = 0.0;
        for (int i = 0; i < pointA.length; i++) {
            double d = pointA[i] - pointB[i];
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
Clustering moa.clusterers.clustream.WithKmeans.getClusteringResult (Clustering gtClustering)
Definition at line 201 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.options.IntOption.getValue(), moa.clusterers.clustream.WithKmeans.kMeans_gta(), and moa.clusterers.clustream.WithKmeans.kOption.
{
        return kMeans_gta(kOption.getValue(), getMicroClusteringResult(), gtClustering);
    }
Clustering moa.clusterers.clustream.WithKmeans.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 194 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.options.IntOption.getValue(), moa.clusterers.clustream.WithKmeans.initialized, moa.clusterers.clustream.WithKmeans.kMeans_rand(), and moa.clusterers.clustream.WithKmeans.kOption.
{
                if (!initialized) {
                    return new Clustering(new Cluster[0]);
        }
        return kMeans_rand(kOption.getValue(), getMicroClusteringResult());
    }
Clustering moa.clusterers.clustream.WithKmeans.getMicroClusteringResult ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 180 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.initialized, moa.clusterers.clustream.WithKmeans.kernels, moa.clusterers.clustream.WithKmeans.m, and moa.clusterers.clustream.WithKmeans.t.
Referenced by moa.clusterers.clustream.WithKmeans.getClusteringResult().
{
        if (!initialized) {
            return new Clustering(new Cluster[0]);
        }
        ClustreamKernel[] result = new ClustreamKernel[kernels.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = new ClustreamKernel(kernels[i], t, m);
        }
        return new Clustering(result);
    }
void moa.clusterers.clustream.WithKmeans.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 473 of file WithKmeans.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
Measurement [] moa.clusterers.clustream.WithKmeans.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 468 of file WithKmeans.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.clusterers.clustream.WithKmeans.getName ()
Definition at line 205 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.timeWindow.
{
        return "CluStreamWithKMeans " + timeWindow;
    }
double [] moa.clusterers.clustream.WithKmeans.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 463 of file WithKmeans.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
boolean moa.clusterers.clustream.WithKmeans.implementsMicroClusterer ()
Miscellaneous.
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 455 of file WithKmeans.java.
{
        return true;
    }
boolean moa.clusterers.clustream.WithKmeans.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 459 of file WithKmeans.java.
{
        return false;
    }
static Clustering moa.clusterers.clustream.WithKmeans.kMeans (int k, Cluster[] centers, List<?extends Cluster > data) [static, protected]
(The Actual Algorithm) k-means of (micro)clusters, with specified initialization points.
Parameters:
k
centers - initial centers
data
Returns:
(macro)clustering - SphereClusters
Definition at line 305 of file WithKmeans.java.
References moa.cluster.Clustering.add(), moa.clusterers.clustream.WithKmeans.calculateCenter(), moa.clusterers.AbstractClusterer.clustering, moa.clusterers.clustream.WithKmeans.distance(), moa.cluster.SphereCluster.getCenter(), and moa.cluster.Cluster.getCenter().
Referenced by moa.clusterers.clustream.WithKmeans.kMeans_gta(), and moa.clusterers.clustream.WithKmeans.kMeans_rand().
{
        assert (centers.length == k);
        assert (k > 0);
        int dimensions = centers[0].getCenter().length;
        ArrayList<ArrayList<Cluster>> clustering = new ArrayList<ArrayList<Cluster>>();
        for (int i = 0; i < k; i++) {
            clustering.add(new ArrayList<Cluster>());
        }
        while (true) {
            // Assign points to clusters
            for (Cluster point : data) {
                double minDistance = distance(point.getCenter(), centers[0].getCenter());
                int closestCluster = 0;
                for (int i = 1; i < k; i++) {
                    double distance = distance(point.getCenter(), centers[i].getCenter());
                    if (distance < minDistance) {
                        closestCluster = i;
                        minDistance = distance;
                    }
                }
                clustering.get(closestCluster).add(point);
            }
            // Calculate new centers and clear clustering lists
            SphereCluster[] newCenters = new SphereCluster[centers.length];
            for (int i = 0; i < k; i++) {
                newCenters[i] = calculateCenter(clustering.get(i), dimensions);
                clustering.get(i).clear();
            }
            // Convergence check
            boolean converged = true;
            for (int i = 0; i < k; i++) {
                if (!Arrays.equals(centers[i].getCenter(), newCenters[i].getCenter())) {
                    converged = false;
                    break;
                }
            }
            if (converged) {
                break;
            } else {
                centers = newCenters;
            }
        }
        return new Clustering(centers);
    }
static Clustering moa.clusterers.clustream.WithKmeans.kMeans_gta (int k, Clustering clustering, Clustering gtClustering) [static]
k-means of (micro)clusters, with ground-truth-aided initialization.
(to produce best results)
Parameters:
k
data
Returns:
(macro)clustering - CFClusters
Definition at line 233 of file WithKmeans.java.
References moa.cluster.Clustering.add(), moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.cluster.Clustering.get(), moa.cluster.Cluster.getCenter(), moa.clusterers.clustream.WithKmeans.kMeans(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.clustream.WithKmeans.getClusteringResult().
{
        ArrayList<CFCluster> microclusters = new ArrayList<CFCluster>();
        for (int i = 0; i < clustering.size(); i++) {
            if (clustering.get(i) instanceof CFCluster) {
                microclusters.add((CFCluster)clustering.get(i));
            } else {
                System.out.println("Unsupported Cluster Type:" + clustering.get(i).getClass() + ". Cluster needs to extend moa.cluster.CFCluster");
            }
        }
        int n = microclusters.size();
        assert (k <= n);
        /* k-means */
        Random random = new Random(0);
        Cluster[] centers = new Cluster[k];
        int K = gtClustering.size();
        for (int i = 0; i < k; i++) {
            if (i < K) {    // GT-aided
                centers[i] = new SphereCluster(gtClustering.get(i).getCenter(), 0);
            } else {        // Randomized
                int rid = random.nextInt(n);
                centers[i] = new SphereCluster(microclusters.get(rid).getCenter(), 0);
            }
        }
        return cleanUpKMeans(kMeans(k, centers, microclusters), microclusters);
    }
static Clustering moa.clusterers.clustream.WithKmeans.kMeans_rand (int k, Clustering clustering) [static]
k-means of (micro)clusters, with randomized initialization.
Parameters:
k
data
Returns:
(macro)clustering - CFClusters
Definition at line 271 of file WithKmeans.java.
References moa.cluster.Clustering.add(), moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.cluster.Clustering.get(), moa.clusterers.clustream.WithKmeans.kMeans(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.clustream.WithKmeans.getClusteringResult().
{
        ArrayList<CFCluster> microclusters = new ArrayList<CFCluster>();
        for (int i = 0; i < clustering.size(); i++) {
            if (clustering.get(i) instanceof CFCluster) {
                microclusters.add((CFCluster)clustering.get(i));
            } else {
                System.out.println("Unsupported Cluster Type:" + clustering.get(i).getClass() + ". Cluster needs to extend moa.cluster.CFCluster");
            }
        }
        int n = microclusters.size();
        assert (k <= n);
        /* k-means */
        Random random = new Random(0);
        Cluster[] centers = new Cluster[k];
        for (int i = 0; i < k; i++) {
            int rid = random.nextInt(n);
            centers[i] = new SphereCluster(microclusters.get(rid).getCenter(), 0);
        }
        return cleanUpKMeans(kMeans(k, centers, microclusters), microclusters);
    }
void moa.clusterers.clustream.WithKmeans.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 78 of file WithKmeans.java.
References moa.clusterers.clustream.WithKmeans.buffer, moa.clusterers.clustream.WithKmeans.bufferSize, moa.options.IntOption.getValue(), moa.clusterers.clustream.WithKmeans.initialized, moa.clusterers.clustream.WithKmeans.kernelRadiFactorOption, moa.clusterers.clustream.WithKmeans.kernels, moa.clusterers.clustream.WithKmeans.m, moa.clusterers.clustream.WithKmeans.maxNumKernelsOption, moa.clusterers.clustream.WithKmeans.t, moa.clusterers.clustream.WithKmeans.timeWindow, and moa.clusterers.clustream.WithKmeans.timeWindowOption.
{
        this.kernels = new ClustreamKernel[maxNumKernelsOption.getValue()];
        this.timeWindow = timeWindowOption.getValue();
        this.initialized = false;
        this.buffer = new LinkedList<ClustreamKernel>();
        this.bufferSize = maxNumKernelsOption.getValue();
        t = kernelRadiFactorOption.getValue();
        m = maxNumKernelsOption.getValue();
    }
void moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl (Instance instance) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 89 of file WithKmeans.java.
References moa.clusterers.clustream.ClustreamKernel.add(), moa.clusterers.clustream.WithKmeans.buffer, moa.clusterers.clustream.WithKmeans.bufferSize, moa.clusterers.clustream.WithKmeans.distance(), moa.clusterers.clustream.ClustreamKernel.getCenter(), moa.clusterers.clustream.ClustreamKernel.getRadius(), moa.cluster.CFCluster.getWeight(), moa.clusterers.clustream.WithKmeans.initialized, moa.clusterers.clustream.ClustreamKernel.insert(), moa.clusterers.clustream.WithKmeans.kernels, moa.clusterers.clustream.WithKmeans.m, moa.clusterers.clustream.WithKmeans.t, moa.clusterers.clustream.WithKmeans.timestamp, and moa.clusterers.clustream.WithKmeans.timeWindow.
{
        int dim = instance.numValues();
        timestamp++;
        // 0. Initialize
        if (!initialized) {
            if (buffer.size() < bufferSize) {
                buffer.add(new ClustreamKernel(instance, dim, timestamp, t, m));
                return;
            } else {
                for (int i = 0; i < buffer.size(); i++) {
                    kernels[i] = new ClustreamKernel(new DenseInstance(1.0, buffer.get(i).getCenter()), dim, timestamp, t, m);
                }
                buffer.clear();
                initialized = true;
                return;
            }
        }
        // 1. Determine closest kernel
        ClustreamKernel closestKernel = null;
        double minDistance = Double.MAX_VALUE;
        for ( int i = 0; i < kernels.length; i++ ) {
            //System.out.println(i+" "+kernels[i].getWeight()+" "+kernels[i].getDeviation());
            double distance = distance(instance.toDoubleArray(), kernels[i].getCenter());
            if (distance < minDistance) {
                closestKernel = kernels[i];
                minDistance = distance;
            }
        }
        // 2. Check whether instance fits into closestKernel
        double radius = 0.0;
        if ( closestKernel.getWeight() == 1 ) {
            // Special case: estimate radius by determining the distance to the
            // next closest cluster
            radius = Double.MAX_VALUE;
            double[] center = closestKernel.getCenter();
            for ( int i = 0; i < kernels.length; i++ ) {
                if ( kernels[i] == closestKernel ) {
                    continue;
                }
                double distance = distance(kernels[i].getCenter(), center );
                radius = Math.min( distance, radius );
            }
        } else {
            radius = closestKernel.getRadius();
        }
        if ( minDistance < radius ) {
            // Date fits, put into kernel and be happy
            closestKernel.insert( instance, timestamp );
            return;
        }
        // 3. Date does not fit, we need to free
        // some space to insert a new kernel
        long threshold = timestamp - timeWindow; // Kernels before this can be forgotten
        // 3.1 Try to forget old kernels
        for ( int i = 0; i < kernels.length; i++ ) {
            if ( kernels[i].getRelevanceStamp() < threshold ) {
                kernels[i] = new ClustreamKernel( instance, dim, timestamp, t, m );
                return;
            }
        }
        // 3.2 Merge closest two kernels
        int closestA = 0;
        int closestB = 0;
        minDistance = Double.MAX_VALUE;
        for ( int i = 0; i < kernels.length; i++ ) {
            double[] centerA = kernels[i].getCenter();
            for ( int j = i + 1; j < kernels.length; j++ ) {
                double dist = distance( centerA, kernels[j].getCenter() );
                if ( dist < minDistance ) {
                    minDistance = dist;
                    closestA = i;
                    closestB = j;
                }
            }
        }
        assert (closestA != closestB);
        kernels[closestA].add( kernels[closestB] );
        kernels[closestB] = new ClustreamKernel( instance, dim, timestamp, t,  m );
    }
Member Data Documentation
List<ClustreamKernel> moa.clusterers.clustream.WithKmeans.buffer [private]
Definition at line 68 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
int moa.clusterers.clustream.WithKmeans.bufferSize [private]
Definition at line 69 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
boolean moa.clusterers.clustream.WithKmeans.initialized [private]
Definition at line 67 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getClusteringResult(), moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.WithKmeans.kernelRadiFactorOption
Initial value:
 new IntOption(
            "kernelRadiFactor", 't',
            "Multiplier for the kernel radius", 2)
Definition at line 56 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.resetLearningImpl().
ClustreamKernel [] moa.clusterers.clustream.WithKmeans.kernels [private]
Definition at line 66 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.WithKmeans.kOption
Initial value:
 new IntOption(
            "k", 'k',
            "k of macro k-means (number of clusters)", 5)
Definition at line 60 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getClusteringResult().
int moa.clusterers.clustream.WithKmeans.m [private]
Definition at line 71 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.WithKmeans.maxNumKernelsOption
Initial value:
 new IntOption(
            "maxNumKernels", 'm',
            "Maximum number of micro kernels to use.", 100)
Definition at line 52 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.resetLearningImpl().
final long moa.clusterers.clustream.WithKmeans.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 47 of file WithKmeans.java.
double moa.clusterers.clustream.WithKmeans.t [private]
Definition at line 70 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getMicroClusteringResult(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
long moa.clusterers.clustream.WithKmeans.timestamp = -1 [private]
Definition at line 65 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
int moa.clusterers.clustream.WithKmeans.timeWindow [private]
Definition at line 64 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.getName(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), and moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.WithKmeans.timeWindowOption
Initial value:
 new IntOption("horizon",
            'h', "Rang of the window.", 1000)
Definition at line 49 of file WithKmeans.java.
Referenced by moa.clusterers.clustream.WithKmeans.resetLearningImpl().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustream/WithKmeans.java