MOA: moa.classifiers.trees.HoeffdingTree.SplitNode Class Reference
moa.classifiers.trees.HoeffdingTree.SplitNode Class Reference
Public Member Functions
int calcByteSize ()
int calcByteSizeIncludingSubtree ()
SplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
SplitNode (InstanceConditionalTest splitTest, double[] classObservations)
int numChildren ()
void setChild (int index, Node child)
Node getChild (int index)
int instanceChildIndex (Instance inst)
boolean isLeaf ()
FoundNode filterInstanceToLeaf (Instance inst, SplitNode parent, int parentBranch)
void describeSubtree (HoeffdingTree ht, StringBuilder out, int indent)
int subtreeDepth ()
Protected Attributes
InstanceConditionalTest splitTest
AutoExpandVector< Node > children
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 248 of file HoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingTree.SplitNode.SplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
Definition at line 273 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children.
{
            super(classObservations);
            this.splitTest = splitTest;
            this.children = new AutoExpandVector<Node>(size);
        }
moa.classifiers.trees.HoeffdingTree.SplitNode.SplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Definition at line 280 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children.
{
            super(classObservations);
            this.splitTest = splitTest;
            this.children = new AutoExpandVector<Node>();
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 257 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSizeIncludingSubtree().
{
            return super.calcByteSize()
                    + (int) (SizeOf.sizeOf(this.children) + SizeOf.fullSizeOf(this.splitTest));
        }
int moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSizeIncludingSubtree ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 263 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSize(), and moa.classifiers.trees.HoeffdingTree.SplitNode.children.
{
            int byteSize = calcByteSize();
            for (Node child : this.children) {
                if (child != null) {
                    byteSize += child.calcByteSizeIncludingSubtree();
                }
            }
            return byteSize;
        }
void moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree (HoeffdingTree ht, StringBuilder out, int indent)
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 328 of file HoeffdingTree.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.describeConditionForBranch(), moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingTree.SplitNode.getChild(), moa.classifiers.AbstractClassifier.getModelContext(), moa.classifiers.trees.HoeffdingTree.SplitNode.numChildren(), and moa.classifiers.trees.HoeffdingTree.SplitNode.splitTest.
{
            for (int branch = 0; branch < numChildren(); branch++) {
                Node child = getChild(branch);
                if (child != null) {
                    StringUtils.appendIndented(out, indent, "if ");
                    out.append(this.splitTest.describeConditionForBranch(branch,
                            ht.getModelContext()));
                    out.append(": ");
                    StringUtils.appendNewline(out);
                    child.describeSubtree(ht, out, indent + 2);
                }
            }
        }
FoundNode moa.classifiers.trees.HoeffdingTree.SplitNode.filterInstanceToLeaf (Instance inst, SplitNode parent, int parentBranch)
Definition at line 314 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.filterInstanceToLeaf(), moa.classifiers.trees.HoeffdingTree.SplitNode.getChild(), and moa.classifiers.trees.HoeffdingTree.SplitNode.instanceChildIndex().
{
            int childIndex = instanceChildIndex(inst);
            if (childIndex >= 0) {
                Node child = getChild(childIndex);
                if (child != null) {
                    return child.filterInstanceToLeaf(inst, this, childIndex);
                }
                return new FoundNode(null, this, childIndex);
            }
            return new FoundNode(this, parent, parentBranch);
        }
Node moa.classifiers.trees.HoeffdingTree.SplitNode.getChild (int index)
Definition at line 300 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), moa.classifiers.trees.HoeffdingTree.SplitNode.filterInstanceToLeaf(), moa.classifiers.trees.HoeffdingTree.findLearningNodes(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            return this.children.get(index);
        }
int moa.classifiers.trees.HoeffdingTree.SplitNode.instanceChildIndex (Instance inst)
Definition at line 304 of file HoeffdingTree.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), and moa.classifiers.trees.HoeffdingTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.filterInstanceToLeaf().
{
            return this.splitTest.branchForInstance(inst);
        }
boolean moa.classifiers.trees.HoeffdingTree.SplitNode.isLeaf ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 309 of file HoeffdingTree.java.
{
            return false;
        }
int moa.classifiers.trees.HoeffdingTree.SplitNode.numChildren ()
Definition at line 288 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), and moa.classifiers.trees.HoeffdingTree.findLearningNodes().
{
            return this.children.size();
        }
void moa.classifiers.trees.HoeffdingTree.SplitNode.setChild (int index, Node child)
Definition at line 292 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children, moa.classifiers.core.conditionaltests.InstanceConditionalTest.maxBranches(), and moa.classifiers.trees.HoeffdingTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingTree.activateLearningNode(), moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.trees.HoeffdingTree.deactivateLearningNode(), moa.classifiers.multilabel.MultilabelHoeffdingTree.deactivateLearningNode(), moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl(), moa.classifiers.trees.FIMTDD.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            if ((this.splitTest.maxBranches() >= 0)
                    && (index >= this.splitTest.maxBranches())) {
                throw new IndexOutOfBoundsException();
            }
            this.children.set(index, child);
        }
int moa.classifiers.trees.HoeffdingTree.SplitNode.subtreeDepth ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 344 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.children.
{
            int maxChildDepth = 0;
            for (Node child : this.children) {
                if (child != null) {
                    int depth = child.subtreeDepth();
                    if (depth > maxChildDepth) {
                        maxChildDepth = depth;
                    }
                }
            }
            return maxChildDepth + 1;
        }
Member Data Documentation
AutoExpandVector<Node> moa.classifiers.trees.HoeffdingTree.SplitNode.children [protected]
Definition at line 254 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingTree.SplitNode.getChild(), moa.classifiers.trees.HoeffdingTree.SplitNode.numChildren(), moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), moa.classifiers.trees.HoeffdingTree.SplitNode.SplitNode(), and moa.classifiers.trees.HoeffdingTree.SplitNode.subtreeDepth().
final long moa.classifiers.trees.HoeffdingTree.SplitNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Reimplemented in moa.classifiers.rules.nodes.RuleSplitNode.
Definition at line 250 of file HoeffdingTree.java.
InstanceConditionalTest moa.classifiers.trees.HoeffdingTree.SplitNode.splitTest [protected]
Definition at line 252 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.calcByteSize(), moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), moa.classifiers.rules.nodes.RuleSplitNode.evaluate(), moa.classifiers.rules.nodes.RuleSplitNode.getSplitTest(), moa.classifiers.trees.HoeffdingTree.SplitNode.instanceChildIndex(), and moa.classifiers.trees.HoeffdingTree.SplitNode.setChild().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingTree.java