MOA: moa.classifiers.AbstractClassifierTestCase Class Reference
moa.classifiers.AbstractClassifierTestCase Class Reference
Ancestor for all classifier test cases.
Classes
class InspectionData
Container for the data collected from a classifier at a specified inspection point in the stream.
Public Member Functions
AbstractClassifierTestCase (String name)
Constructs the test case.
void testRegression ()
Compares the processed data against previously saved output data.
Protected Member Functions
AbstractTestHelper newTestHelper ()
Returns the test helper class to use.
Instances load (String filename, int classIndex)
Loads the data to process.
InspectionData[] inspect (Instances data, int[] inspectionPoints, ClassificationPerformanceEvaluator evaluator, Classifier scheme)
Processes the input data and returns the inspection data.
boolean save (Classifier cls, InspectionData[] data, String filename)
Saves the data in the tmp directory.
abstract String[] getRegressionInputFiles ()
Returns the filenames (without path) of the input data files to use in the regression test.
abstract int[] getRegressionInputClassIndex ()
Returns the class index for the datasets.
abstract int[][] getRegressionInspectionPoints ()
Returns the index of the instances in the stream to inspect the performance/classification output of the classifiers.
abstract Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
abstract
ClassificationPerformanceEvaluator[] getRegressionEvaluatorSetups ()
Returns the evaluator setups to use in the regression test.
String createOutputFilename (String input, int no)
Creates an output filename based on the input filename.
Detailed Description
Ancestor for all classifier test cases.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 40 of file AbstractClassifierTestCase.java.
Constructor & Destructor Documentation
moa.classifiers.AbstractClassifierTestCase.AbstractClassifierTestCase (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 103 of file AbstractClassifierTestCase.java.
{
    super(name);
  }
Member Function Documentation
String moa.classifiers.AbstractClassifierTestCase.createOutputFilename (String input, int no) [protected]
Creates an output filename based on the input filename.
Parameters:
input the input filename (no path)
no the number of the test
Returns:
the generated output filename (no path)
Definition at line 259 of file AbstractClassifierTestCase.java.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
{
    String  result;
    int     index;
    String  ext;
    ext = "-out" + no;
    index = input.lastIndexOf('.');
    if (index == -1) {
      result = input + ext;
    }
    else {
      result  = input.substring(0, index);
      result += ext;
      result += input.substring(index);
    }
    return result;
  }
abstract Classifier [] moa.classifiers.AbstractClassifierTestCase.getRegressionClassifierSetups () [protected, pure virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implemented in moa.classifiers.AbstractMultipleClassifierTestCase, moa.classifiers.AbstractMultipleRegressorTestCase, moa.classifiers.active.ActiveClassifierTest, moa.classifiers.bayes.NaiveBayesMultinomialTest, moa.classifiers.bayes.NaiveBayesTest, moa.classifiers.drift.DriftDetectionMethodClassifierTest, moa.classifiers.drift.SingleClassifierDriftTest, moa.classifiers.functions.MajorityClassTest, moa.classifiers.functions.NoChangeTest, moa.classifiers.functions.PerceptronTest, moa.classifiers.functions.SGDTest, moa.classifiers.functions.SPegasosTest, moa.classifiers.meta.AccuracyUpdatedEnsembleTest, moa.classifiers.meta.AccuracyWeightedEnsembleTest, moa.classifiers.meta.LeveragingBagTest, moa.classifiers.meta.LimAttClassifierTest, moa.classifiers.meta.OCBoostTest, moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest, moa.classifiers.meta.OzaBagAdwinTest, moa.classifiers.meta.OzaBagASHTTest, moa.classifiers.meta.OzaBagTest, moa.classifiers.meta.OzaBoostAdwinTest, moa.classifiers.meta.OzaBoostTest, moa.classifiers.meta.TemporallyAugmentedClassifierTest, moa.classifiers.meta.WeightedMajorityAlgorithmTest, moa.classifiers.meta.WEKAClassifierTest, moa.classifiers.rules.AMRulesRegressorTest, moa.classifiers.rules.RuleClassifierNBayesTest, moa.classifiers.rules.RuleClassifierTest, moa.classifiers.trees.AdaHoeffdingOptionTreeTest, moa.classifiers.trees.ASHoeffdingTreeTest, moa.classifiers.trees.DecisionStumpTest, moa.classifiers.trees.FIMTDDTest, moa.classifiers.trees.HoeffdingAdaptiveTreeTest, moa.classifiers.trees.HoeffdingOptionTreeTest, moa.classifiers.trees.HoeffdingTreeTest, moa.classifiers.trees.LimAttHoeffdingTreeTest, moa.classifiers.trees.ORTOTest, and moa.classifiers.trees.RandomHoeffdingTreeTest.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
abstract ClassificationPerformanceEvaluator [] moa.classifiers.AbstractClassifierTestCase.getRegressionEvaluatorSetups () [protected, pure virtual]
Returns the evaluator setups to use in the regression test.
Returns:
the setups
Implemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
abstract int [] moa.classifiers.AbstractClassifierTestCase.getRegressionInputClassIndex () [protected, pure virtual]
Returns the class index for the datasets.
Returns:
the class indices (0-based)
Implemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
abstract String [] moa.classifiers.AbstractClassifierTestCase.getRegressionInputFiles () [protected, pure virtual]
Returns the filenames (without path) of the input data files to use in the regression test.
Returns:
the filenames
Implemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
abstract int [][] moa.classifiers.AbstractClassifierTestCase.getRegressionInspectionPoints () [protected, pure virtual]
Returns the index of the instances in the stream to inspect the performance/classification output of the classifiers.
Returns:
the inspection indices
Implemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
InspectionData [] moa.classifiers.AbstractClassifierTestCase.inspect (Instances data, int[] inspectionPoints, ClassificationPerformanceEvaluator evaluator, Classifier scheme) [protected]
Processes the input data and returns the inspection data.
Parameters:
data the data to work on
inspectionPoints the inspection points
evaluator the evaluator to use
scheme the scheme to process the data with
Returns:
the processed data
Definition at line 155 of file AbstractClassifierTestCase.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.classifiers.Classifier.getModelMeasurements(), moa.evaluation.ClassificationPerformanceEvaluator.getPerformanceMeasurements(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.AbstractClassifierTestCase.InspectionData.index, moa.classifiers.AbstractClassifierTestCase.InspectionData.measurements, moa.classifiers.AbstractClassifierTestCase.InspectionData.modelMeasurements, moa.options.OptionHandler.prepareForUse(), moa.classifiers.Classifier.trainOnInstance(), and moa.classifiers.AbstractClassifierTestCase.InspectionData.votes.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
{
    InspectionData[]    result;
    int         i;
    int         point;
    Instance        inst;
    double[]        votes;
    result = new InspectionData[inspectionPoints.length];
    scheme.prepareForUse();
    point = 0;
    for (i = 0; i < data.numInstances(); i++) {
      inst = data.instance(i);
      if (i > 0) {
    votes = scheme.getVotesForInstance(inst);
    evaluator.addResult(inst, votes);
    if (point < inspectionPoints.length) {
      if (i == inspectionPoints[point] - 1) {
        result[point]                   = new InspectionData();
        result[point].index             = inspectionPoints[point];
        result[point].votes             = votes;
        result[point].measurements      = evaluator.getPerformanceMeasurements();
        result[point].modelMeasurements = scheme.getModelMeasurements();
        point++;
      }
    }
      }
      scheme.trainOnInstance(inst);
    }
    return result;
  }
Instances moa.classifiers.AbstractClassifierTestCase.load (String filename, int classIndex) [protected]
Loads the data to process.
Parameters:
filename the filename to load (without path)
classIndex the class index to use
Returns:
the data, null if it could not be loaded
See also:
getDataDirectory()
Definition at line 125 of file AbstractClassifierTestCase.java.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
{
    Instances   result;
    ArffLoader  loader;
    result = null;
    try {
      loader = new ArffLoader();
      loader.setFile(new TmpFile(filename));
      result = loader.getDataSet();
      result.setClassIndex(classIndex);
    }
    catch (Exception e) {
      System.err.println("Failed to load dataset: " + filename);
      e.printStackTrace();
      result = null;
    }
    return result;
  }
AbstractTestHelper moa.classifiers.AbstractClassifierTestCase.newTestHelper () [protected]
Returns the test helper class to use.
Returns:
the helper class instance
Reimplemented from moa.test.MoaTestCase.
Definition at line 113 of file AbstractClassifierTestCase.java.
{
    return new TestHelper(this, "moa/classifiers/data");
  }
boolean moa.classifiers.AbstractClassifierTestCase.save (Classifier cls, InspectionData[] data, String filename) [protected]
Saves the data in the tmp directory.
Parameters:
data the data to save
filename the filename to save to (without path)
Returns:
true if successfully saved
Definition at line 199 of file AbstractClassifierTestCase.java.
References moa.test.MoaTestCase.m_TestHelper.
Referenced by moa.classifiers.AbstractClassifierTestCase.testRegression().
{
    StringBuilder   str;
    str = new StringBuilder();
    str.append(MOAUtils.toCommandLine(cls) + "\n");
    str.append("\n");
    for (InspectionData d: data) {
      str.append(d.toString());
      str.append("\n");
    }
    return m_TestHelper.save(str, filename);
  }
void moa.classifiers.AbstractClassifierTestCase.testRegression ()
Compares the processed data against previously saved output data.
Definition at line 282 of file AbstractClassifierTestCase.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.AbstractClassifierTestCase.createOutputFilename(), moa.classifiers.AbstractClassifierTestCase.getRegressionClassifierSetups(), moa.classifiers.AbstractClassifierTestCase.getRegressionEvaluatorSetups(), moa.classifiers.AbstractClassifierTestCase.getRegressionInputClassIndex(), moa.classifiers.AbstractClassifierTestCase.getRegressionInputFiles(), moa.classifiers.AbstractClassifierTestCase.getRegressionInspectionPoints(), moa.classifiers.AbstractClassifierTestCase.inspect(), moa.classifiers.AbstractClassifierTestCase.load(), moa.test.MoaTestCase.m_NoRegressionTest, moa.test.MoaTestCase.m_Regression, moa.test.MoaTestCase.m_TestHelper, moa.options.OptionHandler.prepareForUse(), moa.classifiers.AbstractClassifierTestCase.save(), and moa.classifiers.Classifier.setModelContext().
{
    Instances                   data;
    InspectionData[]                processed;
    boolean                 ok;
    String                  regression;
    int                     i;
    String[]                    input;
    int[]                   cindices;
    Classifier[]                setups;
    ClassificationPerformanceEvaluator[]    evals;
    int[][]                 points;
    Classifier                  current;
    String[]                    output;
    TmpFile[]                   outputFiles;
    if (m_NoRegressionTest)
      return;
    input    = getRegressionInputFiles();
    cindices = getRegressionInputClassIndex();
    output   = new String[input.length];
    setups   = getRegressionClassifierSetups();
    evals    = getRegressionEvaluatorSetups();
    points   = getRegressionInspectionPoints();
    assertEquals("Number of files and class indices differ!", input.length, cindices.length);
    assertEquals("Number of files and classifier setups differ!", input.length, setups.length);
    assertEquals("Number of classifier setups and evaluator setups differ!", setups.length, evals.length);
    assertEquals("Number of classifier setups and inspection points differ!", setups.length, points.length);
    // process data
    for (i = 0; i < input.length; i++) {
      data = load(input[i], cindices[i]);
      assertNotNull("Could not load data for regression test from " + input[i], data);
      current = setups[i].copy();
      current.prepareForUse();
      current.setModelContext(new InstancesHeader(data));
      assertNotNull("Failed to create copy of algorithm: " + MOAUtils.toCommandLine(setups[i]), current);
      processed = inspect(data, points[i], evals[i], current);
      assertNotNull("Failed to process data?", processed);
      output[i] = createOutputFilename(input[i], i);
      ok        = save(current, processed, output[i]);
      assertTrue("Failed to save regression data?", ok);
    }
    // test regression
    outputFiles = new TmpFile[output.length];
    for (i = 0; i < output.length; i++)
      outputFiles[i] = new TmpFile(output[i]);
    regression = m_Regression.compare(outputFiles);
    assertNull("Output differs:\n" + regression, regression);
    // remove output
    for (i = 0; i < output.length; i++)
      m_TestHelper.deleteFileFromTmp(output[i]);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/AbstractClassifierTestCase.java