MOA: moa.clusterers.outliers.Angiulli.ISBIndex Class Reference
moa.clusterers.outliers.Angiulli.ISBIndex Class Reference
Classes
class ISBNode
class ISBSearchResult
Public Member Functions
ISBIndex (double radius, int k)
Vector< ISBSearchResult > RangeSearch (ISBNode node, double radius)
void Insert (ISBNode node)
void Remove (ISBNode node)
Package Functions
Vector< ISBNode > MapGetNodes (StreamObj obj)
int MapCountObjRefs (StreamObj obj)
void MapInsert (ISBNode node)
void MapDelete (ISBNode node)
Package Attributes
MyMTree mtree
Map< Integer, Set< ISBNode > > mapNodes
double m_radius
int m_k
Detailed Description
Definition at line 30 of file ISBIndex.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.Angiulli.ISBIndex.ISBIndex (double radius, int k)
Definition at line 56 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.m_k, moa.clusterers.outliers.Angiulli.ISBIndex.m_radius, moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes, and moa.clusterers.outliers.Angiulli.ISBIndex.mtree.
{
        mtree = new MyMTree();
        mapNodes = new HashMap<Integer, Set<ISBNode>>();
        m_radius = radius;
        m_k = k;
    }
Member Function Documentation
void moa.clusterers.outliers.Angiulli.ISBIndex.Insert (ISBNode node)
Definition at line 92 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.MyMTree.add(), moa.clusterers.outliers.Angiulli.ISBIndex.MapInsert(), moa.clusterers.outliers.Angiulli.ISBIndex.mtree, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        // insert object of node at mtree
        mtree.add(node.obj);
        // insert node at map
        MapInsert(node);
    }
int moa.clusterers.outliers.Angiulli.ISBIndex.MapCountObjRefs (StreamObj obj) [package]
Definition at line 125 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.StreamObj.equals(), moa.clusterers.outliers.Angiulli.StreamObj.hashCode, moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.Remove().
{
        int h = obj.hashCode();
        int iCount = 0;
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            ISBNode n;
            Iterator<ISBNode> i = s.iterator();
            while (i.hasNext()) {
                n = i.next();
                if (n.obj.equals(obj))
                    iCount++;
            }
        }
        return iCount;
    }
void moa.clusterers.outliers.Angiulli.ISBIndex.MapDelete (ISBNode node) [package]
Definition at line 155 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.StreamObj.hashCode, moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.Remove().
{
        int h = node.obj.hashCode();
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            s.remove(node);
            if (s.isEmpty()) { // ### added
                mapNodes.remove(h);
            }
        }
    }
Vector<ISBNode> moa.clusterers.outliers.Angiulli.ISBIndex.MapGetNodes (StreamObj obj) [package]
Definition at line 109 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.StreamObj.equals(), moa.clusterers.outliers.Angiulli.StreamObj.hashCode, moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.RangeSearch().
{
        int h = obj.hashCode();
        Vector<ISBNode> v = new Vector<ISBNode>();
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            ISBNode node;
            Iterator<ISBNode> i = s.iterator();
            while (i.hasNext()) {
                node = i.next();
                if (node.obj.equals(obj))
                    v.add(node);
            }
        }
        return v;
    }
void moa.clusterers.outliers.Angiulli.ISBIndex.MapInsert (ISBNode node) [package]
Definition at line 141 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.StreamObj.hashCode, moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.Insert().
{
        int h = node.obj.hashCode();
        Set<ISBNode> s;
        if (mapNodes.containsKey(h)) {
            s = mapNodes.get(h);
            s.add(node);
        }
        else {
            s = new HashSet<ISBNode>();
            s.add(node);
            mapNodes.put(h, s);
        }
    }
Vector<ISBSearchResult> moa.clusterers.outliers.Angiulli.ISBIndex.RangeSearch (ISBNode node, double radius)
Definition at line 73 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.MapGetNodes(), moa.clusterers.outliers.Angiulli.ISBIndex.mtree, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        Vector<ISBSearchResult> results = new Vector<ISBSearchResult>();
        // execute range search at mtree
        StreamObj obj;
        double d;
        MyMTree.Query query = mtree.getNearestByRange(node.obj, radius);
        for (MyMTree.ResultItem q : query) {
            // get next obj found within range
            obj = q.data;
            // get distance of obj from query
            d = q.distance;
            // get all nodes referencing obj
            Vector<ISBNode> nodes = MapGetNodes(obj);
            for (int i = 0; i < nodes.size(); i++)
                results.add(new ISBSearchResult(nodes.get(i), d));
        }
        return results;
    }
void moa.clusterers.outliers.Angiulli.ISBIndex.Remove (ISBNode node)
Definition at line 99 of file ISBIndex.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.MapCountObjRefs(), moa.clusterers.outliers.Angiulli.ISBIndex.MapDelete(), moa.clusterers.outliers.Angiulli.ISBIndex.mtree, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj, and moa.clusterers.outliers.Angiulli.MyMTree.remove().
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveSafeInlier().
{
        // remove from map
        MapDelete(node);
        // check if stream object at mtree is still being referenced
        if (MapCountObjRefs(node.obj) <= 0) {
            // delete stream object from mtree
            mtree.remove(node.obj);
        }
    }
Member Data Documentation
int moa.clusterers.outliers.Angiulli.ISBIndex.m_k [package]
Definition at line 54 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.ISBIndex().
double moa.clusterers.outliers.Angiulli.ISBIndex.m_radius [package]
Definition at line 53 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.ISBIndex().
Map<Integer, Set<ISBNode> > moa.clusterers.outliers.Angiulli.ISBIndex.mapNodes [package]
Definition at line 52 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.ISBIndex(), moa.clusterers.outliers.Angiulli.ISBIndex.MapCountObjRefs(), moa.clusterers.outliers.Angiulli.ISBIndex.MapDelete(), moa.clusterers.outliers.Angiulli.ISBIndex.MapGetNodes(), and moa.clusterers.outliers.Angiulli.ISBIndex.MapInsert().
MyMTree moa.clusterers.outliers.Angiulli.ISBIndex.mtree [package]
Definition at line 51 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.Angiulli.ISBIndex.Insert(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBIndex(), moa.clusterers.outliers.Angiulli.ISBIndex.RangeSearch(), and moa.clusterers.outliers.Angiulli.ISBIndex.Remove().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/Angiulli/ISBIndex.java