MOA: moa.evaluation.SSQ Class Reference
moa.evaluation.SSQ Class Reference
Public Member Functions
SSQ ()
String[] getNames ()
void evaluateClustering (Clustering clustering, Clustering trueClsutering, ArrayList< DataPoint > points)
Protected Member Functions
boolean[] getDefaultEnabled ()
Detailed Description
Definition at line 27 of file SSQ.java.
Constructor & Destructor Documentation
moa.evaluation.SSQ.SSQ ()
Definition at line 29 of file SSQ.java.
                 {
        super();
    }
Member Function Documentation
void moa.evaluation.SSQ.evaluateClustering (Clustering clustering, Clustering trueClsutering, ArrayList< DataPoint > points) [virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 45 of file SSQ.java.
References moa.evaluation.MeasureCollection.addValue(), moa.cluster.Clustering.get(), moa.cluster.Cluster.getCenter(), and moa.cluster.Clustering.size().
{
        double sum = 0.0;
        for (int p = 0; p < points.size(); p++) {
            //don't include noise
            if(points.get(p).classValue()==-1) continue;
            double minDistance = Double.MAX_VALUE;
            for (int c = 0; c < clustering.size(); c++) {
                double distance = 0.0;
                double[] center = clustering.get(c).getCenter();
                for (int i = 0; i < center.length; i++) {
                    double d = points.get(p).value(i) - center[i];
                    distance += d * d;
                }
                minDistance = Math.min(distance, minDistance);
            }
            sum+=minDistance;
        }
        addValue(0,sum);
    }
boolean [] moa.evaluation.SSQ.getDefaultEnabled () [protected]
Reimplemented from moa.evaluation.MeasureCollection.
Definition at line 40 of file SSQ.java.
{
      boolean [] defaults = {false};
      return defaults;
  }
String [] moa.evaluation.SSQ.getNames () [virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 34 of file SSQ.java.
References moa.evaluation.MeasureCollection.names.
{
        String[] names = {"SSQ"};
        return names;
    }
The documentation for this class was generated from the following file:
main/java/moa/evaluation/SSQ.java