MOA: moa.gui.FlagOptionEditComponent Class Reference
moa.gui.FlagOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a flag option.
Public Member Functions
FlagOptionEditComponent (FlagOption option)
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void applyState ()
This method applies the state.
Protected Attributes
FlagOption editedOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a flag option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file FlagOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.FlagOptionEditComponent.FlagOptionEditComponent (FlagOption option)
Definition at line 40 of file FlagOptionEditComponent.java.
References moa.gui.FlagOptionEditComponent.editedOption, moa.options.FlagOption.getValueAsCLIString(), and moa.gui.FlagOptionEditComponent.setEditState().
{
        this.editedOption = option;
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.FlagOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 56 of file FlagOptionEditComponent.java.
References moa.gui.FlagOptionEditComponent.editedOption, and moa.options.FlagOption.setValue().
{
        this.editedOption.setValue(isSelected());
    }
Option moa.gui.FlagOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 46 of file FlagOptionEditComponent.java.
References moa.gui.FlagOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.FlagOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 51 of file FlagOptionEditComponent.java.
Referenced by moa.gui.FlagOptionEditComponent.FlagOptionEditComponent().
{
        setSelected(cliString != null);
    }
Member Data Documentation
FlagOption moa.gui.FlagOptionEditComponent.editedOption [protected]
Definition at line 38 of file FlagOptionEditComponent.java.
Referenced by moa.gui.FlagOptionEditComponent.applyState(), moa.gui.FlagOptionEditComponent.FlagOptionEditComponent(), and moa.gui.FlagOptionEditComponent.getEditedOption().
final long moa.gui.FlagOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 36 of file FlagOptionEditComponent.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/FlagOptionEditComponent.java