MOA: moa.gui.clustertab.ClusteringAlgoPanel Class Reference
moa.gui.clustertab.ClusteringAlgoPanel Class Reference
Public Member Functions
ClusteringAlgoPanel ()
void renderAlgoPanel ()
void actionPerformed (ActionEvent e)
AbstractClusterer getClusterer0 ()
AbstractClusterer getClusterer1 ()
ClusteringStream getStream ()
String getStreamValueAsCLIString ()
String getAlgorithm0ValueAsCLIString ()
String getAlgorithm1ValueAsCLIString ()
void setStreamValueAsCLIString (String s)
void setAlgorithm0ValueAsCLIString (String s)
void setAlgorithm1ValueAsCLIString (String s)
void applyChanges ()
void setPanelTitle (String title)
Protected Attributes
List< OptionEditComponent > editComponents = new LinkedList<OptionEditComponent>()
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
ClassOption streamOption
ClassOption algorithmOption0
ClassOption algorithmOption1
Detailed Description
Definition at line 49 of file ClusteringAlgoPanel.java.
Constructor & Destructor Documentation
moa.gui.clustertab.ClusteringAlgoPanel.ClusteringAlgoPanel ()
Definition at line 64 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.initComponents().
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
{
        initComponents();
    }
Member Function Documentation
void moa.gui.clustertab.ClusteringAlgoPanel.actionPerformed (ActionEvent e)
Definition at line 141 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1, moa.gui.clustertab.ClusteringAlgoPanel.editComponents, and moa.options.ClassOption.setValueViaCLIString().
{
        if(e.getActionCommand().equals("clear")){
            algorithmOption1.setValueViaCLIString("None");
            editComponents.get(2).setEditState("None");
        }
    }
void moa.gui.clustertab.ClusteringAlgoPanel.applyChanges ()
Definition at line 214 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.editComponents.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer0(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer1(), moa.gui.clustertab.ClusteringAlgoPanel.getStream(), and moa.gui.clustertab.ClusteringAlgoPanel.getStreamValueAsCLIString().
{
            for (OptionEditComponent editor : this.editComponents) {
                    try {
                            editor.applyState();
                    } catch (Exception ex) {
                            GUIUtils.showExceptionDialog(this, "Problem with option "
                                            + editor.getEditedOption().getName(), ex);
                    }
            }
    }
String moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm0ValueAsCLIString ()
Definition at line 188 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption0, moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed().
{
        applyChanges();
        return algorithmOption0.getValueAsCLIString();
    }
String moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm1ValueAsCLIString ()
Definition at line 193 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1, moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed().
{
        applyChanges();
        return algorithmOption1.getValueAsCLIString();
    }
AbstractClusterer moa.gui.clustertab.ClusteringAlgoPanel.getClusterer0 ()
Definition at line 148 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption0, moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.getClusterer0().
{
        AbstractClusterer c = null;
        applyChanges();
        try {
            c = (AbstractClusterer) ClassOption.cliStringToObject(algorithmOption0.getValueAsCLIString(), Clusterer.class, null);
        } catch (Exception ex) {
            Logger.getLogger(ClusteringAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }
AbstractClusterer moa.gui.clustertab.ClusteringAlgoPanel.getClusterer1 ()
Definition at line 159 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1, moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.getClusterer1().
{
        AbstractClusterer c = null;
        applyChanges();
        if(!algorithmOption1.getValueAsCLIString().equals("None")){
            try {
                c = (AbstractClusterer) ClassOption.cliStringToObject(algorithmOption1.getValueAsCLIString(), Clusterer.class, null);
            } catch (Exception ex) {
                Logger.getLogger(ClusteringAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return c;
    }
ClusteringStream moa.gui.clustertab.ClusteringAlgoPanel.getStream ()
Definition at line 172 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), moa.options.ClassOption.getValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.streamOption.
Referenced by moa.gui.clustertab.ClusteringSetupTab.getStream0().
{
        ClusteringStream s = null;
        applyChanges();
        try {
            s = (ClusteringStream) ClassOption.cliStringToObject(streamOption.getValueAsCLIString(), ClusteringStream.class, null);
        } catch (Exception ex) {
            Logger.getLogger(ClusteringAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s;
    }
String moa.gui.clustertab.ClusteringAlgoPanel.getStreamValueAsCLIString ()
Definition at line 183 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), moa.options.ClassOption.getValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.streamOption.
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed().
{
        applyChanges();
        return streamOption.getValueAsCLIString();
    }
void moa.gui.clustertab.ClusteringAlgoPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 236 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.ClusteringAlgoPanel().
{
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cluster Algorithm Setup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel ()
Definition at line 68 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption0, moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1, moa.gui.clustertab.ClusteringAlgoPanel.editComponents, moa.options.ClassOption.getEditComponent(), and moa.gui.clustertab.ClusteringAlgoPanel.streamOption.
Referenced by moa.gui.clustertab.ClusteringSetupTab.ClusteringSetupTab().
{
        setLayout(new BorderLayout());
        ArrayList<Option> options = new ArrayList<Option>();
        options.add(streamOption);
        options.add(algorithmOption0);
        options.add(algorithmOption1);
        JPanel optionsPanel = new JPanel();
        GridBagLayout gbLayout = new GridBagLayout();
        optionsPanel.setLayout(gbLayout);
        //Create generic label constraints
        GridBagConstraints gbcLabel = new GridBagConstraints();
        gbcLabel.gridx = 0;
        gbcLabel.fill = GridBagConstraints.NONE;
        gbcLabel.anchor = GridBagConstraints.EAST;
        gbcLabel.weightx = 0;
        gbcLabel.insets = new Insets(5, 5, 5, 5);
        //Create generic editor constraints
        GridBagConstraints gbcOption = new GridBagConstraints();
        gbcOption.gridx = 1;
        gbcOption.fill = GridBagConstraints.HORIZONTAL;
        gbcOption.anchor = GridBagConstraints.CENTER;
        gbcOption.weightx = 1;
        gbcOption.insets = new Insets(5, 5, 5, 0);
        //Stream Option
        JLabel labelStream = new JLabel("Stream");
        labelStream.setToolTipText("Stream to use.");
        optionsPanel.add(labelStream, gbcLabel);
        JComponent editorStream = streamOption.getEditComponent();
        labelStream.setLabelFor(editorStream);
        editComponents.add((OptionEditComponent) editorStream);
        optionsPanel.add(editorStream, gbcOption);
        //Algorithm0 Option
        JLabel labelAlgo0 = new JLabel("Algorithm1");
        labelAlgo0.setToolTipText("Algorithm to use.");
        optionsPanel.add(labelAlgo0, gbcLabel);
        JComponent editorAlgo0 = algorithmOption0.getEditComponent();
        labelAlgo0.setLabelFor(editorAlgo0);
        editComponents.add((OptionEditComponent) editorAlgo0);
        optionsPanel.add(editorAlgo0, gbcOption);
        //Algorithm1 Option
        JLabel labelAlgo1 = new JLabel("Algorithm2");
        labelAlgo1.setToolTipText("Comparison algorithm to use.");
        optionsPanel.add(labelAlgo1, gbcLabel);
        JComponent editorAlgo1 = algorithmOption1.getEditComponent();
        labelAlgo1.setLabelFor(editorAlgo1);
        editComponents.add((OptionEditComponent) editorAlgo1);
        optionsPanel.add(editorAlgo1, gbcOption);
        //use comparison Algorithm Option
        GridBagConstraints gbcClearButton = new GridBagConstraints();
        gbcClearButton.gridx = 2;
        gbcClearButton.gridy = 2;
        gbcClearButton.fill = GridBagConstraints.NONE;
        gbcClearButton.anchor = GridBagConstraints.CENTER;
        gbcClearButton.insets = new Insets(5, 0, 5, 5);
        JButton clearButton = new JButton("Clear");
        clearButton.addActionListener(this);
        clearButton.setActionCommand("clear");
        optionsPanel.add(clearButton, gbcClearButton);
        add(optionsPanel);
    }
void moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString (String s)
Definition at line 204 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption0, moa.gui.clustertab.ClusteringAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), and moa.options.ClassOption.setValueViaCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
{
        algorithmOption0.setValueViaCLIString(s);
        editComponents.get(1).setEditState(algorithmOption0.getValueAsCLIString());
    }
void moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString (String s)
Definition at line 209 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1, moa.gui.clustertab.ClusteringAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), and moa.options.ClassOption.setValueViaCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
{
        algorithmOption1.setValueViaCLIString(s);
        editComponents.get(2).setEditState(algorithmOption1.getValueAsCLIString());
    }
void moa.gui.clustertab.ClusteringAlgoPanel.setPanelTitle (String title)
Definition at line 225 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
{
        setBorder(javax.swing.BorderFactory.createTitledBorder(null,title, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
    }
void moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString (String s)
Definition at line 199 of file ClusteringAlgoPanel.java.
References moa.gui.clustertab.ClusteringAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), moa.options.ClassOption.setValueViaCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.streamOption.
Referenced by moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
{
        streamOption.setValueViaCLIString(s);
        editComponents.get(0).setEditState(streamOption.getValueAsCLIString());
    }
Member Data Documentation
ClassOption moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption0 [private]
Initial value:
 new ClassOption("Algorithm0", 'a',
               "Algorithm to use.", Clusterer.class, "ClusterGenerator")
Definition at line 57 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer0(), moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel(), and moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString().
ClassOption moa.gui.clustertab.ClusteringAlgoPanel.algorithmOption1 [private]
Initial value:
 new ClassOption("Algorithm1", 'c',
               "Comparison algorithm", Clusterer.class, "", "clustream.WithKmeans")
Definition at line 60 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.actionPerformed(), moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer1(), moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel(), and moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString().
List<OptionEditComponent> moa.gui.clustertab.ClusteringAlgoPanel.editComponents = new LinkedList<OptionEditComponent>() [protected]
Definition at line 51 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.actionPerformed(), moa.gui.clustertab.ClusteringAlgoPanel.applyChanges(), moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString().
ClassOption moa.gui.clustertab.ClusteringAlgoPanel.streamOption [private]
Initial value:
 new ClassOption("Stream", 's',
                "", ClusteringStream.class,
                "RandomRBFGeneratorEvents")
Definition at line 53 of file ClusteringAlgoPanel.java.
Referenced by moa.gui.clustertab.ClusteringAlgoPanel.getStream(), moa.gui.clustertab.ClusteringAlgoPanel.getStreamValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel(), and moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString().
The documentation for this class was generated from the following file:
main/java/moa/gui/clustertab/ClusteringAlgoPanel.java