MOA: moa.classifiers.lazy.neighboursearch.NormalizableDistance Class Reference
moa.classifiers.lazy.neighboursearch.NormalizableDistance Class Reference
Represents the abstract ancestor for normalizable distance functions, like Euclidean or Manhattan distance.
Public Member Functions
NormalizableDistance ()
Invalidates the distance function, Instances must be still set.
NormalizableDistance (Instances data)
Initializes the distance function and automatically initializes the ranges.
abstract String globalInfo ()
Returns a string describing this object.
String dontNormalizeTipText ()
Returns the tip text for this property.
void setDontNormalize (boolean dontNormalize)
Sets whether if the attribute values are to be normalized in distance calculation.
boolean getDontNormalize ()
Gets whether if the attribute values are to be normazlied in distance calculation.
String attributeIndicesTipText ()
Returns the tip text for this property.
void setAttributeIndices (String value)
Sets the range of attributes to use in the calculation of the distance.
String getAttributeIndices ()
Gets the range of attributes used in the calculation of the distance.
String invertSelectionTipText ()
Returns the tip text for this property.
void setInvertSelection (boolean value)
Sets whether the matching sense of attribute indices is inverted or not.
boolean getInvertSelection ()
Gets whether the matching sense of attribute indices is inverted or not.
void setInstances (Instances insts)
Sets the instances.
Instances getInstances ()
returns the instances currently set.
void postProcessDistances (double[] distances)
Does nothing, derived classes may override it though.
void update (Instance ins)
Update the distance function (if necessary) for the newly added instance.
double distance (Instance first, Instance second)
Calculates the distance between two instances.
double distance (Instance first, Instance second, double cutOffValue)
Calculates the distance between two instances.
double[][] initializeRanges ()
Initializes the ranges using all instances of the dataset.
void updateRangesFirst (Instance instance, int numAtt, double[][] ranges)
Used to initialize the ranges.
void updateRanges (Instance instance, int numAtt, double[][] ranges)
Updates the minimum and maximum and width values for all the attributes based on a new instance.
void initializeRangesEmpty (int numAtt, double[][] ranges)
Used to initialize the ranges.
double[][] updateRanges (Instance instance, double[][] ranges)
Updates the ranges given a new instance.
double[][] initializeRanges (int[] instList) throws Exception
Initializes the ranges of a subset of the instances of this dataset.
double[][] initializeRanges (int[] instList, int startIdx, int endIdx) throws Exception
Initializes the ranges of a subset of the instances of this dataset.
void updateRanges (Instance instance)
Update the ranges if a new instance comes.
boolean inRanges (Instance instance, double[][] ranges)
Test if an instance is within the given ranges.
boolean rangesSet ()
Check if ranges are set.
double[][] getRanges () throws Exception
Method to get the ranges.
String toString ()
Returns an empty string.
Static Public Member Functions
static boolean isMissingValue (double val)
Tests if the given value codes "missing".
Static Public Attributes
static final int R_MIN = 0
Index in ranges for MIN.
static final int R_MAX = 1
Index in ranges for MAX.
static final int R_WIDTH = 2
Index in ranges for WIDTH.
Protected Member Functions
void invalidate ()
invalidates all initializations.
void validate ()
performs the initializations if necessary.
void initialize ()
initializes the ranges and the attributes being used.
void initializeAttributeIndices ()
initializes the attribute indices.
abstract double updateDistance (double currDist, double diff)
Updates the current distance calculated so far with the new difference between two attributes.
double norm (double x, int i)
Normalizes a given value of a numeric attribute.
double difference (int index, double val1, double val2)
Computes the difference between two given attribute values.
Protected Attributes
Instances m_Data = null
the instances used internally.
boolean m_DontNormalize = false
True if normalization is turned off (default false).
double[][] m_Ranges
The range of the attributes.
boolean[] m_ActiveIndices
The range of attributes to use for calculating the distance.
boolean m_Validated
Whether all the necessary preparations have been done.
Detailed Description
Represents the abstract ancestor for normalizable distance functions, like Euclidean or Manhattan distance.
Author:
Fracpete (fracpete at waikato dot ac dot nz)
Gabi Schmidberger (gabi@cs.waikato.ac.nz) -- original code from weka.core.EuclideanDistance
Ashraf M. Kibriya (amk14@cs.waikato.ac.nz) -- original code from weka.core.EuclideanDistance
Version:
Revision
8034
Definition at line 37 of file NormalizableDistance.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.NormalizableDistance.NormalizableDistance ()
Invalidates the distance function, Instances must be still set.
Definition at line 71 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate().
{
    invalidate();
  }
moa.classifiers.lazy.neighboursearch.NormalizableDistance.NormalizableDistance (Instances data)
Initializes the distance function and automatically initializes the ranges.
Parameters:
data the instances the distance function should work on
Definition at line 81 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInstances().
{
    setInstances(data);
  }
Member Function Documentation
String moa.classifiers.lazy.neighboursearch.NormalizableDistance.attributeIndicesTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 132 of file NormalizableDistance.java.
{
    return
        "Specify range of attributes to act on. "
      + "This is a comma separated list of attribute indices, with "
      + "\"first\" and \"last\" valid values. Specify an inclusive "
      + "range with \"-\". E.g: \"first-3,5,6-10,last\".";
  }
double moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference (int index, double val1, double val2) [protected]
Computes the difference between two given attribute values.
Parameters:
index the attribute index
val1 the first value
val2 the second value
Returns:
the difference
Definition at line 396 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.isMissingValue(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data, moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_DontNormalize, moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance(), and moa.classifiers.lazy.neighboursearch.EuclideanDistance.sqDifference().
{
    switch (m_Data.attribute(index).type()) {
      case Attribute.NOMINAL:
        if (isMissingValue(val1) ||
           isMissingValue(val2) ||
           ((int) val1 != (int) val2)) {
          return 1;
        }
        else {
          return 0;
        }
      case Attribute.NUMERIC:
        if (isMissingValue(val1) ||
           isMissingValue(val2)) {
          if (isMissingValue(val1) &&
             isMissingValue(val2)) {
            if (!m_DontNormalize)  //We are doing normalization
              return 1;
            else
              return (m_Ranges[index][R_MAX] - m_Ranges[index][R_MIN]);
          }
          else {
            double diff;
            if (isMissingValue(val2)) {
              diff = (!m_DontNormalize) ? norm(val1, index) : val1;
            }
            else {
              diff = (!m_DontNormalize) ? norm(val2, index) : val2;
            }
            if (!m_DontNormalize && diff < 0.5) {
              diff = 1.0 - diff;
            }
            else if (m_DontNormalize) {
              if ((m_Ranges[index][R_MAX]-diff) > (diff-m_Ranges[index][R_MIN]))
                return m_Ranges[index][R_MAX]-diff;
              else
                return diff-m_Ranges[index][R_MIN];
            }
            return diff;
          }
        }
        else {
          return (!m_DontNormalize) ?
                 (norm(val1, index) - norm(val2, index)) :
                 (val1 - val2);
        }
      default:
        return 0;
    }
  }
double moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance (Instance first, Instance second, double cutOffValue)
Calculates the distance between two instances.
Offers speed up (if the distance function class in use supports it) in nearest neighbour search by taking into account the cutOff or maximum distance. Depending on the distance function class, post processing of the distances by postProcessDistances(double []) may be required if this function is used.
Parameters:
first the first instance
second the second instance
cutOffValue If the distance being calculated becomes larger than cutOffValue then the rest of the calculation is discarded.
Returns:
the distance between the two given instances or Double.POSITIVE_INFINITY if the distance being calculated becomes larger than cutOffValue.
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 294 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_ActiveIndices, moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateDistance(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
{
    double distance = 0;
    int firstI, secondI;
    int firstNumValues = first.numValues();
    int secondNumValues = second.numValues();
    int numAttributes = m_Data.numAttributes();
    int classIndex = m_Data.classIndex();
    validate();
    for (int p1 = 0, p2 = 0; p1 < firstNumValues || p2 < secondNumValues; ) {
      if (p1 >= firstNumValues)
    firstI = numAttributes;
      else
    firstI = first.index(p1);
      if (p2 >= secondNumValues)
    secondI = numAttributes;
      else
    secondI = second.index(p2);
      if (firstI == classIndex) {
    p1++;
    continue;
      }
      if ((firstI < numAttributes) && !m_ActiveIndices[firstI]) {
    p1++;
    continue;
      }
      if (secondI == classIndex) {
    p2++;
    continue;
      }
      if ((secondI < numAttributes) && !m_ActiveIndices[secondI]) {
    p2++;
    continue;
      }
      double diff;
      if (firstI == secondI) {
    diff = difference(firstI,
                  first.valueSparse(p1),
                  second.valueSparse(p2));
    p1++;
    p2++;
      }
      else if (firstI > secondI) {
    diff = difference(secondI,
                  0, second.valueSparse(p2));
    p2++;
      }
      else {
    diff = difference(firstI,
                  first.valueSparse(p1), 0);
    p1++;
      }
      distance = updateDistance(distance, diff);
      if (distance > cutOffValue)
        return Double.POSITIVE_INFINITY;
    }
    return distance;
  }
double moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance (Instance first, Instance second)
Calculates the distance between two instances.
Parameters:
first the first instance
second the second instance
Returns:
the distance between the two given instances
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Reimplemented in moa.classifiers.lazy.neighboursearch.EuclideanDistance.
Definition at line 273 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance().
{
    return distance(first, second, Double.POSITIVE_INFINITY);
  }
String moa.classifiers.lazy.neighboursearch.NormalizableDistance.dontNormalizeTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 99 of file NormalizableDistance.java.
{
    return "Whether if the normalization of attributes should be turned off " +
           "for distance calculation (Default: false i.e. attribute values " +
           "are normalized). ";
  }
String moa.classifiers.lazy.neighboursearch.NormalizableDistance.getAttributeIndices ()
Gets the range of attributes used in the calculation of the distance.
Returns:
the attribute index range
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 157 of file NormalizableDistance.java.
{
    return null; //m_AttributeIndices.getRanges();
  }
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.getDontNormalize ()
Gets whether if the attribute values are to be normazlied in distance calculation.
(default false i.e. attribute values are normalized.)
Returns:
false if values get normalized
Definition at line 122 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_DontNormalize.
{
    return m_DontNormalize;
  }
Instances moa.classifiers.lazy.neighboursearch.NormalizableDistance.getInstances ()
returns the instances currently set.
Returns:
the current instances
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 243 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data.
{
    return m_Data;
  }
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.getInvertSelection ()
Gets whether the matching sense of attribute indices is inverted or not.
Returns:
true if the matching sense is inverted
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 189 of file NormalizableDistance.java.
{
    return false; //m_AttributeIndices.getInvert();
  }
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.getRanges () throws Exception
Method to get the ranges.
Returns:
the ranges
Exceptions:
Exception if no randes are set yet
Definition at line 694 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), and moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree().
{
    validate();
    if (m_Ranges == null)
      throw new Exception("Ranges not yet set.");
    return m_Ranges;
  }
abstract String moa.classifiers.lazy.neighboursearch.NormalizableDistance.globalInfo () [pure virtual]
Returns a string describing this object.
Returns:
a description of the evaluator suitable for displaying in the explorer/experimenter gui
Implemented in moa.classifiers.lazy.neighboursearch.EuclideanDistance.
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.initialize () [protected]
initializes the ranges and the attributes being used.
Definition at line 213 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeAttributeIndices(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges().
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
{
    initializeAttributeIndices();
    initializeRanges();
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeAttributeIndices () [protected]
initializes the attribute indices.
Definition at line 221 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_ActiveIndices, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.initialize().
{
    //m_AttributeIndices.setUpper(m_Data.numAttributes() - 1);
    m_ActiveIndices = new boolean[m_Data.numAttributes()];
    for (int i = 0; i < m_ActiveIndices.length; i++)
      m_ActiveIndices[i] = true; //m_AttributeIndices.isInRange(i);
  }
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges (int[] instList, int startIdx, int endIdx) throws Exception
Initializes the ranges of a subset of the instances of this dataset.
Therefore m_Ranges is not set. The caller of this method should ensure that the supplied start and end indices are valid (start <= end, end<instList.length etc) and correct.
Parameters:
instList list of indexes of the instances
startIdx start index of the subset of instances in the indices array
endIdx end index of the subset of instances in the indices array
Returns:
the ranges
Exceptions:
Exception if something goes wrong
Definition at line 623 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
{
    if (m_Data == null)
      throw new Exception("No instances supplied.");
    int numAtt = m_Data.numAttributes();
    double[][] ranges = new double [numAtt][3];
    if (m_Data.numInstances() <= 0) {
      initializeRangesEmpty(numAtt, ranges);
      return ranges;
    }
    else {
      // initialize ranges using the first instance
      updateRangesFirst(m_Data.instance(instList[startIdx]), numAtt, ranges);
      // update ranges, starting from the second
      for (int i = startIdx+1; i <= endIdx; i++) {
        updateRanges(m_Data.instance(instList[i]), numAtt, ranges);
      }
    }
    return ranges;
  }
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges (int[] instList) throws Exception
Initializes the ranges of a subset of the instances of this dataset.
Therefore m_Ranges is not set.
Parameters:
instList list of indexes of the subset
Returns:
the ranges
Exceptions:
Exception if something goes wrong
Definition at line 588 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
{
    if (m_Data == null)
      throw new Exception("No instances supplied.");
    int numAtt = m_Data.numAttributes();
    double[][] ranges = new double [numAtt][3];
    if (m_Data.numInstances() <= 0) {
      initializeRangesEmpty(numAtt, ranges);
      return ranges;
    }
    else {
      // initialize ranges using the first instance
      updateRangesFirst(m_Data.instance(instList[0]), numAtt, ranges);
      // update ranges, starting from the second
      for (int i = 1; i < instList.length; i++) {
        updateRanges(m_Data.instance(instList[i]), numAtt, ranges);
      }
    }
    return ranges;
  }
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges ()
Initializes the ranges using all instances of the dataset.
Sets m_Ranges.
Returns:
the ranges
Definition at line 455 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data, moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.initialize(), moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.splitNode(), moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.splitNode(), moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.splitNode(), moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.splitNode(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
{
    if (m_Data == null) {
      m_Ranges = null;
      return m_Ranges;
    }
    int numAtt = m_Data.numAttributes();
    double[][] ranges = new double [numAtt][3];
    if (m_Data.numInstances() <= 0) {
      initializeRangesEmpty(numAtt, ranges);
      m_Ranges = ranges;
      return m_Ranges;
    }
    else {
      // initialize ranges using the first instance
      updateRangesFirst(m_Data.instance(0), numAtt, ranges);
    }
    // update ranges, starting from the second
    for (int i = 1; i < m_Data.numInstances(); i++)
      updateRanges(m_Data.instance(i), numAtt, ranges);
    m_Ranges = ranges;
    return m_Ranges;
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty (int numAtt, double ranges[][])
Used to initialize the ranges.
Parameters:
numAtt number of attributes in the model
ranges low, high and width values for all attributes
Definition at line 545 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges().
{
    for (int j = 0; j < numAtt; j++) {
      ranges[j][R_MIN] = Double.POSITIVE_INFINITY;
      ranges[j][R_MAX] = -Double.POSITIVE_INFINITY;
      ranges[j][R_WIDTH] = Double.POSITIVE_INFINITY;
    }
  }
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.inRanges (Instance instance, double ranges[][])
Test if an instance is within the given ranges.
Parameters:
instance the instance
ranges the ranges the instance is tested to be in
Returns:
true if instance is within the ranges
Definition at line 664 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN.
{
    boolean isIn = true;
    // updateRangesFirst must have been called on ranges
    for (int j = 0; isIn && (j < ranges.length); j++) {
      if (!instance.isMissing(j)) {
        double value = instance.value(j);
        isIn = value <= ranges[j][R_MAX];
        if (isIn) isIn = value >= ranges[j][R_MIN];
      }
    }
    return isIn;
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate () [protected]
invalidates all initializations.
Definition at line 196 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Validated.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.NormalizableDistance(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.setAttributeIndices(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.setDontNormalize(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInstances(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInvertSelection().
{
    m_Validated = false;
  }
String moa.classifiers.lazy.neighboursearch.NormalizableDistance.invertSelectionTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 167 of file NormalizableDistance.java.
{
    return
        "Set attribute selection mode. If false, only selected "
      + "attributes in the range will be used in the distance calculation; if "
      + "true, only non-selected attributes will be used for the calculation.";
  }
static boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.isMissingValue (double val) [static]
Tests if the given value codes "missing".
Parameters:
val the value to be tested
Returns:
true if val codes "missing"
Definition at line 718 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference().
{
    return Double.isNaN(val);
  }
double moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm (double x, int i) [protected]
Normalizes a given value of a numeric attribute.
Parameters:
x the value to be normalized
i the attribute's index
Returns:
the normalized value
Definition at line 380 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference().
{
    if (Double.isNaN(m_Ranges[i][R_MIN]) || (m_Ranges[i][R_MAX] == m_Ranges[i][R_MIN]))
      return 0;
    else
      return (x - m_Ranges[i][R_MIN]) / (m_Ranges[i][R_WIDTH]);
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.postProcessDistances (double[] distances)
Does nothing, derived classes may override it though.
Parameters:
distances the distances to post-process
Definition at line 252 of file NormalizableDistance.java.
{
  }
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.rangesSet ()
Check if ranges are set.
Returns:
true if ranges are set
Definition at line 684 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges.
{
    return (m_Ranges != null);
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.setAttributeIndices (String value)
Sets the range of attributes to use in the calculation of the distance.
The indices start from 1, 'first' and 'last' are valid as well. E.g.: first-3,5,6-last
Parameters:
value the new attribute index range
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 147 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate().
{
    //m_AttributeIndices.setRanges(value);
    invalidate();
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.setDontNormalize (boolean dontNormalize)
Sets whether if the attribute values are to be normalized in distance calculation.
Parameters:
dontNormalize if true the values are not normalized
Definition at line 111 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_DontNormalize.
{
    m_DontNormalize = dontNormalize;
    invalidate();
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInstances (Instances insts)
Sets the instances.
Parameters:
insts the instances to use
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 233 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.NormalizableDistance().
{
    m_Data = insts;
    invalidate();
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInvertSelection (boolean value)
Sets whether the matching sense of attribute indices is inverted or not.
Parameters:
value if true the matching sense is inverted
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 179 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate().
{
    //m_AttributeIndices.setInvert(value);
    invalidate();
  }
String moa.classifiers.lazy.neighboursearch.NormalizableDistance.toString ()
Returns an empty string.
Returns:
an empty string
Definition at line 708 of file NormalizableDistance.java.
{
    return "";
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.update (Instance ins)
Update the distance function (if necessary) for the newly added instance.
Parameters:
ins the instance to add
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 260 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
{
    validate();
    m_Ranges = updateRanges(ins, m_Ranges);
  }
abstract double moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateDistance (double currDist, double diff) [protected, pure virtual]
Updates the current distance calculated so far with the new difference between two attributes.
The difference between the attributes was calculated with the difference(int,double,double) method.
Parameters:
currDist the current distance calculated so far
diff the difference between two new attributes
Returns:
the update distance
See also:
difference(int, double, double)
Implemented in moa.classifiers.lazy.neighboursearch.EuclideanDistance.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance().
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges (Instance instance)
Update the ranges if a new instance comes.
Parameters:
instance the new instance
Definition at line 651 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges, moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
{
    validate();
    m_Ranges = updateRanges(instance, m_Ranges);
  }
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges (Instance instance, double ranges[][])
Updates the ranges given a new instance.
Parameters:
instance the new instance
ranges low, high and width values for all attributes
Returns:
the updated ranges
Definition at line 560 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
{
    // updateRangesFirst must have been called on ranges
    for (int j = 0; j < ranges.length; j++) {
      double value = instance.value(j);
      if (!instance.isMissing(j)) {
        if (value < ranges[j][R_MIN]) {
          ranges[j][R_MIN] = value;
          ranges[j][R_WIDTH] = ranges[j][R_MAX] - ranges[j][R_MIN];
        } else {
          if (instance.value(j) > ranges[j][R_MAX]) {
            ranges[j][R_MAX] = value;
            ranges[j][R_WIDTH] = ranges[j][R_MAX] - ranges[j][R_MIN];
          }
        }
      }
    }
    return ranges;
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges (Instance instance, int numAtt, double ranges[][])
Updates the minimum and maximum and width values for all the attributes based on a new instance.
Parameters:
instance the new instance
numAtt number of attributes in the model
ranges low, high and width values for all attributes
Definition at line 516 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceInfo(), moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.update(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges().
{
    // updateRangesFirst must have been called on ranges
    for (int j = 0; j < numAtt; j++) {
      double value = instance.value(j);
      if (!instance.isMissing(j)) {
        if (value < ranges[j][R_MIN]) {
          ranges[j][R_MIN] = value;
          ranges[j][R_WIDTH] = ranges[j][R_MAX] - ranges[j][R_MIN];
          if (value > ranges[j][R_MAX]) { //if this is the first value that is
            ranges[j][R_MAX] = value;    //not missing. The,0
            ranges[j][R_WIDTH] = ranges[j][R_MAX] - ranges[j][R_MIN];
          }
        }
        else {
          if (value > ranges[j][R_MAX]) {
            ranges[j][R_MAX] = value;
            ranges[j][R_WIDTH] = ranges[j][R_MAX] - ranges[j][R_MIN];
          }
        }
      }
    }
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst (Instance instance, int numAtt, double ranges[][])
Used to initialize the ranges.
For this the values of the first instance is used to save time. Sets low and high to the values of the first instance and width to zero.
Parameters:
instance the new instance
numAtt number of attributes in the model
ranges low, high and width values for all attributes
Definition at line 493 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX, moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges().
{
    for (int j = 0; j < numAtt; j++) {
      if (!instance.isMissing(j)) {
        ranges[j][R_MIN] = instance.value(j);
        ranges[j][R_MAX] = instance.value(j);
        ranges[j][R_WIDTH] = 0.0;
      }
      else { // if value was missing
        ranges[j][R_MIN] = Double.POSITIVE_INFINITY;
        ranges[j][R_MAX] = -Double.POSITIVE_INFINITY;
        ranges[j][R_WIDTH] = Double.POSITIVE_INFINITY;
      }
    }
  }
void moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate () [protected]
performs the initializations if necessary.
Definition at line 203 of file NormalizableDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.initialize(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Validated.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.update(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges().
{
    if (!m_Validated) {
      initialize();
      m_Validated = true;
    }
  }
Member Data Documentation
boolean [] moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_ActiveIndices [protected]
The range of attributes to use for calculating the distance.
The boolean flags, whether an attribute will be used or not.
Definition at line 63 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeAttributeIndices().
Instances moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Data = null [protected]
the instances used internally.
Definition at line 51 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.distance(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getInstances(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeAttributeIndices(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInstances().
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_DontNormalize = false [protected]
True if normalization is turned off (default false).
Definition at line 54 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getDontNormalize(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.setDontNormalize().
double [][] moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Ranges [protected]
The range of the attributes.
Definition at line 57 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.rangesSet(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.update(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges().
boolean moa.classifiers.lazy.neighboursearch.NormalizableDistance.m_Validated [protected]
Whether all the necessary preparations have been done.
Definition at line 66 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.invalidate(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.validate().
final int moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MAX = 1 [static]
Index in ranges for MAX.
Definition at line 45 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.inRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
final int moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN = 0 [static]
Index in ranges for MIN.
Definition at line 41 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference(), moa.classifiers.lazy.neighboursearch.EuclideanDistance.getMiddle(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.inRanges(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
final int moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH = 2 [static]
Index in ranges for WIDTH.
Definition at line 48 of file NormalizableDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.EuclideanDistance.getMiddle(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRangesEmpty(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.norm(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRangesFirst().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/NormalizableDistance.java