MOA: moa.gui.clustertab.ClusteringEvalPanel Class Reference
moa.gui.clustertab.ClusteringEvalPanel Class Reference
Public Member Functions
ClusteringEvalPanel ()
Creates new form ClusteringEvalPanel.
MeasureCollection[] getSelectedMeasures ()
Package Attributes
Class<?>[] measure_classes = null
ArrayList< JLabel > labels = null
ArrayList< JCheckBox > checkboxes = null
Private Member Functions
void addComponents ()
Class<?>[] findMeasureClasses ()
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
javax.swing.JPanel contentPanel
javax.swing.JScrollPane scrollPane
Detailed Description
Definition at line 32 of file ClusteringEvalPanel.java.
Constructor & Destructor Documentation
moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel ()
Creates new form ClusteringEvalPanel.
Definition at line 41 of file ClusteringEvalPanel.java.
References moa.gui.clustertab.ClusteringEvalPanel.addComponents(), moa.gui.clustertab.ClusteringEvalPanel.checkboxes, moa.gui.clustertab.ClusteringEvalPanel.findMeasureClasses(), moa.gui.clustertab.ClusteringEvalPanel.initComponents(), moa.gui.clustertab.ClusteringEvalPanel.labels, and moa.gui.clustertab.ClusteringEvalPanel.measure_classes.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
{
        initComponents();
        measure_classes = findMeasureClasses();
        labels = new ArrayList<JLabel>();
        checkboxes = new ArrayList<JCheckBox>();
        addComponents();
    }
Member Function Documentation
void moa.gui.clustertab.ClusteringEvalPanel.addComponents () [private]
Definition at line 49 of file ClusteringEvalPanel.java.
References moa.gui.clustertab.ClusteringEvalPanel.checkboxes, moa.gui.clustertab.ClusteringEvalPanel.contentPanel, moa.evaluation.MeasureCollection.getName(), moa.evaluation.MeasureCollection.getNumMeasures(), moa.evaluation.MeasureCollection.isEnabled(), moa.gui.clustertab.ClusteringEvalPanel.labels, and moa.gui.clustertab.ClusteringEvalPanel.measure_classes.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel().
{
        GridBagConstraints gb = new GridBagConstraints();
        gb.insets = new java.awt.Insets(4, 7, 4, 7);
        int counter = 0;
        for (int i = 0; i < measure_classes.length; i++) {
            try {
                MeasureCollection m = (MeasureCollection) measure_classes[i].newInstance();
                for (int j = 0; j < m.getNumMeasures(); j++) {
                    String t = m.getName(j);
                    JLabel l = new JLabel(m.getName(j));
                    l.setPreferredSize(new java.awt.Dimension(100, 14));
                    //labels[i].setToolTipText("");
                    gb.gridx = 0;
                    gb.gridy = counter;
                    labels.add(l);
                    contentPanel.add(l, gb);
                    JCheckBox cb = new JCheckBox();
                    if (m.isEnabled(j)) {
                        cb.setSelected(true);
                    } else {
                        cb.setSelected(false);
                    }
                    gb.gridx = 1;
                    checkboxes.add(cb);
                    contentPanel.add(cb, gb);
                    counter++;
                }
            } catch (Exception ex) {
                Logger.getLogger("Couldn't create Instance for " + measure_classes[i].getName());
                ex.printStackTrace();
            }
        }
        JLabel dummy = new JLabel();
        gb.gridx = 0;
        gb.gridy++;
        gb.gridwidth = 3;
        gb.weightx = 1;
        gb.weighty = 1;
        add(dummy, gb);
    }
Class<?> [] moa.gui.clustertab.ClusteringEvalPanel.findMeasureClasses () [private]
Definition at line 95 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel().
{
        AutoExpandVector<Class<?>> finalClasses = new AutoExpandVector<Class<?>>();
        Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("moa.evaluation",
                MeasureCollection.class);
        for (Class<?> foundClass : classesFound) {
            //Not add ClassificationMeasureCollection
            boolean noClassificationMeasures = true;
            for (Class cl: foundClass.getInterfaces()) {
                if (cl.toString().contains("moa.evaluation.ClassificationMeasureCollection")){
                    noClassificationMeasures = false;
                }
            }
            if (noClassificationMeasures ) {
                finalClasses.add(foundClass);
            }
        }
        return finalClasses.toArray(new Class<?>[finalClasses.size()]);
    }
MeasureCollection [] moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures ()
Definition at line 114 of file ClusteringEvalPanel.java.
References moa.gui.clustertab.ClusteringEvalPanel.checkboxes, moa.evaluation.MeasureCollection.getNumMeasures(), moa.gui.clustertab.ClusteringEvalPanel.measure_classes, and moa.evaluation.MeasureCollection.setEnabled().
Referenced by moa.gui.clustertab.ClusteringSetupTab.getMeasures().
{
        ArrayList<MeasureCollection> measuresSelect = new ArrayList<MeasureCollection>();
        int counter = 0;
        for (int i = 0; i < measure_classes.length; i++) {
            try {
                MeasureCollection m = (MeasureCollection) measure_classes[i].newInstance();
                boolean addMeasure = false;
                for (int j = 0; j < m.getNumMeasures(); j++) {
                    boolean selected = checkboxes.get(counter).isSelected();
                    m.setEnabled(j, selected);
                    if (selected) {
                        addMeasure = true;
                    }
                    counter++;
                }
                if (addMeasure) {
                    measuresSelect.add(m);
                }
            } catch (Exception ex) {
                Logger.getLogger("Couldn't create Instance for " + measure_classes[i].getName());
                ex.printStackTrace();
            }
        }
        MeasureCollection[] measures = new MeasureCollection[measuresSelect.size()];
        for (int i = 0; i < measures.length; i++) {
            measures[i] = measuresSelect.get(i);
        }
        return measures;
    }
void moa.gui.clustertab.ClusteringEvalPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 157 of file ClusteringEvalPanel.java.
References moa.gui.clustertab.ClusteringEvalPanel.contentPanel, and moa.gui.clustertab.ClusteringEvalPanel.scrollPane.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel().
{
        java.awt.GridBagConstraints gridBagConstraints;
        scrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluation Measures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        setLayout(new java.awt.GridBagLayout());
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        if(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight() > 650) {
            scrollPane.setPreferredSize(new java.awt.Dimension(100, 225));
        } else {
            scrollPane.setPreferredSize(new java.awt.Dimension(100, 115));
        }
        contentPanel.setLayout(new java.awt.GridBagLayout());
        scrollPane.setViewportView(contentPanel);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
Member Data Documentation
ArrayList<JCheckBox> moa.gui.clustertab.ClusteringEvalPanel.checkboxes = null [package]
Definition at line 38 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.addComponents(), moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel(), and moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures().
javax.swing.JPanel moa.gui.clustertab.ClusteringEvalPanel.contentPanel [private]
Definition at line 186 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.addComponents(), and moa.gui.clustertab.ClusteringEvalPanel.initComponents().
ArrayList<JLabel> moa.gui.clustertab.ClusteringEvalPanel.labels = null [package]
Definition at line 36 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.addComponents(), and moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel().
Class<?> [] moa.gui.clustertab.ClusteringEvalPanel.measure_classes = null [package]
Definition at line 34 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.addComponents(), moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel(), and moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures().
javax.swing.JScrollPane moa.gui.clustertab.ClusteringEvalPanel.scrollPane [private]
Definition at line 187 of file ClusteringEvalPanel.java.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.initComponents().
The documentation for this class was generated from the following file:
main/java/moa/gui/clustertab/ClusteringEvalPanel.java