MOA: moa.streams.generators.multilabel.MetaMultilabelGenerator Class Reference
moa.streams.generators.multilabel.MetaMultilabelGenerator Class Reference
Stream generator for multilabel data.
Public Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void restart ()
Restarts this stream.
Instance nextInstance ()
GenerateML.
InstancesHeader getHeader ()
Gets the header of this stream.
String getPurposeString ()
Gets the purpose of this object.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Member Functions
static void main (String args[])
Public Attributes
ClassOption binaryGeneratorOption
IntOption metaRandomSeedOption
IntOption numLabelsOption
IntOption skewOption
FloatOption labelCardinalityOption
FloatOption labelCardinalityVarOption
FloatOption labelCardinalityRatioOption
FloatOption labelDependencyChangeRatioOption
Protected Member Functions
MultilabelInstancesHeader generateMultilabelHeader (Instances si)
GenerateMultilabelHeader.
double[] modifyPriorVector (double P[], double u, Random r, boolean skew)
ModifyPriorVector.
boolean[][] modifyDependencyMatrix (boolean M[][], double u, Random r)
ModifyDependencyMatrix.
double[][] generateConditional (double P[], boolean M[][])
GenerateConditional.
Protected Attributes
MultilabelInstancesHeader m_MultilabelInstancesHeader = null
InstanceStream m_BinaryGenerator = null
Instances multilabelStreamTemplate = null
Random m_MetaRandom = new Random()
int m_L = 0
int m_A = 0
double priors [] = null
double priors_norm [] = null
double Conditional [][] = null
HashSet m_TopCombinations [] = null
Package Attributes
LinkedList< Instance > queue [] = null
GetNextWithBinary.
Private Member Functions
double[] generatePriors (Random r, int L, double z, boolean skew)
Generate Priors.
Instance getNextWithBinary (int i)
HashSet generateSet ()
Generate Set.
double joint (int k, int y[])
Instance generateMLInstance (HashSet< Integer > Y)
GenerateMLInstance.
int samplePMF (double p[])
samplePMF.
HashSet[] getTopCombinations (int n)
GetTopCombinations.
int[] set2vector (HashSet< Integer > Y, int L)
HashSet< Integer > vector2set (int y[])
double max (double A, double B)
double min (double A, double B)
ArrayList< Integer > getShuffledListToLWithoutK (int L, int k)
void printMatrix (double M[][])
void printVector (double V[])
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for multilabel data.
Author:
Jesse Read ((jesse@tsc.uc3m.es))
Version:
Revision
7
Definition at line 40 of file MetaMultilabelGenerator.java.
Member Function Documentation
long moa.streams.generators.multilabel.MetaMultilabelGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 485 of file MetaMultilabelGenerator.java.
{
        return -1;
    }
double [][] moa.streams.generators.multilabel.MetaMultilabelGenerator.generateConditional (double P[], boolean M[][]) [protected]
GenerateConditional.
Given the priors distribution and a matrix flagging dependencies, generate a conditional distribution matrix Q; such that: P(i) = Q[i][i] P(i|j) = Q[i][j]
Parameters:
P prior distribution
M dependency matrix (where 1 == dependency)
Returns:
Q conditional dependency matrix
Definition at line 370 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MetaRandom, moa.streams.generators.multilabel.MetaMultilabelGenerator.max(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.min().
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        int L = P.length;
        double Q[][] = new double[L][L];
        // set priors
        for (int j = 0; j < L; j++) {
            Q[j][j] = P[j];
        }
        // create conditionals
        for (int j = 0; j < Q.length; j++) {
            for (int k = j + 1; k < Q[j].length; k++) {
                // dependence
                if (M[j][k]) {
                    // min = tending toward mutual exclusivity
                    // max = tending toward total co-occurence
                    // @NOTE it would also be an option to select in [min,max], but since
                    //       we are approximating the joint distribution, we can take
                    //       a stronger approach, and just take either min or max.
                    Q[j][k] = (m_MetaRandom.nextBoolean() ? min(P[j], P[k]) : max(P[j], P[k]));
                    Q[k][j] = (Q[j][k] * Q[j][j]) / Q[k][k]; // Bayes Rule
                } // independence
                else {
                    Q[j][k] = P[j];
                    Q[k][j] = (Q[j][k] * P[k]) / P[j]; // Bayes Rule
                }
            }
        }
        return Q;
    }
Instance moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance (HashSet< Integer > Y) [private]
GenerateMLInstance.
Parameters:
Y a set of label [indices]
Returns:
a multit-labelled example
Definition at line 260 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.getNextWithBinary(), moa.streams.generators.multilabel.MetaMultilabelGenerator.m_A, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_L, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_TopCombinations, and moa.streams.generators.multilabel.MetaMultilabelGenerator.multilabelStreamTemplate.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.nextInstance().
{
        // create a multi-label instance:
        Instance x_ml = new SparseInstance(this.multilabelStreamTemplate.numAttributes());
        x_ml.setDataset(this.multilabelStreamTemplate);
        // set classes
        for (int j = 0; j < m_L; j++) {
            x_ml.setValue(j, 0.0);
        }
        for (int l : Y) {
            x_ml.setValue(l, 1.0);
        }
        // generate binary instances
        Instance x_0 = getNextWithBinary(0);
        Instance x_1 = getNextWithBinary(1);
        // Loop through each feature attribute @warning: assumes class is last index
        for (int a = 0; a < m_A; a++) {
            // The combination is present: use a positive value
            if (Y.containsAll(m_TopCombinations[a])) {
                x_ml.setValue(m_L + a, x_1.value(a));
                //x_ml.setValue(m_L+a,1.0);
            } // The combination is absent: use a negative value
            else {
                x_ml.setValue(m_L + a, x_0.value(a));
                //x_ml.setValue(m_L+a,0.0);
            }
        }
        return x_ml;
    }
MultilabelInstancesHeader moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader (Instances si) [protected]
GenerateMultilabelHeader.
Parameters:
si single-label Instances
Definition at line 149 of file MetaMultilabelGenerator.java.
References moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_A, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_L, moa.streams.generators.multilabel.MetaMultilabelGenerator.metaRandomSeedOption, and moa.streams.generators.multilabel.MetaMultilabelGenerator.multilabelStreamTemplate.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        Instances mi = new Instances(si, 0, 0);
        mi.setClassIndex(-1);
        mi.deleteAttributeAt(mi.numAttributes() - 1);
        FastVector bfv = new FastVector();
        bfv.addElement("0");
        bfv.addElement("1");
        for (int i = 0; i < this.m_L; i++) {
            mi.insertAttributeAt(new Attribute("class" + i, bfv), i);
        }
        this.multilabelStreamTemplate = mi;
        this.multilabelStreamTemplate.setRelationName("SYN_Z" + this.labelCardinalityOption.getValue() + "L" + this.m_L + "X" + m_A + "S" + metaRandomSeedOption.getValue() + ": -C " + this.m_L);
        this.multilabelStreamTemplate.setClassIndex(this.m_L);
        return new MultilabelInstancesHeader(multilabelStreamTemplate, m_L);
    }
double [] moa.streams.generators.multilabel.MetaMultilabelGenerator.generatePriors (Random r, int L, double z, boolean skew) [private]
Generate Priors.
Generate the label priors.
Parameters:
L number of labels
z desired label cardinality
r random number generator
skew whether to be very skewed or not (not currently used)
Returns:
P label prior distribution
Definition at line 174 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        double P[] = new double[L];
        for (int i = 0; i < L; i++) {
            P[i] = r.nextDouble();
            //P[i] = 1.0; // @temp
        }
        // normalise to z
        do {
            double c = Utils.sum(P) / z;
            for (int i = 0; i < L; i++) {
                P[i] = Math.min(1.0, P[i] / c); // must be in [0,1]
            }
        } while (Utils.sum(P) < z);
        return P;
    }
HashSet moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet () [private]
Generate Set.
Returns:
a label set Y
Definition at line 230 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.getShuffledListToLWithoutK(), moa.streams.generators.multilabel.MetaMultilabelGenerator.joint(), moa.streams.generators.multilabel.MetaMultilabelGenerator.m_L, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MetaRandom, moa.streams.generators.multilabel.MetaMultilabelGenerator.priors_norm, moa.streams.generators.multilabel.MetaMultilabelGenerator.samplePMF(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.vector2set().
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.getTopCombinations(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.nextInstance().
{
        int y[] = new int[m_L];             // [0,0,0]
        int k = samplePMF(priors_norm);     // k = 1     // y[k] ~ p(k==1)
        y[k] = 1;                           // [0,1,0]
        ArrayList<Integer> indices = getShuffledListToLWithoutK(m_L, k);
        for (int j : indices) {
            //y[j] ~ p(j==1|y)
            y[j] = (joint(j, y) > m_MetaRandom.nextDouble()) ? 1 : 0;
        }
        return vector2set(y);
    }
void moa.streams.generators.multilabel.MetaMultilabelGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 500 of file MetaMultilabelGenerator.java.
{
    }
InstancesHeader moa.streams.generators.multilabel.MetaMultilabelGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 475 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MultilabelInstancesHeader.
{
        return m_MultilabelInstancesHeader;
    }
Instance moa.streams.generators.multilabel.MetaMultilabelGenerator.getNextWithBinary (int i) [private]
Definition at line 196 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.m_BinaryGenerator, moa.streams.InstanceStream.nextInstance(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.queue.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance().
{
        int lim = 1000;
        if (queue[i].size() <= 0) {
            int c = -1;
            while (lim-- > 0) {
                Instance tinst = this.m_BinaryGenerator.nextInstance();
                c = (int) Math.round(tinst.classValue());
                if (i == c) {
                    return tinst;
                } else if (queue[c].size() < 100) {
                    queue[c].add(tinst);
                }
            }
            System.err.println("[Overflow] The binary stream is too skewed, could not get an example of class " + i + "");
            System.exit(1);
            return null;
        } else {
            return queue[i].remove();
        }
    }
String moa.streams.generators.multilabel.MetaMultilabelGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 480 of file MetaMultilabelGenerator.java.
{
        return "Generates a multi-label stream based on a binary random generator.";
    }
ArrayList<Integer> moa.streams.generators.multilabel.MetaMultilabelGenerator.getShuffledListToLWithoutK (int L, int k) [private]
Definition at line 534 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
{
        ArrayList<Integer> list = new ArrayList<Integer>(L - 1);
        for (int j = 0; j < L; j++) {
            if (j != k) {
                list.add(j);
            }
        }
        Collections.shuffle(list);
        return list;
    }
HashSet [] moa.streams.generators.multilabel.MetaMultilabelGenerator.getTopCombinations (int n) [private]
GetTopCombinations.
Calculating the full joint probability distribution is too complex. - sample from the approximate joint many times - record the the n most commonly ocurring Y and their frequencies - create a map based on these frequencies
Parameters:
n the number of labelsets
Returns:
n labelsts
Definition at line 414 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        final HashMap<HashSet, Integer> count = new HashMap<HashSet, Integer>();
        HashMap<HashSet, Integer> isets = new HashMap<HashSet, Integer>();
        int N = 100000;
        double lc = 0.0;
        for (int i = 0; i < N; i++) {
            HashSet Y = generateSet();
            lc += Y.size();
            count.put(Y, count.get(Y) != null ? count.get(Y) + 1 : 1);
        }
        lc = lc / N;
        // @TODO could generate closed frequent itemsets from 'count'
        List<HashSet> top_set = new ArrayList<HashSet>(count.keySet());
        // Sort the sets by their count
        Collections.sort(top_set, new Comparator<HashSet>() {
            @Override
            public int compare(HashSet Y1, HashSet Y2) {
                return count.get(Y2).compareTo(count.get(Y1));
            }
        });
        System.err.println("The most common labelsets (from which we will build the map) will likely be: ");
        HashSet map_set[] = new HashSet[n];
        double weights[] = new double[n];
        int idx = 0;
        for (HashSet Y : top_set) {
            System.err.println(" " + Y + " : " + (count.get(Y) * 100.0 / N) + "%");
            weights[idx++] = count.get(Y);
            if (idx == weights.length) {
                break;
            }
        }
        double sum = Utils.sum(weights);
        System.err.println("Estimated Label Cardinality:  " + lc + "\n\n");
        System.err.println("Estimated % Unique Labelsets: " + (count.size() * 100.0 / N) + "%\n\n");
        // normalize weights[]
        Utils.normalize(weights);
        // add sets to the map set, according to their weights
        for (int i = 0, k = 0; i < top_set.size() && k < map_set.length; i++) {   // i'th combination (pre)
            int num = (int) Math.round(Math.max(weights[i] * map_set.length, 1.0));  // i'th weight
            for (int j = 0; j < num && k < map_set.length; j++) {
                map_set[k++] = top_set.get(i);
            }
        }
        // shuffle
        Collections.shuffle(Arrays.asList(map_set));
        // return
        return map_set;
    }
boolean moa.streams.generators.multilabel.MetaMultilabelGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 490 of file MetaMultilabelGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.multilabel.MetaMultilabelGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 495 of file MetaMultilabelGenerator.java.
{
        return true;
    }
double moa.streams.generators.multilabel.MetaMultilabelGenerator.joint (int k, int y[]) [private]
Definition at line 244 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.Conditional.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
{
        double p = 1.0; //priors[k];
        for (int j = 0; j < y.length; j++) {
            if (j != k && y[j] == 1) {
                p *= Conditional[k][j];
            }
        }
        return p;
    }
static void moa.streams.generators.multilabel.MetaMultilabelGenerator.main (String args[]) [static]
Definition at line 546 of file MetaMultilabelGenerator.java.
{
        // test routines
    }
double moa.streams.generators.multilabel.MetaMultilabelGenerator.max (double A, double B) [private]
Definition at line 525 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateConditional().
{
        return Math.min(1.0, (B / A));
    }
double moa.streams.generators.multilabel.MetaMultilabelGenerator.min (double A, double B) [private]
Definition at line 530 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateConditional().
{
        return Math.max(0.0, (-1.0 + A + B));
    }
boolean [][] moa.streams.generators.multilabel.MetaMultilabelGenerator.modifyDependencyMatrix (boolean M[][], double u, Random r) [protected]
ModifyDependencyMatrix.
A certain number of values will be altered. a future improvement would be to detect cycles, since this may lead to inconsistencies. However, due to the rarity of this occurring, and the minimal problems it would cause (and considering that inconsistencies also occr in real datasets) we don't implement this.
Parameters:
M[][] a boolean matrix
u the probability of changing the relationship M[j][k]
r for random numbers
Returns:
the modified M
Definition at line 346 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        //List<int[]> L = new ArrayList<int[]>();
        for (int j = 0; j < M.length; j++) {
            for (int k = j + 1; k < M[j].length; k++) {
                if (/*
                         * !hasCycle(L) &&
                         */r.nextDouble() <= u) {
                    M[j][k] ^= true;
                    //L.add(new int[]{j,k});
                }
            }
        }
        return M;
    }
double [] moa.streams.generators.multilabel.MetaMultilabelGenerator.modifyPriorVector (double P[], double u, Random r, boolean skew) [protected]
ModifyPriorVector.
A certain number of values will be altered.
Parameters:
P[] the prior distribution
u the probability of changing P[j]
r for random numbers
skew NOTE not currently used
Returns:
the modified P
Definition at line 325 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        for (int j = 0; j < P.length; j++) {
            if (r.nextDouble() < u) {
                P[j] = r.nextDouble();
            }
        }
        return P;
    }
Instance moa.streams.generators.multilabel.MetaMultilabelGenerator.nextInstance ()
GenerateML.
Generates a multi-label example.
Implements moa.streams.InstanceStream.
Definition at line 221 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
{
        return generateMLInstance(generateSet());
    }
void moa.streams.generators.multilabel.MetaMultilabelGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 85 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
{
        this.restart();
    }
void moa.streams.generators.multilabel.MetaMultilabelGenerator.printMatrix (double M[][]) [private]
Definition at line 550 of file MetaMultilabelGenerator.java.
{
        System.out.println("--- MATRIX ---");
        for (int i = 0; i < M.length; i++) {
            for (int j = 0; j < M[i].length; j++) {
                System.out.print(" " + Utils.doubleToString(M[i][j], 5, 3));
            }
            System.out.println("");
        }
    }
void moa.streams.generators.multilabel.MetaMultilabelGenerator.printVector (double V[]) [private]
Definition at line 560 of file MetaMultilabelGenerator.java.
{
        System.out.println("--- VECTOR ---");
        for (int j = 0; j < V.length; j++) {
            System.out.print(" " + Utils.doubleToString(V[j], 5, 3));
        }
        System.out.println("");
    }
void moa.streams.generators.multilabel.MetaMultilabelGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 90 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.binaryGeneratorOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.Conditional, moa.streams.generators.multilabel.MetaMultilabelGenerator.generateConditional(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generatePriors(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.streams.generators.multilabel.MetaMultilabelGenerator.getTopCombinations(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityRatioOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.labelDependencyChangeRatioOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_A, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_BinaryGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_L, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MetaRandom, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MultilabelInstancesHeader, moa.streams.generators.multilabel.MetaMultilabelGenerator.m_TopCombinations, moa.streams.generators.multilabel.MetaMultilabelGenerator.metaRandomSeedOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.modifyDependencyMatrix(), moa.streams.generators.multilabel.MetaMultilabelGenerator.modifyPriorVector(), moa.streams.generators.multilabel.MetaMultilabelGenerator.numLabelsOption, moa.streams.generators.multilabel.MetaMultilabelGenerator.priors, moa.streams.generators.multilabel.MetaMultilabelGenerator.priors_norm, moa.streams.generators.multilabel.MetaMultilabelGenerator.queue, moa.streams.InstanceStream.restart(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.skewOption.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.prepareForUseImpl().
{
        // The number of class labels L
        this.m_L = numLabelsOption.getValue();
        if (this.labelCardinalityOption.getValue() > m_L) {
            System.err.println("Error: Label cardinality (z) cannot be greater than the number of labels (c)!");
            System.exit(1);
        }
        // Initialise the chosen binary generator
        this.m_BinaryGenerator = (InstanceStream) getPreparedClassOption(this.binaryGeneratorOption);
        this.m_BinaryGenerator.restart();
        // The number of attributes A (not including class-attributes)
        this.m_A = this.m_BinaryGenerator.getHeader().numAttributes() - 1;
        // Random seed
        this.m_MetaRandom = new Random(this.metaRandomSeedOption.getValue());
        // Set up a queue system
        this.queue = new LinkedList[2];
        for (int i = 0; i < this.queue.length; i++) {
            this.queue[i] = new LinkedList<Instance>();
        }
        // Generate the multi-label header
        this.m_MultilabelInstancesHeader = generateMultilabelHeader(this.m_BinaryGenerator.getHeader());
        // Generate label prior distribution
        this.priors = generatePriors(m_MetaRandom, m_L, labelCardinalityOption.getValue(), (skewOption.getValue() >= 1));
        //printVector(this.priors);
        // Generate the matrix marking the label-dependencies
        boolean DependencyMatrix[][] = modifyDependencyMatrix(new boolean[m_L][m_L], labelCardinalityRatioOption.getValue(), m_MetaRandom);
        // Modify the dependency matrix (and the priors) if they are to change in this stream
        if (labelDependencyChangeRatioOption.getValue() > 0.0) {
            priors = modifyPriorVector(priors, labelDependencyChangeRatioOption.getValue(), m_MetaRandom, (skewOption.getValue() >= 1));
            modifyDependencyMatrix(DependencyMatrix, labelDependencyChangeRatioOption.getValue(), m_MetaRandom);
        }
        // Generate the conditional matrix, using this change matrix
        this.Conditional = generateConditional(priors, DependencyMatrix);
        //printMatrix(this.Conditional);
        // Make a normalised version of the priors
        this.priors_norm = Arrays.copyOf(priors, priors.length);
        Utils.normalize(this.priors_norm);
        // Create the feature-label mappings
        m_TopCombinations = getTopCombinations(m_A);
    }
int moa.streams.generators.multilabel.MetaMultilabelGenerator.samplePMF (double p[]) [private]
samplePMF.
Parameters:
p a pmf
Returns:
an index i of p with probability p[i], and -1 with probability 1.0-p[i]
Definition at line 302 of file MetaMultilabelGenerator.java.
References moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MetaRandom.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
{
        double r = m_MetaRandom.nextDouble();
        double sum = 0.0;
        for (int i = 0; i < p.length; i++) {
            sum += p[i];
            if (r < sum) {
                return i;
            }
        }
        return -1;
    }
int [] moa.streams.generators.multilabel.MetaMultilabelGenerator.set2vector (HashSet< Integer > Y, int L) [private]
Definition at line 505 of file MetaMultilabelGenerator.java.
{
        int y[] = new int[L];
        for (int j : Y) {
            y[j] = 1;
        }
        return y;
    }
HashSet<Integer> moa.streams.generators.multilabel.MetaMultilabelGenerator.vector2set (int y[]) [private]
Definition at line 514 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet().
{
        HashSet<Integer> Y = new HashSet<Integer>();
        for (int j = 0; j < y.length; j++) {
            if (y[j] > 0) {
                Y.add(j);
            }
        }
        return Y;
    }
Member Data Documentation
ClassOption moa.streams.generators.multilabel.MetaMultilabelGenerator.binaryGeneratorOption
Initial value:
 new ClassOption(
            "binaryGenerator", 's', "Binary Generator (specify the number of attributes here, but only two classes!).", InstanceStream.class, "generators.RandomTreeGenerator")
Definition at line 44 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
double moa.streams.generators.multilabel.MetaMultilabelGenerator.Conditional[][] = null [protected]
Definition at line 80 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.joint(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
FloatOption moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityOption
Initial value:
 new FloatOption(
            "labelCardinality", 'z', "Desired label cardinality (average number of labels per example).", 1.5, 0.0, Integer.MAX_VALUE)
Definition at line 56 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
FloatOption moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityRatioOption
Initial value:
 new FloatOption(
            "labelDependency", 'u', "Specifies how much label dependency from 0 (total independence) to 1 (full dependence).", 0.25, 0.0, 1.0)
Definition at line 62 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
FloatOption moa.streams.generators.multilabel.MetaMultilabelGenerator.labelCardinalityVarOption
Initial value:
 new FloatOption(
            "labelCardinalityVar", 'v', "Desired label cardinality variance (variance of z) @NOTE: not currently implemented.", 1.0, 0.0, Integer.MAX_VALUE)
Definition at line 59 of file MetaMultilabelGenerator.java.
FloatOption moa.streams.generators.multilabel.MetaMultilabelGenerator.labelDependencyChangeRatioOption
Initial value:
 new FloatOption(
            "labelDependencyRatioChange", 'r', "Each label-pair dependency has a 'r' chance of being modified. Use this option on the second of two streams with the same random seed (-m) to introduce label-dependence drift.", 0.0, 0.0, 1.0)
Definition at line 65 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
int moa.streams.generators.multilabel.MetaMultilabelGenerator.m_A = 0 [protected]
Definition at line 76 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
InstanceStream moa.streams.generators.multilabel.MetaMultilabelGenerator.m_BinaryGenerator = null [protected]
Definition at line 70 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.getNextWithBinary(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
int moa.streams.generators.multilabel.MetaMultilabelGenerator.m_L = 0 [protected]
Definition at line 76 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
Random moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MetaRandom = new Random() [protected]
Definition at line 74 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateConditional(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet(), moa.streams.generators.multilabel.MetaMultilabelGenerator.restart(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.samplePMF().
MultilabelInstancesHeader moa.streams.generators.multilabel.MetaMultilabelGenerator.m_MultilabelInstancesHeader = null [protected]
Definition at line 68 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.getHeader(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
HashSet moa.streams.generators.multilabel.MetaMultilabelGenerator.m_TopCombinations[] = null [protected]
Definition at line 82 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
IntOption moa.streams.generators.multilabel.MetaMultilabelGenerator.metaRandomSeedOption
Initial value:
 new IntOption(
            "metaRandomSeed", 'm', "Random seed (for the meta process). Use two streams with the same seed and r > 0.0 in the second stream if you wish to introduce drift to the label dependencies without changing the underlying concept.", 1)
Definition at line 47 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
Instances moa.streams.generators.multilabel.MetaMultilabelGenerator.multilabelStreamTemplate = null [protected]
Definition at line 72 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMLInstance(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader().
IntOption moa.streams.generators.multilabel.MetaMultilabelGenerator.numLabelsOption
Initial value:
 new IntOption(
            "numLabels", 'c', "Number of labels.", 10, 2, Integer.MAX_VALUE)
Definition at line 50 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
double moa.streams.generators.multilabel.MetaMultilabelGenerator.priors[] = null [protected]
Definition at line 78 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
double moa.streams.generators.multilabel.MetaMultilabelGenerator.priors_norm[] = null [protected]
Definition at line 78 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.generateSet(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
LinkedList<Instance> moa.streams.generators.multilabel.MetaMultilabelGenerator.queue[] = null [package]
GetNextWithBinary.
Get the next instance with binary class i
Parameters:
i the class to generate (0,1)
Definition at line 194 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.getNextWithBinary(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
final long moa.streams.generators.multilabel.MetaMultilabelGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file MetaMultilabelGenerator.java.
IntOption moa.streams.generators.multilabel.MetaMultilabelGenerator.skewOption
Initial value:
 new IntOption(
            "skew", 'k', "Skewed label distribution: 1 (default) = yes; 0 = no (relatively uniform) @NOTE: not currently implemented.", 1, 0, 1)
Definition at line 53 of file MetaMultilabelGenerator.java.
Referenced by moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/multilabel/MetaMultilabelGenerator.java