MOA: moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList Class Reference
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList Class Reference
A class for a linked list to store the nearest k neighbours to an instance.
Public Member Functions
NeighborList (int length)
Creates the neighborlist with a desired length.
boolean isEmpty ()
Gets whether the list is empty.
int currentLength ()
Gets the current length of the list.
void insertSorted (double distance, Instance instance)
Inserts an instance neighbor into the list, maintaining the list sorted by distance.
void pruneToK (int k)
Prunes the list to contain the k nearest neighbors.
void printList ()
Prints out the contents of the neighborlist.
NeighborNode getFirst ()
returns the first element in the list.
NeighborNode getLast ()
returns the last element in the list.
Protected Attributes
NeighborNode m_First
The first node in the list.
NeighborNode m_Last
The last node in the list.
int m_Length = 1
The number of nodes to attempt to maintain in the list.
Detailed Description
A class for a linked list to store the nearest k neighbours to an instance.
We use a list so that we can take care of cases where multiple neighbours are the same distance away. i.e. the minimum length of the list is k.
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 332 of file NearestNeighbourSearch.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.NeighborList (int length)
Creates the neighborlist with a desired length.
Parameters:
length the length of list to attempt to maintain
Definition at line 348 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Length.
{
      m_Length = length;
    }
Member Function Documentation
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.currentLength ()
Gets the current length of the list.
Returns:
the current length of the list
Definition at line 366 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Next.
{
      int i = 0;
      NeighborNode current = m_First;
      while (current != null) {
        i++;
        current = current.m_Next;
      }
      return i;
    }
NeighborNode moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.getFirst ()
returns the first element in the list.
Returns:
the first element
Definition at line 469 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First.
{
      return m_First;
    }
NeighborNode moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.getLast ()
returns the last element in the list.
Returns:
the last element
Definition at line 478 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Last.
{
      return m_Last;
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.insertSorted (double distance, Instance instance)
Inserts an instance neighbor into the list, maintaining the list sorted by distance.
Parameters:
distance the distance to the instance
instance the neighboring instance
Definition at line 383 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.isEmpty(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Distance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Last, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Length, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Next.
{
      if (isEmpty()) {
        m_First = m_Last = new NeighborNode(distance, instance);
      } else {
        NeighborNode current = m_First;
        if (distance < m_First.m_Distance) {// Insert at head
          m_First = new NeighborNode(distance, instance, m_First);
        } else { // Insert further down the list
          for( ;(current.m_Next != null) &&
          (current.m_Next.m_Distance < distance);
          current = current.m_Next);
          current.m_Next = new NeighborNode(distance, instance,
          current.m_Next);
          if (current.equals(m_Last)) {
            m_Last = current.m_Next;
          }
        }
        // Trip down the list until we've got k list elements (or more if the
        // distance to the last elements is the same).
        int valcount = 0;
        for(current = m_First; current.m_Next != null;
        current = current.m_Next) {
          valcount++;
          if ((valcount >= m_Length) && (current.m_Distance !=
          current.m_Next.m_Distance)) {
            m_Last = current;
            current.m_Next = null;
            break;
          }
        }
      }
    }
boolean moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.isEmpty ()
Gets whether the list is empty.
Returns:
true if list is empty
Definition at line 357 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.insertSorted(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.printList(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.pruneToK().
{
      return (m_First == null);
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.printList ()
Prints out the contents of the neighborlist.
Definition at line 449 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.isEmpty(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Distance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Instance, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Next.
{
      if (isEmpty()) {
        System.out.println("Empty list");
      } else {
        NeighborNode current = m_First;
        while (current != null) {
          System.out.println("Node: instance " + current.m_Instance
          + ", distance " + current.m_Distance);
          current = current.m_Next;
        }
        System.out.println();
      }
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.pruneToK (int k)
Prunes the list to contain the k nearest neighbors.
If there are multiple neighbors at the k'th distance, all will be kept.
Parameters:
k the number of neighbors to keep in the list.
Definition at line 424 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.isEmpty(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Distance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Last, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborNode.m_Next.
{
      if (isEmpty()) {
        return;
      }
      if (k < 1) {
        k = 1;
      }
      int currentK = 0;
      double currentDist = m_First.m_Distance;
      NeighborNode current = m_First;
      for(; current.m_Next != null; current = current.m_Next) {
        currentK++;
        currentDist = current.m_Distance;
        if ((currentK >= k) && (currentDist != current.m_Next.m_Distance)) {
          m_Last = current;
          current.m_Next = null;
          break;
        }
      }
    }
Member Data Documentation
NeighborNode moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_First [protected]
The first node in the list.
Definition at line 335 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.currentLength(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.getFirst(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.insertSorted(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.isEmpty(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.printList(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.pruneToK().
NeighborNode moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Last [protected]
The last node in the list.
Definition at line 338 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.getLast(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.insertSorted(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.pruneToK().
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.m_Length = 1 [protected]
The number of nodes to attempt to maintain in the list.
Definition at line 341 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.insertSorted(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NeighborList.NeighborList().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/NearestNeighbourSearch.java