MOA: moa.classifiers.AbstractClassifier Class Reference
moa.classifiers.AbstractClassifier Class Reference
Abstract Classifier.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
AbstractClassifier ()
Creates an classifier and setups the random seed option if the classifier is randomizable.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
InstancesHeader getModelContext ()
Gets the reference to the header of the data stream.
void setRandomSeed (int s)
Sets the seed for random number generation.
boolean trainingHasStarted ()
Gets whether training has started.
double trainingWeightSeenByModel ()
Gets the sum of the weights of the instances that have been used by this classifier during the training in trainOnInstance.
void resetLearning ()
Resets this classifier.
void trainOnInstance (Instance inst)
Trains this classifier incrementally using the given instance.
Measurement[] getModelMeasurements ()
Gets the current measurements of this classifier.
void getDescription (StringBuilder out, int indent)
Returns a string representation of this object.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Classifier copy ()
Produces a copy of this classifier.
boolean correctlyClassifies (Instance inst)
Gets whether this classifier correctly classifies an instance.
String getClassNameString ()
Gets the name of the attribute of the class from the header.
String getClassLabelString (int classLabelIndex)
Gets the name of a label of the class from the header.
String getAttributeNameString (int attIndex)
Gets the name of an attribute from the header.
String getNominalValueString (int attIndex, int valIndex)
Gets the name of a value of an attribute from the header.
AWTRenderer getAWTRenderer ()
Returns the AWT Renderer.
abstract void resetLearningImpl ()
Resets this classifier.
abstract void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
abstract void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Static Public Member Functions
static boolean contextIsCompatible (InstancesHeader originalContext, InstancesHeader newContext)
Returns if two contexts or headers of instances are compatible.
Public Attributes
IntOption randomSeedOption
Option for randomizable learners to change the random seed.
Random classifierRandom
Random Generator used in randomizable learners.
Protected Member Functions
abstract Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Static Protected Member Functions
static int modelAttIndexToInstanceAttIndex (int index, Instance inst)
Gets the index of the attribute in the instance, given the index of the attribute in the learner.
static int modelAttIndexToInstanceAttIndex (int index, Instances insts)
Gets the index of the attribute in a set of instances, given the index of the attribute in the learner.
Protected Attributes
InstancesHeader modelContext
Header of the instances of the data stream.
double trainingWeightSeenByModel = 0.0
Sum of the weights of the instances trained by this model.
int randomSeed = 1
Random seed used in randomizable learners.
Detailed Description
Abstract Classifier.
All learners for nominal prediction in MOA extend this class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 45 of file AbstractClassifier.java.
Constructor & Destructor Documentation
moa.classifiers.AbstractClassifier.AbstractClassifier ()
Creates an classifier and setups the random seed option if the classifier is randomizable.
Definition at line 72 of file AbstractClassifier.java.
References moa.classifiers.Classifier.isRandomizable(), and moa.classifiers.AbstractClassifier.randomSeedOption.
{
        if (isRandomizable()) {
            this.randomSeedOption = new IntOption("randomSeed", 'r',
                    "Seed for random behaviour of the classifier.", 1);
        }
    }
Member Function Documentation
static boolean moa.classifiers.AbstractClassifier.contextIsCompatible (InstancesHeader originalContext, InstancesHeader newContext) [static]
Returns if two contexts or headers of instances are compatible.
Two contexts are compatible if they follow the following rules:
Rule 1: num classes can increase but never decrease
Rule 2: num attributes can increase but never decrease
Rule 3: num nominal attribute values can increase but never decrease
Rule 4: attribute types must stay in the same order (although class can move; is always skipped over)
Attribute names are free to change, but should always still represent the original attributes.
Parameters:
originalContext the first context to compare
newContext the second context to compare
Returns:
true if the two contexts are compatible.
Definition at line 270 of file AbstractClassifier.java.
Referenced by moa.classifiers.AbstractClassifier.setModelContext().
{
        if (newContext.numClasses() < originalContext.numClasses()) {
            return false; // rule 1
        }
        if (newContext.numAttributes() < originalContext.numAttributes()) {
            return false; // rule 2
        }
        int oPos = 0;
        int nPos = 0;
        while (oPos < originalContext.numAttributes()) {
            if (oPos == originalContext.classIndex()) {
                oPos++;
                if (!(oPos < originalContext.numAttributes())) {
                    break;
                }
            }
            if (nPos == newContext.classIndex()) {
                nPos++;
            }
            if (originalContext.attribute(oPos).isNominal()) {
                if (!newContext.attribute(nPos).isNominal()) {
                    return false; // rule 4
                }
                if (newContext.attribute(nPos).numValues() < originalContext.attribute(oPos).numValues()) {
                    return false; // rule 3
                }
            } else {
                assert (originalContext.attribute(oPos).isNumeric());
                if (!newContext.attribute(nPos).isNumeric()) {
                    return false; // rule 4
                }
            }
            oPos++;
            nPos++;
        }
        return true; // all checks clear
    }
Classifier moa.classifiers.AbstractClassifier.copy ()
Produces a copy of this classifier.
Returns:
the copy of this classifier
Implements moa.classifiers.Classifier.
Definition at line 200 of file AbstractClassifier.java.
References moa.classifiers.Classifier.copy().
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier(), moa.classifiers.rules.AMRulesRegressor.newErrorWeightedVote(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.learners.ChangeDetectorLearner.resetLearningImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), moa.classifiers.active.ActiveClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
{
        return (Classifier) super.copy();
    }
boolean moa.classifiers.AbstractClassifier.correctlyClassifies (Instance inst)
Gets whether this classifier correctly classifies an instance.
Uses getVotesForInstance to obtain the prediction and the instance to obtain its true class.
Parameters:
inst the instance to be classified
Returns:
true if the instance is correctly classified
Implements moa.classifiers.Classifier.
Definition at line 205 of file AbstractClassifier.java.
References moa.classifiers.Classifier.getVotesForInstance().
Referenced by moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoost.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OCBoost.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
{
        return Utils.maxIndex(getVotesForInstance(inst)) == (int) inst.classValue();
    }
String moa.classifiers.AbstractClassifier.getAttributeNameString (int attIndex)
Gets the name of an attribute from the header.
Parameters:
attIndex the attribute index
Returns:
the name of the attribute
Definition at line 235 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.modelContext.
Referenced by moa.classifiers.bayes.NaiveBayes.getModelDescription().
{
        return InstancesHeader.getAttributeNameString(this.modelContext,
                attIndex);
    }
AWTRenderer moa.classifiers.AbstractClassifier.getAWTRenderer ()
Returns the AWT Renderer.
Returns:
the AWT Renderer
Implements moa.gui.AWTRenderable.
Definition at line 316 of file AbstractClassifier.java.
{
        // TODO should return a default renderer here
        // - or should null be interpreted as the default?
        return null;
    }
String moa.classifiers.AbstractClassifier.getClassLabelString (int classLabelIndex)
Gets the name of a label of the class from the header.
Parameters:
classLabelIndex the label index
Returns:
the name of the label of the class
Definition at line 224 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.modelContext.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), moa.classifiers.functions.MajorityClass.getModelDescription(), and moa.classifiers.bayes.NaiveBayes.getModelDescription().
{
        return InstancesHeader.getClassLabelString(this.modelContext,
                classLabelIndex);
    }
String moa.classifiers.AbstractClassifier.getClassNameString ()
Gets the name of the attribute of the class from the header.
Returns:
the string with name of the attribute of the class
Definition at line 214 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.modelContext.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), moa.classifiers.functions.MajorityClass.getModelDescription(), and moa.classifiers.bayes.NaiveBayes.getModelDescription().
{
        return InstancesHeader.getClassNameString(this.modelContext);
    }
void moa.classifiers.AbstractClassifier.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 178 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.getModelDescription(), moa.classifiers.AbstractClassifier.getModelMeasurements(), and moa.classifiers.AbstractClassifier.trainingHasStarted().
{
        StringUtils.appendIndented(out, indent, "Model type: ");
        out.append(this.getClass().getName());
        StringUtils.appendNewline(out);
        Measurement.getMeasurementsDescription(getModelMeasurements(), out,
                indent);
        StringUtils.appendNewlineIndented(out, indent, "Model description:");
        StringUtils.appendNewline(out);
        if (trainingHasStarted()) {
            getModelDescription(out, indent);
        } else {
            StringUtils.appendIndented(out, indent,
                    "Model has not been trained.");
        }
    }
InstancesHeader moa.classifiers.AbstractClassifier.getModelContext ()
Gets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Returns:
the reference to the data stream header
Implements moa.classifiers.Classifier.
Definition at line 106 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.modelContext.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.AccuracyWeightedEnsemble.initVariables(), moa.classifiers.meta.AccuracyUpdatedEnsemble.initVariables(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier(), and moa.classifiers.meta.ADACC.trainOnInstanceImpl().
{
        return this.modelContext;
    }
abstract void moa.classifiers.AbstractClassifier.getModelDescription (StringBuilder out, int indent) [pure virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.AMRulesRegressor, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.ORTO, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.AbstractClassifier.getDescription().
Measurement [] moa.classifiers.AbstractClassifier.getModelMeasurements ()
Gets the current measurements of this classifier.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.Classifier.
Definition at line 152 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.getModelMeasurementsImpl(), moa.classifiers.AbstractClassifier.getSubClassifiers(), moa.AbstractMOAObject.measureByteSize(), and moa.classifiers.AbstractClassifier.trainingWeightSeenByModel().
Referenced by moa.classifiers.AbstractClassifier.getDescription().
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        measurementList.add(new Measurement("model training instances",
                trainingWeightSeenByModel()));
        measurementList.add(new Measurement("model serialized size (bytes)",
                measureByteSize()));
        Measurement[] modelMeasurements = getModelMeasurementsImpl();
        if (modelMeasurements != null) {
            measurementList.addAll(Arrays.asList(modelMeasurements));
        }
        // add average of sub-model measurements
        Classifier[] subModels = getSubClassifiers();
        if ((subModels != null) && (subModels.length > 0)) {
            List<Measurement[]> subMeasurements = new LinkedList<Measurement[]>();
            for (Classifier subModel : subModels) {
                if (subModel != null) {
                    subMeasurements.add(subModel.getModelMeasurements());
                }
            }
            Measurement[] avgMeasurements = Measurement.averageMeasurements(subMeasurements.toArray(new Measurement[subMeasurements.size()][]));
            measurementList.addAll(Arrays.asList(avgMeasurements));
        }
        return measurementList.toArray(new Measurement[measurementList.size()]);
    }
abstract Measurement [] moa.classifiers.AbstractClassifier.getModelMeasurementsImpl () [protected, pure virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.ORTO, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.AbstractClassifier.getModelMeasurements().
String moa.classifiers.AbstractClassifier.getNominalValueString (int attIndex, int valIndex)
Gets the name of a value of an attribute from the header.
Parameters:
attIndex the attribute index
valIndex the value of the attribute
Returns:
the name of the value of the attribute
Definition at line 247 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.modelContext.
{
        return InstancesHeader.getNominalValueString(this.modelContext,
                attIndex, valIndex);
    }
String moa.classifiers.AbstractClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.AdaHoeffdingOptionTree, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.LimAttHoeffdingTree, moa.classifiers.trees.ORTO, and moa.classifiers.trees.RandomHoeffdingTree.
Definition at line 49 of file AbstractClassifier.java.
{
        return "MOA Classifier: " + getClass().getCanonicalName();
    }
Classifier [] moa.classifiers.AbstractClassifier.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, and moa.classifiers.meta.WeightedMajorityAlgorithm.
Definition at line 195 of file AbstractClassifier.java.
Referenced by moa.classifiers.AbstractClassifier.getModelMeasurements().
{
        return null;
    }
static int moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex (int index, Instances insts) [static, protected]
Gets the index of the attribute in a set of instances, given the index of the attribute in the learner.
Parameters:
index the index of the attribute in the learner
insts the instances
Returns:
the index of the attribute in the instances
Definition at line 384 of file AbstractClassifier.java.
{
        return insts.classIndex() > index ? index : index + 1;
    }
static int moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex (int index, Instance inst) [static, protected]
Gets the index of the attribute in the instance, given the index of the attribute in the learner.
Parameters:
index the index of the attribute in the learner
inst the instance
Returns:
the index in the instance
Reimplemented in moa.classifiers.rules.AbstractAMRules.
Definition at line 371 of file AbstractClassifier.java.
Referenced by moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog(), moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.rules.RuleClassifier.theBestAttributes(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl(), moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics(), and moa.classifiers.rules.functions.Perceptron.updateWeights().
{
        return inst.classIndex() > index ? index : index + 1;
    }
void moa.classifiers.AbstractClassifier.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, and moa.classifiers.meta.WeightedMajorityAlgorithm.
Definition at line 80 of file AbstractClassifier.java.
References moa.options.IntOption.getValue(), moa.classifiers.AbstractClassifier.randomSeed, moa.classifiers.AbstractClassifier.randomSeedOption, moa.classifiers.AbstractClassifier.resetLearning(), and moa.classifiers.AbstractClassifier.trainingHasStarted().
{
        if (this.randomSeedOption != null) {
            this.randomSeed = this.randomSeedOption.getValue();
        }
        if (!trainingHasStarted()) {
            resetLearning();
        }
    }
void moa.classifiers.AbstractClassifier.resetLearning ()
Resets this classifier.
It must be similar to starting a new classifier from scratch.
Implements moa.classifiers.Classifier.
Definition at line 130 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.Classifier.isRandomizable(), moa.classifiers.AbstractClassifier.randomSeed, moa.classifiers.AbstractClassifier.resetLearningImpl(), and moa.classifiers.AbstractClassifier.trainingWeightSeenByModel().
Referenced by moa.classifiers.AbstractClassifier.prepareForUseImpl().
{
        this.trainingWeightSeenByModel = 0.0;
        if (isRandomizable()) {
            this.classifierRandom = new Random(this.randomSeed);
        }
        resetLearningImpl();
    }
abstract void moa.classifiers.AbstractClassifier.resetLearningImpl () [pure virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.meta.MLOzaBag, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.AMRulesRegressor, moa.classifiers.rules.functions.FadingTargetMean, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.ORTO, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.AbstractClassifier.resetLearning().
void moa.classifiers.AbstractClassifier.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.lazy.kNN, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.MEKAClassifier, moa.classifiers.multilabel.meta.MLOzaBag, moa.classifiers.multilabel.meta.MLOzaBagAdwin, and moa.classifiers.multilabel.MultilabelHoeffdingTree.
Definition at line 91 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.contextIsCompatible(), moa.classifiers.AbstractClassifier.modelContext, and moa.classifiers.AbstractClassifier.trainingHasStarted().
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
{
        if ((ih != null) && (ih.classIndex() < 0)) {
            throw new IllegalArgumentException(
                    "Context for a classifier must include a class to learn");
        }
        if (trainingHasStarted()
                && (this.modelContext != null)
                && ((ih == null) || !contextIsCompatible(this.modelContext, ih))) {
            throw new IllegalArgumentException(
                    "New context is not compatible with existing model");
        }
        this.modelContext = ih;
    }
void moa.classifiers.AbstractClassifier.setRandomSeed (int s)
Sets the seed for random number generation.
Parameters:
s the seed
Implements moa.classifiers.Classifier.
Definition at line 111 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.randomSeed, moa.classifiers.AbstractClassifier.randomSeedOption, and moa.options.IntOption.setValue().
{
        this.randomSeed = s;
        if (this.randomSeedOption != null) {
            // keep option consistent
            this.randomSeedOption.setValue(s);
        }
    }
boolean moa.classifiers.AbstractClassifier.trainingHasStarted ()
Gets whether training has started.
Returns:
true if training has started
Implements moa.classifiers.Classifier.
Definition at line 120 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.trainingWeightSeenByModel().
Referenced by moa.classifiers.AbstractClassifier.getDescription(), moa.classifiers.AbstractClassifier.prepareForUseImpl(), and moa.classifiers.AbstractClassifier.setModelContext().
{
        return this.trainingWeightSeenByModel > 0.0;
    }
double moa.classifiers.AbstractClassifier.trainingWeightSeenByModel ()
Gets the sum of the weights of the instances that have been used by this classifier during the training in trainOnInstance.
Returns:
the weight of the instances that have been used training
Implements moa.classifiers.Classifier.
Definition at line 125 of file AbstractClassifier.java.
Referenced by moa.classifiers.AbstractClassifier.getModelMeasurements(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.AbstractClassifier.resetLearning(), moa.classifiers.AbstractClassifier.trainingHasStarted(), moa.classifiers.AbstractClassifier.trainOnInstance(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoost.trainOnInstanceImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
{
        return this.trainingWeightSeenByModel;
    }
void moa.classifiers.AbstractClassifier.trainOnInstance (Instance inst)
Trains this classifier incrementally using the given instance.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.Classifier.
Definition at line 139 of file AbstractClassifier.java.
References moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.AbstractClassifier.trainOnInstanceImpl().
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask(), moa.classifiers.meta.DACC.trainAndClassify(), and moa.classifiers.rules.core.RuleActiveRegressionNode.updateStatistics().
{
        boolean isTraining = (inst.weight() > 0.0);
        if (this instanceof SemiSupervisedLearner == false &&
                inst.classIsMissing() == true){
            isTraining = false;
        }
        if (isTraining) {
            this.trainingWeightSeenByModel += inst.weight();
            trainOnInstanceImpl(inst);
        }
    }
abstract void moa.classifiers.AbstractClassifier.trainOnInstanceImpl (Instance inst) [pure virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.MEKAClassifier, moa.classifiers.multilabel.meta.MLOzaBagAdwin, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.functions.FadingTargetMean, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.ORTO, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.AbstractClassifier.trainOnInstance().
Member Data Documentation
Random moa.classifiers.AbstractClassifier.classifierRandom
Random Generator used in randomizable learners.
Definition at line 66 of file AbstractClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance(), moa.classifiers.AbstractClassifier.resetLearning(), moa.classifiers.meta.DACC.trainAndClassify(), moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.RandomRules.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoost.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagASHT.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBag.trainOnInstanceImpl(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl(), moa.classifiers.lazy.kNNwithPAW.trainOnInstanceImpl(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.RandomRules.transformInstance().
InstancesHeader moa.classifiers.AbstractClassifier.modelContext [protected]
Header of the instances of the data stream.
Definition at line 54 of file AbstractClassifier.java.
Referenced by moa.classifiers.meta.ADACC.computeKappa(), moa.classifiers.AbstractClassifier.getAttributeNameString(), moa.classifiers.AbstractClassifier.getClassLabelString(), moa.classifiers.AbstractClassifier.getClassNameString(), moa.classifiers.AbstractClassifier.getModelContext(), moa.classifiers.AbstractClassifier.getNominalValueString(), moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance(), moa.classifiers.multilabel.MultilabelHoeffdingTree.setModelContext(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.setModelContext(), moa.classifiers.multilabel.meta.MLOzaBag.setModelContext(), moa.classifiers.multilabel.MajorityLabelset.setModelContext(), moa.classifiers.AbstractClassifier.setModelContext(), and moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl().
int moa.classifiers.AbstractClassifier.randomSeed = 1 [protected]
Random seed used in randomizable learners.
Definition at line 60 of file AbstractClassifier.java.
Referenced by moa.classifiers.AbstractClassifier.prepareForUseImpl(), moa.classifiers.AbstractClassifier.resetLearning(), and moa.classifiers.AbstractClassifier.setRandomSeed().
IntOption moa.classifiers.AbstractClassifier.randomSeedOption
Option for randomizable learners to change the random seed.
Definition at line 63 of file AbstractClassifier.java.
Referenced by moa.classifiers.AbstractClassifier.AbstractClassifier(), moa.classifiers.AbstractClassifier.prepareForUseImpl(), moa.classifiers.AbstractClassifier.setRandomSeed(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.AbstractClassifier.trainingWeightSeenByModel = 0.0 [protected]
Sum of the weights of the instances trained by this model.
Definition at line 57 of file AbstractClassifier.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/AbstractClassifier.java