MOA: moa.options.AbstractOption Class Reference
moa.options.AbstractOption Class Reference
Abstract option.
Public Member Functions
AbstractOption (String name, char cliChar, String purpose)
Creates a new instance of an abstract option given its class name, command line interface text and its purpose.
String getName ()
Gets the name of this option.
char getCLIChar ()
Gets the Command Line Interface text of this option.
String getPurpose ()
Gets the purpose of this option.
void resetToDefault ()
Resets this option to the default value.
String getStateString ()
Gets the state of this option in human readable form.
Option copy ()
This method produces a copy of this object.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static boolean nameIsLegal (String optionName)
Gets whether the name is valid or not.
Static Public Attributes
static final char[] illegalNameCharacters
Array of characters not valid to use in option names.
Protected Attributes
String name
Name of this option.
char cliChar
Command line interface text of this option.
String purpose
Text of the purpose of this option.
Detailed Description
Abstract option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file AbstractOption.java.
Constructor & Destructor Documentation
moa.options.AbstractOption.AbstractOption (String name, char cliChar, String purpose)
Creates a new instance of an abstract option given its class name, command line interface text and its purpose.
Parameters:
name the name of this option
cliChar the command line interface text
purpose the text describing the purpose of this option
Definition at line 72 of file AbstractOption.java.
References moa.options.AbstractOption.nameIsLegal().
{
        if (!nameIsLegal(name)) {
            throw new IllegalArgumentException("Illegal option name: " + name);
        }
        this.name = name;
        this.cliChar = cliChar;
        this.purpose = purpose;
    }
Member Function Documentation
Option moa.options.AbstractOption.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Reimplemented from moa.AbstractMOAObject.
Definition at line 107 of file AbstractOption.java.
References moa.options.Option.copy().
Referenced by moa.gui.MultiChoiceOptionEditComponent.setEditState(), weka.datagenerators.classifiers.classification.MOA.setOptions(), and weka.classifiers.meta.MOA.setOptions().
{
        return (Option) super.copy();
    }
char moa.options.AbstractOption.getCLIChar ()
Gets the Command Line Interface text of this option.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 87 of file AbstractOption.java.
References moa.options.AbstractOption.cliChar.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString().
{
        return this.cliChar;
    }
void moa.options.AbstractOption.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 112 of file AbstractOption.java.
{
        // TODO Auto-generated method stub
    }
JComponent moa.options.AbstractOption.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Implements moa.options.Option.
Reimplemented in moa.options.AbstractClassOption, moa.options.ClassOption, moa.options.ClassOptionWithNames, moa.options.FileOption, moa.options.FlagOption, moa.options.FloatOption, moa.options.IntOption, moa.options.MultiChoiceOption, and moa.options.WEKAClassOption.
Definition at line 117 of file AbstractOption.java.
{
        return new StringOptionEditComponent(this);
    }
String moa.options.AbstractOption.getName ()
Gets the name of this option.
Returns:
the name of this option
Implements moa.options.Option.
Definition at line 82 of file AbstractOption.java.
References moa.options.AbstractOption.name.
Referenced by moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.AbstractOptionHandler.prepareClassOptions(), moa.options.IntOption.setValue(), moa.options.FloatOption.setValue(), moa.options.WEKAClassOption.setValueViaCLIString(), moa.options.ClassOptionWithNames.setValueViaCLIString(), and moa.options.ClassOption.setValueViaCLIString().
{
        return this.name;
    }
String moa.options.AbstractOption.getPurpose ()
Gets the purpose of this option.
Returns:
the purpose of this option
Implements moa.options.Option.
Definition at line 92 of file AbstractOption.java.
References moa.options.AbstractOption.purpose.
{
        return this.purpose;
    }
String moa.options.AbstractOption.getStateString ()
Gets the state of this option in human readable form.
Returns:
the string with state of this option in human readable form
Implements moa.options.Option.
Reimplemented in moa.options.FlagOption.
Definition at line 102 of file AbstractOption.java.
References moa.options.Option.getValueAsCLIString().
{
        return getValueAsCLIString();
    }
static boolean moa.options.AbstractOption.nameIsLegal (String optionName) [static]
Gets whether the name is valid or not.
Parameters:
optionName the name of the option
Returns:
true if the name that not contain any illegal character
Definition at line 55 of file AbstractOption.java.
References moa.options.AbstractOption.illegalNameCharacters.
Referenced by moa.options.AbstractOption.AbstractOption().
{
        for (char illegalChar : illegalNameCharacters) {
            if (optionName.indexOf(illegalChar) >= 0) {
                return false;
            }
        }
        return true;
    }
void moa.options.AbstractOption.resetToDefault ()
Resets this option to the default value.
Implements moa.options.Option.
Definition at line 97 of file AbstractOption.java.
References moa.options.Option.getDefaultCLIString(), and moa.options.Option.setValueViaCLIString().
Referenced by moa.options.AbstractClassOption.AbstractClassOption(), moa.options.FloatOption.FloatOption(), moa.options.IntOption.IntOption(), moa.options.ListOption.ListOption(), moa.options.MultiChoiceOption.MultiChoiceOption(), and moa.options.StringOption.StringOption().
{
        setValueViaCLIString(getDefaultCLIString());
    }
Member Data Documentation
char moa.options.AbstractOption.cliChar [protected]
Command line interface text of this option.
Definition at line 44 of file AbstractOption.java.
Referenced by moa.options.AbstractOption.getCLIChar().
final char [] moa.options.AbstractOption.illegalNameCharacters [static]
Initial value:
 new char[]{' ', '-',
        '(', ')'}
Array of characters not valid to use in option names.
Definition at line 37 of file AbstractOption.java.
Referenced by moa.options.AbstractOption.nameIsLegal().
String moa.options.AbstractOption.name [protected]
Name of this option.
Definition at line 41 of file AbstractOption.java.
Referenced by moa.options.AbstractOption.getName().
String moa.options.AbstractOption.purpose [protected]
Text of the purpose of this option.
Definition at line 47 of file AbstractOption.java.
Referenced by moa.options.AbstractOption.getPurpose().
The documentation for this class was generated from the following file:
main/java/moa/options/AbstractOption.java