MOA: moa.classifiers.lazy.neighboursearch.EuclideanDistance Class Reference
moa.classifiers.lazy.neighboursearch.EuclideanDistance Class Reference
Implementing Euclidean distance (or similarity) function.
Public Member Functions
EuclideanDistance ()
Constructs an Euclidean Distance object, Instances must be still set.
EuclideanDistance (Instances data)
Constructs an Euclidean Distance object and automatically initializes the ranges.
String globalInfo ()
Returns a string describing this object.
double distance (Instance first, Instance second)
Calculates the distance between two instances.
void postProcessDistances (double distances[])
Does post processing of the distances (if necessary) returned by distance(distance(Instance first, Instance second, double cutOffValue).
double sqDifference (int index, double val1, double val2)
Returns the squared difference of two values of an attribute.
double getMiddle (double[] ranges)
Returns value in the middle of the two parameter values.
int closestPoint (Instance instance, Instances allPoints, int[] pointList) throws Exception
Returns the index of the closest point to the current instance.
boolean valueIsSmallerEqual (Instance instance, int dim, double value)
Returns true if the value of the given dimension is smaller or equal the value to be compared with.
Protected Member Functions
double updateDistance (double currDist, double diff)
Updates the current distance calculated so far with the new difference between two attributes.
Static Private Attributes
static final long serialVersionUID = 1068606253458807903L
for serialization.
Detailed Description
Implementing Euclidean distance (or similarity) function.
One object defines not one distance but the data model in which the distances between objects of that data model can be computed.
Attention: For efficiency reasons the use of consistency checks (like are the data models of the two instances exactly the same), is low.
For more information, see:
Wikipedia. Euclidean distance. URL http://en.wikipedia.org/wiki/Euclidean_distance.
BibTeX:
 &#64;misc{missing_id,
    author = {Wikipedia},
    title = {Euclidean distance},
    URL = {http://en.wikipedia.org/wiki/Euclidean_distance}
 }
Valid options are:
 -D
  Turns off the normalization of attribute
  values in distance calculation.
 -R <col1,col2-col4,...>
  Specifies list of columns to used in the calculation of the
  distance. 'first' and 'last' are valid indices.
  (default: first-last)
 -V
  Invert matching sense of column indices.
Author:
Gabi Schmidberger (gabi@cs.waikato.ac.nz)
Ashraf M. Kibriya (amk14@cs.waikato.ac.nz)
FracPete (fracpete at waikato dot ac dot nz)
Version:
Revision
8034
Definition at line 75 of file EuclideanDistance.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.EuclideanDistance.EuclideanDistance ()
Constructs an Euclidean Distance object, Instances must be still set.
Definition at line 85 of file EuclideanDistance.java.
{
    super();
  }
moa.classifiers.lazy.neighboursearch.EuclideanDistance.EuclideanDistance (Instances data)
Constructs an Euclidean Distance object and automatically initializes the ranges.
Parameters:
data the instances the distance function should work on
Definition at line 95 of file EuclideanDistance.java.
{
    super(data);
  }
Member Function Documentation
int moa.classifiers.lazy.neighboursearch.EuclideanDistance.closestPoint (Instance instance, Instances allPoints, int[] pointList) throws Exception
Returns the index of the closest point to the current instance.
Index is index in Instances object that is the second parameter.
Parameters:
instance the instance to assign a cluster to
allPoints all points
pointList the list of points
Returns:
the index of the closest point
Exceptions:
Exception if something goes wrong
Definition at line 198 of file EuclideanDistance.java.
References moa.classifiers.lazy.neighboursearch.EuclideanDistance.distance().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters().
{
    double minDist = Integer.MAX_VALUE;
    int bestPoint = 0;
    for (int i = 0; i < pointList.length; i++) {
      double dist = distance(instance, allPoints.instance(pointList[i]), Double.POSITIVE_INFINITY);
      if (dist < minDist) {
        minDist = dist;
        bestPoint = i;
      }
    }
    return pointList[bestPoint];
  }
double moa.classifiers.lazy.neighboursearch.EuclideanDistance.distance (Instance first, Instance second)
Calculates the distance between two instances.
Parameters:
first the first instance
second the second instance
Returns:
the distance between the two given instances
Reimplemented from moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Definition at line 123 of file EuclideanDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), moa.classifiers.lazy.neighboursearch.EuclideanDistance.closestPoint(), moa.classifiers.lazy.neighboursearch.KDTree.distanceToHrect(), and moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours().
{
    return Math.sqrt(distance(first, second, Double.POSITIVE_INFINITY));
  }
double moa.classifiers.lazy.neighboursearch.EuclideanDistance.getMiddle (double[] ranges)
Returns value in the middle of the two parameter values.
Parameters:
ranges the ranges to this dimension
Returns:
the middle value
Definition at line 182 of file EuclideanDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_MIN, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.R_WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.splitNode().
{
    double middle = ranges[R_MIN] + ranges[R_WIDTH] * 0.5;
    return middle;
  }
String moa.classifiers.lazy.neighboursearch.EuclideanDistance.globalInfo () [virtual]
Returns a string describing this object.
Returns:
a description of the evaluator suitable for displaying in the explorer/experimenter gui
Implements moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Definition at line 105 of file EuclideanDistance.java.
{
    return
        "Implementing Euclidean distance (or similarity) function.\n\n"
      + "One object defines not one distance but the data model in which "
      + "the distances between objects of that data model can be computed.\n\n"
      + "Attention: For efficiency reasons the use of consistency checks "
      + "(like are the data models of the two instances exactly the same), "
      + "is low.\n\n";
  }
void moa.classifiers.lazy.neighboursearch.EuclideanDistance.postProcessDistances (double distances[])
Does post processing of the distances (if necessary) returned by distance(distance(Instance first, Instance second, double cutOffValue).
It is necessary to do so to get the correct distances if distance(distance(Instance first, Instance second, double cutOffValue) is used. This is because that function actually returns the squared distance to avoid inaccuracies arising from floating point comparison.
Parameters:
distances the distances to post-process
Implements moa.classifiers.lazy.neighboursearch.DistanceFunction.
Definition at line 157 of file EuclideanDistance.java.
{
    for(int i = 0; i < distances.length; i++) {
      distances[i] = Math.sqrt(distances[i]);
    }
  }
double moa.classifiers.lazy.neighboursearch.EuclideanDistance.sqDifference (int index, double val1, double val2)
Returns the squared difference of two values of an attribute.
Parameters:
index the attribute index
val1 the first value
val2 the second value
Returns:
the squared difference
Definition at line 171 of file EuclideanDistance.java.
References moa.classifiers.lazy.neighboursearch.NormalizableDistance.difference().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours().
{
    double val = difference(index, val1, val2);
    return val*val;
  }
double moa.classifiers.lazy.neighboursearch.EuclideanDistance.updateDistance (double currDist, double diff) [protected, virtual]
Updates the current distance calculated so far with the new difference between two attributes.
The difference between the attributes was calculated with the difference(int,double,double) method.
Parameters:
currDist the current distance calculated so far
diff the difference between two new attributes
Returns:
the update distance
See also:
difference(int, double, double)
Implements moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Definition at line 138 of file EuclideanDistance.java.
{
    double  result;
    result  = currDist;
    result += diff * diff;
    return result;
  }
boolean moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual (Instance instance, int dim, double value)
Returns true if the value of the given dimension is smaller or equal the value to be compared with.
Parameters:
instance the instance where the value should be taken of
dim the dimension of the value
value the value to compare with
Returns:
true if value of instance is smaller or equal value
Definition at line 221 of file EuclideanDistance.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours(), moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.rearrangePoints(), moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.rearrangePoints(), and moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.rearrangePoints().
                                       {  //This stays
    return instance.value(dim) <= value;
  }
Member Data Documentation
final long moa.classifiers.lazy.neighboursearch.EuclideanDistance.serialVersionUID = 1068606253458807903L [static, private]
for serialization.
Definition at line 80 of file EuclideanDistance.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/EuclideanDistance.java