MOA: moa.recommender.rc.utils.SparseVector Class Reference
moa.recommender.rc.utils.SparseVector Class Reference
Classes
class SparseVectorIterator
Public Member Functions
SparseVector ()
SparseVector (Map< Integer, Double > map)
int size ()
void set (int index, double val)
void remove (int index)
Set< Integer > getIdxs ()
SparseVector copy ()
Double get (int index)
Iterator< Pair< Integer, Double > > iterator ()
Private Attributes
Map< Integer, Double > map
Static Private Attributes
static final long serialVersionUID = 1971022389328939125L
Detailed Description
Definition at line 27 of file SparseVector.java.
Constructor & Destructor Documentation
moa.recommender.rc.utils.SparseVector.SparseVector ()
Definition at line 34 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
Referenced by moa.recommender.rc.utils.SparseVector.copy().
{
        this.map = new HashMap<Integer, Double>();
    }
moa.recommender.rc.utils.SparseVector.SparseVector (Map< Integer, Double > map)
Definition at line 38 of file SparseVector.java.
{
        if (map == null) this.map = new HashMap<Integer, Double>();
        else this.map = map;
    }
Member Function Documentation
SparseVector moa.recommender.rc.utils.SparseVector.copy () [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 59 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map, and moa.recommender.rc.utils.SparseVector.SparseVector().
{
        return new SparseVector(new HashMap<Integer, Double>(this.map));
    }
Double moa.recommender.rc.utils.SparseVector.get (int index) [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 64 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
{
        return map.get(index);
    }
Set<Integer> moa.recommender.rc.utils.SparseVector.getIdxs () [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 55 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
{
        return map.keySet();
    }
Iterator<Pair<Integer, Double> > moa.recommender.rc.utils.SparseVector.iterator () [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 89 of file SparseVector.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
{
        return new SparseVectorIterator();
    }
void moa.recommender.rc.utils.SparseVector.remove (int index) [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 51 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
{
        map.remove(index);
    }
void moa.recommender.rc.utils.SparseVector.set (int index, double val) [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 47 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
{
        map.put(index, val);
    }
int moa.recommender.rc.utils.SparseVector.size () [virtual]
Implements moa.recommender.rc.utils.Vector.
Definition at line 43 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.map.
                      {
        return map.size();
    }
Member Data Documentation
Map<Integer, Double> moa.recommender.rc.utils.SparseVector.map [private]
Definition at line 32 of file SparseVector.java.
Referenced by moa.recommender.rc.utils.SparseVector.copy(), moa.recommender.rc.utils.SparseVector.get(), moa.recommender.rc.utils.SparseVector.getIdxs(), moa.recommender.rc.utils.SparseVector.remove(), moa.recommender.rc.utils.SparseVector.set(), moa.recommender.rc.utils.SparseVector.size(), and moa.recommender.rc.utils.SparseVector.SparseVector().
final long moa.recommender.rc.utils.SparseVector.serialVersionUID = 1971022389328939125L [static, private]
Reimplemented from moa.recommender.rc.utils.Vector.
Definition at line 31 of file SparseVector.java.
The documentation for this class was generated from the following file:
main/java/moa/recommender/rc/utils/SparseVector.java