MOA: moa.classifiers.trees.FIMTDD Class Reference
moa.classifiers.trees.FIMTDD Class Reference
Classes
interface AdaptationCompatibleNode
A new interface for nodes to be used in an adaptive setting.
class FIMTDDActiveLearningNode
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
class FIMTDDPerceptron
A Perceptron classifier modified to conform to the specifications of Ikonomovska et al.
class FIMTDDSplitNode
A modified SplitNode method implementing the extra information regarding it's parent, and the ability to track the error rate and perform Page-Hinckley tests.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
FIMTDD ()
void trainOnInstanceImpl (Instance inst)
Method for updating (training) the model using a new instance.
Public Attributes
FloatOption PageHinckleyAlphaOption
IntOption PageHinckleyThresholdOption
FloatOption AlternateTreeFadingFactorOption
IntOption AlternateTreeTMinOption
IntOption AlternateTreeTimeOption
FloatOption learningRatioOption = new FloatOption("learningRatio", 'w', "Learning ratio to use for training the Perceptrons in the leaves.", 0.01)
FlagOption learningRatio_Decay_or_Const_Option
Protected Member Functions
void FIMTDD_attemptToSplit (FIMTDDActiveLearningNode node, FIMTDDSplitNode parent, int parentIndex)
Method used to split a leaf node and generate child nodes, if appropriate.
FIMTDDActiveLearningNode newLearningNode ()
Return an empty FIMTDDActiveLearningNode.
FIMTDDActiveLearningNode newLearningNode (double[] initialClassObservations)
Return a new FIMTDDActiveLearningNode using the initial class observations.
FIMTDDSplitNode newSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Return a new FIMTDDSplitNode.
Protected Attributes
DoubleVector splitRatioStatistics = new DoubleVector()
ArrayList< FIMTDDSplitNode > nodesToAdapt = new ArrayList<FIMTDDSplitNode>()
boolean Adaptable = true
double initLearnRate = 0.1
double learnRateDecay = 0.001
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 53 of file FIMTDD.java.
Constructor & Destructor Documentation
moa.classifiers.trees.FIMTDD.FIMTDD ()
Definition at line 64 of file FIMTDD.java.
References moa.classifiers.trees.HoeffdingTree.numericEstimatorOption, and moa.classifiers.trees.HoeffdingTree.splitCriterionOption.
                    {
        numericEstimatorOption = new ClassOption("numericEstimator",
            'n', "Numeric estimator to use.", FIMTDDNumericAttributeClassObserver.class,
            "FIMTDDNumericAttributeClassObserver");
            splitCriterionOption = new ClassOption("splitCriterion",
            's', "Split criterion to use.", SDRSplitCriterion.class,
            "SDRSplitCriterion");
        }
Member Function Documentation
void moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit (FIMTDDActiveLearningNode node, FIMTDDSplitNode parent, int parentIndex) [protected]
Method used to split a leaf node and generate child nodes, if appropriate.
Definition at line 775 of file FIMTDD.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getWeightSeen(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learningModel, moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.setParent(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.setParent(), and moa.classifiers.core.AttributeSplitSuggestion.splitTest.
{
                // Set the split criterion to use to the SDR split criterion as described by Ikonomovska et al.
            SplitCriterion splitCriterion = (SplitCriterion) getPreparedClassOption(this.splitCriterionOption);
            // Using this criterion, find the best split per attribute and rank the results
            AttributeSplitSuggestion[] bestSplitSuggestions = node.getBestSplitSuggestions(splitCriterion, this);
            Arrays.sort(bestSplitSuggestions);
            // Declare a variable to determine if any of the splits should be performed
            boolean shouldSplit = false;
            // If only one split was returned, use it
            if (bestSplitSuggestions.length < 2) {
            shouldSplit = bestSplitSuggestions.length > 0;
            }
            // Otherwise, consider which of the splits proposed may be worth trying
            else {
                // Determine the hoeffding bound value, used to select how many instances should be used to make a test decision
                // to feel reasonably confident that the test chosen by this sample is the same as what would be chosen using infinite examples
            double hoeffdingBound = computeHoeffdingBound(1,this.splitConfidenceOption.getValue(), node.getWeightSeen());
            // Determine the top two ranked splitting suggestions
            AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
            AttributeSplitSuggestion secondBestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 2];
            splitRatioStatistics.addToValue(0,1);
            splitRatioStatistics.addToValue(1,secondBestSuggestion.merit / bestSuggestion.merit);
            // If the upper bound of the sample mean for the ratio of SDR(best suggestion) to SDR(second best suggestion),
            // as determined using the hoeffding bound, is less than 1, then the true mean is also less than 1, and thus at this
            // particular moment of observation the bestSuggestion is indeed the best split option with confidence 1-delta, and
            // splitting should occur.
            // Alternatively, if two or more splits are very similar or identical in terms of their splits, then a threshold limit
            // (default 0.05) is applied to the hoeffding bound; if the hoeffding bound is smaller than this limit then the two
            // competing attributes are equally good, and the split will be made on the one with the higher SDR value.
            if ((((splitRatioStatistics.getValue(1)/splitRatioStatistics.getValue(0)) + hoeffdingBound)  < 1) || (hoeffdingBound < this.tieThresholdOption.getValue())) {
                shouldSplit = true;
            }
            // If the splitting criterion was not met, initiate pruning of the E-BST structures in each attribute observer
            else
            {
                for (int i = 0; i < node.attributeObservers.size(); i++) {
                    AttributeClassObserver obs = node.attributeObservers.get(i);
                    if (obs != null) {
                        ((FIMTDDNumericAttributeClassObserver)obs).removeBadSplits(splitCriterion, secondBestSuggestion.merit / bestSuggestion.merit, bestSuggestion.merit, hoeffdingBound);
                    }
                }
            }
            // If the user has selected this option, it is also possible to remove poor attributes at this stage
            if ((this.removePoorAttsOption != null)
                && this.removePoorAttsOption.isSet()) {
                Set<Integer> poorAtts = new HashSet<Integer>();
                // scan 1 - add any poor to set
                for (int i = 0; i < bestSplitSuggestions.length; i++) {
                if (bestSplitSuggestions[i].splitTest != null) {
                    int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                    if (splitAtts.length == 1) {
                    if (((bestSuggestion.merit / secondBestSuggestion.merit) + hoeffdingBound)  < 1) {
                        poorAtts.add(new Integer(splitAtts[0]));
                    }
                    }
                }
                }
                // scan 2 - remove good ones from set
                for (int i = 0; i < bestSplitSuggestions.length; i++) {
                if (bestSplitSuggestions[i].splitTest != null) {
                    int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                    if (splitAtts.length == 1) {
                    if (((bestSuggestion.merit / secondBestSuggestion.merit) + hoeffdingBound)  < 1) {
                        poorAtts.remove(new Integer(splitAtts[0]));
                    }
                    }
                }
                }
                for (int poorAtt : poorAtts) {
                node.disableAttribute(poorAtt);
                }
            }
            }
            // If the splitting criterion were met, split the current node using the chosen attribute test, and
            // make two new branches leading to (empty) leaves
            if (shouldSplit) {
            AttributeSplitSuggestion splitDecision = bestSplitSuggestions[bestSplitSuggestions.length - 1];
            // Deactivate this node if the best split was to do nothing
            if (splitDecision.splitTest == null) {
                // preprune - null wins
                deactivateLearningNode(node, parent, parentIndex);
            }
            // Otherwise
            else {
                FIMTDDSplitNode newSplit = newSplitNode(splitDecision.splitTest,
                    node.getObservedClassDistribution());
                for (int i = 0; i < splitDecision.numSplits(); i++) {
                FIMTDDActiveLearningNode newChild = newLearningNode(splitDecision.resultingClassDistributionFromSplit(i));
                newChild.learningModel = new FIMTDDPerceptron(node.learningModel);
                newChild.setParent(newSplit);
                newSplit.setChild(i, newChild);
                }
                this.activeLeafNodeCount--;
                this.decisionNodeCount++;
                this.activeLeafNodeCount += splitDecision.numSplits();
                if (parent == null) {
                this.treeRoot = newSplit;
                } else {
                parent.setChild(parentIndex, newSplit);
                newSplit.setParent(parent);
                }
            }
            // Check the memory limits are not being exceeded
            enforceTrackerLimit();
            }
        }
String moa.classifiers.trees.FIMTDD.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 58 of file FIMTDD.java.
{
        return "Implementation of the FIMT-DD tree as described by Ikonomovska et al.";
    }
FIMTDDActiveLearningNode moa.classifiers.trees.FIMTDD.newLearningNode (double[] initialClassObservations) [protected]
Return a new FIMTDDActiveLearningNode using the initial class observations.
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 910 of file FIMTDD.java.
{
                return new FIMTDDActiveLearningNode(initialClassObservations);
        }
FIMTDDActiveLearningNode moa.classifiers.trees.FIMTDD.newLearningNode () [protected]
Return an empty FIMTDDActiveLearningNode.
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 903 of file FIMTDD.java.
{
                return newLearningNode(new double[0]);
        }
FIMTDDSplitNode moa.classifiers.trees.FIMTDD.newSplitNode (InstanceConditionalTest splitTest, double[] classObservations) [protected]
Return a new FIMTDDSplitNode.
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 917 of file FIMTDD.java.
{
                return new FIMTDDSplitNode(splitTest, classObservations);
        }
void moa.classifiers.trees.FIMTDD.trainOnInstanceImpl (Instance inst) [virtual]
Method for updating (training) the model using a new instance.
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 674 of file FIMTDD.java.
References moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.getParent(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getParent(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getPHError(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingTree.LearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.FoundNode.node, moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.PageHinckleyTest(), moa.classifiers.trees.HoeffdingTree.FoundNode.parent, moa.classifiers.trees.HoeffdingTree.FoundNode.parentBranch, moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), and moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.setParent().
{
            // Convert any nominal attributes to numeric ones???
            // If no model exists yet, begin with an empty leaf node (the root)
            if (this.treeRoot == null) {
            this.treeRoot = newLearningNode();
            this.activeLeafNodeCount = 1;
        }
        // Take the current example and traverse it through the tree to a leaf
        FoundNode foundNode = this.treeRoot.filterInstanceToLeaf(inst, null, -1);
        Node leafNode = foundNode.node;
        // If no appropriate leaf already existed, create one
        if (leafNode == null) {
            FIMTDDActiveLearningNode newNode = newLearningNode();
            foundNode.parent.setChild(foundNode.parentBranch, newNode);
            newNode.setParent(foundNode.parent);
            leafNode = newNode;
            this.activeLeafNodeCount++;
        }
        // Update the change detection tests on the path traversed in a bottom-up
        // fashion (i.e. using the error from the leaf node)
        if(leafNode instanceof FIMTDDActiveLearningNode)
        {
            FIMTDDActiveLearningNode currentNode = (FIMTDDActiveLearningNode)leafNode;
            // Retrieve the error for the found leaf node
            //currentNode.learnFromInstance(inst, this);
            Double leafError = currentNode.getPHError(inst) - this.PageHinckleyAlphaOption.getValue();
            // Back-propagate the error through all the parent nodes
            FIMTDDSplitNode parent = (FIMTDDSplitNode)currentNode.getParent();
            while(parent != null && Adaptable)
            {
                // Update the Page-Hinckley error test in the parent node
                if(parent.PageHinckleyTest(leafError, this.PageHinckleyThresholdOption.getValue()) == true)
                {
                    if(!nodesToAdapt.contains(parent))
                    {
                        nodesToAdapt.add(parent);
                        nodesToAdapt.remove(parent.getChild(parent.instanceChildIndex(inst)));
                    }
                }
                // Propagate back to the next parent node
                parent = (FIMTDDSplitNode)parent.getParent();
            }
        }
        if(nodesToAdapt.size() > 0 && Adaptable)
        {
            // Adapt the model tree by creating an alternate tree at this node which
            // will be updated as new instances arrive and may, in time, replace the current subtree
            for(int i = 0; i < nodesToAdapt.size(); i++)
            {
                nodesToAdapt.get(i).learnFromInstance(inst, this, true);
            }
        }
        else
        {
            // Check that the current node is in fact a leaf node (i.e. that we
            // haven't accidently stopped earlier in the tree)
            if (leafNode instanceof LearningNode) {
                LearningNode learningNode = (LearningNode) leafNode;
                // Update the statistics in this leaf node, based on the new instance
                learningNode.learnFromInstance(inst, this);
                // Provided growth is allowed, and this leaf node hasn't been deactivated...
                if (this.growthAllowed && (learningNode instanceof FIMTDDActiveLearningNode)) {
                    // Extract details about this leaf, and the number of examples it has seen
                FIMTDDActiveLearningNode activeLearningNode = (FIMTDDActiveLearningNode) learningNode;
                double weightSeen = activeLearningNode.getWeightSeen();
                // If it has seen Nmin examples since it was last tested for splitting, attempt a split of this node
                if (weightSeen - activeLearningNode.getWeightSeenAtLastSplitEvaluation() >= this.gracePeriodOption.getValue()) {
                    FIMTDD_attemptToSplit(activeLearningNode, (FIMTDDSplitNode)foundNode.parent, foundNode.parentBranch);
                    // Take note of how many instances were seen when this split evaluation was made, so we know when to perform the next split evaluation
                    activeLearningNode.setWeightSeenAtLastSplitEvaluation(weightSeen);
                }
                }
            }
            /*if (this.trainingWeightSeenByModel% this.memoryEstimatePeriodOption.getValue() == 0) {
                estimateModelByteSizes();
            }*/
        }
        }
Member Data Documentation
boolean moa.classifiers.trees.FIMTDD.Adaptable = true [protected]
Definition at line 80 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance().
FloatOption moa.classifiers.trees.FIMTDD.AlternateTreeFadingFactorOption
Initial value:
 new FloatOption(
        "AlternateTreeFadingFactor",
        'f',
        "The fading factor to use when deciding if an alternate tree should replace an original.",
        0.995, 0.0, 1.0)
Definition at line 100 of file FIMTDD.java.
IntOption moa.classifiers.trees.FIMTDD.AlternateTreeTimeOption
Initial value:
 new IntOption(
        "AlternateTreeTime",
        'u',
        "The 'time' (in terms of number of instances) value to use when deciding if an alternate tree should be discarded.",
        1500, 0, Integer.MAX_VALUE)
Definition at line 112 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance().
IntOption moa.classifiers.trees.FIMTDD.AlternateTreeTMinOption
Initial value:
 new IntOption(
        "AlternateTreeTMin",
        'y',
        "The Tmin value to use when deciding if an alternate tree should replace an original.",
        150, 0, Integer.MAX_VALUE)
Definition at line 106 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance().
double moa.classifiers.trees.FIMTDD.initLearnRate = 0.1 [protected]
Definition at line 82 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl().
FlagOption moa.classifiers.trees.FIMTDD.learningRatio_Decay_or_Const_Option
Initial value:
 new FlagOption("learningRatio_Decay_or_Const", 'j',
            "learning Ratio Decay or const parameter.")
Definition at line 120 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl().
FloatOption moa.classifiers.trees.FIMTDD.learningRatioOption = new FloatOption("learningRatio", 'w', "Learning ratio to use for training the Perceptrons in the leaves.", 0.01)
Definition at line 118 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl().
double moa.classifiers.trees.FIMTDD.learnRateDecay = 0.001 [protected]
Definition at line 84 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl().
ArrayList<FIMTDDSplitNode> moa.classifiers.trees.FIMTDD.nodesToAdapt = new ArrayList<FIMTDDSplitNode>() [protected]
Definition at line 78 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance().
FloatOption moa.classifiers.trees.FIMTDD.PageHinckleyAlphaOption
Initial value:
 new FloatOption(
        "PageHinckleyAlpha",
        'a',
        "The alpha value to use in the Page Hinckley change detection tests.",
        0.005, 0.0, 1.0)
Definition at line 88 of file FIMTDD.java.
IntOption moa.classifiers.trees.FIMTDD.PageHinckleyThresholdOption
Initial value:
 new IntOption(
        "PageHinckleyThreshold",
        'h',
        "The threshold value to be used in the Page Hinckley change detection tests.",
        50, 0, Integer.MAX_VALUE)
Definition at line 94 of file FIMTDD.java.
final long moa.classifiers.trees.FIMTDD.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 55 of file FIMTDD.java.
DoubleVector moa.classifiers.trees.FIMTDD.splitRatioStatistics = new DoubleVector() [protected]
Definition at line 75 of file FIMTDD.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/FIMTDD.java