MOA: moa.clusterers.macro.NonConvexCluster Class Reference
moa.clusterers.macro.NonConvexCluster Class Reference
Public Member Functions
NonConvexCluster (CFCluster cluster, List< CFCluster > microclusters)
CFCluster getCF ()
void insert (CFCluster cf)
void remove (CFCluster cf)
double getInclusionProbability (Instance instance)
Returns the probability of the given point belonging to this cluster.
double getRadius ()
See interface Cluster.
Clustering getClustering ()
List< CFCluster > getMicroClusters ()
Package Attributes
List< CFCluster > mMicroClusters
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 33 of file NonConvexCluster.java.
Constructor & Destructor Documentation
moa.clusterers.macro.NonConvexCluster.NonConvexCluster (CFCluster cluster, List< CFCluster > microclusters)
Definition at line 41 of file NonConvexCluster.java.
References moa.cluster.CFCluster.add(), and moa.clusterers.macro.NonConvexCluster.mMicroClusters.
{
        super(cluster); // required
        mMicroClusters = new Vector<CFCluster>();
        mMicroClusters.addAll(microclusters);
        // assuming we have a circular shaped cluster, compute it's center: only
        // for visualization
        for (CFCluster cf : microclusters) {
            if (!cf.equals(cluster))
                this.add(cf);
        }
    }
Member Function Documentation
CFCluster moa.clusterers.macro.NonConvexCluster.getCF () [virtual]
Implements moa.cluster.CFCluster.
Definition at line 54 of file NonConvexCluster.java.
{
        // TODO Auto-generated method stub
        return this;
    }
Clustering moa.clusterers.macro.NonConvexCluster.getClustering ()
Implements moa.clusterers.macro.IDenseMacroCluster.
Definition at line 84 of file NonConvexCluster.java.
References moa.cluster.Clustering.add(), and moa.clusterers.macro.NonConvexCluster.mMicroClusters.
{
        Clustering c = new Clustering();
        for (CFCluster mc : mMicroClusters)
            c.add(mc);
        return c;
    }
double moa.clusterers.macro.NonConvexCluster.getInclusionProbability (Instance instance) [virtual]
Returns the probability of the given point belonging to this cluster.
Parameters:
point
Returns:
a value between 0 and 1
Implements moa.cluster.CFCluster.
Definition at line 68 of file NonConvexCluster.java.
References moa.clusterers.macro.NonConvexCluster.mMicroClusters.
{
        double probability = 0;
        for (CFCluster cf : mMicroClusters) {
            probability = cf.getInclusionProbability(instance);
            if (probability > 0d)
                return probability;
        }
        return probability;
    }
List<CFCluster> moa.clusterers.macro.NonConvexCluster.getMicroClusters ()
Implements moa.clusterers.macro.IDenseMacroCluster.
Definition at line 91 of file NonConvexCluster.java.
References moa.clusterers.macro.NonConvexCluster.mMicroClusters.
Referenced by moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs().
{
        return mMicroClusters;
    }
double moa.clusterers.macro.NonConvexCluster.getRadius () [virtual]
See interface Cluster.
Returns:
The radius of the cluster.
Implements moa.cluster.CFCluster.
Definition at line 79 of file NonConvexCluster.java.
{
        // zero since this is an arbitrarily shaped cluster
        return 0;
    }
void moa.clusterers.macro.NonConvexCluster.insert (CFCluster cf)
Definition at line 59 of file NonConvexCluster.java.
References moa.clusterers.macro.NonConvexCluster.mMicroClusters.
{
        mMicroClusters.add(cf);
    }
void moa.clusterers.macro.NonConvexCluster.remove (CFCluster cf)
Definition at line 63 of file NonConvexCluster.java.
References moa.clusterers.macro.NonConvexCluster.mMicroClusters.
{
        mMicroClusters.remove(cf);
    }
Member Data Documentation
List<CFCluster> moa.clusterers.macro.NonConvexCluster.mMicroClusters [package]
Definition at line 35 of file NonConvexCluster.java.
Referenced by moa.clusterers.macro.NonConvexCluster.getClustering(), moa.clusterers.macro.NonConvexCluster.getInclusionProbability(), moa.clusterers.macro.NonConvexCluster.getMicroClusters(), moa.clusterers.macro.NonConvexCluster.insert(), moa.clusterers.macro.NonConvexCluster.NonConvexCluster(), and moa.clusterers.macro.NonConvexCluster.remove().
final long moa.clusterers.macro.NonConvexCluster.serialVersionUID = 1L [static, private]
Reimplemented from moa.cluster.CFCluster.
Definition at line 39 of file NonConvexCluster.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/macro/NonConvexCluster.java