MOA: moa.streams.filters.CacheFilter Class Reference
moa.streams.filters.CacheFilter Class Reference
Filter for representing a stream that is cached in memory.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
InstancesHeader getHeader ()
Gets the header of this stream.
Instance nextInstance ()
Gets the next instance from this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Member Functions
void restartImpl ()
Restarts this filter.
void init ()
Protected Attributes
Instances cache
int indexCache
int totalCacheInstances
boolean isInitialized
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Filter for representing a stream that is cached in memory.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file CacheFilter.java.
Member Function Documentation
long moa.streams.filters.CacheFilter.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Reimplemented from moa.streams.filters.AbstractStreamFilter.
Definition at line 89 of file CacheFilter.java.
References moa.streams.filters.CacheFilter.indexCache, and moa.streams.filters.CacheFilter.totalCacheInstances.
{
        return this.totalCacheInstances - this.indexCache;
    }
void moa.streams.filters.CacheFilter.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 94 of file CacheFilter.java.
{
        // TODO Auto-ge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         nerated method stub
    }
InstancesHeader moa.streams.filters.CacheFilter.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 69 of file CacheFilter.java.
References moa.streams.InstanceStream.getHeader(), and moa.streams.filters.AbstractStreamFilter.inputStream.
{
        return this.inputStream.getHeader();
    }
String moa.streams.filters.CacheFilter.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 35 of file CacheFilter.java.
{
        return "Stores a dataset in memory.";
    }
boolean moa.streams.filters.CacheFilter.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Reimplemented from moa.streams.filters.AbstractStreamFilter.
Definition at line 84 of file CacheFilter.java.
References moa.streams.filters.CacheFilter.indexCache, and moa.streams.filters.CacheFilter.totalCacheInstances.
Referenced by moa.streams.filters.CacheFilter.nextInstance().
{
        return (this.indexCache < this.totalCacheInstances);
    }
void moa.streams.filters.CacheFilter.init () [protected]
Definition at line 57 of file CacheFilter.java.
References moa.streams.filters.CacheFilter.cache, moa.streams.InstanceStream.getHeader(), moa.streams.InstanceStream.hasMoreInstances(), moa.streams.filters.CacheFilter.indexCache, moa.streams.filters.AbstractStreamFilter.inputStream, moa.streams.filters.CacheFilter.isInitialized, moa.streams.InstanceStream.nextInstance(), and moa.streams.filters.CacheFilter.totalCacheInstances.
Referenced by moa.streams.filters.CacheFilter.restartImpl().
{
        this.cache = new Instances(this.inputStream.getHeader(), 0);
        this.indexCache = 0;
        this.totalCacheInstances = 0;
        while (this.inputStream.hasMoreInstances()) {
            cache.add(this.inputStream.nextInstance());
            this.totalCacheInstances++;
        }
        this.isInitialized = true;
    }
Instance moa.streams.filters.CacheFilter.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 74 of file CacheFilter.java.
References moa.streams.filters.CacheFilter.cache, moa.streams.filters.CacheFilter.hasMoreInstances(), and moa.streams.filters.CacheFilter.indexCache.
{
        Instance inst = null;
        if (this.hasMoreInstances()) {
            inst = (Instance) this.cache.get(indexCache);
            this.indexCache++;
        }
        return inst;
    }
void moa.streams.filters.CacheFilter.restartImpl () [protected, virtual]
Restarts this filter.
All instances that extends from AbstractStreamFilter must implement restartImpl. restart uses restartImpl in AbstractStreamFilter.
Implements moa.streams.filters.AbstractStreamFilter.
Definition at line 50 of file CacheFilter.java.
References moa.streams.filters.CacheFilter.init(), moa.streams.filters.AbstractStreamFilter.inputStream, and moa.streams.filters.CacheFilter.isInitialized.
{
        this.isInitialized = false;
        if (this.inputStream != null) {
            this.init();
        }
    }
Member Data Documentation
Instances moa.streams.filters.CacheFilter.cache [protected]
Definition at line 41 of file CacheFilter.java.
Referenced by moa.streams.filters.CacheFilter.init(), and moa.streams.filters.CacheFilter.nextInstance().
int moa.streams.filters.CacheFilter.indexCache [protected]
Definition at line 43 of file CacheFilter.java.
Referenced by moa.streams.filters.CacheFilter.estimatedRemainingInstances(), moa.streams.filters.CacheFilter.hasMoreInstances(), moa.streams.filters.CacheFilter.init(), and moa.streams.filters.CacheFilter.nextInstance().
boolean moa.streams.filters.CacheFilter.isInitialized [protected]
Definition at line 47 of file CacheFilter.java.
Referenced by moa.streams.filters.CacheFilter.init(), and moa.streams.filters.CacheFilter.restartImpl().
final long moa.streams.filters.CacheFilter.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file CacheFilter.java.
int moa.streams.filters.CacheFilter.totalCacheInstances [protected]
Definition at line 45 of file CacheFilter.java.
Referenced by moa.streams.filters.CacheFilter.estimatedRemainingInstances(), moa.streams.filters.CacheFilter.hasMoreInstances(), and moa.streams.filters.CacheFilter.init().
The documentation for this class was generated from the following file:
main/java/moa/streams/filters/CacheFilter.java