MOA: moa.classifiers.trees.FIMTDD.FIMTDDPerceptron Class Reference
moa.classifiers.trees.FIMTDD.FIMTDDPerceptron Class Reference
A Perceptron classifier modified to conform to the specifications of Ikonomovska et al.
Public Member Functions
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
FIMTDDPerceptron (FIMTDDPerceptron copy)
FIMTDDPerceptron ()
void setWeights (double[] w)
double[] getWeights ()
void resetLearningImpl ()
A method to reset the model.
void trainOnInstanceImpl (Instance inst, FIMTDD ft)
Update the model using the provided instance.
double prediction (Instance inst)
Output the prediction made by this perceptron on the given instance.
Protected Attributes
double[] weightAttribute
DoubleVector attributeStatistics = new DoubleVector()
DoubleVector squaredAttributeStatistics = new DoubleVector()
int instancesSeen = 0
boolean reset
Detailed Description
A Perceptron classifier modified to conform to the specifications of Ikonomovska et al.
Definition at line 536 of file FIMTDD.java.
Constructor & Destructor Documentation
moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.FIMTDDPerceptron (FIMTDDPerceptron copy)
Definition at line 556 of file FIMTDD.java.
References moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.getWeights().
                {
                        this.weightAttribute = copy.getWeights();
                }
moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.FIMTDDPerceptron ()
Definition at line 561 of file FIMTDD.java.
                {
                        this.reset = true;
                }
Member Function Documentation
void moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 552 of file FIMTDD.java.
{
            // TODO Auto-generated method stub
            }
double [] moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.getWeights ()
Definition at line 571 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.FIMTDDPerceptron().
                {
                    return this.weightAttribute;
                }
double moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.prediction (Instance inst)
Output the prediction made by this perceptron on the given instance.
Definition at line 645 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance().
            {
            double prediction = 0;
            if(this.reset == false)
            {
                for (int j = 0; j < inst.numAttributes() - 1; j++) {
                    if(inst.attribute(j).isNumeric())
                    {
                        prediction += this.weightAttribute[j] * inst.value(j);
                    }
                }
                prediction += this.weightAttribute[inst.numAttributes() - 1];
            }
            // Return prediction to 3dp
            return (double)Math.round(prediction * 1000) / 1000;
            }
void moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.resetLearningImpl ()
A method to reset the model.
Definition at line 579 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.FIMTDDActiveLearningNode().
{
            this.reset = true;
            }
void moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.setWeights (double[] w)
Definition at line 566 of file FIMTDD.java.
                {
                    this.weightAttribute = w;
                }
void moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl (Instance inst, FIMTDD ft)
Update the model using the provided instance.
Definition at line 586 of file FIMTDD.java.
References moa.options.FloatOption.getValue(), moa.classifiers.trees.FIMTDD.initLearnRate, moa.options.FlagOption.isSet, moa.classifiers.trees.FIMTDD.learningRatio_Decay_or_Const_Option, moa.classifiers.trees.FIMTDD.learningRatioOption, and moa.classifiers.trees.FIMTDD.learnRateDecay.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance().
{
            // Initialise Perceptron if necessary
            if (this.reset == true) {
                this.reset = false;
                this.weightAttribute = new double[inst.numAttributes()];
                this.instancesSeen = 0;
                this.attributeStatistics = new DoubleVector();
                this.squaredAttributeStatistics = new DoubleVector();
                for (int j = 0; j < inst.numAttributes(); j++) {
                    weightAttribute[j] = 2 * Math.random() - 1;
                }
            }
            // Update attribute statistics
            instancesSeen++;
            for(int j = 0; j < inst.numAttributes() -1; j++)
            {
                attributeStatistics.addToValue(j, inst.value(j));
                squaredAttributeStatistics.addToValue(j, inst.value(j)*inst.value(j));
            }
            // Update weights
            double learningRatio = 0.0;
            if(ft.learningRatio_Decay_or_Const_Option.isSet()){
                learningRatio = ft.learningRatioOption.getValue();
            }else{
                learningRatio = ft.initLearnRate / (1+ instancesSeen*ft.learnRateDecay);
            }
        //  double learningRatio = ft.learningRatioOption.getValue();
            double actualClass = inst.classValue();
            double predictedClass = this.prediction(inst);
            //System.out.println("Actual Class: " + actualClass + "  Prediction: " + predictedClass);
            // SET DELTA TO ACTUAL - PREDICTED, NOT PREDICTED - ACTUAL AS SAID IN PAPER
            double delta = actualClass - predictedClass;
            for (int j = 0; j < inst.numAttributes() - 1; j++) {
                if(inst.attribute(j).isNumeric())
                {
                    // Update weights. Ensure attribute values are normalised first
                    double sd = Math.sqrt((squaredAttributeStatistics.getValue(j) - ((attributeStatistics.getValue(j) * attributeStatistics.getValue(j))/instancesSeen))/instancesSeen);
                    double instanceValue = 0;
                    if(sd > 0.0000001) // Limit found in implementation by Ikonomovska et al (2011)
                    {
                        instanceValue = (inst.value(j) - (attributeStatistics.getValue(j)/instancesSeen))/(3*sd);
                    }
                    this.weightAttribute[j] += learningRatio * delta * instanceValue;
                }
            }
            this.weightAttribute[inst.numAttributes() - 1] += learningRatio * delta;
            }
Member Data Documentation
DoubleVector moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.attributeStatistics = new DoubleVector() [protected]
Definition at line 542 of file FIMTDD.java.
int moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.instancesSeen = 0 [protected]
Definition at line 546 of file FIMTDD.java.
boolean moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.reset [protected]
Definition at line 549 of file FIMTDD.java.
DoubleVector moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.squaredAttributeStatistics = new DoubleVector() [protected]
Definition at line 543 of file FIMTDD.java.
double [] moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.weightAttribute [protected]
Definition at line 539 of file FIMTDD.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/FIMTDD.java