MOA: moa.gui.TextViewerPanel Class Reference
moa.gui.TextViewerPanel Class Reference
This panel displays text.
Public Member Functions
TextViewerPanel ()
void setText (String newText)
void addText (String newText)
Static Public Attributes
static String exportFileExtension = "txt"
Protected Attributes
JTextArea textArea
JScrollPane scrollPane
JButton exportButton
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays text.
Used to output the results of tasks.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file TextViewerPanel.java.
Constructor & Destructor Documentation
moa.gui.TextViewerPanel.TextViewerPanel ()
Definition at line 58 of file TextViewerPanel.java.
References moa.gui.TextViewerPanel.exportButton, moa.gui.TextViewerPanel.exportFileExtension, moa.gui.TextViewerPanel.scrollPane, and moa.gui.TextViewerPanel.textArea.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents(), and moa.gui.clustertab.ClusteringSetupTab.initComponents().
{
        this.textArea = new JTextArea();
        this.textArea.setEditable(false);
        this.textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        this.exportButton = new JButton("Export as .txt file...");
        this.exportButton.setEnabled(false);
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(1, 2));
        buttonPanel.add(this.exportButton);
        setLayout(new BorderLayout());
        this.scrollPane = new JScrollPane(this.textArea);
        add(this.scrollPane, BorderLayout.CENTER);
        add(buttonPanel, BorderLayout.SOUTH);
        this.exportButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setAcceptAllFileFilterUsed(true);
                fileChooser.addChoosableFileFilter(new FileExtensionFilter(
                        exportFileExtension));
                if (fileChooser.showSaveDialog(TextViewerPanel.this) == JFileChooser.APPROVE_OPTION) {
                    File chosenFile = fileChooser.getSelectedFile();
                    String fileName = chosenFile.getPath();
                    if (!chosenFile.exists()
                            && !fileName.endsWith(exportFileExtension)) {
                        fileName = fileName + "." + exportFileExtension;
                    }
                    try {
                        PrintWriter out = new PrintWriter(new BufferedWriter(
                                new FileWriter(fileName)));
                        out.write(TextViewerPanel.this.textArea.getText());
                        out.close();
                    } catch (IOException ioe) {
                        GUIUtils.showExceptionDialog(
                                TextViewerPanel.this.exportButton,
                                "Problem saving file " + fileName, ioe);
                    }
                }
            }
        });
    }
Member Function Documentation
void moa.gui.TextViewerPanel.addText (String newText)
Definition at line 107 of file TextViewerPanel.java.
References moa.gui.TextViewerPanel.setText(), and moa.gui.TextViewerPanel.textArea.
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed(), moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile(), moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile(), moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.print(), moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.printf(), moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.println(), moa.gui.visualization.RunOutlierVisualizer.ShowStatistics(), moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj(), moa.gui.visualization.RunVisualizer.weka(), and moa.gui.visualization.RunOutlierVisualizer.weka().
{
        String text = textArea.getText();
        text += (!text.isEmpty()) ? "\n" : "";
        text += newText;
        setText(text);
    }
void moa.gui.TextViewerPanel.setText (String newText)
Definition at line 100 of file TextViewerPanel.java.
References moa.gui.TextViewerPanel.exportButton, moa.gui.TextViewerPanel.scrollPane, and moa.gui.TextViewerPanel.textArea.
Referenced by moa.gui.TextViewerPanel.addText(), moa.gui.visualization.RunVisualizer.evaluateClustering(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        Point p = this.scrollPane.getViewport().getViewPosition();
        this.textArea.setText(newText);
        this.scrollPane.getViewport().setViewPosition(p);
        this.exportButton.setEnabled(newText != null);
    }
Member Data Documentation
JButton moa.gui.TextViewerPanel.exportButton [protected]
Definition at line 56 of file TextViewerPanel.java.
Referenced by moa.gui.TextViewerPanel.setText(), and moa.gui.TextViewerPanel.TextViewerPanel().
String moa.gui.TextViewerPanel.exportFileExtension = "txt" [static]
Definition at line 50 of file TextViewerPanel.java.
Referenced by moa.gui.TextViewerPanel.TextViewerPanel().
JScrollPane moa.gui.TextViewerPanel.scrollPane [protected]
Definition at line 54 of file TextViewerPanel.java.
Referenced by moa.gui.TextViewerPanel.setText(), and moa.gui.TextViewerPanel.TextViewerPanel().
final long moa.gui.TextViewerPanel.serialVersionUID = 1L [static, private]
Definition at line 48 of file TextViewerPanel.java.
JTextArea moa.gui.TextViewerPanel.textArea [protected]
Definition at line 52 of file TextViewerPanel.java.
Referenced by moa.gui.TextViewerPanel.addText(), moa.gui.TextViewerPanel.setText(), and moa.gui.TextViewerPanel.TextViewerPanel().
The documentation for this class was generated from the following file:
main/java/moa/gui/TextViewerPanel.java