MOA: moa.clusterers.outliers.Angiulli.STORMBase Class Reference
moa.clusterers.outliers.Angiulli.STORMBase Class Reference
Public Member Functions
String getStatistics ()
Public Attributes
FlagOption waitWinFullOption = new FlagOption("waitWinFull", 'a', "Output outliers when windows is full.")
int m_nBothInlierOutlier
int m_nOnlyInlier
int m_nOnlyOutlier
Protected Member Functions
void UpdateStatistics (ISBNode node)
boolean IsNodeIdInWin (long id)
Protected Attributes
Long objId
Vector< ISBNode > windowNodes
ISBIndex ISB
int m_WindowSize
double m_radius
int m_k
int m_QueryFreq
Static Protected Attributes
static final Long FIRST_OBJ_ID = 1L
Package Functions
Long GetWindowEnd ()
Long GetWindowStart ()
boolean IsWinFull ()
boolean CanSearch ()
void SaveOutlier (ISBNode node)
void RemoveOutlier (ISBNode node)
void PrintWindow ()
void PrintNode (ISBNode n)
Detailed Description
Definition at line 28 of file STORMBase.java.
Member Function Documentation
boolean moa.clusterers.outliers.Angiulli.STORMBase.CanSearch () [package]
Definition at line 101 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), moa.options.FlagOption.isSet, moa.clusterers.outliers.Angiulli.STORMBase.IsWinFull(), moa.clusterers.outliers.Angiulli.STORMBase.m_QueryFreq, and moa.clusterers.outliers.Angiulli.STORMBase.waitWinFullOption.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        if (IsWinFull()  || !waitWinFullOption.isSet()) {
            if ((GetWindowEnd() - FIRST_OBJ_ID + 1) % m_QueryFreq == 0) {
                // perform query every m_QueryFreq objects
                return true;
            }
        }
        return false;
    }
String moa.clusterers.outliers.Angiulli.STORMBase.getStatistics ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 50 of file STORMBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage, moa.clusterers.outliers.Angiulli.STORMBase.m_nBothInlierOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyInlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
{
        StringBuilder sb = new StringBuilder();
        sb.append("Statistics:\n\n");
        // get counters of expired nodes
        int nBothInlierOutlier = m_nBothInlierOutlier;
        int nOnlyInlier = m_nOnlyInlier;
        int nOnlyOutlier = m_nOnlyOutlier;
        // add counters of non expired nodes
        for (ISBNode node : windowNodes) {
            if ((node.nInlier > 0) && (node.nOutlier > 0))
                nBothInlierOutlier++;
            else if (node.nInlier > 0)
                nOnlyInlier++;
            else
                nOnlyOutlier++;
        }
        int sum = nBothInlierOutlier + nOnlyInlier + nOnlyOutlier;
        if (sum > 0) {
            sb.append(String.format("  Nodes always inlier: %d (%.1f%%)\n", nOnlyInlier, (100 * nOnlyInlier) / (double)sum));
            sb.append(String.format("  Nodes always outlier: %d (%.1f%%)\n", nOnlyOutlier, (100 * nOnlyOutlier) / (double)sum));
            sb.append(String.format("  Nodes both inlier and outlier: %d (%.1f%%)\n", nBothInlierOutlier, (100 * nBothInlierOutlier) / (double)sum));
            sb.append("  (Sum: " + sum + ")\n");
        }
        sb.append("\n  Total range queries: " + nRangeQueriesExecuted + "\n");
        sb.append("  Max memory usage: " + iMaxMemUsage + " MB\n");
        sb.append("  Total process time: " + String.format("%.2f ms", nTotalRunTime / 1000.0) + "\n");
        return sb.toString();
    }
Long moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd () [package]
Definition at line 86 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.objId.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.CanSearch(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.STORMBase.IsNodeIdInWin(), moa.clusterers.outliers.Angiulli.STORMBase.IsWinFull(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        return objId - 1;
    }
Long moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart () [package]
Definition at line 90 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), and moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.getObjectInfo(), moa.clusterers.outliers.Angiulli.STORMBase.IsNodeIdInWin(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType().
{
        Long x = GetWindowEnd() - m_WindowSize + 1;
        if (x < FIRST_OBJ_ID)
            x = FIRST_OBJ_ID;
        return x;
    }
boolean moa.clusterers.outliers.Angiulli.STORMBase.IsNodeIdInWin (long id) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 131 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), and moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart().
{
        if ((GetWindowStart() <= id) && (id <= GetWindowEnd()) )
            return true;
        else
            return false;
    }
boolean moa.clusterers.outliers.Angiulli.STORMBase.IsWinFull () [package]
Definition at line 97 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), and moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.CanSearch().
{
        return (GetWindowEnd() >= FIRST_OBJ_ID + m_WindowSize - 1);
    }
void moa.clusterers.outliers.Angiulli.STORMBase.PrintNode (ISBNode n) [package]
Definition at line 148 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.StreamObj.dimensions(), moa.clusterers.outliers.Angiulli.StreamObj.get(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        Print("id=" + n.id + " (");
        int dim = n.obj.dimensions();
        for (int d = 0; d < dim; d++) {
            Print(Double.toString(n.obj.get(d)));
            if (d < dim - 1)
                Print(", ");
        }
        Println(")");
    }
void moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow () [package]
Definition at line 138 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
                       {
        Println("Window [" + GetWindowStart() + "-" + GetWindowEnd() + "]: ");
        ISBNode node;
        for (int i = 0; i < windowNodes.size(); i++) {
            node = windowNodes.get(i);
            Print("   Node: ");
            PrintNode(node);
        }
    }
void moa.clusterers.outliers.Angiulli.STORMBase.RemoveOutlier (ISBNode node) [package]
Definition at line 116 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nInlier.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        RemoveOutlier(new Outlier(node.inst, node.id, node));
        node.nInlier++; // update statistics
    }
void moa.clusterers.outliers.Angiulli.STORMBase.SaveOutlier (ISBNode node) [package]
Definition at line 111 of file STORMBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        AddOutlier(new Outlier(node.inst, node.id, node));
        node.nOutlier++; // update statistics
    }
void moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics (ISBNode node) [protected]
Definition at line 121 of file STORMBase.java.
References moa.clusterers.outliers.Angiulli.STORMBase.m_nBothInlierOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyInlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyOutlier, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nInlier, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode().
{
        if ((node.nInlier > 0) && (node.nOutlier > 0))
            m_nBothInlierOutlier++;
        else if (node.nInlier > 0)
            m_nOnlyInlier++;
        else
            m_nOnlyOutlier++;
    }
Member Data Documentation
final Long moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID = 1L [static, protected]
Definition at line 31 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.CanSearch(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.STORMBase.IsWinFull().
ISBIndex moa.clusterers.outliers.Angiulli.STORMBase.ISB [protected]
Definition at line 37 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveSafeInlier().
int moa.clusterers.outliers.Angiulli.STORMBase.m_k [protected]
Definition at line 40 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.ISBNodeAppr(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.ISBNodeExact(), moa.clusterers.outliers.Angiulli.ApproxSTORM.IsSafeInlier(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics(), moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeStatistics(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
int moa.clusterers.outliers.Angiulli.STORMBase.m_nBothInlierOutlier
Definition at line 45 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics().
int moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyInlier
Definition at line 46 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics().
int moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyOutlier
Definition at line 47 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics().
int moa.clusterers.outliers.Angiulli.STORMBase.m_QueryFreq [protected]
Definition at line 42 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.CanSearch(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.Init().
double moa.clusterers.outliers.Angiulli.STORMBase.m_radius [protected]
Definition at line 39 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
int moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize [protected]
Definition at line 38 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.STORMBase.IsWinFull(), moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
Long moa.clusterers.outliers.Angiulli.STORMBase.objId [protected]
Definition at line 34 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
FlagOption moa.clusterers.outliers.Angiulli.STORMBase.waitWinFullOption = new FlagOption("waitWinFull", 'a', "Output outliers when windows is full.")
Definition at line 29 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.STORMBase.CanSearch().
Vector<ISBNode> moa.clusterers.outliers.Angiulli.STORMBase.windowNodes [protected]
Definition at line 36 of file STORMBase.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/Angiulli/STORMBase.java