MOA: moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node Class Reference
moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node Class Reference
Public Member Functions
Node (double val, double label, double weight)
void insertValue (double val, double label, double weight)
Insert a new value into the tree, updating both the sum of values and sum of squared values arrays.
Protected Attributes
Node root = null
Static Private Attributes
static final long serialVersionUID = -4484141636424708465L
Detailed Description
Definition at line 50 of file FIMTDDNumericAttributeClassLimitObserver.java.
Constructor & Destructor Documentation
moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.Node (double val, double label, double weight)
Reimplemented from moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.
Definition at line 58 of file FIMTDDNumericAttributeClassLimitObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), and moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass().
{
            super(val, label, weight);
        }
Member Function Documentation
void moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue (double val, double label, double weight)
Insert a new value into the tree, updating both the sum of values and sum of squared values arrays.
Reimplemented from moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.
Definition at line 71 of file FIMTDDNumericAttributeClassLimitObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.cut_point, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.left, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.leftStatistics, moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.maxNodes, moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.Node(), moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.numNodes, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.right, and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.rightStatistics.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass().
{
        // If the new value equals the value stored in a node, update
        // the left (<=) node information
        if (val == this.cut_point)
        {
            this.leftStatistics.addToValue(0,1);
            this.leftStatistics.addToValue(1,label);
            this.leftStatistics.addToValue(2,label*label);
        }
        // If the new value is less than the value in a node, update the
        // left distribution and send the value down to the left child node.
        // If no left child exists, create one
        else if (val <= this.cut_point) {
            this.leftStatistics.addToValue(0,1);
            this.leftStatistics.addToValue(1,label);
            this.leftStatistics.addToValue(2,label*label);
            if (this.left == null) {
                if(numNodes<maxNodes){
                    this.left = new Node(val, label, weight);
                    ++numNodes;
                }
            } else {
                this.left.insertValue(val, label, weight);
            }
        }
        // If the new value is greater than the value in a node, update the
        // right (>) distribution and send the value down to the right child node.
        // If no right child exists, create one
        else { // val > cut_point
            this.rightStatistics.addToValue(0,1);
            this.rightStatistics.addToValue(1,label);
            this.rightStatistics.addToValue(2,label*label);
            if (this.right == null) {
                if(numNodes<maxNodes){
                    this.right = new Node(val, label, weight);
                    ++numNodes;
                }
            } else {
                this.right.insertValue(val, label, weight);
            }
        }
        }
Member Data Documentation
Node moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.root = null [protected]
Definition at line 62 of file FIMTDDNumericAttributeClassLimitObserver.java.
final long moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.serialVersionUID = -4484141636424708465L [static, private]
Reimplemented from moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.
Definition at line 54 of file FIMTDDNumericAttributeClassLimitObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/attributeclassobservers/FIMTDDNumericAttributeClassLimitObserver.java