MOA: moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier Class Reference
moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier Class Reference
Public Member Functions
MultilabelLearningNodeClassifier (double[] initialClassObservations, Classifier cl, MultilabelHoeffdingTree ht)
double[] getClassVotes (Instance inst, HoeffdingTree ht)
void disableAttribute (int attIndex)
Classifier getClassifier ()
void learnFromInstance (Instance mlinst, HoeffdingTree ht)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 78 of file MultilabelHoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier (double[] initialClassObservations, Classifier cl, MultilabelHoeffdingTree ht)
Definition at line 84 of file MultilabelHoeffdingTree.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.AbstractClassifier.copy(), moa.classifiers.AbstractClassifier.getModelContext(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.learnerOption, and moa.classifiers.Classifier.resetLearning().
{
            super(initialClassObservations);
            if (cl== null) {
                this.classifier = ((Classifier) getPreparedClassOption(ht.learnerOption)).copy();
                this.classifier.resetLearning();
                InstancesHeader raw_header = ht.getModelContext();
                this.classifier.setModelContext(raw_header);
            }
            else{
                this.classifier = cl.copy();
            }
        }
Member Function Documentation
void moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.disableAttribute (int attIndex)
Definition at line 109 of file MultilabelHoeffdingTree.java.
{
            // should not disable poor atts - they are used in NB calc
        }
Classifier moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.getClassifier ()
Definition at line 113 of file MultilabelHoeffdingTree.java.
{
            return this.classifier;
        }
double [] moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.getClassVotes (Instance inst, HoeffdingTree ht)
Definition at line 100 of file MultilabelHoeffdingTree.java.
{
            if (this.classifier == null) {
                return new double[((MultilabelHoeffdingTree) ht).converter.getL()];
            }
            return this.classifier.getVotesForInstance(inst);
        }
void moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance (Instance mlinst, HoeffdingTree ht)
Definition at line 119 of file MultilabelHoeffdingTree.java.
References moa.classifiers.multilabel.MultilabelHoeffdingTree.converter, moa.core.utils.Converter.formatInstance(), moa.core.utils.Converter.getRelevantLabels(), moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.HoeffdingTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingTree.newNumericClassObserver(), and moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass().
{
            this.classifier.trainOnInstance(mlinst);
            MultilabelHoeffdingTree mht = ((MultilabelHoeffdingTree) ht);
            List<Integer> labels = mht.converter.getRelevantLabels(mlinst);
            for (int l : labels){
                this.observedClassDistribution.addToValue( l, mlinst.weight());
            }
            Instance inst = mht.converter.formatInstance(mlinst);
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
            //for (int i = 1; i < inst.numAttributes(); i++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? mht.newNominalClassObserver() : mht.newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
                for (int l : labels){
                    obs.observeAttributeClass(inst.value(instAttIndex), l, inst.weight());
                    //obs.observeAttributeClass(inst.value(instAttIndex), 0, inst.weight());
                }
            }
        }
Member Data Documentation
final long moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.serialVersionUID = 1L [static, private]
Definition at line 82 of file MultilabelHoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/MultilabelHoeffdingTree.java