MOA: moa.classifiers.lazy.kNNwithPAWandADWIN Class Reference
moa.classifiers.lazy.kNNwithPAWandADWIN Class Reference
k Nearest Neighbor ADAPTIVE with ADWIN+PAW.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Protected Attributes
int marker = 0
ArrayList< Integer > timeStamp
double prob
int time
Private Attributes
ADWIN adwin
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
k Nearest Neighbor ADAPTIVE with ADWIN+PAW.
Valid options are:
-k number of neighbours
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
03.2012
Definition at line 36 of file kNNwithPAWandADWIN.java.
Member Function Documentation
void moa.classifiers.lazy.kNNwithPAWandADWIN.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 100 of file kNNwithPAWandADWIN.java.
{
    }
String moa.classifiers.lazy.kNNwithPAWandADWIN.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 47 of file kNNwithPAWandADWIN.java.
{
        return "kNNwithPAWandADWIN: kNN with Probabilistic Approximate Window and ADWIN";
    }
boolean moa.classifiers.lazy.kNNwithPAWandADWIN.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 104 of file kNNwithPAWandADWIN.java.
{
        return true;
    }
void moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 54 of file kNNwithPAWandADWIN.java.
References moa.classifiers.lazy.kNNwithPAWandADWIN.adwin, moa.options.IntOption.getValue(), moa.classifiers.lazy.kNN.limitOption, moa.classifiers.lazy.kNNwithPAWandADWIN.prob, moa.classifiers.lazy.kNNwithPAWandADWIN.time, and moa.classifiers.lazy.kNN.window.
{
        this.window = null;
        this.adwin = new ADWIN();
        this.prob = Math.pow(2.0, -1.0 / this.limitOption.getValue());
        this.time = 0;
    }
void moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 64 of file kNNwithPAWandADWIN.java.
References moa.classifiers.lazy.kNNwithPAWandADWIN.adwin, moa.classifiers.lazy.kNN.C, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.AbstractClassifier.correctlyClassifies(), moa.classifiers.core.driftdetection.ADWIN.getWidth(), moa.classifiers.lazy.kNNwithPAWandADWIN.prob, moa.classifiers.core.driftdetection.ADWIN.setInput(), moa.classifiers.lazy.kNNwithPAWandADWIN.time, moa.classifiers.lazy.kNNwithPAWandADWIN.timeStamp, and moa.classifiers.lazy.kNN.window.
{
        if (inst.classValue() > C) {
            C = (int) inst.classValue();
        }
        // ADWIN
        if (this.window == null) {
            this.window = new Instances(inst.dataset());
        }
        if (this.timeStamp == null) {
            this.timeStamp = new ArrayList<Integer>(10);
        }
        for (int i = 0; i < this.window.size(); i++) {
            if (this.classifierRandom.nextDouble() > this.prob) {
                this.window.delete(i);
                this.timeStamp.remove(i);
            }
        }
        this.window.add(inst);
        this.timeStamp.add(this.time);
        this.time++;
        boolean correctlyClassifies = this.correctlyClassifies(inst);
        if (this.adwin.setInput(correctlyClassifies ? 0 : 1)) {
            //Change
            int size = (int) this.adwin.getWidth();
            for (int i = 0; i < this.window.size(); i++) {
                if (this.timeStamp.get(i) < this.time - size) {
                    this.window.delete(i);
                    this.timeStamp.remove(i);
                }
            }
        }
    }
Member Data Documentation
ADWIN moa.classifiers.lazy.kNNwithPAWandADWIN.adwin [private]
Definition at line 40 of file kNNwithPAWandADWIN.java.
Referenced by moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
int moa.classifiers.lazy.kNNwithPAWandADWIN.marker = 0 [protected]
Definition at line 42 of file kNNwithPAWandADWIN.java.
double moa.classifiers.lazy.kNNwithPAWandADWIN.prob [protected]
Definition at line 51 of file kNNwithPAWandADWIN.java.
Referenced by moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
final long moa.classifiers.lazy.kNNwithPAWandADWIN.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.lazy.kNN.
Definition at line 38 of file kNNwithPAWandADWIN.java.
int moa.classifiers.lazy.kNNwithPAWandADWIN.time [protected]
Definition at line 61 of file kNNwithPAWandADWIN.java.
Referenced by moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
ArrayList<Integer> moa.classifiers.lazy.kNNwithPAWandADWIN.timeStamp [protected]
Definition at line 44 of file kNNwithPAWandADWIN.java.
Referenced by moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/kNNwithPAWandADWIN.java