MOA: moa.classifiers.rules.RuleClassifier Class Reference
moa.classifiers.rules.RuleClassifier Class Reference
This classifier learn ordered and unordered rule set from data stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void resetLearningImpl ()
Resets this classifier.
double getWeightSeen ()
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
void printAnomaliesUnsupervised (StringBuilder out, int indent)
void printAnomaliesSupervised (StringBuilder out, int indent)
void getModelDescriptionNoAnomalyDetection (StringBuilder out, int indent)
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
int getCountNominalAttrib (ArrayList< Predicates > predicateSet)
void initializeRuleStatistics (RuleClassification rl, Predicates pred, Instance inst)
void updateRuleAttribStatistics (Instance inst, RuleClassification rl, int ruleIndex)
double computeAnomalyUnsupervised (RuleClassification rl, int ruleIndex, Instance inst)
double computeAnomalySupervised (RuleClassification rl, int ruleIndex, Instance inst)
double computeMean (double sum, int size)
double computeSD (double squaredVal, double val, int size)
double computeProbability (double mean, double sd, double value)
void createRule (Instance inst)
void expandeRule (RuleClassification rl, Instance inst, int ruleIndex)
void theBestAttributes (Instance instance, AutoExpandVector< AttributeClassObserver > observersParameter)
double entropy (DoubleVector ValorDistClassE)
void findBestValEntropy (Node node, DoubleVector classCountL, DoubleVector classCountR, boolean status, double minEntropy, DoubleVector parentCCLeft)
void mainFindBestValEntropy (Node root)
void findBestValEntropyNominalAtt (AutoExpandVector< DoubleVector > attrib, int attNumValues)
double ComputeHoeffdingBound (double range, double confidence, double n)
boolean checkBestAttrib (double n, AutoExpandVector< AttributeClassObserver > observerss, DoubleVector observedClassDistribution)
void manageMemory (int currentByteSize, int maxByteSize)
Public Attributes
FloatOption PminOption
FloatOption splitConfidenceOption
FloatOption tieThresholdOption
FloatOption anomalyProbabilityThresholdOption
FloatOption probabilityThresholdOption
IntOption anomalyNumInstThresholdOption
IntOption gracePeriodOption
MultiChoiceOption predictionFunctionOption
FlagOption orderedRulesOption
FlagOption anomalyDetectionOption
FlagOption Supervised
FlagOption Unsupervised
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
BigDecimal round (double val)
double[] getBestSecondBestEntropy (DoubleVector entropy)
double getRuleMajorityClassIndex (RuleClassification r)
double[] oberversDistribProb (Instance inst, DoubleVector classDistrib)
double[] firstHit (Instance inst)
double[] weightedMax (Instance inst)
double[] weightedSum (Instance inst)
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
AttributeClassObserver newNumericClassObserver2 ()
Protected Attributes
Instance instance
AutoExpandVector
< AttributeClassObserver > attributeObservers
AutoExpandVector
< AttributeClassObserver > attributeObserversGauss
DoubleVector observedClassDistribution
DoubleVector saveBestEntropy = new DoubleVector()
DoubleVector saveBestEntropyNominalAttrib = new DoubleVector()
DoubleVector ruleClassIndex = new DoubleVector()
DoubleVector saveBestGlobalEntropy = new DoubleVector()
ArrayList< ArrayList< Double > > saveBestValGlobalEntropy = new ArrayList<ArrayList<Double>>()
ArrayList< Double > saveTheBest = new ArrayList<Double>()
ArrayList< RuleClassification > ruleSet = new ArrayList<RuleClassification>()
ArrayList< RuleClassification > ruleSetAnomalies = new ArrayList<RuleClassification>()
ArrayList< Integer > ruleAnomaliesIndex = new ArrayList<Integer>()
ArrayList< ArrayList< Integer > > caseAnomaly = new ArrayList<ArrayList<Integer>>()
ArrayList< ArrayList
< ArrayList< Double > > > ruleAttribAnomalyStatistics = new ArrayList<ArrayList<ArrayList<Double>>>()
ArrayList< RuleClassification > ruleSetAnomaliesSupervised = new ArrayList<RuleClassification>()
ArrayList< Integer > ruleAnomaliesIndexSupervised = new ArrayList<Integer>()
ArrayList< ArrayList< Integer > > caseAnomalySupervised = new ArrayList<ArrayList<Integer>>()
ArrayList< ArrayList
< ArrayList< Double > > > ruleAttribAnomalyStatisticsSupervised = new ArrayList<ArrayList<ArrayList<Double>>>()
Package Attributes
double minEntropyTemp = Double.MAX_VALUE
double cutPointTemp = 0.0
double minEntropyNominalAttrib = Double.MAX_VALUE
double symbol = 0.0
int numInstance = 0
int numAttributes = 0
int numClass = 0
Node root
Predicates pred
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This classifier learn ordered and unordered rule set from data stream.
This algorithm also does the detection of anomalies.
Learning Decision RuleClassifications from Data Streams, IJCAI 2011, J. Gama, P. Kosina
Parameters:
-p: Minimum value of p
-t: Tie Threshold
-c: Split Confidence
-g: GracePeriod, the number of instances a leaf should observe between split attempts
-o: Prediction function to use. Ex:FirstHit
-r: Learn ordered or unordered rule
Author:
P. Kosina, E. Almeida, J. Gama
Version:
Revision
2
Definition at line 66 of file RuleClassifier.java.
Member Function Documentation
boolean moa.classifiers.rules.RuleClassifier.checkBestAttrib (double n, AutoExpandVector< AttributeClassObserver > observerss, DoubleVector observedClassDistribution)
Definition at line 1110 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.ComputeHoeffdingBound(), moa.classifiers.rules.RuleClassifier.entropy(), moa.classifiers.rules.RuleClassifier.getBestSecondBestEntropy(), moa.options.FloatOption.getValue(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.saveBestGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveBestValGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveTheBest, moa.classifiers.rules.RuleClassifier.splitConfidenceOption, and moa.classifiers.rules.RuleClassifier.tieThresholdOption.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), and moa.classifiers.rules.RuleClassifier.expandeRule().
{
        double h0 = entropy(observedClassDistribution);
        boolean  isTheBest = false;
        double[] entropyValues = getBestSecondBestEntropy(this.saveBestGlobalEntropy);
        double bestEntropy = entropyValues[0];
        double secondBestEntropy = entropyValues[1];
        double range = Utils.log2(this.numClass);
        double hoeffdingBound = ComputeHoeffdingBound(range, this.splitConfidenceOption.getValue(), n);
        if ((h0 > bestEntropy) && ((secondBestEntropy - bestEntropy > hoeffdingBound)
                || (hoeffdingBound < this.tieThresholdOption.getValue()))) {
            for (int i = 0; i < this.saveBestValGlobalEntropy.size(); i++) {
                if (bestEntropy ==(this.saveBestValGlobalEntropy.get(i).get(1))) {
                    this.saveTheBest.add(this.saveBestValGlobalEntropy.get(i).get(0));
                    this.saveTheBest.add(this.saveBestValGlobalEntropy.get(i).get(1));
                    this.saveTheBest.add(this.saveBestValGlobalEntropy.get(i).get(2));
                    this.saveTheBest.add((double)i);
                    if (this.saveTheBest.get(2) != 0.0) {
                        this.saveTheBest.add(this.saveBestValGlobalEntropy.get(i).get(3));
                        }
                    break;
                    }
                }
            isTheBest = true;
            } else {
                isTheBest = false;
                }
        return isTheBest;
        }
double moa.classifiers.rules.RuleClassifier.computeAnomalySupervised (RuleClassification rl, int ruleIndex, Instance inst)
Definition at line 678 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.anomalyDetectionOption, moa.classifiers.rules.RuleClassifier.anomalyProbabilityThresholdOption, moa.classifiers.rules.RuleClassification.attributeMissingValues, moa.classifiers.rules.RuleClassification.attributeStatisticsSupervised, moa.classifiers.rules.RuleClassifier.caseAnomalySupervised, moa.classifiers.rules.RuleClassifier.computeMean(), moa.classifiers.rules.RuleClassifier.computeProbability(), moa.classifiers.rules.RuleClassifier.computeSD(), moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassification.instancesSeen, moa.options.FlagOption.isSet, moa.classifiers.rules.RuleClassifier.numInstance, moa.classifiers.rules.RuleClassification.obserClassDistrib, moa.classifiers.rules.RuleClassification.observers, moa.classifiers.rules.RuleClassifier.probabilityThresholdOption, moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndexSupervised, moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatisticsSupervised, moa.classifiers.rules.RuleClassifier.ruleSet, moa.classifiers.rules.RuleClassifier.ruleSetAnomaliesSupervised, and moa.classifiers.rules.RuleClassification.squaredAttributeStatisticsSupervised.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
                                                                                                    { //Not supervised
            ArrayList<Integer> caseAnomalyTemp = new ArrayList<Integer>();
            ArrayList<ArrayList<Double>> AttribAnomalyStatisticTemp2 = new ArrayList<ArrayList<Double>>();
            double D = 0.0;
            double N = 0.0;
            if (rl.instancesSeen > this.anomalyNumInstThresholdOption.getValue() && this.anomalyDetectionOption.isSet()) {
                for (int x = 0; x < inst.numAttributes() - 1; x++) {
                    if(!inst.isMissing(x)){
                        ArrayList<Double> AttribAnomalyStatisticTemp = new ArrayList<Double>();
                        if (inst.attribute(x).isNumeric()) { //Numeric Attributes
                            if((rl.instancesSeen - rl.attributeMissingValues.getValue(x)) > 30){
                                double mean = computeMean((double)rl.attributeStatisticsSupervised.get(x).get((int)inst.classValue()), (int)rl.obserClassDistrib.getValue((int)inst.classValue()));
                                double sd = computeSD((double)rl.squaredAttributeStatisticsSupervised.get(x).get((int)inst.classValue()), (double)rl.attributeStatisticsSupervised.get(x).get((int)inst.classValue()), (int)rl.obserClassDistrib.getValue((int)inst.classValue()));
                                double probability = computeProbability(mean, sd, inst.value(x));
                                if(probability!=0.0) {
                                    D = D + Math.log(probability);
                                    if(probability < this.probabilityThresholdOption.getValue()){  //0.10
                                        N = N + Math.log(probability);
                                        AttribAnomalyStatisticTemp.add((double)x);
                                        AttribAnomalyStatisticTemp.add(inst.value(x));
                                        AttribAnomalyStatisticTemp.add(mean);
                                        AttribAnomalyStatisticTemp.add(sd);
                                        AttribAnomalyStatisticTemp.add(probability);
                                        AttribAnomalyStatisticTemp2.add(AttribAnomalyStatisticTemp);
                                        }
                                    }
                                }
                            }else { //Nominal
                                double attribVal = inst.value(x); //Attribute value
                                double classVal = inst.classValue(); //Attribute value
                                double probability = rl.observers.get(x).probabilityOfAttributeValueGivenClass(attribVal, (int)classVal);
                                if(probability!=0.0) {
                                    D = D + Math.log(probability);
                                    if(probability < this.probabilityThresholdOption.getValue()){  //0.10
                                        N = N + Math.log(probability);
                                        AttribAnomalyStatisticTemp.add((double)x);
                                        AttribAnomalyStatisticTemp.add(inst.value(x));
                                        AttribAnomalyStatisticTemp.add(probability);
                                        AttribAnomalyStatisticTemp2.add(AttribAnomalyStatisticTemp);
                                        }
                                    }
                                }
                        }
                    }
                }
            double anomaly=0.0;
            if(D !=0){
             anomaly = Math.abs(N/D);
            }
            if(anomaly >= this.anomalyProbabilityThresholdOption.getValue()){
                caseAnomalyTemp.add(this.numInstance);
                double val = anomaly * 100;
                caseAnomalyTemp.add((int)val);
                this.caseAnomalySupervised.add(caseAnomalyTemp);
                RuleClassification y = new RuleClassification(this.ruleSet.get(ruleIndex));
                this.ruleSetAnomaliesSupervised.add(y);
                this.ruleAnomaliesIndexSupervised.add(ruleIndex + 1);
                this.ruleAttribAnomalyStatisticsSupervised.add(AttribAnomalyStatisticTemp2);
            }
            return anomaly;
            }
double moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised (RuleClassification rl, int ruleIndex, Instance inst)
Definition at line 603 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.anomalyDetectionOption, moa.classifiers.rules.RuleClassifier.anomalyProbabilityThresholdOption, moa.classifiers.rules.RuleClassification.attributeMissingValues, moa.classifiers.rules.RuleClassification.attributeStatistics, moa.classifiers.rules.RuleClassifier.caseAnomaly, moa.classifiers.rules.RuleClassifier.computeMean(), moa.classifiers.rules.RuleClassifier.computeProbability(), moa.classifiers.rules.RuleClassifier.computeSD(), moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassification.instancesSeen, moa.options.FlagOption.isSet, moa.classifiers.rules.RuleClassifier.numInstance, moa.classifiers.rules.RuleClassification.observers, moa.classifiers.rules.RuleClassifier.probabilityThresholdOption, moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndex, moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatistics, moa.classifiers.rules.RuleClassifier.ruleSet, moa.classifiers.rules.RuleClassifier.ruleSetAnomalies, and moa.classifiers.rules.RuleClassification.squaredAttributeStatistics.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
                                                                                                  { //Unsupervised
        ArrayList<Integer> caseAnomalyTemp = new ArrayList<Integer>();
        ArrayList<ArrayList<Double>> AttribAnomalyStatisticTemp2 = new ArrayList<ArrayList<Double>>();
        double D = 0.0;
        double N = 0.0;
        if (rl.instancesSeen > this.anomalyNumInstThresholdOption.getValue() && this.anomalyDetectionOption.isSet()) {
            for (int x = 0; x < inst.numAttributes() - 1; x++) {
                if(!inst.isMissing(x)){
                    ArrayList<Double> AttribAnomalyStatisticTemp = new ArrayList<Double>();
                    if (inst.attribute(x).isNumeric()) { //Numeric Attributes
                        if((rl.instancesSeen - rl.attributeMissingValues.getValue(x)) > 30){
                        double mean = computeMean(rl.attributeStatistics.getValue(x), rl.instancesSeen);
                        double sd = computeSD(rl.squaredAttributeStatistics.getValue(x),rl.attributeStatistics.getValue(x), rl.instancesSeen);
                        double probability = computeProbability(mean, sd, inst.value(x));
                        if(probability!=0.0) {
                            D = D + Math.log(probability);
                            if(probability < this.probabilityThresholdOption.getValue()){  //0.10
                                N = N + Math.log(probability);
                                AttribAnomalyStatisticTemp.add((double)x);
                                AttribAnomalyStatisticTemp.add(inst.value(x));
                                AttribAnomalyStatisticTemp.add(mean);
                                AttribAnomalyStatisticTemp.add(sd);
                                AttribAnomalyStatisticTemp.add(probability);
                                AttribAnomalyStatisticTemp2.add(AttribAnomalyStatisticTemp);
                                }
                            }
                        }
                    }else { //Nominal Attributes
                            AutoExpandVector<DoubleVector> attribNominal = ((NominalAttributeClassObserver)rl.observers.get(x)).attValDistPerClass; //Attributes values distribution per class
                            double numbAttribValue = 0.0;
                            double attribVal = inst.value(x); //Attribute value
                            for(int i = 0; i < attribNominal.size(); i++){
                                if(attribNominal.get(i) != null){
                                    numbAttribValue = numbAttribValue + attribNominal.get(i).getValue((int)attribVal);
                                }
                            }
                            double probability = numbAttribValue / rl.instancesSeen;
                            if(probability!= 0.0) {
                                D = D + Math.log(probability);
                                if(probability < this.probabilityThresholdOption.getValue()){  //0.10
                                    N = N + Math.log(probability);
                                    AttribAnomalyStatisticTemp.add((double)x);
                                    AttribAnomalyStatisticTemp.add(inst.value(x));
                                    AttribAnomalyStatisticTemp.add(probability);
                                    AttribAnomalyStatisticTemp2.add(AttribAnomalyStatisticTemp);
                                    }
                                }
                            }
                    }
                }
            }
        double anomaly=0.0;
        if(D !=0){
         anomaly = Math.abs(N/D);
        }
        if(anomaly >= this.anomalyProbabilityThresholdOption.getValue()){
            caseAnomalyTemp.add(this.numInstance);
            double val = anomaly * 100;
            caseAnomalyTemp.add((int)val);
            this.caseAnomaly.add(caseAnomalyTemp);
            RuleClassification x = new RuleClassification(this.ruleSet.get(ruleIndex));
            this.ruleSetAnomalies.add(x);
            this.ruleAnomaliesIndex.add(ruleIndex + 1);
            this.ruleAttribAnomalyStatistics.add(AttribAnomalyStatisticTemp2);
        }
        return anomaly;
    }
double moa.classifiers.rules.RuleClassifier.ComputeHoeffdingBound (double range, double confidence, double n)
Definition at line 1103 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib().
{
        return Math.sqrt(((range * range) * Math.log(1.0 / confidence))
                        / (2.0 * n));
        }
double moa.classifiers.rules.RuleClassifier.computeMean (double sum, int size)
Definition at line 741 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised().
{
        return sum / size;
    }
double moa.classifiers.rules.RuleClassifier.computeProbability (double mean, double sd, double value)
Definition at line 751 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised().
{
        sd = sd + 0.00001;
        double probability = 0.0;
        double diff = value - mean;
        if (sd > 0.0) {
                double k = (Math.abs(value - mean)/sd);
                if (k > 1.0) {
                    probability = 1.0/(k*k);
                }
                else {
                    probability=  Math.exp(-(diff * diff / (2.0 * sd * sd)));
                }
         }
        return probability;
    }
double moa.classifiers.rules.RuleClassifier.computeSD (double squaredVal, double val, int size)
Definition at line 746 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised().
{
        return  Math.sqrt((squaredVal - ((val * val) / size)) / size);
    }
void moa.classifiers.rules.RuleClassifier.createRule (Instance inst)
Definition at line 768 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.options.IntOption.getValue(), moa.classifiers.rules.RuleClassifier.gracePeriodOption, moa.classifiers.rules.RuleClassifier.minEntropyNominalAttrib, moa.classifiers.rules.RuleClassifier.minEntropyTemp, moa.classifiers.rules.RuleClassifier.observedClassDistribution, moa.classifiers.rules.RuleClassifier.pred, moa.classifiers.rules.RuleClassification.predicateSet, moa.classifiers.rules.RuleClassifier.ruleClassIndex, moa.classifiers.rules.RuleClassifier.ruleSet, moa.classifiers.rules.RuleClassifier.saveBestGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveBestValGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveTheBest, moa.core.DoubleVector.setValue(), moa.core.DoubleVector.sumOfValues(), moa.classifiers.rules.RuleClassifier.symbol, and moa.classifiers.rules.RuleClassifier.theBestAttributes().
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
{
        int remainder = (int)Double.MAX_VALUE;
        int numInstanciaObservers = (int)this.observedClassDistribution.sumOfValues();
        if (numInstanciaObservers != 0 && this.gracePeriodOption.getValue() != 0) {
            remainder = (numInstanciaObservers) % (this.gracePeriodOption.getValue());
            }
        if (remainder == 0) {
            this.saveBestValGlobalEntropy = new ArrayList<ArrayList<Double>>();
            this.saveBestGlobalEntropy = new DoubleVector();
            this.saveTheBest = new ArrayList<Double>();
            this.minEntropyTemp = Double.MAX_VALUE;
            this.minEntropyNominalAttrib = Double.MAX_VALUE;
            theBestAttributes(inst, this.attributeObservers);
            boolean HB = checkBestAttrib(numInstanciaObservers, this.attributeObservers, this.observedClassDistribution);
            if (HB == true) {
            //  System.out.print("this.saveTheBest"+this.saveTheBest+"\n");
                double attributeValue = this.saveTheBest.get(3);
                double symbol = this.saveTheBest.get(2);        // =, <=, > : (0.0, -1.0, 1.0).
                double value = this.saveTheBest.get(0);     // Value of the attribute
                this.pred = new Predicates(attributeValue, symbol, value);
                RuleClassification Rl = new RuleClassification();       // Create RuleClassification.
                Rl.predicateSet.add(pred);
                this.ruleSet.add(Rl);
                if (Rl.predicateSet.get(0).getSymbol() == -1.0 ||Rl.predicateSet.get(0).getSymbol() == 1.0) {
                    double posClassDouble = this.saveTheBest.get(4);
                    this.ruleClassIndex.setValue(this.ruleSet.size()-1, posClassDouble);
                    }else{
                            this.ruleClassIndex.setValue(ruleSet.size()-1, 0.0);
                            }
                    this.observedClassDistribution = new DoubleVector();
                    this.attributeObservers = new AutoExpandVector<AttributeClassObserver>();
                    this.attributeObserversGauss = new AutoExpandVector<AttributeClassObserver>();
                }
            }
    }
double moa.classifiers.rules.RuleClassifier.entropy (DoubleVector ValorDistClassE)
Definition at line 940 of file RuleClassifier.java.
References moa.core.DoubleVector.getArrayCopy().
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), and moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy().
{
        double entropy = 0.0;
        double sum = 0.0;
        for (double d : ValorDistClassE.getArrayCopy()) {
            if (d > 0.0) {
                entropy -= d * Utils.log2(d);
                sum += d;
                }
            }
        return sum > 0.0 ? (entropy + sum * Utils.log2(sum)) / sum : 0.0;
        }
void moa.classifiers.rules.RuleClassifier.expandeRule (RuleClassification rl, Instance inst, int ruleIndex)
Definition at line 805 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.Predicates.getAttributeValue(), moa.classifiers.rules.Predicates.getSymbol(), moa.classifiers.rules.Predicates.getValue(), moa.options.IntOption.getValue(), moa.classifiers.rules.RuleClassifier.gracePeriodOption, moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), moa.classifiers.rules.RuleClassifier.minEntropyNominalAttrib, moa.classifiers.rules.RuleClassifier.minEntropyTemp, moa.classifiers.rules.RuleClassification.obserClassDistrib, moa.classifiers.rules.RuleClassification.observers, moa.classifiers.rules.RuleClassifier.pred, moa.classifiers.rules.RuleClassification.predicateSet, moa.classifiers.rules.RuleClassifier.ruleSet, moa.classifiers.rules.RuleClassifier.saveBestGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveBestValGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveTheBest, moa.core.DoubleVector.sumOfValues(), moa.classifiers.rules.RuleClassifier.symbol, moa.classifiers.rules.RuleClassifier.theBestAttributes(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
{
        int remainder = (int)Double.MAX_VALUE;
        int numInstanciaObservers = (int)rl.obserClassDistrib.sumOfValues();        // Number of instances for this rule observers.
        this.updateRuleAttribStatistics(inst, rl, ruleIndex);
        if (numInstanciaObservers != 0 && this.gracePeriodOption.getValue() != 0) {
                 remainder = (numInstanciaObservers) % (this.gracePeriodOption.getValue());
            }
        if (remainder == 0){
            this.saveBestValGlobalEntropy = new ArrayList<ArrayList<Double>>();
            this.saveBestGlobalEntropy = new DoubleVector();
            this.saveTheBest = new ArrayList<Double>();
            this.minEntropyTemp = Double.MAX_VALUE;
            this.minEntropyNominalAttrib = Double.MAX_VALUE;
            theBestAttributes(inst, rl.observers);      // The best value of entropy for each attribute.
            boolean HB = checkBestAttrib(numInstanciaObservers, rl.observers, rl.obserClassDistrib);        // Check if the best attribute value is really the best.
            if (HB == true) {
                double attributeValue = this.saveTheBest.get(3);
                double symbol = this.saveTheBest.get(2);        // =, <=, > (0.0, -1.0, 1.0).
                double value = this.saveTheBest.get(0);     // Value of the attribute.
                this.pred = new Predicates(attributeValue, symbol, value);
                int countPred = 0;
                for (int i = 0; i < rl.predicateSet.size(); i++) {      // Checks if the new predicate is not yet in the predicateSet.
                     if (this.pred.getSymbol() == 0.0) {        // Nominal Attribute.
                         if (rl.predicateSet.get(i).getAttributeValue() != this.pred.getAttributeValue()) {
                             countPred = countPred + 1;
                         }
                     }
                     else {
                         if (rl.predicateSet.get(i).getAttributeValue() != this.pred.getAttributeValue()
                                 || rl.predicateSet.get(i).getSymbol() != this.pred.getSymbol()
                                 || rl.predicateSet.get(i).getValue() != this.pred.getValue()) {
                             countPred = countPred+1;
                             }
                         }
                     }
                if (countPred == rl.predicateSet.size()) {
                    int countDifPred = 0;
                    ArrayList<Predicates> predicSetTemp = new ArrayList<Predicates>();
                    for (int x = 0; x < rl.predicateSet.size(); x++) {
                        predicSetTemp.add(rl.predicateSet.get(x));
                     }
                    predicSetTemp.add(this.pred);
                    for (int f = 0; f < this.ruleSet.size(); f++) {
                        int countDifPredTemp = 0;
                        if (this.ruleSet.get(f).predicateSet.size() == predicSetTemp.size()) {
                            for(int x = 0; x < this.ruleSet.get(f).predicateSet.size(); x++) {
                                if (this.ruleSet.get(f).predicateSet.get(x).getAttributeValue() == predicSetTemp.get(x).getAttributeValue()
                                        && this.ruleSet.get(f).predicateSet.get(x).getSymbol() == predicSetTemp.get(x).getSymbol()
                                        && this.ruleSet.get(f).predicateSet.get(x).getValue() == predicSetTemp.get(x).getValue()) {
                                    countDifPredTemp = countDifPredTemp+1;
                                    }
                                }
                            if (countDifPredTemp == predicSetTemp.size()) {
                                break;
                                }else{
                                    countDifPred = countDifPred + 1;
                                    }
                            }else{
                        countDifPred = countDifPred + 1;
                        }
                        }
                    if (countDifPred == this.ruleSet.size()) {
                        if (this.pred.getSymbol() == 0.0) {
                            initializeRuleStatistics(rl, pred, inst);
                            } else if (this.pred.getSymbol() == 1.0) {
                                int countIqualPred = 0;
                                for (int f = 0; f < rl.predicateSet.size(); f++) {
                                    if (this.pred.getAttributeValue() == rl.predicateSet.get(f).getAttributeValue()
                                            && this.pred.getSymbol() == rl.predicateSet.get(f).getSymbol()) {
                                        countIqualPred = countIqualPred + 1;
                                        if (this.pred.getValue() > rl.predicateSet.get(f).getValue()) {
                                            rl.predicateSet.remove(f);
                                            initializeRuleStatistics(rl, pred, inst);
                                            }
                                        }
                                    }
                                if (countIqualPred == 0) {
                                    initializeRuleStatistics(rl, pred, inst);
                                    }
                                }else{
                                 int countIqualPred = 0;
                                 for (int f = 0; f < rl.predicateSet.size(); f++) {
                                     if (this.pred.getAttributeValue() == rl.predicateSet.get(f).getAttributeValue()
                                             && this.pred.getSymbol() == rl.predicateSet.get(f).getSymbol()) {
                                         countIqualPred = countIqualPred + 1;
                                         if (this.pred.getValue() < rl.predicateSet.get(f).getValue()) {
                                             rl.predicateSet.remove(f);
                                             initializeRuleStatistics(rl, pred, inst);
                                             }
                                         }
                                     }
                                 if (countIqualPred == 0) {
                                     initializeRuleStatistics(rl, pred, inst);
                                     }
                                 }
                        }
                    }
                }
            }
        }
void moa.classifiers.rules.RuleClassifier.findBestValEntropy (Node node, DoubleVector classCountL, DoubleVector classCountR, boolean status, double minEntropy, DoubleVector parentCCLeft)
Definition at line 953 of file RuleClassifier.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsRight, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.cut_point, moa.classifiers.rules.RuleClassifier.cutPointTemp, moa.classifiers.rules.RuleClassifier.entropy(), moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.left, moa.classifiers.rules.RuleClassifier.minEntropyTemp, moa.classifiers.rules.RuleClassifier.numClass, moa.core.DoubleVector.numValues(), moa.classifiers.rules.RuleClassifier.PminOption, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.right, moa.classifiers.rules.RuleClassifier.root, moa.classifiers.rules.RuleClassifier.saveBestEntropy, moa.core.DoubleVector.setValue(), moa.core.DoubleVector.sumOfValues(), and moa.classifiers.rules.RuleClassifier.symbol.
Referenced by moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy().
{
        if (this.root != null) {
            if (node != null) {
                int numClass=0;
                DoubleVector classCountLTemp = new DoubleVector();
                DoubleVector classCountRTemp = new DoubleVector();
                DoubleVector parentCCL = new DoubleVector();
                DoubleVector parentCCLParameter = new DoubleVector();
                for (int f = 0; f < node.classCountsLeft.numValues(); f++) {
                    parentCCLParameter.setValue(f, node.classCountsLeft.getValue(f));
                    }
                for (int p = 0; p < parentCCLeft.numValues(); p++) {
                    parentCCL.addToValue(p, parentCCLeft.getValue(p));
                    }
                if (classCountL.numValues() >= classCountR.numValues()) {
                    numClass = classCountL.numValues();
                } else {
                    numClass = classCountR.numValues();
                }
                // Counting the real class count left and the real class count right.
                if (node.cut_point != this.root.cut_point) {
                    for (int i = 0; i < numClass; i++) {
                        if (status == true) {       // Left node.
                            double parentss = parentCCL.getValue(i) - (node.classCountsLeft.getValue(i)
                                    + node.classCountsRight.getValue(i));
                            double left = classCountL.getValue(i)
                                    - node.classCountsRight.getValue(i) - parentss;
                            double right = classCountR.getValue(i)
                                    + node.classCountsRight.getValue(i) + parentss;
                            classCountLTemp.addToValue(i, left);
                            classCountRTemp.addToValue(i, right);
                            }
                        if (status == false) {      // Right node.
                            double left = classCountL.getValue(i)+ node.classCountsLeft.getValue(i);
                            double right = classCountR.getValue(i)- node.classCountsLeft.getValue(i);
                            classCountLTemp.addToValue(i, left);
                            classCountRTemp.addToValue(i, right);
                            }
                        }
                    } else {
                        classCountLTemp = classCountL;
                        classCountRTemp = classCountR;
                        }
                double classCountLSum = classCountLTemp.sumOfValues();
                double classCountRSum = classCountRTemp.sumOfValues();
                double numInst = this.root.classCountsLeft.sumOfValues() + this.root.classCountsRight.sumOfValues();
                // The entropy value for all nodes except for the root.
                if ((classCountLSum > this.PminOption.getValue()*numInst)
                        && (classCountRSum > this.PminOption.getValue() * numInst)) {
                    double classCountLEntropy = entropy( classCountLTemp);   // Entropy of class count left.
                    double classCountREntropy = entropy(classCountRTemp);    // Entropy of class count right
                    if (((classCountLSum / numInst) * classCountLEntropy + (classCountRSum / numInst)* classCountREntropy) <= minEntropy) {
                        this.minEntropyTemp = (classCountLSum / numInst) * classCountLEntropy
                                + (classCountRSum / numInst) * classCountREntropy;
                        this.cutPointTemp = node.cut_point;
                        if (classCountLEntropy <= classCountREntropy) {
                            this.symbol = -1.0;
                            double value = 0.0;
                            double index = 0.0;
                            for (int h = 0; h < numClass; h++) {
                                if (value <= classCountLTemp.getValue(h)) {
                                    value = classCountLTemp.getValue(h);
                                    index = (double)h;
                                    }
                                }
                            this.saveBestEntropy.setValue(0, this.cutPointTemp);
                            this.saveBestEntropy.setValue(1, classCountLEntropy);
                            this.saveBestEntropy.setValue(2, this.symbol);
                            this.saveBestEntropy.setValue(4, index);
                            } else {
                                this.symbol = 1.0;
                                double value = 0.0;
                                double index = 0.0;
                                for (int h = 0; h < numClass; h++) {
                                    if (value <= classCountRTemp.getValue(h)) {
                                        value = classCountRTemp.getValue(h);
                                        index = (double)h;
                                        }
                                    }
                                this.saveBestEntropy.setValue(0, this.cutPointTemp);
                                this.saveBestEntropy.setValue(1, classCountREntropy);
                                this.saveBestEntropy.setValue(2, this.symbol);
                                this.saveBestEntropy.setValue(4, index);
                                }
                        }
                    }
                findBestValEntropy(node.left ,classCountLTemp , classCountRTemp,
                        true, this.minEntropyTemp, parentCCLParameter);
                findBestValEntropy(node.right ,classCountLTemp , classCountRTemp,
                        false, this.minEntropyTemp, parentCCLParameter);
                }
            }
        }
void moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt (AutoExpandVector< DoubleVector > attrib, int attNumValues)
Definition at line 1069 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.entropy(), moa.classifiers.rules.RuleClassifier.minEntropyNominalAttrib, moa.classifiers.rules.RuleClassifier.saveBestEntropyNominalAttrib, moa.core.DoubleVector.setValue(), and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.rules.RuleClassifier.theBestAttributes().
{
        ArrayList<ArrayList<Double>> distClassValue =  new ArrayList<ArrayList<Double>>();
    //  System.out.print("attrib"+attrib+"\n");
        for (int z = 0; z < attrib.size(); z++) {
            distClassValue.add(new ArrayList<Double>());
        }
        for (int v = 0; v < attNumValues; v++) {
            DoubleVector saveVal = new DoubleVector();
            for (int z = 0; z < attrib.size(); z++) {
                if (attrib.get(z) != null) {
                    distClassValue.get(z).add(attrib.get(z).getValue(v));
                } else {
                    distClassValue.get(z).add(0.0);
                }
                if(distClassValue.get(z).get(v).isNaN()) {
                    distClassValue.get(z).add(0.0);
                }
                saveVal.setValue(z, distClassValue.get(z).get(v));
                }
            double sumValue = saveVal.sumOfValues();
            if (sumValue > 0.0) {
                double entropyVal = entropy(saveVal);
                if (entropyVal <= this.minEntropyNominalAttrib) {
                    this.minEntropyNominalAttrib = entropyVal;
                    this.saveBestEntropyNominalAttrib.setValue(0, v);
                    this.saveBestEntropyNominalAttrib.setValue(1, entropyVal);
                    this.saveBestEntropyNominalAttrib.setValue(2, 0.0);
                    }
                }
            }
        }
double [] moa.classifiers.rules.RuleClassifier.firstHit (Instance inst) [protected]
Definition at line 1186 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.oberversDistribProb(), moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifier.getVotesForInstance().
{
        boolean fired = false;
        int countFired = 0;
        double[] votes = new double[this.numClass];
        for (int j = 0; j < this.ruleSet.size(); j++) {
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired + 1;
                for (int z = 0; z < this.numClass; z++) {
                    votes[z] = this.ruleSet.get(j).obserClassDistrib.getValue(z)
                            / this.ruleSet.get(j).obserClassDistrib.sumOfValues();
                    }
                return votes;
                }
            }
        if (countFired > 0) {
            fired = true;
            } else {
                fired = false;
                }
        if (fired == false) {
            votes = oberversDistribProb(inst, this.observedClassDistribution);
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifier.getBestSecondBestEntropy (DoubleVector entropy) [protected]
Definition at line 1141 of file RuleClassifier.java.
References moa.core.DoubleVector.getValue(), and moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib().
{
        double[] entropyValues = new double[2];
        double best = Double.MAX_VALUE;
        double secondBest = Double.MAX_VALUE;
        for (int i = 0; i < entropy.numValues(); i++) {
            if (entropy.getValue(i) < best) {
                secondBest = best;
                best = entropy.getValue(i);
            } else{
                if (entropy.getValue(i) < secondBest) {
                    secondBest = entropy.getValue(i);
                }
            }
            }
        entropyValues[0] = best;
        entropyValues[1] = secondBest;
        return entropyValues;
    }
int moa.classifiers.rules.RuleClassifier.getCountNominalAttrib (ArrayList< Predicates > predicateSet)
Definition at line 532 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
{
        int count = 0;
        for (int i = 0; i < predicateSet.size(); i++) {
            if (predicateSet.get(i).getSymbol() == 0.0) {
                count = count + 1;
                break;
            }
        }
        return count;
    }
void moa.classifiers.rules.RuleClassifier.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 318 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.anomalyDetectionOption, moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.options.FlagOption.isSet, moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised(), moa.classifiers.rules.RuleClassifier.Supervised, and moa.classifiers.rules.RuleClassifier.Unsupervised.
{
        if(this.anomalyDetectionOption.isSet()){
            if(this.Supervised.isSet()){
                this.printAnomaliesSupervised(out, indent); // Get Model Description (Supervised method)
            }else if(this.Unsupervised.isSet()){
                this.printAnomaliesUnsupervised(out, indent); // Get Model Description (Unsupervised method)
            }
        }else{
            this.getModelDescriptionNoAnomalyDetection(out, indent);  // Get Model Description no Anomaly detection
            }
        }
void moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection (StringBuilder out, int indent)
Definition at line 473 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.getCountNominalAttrib(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.instance, moa.classifiers.rules.RuleClassifier.ruleClassIndex, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescription().
                                                                                     { // Get Model Description no Anomaly detection
        StringUtils.appendNewline(out);
        StringUtils.appendIndented(out, indent, "Number of Rule: " + ruleSet.size());
        StringUtils.appendNewline(out);
        StringUtils.appendNewline(out);
        for (int k = 0; k < this.ruleSet.size(); k++) {
            StringUtils.appendIndented(out, indent, "Rule "+(k+1)+": ");
            for (int i = 0; i < this.ruleSet.get(k).predicateSet.size(); i++) {
                if (this.ruleSet.get(k).predicateSet.size() == 1) {
                    if (this.ruleSet.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                        String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                        String val = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSet.get(k).predicateSet.get(i).getValue());
                        StringUtils.appendIndented(out, indent, nam+" = "+val+" --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSet.get(k))));
                        StringUtils.appendNewline(out);
                        } else if (this.ruleSet.get(k).predicateSet.get(i).getSymbol() == -1.0){
                            String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                            StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSet.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)ruleClassIndex.getValue(k)));
                            StringUtils.appendNewline(out);
                            } else {
                                String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSet.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(k)));
                                StringUtils.appendNewline(out);
                                }
                    } else {
                        if (this.ruleSet.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                            String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                            String val = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSet.get(k).predicateSet.get(i).getValue());
                            StringUtils.appendIndented(out, indent, nam+" = "+val+" ");
                            } else if (this.ruleSet.get(k).predicateSet.get(i).getSymbol()==-1.0){
                                String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSet.get(k).predicateSet.get(i).getValue()+" ");
                                } else {
                                    String nam = this.instance.attribute((int)this.ruleSet.get(k).predicateSet.get(i).getAttributeValue()).name();
                                    StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSet.get(k).predicateSet.get(i).getValue()+" ");
                                    }
                        if (i < this.ruleSet.get(k).predicateSet.size() - 1) {
                            StringUtils.appendIndented(out, indent, "and ");
                            } else {
                                int count = getCountNominalAttrib(this.ruleSet.get(k).predicateSet);
                                if ((this.ruleSet.get(k).predicateSet.get(i).getSymbol() == 0.0) || (count != 0)) {
                                    StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSet.get(k))));
                                    StringUtils.appendNewline(out);
                                    } else {
                                        StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(k)));
                                        StringUtils.appendNewline(out);
                                        }
                                }
                        }
                }
            StringUtils.appendNewline(out);
            }
        }
Measurement [] moa.classifiers.rules.RuleClassifier.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 205 of file RuleClassifier.java.
{
        return null;
        }
String moa.classifiers.rules.RuleClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 71 of file RuleClassifier.java.
{
            return "Rule Classifier.";
        }
double moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex (RuleClassification r) [protected]
Definition at line 1162 of file RuleClassifier.java.
References moa.core.DoubleVector.getValue(), moa.core.DoubleVector.numValues(), and moa.classifiers.rules.RuleClassification.obserClassDistrib.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
{
        double maxvalue = 0.0;
        int posMaxValue = 0;
        for (int i = 0; i < r.obserClassDistrib.numValues(); i++) {
            if (r.obserClassDistrib.getValue(i) > maxvalue) {
                maxvalue = r.obserClassDistrib.getValue(i);
                posMaxValue = i;
            }
        }
        return (double)posMaxValue;
    }
double [] moa.classifiers.rules.RuleClassifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.rules.RuleClassifierNBayes.
Definition at line 188 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.firstHit(), moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.predictionFunctionOption, moa.classifiers.rules.RuleClassifier.weightedMax(), and moa.classifiers.rules.RuleClassifier.weightedSum().
{
        double[] votes = new double[this.numClass];
        switch (this.predictionFunctionOption.getChosenIndex()) {
        case 0:
            votes = firstHit(inst);
            break;
        case 1:
            votes = weightedSum(inst);
            break;
        case 2:
            votes = weightedMax(inst);
            break;
          }
        return votes;
    }
double moa.classifiers.rules.RuleClassifier.getWeightSeen ()
Definition at line 216 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
{
        return this.observedClassDistribution.sumOfValues();
      }
void moa.classifiers.rules.RuleClassifier.initializeRuleStatistics (RuleClassification rl, Predicates pred, Instance inst)
Definition at line 554 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassification.attributeMissingValues, moa.classifiers.rules.RuleClassification.attributeStatistics, moa.classifiers.rules.RuleClassification.attributeStatisticsSupervised, moa.classifiers.rules.RuleClassification.instancesSeen, moa.classifiers.rules.RuleClassification.obserClassDistrib, moa.classifiers.rules.RuleClassification.observers, moa.classifiers.rules.RuleClassification.observersGauss, moa.classifiers.rules.RuleClassification.predicateSet, moa.classifiers.rules.RuleClassification.squaredAttributeStatistics, and moa.classifiers.rules.RuleClassification.squaredAttributeStatisticsSupervised.
Referenced by moa.classifiers.rules.RuleClassifier.expandeRule().
{
        rl.predicateSet.add(pred);
        rl.obserClassDistrib=new DoubleVector();
        rl.observers=new AutoExpandVector<AttributeClassObserver>();
        rl.observersGauss=new AutoExpandVector<AttributeClassObserver>();
        rl.instancesSeen = 0;
        rl.attributeStatistics = new DoubleVector();
        rl.squaredAttributeStatistics = new DoubleVector();
        rl.attributeStatisticsSupervised = new ArrayList<ArrayList<Double>>();
        rl.squaredAttributeStatisticsSupervised = new ArrayList<ArrayList<Double>>();
        rl.attributeMissingValues = new DoubleVector();
    }
boolean moa.classifiers.rules.RuleClassifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 528 of file RuleClassifier.java.
{
        return false;
    }
void moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy (Node root)
Definition at line 1049 of file RuleClassifier.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsRight, moa.classifiers.rules.RuleClassifier.entropy(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.minEntropyTemp, moa.core.DoubleVector.numValues(), moa.core.DoubleVector.setValue(), and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.rules.RuleClassifier.theBestAttributes().
{
        if (root != null) {
            DoubleVector parentClassCL = new DoubleVector();
            DoubleVector classCountL = root.classCountsLeft; //class count left
            DoubleVector classCountR = root.classCountsRight; //class count left
            double numInst = root.classCountsLeft.sumOfValues() + root.classCountsRight.sumOfValues();
            double classCountLSum = root.classCountsLeft.sumOfValues();
            double classCountRSum = root.classCountsRight.sumOfValues();
            double classCountLEntropy = entropy(classCountL);
            double classCountREntropy = entropy(classCountR);
            this.minEntropyTemp = ( classCountLSum / numInst) * classCountLEntropy
                    + (classCountRSum / numInst)* classCountREntropy;
            for (int f = 0; f < root.classCountsLeft.numValues(); f++) {
                parentClassCL.setValue(f, root.classCountsLeft.getValue(f));
                }
            findBestValEntropy(root ,classCountL , classCountR, true, this.minEntropyTemp, parentClassCL);
            }
        }
void moa.classifiers.rules.RuleClassifier.manageMemory (int currentByteSize, int maxByteSize)
Definition at line 1304 of file RuleClassifier.java.
{
        // TODO Auto-generated method stub
    }
AttributeClassObserver moa.classifiers.rules.RuleClassifier.newNominalClassObserver () [protected]
Definition at line 1292 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
{
        return new NominalAttributeClassObserver();
    }
AttributeClassObserver moa.classifiers.rules.RuleClassifier.newNumericClassObserver () [protected]
Definition at line 1296 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
{
        return new BinaryTreeNumericAttributeClassObserver();
    }
AttributeClassObserver moa.classifiers.rules.RuleClassifier.newNumericClassObserver2 () [protected]
Definition at line 1300 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
{
        return new GaussianNumericAttributeClassObserver();
            }
double [] moa.classifiers.rules.RuleClassifier.oberversDistribProb (Instance inst, DoubleVector classDistrib) [protected]
Definition at line 1175 of file RuleClassifier.java.
References moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.numClass, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.rules.RuleClassifier.firstHit(), moa.classifiers.rules.RuleClassifier.weightedMax(), and moa.classifiers.rules.RuleClassifier.weightedSum().
{
        double[] votes = new double[this.numClass];
        double sum = classDistrib.sumOfValues();
        for (int z = 0; z < this.numClass; z++) {
            votes[z] = classDistrib.getValue(z) / sum;
            }
        return votes;
        }
void moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised (StringBuilder out, int indent)
Definition at line 402 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.caseAnomalySupervised, moa.classifiers.rules.RuleClassifier.getCountNominalAttrib(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.instance, moa.classifiers.rules.RuleClassifier.round(), moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndexSupervised, moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatisticsSupervised, moa.classifiers.rules.RuleClassifier.ruleClassIndex, and moa.classifiers.rules.RuleClassifier.ruleSetAnomaliesSupervised.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescription().
                                                                    { // Get Model Description (Supervised method)
        StringUtils.appendNewline(out);
        StringUtils.appendIndented(out, indent, "************************SUPERVISED*******************");
        StringUtils.appendNewline(out);
        StringUtils.appendNewline(out);
        for (int k = 0; k < this.ruleSetAnomaliesSupervised.size(); k++) {
            StringUtils.appendIndented(out, indent, "Case: "+this.caseAnomalySupervised.get(k).get(0)+"   Anomaly Score: "+this.caseAnomalySupervised.get(k).get(1)+"%");
            StringUtils.appendNewline(out); //Ver outra parte default
            StringUtils.appendIndented(out, indent, "Rule "+this.ruleAnomaliesIndexSupervised.get(k)+": ");
            for (int i = 0; i < this.ruleSetAnomaliesSupervised.get(k).predicateSet.size(); i++) {
                if (this.ruleSetAnomaliesSupervised.get(k).predicateSet.size() == 1) {
                    if (this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                        String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                        String val = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue());
                        StringUtils.appendIndented(out, indent, nam+" = "+val+" --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSetAnomaliesSupervised.get(k))));
                        StringUtils.appendNewline(out);
                        } else if (this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getSymbol() == -1.0){
                            String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                            StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)ruleClassIndex.getValue(ruleAnomaliesIndexSupervised.get(k)-1)));
                            StringUtils.appendNewline(out);
                            } else {
                                String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(ruleAnomaliesIndexSupervised.get(k)-1)));
                                StringUtils.appendNewline(out);
                                }
                    } else {
                        if (this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                            String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                            String val = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue());
                            StringUtils.appendIndented(out, indent, nam+" = "+val+" ");
                            } else if (this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getSymbol()==-1.0){
                                String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue()+" ");
                                } else {
                                    String nam = this.instance.attribute((int)this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getAttributeValue()).name();
                                    StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getValue()+" ");
                                    }
                        if (i < this.ruleSetAnomaliesSupervised.get(k).predicateSet.size() - 1) {
                            StringUtils.appendIndented(out, indent, "and ");
                            } else {
                                int count = getCountNominalAttrib(this.ruleSetAnomaliesSupervised.get(k).predicateSet);
                                if ((this.ruleSetAnomaliesSupervised.get(k).predicateSet.get(i).getSymbol() == 0.0) || (count != 0)) {
                                    StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSetAnomaliesSupervised.get(k))));
                                    StringUtils.appendNewline(out);
                                    } else {
                                        StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(ruleAnomaliesIndexSupervised.get(k)-1)));
                                        StringUtils.appendNewline(out);
                                        }
                                }
                        }
                }
            for(int z=0; z < this.ruleAttribAnomalyStatisticsSupervised.get(k).size(); z++) {
                if(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).size() == 5){
                String s = String.format ("%.3e", this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(4));
                StringUtils.appendIndented(out, indent, instance.attribute(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(0).intValue()).name()+"="+round(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(1))+"   ("+round(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(2))+" +- "+round(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(3))+")   P="+s);
                StringUtils.appendNewline(out);
            } else {
                String s = String.format ("%.3e", this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(2));
                String val = this.instance.attribute(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(0).intValue()).value(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(1).intValue());
                StringUtils.appendIndented(out, indent, instance.attribute(this.ruleAttribAnomalyStatisticsSupervised.get(k).get(z).get(0).intValue()).name()+"="+ val+"   P="+s);
                StringUtils.appendNewline(out);
            }
        }
        StringUtils.appendNewline(out);
    }
    }
void moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised (StringBuilder out, int indent)
Definition at line 331 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.caseAnomaly, moa.classifiers.rules.RuleClassifier.getCountNominalAttrib(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.instance, moa.classifiers.rules.RuleClassifier.round(), moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndex, moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatistics, moa.classifiers.rules.RuleClassifier.ruleClassIndex, and moa.classifiers.rules.RuleClassifier.ruleSetAnomalies.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescription().
                                                                          { // Get Model Description (Unsupervised method)
        StringUtils.appendNewline(out);
        StringUtils.appendIndented(out, indent, "**********************UNSUPERVISED*****************");
        StringUtils.appendNewline(out);
        StringUtils.appendNewline(out);
        for (int k = 0; k < this.ruleSetAnomalies.size(); k++) {
            StringUtils.appendIndented(out, indent, "Case: "+this.caseAnomaly.get(k).get(0)+"   Anomaly Score: "+this.caseAnomaly.get(k).get(1)+"%");
            StringUtils.appendNewline(out); //Ver outra parte default
            StringUtils.appendIndented(out, indent, "Rule "+this.ruleAnomaliesIndex.get(k)+": ");
            for (int i = 0; i < this.ruleSetAnomalies.get(k).predicateSet.size(); i++) {
                if (this.ruleSetAnomalies.get(k).predicateSet.size() == 1) {
                    if (this.ruleSetAnomalies.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                        String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                        String val = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue());
                        StringUtils.appendIndented(out, indent, nam+" = "+val+" --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSetAnomalies.get(k))));
                        StringUtils.appendNewline(out);
                        } else if (this.ruleSetAnomalies.get(k).predicateSet.get(i).getSymbol() == -1.0){
                            String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                            StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)ruleClassIndex.getValue(ruleAnomaliesIndex.get(k)-1)));
                            StringUtils.appendNewline(out);
                            } else {
                                String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue()+" --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(ruleAnomaliesIndex.get(k)-1)));
                                StringUtils.appendNewline(out);
                                }
                    } else {
                        if (this.ruleSetAnomalies.get(k).predicateSet.get(i).getSymbol() == 0.0) {
                            String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                            String val = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).value((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue());
                            StringUtils.appendIndented(out, indent, nam+" = "+val+" ");
                            } else if (this.ruleSetAnomalies.get(k).predicateSet.get(i).getSymbol()==-1.0){
                                String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                                StringUtils.appendIndented(out, indent, nam+" <= "+this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue()+" ");
                                } else {
                                    String nam = this.instance.attribute((int)this.ruleSetAnomalies.get(k).predicateSet.get(i).getAttributeValue()).name();
                                    StringUtils.appendIndented(out, indent, nam+" > "+this.ruleSetAnomalies.get(k).predicateSet.get(i).getValue()+" ");
                                    }
                        if (i < this.ruleSetAnomalies.get(k).predicateSet.size() - 1) {
                            StringUtils.appendIndented(out, indent, "and ");
                            } else {
                                int count = getCountNominalAttrib(this.ruleSetAnomalies.get(k).predicateSet);
                                if ((this.ruleSetAnomalies.get(k).predicateSet.get(i).getSymbol() == 0.0) || (count != 0)) {
                                    StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)getRuleMajorityClassIndex(this.ruleSetAnomalies.get(k))));
                                    StringUtils.appendNewline(out);
                                    } else {
                                        StringUtils.appendIndented(out, indent, " --> "+this.instance.classAttribute().value((int)this.ruleClassIndex.getValue(ruleAnomaliesIndex.get(k)-1)));
                                        StringUtils.appendNewline(out);
                                        }
                                }
                        }
                }
            for(int z=0; z < this.ruleAttribAnomalyStatistics.get(k).size(); z++) {
                if(this.ruleAttribAnomalyStatistics.get(k).get(z).size() == 5){
                String s = String.format ("%.3e", this.ruleAttribAnomalyStatistics.get(k).get(z).get(4));
                StringUtils.appendIndented(out, indent, instance.attribute(this.ruleAttribAnomalyStatistics.get(k).get(z).get(0).intValue()).name()+"="+round(this.ruleAttribAnomalyStatistics.get(k).get(z).get(1))+"   ("+round(this.ruleAttribAnomalyStatistics.get(k).get(z).get(2))+" +- "+round(this.ruleAttribAnomalyStatistics.get(k).get(z).get(3))+")   P="+s);
                StringUtils.appendNewline(out);
            } else {
                String s = String.format ("%.3e", this.ruleAttribAnomalyStatistics.get(k).get(z).get(2));
                String val = this.instance.attribute(this.ruleAttribAnomalyStatistics.get(k).get(z).get(0).intValue()).value(this.ruleAttribAnomalyStatistics.get(k).get(z).get(1).intValue());
                StringUtils.appendIndented(out, indent, instance.attribute(this.ruleAttribAnomalyStatistics.get(k).get(z).get(0).intValue()).name()+"="+ val+"   P="+s);
                StringUtils.appendNewline(out);
            }
        }
        StringUtils.appendNewline(out);
    }
    }
void moa.classifiers.rules.RuleClassifier.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 210 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, and moa.classifiers.rules.RuleClassifier.observedClassDistribution.
{
        this.observedClassDistribution = new DoubleVector();
        this.attributeObservers = new AutoExpandVector<AttributeClassObserver>();
        this.attributeObserversGauss = new AutoExpandVector<AttributeClassObserver>();
    }
BigDecimal moa.classifiers.rules.RuleClassifier.round (double val) [protected]
Definition at line 544 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
{
        BigDecimal value = new BigDecimal(val);
        if(val!=0.0){
            value = value.setScale(3, BigDecimal.ROUND_DOWN);
        }
        return value;
    }
void moa.classifiers.rules.RuleClassifier.theBestAttributes (Instance instance, AutoExpandVector< AttributeClassObserver > observersParameter)
Definition at line 907 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.classifiers.rules.RuleClassifier.minEntropyNominalAttrib, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.rules.RuleClassifier.root, moa.classifiers.rules.RuleClassifier.saveBestEntropy, moa.classifiers.rules.RuleClassifier.saveBestEntropyNominalAttrib, moa.classifiers.rules.RuleClassifier.saveBestGlobalEntropy, moa.classifiers.rules.RuleClassifier.saveBestValGlobalEntropy, and moa.core.DoubleVector.setValue().
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), and moa.classifiers.rules.RuleClassifier.expandeRule().
{
        for(int z = 0; z < instance.numAttributes() - 1; z++){
            if(!instance.isMissing(z)){
            int instAttIndex = modelAttIndexToInstanceAttIndex(z, instance);
            ArrayList<Double> attribBest = new ArrayList<Double>();
            if(instance.attribute(instAttIndex).isNominal()){
                this.minEntropyNominalAttrib=Double.MAX_VALUE;
                AutoExpandVector<DoubleVector> attribNominal = ((NominalAttributeClassObserver)observersParameter.get(z)).attValDistPerClass;
                findBestValEntropyNominalAtt(attribNominal, instance.attribute(z).numValues());     // The best value (lowest entropy) of a nominal attribute.
                attribBest.add(this.saveBestEntropyNominalAttrib.getValue(0));
                attribBest.add(this.saveBestEntropyNominalAttrib.getValue(1));
                attribBest.add(this.saveBestEntropyNominalAttrib.getValue(2));
                this.saveBestValGlobalEntropy.add(attribBest);
                this.saveBestGlobalEntropy.setValue(z, this.saveBestEntropyNominalAttrib.getValue(1));
                } else {
                    this.root=((BinaryTreeNumericAttributeClassObserver)observersParameter.get(z)).root;
                    mainFindBestValEntropy(this.root);      // The best value (lowest entropy) of a numeric attribute.
                    attribBest.add(this.saveBestEntropy.getValue(0));
                    attribBest.add(this.saveBestEntropy.getValue(1));
                    attribBest.add(this.saveBestEntropy.getValue(2));
                    attribBest.add(this.saveBestEntropy.getValue(4));
                    this.saveBestValGlobalEntropy.add(attribBest);
                    this.saveBestGlobalEntropy.setValue(z, this.saveBestEntropy.getValue(1));
                    }
            }else{
                 double value = Double.MAX_VALUE;
                 this.saveBestGlobalEntropy.setValue(z, value);
                 }
            }
    }
void moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 221 of file RuleClassifier.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.rules.RuleClassifier.anomalyDetectionOption, moa.classifiers.rules.RuleClassifier.anomalyNumInstThresholdOption, moa.classifiers.rules.RuleClassifier.anomalyProbabilityThresholdOption, moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.classifiers.rules.RuleClassifier.instance, moa.options.FlagOption.isSet, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.rules.RuleClassifier.newNominalClassObserver(), moa.classifiers.rules.RuleClassifier.newNumericClassObserver(), moa.classifiers.rules.RuleClassifier.newNumericClassObserver2(), moa.classifiers.rules.RuleClassifier.numAttributes, moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.numInstance, moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), moa.classifiers.rules.RuleClassifier.observedClassDistribution, moa.classifiers.rules.RuleClassifier.orderedRulesOption, moa.classifiers.rules.RuleClassifier.ruleSet, moa.classifiers.rules.RuleClassifier.Supervised, and moa.classifiers.rules.RuleClassifier.Unsupervised.
{
        int countRuleFiredTrue = 0;
        boolean ruleFired = false;
        this.instance = inst;
        this.numAttributes = instance.numAttributes()-1;
        this.numClass = instance.numClasses();
        this.numInstance = numInstance + 1;
        int conta1=0;
        for (int j = 0; j < ruleSet.size(); j++) {
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countRuleFiredTrue = countRuleFiredTrue + 1;
                double anomaly = 0.0;
                if(this.Supervised.isSet()){
                    anomaly = computeAnomalySupervised(this.ruleSet.get(j), j, inst); // compute anomaly (Supervised method)
                }else if(this.Unsupervised.isSet()){
                    anomaly = computeAnomalyUnsupervised(this.ruleSet.get(j), j, inst); // compute anomaly (Unsupervised method)
                }
                if(anomaly >= this.anomalyProbabilityThresholdOption.getValue()){
                conta1 =conta1+1;
                }
            //  System.out.print(numInstance+";"+anomaly+"\n");
                 try {
                      File dir = new File("SeaAnomaliesUnsupervised.txt");
                      FileWriter fileWriter = new FileWriter(dir, true);
                      PrintWriter printWriter = new PrintWriter(fileWriter);
                      printWriter.println(numInstance+";"+anomaly);
                      printWriter.flush();
                      printWriter.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                 if((this.ruleSet.get(j).instancesSeen <= this.anomalyNumInstThresholdOption.getValue()) || (anomaly < this.anomalyProbabilityThresholdOption.getValue() && this.anomalyDetectionOption.isSet()) ||!this.anomalyDetectionOption.isSet()){
                this.ruleSet.get(j).obserClassDistrib.addToValue((int) inst.classValue(), inst.weight());
                for (int i = 0; i < inst.numAttributes() - 1; i++) {
                    int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                    if(!inst.isMissing(instAttIndex)){
                    AttributeClassObserver obs = this.ruleSet.get(j).observers.get(i);      // Nominal and binary tree.
                    AttributeClassObserver obsGauss = this.ruleSet.get(j).observersGauss.get(i);        // Gaussian.
                    if (obs == null) {
                        obs = inst.attribute(instAttIndex).isNominal() ? newNominalClassObserver()
                                : newNumericClassObserver();
                        this.ruleSet.get(j).observers.set(i, obs);
                    }
                    if (obsGauss == null) {
                        obsGauss = inst.attribute(instAttIndex).isNumeric() ? newNumericClassObserver2():null;
                        this.ruleSet.get(j).observersGauss.set(i, obsGauss);
                    }
                    obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
                    if (inst.attribute(instAttIndex).isNumeric()) {
                        obsGauss.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
                    }
                }
                }
                expandeRule(this.ruleSet.get(j), inst, j); // This function expands the rule
                }
                if (this.orderedRulesOption.isSet()) {  // Ordered rules
                    break;
                    }
                }
            }
        if (countRuleFiredTrue > 0) {
            ruleFired = true;
            }else{
                ruleFired = false;
            }
        if (ruleFired == false) { //If none of the rules cover the example update sufficient statistics of the default rule
            this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                if(!inst.isMissing(instAttIndex)){
                AttributeClassObserver obs = this.attributeObservers.get(i);
                AttributeClassObserver obsGauss = this.attributeObserversGauss.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? newNominalClassObserver()
                            : newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                    }
                if (obsGauss == null) {
                    obsGauss = inst.attribute(instAttIndex).isNumeric() ? newNumericClassObserver2():null;
                    this.attributeObserversGauss.set(i, obsGauss);
                    }
                obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
                if (inst.attribute(instAttIndex).isNumeric()) {
                    obsGauss.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
                    }
                }
            }
            createRule(inst); //This function creates a rule
            }
        }
void moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics (Instance inst, RuleClassification rl, int ruleIndex)
Definition at line 568 of file RuleClassifier.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.rules.RuleClassification.attributeMissingValues, moa.classifiers.rules.RuleClassification.attributeStatistics, moa.classifiers.rules.RuleClassification.attributeStatisticsSupervised, moa.classifiers.rules.RuleClassifier.instance, moa.classifiers.rules.RuleClassification.instancesSeen, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.rules.RuleClassification.squaredAttributeStatistics, and moa.classifiers.rules.RuleClassification.squaredAttributeStatisticsSupervised.
Referenced by moa.classifiers.rules.RuleClassifier.expandeRule().
{
        rl.instancesSeen++;
        if(rl.squaredAttributeStatisticsSupervised.size() == 0 && rl.attributeStatisticsSupervised.size() == 0){
            for (int s = 0; s < inst.numAttributes() -1; s++) {
                ArrayList<Double> temp1 = new ArrayList<Double>();
                ArrayList<Double> temp2 = new ArrayList<Double>();
                rl.attributeStatisticsSupervised.add(temp1);
                rl.squaredAttributeStatisticsSupervised.add(temp2);
                int instAttIndex = modelAttIndexToInstanceAttIndex(s, inst);
                if(instance.attribute(instAttIndex).isNumeric()){
                    for(int i=0; i<inst.numClasses(); i++){
                        rl.attributeStatisticsSupervised.get(s).add(0.0);
                        rl.squaredAttributeStatisticsSupervised.get(s).add(1.0);
                    }
                    }
                }
            }
        for (int s = 0; s < inst.numAttributes() -1; s++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(s, inst);
            if(!inst.isMissing(instAttIndex)){
            if(instance.attribute(instAttIndex).isNumeric()){
            rl.attributeStatistics.addToValue(s, inst.value(s));
            rl.squaredAttributeStatistics.addToValue(s, inst.value(s) * inst.value(s));
            double sumValue = rl.attributeStatisticsSupervised.get(s).get((int)inst.classValue()) + inst.value(s);
            rl.attributeStatisticsSupervised.get(s).set((int)inst.classValue(), sumValue);
            double squaredSumvalue = rl.squaredAttributeStatisticsSupervised.get(s).get((int)inst.classValue()) + (inst.value(s) * inst.value(s));
            rl.squaredAttributeStatisticsSupervised.get(s).set((int)inst.classValue(), squaredSumvalue);
            }
            }else{
                rl.attributeMissingValues.addToValue(s, 1);
                }
            }
        }
double [] moa.classifiers.rules.RuleClassifier.weightedMax (Instance inst) [protected]
Definition at line 1212 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.oberversDistribProb(), moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifier.getVotesForInstance().
{
        int countFired = 0;
        boolean fired = false;
        double highest = 0.0;
        double[] votes = new double[this.numClass];
        ArrayList<Double> ruleSetVotes = new ArrayList<Double>();
        ArrayList<ArrayList<Double>> majorityProb = new ArrayList<ArrayList<Double>>();
        for (int j = 0; j < this.ruleSet.size(); j++) {
            ArrayList<Double> ruleProb = new ArrayList<Double>();
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired+1;
                for (int z = 0; z < this.numClass; z++) {
                    ruleSetVotes.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                    ruleProb.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                    }
                majorityProb.add(ruleProb);
                }
            }
        if (countFired > 0) {
            fired = true;
            Collections.sort(ruleSetVotes);
            highest = ruleSetVotes.get(ruleSetVotes.size() - 1);
            for (int t = 0; t < majorityProb.size(); t++) {
                 for(int m = 0; m < majorityProb.get(t).size(); m++) {
                     if (majorityProb.get(t).get(m) == highest) {
                         for (int h = 0; h < majorityProb.get(t).size(); h++) {
                             votes[h] = majorityProb.get(t).get(h);
                             }
                         break;
                         }
                     }
                 }
            } else {
                fired = false;
                }
        if (fired == false) {
            votes = oberversDistribProb(inst, this.observedClassDistribution);
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifier.weightedSum (Instance inst) [protected]
Definition at line 1254 of file RuleClassifier.java.
References moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.oberversDistribProb(), moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifier.getVotesForInstance().
{
        boolean fired = false;
        int countFired = 0;
        double[] votes = new double[this.numClass];
        ArrayList<Double> weightSum = new ArrayList<Double>();
        ArrayList<ArrayList<Double>> majorityProb = new ArrayList<ArrayList<Double>>();
        for (int j = 0; j < this.ruleSet.size(); j++) {
            ArrayList<Double> ruleProb = new ArrayList<Double>();
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired + 1;
                for (int z = 0; z < this.numClass; z++) {
                    ruleProb.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                    }
                majorityProb.add(ruleProb);
                }
            }
        if (countFired > 0) {
            fired = true;
            for (int m = 0; m < majorityProb.get(0).size(); m++) {
                double sum = 0.0;
                for (int t = 0; t < majorityProb.size(); t++){
                    sum = sum + majorityProb.get(t).get(m);
                    }
                weightSum.add(sum);
                }
            for (int h = 0; h < weightSum.size(); h++) {
                votes[h] = weightSum.get(h) / majorityProb.size();
                }
            } else {
                fired = false;
                }
        if (fired == false) {
            votes = oberversDistribProb(inst, this.observedClassDistribution);
            }
        return votes;
        }
Member Data Documentation
FlagOption moa.classifiers.rules.RuleClassifier.anomalyDetectionOption
Initial value:
 new FlagOption("anomalyDetection", 'u',
                "anomaly Detection.")
Definition at line 176 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.getModelDescription(), and moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
IntOption moa.classifiers.rules.RuleClassifier.anomalyNumInstThresholdOption
Initial value:
 new IntOption(
                "anomalyThreshold",
                'i',
                "The threshold value to be used in the anomaly detection.",
                15, 0, Integer.MAX_VALUE)
Definition at line 158 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.RuleClassifier.anomalyProbabilityThresholdOption
Initial value:
 new FloatOption(
                "anomalyprobabilityThreshold",
                'o',
                "The threshold value.",
                0.99, 0.0, 1.0)
Definition at line 146 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
AutoExpandVector<AttributeClassObserver> moa.classifiers.rules.RuleClassifier.attributeObservers [protected]
Definition at line 77 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifier.resetLearningImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
AutoExpandVector<AttributeClassObserver> moa.classifiers.rules.RuleClassifier.attributeObserversGauss [protected]
Definition at line 79 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifier.resetLearningImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
ArrayList<ArrayList<Integer> > moa.classifiers.rules.RuleClassifier.caseAnomaly = new ArrayList<ArrayList<Integer>>() [protected]
Definition at line 102 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
ArrayList<ArrayList<Integer> > moa.classifiers.rules.RuleClassifier.caseAnomalySupervised = new ArrayList<ArrayList<Integer>>() [protected]
Definition at line 110 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised().
double moa.classifiers.rules.RuleClassifier.cutPointTemp = 0.0 [package]
Definition at line 116 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy().
IntOption moa.classifiers.rules.RuleClassifier.gracePeriodOption
Initial value:
 new IntOption(
                "gracePeriod",'g', "The number of instances a leaf should observe between split attempts.",
                 200, 0, Integer.MAX_VALUE)
Definition at line 164 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), and moa.classifiers.rules.RuleClassifier.expandeRule().
Instance moa.classifiers.rules.RuleClassifier.instance [protected]
Definition at line 75 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
double moa.classifiers.rules.RuleClassifier.minEntropyNominalAttrib = Double.MAX_VALUE [package]
Definition at line 118 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
double moa.classifiers.rules.RuleClassifier.minEntropyTemp = Double.MAX_VALUE [package]
Definition at line 114 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), and moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy().
int moa.classifiers.rules.RuleClassifier.numAttributes = 0 [package]
Definition at line 124 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
int moa.classifiers.rules.RuleClassifier.numClass = 0 [package]
Definition at line 126 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.firstHit(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifierNBayes.getVotesForInstance(), moa.classifiers.rules.RuleClassifier.getVotesForInstance(), moa.classifiers.rules.RuleClassifier.oberversDistribProb(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.weightedMax(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), moa.classifiers.rules.RuleClassifier.weightedSum(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
int moa.classifiers.rules.RuleClassifier.numInstance = 0 [package]
Definition at line 122 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
DoubleVector moa.classifiers.rules.RuleClassifier.observedClassDistribution [protected]
Definition at line 81 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.firstHit(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifier.getWeightSeen(), moa.classifiers.rules.RuleClassifier.resetLearningImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.weightedMax(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), moa.classifiers.rules.RuleClassifier.weightedSum(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
FlagOption moa.classifiers.rules.RuleClassifier.orderedRulesOption
Initial value:
 new FlagOption("orderedRules", 'r',
                "orderedRules.")
Definition at line 173 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.RuleClassifier.PminOption
Initial value:
 new FloatOption("Pmin",
                'p', "Percentage of the total number of example seen in the node.",
                 0.1, 0.0, 1.0)
Definition at line 132 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy().
Predicates moa.classifiers.rules.RuleClassifier.pred [package]
Definition at line 130 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), and moa.classifiers.rules.RuleClassifier.expandeRule().
MultiChoiceOption moa.classifiers.rules.RuleClassifier.predictionFunctionOption
Initial value:
 new MultiChoiceOption(
                "predictionFunctionOption", 'z', "The prediction function to use.", new String[]{
                "firstHit", "weightedSum", "weightedMax"}, new String[]{
                "first Hit",  "weighted Sum", "weighted Max"}, 0)
Definition at line 168 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.getVotesForInstance().
FloatOption moa.classifiers.rules.RuleClassifier.probabilityThresholdOption
Initial value:
 new FloatOption(
                "probabilityThreshold",
                'k',
                "The threshold value.",
                0.10, 0.0, 1.0)
Definition at line 152 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised().
Node moa.classifiers.rules.RuleClassifier.root [package]
Definition at line 128 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
ArrayList<Integer> moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndex = new ArrayList<Integer>() [protected]
Definition at line 100 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
ArrayList<Integer> moa.classifiers.rules.RuleClassifier.ruleAnomaliesIndexSupervised = new ArrayList<Integer>() [protected]
Definition at line 108 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised().
ArrayList<ArrayList<ArrayList<Double> > > moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatistics = new ArrayList<ArrayList<ArrayList<Double>>>() [protected]
Definition at line 104 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
ArrayList<ArrayList<ArrayList<Double> > > moa.classifiers.rules.RuleClassifier.ruleAttribAnomalyStatisticsSupervised = new ArrayList<ArrayList<ArrayList<Double>>>() [protected]
Definition at line 112 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised().
DoubleVector moa.classifiers.rules.RuleClassifier.ruleClassIndex = new DoubleVector() [protected]
Definition at line 87 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
ArrayList<RuleClassification> moa.classifiers.rules.RuleClassifier.ruleSet = new ArrayList<RuleClassification>() [protected]
Definition at line 95 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.firstHit(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.weightedMax(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), moa.classifiers.rules.RuleClassifier.weightedSum(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
ArrayList<RuleClassification> moa.classifiers.rules.RuleClassifier.ruleSetAnomalies = new ArrayList<RuleClassification>() [protected]
Definition at line 98 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised().
ArrayList<RuleClassification> moa.classifiers.rules.RuleClassifier.ruleSetAnomaliesSupervised = new ArrayList<RuleClassification>() [protected]
Definition at line 106 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), and moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised().
DoubleVector moa.classifiers.rules.RuleClassifier.saveBestEntropy = new DoubleVector() [protected]
Definition at line 83 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
DoubleVector moa.classifiers.rules.RuleClassifier.saveBestEntropyNominalAttrib = new DoubleVector() [protected]
Definition at line 85 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
DoubleVector moa.classifiers.rules.RuleClassifier.saveBestGlobalEntropy = new DoubleVector() [protected]
Definition at line 89 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
ArrayList<ArrayList<Double> > moa.classifiers.rules.RuleClassifier.saveBestValGlobalEntropy = new ArrayList<ArrayList<Double>>() [protected]
Definition at line 91 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), and moa.classifiers.rules.RuleClassifier.theBestAttributes().
ArrayList<Double> moa.classifiers.rules.RuleClassifier.saveTheBest = new ArrayList<Double>() [protected]
Definition at line 93 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.createRule(), and moa.classifiers.rules.RuleClassifier.expandeRule().
final long moa.classifiers.rules.RuleClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.rules.RuleClassifierNBayes.
Definition at line 68 of file RuleClassifier.java.
FloatOption moa.classifiers.rules.RuleClassifier.splitConfidenceOption
Initial value:
 new FloatOption(
                "splitConfidence",
                'c',
                "The allowable error in split decision, values closer to 0 will take longer to decide.",
                0.000001, 0.0, 1.0)
Definition at line 136 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib().
FlagOption moa.classifiers.rules.RuleClassifier.Supervised
Initial value:
 new FlagOption("supervised", 'n',
            "supervised.")
Definition at line 179 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescription(), and moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
double moa.classifiers.rules.RuleClassifier.symbol = 0.0 [package]
Definition at line 120 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), and moa.classifiers.rules.RuleClassifier.findBestValEntropy().
FloatOption moa.classifiers.rules.RuleClassifier.tieThresholdOption
Initial value:
 new FloatOption("tieThreshold",
                't', "Threshold below which a split will be forced to break ties.",
                 0.05, 0.0, 1.0)
Definition at line 142 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.checkBestAttrib().
FlagOption moa.classifiers.rules.RuleClassifier.Unsupervised
Initial value:
 new FlagOption("unsupervised", 'm',
            "unsupervised.")
Definition at line 182 of file RuleClassifier.java.
Referenced by moa.classifiers.rules.RuleClassifier.getModelDescription(), and moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/RuleClassifier.java