MOA: moa.classifiers.meta.OzaBagASHTTest Class Reference
moa.classifiers.meta.OzaBagASHTTest Class Reference
Tests the OzaBagASHT classifier.
Public Member Functions
OzaBagASHTTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the OzaBagASHT classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 35 of file OzaBagASHTTest.java.
Constructor & Destructor Documentation
moa.classifiers.meta.OzaBagASHTTest.OzaBagASHTTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 43 of file OzaBagASHTTest.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.meta.OzaBagASHTTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleClassifierTestCase.
Definition at line 54 of file OzaBagASHTTest.java.
References moa.classifiers.meta.OzaBag.baseLearnerOption, and moa.options.ClassOption.setValueViaCLIString().
{
    OzaBagASHT[]    result;
    result    = new OzaBagASHT[1];
    result[0] = new OzaBagASHT();
    result[0].baseLearnerOption.setValueViaCLIString("trees.ASHoeffdingTree");
    return result;
  }
static void moa.classifiers.meta.OzaBagASHTTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 77 of file OzaBagASHTTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.meta.OzaBagASHTTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.meta.OzaBagASHTTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 68 of file OzaBagASHTTest.java.
Referenced by moa.classifiers.meta.OzaBagASHTTest.main().
{
    return new TestSuite(OzaBagASHTTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/meta/OzaBagASHTTest.java