MOA: moa.options.FloatOption Class Reference
moa.options.FloatOption Class Reference
Float option.
Public Member Functions
FloatOption (String name, char cliChar, String purpose, double defaultVal)
FloatOption (String name, char cliChar, String purpose, double defaultVal, double minVal, double maxVal)
void setValue (double v)
double getValue ()
double getMinValue ()
double getMaxValue ()
String getDefaultCLIString ()
Gets the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static double cliStringToDouble (String s)
static String doubleToCLIString (double d)
Protected Attributes
double currentVal
double defaultVal
double minVal
double maxVal
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Float option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file FloatOption.java.
Constructor & Destructor Documentation
moa.options.FloatOption.FloatOption (String name, char cliChar, String purpose, double defaultVal)
Definition at line 44 of file FloatOption.java.
{
        this(name, cliChar, purpose, defaultVal, Double.NEGATIVE_INFINITY,
                Double.POSITIVE_INFINITY);
    }
moa.options.FloatOption.FloatOption (String name, char cliChar, String purpose, double defaultVal, double minVal, double maxVal)
Definition at line 50 of file FloatOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        this.defaultVal = defaultVal;
        this.minVal = minVal;
        this.maxVal = maxVal;
        resetToDefault();
    }
Member Function Documentation
static double moa.options.FloatOption.cliStringToDouble (String s) [static]
Definition at line 100 of file FloatOption.java.
Referenced by moa.options.FloatOption.setValueViaCLIString().
{
        return Double.parseDouble(s.trim());
    }
static String moa.options.FloatOption.doubleToCLIString (double d) [static]
Definition at line 104 of file FloatOption.java.
Referenced by moa.options.FloatOption.getDefaultCLIString(), and moa.options.FloatOption.getValueAsCLIString().
{
        return Double.toString(d);
    }
String moa.options.FloatOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 86 of file FloatOption.java.
References moa.options.FloatOption.defaultVal, and moa.options.FloatOption.doubleToCLIString().
{
        return doubleToCLIString(this.defaultVal);
    }
JComponent moa.options.FloatOption.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Reimplemented from moa.options.AbstractOption.
Definition at line 109 of file FloatOption.java.
{
        return new FloatOptionEditComponent(this);
    }
double moa.options.FloatOption.getMaxValue ()
Definition at line 81 of file FloatOption.java.
References moa.options.FloatOption.maxVal.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), moa.gui.FloatOptionEditComponent.floatValueToSliderValue(), and moa.gui.FloatOptionEditComponent.sliderValueToFloatValue().
{
        return this.maxVal;
    }
double moa.options.FloatOption.getMinValue ()
Definition at line 77 of file FloatOption.java.
References moa.options.FloatOption.minVal.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), moa.gui.FloatOptionEditComponent.floatValueToSliderValue(), and moa.gui.FloatOptionEditComponent.sliderValueToFloatValue().
{
        return this.minVal;
    }
double moa.options.FloatOption.getValue ()
Definition at line 73 of file FloatOption.java.
References moa.options.FloatOption.currentVal.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), moa.clusterers.ClusterGenerator.alterClustering(), moa.classifiers.rules.RuleClassifier.checkBestAttrib(), moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.meta.DACC.discardModel(), moa.tasks.RunTasks.doMainTask(), moa.tasks.RunStreamTasks.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.clusterers.denstream.WithDBSCAN.getClusteringResult(), moa.streams.clustering.ClusteringStream.getDecayThreshold(), moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getMeritOfSplit(), moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.rules.AbstractAMRules.isAnomaly(), moa.clusterers.ClusterGenerator.joinClusters(), moa.classifiers.active.ActiveClassifier.labelFixed(), moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.active.ActiveClassifier.labelVar(), moa.classifiers.core.driftdetection.HDDM_A_Test.meanDecr(), moa.classifiers.rules.AMRulesRegressor.newRule(), moa.streams.generators.RandomRBFGeneratorDrift.nextInstance(), moa.streams.generators.AgrawalGenerator.nextInstance(), moa.streams.filters.ReplacingMissingValuesFilter.nextInstance(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.streams.generators.cd.GradualChangeGenerator.nextValue(), moa.streams.generators.AgrawalGenerator.perturbValue(), moa.streams.ConceptDriftStream.prepareForUseImpl(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.evaluation.FadingFactorClassificationPerformanceEvaluator.reset(), moa.evaluation.EWMAClassificationPerformanceEvaluator.reset(), moa.clusterers.outliers.AnyOut.AnyOutCore.resetLearning(), moa.classifiers.core.driftdetection.PageHinkleyDM.resetLearning(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.classifiers.core.driftdetection.GeometricMovingAverageDM.resetLearning(), moa.classifiers.core.driftdetection.EWMAChartDM.resetLearning(), moa.classifiers.core.driftdetection.CusumDM.resetLearning(), moa.classifiers.core.driftdetection.ADWINChangeDetector.resetLearning(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), moa.clusterers.CobWeb.resetLearningImpl(), moa.classifiers.rules.functions.FadingTargetMean.resetLearningImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.meta.OCBoost.resetLearningImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.functions.SPegasos.resetLearningImpl(), moa.classifiers.functions.SGDMultiClass.resetLearningImpl(), moa.classifiers.functions.SGD.resetLearningImpl(), moa.streams.generators.multilabel.MetaMultilabelGenerator.restart(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), moa.classifiers.rules.functions.TargetMean.TargetMean(), moa.classifiers.meta.DACC.trainAndClassify(), moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl(), moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl(), moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron(), moa.classifiers.meta.RandomRules.transformInstance(), and moa.classifiers.meta.DACC.updateEvaluationWindow().
{
        return this.currentVal;
    }
String moa.options.FloatOption.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Definition at line 91 of file FloatOption.java.
References moa.options.FloatOption.currentVal, and moa.options.FloatOption.doubleToCLIString().
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString().
{
        return doubleToCLIString(this.currentVal);
    }
void moa.options.FloatOption.setValue (double v)
Definition at line 59 of file FloatOption.java.
References moa.options.FloatOption.currentVal, moa.options.AbstractOption.getName(), moa.options.FloatOption.maxVal, and moa.options.FloatOption.minVal.
Referenced by moa.gui.FloatOptionEditComponent.applyState(), moa.classifiers.trees.HoeffdingTreeTest.getRegressionClassifierSetups(), moa.clusterers.outliers.SimpleCOD.Test.main(), and moa.options.FloatOption.setValueViaCLIString().
{
        if (v < this.minVal) {
            throw new IllegalArgumentException("Option " + getName()
                    + " cannot be less than " + this.minVal
                    + ", out of range: " + v);
        }
        if (v > this.maxVal) {
            throw new IllegalArgumentException("Option " + getName()
                    + " cannot be greater than " + this.maxVal
                    + ", out of range: " + v);
        }
        this.currentVal = v;
    }
void moa.options.FloatOption.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Definition at line 96 of file FloatOption.java.
References moa.options.FloatOption.cliStringToDouble(), and moa.options.FloatOption.setValue().
{
        setValue(cliStringToDouble(s));
    }
Member Data Documentation
double moa.options.FloatOption.currentVal [protected]
Definition at line 36 of file FloatOption.java.
Referenced by moa.options.FloatOption.getValue(), moa.options.FloatOption.getValueAsCLIString(), and moa.options.FloatOption.setValue().
double moa.options.FloatOption.defaultVal [protected]
Definition at line 38 of file FloatOption.java.
Referenced by moa.options.FloatOption.getDefaultCLIString().
double moa.options.FloatOption.maxVal [protected]
Definition at line 42 of file FloatOption.java.
Referenced by moa.options.FloatOption.getMaxValue(), and moa.options.FloatOption.setValue().
double moa.options.FloatOption.minVal [protected]
Definition at line 40 of file FloatOption.java.
Referenced by moa.options.FloatOption.getMinValue(), and moa.options.FloatOption.setValue().
final long moa.options.FloatOption.serialVersionUID = 1L [static, private]
Definition at line 34 of file FloatOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/FloatOption.java