MOA: moa.gui.ClassOptionWithNamesSelectionPanel Class Reference
moa.gui.ClassOptionWithNamesSelectionPanel Class Reference
Public Member Functions
ClassOptionWithNamesSelectionPanel (Class<?> requiredType, String initialCLIString, String nullString, String[] classNames)
Class<?>[] findSuitableClasses (Class<?> requiredType, String[] classNames)
String getChosenObjectCLIString (Class<?> requiredType)
void classChoiceChanged (Object chosen)
Static Public Member Functions
static String showSelectClassDialog (Component parent, String title, Class<?> requiredType, String initialCLIString, String nullString, String[] classNames)
Protected Attributes
JComboBox classChoiceBox
JComponent chosenObjectEditor
Object chosenObject
Private Attributes
boolean debug = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 31 of file ClassOptionWithNamesSelectionPanel.java.
Constructor & Destructor Documentation
moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel (Class<?> requiredType, String initialCLIString, String nullString, String[] classNames)
Definition at line 41 of file ClassOptionWithNamesSelectionPanel.java.
References moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceBox, moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged(), moa.gui.ClassOptionWithNamesSelectionPanel.debug, and moa.gui.ClassOptionWithNamesSelectionPanel.findSuitableClasses().
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.showSelectClassDialog().
{
        Class<?>[] classesFound = findSuitableClasses(requiredType, classNames);
        if (debug) {
            System.out.print("[ClassOptionWithNamesSelectionPanel] classNames = ");
            for (String s : classNames) {
                System.out.print(s + ", ");
            }
            System.out.println();
            System.out.print("[ClassOptionWithNamesSelectionPanel] classesFound = ");
            for (Class<?> cl : classesFound) {
                System.out.print(cl.getSimpleName() + ", ");
            }
            System.out.println();
        }
        this.classChoiceBox = new JComboBox(classesFound);
        setLayout(new BorderLayout());
        add(this.classChoiceBox, BorderLayout.NORTH);
        Object initialObject = null;
        try {
            initialObject = ClassOption.cliStringToObject(initialCLIString,
                    requiredType, null);
        } catch (Exception ignored) {
            // ignore exception
        }
        if (initialObject != null) {
            this.classChoiceBox.setSelectedItem(initialObject.getClass());
            classChoiceChanged(initialObject);
        } else {
            try {
                Object chosen = ((Class<?>) ClassOptionWithNamesSelectionPanel.this.classChoiceBox.getSelectedItem()).newInstance();
                classChoiceChanged(chosen);
            } catch (Exception ex) {
                GUIUtils.showExceptionDialog(ClassOptionWithNamesSelectionPanel.this,
                        "Problem", ex);
            }
        }
        this.classChoiceBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                try {
                    Object chosen = ((Class<?>) ClassOptionWithNamesSelectionPanel.this.classChoiceBox.getSelectedItem()).newInstance();
                    classChoiceChanged(chosen);
                } catch (Exception ex) {
                    GUIUtils.showExceptionDialog(
                            ClassOptionWithNamesSelectionPanel.this, "Problem", ex);
                }
            }
        });
    }
Member Function Documentation
void moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged (Object chosen)
Definition at line 145 of file ClassOptionWithNamesSelectionPanel.java.
References moa.gui.ClassOptionWithNamesSelectionPanel.chosenObject, moa.gui.ClassOptionWithNamesSelectionPanel.chosenObjectEditor, moa.options.OptionHandler.getOptions(), and moa.options.OptionHandler.getPurposeString().
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel().
{
        this.chosenObject = chosen;
        JComponent newChosenObjectEditor = null;
        if (this.chosenObject instanceof OptionHandler) {
            OptionHandler chosenOptionHandler = (OptionHandler) this.chosenObject;
            newChosenObjectEditor = new OptionsConfigurationPanel(
                    chosenOptionHandler.getPurposeString(), chosenOptionHandler.getOptions());
        }
        if (this.chosenObjectEditor != null) {
            remove(this.chosenObjectEditor);
        }
        this.chosenObjectEditor = newChosenObjectEditor;
        if (this.chosenObjectEditor != null) {
            add(this.chosenObjectEditor, BorderLayout.CENTER);
        }
        Component component = this;
        while ((component != null) && !(component instanceof JDialog)) {
            component = component.getParent();
        }
        if (component != null) {
            Window window = (Window) component;
            window.pack();
        }
    }
Class<?> [] moa.gui.ClassOptionWithNamesSelectionPanel.findSuitableClasses (Class<?> requiredType, String[] classNames)
Definition at line 94 of file ClassOptionWithNamesSelectionPanel.java.
References moa.tasks.Task.getTaskResultType().
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel().
{
        AutoExpandVector<Class<?>> finalClasses = new AutoExpandVector<Class<?>>();
        Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("moa",
                requiredType);
        for (Class<?> cl : classesFound) {
            for (int i = 0; i < classNames.length; i++) {
                if (cl.getSimpleName().contains(classNames[i])) {
                    finalClasses.add(cl);
                    break;
                }
            }
        }
        Class<?>[] tasksFound = AutoClassDiscovery.findClassesOfType("moa",
                Task.class);
        for (Class<?> foundTask : tasksFound) {
            try {
                Task task = (Task) foundTask.newInstance();
                if (requiredType.isAssignableFrom(task.getTaskResultType())) {
                    for (int i = 0; i < classNames.length; i++) {
                        if (foundTask.getSimpleName().contains(classNames[i])) {
                            finalClasses.add(foundTask);
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                // ignore
            }
        }
        return finalClasses.toArray(new Class<?>[finalClasses.size()]);
    }
String moa.gui.ClassOptionWithNamesSelectionPanel.getChosenObjectCLIString (Class<?> requiredType)
Definition at line 138 of file ClassOptionWithNamesSelectionPanel.java.
References moa.gui.ClassOptionWithNamesSelectionPanel.chosenObject, and moa.gui.ClassOptionWithNamesSelectionPanel.chosenObjectEditor.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.showSelectClassDialog().
{
        if (this.chosenObjectEditor instanceof OptionsConfigurationPanel) {
            ((OptionsConfigurationPanel) this.chosenObjectEditor).applyChanges();
        }
        return ClassOption.objectToCLIString(this.chosenObject, requiredType);
    }
static String moa.gui.ClassOptionWithNamesSelectionPanel.showSelectClassDialog (Component parent, String title, Class<?> requiredType, String initialCLIString, String nullString, String[] classNames) [static]
Definition at line 126 of file ClassOptionWithNamesSelectionPanel.java.
References moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel(), and moa.gui.ClassOptionWithNamesSelectionPanel.getChosenObjectCLIString().
{
        ClassOptionWithNamesSelectionPanel panel = new ClassOptionWithNamesSelectionPanel(
                requiredType, initialCLIString, nullString, classNames);
        if (JOptionPane.showOptionDialog(parent, panel, title,
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                null, null) == JOptionPane.OK_OPTION) {
            return panel.getChosenObjectCLIString(requiredType);
        }
        return initialCLIString;
    }
Member Data Documentation
Object moa.gui.ClassOptionWithNamesSelectionPanel.chosenObject [protected]
Definition at line 39 of file ClassOptionWithNamesSelectionPanel.java.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged(), and moa.gui.ClassOptionWithNamesSelectionPanel.getChosenObjectCLIString().
JComponent moa.gui.ClassOptionWithNamesSelectionPanel.chosenObjectEditor [protected]
Definition at line 38 of file ClassOptionWithNamesSelectionPanel.java.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged(), and moa.gui.ClassOptionWithNamesSelectionPanel.getChosenObjectCLIString().
JComboBox moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceBox [protected]
Definition at line 37 of file ClassOptionWithNamesSelectionPanel.java.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel().
boolean moa.gui.ClassOptionWithNamesSelectionPanel.debug = false [private]
Definition at line 35 of file ClassOptionWithNamesSelectionPanel.java.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.ClassOptionWithNamesSelectionPanel().
final long moa.gui.ClassOptionWithNamesSelectionPanel.serialVersionUID = 1L [static, private]
Definition at line 33 of file ClassOptionWithNamesSelectionPanel.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/ClassOptionWithNamesSelectionPanel.java