MOA: moa.streams.filters.AddNoiseFilter Class Reference
moa.streams.filters.AddNoiseFilter Class Reference
Filter for adding random noise to examples in a stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
InstancesHeader getHeader ()
Gets the header of this stream.
Instance nextInstance ()
Gets the next instance from this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption randomSeedOption
FloatOption attNoiseFractionOption
FloatOption classNoiseFractionOption
Protected Member Functions
void restartImpl ()
Restarts this filter.
Protected Attributes
Random random
AutoExpandVector< Object > attValObservers
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Filter for adding random noise to examples in a stream.
Noise can be added to attribute values or to class labels.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 39 of file AddNoiseFilter.java.
Member Function Documentation
void moa.streams.filters.AddNoiseFilter.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 110 of file AddNoiseFilter.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.filters.AddNoiseFilter.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 68 of file AddNoiseFilter.java.
References moa.streams.InstanceStream.getHeader(), and moa.streams.filters.AbstractStreamFilter.inputStream.
{
        return this.inputStream.getHeader();
    }
String moa.streams.filters.AddNoiseFilter.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file AddNoiseFilter.java.
{
        return "Adds random noise to examples in a stream.";
    }
Instance moa.streams.filters.AddNoiseFilter.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 73 of file AddNoiseFilter.java.
References moa.core.GaussianEstimator.addObservation(), moa.core.DoubleVector.addToValue(), moa.streams.filters.AddNoiseFilter.attNoiseFractionOption, moa.streams.filters.AddNoiseFilter.attValObservers, moa.streams.filters.AddNoiseFilter.classNoiseFractionOption, moa.core.GaussianEstimator.getStdDev(), moa.core.DoubleVector.getValue(), moa.options.FloatOption.getValue(), moa.streams.filters.AbstractStreamFilter.inputStream, moa.streams.InstanceStream.nextInstance(), moa.core.DoubleVector.numNonZeroEntries(), moa.core.DoubleVector.numValues(), and moa.streams.filters.AddNoiseFilter.random.
{
        Instance inst = (Instance) this.inputStream.nextInstance().copy();
        for (int i = 0; i < inst.numAttributes(); i++) {
            double noiseFrac = i == inst.classIndex() ? this.classNoiseFractionOption.getValue()
                    : this.attNoiseFractionOption.getValue();
            if (inst.attribute(i).isNominal()) {
                DoubleVector obs = (DoubleVector) this.attValObservers.get(i);
                if (obs == null) {
                    obs = new DoubleVector();
                    this.attValObservers.set(i, obs);
                }
                int originalVal = (int) inst.value(i);
                if (!inst.isMissing(i)) {
                    obs.addToValue(originalVal, inst.weight());
                }
                if ((this.random.nextDouble() < noiseFrac)
                        && (obs.numNonZeroEntries() > 1)) {
                    do {
                        inst.setValue(i, this.random.nextInt(obs.numValues()));
                    } while (((int) inst.value(i) == originalVal)
                            || (obs.getValue((int) inst.value(i)) == 0.0));
                }
            } else {
                GaussianEstimator obs = (GaussianEstimator) this.attValObservers.get(i);
                if (obs == null) {
                    obs = new GaussianEstimator();
                    this.attValObservers.set(i, obs);
                }
                obs.addObservation(inst.value(i), inst.weight());
                inst.setValue(i, inst.value(i) + this.random.nextGaussian()
                        * obs.getStdDev() * noiseFrac);
            }
        }
        return inst;
    }
void moa.streams.filters.AddNoiseFilter.restartImpl () [protected, virtual]
Restarts this filter.
All instances that extends from AbstractStreamFilter must implement restartImpl. restart uses restartImpl in AbstractStreamFilter.
Implements moa.streams.filters.AbstractStreamFilter.
Definition at line 62 of file AddNoiseFilter.java.
References moa.streams.filters.AddNoiseFilter.attValObservers, moa.options.IntOption.getValue(), moa.streams.filters.AddNoiseFilter.random, and moa.streams.filters.AddNoiseFilter.randomSeedOption.
{
        this.random = new Random(this.randomSeedOption.getValue());
        this.attValObservers = new AutoExpandVector<Object>();
    }
Member Data Documentation
FloatOption moa.streams.filters.AddNoiseFilter.attNoiseFractionOption
Initial value:
 new FloatOption("attNoise",
            'a', "The fraction of attribute values to disturb.", 0.1, 0.0, 1.0)
Definition at line 51 of file AddNoiseFilter.java.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance().
AutoExpandVector<Object> moa.streams.filters.AddNoiseFilter.attValObservers [protected]
Definition at line 59 of file AddNoiseFilter.java.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance(), and moa.streams.filters.AddNoiseFilter.restartImpl().
FloatOption moa.streams.filters.AddNoiseFilter.classNoiseFractionOption
Initial value:
 new FloatOption("classNoise",
            'c', "The fraction of class labels to disturb.", 0.1, 0.0, 1.0)
Definition at line 54 of file AddNoiseFilter.java.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance().
Random moa.streams.filters.AddNoiseFilter.random [protected]
Definition at line 57 of file AddNoiseFilter.java.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance(), and moa.streams.filters.AddNoiseFilter.restartImpl().
IntOption moa.streams.filters.AddNoiseFilter.randomSeedOption
Initial value:
 new IntOption("randomSeed", 'r',
            "Seed for random noise.", 1)
Definition at line 48 of file AddNoiseFilter.java.
Referenced by moa.streams.filters.AddNoiseFilter.restartImpl().
final long moa.streams.filters.AddNoiseFilter.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 46 of file AddNoiseFilter.java.
The documentation for this class was generated from the following file:
main/java/moa/streams/filters/AddNoiseFilter.java