MOA: moa.clusterers.macro.dbscan.DBScan Class Reference
moa.clusterers.macro.dbscan.DBScan Class Reference
Public Member Functions
DBScan (Clustering microClusters, double eps, int MinPts)
Clustering getClustering (Clustering microClusters)
Package Attributes
Clustering datasource
Private Member Functions
ArrayList< DenseMicroCluster > expandCluster (DenseMicroCluster dmc, List< DenseMicroCluster > neighbours, ArrayList< DenseMicroCluster > arrayList, Vector< DenseMicroCluster > dbmc)
List< DenseMicroCluster > getNeighbourhood (DenseMicroCluster mc, Vector< DenseMicroCluster > dbmc)
double distance (double[] center, double[] center2)
eclidean distance
List< CFCluster > Convert2microclusterList (ArrayList< DenseMicroCluster > cluster)
Private Attributes
double mEps
int mMinPts
Detailed Description
Definition at line 36 of file DBScan.java.
Constructor & Destructor Documentation
moa.clusterers.macro.dbscan.DBScan.DBScan (Clustering microClusters, double eps, int MinPts)
Definition at line 42 of file DBScan.java.
References moa.clusterers.macro.dbscan.DBScan.datasource, moa.clusterers.macro.dbscan.DBScan.mEps, and moa.clusterers.macro.dbscan.DBScan.mMinPts.
{
        datasource = microClusters;
        mEps = eps;
        mMinPts = MinPts;
    }
Member Function Documentation
List<CFCluster> moa.clusterers.macro.dbscan.DBScan.Convert2microclusterList (ArrayList< DenseMicroCluster > cluster) [private]
Definition at line 187 of file DBScan.java.
Referenced by moa.clusterers.macro.dbscan.DBScan.getClustering().
{
        List<CFCluster> cfCluster = new Vector<CFCluster>();
        for (DenseMicroCluster d : cluster) {
            cfCluster.add(d.getCFCluster());
        }
        return cfCluster;
    }
double moa.clusterers.macro.dbscan.DBScan.distance (double[] center, double[] center2) [private]
eclidean distance
Parameters:
center
center2
Returns:
Definition at line 100 of file DBScan.java.
Referenced by moa.clusterers.macro.dbscan.DBScan.getNeighbourhood().
{
        double d = 0D;
        for (int i = 0; i < center.length; i++) {
            d += Math.pow((center[i] - center2[i]), 2);
        }
        return Math.sqrt(d);
    }
ArrayList<DenseMicroCluster> moa.clusterers.macro.dbscan.DBScan.expandCluster (DenseMicroCluster dmc, List< DenseMicroCluster > neighbours, ArrayList< DenseMicroCluster > arrayList, Vector< DenseMicroCluster > dbmc) [private]
Definition at line 48 of file DBScan.java.
References moa.clusterers.macro.dbscan.DBScan.getNeighbourhood(), moa.clusterers.macro.dbscan.DenseMicroCluster.isClustered(), moa.clusterers.macro.dbscan.DenseMicroCluster.isVisited(), moa.clusterers.macro.dbscan.DBScan.mMinPts, moa.clusterers.macro.dbscan.DenseMicroCluster.setClustered(), and moa.clusterers.macro.dbscan.DenseMicroCluster.setVisited().
Referenced by moa.clusterers.macro.dbscan.DBScan.getClustering().
{
        if (!dmc.isClustered()) {
            dmc.setClustered();
            arrayList.add(dmc);
        }
        while (!neighbours.isEmpty()) {
            DenseMicroCluster mc = neighbours.get(0);
            neighbours.remove(0);
            if (!mc.isVisited()) {
                mc.setVisited();
                List<DenseMicroCluster> neighbours2 = getNeighbourhood(mc, dbmc);
                if (neighbours2.size() >= mMinPts) {
                    while (!neighbours2.isEmpty()) {
                        DenseMicroCluster temp = neighbours2.get(0);
                        neighbours2.remove(0);
                        if (!temp.isVisited()) {
                            neighbours.add(temp);
                        }
                    }
                    neighbours.addAll(neighbours2);
                    if (!mc.isClustered()) {
                        mc.setClustered();
                        arrayList.add(mc);
                    }
                }
            }
        }
        return arrayList;
    }
Clustering moa.clusterers.macro.dbscan.DBScan.getClustering (Clustering microClusters) [virtual]
Implements moa.clusterers.macro.AbstractMacroClusterer.
Definition at line 109 of file DBScan.java.
References moa.cluster.CFCluster.add(), moa.clusterers.macro.dbscan.DBScan.Convert2microclusterList(), moa.clusterers.macro.dbscan.DBScan.expandCluster(), moa.cluster.Clustering.getClustering(), moa.clusterers.macro.dbscan.DBScan.getNeighbourhood(), moa.clusterers.macro.dbscan.DBScan.mMinPts, moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.denstream.WithDBSCAN.getClusteringResult().
{
        if (microClusters != null && microClusters.size() != 0) {
            Vector<DenseMicroCluster> dbmc = new Vector<DenseMicroCluster>();
            for (Cluster c : microClusters.getClustering()) {
                CFCluster cf = null;
                if (c instanceof CFCluster) {
                    cf = (CFCluster) c;
                    dbmc.add(new DenseMicroCluster(cf));
                } else
                    throw new RuntimeException();
            }
            ArrayList<ArrayList<DenseMicroCluster>> clusters = new ArrayList<ArrayList<DenseMicroCluster>>();
            for (DenseMicroCluster dmc : dbmc) {
                if (!dmc.isVisited()) {
                    dmc.setVisited();
                    List<DenseMicroCluster> neighbours = getNeighbourhood(dmc,
                            dbmc);
                    if (neighbours.size() >= mMinPts) {
                        ArrayList<DenseMicroCluster> cluster = expandCluster(
                                dmc, neighbours,
                                new ArrayList<DenseMicroCluster>(), dbmc);
                        clusters.add(cluster);
                    }
                }
            }
            // ** create big microclusters,
            // CFCluster[] res = new CFCluster[clusters.size()];
            // int clusterPos = 0;
            // for (ArrayList<DenseMicroCluster> cluster : clusters) {
            // if (cluster.size() != 0) {
            // CFCluster temp = (CFCluster) (cluster.get(0).mCluster.copy());
            // res[clusterPos] = temp;
            // for (int i = 1; i < cluster.size(); i++) {
            // res[clusterPos].add(cluster.get(i).mCluster);
            // }
            // clusterPos++;
            // }
            // }
            // Clustering result = new Clustering(res);
            // **
            CFCluster[] res = new CFCluster[clusters.size()];
            int clusterPos = 0;
            for (ArrayList<DenseMicroCluster> cluster : clusters) {
                if (cluster.size() != 0) {
                    CFCluster temp = new NonConvexCluster(
                            cluster.get(0).getCFCluster(),
                            Convert2microclusterList(cluster));
                    res[clusterPos] = temp;
                    for (int i = 1; i < cluster.size(); i++) {
                        res[clusterPos].add(cluster.get(i).getCFCluster());
                    }
                    clusterPos++;
                }
            }
            // //// count Noise
            int noise = 0;
            for (DenseMicroCluster c : dbmc) {
                if (!c.isClustered()) {
                    noise++;
                }
            }
            System.out.println("microclusters which are not clustered:: "
                    + noise);
            Clustering result = new Clustering(res);
            setClusterIDs(result);
            // int i = 0;
            // for (Cluster c : result.getClustering()) {
            // c.setId(i++);
            // }
            return result;
        }
        return new Clustering();
    }
List<DenseMicroCluster> moa.clusterers.macro.dbscan.DBScan.getNeighbourhood (DenseMicroCluster mc, Vector< DenseMicroCluster > dbmc) [private]
Definition at line 82 of file DBScan.java.
References moa.clusterers.macro.dbscan.DBScan.distance(), moa.cluster.CFCluster.getCenter(), moa.clusterers.macro.dbscan.DenseMicroCluster.getCFCluster(), and moa.clusterers.macro.dbscan.DBScan.mEps.
Referenced by moa.clusterers.macro.dbscan.DBScan.expandCluster(), and moa.clusterers.macro.dbscan.DBScan.getClustering().
{
        List<DenseMicroCluster> res = new Vector<DenseMicroCluster>();
        for (DenseMicroCluster dmc : dbmc) {
            if (distance(dmc.getCFCluster().getCenter(), mc.getCFCluster().getCenter()) < mEps) {
                res.add(dmc);
            }
        }
        return res;
    }
Member Data Documentation
Clustering moa.clusterers.macro.dbscan.DBScan.datasource [package]
Definition at line 38 of file DBScan.java.
Referenced by moa.clusterers.macro.dbscan.DBScan.DBScan().
double moa.clusterers.macro.dbscan.DBScan.mEps [private]
Definition at line 39 of file DBScan.java.
Referenced by moa.clusterers.macro.dbscan.DBScan.DBScan(), and moa.clusterers.macro.dbscan.DBScan.getNeighbourhood().
int moa.clusterers.macro.dbscan.DBScan.mMinPts [private]
Definition at line 40 of file DBScan.java.
Referenced by moa.clusterers.macro.dbscan.DBScan.DBScan(), moa.clusterers.macro.dbscan.DBScan.expandCluster(), and moa.clusterers.macro.dbscan.DBScan.getClustering().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/macro/dbscan/DBScan.java