MOA: moa.gui.visualization.OutlierPanel Class Reference
moa.gui.visualization.OutlierPanel Class Reference
Public Member Functions
OutlierPanel (MyBaseOutlierDetector myOutlierDetector, Outlier outlier, SphereCluster cluster, Color color, StreamOutlierPanel sp)
Creates new form ObjectPanel.
void setDirection (double[] direction)
void updateLocation ()
void updateTooltip ()
boolean contains (int x, int y)
String getInfo ()
void highlight (boolean enabled)
boolean isValidCluster ()
int getClusterID ()
int getClusterLabel ()
String getSVGString (int width)
void drawOnCanvas (Graphics2D imageGraphics)
Protected Member Functions
void paintComponent (Graphics g)
Protected Attributes
double decay_rate
int x_dim = 0
int y_dim = 1
Color col
Color default_color = Color.BLACK
StreamOutlierPanel streamPanel
int panel_size
int window_size
boolean highligted = false
Package Attributes
JDialog frameInfo = null
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void formMouseClicked (java.awt.event.MouseEvent evt)
void showInfo ()
Private Attributes
boolean bAntiAlias = false
MyBaseOutlierDetector myOutlierDetector
Outlier myOutlier
SphereCluster cluster
double[] center
double r
Static Private Attributes
static final int DRAW_SIZE = 4
Detailed Description
Definition at line 35 of file OutlierPanel.java.
Constructor & Destructor Documentation
moa.gui.visualization.OutlierPanel.OutlierPanel (MyBaseOutlierDetector myOutlierDetector, Outlier outlier, SphereCluster cluster, Color color, StreamOutlierPanel sp)
Creates new form ObjectPanel.
Definition at line 62 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.center, moa.gui.visualization.OutlierPanel.col, moa.gui.visualization.OutlierPanel.default_color, moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getRadius(), moa.gui.visualization.OutlierPanel.initComponents(), moa.gui.visualization.OutlierPanel.myOutlier, moa.gui.visualization.OutlierPanel.r, and moa.gui.visualization.OutlierPanel.streamPanel.
{
        this.myOutlierDetector = myOutlierDetector;
        this.myOutlier = outlier;
        this.cluster = cluster;
        center = cluster.getCenter();
        r = cluster.getRadius();
        streamPanel = sp;
        default_color = col = color;
        setVisible(true);
        setOpaque(false);
        setSize(new Dimension(1,1));
        setLocation(0,0);
        initComponents();
    }
Member Function Documentation
boolean moa.gui.visualization.OutlierPanel.contains (int x, int y)
Definition at line 110 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.panel_size.
{
        //only react on the hull of the cluster
        double dist = Math.sqrt(Math.pow(x-panel_size/2,2)+Math.pow(y-panel_size/2,2));
        if(panel_size/2 - 5 < dist && dist < panel_size/2 + 5)
            return true;
        else
            return false;
    }
void moa.gui.visualization.OutlierPanel.drawOnCanvas (Graphics2D imageGraphics)
Definition at line 229 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.center, moa.gui.visualization.OutlierPanel.panel_size, moa.gui.visualization.OutlierPanel.window_size, moa.gui.visualization.OutlierPanel.x_dim, and moa.gui.visualization.OutlierPanel.y_dim.
{
        int x = (int)(center[x_dim]*window_size-(panel_size/2));
        int y = (int)(center[y_dim]*window_size-(panel_size/2));
        int radius = panel_size;
        imageGraphics.drawOval(x, y, radius, radius);
    }
void moa.gui.visualization.OutlierPanel.formMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 147 of file OutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.setHighlightedOutlierPanel(), moa.gui.visualization.OutlierPanel.showInfo(), and moa.gui.visualization.OutlierPanel.streamPanel.
Referenced by moa.gui.visualization.OutlierPanel.initComponents().
                                                                 {//GEN-FIRST:event_formMouseClicked
        streamPanel.setHighlightedOutlierPanel(this);
        showInfo();
        streamPanel.setHighlightedOutlierPanel(null);
    }//GEN-LAST:event_formMouseClicked
int moa.gui.visualization.OutlierPanel.getClusterID ()
Definition at line 207 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.cluster, and moa.cluster.Cluster.getId().
{
        return (int)cluster.getId();
    }
int moa.gui.visualization.OutlierPanel.getClusterLabel ()
Definition at line 211 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.cluster, and moa.cluster.Cluster.getGroundTruth().
{
        return (int)cluster.getGroundTruth();
    }
String moa.gui.visualization.OutlierPanel.getInfo ()
Definition at line 153 of file OutlierPanel.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.getObjectInfo(), moa.gui.visualization.OutlierPanel.myOutlier, moa.gui.visualization.OutlierPanel.myOutlierDetector, and moa.clusterers.outliers.MyBaseOutlierDetector.Outlier.obj.
Referenced by moa.gui.visualization.OutlierPanel.showInfo().
{
        return myOutlierDetector.getObjectInfo(myOutlier.obj);
    }
String moa.gui.visualization.OutlierPanel.getSVGString (int width)
Definition at line 215 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.center, moa.gui.visualization.OutlierPanel.panel_size, moa.gui.visualization.OutlierPanel.window_size, moa.gui.visualization.OutlierPanel.x_dim, and moa.gui.visualization.OutlierPanel.y_dim.
{
        StringBuffer out = new StringBuffer();
        int x = (int)(center[x_dim]*window_size);
        int y = (int)(center[y_dim]*window_size);
        int radius = panel_size/2;
        out.append("<circle ");
        out.append("cx='"+x+"' cy='"+y+"' r='"+radius+"'");
        out.append(" stroke='green' stroke-width='1' fill='white' fill-opacity='0' />");
        out.append("\n");
        return out.toString();
    }
void moa.gui.visualization.OutlierPanel.highlight (boolean enabled)
Definition at line 198 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.highligted.
Referenced by moa.gui.visualization.StreamOutlierPanel.formMouseClicked(), and moa.gui.visualization.StreamOutlierPanel.setHighlightedOutlierPanel().
{
        highligted = enabled;
        repaint();
    }
void moa.gui.visualization.OutlierPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 126 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.formMouseClicked().
Referenced by moa.gui.visualization.OutlierPanel.OutlierPanel().
{
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
boolean moa.gui.visualization.OutlierPanel.isValidCluster ()
Definition at line 203 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.center.
{
        return (center!=null);
    }
void moa.gui.visualization.OutlierPanel.paintComponent (Graphics g) [protected]
Definition at line 176 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.bAntiAlias, moa.gui.visualization.OutlierPanel.default_color, moa.gui.visualization.OutlierPanel.DRAW_SIZE, moa.gui.visualization.OutlierPanel.highligted, and moa.gui.visualization.OutlierPanel.updateLocation().
{
        if (bAntiAlias) {
            Graphics2D g2d = (Graphics2D)g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
        }
        updateLocation();
        if (highligted){
            g.setColor(Color.ORANGE);
        }
        else{
            g.setColor(default_color);
        }
        int drawSize = DRAW_SIZE;
        int drawStart = 0;
        g.fillOval(drawStart, drawStart, drawSize, drawSize);
        g.drawOval(drawStart, drawStart, drawSize, drawSize);
    }
void moa.gui.visualization.OutlierPanel.setDirection (double[] direction)
Definition at line 80 of file OutlierPanel.java.
{
    }
void moa.gui.visualization.OutlierPanel.showInfo () [private]
Definition at line 157 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.getInfo().
Referenced by moa.gui.visualization.OutlierPanel.formMouseClicked().
{
        String title = "Outlier information";
        JLabel comp = new JLabel();
        comp.setText(getInfo());
        JOptionPane pane = new JOptionPane(comp);
        pane.setOptionType(JOptionPane.DEFAULT_OPTION);
        pane.setMessageType(JOptionPane.PLAIN_MESSAGE);
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();
        Point mousePoint = pointerInfo.getLocation();
        JDialog dialog = pane.createDialog(this, title);
        dialog.setLocation(mousePoint);
        dialog.setVisible(true);
    }
void moa.gui.visualization.OutlierPanel.updateLocation ()
Definition at line 83 of file OutlierPanel.java.
References moa.gui.visualization.OutlierPanel.center, moa.gui.visualization.OutlierPanel.cluster, moa.gui.visualization.OutlierPanel.DRAW_SIZE, moa.gui.visualization.StreamOutlierPanel.getActiveXDim(), moa.gui.visualization.StreamOutlierPanel.getActiveYDim(), moa.gui.visualization.OutlierPanel.panel_size, moa.gui.visualization.OutlierPanel.streamPanel, moa.gui.visualization.OutlierPanel.window_size, moa.gui.visualization.OutlierPanel.x_dim, and moa.gui.visualization.OutlierPanel.y_dim.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawOutliers(), and moa.gui.visualization.OutlierPanel.paintComponent().
{
        x_dim = streamPanel.getActiveXDim();
        y_dim = streamPanel.getActiveYDim();
        if ((cluster != null) && (center == null)) {
            getParent().remove(this);
        } else {
            //size of the parent
            window_size = Math.min(streamPanel.getWidth(), streamPanel.getHeight());
            panel_size = DRAW_SIZE + 1;
            setSize(new Dimension(panel_size, panel_size));
            int x = (int) Math.round(center[x_dim] * window_size);
            int y = (int) Math.round(center[y_dim] * window_size);
            setLocation((int)(x - (panel_size / 2)), (int)(y - (panel_size / 2)));
        }
    }
void moa.gui.visualization.OutlierPanel.updateTooltip ()
Definition at line 103 of file OutlierPanel.java.
{
        /*setToolTipText(cluster.getInfo());
        ToolTipManager.sharedInstance().registerComponent(this);
        ToolTipManager.sharedInstance().setInitialDelay(0);*/
    }
Member Data Documentation
boolean moa.gui.visualization.OutlierPanel.bAntiAlias = false [private]
Definition at line 36 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.paintComponent().
double [] moa.gui.visualization.OutlierPanel.center [private]
Definition at line 44 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.drawOnCanvas(), moa.gui.visualization.OutlierPanel.getSVGString(), moa.gui.visualization.OutlierPanel.isValidCluster(), moa.gui.visualization.OutlierPanel.OutlierPanel(), and moa.gui.visualization.OutlierPanel.updateLocation().
SphereCluster moa.gui.visualization.OutlierPanel.cluster [private]
Definition at line 40 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.getClusterID(), moa.gui.visualization.OutlierPanel.getClusterLabel(), and moa.gui.visualization.OutlierPanel.updateLocation().
Color moa.gui.visualization.OutlierPanel.col [protected]
Definition at line 50 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.OutlierPanel().
double moa.gui.visualization.OutlierPanel.decay_rate [protected]
Definition at line 46 of file OutlierPanel.java.
Color moa.gui.visualization.OutlierPanel.default_color = Color.BLACK [protected]
Definition at line 51 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.OutlierPanel(), and moa.gui.visualization.OutlierPanel.paintComponent().
final int moa.gui.visualization.OutlierPanel.DRAW_SIZE = 4 [static, private]
Definition at line 45 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.paintComponent(), and moa.gui.visualization.OutlierPanel.updateLocation().
JDialog moa.gui.visualization.OutlierPanel.frameInfo = null [package]
Definition at line 42 of file OutlierPanel.java.
boolean moa.gui.visualization.OutlierPanel.highligted = false [protected]
Definition at line 57 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.highlight(), and moa.gui.visualization.OutlierPanel.paintComponent().
Outlier moa.gui.visualization.OutlierPanel.myOutlier [private]
Definition at line 39 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.getInfo(), and moa.gui.visualization.OutlierPanel.OutlierPanel().
MyBaseOutlierDetector moa.gui.visualization.OutlierPanel.myOutlierDetector [private]
Definition at line 38 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.getInfo().
int moa.gui.visualization.OutlierPanel.panel_size [protected]
Definition at line 55 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.contains(), moa.gui.visualization.OutlierPanel.drawOnCanvas(), moa.gui.visualization.OutlierPanel.getSVGString(), and moa.gui.visualization.OutlierPanel.updateLocation().
double moa.gui.visualization.OutlierPanel.r [private]
Definition at line 58 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.OutlierPanel().
StreamOutlierPanel moa.gui.visualization.OutlierPanel.streamPanel [protected]
Definition at line 53 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.formMouseClicked(), moa.gui.visualization.OutlierPanel.OutlierPanel(), and moa.gui.visualization.OutlierPanel.updateLocation().
int moa.gui.visualization.OutlierPanel.window_size [protected]
Definition at line 56 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.drawOnCanvas(), moa.gui.visualization.OutlierPanel.getSVGString(), and moa.gui.visualization.OutlierPanel.updateLocation().
int moa.gui.visualization.OutlierPanel.x_dim = 0 [protected]
Definition at line 48 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.drawOnCanvas(), moa.gui.visualization.OutlierPanel.getSVGString(), and moa.gui.visualization.OutlierPanel.updateLocation().
int moa.gui.visualization.OutlierPanel.y_dim = 1 [protected]
Definition at line 49 of file OutlierPanel.java.
Referenced by moa.gui.visualization.OutlierPanel.drawOnCanvas(), moa.gui.visualization.OutlierPanel.getSVGString(), and moa.gui.visualization.OutlierPanel.updateLocation().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/OutlierPanel.java