MOA: moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver Class Reference
moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver Class Reference
Classes
class Node
Public Member Functions
void observeAttributeClass (double attVal, double classVal, double weight)
Public Attributes
IntOption maxNodesOption = new IntOption("maxNodesOption", 'z', "Maximum number of nodes", 50, 0, Integer.MAX_VALUE)
Protected Attributes
int maxNodes
int numNodes
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 25 of file FIMTDDNumericAttributeClassLimitObserver.java.
Member Function Documentation
void moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass (double attVal, double classVal, double weight)
Reimplemented from moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 38 of file FIMTDDNumericAttributeClassLimitObserver.java.
References moa.options.IntOption.getValue(), moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.maxNodes, moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.maxNodesOption, moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.Node(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.root.
{
        if (Double.isNaN(attVal)) { //Instance.isMissingValue(attVal)
        } else {
            if (this.root == null) {
                maxNodes=maxNodesOption.getValue();
                this.root = new FIMTDDNumericAttributeClassLimitObserver.Node(attVal, classVal, weight);
            } else {
                this.root.insertValue(attVal, classVal, weight);
            }
        }
    }
Member Data Documentation
int moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.maxNodes [protected]
Definition at line 31 of file FIMTDDNumericAttributeClassLimitObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), and moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass().
IntOption moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.maxNodesOption = new IntOption("maxNodesOption", 'z', "Maximum number of nodes", 50, 0, Integer.MAX_VALUE)
Definition at line 32 of file FIMTDDNumericAttributeClassLimitObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass().
int moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.numNodes [protected]
Definition at line 35 of file FIMTDDNumericAttributeClassLimitObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue().
final long moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 30 of file FIMTDDNumericAttributeClassLimitObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/attributeclassobservers/FIMTDDNumericAttributeClassLimitObserver.java