MOA: moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension Class Reference
moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension Class Reference
The class that splits a KDTree node based on the median value of a dimension in which the node's points have the widest spread.
Public Member Functions
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
void splitNode (KDTreeNode node, int numNodesCreated, double[][] nodeRanges, double[][] universe) throws Exception
Splits a node into two based on the median value of the dimension in which the points have the widest spread.
int select (int attIdx, int[] indices, int left, int right, int k)
Implements computation of the kth-smallest element according to Manber's "Introduction to Algorithms".
Protected Member Functions
int partition (int attIdx, int[] index, int l, int r)
Partitions the instances around a pivot.
Static Private Attributes
static final long serialVersionUID = 1383443320160540663L
for serialization.
Detailed Description
The class that splits a KDTree node based on the median value of a dimension in which the node's points have the widest spread.
For more information see also:
Jerome H. Friedman, Jon Luis Bentley, Raphael Ari Finkel (1977). An Algorithm for Finding Best Matches in Logarithmic Expected Time. ACM Transactions on Mathematics Software. 3(3):209-226.
BibTeX:
 &#64;article{Friedman1977,
    author = {Jerome H. Friedman and Jon Luis Bentley and Raphael Ari Finkel},
    journal = {ACM Transactions on Mathematics Software},
    month = {September},
    number = {3},
    pages = {209-226},
    title = {An Algorithm for Finding Best Matches in Logarithmic Expected Time},
    volume = {3},
    year = {1977}
 }
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 56 of file MedianOfWidestDimension.java.
Member Function Documentation
String moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Definition at line 68 of file MedianOfWidestDimension.java.
{
    return
        "The class that splits a KDTree node based on the median value of "
      + "a dimension in which the node's points have the widest spread.\n\n"
      + "For more information see also:\n\n";
  }
int moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.partition (int attIdx, int[] index, int l, int r) [protected]
Partitions the instances around a pivot.
Used by quicksort and kthSmallestValue.
Parameters:
attIdx The attribution/dimension based on which the instances should be partitioned.
index The master index array containing indices of the instances.
l The begining index of the portion of master index array that should be partitioned.
r The end index of the portion of master index array that should be partitioned.
Returns:
the index of the middle element
Definition at line 133 of file MedianOfWidestDimension.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances.
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.select().
{
    double pivot = m_Instances.instance(index[(l + r) / 2]).value(attIdx);
    int help;
    while (l < r) {
      while ((m_Instances.instance(index[l]).value(attIdx) < pivot) && (l < r)) {
        l++;
      }
      while ((m_Instances.instance(index[r]).value(attIdx) > pivot) && (l < r)) {
        r--;
      }
      if (l < r) {
        help = index[l];
        index[l] = index[r];
        index[r] = help;
        l++;
        r--;
      }
    }
    if ((l == r) && (m_Instances.instance(index[r]).value(attIdx) > pivot)) {
      r--;
    }
    return r;
  }
int moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.select (int attIdx, int[] indices, int left, int right, int k)
Implements computation of the kth-smallest element according to Manber's "Introduction to Algorithms".
Parameters:
attIdx The dimension/attribute of the instances in which to find the kth-smallest element.
indices The master index array containing indices of the instances.
left The begining index of the portion of the master index array in which to find the kth-smallest element.
right The end index of the portion of the master index array in which to find the kth-smallest element.
k The value of k
Returns:
The index of the kth-smallest element
Definition at line 175 of file MedianOfWidestDimension.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.partition().
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.splitNode().
{
    if (left == right) {
      return left;
    } else {
      int middle = partition(attIdx, indices, left, right);
      if ((middle - left + 1) >= k) {
        return select(attIdx, indices, left, middle, k);
      } else {
        return select(attIdx, indices, middle + 1, right, k - (middle - left + 1));
      }
    }
  }
void moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.splitNode (KDTreeNode node, int numNodesCreated, double nodeRanges[][], double universe[][]) throws Exception [virtual]
Splits a node into two based on the median value of the dimension in which the points have the widest spread.
After splitting two new nodes are created and correctly initialised. And, node.left and node.right are set appropriately.
Parameters:
node The node to split.
numNodesCreated The number of nodes that so far have been created for the tree, so that the newly created nodes are assigned correct/meaningful node numbers/ids.
nodeRanges The attributes' range for the points inside the node that is to be split.
universe The attributes' range for the whole point-space.
Exceptions:
Exception If there is some problem in splitting the given node.
Implements moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.
Definition at line 94 of file MedianOfWidestDimension.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.correctlyInitialized(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_InstList, moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.select(), and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.widestDim().
{
    correctlyInitialized();
    int splitDim = widestDim(nodeRanges, universe);
    //In this case median is defined to be either the middle value (in case of
    //odd number of values) or the left of the two middle values (in case of
    //even number of values).
    int medianIdxIdx = node.m_Start + (node.m_End-node.m_Start)/2;
    //the following finds the median and also re-arranges the array so all
    //elements to the left are < median and those to the right are > median.
    int medianIdx = select(splitDim, m_InstList, node.m_Start, node.m_End, (node.m_End-node.m_Start)/2+1);
    node.m_SplitDim = splitDim;
    node.m_SplitValue = m_Instances.instance(m_InstList[medianIdx]).value(splitDim);
    node.m_Left  = new KDTreeNode(numNodesCreated+1, node.m_Start, medianIdxIdx,
    m_EuclideanDistance.initializeRanges(m_InstList, node.m_Start, medianIdxIdx));
    node.m_Right = new KDTreeNode(numNodesCreated+2, medianIdxIdx+1, node.m_End,
    m_EuclideanDistance.initializeRanges(m_InstList, medianIdxIdx+1, node.m_End));
  }
Member Data Documentation
final long moa.classifiers.lazy.neighboursearch.kdtrees.MedianOfWidestDimension.serialVersionUID = 1383443320160540663L [static, private]
for serialization.
Definition at line 60 of file MedianOfWidestDimension.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/kdtrees/MedianOfWidestDimension.java