MOA: moa.tasks.EvaluateInterleavedTestThenTrain Class Reference
moa.tasks.EvaluateInterleavedTestThenTrain Class Reference
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
IntOption randomSeedOption
ClassOption evaluatorOption
IntOption instanceLimitOption
IntOption timeLimitOption
IntOption sampleFrequencyOption
IntOption memCheckFrequencyOption
FileOption dumpFileOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file EvaluateInterleavedTestThenTrain.java.
Member Function Documentation
Object moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 98 of file EvaluateInterleavedTestThenTrain.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.AbstractMOAObject.copy(), moa.tasks.EvaluateInterleavedTestThenTrain.dumpFileOption, moa.evaluation.LearningCurve.entryToString(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluateInterleavedTestThenTrain.evaluatorOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.options.IntOption.getValueAsCLIString(), moa.options.ClassOption.getValueAsCLIString(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.EvaluateInterleavedTestThenTrain.instanceLimitOption, moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.classifiers.Classifier.isRandomizable(), moa.tasks.EvaluateInterleavedTestThenTrain.learnerOption, moa.MOAObject.measureByteSize(), moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.tasks.EvaluateInterleavedTestThenTrain.randomSeedOption, moa.classifiers.Classifier.resetLearning(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluateInterleavedTestThenTrain.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.classifiers.Classifier.setRandomSeed(), moa.options.ClassOption.setValueViaCLIString(), moa.tasks.EvaluateInterleavedTestThenTrain.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluateInterleavedTestThenTrain.timeLimitOption, and moa.classifiers.Classifier.trainOnInstance().
{
        String learnerString = this.learnerOption.getValueAsCLIString();
        String streamString = this.streamOption.getValueAsCLIString();
        //this.learnerOption.setValueViaCLIString(this.learnerOption.getValueAsCLIString() + " -r " +this.randomSeedOption);
        this.streamOption.setValueViaCLIString(streamString + " -i " + this.randomSeedOption.getValueAsCLIString());
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        if (learner.isRandomizable()) {
            learner.setRandomSeed(this.randomSeedOption.getValue());
            learner.resetLearning();
        }
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        learner.setModelContext(stream.getHeader());
        int maxInstances = this.instanceLimitOption.getValue();
        long instancesProcessed = 0;
        int maxSeconds = this.timeLimitOption.getValue();
        int secondsElapsed = 0;
        monitor.setCurrentActivity("Evaluating learner...", -1.0);
        LearningCurve learningCurve = new LearningCurve(
                "learning evaluation instances");
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        boolean firstDump = true;
        boolean preciseCPUTiming = TimingUtils.enablePreciseTiming();
        long evaluateStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        long lastEvaluateStartTime = evaluateStartTime;
        double RAMHours = 0.0;
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))
                && ((maxSeconds < 0) || (secondsElapsed < maxSeconds))) {
            Instance trainInst = stream.nextInstance();
            Instance testInst = (Instance) trainInst.copy();
            int trueClass = (int) trainInst.classValue();
            //testInst.setClassMissing();
            double[] prediction = learner.getVotesForInstance(testInst);
            //evaluator.addClassificationAttempt(trueClass, prediction, testInst
            //      .weight());
            evaluator.addResult(testInst, prediction);
            learner.trainOnInstance(trainInst);
            instancesProcessed++;
            if (instancesProcessed % this.sampleFrequencyOption.getValue() == 0
                    || stream.hasMoreInstances() == false) {
                long evaluateTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
                double time = TimingUtils.nanoTimeToSeconds(evaluateTime - evaluateStartTime);
                double timeIncrement = TimingUtils.nanoTimeToSeconds(evaluateTime - lastEvaluateStartTime);
                double RAMHoursIncrement = learner.measureByteSize() / (1024.0 * 1024.0 * 1024.0); //GBs
                RAMHoursIncrement *= (timeIncrement / 3600.0); //Hours
                RAMHours += RAMHoursIncrement;
                lastEvaluateStartTime = evaluateTime;
                learningCurve.insertEntry(new LearningEvaluation(
                        new Measurement[]{
                            new Measurement(
                                    "learning evaluation instances",
                                    instancesProcessed),
                            new Measurement(
                                    "evaluation time ("
                                    + (preciseCPUTiming ? "cpu "
                                    : "") + "seconds)",
                                    time),
                            new Measurement(
                                    "model cost (RAM-Hours)",
                                    RAMHours)
                        },
                        evaluator, learner));
                if (immediateResultStream != null) {
                    if (firstDump) {
                        immediateResultStream.print("Learner,stream,randomSeed,");
                        immediateResultStream.println(learningCurve.headerToString());
                        firstDump = false;
                    }
                    immediateResultStream.print(learnerString + "," + streamString + "," + this.randomSeedOption.getValueAsCLIString() + ",");
                    immediateResultStream.println(learningCurve.entryToString(learningCurve.numEntries() - 1));
                    immediateResultStream.flush();
                }
            }
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) instancesProcessed
                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.copy());
                }
                secondsElapsed = (int) TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                        - evaluateStartTime);
            }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
        return learningCurve;
    }
String moa.tasks.EvaluateInterleavedTestThenTrain.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 49 of file EvaluateInterleavedTestThenTrain.java.
{
        return "Evaluates a classifier on a stream by testing then training with each example in sequence.";
    }
Class<?> moa.tasks.EvaluateInterleavedTestThenTrain.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 93 of file EvaluateInterleavedTestThenTrain.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FileOption moa.tasks.EvaluateInterleavedTestThenTrain.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv reslts to.", null, "csv", true)
Definition at line 89 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
ClassOption moa.tasks.EvaluateInterleavedTestThenTrain.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "BasicClassificationPerformanceEvaluator")
Definition at line 66 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
IntOption moa.tasks.EvaluateInterleavedTestThenTrain.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            100000000, -1, Integer.MAX_VALUE)
Definition at line 71 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
ClassOption moa.tasks.EvaluateInterleavedTestThenTrain.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Definition at line 55 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
IntOption moa.tasks.EvaluateInterleavedTestThenTrain.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Definition at line 84 of file EvaluateInterleavedTestThenTrain.java.
IntOption moa.tasks.EvaluateInterleavedTestThenTrain.randomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'r',
            "Seed for random generation of instances.", 1)
Definition at line 62 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
IntOption moa.tasks.EvaluateInterleavedTestThenTrain.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            100000, 0, Integer.MAX_VALUE)
Definition at line 79 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
final long moa.tasks.EvaluateInterleavedTestThenTrain.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 53 of file EvaluateInterleavedTestThenTrain.java.
ClassOption moa.tasks.EvaluateInterleavedTestThenTrain.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 58 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
IntOption moa.tasks.EvaluateInterleavedTestThenTrain.timeLimitOption
Initial value:
 new IntOption("timeLimit", 't',
            "Maximum number of seconds to test/train for (-1 = no limit).", -1,
            -1, Integer.MAX_VALUE)
Definition at line 75 of file EvaluateInterleavedTestThenTrain.java.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateInterleavedTestThenTrain.java