MOA: moa.clusterers.clustream.Clustream Class Reference
moa.clusterers.clustream.Clustream Class Reference
Citation: CluStream: Charu C.
Public Member Functions
Clustream ()
void resetLearningImpl ()
void trainOnInstanceImpl (Instance instance)
Clustering getMicroClusteringResult ()
boolean implementsMicroClusterer ()
Clustering getClusteringResult ()
String getName ()
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
double[] getVotesForInstance (Instance inst)
Static Public Member Functions
static Clustering kMeans (int k, List<?extends Cluster > data)
static Clustering kMeans (int k, Cluster[] centers, List<?extends Cluster > data)
Public Attributes
IntOption timeWindowOption
IntOption maxNumKernelsOption
IntOption kernelRadiFactorOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Static Private Member Functions
static double distance (double[] pointA, double[] pointB)
static SphereCluster calculateCenter (ArrayList< Cluster > cluster, int dimensions)
Private Attributes
int timeWindow
long timestamp = -1
ClustreamKernel[] kernels
boolean initialized
List< ClustreamKernel > buffer
int bufferSize
double t
int m
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Citation: CluStream: Charu C.
Aggarwal, Jiawei Han, Jianyong Wang, Philip S. Yu: A Framework for Clustering Evolving Data Streams. VLDB 2003: 81-92
Definition at line 39 of file Clustream.java.
Constructor & Destructor Documentation
moa.clusterers.clustream.Clustream.Clustream ()
Definition at line 63 of file Clustream.java.
                       {
    }
Member Function Documentation
static SphereCluster moa.clusterers.clustream.Clustream.calculateCenter (ArrayList< Cluster > cluster, int dimensions) [static, private]
Definition at line 282 of file Clustream.java.
References moa.clusterers.clustream.Clustream.distance(), and moa.cluster.SphereCluster.setWeight().
Referenced by moa.clusterers.clustream.Clustream.kMeans().
{
        double[] res = new double[dimensions];
        for ( int i = 0; i < res.length; i++ ) {
            res[i] = 0.0;
        }
        if ( cluster.size() == 0 ) {
            return new SphereCluster( res, 0.0 );
        }
        for ( Cluster point : cluster ) {
            double [] center = point.getCenter();
            for (int i = 0; i < res.length; i++) {
                res[i] += center[i];
            }
        }
        // Normalize
        for ( int i = 0; i < res.length; i++ ) {
            res[i] /= cluster.size();
        }
        // Calculate radius
        double radius = 0.0;
        for ( Cluster point : cluster ) {
            double dist = distance( res, point.getCenter() );
            if ( dist > radius ) {
                radius = dist;
            }
        }
        SphereCluster sc = new SphereCluster( res, radius );
        sc.setWeight(cluster.size());
        return sc;
    }
static double moa.clusterers.clustream.Clustream.distance (double[] pointA, double[] pointB) [static, private]
Definition at line 208 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.calculateCenter(), moa.clusterers.clustream.Clustream.kMeans(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        double distance = 0.0;
        for (int i = 0; i < pointA.length; i++) {
            double d = pointA[i] - pointB[i];
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
Clustering moa.clusterers.clustream.Clustream.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 200 of file Clustream.java.
{
        return null;
    }
Clustering moa.clusterers.clustream.Clustream.getMicroClusteringResult ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 181 of file Clustream.java.
References moa.clusterers.clustream.Clustream.initialized, moa.clusterers.clustream.Clustream.kernels, moa.clusterers.clustream.Clustream.m, and moa.clusterers.clustream.Clustream.t.
{
        if ( !initialized ) {
            return new Clustering( new Cluster[0] );
        }
        ClustreamKernel[] res = new ClustreamKernel[kernels.length];
        for ( int i = 0; i < res.length; i++ ) {
            res[i] = new ClustreamKernel( kernels[i], t, m );
        }
        return new Clustering( res );
    }
void moa.clusterers.clustream.Clustream.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 323 of file Clustream.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
Measurement [] moa.clusterers.clustream.Clustream.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 318 of file Clustream.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.clusterers.clustream.Clustream.getName ()
Definition at line 204 of file Clustream.java.
References moa.clusterers.clustream.Clustream.timeWindow.
{
        return "Clustream " + timeWindow;
    }
double [] moa.clusterers.clustream.Clustream.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 331 of file Clustream.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
boolean moa.clusterers.clustream.Clustream.implementsMicroClusterer ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 195 of file Clustream.java.
{
        return true;
    }
boolean moa.clusterers.clustream.Clustream.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 327 of file Clustream.java.
{
        return false;
    }
static Clustering moa.clusterers.clustream.Clustream.kMeans (int k, Cluster[] centers, List<?extends Cluster > data) [static]
Definition at line 242 of file Clustream.java.
References moa.cluster.Clustering.add(), moa.clusterers.clustream.Clustream.calculateCenter(), moa.clusterers.AbstractClusterer.clustering, moa.clusterers.clustream.Clustream.distance(), and moa.cluster.Cluster.getCenter().
{
        assert (centers.length == k);
        assert (k > 0);
        int dimensions = centers[0].getCenter().length;
        ArrayList<ArrayList<Cluster>> clustering = new ArrayList<ArrayList<Cluster>>();
        for ( int i = 0; i < k; i++ ) {
            clustering.add( new ArrayList<Cluster>() );
        }
        int repetitions = 100;
        while ( repetitions-- >= 0 ) {
            // Assign points to clusters
            for ( Cluster point : data ) {
                double minDistance = distance( point.getCenter(), centers[0].getCenter() );
                int closestCluster = 0;
                for ( int i = 1; i < k; i++ ) {
                    double distance = distance( point.getCenter(), centers[i].getCenter() );
                    if ( distance < minDistance ) {
                        closestCluster = i;
                        minDistance = distance;
                    }
                }
                clustering.get( closestCluster ).add( point );
            }
            // Calculate new centers and clear clustering lists
            SphereCluster[] newCenters = new SphereCluster[centers.length];
            for ( int i = 0; i < k; i++ ) {
                newCenters[i] = calculateCenter( clustering.get( i ), dimensions );
                clustering.get( i ).clear();
            }
            centers = newCenters;
        }
        return new Clustering( centers );
    }
static Clustering moa.clusterers.clustream.Clustream.kMeans (int k, List<?extends Cluster > data) [static]
Definition at line 227 of file Clustream.java.
References moa.clusterers.AbstractClusterer.clustering.
Referenced by moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        Random random = new Random(0);
        Cluster[] centers = new Cluster[k];
        for (int i = 0; i < centers.length; i++) {
            int rid = random.nextInt(k);
            centers[i] = new SphereCluster(data.get(rid).getCenter(),0);
        }
        Clustering clustering = kMeans(k, centers, data);
        return clustering;
    }
void moa.clusterers.clustream.Clustream.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 68 of file Clustream.java.
References moa.clusterers.clustream.Clustream.buffer, moa.clusterers.clustream.Clustream.bufferSize, moa.options.IntOption.getValue(), moa.clusterers.clustream.Clustream.initialized, moa.clusterers.clustream.Clustream.kernelRadiFactorOption, moa.clusterers.clustream.Clustream.kernels, moa.clusterers.clustream.Clustream.m, moa.clusterers.clustream.Clustream.maxNumKernelsOption, moa.clusterers.clustream.Clustream.t, moa.clusterers.clustream.Clustream.timeWindow, and moa.clusterers.clustream.Clustream.timeWindowOption.
{
        this.kernels = new ClustreamKernel[maxNumKernelsOption.getValue()];
        this.timeWindow = timeWindowOption.getValue();
        this.initialized = false;
        this.buffer = new LinkedList<ClustreamKernel>();
        this.bufferSize = maxNumKernelsOption.getValue();
        t = kernelRadiFactorOption.getValue();
        m = maxNumKernelsOption.getValue();
    }
void moa.clusterers.clustream.Clustream.trainOnInstanceImpl (Instance instance) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 79 of file Clustream.java.
References moa.clusterers.clustream.ClustreamKernel.add(), moa.clusterers.clustream.Clustream.buffer, moa.clusterers.clustream.Clustream.bufferSize, moa.clusterers.clustream.Clustream.distance(), moa.clusterers.clustream.ClustreamKernel.getCenter(), moa.clusterers.clustream.ClustreamKernel.getRadius(), moa.cluster.CFCluster.getWeight(), moa.clusterers.clustream.Clustream.initialized, moa.clusterers.clustream.ClustreamKernel.insert(), moa.clusterers.clustream.Clustream.kernels, moa.clusterers.clustream.Clustream.kMeans(), moa.clusterers.clustream.Clustream.m, moa.cluster.Clustering.size(), moa.clusterers.clustream.Clustream.t, moa.clusterers.clustream.Clustream.timestamp, and moa.clusterers.clustream.Clustream.timeWindow.
{
        int dim = instance.numValues();
        timestamp++;
        // 0. Initialize
        if ( !initialized ) {
            if ( buffer.size() < bufferSize ) {
                buffer.add( new ClustreamKernel(instance,dim, timestamp, t, m) );
                return;
            }
            int k = kernels.length;
            //System.err.println("k="+k+" bufferSize="+bufferSize);
            assert (k <= bufferSize);
            ClustreamKernel[] centers = new ClustreamKernel[k];
            for ( int i = 0; i < k; i++ ) {
                centers[i] = buffer.get( i ); // TODO: make random!
            }
            Clustering kmeans_clustering = kMeans(k, centers, buffer);
//          Clustering kmeans_clustering = kMeans(k, buffer);
            for ( int i = 0; i < kmeans_clustering.size(); i++ ) {
                kernels[i] = new ClustreamKernel( new DenseInstance(1.0,centers[i].getCenter()), dim, timestamp, t, m );
            }
            buffer.clear();
            initialized = true;
            return;
        }
        // 1. Determine closest kernel
        ClustreamKernel closestKernel = null;
        double minDistance = Double.MAX_VALUE;
        for ( int i = 0; i < kernels.length; i++ ) {
            //System.out.println(i+" "+kernels[i].getWeight()+" "+kernels[i].getDeviation());
            double distance = distance(instance.toDoubleArray(), kernels[i].getCenter() );
            if ( distance < minDistance ) {
                closestKernel = kernels[i];
                minDistance = distance;
            }
        }
        // 2. Check whether instance fits into closestKernel
        double radius = 0.0;
        if ( closestKernel.getWeight() == 1 ) {
            // Special case: estimate radius by determining the distance to the
            // next closest cluster
            radius = Double.MAX_VALUE;
            double[] center = closestKernel.getCenter();
            for ( int i = 0; i < kernels.length; i++ ) {
                if ( kernels[i] == closestKernel ) {
                    continue;
                }
                double distance = distance(kernels[i].getCenter(), center );
                radius = Math.min( distance, radius );
            }
        } else {
            radius = closestKernel.getRadius();
        }
        if ( minDistance < radius ) {
            // Date fits, put into kernel and be happy
            closestKernel.insert( instance, timestamp );
            return;
        }
        // 3. Date does not fit, we need to free
        // some space to insert a new kernel
        long threshold = timestamp - timeWindow; // Kernels before this can be forgotten
        // 3.1 Try to forget old kernels
        for ( int i = 0; i < kernels.length; i++ ) {
            if ( kernels[i].getRelevanceStamp() < threshold ) {
                kernels[i] = new ClustreamKernel( instance, dim, timestamp, t, m );
                return;
            }
        }
        // 3.2 Merge closest two kernels
        int closestA = 0;
        int closestB = 0;
        minDistance = Double.MAX_VALUE;
        for ( int i = 0; i < kernels.length; i++ ) {
            double[] centerA = kernels[i].getCenter();
            for ( int j = i + 1; j < kernels.length; j++ ) {
                double dist = distance( centerA, kernels[j].getCenter() );
                if ( dist < minDistance ) {
                    minDistance = dist;
                    closestA = i;
                    closestB = j;
                }
            }
        }
        assert (closestA != closestB);
        kernels[closestA].add( kernels[closestB] );
        kernels[closestB] = new ClustreamKernel( instance, dim, timestamp, t,  m );
    }
Member Data Documentation
List<ClustreamKernel> moa.clusterers.clustream.Clustream.buffer [private]
Definition at line 58 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
int moa.clusterers.clustream.Clustream.bufferSize [private]
Definition at line 59 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
boolean moa.clusterers.clustream.Clustream.initialized [private]
Definition at line 57 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.getMicroClusteringResult(), moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.Clustream.kernelRadiFactorOption
Initial value:
 new IntOption(
            "kernelRadiFactor", 't',
            "Multiplier for the kernel radius", 2)
Definition at line 50 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.resetLearningImpl().
ClustreamKernel [] moa.clusterers.clustream.Clustream.kernels [private]
Definition at line 56 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.getMicroClusteringResult(), moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
int moa.clusterers.clustream.Clustream.m [private]
Definition at line 61 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.getMicroClusteringResult(), moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.Clustream.maxNumKernelsOption
Initial value:
 new IntOption(
            "maxNumKernels", 'k',
            "Maximum number of micro kernels to use.", 100)
Definition at line 46 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.resetLearningImpl().
final long moa.clusterers.clustream.Clustream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 41 of file Clustream.java.
double moa.clusterers.clustream.Clustream.t [private]
Definition at line 60 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.getMicroClusteringResult(), moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
long moa.clusterers.clustream.Clustream.timestamp = -1 [private]
Definition at line 55 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
int moa.clusterers.clustream.Clustream.timeWindow [private]
Definition at line 54 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.getName(), moa.clusterers.clustream.Clustream.resetLearningImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
IntOption moa.clusterers.clustream.Clustream.timeWindowOption
Initial value:
 new IntOption("horizon",
            'h', "Rang of the window.", 1000)
Definition at line 43 of file Clustream.java.
Referenced by moa.clusterers.clustream.Clustream.resetLearningImpl().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustream/Clustream.java