MOA: moa.classifiers.rules.core.RuleActiveRegressionNode Class Reference
moa.classifiers.rules.core.RuleActiveRegressionNode Class Reference
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Public Member Functions
Perceptron getPerceptron ()
void setPerceptron (Perceptron perceptron)
TargetMean getTargetMean ()
void setTargetMean (TargetMean targetMean)
RuleActiveRegressionNode (double[] initialClassObservations)
RuleActiveRegressionNode ()
RuleActiveRegressionNode (Rule.Builder builder)
void updateStatistics (Instance instance)
double[] getPrediction (Instance instance, int predictionMode)
double getNormalizedPrediction (Instance instance)
int getLearnerToUse (Instance instance, int predMode)
double computeSD (double squaredVal, double val, long size)
double computeError (Instance instance)
boolean isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly)
void initialize (RuleActiveLearningNode oldLearningNode)
double[] getSimplePrediction ()
boolean tryToExpand (double splitConfidence, double tieThreshold)
void learnFromInstance (Instance inst)
AttributeSplitSuggestion[] getBestSplitSuggestions (SplitCriterion criterion)
double getWeightSeen ()
double getCurrentError ()
Protected Member Functions
void debuganomaly (Instance instance, double uni, double multi, double probability)
Protected Attributes
Perceptron perceptron
TargetMean targetMean
Private Member Functions
double normalize (double value)
Static Private Attributes
static final long serialVersionUID = 1607453624545272049L
Detailed Description
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Definition at line 45 of file RuleActiveRegressionNode.java.
Constructor & Destructor Documentation
moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode (double[] initialClassObservations)
Definition at line 71 of file RuleActiveRegressionNode.java.
{
        super(initialClassObservations);
    }
moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode ()
Definition at line 75 of file RuleActiveRegressionNode.java.
{
        this(new double[0]);
    }
moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode (Rule.Builder builder)
Definition at line 79 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.amRules, moa.classifiers.rules.functions.Perceptron.constantLearningRatioDecayOption, moa.classifiers.rules.functions.Perceptron.learningRatioOption, moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics, moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction, moa.options.AbstractOptionHandler.prepareForUse(), moa.classifiers.rules.functions.TargetMean.reset(), and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        super(builder);
        this.perceptron = new Perceptron();
        this.perceptron.prepareForUse();
        this.perceptron.learningRatioOption = ((AMRulesRegressor)this.amRules).learningRatioOption;
        this.perceptron.constantLearningRatioDecayOption = ((AMRulesRegressor)this.amRules).constantLearningRatioDecayOption;
        if(this.predictionFunction!=1)
        {
            this.targetMean = new TargetMean();
            if (builder.statistics[0]>0)
                this.targetMean.reset(builder.statistics[1]/builder.statistics[0],(long)builder.statistics[0]);
        }
        this.predictionFunction = builder.predictionFunction;
        if (builder.statistics!=null)
            this.nodeStatistics=new DoubleVector(builder.statistics);
    }
Member Function Documentation
double moa.classifiers.rules.core.RuleActiveRegressionNode.computeError (Instance instance) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 189 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction(), and moa.classifiers.rules.core.RuleActiveRegressionNode.normalize().
{
        double normalizedPrediction = getNormalizedPrediction(instance);
        double normalizedClassValue = normalize(instance.classValue());
        return Math.abs(normalizedClassValue - normalizedPrediction);
    }
double moa.classifiers.rules.core.RuleActiveRegressionNode.computeSD (double squaredVal, double val, long size)
Definition at line 181 of file RuleActiveRegressionNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), and moa.classifiers.rules.core.RuleActiveRegressionNode.normalize().
{
        if (size > 1) {
            return Math.sqrt((squaredVal - ((val * val) / size)) / (size - 1.0));
        }
        return 0.0;
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly (Instance instance, double uni, double multi, double probability) [protected]
Definition at line 241 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.computeSD(), moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.functions.Perceptron.getInstancesSeen(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.core.RuleActiveLearningNode.owner, moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, moa.classifiers.rules.core.Rule.ruleNumberID, and moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly().
{
        double atribSum = 0.0;
        double atribSquredSum = 0.0;
        for (int x = 0; x < instance.numAttributes() - 1; x++) {
            int instAttIndex = AMRulesRegressor.modelAttIndexToInstanceAttIndex(x, instance);
            atribSum = perceptron.perceptronattributeStatistics.getValue(x);
            atribSquredSum = perceptron.squaredperceptronattributeStatistics.getValue(x);
            double mean = atribSum / perceptron.getInstancesSeen();
            double sd = computeSD(
                    atribSquredSum,
                    atribSum,
                    perceptron.getInstancesSeen()
                    );
            debug("Attribute : " + x, 5);
            debug("Value : " + instance.value(instAttIndex), 5);
            debug("Mean : " + mean, 5);
            debug("SD : " + sd, 5);
            debug("Probability : " + probability, 5);
            debug("Univariate : " + uni, 5);
            debug("Multivariate : " + multi, 5);
            debug("Anomaly in rule :" + this.owner.ruleNumberID, 5);
        }
    }
AttributeSplitSuggestion [] moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions (SplitCriterion criterion)
Definition at line 391 of file RuleActiveRegressionNode.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.attributeObservers, moa.classifiers.rules.core.RuleActiveLearningNode.bestSuggestion, moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.getBestEvaluatedSplitSuggestion(), and moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
{
        List<AttributeSplitSuggestion> bestSuggestions = new LinkedList<AttributeSplitSuggestion>();
        // Set the nodeStatistics up as the preSplitDistribution, rather than the observedClassDistribution
        double[] nodeSplitDist = this.nodeStatistics.getArrayCopy();
        for (int i = 0; i < this.attributeObservers.size(); i++) {
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs != null) {
                // AT THIS STAGE NON-NUMERIC ATTRIBUTES ARE IGNORED
                AttributeSplitSuggestion bestSuggestion = null;
                if (obs instanceof FIMTDDNumericAttributeClassObserver) {
                    bestSuggestion = obs.getBestEvaluatedSplitSuggestion(criterion, nodeSplitDist, i, true);
                }
                if (bestSuggestion != null) {
                    bestSuggestions.add(bestSuggestion);
                }
            }
        }
        return bestSuggestions.toArray(new AttributeSplitSuggestion[bestSuggestions.size()]);
    }
double moa.classifiers.rules.core.RuleActiveRegressionNode.getCurrentError () [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 426 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.functions.TargetMean.getCurrentError(), moa.classifiers.rules.functions.Perceptron.getCurrentError(), moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        double error;
        if (this.perceptron!=null){
            if (targetMean==null)
                error=perceptron.getCurrentError();
            else{
                double errorP=perceptron.getCurrentError();
                double errorTM=targetMean.getCurrentError();
                error = (errorP<errorTM) ? errorP : errorTM;
            }
        }
        else
            error=Double.MAX_VALUE;
        return error;
    }
int moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse (Instance instance, int predMode) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 152 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.functions.TargetMean.getCurrentError(), moa.classifiers.rules.functions.Perceptron.getCurrentError(), moa.classifiers.rules.functions.TargetMean.getVotesForInstance(), moa.classifiers.rules.core.RuleActiveLearningNode.owner, moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.core.Rule.ruleNumberID, and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction().
{
        int predictionMode = predMode;
        if (predictionMode == 0) {
            double  perceptronError= this.perceptron.getCurrentError();
            double meanTargetError =this.targetMean.getCurrentError();
            debug("\n Check P:" + perceptronError + " M:" + meanTargetError,5);
            debug("Rule" + this.owner.ruleNumberID + " P:" + this.perceptron.getVotesForInstance(instance)[0] + " (" + perceptronError + ")" + " M:" + this.targetMean.getVotesForInstance(instance)[0]+ " (" + meanTargetError + ")",3) ; //Commented by JD
            debug("Observed Value: " + instance.classValue(),5);
            if (perceptronError < meanTargetError) {
                predictionMode = 1; //PERCEPTRON
            } else {
                predictionMode = 2; //TARGET MEAN
            }
        }
        return predictionMode;
    }
double moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction (Instance instance)
Definition at line 118 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), moa.classifiers.rules.functions.TargetMean.getVotesForInstance(), moa.classifiers.rules.core.RuleActiveRegressionNode.normalize(), moa.classifiers.rules.functions.Perceptron.normalizedPrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction, and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.computeError().
{
        double res;
        double [] aux;
        switch (this.predictionFunction) {
        //perceptron - 1
        case 1:
            res=this.perceptron.normalizedPrediction(instance); ;
            break;
            //target mean - 2
        case 2:
            aux=this.targetMean.getVotesForInstance(null);
            res=normalize(aux[0]);
            break;
            //adaptive  - 0
        case 0:
            int predictionMode = this.getLearnerToUse(instance, 0);
            if(predictionMode == 1)
            {
                res=this.perceptron.normalizedPrediction(instance);
            }
            else{
                aux=this.targetMean.getVotesForInstance(instance);
                res = normalize(aux[0]);
            }
            break;
        default:
            throw new UnsupportedOperationException("Prediction mode not in range.");
        }
        return res;
    }
Perceptron moa.classifiers.rules.core.RuleActiveRegressionNode.getPerceptron ()
Definition at line 54 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron.
{
        return perceptron;
    }
double [] moa.classifiers.rules.core.RuleActiveRegressionNode.getPrediction (Instance instance, int predictionMode) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 109 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.functions.TargetMean.getVotesForInstance(), moa.classifiers.rules.functions.Perceptron.getVotesForInstance(), moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        double[] ret = new double[1];
        if (predictionMode == 1)
            ret=this.perceptron.getVotesForInstance(instance);
        else
            ret=this.targetMean.getVotesForInstance(instance);
        return ret;
    }
double [] moa.classifiers.rules.core.RuleActiveRegressionNode.getSimplePrediction () [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 286 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.functions.TargetMean.getVotesForInstance(), and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        if( this.targetMean!=null)
            return this.targetMean.getVotesForInstance(null);
        else
            return new double[]{0};
    }
TargetMean moa.classifiers.rules.core.RuleActiveRegressionNode.getTargetMean ()
Definition at line 62 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        return targetMean;
    }
double moa.classifiers.rules.core.RuleActiveRegressionNode.getWeightSeen ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 417 of file RuleActiveRegressionNode.java.
References moa.core.DoubleVector.getValue(), and moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
{
        if (nodeStatistics != null) {
            return this.nodeStatistics.getValue(0);
        } else {
            return 0;
        }
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.initialize (RuleActiveLearningNode oldLearningNode)
Definition at line 265 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.amRules, moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics, moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.core.DoubleVector.setValue(), and moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean.
{
        if(((RuleActiveRegressionNode) oldLearningNode).perceptron!=null)
        {
            this.perceptron=new Perceptron(((RuleActiveRegressionNode) oldLearningNode).perceptron);
            this.perceptron.resetError();
            this.perceptron.setLearningRatio(((AMRulesRegressor)this.amRules).learningRatioOption.getValue());
        }
        if(((RuleActiveRegressionNode) oldLearningNode).targetMean!=null)
        {
            this.targetMean= new TargetMean(((RuleActiveRegressionNode) oldLearningNode).targetMean);
            this.targetMean.resetError();
        }
        //reset statistics
        this.nodeStatistics.setValue(0, 0);
        this.nodeStatistics.setValue(1, 0);
        this.nodeStatistics.setValue(2, 0);
    }
boolean moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 194 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.computeProbability(), moa.classifiers.rules.core.RuleActiveRegressionNode.computeSD(), moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.functions.Perceptron.getInstancesSeen(), moa.core.DoubleVector.getValue(), moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, and moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics.
{
        //AMRUles is equipped with anomaly detection. If on, compute the anomaly value.
        long perceptronIntancesSeen=this.perceptron.getInstancesSeen();
        if ( perceptronIntancesSeen>= numberOfInstanceesForAnomaly) {
            double atribSum = 0.0;
            double atribSquredSum = 0.0;
            double D = 0.0;
            double N = 0.0;
            double anomaly = 0.0;
            for (int x = 0; x < instance.numAttributes() - 1; x++) {
                // Perceptron is initialized each rule.
                // this is a local anomaly.
                int instAttIndex = AMRulesRegressor.modelAttIndexToInstanceAttIndex(x, instance);
                atribSum = this.perceptron.perceptronattributeStatistics.getValue(x);
                atribSquredSum = this.perceptron.squaredperceptronattributeStatistics.getValue(x);
                double mean = atribSum / perceptronIntancesSeen;
                double sd = computeSD(atribSquredSum, atribSum, perceptronIntancesSeen);
                double probability = computeProbability(mean, sd, instance.value(instAttIndex));
                if (probability > 0.0) {
                    D = D + Math.abs(Math.log(probability));
                    if (probability < uniVariateAnomalyProbabilityThreshold) {//0.10
                        N = N + Math.abs(Math.log(probability));
                    }
                } else {
                    debug("Anomaly with probability 0 in atribute : " + x, 4);
                }
            }
            anomaly = 0.0;
            if (D != 0.0) {
                anomaly = N / D;
            }
            if (anomaly >= multiVariateAnomalyProbabilityThreshold) {
                debuganomaly(instance,
                        uniVariateAnomalyProbabilityThreshold,
                        multiVariateAnomalyProbabilityThreshold,
                        anomaly);
                return true;
            }
        }
        return false;
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.learnFromInstance (Instance inst) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 363 of file RuleActiveRegressionNode.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.attributeObservers, moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver(), and moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
{
        // Update the statistics for this node
        // number of instances passing through the node
        nodeStatistics.addToValue(0, 1);
        // sum of y values
        nodeStatistics.addToValue(1, inst.classValue());
        // sum of squared y values
        nodeStatistics.addToValue(2, inst.classValue()*inst.classValue());
        for (int i = 0; i < inst.numAttributes() - 1; i++) {
            int instAttIndex = AbstractAMRules.modelAttIndexToInstanceAttIndex(i, inst);
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs == null) {
                // At this stage all nominal attributes are ignored
                if (inst.attribute(instAttIndex).isNumeric()) //instAttIndex
                {
                    obs = newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
            }
            if (obs != null) {
                ((FIMTDDNumericAttributeClassObserver) obs).observeAttributeClass(inst.value(instAttIndex), inst.classValue(), inst.weight());
            }
        }
    }
double moa.classifiers.rules.core.RuleActiveRegressionNode.normalize (double value) [private]
Definition at line 170 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.computeSD(), moa.core.DoubleVector.getValue(), and moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.computeError(), and moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction().
{
        double meanY = this.nodeStatistics.getValue(1)/this.nodeStatistics.getValue(0);
        double sdY = computeSD(this.nodeStatistics.getValue(2), this.nodeStatistics.getValue(1), (long)this.nodeStatistics.getValue(0));
        double normalizedY = 0.0;
        if (sdY > 0.0000001) {
            normalizedY = (value - meanY) / (sdY);
        }
        return normalizedY;
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.setPerceptron (Perceptron perceptron)
Definition at line 58 of file RuleActiveRegressionNode.java.
{
        this.perceptron = perceptron;
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.setTargetMean (TargetMean targetMean)
Definition at line 66 of file RuleActiveRegressionNode.java.
{
        this.targetMean = targetMean;
    }
boolean moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand (double splitConfidence, double tieThreshold) [virtual]
Implements moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 294 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.bestSuggestion, moa.classifiers.rules.core.RuleActiveLearningNode.computeHoeffdingBound(), moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions(), moa.classifiers.rules.core.RuleActiveRegressionNode.getWeightSeen(), moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributions, moa.classifiers.rules.core.RuleActiveLearningNode.splitIndex, moa.classifiers.rules.core.RuleActiveLearningNode.statisticsBranchSplit, moa.classifiers.rules.core.RuleActiveLearningNode.statisticsNewRuleActiveLearningNode, and moa.classifiers.rules.core.RuleActiveLearningNode.statisticsOtherBranchSplit.
{
        // splitConfidence. Hoeffding Bound test parameter.
        // tieThreshold. Hoeffding Bound test parameter.
        SplitCriterion splitCriterion = new SDRSplitCriterionAMRules();
            //SplitCriterion splitCriterion = new SDRSplitCriterionAMRulesNode();//JD for assessing only best branch
        // Using this criterion, find the best split per attribute and rank the results
        AttributeSplitSuggestion[] bestSplitSuggestions
        = this.getBestSplitSuggestions(splitCriterion);
        Arrays.sort(bestSplitSuggestions);
        // Declare a variable to determine if any of the splits should be performed
        boolean shouldSplit = false;
        // If only one split was returned, use it
        if (bestSplitSuggestions.length < 2) {
            shouldSplit = ((bestSplitSuggestions.length > 0) && (bestSplitSuggestions[0].merit > 0));
            bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
        } // Otherwise, consider which of the splits proposed may be worth trying
        else {
            // Determine the hoeffding bound value, used to select how many instances should be used to make a test decision
            // to feel reasonably confident that the test chosen by this sample is the same as what would be chosen using infinite examples
            double hoeffdingBound = computeHoeffdingBound(1, splitConfidence, getWeightSeen());
            debug("Hoeffding bound " + hoeffdingBound, 4);
            // Determine the top two ranked splitting suggestions
            bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
            AttributeSplitSuggestion secondBestSuggestion
            = bestSplitSuggestions[bestSplitSuggestions.length - 2];
            debug("Merits: " + secondBestSuggestion.merit + " " + bestSuggestion.merit, 4);
            // If the upper bound of the sample mean for the ratio of SDR(best suggestion) to SDR(second best suggestion),
            // as determined using the hoeffding bound, is less than 1, then the true mean is also less than 1, and thus at this
            // particular moment of observation the bestSuggestion is indeed the best split option with confidence 1-delta, and
            // splitting should occur.
            // Alternatively, if two or more splits are very similar or identical in terms of their splits, then a threshold limit
            // (default 0.05) is applied to the hoeffding bound; if the hoeffding bound is smaller than this limit then the two
            // competing attributes are equally good, and the split will be made on the one with the higher SDR value.
            if (bestSuggestion.merit > 0) {
                if ((((secondBestSuggestion.merit / bestSuggestion.merit) + hoeffdingBound) < 1)
                        || (hoeffdingBound < tieThreshold)) {
                    debug("Expanded ", 5);
                    shouldSplit = true;
                }
            }
        }
        if (shouldSplit == true) {
            AttributeSplitSuggestion splitDecision = bestSplitSuggestions[bestSplitSuggestions.length - 1];
            double minValue = Double.MAX_VALUE;
             double[] branchMerits = SDRSplitCriterionAMRules.computeBranchSplitMerits(bestSuggestion.resultingClassDistributions);
            for (int i = 0; i < bestSuggestion.numSplits(); i++) {
                double value = branchMerits[i];
                if (value < minValue) {
                    minValue = value;
                    splitIndex = i;
                    statisticsNewRuleActiveLearningNode = bestSuggestion.resultingClassDistributionFromSplit(i);
                }
            }
            statisticsBranchSplit = splitDecision.resultingClassDistributionFromSplit(splitIndex);
            statisticsOtherBranchSplit = bestSuggestion.resultingClassDistributionFromSplit(splitIndex == 0 ? 1 : 0);
        }
        return shouldSplit;
    }
void moa.classifiers.rules.core.RuleActiveRegressionNode.updateStatistics (Instance instance)
Reimplemented from moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 101 of file RuleActiveRegressionNode.java.
References moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron, moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction, moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean, and moa.classifiers.AbstractClassifier.trainOnInstance().
{
        super.updateStatistics(instance);
        this.perceptron.trainOnInstance(instance);
        if (this.predictionFunction != 1) { //Train target mean if prediction function is not Perceptron
            this.targetMean.trainOnInstance(instance);
        }
    }
Member Data Documentation
Perceptron moa.classifiers.rules.core.RuleActiveRegressionNode.perceptron [protected]
Definition at line 52 of file RuleActiveRegressionNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.getCurrentError(), moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.getPerceptron(), moa.classifiers.rules.core.RuleActiveRegressionNode.getPrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.initialize(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.updateStatistics().
final long moa.classifiers.rules.core.RuleActiveRegressionNode.serialVersionUID = 1607453624545272049L [static, private]
Reimplemented from moa.classifiers.rules.core.RuleActiveLearningNode.
Definition at line 50 of file RuleActiveRegressionNode.java.
TargetMean moa.classifiers.rules.core.RuleActiveRegressionNode.targetMean [protected]
Definition at line 70 of file RuleActiveRegressionNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getCurrentError(), moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.getPrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.getSimplePrediction(), moa.classifiers.rules.core.RuleActiveRegressionNode.getTargetMean(), moa.classifiers.rules.core.RuleActiveRegressionNode.initialize(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.updateStatistics().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/RuleActiveRegressionNode.java