MOA: moa.clusterers.AbstractClusterer Class Reference
moa.clusterers.AbstractClusterer Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
AbstractClusterer ()
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void setModelContext (InstancesHeader ih)
InstancesHeader getModelContext ()
void setRandomSeed (int s)
boolean trainingHasStarted ()
double trainingWeightSeenByModel ()
void resetLearning ()
void trainOnInstance (Instance inst)
Measurement[] getModelMeasurements ()
void getDescription (StringBuilder out, int indent)
Returns a string representation of this object.
Clusterer[] getSubClusterers ()
Clusterer copy ()
This method produces a copy of this object.
String getClassNameString ()
String getClassLabelString (int classLabelIndex)
String getAttributeNameString (int attIndex)
String getNominalValueString (int attIndex, int valIndex)
AWTRenderer getAWTRenderer ()
abstract void resetLearningImpl ()
abstract void trainOnInstanceImpl (Instance inst)
abstract void getModelDescription (StringBuilder out, int indent)
boolean implementsMicroClusterer ()
boolean keepClassLabel ()
Clustering getMicroClusteringResult ()
Static Public Member Functions
static boolean contextIsCompatible (InstancesHeader originalContext, InstancesHeader newContext)
Public Attributes
FlagOption evaluateMicroClusteringOption
Protected Member Functions
abstract Measurement[] getModelMeasurementsImpl ()
Static Protected Member Functions
static int modelAttIndexToInstanceAttIndex (int index, Instance inst)
static int modelAttIndexToInstanceAttIndex (int index, Instances insts)
Protected Attributes
InstancesHeader modelContext
double trainingWeightSeenByModel = 0.0
int randomSeed = 1
IntOption randomSeedOption
Random clustererRandom
Clustering clustering
Detailed Description
Definition at line 39 of file AbstractClusterer.java.
Constructor & Destructor Documentation
moa.clusterers.AbstractClusterer.AbstractClusterer ()
Definition at line 61 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.evaluateMicroClusteringOption, moa.clusterers.AbstractClusterer.implementsMicroClusterer(), moa.clusterers.Clusterer.isRandomizable(), and moa.clusterers.AbstractClusterer.randomSeedOption.
{
        if (isRandomizable()) {
            this.randomSeedOption = new IntOption("randomSeed", 'r',
                    "Seed for random behaviour of the Clusterer.", 1);
        }
        if( implementsMicroClusterer()){
            this.evaluateMicroClusteringOption =
                    new FlagOption("evaluateMicroClustering", 'M',
                    "Evaluate the underlying microclustering instead of the macro clustering");
        }
    }
Member Function Documentation
static boolean moa.clusterers.AbstractClusterer.contextIsCompatible (InstancesHeader originalContext, InstancesHeader newContext) [static]
Definition at line 217 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.setModelContext().
{
        // rule 1: num classes can increase but never decrease
        // rule 2: num attributes can increase but never decrease
        // rule 3: num nominal attribute values can increase but never decrease
        // rule 4: attribute types must stay in the same order (although class
        // can
        // move; is always skipped over)
        // attribute names are free to change, but should always still represent
        // the original attributes
        if (newContext.numClasses() < originalContext.numClasses()) {
            return false; // rule 1
        }
        if (newContext.numAttributes() < originalContext.numAttributes()) {
            return false; // rule 2
        }
        int oPos = 0;
        int nPos = 0;
        while (oPos < originalContext.numAttributes()) {
            if (oPos == originalContext.classIndex()) {
                oPos++;
                if (!(oPos < originalContext.numAttributes())) {
                    break;
                }
            }
            if (nPos == newContext.classIndex()) {
                nPos++;
            }
            if (originalContext.attribute(oPos).isNominal()) {
                if (!newContext.attribute(nPos).isNominal()) {
                    return false; // rule 4
                }
                if (newContext.attribute(nPos).numValues() < originalContext
                        .attribute(oPos).numValues()) {
                    return false; // rule 3
                }
            } else {
                assert (originalContext.attribute(oPos).isNumeric());
                if (!newContext.attribute(nPos).isNumeric()) {
                    return false; // rule 4
                }
            }
            oPos++;
            nPos++;
        }
        return true; // all checks clear
    }
Clusterer moa.clusterers.AbstractClusterer.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Implements moa.clusterers.Clusterer.
Definition at line 187 of file AbstractClusterer.java.
References moa.clusterers.Clusterer.copy().
{
        return (Clusterer) super.copy();
    }
String moa.clusterers.AbstractClusterer.getAttributeNameString (int attIndex)
Definition at line 205 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.modelContext.
{
        return InstancesHeader.getAttributeNameString(this.modelContext,
                attIndex);
    }
AWTRenderer moa.clusterers.AbstractClusterer.getAWTRenderer ()
Implements moa.gui.AWTRenderable.
Definition at line 265 of file AbstractClusterer.java.
{
        // TODO should return a default renderer here
        // - or should null be interpreted as the default?
        return null;
    }
String moa.clusterers.AbstractClusterer.getClassLabelString (int classLabelIndex)
Definition at line 200 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.modelContext.
{
        return InstancesHeader.getClassLabelString(this.modelContext,
                classLabelIndex);
    }
String moa.clusterers.AbstractClusterer.getClassNameString ()
Definition at line 196 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.modelContext.
{
        return InstancesHeader.getClassNameString(this.modelContext);
    }
void moa.clusterers.AbstractClusterer.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 166 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.getModelDescription(), moa.clusterers.AbstractClusterer.getModelMeasurements(), and moa.clusterers.AbstractClusterer.trainingHasStarted().
{
        StringUtils.appendIndented(out, indent, "Model type: ");
        out.append(this.getClass().getName());
        StringUtils.appendNewline(out);
        Measurement.getMeasurementsDescription(getModelMeasurements(), out,
                indent);
        StringUtils.appendNewlineIndented(out, indent, "Model description:");
        StringUtils.appendNewline(out);
        if (trainingHasStarted()) {
            getModelDescription(out, indent);
        } else {
            StringUtils.appendIndented(out, indent,
                    "Model has not been trained.");
        }
    }
Clustering moa.clusterers.AbstractClusterer.getMicroClusteringResult ()
Implements moa.clusterers.Clusterer.
Reimplemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.denstream.WithDBSCAN, and moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 301 of file AbstractClusterer.java.
Referenced by moa.gui.visualization.RunVisualizer.processClusterings(), and moa.gui.BatchCmd.run().
{
            return null;
        };
InstancesHeader moa.clusterers.AbstractClusterer.getModelContext ()
Implements moa.clusterers.Clusterer.
Definition at line 100 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.modelContext.
{
        return this.modelContext;
    }
abstract void moa.clusterers.AbstractClusterer.getModelDescription (StringBuilder out, int indent) [pure virtual]
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.clusterers.AbstractClusterer.getDescription().
Measurement [] moa.clusterers.AbstractClusterer.getModelMeasurements ()
Implements moa.clusterers.Clusterer.
Definition at line 135 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.getModelMeasurementsImpl(), moa.clusterers.AbstractClusterer.getSubClusterers(), moa.AbstractMOAObject.measureByteSize(), and moa.clusterers.AbstractClusterer.trainingWeightSeenByModel().
Referenced by moa.clusterers.AbstractClusterer.getDescription().
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        measurementList.add(new Measurement("model training instances",
                trainingWeightSeenByModel()));
        measurementList.add(new Measurement("model serialized size (bytes)",
                measureByteSize()));
        Measurement[] modelMeasurements = getModelMeasurementsImpl();
        if (modelMeasurements != null) {
            for (Measurement measurement : modelMeasurements) {
                measurementList.add(measurement);
            }
        }
        // add average of sub-model measurements
        Clusterer[] subModels = getSubClusterers();
        if ((subModels != null) && (subModels.length > 0)) {
            List<Measurement[]> subMeasurements = new LinkedList<Measurement[]>();
            for (Clusterer subModel : subModels) {
                if (subModel != null) {
                    subMeasurements.add(subModel.getModelMeasurements());
                }
            }
            Measurement[] avgMeasurements = Measurement
                    .averageMeasurements(subMeasurements
                            .toArray(new Measurement[subMeasurements.size()][]));
            for (Measurement measurement : avgMeasurements) {
                measurementList.add(measurement);
            }
        }
        return measurementList.toArray(new Measurement[measurementList.size()]);
    }
abstract Measurement [] moa.clusterers.AbstractClusterer.getModelMeasurementsImpl () [protected, pure virtual]
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.clusterers.AbstractClusterer.getModelMeasurements().
String moa.clusterers.AbstractClusterer.getNominalValueString (int attIndex, int valIndex)
Definition at line 210 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.modelContext.
{
        return InstancesHeader.getNominalValueString(this.modelContext,
                attIndex, valIndex);
    }
String moa.clusterers.AbstractClusterer.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.clusterers.outliers.AnyOut.AnyOut, and moa.clusterers.WekaClusteringAlgorithm.
Definition at line 43 of file AbstractClusterer.java.
{
        return "MOA Clusterer: " + getClass().getCanonicalName();
    }
Clusterer [] moa.clusterers.AbstractClusterer.getSubClusterers ()
Implements moa.clusterers.Clusterer.
Definition at line 182 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.getModelMeasurements().
{
        return null;
    }
boolean moa.clusterers.AbstractClusterer.implementsMicroClusterer ()
Implements moa.clusterers.Clusterer.
Reimplemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.denstream.WithDBSCAN, and moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 293 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.AbstractClusterer(), moa.gui.visualization.RunVisualizer.processClusterings(), moa.gui.BatchCmd.run(), and moa.gui.visualization.RunVisualizer.weka().
{
            return false;
        }
boolean moa.clusterers.AbstractClusterer.keepClassLabel ()
Implements moa.clusterers.Clusterer.
Reimplemented in moa.clusterers.ClusterGenerator, moa.clusterers.outliers.MyBaseOutlierDetector, and moa.clusterers.WekaClusteringAlgorithm.
Definition at line 297 of file AbstractClusterer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
            return false;
        }
static int moa.clusterers.AbstractClusterer.modelAttIndexToInstanceAttIndex (int index, Instances insts) [static, protected]
Definition at line 288 of file AbstractClusterer.java.
{
        return insts.classIndex() > index ? index : index + 1;
    }
static int moa.clusterers.AbstractClusterer.modelAttIndexToInstanceAttIndex (int index, Instance inst) [static, protected]
Definition at line 283 of file AbstractClusterer.java.
{
        return inst.classIndex() > index ? index : index + 1;
    }
void moa.clusterers.AbstractClusterer.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 75 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.clustering, moa.options.IntOption.getValue(), moa.clusterers.AbstractClusterer.randomSeed, moa.clusterers.AbstractClusterer.randomSeedOption, moa.clusterers.AbstractClusterer.resetLearning(), and moa.clusterers.AbstractClusterer.trainingHasStarted().
{
        if (this.randomSeedOption != null) {
            this.randomSeed = this.randomSeedOption.getValue();
        }
        if (!trainingHasStarted()) {
            resetLearning();
        }
                clustering = new Clustering();
    }
void moa.clusterers.AbstractClusterer.resetLearning ()
Implements moa.clusterers.Clusterer.
Reimplemented in moa.clusterers.outliers.AnyOut.AnyOutCore.
Definition at line 120 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.clustererRandom, moa.clusterers.Clusterer.isRandomizable(), moa.clusterers.AbstractClusterer.randomSeed, moa.clusterers.AbstractClusterer.resetLearningImpl(), and moa.clusterers.AbstractClusterer.trainingWeightSeenByModel().
Referenced by moa.clusterers.AbstractClusterer.prepareForUseImpl().
{
        this.trainingWeightSeenByModel = 0.0;
        if (isRandomizable()) {
            this.clustererRandom = new Random(this.randomSeed);
        }
        resetLearningImpl();
    }
abstract void moa.clusterers.AbstractClusterer.resetLearningImpl () [pure virtual]
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.clusterers.AbstractClusterer.resetLearning().
void moa.clusterers.AbstractClusterer.setModelContext (InstancesHeader ih)
Implements moa.clusterers.Clusterer.
Definition at line 86 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.contextIsCompatible(), moa.clusterers.AbstractClusterer.modelContext, and moa.clusterers.AbstractClusterer.trainingHasStarted().
Referenced by moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), and moa.clusterers.outliers.AbstractC.Test.main().
{
        if ((ih != null) && (ih.classIndex() < 0)) {
            throw new IllegalArgumentException(
                    "Context for a Clusterer must include a class to learn");
        }
        if (trainingHasStarted()
                && (this.modelContext != null)
                && ((ih == null) || !contextIsCompatible(this.modelContext, ih))) {
            throw new IllegalArgumentException(
                    "New context is not compatible with existing model");
        }
        this.modelContext = ih;
    }
void moa.clusterers.AbstractClusterer.setRandomSeed (int s)
Implements moa.clusterers.Clusterer.
Definition at line 104 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.randomSeed, moa.clusterers.AbstractClusterer.randomSeedOption, and moa.options.IntOption.setValue().
{
        this.randomSeed = s;
        if (this.randomSeedOption != null) {
            // keep option consistent
            this.randomSeedOption.setValue(s);
        }
    }
boolean moa.clusterers.AbstractClusterer.trainingHasStarted ()
Implements moa.clusterers.Clusterer.
Definition at line 112 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.trainingWeightSeenByModel().
Referenced by moa.clusterers.AbstractClusterer.getDescription(), moa.clusterers.AbstractClusterer.prepareForUseImpl(), and moa.clusterers.AbstractClusterer.setModelContext().
{
        return this.trainingWeightSeenByModel > 0.0;
    }
double moa.clusterers.AbstractClusterer.trainingWeightSeenByModel ()
Implements moa.clusterers.Clusterer.
Definition at line 116 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.getModelMeasurements(), moa.clusterers.AbstractClusterer.resetLearning(), moa.clusterers.AbstractClusterer.trainingHasStarted(), and moa.clusterers.AbstractClusterer.trainOnInstance().
{
        return this.trainingWeightSeenByModel;
    }
void moa.clusterers.AbstractClusterer.trainOnInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 128 of file AbstractClusterer.java.
References moa.clusterers.AbstractClusterer.trainingWeightSeenByModel(), and moa.clusterers.AbstractClusterer.trainOnInstanceImpl().
{
        if (inst.weight() > 0.0) {
            this.trainingWeightSeenByModel += inst.weight();
            trainOnInstanceImpl(inst);
        }
    }
abstract void moa.clusterers.AbstractClusterer.trainOnInstanceImpl (Instance inst) [pure virtual]
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.gui.BatchCmd.run(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.clusterers.AbstractClusterer.trainOnInstance().
Member Data Documentation
Random moa.clusterers.AbstractClusterer.clustererRandom [protected]
Reimplemented in moa.clusterers.streamkm.StreamKM.
Definition at line 57 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.resetLearning().
Clustering moa.clusterers.AbstractClusterer.clustering [protected]
Definition at line 59 of file AbstractClusterer.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.clusterers.WekaClusteringAlgorithm.getClusteringResult(), moa.clusterers.streamkm.StreamKM.getClusteringResult(), moa.clusterers.clustream.WithKmeans.kMeans(), moa.clusterers.clustream.Clustream.kMeans(), and moa.clusterers.AbstractClusterer.prepareForUseImpl().
FlagOption moa.clusterers.AbstractClusterer.evaluateMicroClusteringOption
Definition at line 55 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.AbstractClusterer(), moa.gui.visualization.RunVisualizer.processClusterings(), moa.gui.BatchCmd.run(), and moa.gui.visualization.RunVisualizer.weka().
InstancesHeader moa.clusterers.AbstractClusterer.modelContext [protected]
Definition at line 47 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.getAttributeNameString(), moa.clusterers.AbstractClusterer.getClassLabelString(), moa.clusterers.AbstractClusterer.getClassNameString(), moa.clusterers.AbstractClusterer.getModelContext(), moa.clusterers.AbstractClusterer.getNominalValueString(), and moa.clusterers.AbstractClusterer.setModelContext().
int moa.clusterers.AbstractClusterer.randomSeed = 1 [protected]
Definition at line 51 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.prepareForUseImpl(), moa.clusterers.AbstractClusterer.resetLearning(), and moa.clusterers.AbstractClusterer.setRandomSeed().
IntOption moa.clusterers.AbstractClusterer.randomSeedOption [protected]
Reimplemented in moa.clusterers.CobWeb, and moa.clusterers.streamkm.StreamKM.
Definition at line 53 of file AbstractClusterer.java.
Referenced by moa.clusterers.AbstractClusterer.AbstractClusterer(), moa.clusterers.AbstractClusterer.prepareForUseImpl(), and moa.clusterers.AbstractClusterer.setRandomSeed().
double moa.clusterers.AbstractClusterer.trainingWeightSeenByModel = 0.0 [protected]
Definition at line 49 of file AbstractClusterer.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/AbstractClusterer.java