MOA: moa.cluster.Miniball Class Reference
moa.cluster.Miniball Class Reference
Java Porting of the Miniball.h code of Bernd Gaertner.
Classes
class Miniball_b
class pvt
Public Member Functions
Miniball (int dim)
void clear ()
Method clear: clears the ArrayList of the selection points.
void check_in (double[] p)
Adds a point to the list.
void build ()
Recalculate Miniball parameter Center and Radius.
double[] center ()
Return the center of the Miniball.
double squared_radius ()
Return the sqaured Radius of the miniball.
double radius ()
Return the Radius of the miniball.
int nr_points ()
Return the actual number of points in the list.
int nr_support_points ()
Return the number of support points (used to calculate the miniball).
Package Functions
void mtf_mb (int i)
void move_to_front (int j)
void pivot_mb (int i)
double max_excess (int t, int i, pvt pivot)
int points_begin ()
int points_end ()
int support_points_begin ()
int support_points_end ()
double accuracy (double slack)
boolean is_valid (double tolerance)
double mb_sqr (double r)
Package Attributes
int d
ArrayList L
Miniball_b B
int support_end = 0
Detailed Description
Java Porting of the Miniball.h code of Bernd Gaertner.
Look at http://www.inf.ethz.ch/personal/gaertner/miniball.html
and related work at http://www.inf.ethz.ch/personal/gaertner/texts/own_work/esa99_final.pdf
for reading about the algorithm and the implementation of it.
If interested in Bounding Sphere algorithms read also published work of Emo Welzl "Smallest enclosing disks (balls and Ellipsoid)" and the work of Jack Ritter on "Efficient Bounding Spheres" at
http://tog.acm.org/GraphicsGems/gems/BoundSphere.c?searchterm=calc
For Licencing Info report to Bernd Gaertner's one reported below:
Copright (C) 1999-2006, Bernd Gaertner
Revision
1.3
Date
2006/11/16 08:01:52
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA,
or download the License terms from prep.ai.mit.edu/pub/gnu/COPYING-2.0.
Contact:
--------
Bernd Gaertner
Institute of Theoretical Computer Science
ETH Zuerich
CAB G32.2
CH-8092 Zuerich, Switzerland
http://www.inf.ethz.ch/personal/gaertner
Original Java port from Paolo Perissinotto for Jpatch Project by Sascha Ledinsky found at http://forum.jpatch.com/viewtopic.php?f=3&t=919
Author:
Paolo Perissinotto for Jpatch Project by Sascha Ledinsky
Version:
1.0 { Date: 2007/11/18 21:57}
used for moa for calculating most compact sphere cluster modified by Timm Jansen (moa@cs.rwth-aachen.de) to be used with high dimensional points
Definition at line 61 of file Miniball.java.
Constructor & Destructor Documentation
moa.cluster.Miniball.Miniball (int dim)
Definition at line 68 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.d, and moa.cluster.Miniball.L.
{
        d = dim;
        L = new ArrayList();
        B = new Miniball_b();
    }
Member Function Documentation
double moa.cluster.Miniball.accuracy (double slack) [package]
Definition at line 393 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.L, moa.cluster.Miniball.nr_support_points(), moa.cluster.Miniball.points_begin(), moa.cluster.Miniball.points_end(), moa.cluster.Miniball.Miniball_b.slack(), moa.cluster.Miniball.squared_radius(), and moa.cluster.Miniball.support_end.
Referenced by moa.cluster.Miniball.is_valid().
{
        double e, max_e = 0;
        int n_supp = 0;
        int i;
        for (i = points_begin(); i != support_end; ++i, ++n_supp) {
            double[] sp = (double[]) L.get(i);
            if ((e = Math.abs(B.excess(sp))) > max_e) {
                max_e = e;
            }
        }
        if (n_supp == nr_support_points()) {
            System.out.println("Miniball.accuracy WARNING: STRANGE PROBLEM HERE!");
        }
        for (i = support_end; i != points_end(); ++i) {
            double[] sp = (double[]) L.get(i);
            if ((e = B.excess(sp)) > max_e) {
                max_e = e;
            }
        }
        slack = B.slack();
        return (max_e / squared_radius());
    }
void moa.cluster.Miniball.build ()
Recalculate Miniball parameter Center and Radius.
Definition at line 258 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.pivot_mb(), moa.cluster.Miniball.points_end(), moa.cluster.Miniball.Miniball_b.reset(), and moa.cluster.Miniball.support_end.
Referenced by moa.cluster.SphereCluster.SphereCluster().
{
        B.reset();
        support_end = 0;
        pivot_mb(points_end());
    }
double [] moa.cluster.Miniball.center ()
Return the center of the Miniball.
Returns:
The center (double[])
Definition at line 340 of file Miniball.java.
References moa.cluster.Miniball.B, and moa.cluster.Miniball.Miniball_b.getCenter().
Referenced by moa.cluster.SphereCluster.SphereCluster().
{
        return B.getCenter();
    }
void moa.cluster.Miniball.check_in (double[] p)
Adds a point to the list.
Skip action on null parameter.
Parameters:
p The object to be added to the list
Definition at line 245 of file Miniball.java.
References moa.cluster.Miniball.L.
Referenced by moa.cluster.SphereCluster.SphereCluster().
{
        if (p != null) {
            L.add(p);
        } else {
            System.out.println("Miniball.check_in WARNING: Skipping null point");
        }
    }
void moa.cluster.Miniball.clear ()
Method clear: clears the ArrayList of the selection points.
Use it for starting a new selection list to calculate Bounding Sphere on
or to clear memory references to the list of objects.
Always use at the end of a Miniball use if you want to reuse later the Miniball object
Definition at line 236 of file Miniball.java.
References moa.cluster.Miniball.L.
Referenced by moa.cluster.SphereCluster.SphereCluster().
{
        L.clear();
    }
boolean moa.cluster.Miniball.is_valid (double tolerance) [package]
Definition at line 417 of file Miniball.java.
References moa.cluster.Miniball.accuracy().
{
        double slack = 0.0;
        return ((accuracy(slack) < tolerance) && (slack == 0));
    }
double moa.cluster.Miniball.max_excess (int t, int i, pvt pivot) [package]
Definition at line 317 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.d, moa.cluster.Miniball.Miniball_b.getCenter(), moa.cluster.Miniball.L, moa.cluster.Miniball.mb_sqr(), moa.cluster.Miniball.pvt.setVal(), and moa.cluster.Miniball.Miniball_b.squared_radius().
Referenced by moa.cluster.Miniball.pivot_mb().
{
        double[] c = B.getCenter();
        double sqr_r = B.squared_radius();
        double e, max_e = 0;
        for (int k = t; k != i; ++k) {
            double[] p = (double[]) L.get(k);
            e = -sqr_r;
            for (int j = 0; j < d; ++j) {
                e += mb_sqr(p[j] - c[j]);
            }
            if (e > max_e) {
                max_e = e;
                pivot.setVal(k);
            }
        }
        return max_e;
    }
double moa.cluster.Miniball.mb_sqr (double r) [package]
Definition at line 422 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.max_excess(), and moa.cluster.Miniball.Miniball_b.push().
{
        return r * r;
    }
void moa.cluster.Miniball.move_to_front (int j) [package]
Definition at line 284 of file Miniball.java.
References moa.cluster.Miniball.L, and moa.cluster.Miniball.support_end.
Referenced by moa.cluster.Miniball.mtf_mb(), and moa.cluster.Miniball.pivot_mb().
{
        if (support_end <= j) {
            support_end++;
        }
        //   L.splice (L.begin(), L, j);
        double[] sp = (double[]) L.get(j);
        L.remove(j);
        L.add(0, sp);
    }
void moa.cluster.Miniball.mtf_mb (int i) [package]
Definition at line 264 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.d, moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.L, moa.cluster.Miniball.move_to_front(), moa.cluster.Miniball.points_begin(), moa.cluster.Miniball.Miniball_b.pop(), moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.size(), and moa.cluster.Miniball.support_end.
Referenced by moa.cluster.Miniball.pivot_mb().
                       {
        int pj = 0;
        support_end = points_begin();
        if ((B.size()) == d + 1) {
            return;
        }
        for (int k = points_begin(); k != i;) {
            pj = pj + 1;
            int j = k++;
            double[] sp = (double[]) L.get(j);
            if (B.excess(sp) > 0) {
                if (B.push(sp)) {
                    mtf_mb(j);
                    B.pop();
                    move_to_front(j);
                }
            }
        }
    }
int moa.cluster.Miniball.nr_points ()
Return the actual number of points in the list.
Returns:
the actual number of points
Definition at line 364 of file Miniball.java.
References moa.cluster.Miniball.L.
{
        return L.size();
    }
int moa.cluster.Miniball.nr_support_points ()
Return the number of support points (used to calculate the miniball).
It's and internal info
Returns:
the number of support points
Definition at line 381 of file Miniball.java.
References moa.cluster.Miniball.B, and moa.cluster.Miniball.Miniball_b.support_size().
Referenced by moa.cluster.Miniball.accuracy().
{
        return B.support_size();
    }
void moa.cluster.Miniball.pivot_mb (int i) [package]
Definition at line 295 of file Miniball.java.
References moa.cluster.Miniball.B, moa.cluster.Miniball.pvt.getVal(), moa.cluster.Miniball.L, moa.cluster.Miniball.max_excess(), moa.cluster.Miniball.move_to_front(), moa.cluster.Miniball.mtf_mb(), moa.cluster.Miniball.Miniball_b.pop(), moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.squared_radius(), and moa.cluster.Miniball.support_end.
Referenced by moa.cluster.Miniball.build().
{
        int t = 1;
        mtf_mb(t);
        double max_e = 0.0, old_sqr_r = -1;
        pvt pivot = new pvt();
        do {
            max_e = max_excess(t, i, pivot);
            if (max_e > 0) {
                t = support_end;
                if (t == pivot.getVal()) {
                    ++t;
                }
                old_sqr_r = B.squared_radius();
                double[] sp = (double[]) L.get(pivot.getVal());
                B.push(sp);
                mtf_mb(support_end);
                B.pop();
                move_to_front(pivot.getVal());
            }
        } while ((max_e > 0) && (B.squared_radius() > old_sqr_r));
    }
int moa.cluster.Miniball.points_begin () [package]
Definition at line 368 of file Miniball.java.
Referenced by moa.cluster.Miniball.accuracy(), and moa.cluster.Miniball.mtf_mb().
                       {
        return (0);
    }
int moa.cluster.Miniball.points_end () [package]
Definition at line 372 of file Miniball.java.
References moa.cluster.Miniball.L.
Referenced by moa.cluster.Miniball.accuracy(), and moa.cluster.Miniball.build().
                     {
        return (L.size());
    }
double moa.cluster.Miniball.radius ()
Return the Radius of the miniball.
Returns:
The radius
Definition at line 356 of file Miniball.java.
References moa.cluster.Miniball.B, and moa.cluster.Miniball.Miniball_b.squared_radius().
Referenced by moa.cluster.SphereCluster.SphereCluster().
{
        return ((1 + 0.00001) * Math.sqrt(B.squared_radius()));
    }
double moa.cluster.Miniball.squared_radius ()
Return the sqaured Radius of the miniball.
Returns:
The square radius
Definition at line 348 of file Miniball.java.
References moa.cluster.Miniball.B, and moa.cluster.Miniball.Miniball_b.squared_radius().
Referenced by moa.cluster.Miniball.accuracy().
{
        return B.squared_radius();
    }
int moa.cluster.Miniball.support_points_begin () [package]
Definition at line 385 of file Miniball.java.
{
        return (0);
    }
int moa.cluster.Miniball.support_points_end () [package]
Definition at line 389 of file Miniball.java.
References moa.cluster.Miniball.support_end.
{
        return support_end;
    }
Member Data Documentation
Miniball_b moa.cluster.Miniball.B [package]
Definition at line 65 of file Miniball.java.
Referenced by moa.cluster.Miniball.accuracy(), moa.cluster.Miniball.build(), moa.cluster.Miniball.center(), moa.cluster.Miniball.max_excess(), moa.cluster.Miniball.Miniball(), moa.cluster.Miniball.mtf_mb(), moa.cluster.Miniball.nr_support_points(), moa.cluster.Miniball.pivot_mb(), moa.cluster.Miniball.radius(), and moa.cluster.Miniball.squared_radius().
int moa.cluster.Miniball.d [package]
Definition at line 63 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.max_excess(), moa.cluster.Miniball.Miniball(), moa.cluster.Miniball.mtf_mb(), moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.reset(), and moa.cluster.Miniball.Miniball_b.slack().
ArrayList moa.cluster.Miniball.L [package]
Definition at line 64 of file Miniball.java.
Referenced by moa.cluster.Miniball.accuracy(), moa.cluster.Miniball.check_in(), moa.cluster.Miniball.clear(), moa.cluster.Miniball.max_excess(), moa.cluster.Miniball.Miniball(), moa.cluster.Miniball.move_to_front(), moa.cluster.Miniball.mtf_mb(), moa.cluster.Miniball.nr_points(), moa.cluster.Miniball.pivot_mb(), and moa.cluster.Miniball.points_end().
int moa.cluster.Miniball.support_end = 0 [package]
Definition at line 66 of file Miniball.java.
Referenced by moa.cluster.Miniball.accuracy(), moa.cluster.Miniball.build(), moa.cluster.Miniball.move_to_front(), moa.cluster.Miniball.mtf_mb(), moa.cluster.Miniball.pivot_mb(), and moa.cluster.Miniball.support_points_end().
The documentation for this class was generated from the following file:
main/java/moa/cluster/Miniball.java