MOA: moa.streams.clustering.ClusterEvent Class Reference
moa.streams.clustering.ClusterEvent Class Reference
Public Member Functions
ClusterEvent (Object source, long timestamp, String type, String message)
String getMessage ()
long getTimestamp ()
String getType ()
Private Attributes
String type
String message
long timestamp
Detailed Description
Definition at line 25 of file ClusterEvent.java.
Constructor & Destructor Documentation
moa.streams.clustering.ClusterEvent.ClusterEvent (Object source, long timestamp, String type, String message)
Definition at line 31 of file ClusterEvent.java.
{
    super(source);
    this.type = type;
    this.message = message;
    this.timestamp = timestamp;
  }
Member Function Documentation
String moa.streams.clustering.ClusterEvent.getMessage ()
Definition at line 38 of file ClusterEvent.java.
References moa.streams.clustering.ClusterEvent.message.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.RunVisualizer.changeCluster(), moa.gui.visualization.RunOutlierVisualizer.changeCluster(), and moa.gui.visualization.GraphCanvas.forceAddEvents().
{
      return message;
  }
long moa.streams.clustering.ClusterEvent.getTimestamp ()
Definition at line 42 of file ClusterEvent.java.
References moa.streams.clustering.ClusterEvent.timestamp.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), and moa.gui.visualization.GraphCanvas.forceAddEvents().
{
      return timestamp;
  }
String moa.streams.clustering.ClusterEvent.getType ()
Definition at line 46 of file ClusterEvent.java.
References moa.streams.clustering.ClusterEvent.type.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.RunVisualizer.changeCluster(), moa.gui.visualization.RunOutlierVisualizer.changeCluster(), and moa.gui.visualization.GraphCanvas.forceAddEvents().
{
      return type;
  }
Member Data Documentation
String moa.streams.clustering.ClusterEvent.message [private]
Definition at line 28 of file ClusterEvent.java.
Referenced by moa.streams.clustering.ClusterEvent.getMessage().
long moa.streams.clustering.ClusterEvent.timestamp [private]
Definition at line 29 of file ClusterEvent.java.
Referenced by moa.streams.clustering.ClusterEvent.getTimestamp().
String moa.streams.clustering.ClusterEvent.type [private]
Definition at line 27 of file ClusterEvent.java.
Referenced by moa.streams.clustering.ClusterEvent.getType().
The documentation for this class was generated from the following file:
main/java/moa/streams/clustering/ClusterEvent.java