MOA: moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode Class Reference
moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode Class Reference
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Public Member Functions
FIMTDDActiveLearningNode (double[] initialClassObservations)
Create a new FIMTDDActiveLearningNode.
void setParent (Node parent)
Set the parent node.
Node getParent ()
Return the parent node.
double getWeightSeen ()
void learnFromInstance (Instance inst, HoeffdingTree ht)
Method to learn from an instance that passes the new instance to the perceptron learner, and also prevents the class value from being truncated to an int when it is passed to the attribute observer.
AttributeSplitSuggestion[] getBestSplitSuggestions (SplitCriterion criterion, HoeffdingTree ht)
Return the best split suggestions for this node using the given split criteria.
double getPrediction (Instance inst, HoeffdingTree ht)
Retrieve the class votes using the perceptron learner.
double getPredictionTargetMean (Instance inst, HoeffdingTree ht)
Retrieve the class votes using the target mean.
double[] getClassVotes (Instance inst, HoeffdingTree ht)
double getError (Instance inst)
Return the error for a given instance.
double getPHError (Instance inst)
A method returning the Page-Hinckley error produced on this instance in the leaf node, which will then be back-propagated back through the tree to allow the Page-Hinckley change detection tests to be updated.
double getSquaredError ()
Returns the squared error, for use in determining if an alternate tree is performing better than an original tree, or if the alternate tree should be deleted.
Public Attributes
FIMTDDPerceptron learningModel = new FIMTDDPerceptron()
Protected Attributes
Node parent
DoubleVector nodeStatistics
double PHmT = 0
double PHMT = Double.MAX_VALUE
Detailed Description
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Definition at line 140 of file FIMTDD.java.
Constructor & Destructor Documentation
moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.FIMTDDActiveLearningNode (double[] initialClassObservations)
Create a new FIMTDDActiveLearningNode.
Definition at line 163 of file FIMTDD.java.
References moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learningModel, moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.nodeStatistics, and moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.resetLearningImpl().
{
            super(initialClassObservations);
            learningModel.resetLearningImpl();
            nodeStatistics = new DoubleVector();
        }
Member Function Documentation
AttributeSplitSuggestion [] moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions (SplitCriterion criterion, HoeffdingTree ht)
Return the best split suggestions for this node using the given split criteria.
Definition at line 245 of file FIMTDD.java.
References moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.options.FlagOption.isSet, moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.nodeStatistics, and moa.classifiers.trees.HoeffdingTree.noPrePruneOption.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit().
{
            List<AttributeSplitSuggestion> bestSuggestions = new LinkedList<AttributeSplitSuggestion>();
            // Set the nodeStatistics up as the preSplitDistribution, rather than the observedClassDistribution
            double[] nodeSplitDist = this.nodeStatistics.getArrayCopy();
            double[] preSplitDist = this.observedClassDistribution.getArrayCopy();
            if (!ht.noPrePruneOption.isSet()) {
                // add null split as an option
                bestSuggestions.add(new AttributeSplitSuggestion(null,new double[0][], criterion.getMeritOfSplit(nodeSplitDist,new double[][]{nodeSplitDist})));
            }
            for (int i = 0; i < this.attributeObservers.size(); i++) {
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs != null) {
                    // AT THIS STAGE NON-NUMERIC ATTRIBUTES ARE IGNORED
                    AttributeSplitSuggestion bestSuggestion = null;
                    if(obs instanceof FIMTDDNumericAttributeClassObserver) {
                        bestSuggestion = obs.getBestEvaluatedSplitSuggestion(criterion,nodeSplitDist, i, ht.binarySplitsOption.isSet());
                    }
                    if (bestSuggestion != null) {
                        bestSuggestions.add(bestSuggestion);
                    }
                }
            }
            return bestSuggestions.toArray(new AttributeSplitSuggestion[bestSuggestions.size()]);
        }
double [] moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getClassVotes (Instance inst, HoeffdingTree ht)
Definition at line 294 of file FIMTDD.java.
{
            double[] ret = new double[1];
            double perceptronPrediction = getPrediction(inst, ht); // Prediction using perceptron
            double targetMeanPrediction = getPredictionTargetMean(inst, ht); // Prediction using Target Mean
            double perceptronError = Math.abs(inst.classValue() - perceptronPrediction);
            double targetMeanError = Math.abs(inst.classValue() - targetMeanPrediction);
            if(perceptronError < targetMeanError){ // Adaptative strategy
                ret[0] = perceptronPrediction;
            }else{
                ret[0] = targetMeanPrediction;
            }
            return ret;
        }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getError (Instance inst)
Return the error for a given instance.
Definition at line 319 of file FIMTDD.java.
        {
            return inst.classValue() - learningModel.prediction(inst);
        }
Node moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getParent ()
Return the parent node.
Implements moa.classifiers.trees.FIMTDD.AdaptationCompatibleNode.
Definition at line 179 of file FIMTDD.java.
References moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.parent.
Referenced by moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
{
            return parent;
        }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getPHError (Instance inst)
A method returning the Page-Hinckley error produced on this instance in the leaf node, which will then be back-propagated back through the tree to allow the Page-Hinckley change detection tests to be updated.
Definition at line 329 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
        {
            double sd = Math.sqrt((nodeStatistics.getValue(2) - ((nodeStatistics.getValue(1) * nodeStatistics.getValue(1))/nodeStatistics.getValue(0)))/nodeStatistics.getValue(0));
            double mean = nodeStatistics.getValue(1) / nodeStatistics.getValue(0);
            return Math.abs(((inst.classValue()-mean)/sd) - ((learningModel.prediction(inst)-mean)/sd)) -  ((nodeStatistics.getValue(3) + Math.abs(((inst.classValue()-mean)/sd) - ((learningModel.prediction(inst)-mean)/sd))) / (nodeStatistics.getValue(0)+1));
        }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getPrediction (Instance inst, HoeffdingTree ht)
Retrieve the class votes using the perceptron learner.
Definition at line 278 of file FIMTDD.java.
{
            return learningModel.prediction(inst);
        }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getPredictionTargetMean (Instance inst, HoeffdingTree ht)
Retrieve the class votes using the target mean.
Definition at line 285 of file FIMTDD.java.
{
            double valor = 0.0;
            if(this.nodeStatistics.getValue(0) > 0.0){
                valor = this.nodeStatistics.getValue(1)/this.nodeStatistics.getValue(0);
                }
            return valor;
            }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getSquaredError ()
Returns the squared error, for use in determining if an alternate tree is performing better than an original tree, or if the alternate tree should be deleted.
Definition at line 340 of file FIMTDD.java.
        {
            return nodeStatistics.getValue(4);
        }
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getWeightSeen ()
Definition at line 184 of file FIMTDD.java.
References moa.core.DoubleVector.getValue(), and moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit(), and moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
{
            if(nodeStatistics != null)
            {
                return this.nodeStatistics.getValue(0);
            }
            else
            {
                return 0;
            }
        }
void moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance (Instance inst, HoeffdingTree ht)
Method to learn from an instance that passes the new instance to the perceptron learner, and also prevents the class value from being truncated to an int when it is passed to the attribute observer.
Definition at line 201 of file FIMTDD.java.
References moa.core.DoubleVector.addToValue(), moa.core.DoubleVector.getValue(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learningModel, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.nodeStatistics, moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.prediction(), moa.core.DoubleVector.setValue(), and moa.classifiers.trees.FIMTDD.FIMTDDPerceptron.trainOnInstanceImpl().
{
           // this.observedClassDistribution.addToValue((int)inst.classValue(),inst.weight());
            // Update the statistics for this node
                // number of instances passing through the node
                nodeStatistics.addToValue(0, 1);
                // sum of y values
                nodeStatistics.addToValue(1, inst.classValue());
                // sum of squared y values
                nodeStatistics.addToValue(2, inst.classValue() * inst.classValue());
                // sum of absolute errors
                    // Normalise values prior to calculating absolute error
                    double sd = Math.sqrt((nodeStatistics.getValue(2) - ((nodeStatistics.getValue(1) *
                nodeStatistics.getValue(1))/nodeStatistics.getValue(0)))/nodeStatistics.getValue(0));
                double mean = nodeStatistics.getValue(1) / nodeStatistics.getValue(0);
                nodeStatistics.addToValue(3, Math.abs(((inst.classValue()-mean)/sd) - ((learningModel.prediction(inst)-mean)/sd)));
                // sum of squared errors
                nodeStatistics.setValue(4, Math.pow(this.getError(inst), 2) + nodeStatistics.getValue(4) * ((FIMTDD) ht).AlternateTreeFadingFactorOption.getValue());
            learningModel.trainOnInstanceImpl(inst, (FIMTDD)ht);
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs == null) {
                // At this stage all nominal attributes are ignored
                if(inst.attribute(instAttIndex).isNumeric())
                {
                        obs = ((FIMTDD)ht).newNumericClassObserver();
                        this.attributeObservers.set(i, obs);
                }
            }
            if(obs != null)
            {
                ((FIMTDDNumericAttributeClassObserver)obs).observeAttributeClass(inst.value(instAttIndex),inst.classValue(), inst.weight());
            }
            }
        }
void moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.setParent (Node parent)
Set the parent node.
Implements moa.classifiers.trees.FIMTDD.AdaptationCompatibleNode.
Definition at line 172 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit(), and moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
{
            this.parent = parent;
        }
Member Data Documentation
FIMTDDPerceptron moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learningModel = new FIMTDDPerceptron()
Definition at line 143 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.FIMTDDActiveLearningNode(), and moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance().
DoubleVector moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.nodeStatistics [protected]
Definition at line 152 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.FIMTDDActiveLearningNode(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getWeightSeen(), and moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance().
Node moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.parent [protected]
Definition at line 146 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getParent().
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.PHMT = Double.MAX_VALUE [protected]
Definition at line 158 of file FIMTDD.java.
double moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.PHmT = 0 [protected]
Definition at line 157 of file FIMTDD.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/FIMTDD.java