MOA: moa.classifiers.rules.core.Rule Class Reference
moa.classifiers.rules.core.Rule Class Reference
Classes
class Builder
Public Member Functions
int getRuleNumberID ()
void setRuleNumberID (int ruleNumberID)
RuleActiveLearningNode getLearningNode ()
getLearningNode Method This is the way to pass info for other classes.
void setLearningNode (RuleActiveLearningNode learningNode)
List< RuleSplitNode > getNodeList ()
long getInstancesSeen ()
void setNodeList (List< RuleSplitNode > nodeList)
Rule (Builder builder)
boolean isCovering (Instance inst)
void getDescription (StringBuilder sb, int indent)
MOA GUI output.
void updateStatistics (Instance instance)
boolean tryToExpand (double splitConfidence, double tieThreshold)
Try to Expand method.
void split ()
double[] statisticsOtherBranchSplit ()
String printRule ()
boolean isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly)
double computeError (Instance instance)
boolean updatePageHinckleyTest (double error)
double[] getPrediction (Instance instance, int mode)
double[] getPrediction (Instance instance)
Builder getBuilder ()
void setBuilder (Builder builder)
double getCurrentError ()
Protected Member Functions
void debug (String string, int level)
Protected Attributes
List< RuleSplitNode > nodeList = new LinkedList<RuleSplitNode>()
RuleActiveLearningNode learningNode
int ruleNumberID
AbstractAMRules amRules
Private Member Functions
RuleActiveLearningNode newRuleActiveLearningNode (Builder builder)
boolean nodeListAdd (RuleSplitNode ruleSplitNode)
Private Attributes
double[] statisticsOtherBranchSplit
Builder builder
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 51 of file Rule.java.
Constructor & Destructor Documentation
moa.classifiers.rules.core.Rule.Rule (Builder builder)
Definition at line 100 of file Rule.java.
References moa.classifiers.rules.core.Rule.amRules, moa.classifiers.rules.core.Rule.Builder.getAMRules(), moa.classifiers.rules.core.Rule.Builder.id, moa.classifiers.rules.core.Rule.learningNode, moa.classifiers.rules.core.Rule.newRuleActiveLearningNode(), moa.classifiers.rules.core.Rule.ruleNumberID, moa.classifiers.rules.core.Rule.setBuilder(), and moa.classifiers.rules.core.Rule.Builder.setOwner().
Referenced by moa.classifiers.rules.core.Rule.Builder.build().
{
        builder.setOwner(this);
        this.setBuilder(builder);
        this.amRules = builder.getAMRules();
        this.learningNode = newRuleActiveLearningNode(builder);
        //JD - use builder ID to set ruleNumberID
        this.ruleNumberID=builder.id;
    }
Member Function Documentation
double moa.classifiers.rules.core.Rule.computeError (Instance instance)
Definition at line 330 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.computeError(), and moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        return this.learningNode.computeError(instance);
    }
void moa.classifiers.rules.core.Rule.debug (String string, int level) [protected]
Definition at line 315 of file Rule.java.
References moa.classifiers.rules.core.Rule.amRules, moa.options.IntOption.getValue(), and moa.classifiers.rules.AbstractAMRules.VerbosityOption.
{
        if (this.amRules.VerbosityOption.getValue()>=level) {
            System.out.println(string);
        }
    }
Builder moa.classifiers.rules.core.Rule.getBuilder ()
Definition at line 346 of file Rule.java.
References moa.classifiers.rules.core.Rule.builder.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule(), and moa.classifiers.rules.core.Rule.split().
{
        return builder;
    }
double moa.classifiers.rules.core.Rule.getCurrentError ()
Definition at line 354 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getCurrentError(), and moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
{
        return this.learningNode.getCurrentError();
    }
void moa.classifiers.rules.core.Rule.getDescription (StringBuilder sb, int indent)
MOA GUI output.
Implements moa.MOAObject.
Definition at line 136 of file Rule.java.
{
    }
long moa.classifiers.rules.core.Rule.getInstancesSeen ()
Definition at line 92 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getInstancesSeen(), and moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AbstractAMRules.isAnomaly(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        return this.learningNode.getInstancesSeen();
    }
RuleActiveLearningNode moa.classifiers.rules.core.Rule.getLearningNode ()
getLearningNode Method This is the way to pass info for other classes.
Implements getLearningNode() in class RuleActiveLearningNode
Returns:
Definition at line 80 of file Rule.java.
References moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        return learningNode;
    }
List<RuleSplitNode> moa.classifiers.rules.core.Rule.getNodeList ()
Definition at line 88 of file Rule.java.
References moa.classifiers.rules.core.Rule.nodeList.
{
        return nodeList;
    }
double [] moa.classifiers.rules.core.Rule.getPrediction (Instance instance)
Definition at line 342 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction(), and moa.classifiers.rules.core.Rule.learningNode.
{
        return this.learningNode.getPrediction(instance);
    }
double [] moa.classifiers.rules.core.Rule.getPrediction (Instance instance, int mode)
Definition at line 338 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction(), and moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
{
        return this.learningNode.getPrediction(instance, mode);
    }
int moa.classifiers.rules.core.Rule.getRuleNumberID ()
Definition at line 61 of file Rule.java.
References moa.classifiers.rules.core.Rule.ruleNumberID.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        return ruleNumberID;
    }
boolean moa.classifiers.rules.core.Rule.isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly)
Definition at line 321 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.isAnomaly(), and moa.classifiers.rules.core.Rule.learningNode.
Referenced by moa.classifiers.rules.AbstractAMRules.isAnomaly().
{
        return this.learningNode.isAnomaly(instance, uniVariateAnomalyProbabilityThreshold,
                multiVariateAnomalyProbabilityThreshold,
                numberOfInstanceesForAnomaly);
    }
boolean moa.classifiers.rules.core.Rule.isCovering (Instance inst)
Definition at line 121 of file Rule.java.
References moa.classifiers.rules.core.Rule.nodeList.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        boolean isCovering = true;
        for (RuleSplitNode node : nodeList) {
            if (node.evaluate(inst) == false) {
                isCovering = false;
                break;
            }
        }
        return isCovering;
    }
RuleActiveLearningNode moa.classifiers.rules.core.Rule.newRuleActiveLearningNode (Builder builder) [private]
Definition at line 112 of file Rule.java.
References moa.classifiers.rules.core.Rule.amRules, and moa.classifiers.rules.AbstractAMRules.newRuleActiveLearningNode().
Referenced by moa.classifiers.rules.core.Rule.Rule(), and moa.classifiers.rules.core.Rule.split().
{
        return amRules.newRuleActiveLearningNode(builder);
    }
boolean moa.classifiers.rules.core.Rule.nodeListAdd (RuleSplitNode ruleSplitNode) [private]
Definition at line 264 of file Rule.java.
References moa.classifiers.rules.nodes.RuleSplitNode.getSplitTest(), moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.isIncludedInRuleNode(), moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.isUsingSameAttribute(), moa.classifiers.rules.core.Rule.nodeList, and moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.setAttributeValue().
Referenced by moa.classifiers.rules.core.Rule.split().
{
        //Check that the node is not already in the list
        boolean isIncludedInNodeList = false;
        boolean isUpdated=false;
        for (RuleSplitNode node : nodeList) {
            NumericAttributeBinaryRulePredicate nodeTest = (NumericAttributeBinaryRulePredicate) node.getSplitTest();
            NumericAttributeBinaryRulePredicate ruleSplitNodeTest = (NumericAttributeBinaryRulePredicate) ruleSplitNode.getSplitTest();
            if (nodeTest.isUsingSameAttribute(ruleSplitNodeTest)) {
                isIncludedInNodeList = true;
                if (nodeTest.isIncludedInRuleNode(ruleSplitNodeTest) == true) { //remove this line to keep the most recent attribute value
                    //replace the value
                    nodeTest.setAttributeValue(ruleSplitNodeTest);
                    isUpdated=true; //if is updated (i.e. an expansion happened) a new learning node should be created
                }
            }
        }
        if (isIncludedInNodeList == false) {
            this.nodeList.add(ruleSplitNode);
        }
        return (!isIncludedInNodeList || isUpdated);
    }
String moa.classifiers.rules.core.Rule.printRule ()
Definition at line 291 of file Rule.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getInstancesSeen(), moa.classifiers.rules.core.RuleActiveLearningNode.getSimplePrediction(), moa.classifiers.rules.core.Rule.learningNode, moa.classifiers.rules.core.Rule.nodeList, moa.classifiers.rules.core.Rule.ruleNumberID, and moa.AbstractMOAObject.toString().
Referenced by moa.classifiers.rules.AbstractAMRules.PrintRuleSet(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        StringBuilder out = new StringBuilder();
        int indent = 1;
        StringUtils.appendIndented(out, indent, "Rule Nr." + this.ruleNumberID + " Instances seen:" + this.learningNode.getInstancesSeen() + "\n"); // AC
        for (RuleSplitNode node : nodeList) {
            StringUtils.appendIndented(out, indent, node.getSplitTest().toString());
            StringUtils.appendIndented(out, indent, " ");
            StringUtils.appendIndented(out, indent, node.toString());
        }
        DoubleVector pred = new DoubleVector(this.learningNode.getSimplePrediction());
        StringUtils.appendIndented(out, 0, " --> y: " + pred.toString());
        StringUtils.appendNewline(out);
        if (this.learningNode instanceof RuleActiveRegressionNode) {
            if(((RuleActiveRegressionNode)this.learningNode).perceptron!=null){
                ((RuleActiveRegressionNode)this.learningNode).perceptron.getModelDescription(out,0 );
                StringUtils.appendNewline(out);
            }
        }
        return(out.toString());
    }
void moa.classifiers.rules.core.Rule.setBuilder (Builder builder)
Definition at line 350 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.Rule().
{
        this.builder = builder;
    }
void moa.classifiers.rules.core.Rule.setLearningNode (RuleActiveLearningNode learningNode)
Definition at line 84 of file Rule.java.
{
        this.learningNode = learningNode;
    }
void moa.classifiers.rules.core.Rule.setNodeList (List< RuleSplitNode > nodeList)
Definition at line 96 of file Rule.java.
{
        this.nodeList = nodeList;
    }
void moa.classifiers.rules.core.Rule.setRuleNumberID (int ruleNumberID)
Definition at line 65 of file Rule.java.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        this.ruleNumberID = ruleNumberID;
    }
void moa.classifiers.rules.core.Rule.split ()
Definition at line 235 of file Rule.java.
References moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest.getAttsTestDependsOn(), moa.classifiers.rules.core.RuleActiveLearningNode.getBestSuggestion(), moa.classifiers.rules.core.Rule.getBuilder(), moa.classifiers.rules.core.RuleActiveLearningNode.getSplitIndex(), moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest.getSplitValue(), moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsBranchSplit(), moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsNewRuleActiveLearningNode(), moa.classifiers.rules.core.RuleActiveLearningNode.initialize(), moa.classifiers.rules.core.Rule.learningNode, moa.classifiers.rules.core.Rule.newRuleActiveLearningNode(), moa.classifiers.rules.core.Rule.nodeListAdd(), and moa.classifiers.core.AttributeSplitSuggestion.splitTest.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
    {
        //this.statisticsOtherBranchSplit  = this.learningNode.getStatisticsOtherBranchSplit();
        //create a split node,
        int splitIndex = this.learningNode.getSplitIndex();
        InstanceConditionalTest st=this.learningNode.getBestSuggestion().splitTest;
        if(st instanceof NumericAttributeBinaryTest ) {
            NumericAttributeBinaryTest splitTest = (NumericAttributeBinaryTest) st;
            NumericAttributeBinaryRulePredicate predicate = new NumericAttributeBinaryRulePredicate(
                    splitTest.getAttsTestDependsOn()[0], splitTest.getSplitValue(),
                    splitIndex + 1);
            RuleSplitNode ruleSplitNode = new RuleSplitNode(predicate, this.learningNode.getStatisticsBranchSplit() );
            if (this.nodeListAdd(ruleSplitNode) == true) {
                // create a new learning node
                RuleActiveLearningNode newLearningNode = newRuleActiveLearningNode(this.getBuilder().statistics(this.learningNode.getStatisticsNewRuleActiveLearningNode()));
                newLearningNode.initialize(this.learningNode);
                this.learningNode = newLearningNode;
            }
        }
        else
            throw new UnsupportedOperationException("AMRules (currently) only supports numerical attributes.");
    }
double [] moa.classifiers.rules.core.Rule.statisticsOtherBranchSplit ()
Definition at line 286 of file Rule.java.
{
        return this.statisticsOtherBranchSplit;
    }
boolean moa.classifiers.rules.core.Rule.tryToExpand (double splitConfidence, double tieThreshold)
Try to Expand method.
Parameters:
splitConfidence
tieThreshold
Returns:
Definition at line 228 of file Rule.java.
References moa.classifiers.rules.core.Rule.learningNode, and moa.classifiers.rules.core.RuleActiveLearningNode.tryToExpand().
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        boolean shouldSplit= this.learningNode.tryToExpand(splitConfidence, tieThreshold);
        return shouldSplit;
    }
boolean moa.classifiers.rules.core.Rule.updatePageHinckleyTest (double error)
Definition at line 334 of file Rule.java.
References moa.classifiers.rules.core.Rule.learningNode, and moa.classifiers.rules.core.RuleActiveLearningNode.updatePageHinckleyTest().
{
        return this.learningNode.updatePageHinckleyTest(error);
    }
void moa.classifiers.rules.core.Rule.updateStatistics (Instance instance)
Definition at line 218 of file Rule.java.
References moa.classifiers.rules.core.Rule.learningNode, and moa.classifiers.rules.core.RuleActiveLearningNode.updateStatistics().
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        this.learningNode.updateStatistics(instance);
    }
Member Data Documentation
AbstractAMRules moa.classifiers.rules.core.Rule.amRules [protected]
Definition at line 110 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.debug(), moa.classifiers.rules.core.Rule.newRuleActiveLearningNode(), and moa.classifiers.rules.core.Rule.Rule().
Builder moa.classifiers.rules.core.Rule.builder [private]
Definition at line 72 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.getBuilder().
RuleActiveLearningNode moa.classifiers.rules.core.Rule.learningNode [protected]
Definition at line 57 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.computeError(), moa.classifiers.rules.core.Rule.getCurrentError(), moa.classifiers.rules.core.Rule.getInstancesSeen(), moa.classifiers.rules.core.Rule.getLearningNode(), moa.classifiers.rules.core.Rule.getPrediction(), moa.classifiers.rules.core.Rule.isAnomaly(), moa.classifiers.rules.core.Rule.printRule(), moa.classifiers.rules.core.Rule.Rule(), moa.classifiers.rules.core.Rule.split(), moa.classifiers.rules.core.Rule.tryToExpand(), moa.classifiers.rules.core.Rule.updatePageHinckleyTest(), and moa.classifiers.rules.core.Rule.updateStatistics().
List<RuleSplitNode> moa.classifiers.rules.core.Rule.nodeList = new LinkedList<RuleSplitNode>() [protected]
Definition at line 55 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.getNodeList(), moa.classifiers.rules.core.Rule.isCovering(), moa.classifiers.rules.core.Rule.nodeListAdd(), and moa.classifiers.rules.core.Rule.printRule().
int moa.classifiers.rules.core.Rule.ruleNumberID [protected]
Definition at line 59 of file Rule.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), moa.classifiers.rules.core.Rule.getRuleNumberID(), moa.classifiers.rules.core.Rule.printRule(), and moa.classifiers.rules.core.Rule.Rule().
final long moa.classifiers.rules.core.Rule.serialVersionUID = 1L [static, private]
Definition at line 53 of file Rule.java.
double [] moa.classifiers.rules.core.Rule.statisticsOtherBranchSplit [private]
Definition at line 70 of file Rule.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/Rule.java