MOA: moa.gui.FileOptionEditComponent Class Reference
moa.gui.FileOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a file option.
Public Member Functions
FileOptionEditComponent (FileOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void browseForFile ()
Protected Attributes
FileOption editedOption
JTextField textField = new JTextField()
JButton browseButton = new JButton("Browse")
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a file option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 41 of file FileOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.FileOptionEditComponent.FileOptionEditComponent (FileOption option)
Definition at line 52 of file FileOptionEditComponent.java.
References moa.gui.FileOptionEditComponent.browseButton, moa.gui.FileOptionEditComponent.browseForFile(), moa.gui.FileOptionEditComponent.editedOption, moa.options.StringOption.getValueAsCLIString(), moa.gui.FileOptionEditComponent.setEditState(), and moa.gui.FileOptionEditComponent.textField.
{
        this.editedOption = option;
        setLayout(new BorderLayout());
        add(this.textField, BorderLayout.CENTER);
        add(this.browseButton, BorderLayout.EAST);
        this.browseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                browseForFile();
            }
        });
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.FileOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 68 of file FileOptionEditComponent.java.
References moa.gui.FileOptionEditComponent.editedOption, moa.options.StringOption.setValueViaCLIString(), and moa.gui.FileOptionEditComponent.textField.
{
        this.editedOption.setValueViaCLIString(this.textField.getText().length() > 0 ? this.textField.getText() : null);
    }
void moa.gui.FileOptionEditComponent.browseForFile ()
Definition at line 82 of file FileOptionEditComponent.java.
References moa.gui.FileOptionEditComponent.editedOption, moa.options.FileOption.getDefaultFileExtension(), moa.options.FileOption.isOutputFile, and moa.gui.FileOptionEditComponent.textField.
Referenced by moa.gui.FileOptionEditComponent.FileOptionEditComponent().
{
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        String extension = this.editedOption.getDefaultFileExtension();
        if (extension != null) {
            fileChooser.addChoosableFileFilter(new FileExtensionFilter(
                    extension));
        }
        fileChooser.setSelectedFile(new File(this.textField.getText()));
        if (this.editedOption.isOutputFile()) {
            if (fileChooser.showSaveDialog(this.browseButton) == JFileChooser.APPROVE_OPTION) {
                File chosenFile = fileChooser.getSelectedFile();
                String fileName = chosenFile.getPath();
                if (!chosenFile.exists()) {
                    if ((extension != null) && !fileName.endsWith(extension)) {
                        fileName = fileName + "." + extension;
                    }
                }
                this.textField.setText(fileName);
            }
        } else {
            if (fileChooser.showOpenDialog(this.browseButton) == JFileChooser.APPROVE_OPTION) {
                this.textField.setText(fileChooser.getSelectedFile().getPath());
            }
        }
    }
Option moa.gui.FileOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 73 of file FileOptionEditComponent.java.
References moa.gui.FileOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.FileOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 78 of file FileOptionEditComponent.java.
References moa.gui.FileOptionEditComponent.textField.
Referenced by moa.gui.FileOptionEditComponent.FileOptionEditComponent().
{
        this.textField.setText(cliString);
    }
Member Data Documentation
JButton moa.gui.FileOptionEditComponent.browseButton = new JButton("Browse") [protected]
Definition at line 50 of file FileOptionEditComponent.java.
Referenced by moa.gui.FileOptionEditComponent.FileOptionEditComponent().
FileOption moa.gui.FileOptionEditComponent.editedOption [protected]
Definition at line 46 of file FileOptionEditComponent.java.
Referenced by moa.gui.FileOptionEditComponent.applyState(), moa.gui.FileOptionEditComponent.browseForFile(), moa.gui.FileOptionEditComponent.FileOptionEditComponent(), and moa.gui.FileOptionEditComponent.getEditedOption().
final long moa.gui.FileOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 44 of file FileOptionEditComponent.java.
JTextField moa.gui.FileOptionEditComponent.textField = new JTextField() [protected]
Definition at line 48 of file FileOptionEditComponent.java.
Referenced by moa.gui.FileOptionEditComponent.applyState(), moa.gui.FileOptionEditComponent.browseForFile(), moa.gui.FileOptionEditComponent.FileOptionEditComponent(), and moa.gui.FileOptionEditComponent.setEditState().
The documentation for this class was generated from the following file:
main/java/moa/gui/FileOptionEditComponent.java