MOA: moa.evaluation.WindowClassificationPerformanceEvaluator Class Reference
moa.evaluation.WindowClassificationPerformanceEvaluator Class Reference
Classification evaluator that updates evaluation results using a sliding window.
Classes
class Estimator
Public Member Functions
void reset ()
Resets this evaluator.
void reset (int numClasses)
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getFractionCorrectlyClassified ()
double getKappaStatistic ()
double getKappaTemporalStatistic ()
double getFractionIncorrectlyClassified ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Public Attributes
IntOption widthOption
Protected Attributes
double TotalweightObserved = 0
Estimator weightObserved
Estimator weightCorrect
Estimator weightCorrectNoChangeClassifier
double lastSeenClass
Estimator[] columnKappa
Estimator[] rowKappa
Estimator[] classAccuracy
int numClasses
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Classification evaluator that updates evaluation results using a sliding window.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 37 of file WindowClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.WindowClassificationPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Reimplemented in moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.
Definition at line 132 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.Estimator.add(), moa.evaluation.WindowClassificationPerformanceEvaluator.classAccuracy, moa.evaluation.WindowClassificationPerformanceEvaluator.columnKappa, moa.evaluation.WindowClassificationPerformanceEvaluator.lastSeenClass, moa.evaluation.WindowClassificationPerformanceEvaluator.numClasses, moa.evaluation.WindowClassificationPerformanceEvaluator.reset(), moa.evaluation.WindowClassificationPerformanceEvaluator.rowKappa, moa.evaluation.WindowClassificationPerformanceEvaluator.TotalweightObserved, moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, and moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved.
{
        double weight = inst.weight();
        int trueClass = (int) inst.classValue();
        if (weight > 0.0) {
            if (TotalweightObserved == 0) {
                reset(inst.dataset().numClasses());
            }
            this.TotalweightObserved += weight;
            this.weightObserved.add(weight);
            int predictedClass = Utils.maxIndex(classVotes);
            if (predictedClass == trueClass) {
                this.weightCorrect.add(weight);
            } else {
                this.weightCorrect.add(0);
            }
            //Add Kappa statistic information
            for (int i = 0; i < this.numClasses; i++) {
                this.rowKappa[i].add(i == predictedClass ? weight : 0);
                this.columnKappa[i].add(i == trueClass ? weight : 0);
            }
            if (this.lastSeenClass == trueClass) {
                this.weightCorrectNoChangeClassifier.add(weight);
            } else {
                this.weightCorrectNoChangeClassifier.add(0);
            }
            this.classAccuracy[trueClass].add(predictedClass == trueClass ? weight : 0.0);
            this.lastSeenClass = trueClass;
        }
    }
void moa.evaluation.WindowClassificationPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Reimplemented in moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.
Definition at line 216 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionCorrectlyClassified ()
Definition at line 181 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.Estimator.total(), moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect, and moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionIncorrectlyClassified(), and moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved.total() > 0.0 ? (double) this.weightCorrect.total()
                / this.weightObserved.total() : 0.0;
    }
double moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionIncorrectlyClassified ()
Definition at line 211 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
{
        return 1.0 - getFractionCorrectlyClassified();
    }
double moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic ()
Definition at line 186 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.columnKappa, moa.evaluation.WindowClassificationPerformanceEvaluator.numClasses, moa.evaluation.WindowClassificationPerformanceEvaluator.rowKappa, moa.evaluation.WindowClassificationPerformanceEvaluator.Estimator.total(), moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect, and moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        if (this.weightObserved.total() > 0.0) {
            double p0 = this.weightCorrect.total() / this.weightObserved.total();
            double pc = 0;
            for (int i = 0; i < this.numClasses; i++) {
                pc += (this.rowKappa[i].total() / this.weightObserved.total())
                        * (this.columnKappa[i].total() / this.weightObserved.total());
            }
            return (p0 - pc) / (1 - pc);
        } else {
            return 0;
        }
    }
double moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaTemporalStatistic ()
Definition at line 200 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.Estimator.total(), moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, and moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        if (this.weightObserved.total() > 0.0) {
            double p0 = this.weightCorrect.total() / this.weightObserved.total();
            double pc = this.weightCorrectNoChangeClassifier.total() / this.weightObserved.total();
            return (p0 - pc) / (1 - pc);
        } else {
            return 0;
        }
    }
Measurement [] moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Reimplemented in moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.
Definition at line 163 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.WindowClassificationPerformanceEvaluator.TotalweightObserved.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
            new Measurement("classified instances",
            this.TotalweightObserved),
            new Measurement("classifications correct (percent)",
            getFractionCorrectlyClassified() * 100.0),
            new Measurement("Kappa Statistic (percent)",
            getKappaStatistic() * 100.0),
            new Measurement("Kappa Temporal Statistic (percent)",
            getKappaTemporalStatistic() * 100.0)
        };
    }
double moa.evaluation.WindowClassificationPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 177 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.Estimator.total(), and moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved.
{
        return this.weightObserved.total();
    }
void moa.evaluation.WindowClassificationPerformanceEvaluator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 222 of file WindowClassificationPerformanceEvaluator.java.
{
    }
void moa.evaluation.WindowClassificationPerformanceEvaluator.reset (int numClasses)
Reimplemented in moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.
Definition at line 114 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.classAccuracy, moa.evaluation.WindowClassificationPerformanceEvaluator.columnKappa, moa.options.IntOption.getValue(), moa.evaluation.WindowClassificationPerformanceEvaluator.lastSeenClass, moa.evaluation.WindowClassificationPerformanceEvaluator.rowKappa, moa.evaluation.WindowClassificationPerformanceEvaluator.TotalweightObserved, moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved, and moa.evaluation.WindowClassificationPerformanceEvaluator.widthOption.
{
        this.numClasses = numClasses;
        this.rowKappa = new Estimator[numClasses];
        this.columnKappa = new Estimator[numClasses];
        this.classAccuracy = new Estimator[numClasses];
        for (int i = 0; i < this.numClasses; i++) {
            this.rowKappa[i] = new Estimator(this.widthOption.getValue());
            this.columnKappa[i] = new Estimator(this.widthOption.getValue());
            this.classAccuracy[i] = new Estimator(this.widthOption.getValue());
        }
        this.weightCorrect = new Estimator(this.widthOption.getValue());
        this.weightCorrectNoChangeClassifier = new Estimator(this.widthOption.getValue());
        this.weightObserved = new Estimator(this.widthOption.getValue());
        this.TotalweightObserved = 0;
        this.lastSeenClass = 0;
    }
void moa.evaluation.WindowClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Reimplemented in moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.
Definition at line 110 of file WindowClassificationPerformanceEvaluator.java.
References moa.evaluation.WindowClassificationPerformanceEvaluator.numClasses.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult().
{
        reset(this.numClasses);
    }
Member Data Documentation
Estimator [] moa.evaluation.WindowClassificationPerformanceEvaluator.classAccuracy [protected]
Definition at line 59 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
Estimator [] moa.evaluation.WindowClassificationPerformanceEvaluator.columnKappa [protected]
Definition at line 55 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
double moa.evaluation.WindowClassificationPerformanceEvaluator.lastSeenClass [protected]
Definition at line 53 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
int moa.evaluation.WindowClassificationPerformanceEvaluator.numClasses [protected]
Definition at line 61 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.WindowClassificationPerformanceEvaluator.reset(), and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset().
Estimator [] moa.evaluation.WindowClassificationPerformanceEvaluator.rowKappa [protected]
Definition at line 57 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
final long moa.evaluation.WindowClassificationPerformanceEvaluator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 40 of file WindowClassificationPerformanceEvaluator.java.
double moa.evaluation.WindowClassificationPerformanceEvaluator.TotalweightObserved = 0 [protected]
Definition at line 45 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
Estimator moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrect [protected]
Definition at line 49 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
Estimator moa.evaluation.WindowClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier [protected]
Definition at line 51 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
Estimator moa.evaluation.WindowClassificationPerformanceEvaluator.weightObserved [protected]
Definition at line 47 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.WindowClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.WindowClassificationPerformanceEvaluator.getKappaTemporalStatistic(), moa.evaluation.WindowClassificationPerformanceEvaluator.getTotalWeightObserved(), and moa.evaluation.WindowClassificationPerformanceEvaluator.reset().
IntOption moa.evaluation.WindowClassificationPerformanceEvaluator.widthOption
Initial value:
 new IntOption("width",
            'w', "Size of Window", 1000)
Definition at line 42 of file WindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowClassificationPerformanceEvaluator.reset(), and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/WindowClassificationPerformanceEvaluator.java