MOA: moa.tasks.EvaluateClustering Class Reference
moa.tasks.EvaluateClustering Class Reference
Task for evaluating a clusterer on a stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
IntOption instanceLimitOption
IntOption measureCollectionTypeOption
FileOption dumpFileOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a clusterer on a stream.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 26 of file EvaluateClustering.java.
Member Function Documentation
Object moa.tasks.EvaluateClustering.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 82 of file EvaluateClustering.java.
References moa.tasks.EvaluateClustering.dumpFileOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.StringOption.getValue(), moa.options.IntOption.getValue(), moa.tasks.EvaluateClustering.instanceLimitOption, moa.tasks.EvaluateClustering.learnerOption, moa.tasks.EvaluateClustering.measureCollectionTypeOption, and moa.tasks.EvaluateClustering.streamOption.
{
        BatchCmd.runBatch((ClusteringStream) getPreparedClassOption(this.streamOption),
                (AbstractClusterer) getPreparedClassOption(this.learnerOption),
                (int) measureCollectionTypeOption.getValue(),
                (int) this.instanceLimitOption.getValue(),
                (String) dumpFileOption.getValue());
        LearningCurve learningCurve = new LearningCurve("EvaluateClustering does not support custom output file (> [filename]).\n" +
                                                        "Check out the dump file to see the results (if you haven't specified, dumpClustering.csv by default).");
        //System.out.println(learner.toString());
        return learningCurve;
    }
String moa.tasks.EvaluateClustering.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 29 of file EvaluateClustering.java.
{
        return "Evaluates a clusterer on a stream.";
    }
Class<?> moa.tasks.EvaluateClustering.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 77 of file EvaluateClustering.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FileOption moa.tasks.EvaluateClustering.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv reslts to.", "dumpClustering.csv", "csv", true)
Definition at line 73 of file EvaluateClustering.java.
Referenced by moa.tasks.EvaluateClustering.doMainTask().
IntOption moa.tasks.EvaluateClustering.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            100000, -1, Integer.MAX_VALUE)
Definition at line 42 of file EvaluateClustering.java.
Referenced by moa.tasks.EvaluateClustering.doMainTask().
ClassOption moa.tasks.EvaluateClustering.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Clusterer to train.", AbstractClusterer.class, "clustream.Clustream")
Definition at line 35 of file EvaluateClustering.java.
Referenced by moa.tasks.EvaluateClustering.doMainTask().
IntOption moa.tasks.EvaluateClustering.measureCollectionTypeOption
Initial value:
 new IntOption(
            "measureCollectionType", 'm',
            "Type of measure collection", 0, 0,
            Integer.MAX_VALUE)
Definition at line 46 of file EvaluateClustering.java.
Referenced by moa.tasks.EvaluateClustering.doMainTask().
final long moa.tasks.EvaluateClustering.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 33 of file EvaluateClustering.java.
ClassOption moa.tasks.EvaluateClustering.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.",  ClusteringStream.class,
            "RandomRBFGeneratorEvents")
Definition at line 38 of file EvaluateClustering.java.
Referenced by moa.tasks.EvaluateClustering.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateClustering.java