MOA: moa.classifiers.meta.LeveragingBag Class Reference
moa.classifiers.meta.LeveragingBag Class Reference
Leveraging Bagging for evolving data streams using ADWIN.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
double[] getVotesForInstanceBinary (Instance inst)
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
FloatOption weightShrinkOption
FloatOption deltaAdwinOption
FlagOption outputCodesOption
MultiChoiceOption leveraginBagAlgorithmOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
ADWIN[] ADError
int numberOfChangesDetected
int[][] matrixCodes
boolean initMatrixCodes = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Leveraging Bagging for evolving data streams using ADWIN.
Leveraging Bagging and Leveraging Bagging MC using Random Output Codes (-o option).
See details in:
Albert Bifet, Geoffrey Holmes, Bernhard Pfahringer. Leveraging Bagging for Evolving Data Streams Machine Learning and Knowledge Discovery in Databases, European Conference, ECML PKDD}, 2010.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 43 of file LeveragingBag.java.
Member Function Documentation
void moa.classifiers.meta.LeveragingBag.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 250 of file LeveragingBag.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.LeveragingBag.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 255 of file LeveragingBag.java.
References moa.classifiers.meta.LeveragingBag.ensemble, and moa.classifiers.meta.LeveragingBag.numberOfChangesDetected.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0),
                    new Measurement("change detections", this.numberOfChangesDetected)
                };
    }
String moa.classifiers.meta.LeveragingBag.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 48 of file LeveragingBag.java.
{
        return "Leveraging Bagging for evolving data streams using ADWIN.";
    }
Classifier [] moa.classifiers.meta.LeveragingBag.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 263 of file LeveragingBag.java.
References moa.classifiers.meta.LeveragingBag.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.LeveragingBag.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 203 of file LeveragingBag.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.LeveragingBag.ensemble, moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary(), moa.options.FlagOption.isSet, moa.core.DoubleVector.normalize(), moa.classifiers.meta.LeveragingBag.outputCodesOption, and moa.core.DoubleVector.sumOfValues().
{
        if (this.outputCodesOption.isSet()) {
            return getVotesForInstanceBinary(inst);
        }
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
            if (vote.sumOfValues() > 0.0) {
                vote.normalize();
                combinedVote.addValues(vote);
            }
        }
        return combinedVote.getArrayRef();
    }
double [] moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary (Instance inst)
Definition at line 218 of file LeveragingBag.java.
References moa.classifiers.meta.LeveragingBag.ensemble, moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.initMatrixCodes, and moa.classifiers.meta.LeveragingBag.matrixCodes.
Referenced by moa.classifiers.meta.LeveragingBag.getVotesForInstance().
{
        double combinedVote[] = new double[(int) inst.numClasses()];
        Instance weightedInst = (Instance) inst.copy();
        if (this.initMatrixCodes == false) {
            for (int i = 0; i < this.ensemble.length; i++) {
                //Replace class by OC
                weightedInst.setClassValue((double) this.matrixCodes[i][(int) inst.classValue()]);
                double vote[];
                vote = this.ensemble[i].getVotesForInstance(weightedInst);
                //Binary Case
                int voteClass = 0;
                if (vote.length == 2) {
                    voteClass = (vote[1] > vote[0] ? 1 : 0);
                }
                //Update votes
                for (int j = 0; j < inst.numClasses(); j++) {
                    if (this.matrixCodes[i][j] == voteClass) {
                        combinedVote[j] += 1;
                    }
                }
            }
        }
        return combinedVote;
    }
boolean moa.classifiers.meta.LeveragingBag.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 245 of file LeveragingBag.java.
{
        return true;
    }
void moa.classifiers.meta.LeveragingBag.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 89 of file LeveragingBag.java.
References moa.classifiers.meta.LeveragingBag.ADError, moa.classifiers.meta.LeveragingBag.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.LeveragingBag.deltaAdwinOption, moa.classifiers.meta.LeveragingBag.ensemble, moa.classifiers.meta.LeveragingBag.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.meta.LeveragingBag.initMatrixCodes, moa.options.FlagOption.isSet, moa.classifiers.meta.LeveragingBag.numberOfChangesDetected, moa.classifiers.meta.LeveragingBag.outputCodesOption, and moa.classifiers.Classifier.resetLearning().
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
        this.ADError = new ADWIN[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ADError[i] = new ADWIN((double) this.deltaAdwinOption.getValue());
        }
        this.numberOfChangesDetected = 0;
        if (this.outputCodesOption.isSet()) {
            this.initMatrixCodes = true;
        }
    }
void moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 107 of file LeveragingBag.java.
References moa.classifiers.meta.LeveragingBag.ADError, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.AbstractClassifier.correctlyClassifies(), moa.classifiers.Classifier.correctlyClassifies(), moa.classifiers.meta.LeveragingBag.deltaAdwinOption, moa.classifiers.meta.LeveragingBag.ensemble, moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.options.FloatOption.getValue(), moa.classifiers.meta.LeveragingBag.initMatrixCodes, moa.options.FlagOption.isSet, moa.classifiers.meta.LeveragingBag.leveraginBagAlgorithmOption, moa.classifiers.meta.LeveragingBag.matrixCodes, moa.classifiers.meta.LeveragingBag.numberOfChangesDetected, moa.classifiers.meta.LeveragingBag.outputCodesOption, moa.classifiers.Classifier.resetLearning(), moa.classifiers.Classifier.trainOnInstance(), and moa.classifiers.meta.LeveragingBag.weightShrinkOption.
{
        int numClasses = inst.numClasses();
        //Output Codes
        if (this.initMatrixCodes == true) {
            this.matrixCodes = new int[this.ensemble.length][inst.numClasses()];
            for (int i = 0; i < this.ensemble.length; i++) {
                int numberOnes;
                int numberZeros;
                do { // until we have the same number of zeros and ones
                    numberOnes = 0;
                    numberZeros = 0;
                    for (int j = 0; j < numClasses; j++) {
                        int result = 0;
                        if (j == 1 && numClasses == 2) {
                            result = 1 - this.matrixCodes[i][0];
                        } else {
                            result = (this.classifierRandom.nextBoolean() ? 1 : 0);
                        }
                        this.matrixCodes[i][j] = result;
                        if (result == 1) {
                            numberOnes++;
                        } else {
                            numberZeros++;
                        }
                    }
                } while ((numberOnes - numberZeros) * (numberOnes - numberZeros) > (this.ensemble.length % 2));
            }
            this.initMatrixCodes = false;
        }
        boolean Change = false;
        Instance weightedInst = (Instance) inst.copy();
        double w = this.weightShrinkOption.getValue();
        //Train ensemble of classifiers
        for (int i = 0; i < this.ensemble.length; i++) {
            double k = 0.0;
            switch (this.leveraginBagAlgorithmOption.getChosenIndex()) {
                case 0: //LeveragingBag
                    k = MiscUtils.poisson(w, this.classifierRandom);
                    break;
                case 1: //LeveragingBagME
                    double error = this.ADError[i].getEstimation();
                    k = !this.ensemble[i].correctlyClassifies(weightedInst) ? 1.0 : (this.classifierRandom.nextDouble() < (error / (1.0 - error)) ? 1.0 : 0.0);
                    break;
                case 2: //LeveragingBagHalf
                    w = 1.0;
                    k = this.classifierRandom.nextBoolean() ? 0.0 : w;
                    break;
                case 3: //LeveragingBagWT
                    w = 1.0;
                    k = 1.0 + MiscUtils.poisson(w, this.classifierRandom);
                    break;
                case 4: //LeveragingSubag
                    w = 1.0;
                    k = MiscUtils.poisson(1, this.classifierRandom);
                    k = (k > 0) ? w : 0;
                    break;
            }
            if (k > 0) {
                if (this.outputCodesOption.isSet()) {
                    weightedInst.setClassValue((double) this.matrixCodes[i][(int) inst.classValue()]);
                }
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
            boolean correctlyClassifies = this.ensemble[i].correctlyClassifies(weightedInst);
            double ErrEstim = this.ADError[i].getEstimation();
            if (this.ADError[i].setInput(correctlyClassifies ? 0 : 1)) {
                if (this.ADError[i].getEstimation() > ErrEstim) {
                    Change = true;
                }
            }
        }
        if (Change) {
            numberOfChangesDetected++;
            double max = 0.0;
            int imax = -1;
            for (int i = 0; i < this.ensemble.length; i++) {
                if (max < this.ADError[i].getEstimation()) {
                    max = this.ADError[i].getEstimation();
                    imax = i;
                }
            }
            if (imax != -1) {
                this.ensemble[imax].resetLearning();
                //this.ensemble[imax].trainOnInstance(inst);
                this.ADError[imax] = new ADWIN((double) this.deltaAdwinOption.getValue());
            }
        }
    }
Member Data Documentation
ADWIN [] moa.classifiers.meta.LeveragingBag.ADError [protected]
Definition at line 80 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.LeveragingBag.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 52 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.resetLearningImpl().
FloatOption moa.classifiers.meta.LeveragingBag.deltaAdwinOption
Initial value:
 new FloatOption("deltaAdwin", 'a',
            "Delta of Adwin change detection", 0.002, 0.0, 1.0)
Definition at line 61 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
Classifier [] moa.classifiers.meta.LeveragingBag.ensemble [protected]
Definition at line 78 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.getModelMeasurementsImpl(), moa.classifiers.meta.LeveragingBag.getSubClassifiers(), moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
IntOption moa.classifiers.meta.LeveragingBag.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models in the bag.", 10, 1, Integer.MAX_VALUE)
Definition at line 55 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.resetLearningImpl().
boolean moa.classifiers.meta.LeveragingBag.initMatrixCodes = false [protected]
Definition at line 86 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
MultiChoiceOption moa.classifiers.meta.LeveragingBag.leveraginBagAlgorithmOption
Initial value:
 new MultiChoiceOption(
            "leveraginBagAlgorithm", 'm', "Leveraging Bagging to use.", new String[]{
                "LeveragingBag", "LeveragingBagME", "LeveragingBagHalf", "LeveragingBagWT", "LeveragingSubag"},
            new String[]{"Leveraging Bagging for evolving data streams using ADWIN",
                "Leveraging Bagging ME using weight 1 if misclassified, otherwise error/(1-error)",
                "Leveraging Bagging Half using resampling without replacement half of the instances",
                "Leveraging Bagging WT without taking out all instances.",
                "Leveraging Subagging using resampling without replacement."
            }, 0)
Definition at line 68 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
int [][] moa.classifiers.meta.LeveragingBag.matrixCodes [protected]
Definition at line 84 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
int moa.classifiers.meta.LeveragingBag.numberOfChangesDetected [protected]
Definition at line 82 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.getModelMeasurementsImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.LeveragingBag.outputCodesOption
Initial value:
 new FlagOption("outputCodes", 'o',
            "Use Output Codes to use binary classifiers.")
Definition at line 65 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
final long moa.classifiers.meta.LeveragingBag.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 45 of file LeveragingBag.java.
FloatOption moa.classifiers.meta.LeveragingBag.weightShrinkOption
Initial value:
 new FloatOption("weightShrink", 'w',
            "The number to use to compute the weight of new instances.", 6, 0.0, Float.MAX_VALUE)
Definition at line 58 of file LeveragingBag.java.
Referenced by moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/LeveragingBag.java