MOA: moa.tasks.RunStreamTasks Class Reference
moa.tasks.RunStreamTasks Class Reference
Task for running several experiments modifying values of parameters.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption taskOption
StringOption streamParameterOption
FloatOption firstValueOption
FloatOption lastValueOption
FloatOption incrementValueOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Protected Attributes
Task task
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for running several experiments modifying values of parameters.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 36 of file RunStreamTasks.java.
Member Function Documentation
Object moa.tasks.RunStreamTasks.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 68 of file RunStreamTasks.java.
References moa.options.AbstractOptionHandler.copy(), moa.tasks.Task.doTask(), moa.tasks.RunStreamTasks.firstValueOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.StringOption.getValue(), moa.options.FloatOption.getValue(), moa.options.ClassOption.getValueAsCLIString(), moa.tasks.RunStreamTasks.incrementValueOption, moa.tasks.RunStreamTasks.lastValueOption, moa.tasks.RunStreamTasks.streamParameterOption, moa.tasks.RunStreamTasks.task, and moa.tasks.RunStreamTasks.taskOption.
{
        Object result = null;
        Task taskBase = (Task) getPreparedClassOption(this.taskOption);
        String commandString = this.taskOption.getValueAsCLIString();
        //for each possible value of the parameter
        for (int valueParameter = (int) this.firstValueOption.getValue();
                valueParameter <= this.lastValueOption.getValue();
                valueParameter += (int) this.incrementValueOption.getValue()) {
            //Add parameter
            this.task = (Task) ((MOAObject) taskBase).copy();
            if (this.task instanceof EvaluateConceptDrift) {
                String stream = ((EvaluateConceptDrift) this.task).streamOption.getValueAsCLIString();
                ((EvaluateConceptDrift) this.task).streamOption.setValueViaCLIString(stream + " -" + streamParameterOption.getValue() + " " + valueParameter);
            }
            //Run task
            result = this.task.doTask(monitor, repository);
            //System.out.println(((AbstractOptionHandler) this.task).getCLICreationString(Task.class));
        }
        return result;
    }
String moa.tasks.RunStreamTasks.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file RunStreamTasks.java.
{
        return "Runs several experiments modifying values of parameters.";
    }
Class<?> moa.tasks.RunStreamTasks.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 61 of file RunStreamTasks.java.
References moa.tasks.Task.getTaskResultType(), and moa.tasks.RunStreamTasks.task.
{
        return this.task.getTaskResultType();
    }
Member Data Documentation
FloatOption moa.tasks.RunStreamTasks.firstValueOption
Initial value:
 new FloatOption("firstValue",
            'f', "First value", 0.0)
Definition at line 51 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask().
FloatOption moa.tasks.RunStreamTasks.incrementValueOption
Initial value:
 new FloatOption("incrementValue",
            'i', "Increment value", 0.1)
Definition at line 57 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask().
FloatOption moa.tasks.RunStreamTasks.lastValueOption
Initial value:
 new FloatOption("lastValue",
            'l', "Last value", 1.0)
Definition at line 54 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask().
final long moa.tasks.RunStreamTasks.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 43 of file RunStreamTasks.java.
StringOption moa.tasks.RunStreamTasks.streamParameterOption
Initial value:
 new StringOption("streamParameter", 'p',
            "Stream parameter to vary.", "b")
Definition at line 48 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask().
Task moa.tasks.RunStreamTasks.task [protected]
Definition at line 65 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask(), and moa.tasks.RunStreamTasks.getTaskResultType().
ClassOption moa.tasks.RunStreamTasks.taskOption
Initial value:
 new ClassOption("task", 't',
            "Task to do.", Task.class, "EvaluatePrequential -l active.ActiveClassifier -i 1000000 -d temp.txt")
Definition at line 45 of file RunStreamTasks.java.
Referenced by moa.tasks.RunStreamTasks.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/RunStreamTasks.java