MOA: moa.classifiers.DecisionStumpTutorial Class Reference
moa.classifiers.DecisionStumpTutorial Class Reference
Public Member Functions
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Public Attributes
IntOption gracePeriodOption
FlagOption binarySplitsOption
ClassOption splitCriterionOption
Protected Member Functions
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
AttributeSplitSuggestion findBestSplit (SplitCriterion criterion)
moa.core.Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
AttributeSplitSuggestion bestSplit
DoubleVector observedClassDistribution
AutoExpandVector
< AttributeClassObserver > attributeObservers
double weightSeenAtLastSplit
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 10 of file DecisionStumpTutorial.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.DecisionStumpTutorial.findBestSplit (SplitCriterion criterion) [protected]
Definition at line 87 of file DecisionStumpTutorial.java.
References moa.classifiers.DecisionStumpTutorial.attributeObservers, moa.classifiers.DecisionStumpTutorial.binarySplitsOption, moa.core.DoubleVector.getArrayCopy(), moa.options.FlagOption.isSet, and moa.classifiers.DecisionStumpTutorial.observedClassDistribution.
Referenced by moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
{
        AttributeSplitSuggestion bestFound = null;
        double bestMerit = Double.NEGATIVE_INFINITY;
        double[] preSplitDist = this.observedClassDistribution.getArrayCopy();
        for (int i = 0; i < this.attributeObservers.size(); i++) {
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs != null) {
                AttributeSplitSuggestion suggestion =
                    obs.getBestEvaluatedSplitSuggestion(
                        criterion,
                        preSplitDist,
                        i,
                        this.binarySplitsOption.isSet());
                if (suggestion.merit > bestMerit) {
                    bestMerit = suggestion.merit;
                    bestFound = suggestion;
                }
            }
        }
        return bestFound;
    }
void moa.classifiers.DecisionStumpTutorial.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 109 of file DecisionStumpTutorial.java.
{
    }
moa.core.Measurement [] moa.classifiers.DecisionStumpTutorial.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 112 of file DecisionStumpTutorial.java.
{
        return null;
    }
double [] moa.classifiers.DecisionStumpTutorial.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 68 of file DecisionStumpTutorial.java.
References moa.classifiers.DecisionStumpTutorial.bestSplit, moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.DecisionStumpTutorial.observedClassDistribution.
{
        if (this.bestSplit != null) {
            int branch = this.bestSplit.splitTest.branchForInstance(inst);
            if (branch >= 0) {
                return this.bestSplit
                        .resultingClassDistributionFromSplit(branch);
            }
        }
        return this.observedClassDistribution.getArrayCopy();
    }
boolean moa.classifiers.DecisionStumpTutorial.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 33 of file DecisionStumpTutorial.java.
{
        return false;
    }
AttributeClassObserver moa.classifiers.DecisionStumpTutorial.newNominalClassObserver () [protected]
Definition at line 79 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
{
        return new NominalAttributeClassObserver();
    }
AttributeClassObserver moa.classifiers.DecisionStumpTutorial.newNumericClassObserver () [protected]
Definition at line 83 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
{
        return new GaussianNumericAttributeClassObserver();
    }
void moa.classifiers.DecisionStumpTutorial.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 38 of file DecisionStumpTutorial.java.
References moa.classifiers.DecisionStumpTutorial.attributeObservers, moa.classifiers.DecisionStumpTutorial.bestSplit, moa.classifiers.DecisionStumpTutorial.observedClassDistribution, and moa.classifiers.DecisionStumpTutorial.weightSeenAtLastSplit.
{
        this.bestSplit = null;
        this.observedClassDistribution = new DoubleVector();
        this.attributeObservers = new AutoExpandVector<AttributeClassObserver>();
        this.weightSeenAtLastSplit = 0.0;
    }
void moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 46 of file DecisionStumpTutorial.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.DecisionStumpTutorial.attributeObservers, moa.classifiers.DecisionStumpTutorial.bestSplit, moa.classifiers.DecisionStumpTutorial.findBestSplit(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.DecisionStumpTutorial.gracePeriodOption, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.DecisionStumpTutorial.newNominalClassObserver(), moa.classifiers.DecisionStumpTutorial.newNumericClassObserver(), moa.classifiers.DecisionStumpTutorial.observedClassDistribution, moa.classifiers.DecisionStumpTutorial.splitCriterionOption, moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.DecisionStumpTutorial.weightSeenAtLastSplit.
{
        this.observedClassDistribution.addToValue((int) inst.classValue(), inst
                .weight());
        for (int i = 0; i < inst.numAttributes() - 1; i++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs == null) {
                obs = inst.attribute(instAttIndex).isNominal() ?
                    newNominalClassObserver() : newNumericClassObserver();
                this.attributeObservers.set(i, obs);
            }
            obs.observeAttributeClass(inst.value(instAttIndex), (int) inst
                    .classValue(), inst.weight());
        }
        if (this.trainingWeightSeenByModel - this.weightSeenAtLastSplit >=
                this.gracePeriodOption.getValue()) {
            this.bestSplit = findBestSplit((SplitCriterion)
                getPreparedClassOption(this.splitCriterionOption));
            this.weightSeenAtLastSplit = this.trainingWeightSeenByModel;
        }
    }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.DecisionStumpTutorial.attributeObservers [protected]
Definition at line 29 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.findBestSplit(), moa.classifiers.DecisionStumpTutorial.resetLearningImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
AttributeSplitSuggestion moa.classifiers.DecisionStumpTutorial.bestSplit [protected]
Definition at line 25 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.getVotesForInstance(), moa.classifiers.DecisionStumpTutorial.resetLearningImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
FlagOption moa.classifiers.DecisionStumpTutorial.binarySplitsOption
Initial value:
 new FlagOption("binarySplits", 'b',
            "Only allow binary splits.")
Definition at line 18 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.findBestSplit().
IntOption moa.classifiers.DecisionStumpTutorial.gracePeriodOption
Initial value:
 new IntOption("gracePeriod", 'g',
            "The number of instances to observe between model changes.",
            1000, 0, Integer.MAX_VALUE)
Definition at line 14 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
DoubleVector moa.classifiers.DecisionStumpTutorial.observedClassDistribution [protected]
Definition at line 27 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.findBestSplit(), moa.classifiers.DecisionStumpTutorial.getVotesForInstance(), moa.classifiers.DecisionStumpTutorial.resetLearningImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
final long moa.classifiers.DecisionStumpTutorial.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 12 of file DecisionStumpTutorial.java.
ClassOption moa.classifiers.DecisionStumpTutorial.splitCriterionOption
Initial value:
 new ClassOption("splitCriterion",
            'c', "Split criterion to use.", SplitCriterion.class,
            "InfoGainSplitCriterion")
Definition at line 21 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
double moa.classifiers.DecisionStumpTutorial.weightSeenAtLastSplit [protected]
Definition at line 31 of file DecisionStumpTutorial.java.
Referenced by moa.classifiers.DecisionStumpTutorial.resetLearningImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
examples/java/moa/classifiers/DecisionStumpTutorial.java