MOA: moa.gui.outliertab.OutlierAlgoPanel Class Reference
moa.gui.outliertab.OutlierAlgoPanel Class Reference
Public Member Functions
OutlierAlgoPanel ()
void renderAlgoPanel ()
void actionPerformed (ActionEvent e)
MyBaseOutlierDetector getClusterer0 ()
MyBaseOutlierDetector getClusterer1 ()
ClusteringStream getStream ()
String getStreamValueAsCLIString ()
String getAlgorithm0ValueAsCLIString ()
String getAlgorithm1ValueAsCLIString ()
void setStreamValueAsCLIString (String s)
void setAlgorithm0ValueAsCLIString (String s)
void setAlgorithm1ValueAsCLIString (String s)
void applyChanges ()
void setPanelTitle (String title)
Protected Attributes
List< OptionEditComponent > editComponents = new LinkedList<OptionEditComponent>()
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
ClassOption streamOption
ClassOption algorithmOption0
ClassOption algorithmOption1
Detailed Description
Definition at line 42 of file OutlierAlgoPanel.java.
Constructor & Destructor Documentation
moa.gui.outliertab.OutlierAlgoPanel.OutlierAlgoPanel ()
Definition at line 56 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.initComponents().
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
{
        initComponents();
    }
Member Function Documentation
void moa.gui.outliertab.OutlierAlgoPanel.actionPerformed (ActionEvent e)
Definition at line 135 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1, moa.gui.outliertab.OutlierAlgoPanel.editComponents, and moa.options.ClassOption.setValueViaCLIString().
{
        if (e.getActionCommand().equals("clear")){
            algorithmOption1.setValueViaCLIString("None");
            editComponents.get(2).setEditState("None");
        }
    }
void moa.gui.outliertab.OutlierAlgoPanel.applyChanges ()
Definition at line 208 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.editComponents.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer0(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer1(), moa.gui.outliertab.OutlierAlgoPanel.getStream(), and moa.gui.outliertab.OutlierAlgoPanel.getStreamValueAsCLIString().
{
            for (OptionEditComponent editor : this.editComponents) {
                    try {
                            editor.applyState();
                    } catch (Exception ex) {
                            GUIUtils.showExceptionDialog(this, "Problem with option "
                                            + editor.getEditedOption().getName(), ex);
                    }
            }
    }
String moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm0ValueAsCLIString ()
Definition at line 182 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption0, moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed().
{
        applyChanges();
        return algorithmOption0.getValueAsCLIString();
    }
String moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm1ValueAsCLIString ()
Definition at line 187 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1, moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
{
        applyChanges();
        return algorithmOption1.getValueAsCLIString();
    }
MyBaseOutlierDetector moa.gui.outliertab.OutlierAlgoPanel.getClusterer0 ()
Definition at line 142 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption0, moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.outliertab.OutlierSetupTab.getOutlierer0().
{
        MyBaseOutlierDetector c = null;
        applyChanges();
        try {
            c = (MyBaseOutlierDetector) ClassOption.cliStringToObject(algorithmOption0.getValueAsCLIString(), MyBaseOutlierDetector.class, null);
        } catch (Exception ex) {
            Logger.getLogger(OutlierAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }
MyBaseOutlierDetector moa.gui.outliertab.OutlierAlgoPanel.getClusterer1 ()
Definition at line 153 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1, moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), and moa.options.ClassOption.getValueAsCLIString().
Referenced by moa.gui.outliertab.OutlierSetupTab.getOutlierer1().
{
        MyBaseOutlierDetector c = null;
        if (algorithmOption1.getValueAsCLIString().equalsIgnoreCase("None") == false) {
            applyChanges();
            try {
                c = (MyBaseOutlierDetector) ClassOption.cliStringToObject(algorithmOption1.getValueAsCLIString(), MyBaseOutlierDetector.class, null);
            } catch (Exception ex) {
                Logger.getLogger(OutlierAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return c;
    }
ClusteringStream moa.gui.outliertab.OutlierAlgoPanel.getStream ()
Definition at line 166 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), moa.options.ClassOption.getValueAsCLIString(), and moa.gui.outliertab.OutlierAlgoPanel.streamOption.
Referenced by moa.gui.outliertab.OutlierSetupTab.getStream0().
{
        ClusteringStream s = null;
        applyChanges();
        try {
            s = (ClusteringStream) ClassOption.cliStringToObject(streamOption.getValueAsCLIString(), ClusteringStream.class, null);
        } catch (Exception ex) {
            Logger.getLogger(OutlierAlgoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return s;
    }
String moa.gui.outliertab.OutlierAlgoPanel.getStreamValueAsCLIString ()
Definition at line 177 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), moa.options.ClassOption.getValueAsCLIString(), and moa.gui.outliertab.OutlierAlgoPanel.streamOption.
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed().
{
        applyChanges();
        return streamOption.getValueAsCLIString();
    }
void moa.gui.outliertab.OutlierAlgoPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 230 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.OutlierAlgoPanel().
{
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cluster Algorithm Setup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel ()
Definition at line 60 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption0, moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1, moa.gui.outliertab.OutlierAlgoPanel.editComponents, moa.options.ClassOption.getEditComponent(), and moa.gui.outliertab.OutlierAlgoPanel.streamOption.
Referenced by moa.gui.outliertab.OutlierSetupTab.OutlierSetupTab().
{
        setLayout(new BorderLayout());
        ArrayList<Option> options = new ArrayList<Option>();
        options.add(streamOption);
        options.add(algorithmOption0);
        options.add(algorithmOption1);
        JPanel optionsPanel = new JPanel();
        GridBagLayout gbLayout = new GridBagLayout();
        optionsPanel.setLayout(gbLayout);
        //Create generic label constraints
        GridBagConstraints gbcLabel = new GridBagConstraints();
        gbcLabel.gridx = 0;
        gbcLabel.fill = GridBagConstraints.NONE;
        gbcLabel.anchor = GridBagConstraints.EAST;
        gbcLabel.weightx = 0;
        gbcLabel.insets = new Insets(5, 5, 5, 5);
        //Create generic editor constraints
        GridBagConstraints gbcOption = new GridBagConstraints();
        gbcOption.gridx = 1;
        gbcOption.fill = GridBagConstraints.HORIZONTAL;
        gbcOption.anchor = GridBagConstraints.CENTER;
        gbcOption.weightx = 1;
        gbcOption.insets = new Insets(5, 5, 5, 0);
        //Stream Option
        JLabel labelStream = new JLabel("Stream");
        labelStream.setToolTipText("Stream to use.");
        optionsPanel.add(labelStream, gbcLabel);
        JComponent editorStream = streamOption.getEditComponent();
        labelStream.setLabelFor(editorStream);
        editComponents.add((OptionEditComponent) editorStream);
        optionsPanel.add(editorStream, gbcOption);
        //Algorithm0 Option
        JLabel labelAlgo0 = new JLabel("Algorithm1");
        labelAlgo0.setForeground(Color.RED);
        labelAlgo0.setToolTipText("Algorithm to use.");
        optionsPanel.add(labelAlgo0, gbcLabel);
        JComponent editorAlgo0 = algorithmOption0.getEditComponent();
        labelAlgo0.setLabelFor(editorAlgo0);
        editComponents.add((OptionEditComponent) editorAlgo0);
        optionsPanel.add(editorAlgo0, gbcOption);
        //Algorithm1 Option
        JLabel labelAlgo1 = new JLabel("Algorithm2");
        labelAlgo1.setForeground(Color.BLUE);
        labelAlgo1.setToolTipText("Algorithm to use.");
        optionsPanel.add(labelAlgo1, gbcLabel);
        JComponent editorAlgo1 = algorithmOption1.getEditComponent();
        labelAlgo1.setLabelFor(editorAlgo1);
        editComponents.add((OptionEditComponent) editorAlgo1);
        optionsPanel.add(editorAlgo1, gbcOption);
        //use comparison Algorithm Option
        GridBagConstraints gbcClearButton = new GridBagConstraints();
        gbcClearButton.gridx = 2;
        gbcClearButton.gridy = 2;
        gbcClearButton.fill = GridBagConstraints.NONE;
        gbcClearButton.anchor = GridBagConstraints.CENTER;
        gbcClearButton.insets = new Insets(5, 0, 5, 5);
        JButton clearButton = new JButton("Clear");
        clearButton.addActionListener(this);
        clearButton.setActionCommand("clear");
        optionsPanel.add(clearButton, gbcClearButton);
        add(optionsPanel);
    }
void moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString (String s)
Definition at line 198 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption0, moa.gui.outliertab.OutlierAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), and moa.options.ClassOption.setValueViaCLIString().
Referenced by moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile().
{
        algorithmOption0.setValueViaCLIString(s);
        editComponents.get(1).setEditState(algorithmOption0.getValueAsCLIString());
    }
void moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm1ValueAsCLIString (String s)
Definition at line 203 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1, moa.gui.outliertab.OutlierAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), and moa.options.ClassOption.setValueViaCLIString().
{
        algorithmOption1.setValueViaCLIString(s);
        editComponents.get(2).setEditState(algorithmOption1.getValueAsCLIString());
    }
void moa.gui.outliertab.OutlierAlgoPanel.setPanelTitle (String title)
Definition at line 219 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
{
        setBorder(javax.swing.BorderFactory.createTitledBorder(null,title, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
    }
void moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString (String s)
Definition at line 193 of file OutlierAlgoPanel.java.
References moa.gui.outliertab.OutlierAlgoPanel.editComponents, moa.options.ClassOption.getValueAsCLIString(), moa.options.ClassOption.setValueViaCLIString(), and moa.gui.outliertab.OutlierAlgoPanel.streamOption.
Referenced by moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile().
{
        streamOption.setValueViaCLIString(s);
        editComponents.get(0).setEditState(streamOption.getValueAsCLIString());
    }
Member Data Documentation
ClassOption moa.gui.outliertab.OutlierAlgoPanel.algorithmOption0 [private]
Initial value:
 new ClassOption("Algorithm0", 'a',
               "Algorithm to use.", MyBaseOutlierDetector.class, "MCOD.MCOD")
Definition at line 50 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer0(), moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel(), and moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString().
ClassOption moa.gui.outliertab.OutlierAlgoPanel.algorithmOption1 [private]
Initial value:
 new ClassOption("Algorithm1", 'a',
               "Algorithm to use.", MyBaseOutlierDetector.class, "Angiulli.ExactSTORM")
Definition at line 53 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.actionPerformed(), moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer1(), moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel(), and moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm1ValueAsCLIString().
List<OptionEditComponent> moa.gui.outliertab.OutlierAlgoPanel.editComponents = new LinkedList<OptionEditComponent>() [protected]
Definition at line 44 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.actionPerformed(), moa.gui.outliertab.OutlierAlgoPanel.applyChanges(), moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm1ValueAsCLIString(), and moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString().
ClassOption moa.gui.outliertab.OutlierAlgoPanel.streamOption [private]
Initial value:
 new ClassOption("Stream", 's',
                "", ClusteringStream.class,
                "RandomRBFGeneratorEvents")
Definition at line 46 of file OutlierAlgoPanel.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.getStream(), moa.gui.outliertab.OutlierAlgoPanel.getStreamValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel(), and moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString().
The documentation for this class was generated from the following file:
main/java/moa/gui/outliertab/OutlierAlgoPanel.java