MOA: moa.recommender.rc.utils.Vector Class Reference
moa.recommender.rc.utils.Vector Class Reference
Public Member Functions
abstract int size ()
abstract void set (int index, double val)
abstract void remove (int index)
abstract Double get (int index)
abstract Iterator< Pair
< Integer, Double > > iterator ()
abstract Set< Integer > getIdxs ()
double dotProduct (Vector vec)
double norm ()
abstract Vector copy ()
Static Private Attributes
static final long serialVersionUID = 2440314068879207731L
Detailed Description
Definition at line 27 of file Vector.java.
Member Function Documentation
abstract Vector moa.recommender.rc.utils.Vector.copy () [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
double moa.recommender.rc.utils.Vector.dotProduct (Vector vec)
Definition at line 39 of file Vector.java.
References moa.recommender.rc.utils.Vector.dotProduct(), moa.recommender.rc.utils.Vector.get(), moa.recommender.rc.utils.Vector.iterator(), and moa.recommender.rc.utils.Vector.size().
Referenced by moa.recommender.rc.utils.Vector.dotProduct().
{
        if (size() > vec.size()) return vec.dotProduct(this);
        Iterator<Pair<Integer, Double>> it = iterator();
        double ret = 0;
        while(it.hasNext()) {
            Pair<Integer, Double> ind = it.next();
            Double val1 = ind.getSecond();
            Double val2 = vec.get(ind.getFirst());
            if (val2 != null) ret += val1*val2;
        }
        return ret;
    }
abstract Double moa.recommender.rc.utils.Vector.get (int index) [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
Referenced by moa.recommender.rc.utils.Vector.dotProduct().
abstract Set<Integer> moa.recommender.rc.utils.Vector.getIdxs () [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
abstract Iterator<Pair<Integer, Double> > moa.recommender.rc.utils.Vector.iterator () [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
Referenced by moa.recommender.rc.utils.Vector.dotProduct(), and moa.recommender.rc.utils.Vector.norm().
double moa.recommender.rc.utils.Vector.norm ()
Definition at line 54 of file Vector.java.
References moa.recommender.rc.utils.Vector.iterator().
{
        Iterator<Pair<Integer, Double>> it = iterator();
        double ret = 0;
        while(it.hasNext())
            ret += Math.pow(it.next().getSecond(), 2);
        return Math.sqrt(ret);
    }
abstract void moa.recommender.rc.utils.Vector.remove (int index) [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
abstract void moa.recommender.rc.utils.Vector.set (int index, double val) [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
abstract int moa.recommender.rc.utils.Vector.size () [pure virtual]
Implemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
Referenced by moa.recommender.rc.utils.Vector.dotProduct().
Member Data Documentation
final long moa.recommender.rc.utils.Vector.serialVersionUID = 2440314068879207731L [static, private]
Reimplemented in moa.recommender.rc.utils.DenseVector, and moa.recommender.rc.utils.SparseVector.
Definition at line 31 of file Vector.java.
The documentation for this class was generated from the following file:
main/java/moa/recommender/rc/utils/Vector.java