MOA: moa.clusterers.outliers.MCOD.MicroCluster Class Reference
moa.clusterers.outliers.MCOD.MicroCluster Class Reference
Public Member Functions
MicroCluster (ISBNode mcc)
void AddNode (ISBNode node)
void RemoveNode (ISBNode node)
int GetNodesCount ()
int dimensions ()
The number of dimensions.
double get (int index)
boolean equals (Object obj)
int compareTo (MicroCluster that)
Public Attributes
ISBNode mcc
ArrayList< ISBNode > nodes
Detailed Description
Definition at line 27 of file MicroCluster.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.MCOD.MicroCluster.MicroCluster (ISBNode mcc)
Definition at line 31 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.AddNode(), and moa.clusterers.outliers.MCOD.MicroCluster.nodes.
{
        this.mcc = mcc;
        nodes = new ArrayList<ISBNode>();
        AddNode(mcc);
    }
Member Function Documentation
void moa.clusterers.outliers.MCOD.MicroCluster.AddNode (ISBNode node)
Definition at line 37 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.nodes.
Referenced by moa.clusterers.outliers.MCOD.MicroCluster.MicroCluster(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        if (node != null)
            nodes.add(node);
    }
int moa.clusterers.outliers.MCOD.MicroCluster.compareTo (MicroCluster that)
Definition at line 80 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.dimensions(), moa.clusterers.outliers.MCOD.StreamObj.get(), moa.clusterers.outliers.MCOD.MicroCluster.mcc, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
{
        int dimensions = Math.min(this.dimensions(), that.dimensions());
        for (int i = 0; i < dimensions; i++) {
            double v1 = this.mcc.obj.get(i);
            double v2 = that.mcc.obj.get(i);
            if (v1 > v2) {
                return +1;
            }
            if (v1 < v2) {
                return -1;
            }
        }
        if (this.dimensions() > dimensions) {
            return +1;
        }
        if (that.dimensions() > dimensions) {
            return -1;
        }
        return 0;
    }
int moa.clusterers.outliers.MCOD.MicroCluster.dimensions ()
The number of dimensions.
Implements moa.clusterers.outliers.utils.mtree.DistanceFunctions.EuclideanCoordinate.
Definition at line 52 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.StreamObj.dimensions(), moa.clusterers.outliers.MCOD.MicroCluster.mcc, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.MicroCluster.compareTo(), and moa.clusterers.outliers.MCOD.MicroCluster.equals().
{
        return mcc.obj.dimensions();
    }
boolean moa.clusterers.outliers.MCOD.MicroCluster.equals (Object obj)
Definition at line 62 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.dimensions(), moa.clusterers.outliers.MCOD.StreamObj.get(), moa.clusterers.outliers.MCOD.MicroCluster.mcc, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
{
        if (obj instanceof MicroCluster) {
            MicroCluster that = (MicroCluster) obj;
            if (this.dimensions() != that.dimensions()) {
                return false;
            }
            for (int i = 0; i < this.dimensions(); i++) {
                if (this.mcc.obj.get(i) != that.mcc.obj.get(i)) {
                    return false;
                }
            }
            return true;
        } else {
            return false;
        }
    }
double moa.clusterers.outliers.MCOD.MicroCluster.get (int index)
Definition at line 57 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.StreamObj.get(), moa.clusterers.outliers.MCOD.MicroCluster.mcc, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        return mcc.obj.get(index);
    }
int moa.clusterers.outliers.MCOD.MicroCluster.GetNodesCount ()
Definition at line 47 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.nodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode().
{
        return nodes.size();
    }
void moa.clusterers.outliers.MCOD.MicroCluster.RemoveNode (ISBNode node)
Definition at line 42 of file MicroCluster.java.
References moa.clusterers.outliers.MCOD.MicroCluster.nodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode().
{
        if (node != null)
            nodes.remove(node);
    }
Member Data Documentation
ISBNode moa.clusterers.outliers.MCOD.MicroCluster.mcc
Definition at line 28 of file MicroCluster.java.
Referenced by moa.clusterers.outliers.MCOD.MicroCluster.compareTo(), moa.clusterers.outliers.MCOD.MicroCluster.dimensions(), moa.clusterers.outliers.MCOD.MicroCluster.equals(), moa.clusterers.outliers.MCOD.MicroCluster.get(), moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
ArrayList<ISBNode> moa.clusterers.outliers.MCOD.MicroCluster.nodes
Definition at line 29 of file MicroCluster.java.
Referenced by moa.clusterers.outliers.MCOD.MicroCluster.AddNode(), moa.clusterers.outliers.MCOD.MicroCluster.GetNodesCount(), moa.clusterers.outliers.MCOD.MicroCluster.MicroCluster(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), and moa.clusterers.outliers.MCOD.MicroCluster.RemoveNode().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/MicroCluster.java