MOA: moa.clusterers.outliers.SimpleCOD.Test Class Reference
moa.clusterers.outliers.SimpleCOD.Test Class Reference
Static Public Member Functions
static void main (String[] args) throws Exception
Detailed Description
Definition at line 27 of file Test.java.
Member Function Documentation
static void moa.clusterers.outliers.SimpleCOD.Test.main (String[] args) throws Exception [static]
Definition at line 28 of file Test.java.
References moa.options.IntOption.getValue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.kOption, moa.options.AbstractOptionHandler.prepareForUse(), moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.radiusOption, moa.clusterers.AbstractClusterer.setModelContext(), moa.options.FloatOption.setValue(), moa.options.IntOption.setValue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.SimpleCOD(), and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
    {
        //if (true) return;
        int numInstances = 30;
        moa.streams.ArffFileStream stream = new ArffFileStream("./datasets/debug_1.txt", -1);
        //RandomRBFGeneratorEvents stream = new RandomRBFGeneratorEvents();
        stream.prepareForUse();
        SimpleCOD myOutlierDetector= new SimpleCOD();
        myOutlierDetector.kOption.setValue(3);
        myOutlierDetector.radiusOption.setValue(5);
        myOutlierDetector.windowSizeOption.setValue(6);
        myOutlierDetector.setModelContext(stream.getHeader());
        myOutlierDetector.prepareForUse();
        Long tmStart = System.currentTimeMillis();
        int numberSamples = 0;
        int w = myOutlierDetector.windowSizeOption.getValue();
        while (stream.hasMoreInstances() && (numberSamples < numInstances)) {
            Instance newInst = stream.nextInstance();
            myOutlierDetector.processNewInstanceImpl(newInst);
            numberSamples++;
        }
        //myOutlierDetector.PrintOutliers();
        System.out.println("Total time = " + (System.currentTimeMillis() - tmStart) + " ms");
    }
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/SimpleCOD/Test.java