MOA: moa.gui.RegressionTaskManagerPanel Class Reference
moa.gui.RegressionTaskManagerPanel Class Reference
This panel displays the running tasks.
Classes
class ProgressCellRenderer
class TaskTableModel
Public Member Functions
RegressionTaskManagerPanel ()
void setPreviewPanel (PreviewPanel previewPanel)
void setTaskString (String cliString)
void setTaskString (String cliString, boolean storePreference)
void runTask (Task task)
void taskSelectionChanged ()
TaskThread[] getSelectedTasks ()
void pauseSelectedTasks ()
void resumeSelectedTasks ()
void cancelSelectedTasks ()
void deleteSelectedTasks ()
void copyClipBoardConfiguration ()
void saveLogSelectedTasks ()
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final int MILLISECS_BETWEEN_REFRESH = 600
static String exportFileExtension = "log"
Protected Attributes
RegressionMainTask currentTask = new EvaluatePrequentialRegression()
List< TaskThread > taskList = new ArrayList<TaskThread>()
JButton configureTaskButton = new JButton("Configure")
JTextField taskDescField = new JTextField()
JButton runTaskButton = new JButton("Run")
TaskTableModel taskTableModel
JTable taskTable
JButton pauseTaskButton = new JButton("Pause")
JButton resumeTaskButton = new JButton("Resume")
JButton cancelTaskButton = new JButton("Cancel")
JButton deleteTaskButton = new JButton("Delete")
PreviewPanel previewPanel
Static Private Member Functions
static void createAndShowGUI ()
Private Attributes
Preferences prefs
final String PREF_NAME = "currentTask"
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays the running tasks.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 75 of file RegressionTaskManagerPanel.java.
Constructor & Destructor Documentation
moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel ()
Definition at line 216 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.cancelSelectedTasks(), moa.gui.RegressionTaskManagerPanel.cancelTaskButton, moa.gui.RegressionTaskManagerPanel.configureTaskButton, moa.gui.RegressionTaskManagerPanel.copyClipBoardConfiguration(), moa.gui.RegressionTaskManagerPanel.currentTask, moa.gui.RegressionTaskManagerPanel.deleteSelectedTasks(), moa.gui.RegressionTaskManagerPanel.deleteTaskButton, moa.options.AbstractOptionHandler.getCLICreationString(), moa.gui.RegressionTaskManagerPanel.MILLISECS_BETWEEN_REFRESH, moa.gui.RegressionTaskManagerPanel.pauseSelectedTasks(), moa.gui.RegressionTaskManagerPanel.pauseTaskButton, moa.gui.RegressionTaskManagerPanel.PREF_NAME, moa.gui.RegressionTaskManagerPanel.prefs, moa.gui.RegressionTaskManagerPanel.resumeSelectedTasks(), moa.gui.RegressionTaskManagerPanel.resumeTaskButton, moa.gui.RegressionTaskManagerPanel.runTask(), moa.gui.RegressionTaskManagerPanel.runTaskButton, moa.gui.RegressionTaskManagerPanel.saveLogSelectedTasks(), moa.gui.RegressionTaskManagerPanel.setTaskString(), moa.gui.RegressionTaskManagerPanel.taskDescField, moa.gui.RegressionTaskManagerPanel.taskSelectionChanged(), moa.gui.RegressionTaskManagerPanel.taskTable, and moa.gui.RegressionTaskManagerPanel.taskTableModel.
Referenced by moa.gui.RegressionTaskManagerPanel.createAndShowGUI().
{
        // Read current task preference
        prefs = Preferences.userRoot().node(this.getClass().getName());
        currentTask = new EvaluatePrequentialRegression();
        String taskText = this.currentTask.getCLICreationString(RegressionMainTask.class);
        String propertyValue = prefs.get(PREF_NAME, taskText);
        //this.taskDescField.setText(propertyValue);
        setTaskString(propertyValue, false); //Not store preference
        this.taskDescField.setEditable(false);
        final Component comp = this.taskDescField;
        this.taskDescField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    if ((evt.getButton() == MouseEvent.BUTTON3)
                            || ((evt.getButton() == MouseEvent.BUTTON1) && evt.isAltDown() && evt.isShiftDown())) {
                        JPopupMenu menu = new JPopupMenu();
                        JMenuItem item;
                        item = new JMenuItem("Copy configuration to clipboard");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                copyClipBoardConfiguration();
                            }
                        });
                        menu.add(item);
                        item = new JMenuItem("Save selected tasks to file");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent arg0) {
                                saveLogSelectedTasks();
                            }
                        });
                        menu.add(item);
                        item = new JMenuItem("Enter configuration...");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent arg0) {
                                String newTaskString = JOptionPane.showInputDialog("Insert command line");
                                if (newTaskString != null) {
                                    setTaskString(newTaskString);
                                }
                            }
                        });
                        menu.add(item);
                        menu.show(comp, evt.getX(), evt.getY());
                    }
                }
            }
        });
        JPanel configPanel = new JPanel();
        configPanel.setLayout(new BorderLayout());
        configPanel.add(this.configureTaskButton, BorderLayout.WEST);
        configPanel.add(this.taskDescField, BorderLayout.CENTER);
        configPanel.add(this.runTaskButton, BorderLayout.EAST);
        this.taskTableModel = new TaskTableModel();
        this.taskTable = new JTable(this.taskTableModel);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        this.taskTable.getColumnModel().getColumn(1).setCellRenderer(
                centerRenderer);
        this.taskTable.getColumnModel().getColumn(2).setCellRenderer(
                centerRenderer);
        this.taskTable.getColumnModel().getColumn(4).setCellRenderer(
                new ProgressCellRenderer());
        JPanel controlPanel = new JPanel();
        controlPanel.add(this.pauseTaskButton);
        controlPanel.add(this.resumeTaskButton);
        controlPanel.add(this.cancelTaskButton);
        controlPanel.add(this.deleteTaskButton);
        setLayout(new BorderLayout());
        add(configPanel, BorderLayout.NORTH);
        add(new JScrollPane(this.taskTable), BorderLayout.CENTER);
        add(controlPanel, BorderLayout.SOUTH);
        this.taskTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
                    @Override
                    public void valueChanged(ListSelectionEvent arg0) {
                        taskSelectionChanged();
                    }
                });
        this.configureTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                String newTaskString = ClassOptionSelectionPanel.showSelectClassDialog(RegressionTaskManagerPanel.this,
                        "Configure task", RegressionMainTask.class,
                        RegressionTaskManagerPanel.this.currentTask.getCLICreationString(RegressionMainTask.class),
                        null);
                setTaskString(newTaskString);
            }
        });
        this.runTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                runTask((Task) RegressionTaskManagerPanel.this.currentTask.copy());
            }
        });
        this.pauseTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                pauseSelectedTasks();
            }
        });
        this.resumeTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                resumeSelectedTasks();
            }
        });
        this.cancelTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                cancelSelectedTasks();
            }
        });
        this.deleteTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                deleteSelectedTasks();
            }
        });
        javax.swing.Timer updateListTimer = new javax.swing.Timer(
                MILLISECS_BETWEEN_REFRESH, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                RegressionTaskManagerPanel.this.taskTable.repaint();
            }
        });
        updateListTimer.start();
        setPreferredSize(new Dimension(0, 200));
    }
Member Function Documentation
void moa.gui.RegressionTaskManagerPanel.cancelSelectedTasks ()
Definition at line 436 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.cancelTask();
        }
    }
void moa.gui.RegressionTaskManagerPanel.copyClipBoardConfiguration ()
Definition at line 452 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.taskDescField.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        StringSelection selection = new StringSelection(this.taskDescField.getText().trim());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }
static void moa.gui.RegressionTaskManagerPanel.createAndShowGUI () [static, private]
Definition at line 491 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
Referenced by moa.gui.RegressionTaskManagerPanel.main().
{
        // Create and set up the window.
        JFrame frame = new JFrame("Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create and set up the content pane.
        JPanel panel = new RegressionTaskManagerPanel();
        panel.setOpaque(true); // content panes must be opaque
        frame.setContentPane(panel);
        // Display the window.
        frame.pack();
        // frame.setSize(400, 400);
        frame.setVisible(true);
    }
void moa.gui.RegressionTaskManagerPanel.deleteSelectedTasks ()
Definition at line 443 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.getSelectedTasks(), moa.gui.RegressionTaskManagerPanel.taskList, and moa.gui.RegressionTaskManagerPanel.taskTableModel.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.cancelTask();
            this.taskList.remove(thread);
        }
        this.taskTableModel.fireTableDataChanged();
    }
TaskThread [] moa.gui.RegressionTaskManagerPanel.getSelectedTasks ()
Definition at line 413 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.taskList, and moa.gui.RegressionTaskManagerPanel.taskTable.
Referenced by moa.gui.RegressionTaskManagerPanel.cancelSelectedTasks(), moa.gui.RegressionTaskManagerPanel.deleteSelectedTasks(), moa.gui.RegressionTaskManagerPanel.pauseSelectedTasks(), moa.gui.RegressionTaskManagerPanel.resumeSelectedTasks(), moa.gui.RegressionTaskManagerPanel.saveLogSelectedTasks(), and moa.gui.RegressionTaskManagerPanel.taskSelectionChanged().
{
        int[] selectedRows = this.taskTable.getSelectedRows();
        TaskThread[] selectedTasks = new TaskThread[selectedRows.length];
        for (int i = 0; i < selectedRows.length; i++) {
            selectedTasks[i] = this.taskList.get(selectedRows[i]);
        }
        return selectedTasks;
    }
static void moa.gui.RegressionTaskManagerPanel.main (String[] args) [static]
Definition at line 508 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.createAndShowGUI().
{
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    createAndShowGUI();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
void moa.gui.RegressionTaskManagerPanel.pauseSelectedTasks ()
Definition at line 422 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.pauseTask();
        }
    }
void moa.gui.RegressionTaskManagerPanel.resumeSelectedTasks ()
Definition at line 429 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.resumeTask();
        }
    }
void moa.gui.RegressionTaskManagerPanel.runTask (Task task)
Definition at line 393 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.taskList, moa.gui.RegressionTaskManagerPanel.taskTable, and moa.gui.RegressionTaskManagerPanel.taskTableModel.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread thread = new TaskThread(task);
        this.taskList.add(0, thread);
        this.taskTableModel.fireTableDataChanged();
        this.taskTable.setRowSelectionInterval(0, 0);
        thread.start();
    }
void moa.gui.RegressionTaskManagerPanel.saveLogSelectedTasks ()
Definition at line 460 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.exportFileExtension, and moa.gui.RegressionTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        String tasksLog = "";
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            tasksLog += ((OptionHandler) thread.getTask()).getCLICreationString(RegressionMainTask.class) + "\n";
        }
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        fileChooser.addChoosableFileFilter(new FileExtensionFilter(
                exportFileExtension));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File chosenFile = fileChooser.getSelectedFile();
            String fileName = chosenFile.getPath();
            if (!chosenFile.exists()
                    && !fileName.endsWith(exportFileExtension)) {
                fileName = fileName + "." + exportFileExtension;
            }
            try {
                PrintWriter out = new PrintWriter(new BufferedWriter(
                        new FileWriter(fileName)));
                out.write(tasksLog);
                out.close();
            } catch (IOException ioe) {
                GUIUtils.showExceptionDialog(
                        this,
                        "Problem saving file " + fileName, ioe);
            }
        }
    }
void moa.gui.RegressionTaskManagerPanel.setPreviewPanel (PreviewPanel previewPanel)
Definition at line 370 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTabPanel.RegressionTabPanel().
{
        this.previewPanel = previewPanel;
    }
void moa.gui.RegressionTaskManagerPanel.setTaskString (String cliString, boolean storePreference)
Definition at line 378 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.currentTask, moa.options.AbstractOptionHandler.getCLICreationString(), moa.gui.RegressionTaskManagerPanel.PREF_NAME, moa.gui.RegressionTaskManagerPanel.prefs, and moa.gui.RegressionTaskManagerPanel.taskDescField.
{
        try {
            this.currentTask = (RegressionMainTask) ClassOption.cliStringToObject(
                    cliString, RegressionMainTask.class, null);
            String taskText = this.currentTask.getCLICreationString(RegressionMainTask.class);
            this.taskDescField.setText(taskText);
            if (storePreference == true){
            //Save task text as a preference
            prefs.put(PREF_NAME, taskText);
            }
        } catch (Exception ex) {
            GUIUtils.showExceptionDialog(this, "Problem with task", ex);
        }
    }
void moa.gui.RegressionTaskManagerPanel.setTaskString (String cliString)
Definition at line 374 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.taskSelectionChanged().
{
        setTaskString(cliString, true);
    }
void moa.gui.RegressionTaskManagerPanel.taskSelectionChanged ()
Definition at line 401 of file RegressionTaskManagerPanel.java.
References moa.gui.RegressionTaskManagerPanel.getSelectedTasks(), moa.gui.RegressionTaskManagerPanel.previewPanel, moa.gui.RegressionTaskManagerPanel.setTaskString(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        if (selectedTasks.length == 1) {
            setTaskString(((OptionHandler) selectedTasks[0].getTask()).getCLICreationString(RegressionMainTask.class));
            if (this.previewPanel != null) {
                this.previewPanel.setTaskThreadToPreview(selectedTasks[0]);
            }
        } else {
            this.previewPanel.setTaskThreadToPreview(null);
        }
    }
Member Data Documentation
JButton moa.gui.RegressionTaskManagerPanel.cancelTaskButton = new JButton("Cancel") [protected]
Definition at line 206 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
JButton moa.gui.RegressionTaskManagerPanel.configureTaskButton = new JButton("Configure") [protected]
Definition at line 192 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
RegressionMainTask moa.gui.RegressionTaskManagerPanel.currentTask = new EvaluatePrequentialRegression() [protected]
Definition at line 188 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.setTaskString().
JButton moa.gui.RegressionTaskManagerPanel.deleteTaskButton = new JButton("Delete") [protected]
Definition at line 208 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
String moa.gui.RegressionTaskManagerPanel.exportFileExtension = "log" [static]
Definition at line 81 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.saveLogSelectedTasks().
final int moa.gui.RegressionTaskManagerPanel.MILLISECS_BETWEEN_REFRESH = 600 [static]
Definition at line 79 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
JButton moa.gui.RegressionTaskManagerPanel.pauseTaskButton = new JButton("Pause") [protected]
Definition at line 202 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
final String moa.gui.RegressionTaskManagerPanel.PREF_NAME = "currentTask" [private]
Definition at line 214 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.setTaskString().
Preferences moa.gui.RegressionTaskManagerPanel.prefs [private]
Definition at line 212 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.setTaskString().
PreviewPanel moa.gui.RegressionTaskManagerPanel.previewPanel [protected]
Definition at line 210 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.taskSelectionChanged().
JButton moa.gui.RegressionTaskManagerPanel.resumeTaskButton = new JButton("Resume") [protected]
Definition at line 204 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
JButton moa.gui.RegressionTaskManagerPanel.runTaskButton = new JButton("Run") [protected]
Definition at line 196 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel().
final long moa.gui.RegressionTaskManagerPanel.serialVersionUID = 1L [static, private]
Definition at line 77 of file RegressionTaskManagerPanel.java.
JTextField moa.gui.RegressionTaskManagerPanel.taskDescField = new JTextField() [protected]
Definition at line 194 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.copyClipBoardConfiguration(), moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.setTaskString().
List<TaskThread> moa.gui.RegressionTaskManagerPanel.taskList = new ArrayList<TaskThread>() [protected]
Definition at line 190 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.deleteSelectedTasks(), moa.gui.RegressionTaskManagerPanel.getSelectedTasks(), and moa.gui.RegressionTaskManagerPanel.runTask().
JTable moa.gui.RegressionTaskManagerPanel.taskTable [protected]
Definition at line 200 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.getSelectedTasks(), moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.runTask().
TaskTableModel moa.gui.RegressionTaskManagerPanel.taskTableModel [protected]
Definition at line 198 of file RegressionTaskManagerPanel.java.
Referenced by moa.gui.RegressionTaskManagerPanel.deleteSelectedTasks(), moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), and moa.gui.RegressionTaskManagerPanel.runTask().
The documentation for this class was generated from the following file:
main/java/moa/gui/RegressionTaskManagerPanel.java