MOA: moa.streams.ArffFileStream Class Reference
moa.streams.ArffFileStream Class Reference
Stream reader of ARFF files.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
ArffFileStream ()
ArffFileStream (String arffFileName, int classIndex)
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
InstancesHeader getHeader ()
Gets the header of this stream.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
Instance nextInstance ()
Gets the next instance from this stream.
boolean isRestartable ()
Gets whether this stream can restart.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
FileOption arffFileOption
IntOption classIndexOption
Protected Member Functions
boolean readNextInstanceFromFile ()
Protected Attributes
Instances instances
Reader fileReader
boolean hitEndOfFile
Instance lastInstanceRead
int numInstancesRead
InputStreamProgressMonitor fileProgressMonitor
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream reader of ARFF files.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file ArffFileStream.java.
Constructor & Destructor Documentation
moa.streams.ArffFileStream.ArffFileStream ()
Definition at line 77 of file ArffFileStream.java.
{
    }
moa.streams.ArffFileStream.ArffFileStream (String arffFileName, int classIndex)
Definition at line 80 of file ArffFileStream.java.
References moa.streams.ArffFileStream.arffFileOption, moa.streams.ArffFileStream.classIndexOption, moa.streams.ArffFileStream.restart(), moa.options.IntOption.setValue(), and moa.options.StringOption.setValue().
{
        this.arffFileOption.setValue(arffFileName);
        this.classIndexOption.setValue(classIndex);
        restart();
    }
Member Function Documentation
long moa.streams.ArffFileStream.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 98 of file ArffFileStream.java.
References moa.streams.ArffFileStream.fileProgressMonitor, moa.core.InputStreamProgressMonitor.getProgressFraction(), and moa.streams.ArffFileStream.numInstancesRead.
{
        double progressFraction = this.fileProgressMonitor.getProgressFraction();
        if ((progressFraction > 0.0) && (this.numInstancesRead > 0)) {
            return (long) ((this.numInstancesRead / progressFraction) - this.numInstancesRead);
        }
        return -1;
    }
void moa.streams.ArffFileStream.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 168 of file ArffFileStream.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.ArffFileStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Reimplemented in moa.streams.generators.multilabel.MultilabelArffFileStream.
Definition at line 93 of file ArffFileStream.java.
References moa.streams.ArffFileStream.instances.
{
        return new InstancesHeader(this.instances);
    }
String moa.streams.ArffFileStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.streams.generators.multilabel.MultilabelArffFileStream.
Definition at line 50 of file ArffFileStream.java.
{
        return "A stream read from an ARFF file.";
    }
boolean moa.streams.ArffFileStream.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 107 of file ArffFileStream.java.
References moa.streams.ArffFileStream.hitEndOfFile.
{
        return !this.hitEndOfFile;
    }
boolean moa.streams.ArffFileStream.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 119 of file ArffFileStream.java.
{
        return true;
    }
Instance moa.streams.ArffFileStream.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 112 of file ArffFileStream.java.
References moa.streams.ArffFileStream.hitEndOfFile, moa.streams.ArffFileStream.lastInstanceRead, and moa.streams.ArffFileStream.readNextInstanceFromFile().
{
        Instance prevInstance = this.lastInstanceRead;
        this.hitEndOfFile = !readNextInstanceFromFile();
        return prevInstance;
    }
void moa.streams.ArffFileStream.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 87 of file ArffFileStream.java.
References moa.streams.ArffFileStream.restart().
{
        restart();
    }
boolean moa.streams.ArffFileStream.readNextInstanceFromFile () [protected]
Definition at line 148 of file ArffFileStream.java.
References moa.streams.ArffFileStream.fileReader, moa.streams.ArffFileStream.instances, moa.streams.ArffFileStream.lastInstanceRead, and moa.streams.ArffFileStream.numInstancesRead.
Referenced by moa.streams.ArffFileStream.nextInstance(), and moa.streams.ArffFileStream.restart().
{
        try {
            if (this.instances.readInstance(this.fileReader)) {
                this.lastInstanceRead = this.instances.instance(0);
                this.instances.delete(); // keep instances clean
                this.numInstancesRead++;
                return true;
            }
            if (this.fileReader != null) {
                this.fileReader.close();
                this.fileReader = null;
            }
            return false;
        } catch (IOException ioe) {
            throw new RuntimeException(
                    "ArffFileStream failed to read instance from stream.", ioe);
        }
    }
void moa.streams.ArffFileStream.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 124 of file ArffFileStream.java.
References moa.streams.ArffFileStream.arffFileOption, moa.streams.ArffFileStream.classIndexOption, moa.streams.ArffFileStream.fileProgressMonitor, moa.streams.ArffFileStream.fileReader, moa.options.FileOption.getFile(), moa.options.IntOption.getValue(), moa.streams.ArffFileStream.hitEndOfFile, moa.streams.ArffFileStream.instances, moa.streams.ArffFileStream.lastInstanceRead, moa.streams.ArffFileStream.numInstancesRead, and moa.streams.ArffFileStream.readNextInstanceFromFile().
Referenced by moa.streams.ArffFileStream.ArffFileStream(), moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream(), and moa.streams.ArffFileStream.prepareForUseImpl().
{
        try {
            if (this.fileReader != null) {
                this.fileReader.close();
            }
            InputStream fileStream = new FileInputStream(this.arffFileOption.getFile());
            this.fileProgressMonitor = new InputStreamProgressMonitor(
                    fileStream);
            this.fileReader = new BufferedReader(new InputStreamReader(
                    this.fileProgressMonitor));
            this.instances = new Instances(this.fileReader, 1);
            if (this.classIndexOption.getValue() < 0) {
                this.instances.setClassIndex(this.instances.numAttributes() - 1);
            } else if (this.classIndexOption.getValue() > 0) {
                this.instances.setClassIndex(this.classIndexOption.getValue() - 1);
            }
            this.numInstancesRead = 0;
            this.lastInstanceRead = null;
            this.hitEndOfFile = !readNextInstanceFromFile();
        } catch (IOException ioe) {
            throw new RuntimeException("ArffFileStream restart failed.", ioe);
        }
    }
Member Data Documentation
FileOption moa.streams.ArffFileStream.arffFileOption
Initial value:
 new FileOption("arffFile", 'f',
            "ARFF file to load.", null, "arff", false)
Definition at line 56 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.ArffFileStream(), moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream(), and moa.streams.ArffFileStream.restart().
IntOption moa.streams.ArffFileStream.classIndexOption
Initial value:
 new IntOption(
            "classIndex",
            'c',
            "Class index of data. 0 for none or -1 for last attribute in file.",
            -1, -1, Integer.MAX_VALUE)
Definition at line 59 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.ArffFileStream(), and moa.streams.ArffFileStream.restart().
InputStreamProgressMonitor moa.streams.ArffFileStream.fileProgressMonitor [protected]
Definition at line 75 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.estimatedRemainingInstances(), and moa.streams.ArffFileStream.restart().
Reader moa.streams.ArffFileStream.fileReader [protected]
Definition at line 67 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.readNextInstanceFromFile(), and moa.streams.ArffFileStream.restart().
boolean moa.streams.ArffFileStream.hitEndOfFile [protected]
Definition at line 69 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.hasMoreInstances(), moa.streams.ArffFileStream.nextInstance(), and moa.streams.ArffFileStream.restart().
Instances moa.streams.ArffFileStream.instances [protected]
Definition at line 65 of file ArffFileStream.java.
Referenced by moa.streams.generators.multilabel.MultilabelArffFileStream.getHeader(), moa.streams.ArffFileStream.getHeader(), moa.streams.ArffFileStream.readNextInstanceFromFile(), and moa.streams.ArffFileStream.restart().
Instance moa.streams.ArffFileStream.lastInstanceRead [protected]
Definition at line 71 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.nextInstance(), moa.streams.ArffFileStream.readNextInstanceFromFile(), and moa.streams.ArffFileStream.restart().
int moa.streams.ArffFileStream.numInstancesRead [protected]
Definition at line 73 of file ArffFileStream.java.
Referenced by moa.streams.ArffFileStream.estimatedRemainingInstances(), moa.streams.ArffFileStream.readNextInstanceFromFile(), and moa.streams.ArffFileStream.restart().
final long moa.streams.ArffFileStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.streams.generators.multilabel.MultilabelArffFileStream.
Definition at line 54 of file ArffFileStream.java.
The documentation for this class was generated from the following file:
main/java/moa/streams/ArffFileStream.java