MOA: moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode Class Reference
moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode Class Reference
Public Member Functions
ActiveLearningNode (double[] initialClassObservations)
int calcByteSize ()
void learnFromInstance (Instance inst, HoeffdingOptionTree ht)
double getWeightSeen ()
double getWeightSeenAtLastSplitEvaluation ()
void setWeightSeenAtLastSplitEvaluation (double weight)
AttributeSplitSuggestion[] getBestSplitSuggestions (SplitCriterion criterion, HoeffdingOptionTree ht)
void disableAttribute (int attIndex)
Protected Attributes
double weightSeenAtLastSplitEvaluation
AutoExpandVector
< AttributeClassObserver > attributeObservers = new AutoExpandVector<AttributeClassObserver>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 529 of file HoeffdingOptionTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.ActiveLearningNode (double[] initialClassObservations)
Definition at line 537 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen(), and moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
{
            super(initialClassObservations);
            this.weightSeenAtLastSplitEvaluation = getWeightSeen();
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 543 of file HoeffdingOptionTree.java.
{
            return super.calcByteSize()
                    + (int) (SizeOf.fullSizeOf(this.attributeObservers));
        }
void moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.disableAttribute (int attIndex)
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB.
Definition at line 599 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit().
{
            this.attributeObservers.set(attIndex,
                    new NullAttributeClassObserver());
        }
AttributeSplitSuggestion [] moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions (SplitCriterion criterion, HoeffdingOptionTree ht)
Definition at line 575 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.options.FlagOption.isSet, moa.classifiers.trees.HoeffdingOptionTree.noPrePruneOption, and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit().
{
            List<AttributeSplitSuggestion> bestSuggestions = new LinkedList<AttributeSplitSuggestion>();
            double[] preSplitDist = this.observedClassDistribution.getArrayCopy();
            if (!ht.noPrePruneOption.isSet()) {
                // add null split as an option
                bestSuggestions.add(new AttributeSplitSuggestion(null,
                        new double[0][], criterion.getMeritOfSplit(
                                preSplitDist,
                                new double[][]{preSplitDist})));
            }
            for (int i = 0; i < this.attributeObservers.size(); i++) {
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs != null) {
                    AttributeSplitSuggestion bestSuggestion = obs.getBestEvaluatedSplitSuggestion(criterion,
                            preSplitDist, i, ht.binarySplitsOption.isSet());
                    if (bestSuggestion != null) {
                        bestSuggestions.add(bestSuggestion);
                    }
                }
            }
            return bestSuggestions.toArray(new AttributeSplitSuggestion[bestSuggestions.size()]);
        }
double moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen ()
Definition at line 563 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), and moa.classifiers.trees.HoeffdingOptionTree.trainOnInstanceImpl().
{
            return this.observedClassDistribution.sumOfValues();
        }
double moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation ()
Definition at line 567 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.trainOnInstanceImpl().
{
            return this.weightSeenAtLastSplitEvaluation;
        }
void moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance (Instance inst, HoeffdingOptionTree ht) [virtual]
Implements moa.classifiers.trees.HoeffdingOptionTree.LearningNode.
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode, and moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNBAdaptive.
Definition at line 549 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.attributeObservers, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.HoeffdingOptionTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingOptionTree.newNumericClassObserver(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
{
            this.observedClassDistribution.addToValue((int) inst.classValue(),
                    inst.weight());
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? ht.newNominalClassObserver() : ht.newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
                obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
            }
        }
void moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation (double weight)
Definition at line 571 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.trainOnInstanceImpl().
{
            this.weightSeenAtLastSplitEvaluation = weight;
        }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.attributeObservers = new AutoExpandVector<AttributeClassObserver>() [protected]
Definition at line 535 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode.getClassVotes(), and moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance().
final long moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.LearningNode.
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode, moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNBAdaptive.
Definition at line 531 of file HoeffdingOptionTree.java.
double moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation [protected]
Definition at line 533 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation(), and moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingOptionTree.java