MOA: moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver Class Reference
moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver Class Reference
Class for observing the class data distribution for a numeric attribute as in VFML.
Classes
class Bin
Public Member Functions
void observeAttributeTarget (double attVal, double target)
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption numBinsOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
List< Bin > binList = new ArrayList<Bin>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for observing the class data distribution for a numeric attribute as in VFML.
Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 44 of file VFMLNumericAttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 191 of file VFMLNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.binList, moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.classifiers.core.AttributeSplitSuggestion.merit, and moa.core.DoubleVector.subtractValues().
{
        AttributeSplitSuggestion bestSuggestion = null;
        DoubleVector rightDist = new DoubleVector();
        for (Bin bin : this.binList) {
            rightDist.addValues(bin.classWeights);
        }
        DoubleVector leftDist = new DoubleVector();
        for (Bin bin : this.binList) {
            leftDist.addValues(bin.classWeights);
            rightDist.subtractValues(bin.classWeights);
            double[][] postSplitDists = new double[][]{
                leftDist.getArrayCopy(), rightDist.getArrayCopy()};
            double merit = criterion.getMeritOfSplit(preSplitDist,
                    postSplitDists);
            if ((bestSuggestion == null) || (merit > bestSuggestion.merit)) {
                bestSuggestion = new AttributeSplitSuggestion(
                        new NumericAttributeBinaryTest(attIndex,
                        bin.upperBound, false), postSplitDists, merit);
            }
        }
        return bestSuggestion;
    }
void moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 217 of file VFMLNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 74 of file VFMLNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.core.DoubleVector.addValues(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.binList, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.Bin.boundaryClass, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.Bin.boundaryWeight, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.Bin.classWeights, moa.options.IntOption.getValue(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.Bin.lowerBound, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.numBinsOption, moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.subtractValues(), and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.Bin.upperBound.
{
        if (Utils.isMissingValue(attVal)) {
        } else {
            if (this.binList.size() < 1) {
                // create the first bin
                Bin newBin = new Bin();
                newBin.classWeights.addToValue(classVal, weight);
                newBin.boundaryClass = classVal;
                newBin.boundaryWeight = weight;
                newBin.upperBound = attVal;
                newBin.lowerBound = attVal;
                this.binList.add(newBin);
            } else {
                // find bin containing new example with binary search
                int index = -1;
                boolean found = false;
                int min = 0;
                int max = this.binList.size() - 1;
                index = 0;
                while ((min <= max) && !found) {
                    int i = (min + max) / 2;
                    Bin bin = this.binList.get(i);
                    if (((attVal >= bin.lowerBound) && (attVal < bin.upperBound))
                            || ((i == this.binList.size() - 1)
                            && (attVal >= bin.lowerBound) && (attVal <= bin.upperBound))) {
                        found = true;
                        index = i;
                    } else if (attVal < bin.lowerBound) {
                        max = i - 1;
                    } else {
                        min = i + 1;
                    }
                }
                boolean first = false;
                boolean last = false;
                if (!found) {
                    // determine if it is before or after the existing range
                    Bin bin = this.binList.get(0);
                    if (bin.lowerBound > attVal) {
                        // go before the first bin
                        index = 0;
                        first = true;
                    } else {
                        // if we haven't found it yet value must be > last bins
                        // upperBound
                        index = this.binList.size() - 1;
                        last = true;
                    }
                }
                Bin bin = this.binList.get(index); // VLIndex(ct->bins, index);
                if ((bin.lowerBound == attVal)
                        || (this.binList.size() >= this.numBinsOption.getValue())) {// Option.getValue())
                    // {//1000)
                    // {
                    // if this is the exact same boundary and class as the bin
                    // boundary or we aren't adding new bins any more then
                    // increment
                    // boundary counts
                    bin.classWeights.addToValue(classVal, weight);
                    if ((bin.boundaryClass == classVal)
                            && (bin.lowerBound == attVal)) {
                        // if it is also the same class then special case it
                        bin.boundaryWeight += weight;
                    }
                } else {
                    // create a new bin
                    Bin newBin = new Bin();
                    newBin.classWeights.addToValue(classVal, weight);
                    newBin.boundaryWeight = weight;
                    newBin.boundaryClass = classVal;
                    newBin.upperBound = bin.upperBound;
                    newBin.lowerBound = attVal;
                    double percent = 0.0;
                    // estimate initial counts with a linear interpolation
                    if (!((bin.upperBound - bin.lowerBound == 0) || last || first)) {
                        percent = 1.0 - ((attVal - bin.lowerBound) / (bin.upperBound - bin.lowerBound));
                    }
                    // take out the boundry points, they stay with the old bin
                    bin.classWeights.addToValue(bin.boundaryClass,
                            -bin.boundaryWeight);
                    DoubleVector weightToShift = new DoubleVector(
                            bin.classWeights);
                    weightToShift.scaleValues(percent);
                    newBin.classWeights.addValues(weightToShift);
                    bin.classWeights.subtractValues(weightToShift);
                    // put the boundry examples back in
                    bin.classWeights.addToValue(bin.boundaryClass,
                            bin.boundaryWeight);
                    // insert the new bin in the right place
                    if (last) {
                        bin.upperBound = attVal;
                        newBin.upperBound = attVal;
                        this.binList.add(newBin);
                    } else if (first) {
                        newBin.upperBound = bin.lowerBound;
                        this.binList.add(0, newBin);
                    } else {
                        newBin.upperBound = bin.upperBound;
                        bin.upperBound = attVal;
                        this.binList.add(index + 1, newBin);
                    }
                }
            }
        }
    }
void moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 50 of file VFMLNumericAttributeClassObserver.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
void moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 222 of file VFMLNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 184 of file VFMLNumericAttributeClassObserver.java.
{
        // TODO: NaiveBayes broken until implemented
        return 0.0;
    }
Member Data Documentation
List<Bin> moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.binList = new ArrayList<Bin>() [protected]
Definition at line 67 of file VFMLNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass().
IntOption moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.numBinsOption
Initial value:
 new IntOption("numBins", 'n',
        "The number of bins.", 10, 1, Integer.MAX_VALUE)
Definition at line 69 of file VFMLNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass().
final long moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 47 of file VFMLNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/VFMLNumericAttributeClassObserver.java