MOA: moa.classifiers.functions.SPegasos Class Reference
moa.classifiers.functions.SPegasos Class Reference
Implements the stochastic variant of the Pegasos (Primal Estimated sub-GrAdient SOlver for SVM) method of Shalev-Shwartz et al.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void setLambda (double lambda)
Set the value of lambda to use.
double getLambda ()
Get the current value of lambda.
void setLossFunction (int function)
Set the loss function to use.
int getLossFunction ()
Get the current loss function.
void reset ()
Reset the classifier.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance instance)
Trains the classifier with the given instance.
double[] getVotesForInstance (Instance inst)
Calculates the class membership probabilities for the given test instance.
void getModelDescription (StringBuilder result, int indent)
Returns a string representation of the model.
String toString ()
Prints out the classifier.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
FloatOption lambdaRegularizationOption
MultiChoiceOption lossFunctionOption
Protected Member Functions
double dloss (double z)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Static Protected Member Functions
static double dotProd (Instance inst1, double[] weights, int classIndex)
Protected Attributes
double m_lambda = 0.0001
The regularization parameter.
int m_loss = HINGE
The current loss function to minimize.
double[] m_weights
Stores the weights (+ bias in the last element).
double m_t
Holds the current iteration number.
Static Protected Attributes
static final int HINGE = 0
static final int LOGLOSS = 1
Static Private Attributes
static final long serialVersionUID = -3732968666673530290L
For serialization.
Detailed Description
Implements the stochastic variant of the Pegasos (Primal Estimated sub-GrAdient SOlver for SVM) method of Shalev-Shwartz et al.
(2007). For more information, see
S. Shalev-Shwartz, Y. Singer, N. Srebro: Pegasos: Primal Estimated sub-GrAdient SOlver for SVM. In: 24th International Conference on MachineLearning, 807-814, 2007.
* BibTeX:
 &#64;inproceedings{Shalev-Shwartz2007,
    author = {S. Shalev-Shwartz and Y. Singer and N. Srebro},
    booktitle = {24th International Conference on MachineLearning},
    pages = {807-814},
    title = {Pegasos: Primal Estimated sub-GrAdient SOlver for SVM},
    year = {2007}
 }
Definition at line 59 of file SPegasos.java.
Member Function Documentation
double moa.classifiers.functions.SPegasos.dloss (double z) [protected]
Definition at line 173 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.HINGE, and moa.classifiers.functions.SPegasos.m_loss.
Referenced by moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
{
        if (m_loss == HINGE) {
            return (z < 1) ? 1 : 0;
        }
        // log loss
        if (z < 0) {
            return 1.0 / (Math.exp(z) + 1.0);
        } else {
            double t = Math.exp(-z);
            return t / (t + 1);
        }
    }
static double moa.classifiers.functions.SPegasos.dotProd (Instance inst1, double[] weights, int classIndex) [static, protected]
Definition at line 149 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.getVotesForInstance(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
{
        double result = 0;
        int n1 = inst1.numValues();
        int n2 = weights.length - 1;
        for (int p1 = 0, p2 = 0; p1 < n1 && p2 < n2;) {
            int ind1 = inst1.index(p1);
            int ind2 = p2;
            if (ind1 == ind2) {
                if (ind1 != classIndex && !inst1.isMissingSparse(p1)) {
                    result += inst1.valueSparse(p1) * weights[p2];
                }
                p1++;
                p2++;
            } else if (ind1 > ind2) {
                p2++;
            } else {
                p1++;
            }
        }
        return (result);
    }
double moa.classifiers.functions.SPegasos.getLambda ()
Get the current value of lambda.
Returns:
the current value of lambda
Definition at line 119 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.m_lambda.
{
        return m_lambda;
    }
int moa.classifiers.functions.SPegasos.getLossFunction ()
Get the current loss function.
Returns:
the current loss function.
Definition at line 137 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.m_loss.
{
        return m_loss;
    }
void moa.classifiers.functions.SPegasos.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 295 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.toString().
{
        StringUtils.appendIndented(result, indent, toString());
        StringUtils.appendNewline(result);
    }
Measurement [] moa.classifiers.functions.SPegasos.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 345 of file SPegasos.java.
{
        return null;
    }
String moa.classifiers.functions.SPegasos.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 67 of file SPegasos.java.
{
        return "Stochastic variant of the Pegasos (Primal Estimated sub-GrAdient SOlver for SVM) method of Shalev-Shwartz et al. (2007).";
    }
double [] moa.classifiers.functions.SPegasos.getVotesForInstance (Instance inst)
Calculates the class membership probabilities for the given test instance.
Parameters:
instance the instance to be classified
Returns:
predicted class probability distribution
Implements moa.classifiers.Classifier.
Definition at line 263 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.dotProd(), moa.classifiers.functions.SPegasos.LOGLOSS, moa.classifiers.functions.SPegasos.m_loss, and moa.classifiers.functions.SPegasos.m_weights.
{
        if (m_weights == null) {
            return new double[inst.numAttributes() + 1];
        }
        double[] result = new double[2];
        double wx = dotProd(inst, m_weights, inst.classIndex());// * m_wScale;
        double z = (wx + m_weights[m_weights.length - 1]);
        //System.out.print("" + z + ": ");
        // System.out.println(1.0 / (1.0 + Math.exp(-z)));
        if (z <= 0) {
            //  z = 0;
            if (m_loss == LOGLOSS) {
                result[0] = 1.0 / (1.0 + Math.exp(z));
                result[1] = 1.0 - result[0];
            } else {
                result[0] = 1;
            }
        } else {
            if (m_loss == LOGLOSS) {
                result[1] = 1.0 / (1.0 + Math.exp(-z));
                result[0] = 1.0 - result[1];
            } else {
                result[1] = 1;
            }
        }
        return result;
    }
boolean moa.classifiers.functions.SPegasos.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 350 of file SPegasos.java.
{
        return false;
    }
void moa.classifiers.functions.SPegasos.reset ()
Reset the classifier.
Definition at line 144 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.m_t, and moa.classifiers.functions.SPegasos.m_weights.
Referenced by moa.classifiers.functions.SPegasos.resetLearningImpl().
{
        m_t = 2;
        m_weights = null;
    }
void moa.classifiers.functions.SPegasos.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 188 of file SPegasos.java.
References moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.classifiers.functions.SPegasos.lambdaRegularizationOption, moa.classifiers.functions.SPegasos.lossFunctionOption, moa.classifiers.functions.SPegasos.reset(), moa.classifiers.functions.SPegasos.setLambda(), and moa.classifiers.functions.SPegasos.setLossFunction().
{
        reset();
        setLambda(this.lambdaRegularizationOption.getValue());
        setLossFunction(this.lossFunctionOption.getChosenIndex());
    }
void moa.classifiers.functions.SPegasos.setLambda (double lambda)
Set the value of lambda to use.
Parameters:
lambda the value of lambda to use
Definition at line 110 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.m_lambda.
Referenced by moa.classifiers.functions.SPegasos.resetLearningImpl().
{
        m_lambda = lambda;
    }
void moa.classifiers.functions.SPegasos.setLossFunction (int function)
Set the loss function to use.
Parameters:
function the loss function to use.
Definition at line 128 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.m_loss.
Referenced by moa.classifiers.functions.SPegasos.resetLearningImpl().
{
        m_loss = function;
    }
String moa.classifiers.functions.SPegasos.toString ()
Prints out the classifier.
Returns:
a description of the classifier as a string
Reimplemented from moa.AbstractMOAObject.
Definition at line 306 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.HINGE, moa.classifiers.functions.SPegasos.m_loss, and moa.classifiers.functions.SPegasos.m_weights.
Referenced by moa.classifiers.functions.SPegasos.getModelDescription().
{
        if (m_weights == null) {
            return "SPegasos: No model built yet.\n";
        }
        StringBuffer buff = new StringBuffer();
        buff.append("Loss function: ");
        if (m_loss == HINGE) {
            buff.append("Hinge loss (SVM)\n\n");
        } else {
            buff.append("Log loss (logistic regression)\n\n");
        }
        int printed = 0;
        for (int i = 0; i < m_weights.length - 1; i++) {
            //   if (i != m_data.classIndex()) {
            if (printed > 0) {
                buff.append(" + ");
            } else {
                buff.append("   ");
            }
            buff.append(Utils.doubleToString(m_weights[i], 12, 4) + " "
                    //+ m_data.attribute(i).name()
                    + "\n");
            printed++;
        }
        //}
        if (m_weights[m_weights.length - 1] > 0) {
            buff.append(" + " + Utils.doubleToString(m_weights[m_weights.length - 1], 12, 4));
        } else {
            buff.append(" - " + Utils.doubleToString(-m_weights[m_weights.length - 1], 12, 4));
        }
        return buff.toString();
    }
void moa.classifiers.functions.SPegasos.trainOnInstanceImpl (Instance instance) [virtual]
Trains the classifier with the given instance.
Parameters:
instance the new training instance to include in the model
Implements moa.classifiers.AbstractClassifier.
Definition at line 200 of file SPegasos.java.
References moa.classifiers.functions.SPegasos.dloss(), moa.classifiers.functions.SPegasos.dotProd(), moa.classifiers.functions.SPegasos.LOGLOSS, moa.classifiers.functions.SPegasos.m_lambda, moa.classifiers.functions.SPegasos.m_loss, moa.classifiers.functions.SPegasos.m_t, and moa.classifiers.functions.SPegasos.m_weights.
{
        if (m_weights == null) {
            m_weights = new double[instance.numAttributes() + 1];
        }
        if (!instance.classIsMissing()) {
            double learningRate = 1.0 / (m_lambda * m_t);
            //double scale = 1.0 - learningRate * m_lambda;
            double scale = 1.0 - 1.0 / m_t;
            double y = (instance.classValue() == 0) ? -1 : 1;
            double wx = dotProd(instance, m_weights, instance.classIndex());
            double z = y * (wx + m_weights[m_weights.length - 1]);
            for (int j = 0; j < m_weights.length - 1; j++) {
                if (j != instance.classIndex()) {
                    m_weights[j] *= scale;
                }
            }
            if (m_loss == LOGLOSS || (z < 1)) {
                double loss = dloss(z);
                int n1 = instance.numValues();
                for (int p1 = 0; p1 < n1; p1++) {
                    int indS = instance.index(p1);
                    if (indS != instance.classIndex() && !instance.isMissingSparse(p1)) {
                        double m = learningRate * loss * (instance.valueSparse(p1) * y);
                        m_weights[indS] += m;
                    }
                }
                // update the bias
                m_weights[m_weights.length - 1] += learningRate * loss * y;
            }
            double norm = 0;
            for (int k = 0; k < m_weights.length - 1; k++) {
                if (k != instance.classIndex()) {
                    norm += (m_weights[k] * m_weights[k]);
                }
            }
            double scale2 = Math.min(1.0, (1.0 / (m_lambda * norm)));
            if (scale2 < 1.0) {
                scale2 = Math.sqrt(scale2);
                for (int j = 0; j < m_weights.length - 1; j++) {
                    if (j != instance.classIndex()) {
                        m_weights[j] *= scale2;
                    }
                }
            }
            m_t++;
        }
    }
Member Data Documentation
final int moa.classifiers.functions.SPegasos.HINGE = 0 [static, protected]
Definition at line 80 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.dloss(), and moa.classifiers.functions.SPegasos.toString().
FloatOption moa.classifiers.functions.SPegasos.lambdaRegularizationOption
Initial value:
 new FloatOption("lambdaRegularization",
            'l', "Lambda regularization parameter .",
            0.0001, 0.00, Integer.MAX_VALUE)
Definition at line 76 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.resetLearningImpl().
final int moa.classifiers.functions.SPegasos.LOGLOSS = 1 [static, protected]
Definition at line 82 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.getVotesForInstance(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
MultiChoiceOption moa.classifiers.functions.SPegasos.lossFunctionOption
Initial value:
 new MultiChoiceOption(
            "lossFunction", 'o', "The loss function to use.", new String[]{
                "HINGE", "LOGLOSS"}, new String[]{
                "Hinge loss (SVM)",
                "Log loss (logistic regression)"}, 0)
Definition at line 89 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.resetLearningImpl().
double moa.classifiers.functions.SPegasos.m_lambda = 0.0001 [protected]
The regularization parameter.
Definition at line 74 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.getLambda(), moa.classifiers.functions.SPegasos.setLambda(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
int moa.classifiers.functions.SPegasos.m_loss = HINGE [protected]
The current loss function to minimize.
Definition at line 87 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.dloss(), moa.classifiers.functions.SPegasos.getLossFunction(), moa.classifiers.functions.SPegasos.getVotesForInstance(), moa.classifiers.functions.SPegasos.setLossFunction(), moa.classifiers.functions.SPegasos.toString(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
double moa.classifiers.functions.SPegasos.m_t [protected]
Holds the current iteration number.
Definition at line 103 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.reset(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
double [] moa.classifiers.functions.SPegasos.m_weights [protected]
Stores the weights (+ bias in the last element).
Definition at line 98 of file SPegasos.java.
Referenced by moa.classifiers.functions.SPegasos.getVotesForInstance(), moa.classifiers.functions.SPegasos.reset(), moa.classifiers.functions.SPegasos.toString(), and moa.classifiers.functions.SPegasos.trainOnInstanceImpl().
final long moa.classifiers.functions.SPegasos.serialVersionUID = -3732968666673530290L [static, private]
For serialization.
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 64 of file SPegasos.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/functions/SPegasos.java