MOA: moa.tasks.EvaluatePeriodicHeldOutTest Class Reference
moa.tasks.EvaluatePeriodicHeldOutTest Class Reference
Task for evaluating a classifier on a stream by periodically testing on a heldout set.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
ClassOption evaluatorOption
IntOption testSizeOption
IntOption trainSizeOption
IntOption trainTimeOption
IntOption sampleFrequencyOption
FileOption dumpFileOption
FlagOption cacheTestOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a classifier on a stream by periodically testing on a heldout set.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 52 of file EvaluatePeriodicHeldOutTest.java.
Member Function Documentation
Object moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 96 of file EvaluatePeriodicHeldOutTest.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.tasks.EvaluatePeriodicHeldOutTest.cacheTestOption, moa.AbstractMOAObject.copy(), moa.tasks.EvaluatePeriodicHeldOutTest.dumpFileOption, moa.evaluation.LearningCurve.entryToString(), moa.tasks.EvaluatePeriodicHeldOutTest.evaluatorOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.classifiers.Classifier.getModelMeasurements(), moa.evaluation.ClassificationPerformanceEvaluator.getPerformanceMeasurements(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.options.FlagOption.isSet, moa.tasks.EvaluatePeriodicHeldOutTest.learnerOption, moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.evaluation.ClassificationPerformanceEvaluator.reset(), moa.streams.InstanceStream.restart(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluatePeriodicHeldOutTest.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityDescription(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.EvaluatePeriodicHeldOutTest.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluatePeriodicHeldOutTest.testSizeOption, moa.classifiers.Classifier.trainOnInstance(), moa.tasks.EvaluatePeriodicHeldOutTest.trainSizeOption, and moa.tasks.EvaluatePeriodicHeldOutTest.trainTimeOption.
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        learner.setModelContext(stream.getHeader());
        long instancesProcessed = 0;
        LearningCurve learningCurve = new LearningCurve("evaluation instances");
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        boolean firstDump = true;
        InstanceStream testStream = null;
        int testSize = this.testSizeOption.getValue();
        if (this.cacheTestOption.isSet()) {
            monitor.setCurrentActivity("Caching test examples...", -1.0);
            Instances testInstances = new Instances(stream.getHeader(),
                    this.testSizeOption.getValue());
            while (testInstances.numInstances() < testSize) {
                testInstances.add(stream.nextInstance());
                if (testInstances.numInstances()
                        % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    monitor.setCurrentActivityFractionComplete((double) testInstances.numInstances()
                            / (double) (this.testSizeOption.getValue()));
                }
            }
            testStream = new CachedInstancesStream(testInstances);
        } else {
            //testStream = (InstanceStream) stream.copy();
            testStream = stream;
            /*monitor.setCurrentActivity("Skipping test examples...", -1.0);
            for (int i = 0; i < testSize; i++) {
            stream.nextInstance();
            }*/
        }
        instancesProcessed = 0;
        TimingUtils.enablePreciseTiming();
        double totalTrainTime = 0.0;
        while ((this.trainSizeOption.getValue() < 1
                || instancesProcessed < this.trainSizeOption.getValue())
                && stream.hasMoreInstances() == true) {
            monitor.setCurrentActivityDescription("Training...");
            long instancesTarget = instancesProcessed
                    + this.sampleFrequencyOption.getValue();
            long trainStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
            while (instancesProcessed < instancesTarget && stream.hasMoreInstances() == true) {
                learner.trainOnInstance(stream.nextInstance());
                instancesProcessed++;
                if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    monitor.setCurrentActivityFractionComplete((double) (instancesProcessed)
                            / (double) (this.trainSizeOption.getValue()));
                }
            }
            double lastTrainTime = TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                    - trainStartTime);
            totalTrainTime += lastTrainTime;
            if (totalTrainTime > this.trainTimeOption.getValue()) {
                break;
            }
        if (this.cacheTestOption.isSet()) {
                testStream.restart();
            }
            evaluator.reset();
            long testInstancesProcessed = 0;
            monitor.setCurrentActivityDescription("Testing (after "
                    + StringUtils.doubleToString(
                    ((double) (instancesProcessed)
                    / (double) (this.trainSizeOption.getValue()) * 100.0), 2)
                    + "% training)...");
            long testStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
            int instCount = 0 ;
            for (instCount = 0; instCount < testSize; instCount++) {
                if (stream.hasMoreInstances() == false) {
                    break;
                }
                Instance testInst = (Instance) testStream.nextInstance().copy();
                double trueClass = testInst.classValue();
                testInst.setClassMissing();
                double[] prediction = learner.getVotesForInstance(testInst);
                testInst.setClassValue(trueClass);
                evaluator.addResult(testInst, prediction);
                testInstancesProcessed++;
                if (testInstancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    monitor.setCurrentActivityFractionComplete((double) testInstancesProcessed
                            / (double) (testSize));
                }
            }
            if ( instCount != testSize) {
                break;
            }
            double testTime = TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                    - testStartTime);
            List<Measurement> measurements = new ArrayList<Measurement>();
            measurements.add(new Measurement("evaluation instances",
                    instancesProcessed));
            measurements.add(new Measurement("total train time", totalTrainTime));
            measurements.add(new Measurement("total train speed",
                    instancesProcessed / totalTrainTime));
            measurements.add(new Measurement("last train time", lastTrainTime));
            measurements.add(new Measurement("last train speed",
                    this.sampleFrequencyOption.getValue() / lastTrainTime));
            measurements.add(new Measurement("test time", testTime));
            measurements.add(new Measurement("test speed", this.testSizeOption.getValue()
                    / testTime));
            Measurement[] performanceMeasurements = evaluator.getPerformanceMeasurements();
            for (Measurement measurement : performanceMeasurements) {
                measurements.add(measurement);
            }
            Measurement[] modelMeasurements = learner.getModelMeasurements();
            for (Measurement measurement : modelMeasurements) {
                measurements.add(measurement);
            }
            learningCurve.insertEntry(new LearningEvaluation(measurements.toArray(new Measurement[measurements.size()])));
            if (immediateResultStream != null) {
                if (firstDump) {
                    immediateResultStream.println(learningCurve.headerToString());
                    firstDump = false;
                }
                immediateResultStream.println(learningCurve.entryToString(learningCurve.numEntries() - 1));
                immediateResultStream.flush();
            }
            if (monitor.resultPreviewRequested()) {
                monitor.setLatestResultPreview(learningCurve.copy());
            }
            // if (learner instanceof HoeffdingTree
            // || learner instanceof HoeffdingOptionTree) {
            // int numActiveNodes = (int) Measurement.getMeasurementNamed(
            // "active learning leaves",
            // modelMeasurements).getValue();
            // // exit if tree frozen
            // if (numActiveNodes < 1) {
            // break;
            // }
            // int numNodes = (int) Measurement.getMeasurementNamed(
            // "tree size (nodes)", modelMeasurements)
            // .getValue();
            // if (numNodes == lastNumNodes) {
            // noGrowthCount++;
            // } else {
            // noGrowthCount = 0;
            // }
            // lastNumNodes = numNodes;
            // } else if (learner instanceof OzaBoost || learner instanceof
            // OzaBag) {
            // double numActiveNodes = Measurement.getMeasurementNamed(
            // "[avg] active learning leaves",
            // modelMeasurements).getValue();
            // // exit if all trees frozen
            // if (numActiveNodes == 0.0) {
            // break;
            // }
            // int numNodes = (int) (Measurement.getMeasurementNamed(
            // "[avg] tree size (nodes)",
            // learner.getModelMeasurements()).getValue() * Measurement
            // .getMeasurementNamed("ensemble size",
            // modelMeasurements).getValue());
            // if (numNodes == lastNumNodes) {
            // noGrowthCount++;
            // } else {
            // noGrowthCount = 0;
            // }
            // lastNumNodes = numNodes;
            // }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
        return learningCurve;
    }
String moa.tasks.EvaluatePeriodicHeldOutTest.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 55 of file EvaluatePeriodicHeldOutTest.java.
{
        return "Evaluates a classifier on a stream by periodically testing on a heldout set.";
    }
Class<?> moa.tasks.EvaluatePeriodicHeldOutTest.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 288 of file EvaluatePeriodicHeldOutTest.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FlagOption moa.tasks.EvaluatePeriodicHeldOutTest.cacheTestOption
Initial value:
 new FlagOption("cacheTest", 'c',
            "Cache test instances in memory.")
Definition at line 92 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
FileOption moa.tasks.EvaluatePeriodicHeldOutTest.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv results to.", null, "csv", true)
Definition at line 89 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
ClassOption moa.tasks.EvaluatePeriodicHeldOutTest.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "BasicClassificationPerformanceEvaluator")
Definition at line 68 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
ClassOption moa.tasks.EvaluatePeriodicHeldOutTest.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 61 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
IntOption moa.tasks.EvaluatePeriodicHeldOutTest.sampleFrequencyOption
Initial value:
 new IntOption(
            "sampleFrequency",
            'f',
            "Number of training examples between samples of learning performance.",
            100000, 0, Integer.MAX_VALUE)
Definition at line 83 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
final long moa.tasks.EvaluatePeriodicHeldOutTest.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 59 of file EvaluatePeriodicHeldOutTest.java.
ClassOption moa.tasks.EvaluatePeriodicHeldOutTest.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 64 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
IntOption moa.tasks.EvaluatePeriodicHeldOutTest.testSizeOption
Initial value:
 new IntOption("testSize", 'n',
            "Number of testing examples.", 1000000, 0, Integer.MAX_VALUE)
Definition at line 73 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
IntOption moa.tasks.EvaluatePeriodicHeldOutTest.trainSizeOption
Initial value:
 new IntOption("trainSize", 'i',
            "Number of training examples, <1 = unlimited.", 0, 0,
            Integer.MAX_VALUE)
Definition at line 76 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
IntOption moa.tasks.EvaluatePeriodicHeldOutTest.trainTimeOption
Initial value:
 new IntOption("trainTime", 't',
            "Number of training seconds.", 10 * 60 * 60, 0, Integer.MAX_VALUE)
Definition at line 80 of file EvaluatePeriodicHeldOutTest.java.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluatePeriodicHeldOutTest.java