MOA: moa.options.AbstractClassOption Class Reference
moa.options.AbstractClassOption Class Reference
Abstract class option.
Public Member Functions
AbstractClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
Creates a new instance of an abstract option given its class name, command line interface text, its purpose, its class type and its default command line interface text.
AbstractClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
Creates a new instance of an abstract option given its class name, command line interface text, its purpose, its class type, default command line interface text, and its null text.
void setCurrentObject (Object obj)
Sets current object.
Object getPreMaterializedObject ()
Returns the current object.
Class<?> getRequiredType ()
Gets the class type of this option.
String getNullString ()
Gets the null string of this option.
Object materializeObject (TaskMonitor monitor, ObjectRepository repository)
Gets a materialized object of this option.
String getDefaultCLIString ()
Gets the Command Line Interface text.
abstract String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
abstract void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
abstract JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static String classToCLIString (Class<?> aClass, Class<?> requiredType)
Gets the command line interface text of the class.
static String stripPackagePrefix (String className, Class<?> expectedType)
Gets the class name without its package name prefix.
Static Public Attributes
static final String FILE_PREFIX_STRING = "file:"
The prefix text to use to indicate file.
static final String INMEM_PREFIX_STRING = "inmem:"
The prefix text to use to indicate inmem.
Protected Attributes
Object currentValue
The current object.
Class<?> requiredType
The class type.
String defaultCLIString
The default command line interface text.
String nullString
The null text.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Abstract class option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
$Revision$
Definition at line 37 of file AbstractClassOption.java.
Constructor & Destructor Documentation
moa.options.AbstractClassOption.AbstractClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
Creates a new instance of an abstract option given its class name, command line interface text, its purpose, its class type and its default command line interface text.
Parameters:
name the name of this option
cliChar the command line interface text
purpose the text describing the purpose of this option
requiredType the class type
defaultCLIString the default command line interface text
Definition at line 70 of file AbstractClassOption.java.
{
        this(name, cliChar, purpose, requiredType, defaultCLIString, null);
    }
moa.options.AbstractClassOption.AbstractClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
Creates a new instance of an abstract option given its class name, command line interface text, its purpose, its class type, default command line interface text, and its null text.
Parameters:
name the name of this option
cliChar the command line interface text
purpose the text describing the purpose of this option
requiredType the class type
defaultCLIString the default command line interface text
nullString the null text
Definition at line 87 of file AbstractClassOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        this.requiredType = requiredType;
        this.defaultCLIString = defaultCLIString;
        this.nullString = nullString;
        resetToDefault();
    }
Member Function Documentation
static String moa.options.AbstractClassOption.classToCLIString (Class<?> aClass, Class<?> requiredType) [static]
Gets the command line interface text of the class.
Parameters:
aClass the class
requiredType the class type
Returns:
the command line interface text of the class
Definition at line 198 of file AbstractClassOption.java.
Referenced by moa.options.WEKAClassOption.objectToCLIString(), moa.options.ClassOptionWithNames.objectToCLIString(), and moa.options.ClassOption.objectToCLIString().
{
        String className = aClass.getName();
        String packageName = requiredType.getPackage().getName();
        if (className.startsWith(packageName)) {
            // cut off package name
            className = className.substring(packageName.length() + 1, className.length());
        } else if (Task.class.isAssignableFrom(aClass)) {
            packageName = Task.class.getPackage().getName();
            if (className.startsWith(packageName)) {
                // cut off task package name
                className = className.substring(packageName.length() + 1,
                        className.length());
            }
        }
        return className;
    }
String moa.options.AbstractClassOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 187 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.defaultCLIString.
{
        return this.defaultCLIString;
    }
abstract JComponent moa.options.AbstractClassOption.getEditComponent () [pure virtual]
Gets the GUI component to edit.
Returns:
the component to edit
Reimplemented from moa.options.AbstractOption.
Implemented in moa.options.ClassOption, moa.options.ClassOptionWithNames, and moa.options.WEKAClassOption.
String moa.options.AbstractClassOption.getNullString ()
Gets the null string of this option.
Returns:
the null string of this option
Definition at line 136 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.nullString.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.editObject(), and moa.gui.ClassOptionEditComponent.editObject().
{
        return this.nullString;
    }
Object moa.options.AbstractClassOption.getPreMaterializedObject ()
Returns the current object.
Returns:
the current object
Definition at line 118 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.currentValue.
Referenced by moa.classifiers.rules.AMRulesRegressor.newErrorWeightedVote(), and moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver().
{
        return this.currentValue;
    }
Class<?> moa.options.AbstractClassOption.getRequiredType ()
Gets the class type of this option.
Returns:
the class type of this option
Definition at line 127 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.WEKAClassOptionEditComponent.editObject(), moa.gui.ClassOptionWithNamesEditComponent.editObject(), moa.gui.ClassOptionEditComponent.editObject(), weka.core.MOAUtils.fromCommandLine(), and weka.core.MOAUtils.fromOption().
{
        return this.requiredType;
    }
abstract String moa.options.AbstractClassOption.getValueAsCLIString () [pure virtual]
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Implemented in moa.options.ClassOption, moa.options.ClassOptionWithNames, and moa.options.WEKAClassOption.
Object moa.options.AbstractClassOption.materializeObject (TaskMonitor monitor, ObjectRepository repository)
Gets a materialized object of this option.
Parameters:
monitor the task monitor to use
repository the object repository to use
Returns:
the materialized object
Definition at line 147 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.currentValue, moa.tasks.Task.doTask(), moa.core.ObjectRepository.getObjectNamed(), and moa.options.AbstractClassOption.requiredType.
Referenced by moa.options.AbstractOptionHandler.prepareClassOptions().
{
        if ((this.currentValue == null)
                || this.requiredType.isInstance(this.currentValue)) {
            return this.currentValue;
        } else if (this.currentValue instanceof String) {
            if (repository != null) {
                Object inmemObj = repository.getObjectNamed((String) this.currentValue);
                if (inmemObj == null) {
                    throw new RuntimeException("No object named "
                            + this.currentValue + " found in repository.");
                }
                return inmemObj;
            }
            throw new RuntimeException("No object repository available.");
        } else if (this.currentValue instanceof Task) {
            Task task = (Task) this.currentValue;
            Object result = task.doTask(monitor, repository);
            return result;
        } else if (this.currentValue instanceof File) {
            File inputFile = (File) this.currentValue;
            Object result = null;
            try {
                result = SerializeUtils.readFromFile(inputFile);
            } catch (Exception ex) {
                throw new RuntimeException("Problem loading "
                        + this.requiredType.getName() + " object from file '"
                        + inputFile.getName() + "':\n" + ex.getMessage(), ex);
            }
            return result;
        } else {
            throw new RuntimeException(
                    "Could not materialize object of required type "
                    + this.requiredType.getName() + ", found "
                    + this.currentValue.getClass().getName()
                    + " instead.");
        }
    }
void moa.options.AbstractClassOption.setCurrentObject (Object obj)
Sets current object.
Parameters:
obj the object to set as current.
Definition at line 101 of file AbstractClassOption.java.
References moa.options.AbstractClassOption.currentValue, moa.options.AbstractClassOption.nullString, and moa.options.AbstractClassOption.requiredType.
Referenced by moa.tasks.EvaluateModel.EvaluateModel(), moa.tasks.EvaluateModelRegression.EvaluateModelRegression(), moa.tasks.LearnModel.LearnModel(), moa.tasks.LearnModelRegression.LearnModelRegression(), weka.datagenerators.classifiers.classification.MOA.setOptions(), and weka.classifiers.meta.MOA.setOptions().
{
        if (((obj == null) && (this.nullString != null))
                || this.requiredType.isInstance(obj)
                || (obj instanceof String)
                || (obj instanceof File)
                || ((obj instanceof Task) && this.requiredType.isAssignableFrom(((Task) obj).getTaskResultType()))) {
            this.currentValue = obj;
        } else {
            throw new IllegalArgumentException("Object not of required type.");
        }
    }
abstract void moa.options.AbstractClassOption.setValueViaCLIString (String s) [pure virtual]
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Implemented in moa.options.ClassOption, moa.options.ClassOptionWithNames, and moa.options.WEKAClassOption.
static String moa.options.AbstractClassOption.stripPackagePrefix (String className, Class<?> expectedType) [static]
Gets the class name without its package name prefix.
Parameters:
className the name of the class
expectedType the type of the class
Returns:
the class name without its package name prefix
Definition at line 231 of file AbstractClassOption.java.
{
        if (className.startsWith(expectedType.getPackage().getName())) {
            return className.substring(expectedType.getPackage().getName().length() + 1);
        }
        return className;
    }
Member Data Documentation
Object moa.options.AbstractClassOption.currentValue [protected]
The current object.
Definition at line 48 of file AbstractClassOption.java.
Referenced by moa.options.AbstractClassOption.getPreMaterializedObject(), moa.options.WEKAClassOption.getValueAsCLIString(), moa.options.ClassOptionWithNames.getValueAsCLIString(), moa.options.ClassOption.getValueAsCLIString(), moa.options.AbstractClassOption.materializeObject(), moa.options.AbstractClassOption.setCurrentObject(), moa.options.WEKAClassOption.setValueViaCLIString(), moa.options.ClassOptionWithNames.setValueViaCLIString(), and moa.options.ClassOption.setValueViaCLIString().
String moa.options.AbstractClassOption.defaultCLIString [protected]
The default command line interface text.
Definition at line 54 of file AbstractClassOption.java.
Referenced by moa.options.AbstractClassOption.getDefaultCLIString().
final String moa.options.AbstractClassOption.FILE_PREFIX_STRING = "file:" [static]
The prefix text to use to indicate file.
Definition at line 42 of file AbstractClassOption.java.
Referenced by moa.options.WEKAClassOption.cliStringToObject(), moa.options.ClassOptionWithNames.cliStringToObject(), moa.options.ClassOption.cliStringToObject(), moa.options.WEKAClassOption.objectToCLIString(), moa.options.ClassOptionWithNames.objectToCLIString(), and moa.options.ClassOption.objectToCLIString().
final String moa.options.AbstractClassOption.INMEM_PREFIX_STRING = "inmem:" [static]
The prefix text to use to indicate inmem.
Definition at line 45 of file AbstractClassOption.java.
Referenced by moa.options.WEKAClassOption.cliStringToObject(), moa.options.ClassOptionWithNames.cliStringToObject(), moa.options.ClassOption.cliStringToObject(), moa.options.WEKAClassOption.objectToCLIString(), moa.options.ClassOptionWithNames.objectToCLIString(), and moa.options.ClassOption.objectToCLIString().
String moa.options.AbstractClassOption.nullString [protected]
The null text.
Definition at line 57 of file AbstractClassOption.java.
Referenced by moa.options.AbstractClassOption.getNullString(), moa.options.WEKAClassOption.getValueAsCLIString(), moa.options.ClassOptionWithNames.getValueAsCLIString(), moa.options.ClassOption.getValueAsCLIString(), moa.options.AbstractClassOption.setCurrentObject(), moa.options.WEKAClassOption.setValueViaCLIString(), moa.options.ClassOptionWithNames.setValueViaCLIString(), and moa.options.ClassOption.setValueViaCLIString().
Class<?> moa.options.AbstractClassOption.requiredType [protected]
The class type.
Definition at line 51 of file AbstractClassOption.java.
Referenced by moa.options.WEKAClassOption.cliStringToObject(), moa.options.ClassOptionWithNames.cliStringToObject(), moa.options.ClassOption.cliStringToObject(), moa.options.AbstractClassOption.getRequiredType(), moa.options.ClassOptionWithNames.getValueAsCLIString(), moa.options.ClassOption.getValueAsCLIString(), moa.options.AbstractClassOption.materializeObject(), moa.options.AbstractClassOption.setCurrentObject(), moa.options.WEKAClassOption.setValueViaCLIString(), moa.options.ClassOptionWithNames.setValueViaCLIString(), and moa.options.ClassOption.setValueViaCLIString().
final long moa.options.AbstractClassOption.serialVersionUID = 1L [static, private]
Reimplemented in moa.options.ClassOption, moa.options.ClassOptionWithNames, and moa.options.WEKAClassOption.
Definition at line 39 of file AbstractClassOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/AbstractClassOption.java