MOA: moa.classifiers.trees.DecisionStump Class Reference
moa.classifiers.trees.DecisionStump Class Reference
Decision trees of one level.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
IntOption gracePeriodOption
FlagOption binarySplitsOption
ClassOption splitCriterionOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
AttributeSplitSuggestion findBestSplit (SplitCriterion criterion)
Protected Attributes
AttributeSplitSuggestion bestSplit
DoubleVector observedClassDistribution
AutoExpandVector
< AttributeClassObserver > attributeObservers
double weightSeenAtLastSplit
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Decision trees of one level.
Parameters:
-g : The number of instances to observe between model changes
-b : Only allow binary splits
-c : Split criterion to use. Example : InfoGainSplitCriterion
-r : Seed for random behaviour of the classifier
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 50 of file DecisionStump.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.trees.DecisionStump.findBestSplit (SplitCriterion criterion) [protected]
Definition at line 139 of file DecisionStump.java.
References moa.classifiers.trees.DecisionStump.attributeObservers, moa.classifiers.trees.DecisionStump.binarySplitsOption, moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.options.FlagOption.isSet, moa.classifiers.core.AttributeSplitSuggestion.merit, and moa.classifiers.trees.DecisionStump.observedClassDistribution.
Referenced by moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
{
        AttributeSplitSuggestion bestFound = null;
        double bestMerit = Double.NEGATIVE_INFINITY;
        double[] preSplitDist = this.observedClassDistribution.getArrayCopy();
        for (int i = 0; i < this.attributeObservers.size(); i++) {
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs != null) {
                AttributeSplitSuggestion suggestion = obs.getBestEvaluatedSplitSuggestion(criterion,
                        preSplitDist, i, this.binarySplitsOption.isSet());
                if (suggestion.merit > bestMerit) {
                    bestMerit = suggestion.merit;
                    bestFound = suggestion;
                }
            }
        }
        return bestFound;
    }
void moa.classifiers.trees.DecisionStump.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 92 of file DecisionStump.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.trees.DecisionStump.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 87 of file DecisionStump.java.
{
        return null;
    }
String moa.classifiers.trees.DecisionStump.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 55 of file DecisionStump.java.
{
        return "Decision trees of one level.";
    }
double [] moa.classifiers.trees.DecisionStump.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 116 of file DecisionStump.java.
References moa.classifiers.trees.DecisionStump.bestSplit, moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), moa.core.DoubleVector.getArrayCopy(), moa.classifiers.trees.DecisionStump.observedClassDistribution, moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), and moa.classifiers.core.AttributeSplitSuggestion.splitTest.
{
        if (this.bestSplit != null) {
            int branch = this.bestSplit.splitTest.branchForInstance(inst);
            if (branch >= 0) {
                return this.bestSplit.resultingClassDistributionFromSplit(branch);
            }
        }
        return this.observedClassDistribution.getArrayCopy();
    }
boolean moa.classifiers.trees.DecisionStump.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 127 of file DecisionStump.java.
{
        return false;
    }
AttributeClassObserver moa.classifiers.trees.DecisionStump.newNominalClassObserver () [protected]
Definition at line 131 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
{
        return new NominalAttributeClassObserver();
    }
AttributeClassObserver moa.classifiers.trees.DecisionStump.newNumericClassObserver () [protected]
Definition at line 135 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
{
        return new GaussianNumericAttributeClassObserver();
    }
void moa.classifiers.trees.DecisionStump.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 79 of file DecisionStump.java.
References moa.classifiers.trees.DecisionStump.attributeObservers, moa.classifiers.trees.DecisionStump.bestSplit, moa.classifiers.trees.DecisionStump.observedClassDistribution, and moa.classifiers.trees.DecisionStump.weightSeenAtLastSplit.
{
        this.bestSplit = null;
        this.observedClassDistribution = new DoubleVector();
        this.attributeObservers = new AutoExpandVector<AttributeClassObserver>();
        this.weightSeenAtLastSplit = 0.0;
    }
void moa.classifiers.trees.DecisionStump.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 97 of file DecisionStump.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.DecisionStump.attributeObservers, moa.classifiers.trees.DecisionStump.bestSplit, moa.classifiers.trees.DecisionStump.findBestSplit(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.trees.DecisionStump.gracePeriodOption, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.DecisionStump.newNominalClassObserver(), moa.classifiers.trees.DecisionStump.newNumericClassObserver(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), moa.classifiers.trees.DecisionStump.observedClassDistribution, moa.classifiers.trees.DecisionStump.splitCriterionOption, moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.trees.DecisionStump.weightSeenAtLastSplit.
{
        this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
        for (int i = 0; i < inst.numAttributes() - 1; i++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs == null) {
                obs = inst.attribute(instAttIndex).isNominal() ? newNominalClassObserver()
                        : newNumericClassObserver();
                this.attributeObservers.set(i, obs);
            }
            obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
        }
        if (this.trainingWeightSeenByModel - this.weightSeenAtLastSplit >= this.gracePeriodOption.getValue()) {
            this.bestSplit = findBestSplit((SplitCriterion) getPreparedClassOption(this.splitCriterionOption));
            this.weightSeenAtLastSplit = this.trainingWeightSeenByModel;
        }
    }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.trees.DecisionStump.attributeObservers [protected]
Definition at line 74 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.findBestSplit(), moa.classifiers.trees.DecisionStump.resetLearningImpl(), and moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
AttributeSplitSuggestion moa.classifiers.trees.DecisionStump.bestSplit [protected]
Definition at line 70 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.getVotesForInstance(), moa.classifiers.trees.DecisionStump.resetLearningImpl(), and moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
FlagOption moa.classifiers.trees.DecisionStump.binarySplitsOption
Initial value:
 new FlagOption("binarySplits", 'b',
            "Only allow binary splits.")
Definition at line 63 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.findBestSplit().
IntOption moa.classifiers.trees.DecisionStump.gracePeriodOption
Initial value:
 new IntOption("gracePeriod", 'g',
            "The number of instances to observe between model changes.", 1000,
            0, Integer.MAX_VALUE)
Definition at line 59 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
DoubleVector moa.classifiers.trees.DecisionStump.observedClassDistribution [protected]
Definition at line 72 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.findBestSplit(), moa.classifiers.trees.DecisionStump.getVotesForInstance(), moa.classifiers.trees.DecisionStump.resetLearningImpl(), and moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
final long moa.classifiers.trees.DecisionStump.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 52 of file DecisionStump.java.
ClassOption moa.classifiers.trees.DecisionStump.splitCriterionOption
Initial value:
 new ClassOption("splitCriterion",
            'c', "Split criterion to use.", SplitCriterion.class,
            "InfoGainSplitCriterion")
Definition at line 66 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
double moa.classifiers.trees.DecisionStump.weightSeenAtLastSplit [protected]
Definition at line 76 of file DecisionStump.java.
Referenced by moa.classifiers.trees.DecisionStump.resetLearningImpl(), and moa.classifiers.trees.DecisionStump.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/DecisionStump.java