MOA: moa.classifiers.trees.ORTO.Node Class Reference
moa.classifiers.trees.ORTO.Node Class Reference
Public Member Functions
Node (int id)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
int calcByteSize ()
boolean isLeaf ()
void calculateDetph (ORTO tree)
int getLevel ()
void setParent (InnerNode parent)
Set the parent node.
InnerNode getParent ()
Return the parent node.
void setChild (int parentBranch, Node node)
int getChildIndex (Node child)
int getNumSubtrees ()
double[] processInstance (Instance inst, ORTO tree)
double[] getPrediction (Instance inst, ORTO tree)
void setAdaptable (boolean value)
void setAlternate (boolean value)
Public Attributes
int ID
Protected Attributes
InnerNode parent
Node alternateTree
boolean Alternate = false
boolean Adaptable = true
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 212 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.Node.Node (int id)
Definition at line 226 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.ID.
{
            this.ID = id;
        }
Member Function Documentation
int moa.classifiers.trees.ORTO.Node.calcByteSize ()
Reimplemented in moa.classifiers.trees.ORTO.InnerNode, and moa.classifiers.trees.ORTO.ActiveLearningNode.
Definition at line 234 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.calcByteSize().
{
            return (int) SizeOf.fullSizeOf(this);
        }
void moa.classifiers.trees.ORTO.Node.calculateDetph (ORTO tree)
Reimplemented in moa.classifiers.trees.ORTO.InnerNode.
Definition at line 242 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.getLevel(), and moa.classifiers.trees.ORTO.maxDepth.
{
            int level = this.getLevel();
            if (level > tree.maxDepth) {
                tree.maxDepth = level;
            }
        }
int moa.classifiers.trees.ORTO.Node.getChildIndex (Node child)
Definition at line 286 of file ORTO.java.
{
            return 0;
        }
void moa.classifiers.trees.ORTO.Node.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 231 of file ORTO.java.
{
        }
int moa.classifiers.trees.ORTO.Node.getLevel ()
Definition at line 249 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Alternate, moa.classifiers.trees.ORTO.Node.alternateTree, moa.classifiers.trees.ORTO.Node.getLevel(), and moa.classifiers.trees.ORTO.Node.getParent().
Referenced by moa.classifiers.trees.ORTO.InnerNode.calculateDetph(), moa.classifiers.trees.ORTO.Node.calculateDetph(), moa.classifiers.trees.ORTO.Node.getLevel(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            Node target = (Node) this.getParent();
            while (target instanceof OptionNode) {
                target = (Node) target.getParent();
            }
            if (target == null) {
                if (!Alternate) {
                    // Actual tree root
                    return 0;
                } else {
                    // Root of alternate tree
                    return alternateTree.getLevel();
                }
            } else {
                return target.getLevel() + 1;
            }
        }
int moa.classifiers.trees.ORTO.Node.getNumSubtrees ()
Reimplemented in moa.classifiers.trees.ORTO.SplitNode, and moa.classifiers.trees.ORTO.OptionNode.
Definition at line 290 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
{
            return 1;
        }
InnerNode moa.classifiers.trees.ORTO.Node.getParent ()
Return the parent node.
Definition at line 278 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.parent.
Referenced by moa.classifiers.trees.ORTO.Node.getLevel().
        {
            return parent;
        }
double [] moa.classifiers.trees.ORTO.Node.getPrediction (Instance inst, ORTO tree)
Reimplemented in moa.classifiers.trees.ORTO.SplitNode, moa.classifiers.trees.ORTO.OptionNode, and moa.classifiers.trees.ORTO.ActiveLearningNode.
Definition at line 303 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.getPrediction(), moa.classifiers.trees.ORTO.SplitNode.getPrediction(), and moa.classifiers.trees.ORTO.getVotesForInstance().
{
            // The returned values represent (by index):
            // 0: the prediction of the node
            // 1: the faded MSE
            // 2: examples seen
            return new double[] {0.0, 0.0, 0.0};
        }
boolean moa.classifiers.trees.ORTO.Node.isLeaf ()
Reimplemented in moa.classifiers.trees.ORTO.SplitNode, and moa.classifiers.trees.ORTO.OptionNode.
Definition at line 238 of file ORTO.java.
{
            return true;
        }
double [] moa.classifiers.trees.ORTO.Node.processInstance (Instance inst, ORTO tree)
Reimplemented in moa.classifiers.trees.ORTO.SplitNode, moa.classifiers.trees.ORTO.OptionNode, and moa.classifiers.trees.ORTO.ActiveLearningNode.
Definition at line 294 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.trainOnInstanceImpl().
{
            // The returned values represent (by index):
            // 0: the prediction of the node
            // 1: the faded MSE
            // 2: examples seen
            // 3: the back propagated PH error
            return new double[] {0.0, 0.0, 0.0, 0.0};
        }
void moa.classifiers.trees.ORTO.Node.setAdaptable (boolean value)
Reimplemented in moa.classifiers.trees.ORTO.InnerNode.
Definition at line 311 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Adaptable.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
{
            Adaptable = value;
        }
void moa.classifiers.trees.ORTO.Node.setAlternate (boolean value)
Reimplemented in moa.classifiers.trees.ORTO.InnerNode.
Definition at line 315 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Alternate.
{
            Alternate = value;
        }
void moa.classifiers.trees.ORTO.Node.setChild (int parentBranch, Node node)
Definition at line 283 of file ORTO.java.
{
        }
void moa.classifiers.trees.ORTO.Node.setParent (InnerNode parent)
Set the parent node.
Definition at line 270 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.SplitNode.getPrediction(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
        {
            this.parent = parent;
        }
Member Data Documentation
boolean moa.classifiers.trees.ORTO.Node.Adaptable = true [protected]
Definition at line 224 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.trees.ORTO.InnerNode.setAdaptable(), and moa.classifiers.trees.ORTO.Node.setAdaptable().
boolean moa.classifiers.trees.ORTO.Node.Alternate = false [protected]
Definition at line 222 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.Node.getLevel(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.trees.ORTO.InnerNode.setAlternate(), and moa.classifiers.trees.ORTO.Node.setAlternate().
Node moa.classifiers.trees.ORTO.Node.alternateTree [protected]
Definition at line 220 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.InnerNode.getAlternateTree(), moa.classifiers.trees.ORTO.Node.getLevel(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.InnerNode.setAlternateTree().
int moa.classifiers.trees.ORTO.Node.ID
Definition at line 216 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.Node.Node().
InnerNode moa.classifiers.trees.ORTO.Node.parent [protected]
Definition at line 218 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.findWorstOption(), moa.classifiers.trees.ORTO.Node.getParent(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.removeExcessTrees().
final long moa.classifiers.trees.ORTO.Node.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.trees.ORTO.InnerNode, moa.classifiers.trees.ORTO.SplitNode, moa.classifiers.trees.ORTO.OptionNode, and moa.classifiers.trees.ORTO.ActiveLearningNode.
Definition at line 214 of file ORTO.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java