MOA: weka.gui.MOAClassOptionEditor Class Reference
weka.gui.MOAClassOptionEditor Class Reference
An editor for MOA ClassOption objects.
Public Member Functions
boolean isPaintable ()
Returns true since this editor is paintable.
boolean supportsCustomEditor ()
Returns true because we do support a custom editor.
Component getCustomEditor ()
Gets the custom editor component.
void paintValue (Graphics gfx, Rectangle box)
Paints a representation of the current Object.
Protected Member Functions
void closeDialog ()
Closes the dialog.
Component createCustomEditor ()
Creates the custom editor.
Protected Attributes
Component m_CustomEditor
the custom editor.
ClassOptionEditComponent m_EditComponent
the component for editing.
Detailed Description
An editor for MOA ClassOption objects.
Author:
FracPete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
See also:
ClassOption
Definition at line 32 of file MOAClassOptionEditor.java.
Member Function Documentation
void weka.gui.MOAClassOptionEditor.closeDialog () [protected]
Closes the dialog.
Definition at line 62 of file MOAClassOptionEditor.java.
References weka.gui.MOAClassOptionEditor.m_CustomEditor.
{
        if (m_CustomEditor instanceof Container) {
            Dialog dlg = PropertyDialog.getParentDialog((Container) m_CustomEditor);
            if (dlg != null)
                dlg.setVisible(false);
        }
    }
Component weka.gui.MOAClassOptionEditor.createCustomEditor () [protected]
Creates the custom editor.
Returns:
the editor
Definition at line 75 of file MOAClassOptionEditor.java.
References moa.gui.ClassOptionEditComponent.addChangeListener(), moa.gui.ClassOptionEditComponent.applyState(), moa.gui.ClassOptionEditComponent.getEditedOption(), and weka.gui.MOAClassOptionEditor.m_EditComponent.
Referenced by weka.gui.MOAClassOptionEditor.getCustomEditor().
{
        JPanel          panel;
        panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        m_EditComponent = (ClassOptionEditComponent) ((ClassOption) getValue()).getEditComponent();
        m_EditComponent.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                m_EditComponent.applyState();
                setValue(m_EditComponent.getEditedOption());
            }
        });
        panel.add(m_EditComponent, BorderLayout.CENTER);
        return panel;
    }
Component weka.gui.MOAClassOptionEditor.getCustomEditor ()
Gets the custom editor component.
Returns:
the editor
Definition at line 97 of file MOAClassOptionEditor.java.
References weka.gui.MOAClassOptionEditor.createCustomEditor(), and weka.gui.MOAClassOptionEditor.m_CustomEditor.
{
        if (m_CustomEditor == null)
            m_CustomEditor = createCustomEditor();
        return m_CustomEditor;
    }
boolean weka.gui.MOAClassOptionEditor.isPaintable ()
Returns true since this editor is paintable.
Returns:
always true.
Definition at line 46 of file MOAClassOptionEditor.java.
{
        return false;
    }
void weka.gui.MOAClassOptionEditor.paintValue (Graphics gfx, Rectangle box)
Paints a representation of the current Object.
Parameters:
gfx the graphics context to use
box the area we are allowed to paint into
Definition at line 110 of file MOAClassOptionEditor.java.
{
    FontMetrics     fm;
    int                     vpad;
    String              val;
    fm   = gfx.getFontMetrics();
    vpad = (box.height - fm.getHeight()) / 2 ;
    val  = ((ClassOption) getValue()).getValueAsCLIString();
    gfx.drawString(val, 2, fm.getHeight() + vpad);
  }
boolean weka.gui.MOAClassOptionEditor.supportsCustomEditor ()
Returns true because we do support a custom editor.
Returns:
always true
Definition at line 55 of file MOAClassOptionEditor.java.
{
        return true;
    }
Member Data Documentation
Component weka.gui.MOAClassOptionEditor.m_CustomEditor [protected]
the custom editor.
Definition at line 36 of file MOAClassOptionEditor.java.
Referenced by weka.gui.MOAClassOptionEditor.closeDialog(), and weka.gui.MOAClassOptionEditor.getCustomEditor().
ClassOptionEditComponent weka.gui.MOAClassOptionEditor.m_EditComponent [protected]
the component for editing.
Definition at line 39 of file MOAClassOptionEditor.java.
Referenced by weka.gui.MOAClassOptionEditor.createCustomEditor().
The documentation for this class was generated from the following file:
main/java/weka/gui/MOAClassOptionEditor.java