MOA: moa.evaluation.FadingFactorClassificationPerformanceEvaluator Class Reference
moa.evaluation.FadingFactorClassificationPerformanceEvaluator Class Reference
Classification evaluator that updates evaluation results using a fading factor.
Classes
class Estimator
Public Member Functions
void reset ()
Resets this evaluator.
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getFractionCorrectlyClassified ()
double getFractionIncorrectlyClassified ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Public Attributes
FloatOption alphaOption
Protected Attributes
double TotalweightObserved
Estimator weightCorrect
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Classification evaluator that updates evaluation results using a fading factor.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 37 of file FadingFactorClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.FadingFactorClassificationPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 94 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.add(), moa.evaluation.FadingFactorClassificationPerformanceEvaluator.TotalweightObserved, and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.weightCorrect.
{
        double weight = inst.weight();
        int trueClass = (int) inst.classValue();
        if (weight > 0.0) {
            this.TotalweightObserved += weight;
            if (Utils.maxIndex(classVotes) == trueClass) {
                this.weightCorrect.add(1);
            } else {
                this.weightCorrect.add(0);
            }
        }
    }
void moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 129 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionCorrectlyClassified ()
Definition at line 120 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation, and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.weightCorrect.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionIncorrectlyClassified(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightCorrect.estimation();
    }
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionIncorrectlyClassified ()
Definition at line 124 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
{
        return 1.0 - getFractionCorrectlyClassified();
    }
Measurement [] moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 108 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.TotalweightObserved.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
                    new Measurement("classified instances",
                    this.TotalweightObserved),
                    new Measurement("classifications correct (percent)",
                    getFractionCorrectlyClassified() * 100.0)};
    }
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 116 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.TotalweightObserved.
{
        return this.TotalweightObserved;
    }
void moa.evaluation.FadingFactorClassificationPerformanceEvaluator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 135 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.reset().
{
        reset();
    }
void moa.evaluation.FadingFactorClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 79 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.alphaOption, moa.options.FloatOption.getValue(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.weightCorrect.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.prepareForUseImpl().
{
        weightCorrect = new Estimator(this.alphaOption.getValue());
    }
Member Data Documentation
FloatOption moa.evaluation.FadingFactorClassificationPerformanceEvaluator.alphaOption
Initial value:
 new FloatOption("alpha",
            'a', "Fading factor or exponential smoothing factor", .999)
Definition at line 44 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.reset().
final long moa.evaluation.FadingFactorClassificationPerformanceEvaluator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 40 of file FadingFactorClassificationPerformanceEvaluator.java.
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.TotalweightObserved [protected]
Definition at line 42 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.addResult(), moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getTotalWeightObserved().
Estimator moa.evaluation.FadingFactorClassificationPerformanceEvaluator.weightCorrect [protected]
Definition at line 47 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.addResult(), moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/FadingFactorClassificationPerformanceEvaluator.java