MOA: moa.test.FileUtils Class Reference
moa.test.FileUtils Class Reference
Basic file-handling stuff.
Static Public Member Functions
static List< String > loadFromFile (File file)
Returns the content of the given file, null in case of an error.
static List< String > loadFromFile (File file, String encoding)
Returns the content of the given file, null in case of an error.
static boolean saveToFile (String[] content, File file)
Saves the content to the given file.
static boolean saveToFile (List< String > content, File file)
Saves the content to the given file.
static boolean saveToFile (List< String > content, File file, String encoding)
Saves the content to the given file.
static boolean writeToFile (String filename, Object obj)
Writes the given object to the specified file.
static boolean writeToFile (String filename, Object obj, String encoding)
Writes the given object to the specified file.
static boolean writeToFile (String filename, Object obj, boolean append)
Writes the given object to the specified file.
static boolean writeToFile (String filename, Object obj, boolean append, String encoding)
Writes the given object to the specified file.
static boolean copy (File sourceLocation, File targetLocation) throws IOException
Copies the file/directory (recursively).
static boolean move (File sourceLocation, File targetLocation) throws IOException
Moves the file/directory (recursively).
static boolean copyOrMove (File sourceLocation, File targetLocation, boolean move) throws IOException
Copies or moves files and directories (recursively).
Detailed Description
Basic file-handling stuff.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 41 of file FileUtils.java.
Member Function Documentation
static boolean moa.test.FileUtils.copy (File sourceLocation, File targetLocation) throws IOException [static]
Copies the file/directory (recursively).
Parameters:
sourceLocation the source file/dir
targetLocation the target file/dir
Returns:
if successfully copied
Exceptions:
IOException if copying fails
Definition at line 226 of file FileUtils.java.
References moa.test.FileUtils.copyOrMove().
{
    return copyOrMove(sourceLocation, targetLocation, false);
  }
static boolean moa.test.FileUtils.copyOrMove (File sourceLocation, File targetLocation, boolean move) throws IOException [static]
Copies or moves files and directories (recursively).
If targetLocation does not exist, it will be created.
Original code from Java-Tips.org.
Parameters:
sourceLocation the source file/dir
targetLocation the target file/dir
move if true then the source files/dirs get deleted as soon as copying finished
Returns:
false if failed to delete when moving or failed to create target directory
Exceptions:
IOException if copying/moving fails
Definition at line 255 of file FileUtils.java.
References moa.test.FileUtils.move().
Referenced by moa.test.FileUtils.copy(), and moa.test.FileUtils.move().
{
    String[]        children;
    int         i;
    InputStream     in;
    OutputStream    out;
    byte[]      buf;
    int         len;
    if (sourceLocation.isDirectory()) {
      if (!targetLocation.exists()) {
    if (!targetLocation.mkdir())
      return false;
      }
      children = sourceLocation.list();
      for (i = 0; i < children.length; i++) {
        if (!copyOrMove(
            new File(sourceLocation.getAbsoluteFile(), children[i]),
            new File(targetLocation.getAbsoluteFile(), children[i]),
            move))
          return false;
      }
      if (move)
        return sourceLocation.delete();
      else
    return true;
    }
    else {
      in = new FileInputStream(sourceLocation.getAbsoluteFile());
      // do we need to append the filename?
      if (targetLocation.isDirectory())
        out = new FileOutputStream(targetLocation.getAbsolutePath() + File.separator + sourceLocation.getName());
      else
        out = new FileOutputStream(targetLocation.getAbsoluteFile());
      // Copy the content from instream to outstream
      buf = new byte[1024];
      while ((len = in.read(buf)) > 0)
        out.write(buf, 0, len);
      in.close();
      out.close();
      if (move)
        return sourceLocation.delete();
      else
    return true;
    }
  }
static List<String> moa.test.FileUtils.loadFromFile (File file, String encoding) [static]
Returns the content of the given file, null in case of an error.
Parameters:
file the file to load
encoding the encoding to use, null to use default
Returns:
the content/lines of the file
Definition at line 60 of file FileUtils.java.
{
    List<String>    result;
    BufferedReader  reader;
    String      line;
    result = new ArrayList<String>();
    try {
      if ((encoding != null) && (encoding.length() > 0))
    reader = new BufferedReader(new InputStreamReader(new FileInputStream(file.getAbsolutePath()), encoding));
      else
    reader = new BufferedReader(new InputStreamReader(new FileInputStream(file.getAbsolutePath())));
      while ((line = reader.readLine()) != null)
        result.add(line);
      reader.close();
    }
    catch (Exception e) {
      result = null;
      e.printStackTrace();
    }
    return result;
  }
static List<String> moa.test.FileUtils.loadFromFile (File file) [static]
Returns the content of the given file, null in case of an error.
Parameters:
file the file to load
Returns:
the content/lines of the file
Definition at line 49 of file FileUtils.java.
{
    return loadFromFile(file, null);
  }
static boolean moa.test.FileUtils.move (File sourceLocation, File targetLocation) throws IOException [static]
Moves the file/directory (recursively).
Parameters:
sourceLocation the source file/dir
targetLocation the target file/dir
Returns:
if successfully moved
Exceptions:
IOException if moving fails
Definition at line 238 of file FileUtils.java.
References moa.test.FileUtils.copyOrMove().
Referenced by moa.test.FileUtils.copyOrMove().
{
    return copyOrMove(sourceLocation, targetLocation, true);
  }
static boolean moa.test.FileUtils.saveToFile (List< String > content, File file, String encoding) [static]
Saves the content to the given file.
Parameters:
content the content to save
file the file to save the content to
encoding the encoding to use, null for default
Returns:
true if successfully saved
Definition at line 121 of file FileUtils.java.
{
    boolean     result;
    BufferedWriter  writer;
    int         i;
    result = true;
    try {
      if ((encoding != null) && (encoding.length() > 0))
    writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file.getAbsolutePath()), encoding));
      else
    writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file.getAbsolutePath())));
      for (i = 0; i < content.size(); i++) {
        writer.write(content.get(i));
        writer.newLine();
      }
      writer.flush();
      writer.close();
    }
    catch (Exception e) {
      result = false;
      e.printStackTrace();
    }
    return result;
  }
static boolean moa.test.FileUtils.saveToFile (List< String > content, File file) [static]
Saves the content to the given file.
Parameters:
content the content to save
file the file to save the content to
Returns:
true if successfully saved
Definition at line 109 of file FileUtils.java.
References moa.test.FileUtils.saveToFile().
{
    return saveToFile(content, file, null);
  }
static boolean moa.test.FileUtils.saveToFile (String[] content, File file) [static]
Saves the content to the given file.
Parameters:
content the content to save
file the file to save the content to
Returns:
true if successfully saved
Definition at line 91 of file FileUtils.java.
Referenced by moa.test.FileUtils.saveToFile().
{
    List<String>    lines;
    int         i;
    lines = new ArrayList<String>();
    for (i = 0; i < content.length; i++)
      lines.add(content[i]);
    return FileUtils.saveToFile(lines, file);
  }
static boolean moa.test.FileUtils.writeToFile (String filename, Object obj, boolean append, String encoding) [static]
Writes the given object to the specified file.
The message is either appended or replaces the current content of the file.
Parameters:
filename the file to write to
obj the object to write
append whether to append the message or not
encoding the encoding to use, null for default
Returns:
true if writing was successful
Definition at line 196 of file FileUtils.java.
{
    boolean     result;
    BufferedWriter  writer;
    try {
      if ((encoding != null) && (encoding.length() > 0))
    writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filename, append), encoding));
      else
    writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filename, append)));
      writer.write("" + obj);
      writer.newLine();
      writer.flush();
      writer.close();
      result = true;
    }
    catch (Exception e) {
      result = false;
    }
    return result;
  }
static boolean moa.test.FileUtils.writeToFile (String filename, Object obj, boolean append) [static]
Writes the given object to the specified file.
The message is either appended or replaces the current content of the file.
Parameters:
filename the file to write to
obj the object to write
append whether to append the message or not
Returns:
true if writing was successful
Definition at line 182 of file FileUtils.java.
References moa.test.FileUtils.writeToFile().
{
    return writeToFile(filename, obj, append, null);
  }
static boolean moa.test.FileUtils.writeToFile (String filename, Object obj, String encoding) [static]
Writes the given object to the specified file.
The object is always appended.
Parameters:
filename the file to write to
obj the object to write
encoding the encoding to use, null for default
Returns:
true if writing was successful
Definition at line 169 of file FileUtils.java.
References moa.test.FileUtils.writeToFile().
{
    return writeToFile(filename, obj, true, encoding);
  }
static boolean moa.test.FileUtils.writeToFile (String filename, Object obj) [static]
Writes the given object to the specified file.
The object is always appended.
Parameters:
filename the file to write to
obj the object to write
Returns:
true if writing was successful
Definition at line 156 of file FileUtils.java.
Referenced by moa.test.FileUtils.writeToFile().
{
    return writeToFile(filename, obj, null);
  }
The documentation for this class was generated from the following file:
test/java/moa/test/FileUtils.java