MOA: moa.classifiers.core.driftdetection.HDDM_A_Test Class Reference
moa.classifiers.core.driftdetection.HDDM_A_Test Class Reference
Public Member Functions
HDDM_A_Test ()
void input (double value)
Adding a numeric value to the change detector<br>
.
void resetLearning ()
Resets this change detector.
double getEstimation ()
Gets the prediction of next values.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
Public Attributes
FloatOption driftConfidenceOption
FloatOption warningConfidenceOption
MultiChoiceOption oneSidedTestOption
Protected Member Functions
void updateEstimations ()
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
int n_min = 0
double c_min = 0
int total_n = 0
double total_c = 0
int n_max = 0
double c_max = 0
double cEstimacion = 0
int nEstimacion = 0
Private Member Functions
boolean meanIncr (double c_min, int n_min, double total_c, int total_n, double confianzaCambio)
boolean meanDecr (double c_max, int n_max, double total_c, int total_n)
Detailed Description
Online drift detection method based on Hoeffding's bounds. HDDMA-test uses the average as estimator. It receives as input a stream of real values and returns the estimated status of the stream: STABLE, WARNING or DRIFT.
I. Frias-Blanco, J. del Campo-Avila, G. Ramos-Jimenez, R. Morales-Bueno, A. Ortiz-Diaz, and Y. Caballero-Mota, Online and non-parametric drift detection methods based on Hoeffding's bound, IEEE Transactions on Knowledge and Data Engineering, 2014. DOI 10.1109/TKDE.2014.2345382.
Parameters:
-d : Confidence to the drift
-w : Confidence to the warning
-t : Option to monitor error increments and decrements (two-sided) or only increments (one-sided)
Author:
Isvani Frias-Blanco (ifriasb@udg.co.cu)
Definition at line 49 of file HDDM_A_Test.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.HDDM_A_Test.HDDM_A_Test ()
Definition at line 73 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
{
        resetLearning();
    }
Member Function Documentation
void moa.classifiers.core.driftdetection.HDDM_A_Test.getDescription (StringBuilder sb, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 174 of file HDDM_A_Test.java.
{
    }
double moa.classifiers.core.driftdetection.HDDM_A_Test.getEstimation ()
Gets the prediction of next values.
Returns:
a prediction of the next value
Reimplemented from moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 169 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.AbstractChangeDetector.estimation.
{
        return this.estimation;
    }
void moa.classifiers.core.driftdetection.HDDM_A_Test.input (double inputValue) [virtual]
Adding a numeric value to the change detector<br>
.
The output of the change detector is modified after the insertion of a new item inside.
Parameters:
inputValue the number to insert into the change detector
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 78 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.c_max, moa.classifiers.core.driftdetection.HDDM_A_Test.c_min, moa.classifiers.core.driftdetection.HDDM_A_Test.cEstimacion, moa.classifiers.core.driftdetection.HDDM_A_Test.driftConfidenceOption, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.classifiers.core.driftdetection.AbstractChangeDetector.isChangeDetected, moa.classifiers.core.driftdetection.AbstractChangeDetector.isWarningZone, moa.classifiers.core.driftdetection.HDDM_A_Test.meanDecr(), moa.classifiers.core.driftdetection.HDDM_A_Test.meanIncr(), moa.classifiers.core.driftdetection.HDDM_A_Test.n_max, moa.classifiers.core.driftdetection.HDDM_A_Test.n_min, moa.classifiers.core.driftdetection.HDDM_A_Test.nEstimacion, moa.classifiers.core.driftdetection.HDDM_A_Test.oneSidedTestOption, moa.classifiers.core.driftdetection.HDDM_A_Test.total_c, moa.classifiers.core.driftdetection.HDDM_A_Test.total_n, moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations(), and moa.classifiers.core.driftdetection.HDDM_A_Test.warningConfidenceOption.
{
        total_n++;
        total_c += value;
        if (n_min == 0) {
            n_min = total_n;
            c_min = total_c;
        }
        if (n_max == 0) {
            n_max = total_n;
            c_max = total_c;
        }
        double cota = Math.sqrt(1.0 / (2 * n_min) * Math.log(1.0 / driftConfidenceOption.getValue())),
                cota1 = Math.sqrt(1.0 / (2 * total_n) * Math.log(1.0 / driftConfidenceOption.getValue()));
        if (c_min / n_min + cota >= total_c / total_n + cota1) {
            c_min = total_c;
            n_min = total_n;
        }
        cota = Math.sqrt(1.0 / (2 * n_max) * Math.log(1.0 / driftConfidenceOption.getValue()));
        if (c_max / n_max - cota <= total_c / total_n - cota1) {
            c_max = total_c;
            n_max = total_n;
        }
        if (meanIncr(c_min, n_min, total_c, total_n, driftConfidenceOption.getValue())) {
            nEstimacion = total_n - n_min;
            cEstimacion = total_c - c_min;
            n_min = n_max = total_n = 0;
            c_min = c_max = total_c = 0;
            this.isChangeDetected = true;
            this.isWarningZone = false;
        } else if (meanIncr(c_min, n_min, total_c, total_n, warningConfidenceOption.getValue())) {
            this.isChangeDetected = false;
            this.isWarningZone = true;
        } else {
            this.isChangeDetected = false;
            this.isWarningZone = false;
        }
        if (this.oneSidedTestOption.getChosenIndex() == 1
                && meanDecr(c_max, n_max, total_c, total_n)) {
            nEstimacion = total_n - n_max;
            cEstimacion = total_c - c_max;
            n_min = n_max = total_n = 0;
            c_min = c_max = total_c = 0;
        }
        updateEstimations();
    }
boolean moa.classifiers.core.driftdetection.HDDM_A_Test.meanDecr (double c_max, int n_max, double total_c, int total_n) [private]
Definition at line 135 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.driftConfidenceOption, and moa.options.FloatOption.getValue().
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input().
{
        if (n_max == total_n) {
            return false;
        }
        double m = (double) (total_n - n_max) / n_max * (1.0 / total_n);
        double cota = Math.sqrt(m / 2 * Math.log(2.0 / driftConfidenceOption.getValue()));
        return c_max / n_max - total_c / total_n >= cota;
    }
boolean moa.classifiers.core.driftdetection.HDDM_A_Test.meanIncr (double c_min, int n_min, double total_c, int total_n, double confianzaCambio) [private]
Definition at line 126 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input().
{
        if (n_min == total_n) {
            return false;
        }
        double m = (double) (total_n - n_min) / n_min * (1.0 / total_n);
        double cota = Math.sqrt(m / 2 * Math.log(2.0 / confianzaCambio));
        return total_c / total_n - c_min / n_min >= cota;
    }
void moa.classifiers.core.driftdetection.HDDM_A_Test.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 178 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
{
        resetLearning();
    }
void moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning ()
Resets this change detector.
It must be similar to starting a new change detector from scratch.
Reimplemented from moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 145 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.c_max, moa.classifiers.core.driftdetection.HDDM_A_Test.c_min, moa.classifiers.core.driftdetection.HDDM_A_Test.cEstimacion, moa.classifiers.core.driftdetection.HDDM_A_Test.n_max, moa.classifiers.core.driftdetection.HDDM_A_Test.n_min, moa.classifiers.core.driftdetection.HDDM_A_Test.nEstimacion, moa.classifiers.core.driftdetection.HDDM_A_Test.total_c, and moa.classifiers.core.driftdetection.HDDM_A_Test.total_n.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.HDDM_A_Test(), and moa.classifiers.core.driftdetection.HDDM_A_Test.prepareForUseImpl().
{
        super.resetLearning();
        n_min = 0;
        c_min = 0;
        total_n = 0;
        total_c = 0;
        n_max = 0;
        c_max = 0;
        cEstimacion = 0;
        nEstimacion = 0;
    }
void moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations () [protected]
Definition at line 157 of file HDDM_A_Test.java.
References moa.classifiers.core.driftdetection.HDDM_A_Test.cEstimacion, moa.classifiers.core.driftdetection.AbstractChangeDetector.delay, moa.classifiers.core.driftdetection.AbstractChangeDetector.estimation, moa.classifiers.core.driftdetection.HDDM_A_Test.nEstimacion, moa.classifiers.core.driftdetection.HDDM_A_Test.total_c, and moa.classifiers.core.driftdetection.HDDM_A_Test.total_n.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input().
{
        if (this.total_n >= this.nEstimacion) {
            this.cEstimacion = this.nEstimacion = 0;
            this.estimation = this.total_c / this.total_n;
            this.delay = this.total_n;
        } else {
            this.estimation = this.cEstimacion / this.nEstimacion;
            this.delay = this.nEstimacion;
        }
    }
Member Data Documentation
double moa.classifiers.core.driftdetection.HDDM_A_Test.c_max = 0 [protected]
Definition at line 69 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), and moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
double moa.classifiers.core.driftdetection.HDDM_A_Test.c_min = 0 [protected]
Definition at line 65 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), and moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
double moa.classifiers.core.driftdetection.HDDM_A_Test.cEstimacion = 0 [protected]
Definition at line 70 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations().
FloatOption moa.classifiers.core.driftdetection.HDDM_A_Test.driftConfidenceOption
Initial value:
 new FloatOption("driftConfidence", 'd',
            "Confidence to the drift",
            0.001, 0, 1)
Definition at line 51 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), and moa.classifiers.core.driftdetection.HDDM_A_Test.meanDecr().
int moa.classifiers.core.driftdetection.HDDM_A_Test.n_max = 0 [protected]
Definition at line 68 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), and moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
int moa.classifiers.core.driftdetection.HDDM_A_Test.n_min = 0 [protected]
Definition at line 64 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), and moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning().
int moa.classifiers.core.driftdetection.HDDM_A_Test.nEstimacion = 0 [protected]
Definition at line 71 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations().
MultiChoiceOption moa.classifiers.core.driftdetection.HDDM_A_Test.oneSidedTestOption
Initial value:
 new MultiChoiceOption(
            "typeOfTest", 't',
            "Monitors error increments and decrements (two-sided) or only increments (one-sided)", new String[]{
        "One-sided", "Two-sided"}, new String[]{
        "One-sided", "Two-sided"},
            1)
Definition at line 57 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input().
double moa.classifiers.core.driftdetection.HDDM_A_Test.total_c = 0 [protected]
Definition at line 67 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations().
int moa.classifiers.core.driftdetection.HDDM_A_Test.total_n = 0 [protected]
Definition at line 66 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.core.driftdetection.HDDM_A_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_A_Test.updateEstimations().
FloatOption moa.classifiers.core.driftdetection.HDDM_A_Test.warningConfidenceOption
Initial value:
 new FloatOption("warningConfidence", 'w',
            "Confidence to the warning",
            0.005, 0, 1)
Definition at line 54 of file HDDM_A_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_A_Test.input().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/HDDM_A_Test.java