MOA: moa.tasks.AbstractTask Class Reference
moa.tasks.AbstractTask Class Reference
Abstract Task.
Public Member Functions
String getTaskName ()
Gets the name of this task.
Object doTask ()
This method performs this task, when TaskMonitor and ObjectRepository are no needed.
Object doTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Member Functions
abstract Object doTaskImpl (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Detailed Description
Abstract Task.
All runnable tasks in MOA extend this class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 31 of file AbstractTask.java.
Member Function Documentation
Object moa.tasks.AbstractTask.doTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
AbstractTask implements this method so all its extensions only need to implement doTaskImpl
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.Task.
Definition at line 49 of file AbstractTask.java.
References moa.options.AbstractOptionHandler.classOptionNamesToPreparedObjects, moa.tasks.AbstractTask.doTaskImpl(), moa.tasks.AbstractTask.getTaskName(), moa.options.AbstractOptionHandler.prepareClassOptions(), moa.tasks.TaskMonitor.setCurrentActivity(), and moa.tasks.TaskMonitor.taskShouldAbort().
{
        monitor.setCurrentActivity("Preparing options to " + getTaskName()
                + "...", -1.0);
        prepareClassOptions(monitor, repository);
        if (monitor.taskShouldAbort()) {
            return null;
        }
        monitor.setCurrentActivity("Doing task " + getTaskName() + "...", -1.0);
        Object result = doTaskImpl(monitor, repository);
        monitor.setCurrentActivity("Task " + getTaskName() + " complete.", 1.0);
        this.classOptionNamesToPreparedObjects = null; // clean up refs
        return result;
    }
Object moa.tasks.AbstractTask.doTask ()
This method performs this task, when TaskMonitor and ObjectRepository are no needed.
Returns:
an object with the result of this task
Implements moa.tasks.Task.
Definition at line 44 of file AbstractTask.java.
{
        return doTask(new NullMonitor(), null);
    }
abstract Object moa.tasks.AbstractTask.doTaskImpl (TaskMonitor monitor, ObjectRepository repository) [protected, pure virtual]
This method performs this task.
AbstractTask implements doTask so all its extensions only need to implement doTaskImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implemented in moa.tasks.CacheShuffledStream, and moa.tasks.MainTask.
Referenced by moa.tasks.AbstractTask.doTask().
void moa.tasks.AbstractTask.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 82 of file AbstractTask.java.
{
        // TODO Auto-generated method stub
    }
String moa.tasks.AbstractTask.getTaskName ()
Gets the name of this task.
Returns:
the name of this task
Definition at line 39 of file AbstractTask.java.
Referenced by moa.tasks.AbstractTask.doTask(), and moa.tasks.MainTask.doTaskImpl().
{
        return this.getClass().getSimpleName();
    }
void moa.tasks.AbstractTask.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 76 of file AbstractTask.java.
{
        // tasks prepare themselves upon running
    }
The documentation for this class was generated from the following file:
main/java/moa/tasks/AbstractTask.java