MOA: moa.classifiers.multilabel.MajorityLabelset Class Reference
moa.classifiers.multilabel.MajorityLabelset Class Reference
Majority Labelset classifier.
Public Member Functions
void setModelContext (InstancesHeader raw_header)
Sets the reference to the header of the data stream.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance x)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance x)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Protected Member Functions
void updateCount (Instance x, int L)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Static Private Member Functions
static final String toBitString (Instance ins, int c)
Private Attributes
int m_L = -1
double maxValue = 0.0
double prediction [] = null
HashMap< String, Double > classFreqs = new HashMap<String, Double>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Majority Labelset classifier.
Each labelset combination of relevances, e.g. [0,0,1,1,0,0], is treated as a single class value.
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
Revision
1
Definition at line 35 of file MajorityLabelset.java.
Member Function Documentation
void moa.classifiers.multilabel.MajorityLabelset.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 115 of file MajorityLabelset.java.
{
    }
Measurement [] moa.classifiers.multilabel.MajorityLabelset.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 105 of file MajorityLabelset.java.
{
        return new Measurement[]{};
    }
double [] moa.classifiers.multilabel.MajorityLabelset.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 93 of file MajorityLabelset.java.
References moa.classifiers.multilabel.MajorityLabelset.m_L, and moa.classifiers.multilabel.MajorityLabelset.prediction.
{
        int L = x.classIndex() + 1;
        if (m_L != L) {
            System.err.println("set L = " + L);
            m_L = L;
            prediction = new double[m_L];
        }
        return prediction;
        //System.out.println("getVotesForInstance(): "+x.classIndex());
    }
boolean moa.classifiers.multilabel.MajorityLabelset.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 110 of file MajorityLabelset.java.
{
        return false;
    }
void moa.classifiers.multilabel.MajorityLabelset.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 84 of file MajorityLabelset.java.
{
    }
void moa.classifiers.multilabel.MajorityLabelset.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 76 of file MajorityLabelset.java.
References moa.classifiers.multilabel.MajorityLabelset.m_L, moa.classifiers.AbstractClassifier.modelContext, and moa.classifiers.multilabel.MajorityLabelset.prediction.
{
        //set the multilabel model context
        this.modelContext = raw_header;
        m_L = raw_header.classIndex() + 1;
        prediction = new double[m_L];
    }
static final String moa.classifiers.multilabel.MajorityLabelset.toBitString (Instance ins, int c) [static, private]
Definition at line 48 of file MajorityLabelset.java.
Referenced by moa.classifiers.multilabel.MajorityLabelset.updateCount().
{
        StringBuilder sb = new StringBuilder(c);
        for (int i = 0; i < c; i++) {
            sb.append((int) Math.round(ins.value(i)));
        }
        return sb.toString();
    }
void moa.classifiers.multilabel.MajorityLabelset.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 88 of file MajorityLabelset.java.
References moa.classifiers.multilabel.MajorityLabelset.m_L, and moa.classifiers.multilabel.MajorityLabelset.updateCount().
{
        updateCount(x, m_L);
    }
void moa.classifiers.multilabel.MajorityLabelset.updateCount (Instance x, int L) [protected]
Definition at line 56 of file MajorityLabelset.java.
References moa.classifiers.multilabel.MajorityLabelset.classFreqs, moa.classifiers.multilabel.MajorityLabelset.maxValue, moa.classifiers.multilabel.MajorityLabelset.prediction, and moa.classifiers.multilabel.MajorityLabelset.toBitString().
Referenced by moa.classifiers.multilabel.MajorityLabelset.trainOnInstanceImpl().
{
        String y = toBitString(x, L);
        if (classFreqs.containsKey(y)) {
            double freq = classFreqs.get(y) + x.weight();
            classFreqs.put(y, freq);
            if (freq >= maxValue) {
                maxValue = freq;
                this.prediction = new double[L];
                for (int j = 0; j < L; j++) {
                    this.prediction[j] = x.value(j);
                }
            }
        } else {
            classFreqs.put(y, x.weight());
        }
    }
Member Data Documentation
HashMap<String, Double> moa.classifiers.multilabel.MajorityLabelset.classFreqs = new HashMap<String, Double>() [private]
Definition at line 45 of file MajorityLabelset.java.
Referenced by moa.classifiers.multilabel.MajorityLabelset.updateCount().
int moa.classifiers.multilabel.MajorityLabelset.m_L = -1 [private]
Definition at line 39 of file MajorityLabelset.java.
Referenced by moa.classifiers.multilabel.MajorityLabelset.getVotesForInstance(), moa.classifiers.multilabel.MajorityLabelset.setModelContext(), and moa.classifiers.multilabel.MajorityLabelset.trainOnInstanceImpl().
double moa.classifiers.multilabel.MajorityLabelset.maxValue = 0.0 [private]
Definition at line 41 of file MajorityLabelset.java.
Referenced by moa.classifiers.multilabel.MajorityLabelset.updateCount().
double moa.classifiers.multilabel.MajorityLabelset.prediction[] = null [private]
Definition at line 43 of file MajorityLabelset.java.
Referenced by moa.classifiers.multilabel.MajorityLabelset.getVotesForInstance(), moa.classifiers.multilabel.MajorityLabelset.setModelContext(), and moa.classifiers.multilabel.MajorityLabelset.updateCount().
final long moa.classifiers.multilabel.MajorityLabelset.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 37 of file MajorityLabelset.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/MajorityLabelset.java