MOA: moa.classifiers.trees.ORTO.InnerNode Class Reference
moa.classifiers.trees.ORTO.InnerNode Class Reference
Public Member Functions
InnerNode (int id)
int numChildren ()
Node getChild (int index)
int getChildIndex (Node child)
void setChild (int index, Node child)
void setAlternateTree (Node tree)
Node getAlternateTree ()
int calcByteSize ()
void calculateDetph (ORTO tree)
boolean PageHinckleyTest (double error, double threshold)
Check to see if the tree needs updating.
void setAdaptable (boolean value)
void setAlternate (boolean value)
Protected Attributes
AutoExpandVector< Node > children = new AutoExpandVector<Node>()
double PHmT = 0
double PHMT = Double.MAX_VALUE
DoubleVector lossStatistics = new DoubleVector()
int weightSeen = 0
int previousWeight = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 320 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.InnerNode.InnerNode (int id)
Definition at line 334 of file ORTO.java.
{
            super(id);
        }
Member Function Documentation
int moa.classifiers.trees.ORTO.InnerNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 362 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
{
            return (int) SizeOf.fullSizeOf(this) + (int) SizeOf.fullSizeOf(children);
        }
void moa.classifiers.trees.ORTO.InnerNode.calculateDetph (ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 366 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.Node.getLevel(), and moa.classifiers.trees.ORTO.maxDepth.
{
            if (this.getLevel() > tree.maxDepth) {
                tree.maxDepth = this.getLevel();
            }
            for (Node child : children) {
                child.calculateDetph(tree);
            }
        }
Node moa.classifiers.trees.ORTO.InnerNode.getAlternateTree ()
Definition at line 358 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.alternateTree.
{
            return this.alternateTree;
        }
Node moa.classifiers.trees.ORTO.InnerNode.getChild (int index)
Definition at line 342 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.OptionNode.getPrediction(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.removeExcessTrees().
{
            return this.children.get(index);
        }
int moa.classifiers.trees.ORTO.InnerNode.getChildIndex (Node child)
Definition at line 346 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.findWorstOption(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.removeExcessTrees().
{
            return this.children.indexOf(child);
        }
int moa.classifiers.trees.ORTO.InnerNode.numChildren ()
Definition at line 338 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance().
{
            return this.children.size();
        }
boolean moa.classifiers.trees.ORTO.InnerNode.PageHinckleyTest (double error, double threshold)
Check to see if the tree needs updating.
Definition at line 379 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.PHMT, and moa.classifiers.trees.ORTO.InnerNode.PHmT.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
        {
            // Update the cumulative mT sum
            PHmT += error;
            // Update the minimum mT value if the new mT is
            // smaller than the current minimum
            if(PHmT < PHMT)
            {
                PHMT = PHmT;
            }
            // Return true if the cumulative value - the current minimum is
            // greater than the current threshold (in which case we should adapt)
            return PHmT - PHMT > threshold;
        }
void moa.classifiers.trees.ORTO.InnerNode.setAdaptable (boolean value)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 395 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Adaptable, and moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
{
            Adaptable = value;
            for (Node child : children) {
                child.setAdaptable(value);
            }
        }
void moa.classifiers.trees.ORTO.InnerNode.setAlternate (boolean value)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 403 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Alternate, and moa.classifiers.trees.ORTO.InnerNode.children.
{
            Alternate = value;
            for (Node child : children) {
                child.setAlternate(value);
            }
        }
void moa.classifiers.trees.ORTO.InnerNode.setAlternateTree (Node tree)
Definition at line 354 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.alternateTree.
{
            this.alternateTree = tree;
        }
void moa.classifiers.trees.ORTO.InnerNode.setChild (int index, Node child)
Reimplemented in moa.classifiers.trees.ORTO.SplitNode.
Definition at line 350 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.removeExcessTrees().
{
            this.children.set(index, child);
        }
Member Data Documentation
AutoExpandVector<Node> moa.classifiers.trees.ORTO.InnerNode.children = new AutoExpandVector<Node>() [protected]
Definition at line 323 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.InnerNode.calcByteSize(), moa.classifiers.trees.ORTO.InnerNode.calculateDetph(), moa.classifiers.trees.ORTO.OptionNode.directionForBestTree(), moa.classifiers.trees.ORTO.InnerNode.getChild(), moa.classifiers.trees.ORTO.InnerNode.getChildIndex(), moa.classifiers.trees.ORTO.OptionNode.getNumSubtrees(), moa.classifiers.trees.ORTO.SplitNode.getNumSubtrees(), moa.classifiers.trees.ORTO.OptionNode.getPrediction(), moa.classifiers.trees.ORTO.SplitNode.getPrediction(), moa.classifiers.trees.ORTO.InnerNode.numChildren(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), moa.classifiers.trees.ORTO.OptionNode.resetFF(), moa.classifiers.trees.ORTO.InnerNode.setAdaptable(), moa.classifiers.trees.ORTO.InnerNode.setAlternate(), moa.classifiers.trees.ORTO.SplitNode.setChild(), and moa.classifiers.trees.ORTO.InnerNode.setChild().
DoubleVector moa.classifiers.trees.ORTO.InnerNode.lossStatistics = new DoubleVector() [protected]
Definition at line 329 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
double moa.classifiers.trees.ORTO.InnerNode.PHMT = Double.MAX_VALUE [protected]
Definition at line 326 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.InnerNode.PageHinckleyTest().
double moa.classifiers.trees.ORTO.InnerNode.PHmT = 0 [protected]
Definition at line 325 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.InnerNode.PageHinckleyTest().
int moa.classifiers.trees.ORTO.InnerNode.previousWeight = 0 [protected]
Definition at line 332 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
final long moa.classifiers.trees.ORTO.InnerNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.ORTO.Node.
Reimplemented in moa.classifiers.trees.ORTO.SplitNode, and moa.classifiers.trees.ORTO.OptionNode.
Definition at line 321 of file ORTO.java.
int moa.classifiers.trees.ORTO.InnerNode.weightSeen = 0 [protected]
Definition at line 331 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java