MOA: moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode Class Reference
moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode Class Reference
Public Member Functions
RandomLearningNode (double[] initialClassObservations)
void learnFromInstance (Instance inst, HoeffdingTree ht)
Protected Attributes
int[] listAttributes
int numAttributes
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 42 of file RandomHoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.RandomLearningNode (double[] initialClassObservations)
Definition at line 50 of file RandomHoeffdingTree.java.
{
            super(initialClassObservations);
        }
Member Function Documentation
void moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance (Instance inst, HoeffdingTree ht)
Reimplemented in moa.classifiers.trees.RandomHoeffdingTree.LearningNodeNBAdaptive.
Definition at line 55 of file RandomHoeffdingTree.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.listAttributes, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.HoeffdingTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingTree.newNumericClassObserver(), moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.numAttributes, and moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass().
{
            this.observedClassDistribution.addToValue((int) inst.classValue(),
                    inst.weight());
            if (this.listAttributes == null) {
                this.numAttributes = (int) Math.floor(Math.sqrt(inst.numAttributes()));
                this.listAttributes = new int[this.numAttributes];
                for (int j = 0; j < this.numAttributes; j++) {
                    boolean isUnique = false;
                    while (isUnique == false) {
                        this.listAttributes[j] = ht.classifierRandom.nextInt(inst.numAttributes() - 1);
                        isUnique = true;
                        for (int i = 0; i < j; i++) {
                            if (this.listAttributes[j] == this.listAttributes[i]) {
                                isUnique = false;
                                break;
                            }
                        }
                    }
                }
            }
            for (int j = 0; j < this.numAttributes - 1; j++) {
                int i = this.listAttributes[j];
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? ht.newNominalClassObserver() : ht.newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
                obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
            }
        }
Member Data Documentation
int [] moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.listAttributes [protected]
Definition at line 46 of file RandomHoeffdingTree.java.
Referenced by moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance().
int moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.numAttributes [protected]
Definition at line 48 of file RandomHoeffdingTree.java.
Referenced by moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance().
final long moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.trees.RandomHoeffdingTree.LearningNodeNB, and moa.classifiers.trees.RandomHoeffdingTree.LearningNodeNBAdaptive.
Definition at line 44 of file RandomHoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/RandomHoeffdingTree.java