MOA: moa.gui.PreviewPanel Class Reference
moa.gui.PreviewPanel Class Reference
This panel displays the running task preview text and buttons.
Public Types
enum TypePanel { CLASSIFICATION = (new Accuracy()), REGRESSION = (new RegressionAccuracy()), CONCEPT_DRIFT = (new ChangeDetectionMeasures()) }
Public Member Functions
PreviewPanel ()
PreviewPanel (TypePanel typePanel)
PreviewPanel (TypePanel typePanel, CDTaskManagerPanel taskManagerPanel)
void refresh ()
void setTaskThreadToPreview (TaskThread thread)
void setLatestPreview (Object preview)
void updateAutoRefreshTimer ()
void disableRefresh ()
void enableRefresh ()
void latestPreviewChanged ()
This method is used to receive a signal from TaskMonitor that the lastest preview has changed.
Static Public Attributes
static final String[] autoFreqStrings
static final int[] autoFreqTimeSecs = {0, 1, 5, 10, 30, 60}
Protected Attributes
TaskThread previewedThread
JLabel previewLabel = new JLabel("No preview available")
JButton refreshButton = new JButton("Refresh")
JLabel autoRefreshLabel = new JLabel("Auto refresh: ")
JComboBox autoRefreshComboBox = new JComboBox(autoFreqStrings)
TaskTextViewerPanel textViewerPanel
javax.swing.Timer autoRefreshTimer
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays the running task preview text and buttons.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file PreviewPanel.java.
Member Enumeration Documentation
enum moa::gui::PreviewPanel::TypePanel
Enumerator:
CLASSIFICATION
REGRESSION
CONCEPT_DRIFT
Definition at line 70 of file PreviewPanel.java.
{
        CLASSIFICATION(new Accuracy()),
        REGRESSION(new RegressionAccuracy()),
        CONCEPT_DRIFT(new ChangeDetectionMeasures());
        private final MeasureCollection measureCollection;
        //Constructor
        TypePanel(MeasureCollection measureCollection){
            this.measureCollection = measureCollection;
        }
        public MeasureCollection getMeasureCollection(){
            return (MeasureCollection) this.measureCollection.copy();
        }
    }
Constructor & Destructor Documentation
moa.gui.PreviewPanel.PreviewPanel ()
Definition at line 85 of file PreviewPanel.java.
{
        this(TypePanel.CLASSIFICATION, null);
    }
moa.gui.PreviewPanel.PreviewPanel (TypePanel typePanel)
Definition at line 89 of file PreviewPanel.java.
{
        this(typePanel, null);
    }
moa.gui.PreviewPanel.PreviewPanel (TypePanel typePanel, CDTaskManagerPanel taskManagerPanel)
Definition at line 93 of file PreviewPanel.java.
References moa.gui.PreviewPanel.autoRefreshComboBox, moa.gui.PreviewPanel.autoRefreshLabel, moa.gui.PreviewPanel.autoRefreshTimer, moa.gui.PreviewPanel.previewLabel, moa.gui.PreviewPanel.refresh(), moa.gui.PreviewPanel.refreshButton, moa.gui.PreviewPanel.setTaskThreadToPreview(), moa.gui.PreviewPanel.textViewerPanel, and moa.gui.PreviewPanel.updateAutoRefreshTimer().
{
        this.textViewerPanel = new TaskTextViewerPanel(typePanel,taskManagerPanel);
        this.autoRefreshComboBox.setSelectedIndex(1); // default to 1 sec
        JPanel controlPanel = new JPanel();
        controlPanel.add(this.previewLabel);
        controlPanel.add(this.refreshButton);
        controlPanel.add(this.autoRefreshLabel);
        controlPanel.add(this.autoRefreshComboBox);
        setLayout(new BorderLayout());
        add(controlPanel, BorderLayout.NORTH);
        add(this.textViewerPanel, BorderLayout.CENTER);
        this.refreshButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                refresh();
            }
        });
        this.autoRefreshTimer = new javax.swing.Timer(1000,
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        refresh();
                    }
                });
        this.autoRefreshComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                updateAutoRefreshTimer();
            }
        });
        setTaskThreadToPreview(null);
    }
Member Function Documentation
void moa.gui.PreviewPanel.disableRefresh ()
Definition at line 185 of file PreviewPanel.java.
References moa.gui.PreviewPanel.autoRefreshComboBox, moa.gui.PreviewPanel.autoRefreshLabel, moa.gui.PreviewPanel.autoRefreshTimer, and moa.gui.PreviewPanel.refreshButton.
Referenced by moa.gui.PreviewPanel.refresh(), moa.gui.PreviewPanel.setLatestPreview(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        this.refreshButton.setEnabled(false);
        this.autoRefreshLabel.setEnabled(false);
        this.autoRefreshComboBox.setEnabled(false);
        this.autoRefreshTimer.stop();
    }
void moa.gui.PreviewPanel.enableRefresh ()
Definition at line 192 of file PreviewPanel.java.
References moa.gui.PreviewPanel.autoRefreshComboBox, moa.gui.PreviewPanel.autoRefreshLabel, moa.gui.PreviewPanel.refreshButton, and moa.gui.PreviewPanel.updateAutoRefreshTimer().
Referenced by moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        this.refreshButton.setEnabled(true);
        this.autoRefreshLabel.setEnabled(true);
        this.autoRefreshComboBox.setEnabled(true);
        updateAutoRefreshTimer();
    }
void moa.gui.PreviewPanel.latestPreviewChanged ()
This method is used to receive a signal from TaskMonitor that the lastest preview has changed.
This method is implemented in PreviewPanel to change the results that are shown in its panel.
Implements moa.tasks.ResultPreviewListener.
Definition at line 200 of file PreviewPanel.java.
References moa.gui.PreviewPanel.previewedThread, and moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        setTaskThreadToPreview(this.previewedThread);
    }
void moa.gui.PreviewPanel.refresh ()
Definition at line 129 of file PreviewPanel.java.
References moa.gui.PreviewPanel.disableRefresh(), moa.tasks.TaskThread.getPreview(), moa.tasks.TaskThread.isComplete(), moa.gui.PreviewPanel.previewedThread, and moa.gui.PreviewPanel.setLatestPreview().
Referenced by moa.gui.PreviewPanel.PreviewPanel().
{
        if (this.previewedThread != null) {
            if (this.previewedThread.isComplete()) {
                setLatestPreview(null);
                disableRefresh();
            } else {
                this.previewedThread.getPreview(PreviewPanel.this);
            }
        }
    }
void moa.gui.PreviewPanel.setLatestPreview (Object preview)
Definition at line 151 of file PreviewPanel.java.
References moa.gui.PreviewPanel.disableRefresh(), moa.tasks.TaskThread.getFinalResult(), moa.tasks.TaskThread.getLatestPreviewGrabTimeSeconds(), moa.tasks.TaskThread.isComplete(), moa.gui.PreviewPanel.previewedThread, moa.gui.PreviewPanel.previewLabel, moa.gui.TaskTextViewerPanel.setText(), and moa.gui.PreviewPanel.textViewerPanel.
Referenced by moa.gui.PreviewPanel.refresh(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        if ((this.previewedThread != null) && this.previewedThread.isComplete()) {
            this.previewLabel.setText("Final result");
            Object finalResult = this.previewedThread.getFinalResult();
            this.textViewerPanel.setText(finalResult != null ? finalResult.toString() : null);
            disableRefresh();
        } else {
            double grabTime = this.previewedThread != null ? this.previewedThread.getLatestPreviewGrabTimeSeconds()
                    : 0.0;
            String grabString = grabTime > 0.0 ? (" ("
                    + StringUtils.secondsToDHMSString(grabTime) + ")") : "";
            this.textViewerPanel.setText(preview != null ? preview.toString()
                    : null);
            if (preview == null) {
                this.previewLabel.setText("No preview available" + grabString);
            } else {
                this.previewLabel.setText("Preview" + grabString);
            }
        }
    }
void moa.gui.PreviewPanel.setTaskThreadToPreview (TaskThread thread)
Definition at line 140 of file PreviewPanel.java.
References moa.gui.PreviewPanel.disableRefresh(), moa.gui.PreviewPanel.enableRefresh(), moa.tasks.TaskThread.getLatestResultPreview(), moa.tasks.TaskThread.isComplete(), moa.gui.PreviewPanel.previewedThread, and moa.gui.PreviewPanel.setLatestPreview().
Referenced by moa.gui.PreviewPanel.latestPreviewChanged(), moa.gui.PreviewPanel.PreviewPanel(), moa.gui.TaskManagerPanel.taskSelectionChanged(), moa.gui.RegressionTaskManagerPanel.taskSelectionChanged(), and moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged().
{
        this.previewedThread = thread;
        setLatestPreview(thread != null ? thread.getLatestResultPreview()
                : null);
        if (thread == null) {
            disableRefresh();
        } else if (!thread.isComplete()) {
            enableRefresh();
        }
    }
void moa.gui.PreviewPanel.updateAutoRefreshTimer ()
Definition at line 172 of file PreviewPanel.java.
References moa.gui.PreviewPanel.autoFreqTimeSecs, moa.gui.PreviewPanel.autoRefreshComboBox, and moa.gui.PreviewPanel.autoRefreshTimer.
Referenced by moa.gui.PreviewPanel.enableRefresh(), and moa.gui.PreviewPanel.PreviewPanel().
{
        int autoDelay = autoFreqTimeSecs[this.autoRefreshComboBox.getSelectedIndex()];
        if (autoDelay > 0) {
            if (this.autoRefreshTimer.isRunning()) {
                this.autoRefreshTimer.stop();
            }
            this.autoRefreshTimer.setDelay(autoDelay * 1000);
            this.autoRefreshTimer.start();
        } else {
            this.autoRefreshTimer.stop();
        }
    }
Member Data Documentation
final String [] moa.gui.PreviewPanel.autoFreqStrings [static]
Initial value:
 {"never", "every second",
        "every 5 seconds", "every 10 seconds", "every 30 seconds",
        "every minute"}
Definition at line 50 of file PreviewPanel.java.
final int [] moa.gui.PreviewPanel.autoFreqTimeSecs = {0, 1, 5, 10, 30, 60} [static]
Definition at line 54 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.updateAutoRefreshTimer().
JComboBox moa.gui.PreviewPanel.autoRefreshComboBox = new JComboBox(autoFreqStrings) [protected]
Definition at line 64 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.disableRefresh(), moa.gui.PreviewPanel.enableRefresh(), moa.gui.PreviewPanel.PreviewPanel(), and moa.gui.PreviewPanel.updateAutoRefreshTimer().
JLabel moa.gui.PreviewPanel.autoRefreshLabel = new JLabel("Auto refresh: ") [protected]
Definition at line 62 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.disableRefresh(), moa.gui.PreviewPanel.enableRefresh(), and moa.gui.PreviewPanel.PreviewPanel().
javax.swing.Timer moa.gui.PreviewPanel.autoRefreshTimer [protected]
Definition at line 68 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.disableRefresh(), moa.gui.PreviewPanel.PreviewPanel(), and moa.gui.PreviewPanel.updateAutoRefreshTimer().
TaskThread moa.gui.PreviewPanel.previewedThread [protected]
Definition at line 56 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.latestPreviewChanged(), moa.gui.PreviewPanel.refresh(), moa.gui.PreviewPanel.setLatestPreview(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
JLabel moa.gui.PreviewPanel.previewLabel = new JLabel("No preview available") [protected]
Definition at line 58 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.PreviewPanel(), and moa.gui.PreviewPanel.setLatestPreview().
JButton moa.gui.PreviewPanel.refreshButton = new JButton("Refresh") [protected]
Definition at line 60 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.disableRefresh(), moa.gui.PreviewPanel.enableRefresh(), and moa.gui.PreviewPanel.PreviewPanel().
final long moa.gui.PreviewPanel.serialVersionUID = 1L [static, private]
Definition at line 48 of file PreviewPanel.java.
TaskTextViewerPanel moa.gui.PreviewPanel.textViewerPanel [protected]
Definition at line 66 of file PreviewPanel.java.
Referenced by moa.gui.PreviewPanel.PreviewPanel(), and moa.gui.PreviewPanel.setLatestPreview().
The documentation for this class was generated from the following file:
main/java/moa/gui/PreviewPanel.java