MOA: moa.classifiers.rules.AbstractAMRules Class Reference
moa.classifiers.rules.AbstractAMRules Class Reference
Public Member Functions
AbstractAMRules ()
abstract boolean isRandomizable ()
description of the Methods used.
void trainOnInstanceImpl (Instance instance)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance instance)
getVotesForInstance extension of the instance method getVotesForInstance in moa.classifier.java returns the prediction of the instance.
void getModelDescription (StringBuilder out, int indent)
print GUI learn model
void PrintRuleSet ()
abstract RuleActiveLearningNode newRuleActiveLearningNode (Builder builder)
abstract RuleActiveLearningNode newRuleActiveLearningNode (double[] initialClassObservations)
int getModelAttIndexToInstanceAttIndex (int index, Instance inst)
void resetLearningImpl ()
Resets this classifier.
abstract ErrorWeightedVote newErrorWeightedVote ()
Static Public Member Functions
static int modelAttIndexToInstanceAttIndex (int index, Instance inst)
Gets the index of the attribute in the instance, given the index of the attribute in the learner.
Public Attributes
FloatOption splitConfidenceOption
FloatOption tieThresholdOption
IntOption gracePeriodOption
FlagOption DriftDetectionOption
FloatOption pageHinckleyAlphaOption
IntOption pageHinckleyThresholdOption
FlagOption noAnomalyDetectionOption
FloatOption multivariateAnomalyProbabilityThresholdOption
FloatOption univariateAnomalyprobabilityThresholdOption
IntOption anomalyNumInstThresholdOption
FlagOption unorderedRulesOption
IntOption VerbosityOption
ClassOption numericObserverOption
Static Public Attributes
static final double NORMAL_CONSTANT = Math.sqrt(2 * Math.PI)
Protected Member Functions
abstract Rule newRule (int ID, RuleActiveLearningNode learningNode, double[] statistics)
Rule.Builder() to build an object with the parameters.
Measurement[] getModelMeasurementsImpl ()
print GUI evaluate model
void debug (String string, int level)
Print to console.
void VerboseToConsole (Instance inst)
Protected Attributes
RuleSet ruleSet = new RuleSet()
Rule defaultRule
int ruleNumberID
double[] statistics
Private Member Functions
boolean isAnomaly (Instance instance, Rule rule)
Method to verify if the instance is an anomaly.
Private Attributes
int numChangesDetected
AMRules Algorithm.
int numAnomaliesDetected
int numInstances
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 53 of file AbstractAMRules.java.
Constructor & Destructor Documentation
moa.classifiers.rules.AbstractAMRules.AbstractAMRules ()
Definition at line 116 of file AbstractAMRules.java.
{
        super();
    }
Member Function Documentation
void moa.classifiers.rules.AbstractAMRules.debug (String string, int level) [protected]
Print to console.
Parameters:
string
Definition at line 353 of file AbstractAMRules.java.
References moa.options.IntOption.getValue(), and moa.classifiers.rules.AbstractAMRules.VerbosityOption.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance(), moa.classifiers.rules.AbstractAMRules.PrintRuleSet(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        if (VerbosityOption.getValue()>=level){
            System.out.println(string);
        }
    }
int moa.classifiers.rules.AbstractAMRules.getModelAttIndexToInstanceAttIndex (int index, Instance inst)
Definition at line 386 of file AbstractAMRules.java.
References moa.classifiers.rules.AbstractAMRules.modelAttIndexToInstanceAttIndex().
{
        return modelAttIndexToInstanceAttIndex(index, inst);
    }
void moa.classifiers.rules.AbstractAMRules.getModelDescription (StringBuilder out, int indent) [virtual]
print GUI learn model
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.rules.AMRulesRegressor.
Definition at line 322 of file AbstractAMRules.java.
References moa.classifiers.rules.AbstractAMRules.DriftDetectionOption, moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.noAnomalyDetectionOption, moa.classifiers.rules.AbstractAMRules.ruleSet, and moa.classifiers.rules.AbstractAMRules.unorderedRulesOption.
{
        indent=0;
        if(!this.unorderedRulesOption.isSet()){
            StringUtils.appendIndented(out, indent, "Method Ordered");
            StringUtils.appendNewline(out);
        }else{
            StringUtils.appendIndented(out, indent, "Method Unordered");
            StringUtils.appendNewline(out);
        }
        if(this.DriftDetectionOption.isSet()){
            StringUtils.appendIndented(out, indent, "Change Detection OFF");
            StringUtils.appendNewline(out);
        }else{
            StringUtils.appendIndented(out, indent, "Change Detection ON");
            StringUtils.appendNewline(out);
        }
        if(this.noAnomalyDetectionOption.isSet()){
            StringUtils.appendIndented(out, indent, "Anomaly Detection OFF");
            StringUtils.appendNewline(out);
        }else{
            StringUtils.appendIndented(out, indent, "Anomaly Detection ON");
            StringUtils.appendNewline(out);
        }
        StringUtils.appendIndented(out, indent, "Number of Rules: " + (this.ruleSet.size()+1));
        StringUtils.appendNewline(out);
    }
Measurement [] moa.classifiers.rules.AbstractAMRules.getModelMeasurementsImpl () [protected, virtual]
print GUI evaluate model
Implements moa.classifiers.AbstractClassifier.
Definition at line 311 of file AbstractAMRules.java.
References moa.classifiers.rules.AbstractAMRules.numAnomaliesDetected, moa.classifiers.rules.AbstractAMRules.numChangesDetected, and moa.classifiers.rules.AbstractAMRules.ruleSet.
{
        return new Measurement[]{
                new Measurement("anomaly detections", this.numAnomaliesDetected),
                new Measurement("change detections", this.numChangesDetected),
                new Measurement("rules (number)", this.ruleSet.size()+1)};
    }
double [] moa.classifiers.rules.AbstractAMRules.getVotesForInstance (Instance instance)
getVotesForInstance extension of the instance method getVotesForInstance in moa.classifier.java returns the prediction of the instance.
Called in EvaluateModelRegression
Implements moa.classifiers.Classifier.
Definition at line 270 of file AbstractAMRules.java.
References moa.classifiers.rules.core.voting.ErrorWeightedVote.addVote(), moa.classifiers.rules.core.voting.ErrorWeightedVote.computeWeightedVote(), moa.classifiers.rules.AbstractAMRules.debug(), moa.classifiers.rules.AbstractAMRules.defaultRule, moa.classifiers.rules.core.Rule.getCurrentError(), moa.classifiers.rules.core.Rule.getPrediction(), moa.classifiers.rules.core.voting.ErrorWeightedVote.getWeightedError(), moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.newErrorWeightedVote(), moa.classifiers.rules.AbstractAMRules.ruleSet, moa.classifiers.rules.AbstractAMRules.unorderedRulesOption, and moa.classifiers.rules.AbstractAMRules.VerboseToConsole().
{
        ErrorWeightedVote errorWeightedVote=newErrorWeightedVote();
        //DoubleVector combinedVote = new DoubleVector();
        debug("Test",3);
        int numberOfRulesCovering = 0;
        VerboseToConsole(instance); // Verbose to console Dataset name.
        for (Rule rule: ruleSet) {
            if (rule.isCovering(instance) == true){
                numberOfRulesCovering++;
                //DoubleVector vote = new DoubleVector(rule.getPrediction(instance));
                double [] vote=rule.getPrediction(instance);
                double error= rule.getCurrentError();
                debug("Rule No"+ rule.getRuleNumberID() + " Vote: " + Arrays.toString(vote) + " Error: " + error + " Y: " + instance.classValue(),3); //predictionValueForThisRule);
                errorWeightedVote.addVote(vote,error);
                //combinedVote.addValues(vote);
                if (!this.unorderedRulesOption.isSet()) { // Ordered Rules Option.
                    break; // Only one rule cover the instance.
                }
            }
        }
        if (numberOfRulesCovering == 0) {
            //combinedVote = new DoubleVector(defaultRule.getPrediction(instance));
            double [] vote=defaultRule.getPrediction(instance);
            double error= defaultRule.getCurrentError();
            errorWeightedVote.addVote(vote,error);
            debug("Default Rule Vote " + Arrays.toString(vote) + " Error " + error + "  Y: " + instance.classValue(),3);
        }
        double[] weightedVote=errorWeightedVote.computeWeightedVote();
        double weightedError=errorWeightedVote.getWeightedError();
        debug("Weighted Rule - Vote: " + Arrays.toString(weightedVote) + " Weighted Error: " + weightedError + " Y:" + instance.classValue(),3);
        return weightedVote;
    }
boolean moa.classifiers.rules.AbstractAMRules.isAnomaly (Instance instance, Rule rule) [private]
Method to verify if the instance is an anomaly.
Parameters:
instance
rule
Returns:
Definition at line 249 of file AbstractAMRules.java.
References moa.classifiers.rules.AbstractAMRules.anomalyNumInstThresholdOption, moa.classifiers.rules.core.Rule.getInstancesSeen(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.rules.core.Rule.isAnomaly(), moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.multivariateAnomalyProbabilityThresholdOption, moa.classifiers.rules.AbstractAMRules.noAnomalyDetectionOption, and moa.classifiers.rules.AbstractAMRules.univariateAnomalyprobabilityThresholdOption.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        //AMRUles is equipped with anomaly detection. If on, compute the anomaly value.
        boolean isAnomaly = false;
        if (this.noAnomalyDetectionOption.isSet() == false){
            if (rule.getInstancesSeen() >= this.anomalyNumInstThresholdOption.getValue()) {
                isAnomaly = rule.isAnomaly(instance,
                        this.univariateAnomalyprobabilityThresholdOption.getValue(),
                        this.multivariateAnomalyProbabilityThresholdOption.getValue(),
                        this.anomalyNumInstThresholdOption.getValue());
            }
        }
        return isAnomaly;
    }
abstract boolean moa.classifiers.rules.AbstractAMRules.isRandomizable () [pure virtual]
description of the Methods used.
isRandomizable resetLearningImpl newRule // to build an object with the parameters. trainOnInstanceImpl isAnomaly getVotesForInstance getModelMeasurementsImpl getModelDescription // to printout to MOA GUI debug // use debug('string') to printout to console
Implements moa.classifiers.Classifier.
Implemented in moa.classifiers.rules.AMRulesRegressor.
static int moa.classifiers.rules.AbstractAMRules.modelAttIndexToInstanceAttIndex (int index, Instance inst) [static]
Gets the index of the attribute in the instance, given the index of the attribute in the learner.
Parameters:
index the index of the attribute in the learner
inst the instance
Returns:
the index in the instance
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 404 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelAttIndexToInstanceAttIndex().
{
        return  index<= inst.classIndex() ? index : index + 1;
    }
abstract ErrorWeightedVote moa.classifiers.rules.AbstractAMRules.newErrorWeightedVote () [pure virtual]
Implemented in moa.classifiers.rules.AMRulesRegressor.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
abstract Rule moa.classifiers.rules.AbstractAMRules.newRule (int ID, RuleActiveLearningNode learningNode, double[] statistics) [protected, pure virtual]
Rule.Builder() to build an object with the parameters.
If you have an algorithm with many parameters, especially if some of them are optional, it can be beneficial to define an object that represents all of the parameters.
Returns:
Implemented in moa.classifiers.rules.AMRulesRegressor.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
abstract RuleActiveLearningNode moa.classifiers.rules.AbstractAMRules.newRuleActiveLearningNode (double[] initialClassObservations) [pure virtual]
Implemented in moa.classifiers.rules.AMRulesRegressor.
abstract RuleActiveLearningNode moa.classifiers.rules.AbstractAMRules.newRuleActiveLearningNode (Builder builder) [pure virtual]
Implemented in moa.classifiers.rules.AMRulesRegressor.
Referenced by moa.classifiers.rules.core.Rule.newRuleActiveLearningNode().
void moa.classifiers.rules.AbstractAMRules.PrintRuleSet ()
Definition at line 372 of file AbstractAMRules.java.
References moa.classifiers.rules.AbstractAMRules.debug(), moa.classifiers.rules.AbstractAMRules.defaultRule, moa.classifiers.rules.core.Rule.printRule(), and moa.classifiers.rules.AbstractAMRules.ruleSet.
{
        debug("Rule in RuleSet:",2);
        for (Rule rule: ruleSet) {
            debug(rule.printRule(),2);
        }
        debug("Default rule :",2);
        debug(this.defaultRule.printRule(),2);
    }
void moa.classifiers.rules.AbstractAMRules.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.rules.AMRulesRegressor.
Definition at line 391 of file AbstractAMRules.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
AMRules Algorithm
For each rule in the rule set If rule covers the instance if the instance is not an anomaly Update Change Detection Tests Compute prediction error Call PHTest If change is detected then Remove rule Else Update sufficient statistics of rule If number of examples in rule > Nmin Expand rule If ordered set then break If none of the rule covers the instance Update sufficient statistics of default rule If number of examples in default rule is multiple of Nmin Expand default rule and add it to the set of rules Reset the default rule
Implements moa.classifiers.AbstractClassifier.
Definition at line 155 of file AbstractAMRules.java.
References moa.classifiers.rules.core.Rule.computeError(), moa.classifiers.rules.AbstractAMRules.debug(), moa.classifiers.rules.AbstractAMRules.defaultRule, moa.classifiers.rules.core.Rule.getInstancesSeen(), moa.classifiers.rules.core.Rule.getLearningNode(), moa.classifiers.rules.core.Rule.getRuleNumberID(), moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsOtherBranchSplit(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.rules.AbstractAMRules.gracePeriodOption, moa.classifiers.rules.AbstractAMRules.isAnomaly(), moa.classifiers.rules.core.Rule.isCovering(), moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.newRule(), moa.classifiers.rules.AbstractAMRules.numAnomaliesDetected, moa.classifiers.rules.AbstractAMRules.numChangesDetected, moa.classifiers.rules.AbstractAMRules.numInstances, moa.classifiers.rules.core.Rule.printRule(), moa.classifiers.rules.AbstractAMRules.ruleNumberID, moa.classifiers.rules.AbstractAMRules.ruleSet, moa.classifiers.rules.core.Rule.setRuleNumberID(), moa.classifiers.rules.core.Rule.split(), moa.classifiers.rules.AbstractAMRules.tieThresholdOption, moa.classifiers.rules.core.Rule.tryToExpand(), moa.classifiers.rules.AbstractAMRules.unorderedRulesOption, moa.classifiers.rules.core.RuleActiveLearningNode.updateChangeDetection(), and moa.classifiers.rules.core.Rule.updateStatistics().
{
        ++numInstances;
        debug("Train",3);
        debug("N instance "+numInstances + " - " + instance.toString(),3);
        boolean rulesCoveringInstance = false;
        Iterator<Rule> ruleIterator= this.ruleSet.iterator();
        while (ruleIterator.hasNext()) {
            Rule rule = ruleIterator.next();
            if (rule.isCovering(instance) == true) {
                rulesCoveringInstance = true;
                if (isAnomaly(instance, rule) == false) {
                    //Update Change Detection Tests
                    double error = rule.computeError(instance); //Use adaptive mode error
                    boolean changeDetected = rule.getLearningNode().updateChangeDetection(error);
                    if (changeDetected == true) {
                        debug("I) Drift Detected. Exa. : " +  this.numInstances + " (" + rule.getInstancesSeen() +") Remove Rule: " +rule.getRuleNumberID(),1);
                        ruleIterator.remove();
                        this.numChangesDetected++;  //Just for statistics
                    } else {
                        rule.updateStatistics(instance);
                        if (rule.getInstancesSeen()  % this.gracePeriodOption.getValue() == 0.0) {
                            if (rule.tryToExpand(this.splitConfidenceOption.getValue(), this.tieThresholdOption.getValue()) )
{
                                rule.split();
                                debug("Rule Expanded:",2);
                                debug(rule.printRule(),2);
                            }
                        }
                    }
                    if (!this.unorderedRulesOption.isSet())
                        break;
                }
                else {
                    debug("Anomaly Detected: " + this.numInstances + " Rule: " +rule.getRuleNumberID() ,1);
                    this.numAnomaliesDetected++;//Just for statistics
                }
            }
        }
        if (rulesCoveringInstance == false){
            defaultRule.updateStatistics(instance);
            if (defaultRule.getInstancesSeen() % this.gracePeriodOption.getValue() == 0.0) {
                debug("Nr. examples "+defaultRule.getInstancesSeen(), 4);
                if (defaultRule.tryToExpand(this.splitConfidenceOption.getValue(), this.tieThresholdOption.getValue()) == true) {
                    Rule newDefaultRule=newRule(defaultRule.getRuleNumberID(),defaultRule.getLearningNode(),defaultRule.getLearningNode().getStatisticsOtherBranchSplit()); //other branch
                    defaultRule.split();
                    defaultRule.setRuleNumberID(++ruleNumberID);
                    this.ruleSet.add(this.defaultRule);
                    debug("Default rule expanded! New Rule:",2);
                    debug(defaultRule.printRule(),2);
                    debug("New default rule:", 3);
                    debug(newDefaultRule.printRule(),3);
                    defaultRule=newDefaultRule;
                }
            }
        }
    }
void moa.classifiers.rules.AbstractAMRules.VerboseToConsole (Instance inst) [protected]
Definition at line 359 of file AbstractAMRules.java.
References moa.options.IntOption.getValue(), moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.unorderedRulesOption, and moa.classifiers.rules.AbstractAMRules.VerbosityOption.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
{
        if(VerbosityOption.getValue()>=5){
            System.out.println();
            System.out.println("I) Dataset: "+inst.dataset().relationName());
            if(!this.unorderedRulesOption.isSet()){
                System.out.println("I) Method Ordered");
            }else{
                System.out.println("I) Method Unordered");
            }
        }
    }
Member Data Documentation
IntOption moa.classifiers.rules.AbstractAMRules.anomalyNumInstThresholdOption
Initial value:
 new IntOption(
            "anomalyThreshold",
            'n',
            "The threshold value of anomalies to be used in the anomaly detection.",
            30, 0, Integer.MAX_VALUE)
Definition at line 96 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.isAnomaly().
Rule moa.classifiers.rules.AbstractAMRules.defaultRule [protected]
Definition at line 57 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance(), moa.classifiers.rules.AbstractAMRules.PrintRuleSet(), moa.classifiers.rules.AMRulesRegressor.resetLearningImpl(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
FlagOption moa.classifiers.rules.AbstractAMRules.DriftDetectionOption
Initial value:
 new FlagOption("DoNotDetectChanges", 'H',
            "Drift Detection. Page-Hinkley.")
Definition at line 72 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelDescription(), and moa.classifiers.rules.AMRulesRegressor.newRule().
IntOption moa.classifiers.rules.AbstractAMRules.gracePeriodOption
Initial value:
 new IntOption("gracePeriod",
            'g', "Hoeffding Bound Parameter. The number of instances a leaf should observe between split attempts.",
            200, 1, Integer.MAX_VALUE)
Definition at line 69 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.AbstractAMRules.multivariateAnomalyProbabilityThresholdOption
Initial value:
 new FloatOption(
            "multivariateAnomalyProbabilityThresholdd",
            'm',
            "Multivariate anomaly threshold value.",
            0.99, 0.0, 1.0)
Definition at line 86 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.isAnomaly().
FlagOption moa.classifiers.rules.AbstractAMRules.noAnomalyDetectionOption
Initial value:
 new FlagOption("noAnomalyDetection", 'A',
            "Disable anomaly Detection.")
Definition at line 84 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelDescription(), and moa.classifiers.rules.AbstractAMRules.isAnomaly().
final double moa.classifiers.rules.AbstractAMRules.NORMAL_CONSTANT = Math.sqrt(2 * Math.PI) [static]
Definition at line 60 of file AbstractAMRules.java.
int moa.classifiers.rules.AbstractAMRules.numAnomaliesDetected [private]
Definition at line 151 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelMeasurementsImpl(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
int moa.classifiers.rules.AbstractAMRules.numChangesDetected [private]
AMRules Algorithm.
Method for updating (training) the AMRules model using a new instance
Definition at line 150 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelMeasurementsImpl(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
ClassOption moa.classifiers.rules.AbstractAMRules.numericObserverOption
Initial value:
 new ClassOption("numericObserver",
            'z', "Numeric observer.",
            FIMTDDNumericAttributeClassLimitObserver.class,
            "FIMTDDNumericAttributeClassLimitObserver")
Definition at line 110 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver().
int moa.classifiers.rules.AbstractAMRules.numInstances [private]
Definition at line 152 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.AbstractAMRules.pageHinckleyAlphaOption
Initial value:
 new FloatOption(
            "pageHinckleyAlpha",
            'a',
            "The alpha value to use in the Page Hinckley change detection tests.",
            0.005, 0.0, 1.0)
Definition at line 74 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule().
IntOption moa.classifiers.rules.AbstractAMRules.pageHinckleyThresholdOption
Initial value:
 new IntOption(
            "pageHinckleyThreshold",
            'l',
            "The threshold value (Lambda) to be used in the Page Hinckley change detection tests.",
            35, 0, Integer.MAX_VALUE)
Definition at line 79 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule().
int moa.classifiers.rules.AbstractAMRules.ruleNumberID [protected]
Definition at line 58 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.resetLearningImpl(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
RuleSet moa.classifiers.rules.AbstractAMRules.ruleSet = new RuleSet() [protected]
Definition at line 56 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelDescription(), moa.classifiers.rules.AbstractAMRules.getModelMeasurementsImpl(), moa.classifiers.rules.AbstractAMRules.getVotesForInstance(), moa.classifiers.rules.AbstractAMRules.PrintRuleSet(), and moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
final long moa.classifiers.rules.AbstractAMRules.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.rules.AMRulesRegressor.
Definition at line 55 of file AbstractAMRules.java.
FloatOption moa.classifiers.rules.AbstractAMRules.splitConfidenceOption
Initial value:
 new FloatOption(
            "splitConfidence",
            'c',
            "Hoeffding Bound Parameter. The allowable error in split decision, values closer to 0 will take longer to decide.",
            0.0000001, 0.0, 1.0)
Definition at line 61 of file AbstractAMRules.java.
double [] moa.classifiers.rules.AbstractAMRules.statistics [protected]
Definition at line 59 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule(), and moa.classifiers.rules.AMRulesRegressor.resetLearningImpl().
FloatOption moa.classifiers.rules.AbstractAMRules.tieThresholdOption
Initial value:
 new FloatOption("tieThreshold",
            't', "Hoeffding Bound Parameter. Threshold below which a split will be forced to break ties.",
            0.05, 0.0, 1.0)
Definition at line 66 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.AbstractAMRules.univariateAnomalyprobabilityThresholdOption
Initial value:
 new FloatOption(
            "univariateAnomalyprobabilityThreshold",
            'u',
            "Univariate anomaly threshold value.",
            0.10, 0.0, 1.0)
Definition at line 91 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.isAnomaly().
FlagOption moa.classifiers.rules.AbstractAMRules.unorderedRulesOption
Initial value:
 new FlagOption("setUnorderedRulesOn", 'U',
            "unorderedRules.")
Definition at line 101 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.AbstractAMRules.getModelDescription(), moa.classifiers.rules.AbstractAMRules.getVotesForInstance(), moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl(), and moa.classifiers.rules.AbstractAMRules.VerboseToConsole().
IntOption moa.classifiers.rules.AbstractAMRules.VerbosityOption
Initial value:
 new IntOption(
            "verbosity",
            'v',
            "Output Verbosity Control Level. 1 (Less) to 5 (More)",
            1, 1, 5)
Definition at line 104 of file AbstractAMRules.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.core.Rule.debug(), moa.classifiers.rules.AbstractAMRules.debug(), and moa.classifiers.rules.AbstractAMRules.VerboseToConsole().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/AbstractAMRules.java