MOA: moa.classifiers.meta.ADACC Class Reference
moa.classifiers.meta.ADACC Class Reference
Anticipative and Dynamic Adaptation to Concept Changes.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Public Attributes
IntOption tauSizeOption
Evaluation window for the stability index computation.
FloatOption stabIndexSizeOption
Threshold for the stability index.
FloatOption equivIndexSizeOption
Threshold for concept equivalence.
Protected Member Functions
void initVariables ()
Initializes the method variables.
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
int getNbActiveClassifiers ()
Returns the number of classifiers used for prediction which includes the adaptive learners and the snapshots in ADACC.
int getNbAdaptiveClassifiers ()
Returns the number of adaptive classifiers in the ensemble which excludes the static snapshots in ADACC.
Protected Attributes
int tau_size = 0
Size of the evaluation window to compute the stability index.
Instances recentChunk
Last chunk of data of size (tau_size) to compute the stability index.
double theta_stab
Threshold values for the stability index and concept equivalence.
double theta_diff
double index
Current stability index.
int addedPermanent = 0
Number of added snapshots.
Static Protected Attributes
static final int MAXPERMANENT = 100
Maximum number of snapshots (copies of classifiers kept in case of recurrence).
Private Member Functions
void takeSnapshot ()
If the environment is stable enough, take a snapshot (a copy) of the best adaptive classifier and keep it for future use, in case of concept recurrence.
double computeKappa (int[] y1, int[] y2)
Returns the kappa statistics, a statistical measure of agreement in the predictions of 2 classifiers.
double computeStabilityIndex ()
Returns the stability index of the adaptive ensemble of classifiers.
Classifier getBestAdaptiveClassifier ()
Returns the adaptive classifier with the highest weight.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Anticipative and Dynamic Adaptation to Concept Changes.
Ensemble method for data streams that adapts to concept changes and deals with concept recurrence.
Reference: JABER, G., CORNUEJOLS, A., and TARROUX, P. A New On-Line Learning Method for Coping with Recurring Concepts: The ADACC System. In : Neural Information Processing. Springer Berlin Heidelberg, 2013. p. 595-604.
Author:
Ghazal Jaber (ghazal.jaber@gmail.com)
Definition at line 46 of file ADACC.java.
Member Function Documentation
double moa.classifiers.meta.ADACC.computeKappa (int[] y1, int[] y2) [private]
Returns the kappa statistics, a statistical measure of agreement in the predictions of 2 classifiers.
Used as a measure of diversity of predictive models: the higher the kappa value, the smaller the diversity
Parameters:
y1 the predictions of classifier A
y2 the predictions of classifier B
Returns:
the kappa measure
Definition at line 177 of file ADACC.java.
References moa.classifiers.AbstractClassifier.modelContext.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), and moa.classifiers.meta.ADACC.takeSnapshot().
{
        int m=y1.length;
        double theta1=0;
        double counts[][]=new double[2][this.modelContext.numClasses()];
        for (int i=0;i<m;i++){
            if (y1[i]==y2[i])
                theta1=theta1+1;
            counts[0][y1[i]]=counts[0][y1[i]]+1;
            counts[1][y2[i]]=counts[1][y2[i]]+1;
        }
        theta1=theta1/m;
        double theta2=0;
        for(int i=0;i<this.modelContext.numClasses();i++)
            theta2+=counts[0][i]/m*counts[1][i]/m;
        if (theta1==theta2 && theta2==1)
            return 1;
        return (theta1-theta2)/(1-theta2);
    }
double moa.classifiers.meta.ADACC.computeStabilityIndex () [private]
Returns the stability index of the adaptive ensemble of classifiers.
The ensemble is considered stable here if its diversity level and error rates are low.
Returns:
the stability measure value
Definition at line 213 of file ADACC.java.
References moa.classifiers.meta.ADACC.computeKappa(), moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.getHalf(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.ADACC.index, moa.classifiers.meta.ADACC.MAXPERMANENT, moa.classifiers.meta.ADACC.recentChunk, and moa.classifiers.meta.ADACC.tau_size.
Referenced by moa.classifiers.meta.ADACC.takeSnapshot().
{
        int m = (int)Math.floor((this.ensemble.length-MAXPERMANENT)/2);
        int[][] votes=new int[m][tau_size];
        double errors=0;
        int count=0;
        Pair[] arr = getHalf(true);
        for (int i=0;i<m;i++){
            for (int j=0;j<tau_size;j++){
                votes[i][j]=Utils.maxIndex(this.ensemble[arr[i].index].getVotesForInstance(recentChunk.get(j)));
                errors+=(votes[i][j]==(int) this.recentChunk.get(j).classValue())?0:1;
                count++;
            }
        }
        errors = errors/count;
        double res=0;  count=0;
        for (int i=0;i<m;i++)
            for (int j=i+1;j<m;j++)
                if (i!=j){
                    res+=computeKappa(votes[i],votes[j]);
                    count++;
                }
        return res/count-errors;
    }
Classifier moa.classifiers.meta.ADACC.getBestAdaptiveClassifier () [private]
Returns the adaptive classifier with the highest weight.
Returns:
the best adaptive classifier
Definition at line 247 of file ADACC.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleWeights, moa.classifiers.meta.DACC.Pair.index, and moa.classifiers.meta.ADACC.MAXPERMANENT.
Referenced by moa.classifiers.meta.ADACC.takeSnapshot().
{
        //take a copy of the ensemble weights (excluding snapshots)
        Pair[] newEnsembleWeights = new Pair[ensembleWeights.length-MAXPERMANENT];
        for (int i = 0 ; i < newEnsembleWeights.length; i++)
            newEnsembleWeights[i]=ensembleWeights[i];
        //sort the weight values
        Arrays.sort(newEnsembleWeights,Collections.reverseOrder());
        return this.ensemble[newEnsembleWeights[0].index].copy();
    }
void moa.classifiers.meta.ADACC.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 262 of file ADACC.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.ADACC.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 267 of file ADACC.java.
References moa.classifiers.meta.ADACC.addedPermanent, moa.classifiers.meta.DACC.combinationOption, moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.classifiers.meta.ADACC.index, moa.classifiers.meta.DACC.maturityOption, moa.classifiers.meta.ADACC.MAXPERMANENT, moa.classifiers.meta.ADACC.tau_size, moa.classifiers.meta.ADACC.theta_diff, and moa.classifiers.meta.ADACC.theta_stab.
{
        Measurement[] measurements  = new Measurement[10];
        measurements[0] = new Measurement("size ",
                    this.ensemble.length-MAXPERMANENT);
        measurements[1] = new Measurement("maturity ",
                   this.maturityOption.getValue());
        measurements[2] = new Measurement("evalsize ",
                   this.evaluationSizeOption.getValue());
        measurements[3] = new Measurement("cmb ",
                   this.combinationOption.getChosenIndex());
        measurements[4] = new Measurement("tau",
                this.tau_size);
        measurements[5] = new Measurement("MaxSnapshotsSize",
                MAXPERMANENT);
        measurements[6] = new Measurement("SnapshotsSize",
                this.addedPermanent);
        measurements[7] = new Measurement("stabilityIndex",
                this.index);
        measurements[8]=new Measurement("stabilityThreshold",
                this.theta_stab);
        measurements[9]=new Measurement("differenceThreshold",
                this.theta_diff);
        return measurements;
    }
int moa.classifiers.meta.ADACC.getNbActiveClassifiers () [protected]
Returns the number of classifiers used for prediction which includes the adaptive learners and the snapshots in ADACC.
Returns:
the number of classifiers used for prediction
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 296 of file ADACC.java.
References moa.classifiers.meta.ADACC.addedPermanent, moa.classifiers.meta.DACC.ensemble, and moa.classifiers.meta.ADACC.MAXPERMANENT.
{
        return ensemble.length-MAXPERMANENT+Math.min(addedPermanent,MAXPERMANENT);
    }
int moa.classifiers.meta.ADACC.getNbAdaptiveClassifiers () [protected]
Returns the number of adaptive classifiers in the ensemble which excludes the static snapshots in ADACC.
Returns:
the number of adaptive classifiers
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 301 of file ADACC.java.
References moa.classifiers.meta.DACC.ensemble, and moa.classifiers.meta.ADACC.MAXPERMANENT.
{
        return this.ensemble.length-MAXPERMANENT;
    }
String moa.classifiers.meta.ADACC.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 51 of file ADACC.java.
{
        return "Anticipative and Dynamic Adaptation to Concept Changes for data streams.";
    }
void moa.classifiers.meta.ADACC.initVariables () [protected]
Initializes the method variables.
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 95 of file ADACC.java.
References moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWindows, moa.classifiers.meta.ADACC.equivIndexSizeOption, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.meta.ADACC.MAXPERMANENT, moa.classifiers.meta.DACC.memberCountOption, moa.classifiers.meta.ADACC.recentChunk, moa.classifiers.meta.ADACC.stabIndexSizeOption, moa.classifiers.meta.ADACC.tau_size, moa.classifiers.meta.ADACC.tauSizeOption, moa.classifiers.meta.ADACC.theta_diff, and moa.classifiers.meta.ADACC.theta_stab.
{
        this.tau_size = this.tauSizeOption.getValue();
        this.theta_stab = this.stabIndexSizeOption.getValue();
        this.theta_diff = this.equivIndexSizeOption.getValue();
        this.recentChunk = null;
        int ensembleSize = (int)this.memberCountOption.getValue() + MAXPERMANENT;
        this.ensemble = new Classifier[ensembleSize];
        this.ensembleAges = new double[ensembleSize];
        this.ensembleWindows = new int[ensembleSize][(int)this.evaluationSizeOption.getValue()];
    }
void moa.classifiers.meta.ADACC.takeSnapshot () [private]
If the environment is stable enough, take a snapshot (a copy) of the best adaptive classifier and keep it for future use, in case of concept recurrence.
Definition at line 132 of file ADACC.java.
References moa.classifiers.meta.ADACC.addedPermanent, moa.classifiers.meta.ADACC.computeKappa(), moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.Classifier.copy(), moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.ADACC.getBestAdaptiveClassifier(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.ADACC.index, moa.classifiers.meta.ADACC.MAXPERMANENT, moa.classifiers.meta.ADACC.recentChunk, moa.classifiers.meta.ADACC.tau_size, moa.classifiers.meta.ADACC.theta_diff, and moa.classifiers.meta.ADACC.theta_stab.
Referenced by moa.classifiers.meta.ADACC.trainOnInstanceImpl().
{
        this.index = computeStabilityIndex();
        if (this.index >= this.theta_stab)
            if (addedPermanent == 0){
                this.ensemble[this.ensemble.length-MAXPERMANENT+addedPermanent] = getBestAdaptiveClassifier().copy();
                addedPermanent++;
            }
            else{
                Classifier candidate = getBestAdaptiveClassifier().copy();
                boolean duplicate = false;
                for (int j=0;j<Math.min(MAXPERMANENT,addedPermanent);j++){
                    Classifier lastSnapshot=this.ensemble[this.ensemble.length-MAXPERMANENT+j];
                    int[][] votes=new int[2][tau_size];
                    for (int k=0;k<tau_size;k++){
                        votes[0][k]=Utils.maxIndex(candidate.getVotesForInstance(recentChunk.get(k)));
                        votes[1][k]=Utils.maxIndex(lastSnapshot.getVotesForInstance(recentChunk.get(k)));
                    }
                    double kappa=computeKappa(votes[0],votes[1]);
                    if (kappa>=this.theta_diff){
                        duplicate = true; break;
                    }
                }
                if (!duplicate){
                    this.ensemble[this.ensemble.length-MAXPERMANENT+(addedPermanent%MAXPERMANENT)]=candidate;
                    addedPermanent++;
                }
            }
        }
void moa.classifiers.meta.ADACC.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 111 of file ADACC.java.
References moa.classifiers.AbstractClassifier.getModelContext(), moa.classifiers.meta.DACC.nbInstances, moa.classifiers.meta.ADACC.recentChunk, moa.classifiers.meta.ADACC.takeSnapshot(), moa.classifiers.meta.ADACC.tau_size, and moa.classifiers.meta.DACC.trainAndClassify().
{
        if (recentChunk == null)
            recentChunk = new Instances(this.getModelContext());
        if (recentChunk.size() < this.tau_size)
            recentChunk.add(inst);
        else
            recentChunk.set(this.nbInstances % this.tau_size,inst);
        trainAndClassify(inst);
        if ((this.nbInstances % this.tau_size)==0)
            takeSnapshot();
    }
Member Data Documentation
int moa.classifiers.meta.ADACC.addedPermanent = 0 [protected]
Number of added snapshots.
Definition at line 92 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getNbActiveClassifiers(), and moa.classifiers.meta.ADACC.takeSnapshot().
FloatOption moa.classifiers.meta.ADACC.equivIndexSizeOption
Initial value:
 new FloatOption("CeThr", 'q',
            "The threshold for concept equivalence", 0.7, 0, 1)
Threshold for concept equivalence.
Definition at line 67 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.initVariables().
double moa.classifiers.meta.ADACC.index [protected]
Current stability index.
Definition at line 84 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), and moa.classifiers.meta.ADACC.takeSnapshot().
final int moa.classifiers.meta.ADACC.MAXPERMANENT = 100 [static, protected]
Maximum number of snapshots (copies of classifiers kept in case of recurrence).
Definition at line 88 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.meta.ADACC.getBestAdaptiveClassifier(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getNbActiveClassifiers(), moa.classifiers.meta.ADACC.getNbAdaptiveClassifiers(), moa.classifiers.meta.ADACC.initVariables(), and moa.classifiers.meta.ADACC.takeSnapshot().
Instances moa.classifiers.meta.ADACC.recentChunk [protected]
Last chunk of data of size (tau_size) to compute the stability index.
Definition at line 76 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.meta.ADACC.takeSnapshot(), and moa.classifiers.meta.ADACC.trainOnInstanceImpl().
final long moa.classifiers.meta.ADACC.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.meta.DACC.
Definition at line 48 of file ADACC.java.
FloatOption moa.classifiers.meta.ADACC.stabIndexSizeOption
Initial value:
 new FloatOption("StabThr", 'z',
            "The threshold for stability", 0.8, 0, 1)
Threshold for the stability index.
Definition at line 62 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.initVariables().
int moa.classifiers.meta.ADACC.tau_size = 0 [protected]
Size of the evaluation window to compute the stability index.
Definition at line 72 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.meta.ADACC.takeSnapshot(), and moa.classifiers.meta.ADACC.trainOnInstanceImpl().
IntOption moa.classifiers.meta.ADACC.tauSizeOption
Initial value:
 new IntOption("tau", 't',
            "The size of the evaluation window for the meta-learning.", 100, 1, 10000)
Evaluation window for the stability index computation.
Definition at line 57 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.initVariables().
double moa.classifiers.meta.ADACC.theta_diff [protected]
Definition at line 80 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.initVariables(), and moa.classifiers.meta.ADACC.takeSnapshot().
double moa.classifiers.meta.ADACC.theta_stab [protected]
Threshold values for the stability index and concept equivalence.
Definition at line 80 of file ADACC.java.
Referenced by moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.initVariables(), and moa.classifiers.meta.ADACC.takeSnapshot().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/ADACC.java