MOA: moa.tasks.MainTask Class Reference
moa.tasks.MainTask Class Reference
Abstract Main Task.
Public Attributes
FileOption outputFileOption
File option to save the final result of the task to.
Protected Member Functions
Object doTaskImpl (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
abstract Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Protected Attributes
static final int INSTANCES_BETWEEN_MONITOR_UPDATES = 10
The number of instances between monitor updates.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Abstract Main Task.
All tasks that want to write their result to a file must extend this class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 37 of file MainTask.java.
Member Function Documentation
abstract Object moa.tasks.MainTask.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, pure virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implemented in moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Referenced by moa.tasks.MainTask.doTaskImpl().
Object moa.tasks.MainTask.doTaskImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask so all its extensions only need to implement doTaskImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.AbstractTask.
Definition at line 49 of file MainTask.java.
References moa.tasks.MainTask.doMainTask(), moa.options.FileOption.getFile(), moa.tasks.AbstractTask.getTaskName(), moa.tasks.MainTask.outputFileOption, moa.tasks.TaskMonitor.setCurrentActivity(), and moa.tasks.TaskMonitor.taskShouldAbort().
{
        Object result = doMainTask(monitor, repository);
        if (monitor.taskShouldAbort()) {
            return null;
        }
        File outputFile = this.outputFileOption.getFile();
        if (outputFile != null) {
            if (result instanceof Serializable) {
                monitor.setCurrentActivity("Saving result of task "
                        + getTaskName() + " to file " + outputFile + "...",
                        -1.0);
                try {
                    SerializeUtils.writeToFile(outputFile,
                            (Serializable) result);
                } catch (IOException ioe) {
                    throw new RuntimeException("Failed writing result of task "
                            + getTaskName() + " to file " + outputFile, ioe);
                }
            } else {
                throw new RuntimeException("Result of task " + getTaskName()
                        + " is not serializable, so cannot be written to file "
                        + outputFile);
            }
        }
        return result;
    }
Member Data Documentation
final int moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES = 10 [static, protected]
The number of instances between monitor updates.
Definition at line 42 of file MainTask.java.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), and moa.tasks.EvaluateConceptDrift.doMainTask().
FileOption moa.tasks.MainTask.outputFileOption
Initial value:
 new FileOption("taskResultFile", 'O',
            "File to save the final result of the task to.", null, "moa", true)
File option to save the final result of the task to.
Definition at line 45 of file MainTask.java.
Referenced by moa.tasks.MainTask.doTaskImpl().
final long moa.tasks.MainTask.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Definition at line 39 of file MainTask.java.
The documentation for this class was generated from the following file:
main/java/moa/tasks/MainTask.java