MOA: moa.classifiers.meta.AccuracyWeightedEnsemble Class Reference
moa.classifiers.meta.AccuracyWeightedEnsemble Class Reference
The Accuracy Weighted Ensemble classifier as proposed by Wang et al.
Classes
class ClassifierWeightComparator
Simple weight comparator.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts a class for an example.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Determines whether the classifier is randomizable.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption learnerOption = new ClassOption("learner", 'l', "Classifier to train.", Classifier.class, "trees.HoeffdingTree -l NB -e 1000 -g 100 -c 0.01")
Type of classifier to use as a component classifier.
FloatOption memberCountOption = new FloatOption("memberCount", 'n', "The maximum number of classifier in an ensemble.", 15, 1, Integer.MAX_VALUE)
Number of component classifiers.
FloatOption storedCountOption = new FloatOption("storedCount", 'r', "The maximum number of classifiers to store and choose from when creating an ensemble.", 30, 1, Integer.MAX_VALUE)
Number of classifiers remembered and available for ensemble construction.
IntOption chunkSizeOption = new IntOption("chunkSize", 'c', "The chunk size used for classifier creation and evaluation.", 500, 1, Integer.MAX_VALUE)
Chunk size.
IntOption numFoldsOption = new IntOption("numFolds", 'f', "Number of cross-validation folds for candidate classifier testing.", 10, 1, Integer.MAX_VALUE)
Number of folds in candidate classifier cross-validation.
Protected Member Functions
void processChunk ()
Processes a chunk.
double computeCandidateWeight (Classifier candidate, Instances chunk, int numFolds)
Computes the weight of a candidate classifier.
double computeWeight (Classifier learner, Instances chunk)
Computes the weight of a given classifie.
double computeMseR ()
Computes the MSEr threshold.
Measurement[] getModelMeasurementsImpl ()
Adds ensemble weights to the measurements.
Classifier addToStored (Classifier newClassifier, double newClassifiersWeight)
Adds a classifier to the storage.
int removePoorestModelBytes ()
Removes the poorest classifier from the model, thus decreasing the models size.
void discardModel (int index)
Removes the classifier at a given index from the model, thus decreasing the models size.
Protected Attributes
long[] classDistributions
Classifier[] ensemble
Classifier[] storedLearners
double[] ensembleWeights
double[][] storedWeights
The weights of stored classifiers.
int processedInstances
int chunkSize
int numFolds
int maxMemberCount
int maxStoredCount
Classifier candidateClassifier
Instances currentChunk
Static Protected Attributes
static java.util.Comparator
< double[]> weightComparator = new ClassifierWeightComparator()
Simple weight comparator.
Private Member Functions
void initVariables ()
Initiates the current chunk and class distribution variables.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Accuracy Weighted Ensemble classifier as proposed by Wang et al.
in "Mining concept-drifting data streams using ensemble classifiers", KDD 2003.
Definition at line 40 of file AccuracyWeightedEnsemble.java.
Member Function Documentation
Classifier moa.classifiers.meta.AccuracyWeightedEnsemble.addToStored (Classifier newClassifier, double newClassifiersWeight) [protected]
Adds a classifier to the storage.
Parameters:
newClassifier The classifier to add.
newClassifiersWeight The new classifiers weight.
Definition at line 408 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.meta.AccuracyWeightedEnsemble.storedLearners, and moa.classifiers.meta.AccuracyWeightedEnsemble.storedWeights.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
{
        Classifier addedClassifier = null;
        Classifier[] newStored = new Classifier[this.storedLearners.length + 1];
        double[][] newStoredWeights = new double[newStored.length][2];
        for (int i = 0; i < newStored.length; i++) {
            if (i < this.storedLearners.length) {
                newStored[i] = this.storedLearners[i];
                newStoredWeights[i][0] = this.storedWeights[i][0];
                newStoredWeights[i][1] = this.storedWeights[i][1];
            } else {
                newStored[i] = addedClassifier = newClassifier.copy();
                newStoredWeights[i][0] = newClassifiersWeight;
                newStoredWeights[i][1] = i;
            }
        }
        this.storedLearners = newStored;
        this.storedWeights = newStoredWeights;
        return addedClassifier;
    }
double moa.classifiers.meta.AccuracyWeightedEnsemble.computeCandidateWeight (Classifier candidate, Instances chunk, int numFolds) [protected]
Computes the weight of a candidate classifier.
Parameters:
candidate Candidate classifier.
chunk Data chunk of examples.
numFolds Number of folds in candidate classifier cross-validation.
useMseR Determines whether to use the MSEr threshold.
Returns:
Candidate classifier weight.
Definition at line 246 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight(), moa.classifiers.Classifier.copy(), and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
{
        double candidateWeight = 0.0;
        Random random = new Random(1);
        Instances randData = new Instances(chunk);
        randData.randomize(random);
        if (randData.classAttribute().isNominal()) {
            randData.stratify(numFolds);
        }
        for (int n = 0; n < numFolds; n++) {
            Instances train = randData.trainCV(numFolds, n, random);
            Instances test = randData.testCV(numFolds, n);
            Classifier learner = candidate.copy();
            for (int num = 0; num < train.numInstances(); num++) {
                learner.trainOnInstance(train.instance(num));
            }
            candidateWeight += computeWeight(learner, test);
        }
        double resultWeight = candidateWeight / numFolds;
        if (Double.isInfinite(resultWeight)) {
            return Double.MAX_VALUE;
        } else {
            return resultWeight;
        }
    }
double moa.classifiers.meta.AccuracyWeightedEnsemble.computeMseR () [protected]
Computes the MSEr threshold.
Returns:
The MSEr threshold.
Definition at line 321 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize, and moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight().
{
        double p_c;
        double mse_r = 0;
        for (int i = 0; i < this.classDistributions.length; i++) {
            p_c = (double) this.classDistributions[i] / (double) this.chunkSize;
            mse_r += p_c * ((1 - p_c) * (1 - p_c));
        }
        return mse_r;
    }
double moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight (Classifier learner, Instances chunk) [protected]
Computes the weight of a given classifie.
Parameters:
learner Classifier to calculate weight for.
chunk Data chunk of examples.
useMseR Determines whether to use the MSEr threshold.
Returns:
The given classifier's weight.
Definition at line 285 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize, moa.classifiers.meta.AccuracyWeightedEnsemble.computeMseR(), and moa.classifiers.Classifier.getVotesForInstance().
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.computeCandidateWeight(), and moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
{
        double mse_i = 0;
        double mse_r = 0;
        double f_ci;
        double voteSum;
        for (int i = 0; i < chunk.numInstances(); i++) {
            try {
                voteSum = 0;
                for (double element : learner.getVotesForInstance(chunk.instance(i))) {
                    voteSum += element;
                }
                if (voteSum > 0) {
                    f_ci = learner.getVotesForInstance(chunk.instance(i))[(int) chunk.instance(i).classValue()] / voteSum;
                    mse_i += (1 - f_ci) * (1 - f_ci);
                } else {
                    mse_i += 1;
                }
            } catch (Exception e) {
                mse_i += 1;
            }
        }
        mse_i /= this.chunkSize;
        mse_r = this.computeMseR();
        return java.lang.Math.max(mse_r - mse_i, 0);
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.discardModel (int index) [protected]
Removes the classifier at a given index from the model, thus decreasing the models size.
Parameters:
index
Definition at line 449 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, and moa.classifiers.meta.AccuracyWeightedEnsemble.ensembleWeights.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.removePoorestModelBytes().
{
        Classifier[] newEnsemble = new Classifier[this.ensemble.length - 1];
        double[] newEnsembleWeights = new double[newEnsemble.length];
        int oldPos = 0;
        for (int i = 0; i < newEnsemble.length; i++) {
            if (oldPos == index) {
                oldPos++;
            }
            newEnsemble[i] = this.ensemble[oldPos];
            newEnsembleWeights[i] = this.ensembleWeights[oldPos];
            oldPos++;
        }
        this.ensemble = newEnsemble;
        this.ensembleWeights = newEnsembleWeights;
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 358 of file AccuracyWeightedEnsemble.java.
{
    }
Measurement [] moa.classifiers.meta.AccuracyWeightedEnsemble.getModelMeasurementsImpl () [protected, virtual]
Adds ensemble weights to the measurements.
Implements moa.classifiers.AbstractClassifier.
Definition at line 365 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, moa.classifiers.meta.AccuracyWeightedEnsemble.maxMemberCount, moa.classifiers.meta.AccuracyWeightedEnsemble.maxStoredCount, and moa.classifiers.meta.AccuracyWeightedEnsemble.storedWeights.
{
        Measurement[] measurements = new Measurement[this.maxStoredCount];
        for (int m = 0; m < this.maxMemberCount; m++) {
            measurements[m] = new Measurement("Member weight " + (m + 1), -1);
        }
        for (int s = this.maxMemberCount; s < this.maxStoredCount; s++) {
            measurements[s] = new Measurement("Stored member weight " + (s + 1), -1);
        }
        if (this.storedWeights != null) {
            int storeSize = this.storedWeights.length;
            for (int i = 0; i < storeSize; i++) {
                if (i < this.ensemble.length) {
                    measurements[i] = new Measurement("Member weight " + (i + 1), this.storedWeights[storeSize - i - 1][0]);
                } else {
                    measurements[i] = new Measurement("Stored member weight " + (i + 1), this.storedWeights[storeSize - i - 1][0]);
                }
            }
        }
        return measurements;
    }
String moa.classifiers.meta.AccuracyWeightedEnsemble.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 43 of file AccuracyWeightedEnsemble.java.
{
        return "Accuracy Weighted Ensemble classifier as proposed by Wang et al. in 'Mining concept-drifting data streams using ensemble classifiers', KDD 2003";
    }
Classifier [] moa.classifiers.meta.AccuracyWeightedEnsemble.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 398 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance (Instance inst)
Predicts a class for an example.
Implements moa.classifiers.Classifier.
Definition at line 336 of file AccuracyWeightedEnsemble.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, moa.classifiers.meta.AccuracyWeightedEnsemble.ensembleWeights, moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.sumOfValues(), and moa.classifiers.AbstractClassifier.trainingWeightSeenByModel().
{
        DoubleVector combinedVote = new DoubleVector();
        if (this.trainingWeightSeenByModel > 0.0) {
            for (int i = 0; i < this.ensemble.length; i++) {
                if (this.ensembleWeights[i] > 0.0) {
                    DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
                    if (vote.sumOfValues() > 0.0) {
                        vote.normalize();
                        //scale weight and prevent overflow
                        vote.scaleValues(this.ensembleWeights[i] / (1.0 * this.ensemble.length + 1));
                        combinedVote.addValues(vote);
                    }
                }
            }
        }
        combinedVote.normalize();
        return combinedVote.getArrayRef();
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.initVariables () [private]
Initiates the current chunk and class distribution variables.
Definition at line 169 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions, moa.classifiers.meta.AccuracyWeightedEnsemble.currentChunk, and moa.classifiers.AbstractClassifier.getModelContext().
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
{
        if (this.currentChunk == null) {
            this.currentChunk = new Instances(this.getModelContext());
        }
        if (this.classDistributions == null) {
            this.classDistributions = new long[this.getModelContext().classAttribute().numValues()];
            for (int i = 0; i < this.classDistributions.length; i++) {
                this.classDistributions[i] = 0;
            }
        }
    }
boolean moa.classifiers.meta.AccuracyWeightedEnsemble.isRandomizable ()
Determines whether the classifier is randomizable.
Implements moa.classifiers.Classifier.
Definition at line 393 of file AccuracyWeightedEnsemble.java.
{
        return false;
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 125 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.candidateClassifier, moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize, moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.classifiers.meta.AccuracyWeightedEnsemble.learnerOption, moa.classifiers.meta.AccuracyWeightedEnsemble.maxMemberCount, moa.classifiers.meta.AccuracyWeightedEnsemble.maxStoredCount, moa.classifiers.meta.AccuracyWeightedEnsemble.memberCountOption, moa.classifiers.meta.AccuracyWeightedEnsemble.numFolds, moa.classifiers.meta.AccuracyWeightedEnsemble.numFoldsOption, moa.classifiers.Classifier.resetLearning(), and moa.classifiers.meta.AccuracyWeightedEnsemble.storedCountOption.
{
        this.maxMemberCount = (int) memberCountOption.getValue();
        this.maxStoredCount = (int) storedCountOption.getValue();
        if (this.maxMemberCount > this.maxStoredCount) {
            this.maxStoredCount = this.maxMemberCount;
        }
        this.chunkSize = this.chunkSizeOption.getValue();
        this.numFolds = this.numFoldsOption.getValue();
        this.candidateClassifier = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidateClassifier.resetLearning();
        super.prepareForUseImpl(monitor, repository);
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk () [protected]
Processes a chunk.
Parameters:
useMseR Determines whether to use the MSEr threshold.
Definition at line 188 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.addToStored(), moa.classifiers.meta.AccuracyWeightedEnsemble.candidateClassifier, moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize, moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions, moa.classifiers.meta.AccuracyWeightedEnsemble.computeCandidateWeight(), moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight(), moa.classifiers.Classifier.copy(), moa.classifiers.meta.AccuracyWeightedEnsemble.currentChunk, moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, moa.classifiers.meta.AccuracyWeightedEnsemble.ensembleWeights, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.AccuracyWeightedEnsemble.learnerOption, moa.classifiers.meta.AccuracyWeightedEnsemble.numFolds, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.AccuracyWeightedEnsemble.storedLearners, moa.classifiers.meta.AccuracyWeightedEnsemble.storedWeights, moa.classifiers.Classifier.trainOnInstance(), and moa.classifiers.meta.AccuracyWeightedEnsemble.weightComparator.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
{
        // Compute weights
        double candidateClassifierWeight = this.computeCandidateWeight(this.candidateClassifier, this.currentChunk, this.numFolds);
        for (int i = 0; i < this.storedLearners.length; i++) {
            this.storedWeights[i][0] = this.computeWeight(this.storedLearners[(int) this.storedWeights[i][1]], this.currentChunk);
        }
        if (this.storedLearners.length < this.maxStoredCount) {
            // Train and add classifier
            for (int num = 0; num < this.chunkSize; num++) {
                this.candidateClassifier.trainOnInstance(this.currentChunk.instance(num));
            }
            this.addToStored(this.candidateClassifier, candidateClassifierWeight);
        } else {
            // Substitute poorest classifier
            java.util.Arrays.sort(this.storedWeights, weightComparator);
            if (this.storedWeights[0][0] < candidateClassifierWeight) {
                for (int num = 0; num < this.chunkSize; num++) {
                    this.candidateClassifier.trainOnInstance(this.currentChunk.instance(num));
                }
                this.storedWeights[0][0] = candidateClassifierWeight;
                this.storedLearners[(int) this.storedWeights[0][1]] = this.candidateClassifier.copy();
            }
        }
        int ensembleSize = java.lang.Math.min(this.storedLearners.length, this.maxMemberCount);
        this.ensemble = new Classifier[ensembleSize];
        this.ensembleWeights = new double[ensembleSize];
        // Sort learners according to their weights
        java.util.Arrays.sort(this.storedWeights, weightComparator);
        // Select top k classifiers to construct the ensemble
        int storeSize = this.storedLearners.length;
        for (int i = 0; i < ensembleSize; i++) {
            this.ensembleWeights[i] = this.storedWeights[storeSize - i - 1][0];
            this.ensemble[i] = this.storedLearners[(int) this.storedWeights[storeSize - i - 1][1]];
        }
        this.classDistributions = null;
        this.currentChunk = null;
        this.candidateClassifier = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidateClassifier.resetLearning();
    }
int moa.classifiers.meta.AccuracyWeightedEnsemble.removePoorestModelBytes () [protected]
Removes the poorest classifier from the model, thus decreasing the models size.
Returns:
the size of the removed classifier.
Definition at line 436 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.discardModel(), moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, moa.classifiers.meta.AccuracyWeightedEnsemble.ensembleWeights, and moa.MOAObject.measureByteSize().
{
        int poorestIndex = Utils.minIndex(this.ensembleWeights);
        int byteSize = this.ensemble[poorestIndex].measureByteSize();
        discardModel(poorestIndex);
        return byteSize;
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 142 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.candidateClassifier, moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions, moa.classifiers.meta.AccuracyWeightedEnsemble.currentChunk, moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.AccuracyWeightedEnsemble.learnerOption, moa.classifiers.meta.AccuracyWeightedEnsemble.processedInstances, moa.classifiers.Classifier.resetLearning(), and moa.classifiers.meta.AccuracyWeightedEnsemble.storedLearners.
{
        this.currentChunk = null;
        this.classDistributions = null;
        this.processedInstances = 0;
        this.ensemble = new Classifier[0];
        this.storedLearners = new Classifier[0];
        this.candidateClassifier = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidateClassifier.resetLearning();
    }
void moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 154 of file AccuracyWeightedEnsemble.java.
References moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize, moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions, moa.classifiers.meta.AccuracyWeightedEnsemble.currentChunk, moa.classifiers.meta.AccuracyWeightedEnsemble.initVariables(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.processedInstances.
{
        this.initVariables();
        this.classDistributions[(int) inst.classValue()]++;
        this.currentChunk.add(inst);
        this.processedInstances++;
        if (this.processedInstances % this.chunkSize == 0) {
            this.processChunk();
        }
    }
Member Data Documentation
Classifier moa.classifiers.meta.AccuracyWeightedEnsemble.candidateClassifier [protected]
Definition at line 120 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl().
int moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSize [protected]
Definition at line 112 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.computeMseR(), moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight(), moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
IntOption moa.classifiers.meta.AccuracyWeightedEnsemble.chunkSizeOption = new IntOption("chunkSize", 'c', "The chunk size used for classifier creation and evaluation.", 500, 1, Integer.MAX_VALUE)
Chunk size.
Definition at line 89 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
long [] moa.classifiers.meta.AccuracyWeightedEnsemble.classDistributions [protected]
Definition at line 96 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.computeMseR(), moa.classifiers.meta.AccuracyWeightedEnsemble.initVariables(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
Instances moa.classifiers.meta.AccuracyWeightedEnsemble.currentChunk [protected]
Definition at line 122 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.initVariables(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
Classifier [] moa.classifiers.meta.AccuracyWeightedEnsemble.ensemble [protected]
Definition at line 98 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.discardModel(), moa.classifiers.meta.AccuracyWeightedEnsemble.getModelMeasurementsImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.getSubClassifiers(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyWeightedEnsemble.removePoorestModelBytes(), and moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl().
double [] moa.classifiers.meta.AccuracyWeightedEnsemble.ensembleWeights [protected]
Definition at line 102 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.discardModel(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.removePoorestModelBytes().
ClassOption moa.classifiers.meta.AccuracyWeightedEnsemble.learnerOption = new ClassOption("learner", 'l', "Classifier to train.", Classifier.class, "trees.HoeffdingTree -l NB -e 1000 -g 100 -c 0.01")
Type of classifier to use as a component classifier.
Definition at line 74 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl().
int moa.classifiers.meta.AccuracyWeightedEnsemble.maxMemberCount [protected]
Definition at line 116 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.getModelMeasurementsImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
int moa.classifiers.meta.AccuracyWeightedEnsemble.maxStoredCount [protected]
Definition at line 118 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.getModelMeasurementsImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
FloatOption moa.classifiers.meta.AccuracyWeightedEnsemble.memberCountOption = new FloatOption("memberCount", 'n', "The maximum number of classifier in an ensemble.", 15, 1, Integer.MAX_VALUE)
Number of component classifiers.
Definition at line 79 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
int moa.classifiers.meta.AccuracyWeightedEnsemble.numFolds [protected]
Definition at line 114 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
IntOption moa.classifiers.meta.AccuracyWeightedEnsemble.numFoldsOption = new IntOption("numFolds", 'f', "Number of cross-validation folds for candidate classifier testing.", 10, 1, Integer.MAX_VALUE)
Number of folds in candidate classifier cross-validation.
Definition at line 94 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
int moa.classifiers.meta.AccuracyWeightedEnsemble.processedInstances [protected]
Definition at line 110 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.trainOnInstanceImpl().
final long moa.classifiers.meta.AccuracyWeightedEnsemble.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 64 of file AccuracyWeightedEnsemble.java.
FloatOption moa.classifiers.meta.AccuracyWeightedEnsemble.storedCountOption = new FloatOption("storedCount", 'r', "The maximum number of classifiers to store and choose from when creating an ensemble.", 30, 1, Integer.MAX_VALUE)
Number of classifiers remembered and available for ensemble construction.
Definition at line 84 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl().
Classifier [] moa.classifiers.meta.AccuracyWeightedEnsemble.storedLearners [protected]
Definition at line 100 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.addToStored(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl().
double [][] moa.classifiers.meta.AccuracyWeightedEnsemble.storedWeights [protected]
The weights of stored classifiers.
storedWeights[x][0] = weight storedWeights[x][1] = classifier
Definition at line 108 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.addToStored(), moa.classifiers.meta.AccuracyWeightedEnsemble.getModelMeasurementsImpl(), and moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
java.util.Comparator<double[]> moa.classifiers.meta.AccuracyWeightedEnsemble.weightComparator = new ClassifierWeightComparator() [static, protected]
Simple weight comparator.
Definition at line 69 of file AccuracyWeightedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/AccuracyWeightedEnsemble.java