MOA: moa.streams.ConceptDriftRealStream Class Reference
moa.streams.ConceptDriftRealStream Class Reference
Stream generator that adds concept drift to examples in a stream with different classes and attributes.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
ClassOption streamOption
ClassOption driftstreamOption
FloatOption alphaOption
IntOption positionOption
IntOption widthOption
IntOption randomSeedOption
Protected Attributes
InstanceStream inputStream
InstanceStream driftStream
Random random
int numberInstanceStream
InstancesHeader streamHeader
Instance inputInstance
Instance driftInstance
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator that adds concept drift to examples in a stream with different classes and attributes.
Example: real datasets.
Example:
ConceptDriftRealStream -s (ArffFileStream -f covtype.arff) \
-d (ConceptDriftRealStream -s (ArffFileStream -f PokerOrig.arff) <br/> -d (ArffFileStream -f elec.arff) -w 5000 -p 1000000) -w 5000 -p 581012
s : Stream
d : Concept drift Stream
p : Central position of concept drift change
w : Width of concept drift change
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 56 of file ConceptDriftRealStream.java.
Member Function Documentation
long moa.streams.ConceptDriftRealStream.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 140 of file ConceptDriftRealStream.java.
{
        return -1;
    }
void moa.streams.ConceptDriftRealStream.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 205 of file ConceptDriftRealStream.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.ConceptDriftRealStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 150 of file ConceptDriftRealStream.java.
References moa.streams.ConceptDriftRealStream.streamHeader.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.ConceptDriftRealStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 60 of file ConceptDriftRealStream.java.
{
        return "Adds Concept Drift to examples in a stream.";
    }
boolean moa.streams.ConceptDriftRealStream.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 145 of file ConceptDriftRealStream.java.
{
        return true;
    }
boolean moa.streams.ConceptDriftRealStream.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 155 of file ConceptDriftRealStream.java.
References moa.streams.ConceptDriftRealStream.driftStream, moa.streams.ConceptDriftRealStream.inputStream, and moa.streams.InstanceStream.isRestartable().
{
        return (this.inputStream.isRestartable() && this.driftStream.isRestartable());
    }
Instance moa.streams.ConceptDriftRealStream.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 160 of file ConceptDriftRealStream.java.
References moa.streams.ConceptDriftRealStream.driftInstance, moa.streams.ConceptDriftRealStream.driftStream, moa.streams.ConceptDriftRealStream.getHeader(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.hasMoreInstances(), moa.streams.ConceptDriftRealStream.inputInstance, moa.streams.ConceptDriftRealStream.inputStream, moa.streams.InstanceStream.nextInstance(), moa.streams.ConceptDriftRealStream.numberInstanceStream, moa.streams.ConceptDriftRealStream.positionOption, moa.streams.ConceptDriftRealStream.random, moa.streams.InstanceStream.restart(), and moa.streams.ConceptDriftRealStream.widthOption.
{
        numberInstanceStream++;
        double numclass = 0.0;
        double x = -4.0 * (double) (numberInstanceStream - this.positionOption.getValue()) / (double) this.widthOption.getValue();
        double probabilityDrift = 1.0 / (1.0 + Math.exp(x));
        if (this.random.nextDouble() > probabilityDrift) {
            if (this.inputStream.hasMoreInstances() == false) {
                this.inputStream.restart();
            }
            this.inputInstance = this.inputStream.nextInstance();
            numclass = this.inputInstance.classValue();
        } else {
            if (this.driftStream.hasMoreInstances() == false) {
                this.driftStream.restart();
            }
            this.driftInstance = this.driftStream.nextInstance();
            numclass = this.driftInstance.classValue();
        }
        int m = 0;
        double[] newVals = new double[this.inputInstance.numAttributes() + this.driftInstance.numAttributes() - 1];
        for (int j = 0; j < this.inputInstance.numAttributes() - 1; j++, m++) {
            newVals[m] = this.inputInstance.value(j);
        }
        for (int j = 0; j < this.driftInstance.numAttributes() - 1; j++, m++) {
            newVals[m] = this.driftInstance.value(j);
        }
        newVals[m] = numclass;
        //return new Instance(1.0, newVals);
        Instance inst = new DenseInstance(1.0, newVals);
        inst.setDataset(this.getHeader());
        inst.setClassValue(numclass);
        return inst;
    }
void moa.streams.ConceptDriftRealStream.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 101 of file ConceptDriftRealStream.java.
References moa.streams.ConceptDriftRealStream.alphaOption, moa.streams.ConceptDriftRealStream.driftStream, moa.streams.ConceptDriftRealStream.driftstreamOption, moa.options.AbstractOptionHandler.getCLICreationString(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.ConceptDriftRealStream.inputStream, moa.streams.ConceptDriftRealStream.numberInstanceStream, moa.streams.ConceptDriftRealStream.random, moa.streams.ConceptDriftRealStream.randomSeedOption, moa.streams.ConceptDriftRealStream.restart(), moa.options.IntOption.setValue(), moa.streams.ConceptDriftRealStream.streamHeader, moa.streams.ConceptDriftRealStream.streamOption, and moa.streams.ConceptDriftRealStream.widthOption.
{
        this.inputStream = (InstanceStream) getPreparedClassOption(this.streamOption);
        this.driftStream = (InstanceStream) getPreparedClassOption(this.driftstreamOption);
        this.random = new Random(this.randomSeedOption.getValue());
        numberInstanceStream = 0;
        if (this.alphaOption.getValue() != 0.0) {
            this.widthOption.setValue((int) (1 / Math.tan(this.alphaOption.getValue() * Math.PI / 180)));
        }
        // generate header
        Instances first = this.inputStream.getHeader();
        Instances second = this.driftStream.getHeader();
        FastVector newAttributes = new FastVector();
        for (int i = 0; i < first.numAttributes() - 1; i++) {
            newAttributes.addElement(first.attribute(i));
        }
        for (int i = 0; i < second.numAttributes() - 1; i++) {
            newAttributes.addElement(second.attribute(i));
        }
        Attribute classLabels;
        if (first.numClasses() < second.numClasses()) {
            classLabels = second.classAttribute();
        } else {
            classLabels = first.classAttribute();
        }
        newAttributes.addElement(classLabels);
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), newAttributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
        restart();
    }
void moa.streams.ConceptDriftRealStream.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 196 of file ConceptDriftRealStream.java.
References moa.streams.ConceptDriftRealStream.driftInstance, moa.streams.ConceptDriftRealStream.driftStream, moa.streams.ConceptDriftRealStream.inputInstance, moa.streams.ConceptDriftRealStream.inputStream, moa.streams.InstanceStream.nextInstance(), moa.streams.ConceptDriftRealStream.numberInstanceStream, and moa.streams.InstanceStream.restart().
Referenced by moa.streams.ConceptDriftRealStream.prepareForUseImpl().
{
        this.inputStream.restart();
        this.driftStream.restart();
        numberInstanceStream = 0;
        this.inputInstance = this.inputStream.nextInstance();
        this.driftInstance = this.driftStream.nextInstance();
    }
Member Data Documentation
FloatOption moa.streams.ConceptDriftRealStream.alphaOption
Initial value:
 new FloatOption("alpha",
            'a', "Angle alpha of change grade.", 0.0, 0.0, 90.0)
Definition at line 74 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.prepareForUseImpl().
Instance moa.streams.ConceptDriftRealStream.driftInstance [protected]
Definition at line 98 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance(), and moa.streams.ConceptDriftRealStream.restart().
InstanceStream moa.streams.ConceptDriftRealStream.driftStream [protected]
Definition at line 88 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.isRestartable(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), and moa.streams.ConceptDriftRealStream.restart().
ClassOption moa.streams.ConceptDriftRealStream.driftstreamOption
Initial value:
 new ClassOption("driftstream", 'd',
            "Concept drift Stream.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 70 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.prepareForUseImpl().
Instance moa.streams.ConceptDriftRealStream.inputInstance [protected]
Definition at line 96 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance(), and moa.streams.ConceptDriftRealStream.restart().
InstanceStream moa.streams.ConceptDriftRealStream.inputStream [protected]
Definition at line 86 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.isRestartable(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), and moa.streams.ConceptDriftRealStream.restart().
int moa.streams.ConceptDriftRealStream.numberInstanceStream [protected]
Definition at line 92 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), and moa.streams.ConceptDriftRealStream.restart().
IntOption moa.streams.ConceptDriftRealStream.positionOption
Initial value:
 new IntOption("position",
            'p', "Central position of concept drift change.", 0)
Definition at line 77 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance().
Random moa.streams.ConceptDriftRealStream.random [protected]
Definition at line 90 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance(), and moa.streams.ConceptDriftRealStream.prepareForUseImpl().
IntOption moa.streams.ConceptDriftRealStream.randomSeedOption
Initial value:
 new IntOption("randomSeed", 'r',
            "Seed for random noise.", 1)
Definition at line 83 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.prepareForUseImpl().
final long moa.streams.ConceptDriftRealStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 64 of file ConceptDriftRealStream.java.
InstancesHeader moa.streams.ConceptDriftRealStream.streamHeader [protected]
Definition at line 94 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.getHeader(), and moa.streams.ConceptDriftRealStream.prepareForUseImpl().
ClassOption moa.streams.ConceptDriftRealStream.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to add concept drift.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 66 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.prepareForUseImpl().
IntOption moa.streams.ConceptDriftRealStream.widthOption
Initial value:
 new IntOption("width",
            'w', "Width of concept drift change.", 1000)
Definition at line 80 of file ConceptDriftRealStream.java.
Referenced by moa.streams.ConceptDriftRealStream.nextInstance(), and moa.streams.ConceptDriftRealStream.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/ConceptDriftRealStream.java