MOA: moa.clusterers.clustree.ClusTree Class Reference
moa.clusterers.clustree.ClusTree Class Reference
Citation: ClusTree: Philipp Kranen, Ira Assent, Corinna Baldauf, Thomas Seidl: The ClusTree: indexing micro-clusters for anytime stream mining.
Classes
class BestMergeInNode
A class to code the return value of searching the smallest merge in a node.
Public Member Functions
void resetLearningImpl ()
boolean isRandomizable ()
void getModelDescription (StringBuilder out, int indent)
double[] getVotesForInstance (Instance inst)
boolean implementsMicroClusterer ()
void trainOnInstanceImpl (Instance instance)
void insert (ClusKernel newPoint, Budget budget, long timestamp)
Insert a new point in the Tree.
int getNumRootSplits ()
Return the number of time the tree has grown in size.
int getHeight ()
Return the current height of the tree.
Clustering getMicroClusteringResult ()
Clustering getClusteringResult ()
Clustering getClustering (long currentTime, int targetLevel)
Public Attributes
IntOption horizonOption
IntOption maxHeightOption
Protected Member Functions
int getDefaultHeight ()
Measurement[] getModelMeasurementsImpl ()
Protected Attributes
Node root
The root node of the tree.
double negLambda
Parameter for the weighting function use to weight the entries.
int maxHeight
The maximal height of the tree.
boolean breadthFirstStrat = false
Parameter to determine wich strategy to use.
Private Member Functions
Entry insertBreadthFirst (ClusKernel newPoint, Budget budget, long timestamp)
insert newPoint into the tree using the BreadthFirst strategy, i.e.
boolean existsOutdatedEntryOnPath (Node node)
This method checks if there is an outdated (or empty) entry on the path from node to root.
void updateToTop (Node toUpdate)
recalculates data for all entries, that lie on the path from the root to the Entry toUpdate.
Entry insertHereWithSplit (Entry toInsert, Node insertNode, long timestamp)
Method called by insertBreadthFirst.
Entry insertHere (Entry newEntry, Node currentNode, Entry parentEntry, ClusKernel carriedBuffer, Budget budget, long timestamp)
Node findBestLeafNode (ClusKernel newPoint)
This method calculates the distances between the new point and each Entry in a leaf node.
ArrayList< Node > collectLeafNodes (Node curr)
Entry insert (ClusKernel pointToInsert, ClusKernel carriedBuffer, Node currentNode, Entry parentEntry, Budget budget, long timestamp)
void mergeEntryWithoutSplit (Node node, Entry newEntry, long timestamp)
Inserts an Entry into a Node without inducing a split.
BestMergeInNode calculateBestMergeInNode (Node node)
Calculates the best merge possible between two nodes in a node.
boolean hasMaximalSize ()
Entry split (Entry newEntry, Node node, Entry parentEntry, long timestamp)
Performs a (2,2) split on the given node with the given entry.
void cleanUp (Node currentNode, int level)
Private Attributes
int numberDimensions
Dimensionality of the data points managed by this tree.
int height
The current height of the tree.
int numRootSplits
This variable is used to keep the inverse height that is stored in every node correct.
double weightThreshold = 0.05
The threshold for the weighting of an Entry.
int numberInsertions
Number of points inserted into the tree.
long timestamp
Entry alsoUpdate
Static Private Attributes
static final long serialVersionUID = 1L
static int INSERTIONS_BETWEEN_CLEANUPS = 10000
Detailed Description
Citation: ClusTree: Philipp Kranen, Ira Assent, Corinna Baldauf, Thomas Seidl: The ClusTree: indexing micro-clusters for anytime stream mining.
Knowl. Inf. Syst. 29(2): 249-272 (2011)
Definition at line 38 of file ClusTree.java.
Member Function Documentation
BestMergeInNode moa.clusterers.clustree.ClusTree.calculateBestMergeInNode (Node node) [private]
Calculates the best merge possible between two nodes in a node.
This means that the pair with the smallest distance is found.
Parameters:
node The node in which these two entries have to be found.
Returns:
An object which encodes the two position of the entries with the smallest distance in the node and the distance between them.
See also:
BestMergeInNode
Entry.calcDistance(tree.Entry)
Definition at line 566 of file ClusTree.java.
References moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.Node.getEntries(), and moa.clusterers.clustree.Node.numFreeEntries().
Referenced by moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit().
{
        assert (node.numFreeEntries() == 0);
        Entry[] entries = node.getEntries();
        int toMerge1 = -1;
        int toMerge2 = -1;
        double distanceBetweenMergeEntries = Double.NaN;
        double minDistance = Double.MAX_VALUE;
        for (int i = 0; i < entries.length; i++) {
            Entry e1 = entries[i];
            for (int j = i + 1; j < entries.length; j++) {
                Entry e2 = entries[j];
                double distance = e1.calcDistance(e2);
                if (distance < minDistance) {
                    toMerge1 = i;
                    toMerge2 = j;
                    distanceBetweenMergeEntries = distance;
                }
            }
        }
        assert (toMerge1 != -1 && toMerge2 != -1);
        if (Double.isNaN(distanceBetweenMergeEntries)) {
            throw new RuntimeException("The minimal distance between two "
                    + "Entrys in a Node was Double.MAX_VAUE. That can hardly "
                    + "be right.");
        }
        return new BestMergeInNode(toMerge1, toMerge2,
                distanceBetweenMergeEntries);
    }
void moa.clusterers.clustree.ClusTree.cleanUp (Node currentNode, int level) [private]
Definition at line 722 of file ClusTree.java.
References moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.ClusTree.maxHeight, and moa.clusterers.clustree.Entry.setChild().
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        if (currentNode == null) {
            return;
        }
        Entry[] entries = currentNode.getEntries();
        if (level == this.maxHeight) {
            for (int i = 0; i < entries.length; i++) {
                Entry e = entries[i];
                e.setChild(null);
            }
        } else {
            for (int i = 0; i < entries.length; i++) {
                Entry e = entries[i];
                cleanUp(e.getChild(), level + 1);
            }
        }
    }
ArrayList<Node> moa.clusterers.clustree.ClusTree.collectLeafNodes (Node curr) [private]
Definition at line 442 of file ClusTree.java.
References moa.clusterers.clustree.Node.getEntries(), and moa.clusterers.clustree.Node.isLeaf().
Referenced by moa.clusterers.clustree.ClusTree.findBestLeafNode().
{
        ArrayList<Node> toReturn = new ArrayList<Node>();
        if (curr==null)
            return toReturn;
        if  (curr.isLeaf()){
            toReturn.add(curr);
            return toReturn;
        }
        else{
            for (Entry e : curr.getEntries())
                toReturn.addAll(collectLeafNodes(e.getChild()));
            return toReturn;
        }
    }
boolean moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath (Node node) [private]
This method checks if there is an outdated (or empty) entry on the path from node to root.
It updates the weights of nodes on path and then checks if it is outdated.
Parameters:
node
Returns:
true if an outdated/empty entry exists on the path
Definition at line 249 of file ClusTree.java.
References moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getIrrelevantEntry(), moa.clusterers.clustree.Entry.getNode(), moa.clusterers.clustree.Entry.getParentEntry(), moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.Node.numFreeEntries(), moa.clusterers.clustree.ClusTree.root, moa.clusterers.clustree.ClusTree.timestamp, and moa.clusterers.clustree.ClusTree.weightThreshold.
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst().
{
        if (node == root){
            node.makeOlder(timestamp, negLambda);
            return node.getIrrelevantEntry(this.weightThreshold)!=null;
        }
        do{
            node = node.getEntries()[0].getParentEntry().getNode();
            node.makeOlder(timestamp, negLambda);
            for (Entry e : node.getEntries()){
                e.recalculateData();
            }
            if (node.numFreeEntries()>0)
                return true;
            if (node.getIrrelevantEntry(this.weightThreshold)!=null)
                return true;
        }while(node.getEntries()[0].getParentEntry()!=null);
        return false;
    }
Node moa.clusterers.clustree.ClusTree.findBestLeafNode (ClusKernel newPoint) [private]
This method calculates the distances between the new point and each Entry in a leaf node.
It returns the node that contains the entry with the smallest distance to the new point.
Parameters:
newPoint
Returns:
best fitting node
Definition at line 427 of file ClusTree.java.
References moa.clusterers.clustree.ClusKernel.calcDistance(), moa.clusterers.clustree.ClusTree.collectLeafNodes(), and moa.clusterers.clustree.ClusTree.root.
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst().
{
        double minDist = Double.MAX_VALUE;
        Node bestFit = null;
        for (Node e: collectLeafNodes(root)){
            if (newPoint.calcDistance(e.nearestEntry(newPoint).getData())<minDist){
                bestFit = e;
                minDist = newPoint.calcDistance(e.nearestEntry(newPoint).getData());
            }
        }
        if (bestFit!=null)
            return bestFit;
        else
            return root;
    }
Clustering moa.clusterers.clustree.ClusTree.getClustering (long currentTime, int targetLevel)
Parameters:
currentTime The current time
Returns:
The kernels at the given level as a clustering.
Definition at line 761 of file ClusTree.java.
References moa.clusterers.clustree.Entry.add(), moa.cluster.Clustering.add(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Entry.getData(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getLevel(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.Entry.isIrrelevant(), moa.clusterers.clustree.Node.isLeaf(), moa.clusterers.clustree.Entry.makeOlder(), moa.clusterers.clustree.ClusTree.maxHeight, moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.ClusTree.root, and moa.clusterers.clustree.ClusTree.weightThreshold.
Referenced by moa.clusterers.clustree.ClusTree.getMicroClusteringResult().
{
        if (root == null) {
            return null;
        }
        Clustering clusters = new Clustering();
        LinkedList<Node> queue = new LinkedList<Node>();
        queue.add(root);
        while (!queue.isEmpty()) {
            Node current = queue.remove();
           // if (current == null)
           //   continue;
            int currentLevel = current.getLevel(this);
            boolean isLeaf = (current.isLeaf() && currentLevel <= maxHeight)
                    || currentLevel == maxHeight;
            if (currentLevel == targetLevel
                    || (targetLevel == - 1 && isLeaf)) {
                assert (currentLevel <= maxHeight);
                Entry[] entries = current.getEntries();
                for (int i = 0; i < entries.length; i++) {
                    Entry entry = entries[i];
                    if (entry == null || entry.isEmpty()) {
                        continue;
                    }
                    // XXX
                    entry.makeOlder(currentTime, this.negLambda);
                    if (entry.isIrrelevant(this.weightThreshold))
                        continue;
                    ClusKernel gaussKernel = new ClusKernel(entry.getData());
//                  long diff = currentTime - entry.getTimestamp();
//                    if (diff > 0) {
//                        gaussKernel.makeOlder(diff, negLambda);
//                    }
                    clusters.add(gaussKernel);
                }
            } else if (!current.isLeaf()) {
                Entry[] entries = current.getEntries();
                for (int i = 0; i < entries.length; i++) {
                    Entry entry = entries[i];
                    if (entry.isEmpty()) {
                        continue;
                    }
                    if (entry.isIrrelevant(weightThreshold)) {
                        continue;
                    }
                    queue.add(entry.getChild());
                }
            }
        }
        return clusters;
    }
Clustering moa.clusterers.clustree.ClusTree.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 752 of file ClusTree.java.
{
        return null;
    }
int moa.clusterers.clustree.ClusTree.getDefaultHeight () [protected]
Definition at line 48 of file ClusTree.java.
{
        return 8;
    }
int moa.clusterers.clustree.ClusTree.getHeight ()
Return the current height of the tree.
This should never be greater than maxHeight.
Returns:
The height of the tree.
See also:
maxHeight
Definition at line 717 of file ClusTree.java.
References moa.clusterers.clustree.ClusTree.height, and moa.clusterers.clustree.ClusTree.maxHeight.
{
        assert (height <= maxHeight);
        return height;
    }
Clustering moa.clusterers.clustree.ClusTree.getMicroClusteringResult ()
Parameters:
currentTime The current time
Returns:
The kernels at the leaf level as a clustering
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 747 of file ClusTree.java.
References moa.clusterers.clustree.ClusTree.getClustering(), and moa.clusterers.clustree.ClusTree.timestamp.
{
        return getClustering(timestamp, -1);
    }
void moa.clusterers.clustree.ClusTree.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 125 of file ClusTree.java.
{
    }
Measurement [] moa.clusterers.clustree.ClusTree.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 116 of file ClusTree.java.
{
        return null;
    }
int moa.clusterers.clustree.ClusTree.getNumRootSplits ()
Return the number of time the tree has grown in size.
If the tree grows and is then cutted from a certain depth, it also counts.
Returns:
The number of times the root node was splitted.
Definition at line 707 of file ClusTree.java.
References moa.clusterers.clustree.ClusTree.numRootSplits.
Referenced by moa.clusterers.clustree.Node.getLevel().
{
        return numRootSplits;
    }
double [] moa.clusterers.clustree.ClusTree.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 128 of file ClusTree.java.
{
        return null;
    }
boolean moa.clusterers.clustree.ClusTree.hasMaximalSize () [private]
Definition at line 600 of file ClusTree.java.
References moa.clusterers.clustree.ClusTree.height, and moa.clusterers.clustree.ClusTree.maxHeight.
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst(), and moa.clusterers.clustree.ClusTree.insertHere().
{
        // TODO: Improve hasMaximalSize(). For now it just works somehow for testing.
        return this.height == this.maxHeight;
    }
boolean moa.clusterers.clustree.ClusTree.implementsMicroClusterer ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 133 of file ClusTree.java.
{
        return true;
    }
Entry moa.clusterers.clustree.ClusTree.insert (ClusKernel pointToInsert, ClusKernel carriedBuffer, Node currentNode, Entry parentEntry, Budget budget, long timestamp) [private]
Definition at line 458 of file ClusTree.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.aggregateCluster(), moa.clusterers.clustree.Entry.aggregateToBuffer(), moa.clusterers.clustree.ClusKernel.clear(), moa.clusterers.clustree.Entry.emptyBuffer(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.util.Budget.hasMoreTime(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusKernel.isEmpty(), moa.clusterers.clustree.Node.isLeaf(), moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.Node.nearestEntry(), moa.clusterers.clustree.ClusTree.negLambda, and moa.clusterers.clustree.ClusTree.numberDimensions.
{
        assert (currentNode != null);
        assert (currentNode.isLeaf()
                || currentNode.getEntries()[0].getChild() != null);
        currentNode.makeOlder(timestamp, this.negLambda);
        // This variable will be changed from to null to an actual reference
        // in the following if-else block if we have to insert something here,
        // either because this is a leaf, or because of split propagation.
        Entry toInsertHere = null;
        if (currentNode.isLeaf()) {
            // At the end of the function the entry will be inserted.
            toInsertHere = new Entry(this.numberDimensions,
                    pointToInsert, timestamp, parentEntry, currentNode);
        } else {
            Entry bestEntry = currentNode.nearestEntry(pointToInsert);
            bestEntry.aggregateCluster(pointToInsert, timestamp,
                    this.negLambda);
            boolean isCarriedBufferEmpty = carriedBuffer.isEmpty();
            Entry bestBufferEntry = null;
            if (!isCarriedBufferEmpty) {
                bestBufferEntry = currentNode.nearestEntry(carriedBuffer);
                bestBufferEntry.aggregateCluster(carriedBuffer, timestamp,
                        this.negLambda);
            }
            if (!budget.hasMoreTime()) {
                bestEntry.aggregateToBuffer(pointToInsert, timestamp,
                        this.negLambda);
                if (!isCarriedBufferEmpty) {
                    bestBufferEntry.aggregateToBuffer(carriedBuffer,
                            timestamp, this.negLambda);
                }
                return null;
            }
            // If the way of the buffer differs from the way of the point to
            // be inserted, leave the buffer here.
            if (!isCarriedBufferEmpty && (bestEntry != bestBufferEntry)) {
                bestBufferEntry.aggregateToBuffer(carriedBuffer, timestamp,
                        this.negLambda);
                carriedBuffer.clear();
            }
            // Take the buffer of the best entry for the point to be inserted
            // along.
            ClusKernel takeAlongBuffer = bestEntry.emptyBuffer(timestamp,
                    this.negLambda);
            carriedBuffer.add(takeAlongBuffer);
            // Recursive call.
            toInsertHere = insert(pointToInsert, carriedBuffer,
                    bestEntry.getChild(), bestEntry, budget, timestamp);
        }
        // If the above block has a new Entry for this place insert it.
        if (toInsertHere != null) {
            return this.insertHere(toInsertHere, currentNode, parentEntry,
                    carriedBuffer, budget, timestamp);
        }
        // If nothing else needs to be done in all the above levels
        // return null to signalize it.
        return null;
    }
void moa.clusterers.clustree.ClusTree.insert (ClusKernel newPoint, Budget budget, long timestamp)
Insert a new point in the Tree.
The point should be represented as a cluster with a single data point(i.e. N = 1). A Budget class is also given, which is informed of the number of operation the tree does, and informs the tree when it does not have time left and should stop the insertion.
Parameters:
newPoint The point to be inserted.
budget The budget and statistics recollector for the insertion.
timestamp The moment at which this point is inserted.
See also:
Kernel
Budget
Definition at line 170 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.ClusTree.breadthFirstStrat, moa.clusterers.clustree.ClusTree.cleanUp(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getRawLevel(), moa.clusterers.clustree.ClusTree.height, moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.INSERTIONS_BETWEEN_CLEANUPS, moa.clusterers.clustree.ClusTree.maxHeight, moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.ClusTree.numberInsertions, moa.clusterers.clustree.ClusTree.numRootSplits, moa.clusterers.clustree.ClusTree.root, and moa.clusterers.clustree.Entry.setNode().
Referenced by moa.clusterers.clustree.ClusTree.insert(), and moa.clusterers.clustree.ClusTree.trainOnInstanceImpl().
{
        if (breadthFirstStrat){
            insertBreadthFirst(newPoint, budget, timestamp);
       }
        else{
            Entry rootEntry = new Entry(this.numberDimensions,
                    root, timestamp, null, null);
            ClusKernel carriedBuffer = new ClusKernel(this.numberDimensions);
            Entry toInsertHere = insert(newPoint, carriedBuffer, root, rootEntry,
                    budget, timestamp);
            if (toInsertHere != null) {
                this.numRootSplits++;
                this.height += this.height < this.maxHeight ? 1 : 0;
                Node newRoot = new Node(this.numberDimensions,
                        toInsertHere.getChild().getRawLevel() + 1);
                newRoot.addEntry(rootEntry, timestamp);
                newRoot.addEntry(toInsertHere, timestamp);
                rootEntry.setNode(newRoot);
                toInsertHere.setNode(newRoot);
                this.root = newRoot;
            }
        }
        this.numberInsertions++;
        if (this.numberInsertions % INSERTIONS_BETWEEN_CLEANUPS == 0) {
            cleanUp(this.root, 0);
        }
    }
Entry moa.clusterers.clustree.ClusTree.insertBreadthFirst (ClusKernel newPoint, Budget budget, long timestamp) [private]
insert newPoint into the tree using the BreadthFirst strategy, i.e.
: insert into the closest entry in a leaf node.
Parameters:
newPoint
budget
timestamp
Returns:
Definition at line 209 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.findBestLeafNode(), moa.clusterers.clustree.ClusKernel.getCenter(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getIrrelevantEntry(), moa.clusterers.clustree.Entry.getNode(), moa.clusterers.clustree.Entry.getParentEntry(), moa.clusterers.clustree.ClusTree.hasMaximalSize(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit(), moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.Node.numFreeEntries(), moa.clusterers.clustree.Entry.overwriteOldEntry(), moa.clusterers.clustree.ClusTree.updateToTop(), and moa.clusterers.clustree.ClusTree.weightThreshold.
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        //check all leaf nodes and get the one with the closest entry to newPoint
        Node bestFit = findBestLeafNode(newPoint);
        bestFit.makeOlder(timestamp, negLambda);
        Entry parent = bestFit.getEntries()[0].getParentEntry();
        // Search for an Entry with a weight under the threshold.
        Entry irrelevantEntry = bestFit.getIrrelevantEntry(this.weightThreshold);
        int numFreeEntries = bestFit.numFreeEntries();
        Entry newEntry = new Entry(newPoint.getCenter().length,
                newPoint, timestamp, parent, bestFit);
        //if there is space, add it to the node ( doesn't ever occur, since nodes are created with 3 entries)
        if (numFreeEntries>0){
            bestFit.addEntry(newEntry, timestamp);
        }
        //if outdated cluster in this best fitting node, replace it
         else if (irrelevantEntry != null) {
            irrelevantEntry.overwriteOldEntry(newEntry);
        }
        //if there is space/outdated cluster on path to top, split. Else merge without split
        else {
            if (existsOutdatedEntryOnPath(bestFit)||!this.hasMaximalSize()){
                // We have to split.
                insertHereWithSplit(newEntry, bestFit, timestamp);
            }
            else {
                mergeEntryWithoutSplit(bestFit, newEntry,
                        timestamp);
            }
        }
        //update all nodes on path to top.
        if (bestFit.getEntries()[0].getParentEntry()!=null)
            updateToTop(bestFit.getEntries()[0].getParentEntry().getNode());
        return null;
    }
Entry moa.clusterers.clustree.ClusTree.insertHere (Entry newEntry, Node currentNode, Entry parentEntry, ClusKernel carriedBuffer, Budget budget, long timestamp) [private]
Definition at line 347 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.Entry.aggregateEntry(), moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.ClusTree.calculateBestMergeInNode(), moa.clusterers.clustree.ClusTree.BestMergeInNode.distance, moa.clusterers.clustree.ClusTree.BestMergeInNode.entryPos1, moa.clusterers.clustree.ClusTree.BestMergeInNode.entryPos2, moa.clusterers.clustree.Node.getIrrelevantEntry(), moa.clusterers.clustree.ClusTree.hasMaximalSize(), moa.clusterers.clustree.util.Budget.hasMoreTime(), moa.clusterers.clustree.ClusKernel.isEmpty(), moa.clusterers.clustree.Node.isLeaf(), moa.clusterers.clustree.Node.mergeEntries(), moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit(), moa.clusterers.clustree.Entry.mergeWith(), moa.clusterers.clustree.Node.nearestEntry(), moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.Node.numFreeEntries(), moa.clusterers.clustree.Entry.overwriteOldEntry(), moa.clusterers.clustree.ClusTree.split(), and moa.clusterers.clustree.ClusTree.weightThreshold.
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        int numFreeEntries = currentNode.numFreeEntries();
        // Insert the buffer that we carry.
        if (!carriedBuffer.isEmpty()) {
            Entry bufferEntry = new Entry(this.numberDimensions,
                    carriedBuffer, timestamp, parentEntry, currentNode);
            if (numFreeEntries <= 1) {
                // Distance from buffer to entries.
                Entry nearestEntryToCarriedBuffer =
                        currentNode.nearestEntry(newEntry);
                double distanceNearestEntryToBuffer =
                        nearestEntryToCarriedBuffer.calcDistance(newEntry);
                // Distance between buffer and point to insert.
                double distanceBufferNewEntry =
                        newEntry.calcDistance(carriedBuffer);
                // Best distance between Entrys in the Node.
                BestMergeInNode bestMergeInNode =
                        calculateBestMergeInNode(currentNode);
                // See what the minimal distance is and do the correspoding
                // action.
                if (distanceNearestEntryToBuffer <= distanceBufferNewEntry
                        && distanceNearestEntryToBuffer <= bestMergeInNode.distance) {
                    // Aggregate buffer entry to nearest entry in node.
                    nearestEntryToCarriedBuffer.aggregateEntry(bufferEntry,
                            timestamp, this.negLambda);
                } else if (distanceBufferNewEntry <= distanceNearestEntryToBuffer
                        && distanceBufferNewEntry <= bestMergeInNode.distance) {
                    newEntry.mergeWith(bufferEntry);
                } else {
                    currentNode.mergeEntries(bestMergeInNode.entryPos1,
                            bestMergeInNode.entryPos2);
                    currentNode.addEntry(bufferEntry, timestamp);
                }
            } else {
                assert (currentNode.isLeaf());
                currentNode.addEntry(bufferEntry, timestamp);
            }
        }
        // Normally the insertion of the carries buffer does not change the
        // number of free entries, but in case of future changes we calculate
        // the number again.
        numFreeEntries = currentNode.numFreeEntries();
        // Search for an Entry with a weight under the threshold.
        Entry irrelevantEntry = currentNode.getIrrelevantEntry(this.weightThreshold);
        if (currentNode.isLeaf() && irrelevantEntry != null) {
            irrelevantEntry.overwriteOldEntry(newEntry);
        } else if (numFreeEntries >= 1) {
            currentNode.addEntry(newEntry, timestamp);
        } else {
            if (currentNode.isLeaf() && (this.hasMaximalSize()
                    || !budget.hasMoreTime())) {
                mergeEntryWithoutSplit(currentNode, newEntry,
                        timestamp);
            } else {
                // We have to split.
                return split(newEntry, currentNode, parentEntry, timestamp);
            }
        }
        return null;
    }
Entry moa.clusterers.clustree.ClusTree.insertHereWithSplit (Entry toInsert, Node insertNode, long timestamp) [private]
Method called by insertBreadthFirst.
Parameters:
toInsert
insertNode
timestamp
Returns:
Definition at line 289 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.ClusTree.alsoUpdate, moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getIrrelevantEntry(), moa.clusterers.clustree.Entry.getNode(), moa.clusterers.clustree.Entry.getParentEntry(), moa.clusterers.clustree.ClusTree.height, moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.ClusTree.maxHeight, moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.Node.numFreeEntries(), moa.clusterers.clustree.ClusTree.numRootSplits, moa.clusterers.clustree.Entry.overwriteOldEntry(), moa.clusterers.clustree.ClusTree.root, moa.clusterers.clustree.ClusTree.split(), and moa.clusterers.clustree.ClusTree.weightThreshold.
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst().
{
        //Handle root split
        if (insertNode.getEntries()[0].getParentEntry()==null){
            root.makeOlder(timestamp, negLambda);
            Entry irrelevantEntry = insertNode.getIrrelevantEntry(this.weightThreshold);
            int numFreeEntries = insertNode.numFreeEntries();
            if (irrelevantEntry != null) {
                irrelevantEntry.overwriteOldEntry(toInsert);
            }
            else if (numFreeEntries>0){
                insertNode.addEntry(toInsert, timestamp);
            }
            else{
                this.numRootSplits++;
                this.height += this.height < this.maxHeight ? 1 : 0;
                Entry oldRootEntry = new Entry(this.numberDimensions,
                        root, timestamp, null, null);
                Node newRoot = new Node(this.numberDimensions,
                        this.height);
                Entry newRootEntry = split(toInsert, root, oldRootEntry, timestamp);
                newRoot.addEntry(oldRootEntry, timestamp);
                newRoot.addEntry(newRootEntry, timestamp);
                this.root = newRoot;
                for (Entry c : oldRootEntry.getChild().getEntries())
                    c.setParentEntry(root.getEntries()[0]);
                for (Entry c : newRootEntry.getChild().getEntries())
                    c.setParentEntry(root.getEntries()[1]);
            }
            return null;
        }
        insertNode.makeOlder(timestamp, negLambda);
        Entry irrelevantEntry = insertNode.getIrrelevantEntry(this.weightThreshold);
        int numFreeEntries = insertNode.numFreeEntries();
        if (irrelevantEntry != null) {
            irrelevantEntry.overwriteOldEntry(toInsert);
        }
        else if (numFreeEntries>0){
            insertNode.addEntry(toInsert, timestamp);
        }
        else {
                // We have to split.
                Entry parentEntry = insertNode.getEntries()[0].getParentEntry();
                Entry residualEntry = split(toInsert, insertNode, parentEntry, timestamp);
                if (alsoUpdate!=null){
                    alsoUpdate = residualEntry;
                }
                Node nodeForResidualEntry = insertNode.getEntries()[0].getParentEntry().getNode();
                //recursive call
                return insertHereWithSplit(residualEntry, nodeForResidualEntry, timestamp);
        }
        //no Split
        return null;
    }
boolean moa.clusterers.clustree.ClusTree.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 120 of file ClusTree.java.
{
        return false;
    }
void moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit (Node node, Entry newEntry, long timestamp) [private]
Inserts an Entry into a Node without inducing a split.
Parameters:
node The node at which the entry is to be inserted.
newEntry The entry to be inserted.
timestamp The moment at which this occurs.
Definition at line 536 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.Entry.aggregateEntry(), moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.ClusTree.calculateBestMergeInNode(), moa.clusterers.clustree.ClusTree.BestMergeInNode.distance, moa.clusterers.clustree.ClusTree.BestMergeInNode.entryPos1, moa.clusterers.clustree.ClusTree.BestMergeInNode.entryPos2, moa.clusterers.clustree.Node.mergeEntries(), moa.clusterers.clustree.Node.nearestEntry(), and moa.clusterers.clustree.ClusTree.negLambda.
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst(), and moa.clusterers.clustree.ClusTree.insertHere().
{
        Entry nearestEntryToCarriedBuffer =
                node.nearestEntry(newEntry);
        double distanceNearestEntryToBuffer =
                nearestEntryToCarriedBuffer.calcDistance(newEntry);
        BestMergeInNode bestMergeInNode =
                calculateBestMergeInNode(node);
        if (distanceNearestEntryToBuffer < bestMergeInNode.distance) {
            nearestEntryToCarriedBuffer.aggregateEntry(newEntry, timestamp,
                    this.negLambda);
        } else {
            node.mergeEntries(bestMergeInNode.entryPos1,
                    bestMergeInNode.entryPos2);
            node.addEntry(newEntry, timestamp);
        }
    }
void moa.clusterers.clustree.ClusTree.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 102 of file ClusTree.java.
References moa.options.IntOption.getValue(), moa.clusterers.clustree.ClusTree.height, moa.clusterers.clustree.ClusTree.horizonOption, moa.clusterers.clustree.ClusTree.maxHeight, moa.clusterers.clustree.ClusTree.maxHeightOption, moa.clusterers.clustree.ClusTree.negLambda, moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.ClusTree.numberInsertions, moa.clusterers.clustree.ClusTree.numRootSplits, moa.clusterers.clustree.ClusTree.root, moa.clusterers.clustree.ClusTree.timestamp, and moa.clusterers.clustree.ClusTree.weightThreshold.
{
        negLambda = (1.0 / (double) horizonOption.getValue())
                * (Math.log(weightThreshold) / Math.log(2));
        maxHeight = maxHeightOption.getValue();
        numberDimensions = -1;
        root = null;
        timestamp = 0;
        height = 0;
        numRootSplits = 0;
        numberInsertions = 0;
    }
Entry moa.clusterers.clustree.ClusTree.split (Entry newEntry, Node node, Entry parentEntry, long timestamp) [private]
Performs a (2,2) split on the given node with the given entry.
This implementation only works if the nodes have three entries each. The split will generate two new nodes. One of them will be put where the old node was, and for the other a new Entry will be generated and returned.
Parameters:
newEntry The entry to be added to the node.
node The node that is going to be splitted.
parentEntry The entry in the tree that points at the node that is going to be splitted.
timestamp The moment at which this split occurs.
Returns:
An entry which points at the second node created in the split. This entry has to be introduced later in the tree.
Definition at line 619 of file ClusTree.java.
References moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getRawLevel(), moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.Node.numFreeEntries(), moa.clusterers.clustree.Entry.recalculateData(), and moa.clusterers.clustree.Entry.setChild().
Referenced by moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.insertHereWithSplit().
{
        // The implemented split function only works in trees where node
        // have three entries.
        // Splitting only makes sense on full nodes.
        assert (node.numFreeEntries() == 0);
        assert (parentEntry.getChild() == node);
        // All the entries we have to separate in two nodes.
        Entry[] allEntries = new Entry[4];
        Entry[] nodeEntries = node.getEntries();
        for (int i = 0; i < nodeEntries.length; i++) {
            allEntries[i] = new Entry(nodeEntries[i]);
        }
        allEntries[3] = newEntry;
        // Clear the given node, since we are going to refill it later.
        node = new Node(this.numberDimensions, node.getRawLevel());
        // Calculate the distance of all the possible pairings, since we want
        // to do a (2,2) split.
        double select01 = allEntries[0].calcDistance(allEntries[1])
                + allEntries[2].calcDistance(allEntries[3]);
        double select02 = allEntries[0].calcDistance(allEntries[2])
                + allEntries[1].calcDistance(allEntries[3]);
        double select03 = allEntries[0].calcDistance(allEntries[3])
                + allEntries[1].calcDistance(allEntries[2]);
        // See which of the pairings is minimal and distribute the entries
        // accordingly.
        Node residualNode = new Node(this.numberDimensions,
                node.getRawLevel());
        if (select01 < select02) {
            if (select01 < select03) {//select01 smallest
                node.addEntry(allEntries[0], timestamp);
                node.addEntry(allEntries[1], timestamp);
                residualNode.addEntry(allEntries[2], timestamp);
                residualNode.addEntry(allEntries[3], timestamp);
            } else {//select03 smallest
                node.addEntry(allEntries[0], timestamp);
                node.addEntry(allEntries[3], timestamp);
                residualNode.addEntry(allEntries[1], timestamp);
                residualNode.addEntry(allEntries[2], timestamp);
            }
        } else {
            if (select02 < select03) {//select02 smallest
                node.addEntry(allEntries[0], timestamp);
                node.addEntry(allEntries[2], timestamp);
                residualNode.addEntry(allEntries[1], timestamp);
                residualNode.addEntry(allEntries[3], timestamp);
            } else {//select03 smallest
                node.addEntry(allEntries[0], timestamp);
                node.addEntry(allEntries[3], timestamp);
                residualNode.addEntry(allEntries[1], timestamp);
                residualNode.addEntry(allEntries[2], timestamp);
            }
        }
        // Set the other node into the tree.
        parentEntry.setChild(node);
        parentEntry.recalculateData();
        int count = 0;
        for (Entry e : node.getEntries()){
            e.setParentEntry(parentEntry);
            if (e.getData().getN() != 0)
                count++;
        }
        //System.out.println(count);
        // Generate a new entry for the residual node.
        Entry residualEntry = new Entry(this.numberDimensions,
                residualNode, timestamp, parentEntry, node);
        count=0;
        for (Entry e: residualNode.getEntries()){
            e.setParentEntry(residualEntry);
            if (e.getData().getN() != 0)
                count++;
        }
        //System.out.println(count);
        return residualEntry;
    }
void moa.clusterers.clustree.ClusTree.trainOnInstanceImpl (Instance instance) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 140 of file ClusTree.java.
References moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.numberDimensions, moa.clusterers.clustree.ClusTree.root, and moa.clusterers.clustree.ClusTree.timestamp.
{
        timestamp++;
        //TODO check if instance contains label
        if(root == null){
            numberDimensions = instance.numAttributes();
            root = new Node(numberDimensions, 0);
        }
        else{
            if(numberDimensions!=instance.numAttributes())
                System.out.println("Wrong dimensionality, expected:"+numberDimensions+ "found:"+instance.numAttributes());
        }
        ClusKernel newPointAsKernel = new ClusKernel(instance.toDoubleArray(), numberDimensions);
        insert(newPointAsKernel, new SimpleBudget(1000),timestamp);
    }
void moa.clusterers.clustree.ClusTree.updateToTop (Node toUpdate) [private]
recalculates data for all entries, that lie on the path from the root to the Entry toUpdate.
Definition at line 272 of file ClusTree.java.
References moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Entry.getNode(), and moa.clusterers.clustree.Entry.getParentEntry().
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst().
{
        while(toUpdate!=null){
            for (Entry e: toUpdate.getEntries())
                e.recalculateData();
            if (toUpdate.getEntries()[0].getParentEntry()==null)
                break;
            toUpdate=toUpdate.getEntries()[0].getParentEntry().getNode();
        }
    }
Member Data Documentation
Entry moa.clusterers.clustree.ClusTree.alsoUpdate [private]
Definition at line 99 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.insertHereWithSplit().
boolean moa.clusterers.clustree.ClusTree.breadthFirstStrat = false [protected]
Parameter to determine wich strategy to use.
Definition at line 96 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.insert().
int moa.clusterers.clustree.ClusTree.height [private]
The current height of the tree.
Should always be smaller than maxHeight.
Definition at line 69 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.getHeight(), moa.clusterers.clustree.ClusTree.hasMaximalSize(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
IntOption moa.clusterers.clustree.ClusTree.horizonOption
Initial value:
 new IntOption("horizon",
            'h', "Range of the window.", 1000)
Definition at line 41 of file ClusTree.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
int moa.clusterers.clustree.ClusTree.INSERTIONS_BETWEEN_CLEANUPS = 10000 [static, private]
Definition at line 52 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.insert().
int moa.clusterers.clustree.ClusTree.maxHeight [protected]
The maximal height of the tree.
Definition at line 73 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.cleanUp(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.ClusTree.getHeight(), moa.clusterers.clustree.ClusTree.hasMaximalSize(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
IntOption moa.clusterers.clustree.ClusTree.maxHeightOption
Initial value:
 new IntOption(
            "maxHeight", 'H',
            "The maximal height of the tree", getDefaultHeight())
Definition at line 44 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.resetLearningImpl().
double moa.clusterers.clustree.ClusTree.negLambda [protected]
Parameter for the weighting function use to weight the entries.
Definition at line 65 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
int moa.clusterers.clustree.ClusTree.numberDimensions [private]
Dimensionality of the data points managed by this tree.
Definition at line 61 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.ClusTree.resetLearningImpl(), moa.clusterers.clustree.ClusTree.split(), and moa.clusterers.clustree.ClusTree.trainOnInstanceImpl().
int moa.clusterers.clustree.ClusTree.numberInsertions [private]
Number of points inserted into the tree.
Definition at line 89 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.insert(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
int moa.clusterers.clustree.ClusTree.numRootSplits [private]
This variable is used to keep the inverse height that is stored in every node correct.
Definition at line 78 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.getNumRootSplits(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
Node moa.clusterers.clustree.ClusTree.root [protected]
The root node of the tree.
Definition at line 56 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.findBestLeafNode(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.ClusTree.resetLearningImpl(), and moa.clusterers.clustree.ClusTree.trainOnInstanceImpl().
final long moa.clusterers.clustree.ClusTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file ClusTree.java.
long moa.clusterers.clustree.ClusTree.timestamp [private]
Definition at line 90 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.getMicroClusteringResult(), moa.clusterers.clustree.ClusTree.resetLearningImpl(), and moa.clusterers.clustree.ClusTree.trainOnInstanceImpl().
double moa.clusterers.clustree.ClusTree.weightThreshold = 0.05 [private]
The threshold for the weighting of an Entry.
An Entry is irrelevant, if it is in a leaf and the weightedN of the data Cluster is smaller than this threshold.
See also:
Entry.data
Reimplemented in moa.clusterers.outliers.AnyOut.AnyOutCore.
Definition at line 85 of file ClusTree.java.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.resetLearningImpl().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustree/ClusTree.java