MOA: moa.options.MultiChoiceOption Class Reference
moa.options.MultiChoiceOption Class Reference
Multi choice option.
Public Member Functions
MultiChoiceOption (String name, char cliChar, String purpose, String[] optionLabels, String[] optionDescriptions, int defaultOptionIndex)
String getDefaultCLIString ()
Gets the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
void setChosenLabel (String label)
void setChosenIndex (int index)
String[] getOptionLabels ()
String getChosenLabel ()
int getChosenIndex ()
JComponent getEditComponent ()
Gets the GUI component to edit.
Protected Attributes
String[] optionLabels
String[] optionDescriptions
int defaultOptionIndex
int chosenOptionIndex
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Multi choice option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file MultiChoiceOption.java.
Constructor & Destructor Documentation
moa.options.MultiChoiceOption.MultiChoiceOption (String name, char cliChar, String purpose, String[] optionLabels, String[] optionDescriptions, int defaultOptionIndex)
Definition at line 44 of file MultiChoiceOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        if (optionLabels.length != optionDescriptions.length) {
            throw new IllegalArgumentException("Labels/descriptions mismatch.");
        }
        this.optionLabels = optionLabels.clone();
        this.optionDescriptions = optionDescriptions.clone();
        this.defaultOptionIndex = defaultOptionIndex;
        resetToDefault();
    }
Member Function Documentation
int moa.options.MultiChoiceOption.getChosenIndex ()
Definition at line 102 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.chosenOptionIndex.
Referenced by moa.classifiers.trees.ORTO.OptionNode.aggregate(), moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.trees.ORTO.OptionNode.getPrediction(), moa.classifiers.rules.RuleClassifier.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.lazy.kNN.getVotesForInstance(), moa.classifiers.core.driftdetection.HDDM_A_Test.input(), moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input(), moa.gui.MultiChoiceOptionEditComponent.MultiChoiceOptionEditComponent(), moa.classifiers.trees.RandomHoeffdingTree.newLearningNode(), moa.classifiers.trees.LimAttHoeffdingTree.newLearningNode(), moa.classifiers.rules.AMRulesRegressor.newRule(), moa.streams.filters.ReplacingMissingValuesFilter.nextInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), moa.classifiers.functions.SPegasos.resetLearningImpl(), moa.classifiers.functions.SGDMultiClass.resetLearningImpl(), moa.classifiers.functions.SGD.resetLearningImpl(), moa.gui.MultiChoiceOptionEditComponent.setEditState(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        return this.chosenOptionIndex;
    }
String moa.options.MultiChoiceOption.getChosenLabel ()
Definition at line 98 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.chosenOptionIndex, and moa.options.MultiChoiceOption.optionLabels.
Referenced by moa.classifiers.trees.ORTO.OptionNode.aggregate(), moa.tasks.Plot.createScript(), moa.classifiers.rules.AMRulesRegressor.getModelDescription(), and moa.options.MultiChoiceOption.getValueAsCLIString().
{
        return this.optionLabels[this.chosenOptionIndex];
    }
String moa.options.MultiChoiceOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 58 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.defaultOptionIndex, and moa.options.MultiChoiceOption.optionLabels.
{
        return this.optionLabels[this.defaultOptionIndex];
    }
JComponent moa.options.MultiChoiceOption.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Reimplemented from moa.options.AbstractOption.
Definition at line 107 of file MultiChoiceOption.java.
{
        return new MultiChoiceOptionEditComponent(this);
    }
String [] moa.options.MultiChoiceOption.getOptionLabels ()
Definition at line 94 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.optionLabels.
Referenced by moa.gui.MultiChoiceOptionEditComponent.MultiChoiceOptionEditComponent().
{
        return this.optionLabels.clone();
    }
String moa.options.MultiChoiceOption.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Definition at line 63 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.getChosenLabel().
{
        return getChosenLabel();
    }
void moa.options.MultiChoiceOption.setChosenIndex (int index)
Definition at line 87 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.chosenOptionIndex, and moa.options.MultiChoiceOption.optionLabels.
Referenced by moa.gui.MultiChoiceOptionEditComponent.applyState(), and moa.options.MultiChoiceOption.setValueViaCLIString().
{
        if ((index < 0) || (index >= this.optionLabels.length)) {
            throw new IndexOutOfBoundsException();
        }
        this.chosenOptionIndex = index;
    }
void moa.options.MultiChoiceOption.setChosenLabel (String label)
Definition at line 76 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.chosenOptionIndex, and moa.options.MultiChoiceOption.optionLabels.
Referenced by moa.options.MultiChoiceOption.setValueViaCLIString().
{
        label = label.trim();
        for (int i = 0; i < this.optionLabels.length; i++) {
            if (this.optionLabels[i].equals(label)) {
                this.chosenOptionIndex = i;
                return;
            }
        }
        throw new IllegalArgumentException("Label not recognised: " + label);
    }
void moa.options.MultiChoiceOption.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Definition at line 68 of file MultiChoiceOption.java.
References moa.options.MultiChoiceOption.setChosenIndex(), and moa.options.MultiChoiceOption.setChosenLabel().
Referenced by moa.gui.MultiChoiceOptionEditComponent.setEditState().
{
        try {
            setChosenIndex(Integer.parseInt(s.trim()));
        } catch (NumberFormatException nfe) {
            setChosenLabel(s);
        }
    }
Member Data Documentation
int moa.options.MultiChoiceOption.chosenOptionIndex [protected]
Definition at line 42 of file MultiChoiceOption.java.
Referenced by moa.options.MultiChoiceOption.getChosenIndex(), moa.options.MultiChoiceOption.getChosenLabel(), moa.options.MultiChoiceOption.setChosenIndex(), and moa.options.MultiChoiceOption.setChosenLabel().
int moa.options.MultiChoiceOption.defaultOptionIndex [protected]
Definition at line 40 of file MultiChoiceOption.java.
Referenced by moa.options.MultiChoiceOption.getDefaultCLIString().
String [] moa.options.MultiChoiceOption.optionDescriptions [protected]
Definition at line 38 of file MultiChoiceOption.java.
String [] moa.options.MultiChoiceOption.optionLabels [protected]
Definition at line 36 of file MultiChoiceOption.java.
Referenced by moa.options.MultiChoiceOption.getChosenLabel(), moa.options.MultiChoiceOption.getDefaultCLIString(), moa.options.MultiChoiceOption.getOptionLabels(), moa.options.MultiChoiceOption.setChosenIndex(), and moa.options.MultiChoiceOption.setChosenLabel().
final long moa.options.MultiChoiceOption.serialVersionUID = 1L [static, private]
Definition at line 34 of file MultiChoiceOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/MultiChoiceOption.java