MOA: moa.tasks.LearnModelRegression Class Reference
moa.tasks.LearnModelRegression Class Reference
Task for learning a model without any evaluation.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
LearnModelRegression ()
LearnModelRegression (Classifier learner, InstanceStream stream, int maxInstances, int numPasses)
Class<?> getTaskResultType ()
Gets the result type of this task.
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
IntOption maxInstancesOption
IntOption numPassesOption
IntOption memCheckFrequencyOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for learning a model without any evaluation.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 35 of file LearnModelRegression.java.
Constructor & Destructor Documentation
moa.tasks.LearnModelRegression.LearnModelRegression ()
Definition at line 64 of file LearnModelRegression.java.
{
    }
moa.tasks.LearnModelRegression.LearnModelRegression (Classifier learner, InstanceStream stream, int maxInstances, int numPasses)
Definition at line 67 of file LearnModelRegression.java.
References moa.tasks.LearnModelRegression.learnerOption, moa.tasks.LearnModelRegression.maxInstancesOption, moa.tasks.LearnModelRegression.numPassesOption, moa.options.AbstractClassOption.setCurrentObject(), moa.options.IntOption.setValue(), and moa.tasks.LearnModelRegression.streamOption.
{
        this.learnerOption.setCurrentObject(learner);
        this.streamOption.setCurrentObject(stream);
        this.maxInstancesOption.setValue(maxInstances);
        this.numPassesOption.setValue(numPasses);
    }
Member Function Documentation
Object moa.tasks.LearnModelRegression.doMainTask (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 81 of file LearnModelRegression.java.
References moa.classifiers.Classifier.copy(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.hasMoreInstances(), moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.LearnModelRegression.learnerOption, moa.tasks.LearnModelRegression.maxInstancesOption, moa.streams.InstanceStream.nextInstance(), moa.tasks.LearnModelRegression.numPassesOption, moa.streams.InstanceStream.restart(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.LearnModelRegression.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), and moa.classifiers.Classifier.trainOnInstance().
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        learner.setModelContext(stream.getHeader());
        int numPasses = this.numPassesOption.getValue();
        int maxInstances = this.maxInstancesOption.getValue();
        for (int pass = 0; pass < numPasses; pass++) {
            long instancesProcessed = 0;
            monitor.setCurrentActivity("Training learner"
                    + (numPasses > 1 ? (" (pass " + (pass + 1) + "/"
                    + numPasses + ")") : "") + "...", -1.0);
            if (pass > 0) {
                stream.restart();
            }
            while (stream.hasMoreInstances()
                    && ((maxInstances < 0) || (instancesProcessed < maxInstances))) {
                learner.trainOnInstance(stream.nextInstance());
                instancesProcessed++;
                if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                    if (maxInstances > 0) {
                        long maxRemaining = maxInstances - instancesProcessed;
                        if ((estimatedRemainingInstances < 0)
                                || (maxRemaining < estimatedRemainingInstances)) {
                            estimatedRemainingInstances = maxRemaining;
                        }
                    }
                    monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                            : (double) instancesProcessed
                            / (double) (instancesProcessed + estimatedRemainingInstances));
                    if (monitor.resultPreviewRequested()) {
                        monitor.setLatestResultPreview(learner.copy());
                    }
                }
            }
        }
        learner.setModelContext(stream.getHeader());
        return learner;
    }
String moa.tasks.LearnModelRegression.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 38 of file LearnModelRegression.java.
{
        return "Learns a model from a stream.";
    }
Class<?> moa.tasks.LearnModelRegression.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 76 of file LearnModelRegression.java.
{
        return Regressor.class;
    }
Member Data Documentation
ClassOption moa.tasks.LearnModelRegression.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Regressor.class, "trees.FIMTDD")
Definition at line 44 of file LearnModelRegression.java.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), and moa.tasks.LearnModelRegression.LearnModelRegression().
IntOption moa.tasks.LearnModelRegression.maxInstancesOption
Initial value:
 new IntOption("maxInstances", 'm',
            "Maximum number of instances to train on per pass over the data.",
            10000000, 0, Integer.MAX_VALUE)
Definition at line 51 of file LearnModelRegression.java.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), and moa.tasks.LearnModelRegression.LearnModelRegression().
IntOption moa.tasks.LearnModelRegression.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Definition at line 59 of file LearnModelRegression.java.
IntOption moa.tasks.LearnModelRegression.numPassesOption
Initial value:
 new IntOption("numPasses", 'p',
            "The number of passes to do over the data.", 1, 1,
            Integer.MAX_VALUE)
Definition at line 55 of file LearnModelRegression.java.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), and moa.tasks.LearnModelRegression.LearnModelRegression().
final long moa.tasks.LearnModelRegression.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 42 of file LearnModelRegression.java.
ClassOption moa.tasks.LearnModelRegression.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 47 of file LearnModelRegression.java.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), and moa.tasks.LearnModelRegression.LearnModelRegression().
The documentation for this class was generated from the following file:
main/java/moa/tasks/LearnModelRegression.java