MOA: moa.classifiers.functions.Perceptron Class Reference
moa.classifiers.functions.Perceptron Class Reference
Single perceptron classifier.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
void setWeights (double[][] w)
double[][] getWeights ()
int getNumberAttributes ()
int getNumberClasses ()
double prediction (Instance inst, int classVal)
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
FloatOption learningRatioOption = new FloatOption("learningRatio", 'l', "Learning ratio", 1)
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
double[][] weightAttribute
boolean reset
int numberAttributes
int numberClasses
int numberDetections
Static Private Attributes
static final long serialVersionUID = 221L
Detailed Description
Single perceptron classifier.
Performs classic perceptron multiclass learning incrementally.
Parameters:
-r : Learning ratio of the classifier
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 37 of file Perceptron.java.
Member Function Documentation
void moa.classifiers.functions.Perceptron.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 147 of file Perceptron.java.
{
    }
Measurement [] moa.classifiers.functions.Perceptron.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 142 of file Perceptron.java.
{
        return null;
    }
int moa.classifiers.functions.Perceptron.getNumberAttributes ()
Definition at line 106 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.numberAttributes.
{
        //Perceptron Hoeffding Tree
        return this.numberAttributes;
    }
int moa.classifiers.functions.Perceptron.getNumberClasses ()
Definition at line 111 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.numberClasses.
{
        //Perceptron Hoeffding Tree
        return this.numberClasses;
    }
String moa.classifiers.functions.Perceptron.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 42 of file Perceptron.java.
{
        return "Perceptron classifier: Single perceptron classifier.";
    }
double [] moa.classifiers.functions.Perceptron.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 126 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.prediction(), and moa.classifiers.functions.Perceptron.reset.
{
        double[] votes = new double[inst.numClasses()];
        if (this.reset == false) {
            for (int i = 0; i < votes.length; i++) {
                votes[i] = prediction(inst, i);
            }
            try {
                weka.core.Utils.normalize(votes);
            } catch (Exception e) {
                // ignore all zero votes error
            }
        }
        return votes;
    }
double [][] moa.classifiers.functions.Perceptron.getWeights ()
Definition at line 101 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.weightAttribute.
{
        //Perceptron Hoeffding Tree
        return this.weightAttribute;
    }
boolean moa.classifiers.functions.Perceptron.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 151 of file Perceptron.java.
{
        return true;
    }
double moa.classifiers.functions.Perceptron.prediction (Instance inst, int classVal)
Definition at line 116 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.weightAttribute.
Referenced by moa.classifiers.functions.Perceptron.getVotesForInstance(), and moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
{
        double sum = 0.0;
        for (int i = 0; i < inst.numAttributes() - 1; i++) {
            sum += weightAttribute[classVal][i] * inst.value(i);
        }
        sum += weightAttribute[classVal][inst.numAttributes() - 1];
        return 1.0 / (1.0 + Math.exp(-sum));
    }
void moa.classifiers.functions.Perceptron.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 59 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.reset.
{
        this.reset = true;
    }
void moa.classifiers.functions.Perceptron.setWeights (double w[][])
Definition at line 96 of file Perceptron.java.
References moa.classifiers.functions.Perceptron.weightAttribute.
{
        //Perceptron Hoeffding Tree
        this.weightAttribute = w;
    }
void moa.classifiers.functions.Perceptron.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 64 of file Perceptron.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.options.FloatOption.getValue(), moa.classifiers.functions.Perceptron.learningRatioOption, moa.classifiers.functions.Perceptron.numberAttributes, moa.classifiers.functions.Perceptron.numberClasses, moa.classifiers.functions.Perceptron.prediction(), moa.classifiers.functions.Perceptron.reset, and moa.classifiers.functions.Perceptron.weightAttribute.
{
        //Init Perceptron
        if (this.reset == true) {
            this.reset = false;
            this.numberAttributes = inst.numAttributes();
            this.numberClasses = inst.numClasses();
            this.weightAttribute = new double[inst.numClasses()][inst.numAttributes()];
            for (int i = 0; i < inst.numClasses(); i++) {
                for (int j = 0; j < inst.numAttributes(); j++) {
                    weightAttribute[i][j] = 0.2 * this.classifierRandom.nextDouble()- 0.1;
                }
            }
        }
        double[] preds = new double[inst.numClasses()];
        for (int i = 0; i < inst.numClasses(); i++) {
            preds[i] = prediction(inst, i);
        }
        double learningRatio = learningRatioOption.getValue();
        int actualClass = (int) inst.classValue();
        for (int i = 0; i < inst.numClasses(); i++) {
            double actual = (i == actualClass) ? 1.0 : 0.0;
            double delta = (actual - preds[i]) * preds[i] * (1 - preds[i]);
            for (int j = 0; j < inst.numAttributes() - 1; j++) {
                this.weightAttribute[i][j] += learningRatio * delta * inst.value(j);
            }
            this.weightAttribute[i][inst.numAttributes() - 1] += learningRatio * delta;
        }
    }
Member Data Documentation
FloatOption moa.classifiers.functions.Perceptron.learningRatioOption = new FloatOption("learningRatio", 'l', "Learning ratio", 1)
Definition at line 46 of file Perceptron.java.
Referenced by moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
int moa.classifiers.functions.Perceptron.numberAttributes [protected]
Definition at line 52 of file Perceptron.java.
Referenced by moa.classifiers.functions.Perceptron.getNumberAttributes(), and moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
int moa.classifiers.functions.Perceptron.numberClasses [protected]
Definition at line 54 of file Perceptron.java.
Referenced by moa.classifiers.functions.Perceptron.getNumberClasses(), and moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
int moa.classifiers.functions.Perceptron.numberDetections [protected]
Definition at line 56 of file Perceptron.java.
boolean moa.classifiers.functions.Perceptron.reset [protected]
Definition at line 50 of file Perceptron.java.
Referenced by moa.classifiers.functions.Perceptron.getVotesForInstance(), moa.classifiers.functions.Perceptron.resetLearningImpl(), and moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
final long moa.classifiers.functions.Perceptron.serialVersionUID = 221L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file Perceptron.java.
double [][] moa.classifiers.functions.Perceptron.weightAttribute [protected]
Definition at line 48 of file Perceptron.java.
Referenced by moa.classifiers.functions.Perceptron.getWeights(), moa.classifiers.functions.Perceptron.prediction(), moa.classifiers.functions.Perceptron.setWeights(), and moa.classifiers.functions.Perceptron.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/functions/Perceptron.java