MOA: moa.classifiers.core.driftdetection.ADWIN.ListItem Class Reference
moa.classifiers.core.driftdetection.ADWIN.ListItem Class Reference
Public Member Functions
ListItem ()
void clear ()
ListItem (ListItem nextNode, ListItem previousNode)
void insertBucket (double Value, double Variance)
void RemoveBucket ()
void compressBucketsRow (int NumberItemsDeleted)
ListItem previous ()
void setPrevious (ListItem previous)
ListItem next ()
void setNext (ListItem next)
double Total (int k)
double Variance (int k)
void setTotal (double value, int k)
void setVariance (double value, int k)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
ListItem next
ListItem previous
int bucketSizeRow = 0
int MAXBUCKETS = ADWIN.MAXBUCKETS
double bucketTotal [] = new double[MAXBUCKETS + 1]
double bucketVariance [] = new double[MAXBUCKETS + 1]
Private Member Functions
void clearBucket (int k)
Detailed Description
Definition at line 137 of file ADWIN.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem ()
Definition at line 152 of file ADWIN.java.
{
//          post: initializes the node to be a tail node
//          containing the given value.
            this(null, null);
        }
moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem (ListItem nextNode, ListItem previousNode)
Definition at line 170 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.clear(), moa.classifiers.core.driftdetection.ADWIN.ListItem.next(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.previous().
{
//          post: initializes the node to contain the given
//          object and link to the given next node.
            //this.data = element;
            this.next = nextNode;
            this.previous = previousNode;
            if (nextNode != null) {
                nextNode.previous = this;
            }
            if (previousNode != null) {
                previousNode.next = this;
            }
            clear();
        }
Member Function Documentation
void moa.classifiers.core.driftdetection.ADWIN.ListItem.clear ()
Definition at line 158 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.ListItem.clearBucket(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.MAXBUCKETS.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem().
{
            bucketSizeRow = 0;
            for (int k = 0; k <= MAXBUCKETS; k++) {
                clearBucket(k);
            }
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.clearBucket (int k) [private]
Definition at line 165 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.setTotal(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.setVariance().
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.clear(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow().
{
            setTotal(0, k);
            setVariance(0, k);
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow (int NumberItemsDeleted)
Definition at line 199 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketTotal, moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketVariance, moa.classifiers.core.driftdetection.ADWIN.ListItem.clearBucket(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.MAXBUCKETS.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.RemoveBucket().
{
            //Delete first elements
            for (int k = NumberItemsDeleted; k <= MAXBUCKETS; k++) {
                bucketTotal[k - NumberItemsDeleted] = bucketTotal[k];
                bucketVariance[k - NumberItemsDeleted] = bucketVariance[k];
            }
            for (int k = 1; k <= NumberItemsDeleted; k++) {
                clearBucket(MAXBUCKETS - k + 1);
            }
            bucketSizeRow -= NumberItemsDeleted;
            //BucketNumber-=NumberItemsDeleted;
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 280 of file ADWIN.java.
{
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket (double Value, double Variance)
Definition at line 185 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.ListItem.setTotal(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.setVariance().
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), and moa.classifiers.core.driftdetection.ADWIN.insertElementBucket().
{
//          insert a Bucket at the end
            int k = bucketSizeRow;
            bucketSizeRow++;
            //Insert new bucket
            setTotal(Value, k);
            setVariance(Variance, k);
        }
ListItem moa.classifiers.core.driftdetection.ADWIN.ListItem.next ()
Definition at line 222 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem().
{
//          post: returns the next node.
            return this.next;
        }
ListItem moa.classifiers.core.driftdetection.ADWIN.ListItem.previous ()
Definition at line 212 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem().
{
//          post: returns the previous node.
            return this.previous;
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.RemoveBucket ()
Definition at line 194 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow().
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement().
{
//          Removes the first Buvket
            compressBucketsRow(1);
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.setNext (ListItem next)
Definition at line 227 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail().
{
//          post: sets the next node to be the given node
            this.next = next;
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.setPrevious (ListItem previous)
Definition at line 217 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead().
{
//          post: sets the previous node to be the given node
            this.previous = previous;
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.setTotal (double value, int k)
Definition at line 242 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketTotal.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.clearBucket(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket().
{
//          post: sets the element in this node to the given
//          object.
            bucketTotal[k] = value;
        }
void moa.classifiers.core.driftdetection.ADWIN.ListItem.setVariance (double value, int k)
Definition at line 248 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketVariance.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.clearBucket(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket().
{
//          post: sets the element in this node to the given
//          object.
            bucketVariance[k] = value;
        }
double moa.classifiers.core.driftdetection.ADWIN.ListItem.Total (int k)
Definition at line 232 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketTotal.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
{
//          post: returns the element in this node
            return bucketTotal[k];
        }
double moa.classifiers.core.driftdetection.ADWIN.ListItem.Variance (int k)
Definition at line 237 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketVariance.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
{
//          post: returns the element in this node
            return bucketVariance[k];
        }
Member Data Documentation
int moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow = 0 [protected]
Definition at line 144 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.clear(), moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
double moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketTotal[] = new double[MAXBUCKETS + 1] [protected]
Definition at line 148 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow(), moa.classifiers.core.driftdetection.ADWIN.ListItem.setTotal(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.Total().
double moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketVariance[] = new double[MAXBUCKETS + 1] [protected]
Definition at line 150 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow(), moa.classifiers.core.driftdetection.ADWIN.ListItem.setVariance(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.Variance().
int moa.classifiers.core.driftdetection.ADWIN.ListItem.MAXBUCKETS = ADWIN.MAXBUCKETS [protected]
Definition at line 146 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.clear(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow().
ListItem moa.classifiers.core.driftdetection.ADWIN.ListItem.next [protected]
Definition at line 140 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem(), and moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead().
ListItem moa.classifiers.core.driftdetection.ADWIN.ListItem.previous [protected]
Definition at line 142 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ListItem.ListItem(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/ADWIN.java