MOA: moa.clusterers.CobWeb.CNode Class Reference
moa.clusterers.CobWeb.CNode Class Reference
Inner class handling node operations for Cobweb.
Public Member Functions
CNode (int numAttributes)
Creates an empty CNode instance.
CNode (int numAttributes, Instance leafInstance)
Creates a new leaf CNode instance.
Protected Member Functions
void addInstance (Instance newInstance)
Adds an instance to this cluster.
void addChildNode (CNode child)
Adds the supplied node as a child of this node.
double categoryUtility ()
Computes the utility of all children with respect to this node.
double categoryUtilityChild (CNode child)
Computes the utility of a single child with respect to this node.
double getProbability (int attIndex, int valueIndex)
Returns the probability of a value of a nominal attribute in this node.
double getStandardDev (int attIndex)
Returns the standard deviation of a numeric attribute.
void updateStats (Instance updateInstance, boolean delete)
Update attribute stats using the supplied instance.
void dumpTree (int depth, StringBuffer text)
Recursively build a string representation of the Cobweb tree.
String dumpData ()
Returns the instances at this node as a string.
void graphTree (StringBuffer text)
Recursively generate the graph string for the Cobweb tree.
void computeTreeClustering (int depth, Clustering clustering)
Recursively build a clustering representation of the Cobweb tree.
Protected Attributes
Instances m_clusterInstances = null
Instances at this node.
Static Package Attributes
static final long serialVersionUID = 3452097436933325631L
for serialization
Private Member Functions
double[] cuScoresForChildren (Instance newInstance)
Temporarily adds a new instance to each of this nodes children in turn and computes the category utility.
double cuScoreForBestTwoMerged (CNode merged, CNode a, CNode b, Instance newInstance)
CNode findHost (Instance newInstance, boolean structureFrozen)
Finds a host for the new instance in this nodes children.
void assignClusterNums (int[] cl_num)
Recursively assigns numbers to the nodes in the tree.
Private Attributes
AttributeStats[] m_attStats
Within cluster attribute statistics.
int m_numAttributes
Number of attributes.
FastVector m_children = null
Children of this node.
double m_totalInstances = 0.0
Total instances at this node.
int m_clusterNum = -1
Cluster number of this node.
Detailed Description
Inner class handling node operations for Cobweb.
See also:
Serializable
Definition at line 61 of file CobWeb.java.
Constructor & Destructor Documentation
moa.clusterers.CobWeb.CNode.CNode (int numAttributes)
Creates an empty CNode instance.
Parameters:
numAttributes the number of attributes in the data
Definition at line 95 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.m_numAttributes.
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.dumpData(), and moa.clusterers.CobWeb.CNode.findHost().
{
            m_numAttributes = numAttributes;
        }
moa.clusterers.CobWeb.CNode.CNode (int numAttributes, Instance leafInstance)
Creates a new leaf CNode instance.
Parameters:
numAttributes the number of attributes in the data
leafInstance the instance to store at this leaf
Definition at line 105 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.m_clusterInstances, and moa.clusterers.CobWeb.CNode.updateStats().
{
            this(numAttributes);
            if (m_clusterInstances == null) {
        //System.out.println(leafInstance.numAttributes()+"-"+leafInstance.value(0)+"-"+leafInstance.value(1)+"-"+leafInstance.value(2));
        //System.out.println(leafInstance.numAttributes()+"-"+leafInstance.attribute(0).type()+"-"+leafInstance.attribute(1).type()+"-"+leafInstance.attribute(2).type());
                m_clusterInstances = new Instances(leafInstance.dataset(), 1);
            }
            m_clusterInstances.add(leafInstance);
            updateStats(leafInstance, false);
        }
Member Function Documentation
void moa.clusterers.CobWeb.CNode.addChildNode (CNode child) [protected]
Adds the supplied node as a child of this node.
All of the child's instances are added to this nodes instances
Parameters:
child the child to add
Definition at line 400 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, and moa.clusterers.CobWeb.CNode.updateStats().
Referenced by moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), and moa.clusterers.CobWeb.CNode.dumpData().
{
            for (int i = 0; i < child.m_clusterInstances.numInstances(); i++) {
                Instance temp = child.m_clusterInstances.instance(i);
                m_clusterInstances.add(temp);
                updateStats(temp, false);
            }
            if (m_children == null) {
                m_children = new FastVector();
            }
            m_children.addElement(child);
        }
void moa.clusterers.CobWeb.CNode.addInstance (Instance newInstance) [protected]
Adds an instance to this cluster.
Parameters:
newInstance the instance to add
Definition at line 121 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.categoryUtility(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.m_cutoff, moa.clusterers.CobWeb.CNode.m_numAttributes, and moa.clusterers.CobWeb.CNode.updateStats().
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), and moa.clusterers.CobWeb.trainOnInstanceImpl().
{
            // Add the instance to this cluster
            if (m_clusterInstances == null) {
                m_clusterInstances = new Instances(newInstance.dataset(), 1);
                m_clusterInstances.add(newInstance);
                updateStats(newInstance, false);
                return;
            } else if (m_children == null) {
                /* we are a leaf, so make our existing instance(s) into a child
                and then add the new instance as a child */
                m_children = new FastVector();
                CNode tempSubCluster = new CNode(m_numAttributes,
                        m_clusterInstances.instance(0));
                //  System.out.println("Dumping "+m_clusterInstances.numInstances());
                for (int i = 1; i < m_clusterInstances.numInstances(); i++) {
                    tempSubCluster.m_clusterInstances.add(m_clusterInstances.instance(i));
                    tempSubCluster.updateStats(m_clusterInstances.instance(i), false);
                }
                m_children = new FastVector();
                m_children.addElement(tempSubCluster);
                m_children.addElement(new CNode(m_numAttributes, newInstance));
                m_clusterInstances.add(newInstance);
                updateStats(newInstance, false);
                // here is where we check against cutoff (also check cutoff
                // in findHost)
                if (categoryUtility() < m_cutoff) {
                    //    System.out.println("Cutting (leaf add) ");
                    m_children = null;
                }
                return;
            }
            // otherwise, find the best host for this instance
            CNode bestHost = findHost(newInstance, false);
            if (bestHost != null) {
                // now add to the best host
                bestHost.addInstance(newInstance);
            }
        }
void moa.clusterers.CobWeb.CNode.assignClusterNums (int[] cl_num) [private]
Recursively assigns numbers to the nodes in the tree.
Parameters:
cl_num an int[] value
Exceptions:
Exception if an error occurs
Definition at line 561 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.assignClusterNums(), moa.clusterers.CobWeb.CNode.m_children, and moa.clusterers.CobWeb.CNode.m_clusterNum.
Referenced by moa.clusterers.CobWeb.CNode.assignClusterNums(), and moa.clusterers.CobWeb.determineNumberOfClusters().
                                                     { //throws Exception {
            // if (m_children != null && m_children.size() < 2) {
            //throw new Exception("assignClusterNums: tree not built correctly!");
            // }
            m_clusterNum = cl_num[0];
            cl_num[0]++;
            if (m_children != null) {
                for (int i = 0; i < m_children.size(); i++) {
                    CNode child = (CNode) m_children.elementAt(i);
                    child.assignClusterNums(cl_num);
                }
            }
        }
double moa.clusterers.CobWeb.CNode.categoryUtility () [protected]
Computes the utility of all children with respect to this node.
Returns:
the category utility of the children with respect to this node.
Exceptions:
Exception if there are no children
Definition at line 419 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.categoryUtilityChild(), and moa.clusterers.CobWeb.CNode.m_children.
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), moa.clusterers.CobWeb.CNode.cuScoresForChildren(), and moa.clusterers.CobWeb.CNode.findHost().
                                           {// {throws Exception {
            // if (m_children == null) {
            //throw new Exception("categoryUtility: No children!");
            // }
            double totalCU = 0;
            for (int i = 0; i < m_children.size(); i++) {
                CNode child = (CNode) m_children.elementAt(i);
                totalCU += categoryUtilityChild(child);
            }
            totalCU /= (double) m_children.size();
            return totalCU;
        }
double moa.clusterers.CobWeb.CNode.categoryUtilityChild (CNode child) [protected]
Computes the utility of a single child with respect to this node.
Parameters:
child the child for which to compute the utility
Returns:
the utility of the child with respect to this node
Exceptions:
Exception if something goes wrong
Definition at line 443 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.getProbability(), moa.clusterers.CobWeb.CNode.getStandardDev(), moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.m_normal, moa.clusterers.CobWeb.CNode.m_numAttributes, and moa.clusterers.CobWeb.CNode.m_totalInstances.
Referenced by moa.clusterers.CobWeb.CNode.categoryUtility().
                                                           {//throws Exception {
            double sum = 0;
            for (int i = 0; i < m_numAttributes; i++) {
                if (m_clusterInstances.attribute(i).isNominal()) {
                    for (int j = 0;
                            j < m_clusterInstances.attribute(i).numValues(); j++) {
                        double x = child.getProbability(i, j);
                        double y = getProbability(i, j);
                        sum += (x * x) - (y * y);
                    }
                } else {
                    // numeric attribute
                    sum += ((m_normal / child.getStandardDev(i))
                            - (m_normal / getStandardDev(i)));
                }
            }
            return (child.m_totalInstances / m_totalInstances) * sum;
        }
void moa.clusterers.CobWeb.CNode.computeTreeClustering (int depth, Clustering clustering) [protected]
Recursively build a clustering representation of the Cobweb tree.
Parameters:
depth depth of this node in the tree
clustering holds the Clustering representation
Definition at line 698 of file CobWeb.java.
References moa.cluster.Clustering.add(), moa.clusterers.CobWeb.determineNumberOfClusters(), moa.clusterers.CobWeb.CNode.m_children, and moa.clusterers.CobWeb.CNode.m_clusterInstances.
Referenced by moa.clusterers.CobWeb.getClusteringResult().
{
            if (depth == 0) {
                determineNumberOfClusters();
            }
            if (m_children == null) {
        //Append Cluster
                /*text.append("\n");
                for (int j = 0; j < depth; j++) {
                    text.append("|   ");
                }
                text.append("leaf " + m_clusterNum + " ["
                        + m_clusterInstances.numInstances() + "]");
        clustering.add(SphereCluster(this.coordinates, .05, m_clusterInstances.numInstances()));*/
                if (depth == 0) {
                    double [] centroidCoordinates = new double[m_clusterInstances.numAttributes()];
                for (int j = 0; j < m_clusterInstances.numAttributes()-1; j++) {
                centroidCoordinates[j] = m_clusterInstances.meanOrMode(j);
                }
                clustering.add(new SphereCluster(centroidCoordinates, .05, m_clusterInstances.numInstances()));
                }
            } else {
                for (int i = 0; i < m_children.size(); i++) {
                    /*text.append("\n");
                    for (int j = 0; j < depth; j++) {
                        text.append("|   ");
                    }
                    text.append("node " + m_clusterNum + " ["
                            + m_clusterInstances.numInstances()
                            + "]");*/
                double [] centroidCoordinates = new double[m_clusterInstances.numAttributes()];
            for (int j = 0; j < m_clusterInstances.numAttributes()-1; j++) {
            centroidCoordinates[j] = m_clusterInstances.meanOrMode(j);
            }
            clustering.add(new SphereCluster(centroidCoordinates, .05, m_clusterInstances.numInstances()));
                    ((CNode) m_children.elementAt(i)).computeTreeClustering(depth + 1, clustering);
                }
            }
        }
double moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged (CNode merged, CNode a, CNode b, Instance newInstance) [private]
Definition at line 192 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.addChildNode(), moa.clusterers.CobWeb.CNode.categoryUtility(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, and moa.clusterers.CobWeb.CNode.updateStats().
Referenced by moa.clusterers.CobWeb.CNode.findHost().
                                      {//throws Exception {
            double mergedCU = -Double.MAX_VALUE;
            // consider merging the best and second
            // best.
            merged.m_clusterInstances = new Instances(m_clusterInstances, 1);
            merged.addChildNode(a);
            merged.addChildNode(b);
            merged.updateStats(newInstance, false); // add new instance to stats
            // remove the best and second best nodes
            m_children.removeElementAt(m_children.indexOf(a));
            m_children.removeElementAt(m_children.indexOf(b));
            m_children.addElement(merged);
            mergedCU = categoryUtility();
            // restore the status quo
            merged.updateStats(newInstance, true);
            m_children.removeElementAt(m_children.indexOf(merged));
            m_children.addElement(a);
            m_children.addElement(b);
            return mergedCU;
        }
double [] moa.clusterers.CobWeb.CNode.cuScoresForChildren (Instance newInstance) [private]
Temporarily adds a new instance to each of this nodes children in turn and computes the category utility.
Parameters:
newInstance the new instance to evaluate
Returns:
an array of category utility values---the result of considering each child in turn as a host for the new instance
Exceptions:
Exception if an error occurs
Definition at line 174 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.categoryUtility(), moa.clusterers.CobWeb.CNode.m_children, and moa.clusterers.CobWeb.CNode.updateStats().
Referenced by moa.clusterers.CobWeb.CNode.findHost().
{
            //throws Exception {
            // look for a host in existing children
            double[] categoryUtils = new double[m_children.size()];
            // look for a home for this instance in the existing children
            for (int i = 0; i < m_children.size(); i++) {
                CNode temp = (CNode) m_children.elementAt(i);
                // tentitively add the new instance to this child
                temp.updateStats(newInstance, false);
                categoryUtils[i] = categoryUtility();
                // remove the new instance from this child
                temp.updateStats(newInstance, true);
            }
            return categoryUtils;
        }
String moa.clusterers.CobWeb.CNode.dumpData () [protected]
Returns the instances at this node as a string.
Appends the cluster number of the child that each instance belongs to.
Returns:
a String value
Exceptions:
Exception if an error occurs
Definition at line 616 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.addChildNode(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.CNode.m_clusterNum, and moa.clusterers.CobWeb.CNode.m_numAttributes.
Referenced by moa.clusterers.CobWeb.CNode.graphTree().
                                    { //throws Exception {
            if (m_children == null) {
                return m_clusterInstances.toString();
            }
            // construct instances string with cluster numbers attached
            CNode tempNode = new CNode(m_numAttributes);
            tempNode.m_clusterInstances = new Instances(m_clusterInstances, 1);
            for (int i = 0; i < m_children.size(); i++) {
                tempNode.addChildNode((CNode) m_children.elementAt(i));
            }
            Instances tempInst = tempNode.m_clusterInstances;
            tempNode = null;
            Add af = new Add();
            af.setAttributeName("Cluster");
            String labels = "";
            for (int i = 0; i < m_children.size(); i++) {
                CNode temp = (CNode) m_children.elementAt(i);
                labels += ("C" + temp.m_clusterNum);
                if (i < m_children.size() - 1) {
                    labels += ",";
                }
            }
            af.setNominalLabels(labels);
            //af.setInputFormat(tempInst);
            //tempInst = Filter.useFilter(tempInst, af);
            tempInst.setRelationName("Cluster " + m_clusterNum);
            int z = 0;
            for (int i = 0; i < m_children.size(); i++) {
                CNode temp = (CNode) m_children.elementAt(i);
                for (int j = 0; j < temp.m_clusterInstances.numInstances(); j++) {
                    tempInst.instance(z).setValue(m_numAttributes, (double) i);
                    z++;
                }
            }
            return tempInst.toString();
        }
void moa.clusterers.CobWeb.CNode.dumpTree (int depth, StringBuffer text) [protected]
Recursively build a string representation of the Cobweb tree.
Parameters:
depth depth of this node in the tree
text holds the string representation
Definition at line 582 of file CobWeb.java.
References moa.clusterers.CobWeb.determineNumberOfClusters(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, and moa.clusterers.CobWeb.CNode.m_clusterNum.
Referenced by moa.clusterers.CobWeb.getModelDescription().
{
            if (depth == 0) {
                determineNumberOfClusters();
            }
            if (m_children == null) {
                text.append("\n");
                for (int j = 0; j < depth; j++) {
                    text.append("|   ");
                }
                text.append("leaf " + m_clusterNum + " ["
                        + m_clusterInstances.numInstances() + "]");
            } else {
                for (int i = 0; i < m_children.size(); i++) {
                    text.append("\n");
                    for (int j = 0; j < depth; j++) {
                        text.append("|   ");
                    }
                    text.append("node " + m_clusterNum + " ["
                            + m_clusterInstances.numInstances()
                            + "]");
                    ((CNode) m_children.elementAt(i)).dumpTree(depth + 1, text);
                }
            }
        }
CNode moa.clusterers.CobWeb.CNode.findHost (Instance newInstance, boolean structureFrozen) [private]
Finds a host for the new instance in this nodes children.
Also considers merging the two best hosts and splitting the best host.
Parameters:
newInstance the instance to find a host for
structureFrozen true if the instance is not to be added to the tree and instead the best potential host is to be returned
Returns:
the best host
Exceptions:
Exception if an error occurs
Definition at line 227 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.categoryUtility(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), moa.clusterers.CobWeb.CNode.cuScoresForChildren(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.m_cutoff, moa.clusterers.CobWeb.CNode.m_numAttributes, moa.clusterers.CobWeb.m_numberMerges, moa.clusterers.CobWeb.m_numberSplits, and moa.clusterers.CobWeb.CNode.updateStats().
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), and moa.clusterers.CobWeb.getVotesForInstance().
                                         {//throws Exception {
            if (!structureFrozen) {
                updateStats(newInstance, false);
            }
            // look for a host in existing children and also consider as a new leaf
            double[] categoryUtils = cuScoresForChildren(newInstance);
            // make a temporary new leaf for this instance and get CU
            CNode newLeaf = new CNode(m_numAttributes, newInstance);
            m_children.addElement(newLeaf);
            double bestHostCU = categoryUtility();
            CNode finalBestHost = newLeaf;
            // remove new leaf when seaching for best and second best nodes to
            // consider for merging and splitting
            m_children.removeElementAt(m_children.size() - 1);
            // now determine the best host (and the second best)
            int best = 0;
            int secondBest = 0;
            for (int i = 0; i < categoryUtils.length; i++) {
                if (categoryUtils[i] > categoryUtils[secondBest]) {
                    if (categoryUtils[i] > categoryUtils[best]) {
                        secondBest = best;
                        best = i;
                    } else {
                        secondBest = i;
                    }
                }
            }
            CNode a = (CNode) m_children.elementAt(best);
            CNode b = (CNode) m_children.elementAt(secondBest);
            if (categoryUtils[best] > bestHostCU) {
                bestHostCU = categoryUtils[best];
                finalBestHost = a;
                //  System.out.println("Node is best");
            }
            if (structureFrozen) {
                if (finalBestHost == newLeaf) {
                    return null; // *this* node is the best host
                } else {
                    return finalBestHost;
                }
            }
            double mergedCU = -Double.MAX_VALUE;
            CNode merged = new CNode(m_numAttributes);
            if (a != b) {
                mergedCU = cuScoreForBestTwoMerged(merged, a, b, newInstance);
                if (mergedCU > bestHostCU) {
                    bestHostCU = mergedCU;
                    finalBestHost = merged;
                }
            }
            // Consider splitting the best
            double splitCU = -Double.MAX_VALUE;
            double splitBestChildCU = -Double.MAX_VALUE;
            double splitPlusNewLeafCU = -Double.MAX_VALUE;
            double splitPlusMergeBestTwoCU = -Double.MAX_VALUE;
            if (a.m_children != null) {
                FastVector tempChildren = new FastVector();
                for (int i = 0; i < m_children.size(); i++) {
                    CNode existingChild = (CNode) m_children.elementAt(i);
                    if (existingChild != a) {
                        tempChildren.addElement(existingChild);
                    }
                }
                for (int i = 0; i < a.m_children.size(); i++) {
                    CNode promotedChild = (CNode) a.m_children.elementAt(i);
                    tempChildren.addElement(promotedChild);
                }
                // also add the new leaf
                tempChildren.addElement(newLeaf);
                FastVector saveStatusQuo = m_children;
                m_children = tempChildren;
                splitPlusNewLeafCU = categoryUtility(); // split + new leaf
                // remove the new leaf
                tempChildren.removeElementAt(tempChildren.size() - 1);
                // now look for best and second best
                categoryUtils = cuScoresForChildren(newInstance);
                // now determine the best host (and the second best)
                best = 0;
                secondBest = 0;
                for (int i = 0; i < categoryUtils.length; i++) {
                    if (categoryUtils[i] > categoryUtils[secondBest]) {
                        if (categoryUtils[i] > categoryUtils[best]) {
                            secondBest = best;
                            best = i;
                        } else {
                            secondBest = i;
                        }
                    }
                }
                CNode sa = (CNode) m_children.elementAt(best);
                CNode sb = (CNode) m_children.elementAt(secondBest);
                splitBestChildCU = categoryUtils[best];
                // now merge best and second best
                CNode mergedSplitChildren = new CNode(m_numAttributes);
                if (sa != sb) {
                    splitPlusMergeBestTwoCU =
                            cuScoreForBestTwoMerged(mergedSplitChildren, sa, sb, newInstance);
                }
                splitCU = (splitBestChildCU > splitPlusNewLeafCU)
                        ? splitBestChildCU : splitPlusNewLeafCU;
                splitCU = (splitCU > splitPlusMergeBestTwoCU)
                        ? splitCU : splitPlusMergeBestTwoCU;
                if (splitCU > bestHostCU) {
                    bestHostCU = splitCU;
                    finalBestHost = this;
                    //    tempChildren.removeElementAt(tempChildren.size()-1);
                } else {
                    // restore the status quo
                    m_children = saveStatusQuo;
                }
            }
            if (finalBestHost != this) {
                // can commit the instance to the set of instances at this node
                m_clusterInstances.add(newInstance);
            } else {
                m_numberSplits++;
            }
            if (finalBestHost == merged) {
                m_numberMerges++;
                m_children.removeElementAt(m_children.indexOf(a));
                m_children.removeElementAt(m_children.indexOf(b));
                m_children.addElement(merged);
            }
            if (finalBestHost == newLeaf) {
                finalBestHost = new CNode(m_numAttributes);
                m_children.addElement(finalBestHost);
            }
            if (bestHostCU < m_cutoff) {
                if (finalBestHost == this) {
                    // splitting was the best, but since we are cutting all children
                    // recursion is aborted and we still need to add the instance
                    // to the set of instances at this node
                    m_clusterInstances.add(newInstance);
                }
                m_children = null;
                finalBestHost = null;
            }
            if (finalBestHost == this) {
                // splitting is still the best, so downdate the stats as
                // we'll be recursively calling on this node
                updateStats(newInstance, true);
            }
            return finalBestHost;
        }
double moa.clusterers.CobWeb.CNode.getProbability (int attIndex, int valueIndex) [protected]
Returns the probability of a value of a nominal attribute in this node.
Parameters:
attIndex the index of the attribute
valueIndex the index of the value of the attribute
Returns:
the probability
Exceptions:
Exception if the requested attribute is not nominal
Definition at line 472 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.m_attStats.
Referenced by moa.clusterers.CobWeb.CNode.categoryUtilityChild().
{
            //throws Exception {
            //  if (!m_clusterInstances.attribute(attIndex).isNominal()) {
            //throw new Exception("getProbability: attribute is not nominal");
            //  }
            if (m_attStats[attIndex].totalCount <= 0) {
                return 0;
            }
            return (double) m_attStats[attIndex].nominalCounts[valueIndex]
                    / (double) m_attStats[attIndex].totalCount;
        }
double moa.clusterers.CobWeb.CNode.getStandardDev (int attIndex) [protected]
Returns the standard deviation of a numeric attribute.
Parameters:
attIndex the index of the attribute
Returns:
the standard deviation
Exceptions:
Exception if an error occurs
Definition at line 494 of file CobWeb.java.
References moa.clusterers.CobWeb.m_acuity, and moa.clusterers.CobWeb.CNode.m_attStats.
Referenced by moa.clusterers.CobWeb.CNode.categoryUtilityChild().
                                                      { //throws Exception {
            //  if (!m_clusterInstances.attribute(attIndex).isNumeric()) {
            //throw new Exception("getStandardDev: attribute is not numeric");
            // }
            m_attStats[attIndex].numericStats.calculateDerived();
            double stdDev = m_attStats[attIndex].numericStats.stdDev;
            if (Double.isNaN(stdDev) || Double.isInfinite(stdDev)) {
                return m_acuity;
            }
            return Math.max(m_acuity, stdDev);
        }
void moa.clusterers.CobWeb.CNode.graphTree (StringBuffer text) [protected]
Recursively generate the graph string for the Cobweb tree.
Parameters:
text holds the graph string
Exceptions:
Exception if generation fails
Definition at line 662 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.dumpData(), moa.clusterers.CobWeb.CNode.graphTree(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.CNode.m_clusterNum, and moa.clusterers.CobWeb.m_saveInstances.
Referenced by moa.clusterers.CobWeb.graph(), and moa.clusterers.CobWeb.CNode.graphTree().
                                                    { //throws Exception {
            text.append("N" + m_clusterNum
                    + " [label=\"" + ((m_children == null)
                    ? "leaf " : "node ")
                    + m_clusterNum + " "
                    + " (" + m_clusterInstances.numInstances()
                    + ")\" "
                    + ((m_children == null)
                    ? "shape=box style=filled " : "")
                    + (m_saveInstances
                    ? "data =\n" + dumpData() + "\n,\n"
                    : "")
                    + "]\n");
            if (m_children != null) {
                for (int i = 0; i < m_children.size(); i++) {
                    CNode temp = (CNode) m_children.elementAt(i);
                    text.append("N" + m_clusterNum
                            + "->"
                            + "N" + temp.m_clusterNum
                            + "\n");
                }
                for (int i = 0; i < m_children.size(); i++) {
                    CNode temp = (CNode) m_children.elementAt(i);
                    temp.graphTree(text);
                }
            }
        }
void moa.clusterers.CobWeb.CNode.updateStats (Instance updateInstance, boolean delete) [protected]
Update attribute stats using the supplied instance.
Parameters:
updateInstance the instance for updating
delete true if the values of the supplied instance are to be removed from the statistics
Definition at line 515 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.m_attStats, moa.clusterers.CobWeb.CNode.m_clusterInstances, moa.clusterers.CobWeb.CNode.m_numAttributes, and moa.clusterers.CobWeb.CNode.m_totalInstances.
Referenced by moa.clusterers.CobWeb.CNode.addChildNode(), moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), moa.clusterers.CobWeb.CNode.cuScoresForChildren(), moa.clusterers.CobWeb.CNode.findHost(), and moa.clusterers.CobWeb.getVotesForInstance().
{
            if (m_attStats == null) {
                m_attStats = new AttributeStats[m_numAttributes];
                for (int i = 0; i < m_numAttributes; i++) {
                    m_attStats[i] = new AttributeStats();
                    if (m_clusterInstances.attribute(i).isNominal()) {
                        m_attStats[i].nominalCounts =
                                new int[m_clusterInstances.attribute(i).numValues()];
                    } else {
                        m_attStats[i].numericStats = new Stats();
                    }
                }
            }
            for (int i = 0; i < m_numAttributes; i++) {
                if (!updateInstance.isMissing(i)) {
                    double value = updateInstance.value(i);
                    if (m_clusterInstances.attribute(i).isNominal()) {
                        m_attStats[i].nominalCounts[(int) value] += (delete)
                                ? (-1.0 * updateInstance.weight())
                                : updateInstance.weight();
                        m_attStats[i].totalCount += (delete)
                                ? (-1.0 * updateInstance.weight())
                                : updateInstance.weight();
                    } else {
                        if (delete) {
                            m_attStats[i].numericStats.subtract(value,
                                    updateInstance.weight());
                        } else {
                            m_attStats[i].numericStats.add(value, updateInstance.weight());
                        }
                    }
                }
            }
            m_totalInstances += (delete)
                    ? (-1.0 * updateInstance.weight())
                    : (updateInstance.weight());
        }
Member Data Documentation
AttributeStats [] moa.clusterers.CobWeb.CNode.m_attStats [private]
Within cluster attribute statistics.
Definition at line 68 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.getProbability(), moa.clusterers.CobWeb.CNode.getStandardDev(), and moa.clusterers.CobWeb.CNode.updateStats().
FastVector moa.clusterers.CobWeb.CNode.m_children = null [private]
Children of this node.
Definition at line 80 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.addChildNode(), moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.assignClusterNums(), moa.clusterers.CobWeb.CNode.categoryUtility(), moa.clusterers.CobWeb.CNode.computeTreeClustering(), moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), moa.clusterers.CobWeb.CNode.cuScoresForChildren(), moa.clusterers.CobWeb.CNode.dumpData(), moa.clusterers.CobWeb.CNode.dumpTree(), moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.getVotesForInstance(), and moa.clusterers.CobWeb.CNode.graphTree().
Instances moa.clusterers.CobWeb.CNode.m_clusterInstances = null [protected]
Instances at this node.
Definition at line 76 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.addChildNode(), moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.categoryUtilityChild(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.computeTreeClustering(), moa.clusterers.CobWeb.CNode.cuScoreForBestTwoMerged(), moa.clusterers.CobWeb.CNode.dumpData(), moa.clusterers.CobWeb.CNode.dumpTree(), moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.CNode.graphTree(), and moa.clusterers.CobWeb.CNode.updateStats().
int moa.clusterers.CobWeb.CNode.m_clusterNum = -1 [private]
Cluster number of this node.
Definition at line 88 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.assignClusterNums(), moa.clusterers.CobWeb.CNode.dumpData(), moa.clusterers.CobWeb.CNode.dumpTree(), moa.clusterers.CobWeb.getVotesForInstance(), and moa.clusterers.CobWeb.CNode.graphTree().
int moa.clusterers.CobWeb.CNode.m_numAttributes [private]
Number of attributes.
Definition at line 72 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.categoryUtilityChild(), moa.clusterers.CobWeb.CNode.CNode(), moa.clusterers.CobWeb.CNode.dumpData(), moa.clusterers.CobWeb.CNode.findHost(), and moa.clusterers.CobWeb.CNode.updateStats().
double moa.clusterers.CobWeb.CNode.m_totalInstances = 0.0 [private]
Total instances at this node.
Definition at line 84 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.categoryUtilityChild(), and moa.clusterers.CobWeb.CNode.updateStats().
final long moa.clusterers.CobWeb.CNode.serialVersionUID = 3452097436933325631L [static, package]
for serialization
Definition at line 64 of file CobWeb.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/CobWeb.java