MOA: moa.classifiers.trees.FIMTDD.FIMTDDSplitNode Class Reference
moa.classifiers.trees.FIMTDD.FIMTDDSplitNode Class Reference
A modified SplitNode method implementing the extra information regarding it's parent, and the ability to track the error rate and perform Page-Hinckley tests.
Public Member Functions
FIMTDDSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Create a new FIMTDDSplitNode.
void setParent (Node parent)
Set the parent node.
Node getParent ()
Return the parent node.
boolean PageHinckleyTest (double error, double threshold)
Check to see if the tree needs updating.
void learnFromInstance (Instance inst, FIMTDD ht, boolean growingAltTree)
This method has been added to the SplitNode subclass to allow alternate trees to be grown and compared to the current tree, to allow adaptation in the face of concept drift.
Protected Attributes
Node parent
double PHmT = 0
double PHMT = Double.MAX_VALUE
FIMTDD alternateTree
DoubleVector lossStatistics = new DoubleVector()
int weightSeen = 0
int previousWeight = 0
Detailed Description
A modified SplitNode method implementing the extra information regarding it's parent, and the ability to track the error rate and perform Page-Hinckley tests.
Definition at line 350 of file FIMTDD.java.
Constructor & Destructor Documentation
moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.FIMTDDSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Create a new FIMTDDSplitNode.
Definition at line 373 of file FIMTDD.java.
{
                  super(splitTest,classObservations);
            }
Member Function Documentation
Node moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.getParent ()
Return the parent node.
Implements moa.classifiers.trees.FIMTDD.AdaptationCompatibleNode.
Definition at line 388 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
            {
                  return parent;
            }
void moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance (Instance inst, FIMTDD ht, boolean growingAltTree)
This method has been added to the SplitNode subclass to allow alternate trees to be grown and compared to the current tree, to allow adaptation in the face of concept drift.
Definition at line 417 of file FIMTDD.java.
References moa.classifiers.trees.FIMTDD.Adaptable, moa.classifiers.trees.FIMTDD.AlternateTreeTimeOption, moa.classifiers.trees.FIMTDD.AlternateTreeTMinOption, moa.classifiers.AbstractClassifier.copy(), moa.options.IntOption.getValue(), moa.classifiers.trees.HoeffdingTree.FoundNode.node, and moa.classifiers.trees.FIMTDD.nodesToAdapt.
{
                if(growingAltTree)
                {
                    weightSeen++;
                    // If no alternate tree exists
                    if (this.alternateTree == null)
                    {
                        // Start a new alternate tree, beginning with a learning node
                        this.alternateTree = (FIMTDD)ht.copy();
                        this.alternateTree.resetLearningImpl();
                        this.alternateTree.Adaptable = false;
                        // Set up the blank statistics
                            // Number of instances reaching this node since the alternate tree was started
                            lossStatistics.setValue(0,0);
                            // Sum of Qi values
                            lossStatistics.setValue(1,0);
                            weightSeen = 0;
                            previousWeight = 0;
                    }
                    // If an alternate tree already exists, check if the current tree should be replaced with it,
                    // or if the alternate tree should be discarded.
                    else if(weightSeen - previousWeight >= ht.AlternateTreeTMinOption.getValue())
                    {
                        // Update the weight at which a decision was tested for
                        previousWeight = weightSeen;
                        // Update the loss statistics for the alternate tree
                        FoundNode foundNode = this.alternateTree.treeRoot.filterInstanceToLeaf(inst,null,-1);
                        Node leaf = foundNode.node;
                                                double squaresAlternate= 0.0;
                                                if(leaf instanceof FIMTDDActiveLearningNode)
{
                                                    squaresAlternate = ((FIMTDDActiveLearningNode)leaf).getSquaredError();
                                                }
                                                // Update the loss statistics for the current tree
                                                foundNode = this.getChild(this.instanceChildIndex(inst)).filterInstanceToLeaf(inst,null,-1);
                                                leaf = foundNode.node;
                                                double squaresOriginal = 0.0;
                                                if(leaf instanceof FIMTDDActiveLearningNode)
{
                                                   squaresOriginal = ((FIMTDDActiveLearningNode)leaf).getSquaredError();
                                                }
                                                // Compute the Qi statistics
                                                double Qi = Math.log(squaresOriginal /squaresAlternate);
                        double previousQiAverage = lossStatistics.getValue(1) / lossStatistics.getValue(0);
                        lossStatistics.addToValue(0,1);
                        lossStatistics.addToValue(1,Qi);
                        double QiAverage = lossStatistics.getValue(1) / lossStatistics.getValue(0);
                        // If appropriate, replace the current tree with the alternate tree
                        if(Qi > 0)
{
                            FIMTDDSplitNode parent = (FIMTDDSplitNode)this.parent;
                            //Replace the main FIMT-DD tree at a subtree
                            if(parent != null)
{
                                parent.setChild(parent.instanceChildIndex(inst),this.alternateTree.treeRoot);
                                ht.nodesToAdapt.remove(this);
                                this.alternateTree = null;
                            }
                            // Or occasionally at the root of the tree
                            else
{
                                ht = this.alternateTree;
                                ht.nodesToAdapt = new ArrayList<FIMTDDSplitNode>();
                                ht.Adaptable = true;
                                this.alternateTree = null;
                            }
                        }
                        // Otherwise, check if the alternate tree should be discarded
                        else if (QiAverage < previousQiAverage && lossStatistics.getValue(0) >= (10 * ht.AlternateTreeTMinOption.getValue()) || weightSeen >= ht.AlternateTreeTimeOption.getValue())
{
                            ht.nodesToAdapt.remove(ht.nodesToAdapt.indexOf(this));
                            this.alternateTree = null;
                        }
                    }
                    // Learn the alternate tree (if it has not just been discarded)
                    if(this.alternateTree != null)
                    {
                        this.alternateTree.trainOnInstanceImpl(inst);
                    }
                }
                // Determine which of the current children this instance should
                // be sent to, and learn that child
                int childBranch = this.instanceChildIndex(inst);
                Node child = this.getChild(childBranch);
                if (child != null) {
                    if(child instanceof FIMTDDActiveLearningNode)
                    {
                        ((FIMTDDActiveLearningNode)child).learnFromInstance(inst, ht);
                    }
                    else
                    {
                        ((FIMTDDSplitNode)child).learnFromInstance(inst,ht, false);
                    }
                }
            }
boolean moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.PageHinckleyTest (double error, double threshold)
Check to see if the tree needs updating.
Definition at line 396 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.trainOnInstanceImpl().
            {
                // Update the cumulative mT sum
                PHmT += error;
                // Update the minimum mT value if the new mT is
                // smaller than the current minimum
                if(PHmT < PHMT)
                {
                    PHMT = PHmT;
                }
                // Return true if the cumulative value - the current minimum is
                // greater than the current threshold (in which case we should adapt)
                return PHmT - PHMT > threshold;
            }
void moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.setParent (Node parent)
Set the parent node.
Implements moa.classifiers.trees.FIMTDD.AdaptationCompatibleNode.
Definition at line 380 of file FIMTDD.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit().
            {
                  this.parent = parent;
            }
Member Data Documentation
FIMTDD moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.alternateTree [protected]
Definition at line 362 of file FIMTDD.java.
DoubleVector moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.lossStatistics = new DoubleVector() [protected]
Definition at line 365 of file FIMTDD.java.
Node moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.parent [protected]
Definition at line 353 of file FIMTDD.java.
double moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.PHMT = Double.MAX_VALUE [protected]
Definition at line 359 of file FIMTDD.java.
double moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.PHmT = 0 [protected]
Definition at line 358 of file FIMTDD.java.
int moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.previousWeight = 0 [protected]
Definition at line 368 of file FIMTDD.java.
int moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.weightSeen = 0 [protected]
Definition at line 367 of file FIMTDD.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/FIMTDD.java