MOA: moa.classifiers.multilabel.MultilabelHoeffdingTree Class Reference
moa.classifiers.multilabel.MultilabelHoeffdingTree Class Reference
Hoeffding Tree for classifying multi-label data.
Classes
class MultilabelInactiveLearningNode
class MultilabelLearningNodeClassifier
Public Member Functions
void setModelContext (InstancesHeader raw_header)
Sets the reference to the header of the data stream.
MultilabelHoeffdingTree ()
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
Public Attributes
int m_L = -1
Protected Member Functions
LearningNode newLearningNode (double[] initialClassObservations)
LearningNode newLearningNode (double[] initialClassObservations, Classifier cl)
void deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch)
Protected Attributes
Converter converter = null
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Hoeffding Tree for classifying multi-label data.
A Hoeffding tree is an incremental, anytime decision tree induction algorithm that is capable of learning from massive data streams, assuming that the distribution generating examples does not change over time.
Definition at line 41 of file MultilabelHoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelHoeffdingTree ()
Definition at line 143 of file MultilabelHoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.removePoorAttsOption.
{
        this.removePoorAttsOption = null;
    }
Member Function Documentation
void moa.classifiers.multilabel.MultilabelHoeffdingTree.deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 161 of file MultilabelHoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.inactiveLeafNodeCount, moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        Node newLeaf = new MultilabelInactiveLearningNode(toDeactivate
                .getObservedClassDistribution());
        if (parent == null) {
            this.treeRoot = newLeaf;
        } else {
            parent.setChild(parentBranch, newLeaf);
        }
        this.activeLeafNodeCount--;
        this.inactiveLeafNodeCount++;
    }
double [] moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 175 of file MultilabelHoeffdingTree.java.
References moa.classifiers.multilabel.MultilabelHoeffdingTree.converter, moa.core.utils.Converter.createTemplate(), moa.classifiers.trees.HoeffdingTree.Node.filterInstanceToLeaf(), moa.classifiers.trees.HoeffdingTree.Node.getClassVotes(), moa.classifiers.multilabel.MultilabelHoeffdingTree.m_L, moa.classifiers.AbstractClassifier.modelContext, moa.classifiers.trees.HoeffdingTree.FoundNode.node, moa.classifiers.trees.HoeffdingTree.FoundNode.parent, and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        int L = inst.classIndex()+1;
        if (m_L != L) {
            // Update class labels
            m_L = L;
            // Create a converter, and its template
            converter = new Converter(m_L);
            try {
                converter.createTemplate(new Instances(new StringReader(this.modelContext.toString()),0));
            } catch(Exception e) {
                System.err.println("Error, failed to create a multi-label Instances template with L = "+m_L);
                System.out.println("Instances: "+this.modelContext.toString());
                e.printStackTrace();
                System.exit(1);
            }
        }
        if (this.treeRoot != null) {
            FoundNode foundNode = this.treeRoot.filterInstanceToLeaf(inst, null, -1);
            Node leafNode = foundNode.node;
            if (leafNode == null) {
                leafNode = foundNode.parent;
            }
            //System.out.println("y[] = "+Arrays.toString(leafNode.getClassVotes(inst,this)));
            return leafNode.getClassVotes(inst, this);
        }
        // Return empty array (this should only happen once! -- before we build the root node).
        return new double[this.m_L];
    }
LearningNode moa.classifiers.multilabel.MultilabelHoeffdingTree.newLearningNode (double[] initialClassObservations, Classifier cl) [protected]
Reimplemented from moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.
Definition at line 154 of file MultilabelHoeffdingTree.java.
{
        // Create new Learning Node
        return new MultilabelLearningNodeClassifier(initialClassObservations,cl,this);
    }
LearningNode moa.classifiers.multilabel.MultilabelHoeffdingTree.newLearningNode (double[] initialClassObservations) [protected]
Reimplemented from moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.
Definition at line 148 of file MultilabelHoeffdingTree.java.
{
        // Create new Learning Node null
        return new MultilabelLearningNodeClassifier(initialClassObservations,null,this);
    }
void moa.classifiers.multilabel.MultilabelHoeffdingTree.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 54 of file MultilabelHoeffdingTree.java.
References moa.classifiers.AbstractClassifier.modelContext.
{
        //set the multilabel model context
        this.modelContext = raw_header;
    }
Member Data Documentation
Converter moa.classifiers.multilabel.MultilabelHoeffdingTree.converter = null [protected]
Definition at line 51 of file MultilabelHoeffdingTree.java.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance(), and moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance().
int moa.classifiers.multilabel.MultilabelHoeffdingTree.m_L = -1
Definition at line 48 of file MultilabelHoeffdingTree.java.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance().
final long moa.classifiers.multilabel.MultilabelHoeffdingTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.
Definition at line 46 of file MultilabelHoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/MultilabelHoeffdingTree.java