MOA: moa.gui.clustertab.ClusteringTabPanel Class Reference
moa.gui.clustertab.ClusteringTabPanel Class Reference
Public Member Functions
ClusteringTabPanel ()
Creates new form ClusterTab.
String getTabTitle ()
Returns the string to display as title of the tab.
String getDescription ()
Returns a short description (can be used as tool tip) of the tab, or contributor, etc.
Package Functions
void toggle ()
void stop ()
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void jTabbedPane1FocusGained (java.awt.event.FocusEvent evt)
void jTabbedPane1MouseClicked (java.awt.event.MouseEvent evt)
Private Attributes
moa.gui.clustertab.ClusteringSetupTab clusteringSetupTab
moa.gui.clustertab.ClusteringVisualTab clusteringVisualTab
javax.swing.JTabbedPane jTabbedPane1
Detailed Description
Definition at line 25 of file ClusteringTabPanel.java.
Constructor & Destructor Documentation
moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel ()
Creates new form ClusterTab.
Definition at line 28 of file ClusteringTabPanel.java.
References moa.gui.clustertab.ClusteringSetupTab.addButtonActionListener(), moa.gui.clustertab.ClusteringTabPanel.clusteringSetupTab, moa.gui.clustertab.ClusteringTabPanel.clusteringVisualTab, moa.gui.clustertab.ClusteringTabPanel.initComponents(), moa.gui.clustertab.ClusteringVisualTab.setClusteringSetupTab(), and moa.gui.clustertab.ClusteringSetupTab.setClusteringTab().
{
        initComponents();
        clusteringVisualTab.setClusteringSetupTab(clusteringSetupTab);
        clusteringSetupTab.addButtonActionListener(clusteringVisualTab);
        clusteringSetupTab.setClusteringTab(this);
    }
Member Function Documentation
String moa.gui.clustertab.ClusteringTabPanel.getDescription () [virtual]
Returns a short description (can be used as tool tip) of the tab, or contributor, etc.
Returns:
a short description of this tab panel.
Implements moa.gui.AbstractTabPanel.
Definition at line 97 of file ClusteringTabPanel.java.
{
            return "MOA Clustering";
    }
String moa.gui.clustertab.ClusteringTabPanel.getTabTitle () [virtual]
Returns the string to display as title of the tab.
Returns:
the string to display as title of the tab
Implements moa.gui.AbstractTabPanel.
Definition at line 92 of file ClusteringTabPanel.java.
{
            return "Clustering";
    }
void moa.gui.clustertab.ClusteringTabPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 51 of file ClusteringTabPanel.java.
References moa.gui.clustertab.ClusteringSetupTab.ClusteringSetupTab(), moa.gui.clustertab.ClusteringTabPanel.clusteringSetupTab, moa.gui.clustertab.ClusteringVisualTab.ClusteringVisualTab(), moa.gui.clustertab.ClusteringTabPanel.clusteringVisualTab, moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1, moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1FocusGained(), and moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1MouseClicked().
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel().
{
        jTabbedPane1 = new javax.swing.JTabbedPane();
        clusteringSetupTab = new moa.gui.clustertab.ClusteringSetupTab();
        clusteringVisualTab = new moa.gui.clustertab.ClusteringVisualTab();
        setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addTab("Setup", clusteringSetupTab);
        jTabbedPane1.addTab("Visualization", clusteringVisualTab);
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1FocusGained (java.awt.event.FocusEvent evt) [private]
Definition at line 75 of file ClusteringTabPanel.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.initComponents().
                                                                        {//GEN-FIRST:event_jTabbedPane1FocusGained
    }//GEN-LAST:event_jTabbedPane1FocusGained
void moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1MouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 79 of file ClusteringTabPanel.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.initComponents().
                                                                         {//GEN-FIRST:event_jTabbedPane1MouseClicked
    }//GEN-LAST:event_jTabbedPane1MouseClicked
void moa.gui.clustertab.ClusteringTabPanel.stop () [package]
Definition at line 39 of file ClusteringTabPanel.java.
References moa.gui.clustertab.ClusteringTabPanel.clusteringVisualTab, and moa.gui.clustertab.ClusteringVisualTab.stopVisualizer().
Referenced by moa.gui.clustertab.ClusteringSetupTab.stop().
                {
        clusteringVisualTab.stopVisualizer();
    }
void moa.gui.clustertab.ClusteringTabPanel.toggle () [package]
Definition at line 35 of file ClusteringTabPanel.java.
References moa.gui.clustertab.ClusteringTabPanel.clusteringVisualTab, and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
Referenced by moa.gui.clustertab.ClusteringSetupTab.toggle().
                  {
        clusteringVisualTab.toggleVisualizer(false);
    }
Member Data Documentation
moa.gui.clustertab.ClusteringSetupTab moa.gui.clustertab.ClusteringTabPanel.clusteringSetupTab [private]
Definition at line 86 of file ClusteringTabPanel.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel(), and moa.gui.clustertab.ClusteringTabPanel.initComponents().
moa.gui.clustertab.ClusteringVisualTab moa.gui.clustertab.ClusteringTabPanel.clusteringVisualTab [private]
Definition at line 87 of file ClusteringTabPanel.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel(), moa.gui.clustertab.ClusteringTabPanel.initComponents(), moa.gui.clustertab.ClusteringTabPanel.stop(), and moa.gui.clustertab.ClusteringTabPanel.toggle().
javax.swing.JTabbedPane moa.gui.clustertab.ClusteringTabPanel.jTabbedPane1 [private]
Definition at line 88 of file ClusteringTabPanel.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.initComponents().
The documentation for this class was generated from the following file:
main/java/moa/gui/clustertab/ClusteringTabPanel.java