MOA: moa.classifiers.drift.DriftDetectionMethodClassifierTest Class Reference
moa.classifiers.drift.DriftDetectionMethodClassifierTest Class Reference
Tests the DriftDetectionMethodClassifier classifier.
Public Member Functions
DriftDetectionMethodClassifierTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the DriftDetectionMethodClassifier classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 33 of file DriftDetectionMethodClassifierTest.java.
Constructor & Destructor Documentation
moa.classifiers.drift.DriftDetectionMethodClassifierTest.DriftDetectionMethodClassifierTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 41 of file DriftDetectionMethodClassifierTest.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.drift.DriftDetectionMethodClassifierTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleClassifierTestCase.
Definition at line 52 of file DriftDetectionMethodClassifierTest.java.
{
    return new Classifier[]{
    new DriftDetectionMethodClassifier(),
    };
  }
static void moa.classifiers.drift.DriftDetectionMethodClassifierTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 72 of file DriftDetectionMethodClassifierTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.drift.DriftDetectionMethodClassifierTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.drift.DriftDetectionMethodClassifierTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 63 of file DriftDetectionMethodClassifierTest.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifierTest.main().
{
    return new TestSuite(DriftDetectionMethodClassifierTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/drift/DriftDetectionMethodClassifierTest.java