MOA: moa.streams.generators.RandomRBFGeneratorDrift Class Reference
moa.streams.generators.RandomRBFGeneratorDrift Class Reference
Stream generator for a random radial basis function stream with drift.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Instance nextInstance ()
Gets the next instance from this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
FloatOption speedChangeOption
IntOption numDriftCentroidsOption
Protected Member Functions
void generateCentroids ()
Protected Attributes
double[][] speedCentroids
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for a random radial basis function stream with drift.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 34 of file RandomRBFGeneratorDrift.java.
Member Function Documentation
void moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids () [protected]
Reimplemented from moa.streams.generators.RandomRBFGenerator.
Definition at line 75 of file RandomRBFGeneratorDrift.java.
References moa.streams.generators.RandomRBFGenerator.centroids, moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.modelRandomSeedOption, moa.streams.generators.RandomRBFGenerator.numAttsOption, moa.streams.generators.RandomRBFGeneratorDrift.numDriftCentroidsOption, and moa.streams.generators.RandomRBFGeneratorDrift.speedCentroids.
{
        super.generateCentroids();
        Random modelRand = new Random(this.modelRandomSeedOption.getValue());
        int len = this.numDriftCentroidsOption.getValue();
        if (len > this.centroids.length) {
            len = this.centroids.length;
        }
        this.speedCentroids = new double[len][this.numAttsOption.getValue()];
        for (int i = 0; i < len; i++) {
            double[] randSpeed = new double[this.numAttsOption.getValue()];
            double normSpeed = 0.0;
            for (int j = 0; j < randSpeed.length; j++) {
                randSpeed[j] = modelRand.nextDouble();
                normSpeed += randSpeed[j] * randSpeed[j];
            }
            normSpeed = Math.sqrt(normSpeed);
            for (int j = 0; j < randSpeed.length; j++) {
                randSpeed[j] /= normSpeed;
            }
            this.speedCentroids[i] = randSpeed;
        }
    }
void moa.streams.generators.RandomRBFGeneratorDrift.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Reimplemented from moa.streams.generators.RandomRBFGenerator.
Definition at line 99 of file RandomRBFGeneratorDrift.java.
{
        // TODO Auto-generated method stub
    }
String moa.streams.generators.RandomRBFGeneratorDrift.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.streams.generators.RandomRBFGenerator.
Definition at line 37 of file RandomRBFGeneratorDrift.java.
{
        return "Generates a random radial basis function stream with drift.";
    }
Instance moa.streams.generators.RandomRBFGeneratorDrift.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Reimplemented from moa.streams.generators.RandomRBFGenerator.
Definition at line 52 of file RandomRBFGeneratorDrift.java.
References moa.streams.generators.RandomRBFGenerator.Centroid.centre, moa.streams.generators.RandomRBFGenerator.centroids, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.numAttsOption, moa.streams.generators.RandomRBFGeneratorDrift.numDriftCentroidsOption, moa.streams.generators.RandomRBFGeneratorDrift.speedCentroids, and moa.streams.generators.RandomRBFGeneratorDrift.speedChangeOption.
{
        //Update Centroids with drift
        int len = this.numDriftCentroidsOption.getValue();
        if (len > this.centroids.length) {
            len = this.centroids.length;
        }
        for (int j = 0; j < len; j++) {
            for (int i = 0; i < this.numAttsOption.getValue(); i++) {
                this.centroids[j].centre[i] += this.speedCentroids[j][i] * this.speedChangeOption.getValue();
                if (this.centroids[j].centre[i] > 1) {
                    this.centroids[j].centre[i] = 1;
                    this.speedCentroids[j][i] = -this.speedCentroids[j][i];
                }
                if (this.centroids[j].centre[i] < 0) {
                    this.centroids[j].centre[i] = 0;
                    this.speedCentroids[j][i] = -this.speedCentroids[j][i];
                }
            }
        }
        return super.nextInstance();
    }
Member Data Documentation
IntOption moa.streams.generators.RandomRBFGeneratorDrift.numDriftCentroidsOption
Initial value:
 new IntOption("numDriftCentroids", 'k',
            "The number of centroids with drift.", 50, 0, Integer.MAX_VALUE)
Definition at line 46 of file RandomRBFGeneratorDrift.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), and moa.streams.generators.RandomRBFGeneratorDrift.nextInstance().
final long moa.streams.generators.RandomRBFGeneratorDrift.serialVersionUID = 1L [static, private]
Reimplemented from moa.streams.generators.RandomRBFGenerator.
Definition at line 41 of file RandomRBFGeneratorDrift.java.
double [][] moa.streams.generators.RandomRBFGeneratorDrift.speedCentroids [protected]
Definition at line 49 of file RandomRBFGeneratorDrift.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), and moa.streams.generators.RandomRBFGeneratorDrift.nextInstance().
FloatOption moa.streams.generators.RandomRBFGeneratorDrift.speedChangeOption
Initial value:
 new FloatOption("speedChange", 's',
            "Speed of change of centroids in the model.", 0, 0, Float.MAX_VALUE)
Definition at line 43 of file RandomRBFGeneratorDrift.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.nextInstance().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/RandomRBFGeneratorDrift.java