MOA: moa.clusterers.clustream.ClustreamKernel Class Reference
moa.clusterers.clustream.ClustreamKernel Class Reference
Public Member Functions
ClustreamKernel (Instance instance, int dimensions, long timestamp, double t, int m)
ClustreamKernel (ClustreamKernel cluster, double t, int m)
void insert (Instance instance, long timestamp)
void add (CFCluster other2)
double getRelevanceStamp ()
double getRadius ()
See interface Cluster.
CFCluster getCF ()
double[] getCenter ()
double getInclusionProbability (Instance instance)
See interface Cluster.
boolean isEmpty ()
Check if this cluster is empty or not.
Static Public Member Functions
static double inverseError (double x)
Approximates the inverse error function.
Static Public Attributes
static final double MIN_VARIANCE = 1e-50
Protected Member Functions
void getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue)
Protected Attributes
double LST
double SST
Package Attributes
int m
double t
Private Member Functions
double getMuTime ()
double getSigmaTime ()
double getQuantile (double z)
double getDeviation ()
double[] getVarianceVector ()
double calcNormalizedDistance (double[] point)
Calculate the normalized euclidean distance (Mahalanobis distance for distribution w/o covariances) to a point.
Static Private Attributes
static final long serialVersionUID = 1L
static final double EPSILON = 0.00005
Detailed Description
Definition at line 26 of file ClustreamKernel.java.
Constructor & Destructor Documentation
moa.clusterers.clustream.ClustreamKernel.ClustreamKernel (Instance instance, int dimensions, long timestamp, double t, int m)
Definition at line 39 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.LST, and moa.clusterers.clustream.ClustreamKernel.SST.
{
        super(instance, dimensions);
        this.t = t;
        this.m = m;
        this.LST = timestamp;
        this.SST = timestamp*timestamp;
    }
moa.clusterers.clustream.ClustreamKernel.ClustreamKernel (ClustreamKernel cluster, double t, int m)
Definition at line 47 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.LST, and moa.clusterers.clustream.ClustreamKernel.SST.
{
        super(cluster);
        this.t = t;
        this.m = m;
        this.LST = cluster.LST;
        this.SST = cluster.SST;
    }
Member Function Documentation
void moa.clusterers.clustream.ClustreamKernel.add (CFCluster other2)
Definition at line 67 of file ClustreamKernel.java.
References moa.cluster.CFCluster.LS, moa.clusterers.clustream.ClustreamKernel.LST, moa.cluster.CFCluster.N, moa.cluster.CFCluster.SS, and moa.clusterers.clustream.ClustreamKernel.SST.
Referenced by moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        ClustreamKernel other = (ClustreamKernel) other2;
        assert( other.LS.length == this.LS.length );
        this.N += other.N;
        this.LST += other.LST;
        this.SST += other.SST;
        for ( int i = 0; i < LS.length; i++ ) {
            this.LS[i] += other.LS[i];
            this.SS[i] += other.SS[i];
        }
    }
double moa.clusterers.clustream.ClustreamKernel.calcNormalizedDistance (double[] point) [private]
Calculate the normalized euclidean distance (Mahalanobis distance for distribution w/o covariances) to a point.
Parameters:
other The point to which the distance is calculated.
Returns:
The normalized distance to the cluster center.
TODO: check whether WEIGHTING is correctly applied to variances
Definition at line 214 of file ClustreamKernel.java.
References moa.cluster.SphereCluster.center, moa.clusterers.clustream.ClustreamKernel.getCenter(), and moa.clusterers.clustream.ClustreamKernel.getVarianceVector().
Referenced by moa.clusterers.clustream.ClustreamKernel.getInclusionProbability().
{
        double[] variance = getVarianceVector();
        double[] center = getCenter();
        double res = 0.0;
        for (int i = 0; i < center.length; i++) {
            double diff = center[i] - point[i];
            res += (diff * diff);// variance[i];
        }
        return Math.sqrt(res);
    }
double [] moa.clusterers.clustream.ClustreamKernel.getCenter () [virtual]
Returns:
this kernels' center
Reimplemented from moa.cluster.CFCluster.
Definition at line 130 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.isEmpty(), moa.cluster.CFCluster.LS, and moa.cluster.CFCluster.N.
Referenced by moa.clusterers.clustream.ClustreamKernel.calcNormalizedDistance(), moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        assert (!this.isEmpty());
        double res[] = new double[this.LS.length];
        for (int i = 0; i < res.length; i++) {
            res[i] = this.LS[i] / N;
        }
        return res;
    }
CFCluster moa.clusterers.clustream.ClustreamKernel.getCF () [virtual]
Implements moa.cluster.CFCluster.
Definition at line 111 of file ClustreamKernel.java.
{
        return this;
    }
void moa.clusterers.clustream.ClustreamKernel.getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue) [protected]
Reimplemented from moa.cluster.SphereCluster.
Definition at line 257 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.getVarianceVector().
{
        super.getClusterSpecificInfo(infoTitle, infoValue);
        infoTitle.add("Deviation");
        double[] variance = getVarianceVector();
        double sumOfDeviation = 0.0;
        for (int i = 0; i < variance.length; i++) {
            double d = Math.sqrt(variance[i]);
            sumOfDeviation += d;
        }
        sumOfDeviation/= variance.length;
        infoValue.add(Double.toString(sumOfDeviation));
    }
double moa.clusterers.clustream.ClustreamKernel.getDeviation () [private]
Definition at line 116 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.getVarianceVector().
Referenced by moa.clusterers.clustream.ClustreamKernel.getRadius().
{
        double[] variance = getVarianceVector();
        double sumOfDeviation = 0.0;
        for (int i = 0; i < variance.length; i++) {
            double d = Math.sqrt(variance[i]);
            sumOfDeviation += d;
        }
        return sumOfDeviation / variance.length;
    }
double moa.clusterers.clustream.ClustreamKernel.getInclusionProbability (Instance instance) [virtual]
See interface Cluster.
Parameters:
point
Returns:
Implements moa.cluster.CFCluster.
Definition at line 145 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.calcNormalizedDistance(), moa.cluster.SphereCluster.distance(), moa.clusterers.clustream.ClustreamKernel.EPSILON, moa.clusterers.clustream.ClustreamKernel.getRadius(), moa.cluster.CFCluster.LS, and moa.cluster.CFCluster.N.
{
        //trivial cluster
        if(N == 1){
            double distance = 0.0;
            for (int i = 0; i < LS.length; i++) {
                double d = LS[i] - instance.value(i);
                distance += d * d;
            }
            distance = Math.sqrt(distance);
            if( distance < EPSILON )
                return 1.0;
            return 0.0;
        }
        else{
            double dist = calcNormalizedDistance(instance.toDoubleArray());
            if(dist <= getRadius()){
                return 1;
            }
            else{
                return 0;
            }
//            double res = AuxiliaryFunctions.distanceProbabilty(dist, LS.length);
//            return res;
        }
    }
double moa.clusterers.clustream.ClustreamKernel.getMuTime () [private]
Definition at line 87 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.LST, and moa.cluster.CFCluster.N.
Referenced by moa.clusterers.clustream.ClustreamKernel.getRelevanceStamp().
{
        return LST / N;
    }
double moa.clusterers.clustream.ClustreamKernel.getQuantile (double z) [private]
Definition at line 95 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.inverseError().
Referenced by moa.clusterers.clustream.ClustreamKernel.getRelevanceStamp().
{
        assert( z >= 0 && z <= 1 );
        return Math.sqrt( 2 ) * inverseError( 2*z - 1 );
    }
double moa.clusterers.clustream.ClustreamKernel.getRadius () [virtual]
See interface Cluster.
Returns:
The radius of the cluster.
Implements moa.cluster.CFCluster.
Definition at line 101 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.getDeviation(), moa.cluster.CFCluster.N, moa.cluster.CFCluster.radiusFactor, and moa.clusterers.clustream.ClustreamKernel.t.
Referenced by moa.clusterers.clustream.ClustreamKernel.getInclusionProbability(), moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        //trivial cluster
        if(N == 1) return 0;
        if(t==1)
            t=1;
        return getDeviation()*radiusFactor;
    }
double moa.clusterers.clustream.ClustreamKernel.getRelevanceStamp ()
Definition at line 80 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.getMuTime(), moa.clusterers.clustream.ClustreamKernel.getQuantile(), moa.clusterers.clustream.ClustreamKernel.getSigmaTime(), moa.clusterers.clustream.ClustreamKernel.m, and moa.cluster.CFCluster.N.
{
        if ( N < 2*m )
            return getMuTime();
        return getMuTime() + getSigmaTime() * getQuantile( ((double)m)/(2*N) );
    }
double moa.clusterers.clustream.ClustreamKernel.getSigmaTime () [private]
Definition at line 91 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.LST, moa.cluster.CFCluster.N, and moa.clusterers.clustream.ClustreamKernel.SST.
Referenced by moa.clusterers.clustream.ClustreamKernel.getRelevanceStamp().
{
        return Math.sqrt(SST/N - (LST/N)*(LST/N));
    }
double [] moa.clusterers.clustream.ClustreamKernel.getVarianceVector () [private]
Definition at line 171 of file ClustreamKernel.java.
References moa.clusterers.clustream.ClustreamKernel.EPSILON, moa.cluster.CFCluster.getWeight(), moa.cluster.CFCluster.LS, moa.clusterers.clustream.ClustreamKernel.MIN_VARIANCE, and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.clustream.ClustreamKernel.calcNormalizedDistance(), moa.clusterers.clustream.ClustreamKernel.getClusterSpecificInfo(), and moa.clusterers.clustream.ClustreamKernel.getDeviation().
{
        double[] res = new double[this.LS.length];
        for (int i = 0; i < this.LS.length; i++) {
            double ls = this.LS[i];
            double ss = this.SS[i];
            double lsDivN = ls / this.getWeight();
            double lsDivNSquared = lsDivN * lsDivN;
            double ssDivN = ss / this.getWeight();
            res[i] = ssDivN - lsDivNSquared;
            // Due to numerical errors, small negative values can occur.
            // We correct this by settings them to almost zero.
            if (res[i] <= 0.0) {
                if (res[i] > -EPSILON) {
                    res[i] = MIN_VARIANCE;
                }
            }
            else{
            }
        }
        return res;
    }
void moa.clusterers.clustream.ClustreamKernel.insert (Instance instance, long timestamp)
Definition at line 55 of file ClustreamKernel.java.
References moa.cluster.CFCluster.LS, moa.clusterers.clustream.ClustreamKernel.LST, moa.cluster.CFCluster.N, moa.cluster.CFCluster.SS, and moa.clusterers.clustream.ClustreamKernel.SST.
Referenced by moa.clusterers.clustream.WithKmeans.trainOnInstanceImpl(), and moa.clusterers.clustream.Clustream.trainOnInstanceImpl().
{
        N++;
        LST += timestamp;
        SST += timestamp*timestamp;
        for ( int i = 0; i < instance.numValues(); i++ ) {
            LS[i] += instance.value(i);
            SS[i] += instance.value(i)*instance.value(i);
        }
    }
static double moa.clusterers.clustream.ClustreamKernel.inverseError (double x) [static]
Approximates the inverse error function.
Clustream needs this.
Parameters:
z
Definition at line 230 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.getQuantile().
{
        double z = Math.sqrt(Math.PI) * x;
        double res = (z) / 2;
        double z2 = z * z;
        double zProd = z * z2; // z^3
        res += (1.0 / 24) * zProd;
        zProd *= z2;  // z^5
        res += (7.0 / 960) * zProd;
        zProd *= z2;  // z^7
        res += (127 * zProd) / 80640;
        zProd *= z2;  // z^9
        res += (4369 * zProd) / 11612160;
        zProd *= z2;  // z^11
        res += (34807 * zProd) / 364953600;
        zProd *= z2;  // z^13
        res += (20036983 * zProd) / 797058662400d;
        return res;
    }
boolean moa.clusterers.clustream.ClustreamKernel.isEmpty ()
Check if this cluster is empty or not.
Returns:
true if the cluster has no data points, false otherwise.
Definition at line 201 of file ClustreamKernel.java.
References moa.cluster.CFCluster.N.
Referenced by moa.clusterers.clustream.ClustreamKernel.getCenter().
{
        return this.N == 0;
    }
Member Data Documentation
final double moa.clusterers.clustream.ClustreamKernel.EPSILON = 0.00005 [static, private]
Definition at line 29 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.getInclusionProbability(), and moa.clusterers.clustream.ClustreamKernel.getVarianceVector().
double moa.clusterers.clustream.ClustreamKernel.LST [protected]
Definition at line 32 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.add(), moa.clusterers.clustream.ClustreamKernel.ClustreamKernel(), moa.clusterers.clustream.ClustreamKernel.getMuTime(), moa.clusterers.clustream.ClustreamKernel.getSigmaTime(), and moa.clusterers.clustream.ClustreamKernel.insert().
int moa.clusterers.clustream.ClustreamKernel.m [package]
Definition at line 35 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.getRelevanceStamp().
final double moa.clusterers.clustream.ClustreamKernel.MIN_VARIANCE = 1e-50 [static]
Definition at line 30 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.getVarianceVector().
final long moa.clusterers.clustream.ClustreamKernel.serialVersionUID = 1L [static, private]
Reimplemented from moa.cluster.CFCluster.
Definition at line 27 of file ClustreamKernel.java.
double moa.clusterers.clustream.ClustreamKernel.SST [protected]
Definition at line 33 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.add(), moa.clusterers.clustream.ClustreamKernel.ClustreamKernel(), moa.clusterers.clustream.ClustreamKernel.getSigmaTime(), and moa.clusterers.clustream.ClustreamKernel.insert().
double moa.clusterers.clustream.ClustreamKernel.t [package]
Definition at line 36 of file ClustreamKernel.java.
Referenced by moa.clusterers.clustream.ClustreamKernel.getRadius().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustream/ClustreamKernel.java