MOA: moa.options.AbstractOptionHandler Class Reference
moa.options.AbstractOptionHandler Class Reference
Abstract Option Handler.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Options getOptions ()
Gets the options of this object.
void prepareForUse ()
This method prepares this object for use.
void prepareForUse (TaskMonitor monitor, ObjectRepository repository)
This method prepares this object for use.
String getCLICreationString (Class<?> expectedType)
Gets the Command Line Interface text to create the object.
OptionHandler copy ()
This method produces a copy of this object.
Protected Member Functions
abstract void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Option[] discoverOptionsViaReflection ()
Gets the options of this class via reflection.
void prepareClassOptions (TaskMonitor monitor, ObjectRepository repository)
Prepares the options of this class.
Object getPreparedClassOption (ClassOption opt)
Gets a prepared option of this class.
Object getPreparedClassOption (ClassOptionWithNames opt)
Gets a prepared option of this class.
Protected Attributes
Options options
Options to handle.
Map< String, Object > classOptionNamesToPreparedObjects
Dictionary with option texts and objects.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Abstract Option Handler.
All classes that have options in MOA extend this class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 41 of file AbstractOptionHandler.java.
Member Function Documentation
OptionHandler moa.options.AbstractOptionHandler.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Reimplemented from moa.AbstractMOAObject.
Reimplemented in moa.classifiers.AbstractClassifier, moa.classifiers.core.driftdetection.AbstractChangeDetector, and moa.clusterers.AbstractClusterer.
Definition at line 100 of file AbstractOptionHandler.java.
References moa.options.OptionHandler.copy().
Referenced by moa.tasks.RunStreamTasks.doMainTask().
{
        return (OptionHandler) super.copy();
    }
Option [] moa.options.AbstractOptionHandler.discoverOptionsViaReflection () [protected]
Gets the options of this class via reflection.
Returns:
an array of options
Definition at line 109 of file AbstractOptionHandler.java.
Referenced by moa.options.AbstractOptionHandler.getOptions().
{
        Class<? extends AbstractOptionHandler> c = this.getClass();
        Field[] fields = c.getFields();
        List<Option> optList = new LinkedList<Option>();
        for (Field field : fields) {
            String fName = field.getName();
            Class<?> fType = field.getType();
            if (fName.endsWith("Option")) {
                if (Option.class.isAssignableFrom(fType)) {
                    Option oVal = null;
                    try {
                        field.setAccessible(true);
                        oVal = (Option) field.get(this);
                    } catch (IllegalAccessException ignored) {
                        // cannot access this field
                    }
                    if (oVal != null) {
                        optList.add(oVal);
                    }
                }
            }
        }
        return optList.toArray(new Option[optList.size()]);
    }
String moa.options.AbstractOptionHandler.getCLICreationString (Class<?> expectedType)
Gets the Command Line Interface text to create the object.
Returns:
the Command Line Interface text to create the object
Implements moa.options.OptionHandler.
Definition at line 93 of file AbstractOptionHandler.java.
References moa.options.Options.getAsCLIString(), and moa.options.AbstractOptionHandler.getOptions().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomRBFGenerator.generateHeader(), moa.streams.generators.HyperplaneGenerator.generateHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.generators.WaveformGenerator.prepareForUseImpl(), moa.streams.generators.STAGGERGenerator.prepareForUseImpl(), moa.streams.generators.SEAGenerator.prepareForUseImpl(), moa.streams.generators.LEDGenerator.prepareForUseImpl(), moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl(), moa.streams.generators.AgrawalGenerator.prepareForUseImpl(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), moa.gui.RegressionTaskManagerPanel.RegressionTaskManagerPanel(), moa.gui.TaskManagerPanel.setTaskString(), moa.gui.RegressionTaskManagerPanel.setTaskString(), moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString(), moa.gui.TaskManagerPanel.TaskManagerPanel(), and moa.classifiers.meta.RandomRules.transformInstance().
{
        return ClassOption.stripPackagePrefix(this.getClass().getName(),
                expectedType)
                + " " + getOptions().getAsCLIString();
    }
Options moa.options.AbstractOptionHandler.getOptions ()
Gets the options of this object.
Returns:
the options of this object
Implements moa.options.OptionHandler.
Reimplemented in moa.clusterers.outliers.AnyOut.AnyOut.
Definition at line 58 of file AbstractOptionHandler.java.
References moa.options.Options.addOption(), moa.options.AbstractOptionHandler.discoverOptionsViaReflection(), and moa.options.AbstractOptionHandler.options.
Referenced by moa.options.AbstractOptionHandler.getCLICreationString(), moa.clusterers.outliers.AnyOut.AnyOut.getOptions(), and moa.options.AbstractOptionHandler.prepareClassOptions().
{
        if (this.options == null) {
            this.options = new Options();
            Option[] myOptions = discoverOptionsViaReflection();
            for (Option option : myOptions) {
                this.options.addOption(option);
            }
        }
        return this.options;
    }
Object moa.options.AbstractOptionHandler.getPreparedClassOption (ClassOptionWithNames opt) [protected]
Gets a prepared option of this class.
Parameters:
opt - ClassOptionWithNames
Returns:
an option stored in the dictionary
Definition at line 211 of file AbstractOptionHandler.java.
References moa.options.AbstractOptionHandler.classOptionNamesToPreparedObjects, and moa.options.AbstractOption.getName().
{
        return this.classOptionNamesToPreparedObjects.get(opt.getName());
    }
Object moa.options.AbstractOptionHandler.getPreparedClassOption (ClassOption opt) [protected]
Gets a prepared option of this class.
Parameters:
opt the class option to get
Returns:
an option stored in the dictionary
Definition at line 201 of file AbstractOptionHandler.java.
References moa.options.AbstractOptionHandler.classOptionNamesToPreparedObjects, and moa.options.AbstractOption.getName().
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.RunTasks.doMainTask(), moa.tasks.RunStreamTasks.doMainTask(), moa.tasks.MeasureStreamSpeed.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.EvaluateClustering.doMainTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier(), moa.classifiers.trees.ORTO.newNumericClassObserver(), moa.streams.MultiFilteredStream.prepareForUseImpl(), moa.streams.FilteredStream.prepareForUseImpl(), moa.streams.ConceptDriftStream.prepareForUseImpl(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl(), moa.recommender.predictor.BaselinePredictor.prepareForUseImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.learners.ChangeDetectorLearner.resetLearningImpl(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl(), moa.classifiers.meta.RandomRules.resetLearningImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), moa.classifiers.meta.OzaBagAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBag.resetLearningImpl(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.meta.OCBoost.resetLearningImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), moa.classifiers.active.ActiveClassifier.resetLearningImpl(), moa.streams.generators.multilabel.MetaMultilabelGenerator.restart(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl(), and moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl().
{
        return this.classOptionNamesToPreparedObjects.get(opt.getName());
    }
String moa.options.AbstractOptionHandler.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Implements moa.options.OptionHandler.
Reimplemented in moa.classifiers.AbstractClassifier, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.AdaHoeffdingOptionTree, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.LimAttHoeffdingTree, moa.classifiers.trees.ORTO, moa.classifiers.trees.RandomHoeffdingTree, moa.clusterers.AbstractClusterer, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.WekaClusteringAlgorithm, moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, moa.recommender.dataset.impl.MovielensDataset, moa.streams.ArffFileStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.multilabel.MultilabelArffFileStream, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomRBFGeneratorDrift, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, moa.streams.MultiFilteredStream, moa.tasks.CacheShuffledStream, moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Definition at line 53 of file AbstractOptionHandler.java.
{
        return "Anonymous object: purpose undocumented.";
    }
void moa.options.AbstractOptionHandler.prepareClassOptions (TaskMonitor monitor, ObjectRepository repository) [protected]
Prepares the options of this class.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Definition at line 140 of file AbstractOptionHandler.java.
References moa.options.AbstractOptionHandler.classOptionNamesToPreparedObjects, moa.options.AbstractOption.getName(), moa.options.Options.getOptionArray(), moa.options.AbstractOptionHandler.getOptions(), moa.options.AbstractClassOption.materializeObject(), moa.tasks.TaskMonitor.setCurrentActivity(), and moa.tasks.TaskMonitor.taskShouldAbort().
Referenced by moa.tasks.AbstractTask.doTask(), and moa.options.AbstractOptionHandler.prepareForUse().
{
        this.classOptionNamesToPreparedObjects = null;
        Option[] optionArray = getOptions().getOptionArray();
        for (Option option : optionArray) {
            if (option instanceof ClassOption) {
                ClassOption classOption = (ClassOption) option;
                monitor.setCurrentActivity("Materializing option "
                        + classOption.getName() + "...", -1.0);
                Object optionObj = classOption.materializeObject(monitor,
                        repository);
                if (monitor.taskShouldAbort()) {
                    return;
                }
                if (optionObj instanceof OptionHandler) {
                    monitor.setCurrentActivity("Preparing option "
                            + classOption.getName() + "...", -1.0);
                    ((OptionHandler) optionObj).prepareForUse(monitor,
                            repository);
                    if (monitor.taskShouldAbort()) {
                        return;
                    }
                }
                if (this.classOptionNamesToPreparedObjects == null) {
                    this.classOptionNamesToPreparedObjects = new HashMap<String, Object>();
                }
                this.classOptionNamesToPreparedObjects.put(option.getName(),
                        optionObj);
            } else if (option instanceof ClassOptionWithNames) {
                ClassOptionWithNames classOption = (ClassOptionWithNames) option;
                monitor.setCurrentActivity("Materializing option "
                        + classOption.getName() + "...", -1.0);
                Object optionObj = classOption.materializeObject(monitor,
                        repository);
                if (monitor.taskShouldAbort()) {
                    return;
                }
                if (optionObj instanceof OptionHandler) {
                    monitor.setCurrentActivity("Preparing option "
                            + classOption.getName() + "...", -1.0);
                    ((OptionHandler) optionObj).prepareForUse(monitor,
                            repository);
                    if (monitor.taskShouldAbort()) {
                        return;
                    }
                }
                if (this.classOptionNamesToPreparedObjects == null) {
                    this.classOptionNamesToPreparedObjects = new HashMap<String, Object>();
                }
                this.classOptionNamesToPreparedObjects.put(option.getName(),
                        optionObj);
            }
        }
    }
void moa.options.AbstractOptionHandler.prepareForUse (TaskMonitor monitor, ObjectRepository repository)
This method prepares this object for use.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.OptionHandler.
Definition at line 75 of file AbstractOptionHandler.java.
References moa.options.AbstractOptionHandler.prepareClassOptions(), and moa.options.AbstractOptionHandler.prepareForUseImpl().
{
        prepareClassOptions(monitor, repository);
        prepareForUseImpl(monitor, repository);
    }
void moa.options.AbstractOptionHandler.prepareForUse ()
This method prepares this object for use.
Implements moa.options.OptionHandler.
Definition at line 70 of file AbstractOptionHandler.java.
Referenced by moa.gui.BatchCmd.BatchCmd(), moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), moa.clusterers.outliers.AbstractC.Test.main(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunVisualizer.RunVisualizer(), and moa.streams.filters.AbstractStreamFilter.setInputStream().
{
        prepareForUse(new NullMonitor(), null);
    }
abstract void moa.options.AbstractOptionHandler.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, pure virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver, moa.classifiers.core.driftdetection.ADWINChangeDetector, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_A_Test, moa.classifiers.core.driftdetection.HDDM_W_Test, moa.classifiers.core.driftdetection.PageHinkleyDM, moa.classifiers.core.splitcriteria.GiniSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterion, moa.classifiers.core.splitcriteria.VarianceReductionSplitCriterion, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.clusterers.AbstractClusterer, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, moa.evaluation.WindowRegressionPerformanceEvaluator, moa.recommender.data.MemRecommenderData, moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, moa.recommender.dataset.impl.MovielensDataset, moa.recommender.predictor.BaselinePredictor, moa.recommender.predictor.BRISMFPredictor, moa.streams.ArffFileStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AbstractStreamFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, moa.streams.MultiFilteredStream, and moa.tasks.AbstractTask.
Referenced by moa.options.AbstractOptionHandler.prepareForUse().
Member Data Documentation
Map<String, Object> moa.options.AbstractOptionHandler.classOptionNamesToPreparedObjects [protected]
Dictionary with option texts and objects.
Definition at line 50 of file AbstractOptionHandler.java.
Referenced by moa.tasks.AbstractTask.doTask(), moa.options.AbstractOptionHandler.getPreparedClassOption(), and moa.options.AbstractOptionHandler.prepareClassOptions().
Options moa.options.AbstractOptionHandler.options [protected]
Options to handle.
Definition at line 47 of file AbstractOptionHandler.java.
Referenced by moa.classifiers.meta.WEKAClassifier.createWekaClassifier(), moa.options.AbstractOptionHandler.getOptions(), moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), moa.classifiers.meta.WEKAClassifier.resetLearningImpl(), and moa.tasks.Plot.terminalOptions().
final long moa.options.AbstractOptionHandler.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_W_Test, moa.classifiers.core.driftdetection.PageHinkleyDM, moa.classifiers.core.splitcriteria.GiniSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterionMultilabel, moa.classifiers.core.splitcriteria.SDRSplitCriterion, moa.classifiers.core.splitcriteria.VarianceReductionSplitCriterion, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.HoeffdingTreeClassifLeaves, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.MEKAClassifier, moa.classifiers.multilabel.MultilabelHoeffdingTree, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.AMRulesRegressor, moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver, moa.classifiers.rules.core.splitcriteria.SDRSplitCriterionAMRules, moa.classifiers.rules.functions.FadingTargetMean, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.rules.RuleClassifierNBayes, moa.classifiers.trees.AdaHoeffdingOptionTree, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.LimAttHoeffdingTree, moa.classifiers.trees.ORTO, moa.classifiers.trees.RandomHoeffdingTree, moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.WekaClusteringAlgorithm, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, moa.evaluation.WindowRegressionPerformanceEvaluator, moa.learners.ChangeDetectorLearner, moa.streams.ArffFileStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.multilabel.MultilabelArffFileStream, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomRBFGeneratorDrift, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, moa.streams.MultiFilteredStream, moa.tasks.CacheShuffledStream, moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MainTask, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Definition at line 44 of file AbstractOptionHandler.java.
The documentation for this class was generated from the following file:
main/java/moa/options/AbstractOptionHandler.java