MOA: moa.DoTask Class Reference
moa.DoTask Class Reference
Class for running a MOA task from the command line.
Static Public Member Functions
static boolean isJavaVersionOK ()
Checks if the Java version is recent enough to run MOA.
static boolean isWekaVersionOK ()
Checks if the Weka version is recent enough to run MOA.
static void main (String[] args)
Main method for running tasks from the command line.
Static Public Attributes
static final char[] progressAnimSequence
Array of characters to use to animate the progress of tasks running.
static final int MAX_STATUS_STRING_LENGTH = 79
Maximum length of the status string that shows the progress of tasks running.
Detailed Description
Class for running a MOA task from the command line.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 41 of file DoTask.java.
Member Function Documentation
static boolean moa.DoTask.isJavaVersionOK () [static]
Checks if the Java version is recent enough to run MOA.
Returns:
true if the Java version is recent.
Definition at line 55 of file DoTask.java.
Referenced by moa.DoTask.main().
{
        boolean isJavaVersionOK = true;
        String version = System.getProperty("java.version");
        char minor = version.charAt(2);
        char point = version.charAt(4);
        if (minor < '6' || point < '0') {
            isJavaVersionOK = false;
            System.err.println();
            System.err.println(Globals.getWorkbenchInfoString());
            System.err.println();
            System.err.print("JDK 1.6.0 or higher is required to run MOA. ");
            System.err.println("JDK version " + version + " found");
        }
        return isJavaVersionOK;
    }
static boolean moa.DoTask.isWekaVersionOK () [static]
Checks if the Weka version is recent enough to run MOA.
For example, if the Weka version is not recent, there may be problems due to the fact that Instance was a class before 3.7.1 and now is an interface.
Returns:
true if the Weka version is recent.
Definition at line 79 of file DoTask.java.
Referenced by moa.DoTask.main().
{
        Version version = new Version();
        if (version.isOlder("3.7.1")) {
            System.err.println();
            System.err.println(Globals.getWorkbenchInfoString());
            System.err.println();
            System.err.print("Weka 3.7.1 or higher is required to run MOA. ");
            System.err.println("Weka version " + Version.VERSION + " found");
            return false;
        } else {
            return true;
        }
    }
static void moa.DoTask.main (String[] args) [static]
Main method for running tasks from the command line.
Parameters:
args the options
Definition at line 98 of file DoTask.java.
References moa.tasks.Task.doTask(), moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.getCurrentActivityFracComplete(), moa.tasks.TaskThread.getCurrentActivityString(), moa.tasks.TaskThread.getCurrentStatusString(), moa.tasks.TaskThread.getFinalResult(), moa.options.IntOption.getValue(), moa.tasks.TaskThread.isComplete(), moa.DoTask.isJavaVersionOK(), moa.options.FlagOption.isSet, moa.DoTask.isWekaVersionOK(), moa.DoTask.MAX_STATUS_STRING_LENGTH, and moa.DoTask.progressAnimSequence.
{
        try {
            if (args.length < 1) {
                System.err.println();
                System.err.println(Globals.getWorkbenchInfoString());
                System.err.println();
                System.err.println("No task specified.");
            } else {
                if (isJavaVersionOK() == false || isWekaVersionOK() == false) {
                    return;
                }
                // create standard options
                FlagOption suppressStatusOutputOption = new FlagOption(
                        "suppressStatusOutput", 'S',
                        "Suppress the task status output that is normally send to stderr.");
                FlagOption suppressResultOutputOption = new FlagOption(
                        "suppressResultOutput", 'R',
                        "Suppress the task result output that is normally send to stdout.");
                IntOption statusUpdateFrequencyOption = new IntOption(
                        "statusUpdateFrequency",
                        'F',
                        "How many milliseconds to wait between status updates.",
                        1000, 0, Integer.MAX_VALUE);
                Option[] extraOptions = new Option[]{
                    suppressStatusOutputOption, suppressResultOutputOption,
                    statusUpdateFrequencyOption};
                // build a single string by concatenating cli options
                StringBuilder cliString = new StringBuilder();
                for (int i = 0; i < args.length; i++) {
                    cliString.append(" ").append(args[i]);
                }
                // parse options
                Task task = (Task) ClassOption.cliStringToObject(cliString.toString(), Task.class, extraOptions);
                Object result = null;
                if (suppressStatusOutputOption.isSet()) {
                    result = task.doTask();
                } else {
                    System.err.println();
                    System.err.println(Globals.getWorkbenchInfoString());
                    System.err.println();
                    boolean preciseTiming = TimingUtils.enablePreciseTiming();
                    // start the task thread
                    TaskThread taskThread = new TaskThread(task);
                    taskThread.start();
                    int progressAnimIndex = 0;
                    // inform user of progress
                    while (!taskThread.isComplete()) {
                        StringBuilder progressLine = new StringBuilder();
                        progressLine.append(progressAnimSequence[progressAnimIndex]);
                        progressLine.append(' ');
                        progressLine.append(StringUtils.secondsToDHMSString(taskThread.getCPUSecondsElapsed()));
                        progressLine.append(" [");
                        progressLine.append(taskThread.getCurrentStatusString());
                        progressLine.append("] ");
                        double fracComplete = taskThread.getCurrentActivityFracComplete();
                        if (fracComplete >= 0.0) {
                            progressLine.append(StringUtils.doubleToString(
                                    fracComplete * 100.0, 2, 2));
                            progressLine.append("% ");
                        }
                        progressLine.append(taskThread.getCurrentActivityString());
                        while (progressLine.length() < MAX_STATUS_STRING_LENGTH) {
                            progressLine.append(" ");
                        }
                        if (progressLine.length() > MAX_STATUS_STRING_LENGTH) {
                            progressLine.setLength(MAX_STATUS_STRING_LENGTH);
                            progressLine.setCharAt(
                                    MAX_STATUS_STRING_LENGTH - 1, '~');
                        }
                        System.err.print(progressLine.toString());
                        System.err.print('\r');
                        if (++progressAnimIndex >= progressAnimSequence.length) {
                            progressAnimIndex = 0;
                        }
                        try {
                            Thread.sleep(statusUpdateFrequencyOption.getValue());
                        } catch (InterruptedException ignored) {
                            // wake up
                        }
                    }
                    StringBuilder cleanupString = new StringBuilder();
                    for (int i = 0; i < MAX_STATUS_STRING_LENGTH; i++) {
                        cleanupString.append(' ');
                    }
                    System.err.println(cleanupString);
                    result = taskThread.getFinalResult();
                    if (!(result instanceof FailedTaskReport)) {
                        System.err.print("Task completed in "
                                + StringUtils.secondsToDHMSString(taskThread.getCPUSecondsElapsed()));
                        if (preciseTiming) {
                            System.err.print(" (CPU time)");
                        }
                        System.err.println();
                        System.err.println();
                    }
                }
                if (result instanceof FailedTaskReport) {
                    System.err.println("Task failed. Reason: ");
                    ((FailedTaskReport) result).getFailureReason().printStackTrace();
                } else {
                    if (!suppressResultOutputOption.isSet()) {
                        if (result instanceof Measurement[]) {
                            StringBuilder sb = new StringBuilder();
                            Measurement.getMeasurementsDescription(
                                    (Measurement[]) result, sb, 0);
                            System.out.println(sb.toString());
                        } else {
                            System.out.println(result);
                        }
                        System.out.flush();
                    }
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
Member Data Documentation
final int moa.DoTask.MAX_STATUS_STRING_LENGTH = 79 [static]
Maximum length of the status string that shows the progress of tasks running.
Definition at line 48 of file DoTask.java.
Referenced by moa.DoTask.main().
final char [] moa.DoTask.progressAnimSequence [static]
Initial value:
 new char[]{'-', '\\',
        '|', '/'}
Array of characters to use to animate the progress of tasks running.
Definition at line 44 of file DoTask.java.
Referenced by moa.DoTask.main().
The documentation for this class was generated from the following file:
main/java/moa/DoTask.java