MOA: moa.options.FileOption Class Reference
moa.options.FileOption Class Reference
File option.
Public Member Functions
FileOption (String name, char cliChar, String purpose, String defaultFileName, String defaultExtension, boolean isOutput)
String getDefaultFileExtension ()
boolean isOutputFile ()
File getFile ()
JComponent getEditComponent ()
Gets the GUI component to edit.
Protected Attributes
String defaultFileExtension
boolean isOutputFile
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
File option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 34 of file FileOption.java.
Constructor & Destructor Documentation
moa.options.FileOption.FileOption (String name, char cliChar, String purpose, String defaultFileName, String defaultExtension, boolean isOutput)
Definition at line 42 of file FileOption.java.
References moa.options.FileOption.defaultFileExtension, and moa.options.FileOption.isOutputFile().
{
        super(name, cliChar, purpose, defaultFileName);
        this.defaultFileExtension = defaultExtension;
        this.isOutputFile = isOutput;
    }
Member Function Documentation
String moa.options.FileOption.getDefaultFileExtension ()
Definition at line 49 of file FileOption.java.
References moa.options.FileOption.defaultFileExtension.
Referenced by moa.gui.FileOptionEditComponent.browseForFile().
{
        return this.defaultFileExtension;
    }
JComponent moa.options.FileOption.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Reimplemented from moa.options.AbstractOption.
Definition at line 65 of file FileOption.java.
{
        return new FileOptionEditComponent(this);
    }
File moa.options.FileOption.getFile ()
Definition at line 57 of file FileOption.java.
References moa.options.StringOption.getValue().
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.Plot.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.MainTask.doTaskImpl(), moa.recommender.dataset.impl.MovielensDataset.init(), moa.recommender.dataset.impl.JesterDataset.init(), moa.recommender.dataset.impl.FlixsterDataset.init(), moa.streams.clustering.FileStream.readMinMaxDiffValues(), moa.streams.clustering.FileStream.restart(), and moa.streams.ArffFileStream.restart().
{
        if ((getValue() != null) && (getValue().length() > 0)) {
            return new File(getValue());
        }
        return null;
    }
boolean moa.options.FileOption.isOutputFile ()
Definition at line 53 of file FileOption.java.
Referenced by moa.options.FileOption.FileOption().
{
        return this.isOutputFile;
    }
Member Data Documentation
String moa.options.FileOption.defaultFileExtension [protected]
Definition at line 38 of file FileOption.java.
Referenced by moa.options.FileOption.FileOption(), and moa.options.FileOption.getDefaultFileExtension().
boolean moa.options.FileOption.isOutputFile [protected]
Definition at line 40 of file FileOption.java.
Referenced by moa.gui.FileOptionEditComponent.browseForFile().
final long moa.options.FileOption.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.StringOption.
Definition at line 36 of file FileOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/FileOption.java