MOA: moa.classifiers.meta.AccuracyWeightedEnsembleTest Class Reference
moa.classifiers.meta.AccuracyWeightedEnsembleTest Class Reference
Tests the AccuracyWeightedEnsemble classifier.
Public Member Functions
AccuracyWeightedEnsembleTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the AccuracyWeightedEnsemble classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 34 of file AccuracyWeightedEnsembleTest.java.
Constructor & Destructor Documentation
moa.classifiers.meta.AccuracyWeightedEnsembleTest.AccuracyWeightedEnsembleTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 42 of file AccuracyWeightedEnsembleTest.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.meta.AccuracyWeightedEnsembleTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleClassifierTestCase.
Definition at line 53 of file AccuracyWeightedEnsembleTest.java.
{
    return new Classifier[]{
    new AccuracyWeightedEnsemble(),
    };
  }
static void moa.classifiers.meta.AccuracyWeightedEnsembleTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 73 of file AccuracyWeightedEnsembleTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.meta.AccuracyWeightedEnsembleTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.meta.AccuracyWeightedEnsembleTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 64 of file AccuracyWeightedEnsembleTest.java.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsembleTest.main().
{
    return new TestSuite(AccuracyWeightedEnsembleTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/meta/AccuracyWeightedEnsembleTest.java