MOA: moa.classifiers.functions.SGD Class Reference
moa.classifiers.functions.SGD Class Reference
Implements stochastic gradient descent for learning various linear models (binary class SVM, binary class logistic regression and linear regression).
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void setLambda (double lambda)
Set the value of lambda to use.
double getLambda ()
Get the current value of lambda.
void setLossFunction (int function)
Set the loss function to use.
int getLossFunction ()
Get the current loss function.
void setLearningRate (double lr)
Set the learning rate.
double getLearningRate ()
Get the learning rate.
void reset ()
Reset the classifier.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance instance)
Trains the classifier with the given instance.
double[] getVotesForInstance (Instance inst)
Calculates the class membership probabilities for the given test instance.
void getModelDescription (StringBuilder result, int indent)
Returns a string representation of the model.
String toString ()
Prints out the classifier.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
FloatOption lambdaRegularizationOption
FloatOption learningRateOption
MultiChoiceOption lossFunctionOption
Protected Member Functions
double dloss (double z)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Static Protected Member Functions
static double dotProd (Instance inst1, DoubleVector weights, int classIndex)
Protected Attributes
double m_lambda = 0.0001
The regularization parameter.
double m_learningRate = 0.01
The learning rate.
DoubleVector m_weights
Stores the weights (+ bias in the last element).
double m_bias
double m_t
Holds the current iteration number.
double m_numInstances
The number of training instances.
int m_loss = HINGE
The current loss function to minimize.
Static Protected Attributes
static final int HINGE = 0
static final int LOGLOSS = 1
static final int SQUAREDLOSS = 2
Static Private Attributes
static final long serialVersionUID = -3732968666673530290L
For serialization.
Detailed Description
Implements stochastic gradient descent for learning various linear models (binary class SVM, binary class logistic regression and linear regression).
Definition at line 47 of file SGD.java.
Member Function Documentation
double moa.classifiers.functions.SGD.dloss (double z) [protected]
Definition at line 161 of file SGD.java.
References moa.classifiers.functions.SGD.HINGE, moa.classifiers.functions.SGD.LOGLOSS, and moa.classifiers.functions.SGD.m_loss.
Referenced by moa.classifiers.functions.SGD.trainOnInstanceImpl().
{
        if (m_loss == HINGE) {
            return (z < 1) ? 1 : 0;
        }
        if (m_loss == LOGLOSS) {
            // log loss
            if (z < 0) {
                return 1.0 / (Math.exp(z) + 1.0);
            } else {
                double t = Math.exp(-z);
                return t / (t + 1);
            }
        }
        // squared loss
        return z;
    }
static double moa.classifiers.functions.SGD.dotProd (Instance inst1, DoubleVector weights, int classIndex) [static, protected]
Definition at line 180 of file SGD.java.
References moa.core.DoubleVector.getValue(), and moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.functions.SGD.getVotesForInstance(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
{
        double result = 0;
        int n1 = inst1.numValues();
        int n2 = weights.numValues();
        for (int p1 = 0, p2 = 0; p1 < n1 && p2 < n2;) {
            int ind1 = inst1.index(p1);
            int ind2 = p2;
            if (ind1 == ind2) {
                if (ind1 != classIndex && !inst1.isMissingSparse(p1)) {
                    result += inst1.valueSparse(p1) * weights.getValue(p2);
                }
                p1++;
                p2++;
            } else if (ind1 > ind2) {
                p2++;
            } else {
                p1++;
            }
        }
        return (result);
    }
double moa.classifiers.functions.SGD.getLambda ()
Get the current value of lambda.
Returns:
the current value of lambda
Definition at line 112 of file SGD.java.
References moa.classifiers.functions.SGD.m_lambda.
{
        return m_lambda;
    }
double moa.classifiers.functions.SGD.getLearningRate ()
Get the learning rate.
Returns:
the learning rate
Definition at line 148 of file SGD.java.
References moa.classifiers.functions.SGD.m_learningRate.
{
        return m_learningRate;
    }
int moa.classifiers.functions.SGD.getLossFunction ()
Get the current loss function.
Returns:
the current loss function.
Definition at line 130 of file SGD.java.
References moa.classifiers.functions.SGD.m_loss.
{
        return m_loss;
    }
void moa.classifiers.functions.SGD.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 319 of file SGD.java.
References moa.classifiers.functions.SGD.toString().
{
        StringUtils.appendIndented(result, indent, toString());
        StringUtils.appendNewline(result);
    }
Measurement [] moa.classifiers.functions.SGD.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 372 of file SGD.java.
{
        return null;
    }
String moa.classifiers.functions.SGD.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 53 of file SGD.java.
{
        return "AStochastic gradient descent for learning various linear models (binary class SVM, binary class logistic regression and linear regression).";
    }
double [] moa.classifiers.functions.SGD.getVotesForInstance (Instance inst)
Calculates the class membership probabilities for the given test instance.
Parameters:
instance the instance to be classified
Returns:
predicted class probability distribution
Implements moa.classifiers.Classifier.
Definition at line 281 of file SGD.java.
References moa.classifiers.functions.SGD.dotProd(), moa.classifiers.functions.SGD.LOGLOSS, moa.classifiers.functions.SGD.m_bias, moa.classifiers.functions.SGD.m_loss, and moa.classifiers.functions.SGD.m_weights.
{
        if (m_weights == null) {
            return new double[inst.numClasses()];
        }
        double[] result = (inst.classAttribute().isNominal())
                ? new double[2]
                : new double[1];
        double wx = dotProd(inst, m_weights, inst.classIndex());// * m_wScale;
        double z = (wx + m_bias);
        if (inst.classAttribute().isNumeric()) {
            result[0] = z;
            return result;
        }
        if (z <= 0) {
            //  z = 0;
            if (m_loss == LOGLOSS) {
                result[0] = 1.0 / (1.0 + Math.exp(z));
                result[1] = 1.0 - result[0];
            } else {
                result[0] = 1;
            }
        } else {
            if (m_loss == LOGLOSS) {
                result[1] = 1.0 / (1.0 + Math.exp(-z));
                result[0] = 1.0 - result[1];
            } else {
                result[1] = 1;
            }
        }
        return result;
    }
boolean moa.classifiers.functions.SGD.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 377 of file SGD.java.
{
        return false;
    }
void moa.classifiers.functions.SGD.reset ()
Reset the classifier.
Definition at line 155 of file SGD.java.
References moa.classifiers.functions.SGD.m_bias, moa.classifiers.functions.SGD.m_t, and moa.classifiers.functions.SGD.m_weights.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
{
        m_t = 1;
        m_weights = null;
        m_bias = 0.0;
    }
void moa.classifiers.functions.SGD.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 205 of file SGD.java.
References moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.classifiers.functions.SGD.lambdaRegularizationOption, moa.classifiers.functions.SGD.learningRateOption, moa.classifiers.functions.SGD.lossFunctionOption, moa.classifiers.functions.SGD.reset(), moa.classifiers.functions.SGD.setLambda(), moa.classifiers.functions.SGD.setLearningRate(), and moa.classifiers.functions.SGD.setLossFunction().
{
        reset();
        setLambda(this.lambdaRegularizationOption.getValue());
        setLearningRate(this.learningRateOption.getValue());
        setLossFunction(this.lossFunctionOption.getChosenIndex());
    }
void moa.classifiers.functions.SGD.setLambda (double lambda)
Set the value of lambda to use.
Parameters:
lambda the value of lambda to use
Definition at line 103 of file SGD.java.
References moa.classifiers.functions.SGD.m_lambda.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
{
        m_lambda = lambda;
    }
void moa.classifiers.functions.SGD.setLearningRate (double lr)
Set the learning rate.
Parameters:
lr the learning rate to use.
Definition at line 139 of file SGD.java.
References moa.classifiers.functions.SGD.m_learningRate.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
{
        m_learningRate = lr;
    }
void moa.classifiers.functions.SGD.setLossFunction (int function)
Set the loss function to use.
Parameters:
function the loss function to use.
Definition at line 121 of file SGD.java.
References moa.classifiers.functions.SGD.m_loss.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
{
        m_loss = function;
    }
String moa.classifiers.functions.SGD.toString ()
Prints out the classifier.
Returns:
a description of the classifier as a string
Reimplemented from moa.AbstractMOAObject.
Definition at line 329 of file SGD.java.
References moa.core.DoubleVector.getValue(), moa.classifiers.functions.SGD.HINGE, moa.classifiers.functions.SGD.LOGLOSS, moa.classifiers.functions.SGD.m_bias, moa.classifiers.functions.SGD.m_loss, moa.classifiers.functions.SGD.m_weights, and moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.functions.SGD.getModelDescription().
{
        if (m_weights == null) {
            return "SGD: No model built yet.\n";
        }
        StringBuffer buff = new StringBuffer();
        buff.append("Loss function: ");
        if (m_loss == HINGE) {
            buff.append("Hinge loss (SVM)\n\n");
        } else if (m_loss == LOGLOSS) {
            buff.append("Log loss (logistic regression)\n\n");
        } else {
            buff.append("Squared loss (linear regression)\n\n");
        }
        // buff.append(m_data.classAttribute().name() + " = \n\n");
        int printed = 0;
        for (int i = 0; i < m_weights.numValues(); i++) {
            // if (i != m_data.classIndex()) {
            if (printed > 0) {
                buff.append(" + ");
            } else {
                buff.append("   ");
            }
            buff.append(Utils.doubleToString(m_weights.getValue(i), 12, 4) + " "
                    // + m_data.attribute(i).name()
                    + "\n");
            printed++;
            //}
        }
        if (m_bias > 0) {
            buff.append(" + " + Utils.doubleToString(m_bias, 12, 4));
        } else {
            buff.append(" - " + Utils.doubleToString(-m_bias, 12, 4));
        }
        return buff.toString();
    }
void moa.classifiers.functions.SGD.trainOnInstanceImpl (Instance instance) [virtual]
Trains the classifier with the given instance.
Parameters:
instance the new training instance to include in the model
Implements moa.classifiers.AbstractClassifier.
Definition at line 218 of file SGD.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.functions.SGD.dloss(), moa.classifiers.functions.SGD.dotProd(), moa.core.DoubleVector.getValue(), moa.classifiers.functions.SGD.HINGE, moa.classifiers.functions.SGD.m_bias, moa.classifiers.functions.SGD.m_lambda, moa.classifiers.functions.SGD.m_learningRate, moa.classifiers.functions.SGD.m_loss, moa.classifiers.functions.SGD.m_numInstances, moa.classifiers.functions.SGD.m_t, moa.classifiers.functions.SGD.m_weights, moa.core.DoubleVector.numValues(), and moa.core.DoubleVector.setValue().
{
        if (m_weights == null) {
            m_weights = new DoubleVector(new double[instance.numAttributes()+1]);
            m_bias = 0.0;
        }
        if (!instance.classIsMissing()) {
            double wx = dotProd(instance, m_weights, instance.classIndex());
            double y;
            double z;
            if (instance.classAttribute().isNominal()) {
                y = (instance.classValue() == 0) ? -1 : 1;
                z = y * (wx + m_bias);
            } else {
                y = instance.classValue();
                z = y - (wx + m_bias);
                y = 1;
            }
            // Compute multiplier for weight decay
            double multiplier = 1.0;
            if (m_numInstances == 0) {
                multiplier = 1.0 - (m_learningRate * m_lambda) / m_t;
            } else {
                multiplier = 1.0 - (m_learningRate * m_lambda) / m_numInstances;
            }
            for (int i = 0; i < m_weights.numValues(); i++) {
                m_weights.setValue(i,m_weights.getValue (i) * multiplier);
            }
            // Only need to do the following if the loss is non-zero
            if (m_loss != HINGE || (z < 1)) {
                // Compute Factor for updates
                double factor = m_learningRate * y * dloss(z);
                // Update coefficients for attributes
                int n1 = instance.numValues();
                for (int p1 = 0; p1 < n1; p1++) {
                    int indS = instance.index(p1);
                    if (indS != instance.classIndex() && !instance.isMissingSparse(p1)) {
                        m_weights.addToValue(indS, factor * instance.valueSparse(p1));
                    }
                }
                // update the bias
                m_bias += factor;
            }
            m_t++;
        }
    }
Member Data Documentation
final int moa.classifiers.functions.SGD.HINGE = 0 [static, protected]
Definition at line 82 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.dloss(), moa.classifiers.functions.SGD.toString(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
FloatOption moa.classifiers.functions.SGD.lambdaRegularizationOption
Initial value:
 new FloatOption("lambdaRegularization",
            'l', "Lambda regularization parameter .",
            0.0001, 0.00, Integer.MAX_VALUE)
Definition at line 60 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
FloatOption moa.classifiers.functions.SGD.learningRateOption
Initial value:
 new FloatOption("learningRate",
            'r', "Learning rate parameter.",
            0.0001, 0.00, Integer.MAX_VALUE)
Definition at line 67 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
final int moa.classifiers.functions.SGD.LOGLOSS = 1 [static, protected]
Definition at line 84 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.dloss(), moa.classifiers.functions.SGD.getVotesForInstance(), and moa.classifiers.functions.SGD.toString().
MultiChoiceOption moa.classifiers.functions.SGD.lossFunctionOption
Initial value:
 new MultiChoiceOption(
            "lossFunction", 'o', "The loss function to use.", new String[]{
                "HINGE", "LOGLOSS", "SQUAREDLOSS"}, new String[]{
                "Hinge loss (SVM)",
                "Log loss (logistic regression)",
                "Squared loss (regression)"}, 0)
Definition at line 91 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.resetLearningImpl().
double moa.classifiers.functions.SGD.m_bias [protected]
Definition at line 74 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.getVotesForInstance(), moa.classifiers.functions.SGD.reset(), moa.classifiers.functions.SGD.toString(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
double moa.classifiers.functions.SGD.m_lambda = 0.0001 [protected]
The regularization parameter.
Definition at line 58 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.getLambda(), moa.classifiers.functions.SGD.setLambda(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
double moa.classifiers.functions.SGD.m_learningRate = 0.01 [protected]
The learning rate.
Definition at line 65 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.getLearningRate(), moa.classifiers.functions.SGD.setLearningRate(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
int moa.classifiers.functions.SGD.m_loss = HINGE [protected]
The current loss function to minimize.
Definition at line 89 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.dloss(), moa.classifiers.functions.SGD.getLossFunction(), moa.classifiers.functions.SGD.getVotesForInstance(), moa.classifiers.functions.SGD.setLossFunction(), moa.classifiers.functions.SGD.toString(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
double moa.classifiers.functions.SGD.m_numInstances [protected]
The number of training instances.
Definition at line 80 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.trainOnInstanceImpl().
double moa.classifiers.functions.SGD.m_t [protected]
Holds the current iteration number.
Definition at line 77 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.reset(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
DoubleVector moa.classifiers.functions.SGD.m_weights [protected]
Stores the weights (+ bias in the last element).
Definition at line 72 of file SGD.java.
Referenced by moa.classifiers.functions.SGD.getVotesForInstance(), moa.classifiers.functions.SGD.reset(), moa.classifiers.functions.SGD.toString(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
final long moa.classifiers.functions.SGD.serialVersionUID = -3732968666673530290L [static, private]
For serialization.
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 50 of file SGD.java.
final int moa.classifiers.functions.SGD.SQUAREDLOSS = 2 [static, protected]
Definition at line 86 of file SGD.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/functions/SGD.java