MOA: moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact Class Reference
moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact Class Reference
Public Member Functions
ISBNodeExact (Instance inst, StreamObj obj, Long id, int k)
void AddPrecNeigh (Long id)
int CountPrecNeighs (Long sinceId)
void PrintPrecNeighs ()
Public Attributes
int count_after
Private Attributes
ArrayList< Long > nn_before
Detailed Description
Definition at line 38 of file ExactSTORM.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.ISBNodeExact (Instance inst, StreamObj obj, Long id, int k)
Definition at line 45 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after, moa.clusterers.outliers.Angiulli.STORMBase.m_k, and moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.nn_before.
{
            super(inst, obj, id);
            m_k = k;
            count_after = 0;
            nn_before = new ArrayList<Long>();
        }
Member Function Documentation
void moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.AddPrecNeigh (Long id)
Definition at line 52 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.nn_before.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj().
{
            int pos = Collections.binarySearch(nn_before, id);
            if (pos < 0) {
                // item does not exist, so add it to the right position
                nn_before.add(-(pos + 1), id);
            }
        }
int moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.CountPrecNeighs (Long sinceId)
Definition at line 60 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.nn_before.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.getObjectInfo(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType().
{
            if (nn_before.size() > 0) {
                // get number of neighs with id >= sinceId
                int startPos;
                int pos = Collections.binarySearch(nn_before, sinceId);
                if (pos < 0) {
                    // item does not exist, should insert at position startPos
                    startPos = -(pos + 1);
                } else {
                    // item exists at startPos
                    startPos = pos;
                }
                if (startPos < nn_before.size()) {
                    return nn_before.size() - startPos;
                }
            }
            return 0;
        }
void moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.PrintPrecNeighs ()
Definition at line 80 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.nn_before, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType().
{
            Print("      nn_before: ");
            Iterator it = nn_before.iterator();
            while (it.hasNext()) {
                Print((Long)it.next() + " ");
            }
            Println(" ");
        }
Member Data Documentation
int moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after
Definition at line 39 of file ExactSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.getObjectInfo(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.ISBNodeExact(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType().
ArrayList<Long> moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.nn_before [private]
Definition at line 43 of file ExactSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.AddPrecNeigh(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.CountPrecNeighs(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.ISBNodeExact(), and moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.PrintPrecNeighs().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/Angiulli/ExactSTORM.java