MOA: moa.gui.clustertab.ClusteringVisualTab Class Reference
moa.gui.clustertab.ClusteringVisualTab Class Reference
Public Member Functions
ClusteringVisualTab ()
Creates new form ClusteringVisualTab.
void setClusteringSetupTab (ClusteringSetupTab clusteringSetupTab)
void setDimensionComobBoxes (int numDimensions)
StreamPanel getLeftStreamPanel ()
StreamPanel getRightStreamPanel ()
GraphCanvas getGraphCanvas ()
ClusteringVisualEvalPanel getEvalPanel ()
boolean isEnabledDrawPoints ()
boolean isEnabledDrawGroundTruth ()
boolean isEnabledDrawMicroclustering ()
boolean isEnabledDrawClustering ()
void setProcessedPointsCounter (int value)
int getPauseInterval ()
void setPauseInterval (int pause)
void repaint ()
void toggleVisualizer (boolean internal)
void stopVisualizer ()
void actionPerformed (ActionEvent e)
Private Member Functions
void resetComponents ()
void createVisualiterThread ()
void initComponents ()
This method is called from within the constructor to initialize the form.
void buttonScreenshotMouseClicked (java.awt.event.MouseEvent evt)
void buttonRunMouseClicked (java.awt.event.MouseEvent evt)
void speedSliderMouseDragged (java.awt.event.MouseEvent evt)
void scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt)
void buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawPointsActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawMicroActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawGTActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawClusteringActionPerformed (java.awt.event.ActionEvent evt)
void comboXActionPerformed (java.awt.event.ActionEvent evt)
void comboYActionPerformed (java.awt.event.ActionEvent evt)
void buttonStopActionPerformed (java.awt.event.ActionEvent evt)
void buttonRunActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
RunVisualizer visualizer = null
Thread visualizerThread = null
Boolean running = false
ClusteringSetupTab clusteringSetupTab = null
String exportFile
String screenshotFilebase
javax.swing.JButton buttonRun
javax.swing.JButton buttonScreenshot
javax.swing.JButton buttonStop
javax.swing.JButton buttonZoomInX
javax.swing.JButton buttonZoomInY
javax.swing.JButton buttonZoomOutX
javax.swing.JButton buttonZoomOutY
javax.swing.JCheckBox checkboxDrawClustering
javax.swing.JCheckBox checkboxDrawGT
javax.swing.JCheckBox checkboxDrawMicro
javax.swing.JCheckBox checkboxDrawPoints
moa.gui.clustertab.ClusteringVisualEvalPanel clusteringVisualEvalPanel1
javax.swing.JComboBox comboX
javax.swing.JComboBox comboY
moa.gui.visualization.GraphCanvas graphCanvas
javax.swing.JPanel graphPanel
javax.swing.JPanel graphPanelControlBottom
javax.swing.JPanel graphPanelControlTop
javax.swing.JScrollPane graphScrollPanel
javax.swing.JLabel jLabel1
javax.swing.JSplitPane jSplitPane1
javax.swing.JLabel labelEvents
javax.swing.JLabel labelNumPause
javax.swing.JLabel labelX
javax.swing.JLabel labelY
javax.swing.JLabel label_processed_points
javax.swing.JLabel label_processed_points_value
javax.swing.JTextField numPauseAfterPoints
javax.swing.JPanel panelControl
javax.swing.JPanel panelEvalOutput
javax.swing.JPanel panelVisualWrapper
javax.swing.JScrollPane scrollPane0
javax.swing.JScrollPane scrollPane1
javax.swing.JSlider speedSlider
javax.swing.JSplitPane splitVisual
moa.gui.visualization.StreamPanel streamPanel0
moa.gui.visualization.StreamPanel streamPanel1
javax.swing.JPanel topWrapper
Detailed Description
Definition at line 36 of file ClusteringVisualTab.java.
Constructor & Destructor Documentation
moa.gui.clustertab.ClusteringVisualTab.ClusteringVisualTab ()
Creates new form ClusteringVisualTab.
Definition at line 45 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.resetComponents().
Referenced by moa.gui.clustertab.ClusteringTabPanel.initComponents().
{
        resetComponents();
    }
Member Function Documentation
void moa.gui.clustertab.ClusteringVisualTab.actionPerformed (ActionEvent e)
Definition at line 742 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
{
        if(e.getSource() instanceof JButton){
            if(e.getActionCommand().equals("csv export")){
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setAcceptAllFileFilterUsed(true);
                fileChooser.addChoosableFileFilter(new FileExtensionFilter("csv"));
                if(exportFile!=null)
                    fileChooser.setSelectedFile(new File(exportFile));
                if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    exportFile = fileChooser.getSelectedFile().getPath();
                    visualizer.exportCSV(exportFile);
                }
            }
            if(e.getActionCommand().equals("weka export")){
                visualizer.weka();
            }
        }
    }
void moa.gui.clustertab.ClusteringVisualTab.buttonRunActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 696 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                          {//GEN-FIRST:event_buttonRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRunActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.buttonRunMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 623 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                      {//GEN-FIRST:event_buttonRunMouseClicked
        toggleVisualizer(true);
    }//GEN-LAST:event_buttonRunMouseClicked
void moa.gui.clustertab.ClusteringVisualTab.buttonScreenshotMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 610 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                             {//GEN-FIRST:event_buttonScreenshotMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        if(screenshotFilebase!=null)
            fileChooser.setSelectedFile(new File(screenshotFilebase));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            screenshotFilebase = fileChooser.getSelectedFile().getPath();
            streamPanel0.screenshot(screenshotFilebase+"_"+label_processed_points_value.getText()+"_0", true, true);
            streamPanel1.screenshot(screenshotFilebase+"_"+label_processed_points_value.getText()+"_1", true, true);
        }
    }//GEN-LAST:event_buttonScreenshotMouseClicked
void moa.gui.clustertab.ClusteringVisualTab.buttonStopActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 691 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                           {//GEN-FIRST:event_buttonStopActionPerformed
        stopVisualizer();
        clusteringSetupTab.stopRun();
    }//GEN-LAST:event_buttonStopActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 636 of file ClusteringVisualTab.java.
                                                                              {//GEN-FIRST:event_buttonZoomInXActionPerformed
        graphCanvas.scaleXResolution(false);
    }//GEN-LAST:event_buttonZoomInXActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 649 of file ClusteringVisualTab.java.
                                                                              {//GEN-FIRST:event_buttonZoomInYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*1.2)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*1.2)));
    }//GEN-LAST:event_buttonZoomInYActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 645 of file ClusteringVisualTab.java.
                                                                               {//GEN-FIRST:event_buttonZoomOutXActionPerformed
        graphCanvas.scaleXResolution(true);
    }//GEN-LAST:event_buttonZoomOutXActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 640 of file ClusteringVisualTab.java.
                                                                               {//GEN-FIRST:event_buttonZoomOutYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*0.8)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*0.8)));
    }//GEN-LAST:event_buttonZoomOutYActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.checkboxDrawClusteringActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 668 of file ClusteringVisualTab.java.
                                                                                       {//GEN-FIRST:event_checkboxDrawClusteringActionPerformed
        //visualizer.redrawClusterings();
        visualizer.setMacroVisibility(checkboxDrawClustering.isSelected());
    }//GEN-LAST:event_checkboxDrawClusteringActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.checkboxDrawGTActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 663 of file ClusteringVisualTab.java.
                                                                               {//GEN-FIRST:event_checkboxDrawGTActionPerformed
        //visualizer.redrawClusterings();
        visualizer.setGroundTruthVisibility(checkboxDrawGT.isSelected());
    }//GEN-LAST:event_checkboxDrawGTActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.checkboxDrawMicroActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 658 of file ClusteringVisualTab.java.
                                                                                  {//GEN-FIRST:event_checkboxDrawMicroActionPerformed
        //visualizer.redrawClusterings();
        visualizer.setMicroLayerVisibility(checkboxDrawMicro.isSelected());
    }//GEN-LAST:event_checkboxDrawMicroActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.checkboxDrawPointsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 654 of file ClusteringVisualTab.java.
                                                                                   {//GEN-FIRST:event_checkboxDrawPointsActionPerformed
        visualizer.setPointLayerVisibility(checkboxDrawPoints.isSelected());
    }//GEN-LAST:event_checkboxDrawPointsActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.comboXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 673 of file ClusteringVisualTab.java.
                                                                       {//GEN-FIRST:event_comboXActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        int dim = cb.getSelectedIndex();
        streamPanel0.setActiveXDim(dim);
        streamPanel1.setActiveXDim(dim);
        if(visualizer!=null)
            visualizer.redraw();
    }//GEN-LAST:event_comboXActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.comboYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 682 of file ClusteringVisualTab.java.
                                                                       {//GEN-FIRST:event_comboYActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        int dim = cb.getSelectedIndex();
        streamPanel0.setActiveYDim(dim);
        streamPanel1.setActiveYDim(dim);
        if(visualizer!=null)
            visualizer.redraw();
    }//GEN-LAST:event_comboYActionPerformed
void moa.gui.clustertab.ClusteringVisualTab.createVisualiterThread () [private]
Definition at line 64 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.clusteringSetupTab, moa.gui.clustertab.ClusteringVisualTab.visualizer, and moa.gui.clustertab.ClusteringVisualTab.visualizerThread.
Referenced by moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
{
        visualizer = new RunVisualizer(this, clusteringSetupTab);
        visualizerThread = new Thread(visualizer);
    }
ClusteringVisualEvalPanel moa.gui.clustertab.ClusteringVisualTab.getEvalPanel ()
Definition at line 92 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.clusteringVisualEvalPanel1.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return clusteringVisualEvalPanel1;
    }
GraphCanvas moa.gui.clustertab.ClusteringVisualTab.getGraphCanvas ()
Definition at line 88 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.graphCanvas.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return graphCanvas;
    }
StreamPanel moa.gui.clustertab.ClusteringVisualTab.getLeftStreamPanel ()
Definition at line 80 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.streamPanel0.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return streamPanel0;
    }
int moa.gui.clustertab.ClusteringVisualTab.getPauseInterval ()
Definition at line 115 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.numPauseAfterPoints.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        return Integer.parseInt(numPauseAfterPoints.getText());
    }
StreamPanel moa.gui.clustertab.ClusteringVisualTab.getRightStreamPanel ()
Definition at line 84 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.streamPanel1.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return streamPanel1;
    }
void moa.gui.clustertab.ClusteringVisualTab.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 170 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.actionPerformed(), moa.gui.clustertab.ClusteringVisualTab.buttonRun, moa.gui.clustertab.ClusteringVisualTab.buttonRunActionPerformed(), moa.gui.clustertab.ClusteringVisualTab.buttonRunMouseClicked(), moa.gui.clustertab.ClusteringVisualTab.buttonScreenshot, moa.gui.clustertab.ClusteringVisualTab.buttonScreenshotMouseClicked(), moa.gui.clustertab.ClusteringVisualTab.buttonStop, moa.gui.clustertab.ClusteringVisualTab.buttonStopActionPerformed(), moa.gui.clustertab.ClusteringVisualTab.buttonZoomInX, moa.gui.clustertab.ClusteringVisualTab.buttonZoomInY, moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutX, moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutY, moa.gui.clustertab.ClusteringVisualTab.checkboxDrawClustering, moa.gui.clustertab.ClusteringVisualTab.checkboxDrawGT, moa.gui.clustertab.ClusteringVisualTab.checkboxDrawMicro, moa.gui.clustertab.ClusteringVisualTab.checkboxDrawPoints, moa.gui.clustertab.ClusteringVisualEvalPanel.ClusteringVisualEvalPanel(), moa.gui.clustertab.ClusteringVisualTab.clusteringVisualEvalPanel1, moa.gui.clustertab.ClusteringVisualTab.comboX, moa.gui.clustertab.ClusteringVisualTab.comboY, moa.gui.visualization.GraphCanvas.GraphCanvas(), moa.gui.clustertab.ClusteringVisualTab.graphCanvas, moa.gui.clustertab.ClusteringVisualTab.graphPanel, moa.gui.clustertab.ClusteringVisualTab.graphPanelControlBottom, moa.gui.clustertab.ClusteringVisualTab.graphPanelControlTop, moa.gui.clustertab.ClusteringVisualTab.graphScrollPanel, moa.gui.clustertab.ClusteringVisualTab.jLabel1, moa.gui.clustertab.ClusteringVisualTab.jSplitPane1, moa.gui.clustertab.ClusteringVisualTab.label_processed_points, moa.gui.clustertab.ClusteringVisualTab.label_processed_points_value, moa.gui.clustertab.ClusteringVisualTab.labelEvents, moa.gui.clustertab.ClusteringVisualTab.labelNumPause, moa.gui.clustertab.ClusteringVisualTab.labelX, moa.gui.clustertab.ClusteringVisualTab.labelY, moa.gui.clustertab.ClusteringVisualTab.numPauseAfterPoints, moa.gui.clustertab.ClusteringVisualTab.panelControl, moa.gui.clustertab.ClusteringVisualTab.panelEvalOutput, moa.gui.clustertab.ClusteringVisualTab.panelVisualWrapper, moa.gui.clustertab.ClusteringVisualTab.scrollPane0, moa.gui.clustertab.ClusteringVisualTab.scrollPane0MouseWheelMoved(), moa.gui.clustertab.ClusteringVisualTab.scrollPane1, moa.gui.clustertab.ClusteringVisualTab.speedSlider, moa.gui.clustertab.ClusteringVisualTab.speedSliderMouseDragged(), moa.gui.clustertab.ClusteringVisualTab.splitVisual, moa.gui.visualization.StreamPanel.StreamPanel(), moa.gui.clustertab.ClusteringVisualTab.streamPanel0, moa.gui.clustertab.ClusteringVisualTab.streamPanel1, and moa.gui.clustertab.ClusteringVisualTab.topWrapper.
Referenced by moa.gui.clustertab.ClusteringVisualTab.resetComponents().
{
        java.awt.GridBagConstraints gridBagConstraints;
        jSplitPane1 = new javax.swing.JSplitPane();
        topWrapper = new javax.swing.JPanel();
        panelVisualWrapper = new javax.swing.JPanel();
        splitVisual = new javax.swing.JSplitPane();
        scrollPane1 = new javax.swing.JScrollPane();
        streamPanel1 = new moa.gui.visualization.StreamPanel();
        scrollPane0 = new javax.swing.JScrollPane();
        streamPanel0 = new moa.gui.visualization.StreamPanel();
        panelControl = new javax.swing.JPanel();
        buttonRun = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonScreenshot = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        comboX = new javax.swing.JComboBox();
        labelX = new javax.swing.JLabel();
        comboY = new javax.swing.JComboBox();
        labelY = new javax.swing.JLabel();
        checkboxDrawPoints = new javax.swing.JCheckBox();
        checkboxDrawGT = new javax.swing.JCheckBox();
        checkboxDrawMicro = new javax.swing.JCheckBox();
        checkboxDrawClustering = new javax.swing.JCheckBox();
        label_processed_points = new javax.swing.JLabel();
        label_processed_points_value = new javax.swing.JLabel();
        labelNumPause = new javax.swing.JLabel();
        numPauseAfterPoints = new javax.swing.JTextField();
        panelEvalOutput = new javax.swing.JPanel();
        clusteringVisualEvalPanel1 = new moa.gui.clustertab.ClusteringVisualEvalPanel();
        graphPanel = new javax.swing.JPanel();
        graphPanelControlTop = new javax.swing.JPanel();
        buttonZoomInY = new javax.swing.JButton();
        buttonZoomOutY = new javax.swing.JButton();
        labelEvents = new javax.swing.JLabel();
        graphScrollPanel = new javax.swing.JScrollPane();
        graphCanvas = new moa.gui.visualization.GraphCanvas();
        graphPanelControlBottom = new javax.swing.JPanel();
        buttonZoomInX = new javax.swing.JButton();
        buttonZoomOutX = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        topWrapper.setPreferredSize(new java.awt.Dimension(688, 500));
        topWrapper.setLayout(new java.awt.GridBagLayout());
        panelVisualWrapper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelVisualWrapper.setLayout(new java.awt.BorderLayout());
        splitVisual.setDividerLocation(403);
        splitVisual.setResizeWeight(1.0);
        streamPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        javax.swing.GroupLayout streamPanel1Layout = new javax.swing.GroupLayout(streamPanel1);
        streamPanel1.setLayout(streamPanel1Layout);
        streamPanel1Layout.setHorizontalGroup(
            streamPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        streamPanel1Layout.setVerticalGroup(
            streamPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        scrollPane1.setViewportView(streamPanel1);
        splitVisual.setRightComponent(scrollPane1);
        scrollPane0.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrollPane0MouseWheelMoved(evt);
            }
        });
        streamPanel0.setPreferredSize(new java.awt.Dimension(400, 250));
        javax.swing.GroupLayout streamPanel0Layout = new javax.swing.GroupLayout(streamPanel0);
        streamPanel0.setLayout(streamPanel0Layout);
        streamPanel0Layout.setHorizontalGroup(
            streamPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        streamPanel0Layout.setVerticalGroup(
            streamPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        scrollPane0.setViewportView(streamPanel0);
        splitVisual.setLeftComponent(scrollPane0);
        panelVisualWrapper.add(splitVisual, java.awt.BorderLayout.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        topWrapper.add(panelVisualWrapper, gridBagConstraints);
        panelControl.setMinimumSize(new java.awt.Dimension(600, 76));
        panelControl.setPreferredSize(new java.awt.Dimension(2000, 76));
        panelControl.setLayout(new java.awt.GridBagLayout());
        buttonRun.setText("Start");
        buttonRun.setPreferredSize(new java.awt.Dimension(70, 33));
        buttonRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRunMouseClicked(evt);
            }
        });
        buttonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 1, 5);
        panelControl.add(buttonRun, gridBagConstraints);
        buttonStop.setText("Stop");
        buttonStop.setPreferredSize(new java.awt.Dimension(70, 33));
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 1, 5);
        panelControl.add(buttonStop, gridBagConstraints);
        buttonScreenshot.setText("Screenshot");
        buttonScreenshot.setPreferredSize(new java.awt.Dimension(90, 23));
        buttonScreenshot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonScreenshotMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 1, 5);
        // ### panelControl.add(buttonScreenshot, gridBagConstraints);
        speedSlider.setValue(100);
        speedSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualisation Speed"));
        speedSlider.setMinimumSize(new java.awt.Dimension(150, 68));
        speedSlider.setPreferredSize(new java.awt.Dimension(160, 68));
        speedSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                speedSliderMouseDragged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 1, 5);
        panelControl.add(speedSlider, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelControl.add(jLabel1, gridBagConstraints);
        comboX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dim 1", "Dim 2", "Dim 3", "Dim 4" }));
        comboX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboXActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(comboX, gridBagConstraints);
        labelX.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 5);
        panelControl.add(labelX, gridBagConstraints);
        comboY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dim 1", "Dim 2", "Dim 3", "Dim 4" }));
        comboY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(comboY, gridBagConstraints);
        labelY.setText("Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 5);
        panelControl.add(labelY, gridBagConstraints);
        checkboxDrawPoints.setSelected(true);
        checkboxDrawPoints.setText("Points");
        checkboxDrawPoints.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawPointsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 4);
        panelControl.add(checkboxDrawPoints, gridBagConstraints);
        checkboxDrawGT.setSelected(true);
        checkboxDrawGT.setText("Ground truth");
        checkboxDrawGT.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawGTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(checkboxDrawGT, gridBagConstraints);
        checkboxDrawMicro.setSelected(true);
        checkboxDrawMicro.setText("Microclustering");
        checkboxDrawMicro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawMicro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawMicroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 4);
        panelControl.add(checkboxDrawMicro, gridBagConstraints);
        checkboxDrawClustering.setSelected(true);
        checkboxDrawClustering.setText("Clustering");
        checkboxDrawClustering.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawClustering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawClusteringActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(checkboxDrawClustering, gridBagConstraints);
        label_processed_points.setText("Processed:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panelControl.add(label_processed_points, gridBagConstraints);
        label_processed_points_value.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelControl.add(label_processed_points_value, gridBagConstraints);
        labelNumPause.setText("Pause in:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panelControl.add(labelNumPause, gridBagConstraints);
        numPauseAfterPoints.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPauseAfterPoints.setText(Integer.toString(RunVisualizer.initialPauseInterval));
        numPauseAfterPoints.setMinimumSize(new java.awt.Dimension(70, 25));
        numPauseAfterPoints.setPreferredSize(new java.awt.Dimension(70, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelControl.add(numPauseAfterPoints, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        topWrapper.add(panelControl, gridBagConstraints);
        jSplitPane1.setLeftComponent(topWrapper);
        panelEvalOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluation"));
        panelEvalOutput.setLayout(new java.awt.GridBagLayout());
        clusteringVisualEvalPanel1.setMinimumSize(new java.awt.Dimension(280, 118));
        clusteringVisualEvalPanel1.setPreferredSize(new java.awt.Dimension(290, 115));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        panelEvalOutput.add(clusteringVisualEvalPanel1, gridBagConstraints);
        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plot"));
        graphPanel.setPreferredSize(new java.awt.Dimension(530, 115));
        graphPanel.setLayout(new java.awt.GridBagLayout());
        graphPanelControlTop.setLayout(new java.awt.GridBagLayout());
        buttonZoomInY.setText("Zoom in Y");
        buttonZoomInY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomInY, gridBagConstraints);
        buttonZoomOutY.setText("Zoom out Y");
        buttonZoomOutY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomOutY, gridBagConstraints);
        labelEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(labelEvents, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        graphPanel.add(graphPanelControlTop, gridBagConstraints);
        graphCanvas.setPreferredSize(new java.awt.Dimension(500, 111));
        javax.swing.GroupLayout graphCanvasLayout = new javax.swing.GroupLayout(graphCanvas);
        graphCanvas.setLayout(graphCanvasLayout);
        graphCanvasLayout.setHorizontalGroup(
            graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        graphCanvasLayout.setVerticalGroup(
            graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        graphScrollPanel.setViewportView(graphCanvas);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        graphPanel.add(graphScrollPanel, gridBagConstraints);
        buttonZoomInX.setText("Zoom in X");
        buttonZoomInX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomInX);
        buttonZoomOutX.setText("Zoom out X");
        buttonZoomOutX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomOutX);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        graphPanel.add(graphPanelControlBottom, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        panelEvalOutput.add(graphPanel, gridBagConstraints);
        jSplitPane1.setRightComponent(panelEvalOutput);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
boolean moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawClustering ()
Definition at line 107 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.checkboxDrawClustering.
{
        return checkboxDrawClustering.isSelected();
    }
boolean moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawGroundTruth ()
Definition at line 100 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.checkboxDrawGT.
{
        return checkboxDrawGT.isSelected();
    }
boolean moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawMicroclustering ()
Definition at line 104 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.checkboxDrawMicro.
{
        return checkboxDrawMicro.isSelected();
    }
boolean moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawPoints ()
Definition at line 96 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.checkboxDrawPoints.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        return checkboxDrawPoints.isSelected();
    }
void moa.gui.clustertab.ClusteringVisualTab.repaint ()
Definition at line 124 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.splitVisual.
{
        if(splitVisual!=null)
            splitVisual.setDividerLocation(splitVisual.getWidth()/2);
        super.repaint();
    }
void moa.gui.clustertab.ClusteringVisualTab.resetComponents () [private]
Definition at line 49 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.comboY, moa.gui.clustertab.ClusteringVisualTab.graphCanvas, moa.gui.clustertab.ClusteringVisualTab.graphScrollPanel, moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.visualization.GraphCanvas.setViewport().
Referenced by moa.gui.clustertab.ClusteringVisualTab.ClusteringVisualTab(), and moa.gui.clustertab.ClusteringVisualTab.stopVisualizer().
{
        initComponents();
        comboY.setSelectedIndex(1);
        graphCanvas.setViewport(graphScrollPanel.getViewport());
        //TODO this needs to only affect the visual Panel
        ToolTipManager.sharedInstance().setDismissDelay(20000);
        ToolTipManager.sharedInstance().setInitialDelay(100);
    }
void moa.gui.clustertab.ClusteringVisualTab.scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt) [private]
Definition at line 632 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                                {//GEN-FIRST:event_scrollPane0MouseWheelMoved
        streamPanel0.setZoom(evt.getX(),evt.getY(),(-1)*evt.getWheelRotation(),scrollPane0);
    }//GEN-LAST:event_scrollPane0MouseWheelMoved
void moa.gui.clustertab.ClusteringVisualTab.setClusteringSetupTab (ClusteringSetupTab clusteringSetupTab)
Definition at line 59 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel().
{
        this.clusteringSetupTab = clusteringSetupTab;
    }
void moa.gui.clustertab.ClusteringVisualTab.setDimensionComobBoxes (int numDimensions)
Definition at line 69 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.comboX, and moa.gui.clustertab.ClusteringVisualTab.comboY.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        String[] dimensions = new String[numDimensions];
        for (int i = 0; i < dimensions.length; i++) {
            dimensions[i] = "Dim "+(i+1);
        }
        comboX.setModel(new javax.swing.DefaultComboBoxModel(dimensions));
        comboY.setModel(new javax.swing.DefaultComboBoxModel(dimensions));
        comboY.setSelectedIndex(1);
    }
void moa.gui.clustertab.ClusteringVisualTab.setPauseInterval (int pause)
Definition at line 119 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.numPauseAfterPoints.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        numPauseAfterPoints.setText(Integer.toString(pause));
    }
void moa.gui.clustertab.ClusteringVisualTab.setProcessedPointsCounter (int value)
Definition at line 111 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.label_processed_points_value.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        label_processed_points_value.setText(Integer.toString(value));
    }
void moa.gui.clustertab.ClusteringVisualTab.speedSliderMouseDragged (java.awt.event.MouseEvent evt) [private]
Definition at line 627 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
                                                                        {//GEN-FIRST:event_speedSliderMouseDragged
        visualizer.setSpeed((int)(speedSlider.getValue()/(100.0/15.0)));
    }//GEN-LAST:event_speedSliderMouseDragged
void moa.gui.clustertab.ClusteringVisualTab.stopVisualizer ()
Definition at line 153 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.resetComponents(), moa.gui.clustertab.ClusteringVisualTab.running, moa.gui.visualization.RunVisualizer.stop, moa.gui.clustertab.ClusteringVisualTab.visualizer, and moa.gui.clustertab.ClusteringVisualTab.visualizerThread.
Referenced by moa.gui.clustertab.ClusteringTabPanel.stop().
{
        visualizer.stop();
        running = false;
        visualizer = null;
        visualizerThread = null;
        removeAll();
        resetComponents();
    }
void moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer (boolean internal)
Definition at line 130 of file ClusteringVisualTab.java.
References moa.gui.clustertab.ClusteringVisualTab.buttonRun, moa.gui.clustertab.ClusteringVisualTab.clusteringSetupTab, moa.gui.clustertab.ClusteringVisualTab.createVisualiterThread(), moa.gui.visualization.RunVisualizer.pause(), moa.gui.visualization.RunVisualizer.resume(), moa.gui.clustertab.ClusteringVisualTab.running, moa.gui.clustertab.ClusteringSetupTab.toggleRunMode(), moa.gui.clustertab.ClusteringVisualTab.visualizer, and moa.gui.clustertab.ClusteringVisualTab.visualizerThread.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.clustertab.ClusteringTabPanel.toggle().
{
        if(visualizer == null)
            createVisualiterThread();
        if(!visualizerThread.isAlive()){
            visualizerThread.start();
        }
        //pause
        if(running){
            running = false;
            visualizer.pause();
            buttonRun.setText("Resume");
        }
        else{
            running = true;
            visualizer.resume();
            buttonRun.setText("Pause");
        }
        if(internal)
            clusteringSetupTab.toggleRunMode();
    }
Member Data Documentation
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonRun [private]
Definition at line 702 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonScreenshot [private]
Definition at line 703 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonStop [private]
Definition at line 704 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonZoomInX [private]
Definition at line 705 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonZoomInY [private]
Definition at line 706 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutX [private]
Definition at line 707 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JButton moa.gui.clustertab.ClusteringVisualTab.buttonZoomOutY [private]
Definition at line 708 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JCheckBox moa.gui.clustertab.ClusteringVisualTab.checkboxDrawClustering [private]
Definition at line 709 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawClustering().
javax.swing.JCheckBox moa.gui.clustertab.ClusteringVisualTab.checkboxDrawGT [private]
Definition at line 710 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawGroundTruth().
javax.swing.JCheckBox moa.gui.clustertab.ClusteringVisualTab.checkboxDrawMicro [private]
Definition at line 711 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawMicroclustering().
javax.swing.JCheckBox moa.gui.clustertab.ClusteringVisualTab.checkboxDrawPoints [private]
Definition at line 712 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawPoints().
ClusteringSetupTab moa.gui.clustertab.ClusteringVisualTab.clusteringSetupTab = null [private]
Definition at line 40 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.createVisualiterThread(), and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
moa.gui.clustertab.ClusteringVisualEvalPanel moa.gui.clustertab.ClusteringVisualTab.clusteringVisualEvalPanel1 [private]
Definition at line 713 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.getEvalPanel(), and moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JComboBox moa.gui.clustertab.ClusteringVisualTab.comboX [private]
Definition at line 714 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.setDimensionComobBoxes().
javax.swing.JComboBox moa.gui.clustertab.ClusteringVisualTab.comboY [private]
Definition at line 715 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), moa.gui.clustertab.ClusteringVisualTab.resetComponents(), and moa.gui.clustertab.ClusteringVisualTab.setDimensionComobBoxes().
String moa.gui.clustertab.ClusteringVisualTab.exportFile [private]
Definition at line 41 of file ClusteringVisualTab.java.
moa.gui.visualization.GraphCanvas moa.gui.clustertab.ClusteringVisualTab.graphCanvas [private]
Definition at line 716 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.getGraphCanvas(), moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.resetComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.graphPanel [private]
Definition at line 717 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.graphPanelControlBottom [private]
Definition at line 718 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.graphPanelControlTop [private]
Definition at line 719 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JScrollPane moa.gui.clustertab.ClusteringVisualTab.graphScrollPanel [private]
Definition at line 720 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.resetComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.jLabel1 [private]
Definition at line 721 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JSplitPane moa.gui.clustertab.ClusteringVisualTab.jSplitPane1 [private]
Definition at line 722 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.label_processed_points [private]
Definition at line 727 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.label_processed_points_value [private]
Definition at line 728 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.setProcessedPointsCounter().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.labelEvents [private]
Definition at line 723 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.labelNumPause [private]
Definition at line 724 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.labelX [private]
Definition at line 725 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JLabel moa.gui.clustertab.ClusteringVisualTab.labelY [private]
Definition at line 726 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JTextField moa.gui.clustertab.ClusteringVisualTab.numPauseAfterPoints [private]
Definition at line 729 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.getPauseInterval(), moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.setPauseInterval().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.panelControl [private]
Definition at line 730 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.panelEvalOutput [private]
Definition at line 731 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.panelVisualWrapper [private]
Definition at line 732 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
Boolean moa.gui.clustertab.ClusteringVisualTab.running = false [private]
Definition at line 39 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.stopVisualizer(), and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
String moa.gui.clustertab.ClusteringVisualTab.screenshotFilebase [private]
Definition at line 42 of file ClusteringVisualTab.java.
javax.swing.JScrollPane moa.gui.clustertab.ClusteringVisualTab.scrollPane0 [private]
Definition at line 733 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JScrollPane moa.gui.clustertab.ClusteringVisualTab.scrollPane1 [private]
Definition at line 734 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JSlider moa.gui.clustertab.ClusteringVisualTab.speedSlider [private]
Definition at line 735 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JSplitPane moa.gui.clustertab.ClusteringVisualTab.splitVisual [private]
Definition at line 736 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.repaint().
moa.gui.visualization.StreamPanel moa.gui.clustertab.ClusteringVisualTab.streamPanel0 [private]
Definition at line 737 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.getLeftStreamPanel(), and moa.gui.clustertab.ClusteringVisualTab.initComponents().
moa.gui.visualization.StreamPanel moa.gui.clustertab.ClusteringVisualTab.streamPanel1 [private]
Definition at line 738 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.getRightStreamPanel(), and moa.gui.clustertab.ClusteringVisualTab.initComponents().
javax.swing.JPanel moa.gui.clustertab.ClusteringVisualTab.topWrapper [private]
Definition at line 739 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
RunVisualizer moa.gui.clustertab.ClusteringVisualTab.visualizer = null [private]
Definition at line 37 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.createVisualiterThread(), moa.gui.clustertab.ClusteringVisualTab.stopVisualizer(), and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
Thread moa.gui.clustertab.ClusteringVisualTab.visualizerThread = null [private]
Definition at line 38 of file ClusteringVisualTab.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.createVisualiterThread(), moa.gui.clustertab.ClusteringVisualTab.stopVisualizer(), and moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
The documentation for this class was generated from the following file:
main/java/moa/gui/clustertab/ClusteringVisualTab.java