MOA: moa.classifiers.core.splitcriteria.InfoGainSplitCriterion Class Reference
moa.classifiers.core.splitcriteria.InfoGainSplitCriterion Class Reference
Class for computing splitting criteria using information gain with respect to distributions of class values.
Public Member Functions
double getMeritOfSplit (double[] preSplitDist, double[][] postSplitDists)
Computes the merit of splitting for a given ditribution before the split and after it.
double getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Member Functions
static double computeEntropy (double[] dist)
static double computeEntropy (double[][] dists)
static int numSubsetsGreaterThanFrac (double[][] distributions, double minFrac)
Public Attributes
FloatOption minBranchFracOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for computing splitting criteria using information gain with respect to distributions of class values.
The split criterion is used as a parameter on decision trees and decision stumps.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 37 of file InfoGainSplitCriterion.java.
Member Function Documentation
static double moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.computeEntropy (double dists[][]) [static]
Definition at line 74 of file InfoGainSplitCriterion.java.
References moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.computeEntropy().
{
        double totalWeight = 0.0;
        double[] distWeights = new double[dists.length];
        for (int i = 0; i < dists.length; i++) {
            distWeights[i] = Utils.sum(dists[i]);
            totalWeight += distWeights[i];
        }
        double entropy = 0.0;
        for (int i = 0; i < dists.length; i++) {
            entropy += distWeights[i] * computeEntropy(dists[i]);
        }
        return entropy / totalWeight;
    }
static double moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.computeEntropy (double[] dist) [static]
Reimplemented in moa.classifiers.core.splitcriteria.InfoGainSplitCriterionMultilabel.
Definition at line 62 of file InfoGainSplitCriterion.java.
Referenced by moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.computeEntropy(), and moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getMeritOfSplit().
{
        double entropy = 0.0;
        double sum = 0.0;
        for (double d : dist) {
            if (d > 0.0) { // TODO: how small can d be before log2 overflows?
                entropy -= d * Utils.log2(d);
                sum += d;
            }
        }
        return sum > 0.0 ? (entropy + sum * Utils.log2(sum)) / sum : 0.0;
    }
void moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 109 of file InfoGainSplitCriterion.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getMeritOfSplit (double[] preSplitDist, double postSplitDists[][])
Computes the merit of splitting for a given ditribution before the split and after it.
Parameters:
preSplitDist the class distribution before the split
postSplitDist the class distribution after the split
Returns:
value of the merit of splitting
Implements moa.classifiers.core.splitcriteria.SplitCriterion.
Definition at line 48 of file InfoGainSplitCriterion.java.
References moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.computeEntropy(), moa.options.FloatOption.getValue(), moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.minBranchFracOption, and moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.numSubsetsGreaterThanFrac().
{
        if (numSubsetsGreaterThanFrac(postSplitDists, this.minBranchFracOption.getValue()) < 2) {
            return Double.NEGATIVE_INFINITY;
        }
        return computeEntropy(preSplitDist) - computeEntropy(postSplitDists);
    }
double moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
Parameters:
preSplitDist the class distribution before the split
Returns:
value of the range of splitting merit
Implements moa.classifiers.core.splitcriteria.SplitCriterion.
Definition at line 57 of file InfoGainSplitCriterion.java.
{
        int numClasses = preSplitDist.length > 2 ? preSplitDist.length : 2;
        return Utils.log2(numClasses);
    }
static int moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.numSubsetsGreaterThanFrac (double distributions[][], double minFrac) [static]
Definition at line 88 of file InfoGainSplitCriterion.java.
Referenced by moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getMeritOfSplit().
{
        double totalWeight = 0.0;
        double[] distSums = new double[distributions.length];
        for (int i = 0; i < distSums.length; i++) {
            for (int j = 0; j < distributions[i].length; j++) {
                distSums[i] += distributions[i][j];
            }
            totalWeight += distSums[i];
        }
        int numGreater = 0;
        for (double d : distSums) {
            double frac = d / totalWeight;
            if (frac > minFrac) {
                numGreater++;
            }
        }
        return numGreater;
    }
void moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 114 of file InfoGainSplitCriterion.java.
{
        // TODO Auto-generated method stub
    }
Member Data Documentation
FloatOption moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.minBranchFracOption
Initial value:
 new FloatOption("minBranchFrac",
            'f',
            "Minimum fraction of weight required down at least two branches.",
            0.01, 0.0, 0.5)
Definition at line 42 of file InfoGainSplitCriterion.java.
Referenced by moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.getMeritOfSplit().
final long moa.classifiers.core.splitcriteria.InfoGainSplitCriterion.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.core.splitcriteria.InfoGainSplitCriterionMultilabel.
Definition at line 40 of file InfoGainSplitCriterion.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/splitcriteria/InfoGainSplitCriterion.java