MOA: moa.gui.outliertab.OutlierSetupTab Class Reference
moa.gui.outliertab.OutlierSetupTab Class Reference
Public Member Functions
OutlierSetupTab ()
Creates new form outlierSetupTab.
MyBaseOutlierDetector getOutlierer0 ()
MyBaseOutlierDetector getOutlierer1 ()
ClusteringStream getStream0 ()
MeasureCollection[] getMeasures ()
TextViewerPanel getLogPanel ()
void addButtonActionListener (ActionListener l)
void toggleRunMode ()
void stopRun ()
Package Functions
void setOutlierTab (OutlierTabPanel outlierTab)
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void buttonImportSettingsActionPerformed (java.awt.event.ActionEvent evt)
void buttonExportSettingsActionPerformed (java.awt.event.ActionEvent evt)
void buttonStartActionPerformed (java.awt.event.ActionEvent evt)
void buttonStopActionPerformed (java.awt.event.ActionEvent evt)
void loadOptionsFromFile (String filepath)
void toggle (boolean internal)
void stop (boolean internal)
void setStateConfigButtons (boolean state)
Private Attributes
OutlierTabPanel outlierTab
String lastfile
javax.swing.JButton buttonExport
javax.swing.JButton buttonExportSettings
javax.swing.JButton buttonImportSettings
javax.swing.JButton buttonStart
javax.swing.JButton buttonStop
javax.swing.JButton buttonWeka
moa.gui.outliertab.OutlierAlgoPanel outlierAlgoPanel0
moa.gui.outliertab.OutlierEvalPanel outlierEvalPanel1
moa.gui.TextViewerPanel logPanel
Detailed Description
Definition at line 34 of file OutlierSetupTab.java.
Constructor & Destructor Documentation
moa.gui.outliertab.OutlierSetupTab.OutlierSetupTab ()
Creates new form outlierSetupTab.
Definition at line 39 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0, and moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel().
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents().
{
        initComponents();
        outlierAlgoPanel0.renderAlgoPanel();
    }
Member Function Documentation
void moa.gui.outliertab.OutlierSetupTab.addButtonActionListener (ActionListener l)
Definition at line 64 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.buttonExport, and moa.gui.outliertab.OutlierSetupTab.buttonWeka.
Referenced by moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel().
{
        buttonWeka.addActionListener(l);
        buttonWeka.setActionCommand("weka export");
        buttonExport.addActionListener(l);
        buttonExport.setActionCommand("csv export");
    }
void moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 222 of file OutlierSetupTab.java.
References moa.gui.TextViewerPanel.addText(), moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getStreamValueAsCLIString(), moa.gui.outliertab.OutlierSetupTab.logPanel, and moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
                                                                                     {//GEN-FIRST:event_buttonExportSettingsActionPerformed
        StringBuffer sb = new StringBuffer();
        sb.append(outlierAlgoPanel0.getStreamValueAsCLIString()+"\n");
        sb.append(outlierAlgoPanel0.getAlgorithm0ValueAsCLIString()+"\n");
        System.out.println(sb);
        logPanel.addText(sb.toString());
    }//GEN-LAST:event_buttonExportSettingsActionPerformed
void moa.gui.outliertab.OutlierSetupTab.buttonImportSettingsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 209 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.lastfile, and moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile().
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
                                                                                     {//GEN-FIRST:event_buttonImportSettingsActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        fileChooser.addChoosableFileFilter(new FileExtensionFilter("txt"));
        if(lastfile!=null)
            fileChooser.setSelectedFile(new File(lastfile));
        if (fileChooser.showOpenDialog(this.buttonImportSettings) == JFileChooser.APPROVE_OPTION) {
            lastfile = fileChooser.getSelectedFile().getPath();
            loadOptionsFromFile(fileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_buttonImportSettingsActionPerformed
void moa.gui.outliertab.OutlierSetupTab.buttonStartActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 232 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.toggle().
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
                                                                            {//GEN-FIRST:event_buttonStartActionPerformed
        toggle(true);
    }//GEN-LAST:event_buttonStartActionPerformed
void moa.gui.outliertab.OutlierSetupTab.buttonStopActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 236 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.stop().
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
                                                                           {//GEN-FIRST:event_buttonStopActionPerformed
        stop(true);
    }//GEN-LAST:event_buttonStopActionPerformed
TextViewerPanel moa.gui.outliertab.OutlierSetupTab.getLogPanel ()
Definition at line 60 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.logPanel.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return logPanel;
    }
MeasureCollection [] moa.gui.outliertab.OutlierSetupTab.getMeasures ()
Definition at line 56 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierEvalPanel.getSelectedMeasures(), and moa.gui.outliertab.OutlierSetupTab.outlierEvalPanel1.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return outlierEvalPanel1.getSelectedMeasures();
    }
MyBaseOutlierDetector moa.gui.outliertab.OutlierSetupTab.getOutlierer0 ()
Definition at line 44 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierAlgoPanel.getClusterer0(), and moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return outlierAlgoPanel0.getClusterer0();
    }
MyBaseOutlierDetector moa.gui.outliertab.OutlierSetupTab.getOutlierer1 ()
Definition at line 48 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierAlgoPanel.getClusterer1(), and moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return outlierAlgoPanel0.getClusterer1();
    }
ClusteringStream moa.gui.outliertab.OutlierSetupTab.getStream0 ()
Definition at line 52 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierAlgoPanel.getStream(), and moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return outlierAlgoPanel0.getStream();
    }
void moa.gui.outliertab.OutlierSetupTab.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 77 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.buttonExport, moa.gui.outliertab.OutlierSetupTab.buttonExportSettings, moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed(), moa.gui.outliertab.OutlierSetupTab.buttonImportSettings, moa.gui.outliertab.OutlierSetupTab.buttonImportSettingsActionPerformed(), moa.gui.outliertab.OutlierSetupTab.buttonStart, moa.gui.outliertab.OutlierSetupTab.buttonStartActionPerformed(), moa.gui.outliertab.OutlierSetupTab.buttonStop, moa.gui.outliertab.OutlierSetupTab.buttonStopActionPerformed(), moa.gui.outliertab.OutlierSetupTab.buttonWeka, moa.gui.outliertab.OutlierSetupTab.logPanel, moa.gui.outliertab.OutlierAlgoPanel.OutlierAlgoPanel(), moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0, moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel(), moa.gui.outliertab.OutlierSetupTab.outlierEvalPanel1, moa.gui.outliertab.OutlierAlgoPanel.setPanelTitle(), and moa.gui.TextViewerPanel.TextViewerPanel().
Referenced by moa.gui.outliertab.OutlierSetupTab.OutlierSetupTab().
{
        java.awt.GridBagConstraints gridBagConstraints;
        outlierAlgoPanel0 = new moa.gui.outliertab.OutlierAlgoPanel();
        outlierEvalPanel1 = new moa.gui.outliertab.OutlierEvalPanel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonExport = new javax.swing.JButton();
        buttonWeka = new javax.swing.JButton();
        buttonImportSettings = new javax.swing.JButton();
        buttonExportSettings = new javax.swing.JButton();
        logPanel = new moa.gui.TextViewerPanel();
        setLayout(new java.awt.GridBagLayout());
        outlierAlgoPanel0.setMinimumSize(new java.awt.Dimension(335, 150));
        outlierAlgoPanel0.setPanelTitle("Outlier Detection Algorithm Setup");
        outlierAlgoPanel0.setPreferredSize(new java.awt.Dimension(500, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(outlierAlgoPanel0, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        // ### add(outlierEvalPanel1, gridBagConstraints);
        int iBtnHeight = 27;
        buttonStart.setText("Start");
        buttonStart.setMinimumSize(new java.awt.Dimension(80, iBtnHeight));
        buttonStart.setPreferredSize(new java.awt.Dimension(80, iBtnHeight));
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonStart, gridBagConstraints);
        buttonStop.setText("Stop");
        buttonStop.setMinimumSize(new java.awt.Dimension(80, iBtnHeight));
        buttonStop.setPreferredSize(new java.awt.Dimension(80, iBtnHeight));
        buttonStop.setEnabled(false);
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonStop, gridBagConstraints);
        buttonExport.setText("Export CSV");
        buttonExport.setMinimumSize(new java.awt.Dimension(120, iBtnHeight));
        buttonExport.setPreferredSize(new java.awt.Dimension(120, iBtnHeight));
        buttonExport.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonExport, gridBagConstraints);
        buttonWeka.setText("Weka Explorer");
        buttonWeka.setMinimumSize(new java.awt.Dimension(120, iBtnHeight));
        buttonWeka.setPreferredSize(new java.awt.Dimension(120, iBtnHeight));
        buttonWeka.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonWeka, gridBagConstraints);
        buttonImportSettings.setText("Import");
        buttonImportSettings.setMinimumSize(new java.awt.Dimension(80, iBtnHeight));
        buttonImportSettings.setPreferredSize(new java.awt.Dimension(80, iBtnHeight));
        buttonImportSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportSettingsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 75, 4, 4);
        add(buttonImportSettings, gridBagConstraints);
        buttonExportSettings.setText("Export");
        buttonExportSettings.setMinimumSize(new java.awt.Dimension(80, iBtnHeight));
        buttonExportSettings.setPreferredSize(new java.awt.Dimension(80, iBtnHeight));
        buttonExportSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportSettingsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonExportSettings, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(logPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile (String filepath) [private]
Definition at line 241 of file OutlierSetupTab.java.
References moa.gui.TextViewerPanel.addText(), moa.gui.outliertab.OutlierSetupTab.logPanel, moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0, moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString(), and moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString().
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonImportSettingsActionPerformed().
{
        try {
            BufferedReader in = new BufferedReader(new FileReader(filepath));
            String stream0 = in.readLine();
            outlierAlgoPanel0.setStreamValueAsCLIString(stream0);
            String algo0 = in.readLine();
            outlierAlgoPanel0.setAlgorithm0ValueAsCLIString(algo0);
            System.out.println("Loading settings from "+filepath);
            logPanel.addText("Loading settings from "+filepath);
        } catch (Exception e) {
            System.out.println("Bad option file:"+e.getMessage());
        }
    }
void moa.gui.outliertab.OutlierSetupTab.setOutlierTab (OutlierTabPanel outlierTab) [package]
Definition at line 271 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel().
{
        this.outlierTab = outlierTab;
    }
void moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons (boolean state) [private]
Definition at line 315 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.buttonExportSettings, moa.gui.outliertab.OutlierSetupTab.buttonImportSettings, and moa.gui.outliertab.OutlierSetupTab.buttonStop.
Referenced by moa.gui.outliertab.OutlierSetupTab.stop(), and moa.gui.outliertab.OutlierSetupTab.toggle().
{
        buttonStop.setEnabled(!state);
        buttonExportSettings.setEnabled(state);
        buttonImportSettings.setEnabled(state);
    }
void moa.gui.outliertab.OutlierSetupTab.stop (boolean internal) [private]
Definition at line 302 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.buttonExport, moa.gui.outliertab.OutlierSetupTab.buttonStart, moa.gui.outliertab.OutlierSetupTab.buttonStop, moa.gui.outliertab.OutlierSetupTab.buttonWeka, moa.gui.outliertab.OutlierSetupTab.outlierTab, moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons(), and moa.gui.outliertab.OutlierTabPanel.stop().
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonStopActionPerformed(), and moa.gui.outliertab.OutlierSetupTab.stopRun().
{
        buttonStart.setEnabled(true);
        buttonStart.setText("Start");
        buttonStop.setEnabled(false);
        buttonWeka.setEnabled(false);
        buttonExport.setEnabled(false);
        setStateConfigButtons(true);
        //push event forward to the cluster tab
        if(internal)
            outlierTab.stop();
    }
void moa.gui.outliertab.OutlierSetupTab.stopRun ()
Definition at line 279 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.stop().
{
        stop(false);
    }
void moa.gui.outliertab.OutlierSetupTab.toggle (boolean internal) [private]
Definition at line 283 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.buttonExport, moa.gui.outliertab.OutlierSetupTab.buttonStart, moa.gui.outliertab.OutlierSetupTab.buttonWeka, moa.gui.outliertab.OutlierSetupTab.outlierTab, moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons(), and moa.gui.outliertab.OutlierTabPanel.toggle().
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonStartActionPerformed(), and moa.gui.outliertab.OutlierSetupTab.toggleRunMode().
{
        setStateConfigButtons(false);
        if(buttonStart.getText().equals("Pause")){
            buttonStart.setText("Resume");
            buttonWeka.setEnabled(true);
            buttonExport.setEnabled(true);
        }
        else{
            buttonStart.setText("Pause");
            buttonWeka.setEnabled(false);
            buttonExport.setEnabled(false);
        }
        //push event forward to the cluster tab
        if(internal)
            outlierTab.toggle();
    }
void moa.gui.outliertab.OutlierSetupTab.toggleRunMode ()
Definition at line 275 of file OutlierSetupTab.java.
References moa.gui.outliertab.OutlierSetupTab.toggle().
Referenced by moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
{
        toggle(false);
    }
Member Data Documentation
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonExport [private]
Definition at line 260 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.addButtonActionListener(), moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.stop(), and moa.gui.outliertab.OutlierSetupTab.toggle().
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonExportSettings [private]
Definition at line 261 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents(), and moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons().
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonImportSettings [private]
Definition at line 262 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents(), and moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons().
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonStart [private]
Definition at line 263 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.stop(), and moa.gui.outliertab.OutlierSetupTab.toggle().
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonStop [private]
Definition at line 264 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.setStateConfigButtons(), and moa.gui.outliertab.OutlierSetupTab.stop().
javax.swing.JButton moa.gui.outliertab.OutlierSetupTab.buttonWeka [private]
Definition at line 265 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.addButtonActionListener(), moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.stop(), and moa.gui.outliertab.OutlierSetupTab.toggle().
String moa.gui.outliertab.OutlierSetupTab.lastfile [private]
Definition at line 36 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonImportSettingsActionPerformed().
moa.gui.TextViewerPanel moa.gui.outliertab.OutlierSetupTab.logPanel [private]
Definition at line 268 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed(), moa.gui.outliertab.OutlierSetupTab.getLogPanel(), moa.gui.outliertab.OutlierSetupTab.initComponents(), and moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile().
moa.gui.outliertab.OutlierAlgoPanel moa.gui.outliertab.OutlierSetupTab.outlierAlgoPanel0 [private]
Definition at line 266 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.buttonExportSettingsActionPerformed(), moa.gui.outliertab.OutlierSetupTab.getOutlierer0(), moa.gui.outliertab.OutlierSetupTab.getOutlierer1(), moa.gui.outliertab.OutlierSetupTab.getStream0(), moa.gui.outliertab.OutlierSetupTab.initComponents(), moa.gui.outliertab.OutlierSetupTab.loadOptionsFromFile(), and moa.gui.outliertab.OutlierSetupTab.OutlierSetupTab().
moa.gui.outliertab.OutlierEvalPanel moa.gui.outliertab.OutlierSetupTab.outlierEvalPanel1 [private]
Definition at line 267 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.getMeasures(), and moa.gui.outliertab.OutlierSetupTab.initComponents().
OutlierTabPanel moa.gui.outliertab.OutlierSetupTab.outlierTab [private]
Definition at line 35 of file OutlierSetupTab.java.
Referenced by moa.gui.outliertab.OutlierSetupTab.stop(), and moa.gui.outliertab.OutlierSetupTab.toggle().
The documentation for this class was generated from the following file:
main/java/moa/gui/outliertab/OutlierSetupTab.java