MOA: moa.tasks.EvaluateInterleavedChunks Class Reference
moa.tasks.EvaluateInterleavedChunks Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Defines the task's result type.
Public Attributes
ClassOption learnerOption
Allows to select the trained classifier.
ClassOption streamOption
Allows to select the stream the classifier will learn.
ClassOption evaluatorOption
Allows to select the classifier performance evaluation method.
IntOption instanceLimitOption
Allows to define the maximum number of instances to test/train on (-1 = no limit).
IntOption chunkSizeOption
Allow to define the training/testing chunk size.
IntOption timeLimitOption
Allows to define the maximum number of seconds to test/train for (-1 = no limit).
IntOption sampleFrequencyOption
Defines how often classifier parameters will be calculated.
IntOption maxMemoryOption
Allows to define the memory limit for the created model.
IntOption memCheckFrequencyOption
Allows to define the frequency of memory checks.
FileOption dumpFileOption
Allows to define the output file name and location.
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 39 of file EvaluateInterleavedChunks.java.
Member Function Documentation
Object moa.tasks.EvaluateInterleavedChunks.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 127 of file EvaluateInterleavedChunks.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.tasks.EvaluateInterleavedChunks.chunkSizeOption, moa.AbstractMOAObject.copy(), moa.tasks.EvaluateInterleavedChunks.dumpFileOption, moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluateInterleavedChunks.evaluatorOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.EvaluateInterleavedChunks.instanceLimitOption, moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.EvaluateInterleavedChunks.learnerOption, moa.MOAObject.measureByteSize(), moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluateInterleavedChunks.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.EvaluateInterleavedChunks.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluateInterleavedChunks.timeLimitOption, and moa.classifiers.Classifier.trainOnInstance().
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        learner.setModelContext(stream.getHeader());
        int maxInstances = this.instanceLimitOption.getValue();
        int chunkSize = this.chunkSizeOption.getValue();
        long instancesProcessed = 0;
        int maxSeconds = this.timeLimitOption.getValue();
        int secondsElapsed = 0;
        monitor.setCurrentActivity("Evaluating learner...", -1.0);
        LearningCurve learningCurve = new LearningCurve(
                "learning evaluation instances");
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        boolean firstDump = true;
        boolean firstChunk = true;
        boolean preciseCPUTiming = TimingUtils.enablePreciseTiming();
        long evaluateStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        long sampleTestTime =0, sampleTrainTime = 0;
        double RAMHours = 0.0;
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))
                && ((maxSeconds < 0) || (secondsElapsed < maxSeconds))) {
            Instances chunkInstances = new Instances(stream.getHeader(), chunkSize);
            while (stream.hasMoreInstances() && chunkInstances.numInstances() < chunkSize) {
                chunkInstances.add(stream.nextInstance());
                if (chunkInstances.numInstances()
                        % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                    if (maxInstances > 0) {
                        long maxRemaining = maxInstances - instancesProcessed;
                        if ((estimatedRemainingInstances < 0) || (maxRemaining < estimatedRemainingInstances)) {
                            estimatedRemainingInstances = maxRemaining;
                        }
                    }
                    monitor.setCurrentActivityFractionComplete((double) instancesProcessed/ (double) (instancesProcessed + estimatedRemainingInstances));
                }
            }
            long testStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
            if(!firstChunk)
            {
                for (int i=0; i< chunkInstances.numInstances(); i++) {
                    Instance testInst = (Instance) chunkInstances.instance(i).copy();
                    //testInst.setClassMissing();
                    double[] prediction = learner.getVotesForInstance(testInst);
                    evaluator.addResult(testInst, prediction);
                }
            }
            else
            {
                firstChunk = false;
            }
            sampleTestTime += TimingUtils.getNanoCPUTimeOfCurrentThread() - testStartTime;
            long trainStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
            for (int i=0; i< chunkInstances.numInstances(); i++) {
                learner.trainOnInstance(chunkInstances.instance(i));
                instancesProcessed++;
            }
            sampleTrainTime += TimingUtils.getNanoCPUTimeOfCurrentThread() - trainStartTime;
            if (instancesProcessed % this.sampleFrequencyOption.getValue() == 0) {
                double RAMHoursIncrement = learner.measureByteSize() / (1024.0 * 1024.0 * 1024.0); //GBs
                RAMHoursIncrement *= (TimingUtils.nanoTimeToSeconds(sampleTrainTime + sampleTestTime) / 3600.0); //Hours
                RAMHours += RAMHoursIncrement;
                double avgTrainTime = TimingUtils.nanoTimeToSeconds(sampleTrainTime)/((double)this.sampleFrequencyOption.getValue()/chunkInstances.numInstances());
                double avgTestTime = TimingUtils.nanoTimeToSeconds(sampleTestTime)/((double)this.sampleFrequencyOption.getValue()/chunkInstances.numInstances());
                sampleTestTime = 0;
                sampleTrainTime = 0;
                learningCurve.insertEntry(new LearningEvaluation(
                    new Measurement[] {
                        new Measurement("learning evaluation instances", instancesProcessed),
                        new Measurement(("evaluation time ("+ (preciseCPUTiming ? "cpu " : "") + "seconds)"),TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread() - evaluateStartTime)),
                        new Measurement("average chunk train time", avgTrainTime),
                        new Measurement("average chunk train speed", chunkInstances.numInstances() / avgTrainTime),
                        new Measurement("average chunk test time", avgTestTime),
                        new Measurement("average chunk test speed", chunkInstances.numInstances()/ avgTestTime),
                        new Measurement( "model cost (RAM-Hours)", RAMHours)},
                    evaluator,
                    learner));
                if (immediateResultStream != null) {
                    if (firstDump) {
                        immediateResultStream.println(learningCurve
                                .headerToString());
                        firstDump = false;
                    }
                    immediateResultStream.println(learningCurve
                            .entryToString(learningCurve.numEntries() - 1));
                    immediateResultStream.flush();
                }
            }
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream
                        .estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor
                        .setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                                : (double) instancesProcessed
                                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.copy());
                }
                secondsElapsed = (int) TimingUtils
                        .nanoTimeToSeconds(TimingUtils
                                .getNanoCPUTimeOfCurrentThread()
                                - evaluateStartTime);
            }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
        return learningCurve;
    }
String moa.tasks.EvaluateInterleavedChunks.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file EvaluateInterleavedChunks.java.
{
        return "Evaluates a classifier on a stream by testing then training with chunks of data in sequence.";
    }
Class<?> moa.tasks.EvaluateInterleavedChunks.getTaskResultType ()
Defines the task's result type.
Implements moa.tasks.Task.
Definition at line 122 of file EvaluateInterleavedChunks.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
IntOption moa.tasks.EvaluateInterleavedChunks.chunkSizeOption
Initial value:
 new IntOption("chunkSize", 'c',
            "Number of instances in a data chunk.",
            1000, 1, Integer.MAX_VALUE)
Allow to define the training/testing chunk size.
Definition at line 79 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
FileOption moa.tasks.EvaluateInterleavedChunks.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv reslts to.", null, "csv", true)
Allows to define the output file name and location.
Definition at line 116 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
ClassOption moa.tasks.EvaluateInterleavedChunks.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "BasicClassificationPerformanceEvaluator")
Allows to select the classifier performance evaluation method.
Definition at line 64 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
IntOption moa.tasks.EvaluateInterleavedChunks.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            100000000, -1, Integer.MAX_VALUE)
Allows to define the maximum number of instances to test/train on (-1 = no limit).
Definition at line 72 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
ClassOption moa.tasks.EvaluateInterleavedChunks.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Allows to select the trained classifier.
Definition at line 51 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
IntOption moa.tasks.EvaluateInterleavedChunks.maxMemoryOption
Initial value:
 new IntOption("maxMemory", 'b',
            "Maximum size of model (in bytes). -1 = no limit.", -1, -1,
            Integer.MAX_VALUE)
Allows to define the memory limit for the created model.
Definition at line 101 of file EvaluateInterleavedChunks.java.
IntOption moa.tasks.EvaluateInterleavedChunks.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Allows to define the frequency of memory checks.
Definition at line 108 of file EvaluateInterleavedChunks.java.
IntOption moa.tasks.EvaluateInterleavedChunks.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            100000, 0, Integer.MAX_VALUE)
Defines how often classifier parameters will be calculated.
Definition at line 93 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
final long moa.tasks.EvaluateInterleavedChunks.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 46 of file EvaluateInterleavedChunks.java.
ClassOption moa.tasks.EvaluateInterleavedChunks.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Allows to select the stream the classifier will learn.
Definition at line 57 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
IntOption moa.tasks.EvaluateInterleavedChunks.timeLimitOption
Initial value:
 new IntOption("timeLimit", 't',
            "Maximum number of seconds to test/train for (-1 = no limit).", -1,
            -1, Integer.MAX_VALUE)
Allows to define the maximum number of seconds to test/train for (-1 = no limit).
Definition at line 86 of file EvaluateInterleavedChunks.java.
Referenced by moa.tasks.EvaluateInterleavedChunks.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateInterleavedChunks.java