MOA: moa.classifiers.meta.TemporallyAugmentedClassifier Class Reference
moa.classifiers.meta.TemporallyAugmentedClassifier Class Reference
Include labels of previous instances into the training data.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance instance)
Trains this classifier incrementally using the given instance.
void addOldLabel (double newPrediction)
void initHeader (Instances dataset)
Instance extendWithOldLabels (Instance instance)
double[] getVotesForInstance (Instance instance)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
String toString ()
Returns a description of the object.
Public Attributes
ClassOption baseLearnerOption
IntOption numOldLabelsOption
FlagOption labelDelayOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier baseLearner
double[] oldLabels
Instances header
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Include labels of previous instances into the training data.
This enables a classifier to exploit potentially present auto-correlation
Parameters:
-l : Classiﬁer to train
-n : The number of old labels to include
Author:
Bernhard Pfahringer (bernhard@cs.waikato.ac.nz)
Version:
Revision
1
Definition at line 50 of file TemporallyAugmentedClassifier.java.
Member Function Documentation
void moa.classifiers.meta.TemporallyAugmentedClassifier.addOldLabel (double newPrediction)
Definition at line 90 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.oldLabels.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance(), and moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl().
{
        int numLabels = this.oldLabels.length;
        if (numLabels > 0) {
            for (int i = 1; i < numLabels; i++) {
                this.oldLabels[i - 1] = this.oldLabels[i];
            }
            this.oldLabels[ numLabels - 1] = newPrediction;
        }
    }
Instance moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels (Instance instance)
Definition at line 121 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.header, moa.classifiers.meta.TemporallyAugmentedClassifier.initHeader(), and moa.classifiers.meta.TemporallyAugmentedClassifier.oldLabels.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance(), and moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl().
{
        if (this.header == null) {
            initHeader(instance.dataset());
        }
        int numLabels = this.oldLabels.length;
        if (numLabels == 0) {
            return instance;
        }
        double[] x = instance.toDoubleArray();
        double[] x2 = Arrays.copyOfRange(this.oldLabels, 0, numLabels + x.length);
        System.arraycopy(x, 0, x2, numLabels, x.length);
        Instance extendedInstance = new DenseInstance(instance.weight(), x2);
        extendedInstance.setDataset(this.header);
        //System.out.println( extendedInstance);
        return extendedInstance;
    }
void moa.classifiers.meta.TemporallyAugmentedClassifier.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 166 of file TemporallyAugmentedClassifier.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.TemporallyAugmentedClassifier.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 154 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner.
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        Measurement[] modelMeasurements = ((AbstractClassifier) this.baseLearner).getModelMeasurements();
        if (modelMeasurements != null) {
            for (Measurement measurement : modelMeasurements) {
                measurementList.add(measurement);
            }
        }
        return measurementList.toArray(new Measurement[measurementList.size()]);
    }
String moa.classifiers.meta.TemporallyAugmentedClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 53 of file TemporallyAugmentedClassifier.java.
{
        return "Add some old labels to every instance";
    }
double [] moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 139 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.addOldLabel(), moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner, moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels(), moa.classifiers.Classifier.getVotesForInstance(), moa.options.FlagOption.isSet, and moa.classifiers.meta.TemporallyAugmentedClassifier.labelDelayOption.
{
        double[] prediction = this.baseLearner.getVotesForInstance(extendWithOldLabels(instance));
        if (this.labelDelayOption.isSet() == true) {
            // Use predicted Labels to add attributes to instances
            addOldLabel(Utils.maxIndex(prediction));
        }
        return prediction;
    }
void moa.classifiers.meta.TemporallyAugmentedClassifier.initHeader (Instances dataset)
Definition at line 100 of file TemporallyAugmentedClassifier.java.
References moa.options.IntOption.getValue(), moa.classifiers.meta.TemporallyAugmentedClassifier.header, and moa.classifiers.meta.TemporallyAugmentedClassifier.numOldLabelsOption.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels().
{
        int numLabels = this.numOldLabelsOption.getValue();
        Attribute target = dataset.classAttribute();
        List<String> possibleValues = new ArrayList<String>();
        int n = target.numValues();
        for (int i = 0; i < n; i++) {
            possibleValues.add(target.value(i));
        }
        ArrayList<Attribute> attrs = new ArrayList<Attribute>(numLabels + dataset.numAttributes());
        for (int i = 0; i < numLabels; i++) {
            attrs.add(new Attribute(target.name() + "_" + i, possibleValues));
        }
        for (int i = 0; i < dataset.numAttributes(); i++) {
            attrs.add((Attribute) dataset.attribute(i).copy());
        }
        this.header = new Instances("extended_" + dataset.relationName(), attrs, 0);
        this.header.setClassIndex(numLabels + dataset.classIndex());
    }
boolean moa.classifiers.meta.TemporallyAugmentedClassifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 149 of file TemporallyAugmentedClassifier.java.
{
        return false; // ??? this.baseLearner.isRandomizable;
    }
void moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 74 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner, moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearnerOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.meta.TemporallyAugmentedClassifier.header, moa.classifiers.meta.TemporallyAugmentedClassifier.numOldLabelsOption, moa.classifiers.meta.TemporallyAugmentedClassifier.oldLabels, and moa.classifiers.Classifier.resetLearning().
{
        this.baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        this.oldLabels = new double[this.numOldLabelsOption.getValue()];
        this.header = null;
        baseLearner.resetLearning();
    }
String moa.classifiers.meta.TemporallyAugmentedClassifier.toString ()
Returns a description of the object.
Returns:
a description of the object
Reimplemented from moa.AbstractMOAObject.
Definition at line 170 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner, moa.options.IntOption.getValue(), and moa.classifiers.meta.TemporallyAugmentedClassifier.numOldLabelsOption.
{
        return "TemporallyAugmentedClassifier using " + this.numOldLabelsOption.getValue() + " labels\n" + this.baseLearner;
    }
void moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 82 of file TemporallyAugmentedClassifier.java.
References moa.classifiers.meta.TemporallyAugmentedClassifier.addOldLabel(), moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner, moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels(), moa.options.FlagOption.isSet, moa.classifiers.meta.TemporallyAugmentedClassifier.labelDelayOption, and moa.classifiers.Classifier.trainOnInstance().
{
        this.baseLearner.trainOnInstance(extendWithOldLabels(instance));
        if (this.labelDelayOption.isSet() == false) {
            // Use true old Labels to add attributes to instances
            addOldLabel(instance.classValue());
        }
    }
Member Data Documentation
Classifier moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearner [protected]
Definition at line 64 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.getModelMeasurementsImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance(), moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.toString(), and moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.TemporallyAugmentedClassifier.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 58 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl().
Instances moa.classifiers.meta.TemporallyAugmentedClassifier.header [protected]
Definition at line 68 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels(), moa.classifiers.meta.TemporallyAugmentedClassifier.initHeader(), and moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl().
FlagOption moa.classifiers.meta.TemporallyAugmentedClassifier.labelDelayOption
Initial value:
 new FlagOption("labelDelay", 'd',
        "Labels arrive with Delay. Use predictions instead of true Labels.")
Definition at line 70 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance(), and moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl().
IntOption moa.classifiers.meta.TemporallyAugmentedClassifier.numOldLabelsOption
Initial value:
 new IntOption("numOldLabels", 'n',
            "The number of old labels to add to each example.", 1, 0, Integer.MAX_VALUE)
Definition at line 61 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.initHeader(), moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl(), and moa.classifiers.meta.TemporallyAugmentedClassifier.toString().
double [] moa.classifiers.meta.TemporallyAugmentedClassifier.oldLabels [protected]
Definition at line 66 of file TemporallyAugmentedClassifier.java.
Referenced by moa.classifiers.meta.TemporallyAugmentedClassifier.addOldLabel(), moa.classifiers.meta.TemporallyAugmentedClassifier.extendWithOldLabels(), and moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl().
final long moa.classifiers.meta.TemporallyAugmentedClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 56 of file TemporallyAugmentedClassifier.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/TemporallyAugmentedClassifier.java