MOA: moa.gui.visualization.ClusterPanel Class Reference
moa.gui.visualization.ClusterPanel Class Reference
Public Member Functions
ClusterPanel (SphereCluster cluster, Color color, StreamPanel sp)
Creates new form ObjectPanel.
void setDirection (double[] direction)
void updateLocation ()
void updateTooltip ()
boolean contains (int x, int y)
void highlight (boolean enabled)
boolean isValidCluster ()
int getClusterID ()
int getClusterLabel ()
String getSVGString (int width)
void drawOnCanvas (Graphics2D imageGraphics)
Protected Member Functions
void paintComponent (Graphics g)
Protected Attributes
double decay_rate
int x_dim = 0
int y_dim = 1
Color col
Color default_color = Color.BLACK
double[] direction = null
StreamPanel streamPanel
int panel_size
int window_size
boolean highligted = false
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void formMouseClicked (java.awt.event.MouseEvent evt)
Private Attributes
SphereCluster cluster
double[] center
double r
Static Private Attributes
static final int MIN_SIZE = 5
Detailed Description
Definition at line 30 of file ClusterPanel.java.
Constructor & Destructor Documentation
moa.gui.visualization.ClusterPanel.ClusterPanel (SphereCluster cluster, Color color, StreamPanel sp)
Creates new form ObjectPanel.
Definition at line 54 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.center, moa.gui.visualization.ClusterPanel.col, moa.gui.visualization.ClusterPanel.default_color, moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getRadius(), moa.gui.visualization.ClusterPanel.initComponents(), moa.gui.visualization.ClusterPanel.r, and moa.gui.visualization.ClusterPanel.streamPanel.
{
        this.cluster = cluster;
        center = cluster.getCenter();
        r = cluster.getRadius();
        streamPanel = sp;
        default_color = col = color;
        setVisible(true);
        setOpaque(false);
        setSize(new Dimension(1,1));
        setLocation(0,0);
        initComponents();
    }
Member Function Documentation
boolean moa.gui.visualization.ClusterPanel.contains (int x, int y)
Definition at line 100 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.panel_size.
{
        //only react on the hull of the cluster
        double dist = Math.sqrt(Math.pow(x-panel_size/2,2)+Math.pow(y-panel_size/2,2));
        if(panel_size/2 - 5 < dist && dist < panel_size/2 + 5)
            return true;
        else
            return false;
    }
void moa.gui.visualization.ClusterPanel.drawOnCanvas (Graphics2D imageGraphics)
Definition at line 201 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.center, moa.gui.visualization.ClusterPanel.panel_size, moa.gui.visualization.ClusterPanel.window_size, moa.gui.visualization.ClusterPanel.x_dim, and moa.gui.visualization.ClusterPanel.y_dim.
Referenced by moa.gui.visualization.StreamPanel.drawClusteringsOnCanvas().
{
        int x = (int)(center[x_dim]*window_size-(panel_size/2));
        int y = (int)(center[y_dim]*window_size-(panel_size/2));
        int radius = panel_size;
        imageGraphics.drawOval(x, y, radius, radius);
    }
void moa.gui.visualization.ClusterPanel.formMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 139 of file ClusterPanel.java.
References moa.gui.visualization.StreamPanel.setHighlightedClusterPanel(), and moa.gui.visualization.ClusterPanel.streamPanel.
Referenced by moa.gui.visualization.ClusterPanel.initComponents().
                                                                 {//GEN-FIRST:event_formMouseClicked
        streamPanel.setHighlightedClusterPanel(this);
    }//GEN-LAST:event_formMouseClicked
int moa.gui.visualization.ClusterPanel.getClusterID ()
Definition at line 178 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.cluster, and moa.cluster.Cluster.getId().
{
        return (int)cluster.getId();
    }
int moa.gui.visualization.ClusterPanel.getClusterLabel ()
Definition at line 182 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.cluster, and moa.cluster.Cluster.getGroundTruth().
Referenced by moa.gui.visualization.PointPanel.getColor().
{
        return (int)cluster.getGroundTruth();
    }
String moa.gui.visualization.ClusterPanel.getSVGString (int width)
Definition at line 187 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.center, moa.gui.visualization.ClusterPanel.panel_size, moa.gui.visualization.ClusterPanel.window_size, moa.gui.visualization.ClusterPanel.x_dim, and moa.gui.visualization.ClusterPanel.y_dim.
{
        StringBuffer out = new StringBuffer();
        int x = (int)(center[x_dim]*window_size);
        int y = (int)(center[y_dim]*window_size);
        int radius = panel_size/2;
        out.append("<circle ");
        out.append("cx='"+x+"' cy='"+y+"' r='"+radius+"'");
        out.append(" stroke='green' stroke-width='1' fill='white' fill-opacity='0' />");
        out.append("\n");
        return out.toString();
    }
void moa.gui.visualization.ClusterPanel.highlight (boolean enabled)
Definition at line 169 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.highligted.
Referenced by moa.gui.visualization.StreamPanel.formMouseClicked().
{
        highligted = enabled;
        repaint();
    }
void moa.gui.visualization.ClusterPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 119 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.formMouseClicked().
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel().
{
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
boolean moa.gui.visualization.ClusterPanel.isValidCluster ()
Definition at line 174 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.center.
{
        return (center!=null);
    }
void moa.gui.visualization.ClusterPanel.paintComponent (Graphics g) [protected]
Definition at line 144 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.cluster, moa.gui.visualization.ClusterPanel.default_color, moa.gui.visualization.ClusterPanel.direction, moa.cluster.Cluster.getId(), moa.gui.visualization.ClusterPanel.highligted, moa.gui.visualization.ClusterPanel.panel_size, moa.gui.visualization.ClusterPanel.updateLocation(), and moa.gui.visualization.ClusterPanel.updateTooltip().
{
        updateLocation();
        if(highligted){
            g.setColor(Color.BLUE);
        }
        else{
            g.setColor(default_color);
        }
        int c = (int)(panel_size/2);
        if(cluster.getId()>=0)
            g.drawString("C"+(int)cluster.getId(),c,c);
        g.drawOval(0, 0, panel_size, panel_size);
        if(direction!=null){
            double length = Math.sqrt(Math.pow(direction[0], 2) + Math.pow(direction[1], 2));
            g.drawLine(c, c, c+(int)((direction[0]/length)*panel_size), c+(int)((direction[1]/length)*panel_size));
        }
        updateTooltip();
    }
void moa.gui.visualization.ClusterPanel.setDirection (double[] direction)
Definition at line 70 of file ClusterPanel.java.
{
        this.direction = direction;
    }
void moa.gui.visualization.ClusterPanel.updateLocation ()
Definition at line 74 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.center, moa.gui.visualization.ClusterPanel.cluster, moa.gui.visualization.StreamPanel.getActiveXDim(), moa.gui.visualization.StreamPanel.getActiveYDim(), moa.gui.visualization.ClusterPanel.MIN_SIZE, moa.gui.visualization.ClusterPanel.panel_size, moa.gui.visualization.ClusterPanel.r, moa.gui.visualization.ClusterPanel.streamPanel, moa.gui.visualization.ClusterPanel.window_size, moa.gui.visualization.ClusterPanel.x_dim, and moa.gui.visualization.ClusterPanel.y_dim.
Referenced by moa.gui.visualization.StreamPanel.drawClustering(), and moa.gui.visualization.ClusterPanel.paintComponent().
{
        x_dim = streamPanel.getActiveXDim();
        y_dim = streamPanel.getActiveYDim();
        if(cluster!=null && center==null)
            getParent().remove(this);
        else{
            //size of the parent
            window_size = Math.min(streamPanel.getWidth(),streamPanel.getHeight());
            //scale down to diameter
            panel_size = (int) (2* r * window_size);
            if(panel_size < MIN_SIZE)
                    panel_size = MIN_SIZE;
            setSize(new Dimension(panel_size+1,panel_size+1));
            setLocation((int)(center[x_dim]*window_size-(panel_size/2)),(int)(center[y_dim]*window_size-(panel_size/2)));
        }
    }
void moa.gui.visualization.ClusterPanel.updateTooltip ()
Definition at line 95 of file ClusterPanel.java.
References moa.gui.visualization.ClusterPanel.cluster, and moa.cluster.Cluster.getInfo().
Referenced by moa.gui.visualization.ClusterPanel.paintComponent().
{
        setToolTipText(cluster.getInfo());
    }
Member Data Documentation
double [] moa.gui.visualization.ClusterPanel.center [private]
Definition at line 33 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel(), moa.gui.visualization.ClusterPanel.drawOnCanvas(), moa.gui.visualization.ClusterPanel.getSVGString(), moa.gui.visualization.ClusterPanel.isValidCluster(), and moa.gui.visualization.ClusterPanel.updateLocation().
SphereCluster moa.gui.visualization.ClusterPanel.cluster [private]
Definition at line 31 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.getClusterID(), moa.gui.visualization.ClusterPanel.getClusterLabel(), moa.gui.visualization.ClusterPanel.paintComponent(), moa.gui.visualization.ClusterPanel.updateLocation(), and moa.gui.visualization.ClusterPanel.updateTooltip().
Color moa.gui.visualization.ClusterPanel.col [protected]
Definition at line 39 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel().
double moa.gui.visualization.ClusterPanel.decay_rate [protected]
Definition at line 35 of file ClusterPanel.java.
Color moa.gui.visualization.ClusterPanel.default_color = Color.BLACK [protected]
Definition at line 40 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel(), and moa.gui.visualization.ClusterPanel.paintComponent().
double [] moa.gui.visualization.ClusterPanel.direction = null [protected]
Definition at line 41 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.paintComponent().
boolean moa.gui.visualization.ClusterPanel.highligted = false [protected]
Definition at line 47 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.highlight(), and moa.gui.visualization.ClusterPanel.paintComponent().
final int moa.gui.visualization.ClusterPanel.MIN_SIZE = 5 [static, private]
Definition at line 34 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.updateLocation().
int moa.gui.visualization.ClusterPanel.panel_size [protected]
Definition at line 45 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.contains(), moa.gui.visualization.ClusterPanel.drawOnCanvas(), moa.gui.visualization.ClusterPanel.getSVGString(), moa.gui.visualization.ClusterPanel.paintComponent(), and moa.gui.visualization.ClusterPanel.updateLocation().
double moa.gui.visualization.ClusterPanel.r [private]
Definition at line 48 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel(), and moa.gui.visualization.ClusterPanel.updateLocation().
StreamPanel moa.gui.visualization.ClusterPanel.streamPanel [protected]
Definition at line 43 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.ClusterPanel(), moa.gui.visualization.ClusterPanel.formMouseClicked(), and moa.gui.visualization.ClusterPanel.updateLocation().
int moa.gui.visualization.ClusterPanel.window_size [protected]
Definition at line 46 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.drawOnCanvas(), moa.gui.visualization.ClusterPanel.getSVGString(), and moa.gui.visualization.ClusterPanel.updateLocation().
int moa.gui.visualization.ClusterPanel.x_dim = 0 [protected]
Definition at line 37 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.drawOnCanvas(), moa.gui.visualization.ClusterPanel.getSVGString(), and moa.gui.visualization.ClusterPanel.updateLocation().
int moa.gui.visualization.ClusterPanel.y_dim = 1 [protected]
Definition at line 38 of file ClusterPanel.java.
Referenced by moa.gui.visualization.ClusterPanel.drawOnCanvas(), moa.gui.visualization.ClusterPanel.getSVGString(), and moa.gui.visualization.ClusterPanel.updateLocation().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/ClusterPanel.java