MOA: moa.classifiers.drift.SingleClassifierDriftTest Class Reference
moa.classifiers.drift.SingleClassifierDriftTest Class Reference
Tests the SingleClassifierDrift classifier.
Public Member Functions
SingleClassifierDriftTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the SingleClassifierDrift classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 35 of file SingleClassifierDriftTest.java.
Constructor & Destructor Documentation
moa.classifiers.drift.SingleClassifierDriftTest.SingleClassifierDriftTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 43 of file SingleClassifierDriftTest.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.drift.SingleClassifierDriftTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleClassifierTestCase.
Definition at line 54 of file SingleClassifierDriftTest.java.
{
    return new Classifier[]{
    new SingleClassifierDrift(),
    };
  }
static void moa.classifiers.drift.SingleClassifierDriftTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 74 of file SingleClassifierDriftTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.drift.SingleClassifierDriftTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.drift.SingleClassifierDriftTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 65 of file SingleClassifierDriftTest.java.
Referenced by moa.classifiers.drift.SingleClassifierDriftTest.main().
{
    return new TestSuite(SingleClassifierDriftTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/drift/SingleClassifierDriftTest.java