MOA: moa.classifiers.trees.HoeffdingTree Class Reference
moa.classifiers.trees.HoeffdingTree Class Reference
Hoeffding Tree or VFDT.
Classes
class ActiveLearningNode
class FoundNode
class InactiveLearningNode
class LearningNode
class LearningNodeNB
class LearningNodeNBAdaptive
class Node
class SplitNode
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
int calcByteSize ()
int measureByteSize ()
Gets the memory size of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
int measureTreeDepth ()
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void enforceTrackerLimit ()
void estimateModelByteSizes ()
void deactivateAllLeaves ()
Static Public Member Functions
static double computeHoeffdingBound (double range, double confidence, double n)
Public Attributes
IntOption maxByteSizeOption
ClassOption numericEstimatorOption
ClassOption nominalEstimatorOption
IntOption memoryEstimatePeriodOption
IntOption gracePeriodOption
ClassOption splitCriterionOption
FloatOption splitConfidenceOption
FloatOption tieThresholdOption
FlagOption binarySplitsOption
FlagOption stopMemManagementOption
FlagOption removePoorAttsOption
FlagOption noPrePruneOption
MultiChoiceOption leafpredictionOption
IntOption nbThresholdOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
SplitNode newSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
SplitNode newSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
void attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex)
void deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch)
void activateLearningNode (InactiveLearningNode toActivate, SplitNode parent, int parentBranch)
FoundNode[] findLearningNodes ()
void findLearningNodes (Node node, SplitNode parent, int parentBranch, List< FoundNode > found)
LearningNode newLearningNode ()
LearningNode newLearningNode (double[] initialClassObservations)
Protected Attributes
Node treeRoot
int decisionNodeCount
int activeLeafNodeCount
int inactiveLeafNodeCount
double inactiveLeafByteSizeEstimate
double activeLeafByteSizeEstimate
double byteSizeEstimateOverheadFraction
boolean growthAllowed
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Hoeffding Tree or VFDT.
A Hoeffding tree is an incremental, anytime decision tree induction algorithm that is capable of learning from massive data streams, assuming that the distribution generating examples does not change over time. Hoeffding trees exploit the fact that a small sample can often be enough to choose an optimal splitting attribute. This idea is supported mathematically by the Hoeffding bound, which quantiﬁes the number of observations (in our case, examples) needed to estimate some statistics within a prescribed precision (in our case, the goodness of an attribute).
A theoretically appealing feature of Hoeffding Trees not shared by other incremental decision tree learners is that it has sound guarantees of performance. Using the Hoeffding bound one can show that its output is asymptotically nearly identical to that of a non-incremental learner using inﬁnitely many examples. See for details:
G. Hulten, L. Spencer, and P. Domingos. Mining time-changing data streams. In KDD’01, pages 97–106, San Francisco, CA, 2001. ACM Press.
Parameters:
-m : Maximum memory consumed by the tree
-n : Numeric estimator to use :
Gaussian approximation evaluating 10 splitpoints
Gaussian approximation evaluating 100 splitpoints
Greenwald-Khanna quantile summary with 10 tuples
Greenwald-Khanna quantile summary with 100 tuples
Greenwald-Khanna quantile summary with 1000 tuples
VFML method with 10 bins
VFML method with 100 bins
VFML method with 1000 bins
Exhaustive binary tree
-e : How many instances between memory consumption checks
-g : The number of instances a leaf should observe between split attempts
-s : Split criterion to use. Example : InfoGainSplitCriterion
-c : The allowable error in split decision, values closer to 0 will take longer to decide
-t : Threshold below which a split will be forced to break ties
-b : Only allow binary splits
-z : Stop growing as soon as memory limit is hit
-r : Disable poor attributes
-p : Disable pre-pruning
-l : Leaf prediction to use: MajorityClass (MC), Naive Bayes (NB) or NaiveBayes adaptive (NBAdaptive).
-q : The number of instances a leaf should observe before permitting Naive Bayes
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 96 of file HoeffdingTree.java.
Member Function Documentation
void moa.classifiers.trees.HoeffdingTree.activateLearningNode (InactiveLearningNode toActivate, SplitNode parent, int parentBranch) [protected]
Definition at line 800 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), and moa.classifiers.trees.HoeffdingTree.SplitNode.setChild().
{
        Node newLeaf = newLearningNode(toActivate.getObservedClassDistribution());
        if (parent == null) {
            this.treeRoot = newLeaf;
        } else {
            parent.setChild(parentBranch, newLeaf);
        }
        this.activeLeafNodeCount++;
        this.inactiveLeafNodeCount--;
    }
void moa.classifiers.trees.HoeffdingTree.attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex) [protected]
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.
Definition at line 622 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.disableAttribute(), moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), moa.classifiers.core.splitcriteria.SplitCriterion.getRangeOfMerit(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.trees.HoeffdingTree.Node.observedClassDistributionIsPure(), moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), and moa.classifiers.core.AttributeSplitSuggestion.splitTest.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
        if (!node.observedClassDistributionIsPure()) {
            SplitCriterion splitCriterion = (SplitCriterion) getPreparedClassOption(this.splitCriterionOption);
            AttributeSplitSuggestion[] bestSplitSuggestions = node.getBestSplitSuggestions(splitCriterion, this);
            Arrays.sort(bestSplitSuggestions);
            boolean shouldSplit = false;
            if (bestSplitSuggestions.length < 2) {
                shouldSplit = bestSplitSuggestions.length > 0;
            } else {
                double hoeffdingBound = computeHoeffdingBound(splitCriterion.getRangeOfMerit(node.getObservedClassDistribution()),
                        this.splitConfidenceOption.getValue(), node.getWeightSeen());
                AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                AttributeSplitSuggestion secondBestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 2];
                if ((bestSuggestion.merit - secondBestSuggestion.merit > hoeffdingBound)
                        || (hoeffdingBound < this.tieThresholdOption.getValue())) {
                    shouldSplit = true;
                }
                // }
                if ((this.removePoorAttsOption != null)
                        && this.removePoorAttsOption.isSet()) {
                    Set<Integer> poorAtts = new HashSet<Integer>();
                    // scan 1 - add any poor to set
                    for (int i = 0; i < bestSplitSuggestions.length; i++) {
                        if (bestSplitSuggestions[i].splitTest != null) {
                            int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                            if (splitAtts.length == 1) {
                                if (bestSuggestion.merit
                                        - bestSplitSuggestions[i].merit > hoeffdingBound) {
                                    poorAtts.add(new Integer(splitAtts[0]));
                                }
                            }
                        }
                    }
                    // scan 2 - remove good ones from set
                    for (int i = 0; i < bestSplitSuggestions.length; i++) {
                        if (bestSplitSuggestions[i].splitTest != null) {
                            int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                            if (splitAtts.length == 1) {
                                if (bestSuggestion.merit
                                        - bestSplitSuggestions[i].merit < hoeffdingBound) {
                                    poorAtts.remove(new Integer(splitAtts[0]));
                                }
                            }
                        }
                    }
                    for (int poorAtt : poorAtts) {
                        node.disableAttribute(poorAtt);
                    }
                }
            }
            if (shouldSplit) {
                AttributeSplitSuggestion splitDecision = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                if (splitDecision.splitTest == null) {
                    // preprune - null wins
                    deactivateLearningNode(node, parent, parentIndex);
                } else {
                    SplitNode newSplit = newSplitNode(splitDecision.splitTest,
                            node.getObservedClassDistribution(),splitDecision.numSplits() );
                    for (int i = 0; i < splitDecision.numSplits(); i++) {
                        Node newChild = newLearningNode(splitDecision.resultingClassDistributionFromSplit(i));
                        newSplit.setChild(i, newChild);
                    }
                    this.activeLeafNodeCount--;
                    this.decisionNodeCount++;
                    this.activeLeafNodeCount += splitDecision.numSplits();
                    if (parent == null) {
                        this.treeRoot = newSplit;
                    } else {
                        parent.setChild(parentIndex, newSplit);
                    }
                }
                // manage memory
                enforceTrackerLimit();
            }
        }
    }
int moa.classifiers.trees.HoeffdingTree.calcByteSize ()
Definition at line 483 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.calcByteSizeIncludingSubtree().
{
        int size = (int) SizeOf.sizeOf(this);
        if (this.treeRoot != null) {
            size += this.treeRoot.calcByteSizeIncludingSubtree();
        }
        return size;
    }
static double moa.classifiers.trees.HoeffdingTree.computeHoeffdingBound (double range, double confidence, double n) [static]
Definition at line 594 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
                      {
        return Math.sqrt(((range * range) * Math.log(1.0 / confidence))
                / (2.0 * n));
    }
void moa.classifiers.trees.HoeffdingTree.deactivateAllLeaves ()
Definition at line 777 of file HoeffdingTree.java.
{
        FoundNode[] learningNodes = findLearningNodes();
        for (int i = 0; i < learningNodes.length; i++) {
            if (learningNodes[i].node instanceof ActiveLearningNode) {
                deactivateLearningNode(
                        (ActiveLearningNode) learningNodes[i].node,
                        learningNodes[i].parent, learningNodes[i].parentBranch);
            }
        }
    }
void moa.classifiers.trees.HoeffdingTree.deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch) [protected]
Reimplemented in moa.classifiers.multilabel.MultilabelHoeffdingTree.
Definition at line 788 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), and moa.classifiers.trees.HoeffdingTree.SplitNode.setChild().
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
        Node newLeaf = new InactiveLearningNode(toDeactivate.getObservedClassDistribution());
        if (parent == null) {
            this.treeRoot = newLeaf;
        } else {
            parent.setChild(parentBranch, newLeaf);
        }
        this.activeLeafNodeCount--;
        this.inactiveLeafNodeCount++;
    }
void moa.classifiers.trees.HoeffdingTree.enforceTrackerLimit ()
Definition at line 700 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.calculatePromise(), and moa.classifiers.trees.HoeffdingTree.FoundNode.node.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
        if ((this.inactiveLeafNodeCount > 0)
                || ((this.activeLeafNodeCount * this.activeLeafByteSizeEstimate + this.inactiveLeafNodeCount
                * this.inactiveLeafByteSizeEstimate)
                * this.byteSizeEstimateOverheadFraction > this.maxByteSizeOption.getValue())) {
            if (this.stopMemManagementOption.isSet()) {
                this.growthAllowed = false;
                return;
            }
            FoundNode[] learningNodes = findLearningNodes();
            Arrays.sort(learningNodes, new Comparator<FoundNode>() {
                @Override
                public int compare(FoundNode fn1, FoundNode fn2) {
                    return Double.compare(fn1.node.calculatePromise(), fn2.node.calculatePromise());
                }
            });
            int maxActive = 0;
            while (maxActive < learningNodes.length) {
                maxActive++;
                if ((maxActive * this.activeLeafByteSizeEstimate + (learningNodes.length - maxActive)
                        * this.inactiveLeafByteSizeEstimate)
                        * this.byteSizeEstimateOverheadFraction > this.maxByteSizeOption.getValue()) {
                    maxActive--;
                    break;
                }
            }
            int cutoff = learningNodes.length - maxActive;
            for (int i = 0; i < cutoff; i++) {
                if (learningNodes[i].node instanceof ActiveLearningNode) {
                    deactivateLearningNode(
                            (ActiveLearningNode) learningNodes[i].node,
                            learningNodes[i].parent,
                            learningNodes[i].parentBranch);
                }
            }
            for (int i = cutoff; i < learningNodes.length; i++) {
                if (learningNodes[i].node instanceof InactiveLearningNode) {
                    activateLearningNode(
                            (InactiveLearningNode) learningNodes[i].node,
                            learningNodes[i].parent,
                            learningNodes[i].parentBranch);
                }
            }
        }
    }
void moa.classifiers.trees.HoeffdingTree.estimateModelByteSizes ()
Definition at line 747 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
        FoundNode[] learningNodes = findLearningNodes();
        long totalActiveSize = 0;
        long totalInactiveSize = 0;
        for (FoundNode foundNode : learningNodes) {
            if (foundNode.node instanceof ActiveLearningNode) {
                totalActiveSize += SizeOf.fullSizeOf(foundNode.node);
            } else {
                totalInactiveSize += SizeOf.fullSizeOf(foundNode.node);
            }
        }
        if (totalActiveSize > 0) {
            this.activeLeafByteSizeEstimate = (double) totalActiveSize
                    / this.activeLeafNodeCount;
        }
        if (totalInactiveSize > 0) {
            this.inactiveLeafByteSizeEstimate = (double) totalInactiveSize
                    / this.inactiveLeafNodeCount;
        }
        int actualModelSize = this.measureByteSize();
        double estimatedModelSize = (this.activeLeafNodeCount
                * this.activeLeafByteSizeEstimate + this.inactiveLeafNodeCount
                * this.inactiveLeafByteSizeEstimate);
        this.byteSizeEstimateOverheadFraction = actualModelSize
                / estimatedModelSize;
        if (actualModelSize > this.maxByteSizeOption.getValue()) {
            enforceTrackerLimit();
        }
    }
void moa.classifiers.trees.HoeffdingTree.findLearningNodes (Node node, SplitNode parent, int parentBranch, List< FoundNode > found) [protected]
Definition at line 818 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.SplitNode.getChild(), and moa.classifiers.trees.HoeffdingTree.SplitNode.numChildren().
{
        if (node != null) {
            if (node instanceof LearningNode) {
                found.add(new FoundNode(node, parent, parentBranch));
            }
            if (node instanceof SplitNode) {
                SplitNode splitNode = (SplitNode) node;
                for (int i = 0; i < splitNode.numChildren(); i++) {
                    findLearningNodes(splitNode.getChild(i), splitNode, i,
                            found);
                }
            }
        }
    }
FoundNode [] moa.classifiers.trees.HoeffdingTree.findLearningNodes () [protected]
Definition at line 812 of file HoeffdingTree.java.
{
        List<FoundNode> foundList = new LinkedList<FoundNode>();
        findLearningNodes(this.treeRoot, null, -1, foundList);
        return foundList.toArray(new FoundNode[foundList.size()]);
    }
void moa.classifiers.trees.HoeffdingTree.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 585 of file HoeffdingTree.java.
{
        this.treeRoot.describeSubtree(this, out, indent);
    }
Measurement [] moa.classifiers.trees.HoeffdingTree.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 560 of file HoeffdingTree.java.
{
        return new Measurement[]{
                    new Measurement("tree size (nodes)", this.decisionNodeCount
                    + this.activeLeafNodeCount + this.inactiveLeafNodeCount),
                    new Measurement("tree size (leaves)", this.activeLeafNodeCount
                    + this.inactiveLeafNodeCount),
                    new Measurement("active learning leaves",
                    this.activeLeafNodeCount),
                    new Measurement("tree depth", measureTreeDepth()),
                    new Measurement("active leaf byte size estimate",
                    this.activeLeafByteSizeEstimate),
                    new Measurement("inactive leaf byte size estimate",
                    this.inactiveLeafByteSizeEstimate),
                    new Measurement("byte size estimate overhead",
                    this.byteSizeEstimateOverheadFraction)};
    }
String moa.classifiers.trees.HoeffdingTree.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.LimAttHoeffdingTree, and moa.classifiers.trees.RandomHoeffdingTree.
Definition at line 101 of file HoeffdingTree.java.
{
        return "Hoeffding Tree or VFDT.";
    }
double [] moa.classifiers.trees.HoeffdingTree.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.multilabel.MultilabelHoeffdingTree, and moa.classifiers.trees.HoeffdingAdaptiveTree.
Definition at line 546 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.getClassVotes(), moa.classifiers.trees.HoeffdingTree.FoundNode.node, and moa.classifiers.trees.HoeffdingTree.FoundNode.parent.
{
        if (this.treeRoot != null) {
            FoundNode foundNode = this.treeRoot.filterInstanceToLeaf(inst,
                    null, -1);
            Node leafNode = foundNode.node;
            if (leafNode == null) {
                leafNode = foundNode.parent;
            }
            return leafNode.getClassVotes(inst, this);
        }
        return new double[0];
    }
boolean moa.classifiers.trees.HoeffdingTree.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.trees.LimAttHoeffdingTree, and moa.classifiers.trees.RandomHoeffdingTree.
Definition at line 590 of file HoeffdingTree.java.
{
        return false;
    }
int moa.classifiers.trees.HoeffdingTree.measureByteSize ()
Gets the memory size of this object.
Returns:
the memory size of this object
Reimplemented from moa.AbstractMOAObject.
Definition at line 492 of file HoeffdingTree.java.
{
        return calcByteSize();
    }
int moa.classifiers.trees.HoeffdingTree.measureTreeDepth ()
Definition at line 577 of file HoeffdingTree.java.
{
        if (this.treeRoot != null) {
            return this.treeRoot.subtreeDepth();
        }
        return 0;
    }
LearningNode moa.classifiers.trees.HoeffdingTree.newLearningNode (double[] initialClassObservations) [protected]
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves, moa.classifiers.multilabel.MultilabelHoeffdingTree, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.LimAttHoeffdingTree, and moa.classifiers.trees.RandomHoeffdingTree.
Definition at line 910 of file HoeffdingTree.java.
{
        LearningNode ret;
        int predictionOption = this.leafpredictionOption.getChosenIndex();
        if (predictionOption == 0) { //MC
            ret = new ActiveLearningNode(initialClassObservations);
        } else if (predictionOption == 1) { //NB
            ret = new LearningNodeNB(initialClassObservations);
        } else { //NBAdaptive
            ret = new LearningNodeNBAdaptive(initialClassObservations);
        }
        return ret;
    }
LearningNode moa.classifiers.trees.HoeffdingTree.newLearningNode () [protected]
Reimplemented in moa.classifiers.trees.FIMTDD.
Definition at line 906 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.trees.HoeffdingAdaptiveTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
        return newLearningNode(new double[0]);
    }
AttributeClassObserver moa.classifiers.trees.HoeffdingTree.newNominalClassObserver () [protected]
Definition at line 612 of file HoeffdingTree.java.
References moa.options.OptionHandler.copy().
Referenced by moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), and moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance().
{
        AttributeClassObserver nominalClassObserver = (AttributeClassObserver) getPreparedClassOption(this.nominalEstimatorOption);
        return (AttributeClassObserver) nominalClassObserver.copy();
    }
AttributeClassObserver moa.classifiers.trees.HoeffdingTree.newNumericClassObserver () [protected]
Definition at line 617 of file HoeffdingTree.java.
References moa.options.OptionHandler.copy().
Referenced by moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), and moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance().
{
        AttributeClassObserver numericClassObserver = (AttributeClassObserver) getPreparedClassOption(this.numericEstimatorOption);
        return (AttributeClassObserver) numericClassObserver.copy();
    }
SplitNode moa.classifiers.trees.HoeffdingTree.newSplitNode (InstanceConditionalTest splitTest, double[] classObservations) [protected]
Reimplemented in moa.classifiers.trees.FIMTDD, and moa.classifiers.trees.HoeffdingAdaptiveTree.
Definition at line 606 of file HoeffdingTree.java.
{
        return new SplitNode(splitTest, classObservations);
    }
SplitNode moa.classifiers.trees.HoeffdingTree.newSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size) [protected]
Reimplemented in moa.classifiers.trees.HoeffdingAdaptiveTree.
Definition at line 601 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
        return new SplitNode(splitTest, classObservations, size);
    }
void moa.classifiers.trees.HoeffdingTree.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.trees.ASHoeffdingTree.
Definition at line 497 of file HoeffdingTree.java.
{
        this.treeRoot = null;
        this.decisionNodeCount = 0;
        this.activeLeafNodeCount = 0;
        this.inactiveLeafNodeCount = 0;
        this.inactiveLeafByteSizeEstimate = 0.0;
        this.activeLeafByteSizeEstimate = 0.0;
        this.byteSizeEstimateOverheadFraction = 1.0;
        this.growthAllowed = true;
        if (this.leafpredictionOption.getChosenIndex()>0) {
            this.removePoorAttsOption = null;
        }
    }
void moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.FIMTDD, and moa.classifiers.trees.HoeffdingAdaptiveTree.
Definition at line 512 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation(), moa.classifiers.trees.HoeffdingTree.LearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.FoundNode.node, moa.classifiers.trees.HoeffdingTree.FoundNode.parent, moa.classifiers.trees.HoeffdingTree.FoundNode.parentBranch, moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), and moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation().
{
        if (this.treeRoot == null) {
            this.treeRoot = newLearningNode();
            this.activeLeafNodeCount = 1;
        }
        FoundNode foundNode = this.treeRoot.filterInstanceToLeaf(inst, null, -1);
        Node leafNode = foundNode.node;
        if (leafNode == null) {
            leafNode = newLearningNode();
            foundNode.parent.setChild(foundNode.parentBranch, leafNode);
            this.activeLeafNodeCount++;
        }
        if (leafNode instanceof LearningNode) {
            LearningNode learningNode = (LearningNode) leafNode;
            learningNode.learnFromInstance(inst, this);
            if (this.growthAllowed
                    && (learningNode instanceof ActiveLearningNode)) {
                ActiveLearningNode activeLearningNode = (ActiveLearningNode) learningNode;
                double weightSeen = activeLearningNode.getWeightSeen();
                if (weightSeen
                        - activeLearningNode.getWeightSeenAtLastSplitEvaluation() >= this.gracePeriodOption.getValue()) {
                    attemptToSplit(activeLearningNode, foundNode.parent,
                            foundNode.parentBranch);
                    activeLearningNode.setWeightSeenAtLastSplitEvaluation(weightSeen);
                }
            }
        }
        if (this.trainingWeightSeenByModel
                % this.memoryEstimatePeriodOption.getValue() == 0) {
            estimateModelByteSizes();
        }
    }
Member Data Documentation
double moa.classifiers.trees.HoeffdingTree.activeLeafByteSizeEstimate [protected]
Definition at line 477 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl().
int moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount [protected]
Definition at line 471 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.multilabel.MultilabelHoeffdingTree.deactivateLearningNode(), moa.classifiers.trees.ASHoeffdingTree.deleteNode(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance(), moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl(), moa.classifiers.trees.HoeffdingAdaptiveTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
FlagOption moa.classifiers.trees.HoeffdingTree.binarySplitsOption
Initial value:
 new FlagOption("binarySplits", 'b',
        "Only allow binary splits.")
Definition at line 153 of file HoeffdingTree.java.
double moa.classifiers.trees.HoeffdingTree.byteSizeEstimateOverheadFraction [protected]
Definition at line 479 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl().
int moa.classifiers.trees.HoeffdingTree.decisionNodeCount [protected]
Definition at line 469 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.trees.ASHoeffdingTree.deleteNode(), moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
IntOption moa.classifiers.trees.HoeffdingTree.gracePeriodOption
Initial value:
 new IntOption(
            "gracePeriod",
            'g',
            "The number of instances a leaf should observe between split attempts.",
            200, 0, Integer.MAX_VALUE)
Definition at line 133 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
boolean moa.classifiers.trees.HoeffdingTree.growthAllowed [protected]
Definition at line 481 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
double moa.classifiers.trees.HoeffdingTree.inactiveLeafByteSizeEstimate [protected]
Definition at line 475 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl().
int moa.classifiers.trees.HoeffdingTree.inactiveLeafNodeCount [protected]
Definition at line 473 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.deactivateLearningNode(), moa.classifiers.trees.ASHoeffdingTree.deleteNode(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds(), and moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl().
MultiChoiceOption moa.classifiers.trees.HoeffdingTree.leafpredictionOption
Initial value:
 new MultiChoiceOption(
            "leafprediction", 'l', "Leaf prediction to use.", new String[]{
                "MC", "NB", "NBAdaptive"}, new String[]{
                "Majority class",
                "Naive Bayes",
                "Naive Bayes Adaptive"}, 2)
Definition at line 834 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.RandomHoeffdingTree.newLearningNode(), and moa.classifiers.trees.LimAttHoeffdingTree.newLearningNode().
IntOption moa.classifiers.trees.HoeffdingTree.maxByteSizeOption
Initial value:
 new IntOption("maxByteSize", 'm',
            "Maximum memory consumed by the tree.", 33554432, 0,
            Integer.MAX_VALUE)
Definition at line 105 of file HoeffdingTree.java.
IntOption moa.classifiers.trees.HoeffdingTree.memoryEstimatePeriodOption
Initial value:
 new IntOption(
            "memoryEstimatePeriod", 'e',
            "How many instances between memory consumption checks.", 1000000,
            0, Integer.MAX_VALUE)
Definition at line 128 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
IntOption moa.classifiers.trees.HoeffdingTree.nbThresholdOption
Initial value:
 new IntOption(
            "nbThreshold",
            'q',
            "The number of instances a leaf should observe before permitting Naive Bayes.",
            0, 0, Integer.MAX_VALUE)
Definition at line 841 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.RandomHoeffdingTree.LearningNodeNB.getClassVotes(), moa.classifiers.trees.LimAttHoeffdingTree.LearningNodeNB.getClassVotes(), moa.classifiers.trees.HoeffdingTree.LearningNodeNB.getClassVotes(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes().
ClassOption moa.classifiers.trees.HoeffdingTree.nominalEstimatorOption
Initial value:
 new ClassOption("nominalEstimator",
            'd', "Nominal estimator to use.", DiscreteAttributeClassObserver.class,
            "NominalAttributeClassObserver")
Definition at line 124 of file HoeffdingTree.java.
FlagOption moa.classifiers.trees.HoeffdingTree.noPrePruneOption
Initial value:
 new FlagOption("noPrePrune", 'p',
            "Disable pre-pruning.")
Definition at line 163 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), and moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions().
ClassOption moa.classifiers.trees.HoeffdingTree.numericEstimatorOption
Initial value:
 new ClassOption("numericEstimator",
            'n', "Numeric estimator to use.", NumericAttributeClassObserver.class,
            "GaussianNumericAttributeClassObserver")
Definition at line 120 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.FIMTDD.FIMTDD().
FlagOption moa.classifiers.trees.HoeffdingTree.removePoorAttsOption
Initial value:
 new FlagOption("removePoorAtts",
            'r', "Disable poor attributes.")
Definition at line 160 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.HoeffdingTreeClassifLeaves(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttHoeffdingTree(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelHoeffdingTree(), and moa.classifiers.trees.RandomHoeffdingTree.RandomHoeffdingTree().
final long moa.classifiers.trees.HoeffdingTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves, moa.classifiers.multilabel.MultilabelHoeffdingTree, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.LimAttHoeffdingTree, and moa.classifiers.trees.RandomHoeffdingTree.
Definition at line 98 of file HoeffdingTree.java.
FloatOption moa.classifiers.trees.HoeffdingTree.splitConfidenceOption
Initial value:
 new FloatOption(
            "splitConfidence",
            'c',
            "The allowable error in split decision, values closer to 0 will take longer to decide.",
            0.0000001, 0.0, 1.0)
Definition at line 143 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
ClassOption moa.classifiers.trees.HoeffdingTree.splitCriterionOption
Initial value:
 new ClassOption("splitCriterion",
            's', "Split criterion to use.", SplitCriterion.class,
            "InfoGainSplitCriterion")
Definition at line 139 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), and moa.classifiers.trees.FIMTDD.FIMTDD().
FlagOption moa.classifiers.trees.HoeffdingTree.stopMemManagementOption
Initial value:
 new FlagOption(
            "stopMemManagement", 'z',
            "Stop growing as soon as memory limit is hit.")
Definition at line 156 of file HoeffdingTree.java.
FloatOption moa.classifiers.trees.HoeffdingTree.tieThresholdOption
Initial value:
 new FloatOption("tieThreshold",
            't', "Threshold below which a split will be forced to break ties.",
            0.05, 0.0, 1.0)
Definition at line 149 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), and moa.classifiers.trees.HoeffdingTreeTest.getRegressionClassifierSetups().
Node moa.classifiers.trees.HoeffdingTree.treeRoot [protected]
Definition at line 467 of file HoeffdingTree.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.multilabel.MultilabelHoeffdingTree.deactivateLearningNode(), moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingAdaptiveTree.filterInstanceToLeaves(), moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance(), moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance(), moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl(), moa.classifiers.trees.HoeffdingAdaptiveTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingTree.java