MOA: moa.classifiers.core.splitcriteria.GiniSplitCriterion Class Reference
moa.classifiers.core.splitcriteria.GiniSplitCriterion Class Reference
Class for computing splitting criteria using Gini with respect to distributions of class values.
Public Member Functions
double getMeritOfSplit (double[] preSplitDist, double[][] postSplitDists)
Computes the merit of splitting for a given ditribution before the split and after it.
double getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Member Functions
static double computeGini (double[] dist, double distSumOfWeights)
static double computeGini (double[] dist)
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for computing splitting criteria using Gini with respect to distributions of class values.
The split criterion is used as a parameter on decision trees and decision stumps.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 36 of file GiniSplitCriterion.java.
Member Function Documentation
static double moa.classifiers.core.splitcriteria.GiniSplitCriterion.computeGini (double[] dist) [static]
Definition at line 72 of file GiniSplitCriterion.java.
References moa.classifiers.core.splitcriteria.GiniSplitCriterion.computeGini().
{
        return computeGini(dist, Utils.sum(dist));
    }
static double moa.classifiers.core.splitcriteria.GiniSplitCriterion.computeGini (double[] dist, double distSumOfWeights) [static]
Definition at line 63 of file GiniSplitCriterion.java.
Referenced by moa.classifiers.core.splitcriteria.GiniSplitCriterion.computeGini(), and moa.classifiers.core.splitcriteria.GiniSplitCriterion.getMeritOfSplit().
{
        double gini = 1.0;
        for (int i = 0; i < dist.length; i++) {
            double relFreq = dist[i] / distSumOfWeights;
            gini -= relFreq * relFreq;
        }
        return gini;
    }
void moa.classifiers.core.splitcriteria.GiniSplitCriterion.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 77 of file GiniSplitCriterion.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.splitcriteria.GiniSplitCriterion.getMeritOfSplit (double[] preSplitDist, double postSplitDists[][])
Computes the merit of splitting for a given ditribution before the split and after it.
Parameters:
preSplitDist the class distribution before the split
postSplitDist the class distribution after the split
Returns:
value of the merit of splitting
Implements moa.classifiers.core.splitcriteria.SplitCriterion.
Definition at line 42 of file GiniSplitCriterion.java.
References moa.classifiers.core.splitcriteria.GiniSplitCriterion.computeGini().
{
        double totalWeight = 0.0;
        double[] distWeights = new double[postSplitDists.length];
        for (int i = 0; i < postSplitDists.length; i++) {
            distWeights[i] = Utils.sum(postSplitDists[i]);
            totalWeight += distWeights[i];
        }
        double gini = 0.0;
        for (int i = 0; i < postSplitDists.length; i++) {
            gini += (distWeights[i] / totalWeight)
                    * computeGini(postSplitDists[i], distWeights[i]);
        }
        return 1.0 - gini;
    }
double moa.classifiers.core.splitcriteria.GiniSplitCriterion.getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
Parameters:
preSplitDist the class distribution before the split
Returns:
value of the range of splitting merit
Implements moa.classifiers.core.splitcriteria.SplitCriterion.
Definition at line 59 of file GiniSplitCriterion.java.
{
        return 1.0;
    }
void moa.classifiers.core.splitcriteria.GiniSplitCriterion.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 82 of file GiniSplitCriterion.java.
{
        // TODO Auto-generated method stub
    }
Member Data Documentation
final long moa.classifiers.core.splitcriteria.GiniSplitCriterion.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file GiniSplitCriterion.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/splitcriteria/GiniSplitCriterion.java