MOA: moa.evaluation.F1 Class Reference
moa.evaluation.F1 Class Reference
Public Member Functions
void evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points)
Protected Member Functions
String[] getNames ()
Detailed Description
Definition at line 26 of file F1.java.
Member Function Documentation
void moa.evaluation.F1.evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) [virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 40 of file F1.java.
References moa.evaluation.MeasureCollection.addValue(), moa.cluster.Clustering.get(), moa.evaluation.MembershipMatrix.getClassSum(), moa.evaluation.MembershipMatrix.getClusterClassWeight(), moa.evaluation.MembershipMatrix.getClusterSum(), moa.evaluation.MembershipMatrix.getNumClasses(), moa.evaluation.MembershipMatrix.hasNoiseClass(), moa.evaluation.MeasureCollection.mm, moa.cluster.Cluster.setMeasureValue(), and moa.cluster.Clustering.size().
{
        if (clustering.size()<0){
            addValue(0,0);
            addValue(1,0);
            return;
        }
        MembershipMatrix mm = new MembershipMatrix(clustering, points);
        //System.out.println(mm.toString());
        int numClasses = mm.getNumClasses();
        if(mm.hasNoiseClass())
            numClasses--;
        //F1 as defined in P3C, try using F1 optimization
        double F1_P = 0.0;
        double purity = 0;
        int realClusters = 0;
        for (int i = 0; i < clustering.size(); i++) {
            int max_weight = 0;
            int max_weight_index = -1;
            //find max index
            for (int j = 0; j < numClasses; j++) {
                if(mm.getClusterClassWeight(i, j) > max_weight){
                    max_weight = mm.getClusterClassWeight(i, j);
                    max_weight_index = j;
                }
            }
            if(max_weight_index!=-1){
                realClusters++;
                double precision = mm.getClusterClassWeight(i, max_weight_index)/(double)mm.getClusterSum(i);
                double recall = mm.getClusterClassWeight(i, max_weight_index)/(double) mm.getClassSum(max_weight_index);
                double f1 = 0;
                if(precision > 0 || recall > 0){
                    f1 = 2*precision*recall/(precision+recall);
                }
                F1_P += f1;
                purity += precision;
                //TODO should we move setMeasure stuff into the Cluster interface?
                clustering.get(i).setMeasureValue("F1-P", Double.toString(f1));
            }
        }
        if(realClusters > 0){
            F1_P/=realClusters;
            purity/=realClusters;
        }
        addValue("F1-P",F1_P);
        addValue("Purity",purity);
        //F1 as defined in .... mainly maximizes F1 for each class
        double F1_R = 0.0;
        for (int j = 0; j < numClasses; j++) {
            double max_f1 = 0;
            for (int i = 0; i < clustering.size(); i++) {
                double precision = mm.getClusterClassWeight(i, j)/(double)mm.getClusterSum(i);
                double recall = mm.getClusterClassWeight(i, j)/(double)mm.getClassSum(j);
                double f1 = 0;
                if(precision > 0 || recall > 0){
                    f1 = 2*precision*recall/(precision+recall);
                }
                if(max_f1 < f1){
                    max_f1 = f1;
                }
            }
            F1_R+= max_f1;
        }
        F1_R/=numClasses;
        addValue("F1-R",F1_R);
    }
String [] moa.evaluation.F1.getNames () [protected, virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 29 of file F1.java.
References moa.evaluation.MeasureCollection.names.
{
        String[] names = {"F1-P","F1-R","Purity"};
        return names;
    }
The documentation for this class was generated from the following file:
main/java/moa/evaluation/F1.java