MOA: moa.streams.generators.cd.AbstractConceptDriftGenerator Class Reference
moa.streams.generators.cd.AbstractConceptDriftGenerator Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
ArrayList< ClusterEvent > getEventsList ()
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
boolean getChange ()
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption instanceRandomSeedOption
FlagOption notBinaryStreamOption
IntOption numInstancesConceptOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
abstract double nextValue ()
Protected Attributes
ArrayList< ClusterEvent > clusterEvents
InstancesHeader streamHeader
Random instanceRandom
int period
int numInstances
boolean change
Private Member Functions
int nextbinaryValue (double num)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 38 of file AbstractConceptDriftGenerator.java.
Member Function Documentation
long moa.streams.generators.cd.AbstractConceptDriftGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 109 of file AbstractConceptDriftGenerator.java.
{
        return -1;
    }
boolean moa.streams.generators.cd.AbstractConceptDriftGenerator.getChange ()
Definition at line 135 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.change.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance().
{
        return this.change;
    }
void moa.streams.generators.cd.AbstractConceptDriftGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 163 of file AbstractConceptDriftGenerator.java.
{
        // TODO Auto-generated method stub
    }
ArrayList<ClusterEvent> moa.streams.generators.cd.AbstractConceptDriftGenerator.getEventsList ()
Implements moa.streams.generators.cd.ConceptDriftGenerator.
Definition at line 47 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.clusterEvents.
{
        return this.clusterEvents;
    }
InstancesHeader moa.streams.generators.cd.AbstractConceptDriftGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 113 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.streamHeader.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.cd.AbstractConceptDriftGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file AbstractConceptDriftGenerator.java.
{
        return "Generates a stream problem of predicting concept drift.";
    }
boolean moa.streams.generators.cd.AbstractConceptDriftGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 117 of file AbstractConceptDriftGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.cd.AbstractConceptDriftGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 121 of file AbstractConceptDriftGenerator.java.
{
        return true;
    }
int moa.streams.generators.cd.AbstractConceptDriftGenerator.nextbinaryValue (double num) [private]
Definition at line 127 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.instanceRandom.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance().
{
        int res = 0;
        if (this.instanceRandom.nextDouble() <= num) {
            res = 1;
        }
        return res;
    }
Instance moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 139 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.getChange(), moa.streams.generators.cd.AbstractConceptDriftGenerator.getHeader(), moa.options.FlagOption.isSet, moa.streams.generators.cd.AbstractConceptDriftGenerator.nextbinaryValue(), moa.streams.generators.cd.AbstractConceptDriftGenerator.nextValue(), moa.streams.generators.cd.AbstractConceptDriftGenerator.notBinaryStreamOption, and moa.streams.generators.cd.AbstractConceptDriftGenerator.numInstances.
{
        this.numInstances++;
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        inst.setDataset(header);
        double nextValue = this.nextValue();
        if (this.notBinaryStreamOption.isSet()) {
            inst.setValue(0,  nextValue);
        } else {
            inst.setValue(0, this.nextbinaryValue(nextValue));
        }
        //Ground truth
        inst.setValue(1, this.getChange() ? 1 : 0);
        if (this.getChange() == true) {
            //this.clusterEvents.add(new ClusterEvent(this, this.numInstances, "Change", "Drift"));
        }
        inst.setValue(2,  nextValue);
        return inst;
    }
abstract double moa.streams.generators.cd.AbstractConceptDriftGenerator.nextValue () [protected, pure virtual]
Implemented in moa.streams.generators.cd.AbruptChangeGenerator, moa.streams.generators.cd.GradualChangeGenerator, and moa.streams.generators.cd.NoChangeGenerator.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance().
void moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 73 of file AbstractConceptDriftGenerator.java.
References moa.streams.generators.cd.AbstractConceptDriftGenerator.clusterEvents, moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.IntOption.getValue(), moa.options.FlagOption.isSet, moa.streams.generators.cd.AbstractConceptDriftGenerator.notBinaryStreamOption, moa.streams.generators.cd.AbstractConceptDriftGenerator.numInstances, moa.streams.generators.cd.AbstractConceptDriftGenerator.numInstancesConceptOption, moa.streams.generators.cd.AbstractConceptDriftGenerator.period, moa.streams.generators.cd.AbstractConceptDriftGenerator.restart(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.streamHeader.
{
        restart();
        this.numInstances = 0;
        this.period = numInstancesConceptOption.getValue();
        // generate header
        FastVector attributes = new FastVector();
        FastVector binaryLabels = new FastVector();
        binaryLabels.addElement("0");
        binaryLabels.addElement("1");
        if (!this.notBinaryStreamOption.isSet()) {
            attributes.addElement(new Attribute("input", binaryLabels));
        } else {
            attributes.addElement(new Attribute("input"));
        }
        // Ground Truth
        attributes.addElement(new Attribute("change", binaryLabels));
        attributes.addElement(new Attribute("ground truth input"));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
        this.clusterEvents = new ArrayList<ClusterEvent>();
        //this.clusterEvents.add(new ClusterEvent(this,100,"Change", "Drift"));
        //this.clusterEvents.add(new ClusterEvent(this,200,"Change2", "Drift2"));
    }
void moa.streams.generators.cd.AbstractConceptDriftGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 159 of file AbstractConceptDriftGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.cd.AbstractConceptDriftGenerator.instanceRandom, and moa.streams.generators.cd.AbstractConceptDriftGenerator.instanceRandomSeedOption.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
    }
Member Data Documentation
boolean moa.streams.generators.cd.AbstractConceptDriftGenerator.change [protected]
Definition at line 70 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.getChange(), moa.streams.generators.cd.GradualChangeGenerator.nextValue(), and moa.streams.generators.cd.AbruptChangeGenerator.nextValue().
ArrayList<ClusterEvent> moa.streams.generators.cd.AbstractConceptDriftGenerator.clusterEvents [protected]
Definition at line 45 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.getEventsList(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
Random moa.streams.generators.cd.AbstractConceptDriftGenerator.instanceRandom [protected]
Definition at line 64 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextbinaryValue(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.restart().
IntOption moa.streams.generators.cd.AbstractConceptDriftGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 52 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.restart().
FlagOption moa.streams.generators.cd.AbstractConceptDriftGenerator.notBinaryStreamOption
Initial value:
 new FlagOption("notBinaryStream",
            'b', "Don't convert to a binary stream of 0 and 1.")
Definition at line 56 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
int moa.streams.generators.cd.AbstractConceptDriftGenerator.numInstances [protected]
Definition at line 68 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.nextInstance(), moa.streams.generators.cd.GradualChangeGenerator.nextValue(), moa.streams.generators.cd.AbruptChangeGenerator.nextValue(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
IntOption moa.streams.generators.cd.AbstractConceptDriftGenerator.numInstancesConceptOption
Initial value:
 new IntOption("numInstancesConcept", 'p',
            "The number of instances for each concept.", 500, 0, Integer.MAX_VALUE)
Definition at line 59 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
int moa.streams.generators.cd.AbstractConceptDriftGenerator.period [protected]
Definition at line 66 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.GradualChangeGenerator.nextValue(), moa.streams.generators.cd.AbruptChangeGenerator.nextValue(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
final long moa.streams.generators.cd.AbstractConceptDriftGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 50 of file AbstractConceptDriftGenerator.java.
InstancesHeader moa.streams.generators.cd.AbstractConceptDriftGenerator.streamHeader [protected]
Definition at line 62 of file AbstractConceptDriftGenerator.java.
Referenced by moa.streams.generators.cd.AbstractConceptDriftGenerator.getHeader(), and moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/cd/AbstractConceptDriftGenerator.java