MOA: moa.core.Measurement Class Reference
moa.core.Measurement Class Reference
Class for storing an evaluation measurement.
Public Member Functions
Measurement (String name, double value)
String getName ()
double getValue ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Member Functions
static Measurement getMeasurementNamed (String name, Measurement[] measurements)
static void getMeasurementsDescription (Measurement[] measurements, StringBuilder out, int indent)
static Measurement[] averageMeasurements (Measurement[][] toAverage)
Protected Attributes
String name
double value
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for storing an evaluation measurement.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file Measurement.java.
Constructor & Destructor Documentation
moa.core.Measurement.Measurement (String name, double value)
Definition at line 41 of file Measurement.java.
Referenced by moa.core.Measurement.averageMeasurements().
{
        this.name = name;
        this.value = value;
    }
Member Function Documentation
static Measurement [] moa.core.Measurement.averageMeasurements (Measurement toAverage[][]) [static]
Definition at line 75 of file Measurement.java.
References moa.core.GaussianEstimator.getMean(), moa.core.GaussianEstimator.getStdDev(), moa.core.GaussianEstimator.getTotalWeightObserved(), and moa.core.Measurement.Measurement().
{
        List<String> measurementNames = new ArrayList<String>();
        for (Measurement[] measurements : toAverage) {
            for (Measurement measurement : measurements) {
                if (measurementNames.indexOf(measurement.getName()) < 0) {
                    measurementNames.add(measurement.getName());
                }
            }
        }
        GaussianEstimator[] estimators = new GaussianEstimator[measurementNames.size()];
        for (int i = 0; i < estimators.length; i++) {
            estimators[i] = new GaussianEstimator();
        }
        for (Measurement[] measurements : toAverage) {
            for (Measurement measurement : measurements) {
                estimators[measurementNames.indexOf(measurement.getName())].addObservation(measurement.getValue(), 1.0);
            }
        }
        List<Measurement> averagedMeasurements = new ArrayList<Measurement>();
        for (int i = 0; i < measurementNames.size(); i++) {
            String mName = measurementNames.get(i);
            GaussianEstimator mEstimator = estimators[i];
            if (mEstimator.getTotalWeightObserved() > 1.0) {
                averagedMeasurements.add(new Measurement("[avg] " + mName,
                        mEstimator.getMean()));
                averagedMeasurements.add(new Measurement("[err] " + mName,
                        mEstimator.getStdDev()
                        / Math.sqrt(mEstimator.getTotalWeightObserved())));
            }
        }
        return averagedMeasurements.toArray(new Measurement[averagedMeasurements.size()]);
    }
void moa.core.Measurement.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 109 of file Measurement.java.
References moa.core.Measurement.getName(), and moa.core.Measurement.getValue().
{
        sb.append(getName());
        sb.append(" = ");
        if (getValue()>.001) {
                sb.append(StringUtils.doubleToString(getValue(),3));
        } else {
                sb.append(getValue());
        }
    }
static Measurement moa.core.Measurement.getMeasurementNamed (String name, Measurement[] measurements) [static]
Definition at line 54 of file Measurement.java.
Referenced by moa.evaluation.LearningCurve.insertEntry().
{
        for (Measurement measurement : measurements) {
            if (name.equals(measurement.getName())) {
                return measurement;
            }
        }
        return null;
    }
static void moa.core.Measurement.getMeasurementsDescription (Measurement[] measurements, StringBuilder out, int indent) [static]
Definition at line 64 of file Measurement.java.
References moa.AbstractMOAObject.toString().
{
        if (measurements.length > 0) {
            StringUtils.appendIndented(out, indent, measurements[0].toString());
            for (int i = 1; i < measurements.length; i++) {
                StringUtils.appendNewlineIndented(out, indent, measurements[i].toString());
            }
        }
    }
String moa.core.Measurement.getName ()
Definition at line 46 of file Measurement.java.
References moa.core.Measurement.name.
Referenced by moa.core.Measurement.getDescription().
{
        return this.name;
    }
double moa.core.Measurement.getValue ()
Definition at line 50 of file Measurement.java.
References moa.core.Measurement.value.
Referenced by moa.core.Measurement.getDescription(), and moa.evaluation.LearningCurve.insertEntry().
{
        return this.value;
    }
Member Data Documentation
String moa.core.Measurement.name [protected]
Definition at line 37 of file Measurement.java.
Referenced by moa.core.Measurement.getName().
final long moa.core.Measurement.serialVersionUID = 1L [static, private]
Definition at line 35 of file Measurement.java.
double moa.core.Measurement.value [protected]
Definition at line 39 of file Measurement.java.
Referenced by moa.core.Measurement.getValue().
The documentation for this class was generated from the following file:
main/java/moa/core/Measurement.java