MOA: moa.gui.outliertab.OutlierTabPanel Class Reference
moa.gui.outliertab.OutlierTabPanel Class Reference
Public Member Functions
OutlierTabPanel ()
Creates new form ClusterTab.
String getTabTitle ()
Returns the string to display as title of the tab.
String getDescription ()
Returns a short description (can be used as tool tip) of the tab, or contributor, etc.
Package Functions
void toggle ()
void stop ()
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void jTabbedPane1FocusGained (java.awt.event.FocusEvent evt)
void jTabbedPane1MouseClicked (java.awt.event.MouseEvent evt)
Private Attributes
moa.gui.outliertab.OutlierSetupTab outlierSetupTab
moa.gui.outliertab.OutlierVisualTab outlierVisualTab
javax.swing.JTabbedPane jTabbedPane1
Detailed Description
Definition at line 26 of file OutlierTabPanel.java.
Constructor & Destructor Documentation
moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel ()
Creates new form ClusterTab.
Definition at line 29 of file OutlierTabPanel.java.
References moa.gui.outliertab.OutlierSetupTab.addButtonActionListener(), moa.gui.outliertab.OutlierTabPanel.initComponents(), moa.gui.outliertab.OutlierTabPanel.outlierSetupTab, moa.gui.outliertab.OutlierTabPanel.outlierVisualTab, moa.gui.outliertab.OutlierVisualTab.setOutlierSetupTab(), and moa.gui.outliertab.OutlierSetupTab.setOutlierTab().
{
        initComponents();
        outlierVisualTab.setOutlierSetupTab(outlierSetupTab);
        outlierSetupTab.addButtonActionListener(outlierVisualTab);
        outlierSetupTab.setOutlierTab(this);
    }
Member Function Documentation
String moa.gui.outliertab.OutlierTabPanel.getDescription () [virtual]
Returns a short description (can be used as tool tip) of the tab, or contributor, etc.
Returns:
a short description of this tab panel.
Implements moa.gui.AbstractTabPanel.
Definition at line 98 of file OutlierTabPanel.java.
{
            return "MOA Outliers";
    }
String moa.gui.outliertab.OutlierTabPanel.getTabTitle () [virtual]
Returns the string to display as title of the tab.
Returns:
the string to display as title of the tab
Implements moa.gui.AbstractTabPanel.
Definition at line 93 of file OutlierTabPanel.java.
{
            return "Outliers";
    }
void moa.gui.outliertab.OutlierTabPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 52 of file OutlierTabPanel.java.
References moa.gui.outliertab.OutlierTabPanel.jTabbedPane1, moa.gui.outliertab.OutlierTabPanel.jTabbedPane1FocusGained(), moa.gui.outliertab.OutlierTabPanel.jTabbedPane1MouseClicked(), moa.gui.outliertab.OutlierSetupTab.OutlierSetupTab(), moa.gui.outliertab.OutlierTabPanel.outlierSetupTab, moa.gui.outliertab.OutlierVisualTab.OutlierVisualTab(), and moa.gui.outliertab.OutlierTabPanel.outlierVisualTab.
Referenced by moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel().
{
        jTabbedPane1 = new javax.swing.JTabbedPane();
        outlierSetupTab = new moa.gui.outliertab.OutlierSetupTab();
        outlierVisualTab = new moa.gui.outliertab.OutlierVisualTab();
        setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addTab("Setup", outlierSetupTab);
        jTabbedPane1.addTab("Visualization", outlierVisualTab);
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.outliertab.OutlierTabPanel.jTabbedPane1FocusGained (java.awt.event.FocusEvent evt) [private]
Definition at line 76 of file OutlierTabPanel.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents().
                                                                        {//GEN-FIRST:event_jTabbedPane1FocusGained
    }//GEN-LAST:event_jTabbedPane1FocusGained
void moa.gui.outliertab.OutlierTabPanel.jTabbedPane1MouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 80 of file OutlierTabPanel.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents().
                                                                         {//GEN-FIRST:event_jTabbedPane1MouseClicked
    }//GEN-LAST:event_jTabbedPane1MouseClicked
void moa.gui.outliertab.OutlierTabPanel.stop () [package]
Definition at line 40 of file OutlierTabPanel.java.
References moa.gui.outliertab.OutlierTabPanel.outlierVisualTab, and moa.gui.outliertab.OutlierVisualTab.stopVisualizer().
Referenced by moa.gui.outliertab.OutlierSetupTab.stop().
                {
        outlierVisualTab.stopVisualizer();
    }
void moa.gui.outliertab.OutlierTabPanel.toggle () [package]
Definition at line 36 of file OutlierTabPanel.java.
References moa.gui.outliertab.OutlierTabPanel.outlierVisualTab, and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
Referenced by moa.gui.outliertab.OutlierSetupTab.toggle().
                  {
        outlierVisualTab.toggleVisualizer(false);
    }
Member Data Documentation
javax.swing.JTabbedPane moa.gui.outliertab.OutlierTabPanel.jTabbedPane1 [private]
Definition at line 89 of file OutlierTabPanel.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents().
moa.gui.outliertab.OutlierSetupTab moa.gui.outliertab.OutlierTabPanel.outlierSetupTab [private]
Definition at line 87 of file OutlierTabPanel.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents(), and moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel().
moa.gui.outliertab.OutlierVisualTab moa.gui.outliertab.OutlierTabPanel.outlierVisualTab [private]
Definition at line 88 of file OutlierTabPanel.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents(), moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel(), moa.gui.outliertab.OutlierTabPanel.stop(), and moa.gui.outliertab.OutlierTabPanel.toggle().
The documentation for this class was generated from the following file:
main/java/moa/gui/outliertab/OutlierTabPanel.java