MOA: moa.streams.generators.LEDGeneratorDrift Class Reference
moa.streams.generators.LEDGeneratorDrift Class Reference
Stream generator for the problem of predicting the digit displayed on a 7-segment LED display with drift.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Instance nextInstance ()
Gets the next instance from this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption numberAttributesDriftOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
int[] numberAttribute
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for the problem of predicting the digit displayed on a 7-segment LED display with drift.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 36 of file LEDGeneratorDrift.java.
Member Function Documentation
void moa.streams.generators.LEDGeneratorDrift.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Reimplemented from moa.streams.generators.LEDGenerator.
Definition at line 94 of file LEDGeneratorDrift.java.
{
        // TODO Auto-generated method stub
    }
String moa.streams.generators.LEDGeneratorDrift.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.streams.generators.LEDGenerator.
Definition at line 39 of file LEDGeneratorDrift.java.
{
        return "Generates a problem of predicting the digit displayed on a 7-segment LED display with drift.";
    }
Instance moa.streams.generators.LEDGeneratorDrift.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Reimplemented from moa.streams.generators.LEDGenerator.
Definition at line 72 of file LEDGeneratorDrift.java.
References moa.streams.generators.LEDGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.LEDGenerator.instanceRandom, moa.options.FlagOption.isSet, moa.streams.generators.LEDGenerator.noisePercentageOption, moa.streams.generators.LEDGenerator.NUM_IRRELEVANT_ATTRIBUTES, moa.streams.generators.LEDGeneratorDrift.numberAttribute, moa.streams.generators.LEDGenerator.originalInstances, and moa.streams.generators.LEDGenerator.suppressIrrelevantAttributesOption.
{
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        inst.setDataset(header);
        int selected = this.instanceRandom.nextInt(10);
        for (int i = 0; i < 7; i++) {
            if ((1 + (this.instanceRandom.nextInt(100))) <= this.noisePercentageOption.getValue()) {
                inst.setValue(this.numberAttribute[i], originalInstances[selected][i] == 0 ? 1 : 0);
            } else {
                inst.setValue(this.numberAttribute[i], originalInstances[selected][i]);
            }
        }
        if (!this.suppressIrrelevantAttributesOption.isSet()) {
            for (int i = 0; i < NUM_IRRELEVANT_ATTRIBUTES; i++) {
                inst.setValue(this.numberAttribute[i + 7], this.instanceRandom.nextInt(2));
            }
        }
        inst.setClassValue(selected);
        return inst;
    }
void moa.streams.generators.LEDGeneratorDrift.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Reimplemented from moa.streams.generators.LEDGenerator.
Definition at line 51 of file LEDGeneratorDrift.java.
References moa.options.IntOption.getValue(), moa.options.FlagOption.isSet, moa.streams.generators.LEDGenerator.NUM_IRRELEVANT_ATTRIBUTES, moa.streams.generators.LEDGeneratorDrift.numberAttribute, moa.streams.generators.LEDGeneratorDrift.numberAttributesDriftOption, and moa.streams.generators.LEDGenerator.suppressIrrelevantAttributesOption.
{
        super.prepareForUseImpl(monitor, repository);
        this.numberAttribute = new int[7 + NUM_IRRELEVANT_ATTRIBUTES];
        for (int i = 0; i < 7 + NUM_IRRELEVANT_ATTRIBUTES; i++) {
            this.numberAttribute[i] = i;
        }
        //Change atributes
        if (!this.suppressIrrelevantAttributesOption.isSet() && this.numberAttributesDriftOption.getValue() > 0) {
            int randomInt = 0;//this.instanceRandom.nextInt(7);
            int offset = 0;//this.instanceRandom.nextInt(NUM_IRRELEVANT_ATTRIBUTES);
            for (int i = 0; i < this.numberAttributesDriftOption.getValue(); i++) {
                int value1 = (i + randomInt) % 7;
                int value2 = 7 + ((i + offset) % (NUM_IRRELEVANT_ATTRIBUTES));
                this.numberAttribute[value1] = value2;
                this.numberAttribute[value2] = value1;
            }
        }
    }
Member Data Documentation
int [] moa.streams.generators.LEDGeneratorDrift.numberAttribute [protected]
Definition at line 48 of file LEDGeneratorDrift.java.
Referenced by moa.streams.generators.LEDGeneratorDrift.nextInstance(), and moa.streams.generators.LEDGeneratorDrift.prepareForUseImpl().
IntOption moa.streams.generators.LEDGeneratorDrift.numberAttributesDriftOption
Initial value:
 new IntOption("numberAttributesDrift",
            'd', "Number of attributes with drift.", 1, 0, 7)
Definition at line 45 of file LEDGeneratorDrift.java.
Referenced by moa.streams.generators.LEDGeneratorDrift.prepareForUseImpl().
final long moa.streams.generators.LEDGeneratorDrift.serialVersionUID = 1L [static, private]
Reimplemented from moa.streams.generators.LEDGenerator.
Definition at line 43 of file LEDGeneratorDrift.java.
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/LEDGeneratorDrift.java