MOA: moa.recommender.predictor.BaselinePredictor Class Reference
moa.recommender.predictor.BaselinePredictor Class Reference
A naive algorithm which combines the global mean of all the existing ratings, the mean rating of the user and the mean rating of the item to make a prediction.
Public Member Functions
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
double predictRating (Integer user, Integer item)
moa.recommender.rc.data.RecommenderData getData ()
double predictRating (int userID, int itemID)
List< Double > predictRatings (int userID, List< Integer > itemIDS)
void train ()
Public Attributes
ClassOption dataOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
moa.recommender.rc.predictor.impl.BaselinePredictor rp
Detailed Description
A naive algorithm which combines the global mean of all the existing ratings, the mean rating of the user and the mean rating of the item to make a prediction.
Definition at line 36 of file BaselinePredictor.java.
Member Function Documentation
moa.recommender.rc.data.RecommenderData moa.recommender.predictor.BaselinePredictor.getData ()
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 57 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.getData(), and moa.recommender.predictor.BaselinePredictor.rp.
Referenced by moa.recommender.predictor.BaselinePredictor.getData().
{
        return rp.getData();
    }
void moa.recommender.predictor.BaselinePredictor.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 49 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.rp, and moa.AbstractMOAObject.toString().
{
        sb.append(rp.toString());
    }
double moa.recommender.predictor.BaselinePredictor.predictRating (int userID, int itemID)
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 62 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.predictRating(), and moa.recommender.predictor.BaselinePredictor.rp.
{
        return rp.predictRating(userID, itemID);
    }
double moa.recommender.predictor.BaselinePredictor.predictRating (Integer user, Integer item)
Definition at line 53 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.predictRating(), and moa.recommender.predictor.BaselinePredictor.rp.
Referenced by moa.recommender.predictor.BaselinePredictor.predictRating().
{
        return rp.predictRating(user,item);
    }
List<Double> moa.recommender.predictor.BaselinePredictor.predictRatings (int userID, List< Integer > itemIDS)
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 67 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.predictRatings(), and moa.recommender.predictor.BaselinePredictor.rp.
Referenced by moa.recommender.predictor.BaselinePredictor.predictRatings().
{
        return rp.predictRatings(userID, itemIDS);
    }
void moa.recommender.predictor.BaselinePredictor.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 43 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.dataOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), and moa.recommender.predictor.BaselinePredictor.rp.
{
        moa.recommender.data.RecommenderData data = (moa.recommender.data.RecommenderData) getPreparedClassOption(this.dataOption);
        rp = new moa.recommender.rc.predictor.impl.BaselinePredictor(data.getData());
    }
void moa.recommender.predictor.BaselinePredictor.train ()
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 72 of file BaselinePredictor.java.
References moa.recommender.predictor.BaselinePredictor.rp, and moa.recommender.predictor.BaselinePredictor.train().
Referenced by moa.recommender.predictor.BaselinePredictor.train().
{
        rp.train();
    }
Member Data Documentation
ClassOption moa.recommender.predictor.BaselinePredictor.dataOption
Initial value:
 new ClassOption("data", 'd',
            "Data", moa.recommender.data.RecommenderData.class, "moa.recommender.data.MemRecommenderData")
Definition at line 39 of file BaselinePredictor.java.
Referenced by moa.recommender.predictor.BaselinePredictor.prepareForUseImpl().
moa.recommender.rc.predictor.impl.BaselinePredictor moa.recommender.predictor.BaselinePredictor.rp [protected]
Definition at line 37 of file BaselinePredictor.java.
Referenced by moa.recommender.predictor.BaselinePredictor.getData(), moa.recommender.predictor.BaselinePredictor.getDescription(), moa.recommender.predictor.BaselinePredictor.predictRating(), moa.recommender.predictor.BaselinePredictor.predictRatings(), moa.recommender.predictor.BaselinePredictor.prepareForUseImpl(), and moa.recommender.predictor.BaselinePredictor.train().
The documentation for this class was generated from the following file:
main/java/moa/recommender/predictor/BaselinePredictor.java