MOA: moa.clusterers.outliers.AbstractC.AbstractCBase Class Reference
moa.clusterers.outliers.AbstractC.AbstractCBase Class Reference
Public Member Functions
String getObjectInfo (Object obj)
String getStatistics ()
void Print_lt_cnt (ArrayList< Integer > lt_cnt)
Public Attributes
int m_nBothInlierOutlier
int m_nOnlyInlier
int m_nOnlyOutlier
Protected Member Functions
boolean IsNodeIdInWin (long id)
Protected Attributes
Long objId
Vector< ISBNode > windowNodes
ISBIndex ISB
int m_WindowSize
double m_radius
double m_Fraction
boolean bWarning = false
Static Protected Attributes
static final Long FIRST_OBJ_ID = 1L
Package Functions
Long GetWindowEnd ()
Long GetWindowStart ()
boolean IsWinFull ()
Long GetExpirationTime (ISBNode node)
void AddNode (ISBNode node)
void RemoveNode (ISBNode node)
ISBNode GetExpiredNode ()
void SaveOutlier (ISBNode node)
void RemoveOutlier (ISBNode node)
void PrintWindow ()
void PrintNode (ISBNode n)
Detailed Description
Definition at line 29 of file AbstractCBase.java.
Member Function Documentation
void moa.clusterers.outliers.AbstractC.AbstractCBase.AddNode (ISBNode node) [package]
Definition at line 137 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.ISBIndex.Insert(), moa.clusterers.outliers.AbstractC.AbstractCBase.ISB, and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        windowNodes.add(node);
        ISB.Insert(node);
    }
Long moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpirationTime (ISBNode node) [package]
Definition at line 133 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, and moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize.
{
        return node.id + m_WindowSize;
    }
ISBNode moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpiredNode () [package]
Definition at line 155 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart(), moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        if (windowNodes.size() <= 0)
            return null;
        // get oldest node
        ISBNode node = windowNodes.get(0);
        // check if node has expired
        if (node.id < GetWindowStart()) {
            return node;
        }
        return null;
    }
String moa.clusterers.outliers.AbstractC.AbstractCBase.getObjectInfo (Object obj)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 48 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.StreamObj.dimensions(), moa.clusterers.outliers.AbstractC.StreamObj.get(), moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, and moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.obj.
{
        if (obj == null) return null;
        ISBNode node = (ISBNode) obj;
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        StringBuilder sb = new StringBuilder();
        // show node position
        for (int i = 0; i < node.obj.dimensions(); i++) {
            infoTitle.add("Dim" + (i+1));
            infoValue.add(String.format("%.3f", node.obj.get(i)));
        }
        // show node properties
        infoTitle.add("id");
        infoValue.add(String.format("%d", node.id));
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td><b>"+infoTitle.get(i)+":</b></td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
String moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 82 of file AbstractCBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nBothInlierOutlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyInlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
{
        StringBuilder sb = new StringBuilder();
        sb.append("Statistics:\n\n");
        // get counters of expired nodes
        int nBothInlierOutlier = m_nBothInlierOutlier;
        int nOnlyInlier = m_nOnlyInlier;
        int nOnlyOutlier = m_nOnlyOutlier;
        // add counters of non expired nodes
        for (ISBNode node : windowNodes) {
            if ((node.nInlier > 0) && (node.nOutlier > 0))
                nBothInlierOutlier++;
            else if (node.nInlier > 0)
                nOnlyInlier++;
            else
                nOnlyOutlier++;
        }
        int sum = nBothInlierOutlier + nOnlyInlier + nOnlyOutlier;
        if (sum > 0) {
            sb.append(String.format("  Nodes always inlier: %d (%.1f%%)\n", nOnlyInlier, (100 * nOnlyInlier) / (double)sum));
            sb.append(String.format("  Nodes always outlier: %d (%.1f%%)\n", nOnlyOutlier, (100 * nOnlyOutlier) / (double)sum));
            sb.append(String.format("  Nodes both inlier and outlier: %d (%.1f%%)\n", nBothInlierOutlier, (100 * nBothInlierOutlier) / (double)sum));
            sb.append("  (Sum: " + sum + ")\n");
        }
        sb.append("\n  Total range queries: " + nRangeQueriesExecuted + "\n");
        sb.append("  Max memory usage: " + iMaxMemUsage + " MB\n");
        sb.append("  Total process time: " + String.format("%.2f ms", nTotalRunTime / 1000.0) + "\n");
        return sb.toString();
    }
Long moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd () [package]
Definition at line 118 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.objId.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart(), moa.clusterers.outliers.AbstractC.AbstractCBase.IsNodeIdInWin(), moa.clusterers.outliers.AbstractC.AbstractCBase.IsWinFull(), and moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow().
{
        return objId - 1;
    }
Long moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart () [package]
Definition at line 122 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.FIRST_OBJ_ID, moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd(), and moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpiredNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.IsNodeIdInWin(), and moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow().
{
        Long x = GetWindowEnd() - m_WindowSize + 1;
        if (x < FIRST_OBJ_ID)
            x = FIRST_OBJ_ID;
        return x;
    }
boolean moa.clusterers.outliers.AbstractC.AbstractCBase.IsNodeIdInWin (long id) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 178 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd(), and moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart().
{
        if ((GetWindowStart() <= id) && (id <= GetWindowEnd()) )
            return true;
        else
            return false;
    }
boolean moa.clusterers.outliers.AbstractC.AbstractCBase.IsWinFull () [package]
Definition at line 129 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.FIRST_OBJ_ID, moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd(), and moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
{
        return (GetWindowEnd() >= FIRST_OBJ_ID + m_WindowSize - 1);
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.Print_lt_cnt (ArrayList< Integer > lt_cnt)
Definition at line 206 of file AbstractCBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        for (int i = 0; i < lt_cnt.size(); i++) {
            Print("(" + i + ": " + lt_cnt.get(i) + ") ");
        }
        Println("");
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.PrintNode (ISBNode n) [package]
Definition at line 195 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.StreamObj.dimensions(), moa.clusterers.outliers.AbstractC.StreamObj.get(), moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.obj, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        Print("id=" + n.id + " (");
        int dim = n.obj.dimensions();
        for (int d = 0; d < dim; d++) {
            Print(Double.toString(n.obj.get(d)));
            if (d < dim - 1)
                Print(", ");
        }
        Println(")");
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow () [package]
Definition at line 185 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd(), moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintNode(), and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
                       {
        Println("Window [" + GetWindowStart() + "-" + GetWindowEnd() + "]: ");
        ISBNode node;
        for (int i = 0; i < windowNodes.size(); i++) {
            node = windowNodes.get(i);
            Print("   Node: ");
            PrintNode(node);
        }
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode (ISBNode node) [package]
Definition at line 142 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.inst, moa.clusterers.outliers.AbstractC.AbstractCBase.ISB, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nBothInlierOutlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyInlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyOutlier, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.nInlier, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.nOutlier, moa.clusterers.outliers.AbstractC.ISBIndex.Remove(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        windowNodes.remove(node);
        ISB.Remove(node);
        RemoveExpiredOutlier(new Outlier(node.inst, node.id, node)); // ### remove when expired?
        // update statistics
        if ((node.nInlier > 0) && (node.nOutlier > 0))
            m_nBothInlierOutlier++;
        else if (node.nInlier > 0)
            m_nOnlyInlier++;
        else
            m_nOnlyOutlier++;
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveOutlier (ISBNode node) [package]
Definition at line 172 of file AbstractCBase.java.
References moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.nInlier.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
{
        RemoveOutlier(new Outlier(node.inst, node.id, node));
        node.nInlier++; // update statistics
    }
void moa.clusterers.outliers.AbstractC.AbstractCBase.SaveOutlier (ISBNode node) [package]
Definition at line 167 of file AbstractCBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
{
        AddOutlier(new Outlier(node.inst, node.id, node));
        node.nOutlier++; // update statistics
    }
Member Data Documentation
boolean moa.clusterers.outliers.AbstractC.AbstractCBase.bWarning = false [protected]
Definition at line 40 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
final Long moa.clusterers.outliers.AbstractC.AbstractCBase.FIRST_OBJ_ID = 1L [static, protected]
Definition at line 30 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractCBase.IsWinFull().
ISBIndex moa.clusterers.outliers.AbstractC.AbstractCBase.ISB [protected]
Definition at line 36 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.AddNode(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
double moa.clusterers.outliers.AbstractC.AbstractCBase.m_Fraction [protected]
Definition at line 39 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
int moa.clusterers.outliers.AbstractC.AbstractCBase.m_nBothInlierOutlier
Definition at line 43 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
int moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyInlier
Definition at line 44 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
int moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyOutlier
Definition at line 45 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
double moa.clusterers.outliers.AbstractC.AbstractCBase.m_radius [protected]
Definition at line 38 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
int moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize [protected]
Definition at line 37 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpirationTime(), moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowStart(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.clusterers.outliers.AbstractC.AbstractCBase.IsWinFull(), moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
Long moa.clusterers.outliers.AbstractC.AbstractCBase.objId [protected]
Definition at line 33 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.GetWindowEnd(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
Vector<ISBNode> moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes [protected]
Definition at line 35 of file AbstractCBase.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractCBase.AddNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpiredNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AbstractC/AbstractCBase.java