MOA: moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression Class Reference
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression Class Reference
Class for observing the class data distribution for a numeric attribute using a binary tree.
Classes
class Node
Public Member Functions
void observeAttributeTarget (double attVal, double target)
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
Node root1 = null
Static Public Attributes
static final long serialVersionUID = 1L
Protected Member Functions
AttributeSplitSuggestion searchForBestSplitOption (Node currentNode, AttributeSplitSuggestion currentBestOption, double[] actualParentLeft, double[] parentLeft, double[] parentRight, boolean leftChild, SplitCriterion criterion, double[] preSplitDist, int attIndex)
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Detailed Description
Class for observing the class data distribution for a numeric attribute using a binary tree.
This observer monitors the class distribution of a given attribute.
Learning Adaptive Model Rules from High-Speed Data Streams, ECML 2013, E. Almeida, C. Ferreira, P. Kosina and J. Gama;
Author:
E. Almeida, J. Gama
Version:
Revision
2
Definition at line 40 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 125 of file BinaryTreeNumericAttributeClassObserverRegression.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.root1, and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.searchForBestSplitOption().
{
        return searchForBestSplitOption(this.root1, null, null, null, null, false,
                criterion, preSplitDist, attIndex);
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 142 of file BinaryTreeNumericAttributeClassObserverRegression.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 113 of file BinaryTreeNumericAttributeClassObserverRegression.java.
{
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 101 of file BinaryTreeNumericAttributeClassObserverRegression.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.root1.
{
         if (Double.isNaN(attVal)) {
         } else {
             if (this.root1 == null) {
                 this.root1 = new Node(attVal, target);
             } else {
                 this.root1.insertValue(attVal, target);
             }
         }
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 147 of file BinaryTreeNumericAttributeClassObserverRegression.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 118 of file BinaryTreeNumericAttributeClassObserverRegression.java.
{
        // TODO: NaiveBayes broken until implemented
        return 0.0;
    }
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.searchForBestSplitOption (Node currentNode, AttributeSplitSuggestion currentBestOption, double[] actualParentLeft, double[] parentLeft, double[] parentRight, boolean leftChild, SplitCriterion criterion, double[] preSplitDist, int attIndex) [protected]
Definition at line 132 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.getBestEvaluatedSplitSuggestion().
{
        return currentBestOption;
    }
Member Data Documentation
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.root1 = null
Definition at line 99 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.getBestEvaluatedSplitSuggestion(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.observeAttributeTarget().
final long moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.serialVersionUID = 1L [static]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 43 of file BinaryTreeNumericAttributeClassObserverRegression.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/BinaryTreeNumericAttributeClassObserverRegression.java