MOA: moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver Class Reference
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver Class Reference
Class for observing the class data distribution for a numeric attribute using a binary tree.
Classes
class Node
Public Member Functions
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void observeAttributeTarget (double attVal, double target)
Public Attributes
Node root = null
Protected Member Functions
AttributeSplitSuggestion searchForBestSplitOption (Node currentNode, AttributeSplitSuggestion currentBestOption, double[] actualParentLeft, double[] parentLeft, double[] parentRight, boolean leftChild, SplitCriterion criterion, double[] preSplitDist, int attIndex)
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for observing the class data distribution for a numeric attribute using a binary tree.
This observer monitors the class distribution of a given attribute. Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 40 of file BinaryTreeNumericAttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 107 of file BinaryTreeNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.root, and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
{
        return searchForBestSplitOption(this.root, null, null, null, null, false,
                criterion, preSplitDist, attIndex);
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 169 of file BinaryTreeNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 88 of file BinaryTreeNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.root.
{
        if (Double.isNaN(attVal)) { //Instance.isMissingValue(attVal)
        } else {
            if (this.root == null) {
                this.root = new Node(attVal, classVal, weight);
            } else {
                this.root.insertValue(attVal, classVal, weight);
            }
        }
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 179 of file BinaryTreeNumericAttributeClassObserver.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 174 of file BinaryTreeNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 100 of file BinaryTreeNumericAttributeClassObserver.java.
{
        // TODO: NaiveBayes broken until implemented
        return 0.0;
    }
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption (Node currentNode, AttributeSplitSuggestion currentBestOption, double[] actualParentLeft, double[] parentLeft, double[] parentRight, boolean leftChild, SplitCriterion criterion, double[] preSplitDist, int attIndex) [protected]
Definition at line 114 of file BinaryTreeNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsRight, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.cut_point, moa.core.DoubleVector.getArrayRef(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.left, moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.right, and moa.core.DoubleVector.subtractValues().
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        if (currentNode == null) {
            return currentBestOption;
        }
        DoubleVector leftDist = new DoubleVector();
        DoubleVector rightDist = new DoubleVector();
        if (parentLeft == null) {
            leftDist.addValues(currentNode.classCountsLeft);
            rightDist.addValues(currentNode.classCountsRight);
        } else {
            leftDist.addValues(parentLeft);
            rightDist.addValues(parentRight);
            if (leftChild) {
                //get the exact statistics of the parent value
                DoubleVector exactParentDist = new DoubleVector();
                exactParentDist.addValues(actualParentLeft);
                exactParentDist.subtractValues(currentNode.classCountsLeft);
                exactParentDist.subtractValues(currentNode.classCountsRight);
                // move the subtrees
                leftDist.subtractValues(currentNode.classCountsRight);
                rightDist.addValues(currentNode.classCountsRight);
                // move the exact value from the parent
                rightDist.addValues(exactParentDist);
                leftDist.subtractValues(exactParentDist);
            } else {
                leftDist.addValues(currentNode.classCountsLeft);
                rightDist.subtractValues(currentNode.classCountsLeft);
            }
        }
        double[][] postSplitDists = new double[][]{leftDist.getArrayRef(),
            rightDist.getArrayRef()};
        double merit = criterion.getMeritOfSplit(preSplitDist, postSplitDists);
        if ((currentBestOption == null) || (merit > currentBestOption.merit)) {
            currentBestOption = new AttributeSplitSuggestion(
                    new NumericAttributeBinaryTest(attIndex,
                    currentNode.cut_point, true), postSplitDists, merit);
        }
        currentBestOption = searchForBestSplitOption(currentNode.left,
                currentBestOption, currentNode.classCountsLeft.getArrayRef(), postSplitDists[0], postSplitDists[1], true,
                criterion, preSplitDist, attIndex);
        currentBestOption = searchForBestSplitOption(currentNode.right,
                currentBestOption, currentNode.classCountsLeft.getArrayRef(), postSplitDists[0], postSplitDists[1], false,
                criterion, preSplitDist, attIndex);
        return currentBestOption;
    }
Member Data Documentation
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.root = null
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.
Definition at line 85 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.observeAttributeClass().
final long moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, and moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.
Definition at line 43 of file BinaryTreeNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/BinaryTreeNumericAttributeClassObserver.java