MOA: moa.test.Regression Class Reference
moa.test.Regression Class Reference
Helper class for regression tests.
Public Member Functions
Regression (Class cls)
Initializes the regression check.
Class getRegressionClass ()
Returns the class this regression helper is for.
void setReferenceFile (File value)
Sets the reference file to use.
File getReferenceFile ()
Returns the file for storing the reference data in.
String compare (String content)
Compares the content generated by the specified class with the stored regression data.
String compare (String content, int[] ignore)
Compares the content generated by the specified class with the stored regression data.
String compare (String content, String nl)
Compares the content generated by the specified class with the stored regression data.
String compare (String content, String nl, int[] ignore)
Compares the content generated by the specified class with the stored regression data.
String compare (File[] files)
Compares the file content generated by the specified class with the stored regression data.
String compare (File[] files, int[] ignore)
Compares the file content generated by the specified class with the stored regression data.
Static Public Member Functions
static List< String > trim (List< String > list, int[] ignore)
Trims the list, i.e., removes the ignored indices from it.
static File createReferenceFile (Class regressionClass)
Creates a reference file for the specified class.
static File createReferenceFile (Class regressionClass, String suffix)
Creates a reference file for the specified class.
static File createReferenceFile (Class regressionClass, String suffix, String extension)
Creates a reference file for the specified class.
Static Public Attributes
static final String REFERENCES = "src/test/resources"
the storage place for reference files.
static final String EXTENSION = ".ref"
the extension for references (incl dot).
Protected Member Functions
String compare (List< String > content)
Compares the content generated by the specified class with the stored regression data.
Protected Attributes
Class m_RegressionClass
the class this regression test is for.
File m_ReferenceFile
the regression file to use.
Detailed Description
Helper class for regression tests.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
Revision
8528
Definition at line 34 of file Regression.java.
Constructor & Destructor Documentation
moa.test.Regression.Regression (Class cls)
Initializes the regression check.
Parameters:
cls the class that is being checked
Definition at line 53 of file Regression.java.
References moa.test.Regression.createReferenceFile(), moa.test.Regression.m_ReferenceFile, and moa.test.Regression.m_RegressionClass.
{
    super();
    m_RegressionClass = cls;
    m_ReferenceFile   = createReferenceFile(m_RegressionClass);
  }
Member Function Documentation
String moa.test.Regression.compare (File[] files, int[] ignore)
Compares the file content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet.
Parameters:
files the files containing the generated output to check
ignore the line indices in the files to ignore
Returns:
the difference, null if no difference
Definition at line 226 of file Regression.java.
References moa.test.Regression.compare(), and moa.test.Regression.trim().
{
    List<String>    content;
    int         i;
    content = new ArrayList<String>();
    for (i = 0; i < files.length; i++) {
      content.add("--> " + files[i].getName());
      if (!files[i].exists())
    content.add("file is missing");
      else
    content.addAll(trim(FileUtils.loadFromFile(files[i]), ignore));
      content.add("");
    }
    return compare(content);
  }
String moa.test.Regression.compare (File[] files)
Compares the file content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet.
Parameters:
files the files containing the generated output to check
Returns:
the difference, null if no difference
Definition at line 214 of file Regression.java.
References moa.test.Regression.compare().
{
    return compare(files, new int[0]);
  }
String moa.test.Regression.compare (String content, String nl, int[] ignore)
Compares the content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet.
Parameters:
content the content to check
nl the new line string to use
ignore the indices of the lines to ignore
Returns:
the difference, null if no difference
Definition at line 203 of file Regression.java.
References moa.test.Regression.compare(), and moa.test.Regression.trim().
{
    return compare(trim(Arrays.asList(content.split(nl)), ignore));
  }
String moa.test.Regression.compare (String content, String nl)
Compares the content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet.
Parameters:
content the content to check
nl the new line string to use
Returns:
the difference, null if no difference
Definition at line 190 of file Regression.java.
References moa.test.Regression.compare().
{
    return compare(content, nl, new int[0]);
  }
String moa.test.Regression.compare (String content, int[] ignore)
Compares the content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet. Uses "\n" for splitting the string content into lines.
Parameters:
content the content to check
ignore the indices of the lines to ignore
Returns:
the difference, null if no difference
Definition at line 178 of file Regression.java.
References moa.test.Regression.compare().
{
    return compare(content, "\n", ignore);
  }
String moa.test.Regression.compare (String content)
Compares the content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet. Uses "\n" for splitting the string content into lines.
Parameters:
content the content to check
Returns:
the difference, null if no difference
Definition at line 165 of file Regression.java.
References moa.test.Regression.compare().
{
    return compare(content, "\n");
  }
String moa.test.Regression.compare (List< String > content) [protected]
Compares the content generated by the specified class with the stored regression data.
Creates a new reference file if not present yet.
Parameters:
content the content to check
Returns:
the difference (or an error message), null if no difference
Definition at line 98 of file Regression.java.
References moa.test.Regression.getReferenceFile(), and moa.test.Regression.m_ReferenceFile.
Referenced by moa.test.Regression.compare().
{
    String      result;
    List<String>    reference;
    // reference available?
    if (!getReferenceFile().exists()) {
      if (!getReferenceFile().getParentFile().exists()) {
    if (!getReferenceFile().getParentFile().mkdirs())
      return "Failed to create reference file: " + m_ReferenceFile;
      }
      if (FileUtils.saveToFile(content, getReferenceFile())) {
    System.err.println("Reference file created: " + m_ReferenceFile);
    return null;
      }
      else {
    return "Failed to create reference file: " + m_ReferenceFile;
      }
    }
    // compare
    reference = FileUtils.loadFromFile(getReferenceFile());
    result    = DiffUtils.unified(reference, content);
    if (result.length() == 0)
      return null;
    else
      return result.toString();
  }
static File moa.test.Regression.createReferenceFile (Class regressionClass, String suffix, String extension) [static]
Creates a reference file for the specified class.
Parameters:
regressionClass the class to build the reference file name for
suffix the suffix to use (between classname and extension), null to omit
extension the file extension (incl the dot, eg ".ref")
Returns:
the generated filename
Definition at line 273 of file Regression.java.
References moa.test.Regression.REFERENCES.
{
    if (suffix == null)
      suffix = "";
    return new File(REFERENCES + "/" + regressionClass.getName().replace(".", "/") + suffix + extension);
  }
static File moa.test.Regression.createReferenceFile (Class regressionClass, String suffix) [static]
Creates a reference file for the specified class.
Parameters:
regressionClass the class to build the reference file name for
suffix the suffix to use (between classname and extension), null to omit
Returns:
the generated filename
Definition at line 261 of file Regression.java.
References moa.test.Regression.createReferenceFile(), and moa.test.Regression.EXTENSION.
{
    return createReferenceFile(regressionClass, suffix, EXTENSION);
  }
static File moa.test.Regression.createReferenceFile (Class regressionClass) [static]
Creates a reference file for the specified class.
Parameters:
regressionClass the class to build the reference file name for
suffix the suffix to use (between classname and extension), null to omit
Returns:
the generated filename
Definition at line 250 of file Regression.java.
Referenced by moa.test.Regression.createReferenceFile(), and moa.test.Regression.Regression().
{
    return createReferenceFile(regressionClass, null);
  }
File moa.test.Regression.getReferenceFile ()
Returns the file for storing the reference data in.
Returns:
the reference file
Definition at line 87 of file Regression.java.
References moa.test.Regression.m_ReferenceFile.
Referenced by moa.test.Regression.compare().
{
    return m_ReferenceFile;
  }
Class moa.test.Regression.getRegressionClass ()
Returns the class this regression helper is for.
Returns:
the class
Definition at line 65 of file Regression.java.
References moa.test.Regression.m_RegressionClass.
Referenced by moa.test.MoaTestCase.testSerializable().
{
    return m_RegressionClass;
  }
void moa.test.Regression.setReferenceFile (File value)
Sets the reference file to use.
Normally, the reference file is determined based on the classname. This method should only be called if a file different from the class name must be used, for instance for an additional regression test.
Parameters:
value the reference file to use
Definition at line 78 of file Regression.java.
References moa.test.Regression.m_ReferenceFile.
{
    m_ReferenceFile = value;
  }
static List<String> moa.test.Regression.trim (List< String > list, int[] ignore) [static]
Trims the list, i.e., removes the ignored indices from it.
Parameters:
list the list to trim
ignore the ignored indices
Returns:
the trimmed list
Definition at line 135 of file Regression.java.
Referenced by moa.test.Regression.compare().
{
    List<String>    result;
    HashSet<Integer>    ignored;
    int         i;
    if (ignore.length == 0)
      return list;
    result  = new ArrayList<String>();
    ignored = new HashSet<Integer>();
    for (int ign: ignore)
      ignored.add(ign);
    for (i = 0; i < list.size(); i++) {
      if (ignored.contains(i))
    continue;
      result.add(list.get(i));
    }
    return result;
  }
Member Data Documentation
final String moa.test.Regression.EXTENSION = ".ref" [static]
the extension for references (incl dot).
Definition at line 40 of file Regression.java.
Referenced by moa.test.Regression.createReferenceFile().
File moa.test.Regression.m_ReferenceFile [protected]
the regression file to use.
Definition at line 46 of file Regression.java.
Referenced by moa.test.Regression.compare(), moa.test.Regression.getReferenceFile(), moa.test.Regression.Regression(), and moa.test.Regression.setReferenceFile().
Class moa.test.Regression.m_RegressionClass [protected]
the class this regression test is for.
Definition at line 43 of file Regression.java.
Referenced by moa.test.Regression.getRegressionClass(), and moa.test.Regression.Regression().
final String moa.test.Regression.REFERENCES = "src/test/resources" [static]
the storage place for reference files.
Definition at line 37 of file Regression.java.
Referenced by moa.test.Regression.createReferenceFile().
The documentation for this class was generated from the following file:
test/java/moa/test/Regression.java