MOA: moa.clusterers.outliers.TestSpeed Class Reference
moa.clusterers.outliers.TestSpeed Class Reference
Static Public Member Functions
static void main (String[] args) throws Exception
Detailed Description
Definition at line 30 of file TestSpeed.java.
Member Function Documentation
static void moa.clusterers.outliers.TestSpeed.main (String[] args) throws Exception [static]
Definition at line 31 of file TestSpeed.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.getHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.hasMoreInstances(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.options.AbstractOptionHandler.prepareForUse(), moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), moa.clusterers.outliers.Angiulli.ExactSTORM.queryFreqOption, moa.clusterers.AbstractClusterer.setModelContext(), and moa.options.IntOption.setValue().
    {
        int numInstances = 2000;
        RandomRBFGeneratorEvents stream = new RandomRBFGeneratorEvents();
        stream.prepareForUse();
        SimpleCOD scod = new SimpleCOD();
        MCOD mcod = new MCOD();
        ExactSTORM angiulli = new ExactSTORM();
        //DistanceOutliersAppr angiulli = new DistanceOutliersAppr();
        AbstractC abstractC = new AbstractC();
        angiulli.queryFreqOption.setValue(1);
        scod.setModelContext(stream.getHeader());
        scod.prepareForUse();
        mcod.setModelContext(stream.getHeader());
        mcod.prepareForUse();
        angiulli.setModelContext(stream.getHeader());
        angiulli.prepareForUse();
        abstractC.setModelContext(stream.getHeader());
        abstractC.prepareForUse();
        Long tmStart = System.currentTimeMillis();
        int numberSamples = 0;
        while (stream.hasMoreInstances() && (numberSamples < numInstances)) {
            Instance newInst = stream.nextInstance();
            //scod.processNewInstanceImpl(newInst);
            mcod.processNewInstanceImpl(newInst);
            //angiulli.processNewInstanceImpl(newInst);
            //abstractC.processNewInstanceImpl(newInst);
            numberSamples++;
        }
        System.out.println("Total time = " + (System.currentTimeMillis() - tmStart) + " ms");
    }
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/TestSpeed.java