MOA: moa.options.StringOption Class Reference
moa.options.StringOption Class Reference
String option.
Public Member Functions
StringOption (String name, char cliChar, String purpose, String defaultVal)
void setValue (String v)
String getValue ()
String getDefaultCLIString ()
Gets the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Protected Attributes
String currentVal
String defaultVal
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
String option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 28 of file StringOption.java.
Constructor & Destructor Documentation
moa.options.StringOption.StringOption (String name, char cliChar, String purpose, String defaultVal)
Definition at line 36 of file StringOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        this.defaultVal = defaultVal;
        resetToDefault();
    }
Member Function Documentation
String moa.options.StringOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 52 of file StringOption.java.
References moa.options.StringOption.defaultVal.
{
        return this.defaultVal;
    }
String moa.options.StringOption.getValue ()
Definition at line 47 of file StringOption.java.
References moa.options.StringOption.currentVal.
Referenced by moa.tasks.Plot.createScript(), moa.tasks.RunTasks.doMainTask(), moa.tasks.RunStreamTasks.doMainTask(), moa.tasks.Plot.doMainTask(), moa.tasks.EvaluateClustering.doMainTask(), moa.options.FileOption.getFile(), and moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl().
{
        return this.currentVal;
    }
String moa.options.StringOption.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Definition at line 57 of file StringOption.java.
References moa.options.StringOption.currentVal.
Referenced by moa.gui.FileOptionEditComponent.FileOptionEditComponent().
{
        return this.currentVal;
    }
void moa.options.StringOption.setValue (String v)
Definition at line 43 of file StringOption.java.
References moa.options.StringOption.currentVal.
Referenced by moa.streams.ArffFileStream.ArffFileStream(), moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream(), and moa.options.StringOption.setValueViaCLIString().
{
        this.currentVal = v;
    }
void moa.options.StringOption.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Definition at line 62 of file StringOption.java.
References moa.options.StringOption.setValue().
Referenced by moa.gui.FileOptionEditComponent.applyState().
{
        setValue(s);
    }
Member Data Documentation
String moa.options.StringOption.currentVal [protected]
Definition at line 32 of file StringOption.java.
Referenced by moa.options.StringOption.getValue(), moa.options.StringOption.getValueAsCLIString(), and moa.options.StringOption.setValue().
String moa.options.StringOption.defaultVal [protected]
Definition at line 34 of file StringOption.java.
Referenced by moa.options.StringOption.getDefaultCLIString().
final long moa.options.StringOption.serialVersionUID = 1L [static, private]
Reimplemented in moa.options.FileOption.
Definition at line 30 of file StringOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/StringOption.java