MOA: moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier Class Reference
moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier Class Reference
Public Member Functions
LearningNodeClassifier (double[] initialClassObservations)
LearningNodeClassifier (double[] initialClassObservations, Classifier cl, HoeffdingTreeClassifLeaves ht)
double[] getClassVotes (Instance inst, HoeffdingTree ht)
void disableAttribute (int attIndex)
void learnFromInstance (Instance inst, HoeffdingTree ht)
Classifier getClassifier ()
Protected Attributes
Classifier classifier
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 48 of file HoeffdingTreeClassifLeaves.java.
Constructor & Destructor Documentation
moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier (double[] initialClassObservations)
Definition at line 54 of file HoeffdingTreeClassifLeaves.java.
{
            super(initialClassObservations);
        }
moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier (double[] initialClassObservations, Classifier cl, HoeffdingTreeClassifLeaves ht)
Definition at line 58 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.classifier, moa.classifiers.Classifier.copy(), moa.options.AbstractOptionHandler.getPreparedClassOption(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.learnerOption.
{
            super(initialClassObservations);
            //public void LearningNodeClassifier1(double[] initialClassObservations, Classifier cl, HoeffdingTreeClassifLeaves ht ) {
            if (cl == null) {
                this.classifier = (Classifier) getPreparedClassOption(ht.learnerOption);
            } else {
                this.classifier = cl.copy();
            }
        }
Member Function Documentation
void moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.disableAttribute (int attIndex)
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 78 of file HoeffdingTreeClassifLeaves.java.
{
            // should not disable poor atts - they are used in NB calc
        }
Classifier moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassifier ()
Definition at line 88 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.classifier.
{
            return this.classifier;
        }
double [] moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes (Instance inst, HoeffdingTree ht)
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 70 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.classifier, moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), and moa.classifiers.trees.HoeffdingTree.nbThresholdOption.
{
            if (getWeightSeen() >= ((HoeffdingTreeClassifLeaves) ht).nbThresholdOption.getValue()) {
                return this.classifier.getVotesForInstance(inst);
            }
            return super.getClassVotes(inst, ht);
        }
void moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.learnFromInstance (Instance inst, HoeffdingTree ht) [virtual]
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 83 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.classifier, and moa.classifiers.Classifier.trainOnInstance().
{
            this.classifier.trainOnInstance(inst);
            super.learnFromInstance(inst, ht);
        }
Member Data Documentation
Classifier moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.classifier [protected]
Definition at line 50 of file HoeffdingTreeClassifLeaves.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassifier(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.learnFromInstance(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier().
final long moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 52 of file HoeffdingTreeClassifLeaves.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/HoeffdingTreeClassifLeaves.java