MOA: moa.clusterers.outliers.AbstractC.AbstractC Class Reference
moa.clusterers.outliers.AbstractC.AbstractC Class Reference
Public Member Functions
AbstractC ()
void Init ()
Public Attributes
FloatOption radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
IntOption kOption = new IntOption("k", 't', "Parameter k.", 50)
FlagOption waitWinFullOption = new FlagOption("waitWinFull", 'a', "Output outliers when windows is full.")
Protected Member Functions
void ProcessNewStreamObj (Instance inst)
Package Functions
void UpdateNeighbors (ISBNode n, ISBNode q)
void OutputPatterns ()
Detailed Description
Definition at line 37 of file AbstractC.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.AbstractC.AbstractC.AbstractC ()
Definition at line 43 of file AbstractC.java.
Referenced by moa.clusterers.outliers.AbstractC.Test.main().
    {
        // System.out.println("AbstractC: created");
    }
Member Function Documentation
void moa.clusterers.outliers.AbstractC.AbstractC.Init ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 49 of file AbstractC.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.bWarning, moa.clusterers.outliers.AbstractC.AbstractCBase.FIRST_OBJ_ID, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.clusterers.outliers.AbstractC.AbstractCBase.ISB, moa.clusterers.outliers.AbstractC.AbstractC.kOption, moa.clusterers.outliers.AbstractC.AbstractCBase.m_Fraction, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nBothInlierOutlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyInlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_nOnlyOutlier, moa.clusterers.outliers.AbstractC.AbstractCBase.m_radius, moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize, moa.clusterers.outliers.AbstractC.AbstractCBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.AbstractC.AbstractC.radiusOption, moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes, and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
                       {
        super.Init();
        m_WindowSize = windowSizeOption.getValue();
        m_radius = radiusOption.getValue();
        //m_Fraction = fractionOption.getValue();
        m_Fraction = (double)kOption.getValue() / (double)m_WindowSize;
        Println("Init AbstractC:");
        Println("   window_size: " + m_WindowSize);
        Println("   radius: " + m_radius);
        Println("   Fraction: " + m_Fraction);
        Println("   (Fraction * window_size: " + String.format("%.2f", m_Fraction * m_WindowSize) + ")");
        //bTrace = true;
        bWarning = true;
        objId = FIRST_OBJ_ID; // init object identifier
        // create fifo
        windowNodes = new Vector<ISBNode>();
        // create ISB
        ISB = new ISBIndex(m_radius, m_Fraction);
        // init statistics
        m_nBothInlierOutlier = 0;
        m_nOnlyInlier = 0;
        m_nOnlyOutlier = 0;
    }
void moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns () [package]
Definition at line 91 of file AbstractC.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.AbstractC.AbstractCBase.bWarning, moa.options.FlagOption.isSet, moa.clusterers.outliers.AbstractC.AbstractCBase.IsWinFull(), moa.clusterers.outliers.AbstractC.AbstractCBase.m_Fraction, moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveOutlier(), moa.clusterers.outliers.AbstractC.AbstractCBase.SaveOutlier(), moa.clusterers.outliers.AbstractC.AbstractC.waitWinFullOption, and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        if (bTrace) Println("OutputPatterns");
        double thr = m_Fraction * m_WindowSize;
        for (ISBNode node : windowNodes) {
            if (node.lt_cnt.size() > 0) {
                if (IsWinFull() || !waitWinFullOption.isSet()) {
                    if (node.lt_cnt.get(0) < thr) {
                        SaveOutlier(node);
                    } else {
                        RemoveOutlier(node);
                    }
                }
                node.lt_cnt.remove(0);
            } else {
                if (bWarning) Println("OutputPatterns: " + node.id + ".lt_cnt is empty!");
            }
        }
    }
void moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 113 of file AbstractC.java.
References moa.clusterers.outliers.AbstractC.AbstractCBase.AddNode(), moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.AbstractC.AbstractCBase.GetExpiredNode(), moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues(), moa.clusterers.outliers.AbstractC.AbstractCBase.ISB, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.lt_cnt, moa.clusterers.outliers.AbstractC.AbstractCBase.m_radius, moa.clusterers.outliers.AbstractC.AbstractCBase.m_WindowSize, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.AbstractC.AbstractCBase.objId, moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.AbstractC.AbstractCBase.Print_lt_cnt(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintNode(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow(), moa.clusterers.outliers.AbstractC.ISBIndex.RangeSearch(), moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode(), moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress(), moa.clusterers.outliers.AbstractC.AbstractC.UpdateNeighbors(), and moa.clusterers.outliers.AbstractC.AbstractCBase.windowNodes.
    {
        if (bShowProgress) ShowProgress("Processed " + (objId - 1) + " stream objects.");
        // PrintInstance(inst);
        double[] values = getInstanceValues(inst);
        StreamObj obj = new StreamObj(values);
        // process new data stream object
        if (bTrace) Println("\n- - - - - - - - - - - -\n");
        // create new ISB node
        ISBNode nodeNew = new ISBNode(inst, obj, objId);
        if (bTrace) { Print("New node: "); PrintNode(nodeNew); }
        objId++; // update object identifier (slide window)
        // purge expired node
        ISBNode nodeExpired = GetExpiredNode();
        if (nodeExpired != null) {
            // purge nodeExpired
            if (bTrace) { Print("nodeExpired: "); PrintNode(nodeExpired); }
            RemoveNode(nodeExpired);
        }
        // initialize nodeNew.lt_cnt
        if (bTrace) Println("initialize nodeNew");
        for (int i = 0; i < m_WindowSize; i++) {
            nodeNew.lt_cnt.add(1);
        }
        AddNode(nodeNew); // add nodeNew to window and index
        if (bTrace) PrintWindow();
        // perform range query search
        if (bTrace) Println("Perform range query seach");
        nRangeQueriesExecuted++;
        Vector<ISBIndex.ISBSearchResult> neighbors = ISB.RangeSearch(nodeNew, m_radius);
        // process each returned node
        for (ISBSearchResult res : neighbors) {
            ISBNode node = res.node;
            UpdateNeighbors(nodeNew, node);
        }
        OutputPatterns();
        if (bTrace) {
            PrintOutliers();
            for (ISBNode node : windowNodes) {
                Print(node.id + ".lt_count: "); Print_lt_cnt(node.lt_cnt);
            }
        }
    }
void moa.clusterers.outliers.AbstractC.AbstractC.UpdateNeighbors (ISBNode n, ISBNode q) [package]
Definition at line 78 of file AbstractC.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.id, moa.clusterers.outliers.AbstractC.ISBIndex.ISBNode.lt_cnt, and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        if (n == q) return;
        if (bTrace) Println("UpdateNeighbors: n.id: " + n.id + ", q.id: " + q.id);
        int len = q.lt_cnt.size();
        for (int i = 0; i < len; i++) {
            // n.lt_cnt++
            n.lt_cnt.set(i, n.lt_cnt.get(i) + 1);
            // q.lt_cnt++
            q.lt_cnt.set(i, q.lt_cnt.get(i) + 1);
        }
    }
Member Data Documentation
IntOption moa.clusterers.outliers.AbstractC.AbstractC.kOption = new IntOption("k", 't', "Parameter k.", 50)
Definition at line 40 of file AbstractC.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.Init().
FloatOption moa.clusterers.outliers.AbstractC.AbstractC.radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
Definition at line 38 of file AbstractC.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.Init().
FlagOption moa.clusterers.outliers.AbstractC.AbstractC.waitWinFullOption = new FlagOption("waitWinFull", 'a', "Output outliers when windows is full.")
Definition at line 41 of file AbstractC.java.
Referenced by moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AbstractC/AbstractC.java