MOA: moa.classifiers.drift.DriftDetectionMethodClassifier Class Reference
moa.classifiers.drift.DriftDetectionMethodClassifier Class Reference
Class for handling concept drift datasets with a wrapper on a classifier.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Public Attributes
ClassOption baseLearnerOption
ClassOption driftDetectionMethodOption
Static Public Attributes
static final int DDM_INCONTROL_LEVEL = 0
static final int DDM_WARNING_LEVEL = 1
static final int DDM_OUTCONTROL_LEVEL = 2
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier classifier
Classifier newclassifier
ChangeDetector driftDetectionMethod
boolean newClassifierReset
int ddmLevel
int changeDetected = 0
int warningDetected = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for handling concept drift datasets with a wrapper on a classifier.
Valid options are:
-l classname
Specify the full class name of a classifier as the basis for the concept drift classifier.
-d Drift detection method to use
Author:
Manuel Baena (mbaena@lcc.uma.es)
Version:
1.1
Definition at line 46 of file DriftDetectionMethodClassifier.java.
Member Function Documentation
void moa.classifiers.drift.DriftDetectionMethodClassifier.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 167 of file DriftDetectionMethodClassifier.java.
References moa.classifiers.drift.DriftDetectionMethodClassifier.classifier.
{
        ((AbstractClassifier) this.classifier).getModelDescription(out, indent);
    }
Measurement [] moa.classifiers.drift.DriftDetectionMethodClassifier.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 172 of file DriftDetectionMethodClassifier.java.
References moa.classifiers.drift.DriftDetectionMethodClassifier.changeDetected, moa.classifiers.drift.DriftDetectionMethodClassifier.classifier, and moa.classifiers.drift.DriftDetectionMethodClassifier.warningDetected.
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        measurementList.add(new Measurement("Change detected", this.changeDetected));
        measurementList.add(new Measurement("Warning detected", this.warningDetected));
        Measurement[] modelMeasurements = ((AbstractClassifier) this.classifier).getModelMeasurements();
        if (modelMeasurements != null) {
            for (Measurement measurement : modelMeasurements) {
                measurementList.add(measurement);
            }
        }
        this.changeDetected = 0;
        this.warningDetected = 0;
        return measurementList.toArray(new Measurement[measurementList.size()]);
    }
String moa.classifiers.drift.DriftDetectionMethodClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 51 of file DriftDetectionMethodClassifier.java.
{
        return "Classifier that replaces the current classifier with a new one when a change is detected in accuracy.";
    }
double [] moa.classifiers.drift.DriftDetectionMethodClassifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 157 of file DriftDetectionMethodClassifier.java.
References moa.classifiers.drift.DriftDetectionMethodClassifier.classifier, and moa.classifiers.Classifier.getVotesForInstance().
{
        return this.classifier.getVotesForInstance(inst);
    }
boolean moa.classifiers.drift.DriftDetectionMethodClassifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 162 of file DriftDetectionMethodClassifier.java.
{
        return true;
    }
void moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 87 of file DriftDetectionMethodClassifier.java.
References moa.classifiers.drift.DriftDetectionMethodClassifier.baseLearnerOption, moa.classifiers.drift.DriftDetectionMethodClassifier.classifier, moa.classifiers.Classifier.copy(), moa.classifiers.AbstractClassifier.copy(), moa.classifiers.drift.DriftDetectionMethodClassifier.driftDetectionMethod, moa.classifiers.drift.DriftDetectionMethodClassifier.driftDetectionMethodOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.drift.DriftDetectionMethodClassifier.newclassifier, moa.classifiers.drift.DriftDetectionMethodClassifier.newClassifierReset, and moa.classifiers.Classifier.resetLearning().
{
        this.classifier = ((Classifier) getPreparedClassOption(this.baseLearnerOption)).copy();
        this.newclassifier = this.classifier.copy();
        this.classifier.resetLearning();
        this.newclassifier.resetLearning();
        this.driftDetectionMethod = ((ChangeDetector) getPreparedClassOption(this.driftDetectionMethodOption)).copy();
        this.newClassifierReset = false;
    }
void moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 101 of file DriftDetectionMethodClassifier.java.
References moa.classifiers.drift.DriftDetectionMethodClassifier.baseLearnerOption, moa.classifiers.drift.DriftDetectionMethodClassifier.changeDetected, moa.classifiers.drift.DriftDetectionMethodClassifier.classifier, moa.classifiers.AbstractClassifier.copy(), moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_INCONTROL_LEVEL, moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_OUTCONTROL_LEVEL, moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_WARNING_LEVEL, moa.classifiers.drift.DriftDetectionMethodClassifier.ddmLevel, moa.classifiers.drift.DriftDetectionMethodClassifier.driftDetectionMethod, moa.classifiers.core.driftdetection.ChangeDetector.getChange(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.core.driftdetection.ChangeDetector.getWarningZone(), moa.classifiers.core.driftdetection.ChangeDetector.input(), moa.classifiers.drift.DriftDetectionMethodClassifier.newclassifier, moa.classifiers.drift.DriftDetectionMethodClassifier.newClassifierReset, moa.classifiers.Classifier.resetLearning(), moa.classifiers.Classifier.trainOnInstance(), and moa.classifiers.drift.DriftDetectionMethodClassifier.warningDetected.
{
        //this.numberInstances++;
        int trueClass = (int) inst.classValue();
        boolean prediction;
        if (Utils.maxIndex(this.classifier.getVotesForInstance(inst)) == trueClass) {
            prediction = true;
        } else {
            prediction = false;
        }
        //this.ddmLevel = this.driftDetectionMethod.computeNextVal(prediction);
        this.driftDetectionMethod.input(prediction ? 0.0 : 1.0);
        this.ddmLevel = DDM_INCONTROL_LEVEL;
        if (this.driftDetectionMethod.getChange()) {
         this.ddmLevel =  DDM_OUTCONTROL_LEVEL;
        }
        if (this.driftDetectionMethod.getWarningZone()) {
           this.ddmLevel =  DDM_WARNING_LEVEL;
        }
        switch (this.ddmLevel) {
            case DDM_WARNING_LEVEL:
                //System.out.println("1 0 W");
                //System.out.println("DDM_WARNING_LEVEL");
                if (newClassifierReset == true) {
                    this.warningDetected++;
                    this.newclassifier.resetLearning();
                    newClassifierReset = false;
                }
                this.newclassifier.trainOnInstance(inst);
                break;
            case DDM_OUTCONTROL_LEVEL:
                //System.out.println("0 1 O");
                //System.out.println("DDM_OUTCONTROL_LEVEL");
                this.changeDetected++;
                this.classifier = null;
                this.classifier = this.newclassifier;
                if (this.classifier instanceof WEKAClassifier) {
                    ((WEKAClassifier) this.classifier).buildClassifier();
                }
                this.newclassifier = ((Classifier) getPreparedClassOption(this.baseLearnerOption)).copy();
                this.newclassifier.resetLearning();
                break;
            case DDM_INCONTROL_LEVEL:
                //System.out.println("0 0 I");
                //System.out.println("DDM_INCONTROL_LEVEL");
                newClassifierReset = true;
                break;
            default:
            //System.out.println("ERROR!");
        }
        this.classifier.trainOnInstance(inst);
    }
Member Data Documentation
ClassOption moa.classifiers.drift.DriftDetectionMethodClassifier.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Definition at line 55 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
int moa.classifiers.drift.DriftDetectionMethodClassifier.changeDetected = 0 [protected]
Definition at line 96 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.getModelMeasurementsImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
Classifier moa.classifiers.drift.DriftDetectionMethodClassifier.classifier [protected]
Definition at line 61 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.getModelDescription(), moa.classifiers.drift.DriftDetectionMethodClassifier.getModelMeasurementsImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.getVotesForInstance(), moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
final int moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_INCONTROL_LEVEL = 0 [static]
Definition at line 80 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
final int moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_OUTCONTROL_LEVEL = 2 [static]
Definition at line 84 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
final int moa.classifiers.drift.DriftDetectionMethodClassifier.DDM_WARNING_LEVEL = 1 [static]
Definition at line 82 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
int moa.classifiers.drift.DriftDetectionMethodClassifier.ddmLevel [protected]
Definition at line 70 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
ChangeDetector moa.classifiers.drift.DriftDetectionMethodClassifier.driftDetectionMethod [protected]
Definition at line 65 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
ClassOption moa.classifiers.drift.DriftDetectionMethodClassifier.driftDetectionMethodOption
Initial value:
 new ClassOption("driftDetectionMethod", 'd',
             "Drift detection method to use.", ChangeDetector.class, "DDM")
Definition at line 58 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl().
Classifier moa.classifiers.drift.DriftDetectionMethodClassifier.newclassifier [protected]
Definition at line 63 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
boolean moa.classifiers.drift.DriftDetectionMethodClassifier.newClassifierReset [protected]
Definition at line 67 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
final long moa.classifiers.drift.DriftDetectionMethodClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 48 of file DriftDetectionMethodClassifier.java.
int moa.classifiers.drift.DriftDetectionMethodClassifier.warningDetected = 0 [protected]
Definition at line 98 of file DriftDetectionMethodClassifier.java.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.getModelMeasurementsImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/drift/DriftDetectionMethodClassifier.java