MOA: moa.classifiers.meta.OzaBoost Class Reference
moa.classifiers.meta.OzaBoost Class Reference
Incremental on-line boosting of Oza and Russell.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
FlagOption pureBoostOption
Protected Member Functions
double getEnsembleMemberWeight (int i)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
double[] scms
double[] swms
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Incremental on-line boosting of Oza and Russell.
See details in:
N. Oza and S. Russell. Online bagging and boosting. In Artiﬁcial Intelligence and Statistics 2001, pages 105–112. Morgan Kaufmann, 2001.
For the boosting method, Oza and Russell note that the weighting procedure of AdaBoost actually divides the total example weight into two halves – half of the weight is assigned to the correctly classiﬁed examples, and the other half goes to the misclassiﬁed examples. They use the Poisson distribution for deciding the random probability that an example is used for training, only this time the parameter changes according to the boosting weight of the example as it is passed through each model in sequence.
Parameters:
-l : Classiﬁer to train
-s : The number of models to boost
-p : Boost with weights only; no poisson
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 54 of file OzaBoost.java.
Member Function Documentation
double moa.classifiers.meta.OzaBoost.getEnsembleMemberWeight (int i) [protected]
Definition at line 110 of file OzaBoost.java.
References moa.classifiers.meta.OzaBoost.scms, and moa.classifiers.meta.OzaBoost.swms.
Referenced by moa.classifiers.meta.OzaBoost.getVotesForInstance().
{
        double em = this.swms[i] / (this.scms[i] + this.swms[i]);
        if ((em == 0.0) || (em > 0.5)) {
            return 0.0;
        }
        double Bm = em / (1.0 - em);
        return Math.log(1.0 / Bm);
    }
void moa.classifiers.meta.OzaBoost.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 142 of file OzaBoost.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.OzaBoost.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 147 of file OzaBoost.java.
References moa.classifiers.meta.OzaBoost.ensemble.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0)};
    }
String moa.classifiers.meta.OzaBoost.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 59 of file OzaBoost.java.
{
        return "Incremental on-line boosting of Oza and Russell.";
    }
Classifier [] moa.classifiers.meta.OzaBoost.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 153 of file OzaBoost.java.
References moa.classifiers.meta.OzaBoost.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.OzaBoost.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 119 of file OzaBoost.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.OzaBoost.ensemble, moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.OzaBoost.getEnsembleMemberWeight(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), and moa.core.DoubleVector.sumOfValues().
{
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            double memberWeight = getEnsembleMemberWeight(i);
            if (memberWeight > 0.0) {
                DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
                if (vote.sumOfValues() > 0.0) {
                    vote.normalize();
                    vote.scaleValues(memberWeight);
                    combinedVote.addValues(vote);
                }
            } else {
                break;
            }
        }
        return combinedVote.getArrayRef();
    }
boolean moa.classifiers.meta.OzaBoost.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 137 of file OzaBoost.java.
{
        return true;
    }
void moa.classifiers.meta.OzaBoost.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 79 of file OzaBoost.java.
References moa.classifiers.meta.OzaBoost.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.OzaBoost.ensemble, moa.classifiers.meta.OzaBoost.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OzaBoost.scms, and moa.classifiers.meta.OzaBoost.swms.
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
        this.scms = new double[this.ensemble.length];
        this.swms = new double[this.ensemble.length];
    }
void moa.classifiers.meta.OzaBoost.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 91 of file OzaBoost.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.AbstractClassifier.correctlyClassifies(), moa.classifiers.meta.OzaBoost.ensemble, moa.options.FlagOption.isSet, moa.classifiers.meta.OzaBoost.pureBoostOption, moa.classifiers.meta.OzaBoost.scms, moa.classifiers.meta.OzaBoost.swms, moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.Classifier.trainOnInstance().
{
        double lambda_d = 1.0;
        for (int i = 0; i < this.ensemble.length; i++) {
            double k = this.pureBoostOption.isSet() ? lambda_d : MiscUtils.poisson(lambda_d, this.classifierRandom);
            if (k > 0.0) {
                Instance weightedInst = (Instance) inst.copy();
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
            if (this.ensemble[i].correctlyClassifies(inst)) {
                this.scms[i] += lambda_d;
                lambda_d *= this.trainingWeightSeenByModel / (2 * this.scms[i]);
            } else {
                this.swms[i] += lambda_d;
                lambda_d *= this.trainingWeightSeenByModel / (2 * this.swms[i]);
            }
        }
    }
Member Data Documentation
ClassOption moa.classifiers.meta.OzaBoost.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 63 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.resetLearningImpl().
Classifier [] moa.classifiers.meta.OzaBoost.ensemble [protected]
Definition at line 72 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.getModelMeasurementsImpl(), moa.classifiers.meta.OzaBoost.getSubClassifiers(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), and moa.classifiers.meta.OzaBoost.trainOnInstanceImpl().
IntOption moa.classifiers.meta.OzaBoost.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models to boost.", 10, 1, Integer.MAX_VALUE)
Definition at line 66 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.resetLearningImpl().
FlagOption moa.classifiers.meta.OzaBoost.pureBoostOption
Initial value:
 new FlagOption("pureBoost", 'p',
            "Boost with weights only; no poisson.")
Definition at line 69 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.trainOnInstanceImpl().
double [] moa.classifiers.meta.OzaBoost.scms [protected]
Definition at line 74 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.getEnsembleMemberWeight(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), and moa.classifiers.meta.OzaBoost.trainOnInstanceImpl().
final long moa.classifiers.meta.OzaBoost.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 56 of file OzaBoost.java.
double [] moa.classifiers.meta.OzaBoost.swms [protected]
Definition at line 76 of file OzaBoost.java.
Referenced by moa.classifiers.meta.OzaBoost.getEnsembleMemberWeight(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), and moa.classifiers.meta.OzaBoost.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/OzaBoost.java