MOA: weka.classifiers.meta.MOA Class Reference
weka.classifiers.meta.MOA Class Reference
Wrapper for MOA classifiers.
Public Member Functions
String globalInfo ()
Returns a string describing the classifier.
Enumeration listOptions ()
Returns an enumeration describing the available options.
void setOptions (String[] options) throws Exception
Parses a given list of options.
String[] getOptions ()
Gets the current settings of the Classifier.
void setClassifier (ClassOption value)
Sets the MOA classifier to use.
ClassOption getClassifier ()
Returns the current MOA classifier in use.
String classifierTipText ()
Returns the tooltip displayed in the GUI.
Capabilities getCapabilities ()
Returns the Capabilities of this classifier.
void buildClassifier (Instances data) throws Exception
Generates a classifier.
void updateClassifier (Instance instance) throws Exception
Updates a classifier using the given instance.
double[] distributionForInstance (Instance instance) throws Exception
Predicts the class memberships for a given instance.
String getRevision ()
Returns the revision string.
String toString ()
Returns a string representation of the model.
Static Public Member Functions
static void main (String[] args)
Main method for testing this class.
Protected Attributes
Classifier m_ActualClassifier = new DecisionStump()
the actual moa classifier to use for learning.
ClassOption m_Classifier
the moa classifier option (this object is used in the GenericObjectEditor).
Static Private Attributes
static final long serialVersionUID = 2605797948130310166L
for serialization.
Detailed Description
Wrapper for MOA classifiers.
Since MOA doesn't offer a mechanism to query a classifier for the types of attributes and classes it can handle, the capabilities of this wrapper are hard-coded: nominal and numeric attributes and only nominal class attributes are allowed.
Valid options are:
 -B <classname + options>
  The MOA classifier to use.
  (default: moa.classifiers.DecisionStump)
 -D
  If set, classifier is run in debug mode and
  may output additional info to the console
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 65 of file MOA.java.
Member Function Documentation
void weka.classifiers.meta.MOA.buildClassifier (Instances data) throws Exception
Generates a classifier.
Parameters:
data set of instances serving as training data
Exceptions:
Exception if the classifier has not been generated successfully
Definition at line 231 of file MOA.java.
References weka.classifiers.meta.MOA.getCapabilities(), weka.classifiers.meta.MOA.m_ActualClassifier, moa.classifiers.Classifier.resetLearning(), and weka.classifiers.meta.MOA.updateClassifier().
{
    getCapabilities().testWithFail(data);
    data = new Instances(data);
    data.deleteWithMissingClass();
    m_ActualClassifier.resetLearning();
    for (int i = 0; i < data.numInstances(); i++)
        updateClassifier(data.instance(i));
  }
String weka.classifiers.meta.MOA.classifierTipText ()
Returns the tooltip displayed in the GUI.
Returns:
the tooltip
Definition at line 196 of file MOA.java.
{
    return "The MOA classifier to use.";
  }
double [] weka.classifiers.meta.MOA.distributionForInstance (Instance instance) throws Exception
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero. If the class is numeric, the array must consist of only one element, which contains the predicted value.
Parameters:
instance the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class or the numeric prediction
Exceptions:
Exception if distribution could not be computed successfully
Definition at line 267 of file MOA.java.
References moa.classifiers.Classifier.getVotesForInstance(), and weka.classifiers.meta.MOA.m_ActualClassifier.
{
    double[]    result;
    result = m_ActualClassifier.getVotesForInstance(instance);
        // ensure that the array has as many elements as there are
        // class values!
        if (result.length < instance.numClasses()) {
          double[] newResult = new double[instance.numClasses()];
          System.arraycopy(result, 0, newResult, 0, result.length);
          result = newResult;
        }
    try {
        Utils.normalize(result);
    }
    catch (Exception e) {
        result = new double[instance.numClasses()];
    }
    return result;
  }
Capabilities weka.classifiers.meta.MOA.getCapabilities ()
Returns the Capabilities of this classifier.
Maximally permissive capabilities are allowed by default. MOA doesn't specify what
Returns:
the capabilities of this object
See also:
Capabilities
Definition at line 207 of file MOA.java.
Referenced by weka.classifiers.meta.MOA.buildClassifier().
{
    Capabilities result = new Capabilities(this);
    // attributes
    result.enable(Capability.NOMINAL_ATTRIBUTES);
    result.enable(Capability.NUMERIC_ATTRIBUTES);
    result.enable(Capability.MISSING_VALUES);
    // class
    result.enable(Capability.NOMINAL_CLASS);
    result.enable(Capability.MISSING_CLASS_VALUES);
    result.setMinimumNumberInstances(0);
    return result;
  }
ClassOption weka.classifiers.meta.MOA.getClassifier ()
Returns the current MOA classifier in use.
Returns:
the classifier in use
Definition at line 187 of file MOA.java.
References weka.classifiers.meta.MOA.m_Classifier.
{
    return m_Classifier;
  }
String [] weka.classifiers.meta.MOA.getOptions ()
Gets the current settings of the Classifier.
Returns:
an array of strings suitable for passing to setOptions
Definition at line 155 of file MOA.java.
References weka.classifiers.meta.MOA.m_ActualClassifier.
{
    Vector<String>  result;
    String[]        options;
    int             i;
    result = new Vector<String>();
    result.add("-B");
    result.add(MOAUtils.toCommandLine(m_ActualClassifier));
    options = super.getOptions();
    for (i = 0; i < options.length; i++)
      result.add(options[i]);
    return result.toArray(new String[result.size()]);
  }
String weka.classifiers.meta.MOA.getRevision ()
Returns the revision string.
Returns:
the revision
Definition at line 294 of file MOA.java.
{
    return RevisionUtils.extract("$Revision$");
  }
String weka.classifiers.meta.MOA.globalInfo ()
Returns a string describing the classifier.
Returns:
a description suitable for displaying in the explorer/experimenter gui
Definition at line 87 of file MOA.java.
{
    return
        "Wrapper for MOA classifiers.\n\n"
      + "Since MOA doesn't offer a mechanism to query a classifier for the "
      + "types of attributes and classes it can handle, the capabilities of "
      + "this wrapper are hard-coded: nominal and numeric attributes and "
      + "only nominal class attributes are allowed.";
  }
Enumeration weka.classifiers.meta.MOA.listOptions ()
Returns an enumeration describing the available options.
Returns:
an enumeration of all the available options.
Definition at line 101 of file MOA.java.
{
    Vector result = new Vector();
    result.addElement(new Option(
        "\tThe MOA classifier to use.\n"
        + "\t(default: " + MOAUtils.toCommandLine(new DecisionStump()) + ")",
        "B", 1, "-B <classname + options>"));
    Enumeration en = super.listOptions();
    while (en.hasMoreElements())
      result.addElement(en.nextElement());
    return result.elements();
  }
static void weka.classifiers.meta.MOA.main (String[] args) [static]
Main method for testing this class.
Parameters:
args the options
Definition at line 317 of file MOA.java.
{
    runClassifier(new MOA(), args);
  }
void weka.classifiers.meta.MOA.setClassifier (ClassOption value)
Sets the MOA classifier to use.
Parameters:
value the classifier to use
Definition at line 177 of file MOA.java.
References weka.classifiers.meta.MOA.m_ActualClassifier, and weka.classifiers.meta.MOA.m_Classifier.
Referenced by weka.classifiers.meta.MOA.setOptions().
{
    m_Classifier       = value;
    m_ActualClassifier = (Classifier) MOAUtils.fromOption(m_Classifier);
  }
void weka.classifiers.meta.MOA.setOptions (String[] options) throws Exception
Parses a given list of options.
Valid options are:
 -B <classname + options>
  The MOA classifier to use.
  (default: moa.classifiers.trees.DecisionStump)
 -D
  If set, classifier is run in debug mode and
  may output additional info to the console
Parameters:
options the list of options as an array of strings
Exceptions:
Exception if an option is not supported
Definition at line 135 of file MOA.java.
References moa.options.AbstractOption.copy(), weka.classifiers.meta.MOA.m_Classifier, weka.classifiers.meta.MOA.setClassifier(), and moa.options.AbstractClassOption.setCurrentObject().
{
    String                  tmpStr;
    ClassOption                 option;
    tmpStr = Utils.getOption('B', options);
    option = (ClassOption) m_Classifier.copy();
    if (tmpStr.length() == 0)
        option.setCurrentObject(new DecisionStump());
    else
        option.setCurrentObject(MOAUtils.fromCommandLine(m_Classifier, tmpStr));
    setClassifier(option);
    super.setOptions(options);
  }
String weka.classifiers.meta.MOA.toString ()
Returns a string representation of the model.
Returns:
the string representation
Definition at line 303 of file MOA.java.
References moa.MOAObject.getDescription(), and weka.classifiers.meta.MOA.m_ActualClassifier.
{
    StringBuilder       result;
    result = new StringBuilder();
    m_ActualClassifier.getDescription(result, 0);
    return result.toString();
  }
void weka.classifiers.meta.MOA.updateClassifier (Instance instance) throws Exception
Updates a classifier using the given instance.
Parameters:
instance the instance to included
Exceptions:
Exception if instance could not be incorporated successfully
Definition at line 249 of file MOA.java.
References weka.classifiers.meta.MOA.m_ActualClassifier, and moa.classifiers.Classifier.trainOnInstance().
Referenced by weka.classifiers.meta.MOA.buildClassifier().
{
        m_ActualClassifier.trainOnInstance(instance);
  }
Member Data Documentation
Classifier weka.classifiers.meta.MOA.m_ActualClassifier = new DecisionStump() [protected]
the actual moa classifier to use for learning.
Definition at line 73 of file MOA.java.
Referenced by weka.classifiers.meta.MOA.buildClassifier(), weka.classifiers.meta.MOA.distributionForInstance(), weka.classifiers.meta.MOA.getOptions(), weka.classifiers.meta.MOA.setClassifier(), weka.classifiers.meta.MOA.toString(), and weka.classifiers.meta.MOA.updateClassifier().
ClassOption weka.classifiers.meta.MOA.m_Classifier [protected]
Initial value:
 new ClassOption(
            "classifier", 'B', "The MOA classifier to use from within WEKA.",
            Classifier.class, m_ActualClassifier.getClass().getName().replace("moa.classifiers.", ""),
            m_ActualClassifier.getClass().getName())
the moa classifier option (this object is used in the GenericObjectEditor).
Definition at line 76 of file MOA.java.
Referenced by weka.classifiers.meta.MOA.getClassifier(), weka.classifiers.meta.MOA.setClassifier(), and weka.classifiers.meta.MOA.setOptions().
final long weka.classifiers.meta.MOA.serialVersionUID = 2605797948130310166L [static, private]
for serialization.
Definition at line 70 of file MOA.java.
The documentation for this class was generated from the following file:
main/java/weka/classifiers/meta/MOA.java