MOA: moa.clusterers.outliers.AnyOut.util.DataSet Class Reference
moa.clusterers.outliers.AnyOut.util.DataSet Class Reference
A set of DataObjects.
Public Member Functions
DataSet (int nrOfDimensions)
Creates an empty set.
DataSet (DataObject newData)
Creates a Set with only the given object.
void addObject (DataObject newData)
Adds a DataObject to the set.
void addObject (DataSet dataSet) throws Exception
Adds all objects in the given data set.
DataObject getObject (int index)
Returns the DataObject at the given position.
int size ()
Returns the size of the set.
int getNrOfDimensions ()
Return the dimension of the objects in the DataSet.
int getNrOfClasses ()
Counts the number of classes that are present in the data set.
double[][] getFeaturesAsArray ()
Returns an array with all the features of all the objects in the set.
DataObject[] getDataObjectArray ()
Returns an array of all the DataObjects in the set.
DataSet[] getDataSetsPerClass () throws Exception
Separates the objects in this data set according to their class label.
double[] getVariances ()
Calculates the variance of this data set for each dimension.
Iterator< DataObject > iterator ()
An iterator for the set.
String toString ()
Returns a String representation of all the DataObjects in the code as a list of the representation implemented for these.
void manipulateIds ()
resets the ids, so that the set contains ids from 0 to noOfObjects-1
void clear ()
Private Attributes
int nrOfDimensions
ArrayList< DataObject > dataList
Detailed Description
A set of DataObjects.
Internally it uses an ArrayList<DataObject> so it is recommended to use with care. For speedy operations after the data is collected use getFeaturesAsArray(). When access speed is not a factor the iterator can be used to go through the data with a foreach loop.
Author:
Fernando Sanchez Villaamil
See also:
getFeaturesAsArray()
Definition at line 38 of file DataSet.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.AnyOut.util.DataSet.DataSet (int nrOfDimensions)
Creates an empty set.
Parameters:
nrOfDimensions The dimension the DataObjects should have.
See also:
DataObject
Exceptions:
praktikum.framework.data.InconsistentDimensionException
Definition at line 49 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass().
{
        if (nrOfDimensions <= 0) {
            System.err.println("Negative dimension given: " + nrOfDimensions);
        } else {
            this.nrOfDimensions = nrOfDimensions;
            dataList = new ArrayList<DataObject>();
        }
    }
moa.clusterers.outliers.AnyOut.util.DataSet.DataSet (DataObject newData)
Creates a Set with only the given object.
The dimension for the DataSet is given by the given DataObject.
Parameters:
newData The first DataObject added to the set.
See also:
DataObject
Exceptions:
praktikum.framework.data.InconsistentDimensionException
Definition at line 65 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList, moa.clusterers.outliers.AnyOut.util.DataObject.getNrOfDimensions(), and moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions.
{
        this.nrOfDimensions = newData.getNrOfDimensions();
        dataList = new ArrayList<DataObject>();
        dataList.add(newData);
    }
Member Function Documentation
void moa.clusterers.outliers.AnyOut.util.DataSet.addObject (DataSet dataSet) throws Exception
Adds all objects in the given data set.
See also:
addObject(DataObject newData)
Parameters:
dataSet
Exceptions:
InconsistentDimensionException
Definition at line 95 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.addObject().
{
        DataObject[] dataObjects = dataSet.getDataObjectArray();
        for (int i = 0; i < dataObjects.length; i++) {
            this.addObject(dataObjects[i]);
        }
    }
void moa.clusterers.outliers.AnyOut.util.DataSet.addObject (DataObject newData)
Adds a DataObject to the set.
Parameters:
newData The DataObject to be added.
Exceptions:
praktikum.framework.data.InconsistentDimensionException This Exception is thrown when the dimension of the object to be added does not fit the rest.
See also:
DataObject
Exceptions:
praktikum.framework.data.InconsistentDimensionException
Definition at line 80 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList, moa.clusterers.outliers.AnyOut.util.DataObject.getNrOfDimensions(), and moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass(), moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.mergeDataSets(), moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj(), moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingEM(), and moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingMeanShift().
{
        if (newData.getNrOfDimensions() != nrOfDimensions) {
            System.err.println("Inconsistent number of dimensions!"); //(this.nrOfDimensions, newData.getNrOfDimensions());
        } else {
            this.dataList.add(newData);
        }
    }
void moa.clusterers.outliers.AnyOut.util.DataSet.clear ()
Definition at line 265 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
{
        dataList.clear();
    }
DataObject [] moa.clusterers.outliers.AnyOut.util.DataSet.getDataObjectArray ()
Returns an array of all the DataObjects in the set.
Use for speedy access when the labels and/or the ids are also needed.
Returns:
An array with all the DataObjects in the set.
See also:
DataObject
Definition at line 174 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingMeanShift(), and moa.clusterers.outliers.AnyOut.AnyOutCore.train().
{
        DataObject[] res = new DataObject[this.dataList.size()];
        return this.dataList.toArray(res);
    }
DataSet [] moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass () throws Exception
Separates the objects in this data set according to their class label.
Returns:
an array of DataSets, one for each class
Definition at line 183 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), moa.clusterers.outliers.AnyOut.util.DataSet.dataList, moa.clusterers.outliers.AnyOut.util.DataSet.DataSet(), moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfClasses(), and moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions.
{
        DataSet[] dataSetsPerClass = new DataSet[this.getNrOfClasses()];
        // create a new data set for each class
        for (int i = 0; i < dataSetsPerClass.length; i++) {
            dataSetsPerClass[i] = new DataSet(this.nrOfDimensions);
        }
        // fill the data sets
        for(DataObject currentObject : dataList) {
            dataSetsPerClass[currentObject.getClassLabel()].addObject(currentObject);
        }
        return dataSetsPerClass;
    }
double [][] moa.clusterers.outliers.AnyOut.util.DataSet.getFeaturesAsArray ()
Returns an array with all the features of all the objects in the set.
Be aware that it does not copy the features so that any changes to the values of the features in this array will result in changes in the initial DataObjects.
Returns:
A double[][] with the features. The first dimension is the feature number, the second the values in the feature.
See also:
DataObject
Definition at line 155 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList, moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions, and moa.clusterers.outliers.AnyOut.util.DataSet.size().
{
        double[][] data = new double[this.size()][this.nrOfDimensions];
        int c = 0;
        for (DataObject d : dataList) {
            data[c] = d.getFeatures();
            c++;
        }
        return data;
    }
int moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfClasses ()
Counts the number of classes that are present in the data set.
!!! It does not check whether all classes are contained !!!
Returns:
the number of distinct class labels
Definition at line 136 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass().
{
        HashMap<Integer, Integer> classes = new HashMap<Integer, Integer>();
        for (DataObject currentObject : dataList) {
            if (!classes.containsKey(currentObject.getClassLabel()))
                classes.put(currentObject.getClassLabel(), 1);
        }
        return classes.size();
    }
int moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfDimensions ()
Return the dimension of the objects in the DataSet.
The DataSet makes sure all objects have the same dimension.
Returns:
The dimension of the DataObjects in the DataSet.
See also:
DataObject
Definition at line 127 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.getVariances(), moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.mergeDataSets(), and moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingMeanShift().
{
        return nrOfDimensions;
    }
DataObject moa.clusterers.outliers.AnyOut.util.DataSet.getObject (int index)
Returns the DataObject at the given position.
Use with care. For speedy operations after the data is collected use getFeaturesAsArray().
Parameters:
index The index position that is to be returned.
Returns:
The DataObeject at the given position.
See also:
DataObject
Definition at line 109 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.mergeDataSets().
{
        return dataList.get(index);
    }
double [] moa.clusterers.outliers.AnyOut.util.DataSet.getVariances ()
Calculates the variance of this data set for each dimension.
Returns:
double array containing the variance per dimension
Definition at line 202 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList, moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfDimensions(), and moa.clusterers.outliers.AnyOut.util.DataSet.size().
{
        double N = this.size();
        double[] LS = new double[this.getNrOfDimensions()];
        double[] SS = new double[this.getNrOfDimensions()];
        double[] tmpFeatures;
        double[] variances = new double[this.getNrOfDimensions()];
        for (DataObject dataObject : dataList) {
            tmpFeatures = dataObject.getFeatures();
            for (int j = 0; j < tmpFeatures.length; j++) {
                LS[j] += tmpFeatures[j];
                SS[j] += tmpFeatures[j] * tmpFeatures[j];
            }
        }
        // sigmaSquared[i] = (SS[i] / N) - ((LS[i] * LS [i]) / (N * N));
        for (int i = 0; i < LS.length; i++) {
            variances[i] = (SS[i] / N - ((LS[i] / N)*(LS[i] / N)));
        }
        return variances;
    }
Iterator<DataObject> moa.clusterers.outliers.AnyOut.util.DataSet.iterator ()
An iterator for the set.
This allows to use a foreach loop over the DataObjects. This is a nice way of going through the data, but when the access speed is relevant its use is not recommended.
Returns:
An iterator for the set.
See also:
DataObject
Definition at line 232 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
{
        return this.dataList.iterator();
    }
void moa.clusterers.outliers.AnyOut.util.DataSet.manipulateIds ()
resets the ids, so that the set contains ids from 0 to noOfObjects-1
Definition at line 256 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
{
        int id = 0;
        for (DataObject o : dataList){
            o.setId(id);
            id++;
        }
    }
int moa.clusterers.outliers.AnyOut.util.DataSet.size ()
Returns the size of the set.
Returns:
The size of the set.
Definition at line 117 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.getFeaturesAsArray(), moa.clusterers.outliers.AnyOut.util.DataSet.getVariances(), moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.mergeDataSets(), and moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingMeanShift().
                      {
        return this.dataList.size();
    }
String moa.clusterers.outliers.AnyOut.util.DataSet.toString ()
Returns a String representation of all the DataObjects in the code as a list of the representation implemented for these.
Returns:
A String representation of all the elements in the set.
See also:
DataObject
Definition at line 243 of file DataSet.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.dataList.
{
        String res = "";
        for (DataObject dataObject : dataList) {
            res += dataObject.toString() + "\n";
        }
        return res;
    }
Member Data Documentation
ArrayList<DataObject> moa.clusterers.outliers.AnyOut.util.DataSet.dataList [private]
Definition at line 41 of file DataSet.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), moa.clusterers.outliers.AnyOut.util.DataSet.clear(), moa.clusterers.outliers.AnyOut.util.DataSet.DataSet(), moa.clusterers.outliers.AnyOut.util.DataSet.getDataObjectArray(), moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass(), moa.clusterers.outliers.AnyOut.util.DataSet.getFeaturesAsArray(), moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfClasses(), moa.clusterers.outliers.AnyOut.util.DataSet.getObject(), moa.clusterers.outliers.AnyOut.util.DataSet.getVariances(), moa.clusterers.outliers.AnyOut.util.DataSet.iterator(), moa.clusterers.outliers.AnyOut.util.DataSet.manipulateIds(), moa.clusterers.outliers.AnyOut.util.DataSet.size(), and moa.clusterers.outliers.AnyOut.util.DataSet.toString().
int moa.clusterers.outliers.AnyOut.util.DataSet.nrOfDimensions [private]
Definition at line 40 of file DataSet.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), moa.clusterers.outliers.AnyOut.util.DataSet.DataSet(), moa.clusterers.outliers.AnyOut.util.DataSet.getDataSetsPerClass(), moa.clusterers.outliers.AnyOut.util.DataSet.getFeaturesAsArray(), and moa.clusterers.outliers.AnyOut.util.DataSet.getNrOfDimensions().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AnyOut/util/DataSet.java