MOA: moa.classifiers.lazy.kNN Class Reference
moa.classifiers.lazy.kNN Class Reference
k Nearest Neighbor.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void setModelContext (InstancesHeader context)
Sets the reference to the header of the data stream.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
IntOption kOption = new IntOption("k", 'k', "The number of neighbors", 10, 1, Integer.MAX_VALUE)
IntOption limitOption = new IntOption("limit", 'w', "The maximum number of instances to store", 1000, 1, Integer.MAX_VALUE)
MultiChoiceOption nearestNeighbourSearchOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Instances window
Package Attributes
int C = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
k Nearest Neighbor.
Valid options are:
-k number of neighbours
-m max instances
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
03.2012
Definition at line 42 of file kNN.java.
Member Function Documentation
void moa.classifiers.lazy.kNN.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 129 of file kNN.java.
{
    }
Measurement [] moa.classifiers.lazy.kNN.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 124 of file kNN.java.
{
        return null;
    }
String moa.classifiers.lazy.kNN.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 61 of file kNN.java.
{
        return "kNN: special.";
    }
double [] moa.classifiers.lazy.kNN.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 98 of file kNN.java.
References moa.classifiers.lazy.kNN.C, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.IntOption.getValue(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.kNearestNeighbours(), moa.classifiers.lazy.kNN.kOption, moa.classifiers.lazy.kNN.nearestNeighbourSearchOption, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.setInstances(), and moa.classifiers.lazy.kNN.window.
{
        double v[] = new double[C+1];
        try {
            NearestNeighbourSearch search;
            if (this.nearestNeighbourSearchOption.getChosenIndex()== 0) {
                search = new LinearNNSearch(this.window);
            } else {
                search = new KDTree();
                search.setInstances(this.window);
            }
            if (this.window.numInstances()>0) {
                Instances neighbours = search.kNearestNeighbours(inst,Math.min(kOption.getValue(),this.window.numInstances()));
                for(int i = 0; i < neighbours.numInstances(); i++) {
                    v[(int)neighbours.instance(i).classValue()]++;
                }
            }
        } catch(Exception e) {
            //System.err.println("Error: kNN search failed.");
            //e.printStackTrace();
            //System.exit(1);
            return new double[inst.numClasses()];
        }
        return v;
    }
boolean moa.classifiers.lazy.kNN.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 132 of file kNN.java.
{
        return false;
    }
void moa.classifiers.lazy.kNN.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 80 of file kNN.java.
References moa.classifiers.lazy.kNN.window.
{
        this.window = null;
    }
void moa.classifiers.lazy.kNN.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 68 of file kNN.java.
References moa.classifiers.lazy.kNN.window.
{
        try {
            this.window = new Instances(new StringReader(context.toString()),0);
            this.window.setClassIndex(context.classIndex());
        } catch(Exception e) {
            System.err.println("Error: no Model Context available.");
            e.printStackTrace();
            System.exit(1);
        }
    }
void moa.classifiers.lazy.kNN.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 85 of file kNN.java.
References moa.classifiers.lazy.kNN.C, moa.options.IntOption.getValue(), moa.classifiers.lazy.kNN.limitOption, and moa.classifiers.lazy.kNN.window.
{
        if (inst.classValue() > C)
            C = (int)inst.classValue();
        if (this.window == null) {
            this.window = new Instances(inst.dataset());
        }
        if (this.limitOption.getValue() <= this.window.numInstances()) {
            this.window.delete(0);
        }
        this.window.add(inst);
    }
Member Data Documentation
int moa.classifiers.lazy.kNN.C = 0 [package]
Definition at line 58 of file kNN.java.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance(), moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl(), moa.classifiers.lazy.kNNwithPAW.trainOnInstanceImpl(), and moa.classifiers.lazy.kNN.trainOnInstanceImpl().
IntOption moa.classifiers.lazy.kNN.kOption = new IntOption("k", 'k', "The number of neighbors", 10, 1, Integer.MAX_VALUE)
Definition at line 46 of file kNN.java.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance().
IntOption moa.classifiers.lazy.kNN.limitOption = new IntOption("limit", 'w', "The maximum number of instances to store", 1000, 1, Integer.MAX_VALUE)
Definition at line 48 of file kNN.java.
Referenced by moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), moa.classifiers.lazy.kNNwithPAW.resetLearningImpl(), and moa.classifiers.lazy.kNN.trainOnInstanceImpl().
MultiChoiceOption moa.classifiers.lazy.kNN.nearestNeighbourSearchOption
Initial value:
 new MultiChoiceOption(
            "nearestNeighbourSearch", 'n', "Nearest Neighbour Search to use", new String[]{
                "LinearNN", "KDTree"},
            new String[]{"Brute force search algorithm for nearest neighbour search. ",
                "KDTree search algorithm for nearest neighbour search"
            }, 0)
Definition at line 50 of file kNN.java.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance().
final long moa.classifiers.lazy.kNN.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.lazy.kNNwithPAW, and moa.classifiers.lazy.kNNwithPAWandADWIN.
Definition at line 44 of file kNN.java.
Instances moa.classifiers.lazy.kNN.window [protected]
Definition at line 65 of file kNN.java.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance(), moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), moa.classifiers.lazy.kNNwithPAW.resetLearningImpl(), moa.classifiers.lazy.kNN.resetLearningImpl(), moa.classifiers.lazy.kNN.setModelContext(), moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl(), moa.classifiers.lazy.kNNwithPAW.trainOnInstanceImpl(), and moa.classifiers.lazy.kNN.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/kNN.java