MOA: weka.core.MOAUtils Class Reference
weka.core.MOAUtils Class Reference
A helper class for MOA related classes.
Static Public Member Functions
static MOAObject fromCommandLine (ClassOption option, String commandline)
Turns a commandline into an object (classname + optional options).
static MOAObject fromCommandLine (Class requiredType, String commandline)
Turns a commandline into an object (classname + optional options).
static MOAObject fromOption (ClassOption option)
Creates a MOA object from the specified class option.
static String toCommandLine (MOAObject obj)
Returs the commandline for the given object.
Detailed Description
A helper class for MOA related classes.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 34 of file MOAUtils.java.
Member Function Documentation
static MOAObject weka.core.MOAUtils.fromCommandLine (Class requiredType, String commandline) [static]
Turns a commandline into an object (classname + optional options).
Parameters:
requiredType the required class
commandline the commandline to turn into an object
Returns:
the generated oblect
Definition at line 54 of file MOAUtils.java.
{
    MOAObject     result;
    String[]            tmpOptions;
    String              classname;
    try {
        tmpOptions    = Utils.splitOptions(commandline);
        classname     = tmpOptions[0];
        tmpOptions[0] = "";
        try {
            result = (MOAObject) Class.forName(classname).newInstance();
        }
        catch (Exception e) {
            // try to prepend package name
            result = (MOAObject) Class.forName(requiredType.getPackage().getName() + "." + classname).newInstance();
        }
        if (result instanceof AbstractOptionHandler) {
            ((AbstractOptionHandler) result).getOptions().setViaCLIString(Utils.joinOptions(tmpOptions));
            ((AbstractOptionHandler) result).prepareForUse();
        }
    }
    catch (Exception e) {
        e.printStackTrace();
        result = null;
    }
    return result;
  }
static MOAObject weka.core.MOAUtils.fromCommandLine (ClassOption option, String commandline) [static]
Turns a commandline into an object (classname + optional options).
Parameters:
option the corresponding class option
commandline the commandline to turn into an object
Returns:
the generated oblect
Definition at line 43 of file MOAUtils.java.
References moa.options.AbstractClassOption.getRequiredType().
{
    return fromCommandLine(option.getRequiredType(), commandline);
  }
static MOAObject weka.core.MOAUtils.fromOption (ClassOption option) [static]
Creates a MOA object from the specified class option.
Parameters:
option the option to build the object from
Returns:
the created object
Definition at line 89 of file MOAUtils.java.
References moa.options.AbstractClassOption.getRequiredType(), and moa.options.ClassOption.getValueAsCLIString().
{
    return MOAUtils.fromCommandLine(option.getRequiredType(), option.getValueAsCLIString());
  }
static String weka.core.MOAUtils.toCommandLine (MOAObject obj) [static]
Returs the commandline for the given object.
If the object is not derived from AbstractOptionHandler, then only the classname. Otherwise the classname and the options are returned.
Parameters:
obj the object to generate the commandline for
Returns:
the commandline
Definition at line 101 of file MOAUtils.java.
{
    String result = obj.getClass().getName();
    if (obj instanceof AbstractOptionHandler)
        result += " " + ((AbstractOptionHandler) obj).getOptions().getAsCLIString();
    return result.trim();
  }
The documentation for this class was generated from the following file:
main/java/weka/core/MOAUtils.java