MOA: moa.recommender.rc.predictor.impl.BaselinePredictor Class Reference
moa.recommender.rc.predictor.impl.BaselinePredictor Class Reference
Public Member Functions
BaselinePredictor (RecommenderData data)
double predictRating (int userID, int itemID)
List< Double > predictRatings (int userID, List< Integer > itemIDS)
RecommenderData getData ()
void train ()
Protected Attributes
RecommenderData data
Static Private Attributes
static final long serialVersionUID = 8444152568941483368L
Detailed Description
Definition at line 28 of file BaselinePredictor.java.
Constructor & Destructor Documentation
moa.recommender.rc.predictor.impl.BaselinePredictor.BaselinePredictor (RecommenderData data)
Definition at line 35 of file BaselinePredictor.java.
{
        this.data = data;
    }
Member Function Documentation
RecommenderData moa.recommender.rc.predictor.impl.BaselinePredictor.getData ()
Implements moa.recommender.rc.predictor.RatingPredictor.
Definition at line 61 of file BaselinePredictor.java.
References moa.recommender.rc.predictor.impl.BaselinePredictor.data.
{
        return data;
    }
double moa.recommender.rc.predictor.impl.BaselinePredictor.predictRating (int userID, int itemID)
Implements moa.recommender.rc.predictor.RatingPredictor.
Definition at line 40 of file BaselinePredictor.java.
References moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
{
        ArrayList<Integer> itm = new ArrayList<Integer>();
        itm.add(itemID);
        return predictRatings(userID, itm).get(0);
    }
List<Double> moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings (int userID, List< Integer > itemIDS)
Implements moa.recommender.rc.predictor.RatingPredictor.
Definition at line 47 of file BaselinePredictor.java.
References moa.recommender.rc.predictor.impl.BaselinePredictor.data, moa.recommender.rc.data.RecommenderData.getAvgRatingItem(), moa.recommender.rc.data.RecommenderData.getAvgRatingUser(), moa.recommender.rc.data.RecommenderData.getGlobalMean(), moa.recommender.rc.data.RecommenderData.getMaxRating(), and moa.recommender.rc.data.RecommenderData.getMinRating().
Referenced by moa.recommender.rc.predictor.impl.BaselinePredictor.predictRating().
{
        ArrayList<Double> ret = new ArrayList<Double>(itemIDS.size());
        double avg = data.getAvgRatingUser(userID) - data.getGlobalMean();
        for (int i = 0; i < itemIDS.size(); ++i) {
            int itemID = itemIDS.get(i);
            double rat = avg + data.getAvgRatingItem(itemID);
            rat = Math.min(Math.max(rat, data.getMinRating()),
                    data.getMaxRating());
            ret.add(rat);
        }
        return ret;
    }
void moa.recommender.rc.predictor.impl.BaselinePredictor.train ()
Implements moa.recommender.rc.predictor.RatingPredictor.
Definition at line 66 of file BaselinePredictor.java.
{
    }
Member Data Documentation
RecommenderData moa.recommender.rc.predictor.impl.BaselinePredictor.data [protected]
Definition at line 33 of file BaselinePredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BaselinePredictor.getData(), and moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
final long moa.recommender.rc.predictor.impl.BaselinePredictor.serialVersionUID = 8444152568941483368L [static, private]
Definition at line 32 of file BaselinePredictor.java.
The documentation for this class was generated from the following file:
main/java/moa/recommender/rc/predictor/impl/BaselinePredictor.java