MOA: moa.classifiers.lazy.neighboursearch.LinearNNSearch Class Reference
moa.classifiers.lazy.neighboursearch.LinearNNSearch Class Reference
Class implementing the brute force search algorithm for nearest neighbour search.
Public Member Functions
LinearNNSearch ()
Constructor.
LinearNNSearch (Instances insts)
Constructor that uses the supplied set of instances.
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
String skipIdenticalTipText ()
Returns the tip text for this property.
void setSkipIdentical (boolean skip)
Sets the property to skip identical instances (with distance zero from the target) from the set of neighbours returned.
boolean getSkipIdentical ()
Gets whether if identical instances are skipped from the neighbourhood.
Instance nearestNeighbour (Instance target) throws Exception
Returns the nearest instance in the current neighbourhood to the supplied instance.
Instances kNearestNeighbours (Instance target, int kNN) throws Exception
Returns k nearest instances in the current neighbourhood to the supplied instance.
double[] getDistances () throws Exception
Returns the distances of the k nearest neighbours.
void setInstances (Instances insts) throws Exception
Sets the instances comprising the current neighbourhood.
void update (Instance ins) throws Exception
Updates the LinearNNSearch to cater for the new added instance.
void addInstanceInfo (Instance ins)
Adds the given instance info.
Protected Attributes
double[] m_Distances
Array holding the distances of the nearest neighbours.
boolean m_SkipIdentical = false
Whether to skip instances from the neighbours that are identical to the query instance.
Static Private Attributes
static final long serialVersionUID = 1915484723703917241L
for serialization.
Detailed Description
Class implementing the brute force search algorithm for nearest neighbour search.
Valid options are:
 -S
  Skip identical instances (distances equal to zero).
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 48 of file LinearNNSearch.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.LinearNNSearch.LinearNNSearch ()
Constructor.
Needs setInstances(Instances) to be called before the class is usable.
Definition at line 66 of file LinearNNSearch.java.
{
    super();
  }
moa.classifiers.lazy.neighboursearch.LinearNNSearch.LinearNNSearch (Instances insts)
Constructor that uses the supplied set of instances.
Parameters:
insts the instances to use
Definition at line 76 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, and moa.classifiers.lazy.neighboursearch.DistanceFunction.setInstances().
{
    super(insts);
    m_DistanceFunction.setInstances(insts);
  }
Member Function Documentation
void moa.classifiers.lazy.neighboursearch.LinearNNSearch.addInstanceInfo (Instance ins)
Adds the given instance info.
This implementation updates the range datastructures of the DistanceFunction class.
Parameters:
ins The instance to add the information of. Usually this is the test instance supplied to update the range of attributes in the distance function.
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 274 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.update().
{
    if(m_Instances!=null)
      try{ update(ins); }
      catch(Exception ex) { ex.printStackTrace(); }
  }
double [] moa.classifiers.lazy.neighboursearch.LinearNNSearch.getDistances () throws Exception [virtual]
Returns the distances of the k nearest neighbours.
The kNearestNeighbours or nearestNeighbour must always be called before calling this function. If this function is called before calling either the kNearestNeighbours or the nearestNeighbour, then it throws an exception. If, however, if either of the nearestNeighbour functions are called at any point in the past then no exception is thrown and the distances of the training set from the last supplied target instance (to either one of the nearestNeighbour functions) is/are returned.
Returns:
array containing the distances of the nearestNeighbours. The length and ordering of the array is the same as that of the instances returned by nearestNeighbour functions.
Exceptions:
Exception if called before calling kNearestNeighbours or nearestNeighbours.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 228 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_Distances.
{
    if(m_Distances==null)
      throw new Exception("No distances available. Please call either "+
                          "kNearestNeighbours or nearestNeighbours first.");
    return m_Distances;
  }
boolean moa.classifiers.lazy.neighboursearch.LinearNNSearch.getSkipIdentical ()
Gets whether if identical instances are skipped from the neighbourhood.
Returns:
true if identical instances are skipped
Definition at line 120 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_SkipIdentical.
{
    return m_SkipIdentical;
  }
String moa.classifiers.lazy.neighboursearch.LinearNNSearch.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 87 of file LinearNNSearch.java.
{
    return
        "Class implementing the brute force search algorithm for nearest "
      + "neighbour search.";
  }
Instances moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours (Instance target, int kNN) throws Exception [virtual]
Returns k nearest instances in the current neighbourhood to the supplied instance.
Parameters:
target The instance to find the k nearest neighbours for.
kNN The number of nearest neighbours to find.
Returns:
the k nearest neighbors
Exceptions:
Exception if the neighbours could not be found.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 146 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.distance, moa.classifiers.lazy.neighboursearch.DistanceFunction.distance(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.get(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.getKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_Distances, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_SkipIdentical, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.noOfKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.peek(), moa.classifiers.lazy.neighboursearch.DistanceFunction.postProcessDistances(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.put(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.size().
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.nearestNeighbour().
{
    //debug
    boolean print=false;
    MyHeap heap = new MyHeap(kNN);
    double distance; int firstkNN=0;
    for(int i=0; i<m_Instances.numInstances(); i++) {
      if(target == m_Instances.instance(i)) //for hold-one-out cross-validation
        continue;
      if(firstkNN<kNN) {
        if(print)
          System.out.println("K(a): "+(heap.size()+heap.noOfKthNearest()));
        distance = m_DistanceFunction.distance(target, m_Instances.instance(i), Double.POSITIVE_INFINITY);
        if(distance == 0.0 && m_SkipIdentical)
          if(i<m_Instances.numInstances()-1)
            continue;
          else
            heap.put(i, distance);
        heap.put(i, distance);
        firstkNN++;
      }
      else {
        MyHeapElement temp = heap.peek();
        if(print)
          System.out.println("K(b): "+(heap.size()+heap.noOfKthNearest()));
        distance = m_DistanceFunction.distance(target, m_Instances.instance(i), temp.distance);
        if(distance == 0.0 && m_SkipIdentical)
          continue;
        if(distance < temp.distance) {
          heap.putBySubstitute(i, distance);
        }
        else if(distance == temp.distance) {
          heap.putKthNearest(i, distance);
        }
      }
    }
    Instances neighbours = new Instances(m_Instances, (heap.size()+heap.noOfKthNearest()));
    m_Distances = new double[heap.size()+heap.noOfKthNearest()];
    int [] indices = new int[heap.size()+heap.noOfKthNearest()];
    int i=1; MyHeapElement h;
    while(heap.noOfKthNearest()>0) {
      h = heap.getKthNearest();
      indices[indices.length-i] = h.index;
      m_Distances[indices.length-i] = h.distance;
      i++;
    }
    while(heap.size()>0) {
      h = heap.get();
      indices[indices.length-i] = h.index;
      m_Distances[indices.length-i] = h.distance;
      i++;
    }
    m_DistanceFunction.postProcessDistances(m_Distances);
    for(int k=0; k<indices.length; k++) {
      neighbours.add(m_Instances.instance(indices[k]));
    }
    return neighbours;
  }
Instance moa.classifiers.lazy.neighboursearch.LinearNNSearch.nearestNeighbour (Instance target) throws Exception [virtual]
Returns the nearest instance in the current neighbourhood to the supplied instance.
Parameters:
target The instance to find the nearest neighbour for.
Returns:
the nearest instance
Exceptions:
Exception if the nearest neighbour could not be found.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 133 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours().
{
    return (kNearestNeighbours(target, 1)).instance(0);
  }
void moa.classifiers.lazy.neighboursearch.LinearNNSearch.setInstances (Instances insts) throws Exception
Sets the instances comprising the current neighbourhood.
Parameters:
insts The set of instances on which the nearest neighbour search is carried out. Usually this set is the training set.
Exceptions:
Exception if setting of instances fails
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 243 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, and moa.classifiers.lazy.neighboursearch.DistanceFunction.setInstances().
{
    m_Instances = insts;
    m_DistanceFunction.setInstances(insts);
  }
void moa.classifiers.lazy.neighboursearch.LinearNNSearch.setSkipIdentical (boolean skip)
Sets the property to skip identical instances (with distance zero from the target) from the set of neighbours returned.
Parameters:
skip if true, identical intances are skipped
Definition at line 111 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_SkipIdentical.
{
    m_SkipIdentical = skip;
  }
String moa.classifiers.lazy.neighboursearch.LinearNNSearch.skipIdenticalTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 101 of file LinearNNSearch.java.
{
    return "Whether to skip identical instances (with distance 0 to the target)";
  }
void moa.classifiers.lazy.neighboursearch.LinearNNSearch.update (Instance ins) throws Exception [virtual]
Updates the LinearNNSearch to cater for the new added instance.
This implementation only updates the ranges of the DistanceFunction class, since our set of instances is passed by reference and should already have the newly added instance.
Parameters:
ins The instance to add. Usually this is the instance that is added to our neighbourhood i.e. the training instances.
Exceptions:
Exception if the given instances are null
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 259 of file LinearNNSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, and moa.classifiers.lazy.neighboursearch.DistanceFunction.update().
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.addInstanceInfo().
{
    if(m_Instances==null)
      throw new Exception("No instances supplied yet. Cannot update without"+
                          "supplying a set of instances first.");
    m_DistanceFunction.update(ins);
  }
Member Data Documentation
double [] moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_Distances [protected]
Array holding the distances of the nearest neighbours.
It is filled up both by nearestNeighbour() and kNearestNeighbours().
Definition at line 57 of file LinearNNSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.getDistances(), and moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours().
boolean moa.classifiers.lazy.neighboursearch.LinearNNSearch.m_SkipIdentical = false [protected]
Whether to skip instances from the neighbours that are identical to the query instance.
Definition at line 60 of file LinearNNSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.getSkipIdentical(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.LinearNNSearch.setSkipIdentical().
final long moa.classifiers.lazy.neighboursearch.LinearNNSearch.serialVersionUID = 1915484723703917241L [static, private]
for serialization.
Definition at line 52 of file LinearNNSearch.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/LinearNNSearch.java