MOA: moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue Class Reference
moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue Class Reference
Public Member Functions
EventQueue ()
void Insert (ISBNode node, Long expTime)
EventItem FindMin ()
EventItem ExtractMin ()
Public Attributes
TreeSet< EventItem > setEvents
Detailed Description
Definition at line 52 of file SimpleCODBase.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.EventQueue ()
Definition at line 55 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents.
{
            setEvents = new TreeSet<EventItem>();
        }
Member Function Documentation
EventItem moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.ExtractMin ()
Definition at line 71 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.FindMin(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
{
            EventItem e = FindMin();
            if (e != null) {
                setEvents.remove(e);
                return e;
            }
            return null;
        }
EventItem moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.FindMin ()
Definition at line 63 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.ExtractMin(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
{
            if (setEvents.size() > 0) {
                // events are sorted ascenting by expiration time
                return setEvents.first();
            }
            return null;
        }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.Insert (ISBNode node, Long expTime)
Definition at line 59 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue().
{
            setEvents.add(new EventItem(node, expTime));
        }
Member Data Documentation
TreeSet<EventItem> moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents
Definition at line 53 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.EventQueue(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.ExtractMin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.FindMin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.Insert(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/SimpleCOD/SimpleCODBase.java