MOA: moa.tasks.LearnModel Class Reference
moa.tasks.LearnModel Class Reference
Task for learning a model without any evaluation.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
LearnModel ()
LearnModel (Classifier learner, InstanceStream stream, int maxInstances, int numPasses)
Class<?> getTaskResultType ()
Gets the result type of this task.
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
IntOption maxInstancesOption
IntOption numPassesOption
IntOption memCheckFrequencyOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for learning a model without any evaluation.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 34 of file LearnModel.java.
Constructor & Destructor Documentation
moa.tasks.LearnModel.LearnModel ()
Definition at line 63 of file LearnModel.java.
{
    }
moa.tasks.LearnModel.LearnModel (Classifier learner, InstanceStream stream, int maxInstances, int numPasses)
Definition at line 66 of file LearnModel.java.
References moa.tasks.LearnModel.learnerOption, moa.tasks.LearnModel.maxInstancesOption, moa.tasks.LearnModel.numPassesOption, moa.options.AbstractClassOption.setCurrentObject(), moa.options.IntOption.setValue(), and moa.tasks.LearnModel.streamOption.
{
        this.learnerOption.setCurrentObject(learner);
        this.streamOption.setCurrentObject(stream);
        this.maxInstancesOption.setValue(maxInstances);
        this.numPassesOption.setValue(numPasses);
    }
Member Function Documentation
Object moa.tasks.LearnModel.doMainTask (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 80 of file LearnModel.java.
References moa.classifiers.Classifier.copy(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.hasMoreInstances(), moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.LearnModel.learnerOption, moa.tasks.LearnModel.maxInstancesOption, moa.streams.InstanceStream.nextInstance(), moa.tasks.LearnModel.numPassesOption, moa.streams.InstanceStream.restart(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.LearnModel.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), and moa.classifiers.Classifier.trainOnInstance().
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        learner.setModelContext(stream.getHeader());
        int numPasses = this.numPassesOption.getValue();
        int maxInstances = this.maxInstancesOption.getValue();
        for (int pass = 0; pass < numPasses; pass++) {
            long instancesProcessed = 0;
            monitor.setCurrentActivity("Training learner"
                    + (numPasses > 1 ? (" (pass " + (pass + 1) + "/"
                    + numPasses + ")") : "") + "...", -1.0);
            if (pass > 0) {
                stream.restart();
            }
            while (stream.hasMoreInstances()
                    && ((maxInstances < 0) || (instancesProcessed < maxInstances))) {
                learner.trainOnInstance(stream.nextInstance());
                instancesProcessed++;
                if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                    if (monitor.taskShouldAbort()) {
                        return null;
                    }
                    long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                    if (maxInstances > 0) {
                        long maxRemaining = maxInstances - instancesProcessed;
                        if ((estimatedRemainingInstances < 0)
                                || (maxRemaining < estimatedRemainingInstances)) {
                            estimatedRemainingInstances = maxRemaining;
                        }
                    }
                    monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                            : (double) instancesProcessed
                            / (double) (instancesProcessed + estimatedRemainingInstances));
                    if (monitor.resultPreviewRequested()) {
                        monitor.setLatestResultPreview(learner.copy());
                    }
                }
            }
        }
        learner.setModelContext(stream.getHeader());
        return learner;
    }
String moa.tasks.LearnModel.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 37 of file LearnModel.java.
{
        return "Learns a model from a stream.";
    }
Class<?> moa.tasks.LearnModel.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 75 of file LearnModel.java.
{
        return Classifier.class;
    }
Member Data Documentation
ClassOption moa.tasks.LearnModel.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Definition at line 43 of file LearnModel.java.
Referenced by moa.tasks.LearnModel.doMainTask(), and moa.tasks.LearnModel.LearnModel().
IntOption moa.tasks.LearnModel.maxInstancesOption
Initial value:
 new IntOption("maxInstances", 'm',
            "Maximum number of instances to train on per pass over the data.",
            10000000, 0, Integer.MAX_VALUE)
Definition at line 50 of file LearnModel.java.
Referenced by moa.tasks.LearnModel.doMainTask(), and moa.tasks.LearnModel.LearnModel().
IntOption moa.tasks.LearnModel.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Definition at line 58 of file LearnModel.java.
IntOption moa.tasks.LearnModel.numPassesOption
Initial value:
 new IntOption("numPasses", 'p',
            "The number of passes to do over the data.", 1, 1,
            Integer.MAX_VALUE)
Definition at line 54 of file LearnModel.java.
Referenced by moa.tasks.LearnModel.doMainTask(), and moa.tasks.LearnModel.LearnModel().
final long moa.tasks.LearnModel.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 41 of file LearnModel.java.
ClassOption moa.tasks.LearnModel.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 46 of file LearnModel.java.
Referenced by moa.tasks.LearnModel.doMainTask(), and moa.tasks.LearnModel.LearnModel().
The documentation for this class was generated from the following file:
main/java/moa/tasks/LearnModel.java