MOA: moa.clusterers.outliers.AnyOut.util.EMProjectedClustering Class Reference
moa.clusterers.outliers.AnyOut.util.EMProjectedClustering Class Reference
Implements clustering via Expectation Maximization but return a clear partitioning of the data, i.e.
Public Member Functions
EMProjectedClustering ()
int[][] getEMClusteringVariances (double[][] pointArray, int k)
Performs an EM clustering on the provided data set !! Only the variances are calculated and used for point assignments ! !!! the number k' of returned clusters might be smaller than k !!!
int[][] getEMClusteringVariancesBestChoice (double[][] pointArray, int k, int nrOfChoices)
Package Attributes
double[][] pointArray
int n
int dim
int k
double[][] clusterMeans
double[][] clusterVariances
double[][] pXgivenC
double[][] pCgivenX
double[] clusterWeights
double[] pX
Private Member Functions
void initFields (double[][] pointArray, int k)
void setInitialPartitions (double[][] pointArray, int k)
creates an initial partitioning
double euclideanDistance (double[] x, double[] y)
void getNewClusterRepresentation ()
void calculateWeights ()
void calculateMeans ()
void calculateVariances ()
void calculateClassConditionalDensities ()
void calculatePX ()
void calculatePCgivenX ()
void calculateAllProbabilities ()
double expectation ()
int[][] createProjectedClustering ()
Private Attributes
long randomSeed = 1L
final double minVariance = 0.01
final double minDeviation = 0.01
final int MAXITER = 20
Detailed Description
Implements clustering via Expectation Maximization but return a clear partitioning of the data, i.e.
a point belongs to only one cluster (the most probable)
Author:
kranen
Definition at line 35 of file EMProjectedClustering.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.EMProjectedClustering ()
Definition at line 65 of file EMProjectedClustering.java.
{}
Member Function Documentation
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateAllProbabilities () [private]
Definition at line 317 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX().
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
{
        this.calculateClassConditionalDensities();
        this.calculatePX();
        this.calculatePCgivenX();
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities () [private]
Definition at line 252 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterVariances, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pointArray, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pXgivenC.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateAllProbabilities().
{
        // P(x|C) = factor * e^( -0.5 (x-mu) * Sigma^-1 * (x-mu) )
        // exponent = -0.5 (x-mu) * Sigma^-1 * (x-mu) )
        //          = -0.5 ( sum_d ((x_i - mu_i)^2 / var_i) )
        double exponent;
        double xMinusMu;
        // factor = 1 / sqrt( (2*PI)^d * \prod_d(variance) )
        //        = 1 / sqrt((2*PI)^d) * sqrt(\prod_d(variance))
        //        = 1 / (2*PI)^(d/2)   * \prod_d(sqrt(variance))
        double factor;
        // for each cluster C_i
        for (int i = 0; i < pXgivenC[0].length; i++) {
            // if the cluster is empty, set P(x|C_i) = 0
            if (clusterWeights[i] <= 0.0) {
                for (int x = 0; x < pXgivenC.length; x++)
                    pXgivenC[x][i] = 0.0;
                continue;
            }
            // calculate the factor for each cluster
            factor = Math.pow( (2.0 * Math.PI) , ((dim/2.0)) );
            for (int d = 0; d < dim; d++) {
                factor *= Math.sqrt(clusterVariances[i][d]);
            }
            // factor = 1 / sqrt( (2*PI)^d * \prod_d(variance) )
            factor = 1 / factor;
            // calculate the density for each point x
            for (int x = 0; x < pXgivenC.length; x++) {
                exponent = 0.0;
                for (int d = 0; d < dim; d++) {
                    xMinusMu = pointArray[x][d] - clusterMeans[i][d];
                    exponent += (xMinusMu * xMinusMu) / clusterVariances[i][d];
                }
                exponent *= -0.5;
                pXgivenC[x][i] = factor * Math.exp(exponent);
            }
        }
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans () [private]
Definition at line 215 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pointArray.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getNewClusterRepresentation().
{
        // per dimension d:
        // mu_i = [\sum_{x in D} ( x * P(C_i|x) )] / [W_i * n]
        for (int i = 0; i < k; i++) {
            for (int d = 0; d < dim; d++) {
                clusterMeans[i][d] = 0.0;
                if (clusterWeights[i] <= 0.0)
                    continue;
                for (int x = 0; x < n; x++) {
                    clusterMeans[i][d] += pointArray[x][d] * pCgivenX[i][x];
                }
                clusterMeans[i][d] /= (clusterWeights[i] * n);
            }
        }
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX () [private]
Definition at line 305 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pXgivenC.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateAllProbabilities().
{
        // P(C_i|x) = W_i * P(x|C_i)/P(x)
        for (int i = 0; i < k; i++) {
            for (int x = 0; x < n; x++) {
                if (pX[x] <= 0.0)
                    pCgivenX[i][x] = 0.0;
                else
                    pCgivenX[i][x] = clusterWeights[i] * pXgivenC[x][i] / pX[x];
            }
        }
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX () [private]
Definition at line 295 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pXgivenC.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateAllProbabilities().
{
        // P(x) = \sum_{i=1 to k} ( W_i * P(x|C_i) )
        for (int x = 0; x < n; x++) {
            pX[x] = 0.0;
            for (int i = 0; i < k; i++) {
                pX[x] += clusterWeights[i] * pXgivenC[x][i];
            }
        }
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances () [private]
Definition at line 231 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterVariances, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.minVariance, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pointArray.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getNewClusterRepresentation().
{
        // per dimension d:
        // sigma_i = [\sum_{x in D} (P(C_i|x) * (x-mu_i)^2)] / ] / [W_i * n]
        double xMinusMu;
        for (int i = 0; i < k; i++) {
            for (int d = 0; d < dim; d++) {
                clusterVariances[i][d] = 0.0;
                if (clusterWeights[i] <= 0.0)
                    continue;
                for (int x = 0; x < n; x++) {
                    xMinusMu = pointArray[x][d] - clusterMeans[i][d];
                    clusterVariances[i][d] += pCgivenX[i][x] * (xMinusMu * xMinusMu);
                }
                if (clusterVariances[i][d] < this.minVariance)
                    clusterVariances[i][d] = this.minVariance;
                else
                    clusterVariances[i][d] /= (clusterWeights[i] * n);
            }
        }
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights () [private]
Definition at line 204 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getNewClusterRepresentation().
{
        // W_i = 1/n * \sum_{x in D} ( P(C_i|x) )
        for (int i = 0; i < k; i++) {
            clusterWeights[i] = 0.0;
            for (int x = 0; x < n; x++) {
                clusterWeights[i] += pCgivenX[i][x];
            }
            clusterWeights[i] /= n;
        }
    }
int [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.createProjectedClustering () [private]
Definition at line 334 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
{
        TreeSet<Integer> nonEmptyClusters = new TreeSet<Integer>();
        ArrayList<Integer>[] clusterMemberLists = new ArrayList[k];
        for (int i = 0; i < k; i++) {
            clusterMemberLists[i] = new ArrayList<Integer>();
        }
        double maxProbability;
        int maxProbIndex = 0;
        // for each point ...
        for (int x = 0; x < n; x++) {
            maxProbability = 0.0;
            // find the most probable cluster
            for (int i = 0; i < k; i++) {
                if (pCgivenX[i][x] > maxProbability) {
                    maxProbability = pCgivenX[i][x];
                    maxProbIndex = i;
                }
            }
            // and add the point to the cluster's member list
            clusterMemberLists[maxProbIndex].add(x);
            nonEmptyClusters.add(maxProbIndex);
        }
        // copy the member lists to an array while removing the empty lists (i.e. empty clusters)
        int[][] result = new int[nonEmptyClusters.size()][];
        int counter = 0;
        for (int i = 0; i < clusterMemberLists.length; i++) {
            if (clusterMemberLists[i].size() > 0) {
                result[counter] = new int[clusterMemberLists[i].size()];
                for (int j = 0; j < clusterMemberLists[i].size(); j++) {
                    result[counter][j] = clusterMemberLists[i].get(j);
                }
                counter++;
            }
        }
        return result;
    }
double moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.euclideanDistance (double[] x, double[] y) [private]
Definition at line 189 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
{
        double result = 0.0;
        // d(x, y) = sqrt( \sum_{i=1 to d} ( (x_i - y_i)^2 ) )
        for (int i = 0; i < x.length; i++) {
            result += (x[i] - y[i]) * (x[i] - y[i]);
        }
        return Math.sqrt(result);
    }
double moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.expectation () [private]
Definition at line 323 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pX.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariancesBestChoice().
{
        // E(M) = \sum_{x in D} ( P(x) )
        double result = 0.0;
        for (int x = 0; x < n; x++) {
            //result += Math.log(pX[x]);
            result += pX[x];
        }
        return result;
    }
int [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances (double pointArray[][], int k)
Performs an EM clustering on the provided data set !! Only the variances are calculated and used for point assignments ! !!! the number k' of returned clusters might be smaller than k !!!
Parameters:
pointArray the data set as an array[n][d] of n points with d dimensions
k the number of requested partitions (!might return less)
Returns:
a mapping int[n][k'] of the n given points to the k' resulting clusters
Definition at line 75 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateAllProbabilities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.createProjectedClustering(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.expectation(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getNewClusterRepresentation(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.MAXITER, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.minDeviation, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariancesBestChoice().
{
        // initialize field and clustering
        initFields(pointArray, k);
        setInitialPartitions(pointArray, k);
        // iterate M and E
        double currentExpectation, newExpectation = 0.0;
        double expectationDeviation;
        int count = 0;
        do{
            currentExpectation = newExpectation;
            // reassign objects
            getNewClusterRepresentation();
            calculateAllProbabilities();
            // calculate new expectation value
            newExpectation = expectation();
            // stop when the deviation is less than minDeviation
            expectationDeviation = 1.0 - (currentExpectation / newExpectation);
            count++;
        } while (expectationDeviation > minDeviation && count < MAXITER);
        // return the resulting mapping from points to clusters
        return createProjectedClustering();
    }
int [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariancesBestChoice (double pointArray[][], int k, int nrOfChoices)
Definition at line 100 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.expectation(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.randomSeed.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingEM().
{
        nrOfChoices = Math.max(1, nrOfChoices);
        int[][] bestChoice = null;
        int[][] tmpChoice = null;
        double tmpMeasure, bestMeasure = Double.NEGATIVE_INFINITY;
        for (int i = 0; i < nrOfChoices; i++) {
            this.randomSeed = i;
            tmpChoice = this.getEMClusteringVariances(pointArray, k);
            tmpMeasure = this.expectation();
            if (tmpMeasure > bestMeasure) {
                bestMeasure = tmpMeasure;
                bestChoice = tmpChoice;
            }
        }
        return bestChoice;
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getNewClusterRepresentation () [private]
Definition at line 198 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights().
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
{
        calculateWeights();
        calculateMeans();
        calculateVariances();
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields (double pointArray[][], int k) [private]
Parameters:
n nrOfPoints
dim nrOfDimensions
k nrOfClusters
Definition at line 124 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterVariances, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pXgivenC.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
{
        this.pointArray = pointArray;
        this.n = pointArray.length;
        this.dim = pointArray[0].length;
        this.k = k;
        // means of the clusters
        this.clusterMeans = new double[k][dim];
        // variance vectors of the clusters
        this.clusterVariances = new double[k][dim];
        // probability for the points given a cluster
        this.pXgivenC = new double[n][k];
        // probabilities for points to belong to a cluster
        this.pCgivenX = new double[k][n];
        // weight of the clusters
        this.clusterWeights = new double[k];
        // probabilities of the points
        this.pX = new double[n];
    }
void moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions (double pointArray[][], int k) [private]
creates an initial partitioning
Parameters:
pointArray
k
Definition at line 150 of file EMProjectedClustering.java.
References moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.euclideanDistance(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n, moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX, and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.randomSeed.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
{
        if (pointArray.length < k) {
            System.err.println("cannot cluster less than k points into k clusters...");
            System.exit(0);
        }
        // select randomly k initial means
        // TODO: choose more stable initialization (comment: this is run several times (with different random seeds), i.e. the worst case should not occur)
        Random random = new Random(randomSeed);
        TreeSet<Integer> usedPoints = new TreeSet<Integer>();
        int nextIndex;
        for (int i = 0; i < k; i++) {
            nextIndex = ((Double)(Math.floor(random.nextDouble() * n))).intValue();
            if (usedPoints.contains(nextIndex)) {
                i--;
                continue;
            } else {
                for (int d = 0; d < dim; d++) {
                    clusterMeans[i][d] = pointArray[nextIndex][d];
                }
            }
        }
        // set pCgivenX=1 for the closest C for each point
        int minDistIndex = 0;
        double minDist, currentDist;
        for (int x = 0; x < pointArray.length; x++) {
            minDist = Double.MAX_VALUE;
            for (int i = 0; i < k; i++) {
                currentDist = euclideanDistance(clusterMeans[i], pointArray[x]);
                if (currentDist < minDist) {
                    minDist = currentDist;
                    minDistIndex = i;
                }
            }
            pCgivenX[minDistIndex][x] = 1.0;
        }
    }
Member Data Documentation
double [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterMeans [package]
Definition at line 52 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
double [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterVariances [package]
Definition at line 54 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields().
double [] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.clusterWeights [package]
Definition at line 61 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields().
int moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.dim [package]
Definition at line 42 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
int moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.k [package]
Definition at line 43 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.createProjectedClustering().
final int moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.MAXITER = 20 [private]
Definition at line 49 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
final double moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.minDeviation = 0.01 [private]
Definition at line 48 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariances().
final double moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.minVariance = 0.01 [private]
Definition at line 46 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances().
int moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.n [package]
Definition at line 41 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.createProjectedClustering(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.expectation(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
double [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pCgivenX [package]
Definition at line 59 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateWeights(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.createProjectedClustering(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
double [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pointArray [package]
Definition at line 40 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateMeans(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateVariances().
double [] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pX [package]
Definition at line 63 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.expectation(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields().
double [][] moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.pXgivenC [package]
Definition at line 57 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculateClassConditionalDensities(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePCgivenX(), moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.calculatePX(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.initFields().
long moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.randomSeed = 1L [private]
Definition at line 37 of file EMProjectedClustering.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.getEMClusteringVariancesBestChoice(), and moa.clusterers.outliers.AnyOut.util.EMProjectedClustering.setInitialPartitions().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AnyOut/util/EMProjectedClustering.java