MOA: moa.recommender.rc.utils.SparseVector.SparseVectorIterator Class Reference
moa.recommender.rc.utils.SparseVector.SparseVectorIterator Class Reference
Public Member Functions
boolean hasNext ()
Pair< Integer, Double > next ()
void remove ()
Private Attributes
Iterator< Integer > it = SparseVector.this.map.keySet().iterator()
Detailed Description
Definition at line 68 of file SparseVector.java.
Member Function Documentation
boolean moa.recommender.rc.utils.SparseVector.SparseVectorIterator.hasNext ()
Definition at line 72 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.SparseVectorIterator.it.
{
            return it.hasNext();
        }
Pair<Integer, Double> moa.recommender.rc.utils.SparseVector.SparseVectorIterator.next ()
Definition at line 77 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.SparseVectorIterator.it.
{
            Integer idx = it.next();
            return new Pair<Integer, Double>(idx, SparseVector.this.map.get(idx));
        }
void moa.recommender.rc.utils.SparseVector.SparseVectorIterator.remove ()
Definition at line 83 of file SparseVector.java.
References moa.recommender.rc.utils.SparseVector.SparseVectorIterator.it.
{
            it.remove();
        }
Member Data Documentation
Iterator<Integer> moa.recommender.rc.utils.SparseVector.SparseVectorIterator.it = SparseVector.this.map.keySet().iterator() [private]
Definition at line 69 of file SparseVector.java.
Referenced by moa.recommender.rc.utils.SparseVector.SparseVectorIterator.hasNext(), moa.recommender.rc.utils.SparseVector.SparseVectorIterator.next(), and moa.recommender.rc.utils.SparseVector.SparseVectorIterator.remove().
The documentation for this class was generated from the following file:
main/java/moa/recommender/rc/utils/SparseVector.java