MOA: moa.classifiers.AbstractMultipleClassifierTestCase Class Reference
moa.classifiers.AbstractMultipleClassifierTestCase Class Reference
Ancestor that defines a setting to test a classifier several times with different parameters using this predefined same setting.
Public Member Functions
AbstractMultipleClassifierTestCase (String name)
Constructs the test case.
void setNumberTests (int numberTests)
Sets the number of tests to run with this classifier.
Protected Member Functions
void setUp () throws Exception
Called by JUnit before each test method.
void tearDown () throws Exception
Called by JUnit after each test method.
String[] getRegressionInputFiles ()
Returns the filenames (without path) of the input data files to use in the regression test.
int[] getRegressionInputClassIndex ()
Returns the class index for the datasets.
int[][] getRegressionInspectionPoints ()
Returns the index of the instances in the stream to inspect the performance/classification output of the classifiers.
abstract Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
ClassificationPerformanceEvaluator[] getRegressionEvaluatorSetups ()
Returns the evaluator setups to use in the regression test.
Protected Attributes
int numberTests = 1
Detailed Description
Ancestor that defines a setting to test a classifier several times with different parameters using this predefined same setting.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 31 of file AbstractMultipleClassifierTestCase.java.
Constructor & Destructor Documentation
moa.classifiers.AbstractMultipleClassifierTestCase.AbstractMultipleClassifierTestCase (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 41 of file AbstractMultipleClassifierTestCase.java.
{
        super(name);
    }
Member Function Documentation
abstract Classifier [] moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionClassifierSetups () [protected, pure virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractClassifierTestCase.
Implemented in moa.classifiers.active.ActiveClassifierTest, moa.classifiers.bayes.NaiveBayesMultinomialTest, moa.classifiers.bayes.NaiveBayesTest, moa.classifiers.drift.DriftDetectionMethodClassifierTest, moa.classifiers.drift.SingleClassifierDriftTest, moa.classifiers.functions.MajorityClassTest, moa.classifiers.functions.NoChangeTest, moa.classifiers.functions.PerceptronTest, moa.classifiers.functions.SGDTest, moa.classifiers.functions.SPegasosTest, moa.classifiers.meta.AccuracyUpdatedEnsembleTest, moa.classifiers.meta.AccuracyWeightedEnsembleTest, moa.classifiers.meta.LeveragingBagTest, moa.classifiers.meta.LimAttClassifierTest, moa.classifiers.meta.OCBoostTest, moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest, moa.classifiers.meta.OzaBagAdwinTest, moa.classifiers.meta.OzaBagASHTTest, moa.classifiers.meta.OzaBagTest, moa.classifiers.meta.OzaBoostAdwinTest, moa.classifiers.meta.OzaBoostTest, moa.classifiers.meta.TemporallyAugmentedClassifierTest, moa.classifiers.meta.WeightedMajorityAlgorithmTest, moa.classifiers.meta.WEKAClassifierTest, moa.classifiers.rules.RuleClassifierNBayesTest, moa.classifiers.rules.RuleClassifierTest, moa.classifiers.trees.AdaHoeffdingOptionTreeTest, moa.classifiers.trees.ASHoeffdingTreeTest, moa.classifiers.trees.DecisionStumpTest, moa.classifiers.trees.HoeffdingAdaptiveTreeTest, moa.classifiers.trees.HoeffdingOptionTreeTest, moa.classifiers.trees.HoeffdingTreeTest, moa.classifiers.trees.LimAttHoeffdingTreeTest, and moa.classifiers.trees.RandomHoeffdingTreeTest.
ClassificationPerformanceEvaluator [] moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionEvaluatorSetups () [protected, virtual]
Returns the evaluator setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractClassifierTestCase.
Definition at line 141 of file AbstractMultipleClassifierTestCase.java.
References moa.MOAObject.copy(), and moa.classifiers.AbstractMultipleClassifierTestCase.numberTests.
{
        ClassificationPerformanceEvaluator value = new BasicClassificationPerformanceEvaluator();
        ClassificationPerformanceEvaluator[] ret = new ClassificationPerformanceEvaluator[this.numberTests];
        for (int i = 0; i < this.numberTests; i++) {
            ret[i] = (ClassificationPerformanceEvaluator) value.copy();
        }
        return ret;
    }
int [] moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInputClassIndex () [protected, virtual]
Returns the class index for the datasets.
Returns:
the class indices (0-based)
Implements moa.classifiers.AbstractClassifierTestCase.
Definition at line 102 of file AbstractMultipleClassifierTestCase.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.numberTests.
{
        int value = 10;
        int[] ret = new int[this.numberTests];
        for (int i = 0; i < this.numberTests; i++) {
            ret[i] = value;
        }
        return ret;
    }
String [] moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInputFiles () [protected, virtual]
Returns the filenames (without path) of the input data files to use in the regression test.
Returns:
the filenames
Implements moa.classifiers.AbstractClassifierTestCase.
Definition at line 87 of file AbstractMultipleClassifierTestCase.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.numberTests.
{
        String value = "classification.arff";
        String[] ret = new String[this.numberTests];
        for (int i = 0; i < this.numberTests; i++) {
            ret[i] = value;
        }
        return ret;
    }
int [][] moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInspectionPoints () [protected, virtual]
Returns the index of the instances in the stream to inspect the performance/classification output of the classifiers.
Returns:
the inspection indices
Implements moa.classifiers.AbstractClassifierTestCase.
Definition at line 118 of file AbstractMultipleClassifierTestCase.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.numberTests.
{
        int[] value = new int[]{10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000};
        int[][] ret = new int[this.numberTests][value.length];
        for (int i = 0; i < this.numberTests; i++) {
            ret[i] = value.clone();
        }
        return ret;
    }
void moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests (int numberTests)
Sets the number of tests to run with this classifier.
Parameters:
name the name of the test
numberTests the numbers of tests to run
Definition at line 52 of file AbstractMultipleClassifierTestCase.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsembleTest.AccuracyUpdatedEnsembleTest(), moa.classifiers.meta.AccuracyWeightedEnsembleTest.AccuracyWeightedEnsembleTest(), moa.classifiers.active.ActiveClassifierTest.ActiveClassifierTest(), moa.classifiers.trees.AdaHoeffdingOptionTreeTest.AdaHoeffdingOptionTreeTest(), moa.classifiers.trees.ASHoeffdingTreeTest.ASHoeffdingTreeTest(), moa.classifiers.trees.DecisionStumpTest.DecisionStumpTest(), moa.classifiers.drift.DriftDetectionMethodClassifierTest.DriftDetectionMethodClassifierTest(), moa.classifiers.trees.HoeffdingAdaptiveTreeTest.HoeffdingAdaptiveTreeTest(), moa.classifiers.trees.HoeffdingOptionTreeTest.HoeffdingOptionTreeTest(), moa.classifiers.trees.HoeffdingTreeTest.HoeffdingTreeTest(), moa.classifiers.meta.LeveragingBagTest.LeveragingBagTest(), moa.classifiers.meta.LimAttClassifierTest.LimAttClassifierTest(), moa.classifiers.trees.LimAttHoeffdingTreeTest.LimAttHoeffdingTreeTest(), moa.classifiers.functions.MajorityClassTest.MajorityClassTest(), moa.classifiers.bayes.NaiveBayesMultinomialTest.NaiveBayesMultinomialTest(), moa.classifiers.bayes.NaiveBayesTest.NaiveBayesTest(), moa.classifiers.functions.NoChangeTest.NoChangeTest(), moa.classifiers.meta.OCBoostTest.OCBoostTest(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest.OnlineAccuracyUpdatedEnsembleTest(), moa.classifiers.meta.OzaBagAdwinTest.OzaBagAdwinTest(), moa.classifiers.meta.OzaBagASHTTest.OzaBagASHTTest(), moa.classifiers.meta.OzaBagTest.OzaBagTest(), moa.classifiers.meta.OzaBoostAdwinTest.OzaBoostAdwinTest(), moa.classifiers.meta.OzaBoostTest.OzaBoostTest(), moa.classifiers.functions.PerceptronTest.PerceptronTest(), moa.classifiers.trees.RandomHoeffdingTreeTest.RandomHoeffdingTreeTest(), moa.classifiers.rules.RuleClassifierNBayesTest.RuleClassifierNBayesTest(), moa.classifiers.rules.RuleClassifierTest.RuleClassifierTest(), moa.classifiers.functions.SGDTest.SGDTest(), moa.classifiers.drift.SingleClassifierDriftTest.SingleClassifierDriftTest(), moa.classifiers.functions.SPegasosTest.SPegasosTest(), moa.classifiers.meta.TemporallyAugmentedClassifierTest.TemporallyAugmentedClassifierTest(), moa.classifiers.meta.WeightedMajorityAlgorithmTest.WeightedMajorityAlgorithmTest(), and moa.classifiers.meta.WEKAClassifierTest.WEKAClassifierTest().
{
        this.numberTests = numberTests;
    }
void moa.classifiers.AbstractMultipleClassifierTestCase.setUp () throws Exception [protected]
Called by JUnit before each test method.
Exceptions:
Exception if an error occurs.
Reimplemented from moa.test.MoaTestCase.
Definition at line 62 of file AbstractMultipleClassifierTestCase.java.
References moa.test.MoaTestCase.m_TestHelper.
{
        super.setUp();
        m_TestHelper.copyResourceToTmp("classification.arff");
    }
void moa.classifiers.AbstractMultipleClassifierTestCase.tearDown () throws Exception [protected]
Called by JUnit after each test method.
Exceptions:
Exception if tear-down fails
Reimplemented from moa.test.MoaTestCase.
Definition at line 74 of file AbstractMultipleClassifierTestCase.java.
References moa.test.MoaTestCase.m_TestHelper.
{
        m_TestHelper.deleteFileFromTmp("classification.arff");
        super.tearDown();
    }
Member Data Documentation
int moa.classifiers.AbstractMultipleClassifierTestCase.numberTests = 1 [protected]
Definition at line 34 of file AbstractMultipleClassifierTestCase.java.
Referenced by moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionEvaluatorSetups(), moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInputClassIndex(), moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInputFiles(), and moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionInspectionPoints().
The documentation for this class was generated from the following file:
test/java/moa/classifiers/AbstractMultipleClassifierTestCase.java