MOA: moa.recommender.rc.predictor.impl.BRISMFPredictor Class Reference
moa.recommender.rc.predictor.impl.BRISMFPredictor Class Reference
Implementation of the algorithm described in Scalable Collaborative Filtering Approaches for Large Recommender Systems (Gábor Takács, István Pilászy, Bottyán Németh, and Domonkos Tikk).
Public Member Functions
void setLRate (double lRate)
void setRFactor (double rFactor)
void setNIterations (int nIterations)
RecommenderData getData ()
BRISMFPredictor (int nFeatures, RecommenderData data, boolean train)
BRISMFPredictor (int nFeatures, RecommenderData data, double lRate, double rFactor, boolean train)
double predictRating (int userID, int itemID)
double predictRating (float userFeats[], float itemFeats[])
float[] trainUserFeats (List< Integer > itm, List< Double > rat, int nIts)
float[] trainItemFeats (int itemID, List< Integer > usr, List< Double > rat, int nIts)
void trainUser (int userID, List< Integer > itm, List< Double > rat, int nIts)
void trainUser (int userID, int nIts)
void trainUser (int userID, List< Integer > itm, List< Double > rat)
void trainItem (int itemID)
void trainItem (int itemID, int nIts)
void trainUser (int userID)
void trainItem (int itemID, List< Integer > usr, List< Double > rat)
void trainItem (int itemID, List< Integer > usr, List< Double > rat, int nIts)
void train ()
float[] getUserFeatures (int userID)
float[] getItemFeatures (int itemID)
int getNumFeatures ()
void updateNewUser (int userID, List< Integer > ratedItems, List< Double > ratings)
void updateNewItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
void updateRemoveUser (int userID)
void updateRemoveItem (int itemID)
void updateSetRating (int userID, int itemID, double rating)
void updateRemoveRating (int userID, int itemID)
List< Double > predictRatings (int userID, List< Integer > itemIDS)
Protected Attributes
RecommenderData data
int nFeatures
HashMap< Integer, float[]> userFeature
HashMap< Integer, float[]> itemFeature
Random rnd
double lRate = 0.01
double rFactor = 0.02
int nIterations = 30
Private Member Functions
void resetFeatures (float[] feats, boolean userFeats)
Detailed Description
Implementation of the algorithm described in Scalable Collaborative Filtering Approaches for Large Recommender Systems (Gábor Takács, István Pilászy, Bottyán Németh, and Domonkos Tikk).
A feature vector is learned for every user and item, so that the prediction of a rating is roughly the dot product of the corresponding user and item vector. Stochastic gradient descent is used to train the model, minimizing its prediction error. Both Tikhonov regularization and early stopping are used to reduce overfitting. The algorithm allows batch training (from scratch, using all ratings available at the moment) as well as incremental, by retraining only the affected user and item vectors when a new rating is inserted.
Parameters:
features - the number of features to be trained for each user and item
learning rate - the learning rate used in the regularization
ratio - the regularization ratio to be used in the Tikhonov regularization
iterations - the number of iterations to be used when retraining user and item features (online training). </lu>
Definition at line 62 of file BRISMFPredictor.java.
Constructor & Destructor Documentation
moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor (int nFeatures, RecommenderData data, boolean train)
Definition at line 89 of file BRISMFPredictor.java.
References moa.recommender.rc.data.RecommenderData.attachUpdatable(), moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, moa.recommender.rc.predictor.impl.BRISMFPredictor.rnd, moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
{
        this.data = data;
        this.nFeatures = nFeatures;
        this.userFeature = new HashMap<Integer, float[]>();
        this.itemFeature = new HashMap<Integer, float[]>();
        this.rnd = new Random(12345);
        data.attachUpdatable(this);
        if (train) train();
    }
moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor (int nFeatures, RecommenderData data, double lRate, double rFactor, boolean train)
Definition at line 99 of file BRISMFPredictor.java.
References moa.recommender.rc.data.RecommenderData.attachUpdatable(), moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, moa.recommender.rc.predictor.impl.BRISMFPredictor.rnd, moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
{
        this.data = data;
        this.nFeatures = nFeatures;
        this.userFeature = new HashMap<Integer, float[]>();
        this.itemFeature = new HashMap<Integer, float[]>();
        this.rnd = new Random(12345);
        this.lRate = lRate;
        this.rFactor = rFactor;
        data.attachUpdatable(this);
        if (train) train();
    }
Member Function Documentation
RecommenderData moa.recommender.rc.predictor.impl.BRISMFPredictor.getData ()
Definition at line 85 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data.
{
        return data;
    }
float [] moa.recommender.rc.predictor.impl.BRISMFPredictor.getItemFeatures (int itemID)
Definition at line 337 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature.
{
        return itemFeature.get(itemID);
    }
int moa.recommender.rc.predictor.impl.BRISMFPredictor.getNumFeatures ()
Definition at line 341 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures.
{
        return nFeatures;
    }
float [] moa.recommender.rc.predictor.impl.BRISMFPredictor.getUserFeatures (int userID)
Definition at line 333 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
{
        return userFeature.get(userID);
    }
double moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating (float userFeats[], float itemFeats[])
Definition at line 125 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getGlobalMean(), moa.recommender.rc.data.RecommenderData.getMaxRating(), moa.recommender.rc.data.RecommenderData.getMinRating(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures.
{
        double ret = data.getGlobalMean();
        if (userFeats != null && itemFeats != null)
            for (int i = 0; i < nFeatures; ++i)
                ret += userFeats[i]*itemFeats[i];
        if (ret < data.getMinRating()) ret = data.getMinRating();
        else if (ret > data.getMaxRating()) ret = data.getMaxRating();
        return ret;
    }
double moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating (int userID, int itemID)
Definition at line 119 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRatings(), moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats().
{
        float[] userFeats = userFeature.get(userID);
        float[] itemFeats = itemFeature.get(itemID);
        return predictRating(userFeats, itemFeats);
    }
List<Double> moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRatings (int userID, List< Integer > itemIDS)
Definition at line 433 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating().
{
        int n = itemIDS.size();
        ArrayList<Double> ret = new ArrayList<Double>(n);
        for (int i = 0; i < n; ++i)
            ret.add(predictRating(userID, itemIDS.get(i)));
        return ret;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.resetFeatures (float[] feats, boolean userFeats) [private]
Definition at line 111 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.rnd.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats().
{
        int n = feats.length;
        for (int i = 0; i < n; ++i)
            feats[i] = (float)0.01*(rnd.nextFloat()*2 - 1);
        if (userFeats) feats[0] = 1;
        else feats[1] = 1;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.setLRate (double lRate)
Definition at line 73 of file BRISMFPredictor.java.
{
        this.lRate = lRate;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.setNIterations (int nIterations)
Definition at line 81 of file BRISMFPredictor.java.
{
        this.nIterations = nIterations;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.setRFactor (double rFactor)
Definition at line 77 of file BRISMFPredictor.java.
{
        this.rFactor = rFactor;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.train ()
Definition at line 255 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getItems(), moa.recommender.rc.data.RecommenderData.getNumRatings(), moa.recommender.rc.data.RecommenderData.getUsers(), moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, moa.recommender.rc.utils.Rating.itemID, moa.recommender.rc.predictor.impl.BRISMFPredictor.lRate, moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures, moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.utils.Rating.rating, moa.recommender.rc.data.RecommenderData.ratingIterator(), moa.recommender.rc.predictor.impl.BRISMFPredictor.resetFeatures(), moa.recommender.rc.predictor.impl.BRISMFPredictor.rFactor, moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature, and moa.recommender.rc.utils.Rating.userID.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor().
{
        userFeature.clear();
        itemFeature.clear();
        int n = data.getNumRatings();
        Iterator<Integer> it = data.getUsers().iterator();
        while (it.hasNext()) {
            float[] feats = new float[nFeatures];
            resetFeatures(feats, true);
            userFeature.put(it.next(), feats);
        }
        it = data.getItems().iterator();
        while (it.hasNext()) {
            float[] feats = new float[nFeatures];
            resetFeatures(feats, false);
            itemFeature.put(it.next(), feats);
        }
        int exit = 0;
        double lastRMSE = 1e20;
        int count = 0;
        int trainDiv = Math.max(20, n/1000000);
        ArrayList<Rating> ratTest = new ArrayList<Rating>(n/trainDiv);
        do {
            long start = System.currentTimeMillis();
            Iterator<Rating> ratIt = data.ratingIterator();
            int idx = 0;
            while (ratIt.hasNext()) {
                Rating rat = ratIt.next();
                if (idx%trainDiv == 0) {
                    if (count == 0) ratTest.add(rat);
                }
                else {
                    int userID = rat.userID;
                    int itemID = rat.itemID;
                    double rating = rat.rating;
                    float[] userFeats = userFeature.get(userID);
                    float[] itemFeats = itemFeature.get(itemID);
                    double pred = predictRating(userFeats, itemFeats);
                    double err = rating - pred;
                    itemFeats[0] += lRate*(err*userFeats[0] - rFactor*itemFeats[0]);
                    userFeats[1] += lRate*(err*itemFeats[1] - rFactor*userFeats[1]);
                    for (int j = 2; j < nFeatures; ++j) {
                        double uv = userFeats[j];
                        userFeats[j] += lRate*(err*itemFeats[j] - rFactor*userFeats[j]);
                        itemFeats[j] += lRate*(err*uv - rFactor*itemFeats[j]);
                    }
                }
                ++idx;
            }
            int nTest = ratTest.size();
            double sum = 0;
            for (int i = 0; i < nTest; ++i) {
                int userID = ratTest.get(i).userID;
                int itemID = ratTest.get(i).itemID;
                double rating = ratTest.get(i).rating;
                double pred = predictRating(userID, itemID);
                sum += Math.pow(rating - pred, 2);
            }
            double curRMSE = Math.sqrt(sum/(double)nTest);
            System.out.println(curRMSE + " " + (System.currentTimeMillis() - start)/1000);
            if (curRMSE + 0.0001 >= lastRMSE) {
                ++exit;
            }
            lastRMSE = curRMSE;
            ++count;
        }
        while (exit < 1);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem (int itemID, List< Integer > usr, List< Double > rat, int nIts)
Definition at line 251 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats().
{
        itemFeature.put(itemID, trainItemFeats(itemID, usr, rat, nIts));
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem (int itemID, List< Integer > usr, List< Double > rat)
Definition at line 247 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, moa.recommender.rc.predictor.impl.BRISMFPredictor.nIterations, and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats().
{
        itemFeature.put(itemID, trainItemFeats(itemID, usr, rat, nIterations));
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem (int itemID, int nIts)
Definition at line 219 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getRatingsItem(), moa.recommender.rc.utils.SparseVector.iterator(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem().
{
        SparseVector itmRats = data.getRatingsItem(itemID);
        ArrayList<Integer> usr = new ArrayList<Integer>();
        ArrayList<Double> rat = new ArrayList<Double>();
        Iterator<Pair<Integer, Double>> it = itmRats.iterator();
        while (it.hasNext()) {
            Pair<Integer, Double> p = it.next();
            usr.add(p.getFirst());
            rat.add(p.getSecond());
        }
        trainItem(itemID, usr, rat, nIts);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem (int itemID)
Definition at line 205 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getRatingsItem(), and moa.recommender.rc.utils.SparseVector.iterator().
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), moa.recommender.rc.predictor.impl.BRISMFPredictor.updateNewItem(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
{
        SparseVector itmRats = data.getRatingsItem(itemID);
        ArrayList<Integer> usr = new ArrayList<Integer>();
        ArrayList<Double> rat = new ArrayList<Double>();
        Iterator<Pair<Integer, Double>> it = itmRats.iterator();
        while (it.hasNext()) {
            Pair<Integer, Double> p = it.next();
            usr.add(p.getFirst());
            rat.add(p.getSecond());
        }
        trainItem(itemID, usr, rat);
    }
float [] moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats (int itemID, List< Integer > usr, List< Double > rat, int nIts)
Definition at line 159 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.lRate, moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures, moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.resetFeatures(), moa.recommender.rc.predictor.impl.BRISMFPredictor.rFactor, and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem().
{
        float[] itemFeats = new float[nFeatures];
        resetFeatures(itemFeats, false);
        int n = usr.size();
        for (int k = 0; k < nIts; ++k) {
            for (int i = 0; i < n; ++i) {
                int userID = usr.get(i);
                float[] userFeats = userFeature.get(userID);
                double rating = rat.get(i);
                double pred = predictRating(userFeats, itemFeats);
                double err = rating - pred;
                if (userFeats != null) {
                    itemFeats[0] += lRate*(err*userFeats[0] - rFactor*itemFeats[0]);
                    for (int j = 2; j < nFeatures; ++j)
                        itemFeats[j] += lRate*(err*userFeats[j] - rFactor*itemFeats[j]);
                }
            }
        }
        return itemFeats;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser (int userID)
Definition at line 233 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getRatingsUser(), moa.recommender.rc.utils.SparseVector.iterator(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
{
        SparseVector usrRats = data.getRatingsUser(userID);
        ArrayList<Integer> itm = new ArrayList<Integer>();
        ArrayList<Double> rat = new ArrayList<Double>();
        Iterator<Pair<Integer, Double>> it = usrRats.iterator();
        while (it.hasNext()) {
            Pair<Integer, Double> p = it.next();
            itm.add(p.getFirst());
            rat.add(p.getSecond());
        }
        trainUser(userID, itm, rat);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser (int userID, List< Integer > itm, List< Double > rat)
Definition at line 201 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.nIterations, moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
{
        userFeature.put(userID, trainUserFeats(itm, rat, nIterations));
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser (int userID, int nIts)
Definition at line 187 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getRatingsUser(), moa.recommender.rc.utils.SparseVector.iterator(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
{
        SparseVector usrRats = data.getRatingsUser(userID);
        ArrayList<Integer> itm = new ArrayList<Integer>();
        ArrayList<Double> rat = new ArrayList<Double>();
        Iterator<Pair<Integer, Double>> it = usrRats.iterator();
        while (it.hasNext()) {
            Pair<Integer, Double> p = it.next();
            itm.add(p.getFirst());
            rat.add(p.getSecond());
        }
        trainUser(userID, itm, rat, nIts);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser (int userID, List< Integer > itm, List< Double > rat, int nIts)
Definition at line 183 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser(), moa.recommender.rc.predictor.impl.BRISMFPredictor.updateNewUser(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
{
        userFeature.put(userID, trainUserFeats(itm, rat, nIts));
    }
float [] moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats (List< Integer > itm, List< Double > rat, int nIts)
Definition at line 137 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature, moa.recommender.rc.predictor.impl.BRISMFPredictor.lRate, moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures, moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.resetFeatures(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.rFactor.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
{
        float[] userFeats = new float[nFeatures];
        resetFeatures(userFeats, true);
        int n = itm.size();
        for (int k = 0; k < nIts; ++k) {
            for (int i = 0; i < n; ++i) {
                int itemID = itm.get(i);
                float[] itemFeats = itemFeature.get(itemID);
                double rating = rat.get(i);
                double pred = predictRating(userFeats, itemFeats);
                double err = rating - pred;
                if (itemFeats != null)
                    for (int j = 1; j < nFeatures; ++j)
                        userFeats[j] += lRate*(err*itemFeats[j] - rFactor*userFeats[j]);
            }
        }
        return userFeats;
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateNewItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 354 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem().
{
        if (!ratingUsers.isEmpty()) {
            trainItem(itemID, ratingUsers, ratings);
        }
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateNewUser (int userID, List< Integer > ratedItems, List< Double > ratings)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 346 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
{
        if (!ratedItems.isEmpty()) {
            trainUser(userID, ratedItems, ratings);
        }
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateRemoveItem (int itemID)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 367 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature.
{
        itemFeature.remove(itemID);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateRemoveRating (int userID, int itemID)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 430 of file BRISMFPredictor.java.
{
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateRemoveUser (int userID)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 362 of file BRISMFPredictor.java.
References moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature.
{
        userFeature.remove(userID);
    }
void moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating (int userID, int itemID, double rating)
Implements moa.recommender.rc.utils.Updatable.
Definition at line 375 of file BRISMFPredictor.java.
References moa.recommender.rc.data.RecommenderData.countRatingsItem(), moa.recommender.rc.data.RecommenderData.countRatingsUser(), moa.recommender.rc.predictor.impl.BRISMFPredictor.data, moa.recommender.rc.data.RecommenderData.getRatingsItem(), moa.recommender.rc.data.RecommenderData.getRatingsUser(), moa.recommender.rc.utils.SparseVector.iterator(), moa.recommender.rc.predictor.impl.BRISMFPredictor.rnd, moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
{
        double nUsr = data.countRatingsUser(userID);
        double nItm = data.countRatingsItem(itemID);
        double prob1 = Math.pow(0.99, nUsr);
        double prob2 = Math.pow(0.99, nItm);
        if (nUsr < 5 || rnd.nextDouble() < prob1) {
            SparseVector usrRats = data.getRatingsUser(userID);
            ArrayList<Integer> itm = new ArrayList<Integer>();
            ArrayList<Double> rat = new ArrayList<Double>();
            //Train user
            boolean found = false;
            Iterator<Pair<Integer, Double>> it = usrRats.iterator();
            while (it.hasNext()) {
                Pair<Integer, Double> p = it.next();
                itm.add(p.getFirst());
                if (p.getFirst() == itemID) {
                    found = true;
                    rat.add(rating);
                }
                else rat.add(p.getSecond());
            }
            if (!found) {
                itm.add(itemID);
                rat.add(rating);
            }
            trainUser(userID, itm, rat);
        }
        if (nItm < 5 || rnd.nextDouble() < prob2) {
            SparseVector itmRats = data.getRatingsItem(itemID);
            //Train item
            Iterator<Pair<Integer, Double>> it = itmRats.iterator();
            boolean found = false;
            ArrayList<Integer> usr = new ArrayList<Integer>();
            ArrayList<Double> rat = new ArrayList<Double>();
            while (it.hasNext()) {
                Pair<Integer, Double> p = it.next();
                usr.add(p.getFirst());
                if (p.getFirst() == userID) {
                    found = true;
                    rat.add(rating);
                }
                else rat.add(p.getSecond());
            }
            if (!found) {
                usr.add(itemID);
                rat.add(rating);
            }
            trainItem(itemID, usr, rat);
        }
    }
Member Data Documentation
RecommenderData moa.recommender.rc.predictor.impl.BRISMFPredictor.data [protected]
Definition at line 64 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.getData(), moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
HashMap<Integer, float[]> moa.recommender.rc.predictor.impl.BRISMFPredictor.itemFeature [protected]
Definition at line 67 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor(), moa.recommender.rc.predictor.impl.BRISMFPredictor.getItemFeatures(), moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateRemoveItem().
double moa.recommender.rc.predictor.impl.BRISMFPredictor.lRate = 0.01 [protected]
Definition at line 69 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats().
int moa.recommender.rc.predictor.impl.BRISMFPredictor.nFeatures [protected]
Definition at line 65 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.getNumFeatures(), moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats().
int moa.recommender.rc.predictor.impl.BRISMFPredictor.nIterations = 30 [protected]
Definition at line 71 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser().
double moa.recommender.rc.predictor.impl.BRISMFPredictor.rFactor = 0.02 [protected]
Definition at line 70 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUserFeats().
Random moa.recommender.rc.predictor.impl.BRISMFPredictor.rnd [protected]
Definition at line 68 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor(), moa.recommender.rc.predictor.impl.BRISMFPredictor.resetFeatures(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
HashMap<Integer, float[]> moa.recommender.rc.predictor.impl.BRISMFPredictor.userFeature [protected]
Definition at line 66 of file BRISMFPredictor.java.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor(), moa.recommender.rc.predictor.impl.BRISMFPredictor.getUserFeatures(), moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), moa.recommender.rc.predictor.impl.BRISMFPredictor.train(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItemFeats(), moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateRemoveUser().
The documentation for this class was generated from the following file:
main/java/moa/recommender/rc/predictor/impl/BRISMFPredictor.java