MOA: moa.clusterers.ClusterGenerator Class Reference
moa.clusterers.ClusterGenerator Class Reference
Public Member Functions
void resetLearningImpl ()
void trainOnInstanceImpl (Instance inst)
boolean implementsMicroClusterer ()
void setSourceClustering (Clustering source)
Clustering getMicroClusteringResult ()
Clustering getClusteringResult ()
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
boolean keepClassLabel ()
double[] getVotesForInstance (Instance inst)
Public Attributes
IntOption timeWindowOption
FloatOption radiusDecreaseOption
FloatOption radiusIncreaseOption
FloatOption positionOffsetOption
FloatOption clusterRemoveOption
FloatOption joinClustersOption
FloatOption clusterAddOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Private Member Functions
Clustering alterClustering (Clustering scclustering)
Clustering joinClusters (Clustering clustering)
Private Attributes
ArrayList< DataPoint > points
int instanceCounter
int windowCounter
Random random
Clustering sourceClustering = null
Static Private Attributes
static final long serialVersionUID = 1L
static double err_intervall_width = 0.0
Detailed Description
Definition at line 34 of file ClusterGenerator.java.
Member Function Documentation
Clustering moa.clusterers.ClusterGenerator.alterClustering (Clustering scclustering) [private]
Definition at line 122 of file ClusterGenerator.java.
References moa.cluster.Clustering.add(), moa.clusterers.ClusterGenerator.clusterAddOption, moa.clusterers.AbstractClusterer.clustering, moa.clusterers.ClusterGenerator.clusterRemoveOption, moa.clusterers.ClusterGenerator.err_intervall_width, moa.cluster.Clustering.get(), moa.cluster.SphereCluster.getCenter(), moa.cluster.Cluster.getId(), moa.cluster.SphereCluster.getRadius(), moa.options.FloatOption.getValue(), moa.cluster.SphereCluster.getWeight(), moa.cluster.Cluster.getWeight(), moa.clusterers.ClusterGenerator.joinClusters(), moa.clusterers.ClusterGenerator.joinClustersOption, moa.clusterers.ClusterGenerator.positionOffsetOption, moa.clusterers.ClusterGenerator.radiusDecreaseOption, moa.clusterers.ClusterGenerator.radiusIncreaseOption, moa.clusterers.ClusterGenerator.random, moa.cluster.Clustering.remove(), moa.cluster.Cluster.setMeasureValue(), moa.cluster.SphereCluster.setWeight(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.ClusterGenerator.getClusteringResult(), and moa.clusterers.ClusterGenerator.getMicroClusteringResult().
{
        //percentage of the radius that will be cut off
        //0: no changes to radius
        //1: radius of 0
        double errLevelRadiusDecrease = radiusDecreaseOption.getValue();
        //0: no changes to radius
        //1: radius 100% bigger
        double errLevelRadiusIncrease = radiusIncreaseOption.getValue();
        //0: no changes
        //1: distance between centers is 2 * original radius
        double errLevelPosition = positionOffsetOption.getValue();
        int numRemoveCluster = (int)(clusterRemoveOption.getValue()*scclustering.size());
        int numAddCluster = (int)(clusterAddOption.getValue()*scclustering.size());
        for (int c = 0; c < numRemoveCluster; c++) {
            int delId = random.nextInt(scclustering.size());
            scclustering.remove(delId);
        }
        int numCluster = scclustering.size();
        double[] err_seeds = new double[numCluster];
        double err_seed_sum = 0.0;
        double tmp_seed;
        for (int i = 0; i < numCluster; i++) {
            tmp_seed = random.nextDouble();
            err_seeds[i] = err_seed_sum + tmp_seed;
            err_seed_sum+= tmp_seed;
        }
        double sumWeight = 0;
        for (int i = 0; i <numCluster; i++) {
            sumWeight+= scclustering.get(i).getWeight();
        }
        Clustering clustering = new Clustering();
        for (int i = 0; i <numCluster; i++) {
            if(!(scclustering.get(i) instanceof SphereCluster)){
                System.out.println("Not a Sphere Cluster");
                continue;
            }
            SphereCluster sourceCluster = (SphereCluster)scclustering.get(i);
            double[] center = Arrays.copyOf(sourceCluster.getCenter(),sourceCluster.getCenter().length);
            double weight = sourceCluster.getWeight();
            double radius = sourceCluster.getRadius();
            //move cluster center
            if(errLevelPosition >0){
                double errOffset = random.nextDouble()*err_intervall_width/2.0;
                double errOffsetDirection = ((random.nextBoolean())? 1 : -1);
                double level = errLevelPosition + errOffsetDirection * errOffset;
                double[] vector = new double[center.length];
                double vectorLength = 0;
                for (int d = 0; d < center.length; d++) {
                    vector[d] = (random.nextBoolean()?1:-1)*random.nextDouble();
                    vectorLength += Math.pow(vector[d],2);
                }
                vectorLength = Math.sqrt(vectorLength);
                //max is when clusters are next to each other
                double length = 2 * radius * level;
                for (int d = 0; d < center.length; d++) {
                    //normalize length and then strecht to reach error position
                    vector[d]=vector[d]/vectorLength*length;
                }
//                System.out.println("Center "+Arrays.toString(center));
//                System.out.println("Vector "+Arrays.toString(vector));
                //check if error position is within bounds
                double [] newCenter = new double[center.length];
                for (int d = 0; d < center.length; d++) {
                    //check bounds, otherwise flip vector
                    if(center[d] + vector[d] >= 0 && center[d] + vector[d] <= 1){
                        newCenter[d] = center[d] + vector[d];
                    }
                    else{
                        newCenter[d] = center[d] + (-1)*vector[d];
                    }
                }
                center = newCenter;
                for (int d = 0; d < center.length; d++) {
                    if(newCenter[d] >= 0 && newCenter[d] <= 1){
                    }
                    else{
                        System.out.println("This shouldnt have happend, Cluster center out of bounds:"+Arrays.toString(newCenter));
                    }
                }
                //System.out.println("new Center "+Arrays.toString(newCenter));
            }
            //alter radius
            if(errLevelRadiusDecrease > 0 || errLevelRadiusIncrease > 0){
                double errOffset = random.nextDouble()*err_intervall_width/2.0;
                int errOffsetDirection = ((random.nextBoolean())? 1 : -1);
                if(errLevelRadiusDecrease > 0 && (errLevelRadiusIncrease == 0 || random.nextBoolean())){
                    double level = (errLevelRadiusDecrease + errOffsetDirection * errOffset);//*sourceCluster.getWeight()/sumWeight;
                    level = (level<0)?0:level;
                    level = (level>1)?1:level;
                    radius*=(1-level);
                }
                else{
                    double level = errLevelRadiusIncrease + errOffsetDirection * errOffset;
                    level = (level<0)?0:level;
                    level = (level>1)?1:level;
                    radius+=radius*level;
                }
            }
            SphereCluster newCluster = new SphereCluster(center, radius, weight);
            newCluster.setMeasureValue("Source Cluster", "C"+sourceCluster.getId());
            clustering.add(newCluster);
        }
        if(joinClustersOption.getValue() > 0){
            clustering = joinClusters(clustering);
        }
        //add new clusters by copying clusters and set a random center
        for (int c = 0; c < numAddCluster; c++) {
            int copyId = random.nextInt(clustering.size());
            SphereCluster scorg = (SphereCluster)clustering.get(copyId);
            int dim = scorg.getCenter().length;
            double[] center = new double [dim];
            double radius = scorg.getRadius();
            boolean outofbounds = true;
            int tryCounter = 0;
            while(outofbounds && tryCounter < 20){
                tryCounter++;
                outofbounds = false;
                for (int j = 0; j < center.length; j++) {
                     center[j] = random.nextDouble();
                     if(center[j]- radius < 0 || center[j] + radius > 1){
                        outofbounds = true;
                        break;
                     }
                }
            }
            if(outofbounds){
                System.out.println("Coludn't place additional cluster");
            }
            else{
                SphereCluster scnew = new SphereCluster(center, radius, scorg.getWeight()/2);
                scorg.setWeight(scorg.getWeight()-scnew.getWeight());
                clustering.add(scnew);
            }
        }
        return clustering;
    }
Clustering moa.clusterers.ClusterGenerator.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 112 of file ClusterGenerator.java.
References moa.clusterers.ClusterGenerator.alterClustering(), moa.clusterers.ClusterGenerator.points, and moa.clusterers.ClusterGenerator.sourceClustering.
{
        sourceClustering = new Clustering(points);
//        if(sourceClustering == null){
//            System.out.println("You need to set a source clustering for the ClusterGenerator to work");
//            return null;
//        }
        return alterClustering(sourceClustering);
    }
Clustering moa.clusterers.ClusterGenerator.getMicroClusteringResult ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 99 of file ClusterGenerator.java.
References moa.clusterers.ClusterGenerator.alterClustering(), and moa.clusterers.ClusterGenerator.sourceClustering.
{
        //System.out.println("Numcluster:"+clustering.size()+" / "+num);
        //Clustering source_clustering = new Clustering(points, overlapThreshold, microInitMinPoints);
        if(sourceClustering == null){
            System.out.println("You need to set a source clustering for the ClusterGenerator to work");
            return null;
        }
        return alterClustering(sourceClustering);
    }
void moa.clusterers.ClusterGenerator.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 348 of file ClusterGenerator.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
Measurement [] moa.clusterers.ClusterGenerator.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 343 of file ClusterGenerator.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
double [] moa.clusterers.ClusterGenerator.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 362 of file ClusterGenerator.java.
{
        return null;
    }
boolean moa.clusterers.ClusterGenerator.implementsMicroClusterer ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 89 of file ClusterGenerator.java.
{
        return true;
    }
boolean moa.clusterers.ClusterGenerator.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 353 of file ClusterGenerator.java.
{
        return false;
    }
Clustering moa.clusterers.ClusterGenerator.joinClusters (Clustering clustering) [private]
Definition at line 285 of file ClusterGenerator.java.
References moa.cluster.Clustering.add(), moa.cluster.Clustering.get(), moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getHullDistance(), moa.cluster.SphereCluster.getRadius(), moa.options.FloatOption.getValue(), moa.cluster.SphereCluster.getWeight(), moa.clusterers.ClusterGenerator.joinClustersOption, moa.cluster.SphereCluster.merge(), and moa.cluster.Clustering.size().
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
{
        double radiusFactor = joinClustersOption.getValue();
        boolean[] merged = new boolean[clustering.size()];
        Clustering mclustering = new Clustering();
        if(radiusFactor >0){
            for (int c1 = 0; c1 < clustering.size(); c1++) {
                SphereCluster sc1 = (SphereCluster) clustering.get(c1);
                double minDist = Double.MAX_VALUE;
                double minOver = 1;
                int maxindexCon = -1;
                int maxindexOver = -1;
                for (int c2 = 0; c2 < clustering.size(); c2++) {
                    SphereCluster sc2 = (SphereCluster) clustering.get(c2);
//                    double over = sc1.overlapRadiusDegree(sc2);
//                    if(over > 0 && over < minOver){
//                       minOver = over;
//                       maxindexOver = c2;
//                    }
                    double dist = sc1.getHullDistance(sc2);
                    double threshold = Math.min(sc1.getRadius(), sc2.getRadius())*radiusFactor;
                    if(dist > 0 && dist < minDist && dist < threshold){
                            minDist = dist;
                            maxindexCon = c2;
                    }
                }
                int maxindex = -1;
                if(maxindexOver!=-1)
                    maxindex = maxindexOver;
                else
                    maxindex = maxindexCon;
                if(maxindex!=-1 && !merged[c1]){
                    merged[c1]=true;
                    merged[maxindex]=true;
                    SphereCluster scnew = new SphereCluster(sc1.getCenter(),sc1.getRadius(),sc1.getWeight());
                    SphereCluster sc2 = (SphereCluster) clustering.get(maxindex);
                    scnew.merge(sc2);
                    mclustering.add(scnew);
                }
            }
        }
        for (int i = 0; i < merged.length; i++) {
            if(!merged[i])
                 mclustering.add(clustering.get(i));
        }
        return mclustering;
    }
boolean moa.clusterers.ClusterGenerator.keepClassLabel ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 358 of file ClusterGenerator.java.
{
        return true;
    }
void moa.clusterers.ClusterGenerator.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 67 of file ClusterGenerator.java.
References moa.clusterers.ClusterGenerator.instanceCounter, moa.clusterers.ClusterGenerator.points, moa.clusterers.ClusterGenerator.random, and moa.clusterers.ClusterGenerator.windowCounter.
{
        points = new ArrayList<DataPoint>();
        instanceCounter = 0;
        windowCounter = 0;
        random = new Random(227);
        //joinClustersOption.set();
        //evaluateMicroClusteringOption.set();
    }
void moa.clusterers.ClusterGenerator.setSourceClustering (Clustering source)
Definition at line 94 of file ClusterGenerator.java.
References moa.clusterers.ClusterGenerator.sourceClustering.
{
        sourceClustering = source;
    }
void moa.clusterers.ClusterGenerator.trainOnInstanceImpl (Instance inst) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 78 of file ClusterGenerator.java.
References moa.options.IntOption.getValue(), moa.clusterers.ClusterGenerator.instanceCounter, moa.clusterers.ClusterGenerator.points, moa.clusterers.ClusterGenerator.timeWindowOption, and moa.clusterers.ClusterGenerator.windowCounter.
{
        if(windowCounter >= timeWindowOption.getValue()){
            points.clear();
            windowCounter = 0;
        }
        windowCounter++;
        instanceCounter++;
        points.add( new DataPoint(inst,instanceCounter));
    }
Member Data Documentation
FloatOption moa.clusterers.ClusterGenerator.clusterAddOption
Initial value:
 new FloatOption("clusterAdd", 'A',
                "Adds additional clusters.", 0, 0, 1)
Definition at line 56 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
FloatOption moa.clusterers.ClusterGenerator.clusterRemoveOption
Initial value:
 new FloatOption("clusterRemove", 'D',
                "Deletes complete clusters from the clustering.", 0, 0, 1)
Definition at line 50 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
double moa.clusterers.ClusterGenerator.err_intervall_width = 0.0 [static, private]
Definition at line 59 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
int moa.clusterers.ClusterGenerator.instanceCounter [private]
Definition at line 61 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.resetLearningImpl(), and moa.clusterers.ClusterGenerator.trainOnInstanceImpl().
FloatOption moa.clusterers.ClusterGenerator.joinClustersOption
Initial value:
 new FloatOption("joinClusters", 'j',
            "Join two clusters if their hull distance is less minRadius times this factor.", 0, 0, 1)
Definition at line 53 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), and moa.clusterers.ClusterGenerator.joinClusters().
ArrayList<DataPoint> moa.clusterers.ClusterGenerator.points [private]
Definition at line 60 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.getClusteringResult(), moa.clusterers.ClusterGenerator.resetLearningImpl(), and moa.clusterers.ClusterGenerator.trainOnInstanceImpl().
FloatOption moa.clusterers.ClusterGenerator.positionOffsetOption
Initial value:
 new FloatOption("positionOffset", 'p',
                "The average radii of the centroids in the model.", 0, 0, 1)
Definition at line 47 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
FloatOption moa.clusterers.ClusterGenerator.radiusDecreaseOption
Initial value:
 new FloatOption("radiusDecrease", 'r',
                "The average radii of the centroids in the model.", 0, 0, 1)
Definition at line 41 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
FloatOption moa.clusterers.ClusterGenerator.radiusIncreaseOption
Initial value:
 new FloatOption("radiusIncrease", 'R',
                "The average radii of the centroids in the model.", 0, 0, 1)
Definition at line 44 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
Random moa.clusterers.ClusterGenerator.random [private]
Definition at line 63 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), and moa.clusterers.ClusterGenerator.resetLearningImpl().
final long moa.clusterers.ClusterGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 36 of file ClusterGenerator.java.
Clustering moa.clusterers.ClusterGenerator.sourceClustering = null [private]
Definition at line 64 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.getClusteringResult(), moa.clusterers.ClusterGenerator.getMicroClusteringResult(), and moa.clusterers.ClusterGenerator.setSourceClustering().
IntOption moa.clusterers.ClusterGenerator.timeWindowOption
Initial value:
 new IntOption("timeWindow",
            't', "Rang of the window.", 1000)
Definition at line 38 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.trainOnInstanceImpl().
int moa.clusterers.ClusterGenerator.windowCounter [private]
Definition at line 62 of file ClusterGenerator.java.
Referenced by moa.clusterers.ClusterGenerator.resetLearningImpl(), and moa.clusterers.ClusterGenerator.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/ClusterGenerator.java