MOA: moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension Class Reference
moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension Class Reference
The class that splits a KDTree node based on the midpoint value of a dimension in which the node's points have the widest spread.
Public Member Functions
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
void splitNode (KDTreeNode node, int numNodesCreated, double[][] nodeRanges, double[][] universe) throws Exception
Splits a node into two based on the midpoint value of the dimension in which the points have the widest spread.
Protected Member Functions
int rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal)
Re-arranges the indices array such that the points <= to the splitVal are on the left of the array and those > the splitVal are on the right.
Static Private Attributes
static final long serialVersionUID = -7617277960046591906L
for serialization.
Detailed Description
The class that splits a KDTree node based on the midpoint value of a dimension in which the node's points have the widest spread.
For more information see also:
Andrew Moore (1991). A tutorial on kd-trees.
BibTeX:
 &#64;techreport{Moore1991,
    author = {Andrew Moore},
    booktitle = {University of Cambridge Computer Laboratory Technical Report No. 209},
    howpublished = {Extract from PhD Thesis},
    title = {A tutorial on kd-trees},
    year = {1991},
    HTTP = {http://www.autonlab.org/autonweb/14665.html}
 }
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 54 of file MidPointOfWidestDimension.java.
Member Function Documentation
String moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Definition at line 66 of file MidPointOfWidestDimension.java.
{
    return
        "The class that splits a KDTree node based on the midpoint value of "
      + "a dimension in which the node's points have the widest spread.\n\n"
      + "For more information see also:\n\n";
  }
int moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal) [protected]
Re-arranges the indices array such that the points <= to the splitVal are on the left of the array and those > the splitVal are on the right.
Parameters:
indices The master index array.
startidx The begining index of portion of indices that needs re-arranging.
endidx The end index of portion of indices that needs re-arranging.
splitDim The split dimension/attribute.
splitVal The split value.
Returns:
The startIdx of the points > the splitVal (the points belonging to the right child of the node).
Definition at line 140 of file MidPointOfWidestDimension.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, and moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual().
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.splitNode().
{
    int tmp, left = startidx - 1;
    for (int i = startidx; i <= endidx; i++) {
      if (m_EuclideanDistance.valueIsSmallerEqual(m_Instances
          .instance(indices[i]), splitDim, splitVal)) {
        left++;
        tmp = indices[left];
        indices[left] = indices[i];
        indices[i] = tmp;
      }//end if valueIsSmallerEqual
    }//end for
    return left + 1;
  }
void moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.splitNode (KDTreeNode node, int numNodesCreated, double nodeRanges[][], double universe[][]) throws Exception [virtual]
Splits a node into two based on the midpoint value of the dimension in which the points have the widest spread.
After splitting two new nodes are created and correctly initialised. And, node.left and node.right are set appropriately.
Parameters:
node The node to split.
numNodesCreated The number of nodes that so far have been created for the tree, so that the newly created nodes are assigned correct/meaningful node numbers/ids.
nodeRanges The attributes' range for the points inside the node that is to be split.
universe The attributes' range for the whole point-space.
Exceptions:
Exception If there is some problem in splitting the given node.
Implements moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.
Definition at line 90 of file MidPointOfWidestDimension.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.correctlyInitialized(), moa.classifiers.lazy.neighboursearch.EuclideanDistance.getMiddle(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_InstList, moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.rearrangePoints(), and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.widestDim().
{
    correctlyInitialized();
    int splitDim = widestDim(nodeRanges, universe);
    double splitVal = m_EuclideanDistance.getMiddle(nodeRanges[splitDim]);
    int rightStart = rearrangePoints(m_InstList, node.m_Start, node.m_End,
        splitDim, splitVal);
    if (rightStart == node.m_Start || rightStart > node.m_End) {
      if (rightStart == node.m_Start)
        throw new Exception("Left child is empty in node "
                            + node.m_NodeNumber +
                            ". Not possible with " +
                            "MidPointofWidestDim splitting method. Please " +
                            "check code.");
      else
        throw new Exception("Right child is empty in node " + node.m_NodeNumber +
                            ". Not possible with " +
                            "MidPointofWidestDim splitting method. Please " +
                            "check code.");
    }
    node.m_SplitDim = splitDim;
    node.m_SplitValue = splitVal;
    node.m_Left = new KDTreeNode(numNodesCreated + 1, node.m_Start,
        rightStart - 1, m_EuclideanDistance.initializeRanges(m_InstList,
            node.m_Start, rightStart - 1));
    node.m_Right = new KDTreeNode(numNodesCreated + 2, rightStart, node.m_End,
        m_EuclideanDistance
            .initializeRanges(m_InstList, rightStart, node.m_End));
  }
Member Data Documentation
final long moa.classifiers.lazy.neighboursearch.kdtrees.MidPointOfWidestDimension.serialVersionUID = -7617277960046591906L [static, private]
for serialization.
Definition at line 58 of file MidPointOfWidestDimension.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/kdtrees/MidPointOfWidestDimension.java