MOA: moa.evaluation.MembershipMatrix Class Reference
moa.evaluation.MembershipMatrix Class Reference
Public Member Functions
MembershipMatrix (Clustering foundClustering, ArrayList< DataPoint > points)
int getClusterClassWeight (int i, int j)
int getClusterSum (int i)
int getClassSum (int j)
int getClassDistribution (int j)
int getClusterClassWeightByLabel (int cluster, int classLabel)
int getClassSumByLabel (int classLabel)
int getClassDistributionByLabel (int classLabel)
int getTotalEntries ()
int getNumClasses ()
boolean hasNoiseClass ()
String toString ()
int getInitalBuildTimestamp ()
Package Attributes
HashMap< Integer, Integer > classmap
int cluster_class_weights [][]
int cluster_sums []
int class_sums []
int total_entries
int class_distribution []
int total_class_entries
int initalBuildTimestamp = -1
Detailed Description
Definition at line 29 of file MembershipMatrix.java.
Constructor & Destructor Documentation
moa.evaluation.MembershipMatrix.MembershipMatrix (Clustering foundClustering, ArrayList< DataPoint > points)
Definition at line 40 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_distribution, moa.evaluation.MembershipMatrix.class_sums, moa.evaluation.MembershipMatrix.classmap, moa.evaluation.MembershipMatrix.cluster_class_weights, moa.evaluation.MembershipMatrix.cluster_sums, moa.cluster.Clustering.get(), moa.cluster.Cluster.getInclusionProbability(), moa.evaluation.MembershipMatrix.initalBuildTimestamp, moa.cluster.Clustering.size(), moa.evaluation.MembershipMatrix.total_class_entries, and moa.evaluation.MembershipMatrix.total_entries.
{
        classmap = Clustering.classValues(points);
//        int lastID  = classmap.size()-1;
//        classmap.put(-1, lastID);
        int numClasses = classmap.size();
        int numCluster = foundClustering.size()+1;
        cluster_class_weights = new int[numCluster][numClasses];
        class_distribution = new int[numClasses];
        cluster_sums = new int[numCluster];
        class_sums = new int[numClasses];
        total_entries = 0;
        total_class_entries = points.size();
        for (int p = 0; p < points.size(); p++) {
            int worklabel = classmap.get((int)points.get(p).classValue());
            //real class distribution
            class_distribution[worklabel]++;
            boolean covered = false;
            for (int c = 0; c < numCluster-1; c++) {
                double prob = foundClustering.get(c).getInclusionProbability(points.get(p));
                if(prob >= 1){
                    cluster_class_weights[c][worklabel]++;
                    class_sums[worklabel]++;
                    cluster_sums[c]++;
                    total_entries++;
                    covered = true;
                }
            }
            if(!covered){
                cluster_class_weights[numCluster-1][worklabel]++;
                class_sums[worklabel]++;
                cluster_sums[numCluster-1]++;
                total_entries++;
            }
        }
        initalBuildTimestamp = points.get(0).getTimestamp();
    }
Member Function Documentation
int moa.evaluation.MembershipMatrix.getClassDistribution (int j)
Definition at line 92 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_distribution.
{
        return class_distribution[j];
    }
int moa.evaluation.MembershipMatrix.getClassDistributionByLabel (int classLabel)
Definition at line 104 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_distribution, and moa.evaluation.MembershipMatrix.classmap.
{
        return class_distribution[classmap.get(classLabel)];
    }
int moa.evaluation.MembershipMatrix.getClassSum (int j)
Definition at line 88 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_sums.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
{
        return class_sums[j];
    }
int moa.evaluation.MembershipMatrix.getClassSumByLabel (int classLabel)
Definition at line 100 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_sums, and moa.evaluation.MembershipMatrix.classmap.
{
        return class_sums[classmap.get(classLabel)];
    }
int moa.evaluation.MembershipMatrix.getClusterClassWeight (int i, int j)
Definition at line 80 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.cluster_class_weights.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
{
        return cluster_class_weights[i][j];
    }
int moa.evaluation.MembershipMatrix.getClusterClassWeightByLabel (int cluster, int classLabel)
Definition at line 96 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.classmap, and moa.evaluation.MembershipMatrix.cluster_class_weights.
{
        return cluster_class_weights[cluster][classmap.get(classLabel)];
    }
int moa.evaluation.MembershipMatrix.getClusterSum (int i)
Definition at line 84 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.cluster_sums.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
{
        return cluster_sums[i];
    }
int moa.evaluation.MembershipMatrix.getInitalBuildTimestamp ()
Definition at line 147 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.initalBuildTimestamp.
{
        return initalBuildTimestamp;
    }
int moa.evaluation.MembershipMatrix.getNumClasses ()
Definition at line 112 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.classmap.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
{
        return classmap.size();
    }
int moa.evaluation.MembershipMatrix.getTotalEntries ()
Definition at line 108 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.total_entries.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
{
        return total_entries;
    }
boolean moa.evaluation.MembershipMatrix.hasNoiseClass ()
Definition at line 116 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.classmap.
Referenced by moa.evaluation.F1.evaluateClustering().
{
        return classmap.containsKey(-1);
    }
String moa.evaluation.MembershipMatrix.toString ()
Definition at line 121 of file MembershipMatrix.java.
References moa.evaluation.MembershipMatrix.class_distribution, moa.evaluation.MembershipMatrix.class_sums, moa.evaluation.MembershipMatrix.cluster_class_weights, moa.evaluation.MembershipMatrix.cluster_sums, moa.evaluation.MembershipMatrix.total_class_entries, and moa.evaluation.MembershipMatrix.total_entries.
{
        StringBuffer sb = new StringBuffer();
        sb.append("Membership Matrix\n");
        for (int i = 0; i < cluster_class_weights.length; i++) {
            for (int j = 0; j < cluster_class_weights[i].length; j++) {
                sb.append(cluster_class_weights[i][j]+"\t ");
            }
            sb.append("| "+cluster_sums[i]+"\n");
        }
        //sb.append("-----------\n");
        for (int i = 0; i < class_sums.length; i++) {
            sb.append(class_sums[i]+"\t ");
        }
        sb.append("| "+total_entries+"\n");
        sb.append("Real class distribution \n");
        for (int i = 0; i < class_distribution.length; i++) {
            sb.append(class_distribution[i]+"\t ");
        }
        sb.append("| "+total_class_entries+"\n");
        return sb.toString();
    }
Member Data Documentation
int moa.evaluation.MembershipMatrix.class_distribution[] [package]
Definition at line 36 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getClassDistribution(), moa.evaluation.MembershipMatrix.getClassDistributionByLabel(), moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
int moa.evaluation.MembershipMatrix.class_sums[] [package]
Definition at line 34 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getClassSum(), moa.evaluation.MembershipMatrix.getClassSumByLabel(), moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
HashMap<Integer, Integer> moa.evaluation.MembershipMatrix.classmap [package]
Definition at line 31 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getClassDistributionByLabel(), moa.evaluation.MembershipMatrix.getClassSumByLabel(), moa.evaluation.MembershipMatrix.getClusterClassWeightByLabel(), moa.evaluation.MembershipMatrix.getNumClasses(), moa.evaluation.MembershipMatrix.hasNoiseClass(), and moa.evaluation.MembershipMatrix.MembershipMatrix().
int moa.evaluation.MembershipMatrix.cluster_class_weights[][] [package]
Definition at line 32 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getClusterClassWeight(), moa.evaluation.MembershipMatrix.getClusterClassWeightByLabel(), moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
int moa.evaluation.MembershipMatrix.cluster_sums[] [package]
Definition at line 33 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getClusterSum(), moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
int moa.evaluation.MembershipMatrix.initalBuildTimestamp = -1 [package]
Definition at line 38 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getInitalBuildTimestamp(), and moa.evaluation.MembershipMatrix.MembershipMatrix().
int moa.evaluation.MembershipMatrix.total_class_entries [package]
Definition at line 37 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
int moa.evaluation.MembershipMatrix.total_entries [package]
Definition at line 35 of file MembershipMatrix.java.
Referenced by moa.evaluation.MembershipMatrix.getTotalEntries(), moa.evaluation.MembershipMatrix.MembershipMatrix(), and moa.evaluation.MembershipMatrix.toString().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/MembershipMatrix.java