MOA: moa.tasks.RunTasks Class Reference
moa.tasks.RunTasks Class Reference
Task for running several experiments modifying values of parameters.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption taskOption
StringOption classifierParameterOption
FloatOption firstValueOption
FloatOption lastValueOption
FloatOption incrementValueOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Protected Attributes
Task task
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for running several experiments modifying values of parameters.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 35 of file RunTasks.java.
Member Function Documentation
Object moa.tasks.RunTasks.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 67 of file RunTasks.java.
References moa.tasks.RunTasks.classifierParameterOption, moa.tasks.Task.doTask(), moa.tasks.RunTasks.firstValueOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.StringOption.getValue(), moa.options.FloatOption.getValue(), moa.options.ClassOption.getValueAsCLIString(), moa.tasks.RunTasks.incrementValueOption, moa.tasks.RunTasks.lastValueOption, moa.tasks.RunTasks.task, and moa.tasks.RunTasks.taskOption.
{
        Object result = null;
        String commandString = this.taskOption.getValueAsCLIString();
        //for each possible value of the parameter
        for (double valueParameter = this.firstValueOption.getValue();
                valueParameter <= this.lastValueOption.getValue();
                valueParameter += this.incrementValueOption.getValue()) {
            //Add parameter
            this.task = (Task) getPreparedClassOption(this.taskOption);
            if (this.task instanceof EvaluatePrequential) {
                String classifier = ((EvaluatePrequential) this.task).learnerOption.getValueAsCLIString();
                ((EvaluatePrequential) this.task).learnerOption.setValueViaCLIString(classifier + " -" + classifierParameterOption.getValue() + " " + valueParameter);
            }
            if (this.task instanceof EvaluateInterleavedTestThenTrain) {
                String classifier = ((EvaluateInterleavedTestThenTrain) this.task).learnerOption.getValueAsCLIString();
                ((EvaluateInterleavedTestThenTrain) this.task).learnerOption.setValueViaCLIString(classifier + " -" + classifierParameterOption.getValue() + " " + valueParameter);
            }
            //Run task
            result = this.task.doTask(monitor, repository);
            //System.out.println(((AbstractOptionHandler) this.task).getCLICreationString(Task.class));
        }
        return result;
    }
String moa.tasks.RunTasks.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 38 of file RunTasks.java.
{
        return "Runs several experiments modifying values of parameters.";
    }
Class<?> moa.tasks.RunTasks.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 60 of file RunTasks.java.
References moa.tasks.Task.getTaskResultType(), and moa.tasks.RunTasks.task.
{
        return this.task.getTaskResultType();
    }
Member Data Documentation
StringOption moa.tasks.RunTasks.classifierParameterOption
Initial value:
 new StringOption("classifierParameter", 'p',
            "Classifier parameter to vary.", "b")
Definition at line 47 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask().
FloatOption moa.tasks.RunTasks.firstValueOption
Initial value:
 new FloatOption("firstValue",
            'f', "First value", 0.0)
Definition at line 50 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask().
FloatOption moa.tasks.RunTasks.incrementValueOption
Initial value:
 new FloatOption("incrementValue",
            'i', "Increment value", 0.1)
Definition at line 56 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask().
FloatOption moa.tasks.RunTasks.lastValueOption
Initial value:
 new FloatOption("lastValue",
            'l', "Last value", 1.0)
Definition at line 53 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask().
final long moa.tasks.RunTasks.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 42 of file RunTasks.java.
Task moa.tasks.RunTasks.task [protected]
Definition at line 64 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask(), and moa.tasks.RunTasks.getTaskResultType().
ClassOption moa.tasks.RunTasks.taskOption
Initial value:
 new ClassOption("task", 't',
            "Task to do.", Task.class, "EvaluatePrequential -l active.ActiveClassifier -i 1000000 -d temp.txt")
Definition at line 44 of file RunTasks.java.
Referenced by moa.tasks.RunTasks.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/RunTasks.java