MOA: moa.classifiers.trees.ORTO.ActiveLearningNode Class Reference
moa.classifiers.trees.ORTO.ActiveLearningNode Class Reference
Public Member Functions
ActiveLearningNode (int id)
int calcByteSize ()
AttributeSplitSuggestion[] getBestSplitSuggestions (SplitCriterion criterion, ORTO tree)
Return the best split suggestions for this node using the given split criteria.
void disableAttribute (int attIndex)
double getPHError (Instance inst)
double getSquaredError ()
Returns the squared error, for use in determining if an alternate tree is performing better than an original tree, or if the alternate tree should be deleted.
double getError (Instance inst)
Return the error for a given instance.
double[] processInstance (Instance inst, ORTO tree)
double[] getPrediction (Instance inst, ORTO tree)
Public Attributes
ORTOPerceptron learningModel = new ORTOPerceptron()
Protected Attributes
DoubleVector nodeStatistics = new DoubleVector()
DoubleVector splitRatioStatistics = new DoubleVector()
double PHmT = 0
double PHMT = Double.MAX_VALUE
int examplesSeenAtLastSplitEvaluation
int examplesSeen = 0
AutoExpandVector
< AttributeClassObserver > attributeObservers = new AutoExpandVector<AttributeClassObserver>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 735 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.ActiveLearningNode.ActiveLearningNode (int id)
Definition at line 761 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            super(id);
            this.learningModel = new ORTOPerceptron();
        }
Member Function Documentation
int moa.classifiers.trees.ORTO.ActiveLearningNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 767 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel.
{
            return super.calcByteSize() + (int) (SizeOf.fullSizeOf(this.attributeObservers)) + (int) (SizeOf.fullSizeOf(this.learningModel));
        }
void moa.classifiers.trees.ORTO.ActiveLearningNode.disableAttribute (int attIndex)
Definition at line 797 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.attributeObservers.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            this.attributeObservers.set(attIndex, new NullAttributeClassObserver());
        }
AttributeSplitSuggestion [] moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions (SplitCriterion criterion, ORTO tree)
Return the best split suggestions for this node using the given split criteria.
Definition at line 774 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.attributeObservers, moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.getBestEvaluatedSplitSuggestion(), and moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            List<AttributeSplitSuggestion> bestSuggestions = new LinkedList<AttributeSplitSuggestion>();
            // Set the nodeStatistics up as the preSplitDistribution, rather than the observedClassDistribution
            double[] nodeSplitDist = this.nodeStatistics.getArrayCopy();
            for (int i = 0; i < this.attributeObservers.size(); i++) {
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs != null) {
                    // AT THIS STAGE NON-NUMERIC ATTRIBUTES ARE IGNORED
                    AttributeSplitSuggestion bestSuggestion = null;
                    if (obs instanceof FIMTDDNumericAttributeClassObserver) {
                        bestSuggestion = obs.getBestEvaluatedSplitSuggestion(criterion, nodeSplitDist, i, true /*ht.binarySplitsOption.isSet()*/);
                    }
                    if (bestSuggestion != null) {
                        bestSuggestions.add(bestSuggestion);
                    }
                }
            }
            return bestSuggestions.toArray(new AttributeSplitSuggestion[bestSuggestions.size()]);
        }
double moa.classifiers.trees.ORTO.ActiveLearningNode.getError (Instance inst)
Return the error for a given instance.
Definition at line 819 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel, and moa.classifiers.trees.ORTO.ORTOPerceptron.prediction().
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
        {
            return inst.classValue() - learningModel.prediction(inst);
        }
double moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError (Instance inst)
Definition at line 801 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeen, moa.core.DoubleVector.getValue(), moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel, moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics, and moa.classifiers.trees.ORTO.ORTOPerceptron.prediction().
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            double sd = Math.sqrt((nodeStatistics.getValue(2) - ((nodeStatistics.getValue(1) * nodeStatistics.getValue(1))/nodeStatistics.getValue(1)))/examplesSeen);
            double mean = nodeStatistics.getValue(2) / nodeStatistics.getValue(1);
            //     AbsErr(inst) - (SumAbsErr + AbsErr(inst)) / (N + 1)   || SumAbsErr only contains errors for the first N examples and not the last one
            return Math.abs( (inst.classValue() - learningModel.prediction(inst)) / sd ) - ((nodeStatistics.getValue(3) + Math.abs(((inst.classValue()-mean)/sd) - ((learningModel.prediction(inst)-mean)/sd))) / (nodeStatistics.getValue(1)+1));
        }
double [] moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 1031 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeen, moa.core.DoubleVector.getValue(), moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel, moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics, and moa.classifiers.trees.ORTO.ORTOPerceptron.prediction().
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            return new double[] {this.learningModel.prediction(inst), this.nodeStatistics.getValue(4), this.examplesSeen};
        }
double moa.classifiers.trees.ORTO.ActiveLearningNode.getSquaredError ()
Returns the squared error, for use in determining if an alternate tree is performing better than an original tree, or if the alternate tree should be deleted.
Definition at line 812 of file ORTO.java.
References moa.core.DoubleVector.getValue(), and moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics.
{
            return nodeStatistics.getValue(4);
        }
double [] moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 824 of file ORTO.java.
References moa.classifiers.trees.ORTO.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.ORTO.Node.Adaptable, moa.core.DoubleVector.addToValue(), moa.classifiers.trees.ORTO.AlternateTreeFadingFactorOption, moa.classifiers.trees.ORTO.ActiveLearningNode.attributeObservers, moa.classifiers.trees.ORTO.computeHoeffdingBound(), moa.classifiers.trees.ORTO.ActiveLearningNode.disableAttribute(), moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeen, moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeenAtLastSplitEvaluation, moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn(), moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.ORTO.InnerNode.getChildIndex(), moa.classifiers.trees.ORTO.ActiveLearningNode.getError(), moa.classifiers.trees.ORTO.Node.getLevel(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.trees.ORTO.gracePeriodOption, moa.classifiers.trees.ORTO.innerNodeCount, moa.options.FlagOption.isSet, moa.classifiers.trees.ORTO.leafNodeCount, moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel, moa.classifiers.trees.ORTO.maxID, moa.classifiers.trees.ORTO.MaxOptionLevelOption, moa.classifiers.trees.ORTO.MaxTreesOption, moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.ORTO.newNumericClassObserver(), moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics, moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.trees.ORTO.numTrees, moa.classifiers.trees.ORTO.OptionDecayFactorOption, moa.classifiers.trees.ORTO.optionNodeCount, moa.classifiers.trees.ORTO.Node.parent, moa.classifiers.trees.ORTO.removePoorAttsOption, moa.classifiers.trees.ORTO.OptionNode.resetFF(), moa.classifiers.trees.ORTO.InnerNode.setChild(), moa.classifiers.trees.ORTO.SplitNode.setChild(), moa.classifiers.trees.ORTO.Node.setParent(), moa.core.DoubleVector.setValue(), moa.classifiers.trees.ORTO.splitConfidenceOption, moa.classifiers.trees.ORTO.splitCriterionOption, moa.classifiers.core.AttributeSplitSuggestion.splitTest, moa.classifiers.trees.ORTO.tieThresholdOption, moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl(), and moa.classifiers.trees.ORTO.treeRoot.
{
            double prediction = getPrediction(inst, tree)[0];
            examplesSeen++;
            // Update the statistics for this node
            // number of instances passing through the node
            nodeStatistics.addToValue(0, 1);
            // sum of y values
            // sum of squared y values
            nodeStatistics.addToValue(2, inst.classValue() * inst.classValue());
            // sum of absolute errors
            // Normalize values prior to calculating absolute error
            double sd = Math.sqrt((nodeStatistics.getValue(2) - ((nodeStatistics.getValue(1) * nodeStatistics.getValue(1))/examplesSeen))/examplesSeen);
            double error = this.getError(inst);
            nodeStatistics.addToValue(3, Math.abs(error / sd));
            // sum of squared errors
            // nodeStatistics.addToValue(4, error * error);
            nodeStatistics.setValue(4, nodeStatistics.getValue(4) * tree.AlternateTreeFadingFactorOption.getValue() + error * error);
            double ph = getPHError(inst);
            learningModel.trainOnInstanceImpl(inst, tree);
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    // At this stage all nominal attributes are ignored
                    if (inst.attribute(instAttIndex).isNumeric()) {
                        obs = tree.newNumericClassObserver();
                        this.attributeObservers.set(i, obs);
                    }
                }
                if (obs != null) {
                    ((FIMTDDNumericAttributeClassObserver) obs).observeAttributeClass(inst.value(instAttIndex), inst.classValue(), inst.weight());
                }
            }
            // If it has seen Nmin examples since it was last tested for splitting, attempt a split of this node
            if (examplesSeen - examplesSeenAtLastSplitEvaluation >= tree.gracePeriodOption.getValue()) {
                // Set the split criterion to use to the SDR split criterion as described by Ikonomovska et al.
                SplitCriterion splitCriterion = (SplitCriterion) tree.getPreparedClassOption(tree.splitCriterionOption);
                // Using this criterion, find the best split per attribute and rank the results
                AttributeSplitSuggestion[] bestSplitSuggestions = getBestSplitSuggestions(splitCriterion, tree);
                List<AttributeSplitSuggestion> acceptedSplits = new LinkedList<AttributeSplitSuggestion>();
                Arrays.sort(bestSplitSuggestions);
                // Declare a variable to determine the number of splits to be performed
                int numSplits = 0;
                // If only one split was returned, use it
                if (bestSplitSuggestions.length == 1) {
                    numSplits = 1;
                    acceptedSplits.add(bestSplitSuggestions[0]);
                } else if (bestSplitSuggestions.length > 1) { // Otherwise, consider which of the splits proposed may be worth trying
                    // Determine the Hoeffding bound value, used to select how many instances should be used to make a test decision
                    // to feel reasonably confident that the test chosen by this sample is the same as what would be chosen using infinite examples
                    double hoeffdingBound = computeHoeffdingBound(1, tree.splitConfidenceOption.getValue(), examplesSeen);
                    // Determine the top two ranked splitting suggestions
                    AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                    AttributeSplitSuggestion secondBestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 2];
                    // assert false : bestSuggestion.merit;
                    // If the upper bound of the sample mean for the ratio of SDR(best suggestion) to SDR(second best suggestion),
                    // as determined using the Hoeffding bound, is less than 1, then the true mean is also less than 1, and thus at this
                    // particular moment of observation the bestSuggestion is indeed the best split option with confidence 1-delta, and
                    // splitting should occur.
                    // Alternatively, if two or more splits are very similar or identical in terms of their splits, then a threshold limit
                    // (default 0.05) is applied to the Hoeffding bound; if the Hoeffding bound is smaller than this limit then the two
                    // competing attributes are equally good, and the split will be made on the one with the higher SDR value.
                    if (secondBestSuggestion.merit / bestSuggestion.merit < 1 - hoeffdingBound) {
                        numSplits = 1;
                        acceptedSplits.add(bestSuggestion);
                    } else if (tree.numTrees < tree.MaxTreesOption.getValue() && getLevel() <= tree.MaxOptionLevelOption.getValue()) {
                        for (AttributeSplitSuggestion suggestion : bestSplitSuggestions) {
                            if (suggestion.merit / bestSuggestion.merit >= 1 - hoeffdingBound) {
                                numSplits++;
                                acceptedSplits.add(suggestion);
                            }
                        }
                    } else if (hoeffdingBound < tree.tieThresholdOption.getValue()) {
                        numSplits = 1;
                        acceptedSplits.add(bestSplitSuggestions[0]);
                    } else { // If the splitting criterion was not met, initiate pruning of the E-BST structures in each attribute observer
                        for (int i = 0; i < attributeObservers.size(); i++) {
                            AttributeClassObserver obs = attributeObservers.get(i);
                            if (obs != null) {
                                ((FIMTDDNumericAttributeClassObserver) obs).removeBadSplits(splitCriterion, secondBestSuggestion.merit / bestSuggestion.merit, bestSuggestion.merit, hoeffdingBound);
                            }
                        }
                    }
                    // If the user has selected this option, it is also possible to remove poor attributes at this stage
                    if ((tree.removePoorAttsOption != null) && tree.removePoorAttsOption.isSet()) {
                        Set<Integer> poorAtts = new HashSet<Integer>();
                        for (int i = 0; i < bestSplitSuggestions.length; i++) { // scan 1 - add any poor to set
                            if (bestSplitSuggestions[i].splitTest != null) {
                                int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                                if (splitAtts.length == 1) {
                                    if (((bestSuggestion.merit / secondBestSuggestion.merit) + hoeffdingBound)  < 1) {
                                        poorAtts.add(new Integer(splitAtts[0]));
                                    }
                                }
                            }
                        }
                        for (int i = 0; i < bestSplitSuggestions.length; i++) { // scan 2 - remove good ones from set
                            if (bestSplitSuggestions[i].splitTest != null) {
                                int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                                if (splitAtts.length == 1) {
                                    if (((bestSuggestion.merit / secondBestSuggestion.merit) + hoeffdingBound)  < 1) {
                                        poorAtts.remove(new Integer(splitAtts[0]));
                                    }
                                }
                            }
                        }
                        for (int poorAtt : poorAtts) {
                            this.disableAttribute(poorAtt);
                        }
                    }
                }
                // assert numSplits == 0 : numSplits;
                // If the splitting criterion were met, split the current node using the chosen attribute test, and
                // make two new branches leading to (empty) leaves
                if (numSplits > 0) {
                    double optionFactor = numSplits * Math.pow(tree.OptionDecayFactorOption.getValue(), (double) getLevel());
                    // Deactivate this node if the best split was to do nothing
                    if (numSplits == 1 || optionFactor < 2.0 || tree.MaxTreesOption.getValue() - tree.numTrees  <= 1) {
                        AttributeSplitSuggestion splitDecision = acceptedSplits.get(0);
                        tree.maxID++;
                        SplitNode newSplit = new SplitNode(splitDecision.splitTest, tree.maxID);
                        newSplit.Adaptable = Adaptable;
                        for (int i = 0; i < splitDecision.numSplits(); i++) {
                            tree.maxID++;
                            ActiveLearningNode newChild = new ActiveLearningNode(tree.maxID);
                            newChild.setParent(newSplit);
                            newChild.Adaptable = Adaptable;
                            newSplit.setChild(i, newChild);
                        }
                        tree.leafNodeCount--;
                        tree.innerNodeCount++;
                        tree.leafNodeCount += splitDecision.numSplits();
                        if (parent == null) {
                            tree.treeRoot = newSplit;
                        } else {
                            parent.setChild(parent.getChildIndex(this), newSplit);
                            newSplit.setParent(parent);
                        }
                    } else {
                        tree.maxID++;
                        OptionNode optionNode = new OptionNode(tree.maxID);
                        optionNode.Adaptable = Adaptable;
                        tree.leafNodeCount--;
                        int j = 0;
                        for (AttributeSplitSuggestion splitDecision : acceptedSplits) {
                            if (j > optionFactor || tree.MaxTreesOption.getValue() - tree.numTrees <= 0) {
                                break;
                            }
                            tree.maxID++;
                            SplitNode newSplit = new SplitNode(splitDecision.splitTest, tree.maxID);
                            newSplit.Adaptable = Adaptable;
                            for (int i = 0; i < splitDecision.numSplits(); i++) {
                                tree.maxID++;
                                ActiveLearningNode newChild = new ActiveLearningNode(tree.maxID);
                                newChild.setParent(newSplit);
                                newSplit.setChild(i, newChild);
                                newChild.Adaptable = Adaptable;
                            }
                            tree.leafNodeCount += splitDecision.numSplits();
                            tree.innerNodeCount++;
                            tree.numTrees++;
                            newSplit.setParent(optionNode);
                            optionNode.setChild(j, newSplit);
                            j++;
                        }
                        tree.innerNodeCount++;
                        tree.optionNodeCount++;
                        if (parent == null) {
                            tree.treeRoot = optionNode;
                        } else {
                            parent.setChild(parent.getChildIndex(this), optionNode);
                            optionNode.setParent(parent);
                        }
                        optionNode.resetFF();
                    }
                }
                // Take note of how many instances were seen when this split evaluation was made, so we know when to perform the next split evaluation
                examplesSeenAtLastSplitEvaluation = examplesSeen;
            }
            return new double[] {prediction, nodeStatistics.getValue(4), examplesSeen, ph};
        }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.trees.ORTO.ActiveLearningNode.attributeObservers = new AutoExpandVector<AttributeClassObserver>() [protected]
Definition at line 759 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.disableAttribute(), moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
int moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeen = 0 [protected]
Definition at line 757 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
int moa.classifiers.trees.ORTO.ActiveLearningNode.examplesSeenAtLastSplitEvaluation [protected]
Definition at line 755 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
ORTOPerceptron moa.classifiers.trees.ORTO.ActiveLearningNode.learningModel = new ORTOPerceptron()
Definition at line 740 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.ORTO.ActiveLearningNode.calcByteSize(), moa.classifiers.trees.ORTO.ActiveLearningNode.getError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
DoubleVector moa.classifiers.trees.ORTO.ActiveLearningNode.nodeStatistics = new DoubleVector() [protected]
Definition at line 745 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), moa.classifiers.trees.ORTO.ActiveLearningNode.getSquaredError(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
double moa.classifiers.trees.ORTO.ActiveLearningNode.PHMT = Double.MAX_VALUE [protected]
Definition at line 753 of file ORTO.java.
double moa.classifiers.trees.ORTO.ActiveLearningNode.PHmT = 0 [protected]
Definition at line 752 of file ORTO.java.
final long moa.classifiers.trees.ORTO.ActiveLearningNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 737 of file ORTO.java.
DoubleVector moa.classifiers.trees.ORTO.ActiveLearningNode.splitRatioStatistics = new DoubleVector() [protected]
Definition at line 747 of file ORTO.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java