MOA: moa.classifiers.meta.OzaBag Class Reference
moa.classifiers.meta.OzaBag Class Reference
Incremental on-line bagging of Oza and Russell.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Incremental on-line bagging of Oza and Russell.
Oza and Russell developed online versions of bagging and boosting for Data Streams. They show how the process of sampling bootstrap replicates from training data can be simulated in a data stream context. They observe that the probability that any individual example will be chosen for a replicate tends to a Poisson(1) distribution.
[OR] N. Oza and S. Russell. Online bagging and boosting. In Artiﬁcial Intelligence and Statistics 2001, pages 105–112. Morgan Kaufmann, 2001.
Parameters:
-l : Classiﬁer to train
-s : The number of models in the bag
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 52 of file OzaBag.java.
Member Function Documentation
void moa.classifiers.meta.OzaBag.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.OzaBagASHT.
Definition at line 110 of file OzaBag.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.OzaBag.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 115 of file OzaBag.java.
References moa.classifiers.meta.OzaBag.ensemble.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0)};
    }
String moa.classifiers.meta.OzaBag.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.OzaBagASHT.
Definition at line 55 of file OzaBag.java.
{
        return "Incremental on-line bagging of Oza and Russell.";
    }
Classifier [] moa.classifiers.meta.OzaBag.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 121 of file OzaBag.java.
References moa.classifiers.meta.OzaBag.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.OzaBag.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.meta.OzaBagASHT, and moa.classifiers.multilabel.meta.MLOzaBag.
Definition at line 92 of file OzaBag.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.OzaBag.ensemble, moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.normalize(), and moa.core.DoubleVector.sumOfValues().
{
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
            if (vote.sumOfValues() > 0.0) {
                vote.normalize();
                combinedVote.addValues(vote);
            }
        }
        return combinedVote.getArrayRef();
    }
boolean moa.classifiers.meta.OzaBag.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Reimplemented in moa.classifiers.multilabel.meta.MLOzaBag.
Definition at line 105 of file OzaBag.java.
{
        return true;
    }
void moa.classifiers.meta.OzaBag.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.OzaBagASHT, and moa.classifiers.multilabel.meta.MLOzaBag.
Definition at line 70 of file OzaBag.java.
References moa.classifiers.meta.OzaBag.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.OzaBag.ensemble, moa.classifiers.meta.OzaBag.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), and moa.classifiers.Classifier.resetLearning().
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
    }
void moa.classifiers.meta.OzaBag.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.OzaBagASHT.
Definition at line 80 of file OzaBag.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.meta.OzaBag.ensemble, and moa.classifiers.Classifier.trainOnInstance().
{
        for (int i = 0; i < this.ensemble.length; i++) {
            int k = MiscUtils.poisson(1.0, this.classifierRandom);
            if (k > 0) {
                Instance weightedInst = (Instance) inst.copy();
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
        }
    }
Member Data Documentation
ClassOption moa.classifiers.meta.OzaBag.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 61 of file OzaBag.java.
Referenced by moa.classifiers.meta.OzaBagASHTTest.getRegressionClassifierSetups(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), and moa.classifiers.meta.OzaBag.resetLearningImpl().
Classifier [] moa.classifiers.meta.OzaBag.ensemble [protected]
Definition at line 67 of file OzaBag.java.
Referenced by moa.classifiers.meta.OzaBag.getModelMeasurementsImpl(), moa.classifiers.meta.OzaBag.getSubClassifiers(), moa.classifiers.multilabel.meta.MLOzaBag.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OzaBag.getVotesForInstance(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), moa.classifiers.meta.OzaBag.resetLearningImpl(), moa.classifiers.multilabel.meta.MLOzaBag.setModelContext(), moa.classifiers.meta.OzaBagASHT.trainOnInstanceImpl(), and moa.classifiers.meta.OzaBag.trainOnInstanceImpl().
IntOption moa.classifiers.meta.OzaBag.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models in the bag.", 10, 1, Integer.MAX_VALUE)
Definition at line 64 of file OzaBag.java.
Referenced by moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), and moa.classifiers.meta.OzaBag.resetLearningImpl().
final long moa.classifiers.meta.OzaBag.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.meta.OzaBagASHT.
Definition at line 59 of file OzaBag.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/OzaBag.java