MOA: moa.gui.GUI Class Reference
moa.gui.GUI Class Reference
The main class for the MOA gui.
Public Member Functions
GUI ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void initGUI ()
Private Attributes
javax.swing.JTabbedPane panel
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The main class for the MOA gui.
Lets the user configure tasks, learners, streams, and perform data stream analysis.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
FracPete (fracpete at waikato dot ac dot nz)
Version:
Revision
7
Definition at line 39 of file GUI.java.
Constructor & Destructor Documentation
moa.gui.GUI.GUI ()
Definition at line 45 of file GUI.java.
References moa.gui.GUI.initGUI().
Referenced by moa.gui.GUI.main().
                 {
        initGUI();
    }
Member Function Documentation
void moa.gui.GUI.initGUI () [private]
Definition at line 49 of file GUI.java.
References moa.gui.AbstractTabPanel.getDescription(), moa.gui.AbstractTabPanel.getTabTitle(), and moa.gui.GUI.panel.
Referenced by moa.gui.GUI.GUI().
{
        setLayout(new BorderLayout());
        // Create and set up tabs
        panel = new javax.swing.JTabbedPane();
        add(panel, BorderLayout.CENTER);
        // initialize additional panels
        String[] tabs = GUIDefaults.getTabs();
        for (int i = 0; i < tabs.length; i++) {
            try {
                // determine classname
                String[] optionsStr = tabs[i].split(":");
                String classname = optionsStr[0];
                // setup panel
                AbstractTabPanel tabPanel = (AbstractTabPanel) Class.forName(classname).newInstance();
                panel.addTab(tabPanel.getTabTitle(), null, (JPanel) tabPanel, tabPanel.getDescription());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
static void moa.gui.GUI.main (String[] args) [static]
Definition at line 73 of file GUI.java.
References moa.gui.GUI.GUI().
{
        try {
            if (DoTask.isJavaVersionOK() == false || DoTask.isWekaVersionOK() == false) {
                return;
            }
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    // Create and set up the window.
                    JFrame frame = new JFrame("MOA Graphical User Interface");
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    } catch (Exception e) {
                        try {
                            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                        } catch (Exception ex) {
                        }
                    }
                    GUI gui = new GUI();
                    frame.getContentPane().setLayout(new BorderLayout());
                    frame.getContentPane().add(gui);
                    // Display the window.
                    frame.pack();
                    frame.setVisible(true);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
Member Data Documentation
javax.swing.JTabbedPane moa.gui.GUI.panel [private]
Definition at line 43 of file GUI.java.
Referenced by moa.gui.GUI.initGUI().
final long moa.gui.GUI.serialVersionUID = 1L [static, private]
Definition at line 41 of file GUI.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/GUI.java