MOA: moa.gui.visualization.GraphAxes Class Reference
moa.gui.visualization.GraphAxes Class Reference
Public Member Functions
GraphAxes ()
Creates new form GraphAxes.
void setXMaxValue (int max)
void setXResolution (double resolution)
void setProcessFrequency (int frequency)
void setYMinMaxValues (double min, double max)
void setMaxXValue (int max)
Protected Member Functions
void paintComponent (Graphics g)
Private Member Functions
void xAxis (Graphics g)
void yAxis (Graphics g)
int calcY (double value)
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
final int x_offset_left = 35
final int x_offset_right = 5
final int y_offset_bottom = 20
final int y_offset_top = 20
int height
int width
double x_resolution
int processFrequency
double min_value = 0
double max_value = 1
int max_x_value
Detailed Description
Definition at line 28 of file GraphAxes.java.
Constructor & Destructor Documentation
moa.gui.visualization.GraphAxes.GraphAxes ()
Creates new form GraphAxes.
Definition at line 45 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.initComponents().
                       {
        initComponents();
    }
Member Function Documentation
int moa.gui.visualization.GraphAxes.calcY (double value) [private]
Definition at line 142 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.height, moa.gui.visualization.GraphAxes.max_value, and moa.gui.visualization.GraphAxes.y_offset_top.
Referenced by moa.gui.visualization.GraphAxes.xAxis(), and moa.gui.visualization.GraphAxes.yAxis().
{
        return (int)(height-(value/max_value)*height)+y_offset_top;
    }
void moa.gui.visualization.GraphAxes.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 153 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.GraphAxes().
{
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.GraphAxes.paintComponent (Graphics g) [protected]
Definition at line 62 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.height, moa.gui.visualization.GraphAxes.processFrequency, moa.gui.visualization.GraphAxes.width, moa.gui.visualization.GraphAxes.x_offset_left, moa.gui.visualization.GraphAxes.x_offset_right, moa.gui.visualization.GraphAxes.xAxis(), moa.gui.visualization.GraphAxes.y_offset_bottom, moa.gui.visualization.GraphAxes.y_offset_top, and moa.gui.visualization.GraphAxes.yAxis().
{
        super.paintComponent(g);
        //stream not started yet
        if(processFrequency == 0) return;
        height = getHeight()-y_offset_bottom-y_offset_top;
        width = getWidth()-x_offset_left-x_offset_right;
        //System.out.println(width);
        g.setColor(new Color(236,233,216));
        g.fillRect(0, 0, getWidth(), getHeight());
        //draw background
        g.setColor(Color.WHITE);
        g.fillRect(x_offset_left, y_offset_top, width, height);
        g.setFont(new Font("Tahoma", 0, 11));
        xAxis(g);
        yAxis(g);
    }
void moa.gui.visualization.GraphAxes.setMaxXValue (int max)
Definition at line 138 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.max_x_value.
{
        max_x_value = max;
    }
void moa.gui.visualization.GraphAxes.setProcessFrequency (int frequency)
Definition at line 57 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.processFrequency.
Referenced by moa.gui.visualization.GraphCanvas.setGraph().
{
        processFrequency = frequency;
    }
void moa.gui.visualization.GraphAxes.setXMaxValue (int max)
Definition at line 49 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.max_x_value.
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas().
{
        max_x_value = max;
    }
void moa.gui.visualization.GraphAxes.setXResolution (double resolution)
Definition at line 53 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.x_resolution.
Referenced by moa.gui.visualization.GraphCanvas.updateXResolution().
{
        x_resolution = resolution;
    }
void moa.gui.visualization.GraphAxes.setYMinMaxValues (double min, double max)
Definition at line 133 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.max_value, and moa.gui.visualization.GraphAxes.min_value.
Referenced by moa.gui.visualization.GraphCanvas.updateYValues().
{
        min_value = min;
        max_value = max;
    }
void moa.gui.visualization.GraphAxes.xAxis (Graphics g) [private]
Definition at line 87 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.calcY(), moa.gui.visualization.GraphAxes.height, moa.gui.visualization.GraphAxes.processFrequency, moa.gui.visualization.GraphAxes.width, moa.gui.visualization.GraphAxes.x_offset_left, moa.gui.visualization.GraphAxes.x_offset_right, moa.gui.visualization.GraphAxes.x_resolution, and moa.gui.visualization.GraphAxes.y_offset_top.
Referenced by moa.gui.visualization.GraphAxes.paintComponent().
{
        g.setColor(Color.BLACK);
        //x-achsis
        g.drawLine(x_offset_left, calcY(0), width+x_offset_left, calcY(0));
        //x achsis labels
        int w = 100;
        for (int i = 0; w*i < width-x_offset_right; i++) {
            g.drawLine(w*i+x_offset_left, height+y_offset_top, w*i+x_offset_left, height+y_offset_top+5);
            String label = Integer.toString((int)(w*i*processFrequency*x_resolution));
            int str_length = g.getFontMetrics().stringWidth(label);
            g.drawString(label,w*i+x_offset_left-str_length/2,height+y_offset_top+18);
        }
    }
void moa.gui.visualization.GraphAxes.yAxis (Graphics g) [private]
Definition at line 106 of file GraphAxes.java.
References moa.gui.visualization.GraphAxes.calcY(), moa.gui.visualization.GraphAxes.height, moa.gui.visualization.GraphAxes.max_value, moa.gui.visualization.GraphAxes.x_offset_left, and moa.gui.visualization.GraphAxes.y_offset_top.
Referenced by moa.gui.visualization.GraphAxes.paintComponent().
{
        //y-achsis
        g.setColor(Color.BLACK);
        g.drawLine(x_offset_left, calcY(0), x_offset_left, y_offset_top);
        //center horizontal line
        g.setColor(new Color(220,220,220));
        g.drawLine(x_offset_left, height/2+y_offset_top, getWidth(), height/2+y_offset_top);
        //3 y-achsis markers + labels
        g.setColor(Color.BLACK);
        DecimalFormat d = new DecimalFormat("0.00");
        int digits_y = (int)(Math.log10(max_value))-1;
        double upper = Math.ceil(max_value/Math.pow(10,digits_y));
        if(digits_y < 0) upper*=Math.pow(10,digits_y);
        if(Double.isNaN(upper)) upper =1.0;
        g.drawString(d.format(0.0), 3, height+y_offset_top+5);
        g.drawString(d.format(upper/2), 3, height/2+y_offset_top + 5);
        g.drawString(d.format(upper), 3, y_offset_top + 5);
        g.drawLine(x_offset_left-5, height+y_offset_top, x_offset_left,height+y_offset_top);
        g.drawLine(x_offset_left-5, height/2+y_offset_top, x_offset_left,height/2+y_offset_top);
        g.drawLine(x_offset_left-5, y_offset_top, x_offset_left,y_offset_top);
    }
Member Data Documentation
int moa.gui.visualization.GraphAxes.height [private]
Definition at line 34 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.calcY(), moa.gui.visualization.GraphAxes.paintComponent(), moa.gui.visualization.GraphAxes.xAxis(), and moa.gui.visualization.GraphAxes.yAxis().
double moa.gui.visualization.GraphAxes.max_value = 1 [private]
Definition at line 41 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.calcY(), moa.gui.visualization.GraphAxes.setYMinMaxValues(), and moa.gui.visualization.GraphAxes.yAxis().
int moa.gui.visualization.GraphAxes.max_x_value [private]
Definition at line 42 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.setMaxXValue(), and moa.gui.visualization.GraphAxes.setXMaxValue().
double moa.gui.visualization.GraphAxes.min_value = 0 [private]
Definition at line 40 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.setYMinMaxValues().
int moa.gui.visualization.GraphAxes.processFrequency [private]
Definition at line 38 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.paintComponent(), moa.gui.visualization.GraphAxes.setProcessFrequency(), and moa.gui.visualization.GraphAxes.xAxis().
int moa.gui.visualization.GraphAxes.width [private]
Definition at line 35 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.paintComponent(), and moa.gui.visualization.GraphAxes.xAxis().
final int moa.gui.visualization.GraphAxes.x_offset_left = 35 [private]
Definition at line 29 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.paintComponent(), moa.gui.visualization.GraphAxes.xAxis(), and moa.gui.visualization.GraphAxes.yAxis().
final int moa.gui.visualization.GraphAxes.x_offset_right = 5 [private]
Definition at line 30 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.paintComponent(), and moa.gui.visualization.GraphAxes.xAxis().
double moa.gui.visualization.GraphAxes.x_resolution [private]
Definition at line 37 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.setXResolution(), and moa.gui.visualization.GraphAxes.xAxis().
final int moa.gui.visualization.GraphAxes.y_offset_bottom = 20 [private]
Definition at line 31 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.paintComponent().
final int moa.gui.visualization.GraphAxes.y_offset_top = 20 [private]
Definition at line 32 of file GraphAxes.java.
Referenced by moa.gui.visualization.GraphAxes.calcY(), moa.gui.visualization.GraphAxes.paintComponent(), moa.gui.visualization.GraphAxes.xAxis(), and moa.gui.visualization.GraphAxes.yAxis().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/GraphAxes.java