MOA: moa.evaluation.LearningCurve Class Reference
moa.evaluation.LearningCurve Class Reference
Class that stores and keeps the history of evaluation measurements.
Public Member Functions
LearningCurve (String orderingMeasurementName)
String getOrderingMeasurementName ()
void insertEntry (LearningEvaluation learningEvaluation)
int numEntries ()
String headerToString ()
String entryToString (int entryIndex)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
double getMeasurement (int entryIndex, int measurementIndex)
String getMeasurementName (int measurementIndex)
Protected Member Functions
int addMeasurementName (String name)
Protected Attributes
List< String > measurementNames = new ArrayList<String>()
List< double[]> measurementValues = new ArrayList<double[]>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class that stores and keeps the history of evaluation measurements.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 36 of file LearningCurve.java.
Constructor & Destructor Documentation
moa.evaluation.LearningCurve.LearningCurve (String orderingMeasurementName)
Definition at line 44 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames.
{
        this.measurementNames.add(orderingMeasurementName);
    }
Member Function Documentation
int moa.evaluation.LearningCurve.addMeasurementName (String name) [protected]
Definition at line 77 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames.
Referenced by moa.evaluation.LearningCurve.insertEntry().
{
        int index = this.measurementNames.indexOf(name);
        if (index < 0) {
            index = this.measurementNames.size();
            this.measurementNames.add(name);
        }
        return index;
    }
String moa.evaluation.LearningCurve.entryToString (int entryIndex)
Definition at line 100 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames, and moa.evaluation.LearningCurve.measurementValues.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), and moa.evaluation.LearningCurve.getDescription().
{
        StringBuilder sb = new StringBuilder();
        double[] vals = this.measurementValues.get(entryIndex);
        for (int i = 0; i < this.measurementNames.size(); i++) {
            if (i > 0) {
                sb.append(',');
            }
            if ((i >= vals.length) || Double.isNaN(vals[i])) {
                sb.append('?');
            } else {
                sb.append(Double.toString(vals[i]));
            }
        }
        return sb.toString();
    }
void moa.evaluation.LearningCurve.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 117 of file LearningCurve.java.
References moa.evaluation.LearningCurve.entryToString(), moa.evaluation.LearningCurve.headerToString(), and moa.evaluation.LearningCurve.numEntries().
{
        sb.append(headerToString());
        for (int i = 0; i < numEntries(); i++) {
            StringUtils.appendNewlineIndented(sb, indent, entryToString(i));
        }
    }
double moa.evaluation.LearningCurve.getMeasurement (int entryIndex, int measurementIndex)
Definition at line 124 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementValues.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot().
{
        return this.measurementValues.get(entryIndex)[measurementIndex];
    }
String moa.evaluation.LearningCurve.getMeasurementName (int measurementIndex)
Definition at line 128 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames.
Referenced by moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
{
        return this.measurementNames.get(measurementIndex);
    }
String moa.evaluation.LearningCurve.getOrderingMeasurementName ()
Definition at line 48 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames.
Referenced by moa.evaluation.LearningCurve.insertEntry().
{
        return this.measurementNames.get(0);
    }
String moa.evaluation.LearningCurve.headerToString ()
Definition at line 86 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementNames.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), and moa.evaluation.LearningCurve.getDescription().
{
        StringBuilder sb = new StringBuilder();
        boolean first = true;
        for (String name : this.measurementNames) {
            if (!first) {
                sb.append(',');
            } else {
                first = false;
            }
            sb.append(name);
        }
        return sb.toString();
    }
void moa.evaluation.LearningCurve.insertEntry (LearningEvaluation learningEvaluation)
Definition at line 52 of file LearningCurve.java.
References moa.evaluation.LearningCurve.addMeasurementName(), moa.core.DoubleVector.getArrayRef(), moa.core.Measurement.getMeasurementNamed(), moa.evaluation.LearningEvaluation.getMeasurements(), moa.evaluation.LearningCurve.getOrderingMeasurementName(), moa.core.Measurement.getValue(), moa.evaluation.LearningCurve.measurementValues, and moa.core.DoubleVector.setValue().
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), and moa.tasks.EvaluateConceptDrift.doMainTask().
{
        Measurement[] measurements = learningEvaluation.getMeasurements();
        Measurement orderMeasurement = Measurement.getMeasurementNamed(
                getOrderingMeasurementName(), measurements);
        if (orderMeasurement == null) {
            throw new IllegalArgumentException();
        }
        DoubleVector entryVals = new DoubleVector();
        for (Measurement measurement : measurements) {
            entryVals.setValue(addMeasurementName(measurement.getName()),
                    measurement.getValue());
        }
        double orderVal = orderMeasurement.getValue();
        int index = 0;
        while ((index < this.measurementValues.size())
                && (orderVal > this.measurementValues.get(index)[0])) {
            index++;
        }
        this.measurementValues.add(index, entryVals.getArrayRef());
    }
int moa.evaluation.LearningCurve.numEntries ()
Definition at line 73 of file LearningCurve.java.
References moa.evaluation.LearningCurve.measurementValues.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.evaluation.LearningCurve.getDescription(), and moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot().
{
        return this.measurementValues.size();
    }
Member Data Documentation
List<String> moa.evaluation.LearningCurve.measurementNames = new ArrayList<String>() [protected]
Definition at line 40 of file LearningCurve.java.
Referenced by moa.evaluation.LearningCurve.addMeasurementName(), moa.evaluation.LearningCurve.entryToString(), moa.evaluation.LearningCurve.getMeasurementName(), moa.evaluation.LearningCurve.getOrderingMeasurementName(), moa.evaluation.LearningCurve.headerToString(), and moa.evaluation.LearningCurve.LearningCurve().
List<double[]> moa.evaluation.LearningCurve.measurementValues = new ArrayList<double[]>() [protected]
Definition at line 42 of file LearningCurve.java.
Referenced by moa.evaluation.LearningCurve.entryToString(), moa.evaluation.LearningCurve.getMeasurement(), moa.evaluation.LearningCurve.insertEntry(), and moa.evaluation.LearningCurve.numEntries().
final long moa.evaluation.LearningCurve.serialVersionUID = 1L [static, private]
Definition at line 38 of file LearningCurve.java.
The documentation for this class was generated from the following file:
main/java/moa/evaluation/LearningCurve.java