MOA: moa.classifiers.meta.LimAttClassifier Class Reference
moa.classifiers.meta.LimAttClassifier Class Reference
Ensemble Combining Restricted Hoeffding Trees using Stacking.
Classes
class CombinationGenerator
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
void trainOnInstanceImplPerceptron (int numClasses, int actualClass, double[][] votes)
double predictionPruning (double[][] votes, int[] bestClassifiers, int classVal)
double prediction (double[][] votes, int classVal)
double[] getVotesForInstancePerceptron (double[][] votesEnsemble, int[] bestClassifiers, int numClasses)
Public Attributes
ClassOption baseLearnerOption
IntOption numAttributesOption
FloatOption weightShrinkOption
FloatOption deltaAdwinOption
FloatOption oddsOffsetOption
FlagOption pruneOption
FlagOption bigTreesOption
IntOption numEnsemblePruningOption
FlagOption adwinReplaceWorstClassifierOption
FloatOption learningRatioOption = new FloatOption("learningRatio", 'e', "Learning ratio", 1)
FloatOption penaltyFactorOption = new FloatOption("lambda", 'p', "Lambda", 0.0)
IntOption initialNumInstancesOption = new IntOption("initialNumInstances", 'i', "initialNumInstances", 10)
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
ADWIN[] ADError
int numberOfChangesDetected
int[][] matrixCodes
boolean initMatrixCodes = false
boolean initClassifiers = false
int numberAttributes = 1
int numInstances = 0
double[][] weightAttribute
boolean reset
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Ensemble Combining Restricted Hoeffding Trees using Stacking.
It produces a classification model based on an ensemble of restricted decision trees, where each tree is built from a distinct subset of the attributes. The overall model is formed by combining the log-odds of the predicted class probabilities of these trees using sigmoid perceptrons, with one perceptron per class. In contrast to the standard boosting approach, which forms an ensemble classifier in a greedy fashion, building each tree in sequence and assigning corresponding weights as a by-product, our method generates each tree in parallel and combines them using perceptron classifiers by adopting the stacking approach.
For more information see,
Albert Bifet, Eibe Frank, Geoffrey Holmes, Bernhard Pfahringer: Accurate Ensembles for Data Streams: Combining Restricted Hoeffding Trees using Stacking. Journal of Machine Learning Research - Proceedings Track 13: 225-240 (2010)
BibTeX:
 &#64;article{BifetFHP10,
 author    = {Albert Bifet and
              Eibe Frank and
              Geoffrey Holmes and
              Bernhard Pfahringer},
 title     = {Accurate Ensembles for Data Streams: Combining Restricted
              Hoeffding Trees using Stacking},
 journal   = {Journal of Machine Learning Research - Proceedings Track},
 volume    = {13},
 year      = {2010},
 pages     = {225-240}
 }
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Eibe Frank (eibe{[at]}cs{[dot]}waikato{[dot]}ac{[dot]}nz)
Version:
Revision
7
Definition at line 81 of file LimAttClassifier.java.
Member Function Documentation
void moa.classifiers.meta.LimAttClassifier.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 448 of file LimAttClassifier.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.LimAttClassifier.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 453 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.ensemble, and moa.classifiers.meta.LimAttClassifier.numberOfChangesDetected.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0),
                    new Measurement("change detections", this.numberOfChangesDetected)
                };
    }
String moa.classifiers.meta.LimAttClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 84 of file LimAttClassifier.java.
{
        return "Ensemble Combining Restricted Hoeffding Trees using Stacking";
    }
Classifier [] moa.classifiers.meta.LimAttClassifier.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 461 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.LimAttClassifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 376 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.ensemble, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.getVotesForInstancePerceptron(), moa.classifiers.meta.LimAttClassifier.initClassifiers, moa.options.FlagOption.isSet, moa.classifiers.meta.LimAttClassifier.numEnsemblePruningOption, moa.classifiers.meta.LimAttClassifier.oddsOffsetOption, moa.classifiers.meta.LimAttClassifier.pruneOption, and moa.classifiers.meta.LimAttClassifier.weightAttribute.
{
        if (this.initClassifiers == true) {
            return new double[0];
        }
        int numClasses = inst.numClasses();
        int sizeEnsemble = this.ensemble.length;
        if (pruneOption.isSet()) {
            sizeEnsemble = this.numEnsemblePruningOption.getValue();
        }
        double[][] votes = new double[sizeEnsemble + 1][numClasses];
        int[] bestClassifiers = new int[sizeEnsemble];
        if (pruneOption.isSet()) {
            //Check for the best classifiers
            double[] weight = new double[this.ensemble.length];
            for (int i = 0; i < numClasses; i++) {
                for (int j = 0; j < this.ensemble.length; j++) {
                    weight[j] += weightAttribute[i][j];
                }
            }
            Arrays.sort(weight);
            double cutValue = weight[this.ensemble.length - sizeEnsemble]; //reverse order
            int ii = 0;
            for (int j = 0; j < this.ensemble.length; j++) {
                if (weight[j] >= cutValue && ii < sizeEnsemble) {
                    bestClassifiers[ii] = j;
                    ii++;
                }
            }
        } else { //Not pruning: all classifiers
            for (int ii = 0; ii < sizeEnsemble; ii++) {
                bestClassifiers[ii] = ii;
            }
        }
        for (int ii = 0; ii < sizeEnsemble; ii++) {
            int i = bestClassifiers[ii];
            double[] v = new double[numClasses];
            for (int j = 0; j < v.length; j++) {
                v[j] = (double) this.oddsOffsetOption.getValue();
            }
            double[] vt = this.ensemble[i].getVotesForInstance(inst);
            double sum = Utils.sum(vt);
            if (!Double.isNaN(sum) && (sum > 0)) {
                for (int j = 0; j < vt.length; j++) {
                    vt[j] /= sum;
                }
            } else {
                // Just in case the base learner returns NaN
                for (int k = 0; k < vt.length; k++) {
                    vt[k] = 0.0;
                }
            }
            sum = numClasses * (double) this.oddsOffsetOption.getValue();
            for (int j = 0; j < vt.length; j++) {
                v[j] += vt[j];
                sum += vt[j];
            }
            for (int j = 0; j < vt.length; j++) {
                votes[ii][j] = Math.log(v[j] / (sum - v[j]));
                //                    votes[i][j] = vt[j];
            }
        }
        return getVotesForInstancePerceptron(votes, bestClassifiers, inst.numClasses());
    }
double [] moa.classifiers.meta.LimAttClassifier.getVotesForInstancePerceptron (double votesEnsemble[][], int[] bestClassifiers, int numClasses)
Definition at line 528 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.predictionPruning(), and moa.classifiers.meta.LimAttClassifier.reset.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance().
{
        double[] votes = new double[numClasses];
        if (this.reset == false) {
            for (int i = 0; i < votes.length; i++) {
                votes[i] = predictionPruning(votesEnsemble, bestClassifiers, i);
            }
        }
        return votes;
    }
boolean moa.classifiers.meta.LimAttClassifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 443 of file LimAttClassifier.java.
{
        return true;
    }
double moa.classifiers.meta.LimAttClassifier.prediction (double votes[][], int classVal)
Definition at line 519 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.weightAttribute.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
{
        double sum = 0.0;
        for (int i = 0; i < votes.length - 1; i++) {
            sum += (double) weightAttribute[classVal][i] * votes[i][classVal];
        }
        sum += weightAttribute[classVal][votes.length - 1];
        return 1.0 / (1.0 + Math.exp(-sum));
    }
double moa.classifiers.meta.LimAttClassifier.predictionPruning (double votes[][], int[] bestClassifiers, int classVal)
Definition at line 510 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.weightAttribute.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstancePerceptron().
{
        double sum = 0.0;
        for (int i = 0; i < votes.length - 1; i++) {
            sum += (double) weightAttribute[classVal][bestClassifiers[i]] * votes[i][classVal];
        }
        sum += weightAttribute[classVal][votes.length - 1];
        return 1.0 / (1.0 + Math.exp(-sum));
    }
void moa.classifiers.meta.LimAttClassifier.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 246 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.initClassifiers, and moa.classifiers.meta.LimAttClassifier.reset.
{
        this.initClassifiers = true;
        this.reset = true;
    }
void moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 252 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.ADError, moa.classifiers.meta.LimAttClassifier.adwinReplaceWorstClassifierOption, moa.classifiers.meta.LimAttClassifier.baseLearnerOption, moa.classifiers.meta.LimAttClassifier.bigTreesOption, moa.classifiers.Classifier.copy(), moa.classifiers.Classifier.correctlyClassifies(), moa.classifiers.AbstractClassifier.correctlyClassifies(), moa.classifiers.meta.LimAttClassifier.deltaAdwinOption, moa.classifiers.meta.LimAttClassifier.ensemble, moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getTotal(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.hasMore(), moa.classifiers.meta.LimAttClassifier.initClassifiers, moa.classifiers.meta.LimAttClassifier.initialNumInstancesOption, moa.options.FlagOption.isSet, moa.classifiers.meta.LimAttClassifier.numAttributesOption, moa.classifiers.meta.LimAttClassifier.numberAttributes, moa.classifiers.meta.LimAttClassifier.numberOfChangesDetected, moa.classifiers.meta.LimAttClassifier.numInstances, moa.classifiers.meta.LimAttClassifier.oddsOffsetOption, moa.classifiers.Classifier.resetLearning(), moa.classifiers.Classifier.trainOnInstance(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron(), and moa.classifiers.meta.LimAttClassifier.weightAttribute.
{
        int numClasses = inst.numClasses();
        //Init Ensemble
        if (this.initClassifiers == true) {
            numberAttributes = numAttributesOption.getValue();
            if (bigTreesOption.isSet()) {
                numberAttributes = inst.numAttributes() - 1 - numAttributesOption.getValue();
            }
            CombinationGenerator x = new CombinationGenerator(inst.numAttributes() - 1, this.numberAttributes);
            int numberClassifiers = x.getTotal().intValue();
            this.ensemble = new Classifier[numberClassifiers];
            Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
            baseLearner.resetLearning();
            for (int i = 0; i < this.ensemble.length; i++) {
                this.ensemble[i] = baseLearner.copy();
            }
            this.ADError = new ADWIN[this.ensemble.length];
            for (int i = 0; i < this.ensemble.length; i++) {
                this.ADError[i] = new ADWIN((double) this.deltaAdwinOption.getValue());
            }
            this.numberOfChangesDetected = 0;
            //Prepare combinations
            int i = 0;
            if (baseLearner instanceof LimAttHoeffdingTree) {
                while (x.hasMore()) {
                    ((LimAttHoeffdingTree) this.ensemble[i]).setlistAttributes(x.getNext());
                    i++;
                }
            }
            this.initClassifiers = false;
        }
        boolean Change = false;
        Instance weightedInst = (Instance) inst.copy();
        //Train Perceptron
        double[][] votes = new double[this.ensemble.length + 1][numClasses];
        for (int i = 0; i < this.ensemble.length; i++) {
            double[] v = new double[numClasses];
            for (int j = 0; j < v.length; j++) {
                v[j] = (double) this.oddsOffsetOption.getValue();
            }
            double[] vt = this.ensemble[i].getVotesForInstance(inst);
            double sum = Utils.sum(vt);
            if (!Double.isNaN(sum) && (sum > 0)) {
                for (int j = 0; j < vt.length; j++) {
                    vt[j] /= sum;
                }
            } else {
                // Just in case the base learner returns NaN
                for (int k = 0; k < vt.length; k++) {
                    vt[k] = 0.0;
                }
            }
            sum = numClasses * (double) this.oddsOffsetOption.getValue();
            for (int j = 0; j < vt.length; j++) {
                v[j] += vt[j];
                sum += vt[j];
            }
            for (int j = 0; j < vt.length; j++) {
                votes[i][j] = Math.log(v[j] / (sum - v[j]));
            }
        }
        if (adwinReplaceWorstClassifierOption.isSet() == false) {
            //Train ensemble of classifiers
            for (int i = 0; i < this.ensemble.length; i++) {
                boolean correctlyClassifies = this.ensemble[i].correctlyClassifies(weightedInst);
                double ErrEstim = this.ADError[i].getEstimation();
                if (this.ADError[i].setInput(correctlyClassifies ? 0 : 1)) {
                    numInstances = initialNumInstancesOption.getValue();
                    if (this.ADError[i].getEstimation() > ErrEstim) {
                        Change = true;
                        //Replace classifier if ADWIN has detected change
                        numberOfChangesDetected++;
                        this.ensemble[i].resetLearning();
                        this.ADError[i] = new ADWIN((double) this.deltaAdwinOption.getValue());
                        for (int ii = 0; ii < inst.numClasses(); ii++) {
                            weightAttribute[ii][i] = 0.0;// 0.2 * Math.random() - 0.1;
                        }
                    }
                }
            }
        } else {
            //Train ensemble of classifiers
            for (int i = 0; i < this.ensemble.length; i++) {
                boolean correctlyClassifies = this.ensemble[i].correctlyClassifies(weightedInst);
                double ErrEstim = this.ADError[i].getEstimation();
                if (this.ADError[i].setInput(correctlyClassifies ? 0 : 1)) {
                    if (this.ADError[i].getEstimation() > ErrEstim) {
                        Change = true;
                    }
                }
            }
            //Replace classifier with higher error if ADWIN has detected change
            if (Change) {
                numberOfChangesDetected++;
                double max = 0.0;
                int imax = -1;
                for (int i = 0; i < this.ensemble.length; i++) {
                    if (max < this.ADError[i].getEstimation()) {
                        max = this.ADError[i].getEstimation();
                        imax = i;
                    }
                }
                if (imax != -1) {
                    this.ensemble[imax].resetLearning();
                    this.ADError[imax] = new ADWIN((double) this.deltaAdwinOption.getValue());
                    for (int ii = 0; ii < inst.numClasses(); ii++) {
                        weightAttribute[ii][imax] = 0.0;
                    }
                }
            }
        }
        trainOnInstanceImplPerceptron(inst.numClasses(), (int) inst.classValue(), votes);
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i].trainOnInstance(inst);
        }
    }
void moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron (int numClasses, int actualClass, double votes[][])
Definition at line 476 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.ensemble, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.meta.LimAttClassifier.initialNumInstancesOption, moa.classifiers.meta.LimAttClassifier.learningRatioOption, moa.classifiers.meta.LimAttClassifier.numInstances, moa.classifiers.meta.LimAttClassifier.penaltyFactorOption, moa.classifiers.meta.LimAttClassifier.prediction(), moa.classifiers.meta.LimAttClassifier.reset, and moa.classifiers.meta.LimAttClassifier.weightAttribute.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
{
        //Init Perceptron
        if (this.reset == true) {
            this.reset = false;
            this.weightAttribute = new double[numClasses][votes.length];
            for (int i = 0; i < numClasses; i++) {
                for (int j = 0; j < votes.length - 1; j++) {
                    weightAttribute[i][j] = 1.0 / (votes.length - 1.0);
                }
            }
            numInstances = initialNumInstancesOption.getValue();
        }
        // Weight decay
        double learningRatio = learningRatioOption.getValue() * 2.0 / (numInstances + (votes.length - 1) + 2.0);
        double lambda = penaltyFactorOption.getValue();
        numInstances++;
        double[] preds = new double[numClasses];
        for (int i = 0; i < numClasses; i++) {
            preds[i] = prediction(votes, i);
        }
        for (int i = 0; i < numClasses; i++) {
            double actual = (i == actualClass) ? 1.0 : 0.0;
            double delta = (actual - preds[i]) * preds[i] * (1 - preds[i]);
            for (int j = 0; j < this.ensemble.length; j++) {
                this.weightAttribute[i][j] += learningRatio * (delta * votes[j][i] - lambda * this.weightAttribute[i][j]);
            }
            this.weightAttribute[i][this.ensemble.length] += learningRatio * delta;
        }
    }
Member Data Documentation
ADWIN [] moa.classifiers.meta.LimAttClassifier.ADError [protected]
Definition at line 231 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.LimAttClassifier.adwinReplaceWorstClassifierOption
Initial value:
 new FlagOption("adwinReplaceWorstClassifier", 'z',
            "When one Adwin detects change, replace worst classifier.")
Definition at line 226 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.LimAttClassifier.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.LimAttHoeffdingTree")
Definition at line 202 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.LimAttClassifier.bigTreesOption
Initial value:
 new FlagOption("bigTrees", 'b',
            "Use m-n attributes on the trees.")
Definition at line 220 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
FloatOption moa.classifiers.meta.LimAttClassifier.deltaAdwinOption
Initial value:
 new FloatOption("deltaAdwin", 'a',
            "Delta of Adwin change detection", 0.002, 0.0, 1.0)
Definition at line 211 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
Classifier [] moa.classifiers.meta.LimAttClassifier.ensemble [protected]
Definition at line 229 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getModelMeasurementsImpl(), moa.classifiers.meta.LimAttClassifier.getSubClassifiers(), moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
boolean moa.classifiers.meta.LimAttClassifier.initClassifiers = false [protected]
Definition at line 239 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.resetLearningImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
IntOption moa.classifiers.meta.LimAttClassifier.initialNumInstancesOption = new IntOption("initialNumInstances", 'i', "initialNumInstances", 10)
Definition at line 470 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
boolean moa.classifiers.meta.LimAttClassifier.initMatrixCodes = false [protected]
Definition at line 237 of file LimAttClassifier.java.
FloatOption moa.classifiers.meta.LimAttClassifier.learningRatioOption = new FloatOption("learningRatio", 'e', "Learning ratio", 1)
Definition at line 466 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
int [][] moa.classifiers.meta.LimAttClassifier.matrixCodes [protected]
Definition at line 235 of file LimAttClassifier.java.
IntOption moa.classifiers.meta.LimAttClassifier.numAttributesOption
Initial value:
 new IntOption("numAttributes", 'n',
            "The number of attributes to use per model.", 1, 1, Integer.MAX_VALUE)
Definition at line 205 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
int moa.classifiers.meta.LimAttClassifier.numberAttributes = 1 [protected]
Definition at line 241 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
int moa.classifiers.meta.LimAttClassifier.numberOfChangesDetected [protected]
Definition at line 233 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getModelMeasurementsImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
IntOption moa.classifiers.meta.LimAttClassifier.numEnsemblePruningOption
Initial value:
 new IntOption("numEnsemblePruning", 'm',
            "The pruned number of classifiers to use to predict.", 10, 1, Integer.MAX_VALUE)
Definition at line 223 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance().
int moa.classifiers.meta.LimAttClassifier.numInstances = 0 [protected]
Definition at line 243 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
FloatOption moa.classifiers.meta.LimAttClassifier.oddsOffsetOption
Initial value:
 new FloatOption("oddsOffset", 'o',
            "Offset for odds to avoid probabilities that are zero.", 0.001, 0.0, Float.MAX_VALUE)
Definition at line 214 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
FloatOption moa.classifiers.meta.LimAttClassifier.penaltyFactorOption = new FloatOption("lambda", 'p', "Lambda", 0.0)
Definition at line 468 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
FlagOption moa.classifiers.meta.LimAttClassifier.pruneOption
Initial value:
 new FlagOption("prune", 'x',
            "Enable pruning.")
Definition at line 217 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance().
boolean moa.classifiers.meta.LimAttClassifier.reset [protected]
Definition at line 474 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstancePerceptron(), moa.classifiers.meta.LimAttClassifier.resetLearningImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
final long moa.classifiers.meta.LimAttClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 200 of file LimAttClassifier.java.
double [][] moa.classifiers.meta.LimAttClassifier.weightAttribute [protected]
Definition at line 472 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.prediction(), moa.classifiers.meta.LimAttClassifier.predictionPruning(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron().
FloatOption moa.classifiers.meta.LimAttClassifier.weightShrinkOption
Initial value:
 new FloatOption("weightShrink", 'w',
            "The number to multiply the weight misclassified counts.", 0.5, 0.0, Float.MAX_VALUE)
Definition at line 208 of file LimAttClassifier.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/LimAttClassifier.java