MOA: moa.streams.filters.AbstractStreamFilter Class Reference
moa.streams.filters.AbstractStreamFilter Class Reference
Abstract Stream Filter.
Public Member Functions
void setInputStream (InstanceStream stream)
Sets the input stream to the filter.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
void restart ()
Restarts this stream.
Protected Member Functions
abstract void restartImpl ()
Restarts this filter.
Protected Attributes
InstanceStream inputStream
The input stream to this filter.
Detailed Description
Abstract Stream Filter.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file AbstractStreamFilter.java.
Member Function Documentation
long moa.streams.filters.AbstractStreamFilter.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Reimplemented in moa.streams.filters.CacheFilter.
Definition at line 52 of file AbstractStreamFilter.java.
References moa.streams.InstanceStream.estimatedRemainingInstances(), and moa.streams.filters.AbstractStreamFilter.inputStream.
{
        return this.inputStream.estimatedRemainingInstances();
    }
boolean moa.streams.filters.AbstractStreamFilter.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Reimplemented in moa.streams.filters.CacheFilter.
Definition at line 57 of file AbstractStreamFilter.java.
References moa.streams.InstanceStream.hasMoreInstances(), and moa.streams.filters.AbstractStreamFilter.inputStream.
{
        return this.inputStream.hasMoreInstances();
    }
boolean moa.streams.filters.AbstractStreamFilter.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 62 of file AbstractStreamFilter.java.
References moa.streams.filters.AbstractStreamFilter.inputStream, and moa.streams.InstanceStream.isRestartable().
{
        return this.inputStream.isRestartable();
    }
void moa.streams.filters.AbstractStreamFilter.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 46 of file AbstractStreamFilter.java.
References moa.streams.filters.AbstractStreamFilter.restartImpl().
{
        restartImpl();
    }
void moa.streams.filters.AbstractStreamFilter.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 67 of file AbstractStreamFilter.java.
References moa.streams.filters.AbstractStreamFilter.inputStream, moa.streams.InstanceStream.restart(), and moa.streams.filters.AbstractStreamFilter.restartImpl().
{
        this.inputStream.restart();
        restartImpl();
    }
abstract void moa.streams.filters.AbstractStreamFilter.restartImpl () [protected, pure virtual]
Restarts this filter.
All instances that extends from AbstractStreamFilter must implement restartImpl. restart uses restartImpl in AbstractStreamFilter.
Implemented in moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, and moa.streams.filters.ReplacingMissingValuesFilter.
Referenced by moa.streams.filters.AbstractStreamFilter.prepareForUseImpl(), and moa.streams.filters.AbstractStreamFilter.restart().
void moa.streams.filters.AbstractStreamFilter.setInputStream (InstanceStream stream)
Sets the input stream to the filter.
Parameters:
stream the input stream to the filter
Implements moa.streams.filters.StreamFilter.
Definition at line 40 of file AbstractStreamFilter.java.
References moa.streams.filters.AbstractStreamFilter.inputStream, and moa.options.AbstractOptionHandler.prepareForUse().
{
        this.inputStream = stream;
        prepareForUse();
    }
Member Data Documentation
InstanceStream moa.streams.filters.AbstractStreamFilter.inputStream [protected]
The input stream to this filter.
Definition at line 37 of file AbstractStreamFilter.java.
Referenced by moa.streams.filters.AbstractStreamFilter.estimatedRemainingInstances(), moa.streams.filters.ReplacingMissingValuesFilter.getHeader(), moa.streams.filters.CacheFilter.getHeader(), moa.streams.filters.AddNoiseFilter.getHeader(), moa.streams.filters.AbstractStreamFilter.hasMoreInstances(), moa.streams.filters.CacheFilter.init(), moa.streams.filters.AbstractStreamFilter.isRestartable(), moa.streams.filters.ReplacingMissingValuesFilter.nextInstance(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.streams.filters.AbstractStreamFilter.restart(), moa.streams.filters.CacheFilter.restartImpl(), and moa.streams.filters.AbstractStreamFilter.setInputStream().
The documentation for this class was generated from the following file:
main/java/moa/streams/filters/AbstractStreamFilter.java