MOA: moa.gui.visualization.GraphCanvas Class Reference
moa.gui.visualization.GraphCanvas Class Reference
Public Member Functions
GraphCanvas ()
Creates new form GraphCanvas.
void scaleXResolution (boolean scaleUp)
void scaleYResolution (boolean scaleUp)
int getMeasureSelected ()
int getProcessFrequency ()
void setGraph (MeasureCollection measure0, MeasureCollection measure1, int mSelect, int processFrequency)
void updateCanvas ()
void updateCanvas (boolean force)
void forceAddEvents ()
void setClusterEventsList (ArrayList< ClusterEvent > clusterEvents)
void setViewport (JViewport viewport)
Protected Member Functions
void paintComponent (Graphics g)
Package Attributes
int measureSelected = 0
Private Member Functions
boolean updateMinMaxValues ()
void updateXResolution ()
void updateYValues ()
void updateSize ()
void addEvents ()
void addComponents ()
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
MeasureCollection measure0 = null
MeasureCollection measure1 = null
ArrayList< ClusterEvent > clusterEvents
ArrayList< JLabel > eventLabelList
GraphAxes axesPanel
GraphCurve curvePanel
JPanel eventPanel
int eventCounter = 0
final int x_offset_left = 35
final int x_offset_right = 5
final int y_offset_bottom = 20
final int y_offset_top = 20
int processFrequency
double min_y_value = 0
double max_y_value = 1
double max_x_value = 250
double x_resolution = 0.5
double y_resolution = 1
JViewport viewport
Detailed Description
Definition at line 31 of file GraphCanvas.java.
Constructor & Destructor Documentation
moa.gui.visualization.GraphCanvas.GraphCanvas ()
Creates new form GraphCanvas.
Definition at line 75 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.addComponents(), and moa.gui.visualization.GraphCanvas.eventLabelList.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.clustertab.ClusteringVisualTab.initComponents().
{
        addComponents();
        eventLabelList = new ArrayList<JLabel>();
    }
Member Function Documentation
void moa.gui.visualization.GraphCanvas.addComponents () [private]
Definition at line 253 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCanvas.eventPanel, moa.gui.visualization.GraphCanvas.x_offset_left, and moa.gui.visualization.GraphCanvas.y_offset_top.
Referenced by moa.gui.visualization.GraphCanvas.GraphCanvas().
{
        axesPanel = new GraphAxes();
        curvePanel = new GraphCurve();
        eventPanel = new JPanel();
        curvePanel.setLocation(x_offset_left + 1, y_offset_top);
        eventPanel.setLocation(x_offset_left + 1, 0);
        eventPanel.setLayout(null);
        add(axesPanel);
        axesPanel.add(curvePanel);
        axesPanel.add(eventPanel);
    }
void moa.gui.visualization.GraphCanvas.addEvents () [private]
Definition at line 203 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.clusterEvents, moa.gui.visualization.GraphCanvas.eventCounter, moa.gui.visualization.GraphCanvas.eventLabelList, moa.gui.visualization.GraphCanvas.eventPanel, moa.streams.clustering.ClusterEvent.getMessage(), moa.streams.clustering.ClusterEvent.getTimestamp(), moa.streams.clustering.ClusterEvent.getType(), moa.gui.visualization.GraphCanvas.processFrequency, moa.gui.visualization.GraphCanvas.x_resolution, and moa.gui.visualization.GraphCanvas.y_offset_top.
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas().
{
        if (clusterEvents != null && clusterEvents.size() > eventCounter) {
            ClusterEvent ev = clusterEvents.get(eventCounter);
            eventCounter++;
            JLabel eventMarker = new JLabel(ev.getType().substring(0, 1));
            eventMarker.setPreferredSize(new Dimension(20, y_offset_top));
            eventMarker.setSize(new Dimension(20, y_offset_top));
            eventMarker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            int x = (int) (ev.getTimestamp() / processFrequency / x_resolution);
            eventMarker.setLocation(x - 10, 0);
            eventMarker.setToolTipText(ev.getType() + " at " + ev.getTimestamp() + ": " + ev.getMessage());
            eventPanel.add(eventMarker);
            eventLabelList.add(eventMarker);
            eventPanel.repaint();
        }
    }
void moa.gui.visualization.GraphCanvas.forceAddEvents ()
Definition at line 223 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.clusterEvents, moa.gui.visualization.GraphCanvas.eventLabelList, moa.gui.visualization.GraphCanvas.eventPanel, moa.streams.clustering.ClusterEvent.getMessage(), moa.streams.clustering.ClusterEvent.getTimestamp(), moa.streams.clustering.ClusterEvent.getType(), moa.gui.visualization.GraphCanvas.processFrequency, moa.gui.visualization.GraphCanvas.x_resolution, and moa.gui.visualization.GraphCanvas.y_offset_top.
{
        if (clusterEvents != null) {
            eventPanel.removeAll();
            for (int i = 0; i < clusterEvents.size(); i++) {
                ClusterEvent ev = clusterEvents.get(i);
                JLabel eventMarker = new JLabel(ev.getType().substring(0, 1));
                eventMarker.setPreferredSize(new Dimension(20, y_offset_top));
                eventMarker.setSize(new Dimension(20, y_offset_top));
                eventMarker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                int x = (int) (ev.getTimestamp() / processFrequency / x_resolution);
                eventMarker.setLocation(x - 10, 0);
                eventMarker.setToolTipText(ev.getType() + " at " + ev.getTimestamp() + ": " + ev.getMessage());
                eventPanel.add(eventMarker);
                eventLabelList.add(eventMarker);
                eventPanel.repaint();
            }
        }
    }
int moa.gui.visualization.GraphCanvas.getMeasureSelected ()
Definition at line 98 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.measureSelected.
{
        return measureSelected;
    }
int moa.gui.visualization.GraphCanvas.getProcessFrequency ()
Definition at line 102 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.processFrequency.
{
        return this.processFrequency;
    }
void moa.gui.visualization.GraphCanvas.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 276 of file GraphCanvas.java.
{
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.GraphCanvas.paintComponent (Graphics g) [protected]
Definition at line 246 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.updateSize().
{
        //needed in case parent component gets resized
        //TODO doesn't fully work yet when reducing height
        updateSize();
        super.paintComponent(g);
    }
void moa.gui.visualization.GraphCanvas.scaleXResolution (boolean scaleUp)
Definition at line 80 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.updateCanvas(), and moa.gui.visualization.GraphCanvas.x_resolution.
{
        if (scaleUp) {
            x_resolution *= 2;
        } else {
            x_resolution /= 2;
        }
        updateCanvas(true);
    }
void moa.gui.visualization.GraphCanvas.scaleYResolution (boolean scaleUp)
Definition at line 89 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.updateCanvas(), and moa.gui.visualization.GraphCanvas.y_resolution.
{
        if (scaleUp) {
            y_resolution *= 2;
        } else {
            y_resolution /= 2;
        }
        updateCanvas(true);
    }
void moa.gui.visualization.GraphCanvas.setClusterEventsList (ArrayList< ClusterEvent > clusterEvents)
Definition at line 281 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.curvePanel, and moa.gui.visualization.GraphCurve.setClusterEventsList().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        this.clusterEvents = clusterEvents;
        curvePanel.setClusterEventsList(clusterEvents);
    }
void moa.gui.visualization.GraphCanvas.setGraph (MeasureCollection measure0, MeasureCollection measure1, int mSelect, int processFrequency)
Definition at line 106 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCanvas.measureSelected, moa.gui.visualization.GraphCurve.setGraph(), moa.gui.visualization.GraphCurve.setProcessFrequency(), moa.gui.visualization.GraphAxes.setProcessFrequency(), and moa.gui.visualization.GraphCanvas.updateCanvas().
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        this.measure0 = measure0;
        this.measure1 = measure1;
        measureSelected = mSelect;
        this.processFrequency = processFrequency;
        axesPanel.setProcessFrequency(processFrequency);
        curvePanel.setProcessFrequency(processFrequency);
        curvePanel.setGraph(measure0, measure1, mSelect);
        updateCanvas();
    }
void moa.gui.visualization.GraphCanvas.setViewport (JViewport viewport)
Definition at line 286 of file GraphCanvas.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.resetComponents(), and moa.gui.clustertab.ClusteringVisualTab.resetComponents().
{
        this.viewport = viewport;
    }
void moa.gui.visualization.GraphCanvas.updateCanvas (boolean force)
Definition at line 121 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCanvas.max_x_value, moa.gui.visualization.GraphAxes.setXMaxValue(), moa.gui.visualization.GraphCanvas.updateMinMaxValues(), moa.gui.visualization.GraphCanvas.updateSize(), moa.gui.visualization.GraphCanvas.updateXResolution(), moa.gui.visualization.GraphCanvas.updateYValues(), and moa.gui.visualization.GraphCanvas.x_resolution.
{
        //check for new min max values first so we know if we have to do some resizing
        if (updateMinMaxValues() || force) {
            int maxLabel = (int) Math.ceil(max_x_value / x_resolution / 500);
            int width = (int) (maxLabel * 500);
            setSize(width, getHeight());
            setPreferredSize(new Dimension(width, getHeight()));
            axesPanel.setXMaxValue(maxLabel);
            updateXResolution();
            updateYValues();
            updateSize();
            axesPanel.repaint();
        }
        //check for new events
        addEvents();
        //add the latest plot point through repaint
        //TODO: somehow realize incremental painting? (real heavyweight canvas: update())
        curvePanel.repaint();
    }
void moa.gui.visualization.GraphCanvas.updateCanvas ()
Definition at line 117 of file GraphCanvas.java.
Referenced by moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.GraphCanvas.scaleXResolution(), moa.gui.visualization.GraphCanvas.scaleYResolution(), moa.gui.visualization.GraphCanvas.setGraph(), and moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj().
{
        updateCanvas(false);
    }
boolean moa.gui.visualization.GraphCanvas.updateMinMaxValues () [private]
Definition at line 148 of file GraphCanvas.java.
References moa.evaluation.MeasureCollection.getMaxValue(), moa.evaluation.MeasureCollection.getMinValue(), moa.evaluation.MeasureCollection.getNumberOfValues(), moa.gui.visualization.GraphCanvas.max_x_value, moa.gui.visualization.GraphCanvas.max_y_value, moa.gui.visualization.GraphCanvas.measure0, moa.gui.visualization.GraphCanvas.measure1, moa.gui.visualization.GraphCanvas.measureSelected, and moa.gui.visualization.GraphCanvas.min_y_value.
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas().
{
        double min_y_value_new = min_y_value;
        double max_y_value_new = max_y_value;
        double max_x_value_new = max_x_value;
        if (measure0 != null && measure1 != null) {
            min_y_value_new = Math.min(measure0.getMinValue(measureSelected), measure1.getMinValue(measureSelected));
            max_y_value_new = Math.max(measure0.getMaxValue(measureSelected), measure1.getMaxValue(measureSelected));
            max_x_value_new = Math.max(measure0.getNumberOfValues(measureSelected), max_x_value);
        } else {
            if (measure0 != null) {
                min_y_value_new = measure0.getMinValue(measureSelected);
                max_y_value_new = measure0.getMaxValue(measureSelected);
                max_x_value_new = Math.max(measure0.getNumberOfValues(measureSelected), max_x_value);
            }
        }
        //resizing needed?
        if (max_x_value_new != max_x_value || max_y_value_new != max_y_value || min_y_value_new != min_y_value) {
            min_y_value = min_y_value_new;
            max_y_value = max_y_value_new;
            max_x_value = max_x_value_new;
            return true;
        }
        return false;
    }
void moa.gui.visualization.GraphCanvas.updateSize () [private]
Definition at line 185 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.clusterEvents, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCanvas.eventLabelList, moa.gui.visualization.GraphCanvas.eventPanel, moa.gui.visualization.GraphCanvas.processFrequency, moa.gui.visualization.GraphCanvas.x_offset_left, moa.gui.visualization.GraphCanvas.x_offset_right, moa.gui.visualization.GraphCanvas.x_resolution, moa.gui.visualization.GraphCanvas.y_offset_bottom, and moa.gui.visualization.GraphCanvas.y_offset_top.
Referenced by moa.gui.visualization.GraphCanvas.paintComponent(), and moa.gui.visualization.GraphCanvas.updateCanvas().
{
        axesPanel.setSize(getWidth(), getHeight());
        //axesPanel.setPreferredSize(new Dimension(getWidth(), getHeight()));
        curvePanel.setSize(getWidth() - x_offset_left - x_offset_right, getHeight() - y_offset_bottom - y_offset_top);
        eventPanel.setSize(getWidth() - x_offset_left - x_offset_right, y_offset_top);
        if (clusterEvents != null) {
            //update Label positions
            for (int i = 0; i < clusterEvents.size(); i++) {
                int x = (int) (clusterEvents.get(i).getTimestamp() / processFrequency / x_resolution);
                if (i < eventLabelList.size()) {
                    eventLabelList.get(i).setLocation(x - 10, 0);
                }
            }
        }
    }
void moa.gui.visualization.GraphCanvas.updateXResolution () [private]
Definition at line 175 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCurve.setXResolution(), moa.gui.visualization.GraphAxes.setXResolution(), and moa.gui.visualization.GraphCanvas.x_resolution.
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas().
{
        axesPanel.setXResolution(x_resolution);
        curvePanel.setXResolution(x_resolution);
    }
void moa.gui.visualization.GraphCanvas.updateYValues () [private]
Definition at line 180 of file GraphCanvas.java.
References moa.gui.visualization.GraphCanvas.axesPanel, moa.gui.visualization.GraphCanvas.curvePanel, moa.gui.visualization.GraphCanvas.max_y_value, moa.gui.visualization.GraphCanvas.min_y_value, moa.gui.visualization.GraphCurve.setYMinMaxValues(), and moa.gui.visualization.GraphAxes.setYMinMaxValues().
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas().
{
        axesPanel.setYMinMaxValues(min_y_value, max_y_value);
        curvePanel.setYMinMaxValues(min_y_value, max_y_value);
    }
Member Data Documentation
GraphAxes moa.gui.visualization.GraphCanvas.axesPanel [private]
Definition at line 43 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addComponents(), moa.gui.visualization.GraphCanvas.setGraph(), moa.gui.visualization.GraphCanvas.updateCanvas(), moa.gui.visualization.GraphCanvas.updateSize(), moa.gui.visualization.GraphCanvas.updateXResolution(), and moa.gui.visualization.GraphCanvas.updateYValues().
ArrayList<ClusterEvent> moa.gui.visualization.GraphCanvas.clusterEvents [private]
Definition at line 39 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), and moa.gui.visualization.GraphCanvas.updateSize().
GraphCurve moa.gui.visualization.GraphCanvas.curvePanel [private]
Definition at line 45 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addComponents(), moa.gui.visualization.GraphCanvas.setClusterEventsList(), moa.gui.visualization.GraphCanvas.setGraph(), moa.gui.visualization.GraphCanvas.updateCanvas(), moa.gui.visualization.GraphCanvas.updateSize(), moa.gui.visualization.GraphCanvas.updateXResolution(), and moa.gui.visualization.GraphCanvas.updateYValues().
int moa.gui.visualization.GraphCanvas.eventCounter = 0 [private]
Definition at line 49 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addEvents().
ArrayList<JLabel> moa.gui.visualization.GraphCanvas.eventLabelList [private]
Definition at line 41 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), moa.gui.visualization.GraphCanvas.GraphCanvas(), and moa.gui.visualization.GraphCanvas.updateSize().
JPanel moa.gui.visualization.GraphCanvas.eventPanel [private]
Definition at line 47 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addComponents(), moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), and moa.gui.visualization.GraphCanvas.updateSize().
double moa.gui.visualization.GraphCanvas.max_x_value = 250 [private]
Definition at line 66 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateCanvas(), and moa.gui.visualization.GraphCanvas.updateMinMaxValues().
double moa.gui.visualization.GraphCanvas.max_y_value = 1 [private]
Definition at line 64 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues(), and moa.gui.visualization.GraphCanvas.updateYValues().
MeasureCollection moa.gui.visualization.GraphCanvas.measure0 = null [private]
Definition at line 33 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues().
MeasureCollection moa.gui.visualization.GraphCanvas.measure1 = null [private]
Definition at line 35 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues().
int moa.gui.visualization.GraphCanvas.measureSelected = 0 [package]
Definition at line 37 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.getMeasureSelected(), moa.gui.visualization.GraphCanvas.setGraph(), and moa.gui.visualization.GraphCanvas.updateMinMaxValues().
double moa.gui.visualization.GraphCanvas.min_y_value = 0 [private]
Definition at line 62 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues(), and moa.gui.visualization.GraphCanvas.updateYValues().
int moa.gui.visualization.GraphCanvas.processFrequency [private]
Definition at line 59 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), moa.gui.visualization.GraphCanvas.getProcessFrequency(), and moa.gui.visualization.GraphCanvas.updateSize().
JViewport moa.gui.visualization.GraphCanvas.viewport [private]
Definition at line 72 of file GraphCanvas.java.
final int moa.gui.visualization.GraphCanvas.x_offset_left = 35 [private]
Definition at line 51 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addComponents(), and moa.gui.visualization.GraphCanvas.updateSize().
final int moa.gui.visualization.GraphCanvas.x_offset_right = 5 [private]
Definition at line 53 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateSize().
double moa.gui.visualization.GraphCanvas.x_resolution = 0.5 [private]
Definition at line 68 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), moa.gui.visualization.GraphCanvas.scaleXResolution(), moa.gui.visualization.GraphCanvas.updateCanvas(), moa.gui.visualization.GraphCanvas.updateSize(), and moa.gui.visualization.GraphCanvas.updateXResolution().
final int moa.gui.visualization.GraphCanvas.y_offset_bottom = 20 [private]
Definition at line 55 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.updateSize().
final int moa.gui.visualization.GraphCanvas.y_offset_top = 20 [private]
Definition at line 57 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.addComponents(), moa.gui.visualization.GraphCanvas.addEvents(), moa.gui.visualization.GraphCanvas.forceAddEvents(), and moa.gui.visualization.GraphCanvas.updateSize().
double moa.gui.visualization.GraphCanvas.y_resolution = 1 [private]
Definition at line 70 of file GraphCanvas.java.
Referenced by moa.gui.visualization.GraphCanvas.scaleYResolution().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/GraphCanvas.java