MOA: moa.streams.generators.SEAGenerator Class Reference
moa.streams.generators.SEAGenerator Class Reference
Stream generator for SEA concepts functions.
Classes
interface ClassFunction
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption functionOption
IntOption instanceRandomSeedOption
FlagOption balanceClassesOption
IntOption numInstancesConcept
IntOption noisePercentageOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
InstancesHeader streamHeader
Random instanceRandom
boolean nextClassShouldBeZero
Static Protected Attributes
static ClassFunction[] classificationFunctions
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for SEA concepts functions.
Generator described in the paper:
W. Nick Street and YongSeog Kim "A streaming ensemble algorithm (SEA) for large-scale classification", KDD '01: Proceedings of the seventh ACM SIGKDD international conference on Knowledge discovery and data mining 377-382 2001.
Notes:
The built in functions are based on the paper.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 52 of file SEAGenerator.java.
Member Function Documentation
long moa.streams.generators.SEAGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 144 of file SEAGenerator.java.
{
        return -1;
    }
void moa.streams.generators.SEAGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 210 of file SEAGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.SEAGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 149 of file SEAGenerator.java.
References moa.streams.generators.SEAGenerator.streamHeader.
Referenced by moa.streams.generators.SEAGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.SEAGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 56 of file SEAGenerator.java.
{
        return "Generates SEA concepts functions.";
    }
boolean moa.streams.generators.SEAGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 154 of file SEAGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.SEAGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 159 of file SEAGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.SEAGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 164 of file SEAGenerator.java.
References moa.streams.generators.SEAGenerator.balanceClassesOption, moa.streams.generators.SEAGenerator.classificationFunctions, moa.streams.generators.SEAGenerator.ClassFunction.determineClass(), moa.streams.generators.SEAGenerator.functionOption, moa.streams.generators.SEAGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.SEAGenerator.instanceRandom, moa.options.FlagOption.isSet, moa.streams.generators.SEAGenerator.nextClassShouldBeZero, and moa.streams.generators.SEAGenerator.noisePercentageOption.
{
        double attrib1 = 0, attrib2 = 0, attrib3 = 0;
        int group = 0;
        boolean desiredClassFound = false;
        while (!desiredClassFound) {
            // generate attributes
            attrib1 = 10 * this.instanceRandom.nextDouble();
            attrib2 = 10 * this.instanceRandom.nextDouble();
            attrib3 = 10 * this.instanceRandom.nextDouble();
            // determine class
            group = classificationFunctions[this.functionOption.getValue() - 1].determineClass(attrib1, attrib2, attrib3);
            if (!this.balanceClassesOption.isSet()) {
                desiredClassFound = true;
            } else {
                // balance the classes
                if ((this.nextClassShouldBeZero && (group == 0))
                        || (!this.nextClassShouldBeZero && (group == 1))) {
                    desiredClassFound = true;
                    this.nextClassShouldBeZero = !this.nextClassShouldBeZero;
                } // else keep searching
            }
        }
        //Add Noise
        if ((1 + (this.instanceRandom.nextInt(100))) <= this.noisePercentageOption.getValue()) {
            group = (group == 0 ? 1 : 0);
        }
        // construct instance
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        inst.setValue(0, attrib1);
        inst.setValue(1, attrib2);
        inst.setValue(2, attrib3);
        inst.setDataset(header);
        inst.setClassValue(group);
        return inst;
    }
void moa.streams.generators.SEAGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 125 of file SEAGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.streams.generators.SEAGenerator.restart(), and moa.streams.generators.SEAGenerator.streamHeader.
{
        // generate header
        FastVector attributes = new FastVector();
        attributes.addElement(new Attribute("attrib1"));
        attributes.addElement(new Attribute("attrib2"));
        attributes.addElement(new Attribute("attrib3"));
        FastVector classLabels = new FastVector();
        classLabels.addElement("groupA");
        classLabels.addElement("groupB");
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
        restart();
    }
void moa.streams.generators.SEAGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 204 of file SEAGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.SEAGenerator.instanceRandom, moa.streams.generators.SEAGenerator.instanceRandomSeedOption, and moa.streams.generators.SEAGenerator.nextClassShouldBeZero.
Referenced by moa.streams.generators.SEAGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
        this.nextClassShouldBeZero = false;
    }
Member Data Documentation
FlagOption moa.streams.generators.SEAGenerator.balanceClassesOption
Initial value:
 new FlagOption("balanceClasses",
            'b', "Balance the number of instances of each class.")
Definition at line 70 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance().
ClassFunction [] moa.streams.generators.SEAGenerator.classificationFunctions [static, protected]
Definition at line 84 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance().
IntOption moa.streams.generators.SEAGenerator.functionOption
Initial value:
 new IntOption("function", 'f',
            "Classification function used, as defined in the original paper.",
            1, 1, 4)
Definition at line 62 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance().
Random moa.streams.generators.SEAGenerator.instanceRandom [protected]
Definition at line 120 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance(), and moa.streams.generators.SEAGenerator.restart().
IntOption moa.streams.generators.SEAGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 66 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.restart().
boolean moa.streams.generators.SEAGenerator.nextClassShouldBeZero [protected]
Definition at line 122 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance(), and moa.streams.generators.SEAGenerator.restart().
IntOption moa.streams.generators.SEAGenerator.noisePercentageOption
Initial value:
 new IntOption("noisePercentage",
            'n', "Percentage of noise to add to the data.", 10, 0, 100)
Definition at line 76 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.nextInstance().
IntOption moa.streams.generators.SEAGenerator.numInstancesConcept
Initial value:
 new IntOption("numInstancesConcept", 'n',
            "The number of instances for each concept.", 0, 0, Integer.MAX_VALUE)
Definition at line 73 of file SEAGenerator.java.
final long moa.streams.generators.SEAGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 60 of file SEAGenerator.java.
InstancesHeader moa.streams.generators.SEAGenerator.streamHeader [protected]
Definition at line 118 of file SEAGenerator.java.
Referenced by moa.streams.generators.SEAGenerator.getHeader(), and moa.streams.generators.SEAGenerator.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/SEAGenerator.java