MOA: moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver Class Reference
moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver Class Reference
Class for observing the class data distribution for a numeric attribute using gaussian estimators.
Public Member Functions
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
double[] getSplitPointSuggestions ()
double[][] getClassDistsResultingFromBinarySplit (double splitValue)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void observeAttributeTarget (double attVal, double target)
Public Attributes
IntOption numBinsOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
DoubleVector minValueObservedPerClass = new DoubleVector()
DoubleVector maxValueObservedPerClass = new DoubleVector()
AutoExpandVector
< GaussianEstimator > attValDistPerClass = new AutoExpandVector<GaussianEstimator>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for observing the class data distribution for a numeric attribute using gaussian estimators.
This observer monitors the class distribution of a given attribute. Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file GaussianNumericAttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 90 of file GaussianNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), and moa.classifiers.core.AttributeSplitSuggestion.merit.
{
        AttributeSplitSuggestion bestSuggestion = null;
        double[] suggestedSplitValues = getSplitPointSuggestions();
        for (double splitValue : suggestedSplitValues) {
            double[][] postSplitDists = getClassDistsResultingFromBinarySplit(splitValue);
            double merit = criterion.getMeritOfSplit(preSplitDist,
                    postSplitDists);
            if ((bestSuggestion == null) || (merit > bestSuggestion.merit)) {
                bestSuggestion = new AttributeSplitSuggestion(
                        new NumericAttributeBinaryTest(attIndex, splitValue,
                        true), postSplitDists, merit);
            }
        }
        return bestSuggestion;
    }
double [][] moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit (double splitValue)
Definition at line 142 of file GaussianNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.attValDistPerClass, moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(), moa.core.DoubleVector.getArrayRef(), moa.core.GaussianEstimator.getTotalWeightObserved(), moa.core.DoubleVector.getValue(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.maxValueObservedPerClass, and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.minValueObservedPerClass.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        DoubleVector lhsDist = new DoubleVector();
        DoubleVector rhsDist = new DoubleVector();
        for (int i = 0; i < this.attValDistPerClass.size(); i++) {
            GaussianEstimator estimator = this.attValDistPerClass.get(i);
            if (estimator != null) {
                if (splitValue < this.minValueObservedPerClass.getValue(i)) {
                    rhsDist.addToValue(i, estimator.getTotalWeightObserved());
                } else if (splitValue >= this.maxValueObservedPerClass.getValue(i)) {
                    lhsDist.addToValue(i, estimator.getTotalWeightObserved());
                } else {
                    double[] weightDist = estimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(splitValue);
                    lhsDist.addToValue(i, weightDist[0] + weightDist[1]);
                    rhsDist.addToValue(i, weightDist[2]);
                }
            }
        }
        return new double[][]{lhsDist.getArrayRef(), rhsDist.getArrayRef()};
    }
void moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 163 of file GaussianNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double [] moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions ()
Definition at line 108 of file GaussianNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.attValDistPerClass, moa.options.IntOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.maxValueObservedPerClass, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.minValueObservedPerClass, and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.numBinsOption.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        Set<Double> suggestedSplitValues = new TreeSet<Double>();
        double minValue = Double.POSITIVE_INFINITY;
        double maxValue = Double.NEGATIVE_INFINITY;
        for (int i = 0; i < this.attValDistPerClass.size(); i++) {
            GaussianEstimator estimator = this.attValDistPerClass.get(i);
            if (estimator != null) {
                if (this.minValueObservedPerClass.getValue(i) < minValue) {
                    minValue = this.minValueObservedPerClass.getValue(i);
                }
                if (this.maxValueObservedPerClass.getValue(i) > maxValue) {
                    maxValue = this.maxValueObservedPerClass.getValue(i);
                }
            }
        }
        if (minValue < Double.POSITIVE_INFINITY) {
            double range = maxValue - minValue;
            for (int i = 0; i < this.numBinsOption.getValue(); i++) {
                double splitValue = range / (this.numBinsOption.getValue() + 1.0) * (i + 1)
                        + minValue;
                if ((splitValue > minValue) && (splitValue < maxValue)) {
                    suggestedSplitValues.add(splitValue);
                }
            }
        }
        double[] suggestions = new double[suggestedSplitValues.size()];
        int i = 0;
        for (double suggestion : suggestedSplitValues) {
            suggestions[i++] = suggestion;
        }
        return suggestions;
    }
void moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 61 of file GaussianNumericAttributeClassObserver.java.
References moa.core.GaussianEstimator.addObservation(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.attValDistPerClass, moa.core.DoubleVector.getValue(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.maxValueObservedPerClass, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.minValueObservedPerClass, and moa.core.DoubleVector.setValue().
{
        if (Utils.isMissingValue(attVal)) {
        } else {
            GaussianEstimator valDist = this.attValDistPerClass.get(classVal);
            if (valDist == null) {
                valDist = new GaussianEstimator();
                this.attValDistPerClass.set(classVal, valDist);
                this.minValueObservedPerClass.setValue(classVal, attVal);
                this.maxValueObservedPerClass.setValue(classVal, attVal);
            } else {
                if (attVal < this.minValueObservedPerClass.getValue(classVal)) {
                    this.minValueObservedPerClass.setValue(classVal, attVal);
                }
                if (attVal > this.maxValueObservedPerClass.getValue(classVal)) {
                    this.maxValueObservedPerClass.setValue(classVal, attVal);
                }
            }
            valDist.addObservation(attVal, weight);
        }
    }
void moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 173 of file GaussianNumericAttributeClassObserver.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
void moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 168 of file GaussianNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 83 of file GaussianNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.attValDistPerClass, and moa.core.GaussianEstimator.probabilityDensity().
{
        GaussianEstimator obs = this.attValDistPerClass.get(classVal);
        return obs != null ? obs.probabilityDensity(attVal) : 0.0;
    }
Member Data Documentation
AutoExpandVector<GaussianEstimator> moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.attValDistPerClass = new AutoExpandVector<GaussianEstimator>() [protected]
Definition at line 55 of file GaussianNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass().
DoubleVector moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.maxValueObservedPerClass = new DoubleVector() [protected]
Definition at line 53 of file GaussianNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass().
DoubleVector moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.minValueObservedPerClass = new DoubleVector() [protected]
Definition at line 51 of file GaussianNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass().
IntOption moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.numBinsOption
Initial value:
 new IntOption("numBins", 'n',
            "The number of bins.", 10, 1, Integer.MAX_VALUE)
Definition at line 57 of file GaussianNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions().
final long moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 49 of file GaussianNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/GaussianNumericAttributeClassObserver.java