MOA: moa.cluster.SphereCluster Class Reference
moa.cluster.SphereCluster Class Reference
A simple implementation of the Cluster interface representing spherical clusters.
Public Member Functions
SphereCluster (double[] center, double radius)
SphereCluster ()
SphereCluster (double[] center, double radius, double weightedSize)
SphereCluster (int dimensions, double radius, Random random)
SphereCluster (List<?extends Instance > instances, int dimension)
double overlapRadiusDegree (SphereCluster other)
Checks whether two SphereCluster overlap based on radius NOTE: overlapRadiusDegree only calculates the overlap based on the centers and the radi, so not the real overlap.
void combine (SphereCluster cluster)
void merge (SphereCluster cluster)
double[] getCenter ()
void setCenter (double[] center)
double getRadius ()
void setRadius (double radius)
double getWeight ()
Returns the weight of this cluster, not neccessarily normalized.
void setWeight (double weight)
double getInclusionProbability (Instance instance)
Returns the probability of the given point belonging to this cluster.
double getCenterDistance (Instance instance)
double getCenterDistance (SphereCluster other)
double getHullDistance (SphereCluster other)
boolean overlapSave (SphereCluster other)
When a clusters looses points the new minimal bounding sphere can be partly outside of the originating cluster.
double[] getDistanceVector (Instance instance)
double[] getDistanceVector (SphereCluster other)
Instance sample (Random random)
Samples this cluster by returning a point from inside it.
Protected Member Functions
void getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue)
Private Member Functions
double distance (double[] v1, double[] v2)
double[] distanceVector (double[] v1, double[] v2)
Private Attributes
double[] center
double radius
double weight
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
A simple implementation of the Cluster interface representing spherical clusters.
The inclusion probability is one inside the sphere and zero everywhere else.
Definition at line 35 of file SphereCluster.java.
Constructor & Destructor Documentation
moa.cluster.SphereCluster.SphereCluster (double[] center, double radius)
Definition at line 44 of file SphereCluster.java.
{
        this( center, radius, 1.0 );
    }
moa.cluster.SphereCluster.SphereCluster ()
Definition at line 48 of file SphereCluster.java.
{
    }
moa.cluster.SphereCluster.SphereCluster (double[] center, double radius, double weightedSize)
Definition at line 51 of file SphereCluster.java.
References moa.cluster.SphereCluster.weight.
{
        this();
        this.center = center;
        this.radius = radius;
        this.weight = weightedSize;
    }
moa.cluster.SphereCluster.SphereCluster (int dimensions, double radius, Random random)
Definition at line 58 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, and moa.cluster.SphereCluster.weight.
{
        this();
        this.center = new double[dimensions];
        this.radius = radius;
        // Position randomly but keep hypersphere inside the boundaries
        double interval = 1.0 - 2 * radius;
        for (int i = 0; i < center.length; i++) {
            this.center[i] = (random.nextDouble() * interval) + radius;
        }
        this.weight = 0.0;
    }
moa.cluster.SphereCluster.SphereCluster (List<?extends Instance > instances, int dimension)
Definition at line 72 of file SphereCluster.java.
References moa.cluster.Miniball.build(), moa.cluster.Miniball.center(), moa.cluster.SphereCluster.center, moa.cluster.Miniball.check_in(), moa.cluster.Miniball.clear(), moa.cluster.Miniball.radius(), moa.cluster.SphereCluster.radius, and moa.cluster.SphereCluster.weight.
{
        this();
        if(instances == null || instances.size() <= 0)
            return;
        weight = instances.size();
        Miniball mb = new Miniball(dimension);
        mb.clear();
        for (Instance instance : instances) {
            mb.check_in(instance.toDoubleArray());
        }
        mb.build();
        center = mb.center();
        radius = mb.radius();
        mb.clear();
    }
Member Function Documentation
void moa.cluster.SphereCluster.combine (SphereCluster cluster)
Definition at line 142 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, moa.cluster.SphereCluster.distance(), moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getRadius(), moa.cluster.SphereCluster.getWeight(), moa.cluster.SphereCluster.radius, and moa.cluster.SphereCluster.weight.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        double[] center = getCenter();
        double[] newcenter = new double[center.length];
        double[] other_center = cluster.getCenter();
        double other_weight = cluster.getWeight();
        double other_radius = cluster.getRadius();
        for (int i = 0; i < center.length; i++) {
            newcenter[i] = (center[i]*getWeight()+other_center[i]*other_weight)/(getWeight()+other_weight);
        }
        center = newcenter;
        double r_0 = getRadius() + Math.abs(distance(center, newcenter));
        double r_1 = other_radius + Math.abs(distance(other_center, newcenter));
        radius = Math.max(r_0, r_1);
        weight+= other_weight;
    }
double moa.cluster.SphereCluster.distance (double[] v1, double[] v2) [private]
Definition at line 300 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, and moa.cluster.SphereCluster.getCenter().
Referenced by moa.cluster.SphereCluster.combine(), moa.cluster.SphereCluster.getCenterDistance(), moa.cluster.SphereCluster.getHullDistance(), moa.clusterers.clustree.ClusKernel.getInclusionProbability(), and moa.clusterers.clustream.ClustreamKernel.getInclusionProbability().
{
        double distance = 0.0;
        double[] center = getCenter();
        for (int i = 0; i < center.length; i++) {
            double d = v1[i] - v2[i];
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
double [] moa.cluster.SphereCluster.distanceVector (double[] v1, double[] v2) [private]
Definition at line 318 of file SphereCluster.java.
Referenced by moa.cluster.SphereCluster.getDistanceVector().
{
        double[] v = new double[v1.length];
        for (int i = 0; i < v1.length; i++) {
            v[i] = v2[i] - v1[i];
        }
        return v;
    }
double [] moa.cluster.SphereCluster.getCenter () [virtual]
Returns:
the center of the cluster
Implements moa.cluster.Cluster.
Reimplemented in moa.cluster.CFCluster, moa.clusterers.clustream.ClustreamKernel, moa.clusterers.clustree.ClusKernel, and moa.clusterers.denstream.MicroCluster.
Definition at line 210 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, and moa.AbstractMOAObject.copy().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.clusterers.ClusterGenerator.alterClustering(), moa.gui.visualization.ClusterPanel.ClusterPanel(), moa.cluster.SphereCluster.combine(), moa.cluster.SphereCluster.distance(), moa.cluster.SphereCluster.getCenterDistance(), moa.cluster.SphereCluster.getDistanceVector(), moa.cluster.SphereCluster.getHullDistance(), moa.clusterers.ClusterGenerator.joinClusters(), moa.clusterers.clustream.WithKmeans.kMeans(), moa.cluster.SphereCluster.merge(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), moa.gui.visualization.OutlierPanel.OutlierPanel(), moa.cluster.SphereCluster.overlapRadiusDegree(), moa.cluster.SphereCluster.sample(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
{
        double[] copy = new double[center.length];
        System.arraycopy(center, 0, copy, 0, center.length);
        return copy;
    }
double moa.cluster.SphereCluster.getCenterDistance (SphereCluster other)
Definition at line 256 of file SphereCluster.java.
References moa.cluster.SphereCluster.distance(), and moa.cluster.SphereCluster.getCenter().
{
        return distance(getCenter(), other.getCenter());
    }
double moa.cluster.SphereCluster.getCenterDistance (Instance instance)
Definition at line 245 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, moa.cluster.SphereCluster.distance(), and moa.cluster.SphereCluster.getCenter().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.clusterers.denstream.MicroCluster.getInclusionProbability(), moa.cluster.SphereCluster.getInclusionProbability(), moa.evaluation.CMM.missedError(), and moa.cluster.SphereCluster.overlapSave().
{
        double distance = 0.0;
        //get the center through getCenter so subclass have a chance
        double[] center = getCenter();
        for (int i = 0; i < center.length; i++) {
            double d = center[i] - instance.value(i);
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
void moa.cluster.SphereCluster.getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue) [protected]
Reimplemented from moa.cluster.Cluster.
Reimplemented in moa.clusterers.clustream.ClustreamKernel.
Definition at line 369 of file SphereCluster.java.
References moa.cluster.SphereCluster.getRadius().
{
        super.getClusterSpecificInfo(infoTitle, infoValue);
        infoTitle.add("Radius");
        infoValue.add(Double.toString(getRadius()));
    }
double [] moa.cluster.SphereCluster.getDistanceVector (SphereCluster other)
Definition at line 314 of file SphereCluster.java.
References moa.cluster.SphereCluster.distanceVector(), and moa.cluster.SphereCluster.getCenter().
{
        return distanceVector(getCenter(), other.getCenter());
    }
double [] moa.cluster.SphereCluster.getDistanceVector (Instance instance)
Definition at line 310 of file SphereCluster.java.
References moa.cluster.SphereCluster.distanceVector(), and moa.cluster.SphereCluster.getCenter().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels().
{
        return distanceVector(getCenter(), instance.toDoubleArray());
    }
double moa.cluster.SphereCluster.getHullDistance (SphereCluster other)
Definition at line 264 of file SphereCluster.java.
References moa.cluster.SphereCluster.distance(), moa.cluster.SphereCluster.getCenter(), and moa.cluster.SphereCluster.getRadius().
Referenced by moa.clusterers.ClusterGenerator.joinClusters().
{
        double distance = 0.0;
        //get the center through getCenter so subclass have a chance
        double[] center0 = getCenter();
        double[] center1 = other.getCenter();
        distance = distance(center0, center1);
        distance = distance - getRadius() - other.getRadius();
        return distance;
    }
double moa.cluster.SphereCluster.getInclusionProbability (Instance instance) [virtual]
Returns the probability of the given point belonging to this cluster.
Parameters:
point
Returns:
a value between 0 and 1
Implements moa.cluster.Cluster.
Reimplemented in moa.cluster.CFCluster, moa.clusterers.clustream.ClustreamKernel, moa.clusterers.clustree.ClusKernel, moa.clusterers.denstream.MicroCluster, and moa.clusterers.macro.NonConvexCluster.
Definition at line 238 of file SphereCluster.java.
References moa.cluster.SphereCluster.getCenterDistance(), and moa.cluster.SphereCluster.getRadius().
Referenced by moa.cluster.Clustering.Clustering().
{
        if (getCenterDistance(instance) <= getRadius()) {
            return 1.0;
        }
        return 0.0;
    }
double moa.cluster.SphereCluster.getRadius ()
Reimplemented in moa.cluster.CFCluster, moa.clusterers.clustream.ClustreamKernel, moa.clusterers.clustree.ClusKernel, moa.clusterers.denstream.MicroCluster, and moa.clusterers.macro.NonConvexCluster.
Definition at line 220 of file SphereCluster.java.
References moa.cluster.SphereCluster.radius.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.clusterers.ClusterGenerator.alterClustering(), moa.gui.visualization.ClusterPanel.ClusterPanel(), moa.cluster.SphereCluster.combine(), moa.evaluation.General.computeCompactness(), moa.cluster.SphereCluster.getClusterSpecificInfo(), moa.cluster.SphereCluster.getHullDistance(), moa.cluster.SphereCluster.getInclusionProbability(), moa.clusterers.ClusterGenerator.joinClusters(), moa.cluster.SphereCluster.merge(), moa.evaluation.CMM.missedError(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), moa.gui.visualization.OutlierPanel.OutlierPanel(), moa.cluster.SphereCluster.overlapRadiusDegree(), moa.cluster.SphereCluster.overlapSave(), moa.cluster.SphereCluster.sample(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        return radius;
    }
double moa.cluster.SphereCluster.getWeight () [virtual]
Returns the weight of this cluster, not neccessarily normalized.
It could, for instance, simply return the number of points contined in this cluster.
Returns:
the weight
Implements moa.cluster.Cluster.
Reimplemented in moa.cluster.CFCluster, moa.clusterers.clustree.ClusKernel, and moa.clusterers.denstream.MicroCluster.
Definition at line 229 of file SphereCluster.java.
References moa.cluster.SphereCluster.weight.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.cluster.SphereCluster.combine(), moa.clusterers.ClusterGenerator.joinClusters(), and moa.cluster.SphereCluster.merge().
{
        return weight;
    }
void moa.cluster.SphereCluster.merge (SphereCluster cluster)
Definition at line 160 of file SphereCluster.java.
References moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getRadius(), moa.cluster.SphereCluster.getWeight(), moa.cluster.SphereCluster.setCenter(), moa.cluster.SphereCluster.setRadius(), and moa.cluster.SphereCluster.setWeight().
Referenced by moa.clusterers.ClusterGenerator.joinClusters().
{
        double[] c0 = getCenter();
        double w0 = getWeight();
        double r0 = getRadius();
        double[] c1 = cluster.getCenter();
        double w1 = cluster.getWeight();
        double r1 = cluster.getRadius();
        //vector
        double[] v = new double[c0.length];
        //center distance
        double d = 0;
        for (int i = 0; i < c0.length; i++) {
            v[i] = c0[i] - c1[i];
            d += v[i] * v[i];
        }
        d = Math.sqrt(d);
        double r = 0;
        double[] c = new double[c0.length];
        //one lays within the others
        if(d + r0 <= r1  || d + r1 <= r0){
            if(d + r0 <= r1){
                r = r1;
                c = c1;
            }
            else{
                r = r0;
                c = c0;
            }
        }
        else{
            r = (r0 + r1 + d)/2.0;
            for (int i = 0; i < c.length; i++) {
                c[i] = c1[i] - v[i]/d * (r1-r);
            }
        }
        setCenter(c);
        setRadius(r);
        setWeight(w0+w1);
    }
double moa.cluster.SphereCluster.overlapRadiusDegree (SphereCluster other)
Checks whether two SphereCluster overlap based on radius NOTE: overlapRadiusDegree only calculates the overlap based on the centers and the radi, so not the real overlap.
TODO: should we do this by MC to get the real overlap???
Parameters:
other
Returns:
Definition at line 104 of file SphereCluster.java.
References moa.cluster.SphereCluster.getCenter(), and moa.cluster.SphereCluster.getRadius().
Referenced by moa.evaluation.General.computeOverlap(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        double[] center0 = getCenter();
        double radius0 = getRadius();
        double[] center1 = other.getCenter();
        double radius1 = other.getRadius();
        double radiusBig;
        double radiusSmall;
        if(radius0 < radius1){
            radiusBig = radius1;
            radiusSmall = radius0;
        }
        else{
            radiusBig = radius0;
            radiusSmall = radius1;
        }
        double dist = 0;
        for (int i = 0; i < center0.length; i++) {
            double delta = center0[i] - center1[i];
            dist += delta * delta;
        }
        dist = Math.sqrt(dist);
        if(dist > radiusSmall + radiusBig)
            return 0;
        if(dist + radiusSmall <= radiusBig){
            //one lies within the other
            return 1;
        }
        else{
            return (radiusSmall+radiusBig-dist)/(2*radiusSmall);
        }
    }
boolean moa.cluster.SphereCluster.overlapSave (SphereCluster other)
When a clusters looses points the new minimal bounding sphere can be partly outside of the originating cluster.
If a another cluster is right next to the original cluster (without overlapping), the new cluster can be overlapping with this second cluster. OverlapSave will tell you if the current cluster can degenerate so much that it overlaps with cluster 'other'
Parameters:
other the potentially overlapping cluster
Returns:
true if cluster can potentially overlap
Definition at line 288 of file SphereCluster.java.
References moa.cluster.SphereCluster.getCenterDistance(), and moa.cluster.SphereCluster.getRadius().
{
        //use basic geometry to figure out the maximal degenerated cluster
        //comes down to Max(radius *(sin alpha + cos alpha)) which is
        double minDist = Math.sqrt(2)*(getRadius() + other.getRadius());
        double diff = getCenterDistance(other) - minDist;
        if(diff > 0)
            return true;
        else
            return false;
    }
Instance moa.cluster.SphereCluster.sample (Random random) [virtual]
Samples this cluster by returning a point from inside it.
Parameters:
random a random number source
Returns:
a point that lies inside this cluster
Implements moa.cluster.Cluster.
Definition at line 332 of file SphereCluster.java.
References moa.cluster.SphereCluster.center, moa.cluster.SphereCluster.getCenter(), and moa.cluster.SphereCluster.getRadius().
{
        // Create sample in hypersphere coordinates
        //get the center through getCenter so subclass have a chance
        double[] center = getCenter();
        final int dimensions = center.length;
        final double sin[] = new double[dimensions - 1];
        final double cos[] = new double[dimensions - 1];
        final double length = random.nextDouble() * getRadius();
        double lastValue = 1.0;
        for (int i = 0; i < dimensions-1; i++) {
            double angle = random.nextDouble() * 2 * Math.PI;
            sin[i] = lastValue * Math.sin( angle ); // Store cumulative values
            cos[i] = Math.cos( angle );
            lastValue = sin[i];
        }
        // Calculate cartesian coordinates
        double res[] = new double[dimensions];
        // First value uses only cosines
        res[0] = center[0] + length*cos[0];
        // Loop through 'middle' coordinates which use cosines and sines
        for (int i = 1; i < dimensions-1; i++) {
            res[i] = center[i] + length*sin[i-1]*cos[i];
        }
        // Last value uses only sines
        res[dimensions-1] = center[dimensions-1] + length*sin[dimensions-2];
        return new DenseInstance(1.0, res);
    }
void moa.cluster.SphereCluster.setCenter (double[] center)
Definition at line 216 of file SphereCluster.java.
Referenced by moa.cluster.SphereCluster.merge(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move().
{
        this.center = center;
    }
void moa.cluster.SphereCluster.setRadius (double radius)
Definition at line 224 of file SphereCluster.java.
Referenced by moa.cluster.SphereCluster.merge(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        this.radius = radius;
    }
void moa.cluster.SphereCluster.setWeight (double weight)
Definition at line 233 of file SphereCluster.java.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.clusterers.clustream.WithKmeans.calculateCenter(), moa.clusterers.clustream.Clustream.calculateCenter(), moa.cluster.Clustering.Clustering(), moa.clusterers.denstream.MicroCluster.copy(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.cluster.SphereCluster.merge(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        this.weight = weight;
    }
Member Data Documentation
double [] moa.cluster.SphereCluster.center [private]
Definition at line 39 of file SphereCluster.java.
Referenced by moa.clusterers.clustree.ClusKernel.calcNormalizedDistance(), moa.clusterers.clustream.ClustreamKernel.calcNormalizedDistance(), moa.cluster.SphereCluster.combine(), moa.cluster.SphereCluster.distance(), moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getCenterDistance(), moa.cluster.SphereCluster.sample(), and moa.cluster.SphereCluster.SphereCluster().
double moa.cluster.SphereCluster.radius [private]
Definition at line 40 of file SphereCluster.java.
Referenced by moa.cluster.SphereCluster.combine(), moa.cluster.SphereCluster.getRadius(), and moa.cluster.SphereCluster.SphereCluster().
final long moa.cluster.SphereCluster.serialVersionUID = 1L [static, private]
Reimplemented from moa.cluster.Cluster.
Reimplemented in moa.cluster.CFCluster, moa.clusterers.clustream.ClustreamKernel, and moa.clusterers.macro.NonConvexCluster.
Definition at line 37 of file SphereCluster.java.
double moa.cluster.SphereCluster.weight [private]
Definition at line 41 of file SphereCluster.java.
Referenced by moa.cluster.SphereCluster.combine(), moa.cluster.SphereCluster.getWeight(), and moa.cluster.SphereCluster.SphereCluster().
The documentation for this class was generated from the following file:
main/java/moa/cluster/SphereCluster.java