MOA: moa.options.ListOption Class Reference
moa.options.ListOption Class Reference
List option.
Public Member Functions
ListOption (String name, char cliChar, String purpose, Option expectedType, Option[] defaultList, char separatorChar)
void setList (Option[] optList)
Option[] getList ()
String getDefaultCLIString ()
Gets the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Static Public Member Functions
static Option[] cliStringToOptionArray (String s, char separator, Option expectedType)
static String optionArrayToCLIString (Option[] os, char separator)
Protected Attributes
Option[] currentList
Option expectedType
Option[] defaultList
char separatorChar
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
List option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 28 of file ListOption.java.
Constructor & Destructor Documentation
moa.options.ListOption.ListOption (String name, char cliChar, String purpose, Option expectedType, Option[] defaultList, char separatorChar)
Definition at line 40 of file ListOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        this.expectedType = expectedType;
        this.defaultList = defaultList.clone();
        this.separatorChar = separatorChar;
        resetToDefault();
    }
Member Function Documentation
static Option [] moa.options.ListOption.cliStringToOptionArray (String s, char separator, Option expectedType) [static]
Definition at line 78 of file ListOption.java.
References moa.options.Option.copy(), and moa.options.Option.setValueViaCLIString().
Referenced by moa.options.ListOption.setValueViaCLIString().
{
     if (s == null || s.length() < 1) {
             return new Option[0];
         }
        String[] subStrings = s.split(Character.toString(separator));
        Option[] options = new Option[subStrings.length];
        for (int i = 0; i < options.length; i++) {
            options[i] = expectedType.copy();
            options[i].setValueViaCLIString(subStrings[i]);
        }
        return options;
    }
String moa.options.ListOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 63 of file ListOption.java.
References moa.options.ListOption.defaultList, moa.options.ListOption.optionArrayToCLIString(), and moa.options.ListOption.separatorChar.
{
        return optionArrayToCLIString(this.defaultList, this.separatorChar);
    }
Option [] moa.options.ListOption.getList ()
Definition at line 58 of file ListOption.java.
References moa.options.ListOption.currentList.
Referenced by moa.tasks.Plot.createScript(), moa.tasks.Plot.doMainTask(), moa.streams.MultiFilteredStream.prepareForUseImpl(), moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl(), moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning(), and moa.streams.clustering.FileStream.restart().
{
        return this.currentList.clone();
    }
String moa.options.ListOption.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Definition at line 68 of file ListOption.java.
References moa.options.ListOption.currentList, moa.options.ListOption.optionArrayToCLIString(), and moa.options.ListOption.separatorChar.
Referenced by moa.options.ListOption.optionArrayToCLIString(), and moa.options.ListOption.setList().
{
        return optionArrayToCLIString(this.currentList, this.separatorChar);
    }
static String moa.options.ListOption.optionArrayToCLIString (Option[] os, char separator) [static]
Definition at line 92 of file ListOption.java.
References moa.options.ListOption.getValueAsCLIString().
Referenced by moa.options.ListOption.getDefaultCLIString(), and moa.options.ListOption.getValueAsCLIString().
{
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < os.length; i++) {
            if (i > 0) {
                sb.append(separator);
            }
            sb.append(os[i].getValueAsCLIString());
        }
        return sb.toString();
    }
void moa.options.ListOption.setList (Option[] optList)
Definition at line 49 of file ListOption.java.
References moa.options.Option.copy(), moa.options.ListOption.currentList, moa.options.ListOption.expectedType, moa.options.ListOption.getValueAsCLIString(), and moa.options.Option.setValueViaCLIString().
{
        Option[] newArray = new Option[optList.length];
        for (int i = 0; i < optList.length; i++) {
            newArray[i] = this.expectedType.copy();
            newArray[i].setValueViaCLIString(optList[i].getValueAsCLIString());
        }
        this.currentList = newArray;
    }
void moa.options.ListOption.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Definition at line 73 of file ListOption.java.
References moa.options.ListOption.cliStringToOptionArray(), moa.options.ListOption.currentList, moa.options.ListOption.expectedType, and moa.options.ListOption.separatorChar.
{
        this.currentList = cliStringToOptionArray(s, this.separatorChar,
                this.expectedType);
    }
Member Data Documentation
Option [] moa.options.ListOption.currentList [protected]
Definition at line 32 of file ListOption.java.
Referenced by moa.options.ListOption.getList(), moa.options.ListOption.getValueAsCLIString(), moa.options.ListOption.setList(), and moa.options.ListOption.setValueViaCLIString().
Option [] moa.options.ListOption.defaultList [protected]
Definition at line 36 of file ListOption.java.
Referenced by moa.options.ListOption.getDefaultCLIString().
Option moa.options.ListOption.expectedType [protected]
Definition at line 34 of file ListOption.java.
Referenced by moa.options.ListOption.setList(), and moa.options.ListOption.setValueViaCLIString().
char moa.options.ListOption.separatorChar [protected]
Definition at line 38 of file ListOption.java.
Referenced by moa.options.ListOption.getDefaultCLIString(), moa.options.ListOption.getValueAsCLIString(), and moa.options.ListOption.setValueViaCLIString().
final long moa.options.ListOption.serialVersionUID = 1L [static, private]
Definition at line 30 of file ListOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/ListOption.java