MOA: moa.evaluation.EWMAClassificationPerformanceEvaluator Class Reference
moa.evaluation.EWMAClassificationPerformanceEvaluator Class Reference
Classification evaluator that updates evaluation results using an Exponential Weighted Moving Average.
Classes
class Estimator
Public Member Functions
void reset ()
Resets this evaluator.
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getFractionCorrectlyClassified ()
double getFractionIncorrectlyClassified ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Public Attributes
FloatOption alphaOption
Protected Attributes
double TotalweightObserved
Estimator weightCorrect
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Classification evaluator that updates evaluation results using an Exponential Weighted Moving Average.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 37 of file EWMAClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.EWMAClassificationPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 80 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.add(), moa.evaluation.EWMAClassificationPerformanceEvaluator.TotalweightObserved, and moa.evaluation.EWMAClassificationPerformanceEvaluator.weightCorrect.
{
        double weight = inst.weight();
        int trueClass = (int) inst.classValue();
        if (weight > 0.0) {
            this.TotalweightObserved += weight;
            if (Utils.maxIndex(classVotes) == trueClass) {
                this.weightCorrect.add(1);
            } else {
                this.weightCorrect.add(0);
            }
        }
    }
void moa.evaluation.EWMAClassificationPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 125 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionCorrectlyClassified ()
Definition at line 116 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.estimation, and moa.evaluation.EWMAClassificationPerformanceEvaluator.weightCorrect.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionIncorrectlyClassified(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightCorrect.estimation();
    }
double moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionIncorrectlyClassified ()
Definition at line 120 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
{
        return 1.0 - getFractionCorrectlyClassified();
    }
Measurement [] moa.evaluation.EWMAClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 104 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.TotalweightObserved.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
                    new Measurement("classified instances",
                    this.TotalweightObserved),
                    new Measurement("classifications correct (percent)",
                    getFractionCorrectlyClassified() * 100.0)};
    }
double moa.evaluation.EWMAClassificationPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 112 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.TotalweightObserved.
{
        return this.TotalweightObserved;
    }
void moa.evaluation.EWMAClassificationPerformanceEvaluator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 131 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.reset().
{
        reset();
    }
void moa.evaluation.EWMAClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 75 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.alphaOption, moa.options.FloatOption.getValue(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.weightCorrect.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.prepareForUseImpl().
{
        weightCorrect = new Estimator(this.alphaOption.getValue());
    }
Member Data Documentation
FloatOption moa.evaluation.EWMAClassificationPerformanceEvaluator.alphaOption
Initial value:
 new FloatOption("alpha",
            'a', "Fading factor or exponential smoothing factor", .01)
Definition at line 44 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.reset().
final long moa.evaluation.EWMAClassificationPerformanceEvaluator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 40 of file EWMAClassificationPerformanceEvaluator.java.
double moa.evaluation.EWMAClassificationPerformanceEvaluator.TotalweightObserved [protected]
Definition at line 42 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.addResult(), moa.evaluation.EWMAClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.getTotalWeightObserved().
Estimator moa.evaluation.EWMAClassificationPerformanceEvaluator.weightCorrect [protected]
Definition at line 47 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.addResult(), moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/EWMAClassificationPerformanceEvaluator.java