MOA: moa.classifiers.rules.AMRulesRegressorTest Class Reference
moa.classifiers.rules.AMRulesRegressorTest Class Reference
Tests the AMRulesRegressor classifier.
Public Member Functions
AMRulesRegressorTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the AMRulesRegressor classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 34 of file AMRulesRegressorTest.java.
Constructor & Destructor Documentation
moa.classifiers.rules.AMRulesRegressorTest.AMRulesRegressorTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 42 of file AMRulesRegressorTest.java.
References moa.classifiers.AbstractMultipleRegressorTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.rules.AMRulesRegressorTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleRegressorTestCase.
Definition at line 53 of file AMRulesRegressorTest.java.
{
    return new Classifier[]{
    new AMRulesRegressor(),
    };
  }
static void moa.classifiers.rules.AMRulesRegressorTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 73 of file AMRulesRegressorTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.rules.AMRulesRegressorTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.rules.AMRulesRegressorTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 64 of file AMRulesRegressorTest.java.
Referenced by moa.classifiers.rules.AMRulesRegressorTest.main().
{
    return new TestSuite(AMRulesRegressorTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/rules/AMRulesRegressorTest.java