MOA: moa.streams.generators.STAGGERGenerator Class Reference
moa.streams.generators.STAGGERGenerator Class Reference
Stream generator for STAGGER Concept functions.
Classes
interface ClassFunction
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption instanceRandomSeedOption
IntOption functionOption
FlagOption balanceClassesOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
InstancesHeader streamHeader
Random instanceRandom
boolean nextClassShouldBeZero
Static Protected Attributes
static ClassFunction[] classificationFunctions
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for STAGGER Concept functions.
Generator described in the paper:
Jeffrey C. Schlimmer and Richard H. Granger Jr. "Incremental Learning from Noisy Data", Machine Learning 1: 317-354 1986.
Notes:
The built in functions are based on the paper (page 341).
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 52 of file STAGGERGenerator.java.
Member Function Documentation
long moa.streams.generators.STAGGERGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 146 of file STAGGERGenerator.java.
{
        return -1;
    }
void moa.streams.generators.STAGGERGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 208 of file STAGGERGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.STAGGERGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 151 of file STAGGERGenerator.java.
References moa.streams.generators.STAGGERGenerator.streamHeader.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.STAGGERGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 56 of file STAGGERGenerator.java.
{
        return "Generates STAGGER Concept functions.";
    }
boolean moa.streams.generators.STAGGERGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 156 of file STAGGERGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.STAGGERGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 161 of file STAGGERGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.STAGGERGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 166 of file STAGGERGenerator.java.
References moa.streams.generators.STAGGERGenerator.balanceClassesOption, moa.streams.generators.STAGGERGenerator.classificationFunctions, moa.streams.generators.STAGGERGenerator.ClassFunction.determineClass(), moa.streams.generators.STAGGERGenerator.functionOption, moa.streams.generators.STAGGERGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.STAGGERGenerator.instanceRandom, moa.options.FlagOption.isSet, and moa.streams.generators.STAGGERGenerator.nextClassShouldBeZero.
{
        int size = 0, color = 0, shape = 0, group = 0;
        boolean desiredClassFound = false;
        while (!desiredClassFound) {
            // generate attributes
            size = this.instanceRandom.nextInt(3);
            color = this.instanceRandom.nextInt(3);
            shape = this.instanceRandom.nextInt(3);
            // determine class
            group = classificationFunctions[this.functionOption.getValue() - 1].determineClass(size, color, shape);
            if (!this.balanceClassesOption.isSet()) {
                desiredClassFound = true;
            } else {
                // balance the classes
                if ((this.nextClassShouldBeZero && (group == 0))
                        || (!this.nextClassShouldBeZero && (group == 1))) {
                    desiredClassFound = true;
                    this.nextClassShouldBeZero = !this.nextClassShouldBeZero;
                } // else keep searching
            }
        }
        // construct instance
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        inst.setValue(0, size);
        inst.setValue(1, color);
        inst.setValue(2, shape);
        inst.setDataset(header);
        inst.setClassValue(group);
        return inst;
    }
void moa.streams.generators.STAGGERGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 112 of file STAGGERGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.streams.generators.STAGGERGenerator.restart(), and moa.streams.generators.STAGGERGenerator.streamHeader.
{
        // generate header
        FastVector attributes = new FastVector();
        FastVector sizeLabels = new FastVector();
        sizeLabels.addElement("small");
        sizeLabels.addElement("medium");
        sizeLabels.addElement("large");
        attributes.addElement(new Attribute("size", sizeLabels));
        FastVector colorLabels = new FastVector();
        colorLabels.addElement("red");
        colorLabels.addElement("blue");
        colorLabels.addElement("green");
        attributes.addElement(new Attribute("color", colorLabels));
        FastVector shapeLabels = new FastVector();
        shapeLabels.addElement("circle");
        shapeLabels.addElement("square");
        shapeLabels.addElement("triangle");
        attributes.addElement(new Attribute("shape", shapeLabels));
        FastVector classLabels = new FastVector();
        classLabels.addElement("false");
        classLabels.addElement("true");
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
        restart();
    }
void moa.streams.generators.STAGGERGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 202 of file STAGGERGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.STAGGERGenerator.instanceRandom, moa.streams.generators.STAGGERGenerator.instanceRandomSeedOption, and moa.streams.generators.STAGGERGenerator.nextClassShouldBeZero.
Referenced by moa.streams.generators.STAGGERGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
        this.nextClassShouldBeZero = false;
    }
Member Data Documentation
FlagOption moa.streams.generators.STAGGERGenerator.balanceClassesOption
Initial value:
 new FlagOption("balanceClasses",
            'b', "Balance the number of instances of each class.")
Definition at line 70 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance().
ClassFunction [] moa.streams.generators.STAGGERGenerator.classificationFunctions [static, protected]
Initial value:
 {
        new ClassFunction() {
    @Override
    public int determineClass(int size, int color, int shape) {
        return (size == 0 && color == 0) ? 1 : 0;
    }
},
        new ClassFunction() {
    @Override
    public int determineClass(int size, int color, int shape) {
        return (color == 2 || shape == 0) ? 1 : 0;
    }
},
        new ClassFunction() {
    @Override
    public int determineClass(int size, int color, int shape) {
        return (size == 1 || size == 2) ? 1 : 0;
    }
}
    }
Definition at line 78 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance().
IntOption moa.streams.generators.STAGGERGenerator.functionOption
Initial value:
 new IntOption("function", 'f',
            "Classification function used, as defined in the original paper.",
            1, 1, 3)
Definition at line 66 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance().
Random moa.streams.generators.STAGGERGenerator.instanceRandom [protected]
Definition at line 107 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance(), and moa.streams.generators.STAGGERGenerator.restart().
IntOption moa.streams.generators.STAGGERGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 62 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.restart().
boolean moa.streams.generators.STAGGERGenerator.nextClassShouldBeZero [protected]
Definition at line 109 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.nextInstance(), and moa.streams.generators.STAGGERGenerator.restart().
final long moa.streams.generators.STAGGERGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 60 of file STAGGERGenerator.java.
InstancesHeader moa.streams.generators.STAGGERGenerator.streamHeader [protected]
Definition at line 105 of file STAGGERGenerator.java.
Referenced by moa.streams.generators.STAGGERGenerator.getHeader(), and moa.streams.generators.STAGGERGenerator.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/STAGGERGenerator.java