MOA: moa.test.Utils Class Reference
moa.test.Utils Class Reference
Class with useful methods.
Static Public Member Functions
static Class getArrayClass (Class c)
Returns the basic class of an array class (handles multi-dimensional arrays).
static int getArrayDimensions (Class array)
Returns the dimensions of the given array.
static int getArrayDimensions (Object array)
Returns the dimensions of the given array.
static String arrayToString (Object array, boolean outputClass)
Returns the given Array in a string representation.
static String arrayToString (Object array)
Returns the given Array in a string representation.
Detailed Description
Class with useful methods.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 30 of file Utils.java.
Member Function Documentation
static String moa.test.Utils.arrayToString (Object array) [static]
Returns the given Array in a string representation.
Even though the parameter is of type "Object" one can hand over primitve arrays, e.g. int[3] or double[2][4].
Parameters:
array the array to return in a string representation
Returns:
the array as string
Definition at line 134 of file Utils.java.
References moa.test.Utils.arrayToString().
{
    return arrayToString(array, false);
  }
static String moa.test.Utils.arrayToString (Object array, boolean outputClass) [static]
Returns the given Array in a string representation.
Even though the parameter is of type "Object" one can hand over primitve arrays, e.g. int[3] or double[2][4].
Parameters:
array the array to return in a string representation
outputClass whether to output the class name instead of calling the object's "toString()" method
Returns:
the array as string
Definition at line 82 of file Utils.java.
References moa.test.Utils.getArrayDimensions().
Referenced by moa.test.Utils.arrayToString().
{
    StringBuilder   result;
    int         dimensions;
    int         i;
    Object      obj;
    result     = new StringBuilder();
    dimensions = getArrayDimensions(array);
    if (dimensions == 0) {
      result.append("null");
    }
    else if (dimensions == 1) {
      for (i = 0; i < Array.getLength(array); i++) {
    if (i > 0)
      result.append(",");
    if (Array.get(array, i) == null) {
      result.append("null");
    }
    else {
      obj = Array.get(array, i);
      if (outputClass) {
        if (obj instanceof Class)
          result.append(((Class) obj).getName());
        else
          result.append(obj.getClass().getName());
      }
      else {
        result.append(obj.toString());
      }
    }
      }
    }
    else {
      for (i = 0; i < Array.getLength(array); i++) {
    if (i > 0)
      result.append(",");
    result.append("[" + arrayToString(Array.get(array, i)) + "]");
      }
    }
    return result.toString();
  }
static Class moa.test.Utils.getArrayClass (Class c) [static]
Returns the basic class of an array class (handles multi-dimensional arrays).
Parameters:
c the array to inspect
Returns:
the class of the innermost elements
Definition at line 38 of file Utils.java.
{
    if (c.getComponentType().isArray())
      return getArrayClass(c.getComponentType());
    else
      return c.getComponentType();
  }
static int moa.test.Utils.getArrayDimensions (Object array) [static]
Returns the dimensions of the given array.
Even though the parameter is of type "Object" one can hand over primitve arrays, e.g. int[3] or double[2][4].
Parameters:
array the array to determine the dimensions for
Returns:
the dimensions of the array
Definition at line 68 of file Utils.java.
References moa.test.Utils.getArrayDimensions().
{
    return getArrayDimensions(array.getClass());
  }
static int moa.test.Utils.getArrayDimensions (Class array) [static]
Returns the dimensions of the given array.
Even though the parameter is of type "Object" one can hand over primitve arrays, e.g. int[3] or double[2][4].
Parameters:
array the array to determine the dimensions for
Returns:
the dimensions of the array
Definition at line 53 of file Utils.java.
Referenced by moa.test.Utils.arrayToString(), and moa.test.Utils.getArrayDimensions().
{
    if (array.getComponentType().isArray())
      return 1 + getArrayDimensions(array.getComponentType());
    else
      return 1;
  }
The documentation for this class was generated from the following file:
test/java/moa/test/Utils.java