MOA: moa.tasks.ConceptDriftMainTask Class Reference
moa.tasks.ConceptDriftMainTask Class Reference
Public Member Functions
ArrayList< ClusterEvent > getEventsList ()
Protected Member Functions
void setEventsList (ArrayList< ClusterEvent > events)
Protected Attributes
ArrayList< ClusterEvent > events
Detailed Description
Author:
albert
Definition at line 15 of file ConceptDriftMainTask.java.
Member Function Documentation
ArrayList<ClusterEvent> moa.tasks.ConceptDriftMainTask.getEventsList ()
Definition at line 23 of file ConceptDriftMainTask.java.
References moa.tasks.ConceptDriftMainTask.events.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask(), and moa.gui.TaskTextViewerPanel.setGraph().
{
        return this.events;
    }
void moa.tasks.ConceptDriftMainTask.setEventsList (ArrayList< ClusterEvent > events) [protected]
Definition at line 19 of file ConceptDriftMainTask.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
{
        this.events = events;
    }
Member Data Documentation
ArrayList<ClusterEvent> moa.tasks.ConceptDriftMainTask.events [protected]
Definition at line 17 of file ConceptDriftMainTask.java.
Referenced by moa.tasks.ConceptDriftMainTask.getEventsList().
The documentation for this class was generated from the following file:
main/java/moa/tasks/ConceptDriftMainTask.java