MOA: moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods Class Reference
moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods Class Reference
Ensemble Drift detection method.
Public Member Functions
EnsembleDriftDetectionMethods ()
void resetLearning ()
Resets this change detector.
void input (double prediction)
Adding a numeric value to the change detector<br>
.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
Public Attributes
IntOption minNumInstancesOption
ListOption changeDetectorsOption
MultiChoiceOption predictionOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
ChangeDetector[] cds
Boolean[] preds
Static Private Attributes
static final long serialVersionUID = -3518369648142099719L
Detailed Description
Ensemble Drift detection method.
Author:
Manuel Baena (mbaena@lcc.uma.es)
Version:
Revision
7
Definition at line 34 of file EnsembleDriftDetectionMethods.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.EnsembleDriftDetectionMethods ()
Definition at line 57 of file EnsembleDriftDetectionMethods.java.
References moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning().
{
        resetLearning();
    }
Member Function Documentation
void moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.getDescription (StringBuilder sb, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 111 of file EnsembleDriftDetectionMethods.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input (double inputValue) [virtual]
Adding a numeric value to the change detector<br>
.
The output of the change detector is modified after the insertion of a new item inside.
Parameters:
inputValue the number to insert into the change detector
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 76 of file EnsembleDriftDetectionMethods.java.
References moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.cds, moa.classifiers.core.driftdetection.AbstractChangeDetector.getChange(), moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.core.driftdetection.ChangeDetector.input(), moa.classifiers.core.driftdetection.AbstractChangeDetector.isChangeDetected, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.predictionOption, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.preds, and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning().
{
        for (int i = 0; i < cds.length; i++) {
            cds[i].input(prediction);
            if (cds[i].getChange()) {
                preds[i] = true;
            }
        }
        int typePrediction = this.predictionOption.getChosenIndex();
                   int numberDetections = 0;
            for (int i = 0; i < cds.length; i++) {
                if (preds[i] == true) {
                    numberDetections++;
                }
            }
        if (typePrediction == 0) {
            //Choose Max
            this.isChangeDetected = (numberDetections == cds.length);
        } else if (typePrediction == 1) {
            //Choose Min
             this.isChangeDetected = (numberDetections > 0);
        } else if (typePrediction == 2) {
            //Choose Avg
            this.isChangeDetected = (numberDetections > cds.length/2) ;
        }
        if (this.isChangeDetected == true) {
            this.resetLearning();
        }
    }
void moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 116 of file EnsembleDriftDetectionMethods.java.
References moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.cds, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.changeDetectorsOption, moa.classifiers.core.driftdetection.AbstractChangeDetector.copy(), moa.options.ListOption.getList(), moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.preds, moa.tasks.TaskMonitor.setCurrentActivity(), and moa.tasks.TaskMonitor.taskShouldAbort().
{
        // TODO Auto-generated method stub
        Option[] changeDetectorOptions = this.changeDetectorsOption.getList();
        cds = new ChangeDetector[changeDetectorOptions.length];
        preds = new Boolean[changeDetectorOptions.length];
        for (int i = 0; i < cds.length; i++) {
            //monitor.setCurrentActivity("Materializing change detector " + (i + 1)
            //        + "...", -1.0);
            cds[i] = ((ChangeDetector) ((ClassOption) changeDetectorOptions[i]).materializeObject(monitor, repository)).copy();
            if (monitor.taskShouldAbort()) {
                return;
            }
            if (cds[i] instanceof OptionHandler) {
                monitor.setCurrentActivity("Preparing change detector " + (i + 1)
                        + "...", -1.0);
                ((OptionHandler) cds[i]).prepareForUse(monitor, repository);
                if (monitor.taskShouldAbort()) {
                    return;
                }
            }
            preds[i] = false;
        }
    }
void moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning ()
Resets this change detector.
It must be similar to starting a new change detector from scratch.
Reimplemented from moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 62 of file EnsembleDriftDetectionMethods.java.
References moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.changeDetectorsOption, moa.options.ListOption.getList(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.preds.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.EnsembleDriftDetectionMethods(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input().
{
        //if (preds == null) {
             preds = new Boolean[this.changeDetectorsOption.getList().length];
        //}
        for (int i = 0; i < preds.length; i++) {
            preds[i] = false;
        }
    }
Member Data Documentation
ChangeDetector [] moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.cds [protected]
Definition at line 71 of file EnsembleDriftDetectionMethods.java.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl().
ListOption moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.changeDetectorsOption
Initial value:
 new ListOption("changeDetectors", 'c',
            "Change Detectors to use.", new ClassOption("driftDetectionMethod", 'd',
            "Drift detection method to use.", ChangeDetector.class, "DDM"),
            new Option[0], ',')
Definition at line 45 of file EnsembleDriftDetectionMethods.java.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning().
IntOption moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.minNumInstancesOption
Initial value:
 new IntOption(
            "minNumInstances",
            'n',
            "The minimum number of instances before permitting detecting change.",
            30, 0, Integer.MAX_VALUE)
Definition at line 39 of file EnsembleDriftDetectionMethods.java.
MultiChoiceOption moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.predictionOption
Initial value:
 new MultiChoiceOption(
            "prediction", 'l', "Prediction to use.", new String[]{
                "max", "min", "majority"}, new String[]{
                "Maximum",
                "Minimum",
                "Majority"}, 0)
Definition at line 50 of file EnsembleDriftDetectionMethods.java.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input().
Boolean [] moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.preds [protected]
Definition at line 73 of file EnsembleDriftDetectionMethods.java.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input(), moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.resetLearning().
final long moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.serialVersionUID = -3518369648142099719L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 36 of file EnsembleDriftDetectionMethods.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/EnsembleDriftDetectionMethods.java