MOA: moa.classifiers.trees.ORTO.SplitNode Class Reference
moa.classifiers.trees.ORTO.SplitNode Class Reference
Public Member Functions
void setChild (int index, Node child)
SplitNode (InstanceConditionalTest splitTest, int id)
int instanceChildIndex (Instance inst)
boolean isLeaf ()
int getNumSubtrees ()
double[] processInstance (Instance inst, ORTO tree)
double[] getPrediction (Instance inst, ORTO tree)
Protected Attributes
InstanceConditionalTest splitTest
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 413 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.SplitNode.SplitNode (InstanceConditionalTest splitTest, int id)
Definition at line 426 of file ORTO.java.
{
            super(id);
            this.splitTest = splitTest;
        }
Member Function Documentation
int moa.classifiers.trees.ORTO.SplitNode.getNumSubtrees ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 440 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.SplitNode.processInstance().
{
            int num = 1;
            for (Node child : children) {
                num += child.getNumSubtrees();
            }
            num -= children.size();
            return num;
        }
double [] moa.classifiers.trees.ORTO.SplitNode.getPrediction (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 538 of file ORTO.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.Node.getPrediction(), moa.classifiers.trees.ORTO.maxID, moa.classifiers.trees.ORTO.SplitNode.setChild(), moa.classifiers.trees.ORTO.Node.setParent(), and moa.classifiers.trees.ORTO.SplitNode.splitTest.
{
            int branch = splitTest.branchForInstance(inst);
            Node child = children.get(branch);
            if (child == null) {
                tree.maxID++;
                child = new ActiveLearningNode(tree.maxID);
                this.setChild(branch, child);
                child.setParent(this);
            }
            return child.getPrediction(inst, tree);
        }
int moa.classifiers.trees.ORTO.SplitNode.instanceChildIndex (Instance inst)
Definition at line 431 of file ORTO.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), and moa.classifiers.trees.ORTO.SplitNode.splitTest.
{
            return this.splitTest.branchForInstance(inst);
        }
boolean moa.classifiers.trees.ORTO.SplitNode.isLeaf ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 436 of file ORTO.java.
{
            return false;
        }
double [] moa.classifiers.trees.ORTO.SplitNode.processInstance (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 449 of file ORTO.java.
References moa.classifiers.trees.ORTO.Node.Adaptable, moa.core.DoubleVector.addToValue(), moa.classifiers.trees.ORTO.Node.Alternate, moa.classifiers.trees.ORTO.Node.alternateTree, moa.classifiers.trees.ORTO.AlternateTreeTimeOption, moa.classifiers.trees.ORTO.AlternateTreeTMinOption, moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.InnerNode.getChildIndex(), moa.classifiers.trees.ORTO.Node.getNumSubtrees(), moa.classifiers.trees.ORTO.SplitNode.getNumSubtrees(), moa.core.DoubleVector.getValue(), moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.classifiers.trees.ORTO.InnerNode.lossStatistics, moa.classifiers.trees.ORTO.maxID, moa.classifiers.trees.ORTO.nodesToAdapt, moa.classifiers.trees.ORTO.numTrees, moa.classifiers.trees.ORTO.PageHinckleyAlphaOption, moa.classifiers.trees.ORTO.InnerNode.PageHinckleyTest(), moa.classifiers.trees.ORTO.PageHinckleyThresholdOption, moa.classifiers.trees.ORTO.Node.parent, moa.classifiers.trees.ORTO.InnerNode.previousWeight, moa.classifiers.trees.ORTO.Node.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), moa.classifiers.trees.ORTO.InnerNode.setAdaptable(), moa.classifiers.trees.ORTO.Node.setAdaptable(), moa.classifiers.trees.ORTO.InnerNode.setChild(), moa.classifiers.trees.ORTO.SplitNode.setChild(), moa.classifiers.trees.ORTO.Node.setParent(), moa.core.DoubleVector.setValue(), moa.classifiers.trees.ORTO.SplitNode.splitTest, moa.classifiers.trees.ORTO.treeRoot, and moa.classifiers.trees.ORTO.InnerNode.weightSeen.
{
            int branch = splitTest.branchForInstance(inst);
            Node child = children.get(branch);
            if (child == null) {
                tree.maxID++;
                child = new ActiveLearningNode(tree.maxID);
                this.setChild(branch, child);
                child.setParent(this);
            }
            double[] processed = child.processInstance(inst, tree);
            weightSeen++;
            // Convert any nominal attributes to numeric ones???
            // If no model exists yet, begin with an empty leaf node (the root)
            // Take the current example and traverse it through the tree to a leaf
            if (Adaptable) {
                if (this.alternateTree == null) {
                    // Retrieve the error for the found leaf node
                    // currentNode.learnFromInstance(inst, this);
                    double PHerror = processed[3] - tree.PageHinckleyAlphaOption.getValue();
                    // Back-propagate the error through all the parent nodes
                    if(PageHinckleyTest(PHerror, tree.PageHinckleyThresholdOption.getValue())) {
                        if (tree.nodesToAdapt.contains(child)) {
                            tree.nodesToAdapt.remove(child);
                        }
                        tree.nodesToAdapt.add(this);
                    }
                } else if (this.alternateTree != null) {
                    // If an alternate tree already exists, check if the current tree should be replaced with it,
                    // or if the alternate tree should be discarded.
                    // this.alternateTree.checkRoot();
                    double[] processedAlt = this.alternateTree.processInstance(inst, tree);
                    // Update the loss statistics for the alternate tree
                    double qAlt = processedAlt[1];
                    double qOrg = processed[1];
                    // Compute the Qi statistics
                    double Qi = Math.log(qOrg / qAlt);
                    lossStatistics.addToValue(0,1);
                    lossStatistics.addToValue(1,Qi);
                    double QiAverage = lossStatistics.getValue(1) / lossStatistics.getValue(0);
                    if(weightSeen - previousWeight >= tree.AlternateTreeTMinOption.getValue()) {
                        // Update the weight at which a decision was tested for
                        previousWeight = weightSeen;
                        // If appropriate, replace the current tree with the alternate tree
                        if(Qi > 0) {
                            // Replace the main FIMT-DD tree at a subtree
                            alternateTree.setAdaptable(true);
                            alternateTree.Alternate = false;
                            if(parent != null) {
                                parent.setChild(parent.getChildIndex(this), alternateTree);
                                alternateTree.setParent(parent);
                                tree.numTrees = tree.numTrees - this.getNumSubtrees() + alternateTree.getNumSubtrees();
                                alternateTree.alternateTree = null;
                            } else { // Or occasionally at the root of the tree
                                tree.numTrees = tree.numTrees - this.getNumSubtrees() + alternateTree.getNumSubtrees();
                                tree.treeRoot = alternateTree;
                                alternateTree.alternateTree = null;
                            }
                            tree.removeExcessTrees();
                        }
                        // Otherwise, check if the alternate tree should be discarded
                        else if (QiAverage < lossStatistics.getValue(2) && lossStatistics.getValue(0) >= (10 * tree.AlternateTreeTMinOption.getValue()) || weightSeen >= tree.AlternateTreeTimeOption.getValue()) {
                            // tree.nodesToAdapt.remove(tree.nodesToAdapt.indexOf(this));
                            this.alternateTree = null;
                            setAdaptable(true);
                        }
                        lossStatistics.setValue(2, QiAverage);
                    }
                }
            }
            return processed;
        }
void moa.classifiers.trees.ORTO.SplitNode.setChild (int index, Node child)
Reimplemented from moa.classifiers.trees.ORTO.InnerNode.
Definition at line 419 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.core.conditionaltests.InstanceConditionalTest.maxBranches(), and moa.classifiers.trees.ORTO.SplitNode.splitTest.
Referenced by moa.classifiers.trees.ORTO.SplitNode.getPrediction(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.processInstance().
{
            if ((this.splitTest.maxBranches() >= 0) && (index >= this.splitTest.maxBranches())) {
                throw new IndexOutOfBoundsException();
            }
            this.children.set(index, child);
        }
Member Data Documentation
final long moa.classifiers.trees.ORTO.SplitNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.ORTO.InnerNode.
Definition at line 415 of file ORTO.java.
InstanceConditionalTest moa.classifiers.trees.ORTO.SplitNode.splitTest [protected]
Definition at line 417 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.SplitNode.getPrediction(), moa.classifiers.trees.ORTO.SplitNode.instanceChildIndex(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.trees.ORTO.SplitNode.setChild().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java