MOA: moa.options.ClassOption Class Reference
moa.options.ClassOption Class Reference
Class option.
Public Member Functions
ClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
ClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static String objectToCLIString (Object obj, Class<?> requiredType)
static Object cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 35 of file ClassOption.java.
Constructor & Destructor Documentation
moa.options.ClassOption.ClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
Definition at line 39 of file ClassOption.java.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString);
    }
moa.options.ClassOption.ClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
Definition at line 44 of file ClassOption.java.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString, nullString);
    }
Member Function Documentation
static Object moa.options.ClassOption.cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception [static]
Definition at line 94 of file ClassOption.java.
References moa.options.Options.addOption(), moa.options.AbstractClassOption.FILE_PREFIX_STRING, moa.options.AbstractClassOption.INMEM_PREFIX_STRING, moa.options.Options.removeAllOptions(), moa.options.AbstractClassOption.requiredType, and moa.options.Options.setViaCLIString().
Referenced by moa.options.ClassOption.setValueViaCLIString().
{
        if (cliString.startsWith(FILE_PREFIX_STRING)) {
            return new File(cliString.substring(FILE_PREFIX_STRING.length()));
        }
        if (cliString.startsWith(INMEM_PREFIX_STRING)) {
            return cliString.substring(INMEM_PREFIX_STRING.length());
        }
        cliString = cliString.trim();
        int firstSpaceIndex = cliString.indexOf(' ', 0);
        String className;
        String classOptions;
        if (firstSpaceIndex > 0) {
            className = cliString.substring(0, firstSpaceIndex);
            classOptions = cliString.substring(firstSpaceIndex + 1, cliString.length());
            classOptions = classOptions.trim();
        } else {
            className = cliString;
            classOptions = "";
        }
        Class<?> classObject;
        try {
            classObject = Class.forName(className);
        } catch (Throwable t1) {
            try {
                // try prepending default package
                classObject = Class.forName(requiredType.getPackage().getName()
                        + "." + className);
            } catch (Throwable t2) {
                try {
                    // try prepending task package
                    classObject = Class.forName(Task.class.getPackage().getName()
                            + "." + className);
                } catch (Throwable t3) {
                    throw new Exception("Class not found: " + className);
                }
            }
        }
        Object classInstance;
        try {
            classInstance = classObject.newInstance();
        } catch (Exception ex) {
            throw new Exception("Problem creating instance of class: "
                    + className, ex);
        }
        if (requiredType.isInstance(classInstance)
                || ((classInstance instanceof Task) && requiredType.isAssignableFrom(((Task) classInstance).getTaskResultType()))) {
            Options options = new Options();
            if (externalOptions != null) {
                for (Option option : externalOptions) {
                    options.addOption(option);
                }
            }
            if (classInstance instanceof OptionHandler) {
                Option[] objectOptions = ((OptionHandler) classInstance).getOptions().getOptionArray();
                for (Option option : objectOptions) {
                    options.addOption(option);
                }
            }
            try {
                options.setViaCLIString(classOptions);
            } catch (Exception ex) {
                throw new Exception("Problem with options to '"
                        + className
                        + "'."
                        + "\n\nValid options for "
                        + className
                        + ":\n"
                        + ((OptionHandler) classInstance).getOptions().getHelpString(), ex);
            } finally {
                options.removeAllOptions(); // clean up listener refs
            }
        } else {
            throw new Exception("Class named '" + className
                    + "' is not an instance of " + requiredType.getName() + ".");
        }
        return classInstance;
    }
JComponent moa.options.ClassOption.getEditComponent () [virtual]
Gets the GUI component to edit.
Returns:
the component to edit
Implements moa.options.AbstractClassOption.
Definition at line 174 of file ClassOption.java.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.renderAlgoPanel(), and moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel().
{
        return new ClassOptionEditComponent(this);
    }
String moa.options.ClassOption.getValueAsCLIString () [virtual]
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 50 of file ClassOption.java.
References moa.options.AbstractClassOption.currentValue, moa.options.AbstractClassOption.nullString, moa.options.ClassOption.objectToCLIString(), and moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.ClassOptionEditComponent.ClassOptionEditComponent(), moa.tasks.RunTasks.doMainTask(), moa.tasks.RunStreamTasks.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), weka.core.MOAUtils.fromOption(), moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer0(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer0(), moa.gui.outliertab.OutlierAlgoPanel.getClusterer1(), moa.gui.clustertab.ClusteringAlgoPanel.getClusterer1(), moa.gui.outliertab.OutlierAlgoPanel.getStream(), moa.gui.clustertab.ClusteringAlgoPanel.getStream(), moa.gui.outliertab.OutlierAlgoPanel.getStreamValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getStreamValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString().
{
        if ((this.currentValue == null) && (this.nullString != null)) {
            return this.nullString;
        } else if (this.currentValue == null) {
            return "None";
        }
        return objectToCLIString(this.currentValue, this.requiredType);
    }
static String moa.options.ClassOption.objectToCLIString (Object obj, Class<?> requiredType) [static]
Definition at line 74 of file ClassOption.java.
References moa.options.AbstractClassOption.classToCLIString(), moa.options.AbstractClassOption.FILE_PREFIX_STRING, and moa.options.AbstractClassOption.INMEM_PREFIX_STRING.
Referenced by moa.options.ClassOption.getValueAsCLIString().
{
        if (obj == null) {
            return "";
        }
        if (obj instanceof File) {
            return (FILE_PREFIX_STRING + ((File) obj).getPath());
        }
        if (obj instanceof String) {
            return (INMEM_PREFIX_STRING + obj);
        }
        String className = classToCLIString(obj.getClass(), requiredType);
        if (obj instanceof OptionHandler) {
            String subOptions = ((OptionHandler) obj).getOptions().getAsCLIString();
            if (subOptions.length() > 0) {
                return (className + " " + subOptions);
            }
        }
        return className;
    }
void moa.options.ClassOption.setValueViaCLIString (String s) [virtual]
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 60 of file ClassOption.java.
References moa.options.ClassOption.cliStringToObject(), moa.options.AbstractClassOption.currentValue, moa.options.AbstractOption.getName(), moa.options.AbstractClassOption.nullString, and moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.outliertab.OutlierAlgoPanel.actionPerformed(), moa.gui.clustertab.ClusteringAlgoPanel.actionPerformed(), moa.gui.ClassOptionEditComponent.applyState(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.classifiers.meta.OzaBagASHTTest.getRegressionClassifierSetups(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString(), moa.gui.outliertab.OutlierAlgoPanel.setStreamValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString().
{
        if ((this.nullString != null) && ((s == null) || (s.length() == 0) || s.equals(this.nullString))) {
            this.currentValue = null;
        } else if ((s != null) && (s.equalsIgnoreCase("None"))) {
            this.currentValue = null;
        } else {
            try {
                this.currentValue = cliStringToObject(s, this.requiredType, null);
            } catch (Exception e) {
                throw new IllegalArgumentException("Problems with option: " + getName(), e);
            }
        }
    }
Member Data Documentation
final long moa.options.ClassOption.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractClassOption.
Definition at line 37 of file ClassOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/ClassOption.java