MOA: moa.tasks.EvaluateOnlineRecommender Class Reference
moa.tasks.EvaluateOnlineRecommender Class Reference
Test for evaluating a recommender by training and periodically testing on samples from a rating dataset.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
EvaluateOnlineRecommender ()
Class<?> getTaskResultType ()
Gets the result type of this task.
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Public Attributes
ClassOption datasetOption
ClassOption ratingPredictorOption
IntOption sampleFrequencyOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Test for evaluating a recommender by training and periodically testing on samples from a rating dataset.
When finished, it will show the learning curve of the recommender rating predictor.
Parameters:
d: dataset - the dataset to be used to train/test the rating predictor.
f: sample frequency - the frequency in which a rating from the dataset will be used to test the model
Author:
Alex Catarineu (a.catarineu@gmail.com)
Version:
Revision
7
Definition at line 46 of file EvaluateOnlineRecommender.java.
Constructor & Destructor Documentation
moa.tasks.EvaluateOnlineRecommender.EvaluateOnlineRecommender ()
Definition at line 67 of file EvaluateOnlineRecommender.java.
{
    }
Member Function Documentation
Object moa.tasks.EvaluateOnlineRecommender.doMainTask (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 76 of file EvaluateOnlineRecommender.java.
References moa.recommender.rc.data.RecommenderData.clear(), moa.recommender.dataset.Dataset.curItemID(), moa.recommender.dataset.Dataset.curRating(), moa.recommender.dataset.Dataset.curUserID(), moa.tasks.EvaluateOnlineRecommender.datasetOption, moa.recommender.rc.data.RecommenderData.disableUpdates(), moa.evaluation.LearningCurve.entryToString(), moa.recommender.predictor.RatingPredictor.getData(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.recommender.dataset.Dataset.next(), moa.evaluation.LearningCurve.numEntries(), moa.recommender.predictor.RatingPredictor.predictRating(), moa.tasks.EvaluateOnlineRecommender.ratingPredictorOption, moa.recommender.dataset.Dataset.reset(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluateOnlineRecommender.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.recommender.rc.data.RecommenderData.setRating(), and moa.tasks.TaskMonitor.taskShouldAbort().
{
        Dataset d = (Dataset) getPreparedClassOption(this.datasetOption);
        RatingPredictor rp = (RatingPredictor)getPreparedClassOption(this.ratingPredictorOption);
        LearningCurve learningCurve = new LearningCurve("n");
        RecommenderData data = rp.getData();
        data.clear();
        data.disableUpdates(false);
        long start = System.currentTimeMillis();
        long evalTime = 0;
        double sum = 0;
        int n = 0;
        //ArrayList<TestMetric> metrics = new ArrayList<TestMetric>();
        int sampleFrequency = this.sampleFrequencyOption.getValue();
        int count = 0;
        while (d.next())
          ++count;
        d.reset();
        while (d.next()) {
            Integer user = d.curUserID();
            Integer item = d.curItemID();
            Double rating = d.curRating();
            long startPredTime = System.currentTimeMillis();
            double pred = rp.predictRating(user, item);
            sum += Math.pow(pred - rating, 2);
            evalTime += System.currentTimeMillis() - startPredTime;
            data.setRating(user, item, rating);
            //System.out.println(data.countRatingsItem(item) + " " + data.countRatingsUser(user));
            //if (n++%100 == 99) metrics.add(new TestMetric("RMSE (" + n +")", Math.sqrt(sum/(double)n)));
            n++;
            if (n%sampleFrequency == sampleFrequency-1) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                monitor.setCurrentActivityFractionComplete((double)n/(double)count);
                learningCurve.insertEntry(new LearningEvaluation(
                        new Measurement[]{
                            new Measurement(
                            "n",
                            n),
                            new Measurement(
                            "RMSE",
                            Math.sqrt(sum/(double)n)),
                            new Measurement(
                            "trainingTime",
                            (int)((System.currentTimeMillis() - start - evalTime)/1000)),
                            new Measurement(
                            "evalTime",
                            (int)(evalTime/1000))
                        }
                         ));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.headerToString() + "\n" +
                      learningCurve.entryToString(learningCurve.numEntries() - 1));
                }
            }
        }
        //System.out.println(n + " " + Math.sqrt(sum/(double)n));
        //metrics.add(new TestMetric("RMSE (" + n +")", Math.sqrt(sum/(double)n)));
       // long trainingTime = System.currentTimeMillis() - start - evalTime;
        //return new TestStatistics((int)(trainingTime/1000),
        //        (int)(evalTime/1000),
        //        metrics.toArray(new TestMetric[metrics.size()]));
        return learningCurve;
    }
String moa.tasks.EvaluateOnlineRecommender.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 49 of file EvaluateOnlineRecommender.java.
{
        return "Evaluates a online reccommender system.";
    }
Class<?> moa.tasks.EvaluateOnlineRecommender.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 71 of file EvaluateOnlineRecommender.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
ClassOption moa.tasks.EvaluateOnlineRecommender.datasetOption
Initial value:
 new ClassOption("dataset", 'd',
            "Dataset to evaluate.", Dataset.class, "moa.recommender.dataset.impl.MovielensDataset")
Definition at line 55 of file EvaluateOnlineRecommender.java.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
ClassOption moa.tasks.EvaluateOnlineRecommender.ratingPredictorOption
Initial value:
 new ClassOption("ratingPredictor", 's',
            "Rating Predictor to evaluate on.", RatingPredictor.class,
            "moa.recommender.predictor.BRISMFPredictor")
Definition at line 58 of file EvaluateOnlineRecommender.java.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
IntOption moa.tasks.EvaluateOnlineRecommender.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            100, 0, Integer.MAX_VALUE)
Definition at line 62 of file EvaluateOnlineRecommender.java.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
final long moa.tasks.EvaluateOnlineRecommender.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 53 of file EvaluateOnlineRecommender.java.
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateOnlineRecommender.java