MOA: moa.clusterers.streamkm.StreamKM Class Reference
moa.clusterers.streamkm.StreamKM Class Reference
Public Member Functions
void resetLearningImpl ()
void trainOnInstanceImpl (Instance inst)
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
double[] getVotesForInstance (Instance inst)
Clustering getClusteringResult ()
double lloydPlusPlus (int k, int n, int d, Point points[], Point centres[])
double targetFunctionValue (int k, int n, Point[] centres, Point[] points)
computes the target function for the given pointarray points[] (of size n) with the given array of centres centres[] (of size k)
Public Attributes
IntOption sizeCoresetOption
IntOption numClustersOption
IntOption widthOption
IntOption randomSeedOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Protected Attributes
MTRandom clustererRandom
Point[] centresStreamingCoreset
int numberInstances
int dimension
int length
int numberOfCentres
int coresetsize
BucketManager manager
boolean initialized = false
Private Member Functions
Point[] chooseRandomCentres (int k, int n, int d, Point points[])
Static Private Attributes
static final double THRESHOLD = 1.000
Detailed Description
Author:
Marcel R. Ackermann, Christiane Lammersen, Marcus Maertens, Christoph Raupach, Christian Sohler, Kamil Swierkot
Citation: Marcel R. Ackermann, Christiane Lammersen, Marcus Märtens, Christoph Raupach, Christian Sohler, Kamil Swierkot: StreamKM++: A Clustering Algorithms for Data Streams. ALENEX 2010: 173-187
Definition at line 21 of file StreamKM.java.
Member Function Documentation
Point [] moa.clusterers.streamkm.StreamKM.chooseRandomCentres (int k, int n, int d, Point points[]) [private]
Definition at line 192 of file StreamKM.java.
References moa.clusterers.streamkm.Point.centreIndex, moa.clusterers.streamkm.Point.clone(), moa.clusterers.streamkm.StreamKM.clustererRandom, moa.clusterers.streamkm.Point.costOfPointToCenter(), and moa.clusterers.streamkm.Point.curCost.
Referenced by moa.clusterers.streamkm.StreamKM.lloydPlusPlus().
{
        //array to store the choosen centres
        Point[] centres = new Point[k];
        //choose the first centre (each point has the same probability of being choosen)
        int i = 0;
        int next = 0;
        int j = 0;
        do{ //only choose from the n-i points not already choosen
            next = this.clustererRandom.nextInt(n-1);
            //check if the choosen point is not a dummy
        } while( points[next].weight < 1);
        //set j to next unchoosen point
        j = next;
        //copy the choosen point to the array
        centres[i] = points[j].clone();
        //set the current centre for all points to the choosen centre
        for(i = 0; i < n; i++){
            points[i].centreIndex = 0;
            points[i].curCost = points[i].costOfPointToCenter(centres[0]);
        }
        //choose centre 1 to k-1 with the kMeans++ distribution
        for(i = 1; i < k; i++){
            double cost = 0.0;
            for(j = 0; j < n; j++){
                cost += points[j].curCost;
            }
            double random = 0;
            double sum = 0.0;
            int pos = -1;
            do{
                    random = this.clustererRandom.nextDouble();//genrand_real3();
                    sum = 0.0;
                    pos = -1;
                for(j = 0; j < n; j++){
                    sum = sum + points[j].curCost;
                    if(random <= sum/cost){
                        pos = j;
                        break;
                    }
                }
            } while (points[pos].weight < 1);
            //copy the choosen centre
            centres[i] = points[pos].clone();
            //check which points are closest to the new centre
            for(j = 0; j < n; j++){
                double newCost = points[j].costOfPointToCenter(centres[i]);
                if(points[j].curCost > newCost){
                    points[j].curCost = newCost;
                    points[j].centreIndex = i;
                }
            }
        }
        /*printf("random centres: \n");
        for(i = 0; i < k; i++){
            //printf("%d: (",i);
            int l = 0;
            for(l = 0; l < centres[i].dimension; l++){
                printf("%f,",centres[i].coordinates[l] / centres[i].weight);
            }
            printf(")\n");
        }*/
        return centres;
    }
Clustering moa.clusterers.streamkm.StreamKM.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 118 of file StreamKM.java.
References moa.cluster.Clustering.add(), moa.clusterers.streamkm.StreamKM.centresStreamingCoreset, moa.clusterers.AbstractClusterer.clustering, and moa.clusterers.streamkm.StreamKM.initialized.
{
        if ( !this.initialized ) {
            return new Clustering();
        }
        Clustering clustering = new Clustering();
        for ( int i = 0; i < centresStreamingCoreset.length; i++ ) {
            if(centresStreamingCoreset[i] != null){
                clustering.add(centresStreamingCoreset[i].toCluster());
            }
        }
        return clustering;
    }
void moa.clusterers.streamkm.StreamKM.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 104 of file StreamKM.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
Measurement [] moa.clusterers.streamkm.StreamKM.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 99 of file StreamKM.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
double [] moa.clusterers.streamkm.StreamKM.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 112 of file StreamKM.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
boolean moa.clusterers.streamkm.StreamKM.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 108 of file StreamKM.java.
{
        return true;
    }
double moa.clusterers.streamkm.StreamKM.lloydPlusPlus (int k, int n, int d, Point points[], Point centres[])
Definition at line 134 of file StreamKM.java.
References moa.clusterers.streamkm.StreamKM.chooseRandomCentres(), moa.clusterers.streamkm.Point.coordinates, moa.clusterers.streamkm.Point.determineClusterCentreKMeans(), moa.clusterers.streamkm.Point.dimension, moa.clusterers.streamkm.StreamKM.targetFunctionValue(), moa.clusterers.streamkm.StreamKM.THRESHOLD, and moa.clusterers.streamkm.Point.weight.
Referenced by moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
{
        //printf("starting kMeans++\n");
        //choose random centres
        centres = chooseRandomCentres(k, n, d, points);
        double cost = targetFunctionValue(k, n, centres, points);
        double newCost = cost;
        Point[] massCentres = new Point[k];
        double[] numberOfPoints = new double[k];
        do{
            cost = newCost;
            //reset centres of mass
            int i = 0;
            for(i = 0; i < k; i++){
                massCentres[i] = new Point(d);
                numberOfPoints[i] = 0.0;
            }
            //compute centres of mass
            for(i = 0; i < n; i++){
                int centre = points[i].determineClusterCentreKMeans(k,centres);
                for(int l = 0; l < massCentres[centre].dimension; l++){
                    if(points[i].weight != 0.0)
                        massCentres[centre].coordinates[l] += points[i].coordinates[l];
                }
                numberOfPoints[centre] += points[i].weight;
            }
            //move centres
            for(i=0; i<k; i++){
                for(int l=0; l<centres[i].dimension; l++){
                    centres[i].coordinates[l] = massCentres[i].coordinates[l];
                    centres[i].weight = numberOfPoints[i];
                }
            }
            //calculate costs
            newCost = targetFunctionValue(k, n, centres, points);
            //printf("old cost:%f, new cost:%f \n",cost,newCost);
        } while (newCost < THRESHOLD * cost);
        /*printf("Centres: \n");
        int i=0;
        for(i=0;i<k;i++){
            printf("(");
            int l = 0;
            for(l=0;l<centres[i].dimension;l++){
                printf("%f,",centres[i].coordinates[l] / centres[i].weight);
            }
            printf(")\n");
        }
        printf("kMeans++ finished\n");
        */
        return newCost;
    }
void moa.clusterers.streamkm.StreamKM.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 53 of file StreamKM.java.
References moa.clusterers.streamkm.StreamKM.centresStreamingCoreset, moa.clusterers.streamkm.StreamKM.clustererRandom, moa.clusterers.streamkm.StreamKM.coresetsize, moa.options.IntOption.getValue(), moa.clusterers.streamkm.StreamKM.initialized, moa.clusterers.streamkm.StreamKM.length, moa.clusterers.streamkm.StreamKM.numberOfCentres, moa.clusterers.streamkm.StreamKM.numClustersOption, moa.clusterers.streamkm.StreamKM.randomSeedOption, moa.clusterers.streamkm.StreamKM.sizeCoresetOption, and moa.clusterers.streamkm.StreamKM.widthOption.
{
        this.initialized = false;
        this.coresetsize = sizeCoresetOption.getValue();
        this.numberOfCentres = numClustersOption.getValue();
        this.length = widthOption.getValue();
        this.centresStreamingCoreset = new Point[this.numberOfCentres];
        //initalize random generator with seed
        this.clustererRandom = new MTRandom(this.randomSeedOption.getValue());
    }
double moa.clusterers.streamkm.StreamKM.targetFunctionValue (int k, int n, Point[] centres, Point[] points)
computes the target function for the given pointarray points[] (of size n) with the given array of centres centres[] (of size k)
Definition at line 275 of file StreamKM.java.
References moa.clusterers.streamkm.Point.coordinates, moa.clusterers.streamkm.Point.dimension, and moa.clusterers.streamkm.Point.weight.
Referenced by moa.clusterers.streamkm.StreamKM.lloydPlusPlus().
{
        int i=0;
        double sum = 0.0;
        for(i=0;i<n;i++){
            double nearestCost = -1.0;
            int j=0;
            for(j=0;j<k;j++){
                double distance = 0.0;
                int l = 0;
                for(l=0;l<points[i].dimension;l++){
                    //Centroid coordinate of the point
                    double centroidCoordinatePoint;
                    if(points[i].weight != 0.0){
                        centroidCoordinatePoint = points[i].coordinates[l] / points[i].weight;
                    } else {
                        centroidCoordinatePoint = points[i].coordinates[l];
                    }
                    //Centroid coordinate of the centre
                    double centroidCoordinateCentre;
                    if(centres[j].weight != 0.0){
                        centroidCoordinateCentre = centres[j].coordinates[l] / centres[j].weight;
                    } else {
                        centroidCoordinateCentre = centres[j].coordinates[l];
                    }
                    distance += (centroidCoordinatePoint-centroidCoordinateCentre) *
                            (centroidCoordinatePoint-centroidCoordinateCentre) ;
                }
                if(nearestCost <0 || distance < nearestCost) {
                    nearestCost = distance;
                }
            }
            sum += nearestCost * points[i].weight;
        }
        return sum;
    }
void moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl (Instance inst) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 65 of file StreamKM.java.
References moa.clusterers.streamkm.StreamKM.centresStreamingCoreset, moa.clusterers.streamkm.StreamKM.clustererRandom, moa.clusterers.streamkm.StreamKM.coresetsize, moa.clusterers.streamkm.StreamKM.dimension, moa.clusterers.streamkm.BucketManager.getCoresetFromManager(), moa.options.IntOption.getValue(), moa.clusterers.streamkm.StreamKM.initialized, moa.clusterers.streamkm.BucketManager.insertPoint(), moa.clusterers.streamkm.StreamKM.length, moa.clusterers.streamkm.StreamKM.lloydPlusPlus(), moa.clusterers.streamkm.StreamKM.manager, moa.clusterers.streamkm.StreamKM.numberInstances, moa.clusterers.streamkm.StreamKM.numberOfCentres, and moa.clusterers.streamkm.StreamKM.widthOption.
{
        if (this.initialized == false) {
            this.dimension =  inst.numAttributes();
            manager = new BucketManager(this.length, this.dimension, this.coresetsize, this.clustererRandom);
            this.initialized = true;
        }
        manager.insertPoint(new Point(inst, this.numberInstances));
        this.numberInstances++;
        if (this.numberInstances % widthOption.getValue() == 0) {
            Point[] streamingCoreset = manager.getCoresetFromManager(dimension);
            //compute 5 clusterings of the coreset with kMeans++ and take the best
            double minCost = 0.0;
            double curCost = 0.0;
            minCost = lloydPlusPlus(numberOfCentres, coresetsize, dimension, streamingCoreset, centresStreamingCoreset);
            curCost = minCost;
            for(int i = 1; i < 5; i++){
                Point[] tmpCentresStreamingCoreset= new Point[0];
                curCost = lloydPlusPlus(numberOfCentres, coresetsize, dimension, streamingCoreset, tmpCentresStreamingCoreset);
                if(curCost < minCost) {
                    minCost = curCost;
                    centresStreamingCoreset = tmpCentresStreamingCoreset;
                }
            }
        }
    }
Member Data Documentation
Point [] moa.clusterers.streamkm.StreamKM.centresStreamingCoreset [protected]
Definition at line 37 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.getClusteringResult(), moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
MTRandom moa.clusterers.streamkm.StreamKM.clustererRandom [protected]
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 36 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.chooseRandomCentres(), moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
int moa.clusterers.streamkm.StreamKM.coresetsize [protected]
Definition at line 44 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
int moa.clusterers.streamkm.StreamKM.dimension [protected]
Definition at line 41 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
boolean moa.clusterers.streamkm.StreamKM.initialized = false [protected]
Definition at line 48 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.getClusteringResult(), moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
int moa.clusterers.streamkm.StreamKM.length [protected]
Definition at line 42 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
BucketManager moa.clusterers.streamkm.StreamKM.manager [protected]
Definition at line 46 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
int moa.clusterers.streamkm.StreamKM.numberInstances [protected]
Definition at line 39 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
int moa.clusterers.streamkm.StreamKM.numberOfCentres [protected]
Definition at line 43 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
IntOption moa.clusterers.streamkm.StreamKM.numClustersOption
Initial value:
 new IntOption(
            "numClusters", 'k',
            "Number of clusters to compute.", 5)
Definition at line 26 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl().
IntOption moa.clusterers.streamkm.StreamKM.randomSeedOption
Initial value:
 new IntOption("randomSeed", 'r',
                    "Seed for random behaviour of the classifier.", 1)
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 33 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl().
IntOption moa.clusterers.streamkm.StreamKM.sizeCoresetOption
Initial value:
 new IntOption("sizeCoreset",
            's', "Size of the coreset.", 10000)
Definition at line 23 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl().
final double moa.clusterers.streamkm.StreamKM.THRESHOLD = 1.000 [static, private]
Definition at line 50 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.lloydPlusPlus().
IntOption moa.clusterers.streamkm.StreamKM.widthOption
Initial value:
 new IntOption("width",
            'w', "Size of Window for training learner.", 100000, 0, Integer.MAX_VALUE)
Definition at line 30 of file StreamKM.java.
Referenced by moa.clusterers.streamkm.StreamKM.resetLearningImpl(), and moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/streamkm/StreamKM.java