MOA: moa.clusterers.outliers.MCOD.MCODBase Class Reference
moa.clusterers.outliers.MCOD.MCODBase Class Reference
Classes
class EventItem
class EventQueue
class SearchResultMC
Public Member Functions
String getObjectInfo (Object obj)
String getStatistics ()
void PrintNodeSet (Set< ISBNode > set)
void PrintMCSet (Set< MicroCluster > set)
void PrintNodeVector (Vector< ISBNode > vector)
void PrintNodeList (List< ISBNode > list)
void PrintEventQueue ()
void PrintPD ()
Public Attributes
boolean bWarning = false
int m_nBothInlierOutlier
int m_nOnlyInlier
int m_nOnlyOutlier
Protected Member Functions
boolean IsNodeIdInWin (long id)
Protected Attributes
Long objId
Vector< ISBNode > windowNodes
EventQueue eventQueue
MTreeMicroClusters mtreeMC
TreeSet< MicroCluster > setMC
TreeSet< ISBNode > nodesReinsert
ISBIndex ISB_PD
int m_WindowSize
double m_radius
int m_k
double m_theta = 1.0
Static Protected Attributes
static final Long FIRST_OBJ_ID = 1L
Package Functions
Long GetWindowEnd ()
Long GetWindowStart ()
boolean IsWinFull ()
Long GetExpirationTime (ISBNode node)
void SaveOutlier (ISBNode node)
void RemoveOutlier (ISBNode node)
void AddNode (ISBNode node)
void RemoveNode (ISBNode node)
void UpdateStatistics (ISBNode node)
ISBNode GetExpiredNode ()
void AddMicroCluster (MicroCluster mc)
void RemoveMicroCluster (MicroCluster mc)
Vector< SearchResultMC > RangeSearchMC (ISBNode nodeNew, double radius)
double GetEuclideanDist (ISBNode n1, ISBNode n2)
void PrintWindow ()
void PrintNode (ISBNode n)
Detailed Description
Definition at line 28 of file MCODBase.java.
Member Function Documentation
void moa.clusterers.outliers.MCOD.MCODBase.AddMicroCluster (MicroCluster mc) [package]
Definition at line 260 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MTreeMicroClusters.add(), moa.clusterers.outliers.MCOD.MCODBase.mtreeMC, and moa.clusterers.outliers.MCOD.MCODBase.setMC.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        mtreeMC.add(mc);
        setMC.add(mc);
    }
void moa.clusterers.outliers.MCOD.MCODBase.AddNode (ISBNode node) [package]
Definition at line 228 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.windowNodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        windowNodes.add(node);
    }
double moa.clusterers.outliers.MCOD.MCODBase.GetEuclideanDist (ISBNode n1, ISBNode n2) [package]
Definition at line 292 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.StreamObj.dimensions(), moa.clusterers.outliers.MCOD.StreamObj.get(), and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
    {
        double diff;
        double sum = 0;
        int d = n1.obj.dimensions();
        for (int i = 0; i < d; i++) {
            diff = n1.obj.get(i) - n2.obj.get(i);
            sum += Math.pow(diff, 2);
        }
        return Math.sqrt(sum);
    }
Long moa.clusterers.outliers.MCOD.MCODBase.GetExpirationTime (ISBNode node) [package]
Definition at line 204 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, and moa.clusterers.outliers.MCOD.MCODBase.m_WindowSize.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue().
{
        return node.id + m_WindowSize;
    }
ISBNode moa.clusterers.outliers.MCOD.MCODBase.GetExpiredNode () [package]
Definition at line 248 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, and moa.clusterers.outliers.MCOD.MCODBase.windowNodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        if (windowNodes.size() <= 0)
            return null;
        // get oldest node
        ISBNode node = windowNodes.get(0);
        // check if node has expired
        if (node.id < GetWindowStart()) {
            return node;
        }
        return null;
    }
String moa.clusterers.outliers.MCOD.MCODBase.getObjectInfo (Object obj)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 111 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.MCOD.StreamObj.dimensions(), moa.clusterers.outliers.MCOD.StreamObj.get(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nodeType, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
{
        if (obj == null) return null;
        ISBNode node = (ISBNode) obj;
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        StringBuilder sb = new StringBuilder();
        // show node type
        infoTitle.add("Node type");
        infoValue.add((node.nodeType == NodeType.OUTLIER) ? "Outlier" : "Inlier");
        // show node position
        for (int i = 0; i < node.obj.dimensions(); i++) {
            infoTitle.add("Dim" + (i+1));
            infoValue.add(String.format("%.3f", node.obj.get(i)));
        }
        // show node properties
        infoTitle.add("id");
        infoValue.add(String.format("%d", node.id));
        infoTitle.add("count_after");
        infoValue.add(String.format("%d", node.count_after));
        infoTitle.add("|nn_before|");
        infoValue.add(String.format("%d", node.CountPrecNeighs(GetWindowStart())));
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td><b>"+infoTitle.get(i)+":</b></td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
String moa.clusterers.outliers.MCOD.MCODBase.getStatistics ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 153 of file MCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage, moa.clusterers.outliers.MCOD.MCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyInlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, and moa.clusterers.outliers.MCOD.MCODBase.windowNodes.
{
        StringBuilder sb = new StringBuilder();
        sb.append("Statistics:\n\n");
        // get counters of expired nodes
        int nBothInlierOutlier = m_nBothInlierOutlier;
        int nOnlyInlier = m_nOnlyInlier;
        int nOnlyOutlier = m_nOnlyOutlier;
        // add counters of non expired nodes
        for (ISBNode node : windowNodes) {
            if ((node.nInlier > 0) && (node.nOutlier > 0))
                nBothInlierOutlier++;
            else if (node.nInlier > 0)
                nOnlyInlier++;
            else
                nOnlyOutlier++;
        }
        int sum = nBothInlierOutlier + nOnlyInlier + nOnlyOutlier;
        if (sum > 0) {
            sb.append(String.format("  Nodes always inlier: %d (%.1f%%)\n", nOnlyInlier, (100 * nOnlyInlier) / (double)sum));
            sb.append(String.format("  Nodes always outlier: %d (%.1f%%)\n", nOnlyOutlier, (100 * nOnlyOutlier) / (double)sum));
            sb.append(String.format("  Nodes both inlier and outlier: %d (%.1f%%)\n", nBothInlierOutlier, (100 * nBothInlierOutlier) / (double)sum));
            sb.append("  (Sum: " + sum + ")\n");
        }
        sb.append("\n  Total range queries: " + nRangeQueriesExecuted + "\n");
        sb.append("  Max memory usage: " + iMaxMemUsage + " MB\n");
        sb.append("  Total process time: " + String.format("%.2f ms", nTotalRunTime / 1000.0) + "\n");
        return sb.toString();
    }
Long moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd () [package]
Definition at line 189 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.objId.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.MCODBase.IsNodeIdInWin(), moa.clusterers.outliers.MCOD.MCODBase.IsWinFull(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), and moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue().
{
        return objId - 1;
    }
Long moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart () [package]
Definition at line 193 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.FIRST_OBJ_ID, moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), and moa.clusterers.outliers.MCOD.MCODBase.m_WindowSize.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MCODBase.GetExpiredNode(), moa.clusterers.outliers.MCOD.MCODBase.getObjectInfo(), moa.clusterers.outliers.MCOD.MCODBase.IsNodeIdInWin(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        Long x = GetWindowEnd() - m_WindowSize + 1;
        if (x < FIRST_OBJ_ID)
            x = FIRST_OBJ_ID;
        return x;
    }
boolean moa.clusterers.outliers.MCOD.MCODBase.IsNodeIdInWin (long id) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 219 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), and moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart().
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), and moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue().
{
        int toleranceStart = 1;
        Long start = GetWindowStart() - toleranceStart;
        if ( (start <= id) && (id <= GetWindowEnd()) )
            return true;
        else
            return false;
    }
boolean moa.clusterers.outliers.MCOD.MCODBase.IsWinFull () [package]
Definition at line 200 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.FIRST_OBJ_ID, moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), and moa.clusterers.outliers.MCOD.MCODBase.m_WindowSize.
{
        return (GetWindowEnd() >= FIRST_OBJ_ID + m_WindowSize - 1);
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintEventQueue ()
Definition at line 353 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.eventQueue, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.MCODBase.EventItem.node, moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.EventQueue.setEvents, and moa.clusterers.outliers.MCOD.MCODBase.EventItem.timeStamp.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue().
{
        Println("event queue: ");
        for (EventItem n : eventQueue.setEvents) {
            Printf("  id=%d, exp=%d\n", n.node.id, n.timeStamp);
        }
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet (Set< MicroCluster > set)
Definition at line 332 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.MicroCluster.mcc, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        for (MicroCluster n : set) {
            Print(n.mcc.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintNode (ISBNode n) [package]
Definition at line 314 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.StreamObj.dimensions(), moa.clusterers.outliers.MCOD.StreamObj.get(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        Print("id=" + n.id + " (");
        int dim = n.obj.dimensions();
        for (int d = 0; d < dim; d++) {
            Print(Double.toString(n.obj.get(d)));
            if (d < dim - 1)
                Print(", ");
        }
        Println(")");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList (List< ISBNode > list)
Definition at line 346 of file MCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        for (ISBNode n : list) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintNodeSet (Set< ISBNode > set)
Definition at line 325 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
{
        for (ISBNode n : set) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintNodeVector (Vector< ISBNode > vector)
Definition at line 339 of file MCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
{
        for (ISBNode n : vector) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintPD ()
Definition at line 360 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.GetAllNodes(), moa.clusterers.outliers.MCOD.MCODBase.ISB_PD, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        Print("PD: ");
        for (ISBNode n : ISB_PD.GetAllNodes()) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.MCOD.MCODBase.PrintWindow () [package]
Definition at line 304 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.PrintNode(), and moa.clusterers.outliers.MCOD.MCODBase.windowNodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
                       {
        Println("Window [" + GetWindowStart() + "-" + GetWindowEnd() + "]: ");
        ISBNode node;
        for (int i = 0; i < windowNodes.size(); i++) {
            node = windowNodes.get(i);
            Print("   Node: ");
            PrintNode(node);
        }
    }
Vector<SearchResultMC> moa.clusterers.outliers.MCOD.MCODBase.RangeSearchMC (ISBNode nodeNew, double radius) [package]
Definition at line 280 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MTreeMicroClusters.add(), and moa.clusterers.outliers.MCOD.MCODBase.mtreeMC.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        Vector<SearchResultMC> results = new Vector<SearchResultMC>();
        // create a dummy mc in order to search w.r.t. nodeNew
        MicroCluster dummy = new MicroCluster(nodeNew);
        // query results are returned ascenting by distance
        MTreeMicroClusters.Query query = mtreeMC.getNearestByRange(dummy, radius);
        for (MTreeMicroClusters.ResultItem q : query) {
            results.add(new SearchResultMC(q.data, q.distance));
        }
        return results;
    }
void moa.clusterers.outliers.MCOD.MCODBase.RemoveMicroCluster (MicroCluster mc) [package]
Definition at line 265 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.mtreeMC, moa.clusterers.outliers.MCOD.MTreeMicroClusters.remove(), and moa.clusterers.outliers.MCOD.MCODBase.setMC.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode().
{
        mtreeMC.remove(mc);
        setMC.remove(mc);
    }
void moa.clusterers.outliers.MCOD.MCODBase.RemoveNode (ISBNode node) [package]
Definition at line 232 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.inst, moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), moa.clusterers.outliers.MCOD.MCODBase.UpdateStatistics(), and moa.clusterers.outliers.MCOD.MCODBase.windowNodes.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode().
{
        windowNodes.remove(node);
        RemoveExpiredOutlier(new Outlier(node.inst, node.id, node)); // ### remove when expired?
        // update statistics
        UpdateStatistics(node);
    }
void moa.clusterers.outliers.MCOD.MCODBase.RemoveOutlier (ISBNode node) [package]
Definition at line 213 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nInlier.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        RemoveOutlier(new Outlier(node.inst, node.id, node));
        node.nInlier++; // update statistics
    }
void moa.clusterers.outliers.MCOD.MCODBase.SaveOutlier (ISBNode node) [package]
Definition at line 208 of file MCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        AddOutlier(new Outlier(node.inst, node.id, node));
        node.nOutlier++; // update statistics
    }
void moa.clusterers.outliers.MCOD.MCODBase.UpdateStatistics (ISBNode node) [package]
Definition at line 239 of file MCODBase.java.
References moa.clusterers.outliers.MCOD.MCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyInlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyOutlier, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nInlier, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.RemoveNode().
{
        if ((node.nInlier > 0) && (node.nOutlier > 0))
            m_nBothInlierOutlier++;
        else if (node.nInlier > 0)
            m_nOnlyInlier++;
        else
            m_nOnlyOutlier++;
    }
Member Data Documentation
boolean moa.clusterers.outliers.MCOD.MCODBase.bWarning = false
Definition at line 103 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue().
EventQueue moa.clusterers.outliers.MCOD.MCODBase.eventQueue [protected]
Definition at line 89 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCODBase.PrintEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue().
final Long moa.clusterers.outliers.MCOD.MCODBase.FIRST_OBJ_ID = 1L [static, protected]
Definition at line 83 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCODBase.IsWinFull().
ISBIndex moa.clusterers.outliers.MCOD.MCODBase.ISB_PD [protected]
Definition at line 97 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
int moa.clusterers.outliers.MCOD.MCODBase.m_k [protected]
Definition at line 100 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
int moa.clusterers.outliers.MCOD.MCODBase.m_nBothInlierOutlier
Definition at line 106 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCODBase.UpdateStatistics().
int moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyInlier
Definition at line 107 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCODBase.UpdateStatistics().
int moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyOutlier
Definition at line 108 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCODBase.UpdateStatistics().
double moa.clusterers.outliers.MCOD.MCODBase.m_radius [protected]
Definition at line 99 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
double moa.clusterers.outliers.MCOD.MCODBase.m_theta = 1.0 [protected]
Definition at line 101 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
int moa.clusterers.outliers.MCOD.MCODBase.m_WindowSize [protected]
Definition at line 98 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.GetExpirationTime(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCODBase.IsWinFull().
MTreeMicroClusters moa.clusterers.outliers.MCOD.MCODBase.mtreeMC [protected]
Definition at line 91 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.AddMicroCluster(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCODBase.RangeSearchMC(), and moa.clusterers.outliers.MCOD.MCODBase.RemoveMicroCluster().
TreeSet<ISBNode> moa.clusterers.outliers.MCOD.MCODBase.nodesReinsert [protected]
Definition at line 95 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
Long moa.clusterers.outliers.MCOD.MCODBase.objId [protected]
Definition at line 86 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), moa.clusterers.outliers.MCOD.MCOD.Init(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
TreeSet<MicroCluster> moa.clusterers.outliers.MCOD.MCODBase.setMC [protected]
Definition at line 93 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.AddMicroCluster(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), and moa.clusterers.outliers.MCOD.MCODBase.RemoveMicroCluster().
Vector<ISBNode> moa.clusterers.outliers.MCOD.MCODBase.windowNodes [protected]
Definition at line 88 of file MCODBase.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.AddNode(), moa.clusterers.outliers.MCOD.MCODBase.GetExpiredNode(), moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), and moa.clusterers.outliers.MCOD.MCODBase.RemoveNode().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/MCODBase.java