MOA: moa.clusterers.clustree.Entry Class Reference
moa.clusterers.clustree.Entry Class Reference
Public Member Functions
Entry (int numberDimensions)
Constructor for the entry.
Entry (int numberDimensions, ClusKernel cluster, long currentTime)
Constructuctor that creates an Entry with an empty buffer and the data given by the Kernel.
Node getNode ()
void setNode (Node node)
double calcDistance (Entry other)
Calculates the distance to the data in this entry of the data in the given entry.
void add (Entry other)
Add the data cluster of another entry to the data cluster of this entry.
Node getChild ()
Return the reference to the child of this Entry to navigate in the tree.
Entry getParentEntry ()
void setParentEntry (Entry parent)
void setChild (Node child)
Setter for the child in this entry.
long getTimestamp ()
Return the current timestamp.
Public Attributes
ClusKernel data
The actual entry data.
Protected Member Functions
Entry (int numberDimensions, Node node, long currentTime, Entry parentEntry, Node containerNode)
Constructor that creates an Entry that points to the given node.
Entry (int numberDimensions, ClusKernel cluster, long currentTime, Entry parentEntry, Node containerNode)
extended constructor with containerNode and parentEntry
Entry (Entry other)
Copy constructor.
void clear ()
Clear the Entry.
void shallowClear ()
Clear the data and the buffer Custer in this entry.
double calcDistance (ClusKernel cluster)
Calculates the distance to the data in this entry.
void initializeEntry (Entry other, long currentTime)
When this entry is empty, give it it's first values.
void aggregateEntry (Entry other, long currentTime, double negLambda)
Aggregate the data in the Kernel of the other Entry.
void aggregateCluster (ClusKernel otherData, long currentTime, double negLambda)
Aggregate the given Kernel to the data cluster of this entry.
void aggregateToBuffer (ClusKernel pointToInsert, long currentTime, double negLambda)
Aggregate the given Kernel to the buffer cluster of this entry.
void mergeWith (Entry other)
Merge this entry witht the given Entry.
ClusKernel getBuffer ()
Getter for the buffer.
ClusKernel getData ()
Getter for the data.
ClusKernel emptyBuffer (long currentTime, double negLambda)
Clear the buffer in this entry and return a copy.
boolean isEmpty ()
Check if this Entry is empty or not.
void overwriteOldEntry (Entry newEntry)
Overwrites the LS, SS and weightedN in the data cluster of this Entry to the values of the data cluster in the given Entry, but adds N and classCount of the cluster in the given Entry to the data cluster in this one.
void recalculateData ()
This functions reads every entry in the child node and calculates the corresponding data Kernel.
boolean isIrrelevant (double threshold)
Returns true if this entry is irrelevant with respecto the given threshold.
void makeOlder (long currentTime, double negLambda)
Ages this entrie's data AND buffer according to the given time and aging constant.
Private Attributes
ClusKernel buffer
The buffer of this entry.
Node child
A reference to the next node in the tree.
Entry parentEntry
A reference to the Entry's parent Entry.
Node node
A reference to the Node, that contains this Entry.
long timestamp
Last time this entry was changed.
Static Private Attributes
static final long defaultTimestamp = 0
The timestamp to be used when no operation has yet been done on this entry.
Detailed Description
Definition at line 22 of file Entry.java.
Constructor & Destructor Documentation
moa.clusterers.clustree.Entry.Entry (int numberDimensions)
Constructor for the entry.
To be used when we want to create an empty entry. Notice that the timestamp will be set to zero, since there is no reason to know when an empty entry was generated.
Parameters:
numberDimensions The dimensionality of the data point in tree where this entry is used.
Definition at line 64 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Entry.data, and moa.clusterers.clustree.Entry.timestamp.
{
        this.data = new ClusKernel(numberDimensions);
        this.buffer = new ClusKernel(numberDimensions);
        this.child = null;
        this.timestamp = Entry.defaultTimestamp;
    }
moa.clusterers.clustree.Entry.Entry (int numberDimensions, Node node, long currentTime, Entry parentEntry, Node containerNode) [protected]
Constructor that creates an Entry that points to the given node.
The values of data will be calculated for this.
Parameters:
numberDimensions The dimensionality of the node.
node The node to which the new Entry should point.
currentTime The timestamp for the moment where this Entry was was generated.
See also:
Node
data
Definition at line 81 of file Entry.java.
References moa.clusterers.clustree.Entry.add(), moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.Entry.setParentEntry(), and moa.clusterers.clustree.Entry.timestamp.
{
        this(numberDimensions);
        this.child = node;
        this.parentEntry = parentEntry;
        this.node = containerNode;
        Entry[] entries = node.getEntries();
        for (int i = 0; i < entries.length; i++) {
            Entry entry = entries[i];
            entry.setParentEntry(this);
            if (entry.isEmpty()) {
                break;
            }
            this.add(entry);
        }
        this.timestamp = currentTime;
    }
moa.clusterers.clustree.Entry.Entry (int numberDimensions, ClusKernel cluster, long currentTime)
Constructuctor that creates an Entry with an empty buffer and the data given by the Kernel.
Parameters:
numberDimensions The dimensionality of the information in the cluster.
cluster The cluster from which the information is to be extracted.
currentTime The timestamp for the moment where this Entry was was generated.
See also:
Kernel
data
Definition at line 114 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.data, and moa.clusterers.clustree.Entry.timestamp.
{
        this(numberDimensions);
        this.data.add(cluster);
        this.timestamp = currentTime;
    }
moa.clusterers.clustree.Entry.Entry (int numberDimensions, ClusKernel cluster, long currentTime, Entry parentEntry, Node containerNode) [protected]
extended constructor with containerNode and parentEntry
Parameters:
numberDimensions
cluster
currentTime
parentEntry
containerNode
Definition at line 127 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.Entry.node, and moa.clusterers.clustree.Entry.timestamp.
{
        this(numberDimensions);
        this.parentEntry = parentEntry;
        this.data.add(cluster);
        this.node = containerNode;
        this.timestamp = currentTime;
    }
moa.clusterers.clustree.Entry.Entry (Entry other) [protected]
Copy constructor.
Everythin is copied, including the child.
Parameters:
other
Definition at line 138 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Entry.node, moa.clusterers.clustree.Entry.parentEntry, and moa.clusterers.clustree.Entry.timestamp.
{
        this.parentEntry = other.parentEntry;
        this.node = other.node;
        this.buffer = new ClusKernel(other.buffer);
        this.data = new ClusKernel(other.data);
        this.timestamp = other.timestamp;
        this.child = other.child;
        if (other.getChild()!=null)
            for (Entry e : other.getChild().getEntries()){
                e.setParentEntry(this);
            }
    }
Member Function Documentation
void moa.clusterers.clustree.Entry.add (Entry other)
Add the data cluster of another entry to the data cluster of this entry.
By using this function the timestamp does not get updated, nor does this entry get older.
Parameters:
other The entry of which the data cluster should be added to the local data cluster.
See also:
data
Kernel.add(tree.Kernel)
Definition at line 242 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), and moa.clusterers.clustree.Entry.data.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.buildTreeRecursively(), moa.clusterers.clustree.Entry.Entry(), and moa.clusterers.clustree.ClusTree.getClustering().
{
        this.data.add(other.data);
    }
void moa.clusterers.clustree.Entry.aggregateCluster (ClusKernel otherData, long currentTime, double negLambda) [protected]
Aggregate the given Kernel to the data cluster of this entry.
Parameters:
otherData The Entry to be aggregated.
See also:
data
Kernel
Definition at line 267 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.aggregate(), moa.clusterers.clustree.Entry.getData(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        this.getData().aggregate(otherData, currentTime - this.timestamp,
                negLambda);
        this.timestamp = currentTime;
    }
void moa.clusterers.clustree.Entry.aggregateEntry (Entry other, long currentTime, double negLambda) [protected]
Aggregate the data in the Kernel of the other Entry.
Parameters:
other The Entry to be aggregated.
See also:
data
Kernel
Definition at line 253 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.aggregate(), moa.clusterers.clustree.Entry.data, and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit().
{
        this.data.aggregate(other.data, currentTime - this.timestamp,
                negLambda);
        this.timestamp = currentTime;
    }
void moa.clusterers.clustree.Entry.aggregateToBuffer (ClusKernel pointToInsert, long currentTime, double negLambda) [protected]
Aggregate the given Kernel to the buffer cluster of this entry.
Parameters:
pointToInsert The cluster to aggregate to the buffer.
currentTime The time at which the aggregation occurs.
negLambda A parameter needed to weight the current state of the buffer.
Definition at line 282 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.aggregate(), moa.clusterers.clustree.Entry.getBuffer(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        ClusKernel currentBuffer = this.getBuffer();
        currentBuffer.aggregate(pointToInsert, currentTime - this.timestamp,
                negLambda);
        this.timestamp = currentTime;
    }
double moa.clusterers.clustree.Entry.calcDistance (Entry other)
Calculates the distance to the data in this entry of the data in the given entry.
Parameters:
other The Entry to which the distance is to be calculated.
Returns:
The distance to the data Kernel in this Entry of the data Kernel in the other Entry.
See also:
Kernel
data
Definition at line 207 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.calcDistance(), and moa.clusterers.clustree.Entry.getData().
{
        return this.getData().calcDistance(other.getData());
    }
double moa.clusterers.clustree.Entry.calcDistance (ClusKernel cluster) [protected]
Calculates the distance to the data in this entry.
Parameters:
cluster The Kernel cluster to which the distance is to be calculated.
Returns:
The distance to the data Kernel in this Entry
See also:
Kernel
data
Definition at line 192 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.calcDistance(), and moa.clusterers.clustree.Entry.data.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.buildTreeRecursively(), moa.clusterers.clustree.ClusTree.calculateBestMergeInNode(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit(), and moa.clusterers.clustree.Node.nearestEntry().
{
        return data.calcDistance(cluster);
    }
void moa.clusterers.clustree.Entry.clear () [protected]
Clear the Entry.
All points in the buffer and in the data cluster are lost, the connection to the child is lost and the timestamp is set to the default value.
Definition at line 164 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.ClusKernel.clear(), moa.clusterers.clustree.Entry.data, and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.Node.mergeEntries(), and moa.clusterers.clustree.Entry.recalculateData().
{
        this.data.clear();
        this.buffer.clear();
        this.child = null;
        this.timestamp = Entry.defaultTimestamp;
    }
ClusKernel moa.clusterers.clustree.Entry.emptyBuffer (long currentTime, double negLambda) [protected]
Clear the buffer in this entry and return a copy.
No side effects are possible (given that the copy constructor of Kernel makes a deep copy).
Returns:
A copy of the buffer.
Definition at line 369 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.ClusKernel.clear(), moa.clusterers.clustree.ClusKernel.makeOlder(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.insert().
{
        this.buffer.makeOlder(currentTime - this.timestamp, negLambda);
        ClusKernel bufferCopy = new ClusKernel(this.buffer);
        this.buffer.clear();
        return bufferCopy;
    }
ClusKernel moa.clusterers.clustree.Entry.getBuffer () [protected]
Getter for the buffer.
It is the real object, that means side effects are possible!
Returns:
A reference to the buffer in this entry.
Definition at line 315 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer.
Referenced by moa.clusterers.clustree.Entry.aggregateToBuffer(), moa.clusterers.clustree.Entry.initializeEntry(), and moa.clusterers.clustree.Entry.overwriteOldEntry().
{
        return buffer;
    }
Node moa.clusterers.clustree.Entry.getChild ()
Return the reference to the child of this Entry to navigate in the tree.
Returns:
A reference to the child of this Entry
Definition at line 324 of file Entry.java.
References moa.clusterers.clustree.Entry.child.
Referenced by moa.clusterers.clustree.ClusTree.cleanUp(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.outliers.AnyOut.AnyOutCore.improveObjectOnce(), moa.clusterers.outliers.AnyOut.AnyOutCore.initObject(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.Node.isLeaf(), moa.clusterers.clustree.Entry.overwriteOldEntry(), moa.clusterers.clustree.Entry.recalculateData(), and moa.clusterers.clustree.ClusTree.split().
{
        return child;
    }
ClusKernel moa.clusterers.clustree.Entry.getData () [protected]
Getter for the data.
It is the real object, that means side effects are possible!
Returns:
A reference to the data Kernel in this entry.
See also:
Kernel
Definition at line 334 of file Entry.java.
References moa.clusterers.clustree.Entry.data.
Referenced by moa.clusterers.clustree.Entry.aggregateCluster(), moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.Entry.isIrrelevant(), and moa.clusterers.clustree.Entry.recalculateData().
{
        return data;
    }
Node moa.clusterers.clustree.Entry.getNode ()
Definition at line 151 of file Entry.java.
References moa.clusterers.clustree.Entry.node.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.updateToTop().
{
        return node;
    }
Entry moa.clusterers.clustree.Entry.getParentEntry ()
Definition at line 337 of file Entry.java.
References moa.clusterers.clustree.Entry.parentEntry.
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), and moa.clusterers.clustree.ClusTree.updateToTop().
{
        return parentEntry;
    }
long moa.clusterers.clustree.Entry.getTimestamp ()
Return the current timestamp.
Returns:
The current timestamp.
Definition at line 359 of file Entry.java.
References moa.clusterers.clustree.Entry.timestamp.
{
        return timestamp;
    }
void moa.clusterers.clustree.Entry.initializeEntry (Entry other, long currentTime) [protected]
When this entry is empty, give it it's first values.
It makes sense to have this operation separated from the aggregation, because the aggregation first weights the values in data and Kernel, which makes no sense in an empty entry.
Parameters:
other The entry with the information to be used to initialize this entry.
currentTime The time at which this is happening.
Definition at line 220 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.Entry.getBuffer(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.ClusKernel.isEmpty(), moa.clusterers.clustree.Entry.isEmpty(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.Node.addEntry().
{
        assert (this.isEmpty());
        assert (other.getBuffer().isEmpty());
        this.data.add(other.data);
        this.timestamp = currentTime;
        this.child = other.child;
        if (child!=null){
            for (Entry e : child.getEntries()){
                e.setParentEntry(this);
            }
        }
    }
boolean moa.clusterers.clustree.Entry.isEmpty () [protected]
Check if this Entry is empty or not.
An Entry is empty if the data Kernel is empty, since then the buffer has to be empty.
Returns:
true if the data cluster has no data points, false otherwise.
Definition at line 383 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.data, and moa.clusterers.clustree.ClusKernel.isEmpty().
Referenced by moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.Node.getNextEmptyPosition(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.Node.nearestEntry(), moa.clusterers.clustree.Node.numFreeEntries(), and moa.clusterers.clustree.Entry.overwriteOldEntry().
{
        // Assert that if the data cluster is empty, the buffer cluster is
        // empty too.
        assert ((this.data.isEmpty() && this.buffer.isEmpty())
                || !this.data.isEmpty());
        return this.data.isEmpty();
    }
boolean moa.clusterers.clustree.Entry.isIrrelevant (double threshold) [protected]
Returns true if this entry is irrelevant with respecto the given threshold.
This is done by comparing the weighted N of this Entry to the threshold, if it is smaller, than the entry is deemed to be irrelevant.
Parameters:
threshold The threshold under which entries at leafs can be erased.
Returns:
True if this entry is deemed irrelevant, false otherwise.
Definition at line 442 of file Entry.java.
References moa.clusterers.clustree.Entry.getData(), and moa.clusterers.clustree.ClusKernel.getWeight().
Referenced by moa.clusterers.clustree.ClusTree.getClustering(), and moa.clusterers.clustree.Node.getIrrelevantEntry().
{
        return this.getData().getWeight() < threshold;
    }
void moa.clusterers.clustree.Entry.makeOlder (long currentTime, double negLambda) [protected]
Ages this entrie's data AND buffer according to the given time and aging constant.
Parameters:
currentTime the current time
negLambda the aging constant
Definition at line 452 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.ClusKernel.makeOlder(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.getClustering(), and moa.clusterers.clustree.Node.makeOlder().
{
//        assert (currentTime > this.timestamp) : "currentTime : "
//                + currentTime + ", this.timestamp: " + this.timestamp;
        long diff = currentTime - this.timestamp;
        this.buffer.makeOlder(diff, negLambda);
        this.data.makeOlder(diff, negLambda);
        this.timestamp = currentTime;
    }
void moa.clusterers.clustree.Entry.mergeWith (Entry other) [protected]
Merge this entry witht the given Entry.
This adds the data cluster of the given Entry to the data cluster of this entry and sets the timestamp to the newest one of the the two entries.
Parameters:
other The entry from which the data cluster is added.
See also:
Kernel.add(tree.Kernel)
Definition at line 297 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.ClusKernel.isEmpty(), and moa.clusterers.clustree.Entry.timestamp.
Referenced by moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.Node.mergeEntries().
{
        // We should only merge entries in leafs, and leafes should have empty
        // buffers.
        assert (this.child == null);
        assert (other.child == null);
        assert (other.buffer.isEmpty());
        this.data.add(other.data);
        if (this.timestamp < other.timestamp) {
            this.timestamp = other.timestamp;
        }
    }
void moa.clusterers.clustree.Entry.overwriteOldEntry (Entry newEntry) [protected]
Overwrites the LS, SS and weightedN in the data cluster of this Entry to the values of the data cluster in the given Entry, but adds N and classCount of the cluster in the given Entry to the data cluster in this one.
This function is useful when the weight of an entry becomes to small, and we want to forget the information of the old points.
Parameters:
newEntry The cluster that should overwrite the information.
Definition at line 401 of file Entry.java.
References moa.clusterers.clustree.Entry.child, moa.clusterers.clustree.Entry.data, moa.clusterers.clustree.Entry.getBuffer(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.ClusKernel.isEmpty(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.ClusKernel.overwriteOldCluster(), moa.clusterers.clustree.Entry.parentEntry, and moa.clusterers.clustree.Entry.setParentEntry().
Referenced by moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.insertHereWithSplit().
{
        assert (this.getBuffer().isEmpty());
        assert (newEntry.getBuffer().isEmpty());
        this.data.overwriteOldCluster(newEntry.data);
        newEntry.setParentEntry(this.parentEntry);
        if (newEntry.getChild()!=null)
        for (Entry e : newEntry.getChild().getEntries())
            e.setParentEntry(this);
        //this.setParentEntry(newEntry.getParentEntry());
        this.child=newEntry.child;
    }
void moa.clusterers.clustree.Entry.recalculateData () [protected]
This functions reads every entry in the child node and calculates the corresponding data Kernel.
Timestamps are not changed.
See also:
data
Kerne
Definition at line 419 of file Entry.java.
References moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.ClusKernel.clear(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Entry.getData(), and moa.clusterers.clustree.Node.getEntries().
Referenced by moa.clusterers.clustree.ClusTree.split().
{
        Node currentChild = this.getChild();
        if (currentChild != null) {
            ClusKernel currentData = this.getData();
            currentData.clear();
            Entry[] entries = currentChild.getEntries();
            for (int i = 0; i < entries.length; i++) {
                currentData.add(entries[i].getData());
            }
        } else {
            this.clear();
        }
    }
void moa.clusterers.clustree.Entry.setChild (Node child)
Setter for the child in this entry.
Use to build the tree.
Parameters:
child The Node that should be a child of this Entry
See also:
Node
Definition at line 351 of file Entry.java.
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.buildTreeRecursively(), moa.clusterers.clustree.ClusTree.cleanUp(), and moa.clusterers.clustree.ClusTree.split().
{
        this.child = child;
    }
void moa.clusterers.clustree.Entry.setNode (Node node)
Definition at line 155 of file Entry.java.
Referenced by moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.ClusTree.insert(), and moa.clusterers.clustree.Node.Node().
{
        this.node = node;
    }
void moa.clusterers.clustree.Entry.setParentEntry (Entry parent)
Definition at line 341 of file Entry.java.
References moa.clusterers.clustree.Entry.parentEntry.
Referenced by moa.clusterers.clustree.Entry.Entry(), and moa.clusterers.clustree.Entry.overwriteOldEntry().
{
        this.parentEntry = parent;
    }
void moa.clusterers.clustree.Entry.shallowClear () [protected]
Clear the data and the buffer Custer in this entry.
This function does not clear the child of this Entry.
See also:
data
buffer
Kernel
Definition at line 178 of file Entry.java.
References moa.clusterers.clustree.Entry.buffer, moa.clusterers.clustree.ClusKernel.clear(), and moa.clusterers.clustree.Entry.data.
Referenced by moa.clusterers.clustree.Node.clear().
{
        this.buffer.clear();
        this.data.clear();
    }
Member Data Documentation
ClusKernel moa.clusterers.clustree.Entry.buffer [private]
The buffer of this entry.
It can also be seen as the buffer of the child node, it is here just to simplify the insertion recuersion.
Definition at line 32 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Entry.emptyBuffer(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.getBuffer(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.Entry.makeOlder(), moa.clusterers.clustree.Entry.mergeWith(), and moa.clusterers.clustree.Entry.shallowClear().
Node moa.clusterers.clustree.Entry.child [private]
A reference to the next node in the tree.
null if we are at a leaf, or this is an entry is part of a lying Node.
Definition at line 37 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.getChild(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.Entry.mergeWith(), and moa.clusterers.clustree.Entry.overwriteOldEntry().
ClusKernel moa.clusterers.clustree.Entry.data
The actual entry data.
Definition at line 27 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.add(), moa.clusterers.clustree.Entry.aggregateEntry(), moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.getData(), moa.clusterers.outliers.AnyOut.AnyOutCore.improveObjectOnce(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.outliers.AnyOut.AnyOutCore.initObject(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.Entry.makeOlder(), moa.clusterers.clustree.Entry.mergeWith(), moa.clusterers.clustree.Entry.overwriteOldEntry(), and moa.clusterers.clustree.Entry.shallowClear().
final long moa.clusterers.clustree.Entry.defaultTimestamp = 0 [static, private]
The timestamp to be used when no operation has yet been done on this entry.
See also:
timestamp
Definition at line 55 of file Entry.java.
Node moa.clusterers.clustree.Entry.node [private]
A reference to the Node, that contains this Entry.
Definition at line 45 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.Entry(), and moa.clusterers.clustree.Entry.getNode().
Entry moa.clusterers.clustree.Entry.parentEntry [private]
A reference to the Entry's parent Entry.
Definition at line 41 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.getParentEntry(), moa.clusterers.clustree.Entry.overwriteOldEntry(), and moa.clusterers.clustree.Entry.setParentEntry().
long moa.clusterers.clustree.Entry.timestamp [private]
Last time this entry was changed.
Definition at line 49 of file Entry.java.
Referenced by moa.clusterers.clustree.Entry.aggregateCluster(), moa.clusterers.clustree.Entry.aggregateEntry(), moa.clusterers.clustree.Entry.aggregateToBuffer(), moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Entry.emptyBuffer(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.getTimestamp(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.Entry.makeOlder(), and moa.clusterers.clustree.Entry.mergeWith().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustree/Entry.java