MOA: moa.classifiers.meta.AccuracyUpdatedEnsemble Class Reference
moa.classifiers.meta.AccuracyUpdatedEnsemble Class Reference
The revised version of the Accuracy Updated Ensemble as proposed by Brzezinski and Stefanowski in "Reacting to Different Types of Concept Drift: The Accuracy Updated Ensemble Algorithm", IEEE Trans.
Public Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
boolean isRandomizable ()
Determines whether the classifier is randomizable.
double[] getVotesForInstance (Instance inst)
Predicts a class for an example.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption learnerOption
Type of classifier to use as a component classifier.
IntOption memberCountOption
Number of component classifiers.
IntOption chunkSizeOption
Chunk size.
IntOption maxByteSizeOption
Determines the maximum size of model (evaluated after every chunk).
Protected Member Functions
void processChunk ()
Processes a chunk of instances.
void enforceMemoryLimit ()
Checks if the memory limit is exceeded and if so prunes the classifiers in the ensemble.
double computeMseR ()
Computes the MSEr threshold.
double computeMse (Classifier learner, Instances chunk)
Computes the MSE of a learner for a given chunk of examples.
Measurement[] getModelMeasurementsImpl ()
Adds ensemble weights to the measurements.
Classifier addToStored (Classifier newClassifier, double newClassifiersWeight)
Adds a classifier to the storage.
Protected Attributes
double[][] weights
The weights of stored classifiers.
long[] classDistributions
Class distributions.
Classifier[] learners
Ensemble classifiers.
int processedInstances
Number of processed examples.
Classifier candidate
Candidate classifier.
Instances currentChunk
Current chunk of instances.
Private Member Functions
int getPoorestClassifierIndex ()
Finds the index of the classifier with the smallest weight.
void initVariables ()
Initiates the current chunk and class distribution variables.
void trainOnChunk (Classifier classifierToTrain)
Trains a component classifier on the most recent chunk of data.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The revised version of the Accuracy Updated Ensemble as proposed by Brzezinski and Stefanowski in "Reacting to Different Types of Concept Drift: The Accuracy Updated Ensemble Algorithm", IEEE Trans.
Neural Netw, 2013.
Definition at line 39 of file AccuracyUpdatedEnsemble.java.
Member Function Documentation
Classifier moa.classifiers.meta.AccuracyUpdatedEnsemble.addToStored (Classifier newClassifier, double newClassifiersWeight) [protected]
Adds a classifier to the storage.
Parameters:
newClassifier The classifier to add.
newClassifiersWeight The new classifiers weight.
Definition at line 308 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learners, and moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        Classifier addedClassifier = null;
        Classifier[] newStored = new Classifier[this.learners.length + 1];
        double[][] newStoredWeights = new double[newStored.length][2];
        for (int i = 0; i < newStored.length; i++) {
            if (i < this.learners.length) {
                newStored[i] = this.learners[i];
                newStoredWeights[i][0] = this.weights[i][0];
                newStoredWeights[i][1] = this.weights[i][1];
            } else {
                newStored[i] = addedClassifier = newClassifier.copy();
                newStoredWeights[i][0] = newClassifiersWeight;
                newStoredWeights[i][1] = i;
            }
        }
        this.learners = newStored;
        this.weights = newStoredWeights;
        return addedClassifier;
    }
double moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMse (Classifier learner, Instances chunk) [protected]
Computes the MSE of a learner for a given chunk of examples.
Parameters:
learner classifier to compute error
chunk chunk of examples
Returns:
the computed error.
Definition at line 250 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.chunkSizeOption, moa.options.IntOption.getValue(), and moa.classifiers.Classifier.getVotesForInstance().
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        double mse_i = 0;
        double f_ci;
        double voteSum;
        for (int i = 0; i < chunk.numInstances(); i++) {
            try {
                voteSum = 0;
                for (double element : learner.getVotesForInstance(chunk.instance(i))) {
                    voteSum += element;
                }
                if (voteSum > 0) {
                    f_ci = learner.getVotesForInstance(chunk.instance(i))[(int) chunk.instance(i).classValue()]
                            / voteSum;
                    mse_i += (1 - f_ci) * (1 - f_ci);
                } else {
                    mse_i += 1;
                }
            } catch (Exception e) {
                mse_i += 1;
            }
        }
        mse_i /= this.chunkSizeOption.getValue();
        return mse_i;
    }
double moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMseR () [protected]
Computes the MSEr threshold.
Returns:
The MSEr threshold.
Definition at line 232 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.chunkSizeOption, moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions, and moa.options.IntOption.getValue().
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        double p_c;
        double mse_r = 0;
        for (int i = 0; i < this.classDistributions.length; i++) {
            p_c = (double) this.classDistributions[i] / (double) this.chunkSizeOption.getValue();
            mse_r += p_c * ((1 - p_c) * (1 - p_c));
        }
        return mse_r;
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit () [protected]
Checks if the memory limit is exceeded and if so prunes the classifiers in the ensemble.
Definition at line 217 of file AccuracyUpdatedEnsemble.java.
References moa.options.IntOption.getValue(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learners, moa.classifiers.meta.AccuracyUpdatedEnsemble.maxByteSizeOption, moa.options.IntOption.setValue(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        double memoryLimit = this.maxByteSizeOption.getValue() / (double) (this.learners.length + 1);
        for (int i = 0; i < this.learners.length; i++) {
            ((HoeffdingTree) this.learners[(int) this.weights[i][1]]).maxByteSizeOption.setValue((int) Math
                    .round(memoryLimit));
            ((HoeffdingTree) this.learners[(int) this.weights[i][1]]).enforceTrackerLimit();
        }
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 164 of file AccuracyUpdatedEnsemble.java.
{
    }
Measurement [] moa.classifiers.meta.AccuracyUpdatedEnsemble.getModelMeasurementsImpl () [protected, virtual]
Adds ensemble weights to the measurements.
Implements moa.classifiers.AbstractClassifier.
Definition at line 284 of file AccuracyUpdatedEnsemble.java.
References moa.options.IntOption.getValue(), moa.classifiers.meta.AccuracyUpdatedEnsemble.memberCountOption, and moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
{
        Measurement[] measurements = new Measurement[(int) this.memberCountOption.getValue()];
        for (int m = 0; m < this.memberCountOption.getValue(); m++) {
            measurements[m] = new Measurement("Member weight " + (m + 1), -1);
        }
        if (this.weights != null) {
            for (int i = 0; i < this.weights.length; i++) {
                measurements[i] = new Measurement("Member weight " + (i + 1), this.weights[i][0]);
            }
        }
        return measurements;
    }
int moa.classifiers.meta.AccuracyUpdatedEnsemble.getPoorestClassifierIndex () [private]
Finds the index of the classifier with the smallest weight.
Returns:
Definition at line 334 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        int minIndex = 0;
        for (int i = 1; i < this.weights.length; i++) {
            if(this.weights[i][0] < this.weights[minIndex][0]){
                minIndex = i;
            }
        }
        return minIndex;
    }
Classifier [] moa.classifiers.meta.AccuracyUpdatedEnsemble.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 168 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.learners.
{
        return this.learners.clone();
    }
double [] moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance (Instance inst)
Predicts a class for an example.
Implements moa.classifiers.Classifier.
Definition at line 141 of file AccuracyUpdatedEnsemble.java.
References moa.core.DoubleVector.addValues(), moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learners, moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.sumOfValues(), moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
{
        DoubleVector combinedVote = new DoubleVector();
        if (this.trainingWeightSeenByModel > 0.0) {
            for (int i = 0; i < this.learners.length; i++) {
                if (this.weights[i][0] > 0.0) {
                    DoubleVector vote = new DoubleVector(this.learners[(int) this.weights[i][1]].getVotesForInstance(inst));
                    if (vote.sumOfValues() > 0.0) {
                        vote.normalize();
                        // scale weight and prevent overflow
                        vote.scaleValues(this.weights[i][0] / (1.0 * this.learners.length + 1.0));
                        combinedVote.addValues(vote);
                    }
                }
            }
        }
        //combinedVote.normalize();
        return combinedVote.getArrayRef();
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.initVariables () [private]
Initiates the current chunk and class distribution variables.
Definition at line 349 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk, and moa.classifiers.AbstractClassifier.getModelContext().
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        if (this.currentChunk == null) {
            this.currentChunk = new Instances(this.getModelContext());
        }
        if (this.classDistributions == null) {
            this.classDistributions = new long[this.getModelContext().classAttribute().numValues()];
            for (int i = 0; i < this.classDistributions.length; i++) {
                this.classDistributions[i] = 0;
            }
        }
    }
boolean moa.classifiers.meta.AccuracyUpdatedEnsemble.isRandomizable ()
Determines whether the classifier is randomizable.
Implements moa.classifiers.Classifier.
Definition at line 134 of file AccuracyUpdatedEnsemble.java.
{
        return false;
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 100 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.candidate, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learnerOption, and moa.classifiers.Classifier.resetLearning().
{
        this.candidate = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidate.resetLearning();
        super.prepareForUseImpl(monitor, repository);
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk () [protected]
Processes a chunk of instances.
This method is called after collecting a chunk of examples.
Definition at line 176 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.AccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMse(), moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.Classifier.copy(), moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk, moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getPoorestClassifierIndex(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learnerOption, moa.classifiers.meta.AccuracyUpdatedEnsemble.learners, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        Classifier addedClassifier = null;
        double mse_r = this.computeMseR();
        // Compute weights
        double candidateClassifierWeight = 1.0 / (mse_r + Double.MIN_VALUE);
        for (int i = 0; i < this.learners.length; i++) {
            this.weights[i][0] = 1.0 / (mse_r + this.computeMse(this.learners[(int) this.weights[i][1]], this.currentChunk) + Double.MIN_VALUE);
        }
        if (this.learners.length < this.memberCountOption.getValue()) {
            // Train and add classifier
            addedClassifier = this.addToStored(this.candidate, candidateClassifierWeight);
        } else {
            // Substitute poorest classifier
            int poorestClassifier = this.getPoorestClassifierIndex();
            if (this.weights[poorestClassifier][0] < candidateClassifierWeight) {
                this.weights[poorestClassifier][0] = candidateClassifierWeight;
                addedClassifier = this.candidate.copy();
                this.learners[(int) this.weights[poorestClassifier][1]] = addedClassifier;
            }
        }
        // train classifiers
        for (int i = 0; i < this.learners.length; i++) {
            this.trainOnChunk(this.learners[(int) this.weights[i][1]]);
        }
        this.classDistributions = null;
        this.currentChunk = null;
        this.candidate = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidate.resetLearning();
        this.enforceMemoryLimit();
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 108 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.meta.AccuracyUpdatedEnsemble.learnerOption, moa.classifiers.meta.AccuracyUpdatedEnsemble.learners, moa.classifiers.meta.AccuracyUpdatedEnsemble.processedInstances, and moa.classifiers.Classifier.resetLearning().
{
        this.currentChunk = null;
        this.classDistributions = null;
        this.processedInstances = 0;
        this.learners = new Classifier[0];
        this.candidate = (Classifier) getPreparedClassOption(this.learnerOption);
        this.candidate.resetLearning();
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk (Classifier classifierToTrain) [private]
Trains a component classifier on the most recent chunk of data.
Parameters:
classifierToTrain Classifier being trained.
Definition at line 369 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.chunkSizeOption, moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk, moa.options.IntOption.getValue(), and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
{
        for (int num = 0; num < this.chunkSizeOption.getValue(); num++) {
            classifierToTrain.trainOnInstance(this.currentChunk.instance(num));
        }
    }
void moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 119 of file AccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.AccuracyUpdatedEnsemble.chunkSizeOption, moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk, moa.options.IntOption.getValue(), moa.classifiers.meta.AccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.processedInstances.
{
        this.initVariables();
        this.classDistributions[(int) inst.classValue()]++;
        this.currentChunk.add(inst);
        this.processedInstances++;
        if (this.processedInstances % this.chunkSizeOption.getValue() == 0) {
            this.processChunk();
        }
    }
Member Data Documentation
Classifier moa.classifiers.meta.AccuracyUpdatedEnsemble.candidate [protected]
Candidate classifier.
Definition at line 92 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl().
IntOption moa.classifiers.meta.AccuracyUpdatedEnsemble.chunkSizeOption
Initial value:
 new IntOption("chunkSize", 'c',
            "The chunk size used for classifier creation and evaluation.", 500, 1, Integer.MAX_VALUE)
Chunk size.
Definition at line 58 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMse(), moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
long [] moa.classifiers.meta.AccuracyUpdatedEnsemble.classDistributions [protected]
Class distributions.
Definition at line 77 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.AccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
Instances moa.classifiers.meta.AccuracyUpdatedEnsemble.currentChunk [protected]
Current chunk of instances.
Definition at line 97 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.AccuracyUpdatedEnsemble.learnerOption
Initial value:
 new ClassOption("learner", 'l', "Classifier to train.", Classifier.class,
            "trees.HoeffdingTree -e 2000000 -g 100 -c 0.01")
Type of classifier to use as a component classifier.
Definition at line 46 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl().
Classifier [] moa.classifiers.meta.AccuracyUpdatedEnsemble.learners [protected]
Ensemble classifiers.
Definition at line 82 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getSubClassifiers(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl().
IntOption moa.classifiers.meta.AccuracyUpdatedEnsemble.maxByteSizeOption
Initial value:
 new IntOption("maxByteSize", 'm', "Maximum memory consumed by ensemble.",
            33554432, 0, Integer.MAX_VALUE)
Determines the maximum size of model (evaluated after every chunk).
Definition at line 64 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit().
IntOption moa.classifiers.meta.AccuracyUpdatedEnsemble.memberCountOption
Initial value:
 new IntOption("memberCount", 'n',
            "The maximum number of classifiers in an ensemble.", 10, 1, Integer.MAX_VALUE)
Number of component classifiers.
Definition at line 52 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.getModelMeasurementsImpl().
int moa.classifiers.meta.AccuracyUpdatedEnsemble.processedInstances [protected]
Number of processed examples.
Definition at line 87 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl().
final long moa.classifiers.meta.AccuracyUpdatedEnsemble.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 41 of file AccuracyUpdatedEnsemble.java.
double [][] moa.classifiers.meta.AccuracyUpdatedEnsemble.weights [protected]
The weights of stored classifiers.
weights[x][0] = weight weights[x][1] = classifier number in learners
Definition at line 72 of file AccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getModelMeasurementsImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getPoorestClassifierIndex(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/AccuracyUpdatedEnsemble.java