MOA: moa.gui.LineGraphViewPanel.PlotLine Class Reference
moa.gui.LineGraphViewPanel.PlotLine Class Reference
Public Member Functions
float convertX (double x)
float convertY (double y)
Shape getShapeToPlot ()
Public Attributes
LearningCurve curve
Color colour
int xAxisIndex
int yAxisIndex
double xMin
double xMax
double yMin
double yMax
Detailed Description
Definition at line 48 of file LineGraphViewPanel.java.
Member Function Documentation
float moa.gui.LineGraphViewPanel.PlotLine.convertX (double x)
Definition at line 66 of file LineGraphViewPanel.java.
References moa.gui.LineGraphViewPanel.PlotLine.xMax, and moa.gui.LineGraphViewPanel.PlotLine.xMin.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot().
{
            return (float) ((x - this.xMin) / (this.xMax - this.xMin));
        }
float moa.gui.LineGraphViewPanel.PlotLine.convertY (double y)
Definition at line 70 of file LineGraphViewPanel.java.
References moa.gui.LineGraphViewPanel.PlotLine.yMax, and moa.gui.LineGraphViewPanel.PlotLine.yMin.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot().
{
            return (float) ((y - this.yMin) / (this.yMax - this.yMin));
        }
Shape moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot ()
Definition at line 74 of file LineGraphViewPanel.java.
References moa.gui.LineGraphViewPanel.PlotLine.convertX(), moa.gui.LineGraphViewPanel.PlotLine.convertY(), moa.gui.LineGraphViewPanel.PlotLine.curve, moa.evaluation.LearningCurve.getMeasurement(), and moa.evaluation.LearningCurve.numEntries().
Referenced by moa.gui.LineGraphViewPanel.PlotPanel.paint().
{
            GeneralPath path = new GeneralPath();
            if (this.curve.numEntries() > 0) {
                path.moveTo(convertX(this.curve.getMeasurement(0,
                        this.xAxisIndex)), convertY(this.curve.getMeasurement(
                        0, this.yAxisIndex)));
                for (int i = 1; i < this.curve.numEntries(); i++) {
                    path.lineTo(convertX(this.curve.getMeasurement(i,
                            this.xAxisIndex)), convertY(this.curve.getMeasurement(i, this.yAxisIndex)));
                }
            }
            return path;
        }
Member Data Documentation
Color moa.gui.LineGraphViewPanel.PlotLine.colour
Definition at line 52 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt(), and moa.gui.LineGraphViewPanel.PlotPanel.paint().
LearningCurve moa.gui.LineGraphViewPanel.PlotLine.curve
Definition at line 50 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.getShapeToPlot(), and moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
int moa.gui.LineGraphViewPanel.PlotLine.xAxisIndex
Definition at line 54 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
double moa.gui.LineGraphViewPanel.PlotLine.xMax
Definition at line 60 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.convertX(), and moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
double moa.gui.LineGraphViewPanel.PlotLine.xMin
Definition at line 58 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.convertX(), and moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
int moa.gui.LineGraphViewPanel.PlotLine.yAxisIndex
Definition at line 56 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
double moa.gui.LineGraphViewPanel.PlotLine.yMax
Definition at line 64 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.convertY(), and moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
double moa.gui.LineGraphViewPanel.PlotLine.yMin
Definition at line 62 of file LineGraphViewPanel.java.
Referenced by moa.gui.LineGraphViewPanel.PlotLine.convertY(), and moa.gui.LineGraphViewPanel.PlotTableModel.getValueAt().
The documentation for this class was generated from the following file:
main/java/moa/gui/LineGraphViewPanel.java