MOA: moa.streams.generators.RandomTreeGenerator Class Reference
moa.streams.generators.RandomTreeGenerator Class Reference
Stream generator for a stream based on a randomly generated tree.
Classes
class Node
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean isRestartable ()
Gets whether this stream can restart.
void restart ()
Restarts this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
Instance nextInstance ()
Gets the next instance from this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption treeRandomSeedOption
IntOption instanceRandomSeedOption
IntOption numClassesOption
IntOption numNominalsOption
IntOption numNumericsOption
IntOption numValsPerNominalOption
IntOption maxTreeDepthOption
IntOption firstLeafLevelOption
FloatOption leafFractionOption
Protected Member Functions
int classifyInstance (Node node, double[] attVals)
void generateHeader ()
void generateRandomTree ()
Node generateRandomTreeNode (int currentDepth, ArrayList< Integer > nominalAttCandidates, double[] minNumericVals, double[] maxNumericVals, Random treeRand)
Protected Attributes
Node treeRoot
InstancesHeader streamHeader
Random instanceRandom
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for a stream based on a randomly generated tree.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 46 of file RandomTreeGenerator.java.
Member Function Documentation
int moa.streams.generators.RandomTreeGenerator.classifyInstance (Node node, double[] attVals) [protected]
Definition at line 162 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.Node.children, moa.streams.generators.RandomTreeGenerator.Node.classLabel, moa.streams.generators.RandomTreeGenerator.Node.splitAttIndex, and moa.streams.generators.RandomTreeGenerator.Node.splitAttValue.
Referenced by moa.streams.generators.RandomTreeGenerator.nextInstance().
{
        if (node.children == null) {
            return node.classLabel;
        }
        if (node.splitAttIndex < this.numNominalsOption.getValue()) {
            return classifyInstance(
                    node.children[(int) attVals[node.splitAttIndex]], attVals);
        }
        return classifyInstance(
                node.children[attVals[node.splitAttIndex] < node.splitAttValue ? 0
                : 1], attVals);
    }
long moa.streams.generators.RandomTreeGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 122 of file RandomTreeGenerator.java.
{
        return -1;
    }
void moa.streams.generators.RandomTreeGenerator.generateHeader () [protected]
Definition at line 175 of file RandomTreeGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.IntOption.getValue(), moa.streams.generators.RandomTreeGenerator.numClassesOption, moa.streams.generators.RandomTreeGenerator.numNominalsOption, moa.streams.generators.RandomTreeGenerator.numNumericsOption, moa.streams.generators.RandomTreeGenerator.numValsPerNominalOption, and moa.streams.generators.RandomTreeGenerator.streamHeader.
Referenced by moa.streams.generators.RandomTreeGenerator.prepareForUseImpl().
{
        FastVector attributes = new FastVector();
        FastVector nominalAttVals = new FastVector();
        for (int i = 0; i < this.numValsPerNominalOption.getValue(); i++) {
            nominalAttVals.addElement("value" + (i + 1));
        }
        for (int i = 0; i < this.numNominalsOption.getValue(); i++) {
            attributes.addElement(new Attribute("nominal" + (i + 1),
                    nominalAttVals));
        }
        for (int i = 0; i < this.numNumericsOption.getValue(); i++) {
            attributes.addElement(new Attribute("numeric" + (i + 1)));
        }
        FastVector classLabels = new FastVector();
        for (int i = 0; i < this.numClassesOption.getValue(); i++) {
            classLabels.addElement("class" + (i + 1));
        }
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
    }
void moa.streams.generators.RandomTreeGenerator.generateRandomTree () [protected]
Definition at line 198 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), moa.options.IntOption.getValue(), moa.streams.generators.RandomTreeGenerator.numNominalsOption, moa.streams.generators.RandomTreeGenerator.numNumericsOption, moa.streams.generators.RandomTreeGenerator.treeRandomSeedOption, and moa.streams.generators.RandomTreeGenerator.treeRoot.
Referenced by moa.streams.generators.RandomTreeGenerator.prepareForUseImpl().
{
        Random treeRand = new Random(this.treeRandomSeedOption.getValue());
        ArrayList<Integer> nominalAttCandidates = new ArrayList<Integer>(
                this.numNominalsOption.getValue());
        for (int i = 0; i < this.numNominalsOption.getValue(); i++) {
            nominalAttCandidates.add(i);
        }
        double[] minNumericVals = new double[this.numNumericsOption.getValue()];
        double[] maxNumericVals = new double[this.numNumericsOption.getValue()];
        for (int i = 0; i < this.numNumericsOption.getValue(); i++) {
            minNumericVals[i] = 0.0;
            maxNumericVals[i] = 1.0;
        }
        this.treeRoot = generateRandomTreeNode(0, nominalAttCandidates,
                minNumericVals, maxNumericVals, treeRand);
    }
Node moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode (int currentDepth, ArrayList< Integer > nominalAttCandidates, double[] minNumericVals, double[] maxNumericVals, Random treeRand) [protected]
Definition at line 215 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.Node.children, moa.streams.generators.RandomTreeGenerator.Node.classLabel, moa.streams.generators.RandomTreeGenerator.firstLeafLevelOption, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.generators.RandomTreeGenerator.leafFractionOption, moa.streams.generators.RandomTreeGenerator.maxTreeDepthOption, moa.streams.generators.RandomTreeGenerator.numClassesOption, moa.streams.generators.RandomTreeGenerator.numNominalsOption, moa.streams.generators.RandomTreeGenerator.numNumericsOption, moa.streams.generators.RandomTreeGenerator.numValsPerNominalOption, moa.streams.generators.RandomTreeGenerator.Node.splitAttIndex, and moa.streams.generators.RandomTreeGenerator.Node.splitAttValue.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTree().
{
        if ((currentDepth >= this.maxTreeDepthOption.getValue())
                || ((currentDepth >= this.firstLeafLevelOption.getValue()) && (this.leafFractionOption.getValue() >= (1.0 - treeRand.nextDouble())))) {
            Node leaf = new Node();
            leaf.classLabel = treeRand.nextInt(this.numClassesOption.getValue());
            return leaf;
        }
        Node node = new Node();
        int chosenAtt = treeRand.nextInt(nominalAttCandidates.size()
                + this.numNumericsOption.getValue());
        if (chosenAtt < nominalAttCandidates.size()) {
            node.splitAttIndex = nominalAttCandidates.get(chosenAtt);
            node.children = new Node[this.numValsPerNominalOption.getValue()];
            ArrayList<Integer> newNominalCandidates = new ArrayList<Integer>(
                    nominalAttCandidates);
            newNominalCandidates.remove(new Integer(node.splitAttIndex));
            newNominalCandidates.trimToSize();
            for (int i = 0; i < node.children.length; i++) {
                node.children[i] = generateRandomTreeNode(currentDepth + 1,
                        newNominalCandidates, minNumericVals, maxNumericVals,
                        treeRand);
            }
        } else {
            int numericIndex = chosenAtt - nominalAttCandidates.size();
            node.splitAttIndex = this.numNominalsOption.getValue()
                    + numericIndex;
            double minVal = minNumericVals[numericIndex];
            double maxVal = maxNumericVals[numericIndex];
            node.splitAttValue = ((maxVal - minVal) * treeRand.nextDouble())
                    + minVal;
            node.children = new Node[2];
            double[] newMaxVals = maxNumericVals.clone();
            newMaxVals[numericIndex] = node.splitAttValue;
            node.children[0] = generateRandomTreeNode(currentDepth + 1,
                    nominalAttCandidates, minNumericVals, newMaxVals, treeRand);
            double[] newMinVals = minNumericVals.clone();
            newMinVals[numericIndex] = node.splitAttValue;
            node.children[1] = generateRandomTreeNode(currentDepth + 1,
                    nominalAttCandidates, newMinVals, maxNumericVals, treeRand);
        }
        return node;
    }
void moa.streams.generators.RandomTreeGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 261 of file RandomTreeGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.RandomTreeGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 137 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.streamHeader.
Referenced by moa.streams.generators.RandomTreeGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.RandomTreeGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 50 of file RandomTreeGenerator.java.
{
        return "Generates a stream based on a randomly generated tree.";
    }
boolean moa.streams.generators.RandomTreeGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 142 of file RandomTreeGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.RandomTreeGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 127 of file RandomTreeGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.RandomTreeGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 147 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.classifyInstance(), moa.streams.generators.RandomTreeGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.RandomTreeGenerator.instanceRandom, moa.streams.generators.RandomTreeGenerator.numNominalsOption, moa.streams.generators.RandomTreeGenerator.numNumericsOption, moa.streams.generators.RandomTreeGenerator.numValsPerNominalOption, and moa.streams.generators.RandomTreeGenerator.treeRoot.
{
        double[] attVals = new double[this.numNominalsOption.getValue()
                + this.numNumericsOption.getValue()];
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        for (int i = 0; i < attVals.length; i++) {
            attVals[i] = i < this.numNominalsOption.getValue() ? this.instanceRandom.nextInt(this.numValsPerNominalOption.getValue())
                    : this.instanceRandom.nextDouble();
            inst.setValue(i, attVals[i]);
        }
        inst.setDataset(header);
        inst.setClassValue(classifyInstance(this.treeRoot, attVals));
        return inst;
    }
void moa.streams.generators.RandomTreeGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 113 of file RandomTreeGenerator.java.
References moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTree(), moa.streams.generators.RandomTreeGenerator.restart(), and moa.tasks.TaskMonitor.setCurrentActivity().
{
        monitor.setCurrentActivity("Preparing random tree...", -1.0);
        generateHeader();
        generateRandomTree();
        restart();
    }
void moa.streams.generators.RandomTreeGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 132 of file RandomTreeGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.RandomTreeGenerator.instanceRandom, and moa.streams.generators.RandomTreeGenerator.instanceRandomSeedOption.
Referenced by moa.streams.generators.RandomTreeGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
    }
Member Data Documentation
IntOption moa.streams.generators.RandomTreeGenerator.firstLeafLevelOption
Initial value:
 new IntOption(
            "firstLeafLevel",
            'l',
            "The first level of the tree above maxTreeDepth that can have leaves.",
            3, 0, Integer.MAX_VALUE)
Definition at line 82 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode().
Random moa.streams.generators.RandomTreeGenerator.instanceRandom [protected]
Definition at line 110 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.nextInstance(), and moa.streams.generators.RandomTreeGenerator.restart().
IntOption moa.streams.generators.RandomTreeGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 59 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.restart().
FloatOption moa.streams.generators.RandomTreeGenerator.leafFractionOption
Initial value:
 new FloatOption("leafFraction",
            'f',
            "The fraction of leaves per level from firstLeafLevel onwards.",
            0.15, 0.0, 1.0)
Definition at line 88 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode().
IntOption moa.streams.generators.RandomTreeGenerator.maxTreeDepthOption
Initial value:
 new IntOption("maxTreeDepth", 'd',
            "The maximum depth of the tree concept.", 5, 0, Integer.MAX_VALUE)
Definition at line 79 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode().
IntOption moa.streams.generators.RandomTreeGenerator.numClassesOption
Initial value:
 new IntOption("numClasses", 'c',
            "The number of classes to generate.", 2, 2, Integer.MAX_VALUE)
Definition at line 63 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateHeader(), and moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode().
IntOption moa.streams.generators.RandomTreeGenerator.numNominalsOption
Initial value:
 new IntOption("numNominals", 'o',
            "The number of nominal attributes to generate.", 5, 0,
            Integer.MAX_VALUE)
Definition at line 66 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTree(), moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), and moa.streams.generators.RandomTreeGenerator.nextInstance().
IntOption moa.streams.generators.RandomTreeGenerator.numNumericsOption
Initial value:
 new IntOption("numNumerics", 'u',
            "The number of numeric attributes to generate.", 5, 0,
            Integer.MAX_VALUE)
Definition at line 70 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTree(), moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), and moa.streams.generators.RandomTreeGenerator.nextInstance().
IntOption moa.streams.generators.RandomTreeGenerator.numValsPerNominalOption
Initial value:
 new IntOption(
            "numValsPerNominal", 'v',
            "The number of values to generate per nominal attribute.", 5, 2,
            Integer.MAX_VALUE)
Definition at line 74 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), and moa.streams.generators.RandomTreeGenerator.nextInstance().
final long moa.streams.generators.RandomTreeGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 54 of file RandomTreeGenerator.java.
InstancesHeader moa.streams.generators.RandomTreeGenerator.streamHeader [protected]
Definition at line 108 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateHeader(), and moa.streams.generators.RandomTreeGenerator.getHeader().
IntOption moa.streams.generators.RandomTreeGenerator.treeRandomSeedOption
Initial value:
 new IntOption("treeRandomSeed",
            'r', "Seed for random generation of tree.", 1)
Definition at line 56 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTree().
Node moa.streams.generators.RandomTreeGenerator.treeRoot [protected]
Definition at line 106 of file RandomTreeGenerator.java.
Referenced by moa.streams.generators.RandomTreeGenerator.generateRandomTree(), and moa.streams.generators.RandomTreeGenerator.nextInstance().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/RandomTreeGenerator.java