MOA: weka.datagenerators.classifiers.classification.MOA Class Reference
weka.datagenerators.classifiers.classification.MOA Class Reference
A wrapper around MOA instance streams.
Public Member Functions
String globalInfo ()
Returns a string describing this data generator.
Enumeration listOptions ()
Returns an enumeration describing the available options.
void setOptions (String[] options) throws Exception
Parses a list of options for this object.
String[] getOptions ()
Gets the current settings of the datagenerator.
void setGenerator (ClassOption value)
Sets the MOA stream generator to use.
ClassOption getGenerator ()
Returns the current MOA stream generator in use.
String generatorTipText ()
Returns the tooltip displayed in the GUI.
boolean getSingleModeFlag () throws Exception
Return if single mode is set for the given data generator mode depends on option setting and or generator type.
Instances defineDataFormat () throws Exception
Initializes the format for the dataset produced.
Instance generateExample () throws Exception
Generates one example of the dataset.
Instances generateExamples () throws Exception
Generates all examples of the dataset.
String generateStart ()
Generates a comment string that documentates the data generator.
String generateFinished () throws Exception
Generates a comment string that documentats the data generator.
String getRevision ()
Returns the revision string.
Static Public Member Functions
static void main (String[] args)
Main method for executing this class.
Protected Attributes
InstanceStream m_ActualGenerator = new LEDGenerator()
the actual data generator.
ClassOption m_Generator = new ClassOption("InstanceStream", 'B', "The MOA instance stream generator to use from within WEKA.", InstanceStream.class, m_ActualGenerator.getClass().getName())
for manipulating the generator through the GUI.
Static Private Attributes
static final long serialVersionUID = 13533833825026962L
for serialization.
Detailed Description
A wrapper around MOA instance streams.
Valid options are:
 -h
  Prints this help.
 -o <file>
  The name of the output file, otherwise the generated data is
  printed to stdout.
 -r <name>
  The name of the relation.
 -d
  Whether to print debug informations.
 -S
  The seed for random function (default 1)
 -n <num>
  The number of examples to generate (default 100)
 -B <classname + options>
  The MOA stream generator.
  (default: moa.streams.generators.LEDGenerator)
Author:
FracPete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 79 of file MOA.java.
Member Function Documentation
Instances weka.datagenerators.classifiers.classification.MOA.defineDataFormat () throws Exception
Initializes the format for the dataset produced.
Returns:
the format for the dataset
Exceptions:
Exception if the generating of the format failed
Definition at line 233 of file MOA.java.
References moa.streams.InstanceStream.estimatedRemainingInstances(), moa.streams.InstanceStream.getHeader(), weka.datagenerators.classifiers.classification.MOA.m_ActualGenerator, and weka.datagenerators.classifiers.classification.MOA.m_Generator.
{
    int     numExamples;
    m_ActualGenerator = (InstanceStream) MOAUtils.fromOption(m_Generator);
    ((AbstractOptionHandler) m_ActualGenerator).prepareForUse();
    m_DatasetFormat = new Instances(m_ActualGenerator.getHeader());
    // determine number of instances to generate
    numExamples = getNumExamples();
    if (m_ActualGenerator.estimatedRemainingInstances() != -1) {
        if (m_ActualGenerator.estimatedRemainingInstances() < numExamples)
            numExamples = (int) m_ActualGenerator.estimatedRemainingInstances();
    }
    setNumExamplesAct(numExamples);
    return m_DatasetFormat;
  }
Instance weka.datagenerators.classifiers.classification.MOA.generateExample () throws Exception
Generates one example of the dataset.
Returns:
the generated example, null if no further example available
Exceptions:
Exception if the format of the dataset is not yet defined
Exception if the generator only works with generateExamples which means in non single mode
Definition at line 259 of file MOA.java.
References moa.streams.InstanceStream.hasMoreInstances(), weka.datagenerators.classifiers.classification.MOA.m_ActualGenerator, and moa.streams.InstanceStream.nextInstance().
Referenced by weka.datagenerators.classifiers.classification.MOA.generateExamples().
{
    if (m_ActualGenerator.hasMoreInstances())
        return m_ActualGenerator.nextInstance();
    else
        return null;
  }
Instances weka.datagenerators.classifiers.classification.MOA.generateExamples () throws Exception
Generates all examples of the dataset.
Re-initializes the random number generator with the given seed, before generating instances.
Returns:
the generated dataset
Exceptions:
Exception if the format of the dataset is not yet defined
Exception if the generator only works with generateExample, which means in single mode
See also:
getSeed()
Definition at line 276 of file MOA.java.
References weka.datagenerators.classifiers.classification.MOA.generateExample().
{
    Instances       result;
    Instance                inst;
    int             i;
    result   = new Instances(m_DatasetFormat, 0);
    m_Random = new Random(getSeed());
    for (i = 0; i < getNumExamplesAct(); i++) {
        inst = generateExample();
        if (inst != null)
            result.add(inst);
        else
            break;
    }
    return result;
  }
String weka.datagenerators.classifiers.classification.MOA.generateFinished () throws Exception
Generates a comment string that documentats the data generator.
By default this string is added at the end of theproduces output as ARFF file type.
Returns:
string contains info about the generated rules
Exceptions:
Exception if the generating of the documentaion fails
Definition at line 314 of file MOA.java.
{
    return "";
  }
String weka.datagenerators.classifiers.classification.MOA.generateStart ()
Generates a comment string that documentates the data generator.
By default this string is added at the beginning of the produced output as ARFF file type, next after the options.
Returns:
string contains info about the generated rules
Definition at line 302 of file MOA.java.
{
    return "";
  }
String weka.datagenerators.classifiers.classification.MOA.generatorTipText ()
Returns the tooltip displayed in the GUI.
Returns:
the tooltip
Definition at line 212 of file MOA.java.
{
    return "The MOA stream generator to use.";
  }
ClassOption weka.datagenerators.classifiers.classification.MOA.getGenerator ()
Returns the current MOA stream generator in use.
Returns:
the stream generator in use
Definition at line 203 of file MOA.java.
References weka.datagenerators.classifiers.classification.MOA.m_Generator.
{
    return m_Generator;
  }
String [] weka.datagenerators.classifiers.classification.MOA.getOptions ()
Gets the current settings of the datagenerator.
Returns:
an array of strings suitable for passing to setOptions
Definition at line 171 of file MOA.java.
References weka.datagenerators.classifiers.classification.MOA.m_ActualGenerator.
{
    Vector<String>  result;
    String[]        options;
    int             i;
    result = new Vector<String>();
    result.add("-B");
    result.add(MOAUtils.toCommandLine(m_ActualGenerator));
    options = super.getOptions();
    for (i = 0; i < options.length; i++)
      result.add(options[i]);
    return result.toArray(new String[result.size()]);
  }
String weka.datagenerators.classifiers.classification.MOA.getRevision ()
Returns the revision string.
Returns:
the revision
Definition at line 323 of file MOA.java.
{
    return RevisionUtils.extract("$Revision$");
  }
boolean weka.datagenerators.classifiers.classification.MOA.getSingleModeFlag () throws Exception
Return if single mode is set for the given data generator mode depends on option setting and or generator type.
Returns:
single mode flag, always true
Exceptions:
Exception if mode is not set yet
Definition at line 223 of file MOA.java.
{
    return true;
  }
String weka.datagenerators.classifiers.classification.MOA.globalInfo ()
Returns a string describing this data generator.
Returns:
a description of the data generator suitable for displaying in the explorer/experimenter gui
Definition at line 97 of file MOA.java.
{
    return "A wrapper around MOA instance streams.";
  }
Enumeration weka.datagenerators.classifiers.classification.MOA.listOptions ()
Returns an enumeration describing the available options.
Returns:
an enumeration of all the available options
Definition at line 106 of file MOA.java.
{
    Vector result = enumToVector(super.listOptions());
    result.add(new Option(
            "\tThe MOA stream generator.\n"
            + "\t(default: " + MOAUtils.toCommandLine(new LEDGenerator()) + ")",
            "B", 1, "-B <classname + options>"));
    return result.elements();
  }
static void weka.datagenerators.classifiers.classification.MOA.main (String[] args) [static]
Main method for executing this class.
Parameters:
args should contain arguments for the data producer:
Definition at line 332 of file MOA.java.
{
    runDataGenerator(new MOA(), args);
  }
void weka.datagenerators.classifiers.classification.MOA.setGenerator (ClassOption value)
Sets the MOA stream generator to use.
Parameters:
value the stream generator to use
Definition at line 193 of file MOA.java.
References weka.datagenerators.classifiers.classification.MOA.m_ActualGenerator, and weka.datagenerators.classifiers.classification.MOA.m_Generator.
Referenced by weka.datagenerators.classifiers.classification.MOA.setOptions().
{
    m_Generator       = value;
    m_ActualGenerator = (InstanceStream) MOAUtils.fromOption(m_Generator);
  }
void weka.datagenerators.classifiers.classification.MOA.setOptions (String[] options) throws Exception
Parses a list of options for this object.
Valid options are:
 -h
  Prints this help.
 -o <file>
  The name of the output file, otherwise the generated data is
  printed to stdout.
 -r <name>
  The name of the relation.
 -d
  Whether to print debug informations.
 -S
  The seed for random function (default 1)
 -n <num>
  The number of examples to generate (default 100)
 -B <classname + options>
  The MOA stream generator.
  (default: moa.streams.generators.LEDGenerator)
Parameters:
options the list of options as an array of strings
Exceptions:
Exception if an option is not supported
Definition at line 151 of file MOA.java.
References moa.options.AbstractOption.copy(), weka.datagenerators.classifiers.classification.MOA.m_Generator, moa.options.AbstractClassOption.setCurrentObject(), and weka.datagenerators.classifiers.classification.MOA.setGenerator().
{
    String                  tmpStr;
    ClassOption                 option;
    tmpStr = Utils.getOption('B', options);
    option = (ClassOption) m_Generator.copy();
    if (tmpStr.length() == 0)
        option.setCurrentObject(new LEDGenerator());
    else
        option.setCurrentObject(MOAUtils.fromCommandLine(m_Generator, tmpStr));
    setGenerator(option);
    super.setOptions(options);
  }
Member Data Documentation
InstanceStream weka.datagenerators.classifiers.classification.MOA.m_ActualGenerator = new LEDGenerator() [protected]
the actual data generator.
Definition at line 86 of file MOA.java.
Referenced by weka.datagenerators.classifiers.classification.MOA.defineDataFormat(), weka.datagenerators.classifiers.classification.MOA.generateExample(), weka.datagenerators.classifiers.classification.MOA.getOptions(), and weka.datagenerators.classifiers.classification.MOA.setGenerator().
ClassOption weka.datagenerators.classifiers.classification.MOA.m_Generator = new ClassOption("InstanceStream", 'B', "The MOA instance stream generator to use from within WEKA.", InstanceStream.class, m_ActualGenerator.getClass().getName()) [protected]
for manipulating the generator through the GUI.
Definition at line 89 of file MOA.java.
Referenced by weka.datagenerators.classifiers.classification.MOA.defineDataFormat(), weka.datagenerators.classifiers.classification.MOA.getGenerator(), weka.datagenerators.classifiers.classification.MOA.setGenerator(), and weka.datagenerators.classifiers.classification.MOA.setOptions().
final long weka.datagenerators.classifiers.classification.MOA.serialVersionUID = 13533833825026962L [static, private]
for serialization.
Definition at line 83 of file MOA.java.
The documentation for this class was generated from the following file:
main/java/weka/datagenerators/classifiers/classification/MOA.java