MOA: moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver Class Reference
moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver Class Reference
Class for observing the class data distribution for a numeric attribute using Greenwald and Khanna methodology.
Public Member Functions
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
double[][] getClassDistsResultingFromBinarySplit (double splitValue)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void observeAttributeTarget (double attVal, double target)
Public Attributes
IntOption numTuplesOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
AutoExpandVector
< GreenwaldKhannaQuantileSummary > attValDistPerClass = new AutoExpandVector<GreenwaldKhannaQuantileSummary>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for observing the class data distribution for a numeric attribute using Greenwald and Khanna methodology.
This observer monitors the class distribution of a given attribute. Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 43 of file GreenwaldKhannaNumericAttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 74 of file GreenwaldKhannaNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.attValDistPerClass, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), and moa.classifiers.core.AttributeSplitSuggestion.merit.
{
        AttributeSplitSuggestion bestSuggestion = null;
        for (GreenwaldKhannaQuantileSummary qs : this.attValDistPerClass) {
            if (qs != null) {
                double[] cutpoints = qs.getSuggestedCutpoints();
                for (double cutpoint : cutpoints) {
                    double[][] postSplitDists = getClassDistsResultingFromBinarySplit(cutpoint);
                    double merit = criterion.getMeritOfSplit(preSplitDist,
                            postSplitDists);
                    if ((bestSuggestion == null)
                            || (merit > bestSuggestion.merit)) {
                        bestSuggestion = new AttributeSplitSuggestion(
                                new NumericAttributeBinaryTest(attIndex,
                                cutpoint, true), postSplitDists, merit);
                    }
                }
            }
        }
        return bestSuggestion;
    }
double [][] moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit (double splitValue)
Definition at line 98 of file GreenwaldKhannaNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.attValDistPerClass, moa.core.DoubleVector.getArrayRef(), moa.core.GreenwaldKhannaQuantileSummary.getCountBelow(), and moa.core.GreenwaldKhannaQuantileSummary.getTotalCount().
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        DoubleVector lhsDist = new DoubleVector();
        DoubleVector rhsDist = new DoubleVector();
        for (int i = 0; i < this.attValDistPerClass.size(); i++) {
            GreenwaldKhannaQuantileSummary estimator = this.attValDistPerClass.get(i);
            if (estimator != null) {
                long countBelow = estimator.getCountBelow(splitValue);
                lhsDist.addToValue(i, countBelow);
                rhsDist.addToValue(i, estimator.getTotalCount() - countBelow);
            }
        }
        return new double[][]{lhsDist.getArrayRef(), rhsDist.getArrayRef()};
    }
void moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 113 of file GreenwaldKhannaNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 53 of file GreenwaldKhannaNumericAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.attValDistPerClass, moa.options.IntOption.getValue(), moa.core.GreenwaldKhannaQuantileSummary.insert(), and moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.numTuplesOption.
{
        if (Utils.isMissingValue(attVal)) {
        } else {
            GreenwaldKhannaQuantileSummary valDist = this.attValDistPerClass.get(classVal);
            if (valDist == null) {
                valDist = new GreenwaldKhannaQuantileSummary(this.numTuplesOption.getValue());
                this.attValDistPerClass.set(classVal, valDist);
            }
            // TODO: not taking weight into account
            valDist.insert(attVal);
        }
    }
void moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 123 of file GreenwaldKhannaNumericAttributeClassObserver.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
void moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 118 of file GreenwaldKhannaNumericAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 67 of file GreenwaldKhannaNumericAttributeClassObserver.java.
{
        // TODO: NaiveBayes broken until implemented
        return 0.0;
    }
Member Data Documentation
AutoExpandVector<GreenwaldKhannaQuantileSummary> moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.attValDistPerClass = new AutoExpandVector<GreenwaldKhannaQuantileSummary>() [protected]
Definition at line 47 of file GreenwaldKhannaNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), and moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeClass().
IntOption moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.numTuplesOption
Initial value:
 new IntOption("numTuples", 'n',
        "The number of tuples.", 10, 1, Integer.MAX_VALUE)
Definition at line 49 of file GreenwaldKhannaNumericAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeClass().
final long moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 45 of file GreenwaldKhannaNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/GreenwaldKhannaNumericAttributeClassObserver.java