MOA: moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode Class Reference
moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode Class Reference
Public Member Functions
int calcByteSize ()
AdaLearningNode (double[] initialClassObservations)
int numberLeaves ()
double getErrorEstimation ()
double getErrorWidth ()
boolean isNullError ()
void killTreeChilds (HoeffdingAdaptiveTree ht)
void learnFromInstance (Instance inst, HoeffdingAdaptiveTree ht, SplitNode parent, int parentBranch)
double[] getClassVotes (Instance inst, HoeffdingTree ht)
void filterInstanceToLeaves (Instance inst, SplitNode splitparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Public Attributes
boolean ErrorChange = false
Protected Attributes
ADWIN estimationErrorWeight
int randomSeed = 1
Random classifierRandom
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 303 of file HoeffdingAdaptiveTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.AdaLearningNode (double[] initialClassObservations)
Definition at line 324 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.classifierRandom, and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.randomSeed.
{
            super(initialClassObservations);
            this.classifierRandom = new Random(this.randomSeed);
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.calcByteSize ()
Definition at line 316 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight, and moa.AbstractMOAObject.measureByteSize().
{
            int byteSize = super.calcByteSize();
            if (estimationErrorWeight != null) {
                byteSize += estimationErrorWeight.measureByteSize();
            }
            return byteSize;
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.filterInstanceToLeaves (Instance inst, SplitNode splitparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 431 of file HoeffdingAdaptiveTree.java.
{
            foundNodes.add(new FoundNode(this, splitparent, parentBranch));
        }
double [] moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getClassVotes (Instance inst, HoeffdingTree ht)
Definition at line 405 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorEstimation().
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance().
{
            double[] dist;
            int predictionOption = ((HoeffdingAdaptiveTree) ht).leafpredictionOption.getChosenIndex();
            if (predictionOption == 0) { //MC
                dist = this.observedClassDistribution.getArrayCopy();
            } else if (predictionOption == 1) { //NB
                dist = NaiveBayes.doNaiveBayesPrediction(inst,
                        this.observedClassDistribution, this.attributeObservers);
            } else { //NBAdaptive
                if (this.mcCorrectWeight > this.nbCorrectWeight) {
                    dist = this.observedClassDistribution.getArrayCopy();
                } else {
                    dist = NaiveBayes.doNaiveBayesPrediction(inst,
                            this.observedClassDistribution, this.attributeObservers);
                }
            }
            //New for option votes
            double distSum = Utils.sum(dist);
            if (distSum * this.getErrorEstimation() * this.getErrorEstimation() > 0.0) {
                Utils.normalize(dist, distSum * this.getErrorEstimation() * this.getErrorEstimation()); //Adding weight
            }
            return dist;
        }
double moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorEstimation ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 335 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight, and moa.classifiers.core.driftdetection.ADWIN.getEstimation().
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getClassVotes(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance().
{
            if (this.estimationErrorWeight != null) {
                return this.estimationErrorWeight.getEstimation();
            } else {
                return 0;
            }
        }
double moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorWidth ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 344 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight, and moa.classifiers.core.driftdetection.ADWIN.getWidth().
{
            return this.estimationErrorWeight.getWidth();
        }
boolean moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.isNullError ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 349 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight.
{
            return (this.estimationErrorWeight == null);
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.killTreeChilds (HoeffdingAdaptiveTree ht)
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 354 of file HoeffdingAdaptiveTree.java.
{
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance (Instance inst, HoeffdingAdaptiveTree ht, SplitNode parent, int parentBranch)
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 358 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.classifierRandom, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.ErrorChange, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getClassVotes(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorEstimation(), moa.options.IntOption.getValue(), moa.classifiers.trees.HoeffdingTree.gracePeriodOption, and moa.classifiers.core.driftdetection.ADWIN.setInput().
{
            int trueClass = (int) inst.classValue();
            //New option vore
            int k = MiscUtils.poisson(1.0, this.classifierRandom);
            Instance weightedInst = (Instance) inst.copy();
            if (k > 0) {
                weightedInst.setWeight(inst.weight() * k);
            }
            //Compute ClassPrediction using filterInstanceToLeaf
            int ClassPrediction = Utils.maxIndex(this.getClassVotes(inst, ht));
            boolean blCorrect = (trueClass == ClassPrediction);
            if (this.estimationErrorWeight == null) {
                this.estimationErrorWeight = new ADWIN();
            }
            double oldError = this.getErrorEstimation();
            this.ErrorChange = this.estimationErrorWeight.setInput(blCorrect == true ? 0.0 : 1.0);
            if (this.ErrorChange == true && oldError > this.getErrorEstimation()) {
                this.ErrorChange = false;
            }
            //Update statistics
            learnFromInstance(weightedInst, ht);    //inst
            //Check for Split condition
            double weightSeen = this.getWeightSeen();
            if (weightSeen
                    - this.getWeightSeenAtLastSplitEvaluation() >= ht.gracePeriodOption.getValue()) {
                ht.attemptToSplit(this, parent,
                        parentBranch);
                this.setWeightSeenAtLastSplitEvaluation(weightSeen);
            }
            //learnFromInstance alternate Tree and Child nodes
            /*if (this.alternateTree != null)  {
            this.alternateTree.learnFromInstance(inst,ht);
            }
            for (Node child : this.children) {
            if (child != null) {
            child.learnFromInstance(inst,ht);
            }
            }*/
        }
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.numberLeaves ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 330 of file HoeffdingAdaptiveTree.java.
{
            return 1;
        }
Member Data Documentation
Random moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.classifierRandom [protected]
Definition at line 313 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.AdaLearningNode(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance().
boolean moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.ErrorChange = false
Definition at line 309 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance().
ADWIN moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.estimationErrorWeight [protected]
Definition at line 307 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.calcByteSize(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorEstimation(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorWidth(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.isNullError(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance().
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.randomSeed = 1 [protected]
Definition at line 311 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.AdaLearningNode().
final long moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.serialVersionUID = 1L [static, private]
Definition at line 305 of file HoeffdingAdaptiveTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingAdaptiveTree.java