MOA: moa.classifiers.meta.WeightedMajorityAlgorithm Class Reference
moa.classifiers.meta.WeightedMajorityAlgorithm Class Reference
Weighted majority algorithm for data streams.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
void discardModel (int index)
Public Attributes
ListOption learnerListOption
FloatOption betaOption
FloatOption gammaOption
FlagOption pruneOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
int removePoorestModelBytes ()
Protected Attributes
Classifier[] ensemble
double[] ensembleWeights
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Weighted majority algorithm for data streams.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 42 of file WeightedMajorityAlgorithm.java.
Member Function Documentation
void moa.classifiers.meta.WeightedMajorityAlgorithm.discardModel (int index)
Definition at line 183 of file WeightedMajorityAlgorithm.java.
{
        Classifier[] newEnsemble = new Classifier[this.ensemble.length - 1];
        double[] newEnsembleWeights = new double[newEnsemble.length];
        int oldPos = 0;
        for (int i = 0; i < newEnsemble.length; i++) {
            if (oldPos == index) {
                oldPos++;
            }
            newEnsemble[i] = this.ensemble[oldPos];
            newEnsembleWeights[i] = this.ensembleWeights[oldPos];
            oldPos++;
        }
        this.ensemble = newEnsemble;
        this.ensembleWeights = newEnsembleWeights;
    }
void moa.classifiers.meta.WeightedMajorityAlgorithm.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 156 of file WeightedMajorityAlgorithm.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.WeightedMajorityAlgorithm.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 161 of file WeightedMajorityAlgorithm.java.
{
        Measurement[] measurements = null;
        if (this.ensembleWeights != null) {
            measurements = new Measurement[this.ensembleWeights.length];
            for (int i = 0; i < this.ensembleWeights.length; i++) {
                measurements[i] = new Measurement("member weight " + (i + 1),
                        this.ensembleWeights[i]);
            }
        }
        return measurements;
    }
String moa.classifiers.meta.WeightedMajorityAlgorithm.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 47 of file WeightedMajorityAlgorithm.java.
{
        return "Weighted majority algorithm for data streams.";
    }
Classifier [] moa.classifiers.meta.WeightedMajorityAlgorithm.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 179 of file WeightedMajorityAlgorithm.java.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 138 of file WeightedMajorityAlgorithm.java.
References moa.core.DoubleVector.addValues(), moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), and moa.core.DoubleVector.sumOfValues().
{
        DoubleVector combinedVote = new DoubleVector();
        if (this.trainingWeightSeenByModel > 0.0) {
            for (int i = 0; i < this.ensemble.length; i++) {
                if (this.ensembleWeights[i] > 0.0) {
                    DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
                    if (vote.sumOfValues() > 0.0) {
                        vote.normalize();
                        vote.scaleValues(this.ensembleWeights[i]);
                        combinedVote.addValues(vote);
                    }
                }
            }
        }
        return combinedVote.getArrayRef();
    }
boolean moa.classifiers.meta.WeightedMajorityAlgorithm.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 174 of file WeightedMajorityAlgorithm.java.
{
        return false;
    }
void moa.classifiers.meta.WeightedMajorityAlgorithm.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 81 of file WeightedMajorityAlgorithm.java.
References moa.tasks.TaskMonitor.setCurrentActivity(), and moa.tasks.TaskMonitor.taskShouldAbort().
{
        Option[] learnerOptions = this.learnerListOption.getList();
        this.ensemble = new Classifier[learnerOptions.length];
        for (int i = 0; i < learnerOptions.length; i++) {
            monitor.setCurrentActivity("Materializing learner " + (i + 1)
                    + "...", -1.0);
            this.ensemble[i] = (Classifier) ((ClassOption) learnerOptions[i]).materializeObject(monitor, repository);
            if (monitor.taskShouldAbort()) {
                return;
            }
            monitor.setCurrentActivity("Preparing learner " + (i + 1) + "...",
                    -1.0);
            this.ensemble[i].prepareForUse(monitor, repository);
            if (monitor.taskShouldAbort()) {
                return;
            }
        }
        super.prepareForUseImpl(monitor, repository);
    }
int moa.classifiers.meta.WeightedMajorityAlgorithm.removePoorestModelBytes () [protected]
Definition at line 199 of file WeightedMajorityAlgorithm.java.
{
        int poorestIndex = Utils.minIndex(this.ensembleWeights);
        int byteSize = this.ensemble[poorestIndex].measureByteSize();
        discardModel(poorestIndex);
        return byteSize;
    }
void moa.classifiers.meta.WeightedMajorityAlgorithm.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 103 of file WeightedMajorityAlgorithm.java.
{
        this.ensembleWeights = new double[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i].resetLearning();
            this.ensembleWeights[i] = 1.0;
        }
    }
void moa.classifiers.meta.WeightedMajorityAlgorithm.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 112 of file WeightedMajorityAlgorithm.java.
{
        double totalWeight = 0.0;
        for (int i = 0; i < this.ensemble.length; i++) {
            boolean prune = false;
            if (!this.ensemble[i].correctlyClassifies(inst)) {
                if (this.ensembleWeights[i] > this.gammaOption.getValue()
                        / this.ensembleWeights.length) {
                    this.ensembleWeights[i] *= this.betaOption.getValue()
                            * inst.weight();
                } else if (this.pruneOption.isSet()) {
                    prune = true;
                    discardModel(i);
                    i--;
                }
            }
            if (!prune) {
                totalWeight += this.ensembleWeights[i];
                this.ensemble[i].trainOnInstance(inst);
            }
        }
        // normalize weights
        for (int i = 0; i < this.ensembleWeights.length; i++) {
            this.ensembleWeights[i] /= totalWeight;
        }
    }
Member Data Documentation
FloatOption moa.classifiers.meta.WeightedMajorityAlgorithm.betaOption
Initial value:
 new FloatOption("beta", 'b',
            "Factor to punish mistakes by.", 0.9, 0.0, 1.0)
Definition at line 67 of file WeightedMajorityAlgorithm.java.
Classifier [] moa.classifiers.meta.WeightedMajorityAlgorithm.ensemble [protected]
Definition at line 76 of file WeightedMajorityAlgorithm.java.
double [] moa.classifiers.meta.WeightedMajorityAlgorithm.ensembleWeights [protected]
Definition at line 78 of file WeightedMajorityAlgorithm.java.
FloatOption moa.classifiers.meta.WeightedMajorityAlgorithm.gammaOption
Initial value:
 new FloatOption("gamma", 'g',
            "Minimum fraction of weight per model.", 0.01, 0.0, 0.5)
Definition at line 70 of file WeightedMajorityAlgorithm.java.
ListOption moa.classifiers.meta.WeightedMajorityAlgorithm.learnerListOption
Initial value:
 new ListOption(
            "learners",
            'l',
            "The learners to combine.",
            new ClassOption("learner", ' ', "", Classifier.class,
            "trees.HoeffdingTree"),
            new Option[]{
                new ClassOption("", ' ', "", Classifier.class,
                "trees.HoeffdingTree -l MC"),
                new ClassOption("", ' ', "", Classifier.class,
                "trees.HoeffdingTree -l NB"),
                new ClassOption("", ' ', "", Classifier.class,
                "trees.HoeffdingTree -l NBAdaptive"),
                new ClassOption("", ' ', "", Classifier.class, "bayes.NaiveBayes")},
            ',')
Definition at line 51 of file WeightedMajorityAlgorithm.java.
FlagOption moa.classifiers.meta.WeightedMajorityAlgorithm.pruneOption
Initial value:
 new FlagOption("prune", 'p',
            "Prune poorly performing models from ensemble.")
Definition at line 73 of file WeightedMajorityAlgorithm.java.
final long moa.classifiers.meta.WeightedMajorityAlgorithm.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 44 of file WeightedMajorityAlgorithm.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/WeightedMajorityAlgorithm.java