MOA: moa.cluster.Miniball.Miniball_b Class Reference
moa.cluster.Miniball.Miniball_b Class Reference
Package Functions
double[] getCenter ()
double squared_radius ()
int size ()
int support_size ()
double excess (double[] p)
void reset ()
void pop ()
boolean push (double[] p)
double slack ()
Package Attributes
int m
int s
double[] q0 = new double[d]
double[] z = new double[d + 1]
double[] f = new double[d + 1]
double[][] v = new double[d + 1][d]
double[][] a = new double[d + 1][d]
double[][] c = new double[d + 1][d]
double[] sqr_r = new double[d + 1]
double[] current_c = new double[d]
double current_sqr_r
Detailed Description
Definition at line 90 of file Miniball.java.
Member Function Documentation
double moa.cluster.Miniball.Miniball_b.excess (double[] p) [package]
Definition at line 120 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.current_c, moa.cluster.Miniball.Miniball_b.current_sqr_r, moa.cluster.Miniball.d, and moa.cluster.Miniball.mb_sqr().
Referenced by moa.cluster.Miniball.accuracy(), and moa.cluster.Miniball.mtf_mb().
{
            double e = -current_sqr_r;
            for (int k = 0; k < d; ++k) {
                e += mb_sqr(p[k] - current_c[k]);
            }
            return e;
        }
double [] moa.cluster.Miniball.Miniball_b.getCenter () [package]
Definition at line 104 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.current_c.
Referenced by moa.cluster.Miniball.center(), and moa.cluster.Miniball.max_excess().
{
            return (current_c);
        }
void moa.cluster.Miniball.Miniball_b.pop () [package]
Definition at line 139 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.m.
Referenced by moa.cluster.Miniball.mtf_mb(), and moa.cluster.Miniball.pivot_mb().
                   {
            --m;
        }
boolean moa.cluster.Miniball.Miniball_b.push (double[] p) [package]
Definition at line 143 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.a, moa.cluster.Miniball.Miniball_b.c, moa.cluster.Miniball.Miniball_b.current_c, moa.cluster.Miniball.Miniball_b.current_sqr_r, moa.cluster.Miniball.d, moa.cluster.Miniball.Miniball_b.f, moa.cluster.Miniball.Miniball_b.m, moa.cluster.Miniball.mb_sqr(), moa.cluster.Miniball.Miniball_b.q0, moa.cluster.Miniball.Miniball_b.s, moa.cluster.Miniball.Miniball_b.sqr_r, moa.cluster.Miniball.Miniball_b.v, and moa.cluster.Miniball.Miniball_b.z.
Referenced by moa.cluster.Miniball.mtf_mb(), and moa.cluster.Miniball.pivot_mb().
{
            //System.out.println("Miniball_b:push");
            int i, j;
            double eps = 1e-32;
            if (m == 0) {
                for (i = 0; i < d; ++i) {
                    q0[i] = p[i];
                }
                for (i = 0; i < d; ++i) {
                    c[0][i] = q0[i];
                }
                sqr_r[0] = 0;
            } else {
                // set v_m to Q_m
                for (i = 0; i < d; ++i) {
                    v[m][i] = p[i] - q0[i];
                }
                // compute the a_{m,i}, i< m
                for (i = 1; i < m; ++i) {
                    a[m][i] = 0;
                    for (j = 0; j < d; ++j) {
                        a[m][i] += v[i][j] * v[m][j];
                    }
                    a[m][i] *= (2 / z[i]);
                }
                // update v_m to Q_m-\bar{Q}_m
                for (i = 1; i < m; ++i) {
                    for (j = 0; j < d; ++j) {
                        v[m][j] -= a[m][i] * v[i][j];
                    }
                }
                // compute z_m
                z[m] = 0;
                for (j = 0; j < d; ++j) {
                    z[m] += mb_sqr(v[m][j]);
                }
                z[m] *= 2;
                // reject push if z_m too small
                if (z[m] < eps * current_sqr_r) {
                    return false;
                }
                // update c, sqr_r
                double e = -sqr_r[m - 1];
                for (i = 0; i < d; ++i) {
                    e += mb_sqr(p[i] - c[m - 1][i]);
                }
                f[m] = e / z[m];
                for (i = 0; i < d; ++i) {
                    c[m][i] = c[m - 1][i] + f[m] * v[m][i];
                }
                sqr_r[m] = sqr_r[m - 1] + e * f[m] / 2;
            }
            current_c = c[m];
            current_sqr_r = sqr_r[m];
            s = ++m;
            return true;
        }
void moa.cluster.Miniball.Miniball_b.reset () [package]
Definition at line 128 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.c, moa.cluster.Miniball.Miniball_b.current_c, moa.cluster.Miniball.Miniball_b.current_sqr_r, moa.cluster.Miniball.d, moa.cluster.Miniball.Miniball_b.m, and moa.cluster.Miniball.Miniball_b.s.
Referenced by moa.cluster.Miniball.build().
                     {
            m = 0;
            s = 0;
            // we misuse c[0] for the center of the empty sphere
            for (int j = 0; j < d; j++) {
                c[0][j] = 0;
            }
            current_c = c[0];
            current_sqr_r = -1;
        }
int moa.cluster.Miniball.Miniball_b.size () [package]
Definition at line 112 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.m.
Referenced by moa.cluster.Miniball.mtf_mb().
                   {
            return m;
        }
double moa.cluster.Miniball.Miniball_b.slack () [package]
Definition at line 208 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.a, moa.cluster.Miniball.d, moa.cluster.Miniball.Miniball_b.f, and moa.cluster.Miniball.Miniball_b.s.
Referenced by moa.cluster.Miniball.accuracy().
                       {
            double min_l = 0;
            double[] l = new double[d + 1];
            l[0] = 1;
            for (int i = s - 1; i > 0; --i) {
                l[i] = f[i];
                for (int k = s - 1; k > i; --k) {
                    l[i] -= a[k][i] * l[k];
                }
                if (l[i] < min_l) {
                    min_l = l[i];
                }
                l[0] -= l[i];
            }
            if (l[0] < min_l) {
                min_l = l[0];
            }
            return ((min_l < 0) ? -min_l : 0);
        }
double moa.cluster.Miniball.Miniball_b.squared_radius () [package]
Definition at line 108 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.current_sqr_r.
Referenced by moa.cluster.Miniball.max_excess(), moa.cluster.Miniball.pivot_mb(), moa.cluster.Miniball.radius(), and moa.cluster.Miniball.squared_radius().
{
            return current_sqr_r;
        }
int moa.cluster.Miniball.Miniball_b.support_size () [package]
Definition at line 116 of file Miniball.java.
References moa.cluster.Miniball.Miniball_b.s.
Referenced by moa.cluster.Miniball.nr_support_points().
{
            return s;
        }
Member Data Documentation
double [][] moa.cluster.Miniball.Miniball_b.a = new double[d + 1][d] [package]
Definition at line 97 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push(), and moa.cluster.Miniball.Miniball_b.slack().
double [][] moa.cluster.Miniball.Miniball_b.c = new double[d + 1][d] [package]
Definition at line 98 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push(), and moa.cluster.Miniball.Miniball_b.reset().
double [] moa.cluster.Miniball.Miniball_b.current_c = new double[d] [package]
Definition at line 100 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.Miniball_b.getCenter(), moa.cluster.Miniball.Miniball_b.push(), and moa.cluster.Miniball.Miniball_b.reset().
double moa.cluster.Miniball.Miniball_b.current_sqr_r [package]
Definition at line 101 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.excess(), moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.reset(), and moa.cluster.Miniball.Miniball_b.squared_radius().
double [] moa.cluster.Miniball.Miniball_b.f = new double[d + 1] [package]
Definition at line 95 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push(), and moa.cluster.Miniball.Miniball_b.slack().
int moa.cluster.Miniball.Miniball_b.m [package]
Definition at line 92 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.pop(), moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.reset(), and moa.cluster.Miniball.Miniball_b.size().
double [] moa.cluster.Miniball.Miniball_b.q0 = new double[d] [package]
Definition at line 93 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push().
int moa.cluster.Miniball.Miniball_b.s [package]
Definition at line 92 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push(), moa.cluster.Miniball.Miniball_b.reset(), moa.cluster.Miniball.Miniball_b.slack(), and moa.cluster.Miniball.Miniball_b.support_size().
double [] moa.cluster.Miniball.Miniball_b.sqr_r = new double[d + 1] [package]
Definition at line 99 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push().
double [][] moa.cluster.Miniball.Miniball_b.v = new double[d + 1][d] [package]
Definition at line 96 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push().
double [] moa.cluster.Miniball.Miniball_b.z = new double[d + 1] [package]
Definition at line 94 of file Miniball.java.
Referenced by moa.cluster.Miniball.Miniball_b.push().
The documentation for this class was generated from the following file:
main/java/moa/cluster/Miniball.java