MOA: moa.clusterers.outliers.SimpleCOD.StreamObj Class Reference
moa.clusterers.outliers.SimpleCOD.StreamObj Class Reference
Public Member Functions
StreamObj (double...values)
int dimensions ()
The number of dimensions.
double get (int index)
int hashCode ()
boolean equals (Object obj)
int compareTo (StreamObj that)
Private Attributes
final double[] values
final int hashCode
Detailed Description
Definition at line 25 of file StreamObj.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.SimpleCOD.StreamObj.StreamObj (double... values)
Definition at line 29 of file StreamObj.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.hashCode().
{
        this.values = values;
        int h = 1;
        for (double value : values) {
            h = 31 * (int) h + (int) value;
        }
        this.hashCode = h;
    }
Member Function Documentation
int moa.clusterers.outliers.SimpleCOD.StreamObj.compareTo (StreamObj that)
Definition at line 73 of file StreamObj.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), and moa.clusterers.outliers.SimpleCOD.StreamObj.values.
{
        int dimensions = Math.min(this.dimensions(), that.dimensions());
        for (int i = 0; i < dimensions; i++) {
            double v1 = this.values[i];
            double v2 = that.values[i];
            if (v1 > v2) {
                return +1;
            }
            if (v1 < v2) {
                return -1;
            }
        }
        if (this.dimensions() > dimensions) {
            return +1;
        }
        if (that.dimensions() > dimensions) {
            return -1;
        }
        return 0;
    }
int moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions ()
The number of dimensions.
Implements moa.clusterers.outliers.utils.mtree.DistanceFunctions.EuclideanCoordinate.
Definition at line 40 of file StreamObj.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.values.
Referenced by moa.clusterers.outliers.SimpleCOD.StreamObj.compareTo(), moa.clusterers.outliers.SimpleCOD.StreamObj.equals(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetEuclideanDist(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getObjectInfo(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode().
{
        return values.length;
    }
boolean moa.clusterers.outliers.SimpleCOD.StreamObj.equals (Object obj)
Definition at line 55 of file StreamObj.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), and moa.clusterers.outliers.SimpleCOD.StreamObj.values.
Referenced by moa.clusterers.outliers.SimpleCOD.ISBIndex.MapCountObjRefs(), and moa.clusterers.outliers.SimpleCOD.ISBIndex.MapGetNodes().
{
        if (obj instanceof StreamObj) {
            StreamObj that = (StreamObj) obj;
            if (this.dimensions() != that.dimensions()) {
                return false;
            }
            for (int i = 0; i < this.dimensions(); i++) {
                if (this.values[i] != that.values[i]) {
                    return false;
                }
            }
            return true;
        } else {
            return false;
        }
    }
double moa.clusterers.outliers.SimpleCOD.StreamObj.get (int index)
Definition at line 45 of file StreamObj.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.values.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetEuclideanDist(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getObjectInfo(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode().
{
        return values[index];
    }
int moa.clusterers.outliers.SimpleCOD.StreamObj.hashCode ()
Definition at line 50 of file StreamObj.java.
Referenced by moa.clusterers.outliers.SimpleCOD.StreamObj.StreamObj().
{
        return hashCode;
    }
Member Data Documentation
final int moa.clusterers.outliers.SimpleCOD.StreamObj.hashCode [private]
Definition at line 27 of file StreamObj.java.
Referenced by moa.clusterers.outliers.SimpleCOD.ISBIndex.MapCountObjRefs(), moa.clusterers.outliers.SimpleCOD.ISBIndex.MapDelete(), moa.clusterers.outliers.SimpleCOD.ISBIndex.MapGetNodes(), and moa.clusterers.outliers.SimpleCOD.ISBIndex.MapInsert().
final double [] moa.clusterers.outliers.SimpleCOD.StreamObj.values [private]
Definition at line 26 of file StreamObj.java.
Referenced by moa.clusterers.outliers.SimpleCOD.StreamObj.compareTo(), moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), moa.clusterers.outliers.SimpleCOD.StreamObj.equals(), and moa.clusterers.outliers.SimpleCOD.StreamObj.get().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/SimpleCOD/StreamObj.java