MOA: moa.classifiers.trees.ORTO.OptionNode Class Reference
moa.classifiers.trees.ORTO.OptionNode Class Reference
Public Member Functions
OptionNode (int id)
void resetFF ()
boolean isLeaf ()
int getNumSubtrees ()
int directionForBestTree ()
double[] getPrediction (Instance inst, ORTO tree)
double[] processInstance (Instance inst, ORTO tree)
double getFFRatio (int childIndex)
Protected Attributes
double[] optionFFSSL
double[] optionFFSeen
Private Member Functions
double[] aggregate (double[][] predictions, ORTO tree)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 552 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.OptionNode.OptionNode (int id)
Definition at line 560 of file ORTO.java.
{
            super(id);
        }
Member Function Documentation
double [] moa.classifiers.trees.ORTO.OptionNode.aggregate (double predictions[][], ORTO tree) [private]
Definition at line 710 of file ORTO.java.
References moa.options.MultiChoiceOption.getChosenIndex(), moa.options.MultiChoiceOption.getChosenLabel(), and moa.classifiers.trees.ORTO.OptionNodeAggregationOption.
Referenced by moa.classifiers.trees.ORTO.OptionNode.getPrediction(), and moa.classifiers.trees.ORTO.OptionNode.processInstance().
{
            if (tree.OptionNodeAggregationOption.getChosenIndex() == 0) { // Average
                double[] average = new double[predictions[0].length];
                for (int i = 0; i < predictions[0].length; i++) {
                    average[i] = 0.0;
                }
                for (int i = 0; i < predictions[0].length; i++) {
                    for (int j = 0; j < predictions.length; j++) {
                        average[i] += predictions[j][i];
                    }
                    average[i] = average[i] / predictions.length;
                }
                return average;
            } else {
                assert false : tree.OptionNodeAggregationOption.getChosenLabel();
                return new double[] {0.0};
            }
        }
int moa.classifiers.trees.ORTO.OptionNode.directionForBestTree ()
Definition at line 588 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.OptionNode.optionFFSeen, and moa.classifiers.trees.ORTO.OptionNode.optionFFSSL.
Referenced by moa.classifiers.trees.ORTO.OptionNode.getPrediction(), and moa.classifiers.trees.ORTO.OptionNode.processInstance().
{
            int d = 0;
            double tmp = 0.0, min = Double.MAX_VALUE;
            for (int i = 0; i < children.size(); i++) {
                tmp = optionFFSSL[i] / optionFFSeen[i];
                if (tmp < min) {
                    min = tmp;
                    d = i;
                }
            }
            return d;
        }
double moa.classifiers.trees.ORTO.OptionNode.getFFRatio (int childIndex)
Definition at line 730 of file ORTO.java.
References moa.classifiers.trees.ORTO.OptionNode.optionFFSeen, and moa.classifiers.trees.ORTO.OptionNode.optionFFSSL.
Referenced by moa.classifiers.trees.ORTO.findWorstOption().
{
            return optionFFSSL[childIndex] / optionFFSeen[childIndex];
        }
int moa.classifiers.trees.ORTO.OptionNode.getNumSubtrees ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 580 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children.
Referenced by moa.classifiers.trees.ORTO.OptionNode.processInstance().
{
            int num = 0;
            for (Node child : children) {
                num += child.getNumSubtrees();
            }
            return num;
        }
double [] moa.classifiers.trees.ORTO.OptionNode.getPrediction (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 601 of file ORTO.java.
References moa.classifiers.trees.ORTO.OptionNode.aggregate(), moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.OptionNode.directionForBestTree(), moa.classifiers.trees.ORTO.InnerNode.getChild(), moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.trees.ORTO.Node.getPrediction(), and moa.classifiers.trees.ORTO.OptionNodeAggregationOption.
{
            double[][] predictions = new double[this.children.size()][];
            if (tree.OptionNodeAggregationOption.getChosenIndex() != 1) {
                int i = 0;
                for (i = 0; i < this.children.size(); i++) {
                    predictions[i] = this.getChild(i).getPrediction(inst, tree);
                }
                return aggregate(predictions, tree);
            } else {
                int d = directionForBestTree();
                return this.getChild(d).getPrediction(inst, tree);
            }
        }
boolean moa.classifiers.trees.ORTO.OptionNode.isLeaf ()
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 576 of file ORTO.java.
{
            return false;
        }
double [] moa.classifiers.trees.ORTO.OptionNode.processInstance (Instance inst, ORTO tree)
Reimplemented from moa.classifiers.trees.ORTO.Node.
Definition at line 615 of file ORTO.java.
References moa.classifiers.trees.ORTO.Adaptable, moa.classifiers.trees.ORTO.Node.Adaptable, moa.core.DoubleVector.addToValue(), moa.classifiers.trees.ORTO.OptionNode.aggregate(), moa.classifiers.trees.ORTO.Node.Alternate, moa.classifiers.trees.ORTO.Node.alternateTree, moa.classifiers.trees.ORTO.AlternateTreeTimeOption, moa.classifiers.trees.ORTO.AlternateTreeTMinOption, moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.OptionNode.directionForBestTree(), moa.classifiers.trees.ORTO.InnerNode.getChild(), moa.classifiers.trees.ORTO.InnerNode.getChildIndex(), moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.trees.ORTO.Node.getNumSubtrees(), moa.classifiers.trees.ORTO.OptionNode.getNumSubtrees(), moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.options.IntOption.getValue(), moa.classifiers.trees.ORTO.gracePeriodOption, moa.classifiers.trees.ORTO.InnerNode.lossStatistics, moa.classifiers.trees.ORTO.nodesToAdapt, moa.classifiers.trees.ORTO.InnerNode.numChildren(), moa.classifiers.trees.ORTO.numTrees, moa.classifiers.trees.ORTO.OptionFadingFactorOption, moa.classifiers.trees.ORTO.OptionNode.optionFFSeen, moa.classifiers.trees.ORTO.OptionNode.optionFFSSL, moa.classifiers.trees.ORTO.OptionNodeAggregationOption, moa.classifiers.trees.ORTO.InnerNode.PageHinckleyTest(), moa.classifiers.trees.ORTO.PageHinckleyThresholdOption, moa.classifiers.trees.ORTO.Node.parent, moa.classifiers.trees.ORTO.InnerNode.previousWeight, moa.classifiers.trees.ORTO.Node.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), moa.classifiers.trees.ORTO.InnerNode.setAdaptable(), moa.classifiers.trees.ORTO.Node.setAdaptable(), moa.classifiers.trees.ORTO.InnerNode.setChild(), moa.classifiers.trees.ORTO.Node.setParent(), moa.core.DoubleVector.setValue(), moa.classifiers.trees.ORTO.treeRoot, and moa.classifiers.trees.ORTO.InnerNode.weightSeen.
{
            double[][] processed = new double[this.numChildren()][];
            int i = 0;
            for (i = 0; i < this.numChildren(); i++) {
                processed[i] = this.getChild(i).processInstance(inst, tree); // All the children get to see the instance
            }
            double[] prediction;
            if (tree.OptionNodeAggregationOption.getChosenIndex() != 1) {
                prediction = aggregate(processed, tree);
            } else {
                prediction = processed[directionForBestTree()];
            }
            if (Adaptable) {
                if (this.alternateTree == null) {
                    // Retrieve the error for the found leaf node
                    double PHerror = inst.classValue() - prediction[0];
                    // Back-propagate the error through all the parent nodes
                    if(PageHinckleyTest(PHerror, tree.PageHinckleyThresholdOption.getValue())) {
                        for (Node node : tree.nodesToAdapt) {
                            if (children.contains(node)) {
                                tree.nodesToAdapt.remove(node);
                            }
                        }
                        tree.nodesToAdapt.add(this);
                    }
                } else {
                    // If an alternate tree already exists, check if the current tree should be replaced with it,
                    // or if the alternate tree should be discarded.
                    double[] predictionAlt = this.alternateTree.processInstance(inst, tree);
                    // Update the loss statistics for the alternate tree
                    double qOrg = prediction[1];
                    double qAlt = predictionAlt[1];
                    // Compute the Qi statistics
                    double Qi = Math.log(qOrg / qAlt);
                    lossStatistics.addToValue(0,1);
                    lossStatistics.addToValue(1,Qi);
                    double QiAverage = lossStatistics.getValue(1) / lossStatistics.getValue(0);
                    if (weightSeen - previousWeight >= tree.AlternateTreeTMinOption.getValue()) {
                        // Update the weight at which a decision was tested for
                        previousWeight = weightSeen;
                        // If appropriate, replace the current tree with the alternate tree
                        if(Qi > 0) {
                            alternateTree.setAdaptable(true);
                            alternateTree.Alternate = false;
                            if (parent != null) { // Replace the main tree at a subtree
                                parent.setChild(parent.getChildIndex(this), alternateTree);
                                tree.numTrees = tree.numTrees - this.getNumSubtrees() + alternateTree.getNumSubtrees();
                                alternateTree.setParent(parent);
                                this.alternateTree = null;
                            } else { // Or occasionally at the root of the tree
                                tree.treeRoot = this.alternateTree;
                                tree.numTrees = tree.numTrees - this.getNumSubtrees() + alternateTree.getNumSubtrees();
                                tree.Adaptable = true;
                                this.alternateTree = null;
                            }
                            tree.removeExcessTrees();
                        }
                        // Otherwise, check if the alternate tree should be discarded
                        else if (QiAverage < lossStatistics.getValue(2) && lossStatistics.getValue(0) >= (10 * tree.AlternateTreeTMinOption.getValue()) || weightSeen >= tree.AlternateTreeTimeOption.getValue()) {
                            // tree.nodesToAdapt.remove(tree.nodesToAdapt.indexOf(this)); ?
                            this.alternateTree = null;
                            setAdaptable(true);
                        }
                        lossStatistics.setValue(2, QiAverage);
                    }
                }
                double sqLoss;
                if (weightSeen + 1 > tree.gracePeriodOption.getValue() + 50) {
                    for (i = 0; i < this.children.size(); i++) {
                        sqLoss = Math.pow(processed[i][0] - inst.classValue(), 2);
                        optionFFSSL[i] = optionFFSSL[i] * tree.OptionFadingFactorOption.getValue() + sqLoss;
                        optionFFSeen[i] = optionFFSeen[i] * tree.OptionFadingFactorOption.getValue() + 1;
                    }
                }
            }
            weightSeen++;
            return prediction;
        }
void moa.classifiers.trees.ORTO.OptionNode.resetFF ()
Definition at line 564 of file ORTO.java.
References moa.classifiers.trees.ORTO.InnerNode.children, moa.classifiers.trees.ORTO.OptionNode.optionFFSeen, and moa.classifiers.trees.ORTO.OptionNode.optionFFSSL.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            this.optionFFSSL = new double[this.children.size()];
            this.optionFFSeen = new double[this.children.size()];
            // this.optionBaseFFSSL = new double[this.children.size()];
            for (int i = 0; i < this.children.size(); i++) {
                this.optionFFSSL[i] = 0.0;
                this.optionFFSeen[i] = 0.0;
                // this.optionBaseFFSSL[i] = 0.0;
            }
        }
Member Data Documentation
double [] moa.classifiers.trees.ORTO.OptionNode.optionFFSeen [protected]
Definition at line 557 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.directionForBestTree(), moa.classifiers.trees.ORTO.OptionNode.getFFRatio(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), and moa.classifiers.trees.ORTO.OptionNode.resetFF().
double [] moa.classifiers.trees.ORTO.OptionNode.optionFFSSL [protected]
Definition at line 556 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.OptionNode.directionForBestTree(), moa.classifiers.trees.ORTO.OptionNode.getFFRatio(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), and moa.classifiers.trees.ORTO.OptionNode.resetFF().
final long moa.classifiers.trees.ORTO.OptionNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.ORTO.InnerNode.
Definition at line 554 of file ORTO.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java