MOA: moa.evaluation.CMM_GTAnalysis Class Reference
moa.evaluation.CMM_GTAnalysis Class Reference
Classes
class CMMPoint
Wrapper class for data points to store CMM relevant attributes.
class GTCluster
Main class to model the new clusters that will be the output of the cluster analysis.
Public Member Functions
CMM_GTAnalysis (Clustering trueClustering, ArrayList< DataPoint > points, boolean enableClassMerge)
double getClassSeparability ()
Calculates how well the original clusters are separable.
double getNoiseSeparability ()
Calculates how well noise is separable from the given clusters Small values indicate bad separability, values close to 1 indicate good separability.
double getModelQuality ()
Calculates the relative number of errors being caused by the underlying cluster model.
String getParameterString ()
String with main CMM parameters.
Protected Member Functions
double getConnectionValue (CMMPoint cmmp, int clusterID)
Calculate the connection of a point to a cluster.
CMMPoint getPoint (int index)
Get CMM internal point.
GTCluster getGT0Cluster (int index)
Return cluster.
int getNumberOfGT0Classes ()
Number of classes/clusters of the new clustering.
Private Member Functions
void getKnnInCluster (CMMPoint cmmp, int k, ArrayList< Integer > pointIDs, AutoExpandVector< Double > knnDist, AutoExpandVector< Integer > knnPointIndex)
void calculateGTPointQualities ()
calculate initial connectivities
void calculateGTClusterConnections ()
Calculate connections between clusters and merge clusters accordingly as long as connections exceed threshold.
double distance (Instance inst1, Instance inst2)
Calculates Euclidian distance.
double distance (Instance inst1, double[] inst2)
Calculates Euclidian distance.
Private Attributes
Clustering gtClustering
the given ground truth clustering
ArrayList< CMMPoint > cmmpoints
list of given points within the horizon
ArrayList< GTCluster > gt0Clusters
the newly calculate ground truth clustering
ArrayList< Integer > noise
IDs of noise points.
int numPoints
total number of points
int numGTClusters
number of clusters of the original ground truth
int numGTClasses
number of classes of the original ground truth, in case of a micro clustering ground truth this differs from numGTClusters
int numGT0Classes
number of classes after we are done with the analysis
int numDims
number of dimensions
HashMap< Integer, Integer > mapTrueLabelToWorkLabel
mapping between true cluster ID/class label of the original ground truth and the internal cluster ID/working class label.
int[] mergeMap
log of how clusters have been merged (for debugging)
int noiseErrorByModel
number of non-noise points that will create an error due to the underlying clustering model (e.g.
int pointErrorByModel
number of noise points that will create an error due to the underlying clustering model (e.g.
boolean debug = false
CMM debug mode.
int knnNeighbourhood = 2
defines how many nearest neighbors will be used
double tauConnection = 0.5
the threshold which defines when ground truth clusters will be merged.
double clusterConnectionMaxPoints = knnNeighbourhood
experimental (default: disabled) separate k for points to cluster and cluster to cluster
boolean useExpConnectivity = false
experimental (default: disabled) use exponential connectivity function to model different behavior: closer points will have a stronger connection compared to the linear function.
double lambdaConnRefXValue = 0.01
double lambdaConnX = 4
double lamdaConn
Detailed Description
Definition at line 44 of file CMM_GTAnalysis.java.
Constructor & Destructor Documentation
moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis (Clustering trueClustering, ArrayList< DataPoint > points, boolean enableClassMerge)
Parameters:
trueClustering the ground truth clustering
points data points
enableClassMerge allow class merging (should be set to true on default)
Definition at line 459 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections(), moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.debug, moa.cluster.Clustering.get(), moa.cluster.Cluster.getGroundTruth(), moa.evaluation.CMM_GTAnalysis.gt0Clusters, moa.evaluation.CMM_GTAnalysis.gtClustering, moa.evaluation.CMM_GTAnalysis.lambdaConnRefXValue, moa.evaluation.CMM_GTAnalysis.lambdaConnX, moa.evaluation.CMM_GTAnalysis.lamdaConn, moa.evaluation.CMM_GTAnalysis.mapTrueLabelToWorkLabel, moa.evaluation.CMM_GTAnalysis.mergeMap, moa.evaluation.CMM_GTAnalysis.noise, moa.evaluation.CMM_GTAnalysis.noiseErrorByModel, moa.evaluation.CMM_GTAnalysis.numDims, moa.evaluation.CMM_GTAnalysis.numGTClasses, moa.evaluation.CMM_GTAnalysis.numGTClusters, moa.evaluation.CMM_GTAnalysis.numPoints, moa.evaluation.CMM_GTAnalysis.pointErrorByModel, moa.cluster.Clustering.size(), and moa.evaluation.CMM_GTAnalysis.tauConnection.
{
        if(debug)
            System.out.println("GT Analysis Debug Output");
        noiseErrorByModel = 0;
        pointErrorByModel = 0;
        if(!enableClassMerge){
            tauConnection = 1.0;
        }
        lamdaConn = -Math.log(lambdaConnRefXValue)/Math.log(2)/lambdaConnX;
        this.gtClustering = trueClustering;
        numPoints = points.size();
        numDims = points.get(0).numAttributes()-1;
        numGTClusters = gtClustering.size();
        //init mappings between work and true labels
        mapTrueLabelToWorkLabel = new HashMap<Integer, Integer>();
        //set up base of new clustering
        gt0Clusters = new ArrayList<GTCluster>();
        int numWorkClasses = 0;
        //create label to worklabel mapping as real labels can be just a set of unordered integers
        for (int i = 0; i < numGTClusters; i++) {
            int label = (int)gtClustering.get(i).getGroundTruth();
            if(!mapTrueLabelToWorkLabel.containsKey(label)){
                gt0Clusters.add(new GTCluster(numWorkClasses,label,i));
                mapTrueLabelToWorkLabel.put(label,numWorkClasses);
                numWorkClasses++;
            }
            else{
                gt0Clusters.get(mapTrueLabelToWorkLabel.get(label)).clusterRepresentations.add(i);
            }
        }
        numGTClasses = numWorkClasses;
        mergeMap = new int[numGTClasses];
        for (int i = 0; i < numGTClasses; i++) {
            mergeMap[i]=i;
        }
        //create cmd point wrapper instances
        cmmpoints = new ArrayList<CMMPoint>();
        for (int p = 0; p < points.size(); p++) {
            CMMPoint cmdp = new CMMPoint(points.get(p), p);
            cmmpoints.add(cmdp);
        }
        //split points up into their GTClusters and Noise (according to class labels)
        noise = new ArrayList<Integer>();
        for (int p = 0; p < numPoints; p++) {
            if(cmmpoints.get(p).isNoise()){
                noise.add(p);
            }
            else{
                gt0Clusters.get(cmmpoints.get(p).workclass()).points.add(p);
            }
        }
        //calculate initial knnMean and knnDev
        for (GTCluster gtc : gt0Clusters) {
            gtc.calculateKnn();
        }
        //calculate cluster connections
        calculateGTClusterConnections();
        //calculate point connections with own clusters
        calculateGTPointQualities();
        if(debug)
            System.out.println("GT Analysis Debug End");
   }
Member Function Documentation
void moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections () [private]
Calculate connections between clusters and merge clusters accordingly as long as connections exceed threshold.
Definition at line 641 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.debug, moa.evaluation.CMM_GTAnalysis.gt0Clusters, moa.evaluation.CMM_GTAnalysis.numGT0Classes, and moa.evaluation.CMM_GTAnalysis.tauConnection.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis().
{
        for (int c0 = 0; c0 < gt0Clusters.size(); c0++) {
            for (int c1 = 0; c1 < gt0Clusters.size(); c1++) {
                    gt0Clusters.get(c0).calculateClusterConnection(c1, true);
            }
        }
        boolean changedConnection = true;
        while(changedConnection){
            if(debug){
                System.out.println("Cluster Connection");
                for (int c = 0; c < gt0Clusters.size(); c++) {
                    System.out.print("C"+gt0Clusters.get(c).label+" --> ");
                    for (int c1 = 0; c1 < gt0Clusters.get(c).connections.size(); c1++) {
                        System.out.print(" C"+gt0Clusters.get(c1).label+": "+gt0Clusters.get(c).connections.get(c1));
                    }
                    System.out.println("");
                }
                System.out.println("");
            }
            double max = 0;
            int maxIndexI = -1;
            int maxIndexJ = -1;
            changedConnection = false;
            for (int c0 = 0; c0 < gt0Clusters.size(); c0++) {
                for (int c1 = c0+1; c1 < gt0Clusters.size(); c1++) {
                    if(c0==c1) continue;
                        double min =Math.min(gt0Clusters.get(c0).connections.get(c1), gt0Clusters.get(c1).connections.get(c0));
                        if(min > max){
                            max = min;
                            maxIndexI = c0;
                            maxIndexJ = c1;
                        }
                }
            }
            if(maxIndexI!=-1 && max > tauConnection){
                gt0Clusters.get(maxIndexI).mergeCluster(maxIndexJ);
                if(debug)
                    System.out.println("Merging "+maxIndexI+" and "+maxIndexJ+" because of connection "+max);
                changedConnection = true;
            }
        }
        numGT0Classes = gt0Clusters.size();
    }
void moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities () [private]
calculate initial connectivities
Definition at line 625 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.CMMPoint.connectivity, moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.gui.visualization.DataPoint.isNoise(), moa.evaluation.CMM_GTAnalysis.numPoints, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.gui.visualization.DataPoint.setMeasureValue(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis().
{
        for (int p = 0; p < numPoints; p++) {
            CMMPoint cmdp = cmmpoints.get(p);
            if(!cmdp.isNoise()){
                cmdp.connectivity = getConnectionValue(cmdp, cmdp.workclass());
                cmdp.p.setMeasureValue("Connectivity", cmdp.connectivity);
            }
        }
    }
double moa.evaluation.CMM_GTAnalysis.distance (Instance inst1, double[] inst2) [private]
Calculates Euclidian distance.
Parameters:
inst1 point as an instance
inst2 point as double array
Returns:
euclidian distance
Definition at line 810 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.distance(), and moa.evaluation.CMM_GTAnalysis.numDims.
{
        double distance = 0.0;
        for (int i = 0; i < numDims; i++) {
            double d = inst1.value(i) - inst2[i];
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
double moa.evaluation.CMM_GTAnalysis.distance (Instance inst1, Instance inst2) [private]
Calculates Euclidian distance.
Parameters:
inst1 point as double array
inst2 point as double array
Returns:
euclidian distance
Definition at line 799 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.distance(), and moa.evaluation.CMM_GTAnalysis.getKnnInCluster().
{
          return distance(inst1, inst2.toDoubleArray());
    }
double moa.evaluation.CMM_GTAnalysis.getClassSeparability ()
Calculates how well the original clusters are separable.
Small values indicate bad separability, values close to 1 indicate good separability
Returns:
index of seperability
Definition at line 695 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.numGT0Classes, and moa.evaluation.CMM_GTAnalysis.numGTClasses.
Referenced by moa.evaluation.CMM.evaluateClustering().
{
//        int totalConn = numGTClasses*(numGTClasses-1)/2;
//        int mergedConn = 0;
//        for(GTCluster gt : gt0Clusters){
//            int merged = gt.clusterRepresentations.size();
//            if(merged > 1)
//                mergedConn+=merged * (merged-1)/2;
//        }
//        if(totalConn == 0)
//            return 0;
//        else
//            return 1-mergedConn/(double)totalConn;
        return numGT0Classes/(double)numGTClasses;
    }
double moa.evaluation.CMM_GTAnalysis.getConnectionValue (CMMPoint cmmp, int clusterID) [protected]
Calculate the connection of a point to a cluster.
Parameters:
cmmp the point to calculate the connection for
clusterID the corresponding cluster
Returns:
the connection value
Definition at line 545 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.getKnnInCluster(), moa.gui.visualization.DataPoint.getTimestamp(), moa.evaluation.CMM_GTAnalysis.gt0Clusters, moa.evaluation.CMM_GTAnalysis.knnNeighbourhood, moa.evaluation.CMM_GTAnalysis.lamdaConn, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, and moa.evaluation.CMM_GTAnalysis.useExpConnectivity.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.getNoiseSeparability(), moa.evaluation.CMM.misplacedError(), and moa.evaluation.CMM.noiseError().
{
        AutoExpandVector<Double> knnDist = new AutoExpandVector<Double>();
        AutoExpandVector<Integer> knnPointIndex = new AutoExpandVector<Integer>();
        //calculate the knn distance of the point to the cluster
        getKnnInCluster(cmmp, knnNeighbourhood, gt0Clusters.get(clusterID).points, knnDist, knnPointIndex);
        //TODO: What to do if we have less then k neighbors?
        double avgDist = 0;
        for (int i = 0; i < knnDist.size(); i++) {
            avgDist+= knnDist.get(i);
        }
        //what to do if we only have a single point???
        if(knnDist.size()!=0)
            avgDist/=knnDist.size();
        else
            return 0;
        //get the upper knn distance of the cluster
        double upperKnn = gt0Clusters.get(clusterID).knnMeanAvg + gt0Clusters.get(clusterID).knnDevAvg;
        /* calculate the connectivity based on knn distance of the point within the cluster
           and the upper knn distance of the cluster*/
        if(avgDist < upperKnn){
            return 1;
        }
        else{
            //value that should be reached at upperKnn distance
            //Choose connection formula
            double conn;
            if(useExpConnectivity)
                conn = Math.pow(2,-lamdaConn*(avgDist-upperKnn)/upperKnn);
            else
                conn = upperKnn/avgDist;
            if(Double.isNaN(conn))
                System.out.println("Connectivity NaN at "+cmmp.p.getTimestamp());
            return conn;
        }
    }
GTCluster moa.evaluation.CMM_GTAnalysis.getGT0Cluster (int index) [protected]
Return cluster.
Parameters:
index of the cluster to return
Returns:
cluster
Definition at line 781 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.gt0Clusters.
Referenced by moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.misplacedError(), and moa.evaluation.CMM.noiseError().
{
        return gt0Clusters.get(index);
    }
void moa.evaluation.CMM_GTAnalysis.getKnnInCluster (CMMPoint cmmp, int k, ArrayList< Integer > pointIDs, AutoExpandVector< Double > knnDist, AutoExpandVector< Integer > knnPointIndex) [private]
Parameters:
cmmp point to calculate knn distance for
k number of nearest neighbors to look for
pointIDs list of point IDs to check
knnDist sorted list of smallest knn distances (can already be filled to make updates possible)
knnPointIndex list of corresponding knn indices
Definition at line 595 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.distance(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.pID.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), and moa.evaluation.CMM_GTAnalysis.getConnectionValue().
{
        //iterate over every point in the choosen cluster, cal distance and insert into list
        for (int p1 = 0; p1 < pointIDs.size(); p1++) {
            int pid = pointIDs.get(p1);
            if(cmmp.pID == pid) continue;
            double dist = distance(cmmp,cmmpoints.get(pid));
            if(knnDist.size() < k || dist < knnDist.get(knnDist.size()-1)){
                int index = 0;
                while(index < knnDist.size() && dist > knnDist.get(index)) {
                    index++;
                }
                knnDist.add(index, dist);
                knnPointIndex.add(index,pid);
                if(knnDist.size() > k){
                    knnDist.remove(knnDist.size()-1);
                    knnPointIndex.remove(knnPointIndex.size()-1);
                }
            }
        }
    }
double moa.evaluation.CMM_GTAnalysis.getModelQuality ()
Calculates the relative number of errors being caused by the underlying cluster model.
Returns:
quality of the model
Definition at line 744 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.debug, moa.cluster.Clustering.get(), moa.cluster.Cluster.getGroundTruth(), moa.cluster.Cluster.getInclusionProbability(), moa.evaluation.CMM_GTAnalysis.gtClustering, moa.gui.visualization.DataPoint.isNoise(), moa.evaluation.CMM_GTAnalysis.noiseErrorByModel, moa.evaluation.CMM_GTAnalysis.numGTClusters, moa.evaluation.CMM_GTAnalysis.numPoints, moa.evaluation.CMM_GTAnalysis.pointErrorByModel, and moa.evaluation.CMM_GTAnalysis.CMMPoint.trueClass.
Referenced by moa.evaluation.CMM.evaluateClustering().
{
        for(int p = 0; p < numPoints; p++){
            CMMPoint cmdp = cmmpoints.get(p);
            for(int hc = 0; hc < numGTClusters;hc++){
                if(gtClustering.get(hc).getGroundTruth() != cmdp.trueClass){
                    if(gtClustering.get(hc).getInclusionProbability(cmdp) >= 1){
                        if(!cmdp.isNoise())
                            pointErrorByModel++;
                        else
                            noiseErrorByModel++;
                        break;
                    }
                }
            }
        }
        if(debug)
            System.out.println("Error by model: noise "+noiseErrorByModel+" point "+pointErrorByModel);
        return 1-((pointErrorByModel + noiseErrorByModel)/(double) numPoints);
    }
double moa.evaluation.CMM_GTAnalysis.getNoiseSeparability ()
Calculates how well noise is separable from the given clusters Small values indicate bad separability, values close to 1 indicate good separability.
Returns:
index of noise separability
Definition at line 717 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.evaluation.CMM_GTAnalysis.gt0Clusters, moa.evaluation.CMM_GTAnalysis.noise, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, and moa.gui.visualization.DataPoint.setMeasureValue().
Referenced by moa.evaluation.CMM.evaluateClustering().
{
        if(noise.isEmpty())
            return 1;
        double connectivity = 0;
        for(int p : noise){
            CMMPoint npoint = cmmpoints.get(p);
            double maxConnection = 0;
            //TODO: some kind of pruning possible. what about weighting?
            for (int c = 0; c < gt0Clusters.size(); c++) {
                double connection = getConnectionValue(npoint, c);
                if(connection > maxConnection)
                    maxConnection = connection;
            }
            connectivity+=maxConnection;
            npoint.p.setMeasureValue("MaxConnection", maxConnection);
        }
        return 1-(connectivity / noise.size());
    }
int moa.evaluation.CMM_GTAnalysis.getNumberOfGT0Classes () [protected]
Number of classes/clusters of the new clustering.
Returns:
number of new clusters
Definition at line 789 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.numGT0Classes.
Referenced by moa.evaluation.CMM.evaluateClustering().
{
        return numGT0Classes;
    }
String moa.evaluation.CMM_GTAnalysis.getParameterString ()
String with main CMM parameters.
Returns:
main CMM parameter
Definition at line 823 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.clusterConnectionMaxPoints, moa.evaluation.CMM_GTAnalysis.knnNeighbourhood, moa.evaluation.CMM_GTAnalysis.lambdaConnRefXValue, moa.evaluation.CMM_GTAnalysis.lambdaConnX, moa.evaluation.CMM_GTAnalysis.lamdaConn, moa.evaluation.CMM_GTAnalysis.tauConnection, and moa.evaluation.CMM_GTAnalysis.useExpConnectivity.
Referenced by moa.evaluation.CMM.getParameterString().
{
        String para = "";
        para+="k="+knnNeighbourhood+";";
        if(useExpConnectivity){
            para+="lambdaConnX="+lambdaConnX+";";
            para+="lambdaConn="+lamdaConn+";";
            para+="lambdaConnRef="+lambdaConnRefXValue+";";
        }
        para+="m="+clusterConnectionMaxPoints+";";
        para+="tauConn="+tauConnection+";";
        return para;
    }
CMMPoint moa.evaluation.CMM_GTAnalysis.getPoint (int index) [protected]
Get CMM internal point.
Parameters:
index of the point
Returns:
cmm point
Definition at line 771 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints.
Referenced by moa.evaluation.CMM.calculateError(), and moa.evaluation.CMM.calculateMatching().
{
        return cmmpoints.get(index);
    }
Member Data Documentation
double moa.evaluation.CMM_GTAnalysis.clusterConnectionMaxPoints = knnNeighbourhood [private]
experimental (default: disabled) separate k for points to cluster and cluster to cluster
Definition at line 140 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
ArrayList<CMMPoint> moa.evaluation.CMM_GTAnalysis.cmmpoints [private]
list of given points within the horizon
Definition at line 54 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.getKnnInCluster(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), moa.evaluation.CMM_GTAnalysis.getNoiseSeparability(), and moa.evaluation.CMM_GTAnalysis.getPoint().
boolean moa.evaluation.CMM_GTAnalysis.debug = false [private]
CMM debug mode.
Definition at line 120 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
ArrayList<GTCluster> moa.evaluation.CMM_GTAnalysis.gt0Clusters [private]
the newly calculate ground truth clustering
Definition at line 59 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.evaluation.CMM_GTAnalysis.getGT0Cluster(), moa.evaluation.CMM_GTAnalysis.getNoiseSeparability(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
Clustering moa.evaluation.CMM_GTAnalysis.gtClustering [private]
the given ground truth clustering
Definition at line 49 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.GTCluster.getInclusionProbability(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
int moa.evaluation.CMM_GTAnalysis.knnNeighbourhood = 2 [private]
defines how many nearest neighbors will be used
Definition at line 128 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), moa.evaluation.CMM_GTAnalysis.getConnectionValue(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
double moa.evaluation.CMM_GTAnalysis.lambdaConnRefXValue = 0.01 [private]
Definition at line 150 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
double moa.evaluation.CMM_GTAnalysis.lambdaConnX = 4 [private]
Definition at line 151 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
double moa.evaluation.CMM_GTAnalysis.lamdaConn [private]
Definition at line 152 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.getConnectionValue(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
HashMap<Integer, Integer> moa.evaluation.CMM_GTAnalysis.mapTrueLabelToWorkLabel [private]
mapping between true cluster ID/class label of the original ground truth and the internal cluster ID/working class label.
different original cluster IDs might map to the same new cluster ID due to merging of two clusters
Definition at line 98 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
int [] moa.evaluation.CMM_GTAnalysis.mergeMap [private]
log of how clusters have been merged (for debugging)
Definition at line 103 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
ArrayList<Integer> moa.evaluation.CMM_GTAnalysis.noise [private]
IDs of noise points.
Definition at line 64 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getNoiseSeparability().
int moa.evaluation.CMM_GTAnalysis.noiseErrorByModel [private]
number of non-noise points that will create an error due to the underlying clustering model (e.g.
point being covered by two clusters representing different classes)
Definition at line 109 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
int moa.evaluation.CMM_GTAnalysis.numDims [private]
number of dimensions
Definition at line 90 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.distance().
int moa.evaluation.CMM_GTAnalysis.numGT0Classes [private]
number of classes after we are done with the analysis
Definition at line 85 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections(), moa.evaluation.CMM_GTAnalysis.getClassSeparability(), and moa.evaluation.CMM_GTAnalysis.getNumberOfGT0Classes().
int moa.evaluation.CMM_GTAnalysis.numGTClasses [private]
number of classes of the original ground truth, in case of a micro clustering ground truth this differs from numGTClusters
Definition at line 80 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.CMM_GTAnalysis.getClassSeparability(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
int moa.evaluation.CMM_GTAnalysis.numGTClusters [private]
number of clusters of the original ground truth
Definition at line 74 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
int moa.evaluation.CMM_GTAnalysis.numPoints [private]
total number of points
Definition at line 69 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
int moa.evaluation.CMM_GTAnalysis.pointErrorByModel [private]
number of noise points that will create an error due to the underlying clustering model (e.g.
noise point being covered by a cluster)
Definition at line 115 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
double moa.evaluation.CMM_GTAnalysis.tauConnection = 0.5 [private]
the threshold which defines when ground truth clusters will be merged.
set to 1 to disable merging
Definition at line 134 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM_GTAnalysis.calculateGTClusterConnections(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
boolean moa.evaluation.CMM_GTAnalysis.useExpConnectivity = false [private]
experimental (default: disabled) use exponential connectivity function to model different behavior: closer points will have a stronger connection compared to the linear function.
Use ConnRefXValue and ConnX to better parameterize lambda, which controls the decay of the connectivity
Definition at line 149 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.getConnectionValue(), and moa.evaluation.CMM_GTAnalysis.getParameterString().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/CMM_GTAnalysis.java