MOA: moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode Class Reference
moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode Class Reference
Public Member Functions
int calcByteSizeIncludingSubtree ()
AdaSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
AdaSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
int numberLeaves ()
double getErrorEstimation ()
double getErrorWidth ()
boolean isNullError ()
void learnFromInstance (Instance inst, HoeffdingAdaptiveTree ht, SplitNode parent, int parentBranch)
void killTreeChilds (HoeffdingAdaptiveTree ht)
void filterInstanceToLeaves (Instance inst, SplitNode myparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Public Attributes
boolean ErrorChange = false
Protected Attributes
Node alternateTree
ADWIN estimationErrorWeight
int randomSeed = 1
Random classifierRandom
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 90 of file HoeffdingAdaptiveTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.AdaSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
Definition at line 125 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.classifierRandom, and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.randomSeed.
{
            super(splitTest, classObservations, size);
            this.classifierRandom = new Random(this.randomSeed);
        }
moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.AdaSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Definition at line 131 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.classifierRandom, and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.randomSeed.
{
            super(splitTest, classObservations);
            this.classifierRandom = new Random(this.randomSeed);
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.calcByteSizeIncludingSubtree ()
Definition at line 109 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.alternateTree, moa.classifiers.trees.HoeffdingTree.calcByteSize(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight, and moa.AbstractMOAObject.measureByteSize().
{
            int byteSize = calcByteSize();
            if (alternateTree != null) {
                byteSize += alternateTree.calcByteSizeIncludingSubtree();
            }
            if (estimationErrorWeight != null) {
                byteSize += estimationErrorWeight.measureByteSize();
            }
            for (Node child : this.children) {
                if (child != null) {
                    byteSize += child.calcByteSizeIncludingSubtree();
                }
            }
            return byteSize;
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.filterInstanceToLeaves (Instance inst, SplitNode myparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Definition at line 280 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.alternateTree.
{
            if (updateSplitterCounts) {
                this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
            }
            int childIndex = instanceChildIndex(inst);
            if (childIndex >= 0) {
                Node child = getChild(childIndex);
                if (child != null) {
                    ((NewNode) child).filterInstanceToLeaves(inst, this, childIndex,
                            foundNodes, updateSplitterCounts);
                } else {
                    foundNodes.add(new FoundNode(null, this, childIndex));
                }
            }
            if (this.alternateTree != null) {
                ((NewNode) this.alternateTree).filterInstanceToLeaves(inst, this, -999,
                        foundNodes, updateSplitterCounts);
            }
        }
double moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorEstimation ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 149 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight, and moa.classifiers.core.driftdetection.ADWIN.getEstimation().
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
            return this.estimationErrorWeight.getEstimation();
        }
double moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorWidth ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 154 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight, moa.classifiers.core.driftdetection.ADWIN.getWidth(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.isNullError().
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
            double w = 0.0;
            if (isNullError() == false) {
                w = this.estimationErrorWeight.getWidth();
            }
            return w;
        }
boolean moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.isNullError ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 163 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorWidth(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
            return (this.estimationErrorWeight == null);
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds (HoeffdingAdaptiveTree ht)
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 255 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.alternateTree, moa.classifiers.trees.HoeffdingTree.inactiveLeafNodeCount, and moa.classifiers.trees.HoeffdingAdaptiveTree.prunedAlternateTrees.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
            for (Node child : this.children) {
                if (child != null) {
                    //Delete alternate tree if it exists
                    if (child instanceof AdaSplitNode && ((AdaSplitNode) child).alternateTree != null) {
                        ((NewNode) ((AdaSplitNode) child).alternateTree).killTreeChilds(ht);
                        ht.prunedAlternateTrees++;
                    }
                    //Recursive delete of SplitNodes
                    if (child instanceof AdaSplitNode) {
                        ((NewNode) child).killTreeChilds(ht);
                    }
                    if (child instanceof ActiveLearningNode) {
                        child = null;
                        ht.activeLeafNodeCount--;
                    } else if (child instanceof InactiveLearningNode) {
                        child = null;
                        ht.inactiveLeafNodeCount--;
                    }
                }
            }
        }
void moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance (Instance inst, HoeffdingAdaptiveTree ht, SplitNode parent, int parentBranch)
Definition at line 171 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.alternateTree, moa.classifiers.trees.HoeffdingAdaptiveTree.alternateTrees, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.classifierRandom, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.ErrorChange, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight, moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorEstimation(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorWidth(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.isNullError(), moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.killTreeChilds(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds(), moa.classifiers.trees.HoeffdingAdaptiveTree.newLearningNode(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.numberLeaves(), moa.classifiers.trees.HoeffdingAdaptiveTree.prunedAlternateTrees, moa.classifiers.core.driftdetection.ADWIN.setInput(), moa.classifiers.trees.HoeffdingAdaptiveTree.switchedAlternateTrees, and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
            int trueClass = (int) inst.classValue();
            //New option vore
            int k = MiscUtils.poisson(1.0, this.classifierRandom);
            Instance weightedInst = (Instance) inst.copy();
            if (k > 0) {
                //weightedInst.setWeight(inst.weight() * k);
            }
            //Compute ClassPrediction using filterInstanceToLeaf
            //int ClassPrediction = Utils.maxIndex(filterInstanceToLeaf(inst, null, -1).node.getClassVotes(inst, ht));
            int ClassPrediction = 0;
            if (filterInstanceToLeaf(inst, parent, parentBranch).node != null) {
                ClassPrediction = Utils.maxIndex(filterInstanceToLeaf(inst, parent, parentBranch).node.getClassVotes(inst, ht));
            }
            boolean blCorrect = (trueClass == ClassPrediction);
            if (this.estimationErrorWeight == null) {
                this.estimationErrorWeight = new ADWIN();
            }
            double oldError = this.getErrorEstimation();
            this.ErrorChange = this.estimationErrorWeight.setInput(blCorrect == true ? 0.0 : 1.0);
            if (this.ErrorChange == true && oldError > this.getErrorEstimation()) {
                //if error is decreasing, don't do anything
                this.ErrorChange = false;
            }
            // Check condition to build a new alternate tree
            //if (this.isAlternateTree == false) {
            if (this.ErrorChange == true) {//&& this.alternateTree == null) {
                //Start a new alternative tree : learning node
                this.alternateTree = ht.newLearningNode();
                //this.alternateTree.isAlternateTree = true;
                ht.alternateTrees++;
            } // Check condition to replace tree
            else if (this.alternateTree != null && ((NewNode) this.alternateTree).isNullError() == false) {
                if (this.getErrorWidth() > 300 && ((NewNode) this.alternateTree).getErrorWidth() > 300) {
                    double oldErrorRate = this.getErrorEstimation();
                    double altErrorRate = ((NewNode) this.alternateTree).getErrorEstimation();
                    double fDelta = .05;
                    //if (gNumAlts>0) fDelta=fDelta/gNumAlts;
                    double fN = 1.0 / ((double) ((NewNode) this.alternateTree).getErrorWidth()) + 1.0 / ((double) this.getErrorWidth());
                    double Bound = (double) Math.sqrt((double) 2.0 * oldErrorRate * (1.0 - oldErrorRate) * Math.log(2.0 / fDelta) * fN);
                    if (Bound < oldErrorRate - altErrorRate) {
                        // Switch alternate tree
                        ht.activeLeafNodeCount -= this.numberLeaves();
                        ht.activeLeafNodeCount += ((NewNode) this.alternateTree).numberLeaves();
                        killTreeChilds(ht);
                        if (parent != null) {
                            parent.setChild(parentBranch, this.alternateTree);
                            //((AdaSplitNode) parent.getChild(parentBranch)).alternateTree = null;
                        } else {
                            // Switch root tree
                            ht.treeRoot = ((AdaSplitNode) ht.treeRoot).alternateTree;
                        }
                        ht.switchedAlternateTrees++;
                    } else if (Bound < altErrorRate - oldErrorRate) {
                        // Erase alternate tree
                        if (this.alternateTree instanceof ActiveLearningNode) {
                            this.alternateTree = null;
                            //ht.activeLeafNodeCount--;
                        } else if (this.alternateTree instanceof InactiveLearningNode) {
                            this.alternateTree = null;
                            //ht.inactiveLeafNodeCount--;
                        } else {
                            ((AdaSplitNode) this.alternateTree).killTreeChilds(ht);
                        }
                        ht.prunedAlternateTrees++;
                    }
                }
            }
            //}
            //learnFromInstance alternate Tree and Child nodes
            if (this.alternateTree != null) {
                ((NewNode) this.alternateTree).learnFromInstance(weightedInst, ht, parent, parentBranch);
            }
            int childBranch = this.instanceChildIndex(inst);
            Node child = this.getChild(childBranch);
            if (child != null) {
                ((NewNode) child).learnFromInstance(weightedInst, ht, this, childBranch);
            }
        }
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.numberLeaves ()
Implements moa.classifiers.trees.HoeffdingAdaptiveTree.NewNode.
Definition at line 138 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
            int numLeaves = 0;
            for (Node child : this.children) {
                if (child != null) {
                    numLeaves += ((NewNode) child).numberLeaves();
                }
            }
            return numLeaves;
        }
Member Data Documentation
Node moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.alternateTree [protected]
Definition at line 94 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.filterInstanceToLeaves(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
Random moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.classifierRandom [protected]
Definition at line 103 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.AdaSplitNode(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
boolean moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.ErrorChange = false
Definition at line 99 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
ADWIN moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.estimationErrorWeight [protected]
Definition at line 96 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorEstimation(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorWidth(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.isNullError(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
int moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.randomSeed = 1 [protected]
Definition at line 101 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.AdaSplitNode().
final long moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.serialVersionUID = 1L [static, private]
Definition at line 92 of file HoeffdingAdaptiveTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingAdaptiveTree.java