MOA: moa.classifiers.active.ActiveClassifier Class Reference
moa.classifiers.active.ActiveClassifier Class Reference
Active learning setting for evolving data streams.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Public Attributes
ClassOption baseLearnerOption
MultiChoiceOption activeLearningStrategyOption
FloatOption budgetOption
FloatOption fixedThresholdOption
FloatOption stepOption
FloatOption numInstancesInitOption
Classifier classifier
int costLabeling
int costLabelingRandom
int iterationControl
double newThreshold
double maxPosterior
double accuracyBaseLearner
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Private Member Functions
double getMaxPosterior (double[] incomingPrediction)
void labelRandom (Instance inst)
void labelFixed (double incomingPosterior, Instance inst)
void labelVar (double incomingPosterior, Instance inst)
void labelSelSampling (double incomingPosterior, Instance inst)
Private Attributes
double outPosterior
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Active learning setting for evolving data streams.
Active learning focuses on learning an accurate model with as few labels as possible. Streaming data poses additional challenges for active learning, since the data distribution may change over time (concept drift) and classifiers need to adapt. Conventional active learning strategies concentrate on querying the most uncertain instances, which are typically concentrated around the decision boundary. If changes do not occur close to the boundary, they will be missed and classifiers will fail to adapt. This class contains four active learning strategies for streaming data that explicitly handle concept drift. They are based on randomization, fixed uncertainty, dynamic allocation of labeling efforts over time and randomization of the search space [ZBPH]. It also contains the Selective Sampling strategy, which is adapted from [CGZ] it uses a variable labeling threshold.
[ZBPH] Indre Zliobaite, Albert Bifet, Bernhard Pfahringer, Geoff Holmes: Active Learning with Evolving Streaming Data. ECML/PKDD (3) 2011: 597-612
[CGZ] N. Cesa-Bianchi, C. Gentile, and L. Zaniboni. Worst-case analysis of selective sampling for linear classification. J. Mach. Learn. Res. (7) 2006: 1205-1230.
Parameters:
-l : Classiﬁer to train
-d : Strategy to use: Random, FixedUncertainty, VarUncertainty, RandVarUncertainty, SelSampling
-b : Budget to use -u : Fixed threshold -s : Floating budget step -n : Number of instances at beginning without active learning
Author:
Indre Zliobaite (zliobaite at gmail dot com)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 73 of file ActiveClassifier.java.
Member Function Documentation
double moa.classifiers.active.ActiveClassifier.getMaxPosterior (double[] incomingPrediction) [private]
Definition at line 126 of file ActiveClassifier.java.
References moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.normalize(), moa.classifiers.active.ActiveClassifier.outPosterior, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        if (incomingPrediction.length > 1) {
            DoubleVector vote = new DoubleVector(incomingPrediction);
            if (vote.sumOfValues() > 0.0) {
                vote.normalize();
            }
            incomingPrediction = vote.getArrayRef();
            outPosterior = (incomingPrediction[Utils.maxIndex(incomingPrediction)]);
        } else {
            outPosterior = 0;
        }
        return outPosterior;
    }
void moa.classifiers.active.ActiveClassifier.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 241 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.classifier.
{
        ((AbstractClassifier) this.classifier).getModelDescription(out, indent);
    }
Measurement [] moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 246 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.accuracyBaseLearner, moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.active.ActiveClassifier.costLabeling, moa.classifiers.active.ActiveClassifier.maxPosterior, and moa.classifiers.active.ActiveClassifier.newThreshold.
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        measurementList.add(new Measurement("labeling cost", this.costLabeling));
        measurementList.add(new Measurement("newThreshold", this.newThreshold));
        measurementList.add(new Measurement("maxPosterior", this.maxPosterior));
        measurementList.add(new Measurement("accuracyBaseLearner (percent)", 100 * this.accuracyBaseLearner / this.costLabeling));
        Measurement[] modelMeasurements = ((AbstractClassifier) this.classifier).getModelMeasurements();
        if (modelMeasurements != null) {
            for (Measurement measurement : modelMeasurements) {
                measurementList.add(measurement);
            }
        }
        return measurementList.toArray(new Measurement[measurementList.size()]);
    }
String moa.classifiers.active.ActiveClassifier.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 78 of file ActiveClassifier.java.
{
        return "Active learning classifier for evolving data streams";
    }
double [] moa.classifiers.active.ActiveClassifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 231 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.classifier, and moa.classifiers.Classifier.getVotesForInstance().
{
        return this.classifier.getVotesForInstance(inst);
    }
boolean moa.classifiers.active.ActiveClassifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 236 of file ActiveClassifier.java.
{
        return true;
    }
void moa.classifiers.active.ActiveClassifier.labelFixed (double incomingPosterior, Instance inst) [private]
Definition at line 149 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.active.ActiveClassifier.costLabeling, moa.classifiers.active.ActiveClassifier.fixedThresholdOption, moa.options.FloatOption.getValue(), and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        if (incomingPosterior < this.fixedThresholdOption.getValue()) {
            this.classifier.trainOnInstance(inst);
            this.costLabeling++;
        }
    }
void moa.classifiers.active.ActiveClassifier.labelRandom (Instance inst) [private]
Definition at line 140 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.budgetOption, moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.active.ActiveClassifier.costLabeling, moa.classifiers.active.ActiveClassifier.costLabelingRandom, moa.options.FloatOption.getValue(), and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        if (this.classifierRandom.nextDouble() < this.budgetOption.getValue()) {
            this.classifier.trainOnInstance(inst);
            this.costLabeling++;
            this.costLabelingRandom++;
        }
    }
void moa.classifiers.active.ActiveClassifier.labelSelSampling (double incomingPosterior, Instance inst) [private]
Definition at line 166 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.budgetOption, moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.active.ActiveClassifier.costLabeling, moa.options.FloatOption.getValue(), and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        double p = Math.abs(incomingPosterior - 1.0 / (inst.numClasses()));
        double budget = this.budgetOption.getValue() / (this.budgetOption.getValue() + p);
        if (this.classifierRandom.nextDouble() < budget) {
            this.classifier.trainOnInstance(inst);
            this.costLabeling++;
        }
    }
void moa.classifiers.active.ActiveClassifier.labelVar (double incomingPosterior, Instance inst) [private]
Definition at line 156 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.active.ActiveClassifier.costLabeling, moa.options.FloatOption.getValue(), moa.classifiers.active.ActiveClassifier.newThreshold, moa.classifiers.active.ActiveClassifier.stepOption, and moa.classifiers.Classifier.trainOnInstance().
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
{
        if (incomingPosterior < this.newThreshold) {
            this.classifier.trainOnInstance(inst);
            this.costLabeling++;
            this.newThreshold *= (1 - this.stepOption.getValue());
        } else {
            this.newThreshold *= (1 + this.stepOption.getValue());
        }
    }
void moa.classifiers.active.ActiveClassifier.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 176 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.accuracyBaseLearner, moa.classifiers.active.ActiveClassifier.baseLearnerOption, moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.AbstractClassifier.copy(), moa.classifiers.active.ActiveClassifier.costLabeling, moa.classifiers.active.ActiveClassifier.costLabelingRandom, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.active.ActiveClassifier.iterationControl, moa.classifiers.active.ActiveClassifier.newThreshold, and moa.classifiers.Classifier.resetLearning().
{
        this.classifier = ((Classifier) getPreparedClassOption(this.baseLearnerOption)).copy();
        this.classifier.resetLearning();
        this.costLabeling = 0;
        this.costLabelingRandom = 0;
        this.iterationControl = 0;
        this.newThreshold = 1.0;
        this.accuracyBaseLearner = 0;
    }
void moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 187 of file ActiveClassifier.java.
References moa.classifiers.active.ActiveClassifier.activeLearningStrategyOption, moa.classifiers.active.ActiveClassifier.budgetOption, moa.classifiers.active.ActiveClassifier.classifier, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.active.ActiveClassifier.costLabeling, moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.active.ActiveClassifier.getMaxPosterior(), moa.options.FloatOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.active.ActiveClassifier.iterationControl, moa.classifiers.active.ActiveClassifier.labelFixed(), moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.active.ActiveClassifier.labelVar(), moa.classifiers.active.ActiveClassifier.maxPosterior, moa.classifiers.active.ActiveClassifier.numInstancesInitOption, and moa.classifiers.Classifier.trainOnInstance().
{
        this.iterationControl++;
        double costNow;
        if (this.iterationControl <= this.numInstancesInitOption.getValue()) {
            costNow = 0;
            //Use all instances at the beginning
            this.classifier.trainOnInstance(inst);
        this.costLabeling++;
            return;
        } else {
            costNow = (this.costLabeling - this.numInstancesInitOption.getValue()) / ((double) this.iterationControl - this.numInstancesInitOption.getValue());
        }
        if (costNow < this.budgetOption.getValue()) { //allow to label
            switch (this.activeLearningStrategyOption.getChosenIndex()) {
                case 0: //Random
                    labelRandom(inst);
                    break;
                case 1: //fixed
                    maxPosterior = getMaxPosterior(this.classifier.getVotesForInstance(inst));
                    labelFixed(maxPosterior, inst);
                    break;
                case 2: //variable
                    maxPosterior = getMaxPosterior(this.classifier.getVotesForInstance(inst));
                    labelVar(maxPosterior, inst);
                    break;
                case 3: //randomized
                    maxPosterior = getMaxPosterior(this.classifier.getVotesForInstance(inst));
                    maxPosterior = maxPosterior / (this.classifierRandom.nextGaussian() + 1.0);
                    labelVar(maxPosterior, inst);
                    break;
                case 4: //selective-sampling
                    maxPosterior = getMaxPosterior(this.classifier.getVotesForInstance(inst));
                    labelSelSampling(maxPosterior, inst);
                    break;
            }
        }
    }
Member Data Documentation
double moa.classifiers.active.ActiveClassifier.accuracyBaseLearner
Definition at line 122 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl(), and moa.classifiers.active.ActiveClassifier.resetLearningImpl().
MultiChoiceOption moa.classifiers.active.ActiveClassifier.activeLearningStrategyOption
Initial value:
 new MultiChoiceOption(
            "activeLearningStrategy", 'd', "Active Learning Strategy to use.", new String[]{
                "Random", "FixedUncertainty", "VarUncertainty", "RandVarUncertainty", "SelSampling"}, new String[]{
                "Random strategy",
                "Fixed uncertainty strategy",
                "Uncertainty strategy with variable threshold",
                "Uncertainty strategy with randomized variable threshold",
                "Selective Sampling"}, 0)
Definition at line 85 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
ClassOption moa.classifiers.active.ActiveClassifier.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "drift.SingleClassifierDrift")
Definition at line 82 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.resetLearningImpl().
FloatOption moa.classifiers.active.ActiveClassifier.budgetOption
Initial value:
 new FloatOption("budget",
            'b', "Budget to use.",
            0.1, 0.0, 1.0)
Definition at line 94 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
Classifier moa.classifiers.active.ActiveClassifier.classifier
Definition at line 110 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getModelDescription(), moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl(), moa.classifiers.active.ActiveClassifier.getVotesForInstance(), moa.classifiers.active.ActiveClassifier.labelFixed(), moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.active.ActiveClassifier.labelVar(), moa.classifiers.active.ActiveClassifier.resetLearningImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
int moa.classifiers.active.ActiveClassifier.costLabeling
Definition at line 112 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl(), moa.classifiers.active.ActiveClassifier.labelFixed(), moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.active.ActiveClassifier.labelVar(), moa.classifiers.active.ActiveClassifier.resetLearningImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
int moa.classifiers.active.ActiveClassifier.costLabelingRandom
Definition at line 114 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.labelRandom(), and moa.classifiers.active.ActiveClassifier.resetLearningImpl().
FloatOption moa.classifiers.active.ActiveClassifier.fixedThresholdOption
Initial value:
 new FloatOption("fixedThreshold",
            'u', "Fixed threshold.",
            0.9, 0.00, 1.00)
Definition at line 98 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.labelFixed().
int moa.classifiers.active.ActiveClassifier.iterationControl
Definition at line 116 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.resetLearningImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
double moa.classifiers.active.ActiveClassifier.maxPosterior
Definition at line 120 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
double moa.classifiers.active.ActiveClassifier.newThreshold
Definition at line 118 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getModelMeasurementsImpl(), moa.classifiers.active.ActiveClassifier.labelVar(), and moa.classifiers.active.ActiveClassifier.resetLearningImpl().
FloatOption moa.classifiers.active.ActiveClassifier.numInstancesInitOption
Initial value:
 new FloatOption("numInstancesInit",
            'n', "Number of instances at beginning without active learning.",
            0.0, 0.00, Integer.MAX_VALUE)
Definition at line 106 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
double moa.classifiers.active.ActiveClassifier.outPosterior [private]
Definition at line 124 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.getMaxPosterior().
final long moa.classifiers.active.ActiveClassifier.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 75 of file ActiveClassifier.java.
FloatOption moa.classifiers.active.ActiveClassifier.stepOption
Initial value:
 new FloatOption("step",
            's', "Floating budget step.",
            0.01, 0.00, 1.00)
Definition at line 102 of file ActiveClassifier.java.
Referenced by moa.classifiers.active.ActiveClassifier.labelVar().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/active/ActiveClassifier.java