MOA: moa.streams.clustering.ClusteringStream Class Reference
moa.streams.clustering.ClusteringStream Class Reference
Public Member Functions
int getDecayHorizon ()
double getDecayThreshold ()
int getEvaluationFrequency ()
Public Attributes
IntOption decayHorizonOption
FloatOption decayThresholdOption
IntOption evaluationFrequencyOption
IntOption numAttsOption
Detailed Description
Definition at line 28 of file ClusteringStream.java.
Member Function Documentation
int moa.streams.clustering.ClusteringStream.getDecayHorizon ()
Definition at line 41 of file ClusteringStream.java.
References moa.streams.clustering.ClusteringStream.decayHorizonOption, and moa.options.IntOption.getValue().
Referenced by moa.gui.BatchCmd.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return decayHorizonOption.getValue();
    }
double moa.streams.clustering.ClusteringStream.getDecayThreshold ()
Definition at line 45 of file ClusteringStream.java.
References moa.streams.clustering.ClusteringStream.decayThresholdOption, and moa.options.FloatOption.getValue().
Referenced by moa.gui.BatchCmd.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return decayThresholdOption.getValue();
    }
int moa.streams.clustering.ClusteringStream.getEvaluationFrequency ()
Definition at line 49 of file ClusteringStream.java.
References moa.streams.clustering.ClusteringStream.evaluationFrequencyOption, and moa.options.IntOption.getValue().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return evaluationFrequencyOption.getValue();
    }
Member Data Documentation
IntOption moa.streams.clustering.ClusteringStream.decayHorizonOption
Initial value:
 new IntOption("decayHorizon", 'h',
                    "Decay horizon", 1000, 0, Integer.MAX_VALUE)
Definition at line 29 of file ClusteringStream.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.ClusteringStream.getDecayHorizon(), moa.gui.BatchCmd.runBatch(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
FloatOption moa.streams.clustering.ClusteringStream.decayThresholdOption
Initial value:
 new FloatOption("decayThreshold", 't',
                    "Decay horizon threshold", 0.01, 0, 1)
Definition at line 32 of file ClusteringStream.java.
Referenced by moa.streams.clustering.ClusteringStream.getDecayThreshold().
IntOption moa.streams.clustering.ClusteringStream.evaluationFrequencyOption
Initial value:
 new IntOption("evaluationFrequency", 'e',
                    "Evaluation frequency", 1000, 0, Integer.MAX_VALUE)
Definition at line 35 of file ClusteringStream.java.
Referenced by moa.streams.clustering.ClusteringStream.getEvaluationFrequency().
IntOption moa.streams.clustering.ClusteringStream.numAttsOption
Initial value:
 new IntOption("numAtts", 'a',
                    "The number of attributes to generate.", 2, 0, Integer.MAX_VALUE)
Definition at line 38 of file ClusteringStream.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.streams.clustering.FileStream.FileStream(), moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.streams.clustering.FileStream.restart(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunVisualizer.RunVisualizer(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation().
The documentation for this class was generated from the following file:
main/java/moa/streams/clustering/ClusteringStream.java