MOA: moa.tasks.StandardTaskMonitor Class Reference
moa.tasks.StandardTaskMonitor Class Reference
Class that represents a standard task monitor.
Public Member Functions
void setCurrentActivity (String activityDescription, double fracComplete)
Sets the description and the percentage done of the current activity.
void setCurrentActivityDescription (String activity)
Sets the description of the current activity.
void setCurrentActivityFractionComplete (double fracComplete)
Sets the percentage done of the current activity.
boolean taskShouldAbort ()
Gets whether the task should abort.
String getCurrentActivityDescription ()
Gets the description of the current activity.
double getCurrentActivityFractionComplete ()
Gets the percentage done of the current activity.
boolean isCancelled ()
Gets whether the task monitored is cancelled.
void requestCancel ()
Requests the task monitored to cancel.
void requestPause ()
Requests the task monitored to pause.
synchronized void requestResume ()
Requests the task monitored to resume.
boolean isPaused ()
Gets whether the task monitored is paused.
Object getLatestResultPreview ()
Gets the current result to preview.
void requestResultPreview ()
Requests to preview the task result.
void requestResultPreview (ResultPreviewListener toInform)
Requests to preview the task result.
boolean resultPreviewRequested ()
Gets whether there is a request for preview the task result.
synchronized void setLatestResultPreview (Object latestPreview)
Sets the current result to preview.
Protected Attributes
String currentActivityDescription = ""
double currentActivityFractionComplete = -1.0
volatile boolean cancelFlag = false
volatile boolean pauseFlag = false
volatile boolean isComplete = false
volatile boolean resultPreviewRequested = false
volatile Object latestResultPreview = null
volatile ResultPreviewListener resultPreviewer = null
Detailed Description
Class that represents a standard task monitor.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 28 of file StandardTaskMonitor.java.
Member Function Documentation
String moa.tasks.StandardTaskMonitor.getCurrentActivityDescription ()
Gets the description of the current activity.
Returns:
the description of the current activity
Implements moa.tasks.TaskMonitor.
Definition at line 79 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.currentActivityDescription.
{
        return this.currentActivityDescription;
    }
double moa.tasks.StandardTaskMonitor.getCurrentActivityFractionComplete ()
Gets the percentage done of the current activity.
Returns:
the percentage done of the current activity
Implements moa.tasks.TaskMonitor.
Definition at line 84 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.currentActivityFractionComplete.
{
        return this.currentActivityFractionComplete;
    }
Object moa.tasks.StandardTaskMonitor.getLatestResultPreview ()
Gets the current result to preview.
Returns:
the result to preview
Implements moa.tasks.TaskMonitor.
Definition at line 116 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.latestResultPreview.
{
        return this.latestResultPreview;
    }
boolean moa.tasks.StandardTaskMonitor.isCancelled ()
Gets whether the task monitored is cancelled.
Returns:
true if the task is cancelled
Implements moa.tasks.TaskMonitor.
Definition at line 89 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.cancelFlag.
{
        return this.cancelFlag;
    }
boolean moa.tasks.StandardTaskMonitor.isPaused ()
Gets whether the task monitored is paused.
Returns:
true if the task is paused
Implements moa.tasks.TaskMonitor.
Definition at line 111 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.pauseFlag.
{
        return this.pauseFlag;
    }
void moa.tasks.StandardTaskMonitor.requestCancel ()
Requests the task monitored to cancel.
Implements moa.tasks.TaskMonitor.
Definition at line 94 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.cancelFlag, and moa.tasks.StandardTaskMonitor.requestResume().
{
        this.cancelFlag = true;
        requestResume();
    }
void moa.tasks.StandardTaskMonitor.requestPause ()
Requests the task monitored to pause.
Implements moa.tasks.TaskMonitor.
Definition at line 100 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.pauseFlag.
{
        this.pauseFlag = true;
    }
void moa.tasks.StandardTaskMonitor.requestResultPreview (ResultPreviewListener toInform)
Requests to preview the task result.
Parameters:
toInform the listener of the changes in the preview of the result
Implements moa.tasks.TaskMonitor.
Definition at line 126 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.resultPreviewer, and moa.tasks.StandardTaskMonitor.resultPreviewRequested().
{
        this.resultPreviewer = toInform;
        this.resultPreviewRequested = true;
    }
void moa.tasks.StandardTaskMonitor.requestResultPreview ()
Requests to preview the task result.
Implements moa.tasks.TaskMonitor.
Definition at line 121 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.resultPreviewRequested().
{
        this.resultPreviewRequested = true;
    }
synchronized void moa.tasks.StandardTaskMonitor.requestResume ()
Requests the task monitored to resume.
Implements moa.tasks.TaskMonitor.
Definition at line 105 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.pauseFlag.
Referenced by moa.tasks.StandardTaskMonitor.requestCancel().
{
        this.pauseFlag = false;
        notify();
    }
boolean moa.tasks.StandardTaskMonitor.resultPreviewRequested ()
Gets whether there is a request for preview the task result.
Returns:
true if there is a request for preview the task result
Implements moa.tasks.TaskMonitor.
Definition at line 132 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.requestResultPreview(), and moa.tasks.StandardTaskMonitor.setLatestResultPreview().
{
        return this.resultPreviewRequested;
    }
void moa.tasks.StandardTaskMonitor.setCurrentActivity (String activityDescription, double fracComplete)
Sets the description and the percentage done of the current activity.
Parameters:
activity the description of the current activity
fracComplete the percentage done of the current activity
Implements moa.tasks.TaskMonitor.
Definition at line 47 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.setCurrentActivityDescription(), and moa.tasks.StandardTaskMonitor.setCurrentActivityFractionComplete().
{
        setCurrentActivityDescription(activityDescription);
        setCurrentActivityFractionComplete(fracComplete);
    }
void moa.tasks.StandardTaskMonitor.setCurrentActivityDescription (String activity)
Sets the description of the current activity.
Parameters:
activity the description of the current activity
Implements moa.tasks.TaskMonitor.
Definition at line 54 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.currentActivityDescription.
Referenced by moa.tasks.StandardTaskMonitor.setCurrentActivity().
{
        this.currentActivityDescription = activity;
    }
void moa.tasks.StandardTaskMonitor.setCurrentActivityFractionComplete (double fracComplete)
Sets the percentage done of the current activity.
Parameters:
fracComplete the percentage done of the current activity
Implements moa.tasks.TaskMonitor.
Definition at line 59 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.currentActivityFractionComplete.
Referenced by moa.tasks.StandardTaskMonitor.setCurrentActivity().
{
        this.currentActivityFractionComplete = fracComplete;
    }
synchronized void moa.tasks.StandardTaskMonitor.setLatestResultPreview (Object latestPreview)
Sets the current result to preview.
Parameters:
latestPreview the result to preview
Implements moa.tasks.TaskMonitor.
Definition at line 137 of file StandardTaskMonitor.java.
References moa.tasks.ResultPreviewListener.latestPreviewChanged(), moa.tasks.StandardTaskMonitor.latestResultPreview, moa.tasks.StandardTaskMonitor.resultPreviewer, and moa.tasks.StandardTaskMonitor.resultPreviewRequested().
{
        this.resultPreviewRequested = false;
        this.latestResultPreview = latestPreview;
        if (this.resultPreviewer != null) {
            this.resultPreviewer.latestPreviewChanged();
        }
        this.resultPreviewer = null;
    }
boolean moa.tasks.StandardTaskMonitor.taskShouldAbort ()
Gets whether the task should abort.
Returns:
true if the task should abort
Implements moa.tasks.TaskMonitor.
Definition at line 64 of file StandardTaskMonitor.java.
References moa.tasks.StandardTaskMonitor.cancelFlag, and moa.tasks.StandardTaskMonitor.pauseFlag.
{
        if (this.pauseFlag) {
            try {
                synchronized (this) {
                    while (this.pauseFlag && !this.cancelFlag) {
                        wait();
                    }
                }
            } catch (InterruptedException e) {
            }
        }
        return this.cancelFlag;
    }
Member Data Documentation
volatile boolean moa.tasks.StandardTaskMonitor.cancelFlag = false [protected]
Definition at line 34 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.isCancelled(), moa.tasks.StandardTaskMonitor.requestCancel(), and moa.tasks.StandardTaskMonitor.taskShouldAbort().
String moa.tasks.StandardTaskMonitor.currentActivityDescription = "" [protected]
Definition at line 30 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.getCurrentActivityDescription(), and moa.tasks.StandardTaskMonitor.setCurrentActivityDescription().
double moa.tasks.StandardTaskMonitor.currentActivityFractionComplete = -1.0 [protected]
Definition at line 32 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.getCurrentActivityFractionComplete(), and moa.tasks.StandardTaskMonitor.setCurrentActivityFractionComplete().
volatile boolean moa.tasks.StandardTaskMonitor.isComplete = false [protected]
Definition at line 38 of file StandardTaskMonitor.java.
volatile Object moa.tasks.StandardTaskMonitor.latestResultPreview = null [protected]
Definition at line 42 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.getLatestResultPreview(), and moa.tasks.StandardTaskMonitor.setLatestResultPreview().
volatile boolean moa.tasks.StandardTaskMonitor.pauseFlag = false [protected]
Definition at line 36 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.isPaused(), moa.tasks.StandardTaskMonitor.requestPause(), moa.tasks.StandardTaskMonitor.requestResume(), and moa.tasks.StandardTaskMonitor.taskShouldAbort().
volatile ResultPreviewListener moa.tasks.StandardTaskMonitor.resultPreviewer = null [protected]
Definition at line 44 of file StandardTaskMonitor.java.
Referenced by moa.tasks.StandardTaskMonitor.requestResultPreview(), and moa.tasks.StandardTaskMonitor.setLatestResultPreview().
volatile boolean moa.tasks.StandardTaskMonitor.resultPreviewRequested = false [protected]
Definition at line 40 of file StandardTaskMonitor.java.
The documentation for this class was generated from the following file:
main/java/moa/tasks/StandardTaskMonitor.java