MOA: moa.classifiers.trees.HoeffdingAdaptiveTree Class Reference
moa.classifiers.trees.HoeffdingAdaptiveTree Class Reference
Hoeffding Adaptive Tree for evolving data streams.
Classes
class AdaLearningNode
class AdaSplitNode
interface NewNode
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
FoundNode[] filterInstanceToLeaves (Instance inst, SplitNode parent, int parentBranch, boolean updateSplitterCounts)
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
Protected Member Functions
LearningNode newLearningNode (double[] initialClassObservations)
SplitNode newSplitNode (InstanceConditionalTest splitTest, double[] classObservations)
SplitNode newSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size)
Protected Attributes
int alternateTrees
int prunedAlternateTrees
int switchedAlternateTrees
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Hoeffding Adaptive Tree for evolving data streams.
This adaptive Hoeffding Tree uses ADWIN to monitor performance of branches on the tree and to replace them with new branches when their accuracy decreases if the new branches are more accurate. See details in:
Adaptive Learning from Evolving Data Streams. Albert Bifet, Ricard Gavaldà. IDA 2009
Same parameters as HoeffdingTreeNBAdaptive
-l : Leaf prediction to use: MajorityClass (MC), Naive Bayes (NB) or NaiveBayes adaptive (NBAdaptive).
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 54 of file HoeffdingAdaptiveTree.java.
Member Function Documentation
FoundNode [] moa.classifiers.trees.HoeffdingAdaptiveTree.filterInstanceToLeaves (Instance inst, SplitNode parent, int parentBranch, boolean updateSplitterCounts)
Definition at line 473 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingTree.treeRoot.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance().
{
        List<FoundNode> nodes = new LinkedList<FoundNode>();
        ((NewNode) this.treeRoot).filterInstanceToLeaves(inst, parent, parentBranch, nodes,
                updateSplitterCounts);
        return nodes.toArray(new FoundNode[nodes.size()]);
    }
String moa.classifiers.trees.HoeffdingAdaptiveTree.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 59 of file HoeffdingAdaptiveTree.java.
{
        return "Hoeffding Adaptive Tree for evolving data streams that uses ADWIN to replace branches for new ones.";
    }
double [] moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 482 of file HoeffdingAdaptiveTree.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.trees.HoeffdingAdaptiveTree.filterInstanceToLeaves(), moa.core.DoubleVector.getArrayRef(), moa.classifiers.trees.HoeffdingTree.Node.getClassVotes(), and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        if (this.treeRoot != null) {
            FoundNode[] foundNodes = filterInstanceToLeaves(inst,
                    null, -1, false);
            DoubleVector result = new DoubleVector();
            int predictionPaths = 0;
            for (FoundNode foundNode : foundNodes) {
                if (foundNode.parentBranch != -999) {
                    Node leafNode = foundNode.node;
                    if (leafNode == null) {
                        leafNode = foundNode.parent;
                    }
                    double[] dist = leafNode.getClassVotes(inst, this);
                    //Albert: changed for weights
                    //double distSum = Utils.sum(dist);
                    //if (distSum > 0.0) {
                    //  Utils.normalize(dist, distSum);
                    //}
                    result.addValues(dist);
                    //predictionPaths++;
                }
            }
            //if (predictionPaths > this.maxPredictionPaths) {
            //  this.maxPredictionPaths++;
            //}
            return result.getArrayRef();
        }
        return new double[0];
    }
LearningNode moa.classifiers.trees.HoeffdingAdaptiveTree.newLearningNode (double[] initialClassObservations) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 445 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
{
        // IDEA: to choose different learning nodes depending on predictionOption
        return new AdaLearningNode(initialClassObservations);
    }
SplitNode moa.classifiers.trees.HoeffdingAdaptiveTree.newSplitNode (InstanceConditionalTest splitTest, double[] classObservations, int size) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 458 of file HoeffdingAdaptiveTree.java.
{
        return new AdaSplitNode(splitTest, classObservations, size);
    }
SplitNode moa.classifiers.trees.HoeffdingAdaptiveTree.newSplitNode (InstanceConditionalTest splitTest, double[] classObservations) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 452 of file HoeffdingAdaptiveTree.java.
{
        return new AdaSplitNode(splitTest, classObservations);
    }
void moa.classifiers.trees.HoeffdingAdaptiveTree.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 464 of file HoeffdingAdaptiveTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.newLearningNode(), and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        if (this.treeRoot == null) {
            this.treeRoot = newLearningNode();
            this.activeLeafNodeCount = 1;
        }
        ((NewNode) this.treeRoot).learnFromInstance(inst, this, null, -1);
    }
Member Data Documentation
int moa.classifiers.trees.HoeffdingAdaptiveTree.alternateTrees [protected]
Definition at line 438 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
int moa.classifiers.trees.HoeffdingAdaptiveTree.prunedAlternateTrees [protected]
Definition at line 440 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.killTreeChilds(), and moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
final long moa.classifiers.trees.HoeffdingAdaptiveTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 56 of file HoeffdingAdaptiveTree.java.
int moa.classifiers.trees.HoeffdingAdaptiveTree.switchedAlternateTrees [protected]
Definition at line 442 of file HoeffdingAdaptiveTree.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingAdaptiveTree.java