MOA: moa.clusterers.macro.dbscan.DenseMicroCluster Class Reference
moa.clusterers.macro.dbscan.DenseMicroCluster Class Reference
Public Member Functions
DenseMicroCluster (CFCluster mc)
void setVisited ()
boolean isVisited ()
void setClustered ()
boolean isClustered ()
CFCluster getCFCluster ()
Private Attributes
CFCluster mCluster
boolean mVisited
boolean mIsClustered
Detailed Description
Definition at line 28 of file DenseMicroCluster.java.
Constructor & Destructor Documentation
moa.clusterers.macro.dbscan.DenseMicroCluster.DenseMicroCluster (CFCluster mc)
Definition at line 34 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mCluster, and moa.clusterers.macro.dbscan.DenseMicroCluster.mVisited.
{
        mCluster = mc;
        mVisited = false;
    }
Member Function Documentation
CFCluster moa.clusterers.macro.dbscan.DenseMicroCluster.getCFCluster ()
Definition at line 55 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mCluster.
Referenced by moa.clusterers.macro.dbscan.DBScan.getNeighbourhood().
{
        return mCluster;
    }
boolean moa.clusterers.macro.dbscan.DenseMicroCluster.isClustered ()
Definition at line 51 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mIsClustered.
Referenced by moa.clusterers.macro.dbscan.DBScan.expandCluster().
{
        return mIsClustered;
    }
boolean moa.clusterers.macro.dbscan.DenseMicroCluster.isVisited ()
Definition at line 43 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mVisited.
Referenced by moa.clusterers.macro.dbscan.DBScan.expandCluster().
{
        return mVisited;
    }
void moa.clusterers.macro.dbscan.DenseMicroCluster.setClustered ()
Definition at line 47 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mIsClustered.
Referenced by moa.clusterers.macro.dbscan.DBScan.expandCluster().
{
        mIsClustered = true;
    }
void moa.clusterers.macro.dbscan.DenseMicroCluster.setVisited ()
Definition at line 39 of file DenseMicroCluster.java.
References moa.clusterers.macro.dbscan.DenseMicroCluster.mVisited.
Referenced by moa.clusterers.macro.dbscan.DBScan.expandCluster().
{
        mVisited = true;
    }
Member Data Documentation
CFCluster moa.clusterers.macro.dbscan.DenseMicroCluster.mCluster [private]
Definition at line 30 of file DenseMicroCluster.java.
Referenced by moa.clusterers.macro.dbscan.DenseMicroCluster.DenseMicroCluster(), and moa.clusterers.macro.dbscan.DenseMicroCluster.getCFCluster().
boolean moa.clusterers.macro.dbscan.DenseMicroCluster.mIsClustered [private]
Definition at line 32 of file DenseMicroCluster.java.
Referenced by moa.clusterers.macro.dbscan.DenseMicroCluster.isClustered(), and moa.clusterers.macro.dbscan.DenseMicroCluster.setClustered().
boolean moa.clusterers.macro.dbscan.DenseMicroCluster.mVisited [private]
Definition at line 31 of file DenseMicroCluster.java.
Referenced by moa.clusterers.macro.dbscan.DenseMicroCluster.DenseMicroCluster(), moa.clusterers.macro.dbscan.DenseMicroCluster.isVisited(), and moa.clusterers.macro.dbscan.DenseMicroCluster.setVisited().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/macro/dbscan/DenseMicroCluster.java