MOA: moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide Class Reference
moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide Class Reference
The class that splits a node into two based on the midpoint value of the dimension in which the node's rectangle is widest.
Public Member Functions
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
void splitNode (KDTreeNode node, int numNodesCreated, double[][] nodeRanges, double[][] universe) throws Exception
Splits a node into two based on the midpoint value of the dimension in which the node's rectangle is widest.
Protected Member Functions
int rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal)
Re-arranges the indices array such that the points <= to the splitVal are on the left of the array and those > the splitVal are on the right.
Static Protected Attributes
static double ERR = 0.001
The floating point error to tolerate in finding the widest rectangular side.
Static Private Attributes
static final long serialVersionUID = 852857628205680562L
for serialization.
Detailed Description
The class that splits a node into two based on the midpoint value of the dimension in which the node's rectangle is widest.
If after splitting one side is empty then it is slided towards the non-empty side until there is at least one point on the empty side.
For more information see also:
David M. Mount (2006). ANN Programming Manual. College Park, MD, USA.
BibTeX:
 &#64;manual{Mount2006,
    address = {College Park, MD, USA},
    author = {David M. Mount},
    organization = {Department of Computer Science, University of Maryland},
    title = {ANN Programming Manual},
    year = {2006},
    HTTP = {Available from http://www.cs.umd.edu/
Definition at line 55 of file SlidingMidPointOfWidestSide.java.
Member Function Documentation
String moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Definition at line 71 of file SlidingMidPointOfWidestSide.java.
{
    return
        "The class that splits a node into two based on the midpoint value of "
      + "the dimension in which the node's rectangle is widest. If after "
      + "splitting one side is empty then it is slided towards the non-empty "
      + "side until there is at least one point on the empty side.\n\n"
      + "For more information see also:\n\n";
  }
int moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal) [protected]
Re-arranges the indices array such that the points <= to the splitVal are on the left of the array and those > the splitVal are on the right.
Parameters:
indices The master index array.
startidx The begining index of portion of indices that needs re-arranging.
endidx The end index of portion of indices that needs re-arranging.
splitDim The split dimension/attribute.
splitVal The split value.
Returns:
The startIdx of the points > the splitVal (the points belonging to the right child of the node).
Definition at line 213 of file SlidingMidPointOfWidestSide.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, and moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual().
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.splitNode().
{
    int tmp, left = startidx - 1;
    for (int i = startidx; i <= endidx; i++) {
      if (m_EuclideanDistance.valueIsSmallerEqual(m_Instances
          .instance(indices[i]), splitDim, splitVal)) {
        left++;
        tmp = indices[left];
        indices[left] = indices[i];
        indices[i] = tmp;
      }// end valueIsSmallerEqual
    }// endfor
    return left + 1;
  }
void moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.splitNode (KDTreeNode node, int numNodesCreated, double nodeRanges[][], double universe[][]) throws Exception [virtual]
Splits a node into two based on the midpoint value of the dimension in which the node's rectangle is widest.
If after splitting one side is empty then it is slided towards the non-empty side until there is at least one point on the empty side. The two nodes created after the whole splitting are correctly initialised. And, node.left and node.right are set appropriately.
Parameters:
node The node to split.
numNodesCreated The number of nodes that so far have been created for the tree, so that the newly created nodes are assigned correct/meaningful node numbers/ids.
nodeRanges The attributes' range for the points inside the node that is to be split.
universe The attributes' range for the whole point-space.
Exceptions:
Exception If there is some problem in splitting the given node.
Implements moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.
Definition at line 99 of file SlidingMidPointOfWidestSide.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.correctlyInitialized(), moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.ERR, moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_InstList, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_NodesRectBounds, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_NormalizeNodeWidth, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Right, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.MAX, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.MIN, moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.rearrangePoints(), and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.WIDTH.
{
    correctlyInitialized();
    if (node.m_NodesRectBounds == null) {
      node.m_NodesRectBounds = new double[2][node.m_NodeRanges.length];
      for (int i = 0; i < node.m_NodeRanges.length; i++) {
        node.m_NodesRectBounds[MIN][i] = node.m_NodeRanges[i][MIN];
        node.m_NodesRectBounds[MAX][i] = node.m_NodeRanges[i][MAX];
      }
    }
    // finding widest side of the hyper rectangle
    double maxRectWidth = Double.NEGATIVE_INFINITY, maxPtWidth = Double.NEGATIVE_INFINITY, tempval;
    int splitDim = -1, classIdx = m_Instances.classIndex();
    for (int i = 0; i < node.m_NodesRectBounds[0].length; i++) {
      if (i == classIdx)
        continue;
      tempval = node.m_NodesRectBounds[MAX][i] - node.m_NodesRectBounds[MIN][i];
      if (m_NormalizeNodeWidth) {
        tempval = tempval / universe[i][WIDTH];
      }
      if (tempval > maxRectWidth && node.m_NodeRanges[i][WIDTH] > 0.0)
        maxRectWidth = tempval;
    }
    for (int i = 0; i < node.m_NodesRectBounds[0].length; i++) {
      if (i == classIdx)
        continue;
      tempval = node.m_NodesRectBounds[MAX][i] - node.m_NodesRectBounds[MIN][i];
      if (m_NormalizeNodeWidth) {
        tempval = tempval / universe[i][WIDTH];
      }
      if (tempval >= maxRectWidth * (1 - ERR)
          && node.m_NodeRanges[i][WIDTH] > 0.0) {
        if (node.m_NodeRanges[i][WIDTH] > maxPtWidth) {
          maxPtWidth = node.m_NodeRanges[i][WIDTH];
          if (m_NormalizeNodeWidth)
            maxPtWidth = maxPtWidth / universe[i][WIDTH];
          splitDim = i;
        }
      }
    }
    double splitVal = node.m_NodesRectBounds[MIN][splitDim]
        + (node.m_NodesRectBounds[MAX][splitDim] - node.m_NodesRectBounds[MIN][splitDim])
        * 0.5;
    // might want to try to slide it further to contain more than one point on
    // the
    // side that is resulting empty
    if (splitVal < node.m_NodeRanges[splitDim][MIN])
      splitVal = node.m_NodeRanges[splitDim][MIN];
    else if (splitVal >= node.m_NodeRanges[splitDim][MAX])
      splitVal = node.m_NodeRanges[splitDim][MAX]
          - node.m_NodeRanges[splitDim][WIDTH] * 0.001;
    int rightStart = rearrangePoints(m_InstList, node.m_Start, node.m_End,
        splitDim, splitVal);
    if (rightStart == node.m_Start || rightStart > node.m_End) {
      if (rightStart == node.m_Start)
        throw new Exception("Left child is empty in node " + node.m_NodeNumber
            + ". Not possible with "
            + "SlidingMidPointofWidestSide splitting method. Please "
            + "check code.");
      else
        throw new Exception("Right child is empty in node " + node.m_NodeNumber
            + ". Not possible with "
            + "SlidingMidPointofWidestSide splitting method. Please "
            + "check code.");
    }
    node.m_SplitDim = splitDim;
    node.m_SplitValue = splitVal;
    double[][] widths = new double[2][node.m_NodesRectBounds[0].length];
    System.arraycopy(node.m_NodesRectBounds[MIN], 0, widths[MIN], 0,
        node.m_NodesRectBounds[MIN].length);
    System.arraycopy(node.m_NodesRectBounds[MAX], 0, widths[MAX], 0,
        node.m_NodesRectBounds[MAX].length);
    widths[MAX][splitDim] = splitVal;
    node.m_Left = new KDTreeNode(numNodesCreated + 1, node.m_Start,
        rightStart - 1, m_EuclideanDistance.initializeRanges(m_InstList,
            node.m_Start, rightStart - 1), widths);
    widths = new double[2][node.m_NodesRectBounds[0].length];
    System.arraycopy(node.m_NodesRectBounds[MIN], 0, widths[MIN], 0,
        node.m_NodesRectBounds[MIN].length);
    System.arraycopy(node.m_NodesRectBounds[MAX], 0, widths[MAX], 0,
        node.m_NodesRectBounds[MAX].length);
    widths[MIN][splitDim] = splitVal;
    node.m_Right = new KDTreeNode(numNodesCreated + 2, rightStart, node.m_End,
        m_EuclideanDistance.initializeRanges(m_InstList, rightStart, node.m_End), widths);
  }
Member Data Documentation
double moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.ERR = 0.001 [static, protected]
The floating point error to tolerate in finding the widest rectangular side.
Definition at line 63 of file SlidingMidPointOfWidestSide.java.
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.splitNode().
final long moa.classifiers.lazy.neighboursearch.kdtrees.SlidingMidPointOfWidestSide.serialVersionUID = 852857628205680562L [static, private]
for serialization.
Definition at line 59 of file SlidingMidPointOfWidestSide.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/kdtrees/SlidingMidPointOfWidestSide.java