MOA: moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node Class Reference
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node Class Reference
Public Member Functions
Node (double val, int label, double weight)
void insertValue (double val, int label, double weight)
Public Attributes
double cut_point
DoubleVector classCountsLeft = new DoubleVector()
DoubleVector classCountsRight = new DoubleVector()
Node left
Node right
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 45 of file BinaryTreeNumericAttributeClassObserver.java.
Constructor & Destructor Documentation
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.Node (double val, int label, double weight)
Definition at line 59 of file BinaryTreeNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft, and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.cut_point.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue().
{
            this.cut_point = val;
            this.classCountsLeft.addToValue(label, weight);
        }
Member Function Documentation
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue (double val, int label, double weight)
Definition at line 64 of file BinaryTreeNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsRight, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.cut_point, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.left, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.Node(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.right.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.observeAttributeClass().
{
            if (val == this.cut_point) {
                this.classCountsLeft.addToValue(label, weight);
            } else if (val <= this.cut_point) {
                this.classCountsLeft.addToValue(label, weight);
                if (this.left == null) {
                    this.left = new Node(val, label, weight);
                } else {
                    this.left.insertValue(val, label, weight);
                }
            } else { // val > cut_point
                this.classCountsRight.addToValue(label, weight);
                if (this.right == null) {
                    this.right = new Node(val, label, weight);
                } else {
                    this.right.insertValue(val, label, weight);
                }
            }
        }
Member Data Documentation
DoubleVector moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsLeft = new DoubleVector()
Definition at line 51 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.Node(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
DoubleVector moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.classCountsRight = new DoubleVector()
Definition at line 53 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
double moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.cut_point
Definition at line 49 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.Node(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.searchForBestSplitOption(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.left
Definition at line 55 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.removeBadSplitNodes(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.searchForBestSplitOption(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.right
Definition at line 57 of file BinaryTreeNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.removeBadSplitNodes(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.searchForBestSplitOption(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
final long moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.serialVersionUID = 1L [static, private]
Definition at line 47 of file BinaryTreeNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/BinaryTreeNumericAttributeClassObserver.java