MOA: moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod Class Reference
moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod Class Reference
The class that splits a node into two such that the overall sum of squared distances of points to their centres on both sides of the (axis-parallel) splitting plane is minimum.
Public Member Functions
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
void splitNode (KDTreeNode node, int numNodesCreated, double[][] nodeRanges, double[][] universe) throws Exception
Splits a node into two such that the overall sum of squared distances of points to their centres on both sides of the (axis-parallel) splitting plane is minimum.
Protected Member Functions
int rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal)
Re-arranges the indices array so that in the portion of the array belonging to the node to be split, the points <= to the splitVal are on the left of the portion and those > the splitVal are on the right.
Static Protected Member Functions
static int partition (Instances insts, int[] index, int attidx, int l, int r)
Partitions the instances around a pivot.
static void quickSort (Instances insts, int[] indices, int attidx, int left, int right)
Sorts the instances according to the given attribute/dimension.
Static Private Member Functions
static void checkSort (Instances insts, int[] indices, int attidx, int start, int end) throws Exception
Method to validate the sorting done by quickSort().
Static Private Attributes
static final long serialVersionUID = -866783749124714304L
for serialization.
Detailed Description
The class that splits a node into two such that the overall sum of squared distances of points to their centres on both sides of the (axis-parallel) splitting plane is minimum.
For more information see also:
Ashraf Masood Kibriya (2007). Fast Algorithms for Nearest Neighbour Search. Hamilton, New Zealand.
BibTeX:
 &#64;mastersthesis{Kibriya2007,
    address = {Hamilton, New Zealand},
    author = {Ashraf Masood Kibriya},
    school = {Department of Computer Science, School of Computing and Mathematical Sciences, University of Waikato},
    title = {Fast Algorithms for Nearest Neighbour Search},
    year = {2007}
 }
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 56 of file KMeansInpiredMethod.java.
Member Function Documentation
static void moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.checkSort (Instances insts, int[] indices, int attidx, int start, int end) throws Exception [static, private]
Method to validate the sorting done by quickSort().
Parameters:
insts The instances on which the tree is (or is to be) built.
indices The master index array containing indices of the instances.
attidx The dimension/attribute based on which the instances should be sorted.
start The start of the portion in master index array that needs to be sorted.
end The end of the portion in master index array that needs to be sorted.
Exceptions:
Exception If the indices of the instances are not in sorted order.
Definition at line 298 of file KMeansInpiredMethod.java.
{
    for(int i=start+1; i<=end; i++) {
      if( insts.instance(indices[i-1]).value(attidx) >
          insts.instance(indices[i]).value(attidx) ) {
        System.out.println("value[i-1]: "+insts.instance(indices[i-1]).value(attidx));
        System.out.println("value[i]: "+insts.instance(indices[i]).value(attidx));
        System.out.println("indices[i-1]: "+indices[i-1]);
        System.out.println("indices[i]: "+indices[i]);
        System.out.println("i: "+i);
        if(insts.instance(indices[i-1]).value(attidx) > insts.instance(indices[i]).value(attidx))
          System.out.println("value[i-1] > value[i]");
        throw new Exception("Indices not sorted correctly.");
      }//end if
    }
  }
String moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Definition at line 68 of file KMeansInpiredMethod.java.
{
    return
        "The class that splits a node into two such that the overall sum "
      + "of squared distances of points to their centres on both sides "
      + "of the (axis-parallel) splitting plane is minimum.\n\n"
      + "For more information see also:\n\n";
  }
static int moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.partition (Instances insts, int[] index, int attidx, int l, int r) [static, protected]
Partitions the instances around a pivot.
Used by quicksort and kthSmallestValue.
Parameters:
insts The instances on which the tree is (or is to be) built.
index The master index array containing indices of the instances.
attidx The attribution/dimension based on which the instances should be partitioned.
l The begining index of the portion of master index array that should be partitioned.
r The end index of the portion of master index array that should be partitioned.
Returns:
the index of the middle element
Definition at line 230 of file KMeansInpiredMethod.java.
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.quickSort().
{
    double pivot = insts.instance(index[(l + r) / 2]).value(attidx);
    int help;
    while (l < r) {
      while ((insts.instance(index[l]).value(attidx) < pivot) && (l < r)) {
        l++;
      }
      while ((insts.instance(index[r]).value(attidx) > pivot) && (l < r)) {
        r--;
      }
      if (l < r) {
        help = index[l];
        index[l] = index[r];
        index[r] = help;
        l++;
        r--;
      }
    }
    if ((l == r) && (insts.instance(index[r]).value(attidx) > pivot)) {
      r--;
    }
    return r;
  }
static void moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.quickSort (Instances insts, int[] indices, int attidx, int left, int right) [static, protected]
Sorts the instances according to the given attribute/dimension.
The sorting is done on the master index array and not on the actual instances object.
Parameters:
insts The instances on which the tree is (or is to be) built.
indices The master index array containing indices of the instances.
attidx The dimension/attribute based on which the instances should be sorted.
left The begining index of the portion of the master index array that needs to be sorted.
right The end index of the portion of the master index array that needs to be sorted.
Definition at line 273 of file KMeansInpiredMethod.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.partition().
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.splitNode().
{
    if (left < right) {
      int middle = partition(insts, indices, attidx, left, right);
      quickSort(insts, indices, attidx, left, middle);
      quickSort(insts, indices, attidx, middle + 1, right);
    }
  }
int moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.rearrangePoints (int[] indices, final int startidx, final int endidx, final int splitDim, final double splitVal) [protected]
Re-arranges the indices array so that in the portion of the array belonging to the node to be split, the points <= to the splitVal are on the left of the portion and those > the splitVal are on the right.
Parameters:
indices The master index array.
startidx The begining index of portion of indices that needs re-arranging.
endidx The end index of portion of indices that needs re-arranging.
splitDim The split dimension/attribute.
splitVal The split value.
Returns:
The startIdx of the points > the splitVal (the points belonging to the right child of the node).
Definition at line 331 of file KMeansInpiredMethod.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, and moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual().
Referenced by moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.splitNode().
{
    int tmp, left = startidx - 1;
    for (int i = startidx; i <= endidx; i++) {
      if (m_EuclideanDistance.valueIsSmallerEqual(m_Instances
          .instance(indices[i]), splitDim, splitVal)) {
        left++;
        tmp = indices[left];
        indices[left] = indices[i];
        indices[i] = tmp;
      }// end valueIsSmallerEqual
    }// endfor
    return left + 1;
  }
void moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.splitNode (KDTreeNode node, int numNodesCreated, double nodeRanges[][], double universe[][]) throws Exception [virtual]
Splits a node into two such that the overall sum of squared distances of points to their centres on both sides of the (axis-parallel) splitting plane is minimum.
The two nodes created after the whole splitting are correctly initialised. And, node.left and node.right are set appropriately.
Parameters:
node The node to split.
numNodesCreated The number of nodes that so far have been created for the tree, so that the newly created nodes are assigned correct/meaningful node numbers/ids.
nodeRanges The attributes' range for the points inside the node that is to be split.
universe The attributes' range for the whole point-space.
Exceptions:
Exception If there is some problem in splitting the given node.
Implements moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.
Definition at line 95 of file KMeansInpiredMethod.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.correctlyInitialized(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_Instances, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_InstList, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.m_NormalizeNodeWidth, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.MAX, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.MIN, moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.quickSort(), moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.rearrangePoints(), and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.WIDTH.
{
    correctlyInitialized();
    int splitDim = -1;
    double splitVal = Double.NEGATIVE_INFINITY;
    double leftAttSum[] = new double[m_Instances.numAttributes()],
           rightAttSum[] = new double[m_Instances.numAttributes()],
           leftAttSqSum[] = new double[m_Instances.numAttributes()],
           rightAttSqSum[] = new double[m_Instances.numAttributes()],
           rightSqMean, leftSqMean, leftSqSum, rightSqSum,
           minSum = Double.POSITIVE_INFINITY, val;
    for (int dim = 0; dim < m_Instances.numAttributes(); dim++) {
      // m_MaxRelativeWidth in KDTree ensure there'll be atleast one dim with
      // width > 0.0
      if (node.m_NodeRanges[dim][WIDTH] == 0.0
          || dim == m_Instances.classIndex())
        continue;
      quickSort(m_Instances, m_InstList, dim, node.m_Start, node.m_End);
      for (int i = node.m_Start; i <= node.m_End; i++) {
        for (int j = 0; j < m_Instances.numAttributes(); j++) {
          if (j == m_Instances.classIndex())
            continue;
          val = m_Instances.instance(m_InstList[i]).value(j);
          if (m_NormalizeNodeWidth) {
            if (Double.isNaN(universe[j][MIN])
                || universe[j][MIN] == universe[j][MAX])
              val = 0.0;
            else
              val = ((val - universe[j][MIN]) / universe[j][WIDTH]); // normalizing
                                                                      // value
          }
          if (i == node.m_Start) {
            leftAttSum[j] = rightAttSum[j] = leftAttSqSum[j] = rightAttSqSum[j] = 0.0;
          }
          rightAttSum[j] += val;
          rightAttSqSum[j] += val * val;
        }
      }
      for (int i = node.m_Start; i <= node.m_End - 1; i++) {
        Instance inst = m_Instances.instance(m_InstList[i]);
        leftSqSum = rightSqSum = 0.0;
        for (int j = 0; j < m_Instances.numAttributes(); j++) {
          if (j == m_Instances.classIndex())
            continue;
          val = inst.value(j);
          if (m_NormalizeNodeWidth) {
            if (Double.isNaN(universe[j][MIN])
                || universe[j][MIN] == universe[j][MAX])
              val = 0.0;
            else
              val = ((val - universe[j][MIN]) / universe[j][WIDTH]); // normalizing
                                                                      // value
          }
          leftAttSum[j] += val;
          rightAttSum[j] -= val;
          leftAttSqSum[j] += val * val;
          rightAttSqSum[j] -= val * val;
          leftSqMean = leftAttSum[j] / (i - node.m_Start + 1);
          leftSqMean *= leftSqMean;
          rightSqMean = rightAttSum[j] / (node.m_End - i);
          rightSqMean *= rightSqMean;
          leftSqSum += leftAttSqSum[j] - (i - node.m_Start + 1) * leftSqMean;
          rightSqSum += rightAttSqSum[j] - (node.m_End - i) * rightSqMean;
        }
        if (minSum > (leftSqSum + rightSqSum)) {
          minSum = leftSqSum + rightSqSum;
          if (i < node.m_End)
            splitVal = (m_Instances.instance(m_InstList[i]).value(dim) + m_Instances
                .instance(m_InstList[i + 1]).value(dim)) / 2;
          else
            splitVal = m_Instances.instance(m_InstList[i]).value(dim);
          splitDim = dim;
        }
      }// end for instance i
    }// end for attribute dim
    int rightStart = rearrangePoints(m_InstList, node.m_Start, node.m_End,
        splitDim, splitVal);
    if (rightStart == node.m_Start || rightStart > node.m_End) {
      System.out.println("node.m_Start: " + node.m_Start + " node.m_End: "
          + node.m_End + " splitDim: " + splitDim + " splitVal: " + splitVal
          + " node.min: " + node.m_NodeRanges[splitDim][MIN] + " node.max: "
          + node.m_NodeRanges[splitDim][MAX] + " node.numInstances: "
          + node.numInstances());
      if (rightStart == node.m_Start)
        throw new Exception("Left child is empty in node " + node.m_NodeNumber
            + ". Not possible with "
            + "KMeanInspiredMethod splitting method. Please " + "check code.");
      else
        throw new Exception("Right child is empty in node " + node.m_NodeNumber
            + ". Not possible with "
            + "KMeansInspiredMethod splitting method. Please " + "check code.");
    }
    node.m_SplitDim = splitDim;
    node.m_SplitValue = splitVal;
    node.m_Left = new KDTreeNode(numNodesCreated + 1, node.m_Start,
        rightStart - 1, m_EuclideanDistance.initializeRanges(m_InstList,
            node.m_Start, rightStart - 1));
    node.m_Right = new KDTreeNode(numNodesCreated + 2, rightStart, node.m_End,
        m_EuclideanDistance
            .initializeRanges(m_InstList, rightStart, node.m_End));
  }
Member Data Documentation
final long moa.classifiers.lazy.neighboursearch.kdtrees.KMeansInpiredMethod.serialVersionUID = -866783749124714304L [static, private]
for serialization.
Definition at line 60 of file KMeansInpiredMethod.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/kdtrees/KMeansInpiredMethod.java