MOA: moa.recommender.dataset.impl.MovielensDataset Class Reference
moa.recommender.dataset.impl.MovielensDataset Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void init ()
boolean next ()
String toString ()
Returns a description of the object.
int curUserID ()
int curItemID ()
double curRating ()
void reset ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
FileOption fileOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Private Attributes
String strLine
BufferedReader br
Detailed Description
Definition at line 37 of file MovielensDataset.java.
Member Function Documentation
int moa.recommender.dataset.impl.MovielensDataset.curItemID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 85 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.strLine.
{
        String[] split = strLine.split("::");
        return Integer.valueOf(split[1]);
    }
double moa.recommender.dataset.impl.MovielensDataset.curRating ()
Implements moa.recommender.dataset.Dataset.
Definition at line 91 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.strLine.
{
        String[] split = strLine.split("::");
        return Double.valueOf(split[2]);
    }
int moa.recommender.dataset.impl.MovielensDataset.curUserID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 79 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.strLine.
{
        String[] split = strLine.split("::");
        return Integer.valueOf(split[0]);
    }
void moa.recommender.dataset.impl.MovielensDataset.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 115 of file MovielensDataset.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.recommender.dataset.impl.MovielensDataset.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 47 of file MovielensDataset.java.
{
        return "A Movie Lens Dataset reader.";
    }
void moa.recommender.dataset.impl.MovielensDataset.init ()
Definition at line 51 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.br, moa.recommender.dataset.impl.MovielensDataset.fileOption, and moa.options.FileOption.getFile().
Referenced by moa.recommender.dataset.impl.MovielensDataset.prepareForUseImpl(), and moa.recommender.dataset.impl.MovielensDataset.reset().
                       {
        FileInputStream fstream = null;
        try {
            //fstream = new FileInputStream("/Users/abifet/Downloads/ml-1M/ratings.dat");
            fstream = new FileInputStream(this.fileOption.getFile());
            DataInputStream in = new DataInputStream(fstream);
            br = new BufferedReader(new InputStreamReader(in));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MovielensDataset.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
boolean moa.recommender.dataset.impl.MovielensDataset.next ()
Implements moa.recommender.dataset.Dataset.
Definition at line 65 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.br, and moa.recommender.dataset.impl.MovielensDataset.strLine.
{
        try {
            return (strLine = ((BufferedReader) br).readLine()) != null;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }
void moa.recommender.dataset.impl.MovielensDataset.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 110 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.init().
{
        this.init();
    }
void moa.recommender.dataset.impl.MovielensDataset.reset ()
Implements moa.recommender.dataset.Dataset.
Definition at line 97 of file MovielensDataset.java.
References moa.recommender.dataset.impl.MovielensDataset.br, and moa.recommender.dataset.impl.MovielensDataset.init().
{
        try {
            br.close();
            //FileInputStream fstream = new FileInputStream("/home/alex/datasets/ml-1m/ratings.dat");
            //DataInputStream in = new DataInputStream(fstream);
            //br = new BufferedReader(new InputStreamReader(in));
            this.init();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
String moa.recommender.dataset.impl.MovielensDataset.toString ()
Returns a description of the object.
Returns:
a description of the object
Reimplemented from moa.AbstractMOAObject.
Definition at line 74 of file MovielensDataset.java.
{
        return "Movielens";
    }
Member Data Documentation
BufferedReader moa.recommender.dataset.impl.MovielensDataset.br [private]
Definition at line 41 of file MovielensDataset.java.
Referenced by moa.recommender.dataset.impl.MovielensDataset.init(), moa.recommender.dataset.impl.MovielensDataset.next(), and moa.recommender.dataset.impl.MovielensDataset.reset().
FileOption moa.recommender.dataset.impl.MovielensDataset.fileOption
Initial value:
 new FileOption("file", 'f',
            "File to load.", "/Users/abifet/Downloads/ml-1M/ratings.dat", "dat", false)
Definition at line 43 of file MovielensDataset.java.
Referenced by moa.recommender.dataset.impl.MovielensDataset.init().
String moa.recommender.dataset.impl.MovielensDataset.strLine [private]
Definition at line 39 of file MovielensDataset.java.
Referenced by moa.recommender.dataset.impl.MovielensDataset.curItemID(), moa.recommender.dataset.impl.MovielensDataset.curRating(), moa.recommender.dataset.impl.MovielensDataset.curUserID(), and moa.recommender.dataset.impl.MovielensDataset.next().
The documentation for this class was generated from the following file:
main/java/moa/recommender/dataset/impl/MovielensDataset.java