MOA: moa.core.GaussianEstimator Class Reference
moa.core.GaussianEstimator Class Reference
Gaussian incremental estimator that uses incremental method that is more resistant to floating point imprecision.
Public Member Functions
void addObservation (double value, double weight)
void addObservations (GaussianEstimator obs)
double getTotalWeightObserved ()
double getMean ()
double getStdDev ()
double getVariance ()
double probabilityDensity (double value)
double[] estimatedWeight_LessThan_EqualTo_GreaterThan_Value (double value)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Attributes
static final double NORMAL_CONSTANT = Math.sqrt(2 * Math.PI)
Protected Attributes
double weightSum
double mean
double varianceSum
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Gaussian incremental estimator that uses incremental method that is more resistant to floating point imprecision.
for more info see Donald Knuth's "The Art of Computer Programming, Volume 2: Seminumerical Algorithms", section 4.2.2.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 31 of file GaussianEstimator.java.
Member Function Documentation
void moa.core.GaussianEstimator.addObservation (double value, double weight)
Definition at line 43 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.mean, moa.core.GaussianEstimator.varianceSum, and moa.core.GaussianEstimator.weightSum.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass().
{
        if (Double.isInfinite(value) || Double.isNaN(value)) {
            return;
        }
        if (this.weightSum > 0.0) {
            this.weightSum += weight;
            double lastMean = this.mean;
            this.mean += weight * (value - lastMean) / this.weightSum;
            this.varianceSum += weight * (value - lastMean) * (value - this.mean);
        } else {
            this.mean = value;
            this.weightSum = weight;
        }
    }
void moa.core.GaussianEstimator.addObservations (GaussianEstimator obs)
Definition at line 58 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.mean, moa.core.GaussianEstimator.varianceSum, and moa.core.GaussianEstimator.weightSum.
{
        // Follows Variance Combination Rule in Section 2 of
        // Brian Babcock, Mayur Datar, Rajeev Motwani, Liadan O'Callaghan:
        // Maintaining variance and k-medians over data stream windows. PODS 2003: 234-243
        //
        if ((this.weightSum > 0.0) && (obs.weightSum > 0.0)) {
            double oldMean = this.mean;
            this.mean = (this.mean * (this.weightSum / (this.weightSum + obs.weightSum)))
                    + (obs.mean * (obs.weightSum / (this.weightSum + obs.weightSum)));
            this.varianceSum += obs.varianceSum + (this.weightSum * obs.weightSum / (this.weightSum + obs.weightSum) *
                                 Math.pow(obs.mean-oldMean, 2));
            this.weightSum += obs.weightSum;
        }
    }
double [] moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value (double value)
Definition at line 103 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.getMean(), moa.core.GaussianEstimator.getStdDev(), moa.core.GaussianEstimator.probabilityDensity(), and moa.core.GaussianEstimator.weightSum.
Referenced by moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit().
{
        double equalToWeight = probabilityDensity(value) * this.weightSum;
        double stdDev = getStdDev();
        double lessThanWeight = stdDev > 0.0 ? weka.core.Statistics.normalProbability((value - getMean()) / stdDev)
                * this.weightSum - equalToWeight
                : (value < getMean() ? this.weightSum - equalToWeight : 0.0);
        double greaterThanWeight = this.weightSum - equalToWeight
                - lessThanWeight;
        if (greaterThanWeight < 0.0) {
            greaterThanWeight = 0.0;
        }
        return new double[]{lessThanWeight, equalToWeight, greaterThanWeight};
    }
void moa.core.GaussianEstimator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 119 of file GaussianEstimator.java.
{
        // TODO Auto-generated method stub
    }
double moa.core.GaussianEstimator.getMean ()
Definition at line 77 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.mean.
Referenced by moa.core.Measurement.averageMeasurements(), moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(), and moa.core.GaussianEstimator.probabilityDensity().
{
        return this.mean;
    }
double moa.core.GaussianEstimator.getStdDev ()
Definition at line 81 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.getVariance().
Referenced by moa.core.Measurement.averageMeasurements(), moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(), moa.streams.filters.AddNoiseFilter.nextInstance(), and moa.core.GaussianEstimator.probabilityDensity().
{
        return Math.sqrt(getVariance());
    }
double moa.core.GaussianEstimator.getTotalWeightObserved ()
Definition at line 73 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.weightSum.
Referenced by moa.core.Measurement.averageMeasurements(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit().
{
        return this.weightSum;
    }
double moa.core.GaussianEstimator.getVariance ()
Definition at line 85 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.varianceSum, and moa.core.GaussianEstimator.weightSum.
Referenced by moa.core.GaussianEstimator.getStdDev().
{
        return this.weightSum > 1.0 ? this.varianceSum / (this.weightSum - 1.0)
                : 0.0;
    }
double moa.core.GaussianEstimator.probabilityDensity (double value)
Definition at line 90 of file GaussianEstimator.java.
References moa.core.GaussianEstimator.getMean(), moa.core.GaussianEstimator.getStdDev(), moa.core.GaussianEstimator.NORMAL_CONSTANT, and moa.core.GaussianEstimator.weightSum.
Referenced by moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(), and moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.probabilityOfAttributeValueGivenClass().
{
        if (this.weightSum > 0.0) {
            double stdDev = getStdDev();
            if (stdDev > 0.0) {
                double diff = value - getMean();
                return (1.0 / (NORMAL_CONSTANT * stdDev))
                        * Math.exp(-(diff * diff / (2.0 * stdDev * stdDev)));
            }
            return value == getMean() ? 1.0 : 0.0;
        }
        return 0.0;
    }
Member Data Documentation
double moa.core.GaussianEstimator.mean [protected]
Definition at line 37 of file GaussianEstimator.java.
Referenced by moa.core.GaussianEstimator.addObservation(), moa.core.GaussianEstimator.addObservations(), and moa.core.GaussianEstimator.getMean().
final double moa.core.GaussianEstimator.NORMAL_CONSTANT = Math.sqrt(2 * Math.PI) [static]
Definition at line 41 of file GaussianEstimator.java.
Referenced by moa.core.GaussianEstimator.probabilityDensity().
final long moa.core.GaussianEstimator.serialVersionUID = 1L [static, private]
Definition at line 33 of file GaussianEstimator.java.
double moa.core.GaussianEstimator.varianceSum [protected]
Definition at line 39 of file GaussianEstimator.java.
Referenced by moa.core.GaussianEstimator.addObservation(), moa.core.GaussianEstimator.addObservations(), and moa.core.GaussianEstimator.getVariance().
double moa.core.GaussianEstimator.weightSum [protected]
Definition at line 35 of file GaussianEstimator.java.
Referenced by moa.core.GaussianEstimator.addObservation(), moa.core.GaussianEstimator.addObservations(), moa.core.GaussianEstimator.estimatedWeight_LessThan_EqualTo_GreaterThan_Value(), moa.core.GaussianEstimator.getTotalWeightObserved(), moa.core.GaussianEstimator.getVariance(), and moa.core.GaussianEstimator.probabilityDensity().
The documentation for this class was generated from the following file:
main/java/moa/core/GaussianEstimator.java