MOA: moa.streams.clustering.RandomRBFGeneratorEvents Class Reference
moa.streams.clustering.RandomRBFGeneratorEvents Class Reference
Classes
class GeneratorCluster
Public Member Functions
RandomRBFGeneratorEvents ()
InstancesHeader getHeader ()
Gets the header of this stream.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void restart ()
Restarts this stream.
Instance nextInstance ()
Gets the next instance from this stream.
Clustering getGeneratingClusters ()
Clustering getMicroClustering ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
synchronized void addClusterChangeListener (ClusterEventListener l)
Add a listener.
synchronized void removeClusterChangeListener (ClusterEventListener l)
Remove a listener.
String getPurposeString ()
Gets the purpose of this object.
String getParameterString ()
Public Attributes
IntOption modelRandomSeedOption
IntOption instanceRandomSeedOption
IntOption numClusterOption
IntOption numClusterRangeOption
FloatOption kernelRadiiOption
FloatOption kernelRadiiRangeOption
FloatOption densityRangeOption
IntOption speedOption
IntOption speedRangeOption
FloatOption noiseLevelOption
FlagOption noiseInClusterOption
IntOption eventFrequencyOption
FlagOption eventMergeSplitOption
FlagOption eventDeleteCreateOption
Protected Member Functions
void generateHeader ()
void initKernels ()
void fireClusterChange (long timestamp, String type, String message)
Fire a ClusterChangeEvent to all registered listeners.
Protected Attributes
Random instanceRandom
InstancesHeader streamHeader
Private Member Functions
void eventScheduler ()
int getNextEvent ()
String fadeOut ()
String fadeIn ()
String changeWeight (boolean increase)
String changeRadius (boolean increase)
String splitKernel ()
String mergeKernels (int steps)
double[] getNoisePoint ()
int chooseWeightedElement ()
void normalizeWeights ()
Private Attributes
transient Vector listeners
double merge_threshold = 0.7
int kernelMovePointFrequency = 10
double maxDistanceMoveThresholdByStep = 0.01
int maxOverlapFitRuns = 50
double eventFrequencyRange = 0
boolean debug = false
AutoExpandVector
< GeneratorCluster > kernels
int numGeneratedInstances
int numActiveKernels
int nextEventCounter
int nextEventChoice = -1
int clusterIdCounter
GeneratorCluster mergeClusterA
GeneratorCluster mergeClusterB
boolean mergeKernelsOverlapping = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 50 of file RandomRBFGeneratorEvents.java.
Constructor & Destructor Documentation
moa.streams.clustering.RandomRBFGeneratorEvents.RandomRBFGeneratorEvents ()
Definition at line 453 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.noiseInClusterOption, and moa.options.FlagOption.set().
{
        noiseInClusterOption.set();
//        eventDeleteCreateOption.set();
//        eventMergeSplitOption.set();
    }
Member Function Documentation
synchronized void moa.streams.clustering.RandomRBFGeneratorEvents.addClusterChangeListener (ClusterEventListener l)
Add a listener.
Definition at line 921 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.listeners.
{
    if (listeners == null)
      listeners = new Vector();
    listeners.addElement(l);
  }
String moa.streams.clustering.RandomRBFGeneratorEvents.changeRadius (boolean increase) [private]
Definition at line 753 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
{
        double maxChangeRate = 0.1;
        int id = instanceRandom.nextInt(kernels.size());
        while(kernels.get(id).kill!=-1)
            id = instanceRandom.nextInt(kernels.size());
        int sign = 1;
        if(!increase)
            sign = -1;
        double r_old = kernels.get(id).generator.getRadius();
        double r_new =r_old+sign*r_old*instanceRandom.nextDouble()*maxChangeRate;
        if(r_new >= 0.5) return "Radius to big";
        kernels.get(id).generator.setRadius(r_new);
        String message;
        if(increase)
            message = "Increase ";
        else
            message = "Decrease ";
        message+=" radius on Cluster "+id+" from "+r_old+" to "+r_new;
        return message;
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.changeWeight (boolean increase) [private]
Definition at line 727 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), and moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels.
{
        double changeRate = 0.1;
        int id = instanceRandom.nextInt(kernels.size());
        while(kernels.get(id).kill!=-1)
            id = instanceRandom.nextInt(kernels.size());
        int sign = 1;
        if(!increase)
            sign = -1;
        double weight_old = kernels.get(id).generator.getWeight();
        double delta = sign*numActiveKernels*instanceRandom.nextDouble()*changeRate;
        kernels.get(id).generator.setWeight(weight_old+delta);
        normalizeWeights();
        String message;
        if(increase)
            message = "Increase ";
        else
            message = "Decrease ";
        message+=" weight on Cluster "+id+" from "+weight_old+" to "+(weight_old+delta);
        return message;
    }
int moa.streams.clustering.RandomRBFGeneratorEvents.chooseWeightedElement () [private]
Definition at line 891 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance().
{
        double r = instanceRandom.nextDouble();
        // Determine index of choosen element
        int i = 0;
        while (r > 0.0) {
            r -= kernels.get(i).generator.getWeight();
            i++;
        }
        --i;    // Overcounted once
        //System.out.println(i);
        return i;
    }
long moa.streams.clustering.RandomRBFGeneratorEvents.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 463 of file RandomRBFGeneratorEvents.java.
{
            return -1;
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler () [private]
Definition at line 591 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.eventFrequencyOption, moa.streams.clustering.RandomRBFGeneratorEvents.eventFrequencyRange, moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.fireClusterChange(), moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.kernelMovePointFrequency, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterA, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterB, moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.nextEventChoice, moa.streams.clustering.RandomRBFGeneratorEvents.nextEventCounter, moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterRangeOption, moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances, and moa.streams.clustering.RandomRBFGeneratorEvents.splitKernel().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance().
{
        for ( int i = 0; i < kernels.size(); i++ ) {
            kernels.get(i).updateKernel();
        }
        nextEventCounter--;
        //only move kernels every 10 points, performance reasons????
        //should this be randomized as well???
        if(nextEventCounter%kernelMovePointFrequency == 0){
            //move kernels
            for ( int i = 0; i < kernels.size(); i++ ) {
                kernels.get(i).move();
                //overlapControl();
            }
        }
        if(eventFrequencyOption.getValue() == 0){
            return;
        }
        String type ="";
        String message ="";
        boolean eventFinished = false;
        switch(nextEventChoice){
            case 0:
                if(numActiveKernels > 1 && numActiveKernels > numClusterOption.getValue() - numClusterRangeOption.getValue()){
                    message = mergeKernels(nextEventCounter);
                    type = "Merge";
                }
                if(mergeClusterA==null && mergeClusterB==null && message.startsWith("Clusters merging")){
                    eventFinished = true;
                }
            break;
            case 1:
                if(nextEventCounter<=0){
                    if(numActiveKernels < numClusterOption.getValue() + numClusterRangeOption.getValue()){
                        type = "Split";
                        message = splitKernel();
                    }
                    eventFinished = true;
                }
            break;
            case 2:
                if(nextEventCounter<=0){
                    if(numActiveKernels > 1 && numActiveKernels > numClusterOption.getValue() - numClusterRangeOption.getValue()){
                        message = fadeOut();
                        type = "Delete";
                    }
                    eventFinished = true;
                }
            break;
            case 3:
                if(nextEventCounter<=0){
                    if(numActiveKernels < numClusterOption.getValue() + numClusterRangeOption.getValue()){
                        message = fadeIn();
                        type = "Create";
                    }
                    eventFinished = true;
                }
            break;
        }
        if (eventFinished){
                nextEventCounter = (int)(eventFrequencyOption.getValue()+(instanceRandom.nextBoolean()?-1:1)*eventFrequencyOption.getValue()*eventFrequencyRange*instanceRandom.nextDouble());
                nextEventChoice = getNextEvent();
                //System.out.println("Next event choice: "+nextEventChoice);
        }
        if(!message.isEmpty()){
            message+=" (numKernels = "+numActiveKernels+" at "+numGeneratedInstances+")";
            if(!type.equals("Merge") || message.startsWith("Clusters merging"))
                fireClusterChange(numGeneratedInstances, type, message);
        }
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn () [private]
Definition at line 718 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.clusterIdCounter, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), and moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
{
            GeneratorCluster gc = new GeneratorCluster(clusterIdCounter++);
            kernels.add(gc);
            numActiveKernels++;
            normalizeWeights();
        return "Creating new cluster";
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.fadeOut () [private]
Definition at line 709 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
{
        int id = instanceRandom.nextInt(kernels.size());
        while(kernels.get(id).kill!=-1)
            id = instanceRandom.nextInt(kernels.size());
        String message = kernels.get(id).fadeOut();
        return message;
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.fireClusterChange (long timestamp, String type, String message) [protected]
Fire a ClusterChangeEvent to all registered listeners.
Definition at line 935 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.ClusterEventListener.changeCluster(), and moa.streams.clustering.RandomRBFGeneratorEvents.listeners.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
{
    // if we have no listeners, do nothing...
    if (listeners != null && !listeners.isEmpty()) {
      // create the event object to send
      ClusterEvent event =
        new ClusterEvent(this, timestamp, type , message);
      // make a copy of the listener list in case
      //   anyone adds/removes listeners
      Vector targets;
      synchronized (this) {
        targets = (Vector) listeners.clone();
      }
      // walk through the listener list and
      //   call the sunMoved method in each
      Enumeration e = targets.elements();
      while (e.hasMoreElements()) {
        ClusterEventListener l = (ClusterEventListener) e.nextElement();
        l.changeCluster(event);
      }
    }
  }
void moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader () [protected]
Definition at line 495 of file RandomRBFGeneratorEvents.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.noiseLevelOption, moa.streams.clustering.ClusteringStream.numAttsOption, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption, and moa.streams.clustering.RandomRBFGeneratorEvents.streamHeader.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.prepareForUseImpl().
                                    {   // 2013/06/02: Noise label
        ArrayList<Attribute> attributes = new ArrayList<Attribute>();
        for (int i = 0; i < this.numAttsOption.getValue(); i++) {
            attributes.add(new Attribute("att" + (i + 1)));
        }
        ArrayList<String> classLabels = new ArrayList<String>();
        for (int i = 0; i < this.numClusterOption.getValue(); i++) {
            classLabels.add("class" + (i + 1));
        }
        if (noiseLevelOption.getValue() > 0) classLabels.add("noise");  // The last label = "noise"
        attributes.add(new Attribute("class", classLabels));
        streamHeader = new InstancesHeader(new Instances(getCLICreationString(InstanceStream.class), attributes, 0));
        streamHeader.setClassIndex(streamHeader.numAttributes() - 1);
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 854 of file RandomRBFGeneratorEvents.java.
{
    }
Clustering moa.streams.clustering.RandomRBFGeneratorEvents.getGeneratingClusters ()
Definition at line 565 of file RandomRBFGeneratorEvents.java.
References moa.cluster.Clustering.add(), and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
{
        Clustering clustering = new Clustering();
        for (int c = 0; c < kernels.size(); c++) {
            clustering.add(kernels.get(c).generator);
        }
        return clustering;
    }
InstancesHeader moa.streams.clustering.RandomRBFGeneratorEvents.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 459 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.streamHeader.
Referenced by moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), moa.clusterers.outliers.AbstractC.Test.main(), and moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance().
{
            return streamHeader;
    }
Clustering moa.streams.clustering.RandomRBFGeneratorEvents.getMicroClustering ()
Definition at line 573 of file RandomRBFGeneratorEvents.java.
References moa.cluster.Clustering.add(), and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
{
        Clustering clustering = new Clustering();
        int id = 0;
            for (int c = 0; c < kernels.size(); c++) {
                for (int m = 0; m < kernels.get(c).microClusters.size(); m++) {
                    kernels.get(c).microClusters.get(m).setId(id);
                    kernels.get(c).microClusters.get(m).setGroundTruth(kernels.get(c).generator.getId());
                    clustering.add(kernels.get(c).microClusters.get(m));
                    id++;
                }
            }
        //System.out.println("numMicroKernels "+clustering.size());
        return clustering;
    }
int moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent () [private]
Definition at line 667 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.eventDeleteCreateOption, moa.streams.clustering.RandomRBFGeneratorEvents.eventMergeSplitOption, moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.options.FlagOption.isSet, moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption, and moa.streams.clustering.RandomRBFGeneratorEvents.numClusterRangeOption.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.restart().
{
        int choice = -1;
        boolean lowerLimit = numActiveKernels <= numClusterOption.getValue() - numClusterRangeOption.getValue();
        boolean upperLimit = numActiveKernels >= numClusterOption.getValue() + numClusterRangeOption.getValue();
        if(!lowerLimit || !upperLimit){
            int mode = -1;
            if(eventDeleteCreateOption.isSet() && eventMergeSplitOption.isSet()){
                mode = instanceRandom.nextInt(2);
            }
            if(mode==0 || (mode==-1 && eventMergeSplitOption.isSet())){
                //have we reached a limit? if not free choice
                if(!lowerLimit && !upperLimit)
                    choice = instanceRandom.nextInt(2);
                else
                    //we have a limit. if lower limit, choose split
                    if(lowerLimit)
                        choice = 1;
                    //otherwise we reached upper level, choose merge
                    else
                        choice = 0;
            }
            if(mode==1 || (mode==-1 && eventDeleteCreateOption.isSet())){
                //have we reached a limit? if not free choice
                if(!lowerLimit && !upperLimit)
                    choice = instanceRandom.nextInt(2)+2;
                else
                    //we have a limit. if lower limit, choose create
                    if(lowerLimit)
                        choice = 3;
                    //otherwise we reached upper level, choose delete
                    else
                        choice = 2;
            }
        }
        return choice;
    }
double [] moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint () [private]
Definition at line 858 of file RandomRBFGeneratorEvents.java.
References moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.options.FlagOption.isSet, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.noiseInClusterOption, and moa.streams.clustering.ClusteringStream.numAttsOption.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance().
{
        double [] sample = new double [numAttsOption.getValue()];
        boolean incluster = true;
        int counter = 20;
        while(incluster){
            for (int j = 0; j < numAttsOption.getValue(); j++) {
                 sample[j] = instanceRandom.nextDouble();
            }
            incluster = false;
            if(!noiseInClusterOption.isSet() && counter > 0){
                counter--;
                for(int c = 0; c < kernels.size(); c++){
                    for(int m = 0; m < kernels.get(c).microClusters.size(); m++){
                        Instance inst = new DenseInstance(1, sample);
                        if(kernels.get(c).microClusters.get(m).getInclusionProbability(inst) > 0){
                            incluster = true;
                            break;
                        }
                    }
                    if(incluster)
                        break;
                }
            }
        }
//        double [] sample = new double [numAttsOption.getValue()];
//        for (int j = 0; j < numAttsOption.getValue(); j++) {
//             sample[j] = instanceRandom.nextDouble();
//        }
        return sample;
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.getParameterString ()
Definition at line 966 of file RandomRBFGeneratorEvents.java.
{
        return "";
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 961 of file RandomRBFGeneratorEvents.java.
{
            return "Generates a random radial basis function stream.";
    }
boolean moa.streams.clustering.RandomRBFGeneratorEvents.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 467 of file RandomRBFGeneratorEvents.java.
Referenced by moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), and moa.clusterers.outliers.AbstractC.Test.main().
{
            return true;
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.initKernels () [protected]
Definition at line 513 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.clusterIdCounter, moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, and moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.restart().
{
        for (int i = 0; i < numClusterOption.getValue(); i++) {
            kernels.add(new GeneratorCluster(clusterIdCounter));
            numActiveKernels++;
            clusterIdCounter++;
        }
        normalizeWeights();
    }
boolean moa.streams.clustering.RandomRBFGeneratorEvents.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 471 of file RandomRBFGeneratorEvents.java.
{
            return true;
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels (int steps) [private]
Definition at line 787 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.debug, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getDistanceVector(), moa.cluster.Cluster.getId(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.maxDistanceMoveThresholdByStep, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterA, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterB, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.merging, moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), moa.streams.clustering.RandomRBFGeneratorEvents.speedOption, and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
{
        if(numActiveKernels >1 && ((mergeClusterA == null && mergeClusterB == null))){
            //choose clusters to merge
            double diseredDist = steps / speedOption.getValue() * maxDistanceMoveThresholdByStep;
            double minDist = Double.MAX_VALUE;
//          System.out.println("DisredDist:"+(2*diseredDist));
            for(int i = 0; i < kernels.size(); i++){
                for(int j = 0; j < i; j++){
                    if(kernels.get(i).kill!=-1 || kernels.get(j).kill!=-1){
                        continue;
                    }
                    else{
                        double kernelDist = kernels.get(i).generator.getCenterDistance(kernels.get(j).generator);
                        double d = kernelDist-2*diseredDist;
//                      System.out.println("Dist:"+i+" / "+j+" "+d);
                        if(Math.abs(d) < minDist &&
                                (minDist != Double.MAX_VALUE || d>0 || Math.abs(d) < 0.001)){
                            minDist = Math.abs(d);
                            mergeClusterA = kernels.get(i);
                            mergeClusterB = kernels.get(j);
                        }
                    }
                }
            }
            if(mergeClusterA!=null && mergeClusterB!=null){
                double[] merge_point = mergeClusterA.generator.getCenter();
                double[] v = mergeClusterA.generator.getDistanceVector(mergeClusterB.generator);
                for (int i = 0; i < v.length; i++) {
                    merge_point[i]= merge_point[i]+v[i]*0.5;
                }
                mergeClusterA.merging = true;
                mergeClusterB.merging = true;
                mergeClusterA.setDesitnation(merge_point);
                mergeClusterB.setDesitnation(merge_point);
                if(debug){
                    System.out.println("Center1"+Arrays.toString(mergeClusterA.generator.getCenter()));
                    System.out.println("Center2"+Arrays.toString(mergeClusterB.generator.getCenter()));
                    System.out.println("Vector"+Arrays.toString(v));
                    System.out.println("Try to merge cluster "+mergeClusterA.generator.getId()+
                            " into "+mergeClusterB.generator.getId()+
                            " at "+Arrays.toString(merge_point)+
                            " time "+numGeneratedInstances);
                }
                return "Init merge";
            }
        }
        if(mergeClusterA != null && mergeClusterB != null){
            //movekernels will move the kernels close to each other,
            //we just need to check and merge here if they are close enough
            return mergeClusterA.tryMerging(mergeClusterB);
        }
        return "";
    }
Instance moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 522 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.chooseWeightedElement(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.getHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.noiseLevelOption, moa.streams.clustering.ClusteringStream.numAttsOption, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption, and moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances.
Referenced by moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), and moa.clusterers.outliers.AbstractC.Test.main().
{
        numGeneratedInstances++;
        eventScheduler();
        //make room for the classlabel
        double[] values_new = new double [numAttsOption.getValue()+1];
        double[] values = null;
        int clusterChoice = -1;
        if(instanceRandom.nextDouble() > noiseLevelOption.getValue()){
            clusterChoice = chooseWeightedElement();
            values = kernels.get(clusterChoice).generator.sample(instanceRandom).toDoubleArray();
        }
        else{
            //get ranodm noise point
            values = getNoisePoint();
        }
        if(Double.isNaN(values[0])){
            System.out.println("Instance corrupted:"+numGeneratedInstances);
        }
        System.arraycopy(values, 0, values_new, 0, values.length);
        Instance inst = new DenseInstance(1.0, values_new);
        inst.setDataset(getHeader());
        if(clusterChoice == -1){
            // 2013/06/02 (Yunsu Kim)
            // Noise instance has the last class value instead of "-1"
            // Preventing ArrayIndexOutOfBoundsException in WriteStreamToARFFFile
            inst.setClassValue(numClusterOption.getValue());
        }
        else{
            inst.setClassValue(kernels.get(clusterChoice).generator.getId());
            //Do we need micro cluster representation if have overlapping clusters?
            //if(!overlappingOption.isSet())
                kernels.get(clusterChoice).addInstance(inst);
        }
//        System.out.println(numGeneratedInstances+": Overlap is"+updateOverlaps());
        return inst;
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights () [private]
Definition at line 905 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.changeWeight(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        double sumWeights = 0.0;
        for (int i = 0; i < kernels.size(); i++) {
            sumWeights+=kernels.get(i).generator.getWeight();
        }
        for (int i = 0; i < kernels.size(); i++) {
            kernels.get(i).generator.setWeight(kernels.get(i).generator.getWeight()/sumWeights);
        }
    }
void moa.streams.clustering.RandomRBFGeneratorEvents.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 476 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), and moa.tasks.TaskMonitor.setCurrentActivity().
{
        monitor.setCurrentActivity("Preparing random RBF...", -1.0);
        generateHeader();
        restart();
    }
synchronized void moa.streams.clustering.RandomRBFGeneratorEvents.removeClusterChangeListener (ClusterEventListener l)
Remove a listener.
Definition at line 928 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.listeners.
{
    if (listeners == null)
      listeners = new Vector();
    listeners.removeElement(l);
  }
void moa.streams.clustering.RandomRBFGeneratorEvents.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 482 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.clusterIdCounter, moa.streams.clustering.RandomRBFGeneratorEvents.eventFrequencyOption, moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandomSeedOption, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterA, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterB, moa.streams.clustering.RandomRBFGeneratorEvents.nextEventChoice, moa.streams.clustering.RandomRBFGeneratorEvents.nextEventCounter, moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, and moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.prepareForUseImpl().
{
            instanceRandom = new Random(instanceRandomSeedOption.getValue());
            nextEventCounter = eventFrequencyOption.getValue();
            nextEventChoice = getNextEvent();
            numActiveKernels = 0;
            numGeneratedInstances = 0;
            clusterIdCounter = 0;
            mergeClusterA = mergeClusterB = null;
            kernels = new AutoExpandVector<GeneratorCluster>();
            initKernels();
    }
String moa.streams.clustering.RandomRBFGeneratorEvents.splitKernel () [private]
Definition at line 777 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, and moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
{
        int id = instanceRandom.nextInt(kernels.size());
        while(kernels.get(id).kill!=-1)
            id = instanceRandom.nextInt(kernels.size());
        String message = kernels.get(id).splitKernel();
        return message;
    }
Member Data Documentation
int moa.streams.clustering.RandomRBFGeneratorEvents.clusterIdCounter [private]
Definition at line 115 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
boolean moa.streams.clustering.RandomRBFGeneratorEvents.debug = false [private]
Definition at line 106 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels().
FloatOption moa.streams.clustering.RandomRBFGeneratorEvents.densityRangeOption
Initial value:
 new FloatOption("densityRange", 'd',
                    "Offset of the average weight a cluster has. Value of 0 means all cluster " +
                    "contain the same amount of points.", 0, 0, 1)
Definition at line 74 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
FlagOption moa.streams.clustering.RandomRBFGeneratorEvents.eventDeleteCreateOption
Initial value:
 new FlagOption("eventDeleteCreate", 'C',
                    "Enable emering and disapperaing of clusters. Set eventFrequency and numClusterRange!")
Definition at line 96 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.eventFrequencyOption
Initial value:
 new IntOption("eventFrequency", 'E',
                    "Event frequency. Enable at least one of the events below and set numClusterRange!", 30000, 0, Integer.MAX_VALUE)
Definition at line 90 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.restart().
double moa.streams.clustering.RandomRBFGeneratorEvents.eventFrequencyRange = 0 [private]
Definition at line 104 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler().
FlagOption moa.streams.clustering.RandomRBFGeneratorEvents.eventMergeSplitOption
Initial value:
 new FlagOption("eventMergeSplitOption", 'M',
                    "Enable merging and splitting of clusters. Set eventFrequency and numClusterRange!")
Definition at line 93 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent().
Random moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom [protected]
Definition at line 109 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.changeRadius(), moa.streams.clustering.RandomRBFGeneratorEvents.changeWeight(), moa.streams.clustering.RandomRBFGeneratorEvents.chooseWeightedElement(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector(), moa.streams.clustering.RandomRBFGeneratorEvents.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandomSeedOption
Initial value:
 new IntOption(
                    "instanceRandomSeed", 'i',
                    "Seed for random generation of instances.", 5)
Definition at line 58 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.restart().
int moa.streams.clustering.RandomRBFGeneratorEvents.kernelMovePointFrequency = 10 [private]
Definition at line 101 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
FloatOption moa.streams.clustering.RandomRBFGeneratorEvents.kernelRadiiOption
Initial value:
 new FloatOption("kernelRadius", 'R',
                    "The average radii of the centroids in the model.", 0.07, 0, 1)
Definition at line 68 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
FloatOption moa.streams.clustering.RandomRBFGeneratorEvents.kernelRadiiRangeOption
Initial value:
 new FloatOption("kernelRadiusRange", 'r',
                    "Deviation of average radii of the centroids in the model.", 0, 0, 1)
Definition at line 71 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster().
AutoExpandVector<GeneratorCluster> moa.streams.clustering.RandomRBFGeneratorEvents.kernels [private]
Definition at line 108 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.changeRadius(), moa.streams.clustering.RandomRBFGeneratorEvents.changeWeight(), moa.streams.clustering.RandomRBFGeneratorEvents.chooseWeightedElement(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.getGeneratingClusters(), moa.streams.clustering.RandomRBFGeneratorEvents.getMicroClustering(), moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.getWorkID(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), moa.streams.clustering.RandomRBFGeneratorEvents.splitKernel(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
transient Vector moa.streams.clustering.RandomRBFGeneratorEvents.listeners [private]
Definition at line 51 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.addClusterChangeListener(), moa.streams.clustering.RandomRBFGeneratorEvents.fireClusterChange(), and moa.streams.clustering.RandomRBFGeneratorEvents.removeClusterChangeListener().
double moa.streams.clustering.RandomRBFGeneratorEvents.maxDistanceMoveThresholdByStep = 0.01 [private]
Definition at line 102 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
int moa.streams.clustering.RandomRBFGeneratorEvents.maxOverlapFitRuns = 50 [private]
Definition at line 103 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster().
double moa.streams.clustering.RandomRBFGeneratorEvents.merge_threshold = 0.7 [private]
Definition at line 100 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
GeneratorCluster moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterA [private]
Definition at line 116 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
GeneratorCluster moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterB [private]
Definition at line 117 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
boolean moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernelsOverlapping = false [private]
Definition at line 118 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.modelRandomSeedOption
Initial value:
 new IntOption("modelRandomSeed",
                    'm', "Seed for random generation of model.", 1)
Definition at line 55 of file RandomRBFGeneratorEvents.java.
int moa.streams.clustering.RandomRBFGeneratorEvents.nextEventChoice = -1 [private]
Definition at line 114 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.restart().
int moa.streams.clustering.RandomRBFGeneratorEvents.nextEventCounter [private]
Definition at line 113 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.restart().
FlagOption moa.streams.clustering.RandomRBFGeneratorEvents.noiseInClusterOption
Initial value:
 new FlagOption("noiseInCluster", 'n',
                    "Allow noise to be placed within a cluster")
Definition at line 87 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), and moa.streams.clustering.RandomRBFGeneratorEvents.RandomRBFGeneratorEvents().
FloatOption moa.streams.clustering.RandomRBFGeneratorEvents.noiseLevelOption
Initial value:
 new FloatOption("noiseLevel", 'N',
                    "Noise level", 0.1, 0, 1)
Definition at line 84 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), and moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance().
int moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels [private]
Definition at line 112 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.changeWeight(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.fadeIn(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption
Initial value:
 new IntOption("numCluster", 'K',
                    "The average number of centroids in the model.", 5, 1, Integer.MAX_VALUE)
Definition at line 62 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.numClusterRangeOption
Initial value:
 new IntOption("numClusterRange", 'k',
                    "Deviation of the number of centroids in the model.", 3, 0, Integer.MAX_VALUE)
Definition at line 65 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), and moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent().
int moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances [private]
Definition at line 111 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
final long moa.streams.clustering.RandomRBFGeneratorEvents.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 53 of file RandomRBFGeneratorEvents.java.
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.speedOption
Initial value:
 new IntOption("speed", 'V',
                    "Kernels move a predefined distance of 0.01 every X points", 500, 1, Integer.MAX_VALUE)
Definition at line 78 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
IntOption moa.streams.clustering.RandomRBFGeneratorEvents.speedRangeOption
Initial value:
 new IntOption("speedRange", 'v',
                    "Speed/Velocity point offset", 0, 0, Integer.MAX_VALUE)
Definition at line 81 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
InstancesHeader moa.streams.clustering.RandomRBFGeneratorEvents.streamHeader [protected]
Definition at line 110 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), and moa.streams.clustering.RandomRBFGeneratorEvents.getHeader().
The documentation for this class was generated from the following file:
main/java/moa/streams/clustering/RandomRBFGeneratorEvents.java