MOA: moa.evaluation.BasicClusteringPerformanceEvaluator Class Reference
moa.evaluation.BasicClusteringPerformanceEvaluator Class Reference
Clustering evaluator that performs basic incremental evaluation.
Public Member Functions
void reset ()
void addLearningAttempt (int trueClass, double[] classVotes, double weight)
Measurement[] getPerformanceMeasurements ()
double getTotalWeightObserved ()
double getFractionCorrectlyClassified ()
double getFractionIncorrectlyClassified ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
double weightObserved
double weightCorrect
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Clustering evaluator that performs basic incremental evaluation.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 32 of file BasicClusteringPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.BasicClusteringPerformanceEvaluator.addLearningAttempt (int trueClass, double[] classVotes, double weight)
Implements moa.evaluation.LearningPerformanceEvaluator.
Definition at line 48 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.weightCorrect, and moa.evaluation.BasicClusteringPerformanceEvaluator.weightObserved.
{
        if (weight > 0.0) {
            this.weightObserved += weight;
            if (Utils.maxIndex(classVotes) == trueClass) {
                this.weightCorrect += weight;
            }
        }
    }
void moa.evaluation.BasicClusteringPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 82 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionCorrectlyClassified ()
Definition at line 72 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.weightCorrect, and moa.evaluation.BasicClusteringPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionIncorrectlyClassified().
{
        return this.weightObserved > 0.0 ? this.weightCorrect
                / this.weightObserved : 0.0;
    }
double moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionIncorrectlyClassified ()
Definition at line 77 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionCorrectlyClassified().
{
        return 1.0 - getFractionCorrectlyClassified();
    }
Measurement [] moa.evaluation.BasicClusteringPerformanceEvaluator.getPerformanceMeasurements ()
Implements moa.evaluation.LearningPerformanceEvaluator.
Definition at line 59 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.getTotalWeightObserved().
Referenced by moa.evaluation.BasicClusteringPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
                    new Measurement("instances",
                    getTotalWeightObserved())
                //,new Measurement("classifications correct (percent)",
                //      getFractionCorrectlyClassified() * 100.0)
                };
    }
double moa.evaluation.BasicClusteringPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 68 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClusteringPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved;
    }
void moa.evaluation.BasicClusteringPerformanceEvaluator.reset ()
Implements moa.evaluation.LearningPerformanceEvaluator.
Definition at line 42 of file BasicClusteringPerformanceEvaluator.java.
References moa.evaluation.BasicClusteringPerformanceEvaluator.weightCorrect, and moa.evaluation.BasicClusteringPerformanceEvaluator.weightObserved.
{
        this.weightObserved = 0.0;
        this.weightCorrect = 0.0;
    }
Member Data Documentation
final long moa.evaluation.BasicClusteringPerformanceEvaluator.serialVersionUID = 1L [static, private]
Definition at line 35 of file BasicClusteringPerformanceEvaluator.java.
double moa.evaluation.BasicClusteringPerformanceEvaluator.weightCorrect [protected]
Definition at line 39 of file BasicClusteringPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClusteringPerformanceEvaluator.addLearningAttempt(), moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionCorrectlyClassified(), and moa.evaluation.BasicClusteringPerformanceEvaluator.reset().
double moa.evaluation.BasicClusteringPerformanceEvaluator.weightObserved [protected]
Definition at line 37 of file BasicClusteringPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClusteringPerformanceEvaluator.addLearningAttempt(), moa.evaluation.BasicClusteringPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.BasicClusteringPerformanceEvaluator.getTotalWeightObserved(), and moa.evaluation.BasicClusteringPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/BasicClusteringPerformanceEvaluator.java