MOA: moa.classifiers.core.conditionaltests.InstanceConditionalTest Class Reference
moa.classifiers.core.conditionaltests.InstanceConditionalTest Class Reference
Abstract conditional test for instances to use to split nodes in Hoeffding trees.
Public Member Functions
abstract int branchForInstance (Instance inst)
Returns the number of the branch for an instance, -1 if unknown.
boolean resultKnownForInstance (Instance inst)
Gets whether the number of the branch for an instance is known.
abstract int maxBranches ()
Gets the number of maximum branches, -1 if unknown.
abstract String describeConditionForBranch (int branch, InstancesHeader context)
Gets the text that describes the condition of a branch.
abstract int[] getAttsTestDependsOn ()
Returns an array with the attributes that the test depends on.
Detailed Description
Abstract conditional test for instances to use to split nodes in Hoeffding trees.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file InstanceConditionalTest.java.
Member Function Documentation
abstract int moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance (Instance inst) [pure virtual]
Returns the number of the branch for an instance, -1 if unknown.
Parameters:
inst the instance to be used
Returns:
the number of the branch for an instance, -1 if unknown.
Implemented in moa.classifiers.core.conditionaltests.NominalAttributeBinaryTest, moa.classifiers.core.conditionaltests.NominalAttributeMultiwayTest, moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest, and moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.
Referenced by moa.classifiers.trees.ORTO.SplitNode.getPrediction(), moa.classifiers.trees.DecisionStump.getVotesForInstance(), moa.classifiers.trees.ORTO.SplitNode.instanceChildIndex(), moa.classifiers.trees.HoeffdingTree.SplitNode.instanceChildIndex(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.instanceChildIndex(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), and moa.classifiers.core.conditionaltests.InstanceConditionalTest.resultKnownForInstance().
abstract String moa.classifiers.core.conditionaltests.InstanceConditionalTest.describeConditionForBranch (int branch, InstancesHeader context) [pure virtual]
Gets the text that describes the condition of a branch.
It is used to describe the branch.
Parameters:
branch the number of the branch to describe
context the context or header of the data stream
Returns:
the text that describes the condition of the branch
Implemented in moa.classifiers.core.conditionaltests.NominalAttributeBinaryTest, moa.classifiers.core.conditionaltests.NominalAttributeMultiwayTest, moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest, and moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree().
abstract int [] moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn () [pure virtual]
Returns an array with the attributes that the test depends on.
Returns:
an array with the attributes that the test depends on
Implemented in moa.classifiers.core.conditionaltests.NominalAttributeBinaryTest, moa.classifiers.core.conditionaltests.NominalAttributeMultiwayTest, moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest, and moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.addToOptionTable(), moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), moa.classifiers.trees.FIMTDD.FIMTDD_attemptToSplit(), and moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
abstract int moa.classifiers.core.conditionaltests.InstanceConditionalTest.maxBranches () [pure virtual]
Gets the number of maximum branches, -1 if unknown.
Returns:
the number of maximum branches, -1 if unknown..
Implemented in moa.classifiers.core.conditionaltests.InstanceConditionalBinaryTest, and moa.classifiers.core.conditionaltests.NominalAttributeMultiwayTest.
Referenced by moa.classifiers.trees.ORTO.SplitNode.setChild(), moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild().
boolean moa.classifiers.core.conditionaltests.InstanceConditionalTest.resultKnownForInstance (Instance inst)
Gets whether the number of the branch for an instance is known.
Parameters:
inst
Returns:
true if the number of the branch for an instance is known
Definition at line 48 of file InstanceConditionalTest.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance().
{
        return branchForInstance(inst) >= 0;
    }
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/conditionaltests/InstanceConditionalTest.java