MOA: moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch Class Reference
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch Class Reference
Abstract class for nearest neighbour search.
Classes
class MyHeap
A class for a heap to store the nearest k neighbours to an instance.
class MyHeapElement
A class for storing data about a neighboring instance.
class NeighborList
A class for a linked list to store the nearest k neighbours to an instance.
class NeighborNode
A class for storing data about a neighboring instance.
Public Member Functions
NearestNeighbourSearch ()
Constructor.
NearestNeighbourSearch (Instances insts)
Constructor.
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
String distanceFunctionTipText ()
Returns the tip text for this property.
DistanceFunction getDistanceFunction ()
returns the distance function currently in use.
void setDistanceFunction (DistanceFunction df) throws Exception
sets the distance function to use for nearest neighbour search.
String measurePerformanceTipText ()
Returns the tip text for this property.
boolean getMeasurePerformance ()
Gets whether performance statistics are being calculated or not.
abstract Instance nearestNeighbour (Instance target) throws Exception
Returns the nearest instance in the current neighbourhood to the supplied instance.
abstract Instances kNearestNeighbours (Instance target, int k) throws Exception
Returns k nearest instances in the current neighbourhood to the supplied instance.
abstract double[] getDistances () throws Exception
Returns the distances of the k nearest neighbours.
abstract void update (Instance ins) throws Exception
Updates the NearNeighbourSearch algorithm for the new added instance.
void addInstanceInfo (Instance ins)
Adds information from the given instance without modifying the datastructure a lot.
void setInstances (Instances insts) throws Exception
Sets the instances.
Instances getInstances ()
returns the instances currently set.
Static Public Member Functions
static void combSort11 (double arrayToSort[], int linkedArray[])
sorts the two given arrays.
static void quickSort (double[] arrayToSort, double[] linkedArray, int left, int right)
performs quicksort.
Static Protected Member Functions
static int partition (double[] arrayToSort, double[] linkedArray, int l, int r)
Partitions the instances around a pivot.
Protected Attributes
Instances m_Instances
The neighbourhood of instances to find neighbours in.
int m_kNN
The number of neighbours to find.
DistanceFunction m_DistanceFunction = new EuclideanDistance()
the distance function used.
boolean m_MeasurePerformance = false
Should we measure Performance.
Detailed Description
Abstract class for nearest neighbour search.
All algorithms (classes) that do nearest neighbour search should extend this class.
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 34 of file NearestNeighbourSearch.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NearestNeighbourSearch ()
Constructor.
Definition at line 499 of file NearestNeighbourSearch.java.
{
  }
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NearestNeighbourSearch (Instances insts)
Constructor.
Parameters:
insts The set of instances that constitute the neighbourhood.
Definition at line 507 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances.
{
    this();
    m_Instances = insts;
  }
Member Function Documentation
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.addInstanceInfo (Instance ins)
Adds information from the given instance without modifying the datastructure a lot.
Parameters:
ins the instance to add the information from
Reimplemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Definition at line 623 of file NearestNeighbourSearch.java.
{
  }
static void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.combSort11 (double arrayToSort[], int linkedArray[]) [static]
sorts the two given arrays.
Parameters:
arrayToSort The array sorting should be based on.
linkedArray The array that should have the same ordering as arrayToSort.
Definition at line 653 of file NearestNeighbourSearch.java.
{
    int switches, j, top, gap;
    double hold1; int hold2;
    gap = arrayToSort.length;
    do {
      gap=(int)(gap/1.3);
      switch(gap) {
        case 0:
          gap = 1;
          break;
        case 9:
        case 10:
          gap=11;
          break;
        default:
          break;
      }
      switches=0;
      top = arrayToSort.length-gap;
      for(int i=0; i<top; i++) {
        j=i+gap;
        if(arrayToSort[i] > arrayToSort[j]) {
          hold1=arrayToSort[i];
          hold2=linkedArray[i];
          arrayToSort[i]=arrayToSort[j];
          linkedArray[i]=linkedArray[j];
          arrayToSort[j]=hold1;
          linkedArray[j]=hold2;
          switches++;
        }//endif
      }//endfor
    } while(switches>0 || gap>1);
  }
String moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.distanceFunctionTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 531 of file NearestNeighbourSearch.java.
{
    return "The distance function to use for finding neighbours " +
           "(default: weka.core.EuclideanDistance). ";
  }
DistanceFunction moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getDistanceFunction ()
returns the distance function currently in use.
Returns:
the distance function
Reimplemented in moa.classifiers.lazy.neighboursearch.KDTree.
Definition at line 541 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction.
{
    return m_DistanceFunction;
  }
abstract double [] moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getDistances () throws Exception [pure virtual]
Returns the distances of the k nearest neighbours.
The kNearestNeighbours or nearestNeighbour needs to be called first for this to work.
Returns:
the distances
Exceptions:
Exception if called before calling kNearestNeighbours or nearestNeighbours.
Implemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Instances moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getInstances ()
returns the instances currently set.
Returns:
the current instances
Definition at line 641 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances.
{
    return m_Instances;
  }
boolean moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getMeasurePerformance ()
Gets whether performance statistics are being calculated or not.
Returns:
true if the measure performance is calculated
Definition at line 571 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_MeasurePerformance.
{
    return m_MeasurePerformance;
  }
String moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Reimplemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Definition at line 518 of file NearestNeighbourSearch.java.
{
    return
        "Abstract class for nearest neighbour search. All algorithms (classes) that "
      + "do nearest neighbour search should extend this class.";
  }
abstract Instances moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.kNearestNeighbours (Instance target, int k) throws Exception [pure virtual]
Returns k nearest instances in the current neighbourhood to the supplied instance.
Parameters:
target The instance to find the k nearest neighbours for.
k The number of nearest neighbours to find.
Returns:
the k nearest neighbors
Exceptions:
Exception if the neighbours could not be found.
Implemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance().
String moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.measurePerformanceTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 561 of file NearestNeighbourSearch.java.
{
    return "Whether to calculate performance statistics " +
           "for the NN search or not";
  }
abstract Instance moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.nearestNeighbour (Instance target) throws Exception [pure virtual]
Returns the nearest instance in the current neighbourhood to the supplied instance.
Parameters:
target The instance to find the nearest neighbour for.
Returns:
the nearest neighbor
Exceptions:
Exception if the nearest neighbour could not be found.
Implemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
static int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.partition (double[] arrayToSort, double[] linkedArray, int l, int r) [static, protected]
Partitions the instances around a pivot.
Used by quicksort and kthSmallestValue.
Parameters:
arrayToSort the array of doubles to be sorted
linkedArray the linked array
l the first index of the subset
r the last index of the subset
Returns:
the index of the middle element
Definition at line 697 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.quickSort().
{
    double pivot = arrayToSort[(l + r) / 2];
    double help;
    while (l < r) {
      while ((arrayToSort[l] < pivot) && (l < r)) {
        l++;
      }
      while ((arrayToSort[r] > pivot) && (l < r)) {
        r--;
      }
      if (l < r) {
        help = arrayToSort[l];
        arrayToSort[l] = arrayToSort[r];
        arrayToSort[r] = help;
        help = linkedArray[l];
        linkedArray[l] = linkedArray[r];
        linkedArray[r] = help;
        l++;
        r--;
      }
    }
    if ((l == r) && (arrayToSort[r] > pivot)) {
      r--;
    }
    return r;
  }
static void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.quickSort (double[] arrayToSort, double[] linkedArray, int left, int right) [static]
performs quicksort.
Parameters:
arrayToSort the array to sort
linkedArray the linked array
left the first index of the subset
right the last index of the subset
Definition at line 734 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.partition().
{
    if (left < right) {
      int middle = partition(arrayToSort, linkedArray, left, right);
      quickSort(arrayToSort, linkedArray, left, middle);
      quickSort(arrayToSort, linkedArray, middle + 1, right);
    }
  }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.setDistanceFunction (DistanceFunction df) throws Exception
sets the distance function to use for nearest neighbour search.
Parameters:
df the new distance function to use
Exceptions:
Exception if instances cannot be processed
Reimplemented in moa.classifiers.lazy.neighboursearch.KDTree.
Definition at line 551 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction.
{
    m_DistanceFunction = df;
  }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.setInstances (Instances insts) throws Exception
Sets the instances.
Parameters:
insts the instances to use
Exceptions:
Exception if setting fails
Reimplemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Definition at line 632 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances.
Referenced by moa.classifiers.lazy.kNN.getVotesForInstance().
{
    m_Instances = insts;
  }
abstract void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.update (Instance ins) throws Exception [pure virtual]
Updates the NearNeighbourSearch algorithm for the new added instance.
P.S.: The method assumes the instance has already been added to the m_Instances object by the caller.
Parameters:
ins the instance to add
Exceptions:
Exception if updating fails
Implemented in moa.classifiers.lazy.neighboursearch.KDTree, and moa.classifiers.lazy.neighboursearch.LinearNNSearch.
Member Data Documentation
DistanceFunction moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction = new EuclideanDistance() [protected]
the distance function used.
Definition at line 491 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getDistanceFunction(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.LinearNNSearch(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.setDistanceFunction(), moa.classifiers.lazy.neighboursearch.KDTree.setDistanceFunction(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.setInstances(), and moa.classifiers.lazy.neighboursearch.LinearNNSearch.update().
Instances moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances [protected]
The neighbourhood of instances to find neighbours in.
Definition at line 485 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.addInstanceInfo(), moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters(), moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), moa.classifiers.lazy.neighboursearch.KDTree.clipToInsideHrect(), moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.getDistances(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getInstances(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.NearestNeighbourSearch(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.setInstances(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.setInstances(), moa.classifiers.lazy.neighboursearch.LinearNNSearch.update(), moa.classifiers.lazy.neighboursearch.KDTree.update(), and moa.classifiers.lazy.neighboursearch.KDTree.widestDim().
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_kNN [protected]
The number of neighbours to find.
Definition at line 488 of file NearestNeighbourSearch.java.
boolean moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_MeasurePerformance = false [protected]
Should we measure Performance.
Definition at line 494 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.getMeasurePerformance(), and moa.classifiers.lazy.neighboursearch.KDTree.setMeasurePerformance().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/NearestNeighbourSearch.java