MOA: moa.test.DiffUtils.SideBySideDiff Class Reference
moa.test.DiffUtils.SideBySideDiff Class Reference
Container object for a side-by-side diff.
Public Member Functions
SideBySideDiff ()
Initializes the container with an empty diff.
SideBySideDiff (List[] diff)
Initializes the container.
List getLeft ()
Return the diff of the left/first list/file.
List getRight ()
Return the diff of the right/second list/file.
List getIndicator ()
Returns the indicator list.
List getStartPos ()
Return the list with starting positions of the deltas.
boolean hasDifferences ()
Returns whether there are any differences between the two files/lists.
int differences ()
Returns the number of differences.
int lineToDelta (int line)
Returns the closest patch delta index for the given line number.
int deltaToLine (int delta, boolean start)
Returns the line number (start or end) of the given delta.
boolean hasNextDelta (int line)
Checks whether there is a next delta after the current line.
int getNextDelta (int line)
Returns the next delta after the current line.
boolean hasPreviousDelta (int line)
Checks whether there is a previous delta after the current line.
int getPreviousDelta (int line)
Returns the previous delta after the current line.
SideBySideDiff clone ()
Returns a clone if itself.
String toString (String separator)
Generates a string representation of the diff information.
String toString ()
Generates a string representation of the diff information.
Protected Attributes
List[] m_Diff
the diff information.
Static Private Attributes
static final long serialVersionUID = -6775907286936991130L
for serialization.
Detailed Description
Container object for a side-by-side diff.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
Revision
6358
Definition at line 99 of file DiffUtils.java.
Constructor & Destructor Documentation
moa.test.DiffUtils.SideBySideDiff.SideBySideDiff ()
Initializes the container with an empty diff.
Definition at line 111 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.clone().
{
      this(
      new List[]{
          new ArrayList(),
          new ArrayList(),
          new ArrayList(),
          new ArrayList(),
          new ArrayList()});
    }
moa.test.DiffUtils.SideBySideDiff.SideBySideDiff (List[] diff)
Initializes the container.
Definition at line 124 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_SIZE.
{
      if (diff.length != SIDEBYSIDE_SIZE)
    throw new IllegalArgumentException("Expected array with length " + SIDEBYSIDE_SIZE + " but got: " + diff.length);
      m_Diff = diff.clone();
    }
Member Function Documentation
SideBySideDiff moa.test.DiffUtils.SideBySideDiff.clone ()
Returns a clone if itself.
Returns:
the clone
Definition at line 304 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SideBySideDiff.SideBySideDiff().
{
      return new SideBySideDiff(m_Diff);
    }
int moa.test.DiffUtils.SideBySideDiff.deltaToLine (int delta, boolean start)
Returns the line number (start or end) of the given delta.
Parameters:
delta the 0-based delta index
Returns:
the line number, -1 if failed to determine
Definition at line 219 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, moa.test.DiffUtils.SIDEBYSIDE_ENDPOS, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
{
      int   result;
      result = -1;
      if ((delta >= 0) && (delta < m_Diff[SIDEBYSIDE_STARTPOS].size())) {
    if (start)
      result = (Integer) m_Diff[SIDEBYSIDE_STARTPOS].get(delta);
    else
      result = (Integer) m_Diff[SIDEBYSIDE_ENDPOS].get(delta);
      }
      return result;
    }
int moa.test.DiffUtils.SideBySideDiff.differences ()
Returns the number of differences.
Returns:
the number of differences
Definition at line 180 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
{
      return m_Diff[SIDEBYSIDE_STARTPOS].size();
    }
List moa.test.DiffUtils.SideBySideDiff.getIndicator ()
Returns the indicator list.
Returns:
the indicator
Definition at line 153 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_INDICATOR.
{
      return m_Diff[SIDEBYSIDE_INDICATOR];
    }
List moa.test.DiffUtils.SideBySideDiff.getLeft ()
Return the diff of the left/first list/file.
Returns:
the diff
Definition at line 135 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_FIRST.
{
      return m_Diff[SIDEBYSIDE_FIRST];
    }
int moa.test.DiffUtils.SideBySideDiff.getNextDelta (int line)
Returns the next delta after the current line.
Parameters:
line the current line number (0-based)
Returns:
the next delta index, -1 if none available
Definition at line 250 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.lineToDelta(), moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
Referenced by moa.test.DiffUtils.SideBySideDiff.hasNextDelta().
{
      int   result;
      int   delta;
      result = -1;
      delta  = lineToDelta(line);
      if (delta == -1)
    return result;
      delta++;
      if (delta < m_Diff[SIDEBYSIDE_STARTPOS].size())
    result = delta;
      return result;
    }
int moa.test.DiffUtils.SideBySideDiff.getPreviousDelta (int line)
Returns the previous delta after the current line.
Parameters:
line the current line number (0-based)
Returns:
the previous delta index, -1 if none available
Definition at line 282 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.lineToDelta().
Referenced by moa.test.DiffUtils.SideBySideDiff.hasPreviousDelta().
{
      int   result;
      int   delta;
      result = -1;
      delta  = lineToDelta(line);
      if (delta == -1)
    return result;
      delta--;
      if (delta >= 0)
    result = delta;
      return result;
    }
List moa.test.DiffUtils.SideBySideDiff.getRight ()
Return the diff of the right/second list/file.
Returns:
the diff
Definition at line 144 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_SECOND.
{
      return m_Diff[SIDEBYSIDE_SECOND];
    }
List moa.test.DiffUtils.SideBySideDiff.getStartPos ()
Return the list with starting positions of the deltas.
Returns:
the list with start positions
Definition at line 162 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
{
      return m_Diff[SIDEBYSIDE_STARTPOS];
    }
boolean moa.test.DiffUtils.SideBySideDiff.hasDifferences ()
Returns whether there are any differences between the two files/lists.
Returns:
true if there are differences
Definition at line 171 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
Referenced by moa.test.DiffUtils.SideBySideDiff.lineToDelta().
{
      return (m_Diff[SIDEBYSIDE_STARTPOS].size() > 0);
    }
boolean moa.test.DiffUtils.SideBySideDiff.hasNextDelta (int line)
Checks whether there is a next delta after the current line.
Parameters:
line the current line number (0-based)
Returns:
the next delta index, -1 if none available
Definition at line 240 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.getNextDelta().
{
      return (getNextDelta(line) != -1);
    }
boolean moa.test.DiffUtils.SideBySideDiff.hasPreviousDelta (int line)
Checks whether there is a previous delta after the current line.
Parameters:
line the current line number (0-based)
Returns:
the previous delta index, -1 if none available
Definition at line 272 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.getPreviousDelta().
{
      return (getPreviousDelta(line) != -1);
    }
int moa.test.DiffUtils.SideBySideDiff.lineToDelta (int line)
Returns the closest patch delta index for the given line number.
Parameters:
line the 0-based line number
Returns:
the index of the delta, -1 if no delta matched
Definition at line 190 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.hasDifferences(), moa.test.DiffUtils.SideBySideDiff.m_Diff, moa.test.DiffUtils.SIDEBYSIDE_ENDPOS, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
Referenced by moa.test.DiffUtils.SideBySideDiff.getNextDelta(), and moa.test.DiffUtils.SideBySideDiff.getPreviousDelta().
{
      int   result;
      int   i;
      List  start;
      List  end;
      result = -1;
      if (!hasDifferences())
    return result;
      start = m_Diff[SIDEBYSIDE_STARTPOS];
      end   = m_Diff[SIDEBYSIDE_ENDPOS];
      for (i = 0; i < start.size(); i++) {
    if ((((Integer) start.get(i)) >= line) && (line <= ((Integer) end.get(i)))) {
      result = i;
      break;
    }
      }
      return result;
    }
String moa.test.DiffUtils.SideBySideDiff.toString ()
Generates a string representation of the diff information.
Returns:
the string representation
Definition at line 338 of file DiffUtils.java.
References moa.test.DiffUtils.SEPARATOR_SIDEBYSIDE.
{
      return toString(SEPARATOR_SIDEBYSIDE);
    }
String moa.test.DiffUtils.SideBySideDiff.toString (String separator)
Generates a string representation of the diff information.
Parameters:
separator the separator between the columns
Returns:
the string representation
Definition at line 314 of file DiffUtils.java.
References moa.test.DiffUtils.SideBySideDiff.m_Diff, moa.test.DiffUtils.SIDEBYSIDE_FIRST, moa.test.DiffUtils.SIDEBYSIDE_INDICATOR, and moa.test.DiffUtils.SIDEBYSIDE_SECOND.
{
      StringBuilder result;
      int       i;
      result = new StringBuilder();
      for (i = 0; i < m_Diff[SIDEBYSIDE_FIRST].size(); i++) {
    result.append(m_Diff[SIDEBYSIDE_INDICATOR].get(i));
    result.append(separator);
    result.append(m_Diff[SIDEBYSIDE_FIRST].get(i));
    result.append(separator);
    result.append(m_Diff[SIDEBYSIDE_SECOND].get(i));
    result.append("\n");
      }
      return result.toString();
    }
Member Data Documentation
List [] moa.test.DiffUtils.SideBySideDiff.m_Diff [protected]
the diff information.
Definition at line 106 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.clone(), moa.test.DiffUtils.SideBySideDiff.deltaToLine(), moa.test.DiffUtils.SideBySideDiff.differences(), moa.test.DiffUtils.SideBySideDiff.getIndicator(), moa.test.DiffUtils.SideBySideDiff.getLeft(), moa.test.DiffUtils.SideBySideDiff.getNextDelta(), moa.test.DiffUtils.SideBySideDiff.getRight(), moa.test.DiffUtils.SideBySideDiff.getStartPos(), moa.test.DiffUtils.SideBySideDiff.hasDifferences(), moa.test.DiffUtils.SideBySideDiff.lineToDelta(), moa.test.DiffUtils.SideBySideDiff.SideBySideDiff(), and moa.test.DiffUtils.SideBySideDiff.toString().
final long moa.test.DiffUtils.SideBySideDiff.serialVersionUID = -6775907286936991130L [static, private]
for serialization.
Definition at line 103 of file DiffUtils.java.
The documentation for this class was generated from the following file:
test/java/moa/test/DiffUtils.java