MOA: moa.classifiers.rules.RuleClassification Class Reference
moa.classifiers.rules.RuleClassification Class Reference
Public Member Functions
RuleClassification (RuleClassification x)
RuleClassification ()
boolean ruleEvaluate (Instance inst)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
ArrayList< Predicates > predicateSet = new ArrayList<Predicates>()
AutoExpandVector
< AttributeClassObserver > observers = new AutoExpandVector<AttributeClassObserver>()
AutoExpandVector
< AttributeClassObserver > observersGauss = new AutoExpandVector<AttributeClassObserver>()
ArrayList< ArrayList< Double > > attributeStatisticsSupervised = new ArrayList<ArrayList<Double>>()
ArrayList< ArrayList< Double > > squaredAttributeStatisticsSupervised = new ArrayList<ArrayList<Double>>()
double[] weightAttribute
DoubleVector attributeStatistics = new DoubleVector()
DoubleVector attributesProbability = new DoubleVector()
DoubleVector squaredAttributeStatistics = new DoubleVector()
DoubleVector obserClassDistrib = new DoubleVector()
DoubleVector attributeMissingValues = new DoubleVector()
int instancesSeen = 0
int instancesSeenTest = 0
boolean reset = true
double actualClassStatistics = 0.0
double squaredActualClassStatistics = 0.0
double PHmT = 0
double PHMT = Double.MAX_VALUE
double XiSum = 0
double ValorTargetRule = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 44 of file RuleClassification.java.
Constructor & Destructor Documentation
moa.classifiers.rules.RuleClassification.RuleClassification (RuleClassification x)
Definition at line 90 of file RuleClassification.java.
References moa.classifiers.rules.RuleClassification.predicateSet.
{
        for (int i = 0; i < x.predicateSet.size(); i++) {
            Predicates pred = new Predicates(x.predicateSet.get(i).getAttributeValue(), x.predicateSet.get(i).getSymbol(), x.predicateSet.get(i).getValue());
            this.predicateSet.add(pred);
        }
    }
moa.classifiers.rules.RuleClassification.RuleClassification ()
Definition at line 98 of file RuleClassification.java.
{
    }
Member Function Documentation
void moa.classifiers.rules.RuleClassification.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 119 of file RuleClassification.java.
{
        // TODO Auto-generated method stub
    }
boolean moa.classifiers.rules.RuleClassification.ruleEvaluate (Instance inst)
Definition at line 102 of file RuleClassification.java.
References moa.classifiers.rules.RuleClassification.predicateSet.
{
        int countTrue = 0;
        boolean ruleEvalu = false;
        for (int i = 0; i < predicateSet.size(); i++) {
            if (predicateSet.get(i).evaluate(inst) == true) {
                countTrue = countTrue + 1;
            }
        }
        if (countTrue == predicateSet.size()) {
            ruleEvalu = true;
        } else {
            ruleEvalu = false;
            }
        return ruleEvalu;
        }
Member Data Documentation
double moa.classifiers.rules.RuleClassification.actualClassStatistics = 0.0 [protected]
Definition at line 77 of file RuleClassification.java.
DoubleVector moa.classifiers.rules.RuleClassification.attributeMissingValues = new DoubleVector() [protected]
Definition at line 68 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
DoubleVector moa.classifiers.rules.RuleClassification.attributesProbability = new DoubleVector() [protected]
Definition at line 62 of file RuleClassification.java.
DoubleVector moa.classifiers.rules.RuleClassification.attributeStatistics = new DoubleVector() [protected]
Definition at line 60 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
ArrayList<ArrayList<Double> > moa.classifiers.rules.RuleClassification.attributeStatisticsSupervised = new ArrayList<ArrayList<Double>>() [protected]
Definition at line 54 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
int moa.classifiers.rules.RuleClassification.instancesSeen = 0 [protected]
Definition at line 70 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
int moa.classifiers.rules.RuleClassification.instancesSeenTest = 0 [protected]
Definition at line 72 of file RuleClassification.java.
DoubleVector moa.classifiers.rules.RuleClassification.obserClassDistrib = new DoubleVector() [protected]
Definition at line 66 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), and moa.classifiers.rules.RuleClassifier.initializeRuleStatistics().
AutoExpandVector<AttributeClassObserver> moa.classifiers.rules.RuleClassification.observers = new AutoExpandVector<AttributeClassObserver>() [protected]
Definition at line 50 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.expandeRule(), and moa.classifiers.rules.RuleClassifier.initializeRuleStatistics().
AutoExpandVector<AttributeClassObserver> moa.classifiers.rules.RuleClassification.observersGauss = new AutoExpandVector<AttributeClassObserver>() [protected]
Definition at line 52 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.initializeRuleStatistics().
double moa.classifiers.rules.RuleClassification.PHMT = Double.MAX_VALUE [protected]
Definition at line 83 of file RuleClassification.java.
double moa.classifiers.rules.RuleClassification.PHmT = 0 [protected]
Definition at line 81 of file RuleClassification.java.
ArrayList<Predicates> moa.classifiers.rules.RuleClassification.predicateSet = new ArrayList<Predicates>() [protected]
Definition at line 48 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), moa.classifiers.rules.RuleClassification.RuleClassification(), and moa.classifiers.rules.RuleClassification.ruleEvaluate().
boolean moa.classifiers.rules.RuleClassification.reset = true [protected]
Definition at line 74 of file RuleClassification.java.
final long moa.classifiers.rules.RuleClassification.serialVersionUID = 1L [static, private]
Definition at line 46 of file RuleClassification.java.
double moa.classifiers.rules.RuleClassification.squaredActualClassStatistics = 0.0 [protected]
Definition at line 79 of file RuleClassification.java.
DoubleVector moa.classifiers.rules.RuleClassification.squaredAttributeStatistics = new DoubleVector() [protected]
Definition at line 64 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
ArrayList<ArrayList<Double> > moa.classifiers.rules.RuleClassification.squaredAttributeStatisticsSupervised = new ArrayList<ArrayList<Double>>() [protected]
Definition at line 56 of file RuleClassification.java.
Referenced by moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.initializeRuleStatistics(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
double moa.classifiers.rules.RuleClassification.ValorTargetRule = 0 [protected]
Definition at line 87 of file RuleClassification.java.
double [] moa.classifiers.rules.RuleClassification.weightAttribute [protected]
Definition at line 58 of file RuleClassification.java.
double moa.classifiers.rules.RuleClassification.XiSum = 0 [protected]
Definition at line 85 of file RuleClassification.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/RuleClassification.java