MOA: moa.clusterers.clustree.Node Class Reference
moa.clusterers.clustree.Node Class Reference
Public Member Functions
Node (int numberDimensions, int level)
Initialze a normal node, which is not fake.
Node (int numberDimensions, int level, Entry[] argEntries)
USED FOR EM_TOP_DOWN BULK LOADING.
Entry nearestEntry (ClusKernel buffer)
Returns the neareast Entry to the given Cluster.
void addEntry (Entry newEntry, long currentTime)
Add a new Entry to this node.
Entry[] getEntries ()
Return an array with references to the children of this node.
Protected Member Functions
Node (int numberDimensions, int numberClasses, int level, boolean fakeRoot)
Initialiazes a node which is a fake root depending on the given boolean.
boolean isLeaf ()
Checks if this node is a leaf.
Entry nearestEntry (Entry newEntry)
Return the nearest entry to the given one.
int numFreeEntries ()
Return the number of free Entrys in this node.
Entry getIrrelevantEntry (double threshold)
If there exists an entry, whose relevance is under the threshold given as a parameter to the tree, this entry is returned.
int getRawLevel ()
Return the level number in the node.
int getLevel (ClusTree tree)
Returns the level at which this node is in the tree.
void clear ()
Clear this Node, which means that the noiseBuffer is cleared, that shallowClear is called upon all the entries of the node, that the split counter is set to zero and the node is set to not be a fake root.
void mergeEntries (int pos1, int pos2)
Merge the two entries at the given position.
void makeOlder (long currentTime, double negLambda)
Package Attributes
final int NUMBER_ENTRIES = 3
Static Package Attributes
static int INSERTIONS_BETWEEN_CLEANUPS = 10000
Private Member Functions
int getNextEmptyPosition ()
Returns the position of the next free Entry.
Private Attributes
Entry[] entries
The children of this node.
int level
The depth at which this Node is in the tree.
Detailed Description
Definition at line 23 of file Node.java.
Constructor & Destructor Documentation
moa.clusterers.clustree.Node.Node (int numberDimensions, int level)
Initialze a normal node, which is not fake.
Parameters:
numberDimensions The dimensionality of the data points it manipulates.
level The INVERSE level at which this node hangs.
Definition at line 44 of file Node.java.
References moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Node.NUMBER_ENTRIES, and moa.clusterers.clustree.Entry.setNode().
{
        this.level = level;
        this.entries = new Entry[NUMBER_ENTRIES];
        // Generate all entries when we generate a Node.
        // That no entry can be null makes it much easier to handle.
        for (int i = 0; i < NUMBER_ENTRIES; i++) {
            entries[i] = new Entry(numberDimensions);
            entries[i].setNode(this);
        }
    }
moa.clusterers.clustree.Node.Node (int numberDimensions, int numberClasses, int level, boolean fakeRoot) [protected]
Initialiazes a node which is a fake root depending on the given boolean.
Parameters:
numberDimensions The dimensionality of the data points it manipulates.
level The level at which this node hangs.
fakeRoot A parameter the says if the node is to be fake or not.
Definition at line 64 of file Node.java.
References moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Node.NUMBER_ENTRIES.
{
        this.level = level;
        this.entries = new Entry[NUMBER_ENTRIES];
        // Generate all entries when we generate a Node.
        // That no entry can be null makes it much easier to handle.
        for (int i = 0; i < NUMBER_ENTRIES; i++) {
            entries[i] = new Entry(numberDimensions);
        }
    }
moa.clusterers.clustree.Node.Node (int numberDimensions, int level, Entry[] argEntries)
USED FOR EM_TOP_DOWN BULK LOADING.
Parameters:
numberDimensions
level
argEntries
Definition at line 83 of file Node.java.
References moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Node.NUMBER_ENTRIES.
{
        this.level = level;
        this.entries = new Entry[NUMBER_ENTRIES];
        // Generate all entries when we generate a Node.
        // That no entry can be null makes it much easier to handle.
        for (int i = 0; i < NUMBER_ENTRIES; i++) {
            entries[i] = argEntries[i];
        }
    }
Member Function Documentation
void moa.clusterers.clustree.Node.addEntry (Entry newEntry, long currentTime)
Add a new Entry to this node.
If there is no space left a NoFreeEntryException is thrown.
Parameters:
newEntry The Entry to be added.
Exceptions:
NoFreeEntryException Is thrown when there is no space left in the node for the new entry.
Definition at line 202 of file Node.java.
References moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Node.getNextEmptyPosition(), moa.clusterers.clustree.Entry.initializeEntry(), and moa.clusterers.clustree.Entry.setNode().
Referenced by moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.buildTreeRecursively(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit(), and moa.clusterers.clustree.ClusTree.split().
{
        newEntry.setNode(this);
        int freePosition = getNextEmptyPosition();
        entries[freePosition].initializeEntry(newEntry, currentTime);
    }
void moa.clusterers.clustree.Node.clear () [protected]
Clear this Node, which means that the noiseBuffer is cleared, that shallowClear is called upon all the entries of the node, that the split counter is set to zero and the node is set to not be a fake root.
Notice that the level stays the same after calling this function.
See also:
Kernel.clear()
Entry.shallowClear()
Definition at line 292 of file Node.java.
References moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Node.NUMBER_ENTRIES, and moa.clusterers.clustree.Entry.shallowClear().
{
        for (int i = 0; i < NUMBER_ENTRIES; i++) {
            entries[i].shallowClear();
        }
    }
Entry [] moa.clusterers.clustree.Node.getEntries ()
Return an array with references to the children of this node.
These are not copies, that means side effects are possible!
Returns:
An array with references to the children of this node.
See also:
Entry
Definition at line 256 of file Node.java.
References moa.clusterers.clustree.Node.entries.
Referenced by moa.clusterers.clustree.ClusTree.calculateBestMergeInNode(), moa.clusterers.clustree.ClusTree.cleanUp(), moa.clusterers.clustree.ClusTree.collectLeafNodes(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.Entry.overwriteOldEntry(), moa.clusterers.clustree.Entry.recalculateData(), moa.clusterers.clustree.ClusTree.split(), and moa.clusterers.clustree.ClusTree.updateToTop().
{
        return entries;
    }
Entry moa.clusterers.clustree.Node.getIrrelevantEntry (double threshold) [protected]
If there exists an entry, whose relevance is under the threshold given as a parameter to the tree, this entry is returned.
Otherwise null is returned.
Returns:
An irrelevant Entry if there exists one, null otherwise.
See also:
Entry
Entry.isIrrelevant(double)
Definition at line 239 of file Node.java.
References moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Entry.isIrrelevant().
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.insertHereWithSplit().
{
        for (int i = 0; i < this.entries.length; i++) {
            Entry entry = this.entries[i];
            if (entry.isIrrelevant(threshold)) {
                return entry;
            }
        }
        return null;
    }
int moa.clusterers.clustree.Node.getLevel (ClusTree tree) [protected]
Returns the level at which this node is in the tree.
If a tree is passed to which the node does not belonged a value is returned, but it is gibberish.
Parameters:
tree The tree to which this node belongs.
Returns:
The level at which this node hangs.
Definition at line 277 of file Node.java.
References moa.clusterers.clustree.ClusTree.getNumRootSplits(), and moa.clusterers.clustree.Node.getRawLevel().
Referenced by moa.clusterers.clustree.ClusTree.getClustering().
{
        int numRootSplits = tree.getNumRootSplits();
        return numRootSplits - this.getRawLevel();
    }
int moa.clusterers.clustree.Node.getNextEmptyPosition () [private]
Returns the position of the next free Entry.
Returns:
The position of the next free Entry.
Exceptions:
NoFreeEntryException Is thrown when there is no free entry left in the node.
Definition at line 214 of file Node.java.
References moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Entry.isEmpty().
Referenced by moa.clusterers.clustree.Node.addEntry().
{
        int counter;
        for (counter = 0; counter < entries.length; counter++) {
            Entry e = entries[counter];
            if (e.isEmpty()) {
                break;
            }
        }
        if (counter == entries.length) {
            throw new RuntimeException("Entry added to a node which is already full.");
        }
        return counter;
    }
int moa.clusterers.clustree.Node.getRawLevel () [protected]
Return the level number in the node.
This is not the real level. For the real level one has to call getLevel(Tree tree).
Returns:
The raw level of the node.
See also:
getLevel(moa.clusterers.LiarTree.Tree)
Definition at line 266 of file Node.java.
References moa.clusterers.clustree.Node.level.
Referenced by moa.clusterers.clustree.Node.getLevel(), moa.clusterers.clustree.ClusTree.insert(), and moa.clusterers.clustree.ClusTree.split().
{
        return level;
    }
boolean moa.clusterers.clustree.Node.isLeaf () [protected]
Checks if this node is a leaf.
A node is a leaf when none of the entries in the node have children.
Returns:
true if the node is leaf, false otherwise.
Definition at line 101 of file Node.java.
References moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Entry.getChild().
Referenced by moa.clusterers.clustree.ClusTree.collectLeafNodes(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.clustree.ClusTree.insert(), and moa.clusterers.clustree.ClusTree.insertHere().
{
        for (int i = 0; i < entries.length; i++) {
            Entry entry = entries[i];
            if (entry.getChild() != null) {
                return false;
            }
        }
        return true;
    }
void moa.clusterers.clustree.Node.makeOlder (long currentTime, double negLambda) [protected]
Definition at line 319 of file Node.java.
References moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Entry.isEmpty(), and moa.clusterers.clustree.Entry.makeOlder().
Referenced by moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), and moa.clusterers.clustree.ClusTree.insertHereWithSplit().
{
        for (int i = 0; i < this.entries.length; i++) {
            Entry entry = this.entries[i];
            if (entry.isEmpty()) {
                break;
            }
            entry.makeOlder(currentTime, negLambda);
        }
    }
void moa.clusterers.clustree.Node.mergeEntries (int pos1, int pos2) [protected]
Merge the two entries at the given position.
The entries are reordered in the entries array so that the non-empty entries are still at the beginning.
Parameters:
pos1 The position of the first entry to be merged. This position has to be smaller than the the second position.
pos2 The position of the second entry to be merged. This position has to be greater than the the first position.
Definition at line 307 of file Node.java.
References moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Entry.mergeWith(), and moa.clusterers.clustree.Node.numFreeEntries().
Referenced by moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit().
{
        assert (this.numFreeEntries() == 0);
        assert (pos1 < pos2);
        this.entries[pos1].mergeWith(this.entries[pos2]);
        for (int i = pos2; i < entries.length - 1; i++) {
            entries[i] = entries[i + 1];
        }
        entries[entries.length - 1].clear();
    }
Entry moa.clusterers.clustree.Node.nearestEntry (Entry newEntry) [protected]
Return the nearest entry to the given one.
The calcDistance(Entry) function is find the one with the shortest distance in this node to the given one.
Parameters:
newEntry The entry to which the entry with the minimal distance to it is calculated.
Returns:
The entry with the minimal distance to the given one.
Definition at line 155 of file Node.java.
References moa.clusterers.clustree.Entry.calcDistance(), and moa.clusterers.clustree.Node.entries.
{
        assert (!this.entries[0].isEmpty());
        Entry res = entries[0];
        double min = res.calcDistance(newEntry);
        for (int i = 1; i < entries.length; i++) {
            if (this.entries[i].isEmpty()) {
                break;
            }
            Entry entry = entries[i];
            double distance = entry.calcDistance(newEntry);
            if (distance < min) {
                min = distance;
                res = entry;
            }
        }
        return res;
    }
Entry moa.clusterers.clustree.Node.nearestEntry (ClusKernel buffer)
Returns the neareast Entry to the given Cluster.
The distance is minimized over Entry.calcDistance(Cluster).
Parameters:
buffer The cluster to which the distance has to be compared.
Returns:
The Entry with minimal distance to the given cluster.
Exceptions:
EmptyNodeException This Exception is thrown when this function is called on an empty node.
See also:
Kernel
Entry.calcDistance(moa.clusterers.tree.Kernel)
Definition at line 124 of file Node.java.
References moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.Node.entries, and moa.clusterers.clustree.Entry.isEmpty().
Referenced by moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHere(), and moa.clusterers.clustree.ClusTree.mergeEntryWithoutSplit().
{
        // TODO: (Fernando) Adapt the nearestEntry(...) function to the new algorithmn.
        Entry res = entries[0];
        double min = res.calcDistance(buffer);
        for (int i = 1; i < entries.length; i++) {
            Entry entry = entries[i];
            if (entry.isEmpty()) {
                break;
            }
            double distance = entry.calcDistance(buffer);
            if (distance < min) {
                min = distance;
                res = entry;
            }
        }
        return res;
    }
int moa.clusterers.clustree.Node.numFreeEntries () [protected]
Return the number of free Entrys in this node.
Returns:
The number of free Entrys in this node.
See also:
Entry
Definition at line 182 of file Node.java.
References moa.clusterers.clustree.Node.entries, moa.clusterers.clustree.Entry.isEmpty(), and moa.clusterers.clustree.Node.NUMBER_ENTRIES.
Referenced by moa.clusterers.clustree.ClusTree.calculateBestMergeInNode(), moa.clusterers.clustree.ClusTree.existsOutdatedEntryOnPath(), moa.clusterers.clustree.ClusTree.insertBreadthFirst(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.ClusTree.insertHereWithSplit(), moa.clusterers.clustree.Node.mergeEntries(), and moa.clusterers.clustree.ClusTree.split().
{
        int res = 0;
        for (int i = 0; i < entries.length; i++) {
            Entry entry = entries[i];
            if (entry.isEmpty()) {
                res++;
            }
        }
        assert (NUMBER_ENTRIES == entries.length);
        return res;
    }
Member Data Documentation
Entry [] moa.clusterers.clustree.Node.entries [private]
The children of this node.
Definition at line 31 of file Node.java.
Referenced by moa.clusterers.clustree.Node.addEntry(), moa.clusterers.clustree.Node.clear(), moa.clusterers.clustree.Node.getEntries(), moa.clusterers.clustree.Node.getIrrelevantEntry(), moa.clusterers.clustree.Node.getNextEmptyPosition(), moa.clusterers.clustree.Node.isLeaf(), moa.clusterers.clustree.Node.makeOlder(), moa.clusterers.clustree.Node.mergeEntries(), moa.clusterers.clustree.Node.nearestEntry(), moa.clusterers.clustree.Node.Node(), and moa.clusterers.clustree.Node.numFreeEntries().
int moa.clusterers.clustree.Node.INSERTIONS_BETWEEN_CLEANUPS = 10000 [static, package]
Definition at line 26 of file Node.java.
int moa.clusterers.clustree.Node.level [private]
The depth at which this Node is in the tree.
Definition at line 36 of file Node.java.
Referenced by moa.clusterers.clustree.Node.getRawLevel().
final int moa.clusterers.clustree.Node.NUMBER_ENTRIES = 3 [package]
Definition at line 25 of file Node.java.
Referenced by moa.clusterers.clustree.Node.clear(), moa.clusterers.clustree.Node.Node(), and moa.clusterers.clustree.Node.numFreeEntries().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustree/Node.java