MOA: moa.gui.TaskLauncher Class Reference
moa.gui.TaskLauncher Class Reference
The old main class for the MOA gui, now the main class is GUI.
Public Member Functions
TaskLauncher ()
Static Public Member Functions
static void main (String[] args)
Protected Attributes
TaskManagerPanel taskManagerPanel
PreviewPanel previewPanel
Static Private Member Functions
static void createAndShowGUI ()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The old main class for the MOA gui, now the main class is GUI.
Lets the user configure tasks, learners, streams, and perform data stream analysis.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 35 of file TaskLauncher.java.
Constructor & Destructor Documentation
moa.gui.TaskLauncher.TaskLauncher ()
Definition at line 43 of file TaskLauncher.java.
References moa.gui.TaskLauncher.previewPanel, moa.gui.TaskManagerPanel.setPreviewPanel(), and moa.gui.TaskLauncher.taskManagerPanel.
Referenced by moa.gui.TaskLauncher.createAndShowGUI().
{
        this.taskManagerPanel = new TaskManagerPanel();
        this.previewPanel = new PreviewPanel();
        this.taskManagerPanel.setPreviewPanel(this.previewPanel);
        setLayout(new BorderLayout());
        add(this.taskManagerPanel, BorderLayout.NORTH);
        add(this.previewPanel, BorderLayout.CENTER);
    }
Member Function Documentation
static void moa.gui.TaskLauncher.createAndShowGUI () [static, private]
Definition at line 52 of file TaskLauncher.java.
References moa.gui.TaskLauncher.TaskLauncher().
Referenced by moa.gui.TaskLauncher.main().
{
        // Create and set up the window.
        JFrame frame = new JFrame("MOA Task Launcher");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create and set up the content pane.
        JPanel panel = new TaskLauncher();
        panel.setOpaque(true); // content panes must be opaque
        frame.setContentPane(panel);
        // Display the window.
        frame.pack();
        frame.setSize(640, 480);
        frame.setVisible(true);
    }
static void moa.gui.TaskLauncher.main (String[] args) [static]
Definition at line 69 of file TaskLauncher.java.
References moa.gui.TaskLauncher.createAndShowGUI().
{
        try {
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    createAndShowGUI();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
Member Data Documentation
PreviewPanel moa.gui.TaskLauncher.previewPanel [protected]
Definition at line 41 of file TaskLauncher.java.
Referenced by moa.gui.TaskLauncher.TaskLauncher().
final long moa.gui.TaskLauncher.serialVersionUID = 1L [static, private]
Definition at line 37 of file TaskLauncher.java.
TaskManagerPanel moa.gui.TaskLauncher.taskManagerPanel [protected]
Definition at line 39 of file TaskLauncher.java.
Referenced by moa.gui.TaskLauncher.TaskLauncher().
The documentation for this class was generated from the following file:
main/java/moa/gui/TaskLauncher.java