MOA: moa.evaluation.MeasureCollection Class Reference
moa.evaluation.MeasureCollection Class Reference
Public Member Functions
MeasureCollection ()
void addValue (int index, double value)
void addEmptyValue (int index)
int getNumMeasures ()
String getName (int index)
double getMaxValue (int index)
double getMinValue (int index)
double getLastValue (int index)
double getMean (int index)
void clean (int index)
double getMedian (int index)
double getLowerQuartile (int index)
double getUpperQuartile (int index)
int getNumberOfValues (int index)
double getValue (int index, int i)
ArrayList< Double > getAllValues (int index)
void setEnabled (int index, boolean value)
boolean isEnabled (int index)
double getMeanRunningTime ()
double evaluateClusteringPerformance (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void addEventType (String type)
String getEventType (int index)
Protected Member Functions
abstract String[] getNames ()
void addValue (String name, double value)
boolean[] getDefaultEnabled ()
abstract void evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception
Private Member Functions
void updateSortedValues (int index)
Private Attributes
String[] names
ArrayList< Double >[] values
ArrayList< Double >[] sortedValues
ArrayList< String > events
double[] minValue
double[] maxValue
double[] sumValues
boolean[] enabled
boolean[] corrupted
double time
boolean debug = true
MembershipMatrix mm = null
HashMap< String, Integer > map
int numMeasures = 0
Detailed Description
Definition at line 29 of file MeasureCollection.java.
Constructor & Destructor Documentation
moa.evaluation.MeasureCollection.MeasureCollection ()
Definition at line 51 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.corrupted, moa.evaluation.MeasureCollection.enabled, moa.evaluation.MeasureCollection.events, moa.evaluation.MeasureCollection.getDefaultEnabled(), moa.evaluation.MeasureCollection.getNames(), moa.evaluation.MeasureCollection.map, moa.evaluation.MeasureCollection.maxValue, moa.evaluation.MeasureCollection.minValue, moa.evaluation.MeasureCollection.names, moa.evaluation.MeasureCollection.numMeasures, moa.evaluation.MeasureCollection.sortedValues, moa.evaluation.MeasureCollection.sumValues, moa.evaluation.MeasureCollection.time, and moa.evaluation.MeasureCollection.values.
{
        names = getNames();
        numMeasures = names.length;
        map = new HashMap<String, Integer>(numMeasures);
        for (int i = 0; i < names.length; i++) {
             map.put(names[i],i);
        }
        values = (ArrayList<Double>[]) new ArrayList[numMeasures];
        sortedValues = (ArrayList<Double>[]) new ArrayList[numMeasures];
        maxValue = new double[numMeasures];
        minValue = new double[numMeasures];
        sumValues = new double[numMeasures];
        corrupted = new boolean[numMeasures];
        enabled = getDefaultEnabled();
        time = 0;
        events = new ArrayList<String>();
        for (int i = 0; i < numMeasures; i++) {
                values[i] = new ArrayList<Double>();
                sortedValues[i] = new ArrayList<Double>();
                maxValue[i] = Double.MIN_VALUE;
                minValue[i] = Double.MAX_VALUE;
                corrupted[i] = false;
                sumValues[i] = 0.0;
        }
    }
Member Function Documentation
void moa.evaluation.MeasureCollection.addEmptyValue (int index)
Definition at line 108 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.corrupted, and moa.evaluation.MeasureCollection.values.
Referenced by moa.gui.visualization.RunVisualizer.evaluateClustering().
{
         values[index].add(Double.NaN);
         corrupted[index] = true;
     }
void moa.evaluation.MeasureCollection.addEventType (String type)
Definition at line 248 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.events.
{
         events.add(type);
     }
void moa.evaluation.MeasureCollection.addValue (String name, double value) [protected]
Definition at line 98 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.addValue(), and moa.evaluation.MeasureCollection.map.
{
        if(map.containsKey(name)){
            addValue(map.get(name),value);
        }
        else{
            System.out.println(name+" is not a valid measure key, no value added");
        }
     }
void moa.evaluation.MeasureCollection.addValue (int index, double value)
Definition at line 81 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.corrupted, moa.evaluation.MeasureCollection.debug, moa.evaluation.MeasureCollection.maxValue, moa.evaluation.MeasureCollection.minValue, moa.evaluation.MeasureCollection.names, moa.evaluation.MeasureCollection.sumValues, and moa.evaluation.MeasureCollection.values.
Referenced by moa.evaluation.OutlierPerformance.addTimePerObject(), moa.evaluation.MeasureCollection.addValue(), moa.evaluation.CMM.calculateError(), moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.SSQ.evaluateClustering(), moa.evaluation.SilhouetteCoefficient.evaluateClustering(), moa.evaluation.General.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), moa.evaluation.EntropyCollection.evaluateClustering(), moa.evaluation.CMM.evaluateClustering(), and moa.gui.TaskTextViewerPanel.setGraph().
{
         if(Double.isNaN(value)){
             if(debug)
                 System.out.println("NaN for "+names[index]);
             corrupted[index] = true;
         }
         if(value < 0){
             if(debug)
                 System.out.println("Negative value for "+names[index]);
         }
         values[index].add(value);
         sumValues[index]+=value;
         if(value < minValue[index]) minValue[index] = value;
         if(value > maxValue[index]) maxValue[index] = value;
     }
void moa.evaluation.MeasureCollection.clean (int index)
Definition at line 156 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.sortedValues.
{
         sortedValues[index].clear();
     }
abstract void moa.evaluation.MeasureCollection.evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception [protected, pure virtual]
Implemented in moa.evaluation.Accuracy, moa.evaluation.ChangeDetectionMeasures, moa.evaluation.CMM, moa.evaluation.EntropyCollection, moa.evaluation.F1, moa.evaluation.General, moa.evaluation.OutlierPerformance, moa.evaluation.SilhouetteCoefficient, moa.evaluation.SSQ, and moa.evaluation.StatisticalCollection.
Referenced by moa.evaluation.MeasureCollection.evaluateClusteringPerformance().
double moa.evaluation.MeasureCollection.evaluateClusteringPerformance (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception
Definition at line 235 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.evaluateClustering(), and moa.evaluation.MeasureCollection.time.
Referenced by moa.gui.visualization.RunVisualizer.evaluateClustering(), and moa.gui.BatchCmd.run().
{
        long start = System.nanoTime();
        evaluateClustering(clustering, trueClustering, points);
        long duration = System.nanoTime()-start;
        time+=duration;
        duration/=10e5;
        return duration;
     }
ArrayList<Double> moa.evaluation.MeasureCollection.getAllValues (int index)
Definition at line 201 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.values.
{
         return values[index];
     }
boolean [] moa.evaluation.MeasureCollection.getDefaultEnabled () [protected]
Reimplemented in moa.evaluation.Accuracy, moa.evaluation.ChangeDetectionMeasures, moa.evaluation.CMM, moa.evaluation.EntropyCollection, moa.evaluation.OutlierPerformance, moa.evaluation.RegressionAccuracy, moa.evaluation.SilhouetteCoefficient, moa.evaluation.SSQ, and moa.evaluation.StatisticalCollection.
Definition at line 220 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.numMeasures.
Referenced by moa.evaluation.MeasureCollection.MeasureCollection().
{
         boolean[] defaults = new boolean[numMeasures];
         for (int i = 0; i < defaults.length; i++) {
             defaults[i] = true;
         }
         return defaults;
     }
void moa.evaluation.MeasureCollection.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 244 of file MeasureCollection.java.
{
    }
String moa.evaluation.MeasureCollection.getEventType (int index)
Definition at line 251 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.events.
{
         if(index < events.size())
             return events.get(index);
         else
             return null;
     }
double moa.evaluation.MeasureCollection.getLastValue (int index)
Definition at line 129 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.values.
{
         if(values[index].size()<1) return Double.NaN;
         return values[index].get(values[index].size()-1);
     }
double moa.evaluation.MeasureCollection.getLowerQuartile (int index)
Definition at line 173 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.sortedValues, and moa.evaluation.MeasureCollection.updateSortedValues().
{
         updateSortedValues(index);
         int size = sortedValues[index].size();
         if(size > 11){
             return sortedValues[index].get(Math.round(size*0.25f));
         }
         return Double.NaN;
     }
double moa.evaluation.MeasureCollection.getMaxValue (int index)
Definition at line 121 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.maxValue.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues().
{
         return maxValue[index];
     }
double moa.evaluation.MeasureCollection.getMean (int index)
Definition at line 134 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.corrupted, moa.evaluation.MeasureCollection.sumValues, and moa.evaluation.MeasureCollection.values.
{
         if(corrupted[index] || values[index].size()<1)
             return Double.NaN;
         return sumValues[index]/values[index].size();
     }
double moa.evaluation.MeasureCollection.getMeanRunningTime ()
Definition at line 213 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.time, and moa.evaluation.MeasureCollection.values.
{
         if(values[0].size()!=0)
            return (time/10e5/values[0].size());
         else
             return 0;
     }
double moa.evaluation.MeasureCollection.getMedian (int index)
Definition at line 160 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.sortedValues, and moa.evaluation.MeasureCollection.updateSortedValues().
{
         updateSortedValues(index);
         int size = sortedValues[index].size();
         if(size > 0){
             if(size%2 == 1)
                 return sortedValues[index].get((int)(size/2));
             else
                 return (sortedValues[index].get((size-1)/2)+sortedValues[index].get((size-1)/2+1))/2.0;
         }
         return Double.NaN;
    }
double moa.evaluation.MeasureCollection.getMinValue (int index)
Definition at line 125 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.minValue.
Referenced by moa.gui.visualization.GraphCanvas.updateMinMaxValues().
{
         return minValue[index];
     }
String moa.evaluation.MeasureCollection.getName (int index)
Definition at line 117 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.names.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), and moa.gui.clustertab.ClusteringEvalPanel.addComponents().
{
        return names[index];
     }
abstract String [] moa.evaluation.MeasureCollection.getNames () [protected, pure virtual]
Implemented in moa.evaluation.Accuracy, moa.evaluation.ChangeDetectionMeasures, moa.evaluation.CMM, moa.evaluation.EntropyCollection, moa.evaluation.F1, moa.evaluation.General, moa.evaluation.OutlierPerformance, moa.evaluation.RegressionAccuracy, moa.evaluation.SilhouetteCoefficient, moa.evaluation.SSQ, and moa.evaluation.StatisticalCollection.
Referenced by moa.evaluation.MeasureCollection.MeasureCollection().
int moa.evaluation.MeasureCollection.getNumberOfValues (int index)
Definition at line 192 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.values.
Referenced by moa.gui.visualization.RunVisualizer.exportCSV(), moa.gui.BatchCmd.exportCSV(), moa.gui.visualization.GraphCurve.paintFullCurve(), and moa.gui.visualization.GraphCanvas.updateMinMaxValues().
{
         return values[index].size();
     }
int moa.evaluation.MeasureCollection.getNumMeasures ()
Definition at line 113 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.numMeasures.
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.TaskTextViewerPanel.actionPerformed(), moa.gui.outliertab.OutlierEvalPanel.addComponents(), moa.gui.clustertab.ClusteringEvalPanel.addComponents(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.RunVisualizer.exportCSV(), moa.gui.BatchCmd.exportCSV(), moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures(), moa.gui.outliertab.OutlierVisualEvalPanel.setMeasures(), and moa.gui.clustertab.ClusteringVisualEvalPanel.setMeasures().
{
         return numMeasures;
     }
double moa.evaluation.MeasureCollection.getUpperQuartile (int index)
Definition at line 182 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.sortedValues, and moa.evaluation.MeasureCollection.updateSortedValues().
{
         updateSortedValues(index);
         int size = sortedValues[index].size();
         if(size > 11){
             return sortedValues[index].get(Math.round(size*0.75f-1));
         }
         return Double.NaN;
     }
double moa.evaluation.MeasureCollection.getValue (int index, int i)
Definition at line 196 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.values.
Referenced by moa.gui.visualization.RunVisualizer.exportCSV(), moa.gui.visualization.GraphCurve.paintFullCurve(), and moa.gui.TaskTextViewerPanel.setGraph().
{
         if(i>=values[index].size()) return Double.NaN;
         return values[index].get(i);
     }
boolean moa.evaluation.MeasureCollection.isEnabled (int index)
Definition at line 209 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.enabled.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), and moa.gui.clustertab.ClusteringEvalPanel.addComponents().
{
         return enabled[index];
     }
void moa.evaluation.MeasureCollection.setEnabled (int index, boolean value)
Definition at line 205 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.enabled.
Referenced by moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures().
{
         enabled[index] = value;
     }
void moa.evaluation.MeasureCollection.updateSortedValues (int index) [private]
Definition at line 141 of file MeasureCollection.java.
References moa.evaluation.MeasureCollection.sortedValues, and moa.evaluation.MeasureCollection.values.
Referenced by moa.evaluation.MeasureCollection.getLowerQuartile(), moa.evaluation.MeasureCollection.getMedian(), and moa.evaluation.MeasureCollection.getUpperQuartile().
{
         //naive implementation of insertion sort
         for (int i = sortedValues[index].size(); i < values[index].size(); i++) {
             double v = values[index].get(i);
             int insertIndex = 0;
             while(!sortedValues[index].isEmpty() && insertIndex < sortedValues[index].size() && v > sortedValues[index].get(insertIndex))
                 insertIndex++;
             sortedValues[index].add(insertIndex,v);
         }
//         for (int i = 0; i < sortedValues[index].size(); i++) {
//             System.out.print(sortedValues[index].get(i)+" ");
//         }
//         System.out.println();
     }
Member Data Documentation
boolean [] moa.evaluation.MeasureCollection.corrupted [private]
Definition at line 39 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addEmptyValue(), moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getMean(), and moa.evaluation.MeasureCollection.MeasureCollection().
boolean moa.evaluation.MeasureCollection.debug = true [private]
Reimplemented in moa.evaluation.Accuracy, moa.evaluation.ChangeDetectionMeasures, moa.evaluation.CMM, moa.evaluation.EntropyCollection, and moa.evaluation.StatisticalCollection.
Definition at line 41 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue().
boolean [] moa.evaluation.MeasureCollection.enabled [private]
Definition at line 38 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.isEnabled(), moa.evaluation.MeasureCollection.MeasureCollection(), and moa.evaluation.MeasureCollection.setEnabled().
ArrayList<String> moa.evaluation.MeasureCollection.events [private]
Definition at line 33 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addEventType(), moa.evaluation.MeasureCollection.getEventType(), and moa.evaluation.MeasureCollection.MeasureCollection().
HashMap<String, Integer> moa.evaluation.MeasureCollection.map [private]
Definition at line 44 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue(), and moa.evaluation.MeasureCollection.MeasureCollection().
double [] moa.evaluation.MeasureCollection.maxValue [private]
Definition at line 36 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getMaxValue(), and moa.evaluation.MeasureCollection.MeasureCollection().
double [] moa.evaluation.MeasureCollection.minValue [private]
Definition at line 35 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getMinValue(), and moa.evaluation.MeasureCollection.MeasureCollection().
MembershipMatrix moa.evaluation.MeasureCollection.mm = null [private]
Definition at line 42 of file MeasureCollection.java.
Referenced by moa.evaluation.StatisticalCollection.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), and moa.evaluation.EntropyCollection.evaluateClustering().
String [] moa.evaluation.MeasureCollection.names [private]
Definition at line 30 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getName(), moa.evaluation.StatisticalCollection.getNames(), moa.evaluation.SSQ.getNames(), moa.evaluation.SilhouetteCoefficient.getNames(), moa.evaluation.RegressionAccuracy.getNames(), moa.evaluation.OutlierPerformance.getNames(), moa.evaluation.General.getNames(), moa.evaluation.F1.getNames(), moa.evaluation.EntropyCollection.getNames(), moa.evaluation.CMM.getNames(), moa.evaluation.ChangeDetectionMeasures.getNames(), moa.evaluation.Accuracy.getNames(), and moa.evaluation.MeasureCollection.MeasureCollection().
int moa.evaluation.MeasureCollection.numMeasures = 0 [private]
Definition at line 46 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.getDefaultEnabled(), moa.evaluation.MeasureCollection.getNumMeasures(), and moa.evaluation.MeasureCollection.MeasureCollection().
ArrayList<Double> [] moa.evaluation.MeasureCollection.sortedValues [private]
Definition at line 32 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.clean(), moa.evaluation.MeasureCollection.getLowerQuartile(), moa.evaluation.MeasureCollection.getMedian(), moa.evaluation.MeasureCollection.getUpperQuartile(), moa.evaluation.MeasureCollection.MeasureCollection(), and moa.evaluation.MeasureCollection.updateSortedValues().
double [] moa.evaluation.MeasureCollection.sumValues [private]
Definition at line 37 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getMean(), and moa.evaluation.MeasureCollection.MeasureCollection().
double moa.evaluation.MeasureCollection.time [private]
Definition at line 40 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.evaluateClusteringPerformance(), moa.evaluation.MeasureCollection.getMeanRunningTime(), and moa.evaluation.MeasureCollection.MeasureCollection().
ArrayList<Double> [] moa.evaluation.MeasureCollection.values [private]
Definition at line 31 of file MeasureCollection.java.
Referenced by moa.evaluation.MeasureCollection.addEmptyValue(), moa.evaluation.MeasureCollection.addValue(), moa.evaluation.MeasureCollection.getAllValues(), moa.evaluation.MeasureCollection.getLastValue(), moa.evaluation.MeasureCollection.getMean(), moa.evaluation.MeasureCollection.getMeanRunningTime(), moa.evaluation.MeasureCollection.getNumberOfValues(), moa.evaluation.MeasureCollection.getValue(), moa.evaluation.MeasureCollection.MeasureCollection(), and moa.evaluation.MeasureCollection.updateSortedValues().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/MeasureCollection.java