MOA: moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg Class Reference
moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg Class Reference
Public Member Functions
StdPrintMsg ()
StdPrintMsg (String sFilename)
void RedirectToDisplay ()
void RedirectToFile (String sFilename)
void RedirectToFile ()
void println (String s)
void print (String s)
void printf (String fmt, Object...args)
Private Attributes
PrintStream printStream
PrintStream fileStream
Detailed Description
Definition at line 327 of file MyBaseOutlierDetector.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.StdPrintMsg ()
Definition at line 330 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToDisplay().
{
            RedirectToDisplay();
        }
moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.StdPrintMsg (String sFilename)
Definition at line 334 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToFile().
{
            RedirectToFile(sFilename);
        }
Member Function Documentation
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.print (String s)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 360 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
{
            printStream.print(s);
        }
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printf (String fmt, Object... args)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 365 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
{
            printStream.printf(fmt, args);
        }
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.println (String s)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 355 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
{
            printStream.println(s);
        }
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToDisplay ()
Definition at line 338 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Init(), and moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.StdPrintMsg().
{
            printStream = System.out;
        }
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToFile ()
Definition at line 350 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.fileStream, and moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.StdPrintMsg().
{
            printStream = fileStream;
        }
void moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToFile (String sFilename)
Definition at line 342 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.fileStream, and moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream.
{
            File file = new File(sFilename);
            try {
                fileStream = new PrintStream(new FileOutputStream(file));
                printStream = fileStream;
            } catch (Exception ex) {}
        }
Member Data Documentation
PrintStream moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.fileStream [private]
Definition at line 328 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToFile().
PrintStream moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printStream [private]
Definition at line 328 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.print(), moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.printf(), moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.println(), moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToDisplay(), and moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToFile().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MyBaseOutlierDetector.java