MOA: moa.cluster.Cluster Class Reference
moa.cluster.Cluster Class Reference
Public Member Functions
Cluster ()
abstract double[] getCenter ()
abstract double getWeight ()
Returns the weight of this cluster, not neccessarily normalized.
abstract double getInclusionProbability (Instance instance)
Returns the probability of the given point belonging to this cluster.
void getDescription (StringBuilder sb, int i)
Returns a string representation of this object.
void setId (double id)
double getId ()
boolean isGroundTruth ()
void setGroundTruth (double truth)
double getGroundTruth ()
abstract Instance sample (Random random)
Samples this cluster by returning a point from inside it.
void setMeasureValue (String measureKey, String value)
void setMeasureValue (String measureKey, double value)
String getMeasureValue (String measureKey)
String getInfo ()
Protected Member Functions
void getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue)
Private Attributes
double id = -1
double gtLabel = -1
HashMap< String, String > measure_values
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 31 of file Cluster.java.
Constructor & Destructor Documentation
moa.cluster.Cluster.Cluster ()
Definition at line 41 of file Cluster.java.
References moa.cluster.Cluster.measure_values.
                    {
        this.measure_values = new HashMap<String, String>();
    }
Member Function Documentation
abstract double [] moa.cluster.Cluster.getCenter () [pure virtual]
Returns:
the center of the cluster
Implemented in moa.cluster.CFCluster, moa.cluster.SphereCluster, moa.clusterers.clustream.ClustreamKernel, moa.clusterers.clustree.ClusKernel, and moa.clusterers.denstream.MicroCluster.
Referenced by moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.evaluation.SSQ.evaluateClustering(), moa.clusterers.KMeans.gaussianMeans(), moa.cluster.Cluster.getClusterSpecificInfo(), moa.clusterers.KMeans.kMeans(), moa.clusterers.clustream.WithKmeans.kMeans(), moa.clusterers.clustream.Clustream.kMeans(), moa.clusterers.clustream.WithKmeans.kMeans_gta(), moa.gui.visualization.RunVisualizer.weka(), and moa.gui.visualization.RunOutlierVisualizer.weka().
void moa.cluster.Cluster.getClusterSpecificInfo (ArrayList< String > infoTitle, ArrayList< String > infoValue) [protected]
Reimplemented in moa.cluster.SphereCluster, and moa.clusterers.clustream.ClustreamKernel.
Definition at line 122 of file Cluster.java.
References moa.cluster.Cluster.getCenter(), moa.cluster.Cluster.getId(), and moa.cluster.Cluster.getWeight().
Referenced by moa.cluster.Cluster.getInfo().
{
        infoTitle.add("ClusterID");
        infoValue.add(Integer.toString((int)getId()));
        infoTitle.add("Type");
        infoValue.add(getClass().getSimpleName());
        double c[] = getCenter();
        if(c!=null)
        for (int i = 0; i < c.length; i++) {
            infoTitle.add("Dim"+i);
            infoValue.add(Double.toString(c[i]));
        }
        infoTitle.add("Weight");
        infoValue.add(Double.toString(getWeight()));
    }
void moa.cluster.Cluster.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 72 of file Cluster.java.
{
        sb.append("Cluster Object");
    }
double moa.cluster.Cluster.getGroundTruth ()
Definition at line 92 of file Cluster.java.
References moa.cluster.Cluster.gtLabel.
Referenced by moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.gui.visualization.OutlierPanel.getClusterLabel(), moa.gui.visualization.ClusterPanel.getClusterLabel(), and moa.evaluation.CMM_GTAnalysis.getModelQuality().
{
        return gtLabel;
    }
double moa.cluster.Cluster.getId ()
Definition at line 80 of file Cluster.java.
References moa.cluster.Cluster.id.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.evaluation.CMM.calculateMatching(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.gui.visualization.OutlierPanel.getClusterID(), moa.gui.visualization.ClusterPanel.getClusterID(), moa.cluster.Cluster.getClusterSpecificInfo(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.gui.visualization.ClusterPanel.paintComponent(), moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
{
        return id;
    }
abstract double moa.cluster.Cluster.getInclusionProbability (Instance instance) [pure virtual]
Returns the probability of the given point belonging to this cluster.
Parameters:
point
Returns:
a value between 0 and 1
Implemented in moa.cluster.CFCluster, moa.cluster.SphereCluster, moa.clusterers.clustream.ClustreamKernel, moa.clusterers.clustree.ClusKernel, moa.clusterers.denstream.MicroCluster, and moa.clusterers.macro.NonConvexCluster.
Referenced by moa.evaluation.CMM.calculateMatching(), moa.evaluation.StatisticalCollection.cindex(), moa.evaluation.General.computeCompactness(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.evaluation.SilhouetteCoefficient.evaluateClustering(), moa.evaluation.General.evaluateClustering(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), and moa.evaluation.MembershipMatrix.MembershipMatrix().
String moa.cluster.Cluster.getInfo ()
Definition at line 141 of file Cluster.java.
References moa.cluster.Cluster.getClusterSpecificInfo(), and moa.cluster.Cluster.measure_values.
Referenced by moa.gui.visualization.ClusterPanel.updateTooltip().
{
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        getClusterSpecificInfo(infoTitle, infoValue);
        StringBuffer sb = new StringBuffer();
        //Cluster properties
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td>"+infoTitle.get(i)+"</td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        //Evaluation info
        sb.append("<br>");
        sb.append("<b>Evaluation</b><br>");
        sb.append("<table>");
        Iterator miterator = measure_values.entrySet().iterator();
        while(miterator.hasNext()) {
             Map.Entry e = (Map.Entry)miterator.next();
             sb.append("<tr><td>"+e.getKey()+"</td><td>"+e.getValue()+"</td></tr>");
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
String moa.cluster.Cluster.getMeasureValue (String measureKey)
Definition at line 114 of file Cluster.java.
References moa.cluster.Cluster.measure_values.
{
        if(measure_values.containsKey(measureKey))
            return measure_values.get(measureKey);
        else
            return "";
    }
abstract double moa.cluster.Cluster.getWeight () [pure virtual]
Returns the weight of this cluster, not neccessarily normalized.
It could, for instance, simply return the number of points contined in this cluster.
Returns:
the weight
Implemented in moa.cluster.CFCluster, moa.cluster.SphereCluster, moa.clusterers.clustree.ClusKernel, and moa.clusterers.denstream.MicroCluster.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.evaluation.CMM.calculateMatching(), moa.cluster.Cluster.getClusterSpecificInfo(), moa.gui.visualization.RunVisualizer.weka(), and moa.gui.visualization.RunOutlierVisualizer.weka().
boolean moa.cluster.Cluster.isGroundTruth ()
Definition at line 84 of file Cluster.java.
References moa.cluster.Cluster.gtLabel.
{
        return gtLabel != -1;
    }
abstract Instance moa.cluster.Cluster.sample (Random random) [pure virtual]
Samples this cluster by returning a point from inside it.
Parameters:
random a random number source
Returns:
an Instance that lies inside this cluster
Implemented in moa.cluster.SphereCluster.
void moa.cluster.Cluster.setGroundTruth (double truth)
Definition at line 88 of file Cluster.java.
References moa.cluster.Cluster.gtLabel.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), and moa.cluster.Clustering.Clustering().
{
        gtLabel = truth;
    }
void moa.cluster.Cluster.setId (double id)
Definition at line 76 of file Cluster.java.
Referenced by moa.cluster.Clustering.Clustering(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), and moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs().
{
        this.id = id;
    }
void moa.cluster.Cluster.setMeasureValue (String measureKey, double value)
Definition at line 109 of file Cluster.java.
References moa.cluster.Cluster.measure_values.
{
        measure_values.put(measureKey, Double.toString(value));
    }
void moa.cluster.Cluster.setMeasureValue (String measureKey, String value)
Definition at line 105 of file Cluster.java.
References moa.cluster.Cluster.measure_values.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.General.computeCompactness(), and moa.evaluation.F1.evaluateClustering().
{
        measure_values.put(measureKey, value);
    }
Member Data Documentation
double moa.cluster.Cluster.gtLabel = -1 [private]
Definition at line 36 of file Cluster.java.
Referenced by moa.cluster.Cluster.getGroundTruth(), moa.cluster.Cluster.isGroundTruth(), and moa.cluster.Cluster.setGroundTruth().
double moa.cluster.Cluster.id = -1 [private]
Definition at line 35 of file Cluster.java.
Referenced by moa.cluster.Cluster.getId().
HashMap<String, String> moa.cluster.Cluster.measure_values [private]
Definition at line 38 of file Cluster.java.
Referenced by moa.cluster.Cluster.Cluster(), moa.cluster.Cluster.getInfo(), moa.cluster.Cluster.getMeasureValue(), and moa.cluster.Cluster.setMeasureValue().
final long moa.cluster.Cluster.serialVersionUID = 1L [static, private]
Reimplemented in moa.cluster.CFCluster, moa.cluster.SphereCluster, moa.clusterers.clustream.ClustreamKernel, and moa.clusterers.macro.NonConvexCluster.
Definition at line 33 of file Cluster.java.
The documentation for this class was generated from the following file:
main/java/moa/cluster/Cluster.java