MOA: moa.gui.IntOptionEditComponent Class Reference
moa.gui.IntOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit an integer option.
Public Member Functions
IntOptionEditComponent (IntOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
Protected Attributes
IntOption editedOption
JSpinner spinner
JSlider slider
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit an integer option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 40 of file IntOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.IntOptionEditComponent.IntOptionEditComponent (IntOption option)
Definition at line 51 of file IntOptionEditComponent.java.
References moa.gui.IntOptionEditComponent.editedOption, moa.options.IntOption.getMaxValue(), moa.options.IntOption.getMinValue(), moa.options.IntOption.getValue(), moa.gui.IntOptionEditComponent.slider, and moa.gui.IntOptionEditComponent.spinner.
{
        this.editedOption = option;
        int minVal = option.getMinValue();
        int maxVal = option.getMaxValue();
        setLayout(new GridLayout(1, 0));
        this.spinner = new JSpinner(new SpinnerNumberModel(option.getValue(),
                minVal, maxVal, 1));
        add(this.spinner);
        if ((minVal > Integer.MIN_VALUE) && (maxVal < Integer.MAX_VALUE)) {
            this.slider = new JSlider(minVal, maxVal, option.getValue());
            add(this.slider);
            this.slider.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    IntOptionEditComponent.this.spinner.setValue(IntOptionEditComponent.this.slider.getValue());
                }
            });
            this.spinner.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    IntOptionEditComponent.this.slider.setValue(((Integer) IntOptionEditComponent.this.spinner.getValue()).intValue());
                }
            });
        }
    }
Member Function Documentation
void moa.gui.IntOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 80 of file IntOptionEditComponent.java.
References moa.gui.IntOptionEditComponent.editedOption, moa.options.IntOption.setValue(), and moa.gui.IntOptionEditComponent.spinner.
{
        this.editedOption.setValue(((Integer) this.spinner.getValue()).intValue());
    }
Option moa.gui.IntOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 85 of file IntOptionEditComponent.java.
References moa.gui.IntOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.IntOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 90 of file IntOptionEditComponent.java.
References moa.gui.IntOptionEditComponent.spinner.
{
        this.spinner.setValue(IntOption.cliStringToInt(cliString));
    }
Member Data Documentation
IntOption moa.gui.IntOptionEditComponent.editedOption [protected]
Definition at line 45 of file IntOptionEditComponent.java.
Referenced by moa.gui.IntOptionEditComponent.applyState(), moa.gui.IntOptionEditComponent.getEditedOption(), and moa.gui.IntOptionEditComponent.IntOptionEditComponent().
final long moa.gui.IntOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 43 of file IntOptionEditComponent.java.
JSlider moa.gui.IntOptionEditComponent.slider [protected]
Definition at line 49 of file IntOptionEditComponent.java.
Referenced by moa.gui.IntOptionEditComponent.IntOptionEditComponent().
JSpinner moa.gui.IntOptionEditComponent.spinner [protected]
Definition at line 47 of file IntOptionEditComponent.java.
Referenced by moa.gui.IntOptionEditComponent.applyState(), moa.gui.IntOptionEditComponent.IntOptionEditComponent(), and moa.gui.IntOptionEditComponent.setEditState().
The documentation for this class was generated from the following file:
main/java/moa/gui/IntOptionEditComponent.java