MOA: moa.gui.RegressionTaskManagerPanel.TaskTableModel Class Reference
moa.gui.RegressionTaskManagerPanel.TaskTableModel Class Reference
Public Member Functions
String getColumnName (int col)
int getColumnCount ()
int getRowCount ()
Object getValueAt (int row, int col)
boolean isCellEditable (int row, int col)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 133 of file RegressionTaskManagerPanel.java.
Member Function Documentation
int moa.gui.RegressionTaskManagerPanel.TaskTableModel.getColumnCount ()
Definition at line 155 of file RegressionTaskManagerPanel.java.
{
            return 5;
        }
String moa.gui.RegressionTaskManagerPanel.TaskTableModel.getColumnName (int col)
Definition at line 138 of file RegressionTaskManagerPanel.java.
{
            switch (col) {
                case 0:
                    return "command";
                case 1:
                    return "status";
                case 2:
                    return "time elapsed";
                case 3:
                    return "current activity";
                case 4:
                    return "% complete";
            }
            return null;
        }
int moa.gui.RegressionTaskManagerPanel.TaskTableModel.getRowCount ()
Definition at line 160 of file RegressionTaskManagerPanel.java.
{
            return RegressionTaskManagerPanel.this.taskList.size();
        }
Object moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt (int row, int col)
Definition at line 165 of file RegressionTaskManagerPanel.java.
References moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.getCurrentActivityFracComplete(), moa.tasks.TaskThread.getCurrentActivityString(), moa.tasks.TaskThread.getCurrentStatusString(), and moa.tasks.TaskThread.getTask().
{
            TaskThread thread = RegressionTaskManagerPanel.this.taskList.get(row);
            switch (col) {
                case 0:
                    return ((OptionHandler) thread.getTask()).getCLICreationString(RegressionMainTask.class);
                case 1:
                    return thread.getCurrentStatusString();
                case 2:
                    return StringUtils.secondsToDHMSString(thread.getCPUSecondsElapsed());
                case 3:
                    return thread.getCurrentActivityString();
                case 4:
                    return new Double(thread.getCurrentActivityFracComplete());
            }
            return null;
        }
boolean moa.gui.RegressionTaskManagerPanel.TaskTableModel.isCellEditable (int row, int col)
Definition at line 183 of file RegressionTaskManagerPanel.java.
{
            return false;
        }
Member Data Documentation
final long moa.gui.RegressionTaskManagerPanel.TaskTableModel.serialVersionUID = 1L [static, private]
Definition at line 135 of file RegressionTaskManagerPanel.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/RegressionTaskManagerPanel.java