MOA: moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator Class Reference
moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator Class Reference
Multilabel Window Classification Performance Evaluator.
Public Member Functions
void reset ()
Resets this evaluator.
void reset (int L)
void addResult (Instance x, double[] y)
Add a Result.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Package Attributes
ArrayList< double[]> result_pred = new ArrayList<double[]>()
ArrayList< int[]> result_real = new ArrayList<int[]>()
Private Attributes
double LC = -1.0
Detailed Description
Multilabel Window Classification Performance Evaluator.
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
Revision
1
Definition at line 34 of file MultilabelWindowClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.addResult (Instance x, double[] y)
Add a Result.
NOTE: In theory, the size of y[] could change, although we do not take into account this possibility *yet*. (for this, we would have to use y[] differently, another format for y[] e.g. HashMap, or store more info in x)
Reimplemented from moa.evaluation.WindowClassificationPerformanceEvaluator.
Definition at line 64 of file MultilabelWindowClassificationPerformanceEvaluator.java.
References moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_pred, and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_real.
{
        if (y.length <= 2) {
            System.err.println("y.length too short (" + y.length + "). We've lost track of L at some point, unable to continue");
            System.exit(1);
        }
        // add to the current evaluation window
        result_real.add(EvalUtils.toIntArray(x, y.length));
        result_pred.add(y);
    }
void moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Reimplemented from moa.evaluation.WindowClassificationPerformanceEvaluator.
Definition at line 112 of file MultilabelWindowClassificationPerformanceEvaluator.java.
{
        sb.append("Multi-label Window Classification Performance Evaluator");
    }
Measurement [] moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Reimplemented from moa.evaluation.WindowClassificationPerformanceEvaluator.
Definition at line 75 of file MultilabelWindowClassificationPerformanceEvaluator.java.
References moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.LC, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset(), moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_pred, and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_real.
{
        // calculate threshold
        double t = 0.5;
        try {
            t = (LC > 0.0) ? EvalUtils.calibrateThreshold(result_pred, LC) : 0.5;
        } catch (Exception e) {
            System.err.println("Warning: failed to calibrate threshold, continuing with default: t = " + t);
            e.printStackTrace();
        }
        // calculate performance
        HashMap<String, Double> result = EvalUtils.evaluateMultiLabel(result_pred, result_real, t);
        // gather measurements
        Measurement m[] = new Measurement[]{
            new Measurement("Subset Accuracy", result.get("Accuracy")),
            new Measurement("Exact Match", result.get("Exact_match")),
            new Measurement("Hamming Accucaracy", result.get("H_acc")),
            new Measurement("Log Loss_D", result.get("LogLossD")),
            //new Measurement( "F1-macro_L", result.get("F1_macro_L")),
            //new Measurement( "LCard_real", result.get("LCard_real")),
            //new Measurement( "LCard_pred", result.get("LCard_pred")),
            new Measurement("Threshold", result.get("Threshold")), //new Measurement( "L", result.get("L")),
        //new Measurement( "N", result.get("N")),
        };
        // save label cardinality for the next window
        LC = result.get("LCard_real");
        // reset
        reset();
        return m;
    }
void moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset (int L)
Reimplemented from moa.evaluation.WindowClassificationPerformanceEvaluator.
Definition at line 51 of file MultilabelWindowClassificationPerformanceEvaluator.java.
References moa.options.IntOption.getValue(), moa.evaluation.WindowClassificationPerformanceEvaluator.numClasses, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_pred, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_real, and moa.evaluation.WindowClassificationPerformanceEvaluator.widthOption.
{
        numClasses = L;
        result_pred = new ArrayList<double[]>(widthOption.getValue());
        result_real = new ArrayList<int[]>(widthOption.getValue());
    }
void moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Reimplemented from moa.evaluation.WindowClassificationPerformanceEvaluator.
Definition at line 45 of file MultilabelWindowClassificationPerformanceEvaluator.java.
References moa.options.IntOption.getValue(), moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_pred, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_real, and moa.evaluation.WindowClassificationPerformanceEvaluator.widthOption.
Referenced by moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        result_pred = new ArrayList<double[]>(widthOption.getValue());
        result_real = new ArrayList<int[]>(widthOption.getValue());
    }
Member Data Documentation
double moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.LC = -1.0 [private]
Definition at line 42 of file MultilabelWindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getPerformanceMeasurements().
ArrayList<double[]> moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_pred = new ArrayList<double[]>() [package]
Definition at line 37 of file MultilabelWindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset().
ArrayList<int[]> moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.result_real = new ArrayList<int[]>() [package]
Definition at line 39 of file MultilabelWindowClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.addResult(), moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/MultilabelWindowClassificationPerformanceEvaluator.java