MOA: moa.clusterers.denstream.Timestamp Class Reference
moa.clusterers.denstream.Timestamp Class Reference
Public Member Functions
Timestamp (long timestamp)
Timestamp ()
long getTimestamp ()
void increase ()
void setTimestamp (long timestamp)
void getDescription (StringBuilder sb, int i)
Returns a string representation of this object.
Private Attributes
long timestamp
Detailed Description
Definition at line 24 of file Timestamp.java.
Constructor & Destructor Documentation
moa.clusterers.denstream.Timestamp.Timestamp (long timestamp)
Definition at line 28 of file Timestamp.java.
{
        this.timestamp = timestamp;
    }
moa.clusterers.denstream.Timestamp.Timestamp ()
Definition at line 32 of file Timestamp.java.
References moa.clusterers.denstream.Timestamp.timestamp.
                       {
        timestamp = 0;
    }
Member Function Documentation
void moa.clusterers.denstream.Timestamp.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 48 of file Timestamp.java.
{
    }
long moa.clusterers.denstream.Timestamp.getTimestamp ()
Definition at line 36 of file Timestamp.java.
References moa.clusterers.denstream.Timestamp.timestamp.
Referenced by moa.clusterers.denstream.MicroCluster.getCenter(), moa.clusterers.denstream.MicroCluster.getRadius(), and moa.clusterers.denstream.MicroCluster.getWeight().
{
        return timestamp;
    }
void moa.clusterers.denstream.Timestamp.increase ()
Definition at line 40 of file Timestamp.java.
References moa.clusterers.denstream.Timestamp.timestamp.
{
        timestamp++;
    }
void moa.clusterers.denstream.Timestamp.setTimestamp (long timestamp)
Definition at line 44 of file Timestamp.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        this.timestamp = timestamp;
    }
Member Data Documentation
long moa.clusterers.denstream.Timestamp.timestamp [private]
Definition at line 26 of file Timestamp.java.
Referenced by moa.clusterers.denstream.Timestamp.getTimestamp(), moa.clusterers.denstream.Timestamp.increase(), and moa.clusterers.denstream.Timestamp.Timestamp().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/denstream/Timestamp.java