MOA: moa.core.DoubleVector Class Reference
moa.core.DoubleVector Class Reference
Vector of double numbers with some utilities.
Public Member Functions
DoubleVector ()
DoubleVector (double[] toCopy)
DoubleVector (DoubleVector toCopy)
int numValues ()
void setValue (int i, double v)
void addToValue (int i, double v)
void addValues (DoubleVector toAdd)
void addValues (double[] toAdd)
void subtractValues (DoubleVector toSubtract)
void subtractValues (double[] toSubtract)
void addToValues (double toAdd)
void scaleValues (double multiplier)
double getValue (int i)
double sumOfValues ()
int maxIndex ()
void normalize ()
int numNonZeroEntries ()
double minWeight ()
double[] getArrayCopy ()
double[] getArrayRef ()
void getSingleLineDescription (StringBuilder out)
void getSingleLineDescription (StringBuilder out, int numValues)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Member Functions
void setArrayLength (int l)
Protected Attributes
double[] array
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Vector of double numbers with some utilities.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 30 of file DoubleVector.java.
Constructor & Destructor Documentation
moa.core.DoubleVector.DoubleVector ()
Definition at line 36 of file DoubleVector.java.
References moa.core.DoubleVector.array.
{
        this.array = new double[0];
    }
moa.core.DoubleVector.DoubleVector (double[] toCopy)
Definition at line 40 of file DoubleVector.java.
References moa.core.DoubleVector.array.
{
        this.array = new double[toCopy.length];
        System.arraycopy(toCopy, 0, this.array, 0, toCopy.length);
    }
moa.core.DoubleVector.DoubleVector (DoubleVector toCopy)
Definition at line 45 of file DoubleVector.java.
References moa.core.DoubleVector.getArrayRef().
{
        this(toCopy.getArrayRef());
    }
Member Function Documentation
void moa.core.DoubleVector.addToValue (int i, double v)
Definition at line 60 of file DoubleVector.java.
References moa.core.DoubleVector.array, and moa.core.DoubleVector.setArrayLength().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.InactiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.InactiveLearningNode.learnFromInstance(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance(), moa.classifiers.rules.core.RuleActiveRegressionNode.learnFromInstance(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.Node(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.Node(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeClass(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.functions.SGDMultiClass.trainOnInstanceImpl(), moa.classifiers.functions.SGD.trainOnInstanceImpl(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.functions.MajorityClass.trainOnInstanceImpl(), moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl(), moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl(), moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl(), and moa.classifiers.rules.RuleClassifier.updateRuleAttribStatistics().
{
        if (i >= this.array.length) {
            setArrayLength(i + 1);
        }
        this.array[i] += v;
    }
void moa.core.DoubleVector.addToValues (double toAdd)
Definition at line 93 of file DoubleVector.java.
References moa.core.DoubleVector.array.
{
        for (int i = 0; i < this.array.length; i++) {
            this.array[i] = this.array[i] + toAdd;
        }
    }
void moa.core.DoubleVector.addValues (double[] toAdd)
Definition at line 71 of file DoubleVector.java.
References moa.core.DoubleVector.array, and moa.core.DoubleVector.setArrayLength().
{
        if (toAdd.length > this.array.length) {
            setArrayLength(toAdd.length);
        }
        for (int i = 0; i < toAdd.length; i++) {
            this.array[i] += toAdd[i];
        }
    }
void moa.core.DoubleVector.addValues (DoubleVector toAdd)
Definition at line 67 of file DoubleVector.java.
References moa.core.DoubleVector.getArrayRef().
Referenced by moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.trees.HoeffdingOptionTree.getVotesForInstance(), moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance(), moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OzaBagAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBag.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
{
        addValues(toAdd.getArrayRef());
    }
double [] moa.core.DoubleVector.getArrayCopy ()
Definition at line 155 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.rules.RuleClassifier.entropy(), moa.classifiers.trees.DecisionStump.findBestSplit(), moa.classifiers.DecisionStumpTutorial.findBestSplit(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.Node.getClassVotes(), moa.classifiers.trees.HoeffdingOptionTree.Node.getClassVotes(), moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode.getClassVotes(), moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution(), moa.classifiers.trees.DecisionStump.getVotesForInstance(), moa.classifiers.functions.MajorityClass.getVotesForInstance(), and moa.classifiers.DecisionStumpTutorial.getVotesForInstance().
{
        double[] aCopy = new double[this.array.length];
        System.arraycopy(this.array, 0, aCopy, 0, this.array.length);
        return aCopy;
    }
double [] moa.core.DoubleVector.getArrayRef ()
Definition at line 161 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.core.DoubleVector.addValues(), moa.core.DoubleVector.DoubleVector(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.active.ActiveClassifier.getMaxPosterior(), moa.classifiers.trees.HoeffdingOptionTree.getVotesForInstance(), moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance(), moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OzaBagAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBag.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.evaluation.LearningCurve.insertEntry(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption(), and moa.core.DoubleVector.subtractValues().
{
        return this.array;
    }
void moa.core.DoubleVector.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 191 of file DoubleVector.java.
References moa.core.DoubleVector.getSingleLineDescription().
{
        getSingleLineDescription(sb);
    }
void moa.core.DoubleVector.getSingleLineDescription (StringBuilder out, int numValues)
Definition at line 179 of file DoubleVector.java.
References moa.core.DoubleVector.getValue().
{
        out.append("{");
        for (int i = 0; i < numValues; i++) {
            if (i > 0) {
                out.append("|");
            }
            out.append(StringUtils.doubleToString(getValue(i), 3));
        }
        out.append("}");
    }
void moa.core.DoubleVector.getSingleLineDescription (StringBuilder out)
Definition at line 175 of file DoubleVector.java.
References moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), and moa.core.DoubleVector.getDescription().
{
        getSingleLineDescription(out, numValues());
    }
double moa.core.DoubleVector.getValue (int i)
Definition at line 106 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise(), moa.classifiers.rules.RuleClassifier.computeAnomalySupervised(), moa.classifiers.rules.RuleClassifier.computeAnomalyUnsupervised(), moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog(), moa.classifiers.functions.SGDMultiClass.dotProd(), moa.classifiers.functions.SGD.dotProd(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.getBestSecondBestEntropy(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.functions.MajorityClass.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayes.getModelDescription(), moa.classifiers.rules.RuleClassifier.getModelDescriptionNoAnomalyDetection(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), moa.core.DoubleVector.getSingleLineDescription(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), moa.classifiers.trees.ORTO.ActiveLearningNode.getSquaredError(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getWeightSeen(), moa.classifiers.rules.core.RuleActiveRegressionNode.getWeightSeen(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.classifiers.rules.AMRulesRegressor.newRule(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.classifiers.rules.core.RuleActiveRegressionNode.normalize(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.rules.RuleClassifier.oberversDistribProb(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass(), moa.classifiers.rules.RuleClassifier.printAnomaliesSupervised(), moa.classifiers.rules.RuleClassifier.printAnomaliesUnsupervised(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.probabilityOfAttributeValueGivenClass(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.rules.RuleClassifier.theBestAttributes(), moa.classifiers.functions.SGDMultiClass.toString(), moa.classifiers.functions.SGD.toString(), moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
{
        return ((i >= 0) && (i < this.array.length)) ? this.array[i] : 0.0;
    }
int moa.core.DoubleVector.maxIndex ()
Definition at line 118 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise(), moa.classifiers.functions.MajorityClass.getModelDescription(), and moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode.learnFromInstance().
{
        int max = -1;
        for (int i = 0; i < this.array.length; i++) {
            if ((max < 0) || (this.array[i] > this.array[max])) {
                max = i;
            }
        }
        return max;
    }
double moa.core.DoubleVector.minWeight ()
Definition at line 142 of file DoubleVector.java.
References moa.core.DoubleVector.array.
{
        if (this.array.length > 0) {
            double min = this.array[0];
            for (int i = 1; i < this.array.length; i++) {
                if (this.array[i] < min) {
                    min = this.array[i];
                }
            }
            return min;
        }
        return 0.0;
    }
void moa.core.DoubleVector.normalize ()
Definition at line 128 of file DoubleVector.java.
References moa.core.DoubleVector.scaleValues(), and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.active.ActiveClassifier.getMaxPosterior(), moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OzaBagAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBag.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), and moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance().
{
        scaleValues(1.0 / sumOfValues());
    }
int moa.core.DoubleVector.numNonZeroEntries ()
Definition at line 132 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.streams.filters.AddNoiseFilter.nextInstance(), moa.classifiers.trees.HoeffdingTree.Node.observedClassDistributionIsPure(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistributionIsPure().
{
        int count = 0;
        for (double element : this.array) {
            if (element != 0.0) {
                count++;
            }
        }
        return count;
    }
int moa.core.DoubleVector.numValues ()
Definition at line 49 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog(), moa.classifiers.functions.SGDMultiClass.dotProd(), moa.classifiers.functions.SGD.dotProd(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.getBestSecondBestEntropy(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.functions.MajorityClass.getModelDescription(), moa.classifiers.bayes.NaiveBayes.getModelDescription(), moa.classifiers.rules.RuleClassifier.getRuleMajorityClassIndex(), moa.core.DoubleVector.getSingleLineDescription(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.probabilityOfAttributeValueGivenClass(), moa.classifiers.functions.SGDMultiClass.toString(), moa.classifiers.functions.SGD.toString(), moa.classifiers.functions.SGDMultiClass.trainOnInstanceImpl(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
{
        return this.array.length;
    }
void moa.core.DoubleVector.scaleValues (double multiplier)
Definition at line 99 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.core.DoubleVector.normalize(), and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass().
{
        for (int i = 0; i < this.array.length; i++) {
            this.array[i] = this.array[i] * multiplier;
        }
    }
void moa.core.DoubleVector.setArrayLength (int l) [protected]
Definition at line 165 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.core.DoubleVector.addToValue(), moa.core.DoubleVector.addValues(), moa.core.DoubleVector.setValue(), and moa.core.DoubleVector.subtractValues().
{
        double[] newArray = new double[l];
        int numToCopy = this.array.length;
        if (numToCopy > l) {
            numToCopy = l;
        }
        System.arraycopy(this.array, 0, newArray, 0, numToCopy);
        this.array = newArray;
    }
void moa.core.DoubleVector.setValue (int i, double v)
Definition at line 53 of file DoubleVector.java.
References moa.core.DoubleVector.array, and moa.core.DoubleVector.setArrayLength().
Referenced by moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), moa.classifiers.rules.core.RuleActiveRegressionNode.initialize(), moa.evaluation.LearningCurve.insertEntry(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.observeAttributeClass(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.rules.RuleClassifier.theBestAttributes(), moa.classifiers.functions.SGDMultiClass.trainOnInstanceImpl(), and moa.classifiers.functions.SGD.trainOnInstanceImpl().
{
        if (i >= this.array.length) {
            setArrayLength(i + 1);
        }
        this.array[i] = v;
    }
void moa.core.DoubleVector.subtractValues (double[] toSubtract)
Definition at line 84 of file DoubleVector.java.
References moa.core.DoubleVector.array, and moa.core.DoubleVector.setArrayLength().
{
        if (toSubtract.length > this.array.length) {
            setArrayLength(toSubtract.length);
        }
        for (int i = 0; i < toSubtract.length; i++) {
            this.array[i] -= toSubtract[i];
        }
    }
void moa.core.DoubleVector.subtractValues (DoubleVector toSubtract)
Definition at line 80 of file DoubleVector.java.
References moa.core.DoubleVector.getArrayRef().
Referenced by moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
{
        subtractValues(toSubtract.getArrayRef());
    }
double moa.core.DoubleVector.sumOfValues ()
Definition at line 110 of file DoubleVector.java.
References moa.core.DoubleVector.array.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise(), moa.classifiers.rules.RuleClassifier.createRule(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.classifiers.rules.RuleClassifier.findBestValEntropy(), moa.classifiers.rules.RuleClassifier.findBestValEntropyNominalAtt(), moa.classifiers.active.ActiveClassifier.getMaxPosterior(), moa.classifiers.bayes.NaiveBayes.getModelDescription(), moa.classifiers.meta.WeightedMajorityAlgorithm.getVotesForInstance(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoost.getVotesForInstance(), moa.classifiers.meta.OzaBagASHT.getVotesForInstance(), moa.classifiers.meta.OzaBagAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBag.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.LeveragingBag.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.getVotesForInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.rules.RuleClassifier.getWeightSeen(), moa.classifiers.rules.RuleClassifier.mainFindBestValEntropy(), moa.core.DoubleVector.normalize(), moa.classifiers.rules.RuleClassifier.oberversDistribProb(), and moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.probabilityOfAttributeValueGivenClass().
{
        double sum = 0.0;
        for (double element : this.array) {
            sum += element;
        }
        return sum;
    }
Member Data Documentation
double [] moa.core.DoubleVector.array [protected]
Definition at line 34 of file DoubleVector.java.
Referenced by moa.core.DoubleVector.addToValue(), moa.core.DoubleVector.addToValues(), moa.core.DoubleVector.addValues(), moa.core.DoubleVector.DoubleVector(), moa.core.DoubleVector.getArrayCopy(), moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.getValue(), moa.core.DoubleVector.maxIndex(), moa.core.DoubleVector.minWeight(), moa.core.DoubleVector.numNonZeroEntries(), moa.core.DoubleVector.numValues(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.setArrayLength(), moa.core.DoubleVector.setValue(), moa.core.DoubleVector.subtractValues(), and moa.core.DoubleVector.sumOfValues().
final long moa.core.DoubleVector.serialVersionUID = 1L [static, private]
Definition at line 32 of file DoubleVector.java.
The documentation for this class was generated from the following file:
main/java/moa/core/DoubleVector.java