MOA: moa.gui.ClassOptionSelectionPanel Class Reference
moa.gui.ClassOptionSelectionPanel Class Reference
Creates a panel that displays the classes available, letting the user select a class.
Public Member Functions
ClassOptionSelectionPanel (Class<?> requiredType, String initialCLIString, String nullString)
Class<?>[] findSuitableClasses (Class<?> requiredType)
String getChosenObjectCLIString (Class<?> requiredType)
void classChoiceChanged (Object chosen)
Static Public Member Functions
static String showSelectClassDialog (Component parent, String title, Class<?> requiredType, String initialCLIString, String nullString)
Protected Attributes
JComboBox classChoiceBox
JComponent chosenObjectEditor
Object chosenObject
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Creates a panel that displays the classes available, letting the user select a class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 48 of file ClassOptionSelectionPanel.java.
Constructor & Destructor Documentation
moa.gui.ClassOptionSelectionPanel.ClassOptionSelectionPanel (Class<?> requiredType, String initialCLIString, String nullString)
Definition at line 62 of file ClassOptionSelectionPanel.java.
References moa.gui.ClassOptionSelectionPanel.classChoiceBox, moa.gui.ClassOptionSelectionPanel.classChoiceChanged(), and moa.gui.ClassOptionSelectionPanel.findSuitableClasses().
Referenced by moa.gui.ClassOptionSelectionPanel.showSelectClassDialog().
{
        // Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("moa",
        // requiredType);
        Class<?>[] classesFound = findSuitableClasses(requiredType);
        this.classChoiceBox = new JComboBox(classesFound);
        setLayout(new BorderLayout());
        add(this.classChoiceBox, BorderLayout.NORTH);
        Object initialObject = null;
        try {
            initialObject = ClassOption.cliStringToObject(initialCLIString,
                    requiredType, null);
        } catch (Exception ignored) {
            // ignore exception
        }
        if (initialObject != null) {
            this.classChoiceBox.setSelectedItem(initialObject.getClass());
            classChoiceChanged(initialObject);
        } else {
            try {
                Object chosen = ((Class<?>) ClassOptionSelectionPanel.this.classChoiceBox.getSelectedItem()).newInstance();
                classChoiceChanged(chosen);
            } catch (Exception ex) {
                GUIUtils.showExceptionDialog(ClassOptionSelectionPanel.this,
                        "Problem", ex);
            }
        }
        this.classChoiceBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                try {
                    Object chosen = ((Class<?>) ClassOptionSelectionPanel.this.classChoiceBox.getSelectedItem()).newInstance();
                    classChoiceChanged(chosen);
                } catch (Exception ex) {
                    GUIUtils.showExceptionDialog(
                            ClassOptionSelectionPanel.this, "Problem", ex);
                }
            }
        });
    }
Member Function Documentation
void moa.gui.ClassOptionSelectionPanel.classChoiceChanged (Object chosen)
Definition at line 145 of file ClassOptionSelectionPanel.java.
References moa.gui.ClassOptionSelectionPanel.chosenObject, moa.gui.ClassOptionSelectionPanel.chosenObjectEditor, moa.options.OptionHandler.getOptions(), and moa.options.OptionHandler.getPurposeString().
Referenced by moa.gui.ClassOptionSelectionPanel.ClassOptionSelectionPanel().
{
        this.chosenObject = chosen;
        JComponent newChosenObjectEditor = null;
        if (this.chosenObject instanceof OptionHandler) {
            OptionHandler chosenOptionHandler = (OptionHandler) this.chosenObject;
            newChosenObjectEditor = new OptionsConfigurationPanel(
                    chosenOptionHandler.getPurposeString(), chosenOptionHandler.getOptions());
        }
        if (this.chosenObjectEditor != null) {
            remove(this.chosenObjectEditor);
        }
        this.chosenObjectEditor = newChosenObjectEditor;
        if (this.chosenObjectEditor != null) {
            add(this.chosenObjectEditor, BorderLayout.CENTER);
        }
        Component component = this;
        while ((component != null) && !(component instanceof JDialog)) {
            component = component.getParent();
        }
        if (component != null) {
            Window window = (Window) component;
            window.pack();
        }
    }
Class<?> [] moa.gui.ClassOptionSelectionPanel.findSuitableClasses (Class<?> requiredType)
Definition at line 104 of file ClassOptionSelectionPanel.java.
References moa.tasks.Task.getTaskResultType().
Referenced by moa.gui.ClassOptionSelectionPanel.ClassOptionSelectionPanel().
{
        AutoExpandVector<Class<?>> finalClasses = new AutoExpandVector<Class<?>>();
        Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("moa",
                requiredType);
        for (Class<?> foundClass : classesFound) {
            finalClasses.add(foundClass);
        }
        Class<?>[] tasksFound = AutoClassDiscovery.findClassesOfType("moa",
                Task.class);
        for (Class<?> foundTask : tasksFound) {
            try {
                Task task = (Task) foundTask.newInstance();
                if (requiredType.isAssignableFrom(task.getTaskResultType())) {
                    finalClasses.add(foundTask);
                }
            } catch (Exception e) {
                // ignore
            }
        }
        return finalClasses.toArray(new Class<?>[finalClasses.size()]);
    }
String moa.gui.ClassOptionSelectionPanel.getChosenObjectCLIString (Class<?> requiredType)
Definition at line 138 of file ClassOptionSelectionPanel.java.
References moa.gui.ClassOptionSelectionPanel.chosenObject, and moa.gui.ClassOptionSelectionPanel.chosenObjectEditor.
Referenced by moa.gui.ClassOptionSelectionPanel.showSelectClassDialog().
{
        if (this.chosenObjectEditor instanceof OptionsConfigurationPanel) {
            ((OptionsConfigurationPanel) this.chosenObjectEditor).applyChanges();
        }
        return ClassOption.objectToCLIString(this.chosenObject, requiredType);
    }
static String moa.gui.ClassOptionSelectionPanel.showSelectClassDialog (Component parent, String title, Class<?> requiredType, String initialCLIString, String nullString) [static]
Definition at line 126 of file ClassOptionSelectionPanel.java.
References moa.gui.ClassOptionSelectionPanel.ClassOptionSelectionPanel(), and moa.gui.ClassOptionSelectionPanel.getChosenObjectCLIString().
{
        ClassOptionSelectionPanel panel = new ClassOptionSelectionPanel(
                requiredType, initialCLIString, nullString);
        if (JOptionPane.showOptionDialog(parent, panel, title,
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                null, null) == JOptionPane.OK_OPTION) {
            return panel.getChosenObjectCLIString(requiredType);
        }
        return initialCLIString;
    }
Member Data Documentation
Object moa.gui.ClassOptionSelectionPanel.chosenObject [protected]
Definition at line 60 of file ClassOptionSelectionPanel.java.
Referenced by moa.gui.ClassOptionSelectionPanel.classChoiceChanged(), and moa.gui.ClassOptionSelectionPanel.getChosenObjectCLIString().
JComponent moa.gui.ClassOptionSelectionPanel.chosenObjectEditor [protected]
Definition at line 58 of file ClassOptionSelectionPanel.java.
Referenced by moa.gui.ClassOptionSelectionPanel.classChoiceChanged(), and moa.gui.ClassOptionSelectionPanel.getChosenObjectCLIString().
JComboBox moa.gui.ClassOptionSelectionPanel.classChoiceBox [protected]
Definition at line 56 of file ClassOptionSelectionPanel.java.
Referenced by moa.gui.ClassOptionSelectionPanel.ClassOptionSelectionPanel().
final long moa.gui.ClassOptionSelectionPanel.serialVersionUID = 1L [static, private]
Definition at line 54 of file ClassOptionSelectionPanel.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/ClassOptionSelectionPanel.java