MOA: moa.streams.MultiFilteredStream Class Reference
moa.streams.MultiFilteredStream Class Reference
Class for representing a stream that is filtered.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
ClassOption streamOption
ListOption filtersOption
Protected Attributes
InstanceStream filterChain
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for representing a stream that is filtered.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 39 of file MultiFilteredStream.java.
Member Function Documentation
long moa.streams.MultiFilteredStream.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 90 of file MultiFilteredStream.java.
References moa.streams.InstanceStream.estimatedRemainingInstances(), and moa.streams.MultiFilteredStream.filterChain.
{
        return this.filterChain.estimatedRemainingInstances();
    }
void moa.streams.MultiFilteredStream.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 120 of file MultiFilteredStream.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.MultiFilteredStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 95 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, and moa.streams.InstanceStream.getHeader().
{
        return this.filterChain.getHeader();
    }
String moa.streams.MultiFilteredStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 43 of file MultiFilteredStream.java.
{
        return "A stream that is filtered.";
    }
boolean moa.streams.MultiFilteredStream.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 100 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, and moa.streams.InstanceStream.hasMoreInstances().
{
        return this.filterChain.hasMoreInstances();
    }
boolean moa.streams.MultiFilteredStream.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 105 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, and moa.streams.InstanceStream.isRestartable().
{
        return this.filterChain.isRestartable();
    }
Instance moa.streams.MultiFilteredStream.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 110 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, and moa.streams.InstanceStream.nextInstance().
{
        return this.filterChain.nextInstance();
    }
void moa.streams.MultiFilteredStream.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 61 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, moa.streams.MultiFilteredStream.filtersOption, moa.options.ListOption.getList(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.streams.filters.StreamFilter.setInputStream(), moa.streams.MultiFilteredStream.streamOption, and moa.tasks.TaskMonitor.taskShouldAbort().
{
        Option[] filterOptions = this.filtersOption.getList();
        StreamFilter[] filters = new StreamFilter[filterOptions.length];
        for (int i = 0; i < filters.length; i++) {
            monitor.setCurrentActivity("Materializing filter " + (i + 1)
                    + "...", -1.0);
            filters[i] = (StreamFilter) ((ClassOption) filterOptions[i]).materializeObject(monitor, repository);
            if (monitor.taskShouldAbort()) {
                return;
            }
            if (filters[i] instanceof OptionHandler) {
                monitor.setCurrentActivity("Preparing filter " + (i + 1)
                        + "...", -1.0);
                ((OptionHandler) filters[i]).prepareForUse(monitor, repository);
                if (monitor.taskShouldAbort()) {
                    return;
                }
            }
        }
        InstanceStream chain = (InstanceStream) getPreparedClassOption(this.streamOption);
        for (int i = 0; i < filters.length; i++) {
            filters[i].setInputStream(chain);
            chain = filters[i];
        }
        this.filterChain = chain;
    }
void moa.streams.MultiFilteredStream.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 115 of file MultiFilteredStream.java.
References moa.streams.MultiFilteredStream.filterChain, and moa.streams.InstanceStream.restart().
{
        this.filterChain.restart();
    }
Member Data Documentation
InstanceStream moa.streams.MultiFilteredStream.filterChain [protected]
Definition at line 58 of file MultiFilteredStream.java.
Referenced by moa.streams.MultiFilteredStream.estimatedRemainingInstances(), moa.streams.MultiFilteredStream.getHeader(), moa.streams.MultiFilteredStream.hasMoreInstances(), moa.streams.MultiFilteredStream.isRestartable(), moa.streams.MultiFilteredStream.nextInstance(), moa.streams.MultiFilteredStream.prepareForUseImpl(), and moa.streams.MultiFilteredStream.restart().
ListOption moa.streams.MultiFilteredStream.filtersOption
Initial value:
 new ListOption("filters", 'f',
            "Filters to apply.", new ClassOption("filter", ' ',
            "Stream filter.", StreamFilter.class, "AddNoiseFilter"),
            new Option[0], ',')
Definition at line 53 of file MultiFilteredStream.java.
Referenced by moa.streams.MultiFilteredStream.prepareForUseImpl().
final long moa.streams.MultiFilteredStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 47 of file MultiFilteredStream.java.
ClassOption moa.streams.MultiFilteredStream.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to filter.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 49 of file MultiFilteredStream.java.
Referenced by moa.streams.MultiFilteredStream.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/MultiFilteredStream.java