MOA: moa.options.ClassOptionWithNames Class Reference
moa.options.ClassOptionWithNames Class Reference
Public Member Functions
ClassOptionWithNames (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String[] classNames)
ClassOptionWithNames (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString, String[] classNames)
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
JComponent getEditComponent ()
Gets the GUI component to edit.
String[] getClassNames ()
Static Public Member Functions
static String objectToCLIString (Object obj, Class<?> requiredType)
static Object cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception
Private Attributes
String[] names
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 21 of file ClassOptionWithNames.java.
Constructor & Destructor Documentation
moa.options.ClassOptionWithNames.ClassOptionWithNames (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String[] classNames)
Definition at line 26 of file ClassOptionWithNames.java.
References moa.options.ClassOptionWithNames.names.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString);
        this.names = classNames;
    }
moa.options.ClassOptionWithNames.ClassOptionWithNames (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString, String[] classNames)
Definition at line 32 of file ClassOptionWithNames.java.
References moa.options.ClassOptionWithNames.names.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString, nullString);
        this.names = classNames;
    }
Member Function Documentation
static Object moa.options.ClassOptionWithNames.cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception [static]
Definition at line 81 of file ClassOptionWithNames.java.
References moa.options.Options.addOption(), moa.options.AbstractClassOption.FILE_PREFIX_STRING, moa.options.AbstractClassOption.INMEM_PREFIX_STRING, moa.options.Options.removeAllOptions(), moa.options.AbstractClassOption.requiredType, and moa.options.Options.setViaCLIString().
Referenced by moa.options.ClassOptionWithNames.setValueViaCLIString().
{
        if (cliString.startsWith(FILE_PREFIX_STRING)) {
            return new File(cliString.substring(FILE_PREFIX_STRING.length()));
        }
        if (cliString.startsWith(INMEM_PREFIX_STRING)) {
            return cliString.substring(INMEM_PREFIX_STRING.length());
        }
        cliString = cliString.trim();
        int firstSpaceIndex = cliString.indexOf(' ', 0);
        String className;
        String classOptions;
        if (firstSpaceIndex > 0) {
            className = cliString.substring(0, firstSpaceIndex);
            classOptions = cliString.substring(firstSpaceIndex + 1, cliString.length());
            classOptions = classOptions.trim();
        } else {
            className = cliString;
            classOptions = "";
        }
        Class<?> classObject;
        try {
            classObject = Class.forName(className);
        } catch (Throwable t1) {
            try {
                // try prepending default package
                classObject = Class.forName(requiredType.getPackage().getName()
                        + "." + className);
            } catch (Throwable t2) {
                try {
                    // try prepending task package
                    classObject = Class.forName(Task.class.getPackage().getName()
                            + "." + className);
                } catch (Throwable t3) {
                    throw new Exception("Class not found: " + className);
                }
            }
        }
        Object classInstance;
        try {
            classInstance = classObject.newInstance();
        } catch (Exception ex) {
            throw new Exception("Problem creating instance of class: "
                    + className, ex);
        }
        if (requiredType.isInstance(classInstance)
                || ((classInstance instanceof Task) && requiredType.isAssignableFrom(((Task) classInstance).getTaskResultType()))) {
            Options options = new Options();
            if (externalOptions != null) {
                for (Option option : externalOptions) {
                    options.addOption(option);
                }
            }
            if (classInstance instanceof OptionHandler) {
                Option[] objectOptions = ((OptionHandler) classInstance).getOptions().getOptionArray();
                for (Option option : objectOptions) {
                    options.addOption(option);
                }
            }
            try {
                options.setViaCLIString(classOptions);
            } catch (Exception ex) {
                throw new Exception("Problem with options to '"
                        + className
                        + "'."
                        + "\n\nValid options for "
                        + className
                        + ":\n"
                        + ((OptionHandler) classInstance).getOptions().getHelpString(), ex);
            } finally {
                options.removeAllOptions(); // clean up listener refs
            }
        } else {
            throw new Exception("Class named '" + className
                    + "' is not an instance of " + requiredType.getName() + ".");
        }
        return classInstance;
    }
String [] moa.options.ClassOptionWithNames.getClassNames ()
Definition at line 165 of file ClassOptionWithNames.java.
References moa.options.ClassOptionWithNames.names.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.editObject().
{
        return this.names;
    }
JComponent moa.options.ClassOptionWithNames.getEditComponent () [virtual]
Gets the GUI component to edit.
Returns:
the component to edit
Implements moa.options.AbstractClassOption.
Definition at line 161 of file ClassOptionWithNames.java.
{
        return new ClassOptionWithNamesEditComponent(this);
    }
String moa.options.ClassOptionWithNames.getValueAsCLIString () [virtual]
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 39 of file ClassOptionWithNames.java.
References moa.options.AbstractClassOption.currentValue, moa.options.AbstractClassOption.nullString, moa.options.ClassOptionWithNames.objectToCLIString(), and moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent().
{
        if ((this.currentValue == null) && (this.nullString != null)) {
            return this.nullString;
        }
        return objectToCLIString(this.currentValue, this.requiredType);
    }
static String moa.options.ClassOptionWithNames.objectToCLIString (Object obj, Class<?> requiredType) [static]
Definition at line 61 of file ClassOptionWithNames.java.
References moa.options.AbstractClassOption.classToCLIString(), moa.options.AbstractClassOption.FILE_PREFIX_STRING, and moa.options.AbstractClassOption.INMEM_PREFIX_STRING.
Referenced by moa.options.ClassOptionWithNames.getValueAsCLIString().
{
        if (obj == null) {
            return "";
        }
        if (obj instanceof File) {
            return (FILE_PREFIX_STRING + ((File) obj).getPath());
        }
        if (obj instanceof String) {
            return (INMEM_PREFIX_STRING + obj);
        }
        String className = classToCLIString(obj.getClass(), requiredType);
        if (obj instanceof OptionHandler) {
            String subOptions = ((OptionHandler) obj).getOptions().getAsCLIString();
            if (subOptions.length() > 0) {
                return (className + " " + subOptions);
            }
        }
        return className;
    }
void moa.options.ClassOptionWithNames.setValueViaCLIString (String s) [virtual]
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 47 of file ClassOptionWithNames.java.
References moa.options.ClassOptionWithNames.cliStringToObject(), moa.options.AbstractClassOption.currentValue, moa.options.AbstractOption.getName(), moa.options.AbstractClassOption.nullString, and moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.applyState().
{
        if ((this.nullString != null)
                && ((s == null) || (s.length() == 0) || s.equals(this.nullString))) {
            this.currentValue = null;
        } else {
            try {
                this.currentValue = cliStringToObject(s, this.requiredType,
                        null);
            } catch (Exception e) {
                throw new IllegalArgumentException("Problems with option: " + getName(), e);
            }
        }
    }
Member Data Documentation
String [] moa.options.ClassOptionWithNames.names [private]
Definition at line 24 of file ClassOptionWithNames.java.
Referenced by moa.options.ClassOptionWithNames.ClassOptionWithNames(), and moa.options.ClassOptionWithNames.getClassNames().
final long moa.options.ClassOptionWithNames.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractClassOption.
Definition at line 23 of file ClassOptionWithNames.java.
The documentation for this class was generated from the following file:
main/java/moa/options/ClassOptionWithNames.java