MOA: moa.gui.visualization.RunOutlierVisualizer Class Reference
moa.gui.visualization.RunOutlierVisualizer Class Reference
Classes
class LogPanelPrintMsg
class MyOutlierNotifier
Public Member Functions
RunOutlierVisualizer (OutlierVisualTab visualPanel, OutlierSetupTab outlierSetupTab)
void run ()
void setWaitWinFull (boolean b)
void redraw ()
void redrawOnResize ()
void stop ()
void setSpeed (int speed)
void actionPerformed (ActionEvent e)
void setPointsVisibility (boolean selected)
void setOutliersVisibility (boolean selected)
void changeCluster (ClusterEvent e)
void exportCSV (String filepath)
void weka ()
Static Public Member Functions
static int getCurrentTimestamp ()
static void pause ()
static void resume ()
Public Attributes
MyBaseOutlierDetector m_outlier [] = new MyBaseOutlierDetector[MAX_ALGORITHMS]
Static Public Attributes
static final int initialPauseInterval = 1000
the pause interval, being read from the gui at startup
Package Attributes
boolean bUseAlgorithm2 = false
int nProcessed
Long m_timePreObjSum [] = new Long[MAX_ALGORITHMS]
int m_timePreObjInterval = 100
Private Member Functions
void updateSettings ()
void MeasuredProcessStreamObj (int idxAlgorithm, Instance newInst)
void processData ()
void UpdateTimePerObj (int idxAlgorithm, double t)
void ShowStatistics ()
boolean CanPause ()
void simulateVisualSpeed ()
void updatePointsWeight ()
boolean CanShowOutliers ()
void drawOutliers ()
void drawOutliers (int idxAlgorithm)
void deleteExpiredEvents (int idxAlgorithm)
void drawEvents ()
void drawEvents (int idxAlgorithm)
void drawPoints ()
void drawPoints (int idxAlgorithm)
void showOutliers (boolean bShow)
void showOutliers (int idxAlgorithm, boolean bShow)
void _redraw ()
void _redrawOnResize ()
void work_pause ()
void Sleep (int ms)
Private Attributes
int m_wait_frequency = 100
factor to control the speed
int m_drawOutliersInterval = 100
int m_redrawInterval = 100
after how many instances do we repaint the streampanel? the GUI becomes very slow with small values
int m_eventsInterval = 20
int m_eventsDecay = 100
int m_MeasureInterval = 1000
boolean bStop = false
int m_pauseInterval
boolean m_bWaitWinFull
final ClusteringStream m_stream0
int m_stream0_decayHorizon
double m_stream0_decay_threshold
double m_stream0_decay_rate
MeasureCollection[] m_measures [] = new MeasureCollection[MAX_ALGORITHMS][]
StreamOutlierPanel m_streampanel [] = new StreamOutlierPanel[MAX_ALGORITHMS]
TreeSet< OutlierEvent > eventBuffer [] = new TreeSet[MAX_ALGORITHMS]
OutlierVisualEvalPanel m_evalPanel
GraphCanvas m_graphcanvas
OutlierVisualTab m_visualPanel
LinkedList< DataPoint > pointBuffer0
final TextViewerPanel m_logPanel
Static Private Attributes
static boolean bWork
static int timestamp
static final int ALGORITHM_1 = 0
static final int ALGORITHM_2 = 1
static final int MAX_ALGORITHMS = 2
Detailed Description
Definition at line 62 of file RunOutlierVisualizer.java.
Constructor & Destructor Documentation
moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer (OutlierVisualTab visualPanel, OutlierSetupTab outlierSetupTab)
Definition at line 197 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.bWork, moa.gui.visualization.RunOutlierVisualizer.eventBuffer, moa.streams.clustering.ClusteringStream.getDecayHorizon(), moa.streams.clustering.ClusteringStream.getDecayThreshold(), moa.gui.outliertab.OutlierVisualTab.getEvalPanel(), moa.gui.outliertab.OutlierVisualTab.getGraphCanvas(), moa.gui.outliertab.OutlierVisualTab.getLeftStreamPanel(), moa.gui.outliertab.OutlierSetupTab.getLogPanel(), moa.gui.outliertab.OutlierSetupTab.getMeasures(), moa.gui.outliertab.OutlierSetupTab.getOutlierer0(), moa.gui.outliertab.OutlierSetupTab.getOutlierer1(), moa.gui.outliertab.OutlierVisualTab.getRightStreamPanel(), moa.gui.outliertab.OutlierSetupTab.getStream0(), moa.options.IntOption.getValue(), moa.gui.visualization.RunOutlierVisualizer.m_evalPanel, moa.gui.visualization.RunOutlierVisualizer.m_graphcanvas, moa.gui.visualization.RunOutlierVisualizer.m_logPanel, moa.gui.visualization.RunOutlierVisualizer.m_measures, moa.gui.visualization.RunOutlierVisualizer.m_outlier, moa.gui.visualization.RunOutlierVisualizer.m_stream0, moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_rate, moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_threshold, moa.gui.visualization.RunOutlierVisualizer.m_stream0_decayHorizon, moa.gui.visualization.RunOutlierVisualizer.m_streampanel, moa.gui.visualization.RunOutlierVisualizer.m_visualPanel, moa.streams.clustering.ClusteringStream.numAttsOption, moa.clusterers.outliers.MyBaseOutlierDetector.outlierNotifier, moa.options.AbstractOptionHandler.prepareForUse(), moa.gui.outliertab.OutlierVisualTab.setDimensionComobBoxes(), moa.gui.visualization.GraphCanvas.setGraph(), moa.gui.visualization.StreamOutlierPanel.setOutlierDetector(), moa.gui.TextViewerPanel.setText(), moa.clusterers.outliers.MyBaseOutlierDetector.SetUserInfo(), moa.options.IntOption.setValue(), moa.gui.visualization.StreamOutlierPanel.setVisualizer(), moa.gui.visualization.RunOutlierVisualizer.timestamp, and moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        m_outlier[ALGORITHM_1] = outlierSetupTab.getOutlierer0();
        m_outlier[ALGORITHM_1].prepareForUse();
        // show algorithm output to log-panel
        m_outlier[ALGORITHM_1].SetUserInfo(false, false, new LogPanelPrintMsg(), 2000);
        m_outlier[ALGORITHM_1].outlierNotifier = new MyOutlierNotifier(ALGORITHM_1);
        m_outlier[ALGORITHM_2] = outlierSetupTab.getOutlierer1();
        bUseAlgorithm2 = (m_outlier[ALGORITHM_2] != null);
        if (bUseAlgorithm2) {
            m_outlier[ALGORITHM_2].prepareForUse();
            // show algorithm output to log-panel
            m_outlier[ALGORITHM_2].SetUserInfo(false, false, new LogPanelPrintMsg(), 2000);
            m_outlier[ALGORITHM_2].outlierNotifier = new MyOutlierNotifier(ALGORITHM_2);
        }
        m_visualPanel = visualPanel;
        m_streampanel[ALGORITHM_1] = visualPanel.getLeftStreamPanel();
        m_streampanel[ALGORITHM_1].setVisualizer(this);
        m_streampanel[ALGORITHM_1].setOutlierDetector(m_outlier[ALGORITHM_1]);
        if (bUseAlgorithm2) {
            m_streampanel[ALGORITHM_2] = visualPanel.getRightStreamPanel();
            m_streampanel[ALGORITHM_2].setVisualizer(this);
            m_streampanel[ALGORITHM_2].setOutlierDetector(m_outlier[ALGORITHM_2]);
        }
        m_logPanel = outlierSetupTab.getLogPanel();
        m_graphcanvas = visualPanel.getGraphCanvas();
        m_evalPanel = visualPanel.getEvalPanel();
        m_stream0 = outlierSetupTab.getStream0();
        m_stream0_decayHorizon = m_stream0.getDecayHorizon();
        m_stream0_decay_threshold = m_stream0.getDecayThreshold();
        m_stream0_decay_rate = (Math.log(1.0/m_stream0_decay_threshold)/Math.log(2)/m_stream0_decayHorizon);
        eventBuffer[ALGORITHM_1] = new TreeSet<OutlierEvent>();
        eventBuffer[ALGORITHM_2] = new TreeSet<OutlierEvent>();
        timestamp = 0;
        bWork = true;
        if (m_stream0 instanceof RandomRBFGeneratorEvents) {
            // ((RandomRBFGeneratorEvents)m_stream0).addClusterChangeListener(this);
        }
        m_stream0.prepareForUse();
        // clear log
        m_logPanel.setText("");
        // init measures
        m_measures[ALGORITHM_1] = outlierSetupTab.getMeasures();
        m_measures[ALGORITHM_2] = outlierSetupTab.getMeasures();
        // show as default process time per object
        m_graphcanvas.setGraph(m_measures[ALGORITHM_1][0], m_measures[ALGORITHM_2][0], 0, 100);
        updateSettings();
        // get those values from the generator
        if (m_stream0 instanceof moa.streams.clustering.FileStream) {
            // manually set last value to be the class
            m_stream0.numAttsOption.setValue(m_stream0.numAttsOption.getValue() - 1);
        }
        int dims = m_stream0.numAttsOption.getValue();
        visualPanel.setDimensionComobBoxes(dims);
    }
Member Function Documentation
void moa.gui.visualization.RunOutlierVisualizer._redraw () [private]
Definition at line 512 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.m_streampanel, and moa.gui.visualization.RunOutlierVisualizer.showOutliers().
Referenced by moa.gui.visualization.RunOutlierVisualizer.redraw().
{
        m_streampanel[ALGORITHM_1].clearPoints();
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].clearPoints();
        drawPoints();
        drawEvents();
        showOutliers(true);
        // drawClusterings();
        m_streampanel[ALGORITHM_1].repaint();
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].repaint();
    }
void moa.gui.visualization.RunOutlierVisualizer._redrawOnResize () [private]
Definition at line 534 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.m_streampanel, and moa.gui.visualization.RunOutlierVisualizer.showOutliers().
Referenced by moa.gui.visualization.RunOutlierVisualizer.redrawOnResize().
{
        m_streampanel[ALGORITHM_1].clearPoints();
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].clearPoints();
        drawPoints();
        drawEvents();
        showOutliers(true);
        drawOutliers();
        m_streampanel[ALGORITHM_1].repaint();
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].repaint();
    }
void moa.gui.visualization.RunOutlierVisualizer.actionPerformed (ActionEvent e)
Definition at line 590 of file RunOutlierVisualizer.java.
{
    }
boolean moa.gui.visualization.RunOutlierVisualizer.CanPause () [private]
Definition at line 399 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_pauseInterval, and moa.gui.visualization.RunOutlierVisualizer.nProcessed.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.run().
{
        if (m_pauseInterval != 0) {
            return (nProcessed % m_pauseInterval == 0);
        }
        return false;
    }
boolean moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers () [private]
Definition at line 427 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_bWaitWinFull, moa.gui.visualization.RunOutlierVisualizer.m_stream0_decayHorizon, and moa.gui.visualization.RunOutlierVisualizer.nProcessed.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), and moa.gui.visualization.RunOutlierVisualizer.showOutliers().
{
        return (!m_bWaitWinFull || (nProcessed >= m_stream0_decayHorizon));
    }
void moa.gui.visualization.RunOutlierVisualizer.changeCluster (ClusterEvent e)
Implements moa.streams.clustering.ClusterEventListener.
Definition at line 606 of file RunOutlierVisualizer.java.
References moa.streams.clustering.ClusterEvent.getMessage(), and moa.streams.clustering.ClusterEvent.getType().
{
        System.out.println(e.getType()+": "+e.getMessage());
    }
void moa.gui.visualization.RunOutlierVisualizer.deleteExpiredEvents (int idxAlgorithm) [private]
Definition at line 443 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.eventBuffer, moa.gui.visualization.RunOutlierVisualizer.m_eventsDecay, moa.gui.visualization.OutlierEvent.timestamp, and moa.gui.visualization.RunOutlierVisualizer.timestamp.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawEvents().
{
        // delete expired events older than m_eventsDecay
        boolean b = true;
        while (b) {
            b = false;
            if (eventBuffer[idxAlgorithm].size() > 0) {
                OutlierEvent ev = eventBuffer[idxAlgorithm].first();
                if (timestamp > ev.timestamp + m_eventsDecay) {
                    eventBuffer[idxAlgorithm].remove(ev);
                    b = true;
                }
            }
        }
    }
void moa.gui.visualization.RunOutlierVisualizer.drawEvents (int idxAlgorithm) [private]
Definition at line 464 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.visualization.StreamOutlierPanel.clearEvents(), moa.gui.visualization.RunOutlierVisualizer.deleteExpiredEvents(), moa.gui.visualization.StreamOutlierPanel.drawEvent(), moa.gui.visualization.RunOutlierVisualizer.eventBuffer, and moa.gui.visualization.RunOutlierVisualizer.m_streampanel.
{
        m_streampanel[idxAlgorithm].clearEvents();
        // System.out.println("Alg " + idxAlgorithm + " events " + eventBuffer[idxAlgorithm].size());
        deleteExpiredEvents(idxAlgorithm);
        if (CanShowOutliers()) {
            for (OutlierEvent ev : eventBuffer[idxAlgorithm]) {
                m_streampanel[idxAlgorithm].drawEvent(ev, false);
            }
        }
        //m_streampanel[idxAlgorithm].RedrawPointLayer();
    }
void moa.gui.visualization.RunOutlierVisualizer.drawEvents () [private]
Definition at line 458 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, and moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), and moa.gui.visualization.RunOutlierVisualizer.processData().
{
        drawEvents(ALGORITHM_1);
        if (bUseAlgorithm2)
            drawEvents(ALGORITHM_2);
    }
void moa.gui.visualization.RunOutlierVisualizer.drawOutliers (int idxAlgorithm) [private]
Definition at line 437 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.getOutliersResult(), moa.gui.visualization.RunOutlierVisualizer.m_outlier, and moa.gui.visualization.RunOutlierVisualizer.m_streampanel.
{
        Vector<MyBaseOutlierDetector.Outlier> outliers = m_outlier[idxAlgorithm].getOutliersResult();
        if ((outliers != null) && (outliers.size() > 0) && CanShowOutliers())
            m_streampanel[idxAlgorithm].drawOutliers(outliers, Color.RED);
    }
void moa.gui.visualization.RunOutlierVisualizer.drawOutliers () [private]
Definition at line 431 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, and moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.run().
{
        drawOutliers(ALGORITHM_1);
        if (bUseAlgorithm2)
            drawOutliers(ALGORITHM_2);
    }
void moa.gui.visualization.RunOutlierVisualizer.drawPoints (int idxAlgorithm) [private]
Definition at line 486 of file RunOutlierVisualizer.java.
References moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.StreamOutlierPanel.drawPoint(), moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_rate, moa.gui.visualization.RunOutlierVisualizer.m_streampanel, moa.gui.visualization.RunOutlierVisualizer.pointBuffer0, moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer(), and moa.gui.visualization.RunOutlierVisualizer.timestamp.
{
        m_streampanel[idxAlgorithm].clearPoints();
        for (DataPoint point0 : pointBuffer0) {
            point0.updateWeight(timestamp, m_stream0_decay_rate);
            m_streampanel[idxAlgorithm].drawPoint(point0, true, false);
        }
        m_streampanel[idxAlgorithm].RedrawPointLayer();
    }
void moa.gui.visualization.RunOutlierVisualizer.drawPoints () [private]
Definition at line 480 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, and moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), and moa.gui.visualization.RunOutlierVisualizer._redrawOnResize().
{
        drawPoints(ALGORITHM_1);
        if (bUseAlgorithm2)
            drawPoints(ALGORITHM_2);
    }
void moa.gui.visualization.RunOutlierVisualizer.exportCSV (String filepath)
Definition at line 610 of file RunOutlierVisualizer.java.
{
        PrintWriter out = null;
        try {
            if(!filepath.endsWith(".csv"))
                filepath+=".csv";
            out = new PrintWriter(new BufferedWriter(new FileWriter(filepath)));
            out.write("\n");
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(RunVisualizer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }
static int moa.gui.visualization.RunOutlierVisualizer.getCurrentTimestamp () [static]
Definition at line 555 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.timestamp.
{
        return timestamp;
    }
void moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj (int idxAlgorithm, Instance newInst) [private]
Definition at line 304 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_outlier, moa.gui.visualization.RunOutlierVisualizer.m_timePreObjInterval, moa.gui.visualization.RunOutlierVisualizer.nProcessed, moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), and moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj().
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData().
{
        m_outlier[idxAlgorithm].processNewInstanceImpl(newInst);
        if (nProcessed % m_timePreObjInterval == 0) {
            UpdateTimePerObj(idxAlgorithm, m_outlier[idxAlgorithm].getTimePerObj());
        }
    }
static void moa.gui.visualization.RunOutlierVisualizer.pause () [static]
Definition at line 571 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.bWork.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
{
        bWork = false;
    }
void moa.gui.visualization.RunOutlierVisualizer.processData () [private]
Definition at line 312 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.StreamOutlierPanel.applyDrawDecay(), moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.CanPause(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.StreamOutlierPanel.drawPoint(), moa.streams.InstanceStream.hasMoreInstances(), moa.gui.visualization.RunOutlierVisualizer.m_redrawInterval, moa.gui.visualization.RunOutlierVisualizer.m_stream0, moa.gui.visualization.RunOutlierVisualizer.m_stream0_decayHorizon, moa.gui.visualization.RunOutlierVisualizer.m_streampanel, moa.gui.visualization.RunOutlierVisualizer.m_visualPanel, moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj(), moa.streams.InstanceStream.nextInstance(), moa.gui.visualization.RunOutlierVisualizer.nProcessed, moa.gui.visualization.RunOutlierVisualizer.pause(), moa.gui.visualization.RunOutlierVisualizer.pointBuffer0, moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer(), moa.gui.outliertab.OutlierVisualTab.setProcessedPointsCounter(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), moa.gui.visualization.RunOutlierVisualizer.simulateVisualSpeed(), moa.gui.visualization.RunOutlierVisualizer.timestamp, and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
Referenced by moa.gui.visualization.RunOutlierVisualizer.run().
{
        if (m_stream0.hasMoreInstances()) {
            timestamp++;
            nProcessed++;
            if (timestamp % 100 == 0)
                m_visualPanel.setProcessedPointsCounter(timestamp);
            Instance nextStreamObj0 = m_stream0.nextInstance();
            DataPoint point0 = new DataPoint(nextStreamObj0,timestamp);
            pointBuffer0.add(point0);
            while (pointBuffer0.size() > m_stream0_decayHorizon) {
                pointBuffer0.removeFirst();
            }
            MeasuredProcessStreamObj(ALGORITHM_1, nextStreamObj0);
            if (bUseAlgorithm2)
                MeasuredProcessStreamObj(ALGORITHM_2, nextStreamObj0);
            // draw new point
            m_streampanel[ALGORITHM_1].drawPoint(point0, false, false);
            if (bUseAlgorithm2)
                m_streampanel[ALGORITHM_2].drawPoint(point0, false, false);
            // apply decay at points
            if (nProcessed % m_redrawInterval == 0) {
                float f;
                if (m_stream0_decayHorizon <= m_redrawInterval)
                    f = 1;
                else
                    f = ((float)m_redrawInterval) / ((float)m_stream0_decayHorizon);
                m_streampanel[ALGORITHM_1].applyDrawDecay(f, false);
                if (bUseAlgorithm2)
                    m_streampanel[ALGORITHM_2].applyDrawDecay(f, false);
            }
            // draw events
            //if (nProcessed % m_eventsInterval == 0) {
            drawEvents();
            // redraw point layer
            m_streampanel[ALGORITHM_1].RedrawPointLayer();
            if (bUseAlgorithm2)
                m_streampanel[ALGORITHM_2].RedrawPointLayer();
            /*if (nProcessed % m_drawOutliersInterval == 0)
                drawOutliers();*/
            if (CanPause()) {
                // automatically pause each m_pauseInterval objects
                //updatePointsWeight();
                showOutliers(true);
                drawOutliers();
                m_visualPanel.toggleVisualizer(true);
            }
        } else {
            System.out.println("DONE");
            pause();
            return;
        }
        simulateVisualSpeed(); // simulate visualization speed
    }
void moa.gui.visualization.RunOutlierVisualizer.redraw ()
Definition at line 528 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer._redraw().
{
        synchronized(this) {
            _redraw();
        }
    }
void moa.gui.visualization.RunOutlierVisualizer.redrawOnResize ()
Definition at line 549 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer._redrawOnResize().
Referenced by moa.gui.visualization.StreamOutlierPanel.componentResized().
{
        synchronized(this) {
            _redrawOnResize();
        }
    }
static void moa.gui.visualization.RunOutlierVisualizer.resume () [static]
Definition at line 575 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.bWork.
Referenced by moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
{
        bWork = true;
    }
void moa.gui.visualization.RunOutlierVisualizer.run ()
Definition at line 271 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bStop, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.bWork, moa.gui.visualization.RunOutlierVisualizer.CanPause(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.m_streampanel, moa.gui.visualization.RunOutlierVisualizer.m_timePreObjSum, moa.gui.visualization.RunOutlierVisualizer.nProcessed, moa.gui.visualization.RunOutlierVisualizer.pointBuffer0, moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.StreamOutlierPanel.setHighlightedOutlierPanel(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), moa.gui.visualization.RunOutlierVisualizer.updateSettings(), and moa.gui.visualization.RunOutlierVisualizer.work_pause().
                      {
        nProcessed = 0;
        m_timePreObjSum[ALGORITHM_1] = 0L;
        m_timePreObjSum[ALGORITHM_2] = 0L;
        pointBuffer0 = new LinkedList<DataPoint>();
        while (!bStop) {
            if (!bWork || CanPause()) {
                updateSettings();
                drawOutliers();
                showOutliers(true);
                m_streampanel[ALGORITHM_1].repaint();
                if (bUseAlgorithm2)
                    m_streampanel[ALGORITHM_2].repaint();
                //redraw();
                work_pause();
                if (bStop) break;
                updateSettings();
                showOutliers(false);
                m_streampanel[ALGORITHM_1].setHighlightedOutlierPanel(null);
                if (bUseAlgorithm2)
                    m_streampanel[ALGORITHM_2].setHighlightedOutlierPanel(null);
            }
            synchronized(this) {
                processData();
            }
        }
    }
void moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility (boolean selected)
Definition at line 599 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.m_streampanel, and moa.gui.visualization.StreamOutlierPanel.setOutliersVisibility().
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        m_streampanel[ALGORITHM_1].setOutliersVisibility(selected);
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].setOutliersVisibility(selected);
    }
void moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility (boolean selected)
Definition at line 593 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.m_streampanel, and moa.gui.visualization.StreamOutlierPanel.setPointsVisibility().
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        m_streampanel[ALGORITHM_1].setPointsVisibility(selected);
        if (bUseAlgorithm2)
            m_streampanel[ALGORITHM_2].setPointsVisibility(selected);
    }
void moa.gui.visualization.RunOutlierVisualizer.setSpeed (int speed)
Definition at line 585 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_wait_frequency.
{
        m_wait_frequency = speed;
    }
void moa.gui.visualization.RunOutlierVisualizer.setWaitWinFull (boolean b)
Definition at line 423 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_bWaitWinFull.
{
        m_bWaitWinFull = b;
    }
void moa.gui.visualization.RunOutlierVisualizer.showOutliers (int idxAlgorithm, boolean bShow) [private]
Definition at line 503 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.bWork, moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.outliertab.OutlierVisualTab.isEnabledDrawOutliers(), moa.gui.visualization.RunOutlierVisualizer.m_streampanel, moa.gui.visualization.RunOutlierVisualizer.m_visualPanel, and moa.gui.visualization.StreamOutlierPanel.setOutliersVisibility().
{
        if (!bWork && m_visualPanel.isEnabledDrawOutliers() && CanShowOutliers()) {
            m_streampanel[idxAlgorithm].setOutliersVisibility(bShow);
        }
        else {
            m_streampanel[idxAlgorithm].setOutliersVisibility(false);
        }
    }
void moa.gui.visualization.RunOutlierVisualizer.showOutliers (boolean bShow) [private]
Definition at line 497 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, and moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.run().
{
        showOutliers(ALGORITHM_1, bShow);
        if (bUseAlgorithm2)
            showOutliers(ALGORITHM_2, bShow);
    }
void moa.gui.visualization.RunOutlierVisualizer.ShowStatistics () [private]
Definition at line 390 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1, moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2, moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2, moa.gui.visualization.RunOutlierVisualizer.m_logPanel, and moa.gui.visualization.RunOutlierVisualizer.m_outlier.
Referenced by moa.gui.visualization.RunOutlierVisualizer.stop().
{
        synchronized(this) {
            m_logPanel.addText(" ");
            m_logPanel.addText("Algorithm1 " + m_outlier[ALGORITHM_1].getStatistics());
            if (bUseAlgorithm2)
                m_logPanel.addText("Algorithm2 " + m_outlier[ALGORITHM_2].getStatistics());
        }
    }
void moa.gui.visualization.RunOutlierVisualizer.simulateVisualSpeed () [private]
Definition at line 406 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_wait_frequency, and moa.gui.visualization.RunOutlierVisualizer.Sleep().
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData().
{
        int iMaxWaitFreq = 100;
        int iSleepMS = iMaxWaitFreq - m_wait_frequency;
        if (iSleepMS < 0) iSleepMS = 0;
        if (iSleepMS > iMaxWaitFreq) iSleepMS = iMaxWaitFreq;
        //System.out.println("iSleepMS="+iSleepMS + ", m_wait_frequency="+m_wait_frequency);
        if (iSleepMS > 0)
            Sleep(iSleepMS);
    }
void moa.gui.visualization.RunOutlierVisualizer.Sleep (int ms) [private]
Definition at line 565 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.simulateVisualSpeed(), and moa.gui.visualization.RunOutlierVisualizer.work_pause().
{
        try {
            Thread.sleep(ms);
        } catch (InterruptedException ex) { }
    }
void moa.gui.visualization.RunOutlierVisualizer.stop ()
Definition at line 579 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.bStop, moa.gui.visualization.RunOutlierVisualizer.bWork, and moa.gui.visualization.RunOutlierVisualizer.ShowStatistics().
Referenced by moa.gui.outliertab.OutlierVisualTab.stopVisualizer().
                      {
        bWork = false;
        bStop = true;
        ShowStatistics();
    }
void moa.gui.visualization.RunOutlierVisualizer.updatePointsWeight () [private]
Definition at line 418 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_rate, moa.gui.visualization.RunOutlierVisualizer.pointBuffer0, and moa.gui.visualization.RunOutlierVisualizer.timestamp.
{
        for(DataPoint p : pointBuffer0)
            p.updateWeight(timestamp, m_stream0_decay_rate);
    }
void moa.gui.visualization.RunOutlierVisualizer.updateSettings () [private]
Definition at line 262 of file RunOutlierVisualizer.java.
References moa.gui.outliertab.OutlierVisualTab.getOutliersVisibility(), moa.gui.outliertab.OutlierVisualTab.getPauseInterval(), moa.gui.outliertab.OutlierVisualTab.getPointVisibility(), moa.gui.outliertab.OutlierVisualTab.GetSpeed(), moa.gui.outliertab.OutlierVisualTab.getWaitWinFull(), moa.gui.visualization.RunOutlierVisualizer.m_bWaitWinFull, moa.gui.visualization.RunOutlierVisualizer.m_pauseInterval, moa.gui.visualization.RunOutlierVisualizer.m_visualPanel, moa.gui.visualization.RunOutlierVisualizer.m_wait_frequency, moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), and moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility().
Referenced by moa.gui.visualization.RunOutlierVisualizer.run(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        m_pauseInterval = m_visualPanel.getPauseInterval();
        m_wait_frequency = m_visualPanel.GetSpeed();
        setPointsVisibility(m_visualPanel.getPointVisibility());
        setOutliersVisibility(m_visualPanel.getOutliersVisibility());
        m_bWaitWinFull = m_visualPanel.getWaitWinFull();
    }
void moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj (int idxAlgorithm, double t) [private]
Definition at line 379 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), moa.evaluation.OutlierPerformance.addTimePerObject(), moa.gui.visualization.RunOutlierVisualizer.m_graphcanvas, moa.gui.visualization.RunOutlierVisualizer.m_logPanel, moa.gui.visualization.RunOutlierVisualizer.m_measures, and moa.gui.visualization.GraphCanvas.updateCanvas().
Referenced by moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj().
{
        double ms = t / (1000.0 * 1000.0);
        OutlierPerformance op = (OutlierPerformance) m_measures[idxAlgorithm][0];
        op.addTimePerObject(ms);
        //m_evalPanel.update();
        m_graphcanvas.updateCanvas();
        m_logPanel.addText("Algorithm " + idxAlgorithm + ", process time per object (ms): " + String.format("%.3f", ms));
    }
void moa.gui.visualization.RunOutlierVisualizer.weka ()
Definition at line 625 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), moa.cluster.Clustering.get(), moa.cluster.Cluster.getCenter(), moa.cluster.Cluster.getWeight(), moa.gui.visualization.RunOutlierVisualizer.m_logPanel, and moa.cluster.Clustering.size().
                       {
        try{
            Class.forName("weka.gui.Logger");
        }
        catch (Exception e){
            m_logPanel.addText("Please add weka.jar to the classpath to use the Weka explorer.");
            return;
        }
        Clustering wekaClustering;
        wekaClustering = null;
        if(wekaClustering == null || wekaClustering.size()==0){
            m_logPanel.addText("Empty Clustering");
            return;
        }
        int dims = wekaClustering.get(0).getCenter().length;
        FastVector attributes = new FastVector();
        for(int i = 0; i < dims; i++)
                attributes.addElement( new Attribute("att" + i) );
        Instances instances = new Instances("trainset",attributes,0);
        for(int c = 0; c < wekaClustering.size(); c++){
            Cluster cluster = wekaClustering.get(c);
            Instance inst = new DenseInstance(cluster.getWeight(), cluster.getCenter());
            inst.setDataset(instances);
            instances.add(inst);
        }
        WekaExplorer explorer = new WekaExplorer(instances);
    }
void moa.gui.visualization.RunOutlierVisualizer.work_pause () [private]
Definition at line 559 of file RunOutlierVisualizer.java.
References moa.gui.visualization.RunOutlierVisualizer.bStop, moa.gui.visualization.RunOutlierVisualizer.bWork, and moa.gui.visualization.RunOutlierVisualizer.Sleep().
Referenced by moa.gui.visualization.RunOutlierVisualizer.run().
{
        while(!bWork && !bStop){
            Sleep(200);
       }
    }
Member Data Documentation
final int moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_1 = 0 [static, private]
Definition at line 110 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), and moa.gui.visualization.RunOutlierVisualizer.ShowStatistics().
final int moa.gui.visualization.RunOutlierVisualizer.ALGORITHM_2 = 1 [static, private]
Definition at line 111 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), and moa.gui.visualization.RunOutlierVisualizer.ShowStatistics().
boolean moa.gui.visualization.RunOutlierVisualizer.bStop = false [private]
Definition at line 84 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.stop(), and moa.gui.visualization.RunOutlierVisualizer.work_pause().
boolean moa.gui.visualization.RunOutlierVisualizer.bUseAlgorithm2 = false [package]
Definition at line 114 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), and moa.gui.visualization.RunOutlierVisualizer.ShowStatistics().
boolean moa.gui.visualization.RunOutlierVisualizer.bWork [static, private]
Definition at line 83 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.pause(), moa.gui.visualization.RunOutlierVisualizer.resume(), moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), moa.gui.visualization.RunOutlierVisualizer.stop(), and moa.gui.visualization.RunOutlierVisualizer.work_pause().
TreeSet<OutlierEvent> moa.gui.visualization.RunOutlierVisualizer.eventBuffer[] = new TreeSet[MAX_ALGORITHMS] [private]
Definition at line 125 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.deleteExpiredEvents(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.MyOutlierNotifier.OnInlier(), moa.gui.visualization.RunOutlierVisualizer.MyOutlierNotifier.OnOutlier(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
final int moa.gui.visualization.RunOutlierVisualizer.initialPauseInterval = 1000 [static]
the pause interval, being read from the gui at startup
Definition at line 64 of file RunOutlierVisualizer.java.
boolean moa.gui.visualization.RunOutlierVisualizer.m_bWaitWinFull [private]
Definition at line 92 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.visualization.RunOutlierVisualizer.setWaitWinFull(), and moa.gui.visualization.RunOutlierVisualizer.updateSettings().
int moa.gui.visualization.RunOutlierVisualizer.m_drawOutliersInterval = 100 [private]
Definition at line 69 of file RunOutlierVisualizer.java.
OutlierVisualEvalPanel moa.gui.visualization.RunOutlierVisualizer.m_evalPanel [private]
Definition at line 128 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
int moa.gui.visualization.RunOutlierVisualizer.m_eventsDecay = 100 [private]
Definition at line 77 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.deleteExpiredEvents().
int moa.gui.visualization.RunOutlierVisualizer.m_eventsInterval = 20 [private]
Definition at line 76 of file RunOutlierVisualizer.java.
GraphCanvas moa.gui.visualization.RunOutlierVisualizer.m_graphcanvas [private]
Definition at line 131 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj().
final TextViewerPanel moa.gui.visualization.RunOutlierVisualizer.m_logPanel [private]
Definition at line 146 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.print(), moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.printf(), moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.println(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.ShowStatistics(), moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj(), and moa.gui.visualization.RunOutlierVisualizer.weka().
int moa.gui.visualization.RunOutlierVisualizer.m_MeasureInterval = 1000 [private]
Definition at line 80 of file RunOutlierVisualizer.java.
MeasureCollection [] moa.gui.visualization.RunOutlierVisualizer.m_measures[] = new MeasureCollection[MAX_ALGORITHMS][] [private]
Definition at line 120 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunOutlierVisualizer.UpdateTimePerObj().
MyBaseOutlierDetector moa.gui.visualization.RunOutlierVisualizer.m_outlier[] = new MyBaseOutlierDetector[MAX_ALGORITHMS]
Definition at line 117 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunOutlierVisualizer.ShowStatistics().
int moa.gui.visualization.RunOutlierVisualizer.m_pauseInterval [private]
Definition at line 90 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.CanPause(), and moa.gui.visualization.RunOutlierVisualizer.updateSettings().
int moa.gui.visualization.RunOutlierVisualizer.m_redrawInterval = 100 [private]
after how many instances do we repaint the streampanel? the GUI becomes very slow with small values
Definition at line 74 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData().
final ClusteringStream moa.gui.visualization.RunOutlierVisualizer.m_stream0 [private]
Definition at line 95 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
double moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_rate [private]
Definition at line 108 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunOutlierVisualizer.updatePointsWeight().
double moa.gui.visualization.RunOutlierVisualizer.m_stream0_decay_threshold [private]
Definition at line 103 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
int moa.gui.visualization.RunOutlierVisualizer.m_stream0_decayHorizon [private]
Definition at line 100 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
StreamOutlierPanel moa.gui.visualization.RunOutlierVisualizer.m_streampanel[] = new StreamOutlierPanel[MAX_ALGORITHMS] [private]
Definition at line 123 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), moa.gui.visualization.RunOutlierVisualizer.drawEvents(), moa.gui.visualization.RunOutlierVisualizer.drawOutliers(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.run(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility(), and moa.gui.visualization.RunOutlierVisualizer.showOutliers().
int moa.gui.visualization.RunOutlierVisualizer.m_timePreObjInterval = 100 [package]
Definition at line 143 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj().
Long moa.gui.visualization.RunOutlierVisualizer.m_timePreObjSum[] = new Long[MAX_ALGORITHMS] [package]
Definition at line 142 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.run().
OutlierVisualTab moa.gui.visualization.RunOutlierVisualizer.m_visualPanel [private]
Definition at line 134 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunOutlierVisualizer.showOutliers(), and moa.gui.visualization.RunOutlierVisualizer.updateSettings().
int moa.gui.visualization.RunOutlierVisualizer.m_wait_frequency = 100 [private]
factor to control the speed
Definition at line 67 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.setSpeed(), moa.gui.visualization.RunOutlierVisualizer.simulateVisualSpeed(), and moa.gui.visualization.RunOutlierVisualizer.updateSettings().
final int moa.gui.visualization.RunOutlierVisualizer.MAX_ALGORITHMS = 2 [static, private]
Definition at line 112 of file RunOutlierVisualizer.java.
int moa.gui.visualization.RunOutlierVisualizer.nProcessed [package]
Definition at line 141 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.CanPause(), moa.gui.visualization.RunOutlierVisualizer.CanShowOutliers(), moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj(), moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.visualization.RunOutlierVisualizer.run().
LinkedList<DataPoint> moa.gui.visualization.RunOutlierVisualizer.pointBuffer0 [private]
Definition at line 137 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.run(), and moa.gui.visualization.RunOutlierVisualizer.updatePointsWeight().
int moa.gui.visualization.RunOutlierVisualizer.timestamp [static, private]
Definition at line 87 of file RunOutlierVisualizer.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.deleteExpiredEvents(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), moa.gui.visualization.RunOutlierVisualizer.getCurrentTimestamp(), moa.gui.visualization.RunOutlierVisualizer.MyOutlierNotifier.OnInlier(), moa.gui.visualization.RunOutlierVisualizer.MyOutlierNotifier.OnOutlier(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), and moa.gui.visualization.RunOutlierVisualizer.updatePointsWeight().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/RunOutlierVisualizer.java