MOA: moa.tasks.CacheShuffledStream Class Reference
moa.tasks.CacheShuffledStream Class Reference
Task for storing and shuffling examples in memory.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption streamOption
IntOption maximumCacheSizeOption
IntOption shuffleRandomSeedOption
Protected Member Functions
Object doTaskImpl (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for storing and shuffling examples in memory.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 37 of file CacheShuffledStream.java.
Member Function Documentation
Object moa.tasks.CacheShuffledStream.doTaskImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask so all its extensions only need to implement doTaskImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.AbstractTask.
Definition at line 59 of file CacheShuffledStream.java.
References moa.streams.InstanceStream.estimatedRemainingInstances(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.hasMoreInstances(), moa.tasks.CacheShuffledStream.maximumCacheSizeOption, moa.streams.InstanceStream.nextInstance(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.CacheShuffledStream.shuffleRandomSeedOption, moa.tasks.CacheShuffledStream.streamOption, and moa.tasks.TaskMonitor.taskShouldAbort().
{
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        Instances cache = new Instances(stream.getHeader(), 0);
        monitor.setCurrentActivity("Caching instances...", -1.0);
        while ((cache.numInstances() < this.maximumCacheSizeOption.getValue())
                && stream.hasMoreInstances()) {
            cache.add(stream.nextInstance());
            if (cache.numInstances()
                    % MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                long maxRemaining = this.maximumCacheSizeOption.getValue()
                        - cache.numInstances();
                if ((estimatedRemainingInstances < 0)
                        || (maxRemaining < estimatedRemainingInstances)) {
                    estimatedRemainingInstances = maxRemaining;
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) cache.numInstances()
                        / (double) (cache.numInstances() + estimatedRemainingInstances));
            }
        }
        monitor.setCurrentActivity("Shuffling instances...", -1.0);
        cache.randomize(new Random(this.shuffleRandomSeedOption.getValue()));
        return new CachedInstancesStream(cache);
    }
String moa.tasks.CacheShuffledStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 40 of file CacheShuffledStream.java.
{
        return "Stores and shuffles examples in memory.";
    }
Class<?> moa.tasks.CacheShuffledStream.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 88 of file CacheShuffledStream.java.
{
        return CachedInstancesStream.class;
    }
Member Data Documentation
IntOption moa.tasks.CacheShuffledStream.maximumCacheSizeOption
Initial value:
 new IntOption("maximumCacheSize",
            'm', "Maximum number of instances to cache.", 1000000, 1,
            Integer.MAX_VALUE)
Definition at line 50 of file CacheShuffledStream.java.
Referenced by moa.tasks.CacheShuffledStream.doTaskImpl().
final long moa.tasks.CacheShuffledStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 44 of file CacheShuffledStream.java.
IntOption moa.tasks.CacheShuffledStream.shuffleRandomSeedOption
Initial value:
 new IntOption(
            "shuffleRandomSeed", 'r',
            "Seed for random shuffling of instances.", 1)
Definition at line 54 of file CacheShuffledStream.java.
Referenced by moa.tasks.CacheShuffledStream.doTaskImpl().
ClassOption moa.tasks.CacheShuffledStream.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to cache and shuffle.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 46 of file CacheShuffledStream.java.
Referenced by moa.tasks.CacheShuffledStream.doTaskImpl().
The documentation for this class was generated from the following file:
main/java/moa/tasks/CacheShuffledStream.java