MOA: moa.classifiers.bayes.NaiveBayesMultinomial Class Reference
moa.classifiers.bayes.NaiveBayesMultinomial Class Reference
Class for building and using a multinomial Naive Bayes classifier.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains the classifier with the given instance.
double[] getVotesForInstance (Instance instance)
Calculates the class membership probabilities for the given test instance.
double totalSize (Instance instance)
void getModelDescription (StringBuilder result, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Public Attributes
FloatOption laplaceCorrectionOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
double[] m_classTotals
sum of weight_of_instance * word_count_of_instance for each class
Instances m_headerInfo
copy of header information for use in toString method
int m_numClasses
number of class values
double[] m_probOfClass
the probability of a class (i.e.
DoubleVector[] m_wordTotalForClass
probability that a word (w) exists in a class (H) (i.e.
boolean reset = false
Static Private Attributes
static final long serialVersionUID = -7204398796974263187L
for serialization
Detailed Description
Class for building and using a multinomial Naive Bayes classifier.
Performs text classic bayesian prediction while making naive assumption that all inputs are independent. For more information see,
Andrew Mccallum, Kamal Nigam: A Comparison of Event Models for Naive Bayes Text Classification. In: AAAI-98 Workshop on 'Learning for Text Categorization', 1998.
The core equation for this classifier:
P[Ci|D] = (P[D|Ci] x P[Ci]) / P[D] (Bayes rule)
where Ci is class i and D is a document.
Incremental version of the algorithm.
* BibTeX:
 &#64;inproceedings{Mccallum1998,
    author = {Andrew Mccallum and Kamal Nigam},
    booktitle = {AAAI-98 Workshop on 'Learning for Text Categorization'},
    title = {A Comparison of Event Models for Naive Bayes Text Classification},
    year = {1998}
 }
Definition at line 56 of file NaiveBayesMultinomial.java.
Member Function Documentation
void moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 214 of file NaiveBayesMultinomial.java.
References moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.bayes.NaiveBayesMultinomial.laplaceCorrectionOption, moa.classifiers.bayes.NaiveBayesMultinomial.m_classTotals, moa.classifiers.bayes.NaiveBayesMultinomial.m_headerInfo, moa.classifiers.bayes.NaiveBayesMultinomial.m_numClasses, moa.classifiers.bayes.NaiveBayesMultinomial.m_probOfClass, and moa.classifiers.bayes.NaiveBayesMultinomial.m_wordTotalForClass.
{
        StringUtils.appendIndented(result, indent, "xxx MNB1 xxx\n\n");
        result.append("The independent probability of a class\n");
        result.append("--------------------------------------\n");
        for (int c = 0; c < m_numClasses; c++) {
            result.append(m_headerInfo.classAttribute().value(c)).append("\t").
                    append(Double.toString(m_probOfClass[c])).append("\n");
        }
        result.append("\nThe probability of a word given the class\n");
        result.append("-----------------------------------------\n\t");
        for (int c = 0; c < m_numClasses; c++) {
            result.append(m_headerInfo.classAttribute().value(c)).append("\t");
        }
        result.append("\n");
        for (int w = 0; w < m_headerInfo.numAttributes(); w++) {
            if (w == m_headerInfo.classIndex()) {
                continue;
            }
            result.append(m_headerInfo.attribute(w).name()).append("\t");
            for (int c = 0; c < m_numClasses; c++) {
                double value = m_wordTotalForClass[c].getValue(w);
                if (value == 0){
                    value = this.laplaceCorrectionOption.getValue();
                }
                result.append(value / m_classTotals[c]).append("\t");
            }
            result.append("\n");
        }
        StringUtils.appendNewline(result);
    }
Measurement [] moa.classifiers.bayes.NaiveBayesMultinomial.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 209 of file NaiveBayesMultinomial.java.
{
        return null;
    }
String moa.classifiers.bayes.NaiveBayesMultinomial.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 68 of file NaiveBayesMultinomial.java.
{
        return "AMultinomial Naive Bayes classifier: performs classic bayesian prediction while making naive assumption that all inputs are independent.";
    }
double [] moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance (Instance instance)
Calculates the class membership probabilities for the given test instance.
Parameters:
instance the instance to be classified
Returns:
predicted class probability distribution
Implements moa.classifiers.Classifier.
Definition at line 161 of file NaiveBayesMultinomial.java.
References moa.options.FloatOption.getValue(), moa.core.DoubleVector.getValue(), moa.classifiers.bayes.NaiveBayesMultinomial.laplaceCorrectionOption, moa.classifiers.bayes.NaiveBayesMultinomial.m_classTotals, moa.classifiers.bayes.NaiveBayesMultinomial.m_numClasses, moa.classifiers.bayes.NaiveBayesMultinomial.m_probOfClass, moa.classifiers.bayes.NaiveBayesMultinomial.m_wordTotalForClass, moa.classifiers.bayes.NaiveBayesMultinomial.reset, and moa.classifiers.bayes.NaiveBayesMultinomial.totalSize().
{
        if (this.reset == true) {
            return new double[2];
        }
        double[] probOfClassGivenDoc = new double[m_numClasses];
        double totalSize = totalSize(instance);
        for (int i = 0; i < m_numClasses; i++) {
            probOfClassGivenDoc[i] = Math.log(m_probOfClass[i]) - totalSize * Math.log(m_classTotals[i]);
        }
        for (int i = 0; i < instance.numValues(); i++) {
            int index = instance.index(i);
            if (index == instance.classIndex() || instance.isMissing(i)) {
                continue;
            }
            double wordCount = instance.valueSparse(i);
            for (int c = 0; c < m_numClasses; c++) {
                double value = m_wordTotalForClass[c].getValue(index);
                probOfClassGivenDoc[c] += wordCount * Math.log(value == 0 ? this.laplaceCorrectionOption.getValue() : value );
            }
        }
        return Utils.logs2probs(probOfClassGivenDoc);
    }
boolean moa.classifiers.bayes.NaiveBayesMultinomial.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 252 of file NaiveBayesMultinomial.java.
{
        return false;
    }
void moa.classifiers.bayes.NaiveBayesMultinomial.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 101 of file NaiveBayesMultinomial.java.
References moa.classifiers.bayes.NaiveBayesMultinomial.reset.
{
        this.reset = true;
    }
double moa.classifiers.bayes.NaiveBayesMultinomial.totalSize (Instance instance)
Definition at line 189 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
{
        int classIndex = instance.classIndex();
        double total = 0.0;
        for (int i = 0; i < instance.numValues(); i++) {
            int index = instance.index(i);
            if (index == classIndex || instance.isMissing(i)) {
                continue;
            }
            double count = instance.valueSparse(i);
            if (count >= 0) {
                total += count;
            } else {
                //throw new Exception("Numeric attribute value is not >= 0. " + i + " " + index + " " +
                //          instance.valueSparse(i) + " " + " " + instance);
            }
        }
        return total;
    }
void moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl (Instance inst) [virtual]
Trains the classifier with the given instance.
Parameters:
instance the new training instance to include in the model
Implements moa.classifiers.AbstractClassifier.
Definition at line 111 of file NaiveBayesMultinomial.java.
References moa.core.DoubleVector.addToValue(), moa.options.FloatOption.getValue(), moa.classifiers.bayes.NaiveBayesMultinomial.laplaceCorrectionOption, moa.classifiers.bayes.NaiveBayesMultinomial.m_classTotals, moa.classifiers.bayes.NaiveBayesMultinomial.m_numClasses, moa.classifiers.bayes.NaiveBayesMultinomial.m_probOfClass, moa.classifiers.bayes.NaiveBayesMultinomial.m_wordTotalForClass, moa.classifiers.bayes.NaiveBayesMultinomial.reset, and moa.classifiers.bayes.NaiveBayesMultinomial.totalSize().
{
        if (this.reset == true) {
            this.m_numClasses = inst.numClasses();
            double laplace = this.laplaceCorrectionOption.getValue();
            int numAttributes = inst.numAttributes();
            m_probOfClass = new double[m_numClasses];
            Arrays.fill(m_probOfClass, laplace);
            m_classTotals = new double[m_numClasses];
            Arrays.fill(m_classTotals, laplace * numAttributes);
            m_wordTotalForClass = new DoubleVector[m_numClasses];
            for (int i = 0; i< m_numClasses; i++) {
                //Arrays.fill(wordTotal, laplace);
                m_wordTotalForClass[i] = new DoubleVector();
            }
            this.reset = false;
        }
        // Update classifier
        int classIndex = inst.classIndex();
        int classValue = (int) inst.value(classIndex);
        double w = inst.weight();
        m_probOfClass[classValue] += w;
        m_classTotals[classValue] += w * totalSize(inst);
        double total = m_classTotals[classValue];
        for (int i = 0; i < inst.numValues(); i++) {
            int index = inst.index(i);
            if (index != classIndex && !inst.isMissing(i)) {
                //m_wordTotalForClass[index][classValue] += w * inst.valueSparse(i);
                double laplaceCorrection = 0.0;
                if (m_wordTotalForClass[classValue].getValue(index)== 0) {
                    laplaceCorrection = this.laplaceCorrectionOption.getValue();
                }
                m_wordTotalForClass[classValue].addToValue(index, w * inst.valueSparse(i) + laplaceCorrection);
            }
        }
    }
Member Data Documentation
FloatOption moa.classifiers.bayes.NaiveBayesMultinomial.laplaceCorrectionOption
Initial value:
 new FloatOption("laplaceCorrection",
            'l', "Laplace correction factor.",
            1.0, 0.00, Integer.MAX_VALUE)
Definition at line 58 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
double [] moa.classifiers.bayes.NaiveBayesMultinomial.m_classTotals [protected]
sum of weight_of_instance * word_count_of_instance for each class
Definition at line 75 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
Instances moa.classifiers.bayes.NaiveBayesMultinomial.m_headerInfo [protected]
copy of header information for use in toString method
Definition at line 80 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription().
int moa.classifiers.bayes.NaiveBayesMultinomial.m_numClasses [protected]
number of class values
Definition at line 85 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
double [] moa.classifiers.bayes.NaiveBayesMultinomial.m_probOfClass [protected]
the probability of a class (i.e.
Pr[H])
Definition at line 90 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
DoubleVector [] moa.classifiers.bayes.NaiveBayesMultinomial.m_wordTotalForClass [protected]
probability that a word (w) exists in a class (H) (i.e.
Pr[w|H]) The matrix is in the this format: m_wordTotalForClass[wordAttribute][class]
Definition at line 96 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getModelDescription(), moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
boolean moa.classifiers.bayes.NaiveBayesMultinomial.reset = false [protected]
Definition at line 98 of file NaiveBayesMultinomial.java.
Referenced by moa.classifiers.bayes.NaiveBayesMultinomial.getVotesForInstance(), moa.classifiers.bayes.NaiveBayesMultinomial.resetLearningImpl(), and moa.classifiers.bayes.NaiveBayesMultinomial.trainOnInstanceImpl().
final long moa.classifiers.bayes.NaiveBayesMultinomial.serialVersionUID = -7204398796974263187L [static, private]
for serialization
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 65 of file NaiveBayesMultinomial.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/bayes/NaiveBayesMultinomial.java