MOA: moa.learners.ChangeDetectorLearner Class Reference
moa.learners.ChangeDetectorLearner Class Reference
Class for detecting concept drift and to be used as a learner.
Public Member Functions
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Public Attributes
ClassOption driftDetectionMethodOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
ChangeDetector driftDetectionMethod
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for detecting concept drift and to be used as a learner.
data
Valid options are:
-l classname
Specify the full class name of a classifier as the basis for the concept drift classifier.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 39 of file ChangeDetectorLearner.java.
Member Function Documentation
void moa.learners.ChangeDetectorLearner.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 68 of file ChangeDetectorLearner.java.
{
        //((AbstractClassifier) this.classifier).getModelDescription(out, indent);
    }
Measurement [] moa.learners.ChangeDetectorLearner.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 73 of file ChangeDetectorLearner.java.
{
        //return ((AbstractClassifier) this.classifier).getModelMeasurementsImpl();
        return new Measurement[0];
    }
double [] moa.learners.ChangeDetectorLearner.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 59 of file ChangeDetectorLearner.java.
References moa.learners.ChangeDetectorLearner.driftDetectionMethod, and moa.classifiers.core.driftdetection.ChangeDetector.getOutput().
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
{
        return this.driftDetectionMethod.getOutput();
    }
boolean moa.learners.ChangeDetectorLearner.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 63 of file ChangeDetectorLearner.java.
{
        return false;
    }
void moa.learners.ChangeDetectorLearner.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 49 of file ChangeDetectorLearner.java.
References moa.classifiers.AbstractClassifier.copy(), moa.learners.ChangeDetectorLearner.driftDetectionMethod, moa.learners.ChangeDetectorLearner.driftDetectionMethodOption, and moa.options.AbstractOptionHandler.getPreparedClassOption().
{
        this.driftDetectionMethod = ((ChangeDetector) getPreparedClassOption(this.driftDetectionMethodOption)).copy();
    }
void moa.learners.ChangeDetectorLearner.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 54 of file ChangeDetectorLearner.java.
References moa.learners.ChangeDetectorLearner.driftDetectionMethod, and moa.classifiers.core.driftdetection.ChangeDetector.input().
{
        this.driftDetectionMethod.input(inst.value(0));
    }
Member Data Documentation
ChangeDetector moa.learners.ChangeDetectorLearner.driftDetectionMethod [protected]
Definition at line 46 of file ChangeDetectorLearner.java.
Referenced by moa.learners.ChangeDetectorLearner.getVotesForInstance(), moa.learners.ChangeDetectorLearner.resetLearningImpl(), and moa.learners.ChangeDetectorLearner.trainOnInstanceImpl().
ClassOption moa.learners.ChangeDetectorLearner.driftDetectionMethodOption
Initial value:
 new ClassOption("driftDetectionMethod", 'd',
            "Drift detection method to use.", ChangeDetector.class, "DDM")
Definition at line 43 of file ChangeDetectorLearner.java.
Referenced by moa.learners.ChangeDetectorLearner.resetLearningImpl().
final long moa.learners.ChangeDetectorLearner.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 41 of file ChangeDetectorLearner.java.
The documentation for this class was generated from the following file:
main/java/moa/learners/ChangeDetectorLearner.java