MOA: moa.tasks.MeasureStreamSpeed Class Reference
moa.tasks.MeasureStreamSpeed Class Reference
Task for measuring the speed of the stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption streamOption
IntOption generateSizeOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for measuring the speed of the stream.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 36 of file MeasureStreamSpeed.java.
Member Function Documentation
Object moa.tasks.MeasureStreamSpeed.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 53 of file MeasureStreamSpeed.java.
References moa.tasks.MeasureStreamSpeed.generateSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.nextInstance(), and moa.tasks.MeasureStreamSpeed.streamOption.
{
        TimingUtils.enablePreciseTiming();
        int numInstances = 0;
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        long genStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        while (numInstances < this.generateSizeOption.getValue()) {
            stream.nextInstance();
            numInstances++;
        }
        double genTime = TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                - genStartTime);
        return new LearningEvaluation(
                new Measurement[]{
                    new Measurement("Number of instances generated",
                    numInstances),
                    new Measurement("Time elapsed", genTime),
                    new Measurement("Instances per second", numInstances
                    / genTime)});
    }
String moa.tasks.MeasureStreamSpeed.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 39 of file MeasureStreamSpeed.java.
{
        return "Measures the speed of a stream.";
    }
Class<?> moa.tasks.MeasureStreamSpeed.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 74 of file MeasureStreamSpeed.java.
{
        return LearningEvaluation.class;
    }
Member Data Documentation
IntOption moa.tasks.MeasureStreamSpeed.generateSizeOption
Initial value:
 new IntOption("generateSize", 'g',
            "Number of examples.", 10000000, 0, Integer.MAX_VALUE)
Definition at line 49 of file MeasureStreamSpeed.java.
Referenced by moa.tasks.MeasureStreamSpeed.doMainTask().
final long moa.tasks.MeasureStreamSpeed.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 43 of file MeasureStreamSpeed.java.
ClassOption moa.tasks.MeasureStreamSpeed.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to measure.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 45 of file MeasureStreamSpeed.java.
Referenced by moa.tasks.MeasureStreamSpeed.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/MeasureStreamSpeed.java