MOA: moa.options.Options Class Reference
moa.options.Options Class Reference
File option.
Public Member Functions
void addOption (Option opt)
int numOptions ()
Option getOption (String optName)
Option getOption (char cliChar)
Option[] getOptionArray ()
void removeOption (String optName)
void removeOption (Option opt)
void removeAllOptions ()
void resetToDefaults ()
void setViaCLIString (String cliString)
String getAsCLIString ()
String getHelpString ()
void getHelp (StringBuilder sb, int indent)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Protected Member Functions
static String[] splitParameterFromRemainingOptions (String cliString)
Internal method that splits a string into two parts - the parameter for the current option, and the remaining options.
Protected Attributes
List< Option > optionList = new LinkedList<Option>()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
File option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 34 of file Options.java.
Member Function Documentation
void moa.options.Options.addOption (Option opt)
Definition at line 40 of file Options.java.
References moa.options.Option.getCLIChar(), moa.options.Option.getName(), moa.options.Options.getOption(), and moa.options.Options.optionList.
Referenced by moa.options.ClassOptionWithNames.cliStringToObject(), moa.options.ClassOption.cliStringToObject(), and moa.options.AbstractOptionHandler.getOptions().
{
        if (getOption(opt.getName()) != null) {
            throw new IllegalArgumentException("Duplicate option name: "
                    + opt.getName());
        }
        if (getOption(opt.getCLIChar()) != null) {
            throw new IllegalArgumentException(
                    "Duplicate option command line character: "
                    + opt.getCLIChar());
        }
        this.optionList.add(opt);
    }
String moa.options.Options.getAsCLIString ()
Definition at line 161 of file Options.java.
References moa.options.Options.optionList.
Referenced by moa.options.AbstractOptionHandler.getCLICreationString().
{
        StringBuilder commandLine = new StringBuilder();
        for (Option option : this.optionList) {
            String value = option.getValueAsCLIString();
            if ((value != null) && !value.equals(option.getDefaultCLIString())) {
                if (commandLine.length() > 0) {
                    commandLine.append(" ");
                }
                commandLine.append("-" + option.getCLIChar());
                if (value.length() > 0) {
                    if (value.indexOf(' ') < 0) {
                        commandLine.append(" " + value);
                    } else {
                        commandLine.append(" (" + value + ")");
                    }
                }
            }
        }
        return commandLine.toString();
    }
void moa.options.Options.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 268 of file Options.java.
{
        // TODO Auto-generated method stub
    }
void moa.options.Options.getHelp (StringBuilder sb, int indent)
Definition at line 188 of file Options.java.
References moa.options.Options.optionList.
Referenced by moa.options.Options.getHelpString().
{
        if (optionList.size() > 0) {
            for (Option option : optionList) {
                StringUtils.appendIndent(sb, indent);
                sb.append('-');
                sb.append(option.getCLIChar());
                sb.append(' ');
                sb.append(option.getName());
                String defaultString = option.getDefaultCLIString();
                if (defaultString != null && defaultString.length() > 0) {
                    sb.append(" (default: ");
                    sb.append(defaultString);
                    sb.append(')');
                }
                StringUtils.appendNewline(sb);
                StringUtils.appendIndent(sb, indent);
                sb.append(option.getPurpose());
                StringUtils.appendNewline(sb);
            }
        } else {
            StringUtils.appendIndented(sb, indent, "No options.");
        }
    }
String moa.options.Options.getHelpString ()
Definition at line 182 of file Options.java.
References moa.options.Options.getHelp().
Referenced by moa.gui.OptionsConfigurationPanel.getHelpText().
{
        StringBuilder sb = new StringBuilder();
        getHelp(sb, 0);
        return sb.toString();
    }
Option moa.options.Options.getOption (char cliChar)
Definition at line 66 of file Options.java.
References moa.options.Options.optionList.
{
        for (Option option : this.optionList) {
            if (option.getCLIChar() == cliChar) {
                return option;
            }
        }
        return null;
    }
Option moa.options.Options.getOption (String optName)
Definition at line 57 of file Options.java.
References moa.options.Options.optionList.
Referenced by moa.options.Options.addOption(), moa.options.Options.removeOption(), and moa.options.Options.setViaCLIString().
{
        for (Option option : this.optionList) {
            if (optName.equals(option.getName())) {
                return option;
            }
        }
        return null;
    }
Option [] moa.options.Options.getOptionArray ()
Definition at line 75 of file Options.java.
References moa.options.Options.optionList.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel(), and moa.options.AbstractOptionHandler.prepareClassOptions().
{
        return this.optionList.toArray(new Option[this.optionList.size()]);
    }
int moa.options.Options.numOptions ()
Definition at line 53 of file Options.java.
References moa.options.Options.optionList.
{
        return this.optionList.size();
    }
void moa.options.Options.removeAllOptions ()
Definition at line 87 of file Options.java.
References moa.options.Options.optionList.
Referenced by moa.options.ClassOptionWithNames.cliStringToObject(), and moa.options.ClassOption.cliStringToObject().
{
        this.optionList = new LinkedList<Option>();
    }
void moa.options.Options.removeOption (Option opt)
Definition at line 83 of file Options.java.
References moa.options.Options.optionList.
{
        this.optionList.remove(opt);
    }
void moa.options.Options.removeOption (String optName)
Definition at line 79 of file Options.java.
References moa.options.Options.getOption().
{
        removeOption(getOption(optName));
    }
void moa.options.Options.resetToDefaults ()
Definition at line 91 of file Options.java.
References moa.options.Options.optionList.
{
        for (Option option : this.optionList) {
            option.resetToDefault();
        }
    }
void moa.options.Options.setViaCLIString (String cliString)
Definition at line 97 of file Options.java.
References moa.options.Options.getOption(), moa.options.Option.setValueViaCLIString(), and moa.options.Options.splitParameterFromRemainingOptions().
Referenced by moa.options.ClassOptionWithNames.cliStringToObject(), and moa.options.ClassOption.cliStringToObject().
{
        cliString = cliString.trim();
        while (cliString.length() > 0) {
            if (cliString.startsWith("-")) {
                boolean flagClusterFound = false;
                String optionString = null;
                int nextSpaceIndex = cliString.indexOf(' ', 1);
                Option opt;
                if (nextSpaceIndex > 0) {
                    optionString = cliString.substring(1, nextSpaceIndex);
                } else {
                    optionString = cliString.substring(1, cliString.length());
                    nextSpaceIndex = cliString.length() - 1;
                }
                if (optionString.length() == 1) {
                    opt = getOption(optionString.charAt(0));
                } else {
                    opt = getOption(optionString);
                    if (opt == null) {
                        // check for cluster of flags
                        flagClusterFound = true;
                        for (int i = 0; i < optionString.length(); i++) {
                            opt = getOption(optionString.charAt(i));
                            if (!(opt instanceof FlagOption)) {
                                flagClusterFound = false;
                                opt = null;
                                break;
                            }
                        }
                        if (flagClusterFound) {
                            for (int i = 0; i < optionString.length(); i++) {
                                opt = getOption(optionString.charAt(i));
                                opt.setValueViaCLIString("");
                            }
                            cliString = cliString.substring(nextSpaceIndex + 1,
                                    cliString.length());
                        }
                    }
                }
                if (!flagClusterFound) {
                    if (opt != null) {
                        String parameters = cliString.substring(
                                nextSpaceIndex + 1, cliString.length());
                        if (opt instanceof FlagOption) {
                            opt.setValueViaCLIString("");
                            cliString = parameters;
                        } else {
                            String[] paramSplit = splitParameterFromRemainingOptions(parameters);
                            opt.setValueViaCLIString(paramSplit[0]);
                            cliString = paramSplit[1];
                        }
                    } else {
                        throw new IllegalArgumentException("Unknown option: -"
                                + optionString);
                    }
                }
            } else {
                throw new IllegalArgumentException("Expecting option, found: '"
                        + cliString + "'.");
            }
            cliString = cliString.trim();
        }
    }
static String [] moa.options.Options.splitParameterFromRemainingOptions (String cliString) [static, protected]
Internal method that splits a string into two parts - the parameter for the current option, and the remaining options.
Parameters:
cliString the command line string, beginning at an option parameter
Returns:
an array of two strings - the first is the option paramter, the second is the remaining cli string
Definition at line 221 of file Options.java.
Referenced by moa.options.Options.setViaCLIString().
{
        String[] paramSplit = new String[2];
        cliString = cliString.trim();
        if (cliString.startsWith("\"") || cliString.startsWith("'")) {
            int endQuoteIndex = cliString.indexOf(cliString.charAt(0), 1);
            if (endQuoteIndex < 0) {
                throw new IllegalArgumentException(
                        "Quotes not terminated correctly.");
            }
            paramSplit[0] = cliString.substring(1, endQuoteIndex);
            paramSplit[1] = cliString.substring(endQuoteIndex + 1, cliString.length());
        } else if (cliString.startsWith("(")) {
            int bracketsOpen = 1;
            int currPos = 1;
            int nextCloseIndex = cliString.indexOf(")", currPos);
            int nextOpenIndex = cliString.indexOf("(", currPos);
            while (bracketsOpen != 0) {
                if (nextCloseIndex < 0) {
                    throw new IllegalArgumentException("Brackets do not match.");
                } else if ((nextOpenIndex < 0)
                        || (nextCloseIndex < nextOpenIndex)) {
                    bracketsOpen--;
                    currPos = nextCloseIndex + 1;
                    nextCloseIndex = cliString.indexOf(")", currPos);
                } else {
                    bracketsOpen++;
                    currPos = nextOpenIndex + 1;
                    nextOpenIndex = cliString.indexOf("(", currPos);
                }
            }
            paramSplit[0] = cliString.substring(1, currPos - 1);
            paramSplit[1] = cliString.substring(currPos, cliString.length());
        } else {
            int firstSpaceIndex = cliString.indexOf(" ", 0);
            if (firstSpaceIndex >= 0) {
                paramSplit[0] = cliString.substring(0, firstSpaceIndex);
                paramSplit[1] = cliString.substring(firstSpaceIndex + 1,
                        cliString.length());
            } else {
                paramSplit[0] = cliString;
                paramSplit[1] = "";
            }
        }
        return paramSplit;
    }
Member Data Documentation
List<Option> moa.options.Options.optionList = new LinkedList<Option>() [protected]
Definition at line 38 of file Options.java.
Referenced by moa.options.Options.addOption(), moa.options.Options.getAsCLIString(), moa.options.Options.getHelp(), moa.options.Options.getOption(), moa.options.Options.getOptionArray(), moa.options.Options.numOptions(), moa.options.Options.removeAllOptions(), moa.options.Options.removeOption(), and moa.options.Options.resetToDefaults().
final long moa.options.Options.serialVersionUID = 1L [static, private]
Definition at line 36 of file Options.java.
The documentation for this class was generated from the following file:
main/java/moa/options/Options.java