MOA: moa.streams.FilteredStream Class Reference
moa.streams.FilteredStream Class Reference
Class for representing a stream that is filtered.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
ClassOption streamOption
ClassOption filtersOption
Protected Attributes
InstanceStream filterChain
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for representing a stream that is filtered.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 37 of file FilteredStream.java.
Member Function Documentation
long moa.streams.FilteredStream.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 82 of file FilteredStream.java.
References moa.streams.InstanceStream.estimatedRemainingInstances(), and moa.streams.FilteredStream.filterChain.
{
        return this.filterChain.estimatedRemainingInstances();
    }
void moa.streams.FilteredStream.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 112 of file FilteredStream.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.FilteredStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 87 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, and moa.streams.InstanceStream.getHeader().
{
        return this.filterChain.getHeader();
    }
String moa.streams.FilteredStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 41 of file FilteredStream.java.
{
        return "A stream that is filtered.";
    }
boolean moa.streams.FilteredStream.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 92 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, and moa.streams.InstanceStream.hasMoreInstances().
{
        return this.filterChain.hasMoreInstances();
    }
boolean moa.streams.FilteredStream.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 97 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, and moa.streams.InstanceStream.isRestartable().
{
        return this.filterChain.isRestartable();
    }
Instance moa.streams.FilteredStream.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 102 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, and moa.streams.InstanceStream.nextInstance().
{
        return this.filterChain.nextInstance();
    }
void moa.streams.FilteredStream.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 58 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, moa.streams.FilteredStream.filtersOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.streams.filters.StreamFilter.setInputStream(), moa.streams.FilteredStream.streamOption, and moa.tasks.TaskMonitor.taskShouldAbort().
{
        StreamFilter filters;
            monitor.setCurrentActivity("Materializing filter " //+ (i + 1)
                    + "...", -1.0);
            filters = (StreamFilter) getPreparedClassOption(this.filtersOption);
            if (monitor.taskShouldAbort()) {
                return;
            }
            if (filters instanceof OptionHandler) {
                monitor.setCurrentActivity("Preparing filter " //+ (i + 1)
                        + "...", -1.0);
                ((OptionHandler) filters).prepareForUse(monitor, repository);
                if (monitor.taskShouldAbort()) {
                    return;
                }
            }
        InstanceStream chain = (InstanceStream) getPreparedClassOption(this.streamOption);
            filters.setInputStream(chain);
            chain = filters;
        this.filterChain = chain;
    }
void moa.streams.FilteredStream.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 107 of file FilteredStream.java.
References moa.streams.FilteredStream.filterChain, and moa.streams.InstanceStream.restart().
{
        this.filterChain.restart();
    }
Member Data Documentation
InstanceStream moa.streams.FilteredStream.filterChain [protected]
Definition at line 55 of file FilteredStream.java.
Referenced by moa.streams.FilteredStream.estimatedRemainingInstances(), moa.streams.FilteredStream.getHeader(), moa.streams.FilteredStream.hasMoreInstances(), moa.streams.FilteredStream.isRestartable(), moa.streams.FilteredStream.nextInstance(), moa.streams.FilteredStream.prepareForUseImpl(), and moa.streams.FilteredStream.restart().
ClassOption moa.streams.FilteredStream.filtersOption
Initial value:
 new ClassOption("filters", 'f',
            "Filters to apply.", StreamFilter.class,
            "AddNoiseFilter")
Definition at line 51 of file FilteredStream.java.
Referenced by moa.streams.FilteredStream.prepareForUseImpl().
final long moa.streams.FilteredStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 45 of file FilteredStream.java.
ClassOption moa.streams.FilteredStream.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to filter.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 47 of file FilteredStream.java.
Referenced by moa.streams.FilteredStream.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/FilteredStream.java