MOA: moa.classifiers.multilabel.meta.MLOzaBag Class Reference
moa.classifiers.multilabel.meta.MLOzaBag Class Reference
OzaBag for Multi-label data.
Public Member Functions
void resetLearningImpl ()
Resets this classifier.
void setModelContext (InstancesHeader raw_header)
Sets the reference to the header of the data stream.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
double[] getVotesForInstance (Instance x)
Predicts the class memberships for a given instance.
Protected Attributes
int m_L = -1
Detailed Description
OzaBag for Multi-label data.
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
Revision
1
Definition at line 33 of file MLOzaBag.java.
Member Function Documentation
double [] moa.classifiers.multilabel.meta.MLOzaBag.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Reimplemented from moa.classifiers.meta.OzaBag.
Definition at line 76 of file MLOzaBag.java.
References moa.classifiers.meta.OzaBag.ensemble, moa.classifiers.Classifier.getVotesForInstance(), and moa.classifiers.multilabel.meta.MLOzaBag.m_L.
{
        int L = x.classIndex() + 1;
        if (m_L != L) {
            m_L = L;
        }
        double y[] = new double[m_L];
        for (int i = 0; i < this.ensemble.length; i++) {
            double w[] = this.ensemble[i].getVotesForInstance(x);
            for (int j = 0; j < w.length; j++) {
                y[j] += w[j];
            }
        }
        return y;
    }
boolean moa.classifiers.multilabel.meta.MLOzaBag.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Reimplemented from moa.classifiers.meta.OzaBag.
Definition at line 71 of file MLOzaBag.java.
{
        return true;
    }
void moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Reimplemented from moa.classifiers.meta.OzaBag.
Definition at line 44 of file MLOzaBag.java.
References moa.classifiers.meta.OzaBag.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.OzaBag.ensemble, moa.classifiers.meta.OzaBag.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), and moa.classifiers.Classifier.resetLearning().
Referenced by moa.classifiers.multilabel.meta.MLOzaBag.setModelContext().
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
    }
void moa.classifiers.multilabel.meta.MLOzaBag.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 54 of file MLOzaBag.java.
References moa.classifiers.meta.OzaBag.ensemble, moa.classifiers.multilabel.meta.MLOzaBag.m_L, moa.classifiers.AbstractClassifier.modelContext, moa.classifiers.Classifier.resetLearning(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), and moa.classifiers.Classifier.setModelContext().
{
        //set the multilabel model context
        this.modelContext = raw_header;
        m_L = raw_header.classIndex() + 1;
        // reset ensemble
        this.resetLearningImpl();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i].setModelContext(raw_header);
            this.ensemble[i].resetLearning();
        }
    }
Member Data Documentation
int moa.classifiers.multilabel.meta.MLOzaBag.m_L = -1 [protected]
Definition at line 35 of file MLOzaBag.java.
Referenced by moa.classifiers.multilabel.meta.MLOzaBag.getVotesForInstance(), and moa.classifiers.multilabel.meta.MLOzaBag.setModelContext().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/meta/MLOzaBag.java