MOA: moa.gui.visualization.StreamPanel Class Reference
moa.gui.visualization.StreamPanel Class Reference
Classes
class pointCanvasPanel
Public Member Functions
StreamPanel ()
Creates new form StreamPanel.
void drawMicroClustering (Clustering clustering, List< DataPoint > points, Color color)
void drawMacroClustering (Clustering clustering, List< DataPoint > points, Color color)
void drawGTClustering (Clustering clustering, List< DataPoint > points, Color color)
void setMicroLayerVisibility (boolean visibility)
void setMacroLayerVisibility (boolean visibility)
void setGroundTruthLayerVisibility (boolean visibility)
void setPointVisibility (boolean visibility)
void drawPoint (DataPoint point)
void applyDrawDecay (float factor)
void screenshot (String filename, boolean svg, boolean png)
ClusterPanel getHighlightedClusterPanel ()
void setHighlightedClusterPanel (ClusterPanel clusterpanel)
void setZoom (int x, int y, int zoom_delta, JScrollPane scrollPane)
int getActiveXDim ()
void setActiveXDim (int activeXDim)
int getActiveYDim ()
void setActiveYDim (int activeYDim)
void componentHidden (ComponentEvent e)
void componentMoved (ComponentEvent e)
void componentResized (ComponentEvent e)
void componentShown (ComponentEvent e)
Package Functions
void drawPointPanels (ArrayList< DataPoint > points, int timestamp, double decay_rate, double decay_threshold)
Private Member Functions
JPanel getNewLayer ()
void drawClusteringsOnCanvas (JPanel layer, Graphics2D imageGraphics)
void drawClustering (JPanel layer, Clustering clustering, List< DataPoint > points, Color color)
void drawNonConvexClustering (JPanel layer, Clustering clustering, List< DataPoint > points, Color color)
void initComponents ()
This method is called from within the constructor to initialize the form.
void formMouseClicked (java.awt.event.MouseEvent evt)
Private Attributes
ClusterPanel highlighted_cluster = null
double zoom_factor = 0.2
int zoom = 1
int width_org
int height_org
int activeXDim = 0
int activeYDim = 1
JPanel layerPoints
JPanel layerMicro
JPanel layerMacro
JPanel layerGroundTruth
BufferedImage pointCanvas
pointCanvasPanel layerPointCanvas
boolean pointsVisible = true
boolean ANTIALIAS = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 56 of file StreamPanel.java.
Constructor & Destructor Documentation
moa.gui.visualization.StreamPanel.StreamPanel ()
Creates new form StreamPanel.
Definition at line 105 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.getNewLayer(), moa.gui.visualization.StreamPanel.initComponents(), moa.gui.visualization.StreamPanel.layerGroundTruth, moa.gui.visualization.StreamPanel.layerMacro, moa.gui.visualization.StreamPanel.layerMicro, moa.gui.visualization.StreamPanel.layerPointCanvas, and moa.gui.visualization.StreamPanel.layerPoints.
Referenced by moa.gui.clustertab.ClusteringVisualTab.initComponents().
{
        initComponents();
        layerPoints = getNewLayer();
        layerPoints.setOpaque(true);
        layerPoints.setBackground(Color.white);
        layerMicro = getNewLayer();
        layerMacro = getNewLayer();
        layerGroundTruth = getNewLayer();
        add(layerMacro);
        add(layerMicro);
        add(layerGroundTruth);
        add(layerPoints);
        layerPointCanvas = new pointCanvasPanel();
        add(layerPointCanvas);
        addComponentListener(this);
    }
Member Function Documentation
void moa.gui.visualization.StreamPanel.applyDrawDecay (float factor)
Definition at line 213 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.pointCanvas, and moa.gui.visualization.StreamPanel.pointCanvasPanel.setImage().
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        RescaleOp brightenOp = new RescaleOp(1f, 150f/factor, null);
        pointCanvas = brightenOp.filter(pointCanvas, null);
        layerPointCanvas.setImage(pointCanvas);
        layerPointCanvas.repaint();
    }
void moa.gui.visualization.StreamPanel.componentHidden (ComponentEvent e)
Definition at line 420 of file StreamPanel.java.
{
    }
void moa.gui.visualization.StreamPanel.componentMoved (ComponentEvent e)
Definition at line 423 of file StreamPanel.java.
{
    }
void moa.gui.visualization.StreamPanel.componentResized (ComponentEvent e)
Definition at line 426 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerGroundTruth, moa.gui.visualization.StreamPanel.layerMacro, moa.gui.visualization.StreamPanel.layerMicro, moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.layerPoints, moa.gui.visualization.StreamPanel.pointCanvas, and moa.gui.visualization.StreamPanel.pointCanvasPanel.setImage().
{
        //System.out.println(e.getComponent().getClass().getName() + " --- Resized ");
        int size = Math.min(getWidth(), getHeight());
        layerMicro.setSize(new Dimension(size,size));
        layerMacro.setSize(new Dimension(size,size));
        layerGroundTruth.setSize(new Dimension(size,size));
        layerPoints.setSize(new Dimension(size,size));
        pointCanvas = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
        layerPointCanvas.setSize(new Dimension(size,size));
        layerPointCanvas.setImage(pointCanvas);
        Graphics2D imageGraphics = (Graphics2D) pointCanvas.getGraphics();
        imageGraphics.setColor(Color.white);
        imageGraphics.fillRect(0, 0, getWidth(), getHeight());
        imageGraphics.dispose();
    }
void moa.gui.visualization.StreamPanel.componentShown (ComponentEvent e)
Definition at line 447 of file StreamPanel.java.
{
    }
void moa.gui.visualization.StreamPanel.drawClustering (JPanel layer, Clustering clustering, List< DataPoint > points, Color color) [private]
Definition at line 222 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.drawClusteringsOnCanvas(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.cluster.Clustering.get(), moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.pointCanvas, moa.gui.visualization.StreamPanel.pointsVisible, moa.cluster.Clustering.size(), and moa.gui.visualization.ClusterPanel.updateLocation().
Referenced by moa.gui.visualization.StreamPanel.drawGTClustering(), moa.gui.visualization.StreamPanel.drawMacroClustering(), and moa.gui.visualization.StreamPanel.drawMicroClustering().
{
        if (clustering.get(0) instanceof NonConvexCluster) {
            drawNonConvexClustering(layer, clustering, points, color);
        } else {
            layer.removeAll();
            for (int c = 0; c < clustering.size(); c++) {
                SphereCluster cluster = (SphereCluster)clustering.get(c);
                ClusterPanel clusterpanel = new ClusterPanel(cluster, color, this);
                layer.add(clusterpanel);
                clusterpanel.updateLocation();
            }
            if(layer.isVisible() && pointsVisible){
                Graphics2D imageGraphics = (Graphics2D) pointCanvas.createGraphics();
                imageGraphics.setColor(color);
                drawClusteringsOnCanvas(layer, imageGraphics);
                layerPointCanvas.repaint();
            }
            layer.repaint();
        }
    }
void moa.gui.visualization.StreamPanel.drawClusteringsOnCanvas (JPanel layer, Graphics2D imageGraphics) [private]
Definition at line 203 of file StreamPanel.java.
References moa.gui.visualization.ClusterPanel.drawOnCanvas().
Referenced by moa.gui.visualization.StreamPanel.drawClustering(), and moa.gui.visualization.StreamPanel.drawNonConvexClustering().
{
        for(Component comp :layer.getComponents()){
            if(comp instanceof ClusterPanel){
                ClusterPanel cp = (ClusterPanel)comp;
                cp.drawOnCanvas(imageGraphics);
            }
        }
    }
void moa.gui.visualization.StreamPanel.drawGTClustering (Clustering clustering, List< DataPoint > points, Color color)
Definition at line 144 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.drawClustering(), and moa.gui.visualization.StreamPanel.layerGroundTruth.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings().
{
        drawClustering(layerGroundTruth, clustering, points, color);
    }
void moa.gui.visualization.StreamPanel.drawMacroClustering (Clustering clustering, List< DataPoint > points, Color color)
Definition at line 141 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.drawClustering(), and moa.gui.visualization.StreamPanel.layerMacro.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings().
{
        drawClustering(layerMacro, clustering, points, color);
    }
void moa.gui.visualization.StreamPanel.drawMicroClustering (Clustering clustering, List< DataPoint > points, Color color)
Definition at line 137 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.drawClustering(), and moa.gui.visualization.StreamPanel.layerMicro.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings().
{
        drawClustering(layerMicro, clustering, points, color);
    }
void moa.gui.visualization.StreamPanel.drawNonConvexClustering (JPanel layer, Clustering clustering, List< DataPoint > points, Color color) [private]
Definition at line 247 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.drawClusteringsOnCanvas(), moa.cluster.Clustering.getClustering(), moa.cluster.Cluster.getInclusionProbability(), moa.gui.visualization.StreamPanel.layerMacro, moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.pointCanvas, moa.gui.visualization.StreamPanel.pointsVisible, and moa.gui.visualization.PointPanel.updateLocation().
Referenced by moa.gui.visualization.StreamPanel.drawClustering().
{
        layerMacro.removeAll();
        List<Cluster> foundClusters = clustering.getClustering();
        double inclusionProbabilityThreshold = 0.5;
        for (DataPoint p : points) {
            for (int i = 0; i < foundClusters.size(); i++) {
                Cluster fc = foundClusters.get(i);
                if (fc.getInclusionProbability(p) >= inclusionProbabilityThreshold) {
                    PointPanel pointPanel = new PointPanel(p, this, color);
                    layerMacro.add(pointPanel);
                    pointPanel.updateLocation();
                }
            }
        }
        if (layerMacro.isVisible() && pointsVisible) {  // Points & Macro together
            Graphics2D imageGraphics = (Graphics2D) pointCanvas.createGraphics();
            imageGraphics.setColor(color);
            drawClusteringsOnCanvas(layerMacro, imageGraphics);
            layerPointCanvas.repaint();
        }
        layerMacro.repaint();
    }
void moa.gui.visualization.StreamPanel.drawPoint (DataPoint point)
Definition at line 174 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.ANTIALIAS, moa.gui.visualization.StreamPanel.getActiveXDim(), moa.gui.visualization.StreamPanel.getActiveYDim(), moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.layerPoints, moa.gui.visualization.StreamPanel.pointCanvas, and moa.gui.visualization.StreamPanel.pointsVisible.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        layerPointCanvas.setVisible(pointsVisible);
        layerPoints.setVisible(false);
        if(!pointsVisible)
            return;
        Graphics2D imageGraphics = (Graphics2D) pointCanvas.createGraphics();
        if (ANTIALIAS) {
            imageGraphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
        }
        int size = Math.min(getWidth(), getHeight());
        int x = (int) Math.round(point.value(getActiveXDim()) * size);
        int y = (int) Math.round(point.value(getActiveYDim()) * size);
        Color c = PointPanel.getPointColorbyClass(point, 10);
        imageGraphics.setColor(c);
        int psize = PointPanel.POINTSIZE;
        int poffset = 2;
        imageGraphics.drawOval(x - poffset, y - poffset, psize, psize);
        imageGraphics.fillOval(x - poffset, y - poffset, psize, psize);
        layerPointCanvas.repaint();
    }
void moa.gui.visualization.StreamPanel.drawPointPanels (ArrayList< DataPoint > points, int timestamp, double decay_rate, double decay_threshold) [package]
Definition at line 164 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.layerPoints, moa.gui.visualization.StreamPanel.pointsVisible, and moa.gui.visualization.PointPanel.updateLocation().
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        for(int p = 0; p < points.size(); p++){
            PointPanel pointPanel = new PointPanel(points.get(p), this, decay_rate, decay_threshold);
            layerPoints.add(pointPanel);
            pointPanel.updateLocation();
        }
        layerPointCanvas.setVisible(false);
        layerPoints.setVisible(pointsVisible);
    }
void moa.gui.visualization.StreamPanel.formMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 407 of file StreamPanel.java.
References moa.gui.visualization.ClusterPanel.highlight(), and moa.gui.visualization.StreamPanel.highlighted_cluster.
Referenced by moa.gui.visualization.StreamPanel.initComponents().
                                                                 {//GEN-FIRST:event_formMouseClicked
        if(highlighted_cluster!=null){
            highlighted_cluster.highlight(false);
            highlighted_cluster=null;
        }
    }//GEN-LAST:event_formMouseClicked
int moa.gui.visualization.StreamPanel.getActiveXDim ()
Definition at line 363 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.activeXDim.
Referenced by moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.PointPanel.updateLocation(), and moa.gui.visualization.ClusterPanel.updateLocation().
{
        return activeXDim;
    }
int moa.gui.visualization.StreamPanel.getActiveYDim ()
Definition at line 371 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.activeYDim.
Referenced by moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.PointPanel.updateLocation(), and moa.gui.visualization.ClusterPanel.updateLocation().
{
        return activeYDim;
    }
ClusterPanel moa.gui.visualization.StreamPanel.getHighlightedClusterPanel ()
Definition at line 335 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.highlighted_cluster.
Referenced by moa.gui.visualization.PointPanel.getColor().
{
        return highlighted_cluster;
    }
JPanel moa.gui.visualization.StreamPanel.getNewLayer () [private]
Definition at line 129 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.StreamPanel().
{
        JPanel layer = new JPanel();
        layer.setOpaque(false);
        layer.setLayout(null);
        return layer;
    }
void moa.gui.visualization.StreamPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 386 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.formMouseClicked().
Referenced by moa.gui.visualization.StreamPanel.StreamPanel().
{
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.StreamPanel.screenshot (String filename, boolean svg, boolean png)
Definition at line 273 of file StreamPanel.java.
References moa.gui.visualization.PointPanel.getSVGString(), moa.gui.visualization.StreamPanel.layerGroundTruth, moa.gui.visualization.StreamPanel.layerMacro, moa.gui.visualization.StreamPanel.layerMicro, and moa.gui.visualization.StreamPanel.layerPoints.
{
        if(layerPoints.getComponentCount()==0 && layerMacro.getComponentCount()==0 && layerMicro.getComponentCount()==0)
            return;
        BufferedImage image = new BufferedImage(getWidth(),getHeight(),BufferedImage.TYPE_INT_RGB);
        if(png){
            synchronized(getTreeLock()){
                Graphics g = image.getGraphics();
                paintAll(g);
                try {
                    ImageIO.write(image, "png", new File(filename+".png"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        if(svg){
            try {
                PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(filename+".svg")));
                int width = 500;
                out.write("<?xml version=\"1.0\"?>\n");
                out.write("<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n");
                out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\""+width+"\" height=\""+width+"\">\n");
                if(layerMicro.isVisible()){
                    for(Component comp :layerMicro.getComponents()){
                        if(comp instanceof ClusterPanel)
                            out.write(((ClusterPanel)comp).getSVGString(width));
                    }
                }
                if(layerMacro.isVisible()){
                    for(Component comp :layerMacro.getComponents()){
                        if(comp instanceof ClusterPanel)
                            out.write(((ClusterPanel)comp).getSVGString(width));
                    }
                }
                if(layerGroundTruth.isVisible()){
                    for(Component comp :layerGroundTruth.getComponents()){
                        if(comp instanceof ClusterPanel)
                            out.write(((ClusterPanel)comp).getSVGString(width));
                    }
                }
                if(layerPoints.isVisible()){
                    for(Component comp :layerPoints.getComponents()){
                        if(comp instanceof PointPanel){
                            PointPanel pp = (PointPanel) comp;
                            out.write(pp.getSVGString(width));
                        }
                    }
                }
                out.write("</svg>");
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(StreamPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
void moa.gui.visualization.StreamPanel.setActiveXDim (int activeXDim)
Definition at line 367 of file StreamPanel.java.
{
        this.activeXDim = activeXDim;
    }
void moa.gui.visualization.StreamPanel.setActiveYDim (int activeYDim)
Definition at line 375 of file StreamPanel.java.
{
        this.activeYDim = activeYDim;
    }
void moa.gui.visualization.StreamPanel.setGroundTruthLayerVisibility (boolean visibility)
Definition at line 154 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerGroundTruth.
Referenced by moa.gui.visualization.RunVisualizer.setGroundTruthVisibility().
{
        layerGroundTruth.setVisible(visibility);
    }
void moa.gui.visualization.StreamPanel.setHighlightedClusterPanel (ClusterPanel clusterpanel)
Definition at line 339 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.highlighted_cluster.
Referenced by moa.gui.visualization.ClusterPanel.formMouseClicked().
{
        highlighted_cluster = clusterpanel;
        repaint();
    }
void moa.gui.visualization.StreamPanel.setMacroLayerVisibility (boolean visibility)
Definition at line 151 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerMacro.
Referenced by moa.gui.visualization.RunVisualizer.setMacroVisibility().
{
        layerMacro.setVisible(visibility);
    }
void moa.gui.visualization.StreamPanel.setMicroLayerVisibility (boolean visibility)
Definition at line 148 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerMicro.
Referenced by moa.gui.visualization.RunVisualizer.setMicroLayerVisibility().
{
        layerMicro.setVisible(visibility);
    }
void moa.gui.visualization.StreamPanel.setPointVisibility (boolean visibility)
Definition at line 157 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.layerPointCanvas, moa.gui.visualization.StreamPanel.layerPoints, and moa.gui.visualization.StreamPanel.pointsVisible.
Referenced by moa.gui.visualization.RunVisualizer.setPointLayerVisibility().
{
        pointsVisible = visibility;
        layerPoints.setVisible(visibility);
        if(!visibility)
            layerPointCanvas.setVisible(false);
    }
void moa.gui.visualization.StreamPanel.setZoom (int x, int y, int zoom_delta, JScrollPane scrollPane)
Definition at line 344 of file StreamPanel.java.
References moa.gui.visualization.StreamPanel.height_org, moa.gui.visualization.StreamPanel.width_org, moa.gui.visualization.StreamPanel.zoom, and moa.gui.visualization.StreamPanel.zoom_factor.
{
        if(zoom ==1){
            width_org = getWidth();
            height_org = getHeight();
        }
        zoom+=zoom_delta;
        if(zoom<1) zoom = 1;
        else{
            int size = (int)(Math.min(width_org, height_org)*zoom_factor*zoom);
            setSize(new Dimension(size*zoom, size*zoom));
            setPreferredSize(new Dimension(size*zoom, size*zoom));
            scrollPane.getViewport().setViewPosition(new Point((int)(x*zoom_factor*zoom+x),(int)( y*zoom_factor*zoom+y)));
        }
    }
Member Data Documentation
int moa.gui.visualization.StreamPanel.activeXDim = 0 [private]
Definition at line 68 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.getActiveXDim().
int moa.gui.visualization.StreamPanel.activeYDim = 1 [private]
Definition at line 69 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.getActiveYDim().
boolean moa.gui.visualization.StreamPanel.ANTIALIAS = false [private]
Definition at line 81 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.drawPoint().
int moa.gui.visualization.StreamPanel.height_org [private]
Definition at line 67 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.setZoom().
ClusterPanel moa.gui.visualization.StreamPanel.highlighted_cluster = null [private]
Definition at line 63 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.formMouseClicked(), moa.gui.visualization.StreamPanel.getHighlightedClusterPanel(), and moa.gui.visualization.StreamPanel.setHighlightedClusterPanel().
JPanel moa.gui.visualization.StreamPanel.layerGroundTruth [private]
Definition at line 75 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawGTClustering(), moa.gui.visualization.StreamPanel.screenshot(), moa.gui.visualization.StreamPanel.setGroundTruthLayerVisibility(), and moa.gui.visualization.StreamPanel.StreamPanel().
JPanel moa.gui.visualization.StreamPanel.layerMacro [private]
Definition at line 74 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawMacroClustering(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.gui.visualization.StreamPanel.screenshot(), moa.gui.visualization.StreamPanel.setMacroLayerVisibility(), and moa.gui.visualization.StreamPanel.StreamPanel().
JPanel moa.gui.visualization.StreamPanel.layerMicro [private]
Definition at line 73 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawMicroClustering(), moa.gui.visualization.StreamPanel.screenshot(), moa.gui.visualization.StreamPanel.setMicroLayerVisibility(), and moa.gui.visualization.StreamPanel.StreamPanel().
pointCanvasPanel moa.gui.visualization.StreamPanel.layerPointCanvas [private]
Definition at line 79 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.applyDrawDecay(), moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawClustering(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.StreamPanel.drawPointPanels(), moa.gui.visualization.StreamPanel.setPointVisibility(), and moa.gui.visualization.StreamPanel.StreamPanel().
JPanel moa.gui.visualization.StreamPanel.layerPoints [private]
Definition at line 72 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.StreamPanel.drawPointPanels(), moa.gui.visualization.StreamPanel.screenshot(), moa.gui.visualization.StreamPanel.setPointVisibility(), and moa.gui.visualization.StreamPanel.StreamPanel().
BufferedImage moa.gui.visualization.StreamPanel.pointCanvas [private]
Definition at line 78 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.applyDrawDecay(), moa.gui.visualization.StreamPanel.componentResized(), moa.gui.visualization.StreamPanel.drawClustering(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), and moa.gui.visualization.StreamPanel.drawPoint().
boolean moa.gui.visualization.StreamPanel.pointsVisible = true [private]
Definition at line 80 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.drawClustering(), moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.StreamPanel.drawPointPanels(), and moa.gui.visualization.StreamPanel.setPointVisibility().
final long moa.gui.visualization.StreamPanel.serialVersionUID = 1L [static, private]
Definition at line 61 of file StreamPanel.java.
int moa.gui.visualization.StreamPanel.width_org [private]
Definition at line 66 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.setZoom().
int moa.gui.visualization.StreamPanel.zoom = 1 [private]
Definition at line 65 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.setZoom().
double moa.gui.visualization.StreamPanel.zoom_factor = 0.2 [private]
Definition at line 64 of file StreamPanel.java.
Referenced by moa.gui.visualization.StreamPanel.setZoom().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/StreamPanel.java