MOA: moa.recommender.dataset.impl.JesterDataset Class Reference
moa.recommender.dataset.impl.JesterDataset Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void init ()
boolean next ()
String toString ()
Returns a description of the object.
int curUserID ()
int curItemID ()
double curRating ()
void reset ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
FileOption fileOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Private Attributes
String strLine
BufferedReader br
Detailed Description
Definition at line 38 of file JesterDataset.java.
Member Function Documentation
int moa.recommender.dataset.impl.JesterDataset.curItemID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 88 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        return Integer.valueOf(split[1]);
    }
double moa.recommender.dataset.impl.JesterDataset.curRating ()
Implements moa.recommender.dataset.Dataset.
Definition at line 94 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        double rating = Double.valueOf(split[2]);
        return (rating / 10) * 2 + 3;
    }
int moa.recommender.dataset.impl.JesterDataset.curUserID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 82 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        return Integer.valueOf(split[0]);
    }
void moa.recommender.dataset.impl.JesterDataset.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 119 of file JesterDataset.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.recommender.dataset.impl.JesterDataset.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 52 of file JesterDataset.java.
{
        return "A Jester Dataset reader.";
    }
void moa.recommender.dataset.impl.JesterDataset.init ()
Definition at line 56 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.br, moa.recommender.dataset.impl.JesterDataset.fileOption, and moa.options.FileOption.getFile().
Referenced by moa.recommender.dataset.impl.JesterDataset.prepareForUseImpl(), and moa.recommender.dataset.impl.JesterDataset.reset().
                       {
        FileInputStream fstream = null;
        try {
            fstream = new FileInputStream(this.fileOption.getFile());
            DataInputStream in = new DataInputStream(fstream);
            br = new BufferedReader(new InputStreamReader(in));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MovielensDataset.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
boolean moa.recommender.dataset.impl.JesterDataset.next ()
Implements moa.recommender.dataset.Dataset.
Definition at line 68 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.br, and moa.recommender.dataset.impl.JesterDataset.strLine.
{
        try {
            return (strLine = br.readLine()) != null;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }
void moa.recommender.dataset.impl.JesterDataset.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 114 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.init().
{
        this.init();
    }
void moa.recommender.dataset.impl.JesterDataset.reset ()
Implements moa.recommender.dataset.Dataset.
Definition at line 101 of file JesterDataset.java.
References moa.recommender.dataset.impl.JesterDataset.br, and moa.recommender.dataset.impl.JesterDataset.init().
{
        try {
            br.close();
            //FileInputStream fstream = new FileInputStream("/home/alicia/datasets/jester/jester_ratings.dat");
            //DataInputStream in = new DataInputStream(fstream);
            //br = new BufferedReader(new InputStreamReader(in));
            this.init();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
String moa.recommender.dataset.impl.JesterDataset.toString ()
Returns a description of the object.
Returns:
a description of the object
Reimplemented from moa.AbstractMOAObject.
Definition at line 77 of file JesterDataset.java.
{
        return "Jester";
    }
Member Data Documentation
BufferedReader moa.recommender.dataset.impl.JesterDataset.br [private]
Definition at line 41 of file JesterDataset.java.
Referenced by moa.recommender.dataset.impl.JesterDataset.init(), moa.recommender.dataset.impl.JesterDataset.next(), and moa.recommender.dataset.impl.JesterDataset.reset().
FileOption moa.recommender.dataset.impl.JesterDataset.fileOption
Initial value:
 new FileOption("file", 'f',
            "File to load.", "/home/alicia/datasets/jester/jester_ratings.dat", "dat", false)
Definition at line 42 of file JesterDataset.java.
Referenced by moa.recommender.dataset.impl.JesterDataset.init().
String moa.recommender.dataset.impl.JesterDataset.strLine [private]
Definition at line 40 of file JesterDataset.java.
Referenced by moa.recommender.dataset.impl.JesterDataset.curItemID(), moa.recommender.dataset.impl.JesterDataset.curRating(), moa.recommender.dataset.impl.JesterDataset.curUserID(), and moa.recommender.dataset.impl.JesterDataset.next().
The documentation for this class was generated from the following file:
main/java/moa/recommender/dataset/impl/JesterDataset.java