MOA: moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator Class Reference
moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator Class Reference
Public Member Functions
Estimator (double a)
void add (double value)
double estimation ()
Protected Attributes
double alpha
double estimation
Detailed Description
Definition at line 49 of file EWMAClassificationPerformanceEvaluator.java.
Constructor & Destructor Documentation
moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.Estimator (double a)
Definition at line 55 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.alpha, and moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.estimation().
{
            alpha = a;
            estimation = 0;
        }
Member Function Documentation
void moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.add (double value)
Definition at line 60 of file EWMAClassificationPerformanceEvaluator.java.
References moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.alpha, and moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.estimation().
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.addResult().
{
            estimation += alpha * (value - estimation);
        }
double moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.estimation ()
Definition at line 64 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.add(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.Estimator().
{
            return estimation;
        }
Member Data Documentation
double moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.alpha [protected]
Definition at line 51 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.add(), and moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.Estimator().
double moa.evaluation.EWMAClassificationPerformanceEvaluator.Estimator.estimation [protected]
Definition at line 53 of file EWMAClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.EWMAClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/EWMAClassificationPerformanceEvaluator.java