MOA: moa.evaluation.CMM_GTAnalysis.GTCluster Class Reference
moa.evaluation.CMM_GTAnalysis.GTCluster Class Reference
Main class to model the new clusters that will be the output of the cluster analysis.
Protected Member Functions
int getLabel ()
The original class label the cluster represents.
double getInclusionProbability (CMMPoint point)
Calculate the probability of the point being covered through the cluster.
Private Member Functions
GTCluster (int workclass, int label, int gtClusteringID)
void calculateKnn ()
calculate knn distances of points within own cluster + average knn distance and average knn distance deviation of all points
void calculateClusterConnection (int otherCid, boolean initial)
Calculate the connection of a cluster to this cluster.
void mergeCluster (int mergeID)
Merge a cluster into this cluster.
Private Attributes
ArrayList< Integer > points = new ArrayList<Integer>()
points that are per definition in the cluster
ArrayList< Integer > clusterRepresentations = new ArrayList<Integer>()
a new GT cluster consists of one or more "old" GT clusters.
int workclass
current work class (changes when merging)
final int orgWorkClass
original work class
final int label
original class label
ArrayList< Integer > mergedWorkLabels = null
clusters that have been merged into this cluster (debugging)
double knnMeanAvg = 0
average knn distance of all points in the cluster
double knnDevAvg = 0
average deviation of knn distance of all points
ArrayList< Double > connections = new ArrayList<Double>()
connectivity of the cluster to all other clusters
Detailed Description
Main class to model the new clusters that will be the output of the cluster analysis.
Definition at line 226 of file CMM_GTAnalysis.java.
Constructor & Destructor Documentation
moa.evaluation.CMM_GTAnalysis.GTCluster.GTCluster (int workclass, int label, int gtClusteringID) [private]
Definition at line 260 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.GTCluster.clusterRepresentations, and moa.evaluation.CMM_GTAnalysis.GTCluster.orgWorkClass.
{
           this.orgWorkClass = workclass;
           this.workclass = workclass;
           this.label = label;
           this.clusterRepresentations.add(gtClusteringID);
        }
Member Function Documentation
void moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection (int otherCid, boolean initial) [private]
Calculate the connection of a cluster to this cluster.
Parameters:
otherCid cluster id of the other cluster
initial flag for initial run
Definition at line 337 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.clusterConnectionMaxPoints, moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.GTCluster.connections, moa.evaluation.CMM_GTAnalysis.CMMPoint.connectivity, moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.evaluation.CMM_GTAnalysis.knnNeighbourhood, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.evaluation.CMM_GTAnalysis.GTCluster.points, moa.gui.visualization.DataPoint.setMeasureValue(), moa.evaluation.CMM_GTAnalysis.tauConnection, and moa.evaluation.CMM_GTAnalysis.GTCluster.workclass.
{
            double avgConnection = 0;
            if(workclass==otherCid){
                avgConnection = 1;
            }
            else{
                AutoExpandVector<Double> kmax = new AutoExpandVector<Double>();
                AutoExpandVector<Integer> kmaxIndexes = new AutoExpandVector<Integer>();
                for(int p : points){
                    CMMPoint cmdp = cmmpoints.get(p);
                    double con_p_Cj = getConnectionValue(cmmpoints.get(p), otherCid);
                    double connection = cmdp.connectivity * con_p_Cj;
                    if(initial){
                        cmdp.p.setMeasureValue("Connection to C"+otherCid, con_p_Cj);
                    }
                    //connection
                    if(kmax.size() < clusterConnectionMaxPoints || connection > kmax.get(kmax.size()-1)){
                        int index = 0;
                        while(index < kmax.size() && connection < kmax.get(index)) {
                            index++;
                        }
                        kmax.add(index, connection);
                        kmaxIndexes.add(index, p);
                        if(kmax.size() > clusterConnectionMaxPoints){
                            kmax.remove(kmax.size()-1);
                            kmaxIndexes.add(kmaxIndexes.size()-1);
                        }
                    }
                }
                //connection
                for (int k = 0; k < kmax.size(); k++) {
                    avgConnection+= kmax.get(k);
                }
                avgConnection/=kmax.size();
            }
            if(otherCid<connections.size()){
                connections.set(otherCid, avgConnection);
            }
            else
                if(connections.size() == otherCid){
                    connections.add(avgConnection);
                }
                else
                    System.out.println("Something is going really wrong with the connection listing!"+knnNeighbourhood+" "+tauConnection);
        }
void moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn () [private]
calculate knn distances of points within own cluster + average knn distance and average knn distance deviation of all points
Definition at line 296 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.cmmpoints, moa.evaluation.CMM_GTAnalysis.getKnnInCluster(), moa.gui.visualization.DataPoint.isNoise(), moa.evaluation.CMM_GTAnalysis.GTCluster.knnDevAvg, moa.evaluation.CMM_GTAnalysis.CMMPoint.knnInCluster, moa.evaluation.CMM_GTAnalysis.CMMPoint.knnIndices, moa.evaluation.CMM_GTAnalysis.GTCluster.knnMeanAvg, moa.evaluation.CMM_GTAnalysis.knnNeighbourhood, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.evaluation.CMM_GTAnalysis.GTCluster.points, and moa.gui.visualization.DataPoint.setMeasureValue().
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
{
            for (int p0 : points) {
                CMMPoint cmdp = cmmpoints.get(p0);
                if(!cmdp.isNoise()){
                    AutoExpandVector<Double> knnDist = new AutoExpandVector<Double>();
                    AutoExpandVector<Integer> knnPointIndex = new AutoExpandVector<Integer>();
                    //calculate nearest neighbours
                    getKnnInCluster(cmdp, knnNeighbourhood, points, knnDist,knnPointIndex);
                    //TODO: What to do if we have less then k neighbours?
                    double avgKnn = 0;
                    for (int i = 0; i < knnDist.size(); i++) {
                        avgKnn+= knnDist.get(i);
                    }
                    if(knnDist.size()!=0)
                        avgKnn/=knnDist.size();
                    cmdp.knnInCluster = avgKnn;
                    cmdp.knnIndices = knnPointIndex;
                    cmdp.p.setMeasureValue("knnAvg", cmdp.knnInCluster);
                    knnMeanAvg+=avgKnn;
                    knnDevAvg+=Math.pow(avgKnn,2);
                }
            }
            knnMeanAvg=knnMeanAvg/(double)points.size();
            knnDevAvg=knnDevAvg/(double)points.size();
            double variance = knnDevAvg-Math.pow(knnMeanAvg,2.0);
            // Due to numerical errors, small negative values can occur.
            if (variance <= 0.0) variance = 1e-50;
            knnDevAvg = Math.sqrt(variance);
        }
double moa.evaluation.CMM_GTAnalysis.GTCluster.getInclusionProbability (CMMPoint point) [protected]
Calculate the probability of the point being covered through the cluster.
Parameters:
point to calculate the probability for
Returns:
probability of the point being covered through the cluster
Definition at line 281 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.GTCluster.clusterRepresentations, moa.cluster.Clustering.get(), and moa.evaluation.CMM_GTAnalysis.gtClustering.
{
            double prob = Double.MIN_VALUE;
            //check all cluster representatives for coverage
            for (int c = 0; c < clusterRepresentations.size(); c++) {
               double tmp_prob = gtClustering.get(clusterRepresentations.get(c)).getInclusionProbability(point);
               if(tmp_prob > prob) prob = tmp_prob;
            }
            return prob;
        }
int moa.evaluation.CMM_GTAnalysis.GTCluster.getLabel () [protected]
The original class label the cluster represents.
Returns:
original class label
Definition at line 272 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.GTCluster.label.
{
            return label;
        }
void moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster (int mergeID) [private]
Merge a cluster into this cluster.
Parameters:
mergeID the ID of the cluster to be merged
Definition at line 391 of file CMM_GTAnalysis.java.
References moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), moa.evaluation.CMM_GTAnalysis.GTCluster.clusterRepresentations, moa.evaluation.CMM_GTAnalysis.GTCluster.connections, moa.evaluation.CMM_GTAnalysis.debug, moa.evaluation.CMM_GTAnalysis.gt0Clusters, moa.evaluation.CMM_GTAnalysis.GTCluster.label, moa.evaluation.CMM_GTAnalysis.mapTrueLabelToWorkLabel, moa.evaluation.CMM_GTAnalysis.GTCluster.mergedWorkLabels, moa.evaluation.CMM_GTAnalysis.mergeMap, moa.evaluation.CMM_GTAnalysis.numGTClasses, moa.evaluation.CMM_GTAnalysis.GTCluster.orgWorkClass, moa.evaluation.CMM_GTAnalysis.GTCluster.points, and moa.evaluation.CMM_GTAnalysis.GTCluster.workclass.
{
            if(mergeID < gt0Clusters.size()){
                //track merging (debugging)
                for (int i = 0; i < numGTClasses; i++) {
                    if(mergeMap[i]==mergeID)
                        mergeMap[i]=workclass;
                    if(mergeMap[i]>mergeID)
                        mergeMap[i]--;
                }
                GTCluster gtcMerge  = gt0Clusters.get(mergeID);
                if(debug)
                    System.out.println("Merging C"+gtcMerge.workclass+" into C"+workclass+
                            " with Con "+connections.get(mergeID)+" / "+gtcMerge.connections.get(workclass));
                //update mapTrueLabelToWorkLabel
                mapTrueLabelToWorkLabel.put(gtcMerge.label, workclass);
                Iterator iterator = mapTrueLabelToWorkLabel.keySet().iterator();
                while (iterator.hasNext()) {
                    Integer key = (Integer)iterator.next();
                    //update pointer of already merged cluster
                    int value = mapTrueLabelToWorkLabel.get(key);
                    if(value == mergeID)
                        mapTrueLabelToWorkLabel.put(key, workclass);
                    if(value > mergeID)
                        mapTrueLabelToWorkLabel.put(key, value-1);
                }
                //merge points from B into A
                points.addAll(gtcMerge.points);
                clusterRepresentations.addAll(gtcMerge.clusterRepresentations);
                if(mergedWorkLabels==null){
                    mergedWorkLabels = new ArrayList<Integer>();
                }
                mergedWorkLabels.add(gtcMerge.orgWorkClass);
                if(gtcMerge.mergedWorkLabels!=null)
                    mergedWorkLabels.addAll(gtcMerge.mergedWorkLabels);
                gt0Clusters.remove(mergeID);
                //update workclass labels
                for(int c=mergeID; c < gt0Clusters.size(); c++){
                    gt0Clusters.get(c).workclass = c;
                }
                //update knn distances
                calculateKnn();
                for(int c=0; c < gt0Clusters.size(); c++){
                    gt0Clusters.get(c).connections.remove(mergeID);
                    //recalculate connection from other clusters to the new merged one
                    gt0Clusters.get(c).calculateClusterConnection(workclass,false);
                    //and from new merged one to other clusters
                    gt0Clusters.get(workclass).calculateClusterConnection(c,false);
                }
            }
            else{
                System.out.println("Merge indices are not valid");
            }
        }
Member Data Documentation
ArrayList<Integer> moa.evaluation.CMM_GTAnalysis.GTCluster.clusterRepresentations = new ArrayList<Integer>() [private]
a new GT cluster consists of one or more "old" GT clusters.
Connected/overlapping clusters cannot be merged directly because of the underlying cluster model. E.g. for merging two spherical clusters the new cluster sphere can cover a lot more space then two separate smaller spheres. To keep the original coverage we need to keep the orignal clusters and merge them on an abstract level.
Definition at line 236 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.getInclusionProbability(), moa.evaluation.CMM_GTAnalysis.GTCluster.GTCluster(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
ArrayList<Double> moa.evaluation.CMM_GTAnalysis.GTCluster.connections = new ArrayList<Double>() [private]
connectivity of the cluster to all other clusters
Definition at line 257 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
double moa.evaluation.CMM_GTAnalysis.GTCluster.knnDevAvg = 0 [private]
average deviation of knn distance of all points
Definition at line 254 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn().
double moa.evaluation.CMM_GTAnalysis.GTCluster.knnMeanAvg = 0 [private]
average knn distance of all points in the cluster
Definition at line 251 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn().
final int moa.evaluation.CMM_GTAnalysis.GTCluster.label [private]
original class label
Definition at line 245 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.getLabel(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
ArrayList<Integer> moa.evaluation.CMM_GTAnalysis.GTCluster.mergedWorkLabels = null [private]
clusters that have been merged into this cluster (debugging)
Definition at line 248 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
final int moa.evaluation.CMM_GTAnalysis.GTCluster.orgWorkClass [private]
original work class
Definition at line 242 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.GTCluster(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
ArrayList<Integer> moa.evaluation.CMM_GTAnalysis.GTCluster.points = new ArrayList<Integer>() [private]
points that are per definition in the cluster
Definition at line 228 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
int moa.evaluation.CMM_GTAnalysis.GTCluster.workclass [private]
current work class (changes when merging)
Definition at line 239 of file CMM_GTAnalysis.java.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), and moa.evaluation.CMM_GTAnalysis.GTCluster.mergeCluster().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/CMM_GTAnalysis.java