MOA: moa.tasks.EvaluateConceptDrift Class Reference
moa.tasks.EvaluateConceptDrift Class Reference
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
ClassOption evaluatorOption
IntOption instanceLimitOption
IntOption timeLimitOption
IntOption sampleFrequencyOption
FileOption dumpFileOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 48 of file EvaluateConceptDrift.java.
Member Function Documentation
Object moa.tasks.EvaluateConceptDrift.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 101 of file EvaluateConceptDrift.java.
References moa.AbstractMOAObject.copy(), moa.tasks.EvaluateConceptDrift.dumpFileOption, moa.evaluation.LearningCurve.entryToString(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluateConceptDrift.evaluatorOption, moa.tasks.ConceptDriftMainTask.getEventsList(), moa.streams.generators.cd.ConceptDriftGenerator.getEventsList(), moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.learners.ChangeDetectorLearner.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.EvaluateConceptDrift.instanceLimitOption, moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.EvaluateConceptDrift.learnerOption, moa.AbstractMOAObject.measureByteSize(), moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluateConceptDrift.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.ConceptDriftMainTask.setEventsList(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.AbstractClassifier.setModelContext(), moa.tasks.EvaluateConceptDrift.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluateConceptDrift.timeLimitOption, and moa.classifiers.AbstractClassifier.trainOnInstance().
{
        ChangeDetectorLearner learner = (ChangeDetectorLearner) getPreparedClassOption(this.learnerOption);
        ConceptDriftGenerator stream = (ConceptDriftGenerator) getPreparedClassOption(this.streamOption);
        this.setEventsList(stream.getEventsList());
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        LearningCurve learningCurve = new LearningCurve(
                "learning evaluation instances");
        learner.setModelContext(stream.getHeader());
        int maxInstances = this.instanceLimitOption.getValue();
        long instancesProcessed = 0;
        int maxSeconds = this.timeLimitOption.getValue();
        int secondsElapsed = 0;
        monitor.setCurrentActivity("Evaluating learner...", -1.0);
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        //File for output predictions
      /*  File outputPredictionFile = this.outputPredictionFileOption.getFile();
        PrintStream outputPredictionResultStream = null;
        if (outputPredictionFile != null) {
            try {
                if (outputPredictionFile.exists()) {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile, true), true);
                } else {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open prediction result file: " + outputPredictionFile, ex);
            }
        }*/
        boolean firstDump = true;
        boolean preciseCPUTiming = TimingUtils.enablePreciseTiming();
        long evaluateStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        long lastEvaluateStartTime = evaluateStartTime;
        double RAMHours = 0.0;
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))
                && ((maxSeconds < 0) || (secondsElapsed < maxSeconds))) {
            Instance trainInst = stream.nextInstance();
            Instance testInst = (Instance) trainInst.copy();
            int trueClass = (int) trainInst.classValue();
            //testInst.setClassMissing();
            double[] prediction = learner.getVotesForInstance(testInst);
            if (prediction[0] ==1 ){ //Change detected
                this.getEventsList().add(new ClusterEvent(this, instancesProcessed, "Detected Change", "Drift"));
            }
            // Output prediction
           /* if (outputPredictionFile != null) {
                outputPredictionResultStream.println(Utils.maxIndex(prediction) + "," + trueClass);
            }*/
            //evaluator.addClassificationAttempt(trueClass, prediction, testInst.weight());
            evaluator.addResult(testInst, prediction);
            learner.trainOnInstance(trainInst);
            instancesProcessed++;
            if (instancesProcessed % this.sampleFrequencyOption.getValue() == 0
                    || stream.hasMoreInstances() == false) {
                long evaluateTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
                double time = TimingUtils.nanoTimeToSeconds(evaluateTime - evaluateStartTime);
                double timeIncrement = TimingUtils.nanoTimeToSeconds(evaluateTime - lastEvaluateStartTime);
                double RAMHoursIncrement = learner.measureByteSize() / (1024.0 * 1024.0 * 1024.0); //GBs
                RAMHoursIncrement *= (timeIncrement / 3600.0); //Hours
                RAMHours += RAMHoursIncrement;
                lastEvaluateStartTime = evaluateTime;
                learningCurve.insertEntry(new LearningEvaluation(
                        new Measurement[]{
                            new Measurement(
                            "learning evaluation instances",
                            instancesProcessed),
                            new Measurement(
                            "evaluation time ("
                            + (preciseCPUTiming ? "cpu "
                            : "") + "seconds)",
                            time),
                            new Measurement(
                            "model cost (RAM-Hours)",
                            RAMHours)
                        },
                        evaluator, learner));
                if (immediateResultStream != null) {
                    if (firstDump) {
                        immediateResultStream.println(learningCurve.headerToString());
                        firstDump = false;
                    }
                    immediateResultStream.println(learningCurve.entryToString(learningCurve.numEntries() - 1));
                    immediateResultStream.flush();
                }
            }
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) instancesProcessed
                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.copy());
                }
                secondsElapsed = (int) TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                        - evaluateStartTime);
            }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
       /* if (outputPredictionResultStream != null) {
            outputPredictionResultStream.close();
        }*/
        return learningCurve;
    }
String moa.tasks.EvaluateConceptDrift.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 52 of file EvaluateConceptDrift.java.
{
        return "Evaluates a classifier on a stream by testing then training with each example in sequence.";
    }
Class<?> moa.tasks.EvaluateConceptDrift.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 95 of file EvaluateConceptDrift.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FileOption moa.tasks.EvaluateConceptDrift.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv results to.", null, "csv", true)
Definition at line 88 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
ClassOption moa.tasks.EvaluateConceptDrift.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "BasicConceptDriftPerformanceEvaluator")
Definition at line 65 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
IntOption moa.tasks.EvaluateConceptDrift.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            1000, -1, Integer.MAX_VALUE)
Definition at line 70 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
ClassOption moa.tasks.EvaluateConceptDrift.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Change detector to train.", ChangeDetectorLearner.class, "ChangeDetectorLearner")
Definition at line 58 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
IntOption moa.tasks.EvaluateConceptDrift.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            10, 0, Integer.MAX_VALUE)
Definition at line 78 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
final long moa.tasks.EvaluateConceptDrift.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 56 of file EvaluateConceptDrift.java.
ClassOption moa.tasks.EvaluateConceptDrift.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", ConceptDriftGenerator.class,
            "GradualChangeGenerator")
Definition at line 61 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
IntOption moa.tasks.EvaluateConceptDrift.timeLimitOption
Initial value:
 new IntOption("timeLimit", 't',
            "Maximum number of seconds to test/train for (-1 = no limit).", -1,
            -1, Integer.MAX_VALUE)
Definition at line 74 of file EvaluateConceptDrift.java.
Referenced by moa.tasks.EvaluateConceptDrift.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateConceptDrift.java