MOA: moa.classifiers.trees.HoeffdingTree.LearningNode Class Reference
moa.classifiers.trees.HoeffdingTree.LearningNode Class Reference
Public Member Functions
LearningNode (double[] initialClassObservations)
abstract void learnFromInstance (Instance inst, HoeffdingTree ht)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 358 of file HoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingTree.LearningNode.LearningNode (double[] initialClassObservations)
Definition at line 362 of file HoeffdingTree.java.
{
            super(initialClassObservations);
        }
Member Function Documentation
abstract void moa.classifiers.trees.HoeffdingTree.LearningNode.learnFromInstance (Instance inst, HoeffdingTree ht) [pure virtual]
Implemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.rules.core.RuleActiveLearningNode, moa.classifiers.trees.HoeffdingTree.InactiveLearningNode, moa.classifiers.trees.HoeffdingTree.ActiveLearningNode, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Referenced by moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl(), moa.classifiers.trees.FIMTDD.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
Member Data Documentation
final long moa.classifiers.trees.HoeffdingTree.LearningNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.rules.core.RuleActiveLearningNode, moa.classifiers.rules.core.RuleActiveRegressionNode, moa.classifiers.trees.HoeffdingTree.InactiveLearningNode, moa.classifiers.trees.HoeffdingTree.ActiveLearningNode, moa.classifiers.trees.HoeffdingTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Definition at line 360 of file HoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingTree.java