MOA: moa.clusterers.outliers.MCOD.Test Class Reference
moa.clusterers.outliers.MCOD.Test Class Reference
Static Public Member Functions
static void main (String[] args) throws Exception
Detailed Description
Definition at line 27 of file Test.java.
Member Function Documentation
static void moa.clusterers.outliers.MCOD.Test.main (String[] args) throws Exception [static]
Definition at line 28 of file Test.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.getHeader(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.hasMoreInstances(), moa.clusterers.outliers.MCOD.MCOD.MCOD(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.options.AbstractOptionHandler.prepareForUse(), moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), moa.clusterers.AbstractClusterer.setModelContext(), and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
    {
        //if (true) return;
        int numInstances = 50000;
        //moa.streams.ArffFileStream stream = new ArffFileStream("./datasets/debug_2.txt", -1);
        RandomRBFGeneratorEvents stream = new RandomRBFGeneratorEvents();
        stream.prepareForUse();
        MCOD myOutlierDetector= new MCOD();
        /*myOutlierDetector.kOption.setValue(3);
        myOutlierDetector.radiusOption.setValue(5);
        myOutlierDetector.windowSizeOption.setValue(6);*/
        myOutlierDetector.setModelContext(stream.getHeader());
        myOutlierDetector.prepareForUse();
        Long tmStart = System.currentTimeMillis();
        int numberSamples = 0;
        int w = myOutlierDetector.windowSizeOption.getValue();
        while (stream.hasMoreInstances() && (numberSamples < numInstances)) {
            Instance newInst = stream.nextInstance();
            myOutlierDetector.processNewInstanceImpl(newInst);
            numberSamples++;
            if (numberSamples % 100 == 0) {
                //System.out.println("Processed " + numberSamples + " stream objects.");
            }
            if ((numberSamples % (w / 2)) == 0) {
                //myOutlierDetector.PrintOutliers();
            }
        }
        //myOutlierDetector.PrintOutliers();
        System.out.println("Total time = " + (System.currentTimeMillis() - tmStart) + " ms");
    }
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/Test.java