MOA: moa.classifiers.functions.NoChangeTest Class Reference
moa.classifiers.functions.NoChangeTest Class Reference
Tests the NoChange classifier.
Public Member Functions
NoChangeTest (String name)
Constructs the test case.
Static Public Member Functions
static Test suite ()
Returns a test suite.
static void main (String[] args)
Runs the test from commandline.
Protected Member Functions
Classifier[] getRegressionClassifierSetups ()
Returns the classifier setups to use in the regression test.
Detailed Description
Tests the NoChange classifier.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 35 of file NoChangeTest.java.
Constructor & Destructor Documentation
moa.classifiers.functions.NoChangeTest.NoChangeTest (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 43 of file NoChangeTest.java.
References moa.classifiers.AbstractMultipleClassifierTestCase.setNumberTests().
{
    super(name);
    this.setNumberTests(1);
  }
Member Function Documentation
Classifier [] moa.classifiers.functions.NoChangeTest.getRegressionClassifierSetups () [protected, virtual]
Returns the classifier setups to use in the regression test.
Returns:
the setups
Implements moa.classifiers.AbstractMultipleClassifierTestCase.
Definition at line 54 of file NoChangeTest.java.
{
    return new Classifier[]{
    new NoChange(),
    };
  }
static void moa.classifiers.functions.NoChangeTest.main (String[] args) [static]
Runs the test from commandline.
Parameters:
args ignored
Definition at line 74 of file NoChangeTest.java.
References moa.test.MoaTestCase.runTest(), and moa.classifiers.functions.NoChangeTest.suite().
{
    runTest(suite());
  }
static Test moa.classifiers.functions.NoChangeTest.suite () [static]
Returns a test suite.
Returns:
the test suite
Definition at line 65 of file NoChangeTest.java.
Referenced by moa.classifiers.functions.NoChangeTest.main().
{
    return new TestSuite(NoChangeTest.class);
  }
The documentation for this class was generated from the following file:
test/java/moa/classifiers/functions/NoChangeTest.java