MOA: moa.gui.ClassOptionEditComponent Class Reference
moa.gui.ClassOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a class option.
Public Member Functions
ClassOptionEditComponent (ClassOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void editObject ()
void addChangeListener (ChangeListener l)
Adds the listener to the internal set of listeners.
void removeChangeListener (ChangeListener l)
Removes the listener from the internal set of listeners.
Protected Member Functions
void notifyChangeListeners ()
Notifies all registered change listeners that the options have changed.
Protected Attributes
ClassOption editedOption
JTextField textField = new JTextField()
JButton editButton = new JButton("Edit")
HashSet< ChangeListener > changeListeners = new HashSet<ChangeListener>()
listeners that listen to changes to the chosen option.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a class option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 44 of file ClassOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.ClassOptionEditComponent.ClassOptionEditComponent (ClassOption option)
Definition at line 58 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.editButton, moa.gui.ClassOptionEditComponent.editedOption, moa.gui.ClassOptionEditComponent.editObject(), moa.options.ClassOption.getValueAsCLIString(), moa.gui.ClassOptionEditComponent.notifyChangeListeners(), moa.gui.ClassOptionEditComponent.setEditState(), and moa.gui.ClassOptionEditComponent.textField.
{
        this.editedOption = option;
        this.textField.setEditable(false);
        this.textField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
        });
        setLayout(new BorderLayout());
        add(this.textField, BorderLayout.CENTER);
        add(this.editButton, BorderLayout.EAST);
        this.editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                editObject();
            }
        });
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.ClassOptionEditComponent.addChangeListener (ChangeListener l)
Adds the listener to the internal set of listeners.
Gets notified when the option string changes.
Parameters:
l the listener to add
Definition at line 119 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.changeListeners.
Referenced by weka.gui.MOAClassOptionEditor.createCustomEditor().
{
        changeListeners.add(l);
    }
void moa.gui.ClassOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 92 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.editedOption, moa.options.ClassOption.setValueViaCLIString(), and moa.gui.ClassOptionEditComponent.textField.
Referenced by weka.gui.MOAClassOptionEditor.createCustomEditor().
{
        this.editedOption.setValueViaCLIString(this.textField.getText());
    }
void moa.gui.ClassOptionEditComponent.editObject ()
Definition at line 106 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.editedOption, moa.options.AbstractClassOption.getNullString(), moa.options.AbstractClassOption.getRequiredType(), moa.gui.ClassOptionEditComponent.setEditState(), and moa.gui.ClassOptionEditComponent.textField.
Referenced by moa.gui.ClassOptionEditComponent.ClassOptionEditComponent().
{
        setEditState(ClassOptionSelectionPanel.showSelectClassDialog(this,
                "Editing option: " + this.editedOption.getName(),
                this.editedOption.getRequiredType(), this.textField.getText(),
                this.editedOption.getNullString()));
    }
Option moa.gui.ClassOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 97 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.editedOption.
Referenced by weka.gui.MOAClassOptionEditor.createCustomEditor().
{
        return this.editedOption;
    }
void moa.gui.ClassOptionEditComponent.notifyChangeListeners () [protected]
Notifies all registered change listeners that the options have changed.
Definition at line 135 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.changeListeners.
Referenced by moa.gui.ClassOptionEditComponent.ClassOptionEditComponent().
{
        ChangeEvent e = new ChangeEvent(this);
        for (ChangeListener l : changeListeners) {
            l.stateChanged(e);
        }
    }
void moa.gui.ClassOptionEditComponent.removeChangeListener (ChangeListener l)
Removes the listener from the internal set of listeners.
Parameters:
l the listener to remove
Definition at line 128 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.changeListeners.
{
        changeListeners.remove(l);
    }
void moa.gui.ClassOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 102 of file ClassOptionEditComponent.java.
References moa.gui.ClassOptionEditComponent.textField.
Referenced by moa.gui.ClassOptionEditComponent.ClassOptionEditComponent(), and moa.gui.ClassOptionEditComponent.editObject().
{
        this.textField.setText(cliString);
    }
Member Data Documentation
HashSet<ChangeListener> moa.gui.ClassOptionEditComponent.changeListeners = new HashSet<ChangeListener>() [protected]
listeners that listen to changes to the chosen option.
Definition at line 56 of file ClassOptionEditComponent.java.
Referenced by moa.gui.ClassOptionEditComponent.addChangeListener(), moa.gui.ClassOptionEditComponent.notifyChangeListeners(), and moa.gui.ClassOptionEditComponent.removeChangeListener().
JButton moa.gui.ClassOptionEditComponent.editButton = new JButton("Edit") [protected]
Definition at line 53 of file ClassOptionEditComponent.java.
Referenced by moa.gui.ClassOptionEditComponent.ClassOptionEditComponent().
ClassOption moa.gui.ClassOptionEditComponent.editedOption [protected]
Definition at line 49 of file ClassOptionEditComponent.java.
Referenced by moa.gui.ClassOptionEditComponent.applyState(), moa.gui.ClassOptionEditComponent.ClassOptionEditComponent(), moa.gui.ClassOptionEditComponent.editObject(), and moa.gui.ClassOptionEditComponent.getEditedOption().
final long moa.gui.ClassOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 47 of file ClassOptionEditComponent.java.
JTextField moa.gui.ClassOptionEditComponent.textField = new JTextField() [protected]
Definition at line 51 of file ClassOptionEditComponent.java.
Referenced by moa.gui.ClassOptionEditComponent.applyState(), moa.gui.ClassOptionEditComponent.ClassOptionEditComponent(), moa.gui.ClassOptionEditComponent.editObject(), and moa.gui.ClassOptionEditComponent.setEditState().
The documentation for this class was generated from the following file:
main/java/moa/gui/ClassOptionEditComponent.java