MOA: moa.classifiers.core.driftdetection.ADWIN.List Class Reference
moa.classifiers.core.driftdetection.ADWIN.List Class Reference
Public Member Functions
List ()
int size ()
ListItem head ()
ListItem tail ()
boolean isEmpty ()
void clear ()
void addToHead ()
void removeFromHead ()
void addToTail ()
void removeFromTail ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
int count
ListItem head
ListItem tail
Detailed Description
Definition at line 37 of file ADWIN.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.ADWIN.List.List ()
Definition at line 45 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.addToHead(), and moa.classifiers.core.driftdetection.ADWIN.List.clear().
                      {
//          post: initializes the list to be empty.
            clear();
            addToHead();
        }
Member Function Documentation
void moa.classifiers.core.driftdetection.ADWIN.List.addToHead ()
Definition at line 80 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count, moa.classifiers.core.driftdetection.ADWIN.List.head(), and moa.classifiers.core.driftdetection.ADWIN.List.tail().
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.List().
{
            //   pre: anObject is non-null
            //   post: the object is added to the beginning of the list
            this.head = new ListItem(this.head, null);
            if (this.tail == null) {
                this.tail = this.head;
            }
            this.count++;
        }
void moa.classifiers.core.driftdetection.ADWIN.List.addToTail ()
Definition at line 106 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count, moa.classifiers.core.driftdetection.ADWIN.List.head(), and moa.classifiers.core.driftdetection.ADWIN.List.tail().
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets().
{
//          pre: anObject is non-null
//          post: the object is added at the end of the list
            this.tail = new ListItem(null, this.tail);
            if (this.head == null) {
                this.head = this.tail;
            }
            this.count++;
        }
void moa.classifiers.core.driftdetection.ADWIN.List.clear ()
Definition at line 72 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count, moa.classifiers.core.driftdetection.ADWIN.List.head(), and moa.classifiers.core.driftdetection.ADWIN.List.tail().
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.List().
{
            //   post: clears the list so that it contains no elements.
            this.head = null;
            this.tail = null;
            this.count = 0;
        }
void moa.classifiers.core.driftdetection.ADWIN.List.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 133 of file ADWIN.java.
{
        }
ListItem moa.classifiers.core.driftdetection.ADWIN.List.head ()
Definition at line 57 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.addToHead(), moa.classifiers.core.driftdetection.ADWIN.List.addToTail(), moa.classifiers.core.driftdetection.ADWIN.List.clear(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead(), and moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail().
{
            //  post: returns the number of elements in the list.
            return this.head;
        }
boolean moa.classifiers.core.driftdetection.ADWIN.List.isEmpty ()
Definition at line 67 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.size().
{
            //   post: returns the true iff store is empty.
            return (this.size() == 0);
        }
void moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead ()
Definition at line 90 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count, moa.classifiers.core.driftdetection.ADWIN.List.head(), moa.classifiers.core.driftdetection.ADWIN.ListItem.next, moa.classifiers.core.driftdetection.ADWIN.ListItem.setPrevious(), and moa.classifiers.core.driftdetection.ADWIN.List.tail().
{
            //       pre: list is not empty
            //       post: removes and returns first object from the list
//          ListItem temp;
//          temp = this.head;
            this.head = this.head.next();
            if (this.head != null) {
                this.head.setPrevious(null);
            } else {
                this.tail = null;
            }
            this.count--;
            //temp=null;
            return;
        }
void moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail ()
Definition at line 116 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count, moa.classifiers.core.driftdetection.ADWIN.List.head(), moa.classifiers.core.driftdetection.ADWIN.ListItem.previous, moa.classifiers.core.driftdetection.ADWIN.ListItem.setNext(), and moa.classifiers.core.driftdetection.ADWIN.List.tail().
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement().
{
//          pre: list is not empty
//          post: the last object in the list is removed and returned
//          ListItem temp;
//          temp = this.tail;
            this.tail = this.tail.previous();
            if (this.tail == null) {
                this.head = null;
            } else {
                this.tail.setNext(null);
            }
            this.count--;
            //temp=null;
            return;
        }
int moa.classifiers.core.driftdetection.ADWIN.List.size ()
Definition at line 52 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.count.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.isEmpty().
{
            //  post: returns the number of elements in the list.
            return this.count;
        }
ListItem moa.classifiers.core.driftdetection.ADWIN.List.tail ()
Definition at line 62 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.addToHead(), moa.classifiers.core.driftdetection.ADWIN.List.addToTail(), moa.classifiers.core.driftdetection.ADWIN.List.clear(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead(), and moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail().
{
            //  post: returns the number of elements in the list.
            return this.tail;
        }
Member Data Documentation
int moa.classifiers.core.driftdetection.ADWIN.List.count [protected]
Definition at line 39 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.List.addToHead(), moa.classifiers.core.driftdetection.ADWIN.List.addToTail(), moa.classifiers.core.driftdetection.ADWIN.List.clear(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromHead(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail(), and moa.classifiers.core.driftdetection.ADWIN.List.size().
ListItem moa.classifiers.core.driftdetection.ADWIN.List.head [protected]
Definition at line 41 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), and moa.classifiers.core.driftdetection.ADWIN.insertElement().
ListItem moa.classifiers.core.driftdetection.ADWIN.List.tail [protected]
Definition at line 43 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/ADWIN.java