MOA: moa.classifiers.multilabel.HoeffdingTreeClassifLeaves Class Reference
moa.classifiers.multilabel.HoeffdingTreeClassifLeaves Class Reference
Hoeffding Tree that have a classifier at the leaves.
Classes
class LearningNodeClassifier
Public Member Functions
HoeffdingTreeClassifLeaves ()
Public Attributes
ClassOption learnerOption
Protected Member Functions
LearningNode newLearningNode (double[] initialClassObservations)
LearningNode newLearningNode (double[] initialClassObservations, Classifier cl)
void attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Hoeffding Tree that have a classifier at the leaves.
A Hoeffding tree is an incremental, anytime decision tree induction algorithm that is capable of learning from massive data streams, assuming that the distribution generating examples does not change over time.
Definition at line 41 of file HoeffdingTreeClassifLeaves.java.
Constructor & Destructor Documentation
moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.HoeffdingTreeClassifLeaves ()
Definition at line 93 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.trees.HoeffdingTree.removePoorAttsOption.
{
        this.removePoorAttsOption = null;
    }
Member Function Documentation
void moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 108 of file HoeffdingTreeClassifLeaves.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.computeHoeffdingBound(), moa.classifiers.trees.HoeffdingTree.deactivateLearningNode(), moa.classifiers.trees.HoeffdingTree.decisionNodeCount, moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.disableAttribute(), moa.classifiers.trees.HoeffdingTree.enforceTrackerLimit(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.classifiers.core.splitcriteria.SplitCriterion.getRangeOfMerit(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.options.FlagOption.isSet, moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.trees.HoeffdingTree.newLearningNode(), moa.classifiers.trees.HoeffdingTree.newSplitNode(), moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.trees.HoeffdingTree.Node.observedClassDistributionIsPure(), moa.classifiers.trees.HoeffdingTree.removePoorAttsOption, moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), moa.classifiers.trees.HoeffdingTree.splitConfidenceOption, moa.classifiers.trees.HoeffdingTree.splitCriterionOption, moa.classifiers.core.AttributeSplitSuggestion.splitTest, moa.classifiers.trees.HoeffdingTree.tieThresholdOption, and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        if (!node.observedClassDistributionIsPure()) {
            SplitCriterion splitCriterion = (SplitCriterion) getPreparedClassOption(this.splitCriterionOption);
            AttributeSplitSuggestion[] bestSplitSuggestions = node.getBestSplitSuggestions(splitCriterion, this);
            Arrays.sort(bestSplitSuggestions);
            boolean shouldSplit = false;
            if (bestSplitSuggestions.length < 2) {
                shouldSplit = bestSplitSuggestions.length > 0;
            } else {
                double hoeffdingBound = computeHoeffdingBound(splitCriterion.getRangeOfMerit(node.getObservedClassDistribution()),
                        this.splitConfidenceOption.getValue(), node.getWeightSeen());
                AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                AttributeSplitSuggestion secondBestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 2];
                if ((bestSuggestion.merit - secondBestSuggestion.merit > hoeffdingBound)
                        || (hoeffdingBound < this.tieThresholdOption.getValue())) {
                    shouldSplit = true;
                }
                // }
                if ((this.removePoorAttsOption != null)
                        && this.removePoorAttsOption.isSet()) {
                    Set<Integer> poorAtts = new HashSet<Integer>();
                    // scan 1 - add any poor to set
                    for (int i = 0; i < bestSplitSuggestions.length; i++) {
                        if (bestSplitSuggestions[i].splitTest != null) {
                            int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                            if (splitAtts.length == 1) {
                                if (bestSuggestion.merit
                                        - bestSplitSuggestions[i].merit > hoeffdingBound) {
                                    poorAtts.add(new Integer(splitAtts[0]));
                                }
                            }
                        }
                    }
                    // scan 2 - remove good ones from set
                    for (int i = 0; i < bestSplitSuggestions.length; i++) {
                        if (bestSplitSuggestions[i].splitTest != null) {
                            int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                            if (splitAtts.length == 1) {
                                if (bestSuggestion.merit
                                        - bestSplitSuggestions[i].merit < hoeffdingBound) {
                                    poorAtts.remove(new Integer(splitAtts[0]));
                                }
                            }
                        }
                    }
                    for (int poorAtt : poorAtts) {
                        node.disableAttribute(poorAtt);
                    }
                }
            }
            if (shouldSplit) {
                AttributeSplitSuggestion splitDecision = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                if (splitDecision.splitTest == null) {
                    // preprune - null wins
                    deactivateLearningNode(node, parent, parentIndex);
                } else {
                    SplitNode newSplit = newSplitNode(splitDecision.splitTest,
                            node.getObservedClassDistribution());
                    for (int i = 0; i < splitDecision.numSplits(); i++) {
                        //Unique Change of HoeffdingTree
                        Node newChild = newLearningNode(splitDecision.resultingClassDistributionFromSplit(i), ((LearningNodeClassifier) node).getClassifier());
                        newSplit.setChild(i, newChild);
                    }
                    this.activeLeafNodeCount--;
                    this.decisionNodeCount++;
                    this.activeLeafNodeCount += splitDecision.numSplits();
                    if (parent == null) {
                        this.treeRoot = newSplit;
                    } else {
                        parent.setChild(parentIndex, newSplit);
                    }
                }
                // manage memory
                enforceTrackerLimit();
            }
        }
    }
LearningNode moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.newLearningNode (double[] initialClassObservations, Classifier cl) [protected]
Reimplemented in moa.classifiers.multilabel.MultilabelHoeffdingTree.
Definition at line 103 of file HoeffdingTreeClassifLeaves.java.
{
        return new LearningNodeClassifier(initialClassObservations, cl, this);
    }
LearningNode moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.newLearningNode (double[] initialClassObservations) [protected]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Reimplemented in moa.classifiers.multilabel.MultilabelHoeffdingTree.
Definition at line 98 of file HoeffdingTreeClassifLeaves.java.
{
        return new LearningNodeClassifier(initialClassObservations, null, this);
    }
Member Data Documentation
ClassOption moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.learnerOption
Initial value:
 new ClassOption("learner", 'a',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Definition at line 45 of file HoeffdingTreeClassifLeaves.java.
Referenced by moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier(), and moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier().
final long moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Reimplemented in moa.classifiers.multilabel.MultilabelHoeffdingTree.
Definition at line 43 of file HoeffdingTreeClassifLeaves.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/multilabel/HoeffdingTreeClassifLeaves.java