MOA: moa.evaluation.General Class Reference
moa.evaluation.General Class Reference
Public Member Functions
General ()
void evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception
Protected Member Functions
String[] getNames ()
Private Member Functions
double computeOverlap ()
double computeCompactness ()
Private Attributes
int numPoints
int numFClusters
int numDims
double pointInclusionProbThreshold = 0.8
Clustering clustering
ArrayList< DataPoint > points
Detailed Description
Definition at line 30 of file General.java.
Constructor & Destructor Documentation
moa.evaluation.General.General ()
Definition at line 39 of file General.java.
                     {
        super();
    }
Member Function Documentation
double moa.evaluation.General.computeCompactness () [private]
Definition at line 139 of file General.java.
References moa.evaluation.General.clustering, moa.cluster.Clustering.get(), moa.cluster.Cluster.getInclusionProbability(), moa.cluster.SphereCluster.getRadius(), moa.evaluation.General.numDims, moa.evaluation.General.numFClusters, moa.evaluation.General.numPoints, moa.evaluation.General.pointInclusionProbThreshold, moa.evaluation.General.points, and moa.cluster.Cluster.setMeasureValue().
{
        if(numFClusters == 0) return 0;
        for (int c = 0; c < numFClusters; c++) {
            if(!(clustering.get(c) instanceof SphereCluster)){
                System.out.println("Compactness only supports Sphere Cluster. Found: "+clustering.get(c).getClass());
                return Double.NaN;
            }
        }
        //TODO weight radius by number of dimensions
        double totalCompactness = 0;
        for (int c = 0; c < numFClusters; c++) {
            ArrayList<Instance> containedPoints = new ArrayList<Instance>();
            for (int p = 0; p < numPoints; p++) {
                //p in c
                if(clustering.get(c).getInclusionProbability(points.get(p)) >= pointInclusionProbThreshold){
                    containedPoints.add(points.get(p));
                }
            }
            double compactness = 0;
            if(containedPoints.size()>1){
                //cluster not empty
                SphereCluster minEnclosingCluster = new SphereCluster(containedPoints, numDims);
                double minRadius = minEnclosingCluster.getRadius();
                double cfRadius = ((SphereCluster)clustering.get(c)).getRadius();
                if(Math.abs(minRadius-cfRadius) < 0.1e-10){
                    compactness = 1;
                }
                else
                    if(minRadius < cfRadius)
                        compactness = minRadius/cfRadius;
                    else{
                        System.out.println("Optimal radius bigger then real one ("+(cfRadius-minRadius)+"), this is really wrong");
                        compactness = 1;
                    }
            }
            else{
                double cfRadius = ((SphereCluster)clustering.get(c)).getRadius();
                if(cfRadius==0) compactness = 1;
            }
            //weight by weight of cluster???
            totalCompactness+=compactness;
            clustering.get(c).setMeasureValue("Compactness", Double.toString(compactness));
        }
        return (totalCompactness/numFClusters);
    }
double moa.evaluation.General.computeOverlap () [private]
Definition at line 105 of file General.java.
References moa.evaluation.General.clustering, moa.cluster.Clustering.get(), moa.evaluation.General.numFClusters, moa.cluster.SphereCluster.overlapRadiusDegree(), and moa.cluster.Clustering.size().
{
        for (int c = 0; c < numFClusters; c++) {
            if(!(clustering.get(c) instanceof SphereCluster)){
                System.out.println("Overlap only supports Sphere Cluster. Found: "+clustering.get(c).getClass());
                return Double.NaN;
            }
        }
        boolean[] overlap = new boolean[numFClusters];
        for (int c0 = 0; c0 < numFClusters; c0++) {
            if(overlap[c0]) continue;
            SphereCluster s0 = (SphereCluster)clustering.get(c0);
            for (int c1 = c0; c1 < clustering.size(); c1++) {
                if(c1 == c0) continue;
                SphereCluster s1 = (SphereCluster)clustering.get(c1);
                if(s0.overlapRadiusDegree(s1) > 0){
                    overlap[c0] = overlap[c1] = true;
                }
            }
        }
        double totalOverlap = 0;
        for (int c0 = 0; c0 < numFClusters; c0++) {
            if(overlap[c0])
                totalOverlap++;
        }
//        if(totalOverlap/(double)numFClusters > .8) RunVisualizer.pause();
        if(numFClusters>0) totalOverlap/=(double)numFClusters;
        return totalOverlap;
    }
void moa.evaluation.General.evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception [virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 58 of file General.java.
References moa.evaluation.MeasureCollection.addValue(), moa.evaluation.General.clustering, moa.cluster.Clustering.get(), moa.cluster.Cluster.getInclusionProbability(), moa.evaluation.General.numDims, moa.evaluation.General.numFClusters, moa.evaluation.General.numPoints, moa.evaluation.General.pointInclusionProbThreshold, moa.evaluation.General.points, and moa.cluster.Clustering.size().
{
        this.points = points;
        this.clustering = clustering;
        numPoints = points.size();
        numFClusters = clustering.size();
        numDims = points.get(0).numAttributes()-1;
        int totalRedundancy = 0;
        int trueCoverage = 0;
        int totalCoverage = 0;
        int numNoise = 0;
        for (int p = 0; p < numPoints; p++) {
            int coverage = 0;
            for (int c = 0; c < numFClusters; c++) {
                //contained in cluster c?
                if(clustering.get(c).getInclusionProbability(points.get(p)) >= pointInclusionProbThreshold){
                    coverage++;
                }
            }
            if(points.get(p).classValue()==-1){
                numNoise++;
            }
            else{
                if(coverage>0) trueCoverage++;
            }
            if(coverage>0) totalCoverage++;  //points covered by clustering (incl. noise)
            if(coverage>1) totalRedundancy++; //include noise
        }
        addValue("numCluster", clustering.size());
        addValue("numClasses", trueClustering.size());
        addValue("Redundancy", ((double)totalRedundancy/(double)numPoints));
        addValue("GPrecision", (totalCoverage==0?0:((double)trueCoverage/(double)(totalCoverage))));
        addValue("GRecall", ((double)trueCoverage/(double)(numPoints-numNoise)));
//        if(isEnabled(3)){
//            addValue("Compactness", computeCompactness());
//        }
//        if(isEnabled(3)){
//            addValue("Overlap", computeOverlap());
//        }
    }
String [] moa.evaluation.General.getNames () [protected, virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 45 of file General.java.
References moa.evaluation.MeasureCollection.names.
{
        String[] names = {"GPrecision","GRecall","Redundancy","numCluster","numClasses"};
        //String[] names = {"GPrecision","GRecall","Redundancy","Overlap","numCluster","numClasses","Compactness"};
        return names;
    }
Member Data Documentation
Clustering moa.evaluation.General.clustering [private]
Definition at line 35 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), moa.evaluation.General.computeOverlap(), and moa.evaluation.General.evaluateClustering().
int moa.evaluation.General.numDims [private]
Definition at line 33 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), and moa.evaluation.General.evaluateClustering().
int moa.evaluation.General.numFClusters [private]
Definition at line 32 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), moa.evaluation.General.computeOverlap(), and moa.evaluation.General.evaluateClustering().
int moa.evaluation.General.numPoints [private]
Definition at line 31 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), and moa.evaluation.General.evaluateClustering().
double moa.evaluation.General.pointInclusionProbThreshold = 0.8 [private]
Definition at line 34 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), and moa.evaluation.General.evaluateClustering().
ArrayList<DataPoint> moa.evaluation.General.points [private]
Definition at line 36 of file General.java.
Referenced by moa.evaluation.General.computeCompactness(), and moa.evaluation.General.evaluateClustering().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/General.java