MOA: moa.gui.clustertab.ClusteringSetupTab Class Reference
moa.gui.clustertab.ClusteringSetupTab Class Reference
Public Member Functions
ClusteringSetupTab ()
Creates new form ClusteringSetupTab.
AbstractClusterer getClusterer0 ()
AbstractClusterer getClusterer1 ()
ClusteringStream getStream0 ()
MeasureCollection[] getMeasures ()
TextViewerPanel getLogPanel ()
void addButtonActionListener (ActionListener l)
void toggleRunMode ()
void stopRun ()
Package Functions
void setClusteringTab (ClusteringTabPanel clusteringTab)
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void buttonImportSettingsActionPerformed (java.awt.event.ActionEvent evt)
void buttonExportSettingsActionPerformed (java.awt.event.ActionEvent evt)
void buttonStartActionPerformed (java.awt.event.ActionEvent evt)
void buttonStopActionPerformed (java.awt.event.ActionEvent evt)
void loadOptionsFromFile (String filepath)
void toggle (boolean internal)
void stop (boolean internal)
void setStateConfigButtons (boolean state)
Private Attributes
ClusteringTabPanel clusteringTab
String lastfile
javax.swing.JButton buttonExport
javax.swing.JButton buttonExportSettings
javax.swing.JButton buttonImportSettings
javax.swing.JButton buttonStart
javax.swing.JButton buttonStop
javax.swing.JButton buttonWeka
moa.gui.clustertab.ClusteringAlgoPanel clusteringAlgoPanel0
moa.gui.clustertab.ClusteringEvalPanel clusteringEvalPanel1
moa.gui.TextViewerPanel logPanel
Detailed Description
Definition at line 34 of file ClusteringSetupTab.java.
Constructor & Destructor Documentation
moa.gui.clustertab.ClusteringSetupTab.ClusteringSetupTab ()
Creates new form ClusteringSetupTab.
Definition at line 39 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, moa.gui.clustertab.ClusteringSetupTab.initComponents(), and moa.gui.clustertab.ClusteringAlgoPanel.renderAlgoPanel().
Referenced by moa.gui.clustertab.ClusteringTabPanel.initComponents().
{
        initComponents();
        clusteringAlgoPanel0.renderAlgoPanel();
    }
Member Function Documentation
void moa.gui.clustertab.ClusteringSetupTab.addButtonActionListener (ActionListener l)
Definition at line 64 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.buttonExport, and moa.gui.clustertab.ClusteringSetupTab.buttonWeka.
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel().
{
        buttonWeka.addActionListener(l);
        buttonWeka.setActionCommand("weka export");
        buttonExport.addActionListener(l);
        buttonExport.setActionCommand("csv export");
    }
void moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 208 of file ClusteringSetupTab.java.
References moa.gui.TextViewerPanel.addText(), moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getAlgorithm1ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.getStreamValueAsCLIString(), and moa.gui.clustertab.ClusteringSetupTab.logPanel.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
                                                                                     {//GEN-FIRST:event_buttonExportSettingsActionPerformed
        StringBuffer sb = new StringBuffer();
        sb.append(clusteringAlgoPanel0.getStreamValueAsCLIString()+"\n");
        sb.append(clusteringAlgoPanel0.getAlgorithm0ValueAsCLIString()+"\n");
        sb.append(clusteringAlgoPanel0.getAlgorithm1ValueAsCLIString()+"\n");
        System.out.println(sb);
        logPanel.addText(sb.toString());
    }//GEN-LAST:event_buttonExportSettingsActionPerformed
void moa.gui.clustertab.ClusteringSetupTab.buttonImportSettingsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 195 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.lastfile, and moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
                                                                                     {//GEN-FIRST:event_buttonImportSettingsActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        fileChooser.addChoosableFileFilter(new FileExtensionFilter("txt"));
        if(lastfile!=null)
            fileChooser.setSelectedFile(new File(lastfile));
        if (fileChooser.showOpenDialog(this.buttonImportSettings) == JFileChooser.APPROVE_OPTION) {
            lastfile = fileChooser.getSelectedFile().getPath();
            loadOptionsFromFile(fileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_buttonImportSettingsActionPerformed
void moa.gui.clustertab.ClusteringSetupTab.buttonStartActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 219 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.toggle().
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
                                                                            {//GEN-FIRST:event_buttonStartActionPerformed
        toggle(true);
    }//GEN-LAST:event_buttonStartActionPerformed
void moa.gui.clustertab.ClusteringSetupTab.buttonStopActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 223 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.stop().
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents().
                                                                           {//GEN-FIRST:event_buttonStopActionPerformed
        stop(true);
    }//GEN-LAST:event_buttonStopActionPerformed
AbstractClusterer moa.gui.clustertab.ClusteringSetupTab.getClusterer0 ()
Definition at line 44 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, and moa.gui.clustertab.ClusteringAlgoPanel.getClusterer0().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return clusteringAlgoPanel0.getClusterer0();
    }
AbstractClusterer moa.gui.clustertab.ClusteringSetupTab.getClusterer1 ()
Definition at line 48 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, and moa.gui.clustertab.ClusteringAlgoPanel.getClusterer1().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return clusteringAlgoPanel0.getClusterer1();
    }
TextViewerPanel moa.gui.clustertab.ClusteringSetupTab.getLogPanel ()
Definition at line 60 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.logPanel.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return logPanel;
    }
MeasureCollection [] moa.gui.clustertab.ClusteringSetupTab.getMeasures ()
Definition at line 56 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.clusteringEvalPanel1, and moa.gui.clustertab.ClusteringEvalPanel.getSelectedMeasures().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return clusteringEvalPanel1.getSelectedMeasures();
    }
ClusteringStream moa.gui.clustertab.ClusteringSetupTab.getStream0 ()
Definition at line 52 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, and moa.gui.clustertab.ClusteringAlgoPanel.getStream().
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
{
        return clusteringAlgoPanel0.getStream();
    }
void moa.gui.clustertab.ClusteringSetupTab.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 77 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.buttonExport, moa.gui.clustertab.ClusteringSetupTab.buttonExportSettings, moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.buttonImportSettings, moa.gui.clustertab.ClusteringSetupTab.buttonImportSettingsActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.buttonStart, moa.gui.clustertab.ClusteringSetupTab.buttonStartActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.buttonStop, moa.gui.clustertab.ClusteringSetupTab.buttonStopActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.buttonWeka, moa.gui.clustertab.ClusteringAlgoPanel.ClusteringAlgoPanel(), moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, moa.gui.clustertab.ClusteringEvalPanel.ClusteringEvalPanel(), moa.gui.clustertab.ClusteringSetupTab.clusteringEvalPanel1, moa.gui.clustertab.ClusteringSetupTab.logPanel, moa.gui.clustertab.ClusteringAlgoPanel.setPanelTitle(), and moa.gui.TextViewerPanel.TextViewerPanel().
Referenced by moa.gui.clustertab.ClusteringSetupTab.ClusteringSetupTab().
{
        java.awt.GridBagConstraints gridBagConstraints;
        clusteringAlgoPanel0 = new moa.gui.clustertab.ClusteringAlgoPanel();
        clusteringEvalPanel1 = new moa.gui.clustertab.ClusteringEvalPanel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonExport = new javax.swing.JButton();
        buttonWeka = new javax.swing.JButton();
        buttonImportSettings = new javax.swing.JButton();
        buttonExportSettings = new javax.swing.JButton();
        logPanel = new moa.gui.TextViewerPanel();
        setLayout(new java.awt.GridBagLayout());
        clusteringAlgoPanel0.setMinimumSize(new java.awt.Dimension(335, 150));
        clusteringAlgoPanel0.setPanelTitle("Cluster Algorithm Setup");
        clusteringAlgoPanel0.setPreferredSize(new java.awt.Dimension(335, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(clusteringAlgoPanel0, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(clusteringEvalPanel1, gridBagConstraints);
        buttonStart.setText("Start");
        buttonStart.setPreferredSize(new java.awt.Dimension(80, 23));
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonStart, gridBagConstraints);
        buttonStop.setText("Stop");
        buttonStop.setEnabled(false);
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonStop, gridBagConstraints);
        buttonExport.setText("Export CSV");
        buttonExport.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonExport, gridBagConstraints);
        buttonWeka.setText("Weka Explorer");
        buttonWeka.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonWeka, gridBagConstraints);
        buttonImportSettings.setText("Import");
        buttonImportSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportSettingsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 75, 4, 4);
        add(buttonImportSettings, gridBagConstraints);
        buttonExportSettings.setText("Export");
        buttonExportSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportSettingsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonExportSettings, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(logPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile (String filepath) [private]
Definition at line 228 of file ClusteringSetupTab.java.
References moa.gui.TextViewerPanel.addText(), moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0, moa.gui.clustertab.ClusteringSetupTab.logPanel, moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm0ValueAsCLIString(), moa.gui.clustertab.ClusteringAlgoPanel.setAlgorithm1ValueAsCLIString(), and moa.gui.clustertab.ClusteringAlgoPanel.setStreamValueAsCLIString().
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonImportSettingsActionPerformed().
{
        try {
            BufferedReader in = new BufferedReader(new FileReader(filepath));
            String stream0 = in.readLine();
            clusteringAlgoPanel0.setStreamValueAsCLIString(stream0);
            String algo0 = in.readLine();
            clusteringAlgoPanel0.setAlgorithm0ValueAsCLIString(algo0);
            String algo1 = in.readLine();
            clusteringAlgoPanel0.setAlgorithm1ValueAsCLIString(algo1);
            System.out.println("Loading settings from "+filepath);
            logPanel.addText("Loading settings from "+filepath);
        } catch (Exception e) {
            System.out.println("Bad option file:"+e.getMessage());
        }
    }
void moa.gui.clustertab.ClusteringSetupTab.setClusteringTab (ClusteringTabPanel clusteringTab) [package]
Definition at line 262 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringTabPanel.ClusteringTabPanel().
{
        this.clusteringTab = clusteringTab;
    }
void moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons (boolean state) [private]
Definition at line 306 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.buttonExportSettings, moa.gui.clustertab.ClusteringSetupTab.buttonImportSettings, and moa.gui.clustertab.ClusteringSetupTab.buttonStop.
Referenced by moa.gui.clustertab.ClusteringSetupTab.stop(), and moa.gui.clustertab.ClusteringSetupTab.toggle().
{
        buttonStop.setEnabled(!state);
        buttonExportSettings.setEnabled(state);
        buttonImportSettings.setEnabled(state);
    }
void moa.gui.clustertab.ClusteringSetupTab.stop (boolean internal) [private]
Definition at line 293 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.buttonExport, moa.gui.clustertab.ClusteringSetupTab.buttonStart, moa.gui.clustertab.ClusteringSetupTab.buttonStop, moa.gui.clustertab.ClusteringSetupTab.buttonWeka, moa.gui.clustertab.ClusteringSetupTab.clusteringTab, moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons(), and moa.gui.clustertab.ClusteringTabPanel.stop().
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonStopActionPerformed(), and moa.gui.clustertab.ClusteringSetupTab.stopRun().
{
        buttonStart.setEnabled(true);
        buttonStart.setText("Start");
        buttonStop.setEnabled(false);
        buttonWeka.setEnabled(false);
        buttonExport.setEnabled(false);
        setStateConfigButtons(true);
        //push event forward to the cluster tab
        if(internal)
            clusteringTab.stop();
    }
void moa.gui.clustertab.ClusteringSetupTab.stopRun ()
Definition at line 270 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.stop().
{
        stop(false);
    }
void moa.gui.clustertab.ClusteringSetupTab.toggle (boolean internal) [private]
Definition at line 274 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.buttonExport, moa.gui.clustertab.ClusteringSetupTab.buttonStart, moa.gui.clustertab.ClusteringSetupTab.buttonWeka, moa.gui.clustertab.ClusteringSetupTab.clusteringTab, moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons(), and moa.gui.clustertab.ClusteringTabPanel.toggle().
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonStartActionPerformed(), and moa.gui.clustertab.ClusteringSetupTab.toggleRunMode().
{
        setStateConfigButtons(false);
        if(buttonStart.getText().equals("Pause")){
            buttonStart.setText("Resume");
            buttonWeka.setEnabled(true);
            buttonExport.setEnabled(true);
        }
        else{
            buttonStart.setText("Pause");
            buttonWeka.setEnabled(false);
            buttonExport.setEnabled(false);
        }
        //push event forward to the cluster tab
        if(internal)
            clusteringTab.toggle();
    }
void moa.gui.clustertab.ClusteringSetupTab.toggleRunMode ()
Definition at line 266 of file ClusteringSetupTab.java.
References moa.gui.clustertab.ClusteringSetupTab.toggle().
Referenced by moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
{
        toggle(false);
    }
Member Data Documentation
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonExport [private]
Definition at line 251 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.addButtonActionListener(), moa.gui.clustertab.ClusteringSetupTab.initComponents(), moa.gui.clustertab.ClusteringSetupTab.stop(), and moa.gui.clustertab.ClusteringSetupTab.toggle().
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonExportSettings [private]
Definition at line 252 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents(), and moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons().
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonImportSettings [private]
Definition at line 253 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents(), and moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons().
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonStart [private]
Definition at line 254 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents(), moa.gui.clustertab.ClusteringSetupTab.stop(), and moa.gui.clustertab.ClusteringSetupTab.toggle().
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonStop [private]
Definition at line 255 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.initComponents(), moa.gui.clustertab.ClusteringSetupTab.setStateConfigButtons(), and moa.gui.clustertab.ClusteringSetupTab.stop().
javax.swing.JButton moa.gui.clustertab.ClusteringSetupTab.buttonWeka [private]
Definition at line 256 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.addButtonActionListener(), moa.gui.clustertab.ClusteringSetupTab.initComponents(), moa.gui.clustertab.ClusteringSetupTab.stop(), and moa.gui.clustertab.ClusteringSetupTab.toggle().
moa.gui.clustertab.ClusteringAlgoPanel moa.gui.clustertab.ClusteringSetupTab.clusteringAlgoPanel0 [private]
Definition at line 257 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.ClusteringSetupTab(), moa.gui.clustertab.ClusteringSetupTab.getClusterer0(), moa.gui.clustertab.ClusteringSetupTab.getClusterer1(), moa.gui.clustertab.ClusteringSetupTab.getStream0(), moa.gui.clustertab.ClusteringSetupTab.initComponents(), and moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
moa.gui.clustertab.ClusteringEvalPanel moa.gui.clustertab.ClusteringSetupTab.clusteringEvalPanel1 [private]
Definition at line 258 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.getMeasures(), and moa.gui.clustertab.ClusteringSetupTab.initComponents().
ClusteringTabPanel moa.gui.clustertab.ClusteringSetupTab.clusteringTab [private]
Definition at line 35 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.stop(), and moa.gui.clustertab.ClusteringSetupTab.toggle().
String moa.gui.clustertab.ClusteringSetupTab.lastfile [private]
Definition at line 36 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonImportSettingsActionPerformed().
moa.gui.TextViewerPanel moa.gui.clustertab.ClusteringSetupTab.logPanel [private]
Definition at line 259 of file ClusteringSetupTab.java.
Referenced by moa.gui.clustertab.ClusteringSetupTab.buttonExportSettingsActionPerformed(), moa.gui.clustertab.ClusteringSetupTab.getLogPanel(), moa.gui.clustertab.ClusteringSetupTab.initComponents(), and moa.gui.clustertab.ClusteringSetupTab.loadOptionsFromFile().
The documentation for this class was generated from the following file:
main/java/moa/gui/clustertab/ClusteringSetupTab.java