MOA: moa.recommender.predictor.BRISMFPredictor Class Reference
moa.recommender.predictor.BRISMFPredictor Class Reference
Implementation of the algorithm described in Scalable Collaborative Filtering Approaches for Large Recommender Systems (Gábor Takács, István Pilászy, Bottyán Németh, and Domonkos Tikk).
Public Member Functions
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
double predictRating (Integer user, Integer item)
moa.recommender.rc.data.RecommenderData getData ()
double predictRating (int userID, int itemID)
List< Double > predictRatings (int userID, List< Integer > itemIDS)
void train ()
Public Attributes
IntOption featuresOption
FloatOption lRateOption
FloatOption rFactorOption
IntOption iterationsOption
ClassOption dataOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
moa.recommender.rc.predictor.impl.BRISMFPredictor rp
Detailed Description
Implementation of the algorithm described in Scalable Collaborative Filtering Approaches for Large Recommender Systems (Gábor Takács, István Pilászy, Bottyán Németh, and Domonkos Tikk).
A feature vector is learned for every user and item, so that the prediction of a rating is roughly the dot product of the corresponding user and item vector. Stochastic gradient descent is used to train the model, minimizing its prediction error. Both Tikhonov regularization and early stopping are used to reduce overfitting. The algorithm allows batch training (from scratch, using all ratings available at the moment) as well as incremental, by retraining only the affected user and item vectors when a new rating is inserted.
Parameters:
f: features - the number of features to be trained for each user and item
r: learning rate - the learning rate used in the regularization
a: ratio - the regularization ratio to be used in the Tikhonov regularization
i: iterations - the number of iterations to be used when retraining user and item features (online training). </lu>
Definition at line 60 of file BRISMFPredictor.java.
Member Function Documentation
moa.recommender.rc.data.RecommenderData moa.recommender.predictor.BRISMFPredictor.getData ()
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 100 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.getData(), and moa.recommender.predictor.BRISMFPredictor.rp.
Referenced by moa.recommender.predictor.BRISMFPredictor.getData().
{
        return rp.getData();
    }
void moa.recommender.predictor.BRISMFPredictor.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 92 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.rp, and moa.AbstractMOAObject.toString().
{
        sb.append(rp.toString());
    }
double moa.recommender.predictor.BRISMFPredictor.predictRating (int userID, int itemID)
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 105 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.predictRating(), and moa.recommender.predictor.BRISMFPredictor.rp.
{
        return rp.predictRating(userID, itemID);
    }
double moa.recommender.predictor.BRISMFPredictor.predictRating (Integer user, Integer item)
Definition at line 96 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.predictRating(), and moa.recommender.predictor.BRISMFPredictor.rp.
Referenced by moa.recommender.predictor.BRISMFPredictor.predictRating().
{
        return rp.predictRating(user,item);
    }
List<Double> moa.recommender.predictor.BRISMFPredictor.predictRatings (int userID, List< Integer > itemIDS)
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 110 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.predictRatings(), and moa.recommender.predictor.BRISMFPredictor.rp.
Referenced by moa.recommender.predictor.BRISMFPredictor.predictRatings().
{
        return rp.predictRatings(userID, itemIDS);
    }
void moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 85 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.dataOption, moa.recommender.predictor.BRISMFPredictor.featuresOption, moa.recommender.data.RecommenderData.getData(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.recommender.predictor.BRISMFPredictor.iterationsOption, moa.recommender.predictor.BRISMFPredictor.lRateOption, moa.recommender.predictor.BRISMFPredictor.rFactorOption, and moa.recommender.predictor.BRISMFPredictor.rp.
{
        RecommenderData data = (RecommenderData) getPreparedClassOption(this.dataOption);
        rp = new moa.recommender.rc.predictor.impl.BRISMFPredictor(featuresOption.getValue(), data.getData(), lRateOption.getValue(), rFactorOption.getValue(), false);
        rp.setNIterations(iterationsOption.getValue());
    }
void moa.recommender.predictor.BRISMFPredictor.train ()
Implements moa.recommender.predictor.RatingPredictor.
Definition at line 115 of file BRISMFPredictor.java.
References moa.recommender.predictor.BRISMFPredictor.rp, and moa.recommender.predictor.BRISMFPredictor.train().
Referenced by moa.recommender.predictor.BRISMFPredictor.train().
{
        rp.train();
    }
Member Data Documentation
ClassOption moa.recommender.predictor.BRISMFPredictor.dataOption
Initial value:
 new ClassOption("data", 'd',
            "Data", RecommenderData.class, "moa.recommender.data.MemRecommenderData")
Definition at line 80 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl().
IntOption moa.recommender.predictor.BRISMFPredictor.featuresOption
Initial value:
 new IntOption("features",
            'f',
            "How many features to use.",
            20, 0, Integer.MAX_VALUE)
Definition at line 64 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl().
IntOption moa.recommender.predictor.BRISMFPredictor.iterationsOption
Initial value:
 new IntOption("iterations",
            'i',
            "How many iterations to use.",
            100, 0, Integer.MAX_VALUE)
Definition at line 75 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl().
FloatOption moa.recommender.predictor.BRISMFPredictor.lRateOption
Initial value:
 new FloatOption("lRate",
            'r', "lRate", 0.001)
Definition at line 69 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl().
FloatOption moa.recommender.predictor.BRISMFPredictor.rFactorOption
Initial value:
 new FloatOption("rFactor",
            'a', "rFactor", 0.01)
Definition at line 72 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl().
moa.recommender.rc.predictor.impl.BRISMFPredictor moa.recommender.predictor.BRISMFPredictor.rp [protected]
Definition at line 62 of file BRISMFPredictor.java.
Referenced by moa.recommender.predictor.BRISMFPredictor.getData(), moa.recommender.predictor.BRISMFPredictor.getDescription(), moa.recommender.predictor.BRISMFPredictor.predictRating(), moa.recommender.predictor.BRISMFPredictor.predictRatings(), moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl(), and moa.recommender.predictor.BRISMFPredictor.train().
The documentation for this class was generated from the following file:
main/java/moa/recommender/predictor/BRISMFPredictor.java