MOA: moa.classifiers.meta.OnlineSmoothBoost Class Reference
moa.classifiers.meta.OnlineSmoothBoost Class Reference
Incremental on-line boosting with Theoretical Justifications of Shang-Tse Chen, Hsuan-Tien Lin and Chi-Jen Lu.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
FloatOption gammaOption
Protected Member Functions
double getEnsembleMemberWeight (int i)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
double[] alpha
double gamma
double theta
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Incremental on-line boosting with Theoretical Justifications of Shang-Tse Chen, Hsuan-Tien Lin and Chi-Jen Lu.
See details in:
Parameters:
-l : Classiﬁer to train
-s : The number of models to boost
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 44 of file OnlineSmoothBoost.java.
Member Function Documentation
double moa.classifiers.meta.OnlineSmoothBoost.getEnsembleMemberWeight (int i) [protected]
Definition at line 104 of file OnlineSmoothBoost.java.
References moa.classifiers.meta.OnlineSmoothBoost.alpha.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance().
{
        return this.alpha[i];
    }
void moa.classifiers.meta.OnlineSmoothBoost.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 132 of file OnlineSmoothBoost.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.OnlineSmoothBoost.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 137 of file OnlineSmoothBoost.java.
References moa.classifiers.meta.OnlineSmoothBoost.ensemble.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0)};
    }
String moa.classifiers.meta.OnlineSmoothBoost.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 49 of file OnlineSmoothBoost.java.
{
        return "Incremental on-line boosting of Shang-Tse Chen, Hsuan-Tien Lin and Chi-Jen Lu.";
    }
Classifier [] moa.classifiers.meta.OnlineSmoothBoost.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 143 of file OnlineSmoothBoost.java.
References moa.classifiers.meta.OnlineSmoothBoost.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 108 of file OnlineSmoothBoost.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.OnlineSmoothBoost.ensemble, moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.OnlineSmoothBoost.getEnsembleMemberWeight(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), and moa.core.DoubleVector.sumOfValues().
{
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            double memberWeight = getEnsembleMemberWeight(i);
            if (memberWeight > 0.0) {
                DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
                if (vote.sumOfValues() > 0.0) {
                    vote.normalize();
                    vote.scaleValues(memberWeight);
                    combinedVote.addValues(vote);
                }
            } else {
                break;
            }
        }
        return combinedVote.getArrayRef();
    }
boolean moa.classifiers.meta.OnlineSmoothBoost.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 127 of file OnlineSmoothBoost.java.
{
        return true;
    }
void moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 76 of file OnlineSmoothBoost.java.
References moa.classifiers.meta.OnlineSmoothBoost.alpha, moa.classifiers.meta.OnlineSmoothBoost.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.OnlineSmoothBoost.ensemble, moa.classifiers.meta.OnlineSmoothBoost.ensembleSizeOption, moa.classifiers.meta.OnlineSmoothBoost.gamma, moa.classifiers.meta.OnlineSmoothBoost.gammaOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.resetLearning(), and moa.classifiers.meta.OnlineSmoothBoost.theta.
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        this.alpha = new double[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
            this.alpha[i] = 1.0/ (double) this.ensemble.length;
        }
        this.gamma = this.gammaOption.getValue();
       this.theta = this.gamma/(2.0+this.gamma);
    }
void moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 90 of file OnlineSmoothBoost.java.
References moa.classifiers.Classifier.correctlyClassifies(), moa.classifiers.meta.OnlineSmoothBoost.ensemble, moa.classifiers.meta.OnlineSmoothBoost.gamma, moa.classifiers.meta.OnlineSmoothBoost.theta, and moa.classifiers.Classifier.trainOnInstance().
{
        double zt = 0.0;
        double weight = 1.0;
        for (int i = 0; i < this.ensemble.length; i++) {
            zt += (this.ensemble[i].correctlyClassifies(inst) ? 1 : -1) - theta;
                    //normalized_predict(ex.x) * ex.y - theta;
            Instance weightedInst = (Instance) inst.copy();
            weightedInst.setWeight(weight);
            this.ensemble[i].trainOnInstance(weightedInst);
            weight = (zt<=0)? 1.0 : Math.pow(1.0-gamma, zt/2.0);
        }
    }
Member Data Documentation
double [] moa.classifiers.meta.OnlineSmoothBoost.alpha [protected]
Definition at line 69 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.getEnsembleMemberWeight(), and moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl().
ClassOption moa.classifiers.meta.OnlineSmoothBoost.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 53 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl().
Classifier [] moa.classifiers.meta.OnlineSmoothBoost.ensemble [protected]
Definition at line 67 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.getModelMeasurementsImpl(), moa.classifiers.meta.OnlineSmoothBoost.getSubClassifiers(), moa.classifiers.meta.OnlineSmoothBoost.getVotesForInstance(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), and moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl().
IntOption moa.classifiers.meta.OnlineSmoothBoost.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models to boost.", 10, 1, Integer.MAX_VALUE)
Definition at line 56 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl().
double moa.classifiers.meta.OnlineSmoothBoost.gamma [protected]
Definition at line 71 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), and moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl().
FloatOption moa.classifiers.meta.OnlineSmoothBoost.gammaOption
Initial value:
 new FloatOption("gamma",
            'g',
            "The value of the gamma parameter.",
            0.1, 0.0, 1.0)
Definition at line 62 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl().
final long moa.classifiers.meta.OnlineSmoothBoost.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 46 of file OnlineSmoothBoost.java.
double moa.classifiers.meta.OnlineSmoothBoost.theta [protected]
Definition at line 73 of file OnlineSmoothBoost.java.
Referenced by moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), and moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/OnlineSmoothBoost.java