MOA: moa.classifiers.trees.HoeffdingOptionTree.Node Class Reference
moa.classifiers.trees.HoeffdingOptionTree.Node Class Reference
Public Member Functions
Node (double[] classObservations)
int calcByteSize ()
int calcByteSizeIncludingSubtree ()
boolean isLeaf ()
FoundNode[] filterInstanceToLeaves (Instance inst, SplitNode parent, int parentBranch, boolean updateSplitterCounts)
void filterInstanceToLeaves (Instance inst, SplitNode splitparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
double[] getObservedClassDistribution ()
double[] getClassVotes (Instance inst, HoeffdingOptionTree ht)
boolean observedClassDistributionIsPure ()
void describeSubtree (HoeffdingOptionTree ht, StringBuilder out, int indent)
int subtreeDepth ()
double calculatePromise ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
DoubleVector observedClassDistribution
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 195 of file HoeffdingOptionTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingOptionTree.Node.Node (double[] classObservations)
Definition at line 201 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
{
            this.observedClassDistribution = new DoubleVector(classObservations);
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSize ()
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.SplitNode, and moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.
Definition at line 205 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSizeIncludingSubtree().
{
            return (int) (SizeOf.sizeOf(this) + SizeOf.fullSizeOf(this.observedClassDistribution));
        }
int moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSizeIncludingSubtree ()
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.SplitNode.
Definition at line 209 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSize().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSizeIncludingSubtree().
{
            return calcByteSize();
        }
double moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise ()
Definition at line 264 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.getValue(), moa.core.DoubleVector.maxIndex(), moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.enforceTrackerLimit().
{
            double totalSeen = this.observedClassDistribution.sumOfValues();
            return totalSeen > 0.0 ? (totalSeen - this.observedClassDistribution.getValue(this.observedClassDistribution.maxIndex()))
                    : 0.0;
        }
void moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree (HoeffdingOptionTree ht, StringBuilder out, int indent)
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.SplitNode.
Definition at line 248 of file HoeffdingOptionTree.java.
References moa.classifiers.AbstractClassifier.getClassLabelString(), moa.classifiers.AbstractClassifier.getClassNameString(), moa.core.DoubleVector.getSingleLineDescription(), moa.core.DoubleVector.numValues(), moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution, and moa.classifiers.trees.HoeffdingOptionTree.treeRoot.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), and moa.classifiers.trees.HoeffdingOptionTree.Node.getDescription().
{
            StringUtils.appendIndented(out, indent, "Leaf ");
            out.append(ht.getClassNameString());
            out.append(" = ");
            out.append(ht.getClassLabelString(this.observedClassDistribution.maxIndex()));
            out.append(" weights: ");
            this.observedClassDistribution.getSingleLineDescription(out,
                    ht.treeRoot.observedClassDistribution.numValues());
            StringUtils.appendNewline(out);
        }
void moa.classifiers.trees.HoeffdingOptionTree.Node.filterInstanceToLeaves (Instance inst, SplitNode splitparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Definition at line 225 of file HoeffdingOptionTree.java.
{
            foundNodes.add(new FoundNode(this, splitparent, parentBranch));
        }
FoundNode [] moa.classifiers.trees.HoeffdingOptionTree.Node.filterInstanceToLeaves (Instance inst, SplitNode parent, int parentBranch, boolean updateSplitterCounts)
Definition at line 217 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves().
{
            List<FoundNode> nodes = new LinkedList<FoundNode>();
            filterInstanceToLeaves(inst, parent, parentBranch, nodes,
                    updateSplitterCounts);
            return nodes.toArray(new FoundNode[nodes.size()]);
        }
double [] moa.classifiers.trees.HoeffdingOptionTree.Node.getClassVotes (Instance inst, HoeffdingOptionTree ht)
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode, moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNBAdaptive.
Definition at line 235 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.getVotesForInstance().
{
            double[] dist = this.observedClassDistribution.getArrayCopy();
            double distSum = Utils.sum(dist);
            if (distSum > 0.0) {
                Utils.normalize(dist, distSum);
            }
            return dist;
        }
void moa.classifiers.trees.HoeffdingOptionTree.Node.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 270 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree().
{
            describeSubtree(null, sb, indent);
        }
double [] moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution ()
Definition at line 231 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.activateLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), and moa.classifiers.trees.HoeffdingOptionTree.deactivateLearningNode().
{
            return this.observedClassDistribution.getArrayCopy();
        }
boolean moa.classifiers.trees.HoeffdingOptionTree.Node.isLeaf ()
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.SplitNode.
Definition at line 213 of file HoeffdingOptionTree.java.
{
            return true;
        }
boolean moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistributionIsPure ()
Definition at line 244 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.numNonZeroEntries(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit().
{
            return this.observedClassDistribution.numNonZeroEntries() < 2;
        }
int moa.classifiers.trees.HoeffdingOptionTree.Node.subtreeDepth ()
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree.SplitNode.
Definition at line 260 of file HoeffdingOptionTree.java.
{
            return 0;
        }
Member Data Documentation
DoubleVector moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution [protected]
Definition at line 199 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSize(), moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingOptionTree.Node.getClassVotes(), moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode.getClassVotes(), moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.InactiveLearningNode.learnFromInstance(), moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.Node.Node(), and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistributionIsPure().
final long moa.classifiers.trees.HoeffdingOptionTree.Node.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.AdaLearningNode, moa.classifiers.trees.HoeffdingOptionTree.SplitNode, moa.classifiers.trees.HoeffdingOptionTree.LearningNode, moa.classifiers.trees.HoeffdingOptionTree.InactiveLearningNode, moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode, moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNBAdaptive.
Definition at line 197 of file HoeffdingOptionTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingOptionTree.java