MOA: moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble Class Reference
moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble Class Reference
The online version of the Accuracy Updated Ensemble as proposed by Brzezinski and Stefanowski in "Combining block-based and online methods in learning ensembles from concept drifting data streams", Information Sciences, 2014.
Classes
class ClassifierWithMemory
Public Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
boolean isRandomizable ()
Determines whether the classifier is randomizable.
double[] getVotesForInstance (Instance inst)
Predicts a class for an example.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption learnerOption
Type of classifier to use as a component classifier.
IntOption memberCountOption
Number of component classifiers.
FloatOption windowSizeOption
Chunk size.
IntOption maxByteSizeOption
Determines the maximum size of model (evaluated after every chunk).
FlagOption verboseOption = new FlagOption("verbose", 'v', "When checked the algorithm outputs additional information about component classifier weights.")
Determines whether additional information should be sent to the output.
FlagOption linearOption = new FlagOption("linearFunction", 'f', "When checked the algorithm uses a linear weighting function.")
Determines whether additional information should be sent to the output.
Protected Member Functions
void createNewClassifier (Instance inst)
Processes a chunk.
void enforceMemoryLimit ()
Checks if the memory limit is exceeded and if so prunes the classifiers in the ensemble.
void computeMseR ()
Computes the MSEr threshold.
double computeWeight (int i, Instance example)
Computes the weight of a learner before training a given example.
Measurement[] getModelMeasurementsImpl ()
Adds ensemble weights to the measurements.
void addToStored (ClassifierWithMemory newClassifier, double newClassifiersWeight)
Adds a classifier to the storage.
Protected Attributes
double[][] weights
The weights of stored classifiers.
long[] classDistributions
Class distributions.
ClassifierWithMemory[] ensemble
Ensemble classifiers.
int processedInstances
Number of processed examples.
ClassifierWithMemory candidate
Candidate classifier.
int[] currentWindow
Current window of instance class values.
double mse_r = 0
The mean square residual in a given moment, based on a window of latest examples.
int windowSize = 0
Window size.
Private Member Functions
int getPoorestClassifierIndex ()
Finds the index of the classifier with the smallest weight.
void initVariables ()
Initiates the current chunk and class distribution variables.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The online version of the Accuracy Updated Ensemble as proposed by Brzezinski and Stefanowski in "Combining block-based and online methods in learning ensembles from concept drifting data streams", Information Sciences, 2014.
Definition at line 40 of file OnlineAccuracyUpdatedEnsemble.java.
Member Function Documentation
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.addToStored (ClassifierWithMemory newClassifier, double newClassifiersWeight) [protected]
Adds a classifier to the storage.
Parameters:
newClassifier The classifier to add.
newClassifiersWeight The new classifiers weight.
Definition at line 382 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier().
{
        ClassifierWithMemory[] newStored = new ClassifierWithMemory[this.ensemble.length + 1];
        double[][] newStoredWeights = new double[newStored.length][2];
        for (int i = 0; i < newStored.length; i++) {
            if (i < this.ensemble.length) {
                newStored[i] = this.ensemble[i];
                newStoredWeights[i][0] = this.weights[i][0];
                newStoredWeights[i][1] = this.weights[i][1];
            } else {
                newStored[i] = newClassifier;
                newStoredWeights[i][0] = newClassifiersWeight;
                newStoredWeights[i][1] = i;
            }
        }
        this.ensemble = newStored;
        this.weights = newStoredWeights;
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeMseR () [protected]
Computes the MSEr threshold.
Returns:
The MSEr threshold.
Definition at line 282 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.mse_r, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        double p_c;
        this.mse_r = 0;
        for (int i = 0; i < this.classDistributions.length; i++) {
            p_c = (double) this.classDistributions[i] / (double) this.windowSize;
            this.mse_r += p_c * ((1 - p_c) * (1 - p_c));
        }
    }
double moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight (int i, Instance example) [protected]
Computes the weight of a learner before training a given example.
Parameters:
i the identifier (in terms of array learners) of the classifier for which the weight is supposed to be computed
example the newest example
Returns:
the computed weight.
Definition at line 299 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.birthday, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.classifiers.Classifier.getVotesForInstance(), moa.options.FlagOption.isSet, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.linearOption, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.mse_it, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.mse_r, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.processedInstances, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.squareErrors, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        int d = this.windowSize;
        int t = this.processedInstances - this.ensemble[i].birthday;
        double e_it = 0;
        double mse_it = 0;
        double voteSum = 0;
        try{
            double[] votes = this.ensemble[i].classifier.getVotesForInstance(example);
            for (double element : votes) {
                voteSum += element;
            }
            if (voteSum > 0) {
                double f_it = 1 - (votes[(int) example.classValue()] / voteSum);
                e_it = f_it * f_it;
            } else {
                e_it = 1;
            }
        } catch (Exception e) {
            e_it = 1;
        }
        if(t > d)
        {
            mse_it = this.ensemble[i].mse_it + e_it/(double)d - this.ensemble[i].squareErrors[t % d]/(double)d;
        }
        else
        {
            mse_it = this.ensemble[i].mse_it*(t-1)/t + e_it/(double)t;
        }
        this.ensemble[i].squareErrors[t % d] = e_it;
        this.ensemble[i].mse_it = mse_it;
        if(linearOption.isSet())
        {
            return java.lang.Math.max(mse_r - mse_it, Double.MIN_VALUE);
        }
        else
        {
            return 1.0 / (this.mse_r + mse_it + Double.MIN_VALUE);
        }
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier (Instance inst) [protected]
Processes a chunk.
Parameters:
inst New example
Definition at line 227 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.birthday, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.AbstractClassifier.copy(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getPoorestClassifierIndex(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FlagOption.isSet, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.learnerOption, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.linearOption, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.mse_r, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.processedInstances, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        // Compute weights
        double candidateClassifierWeight = 1.0 / (this.mse_r + Double.MIN_VALUE);
        if(linearOption.isSet())
        {
            candidateClassifierWeight = java.lang.Math.max(this.mse_r, Double.MIN_VALUE);
        }
        for (int i = 0; i < this.ensemble.length; i++) {
            this.weights[i][0] = this.computeWeight(i, inst);
        }
        // Configure candidate classifier
        // The candidate classifier has been trained on the last window of examples
        this.candidate.birthday = this.processedInstances;
        if (this.ensemble.length < this.memberCountOption.getValue()) {
            // Add candidate classifier
            this.addToStored(this.candidate, candidateClassifierWeight);
        } else {
            // Substitute poorest classifier
            int poorestClassifier = this.getPoorestClassifierIndex();
            if (this.weights[poorestClassifier][0] < candidateClassifierWeight) {
                this.weights[poorestClassifier][0] = candidateClassifierWeight;
                this.candidate.classifier = this.candidate.classifier;
                this.ensemble[(int) this.weights[poorestClassifier][1]] = this.candidate;
            }
        }
        this.candidate = new ClassifierWithMemory(((Classifier) getPreparedClassOption(this.learnerOption)).copy(), this.windowSize);
        this.candidate.classifier.resetLearning();
        this.enforceMemoryLimit();
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit () [protected]
Checks if the memory limit is exceeded and if so prunes the classifiers in the ensemble.
Definition at line 267 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.options.IntOption.getValue(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.maxByteSizeOption, moa.options.IntOption.setValue(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier().
{
        double memoryLimit = this.maxByteSizeOption.getValue() / (double) (this.ensemble.length + 1);
        for (int i = 0; i < this.ensemble.length; i++) {
            ((HoeffdingTree) this.ensemble[(int) this.weights[i][1]].classifier).maxByteSizeOption.setValue((int) Math
                    .round(memoryLimit));
            ((HoeffdingTree) this.ensemble[(int) this.weights[i][1]].classifier).enforceTrackerLimit();
        }
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 208 of file OnlineAccuracyUpdatedEnsemble.java.
{
    }
Measurement [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelMeasurementsImpl () [protected, virtual]
Adds ensemble weights to the measurements.
Implements moa.classifiers.AbstractClassifier.
Definition at line 351 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.options.IntOption.getValue(), moa.options.FlagOption.isSet, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.memberCountOption, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.verboseOption, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights.
{
        if(this.verboseOption.isSet())
        {
            Measurement[] measurements = new Measurement[(int) this.memberCountOption.getValue()];
            for (int m = 0; m < this.memberCountOption.getValue(); m++) {
                measurements[m] = new Measurement("Member weight " + (m + 1), -1);
            }
            if (this.weights != null) {
                for (int i = 0; i < this.weights.length; i++) {
                    measurements[i] = new Measurement("Member weight " + (i + 1), this.weights[i][0]);
                }
            }
            return measurements;
        }
        else
        {
            return null;
        }
    }
int moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getPoorestClassifierIndex () [private]
Finds the index of the classifier with the smallest weight.
Returns:
Definition at line 405 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier().
{
        int minIndex = 0;
        for (int i = 1; i < this.weights.length; i++) {
            if(this.weights[i][0] < this.weights[minIndex][0]){
                minIndex = i;
            }
        }
        return minIndex;
    }
Classifier [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 212 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble.
{
        Classifier[] subClassifiers = new Classifier[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            subClassifiers[i] = this.ensemble[i].classifier;
        }
        return subClassifiers;
    }
double [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance (Instance inst)
Predicts a class for an example.
Implements moa.classifiers.Classifier.
Definition at line 185 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.sumOfValues(), moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights.
{
        DoubleVector combinedVote = new DoubleVector();
        if (this.trainingWeightSeenByModel > 0.0) {
            for (int i = 0; i < this.ensemble.length; i++) {
                if (this.weights[i][0] > 0.0) {
                    DoubleVector vote = new DoubleVector(this.ensemble[(int) this.weights[i][1]].classifier.getVotesForInstance(inst));
                    if (vote.sumOfValues() > 0.0) {
                        vote.normalize();
                        // scale weight and prevent overflow
                        vote.scaleValues(this.weights[i][0] / (1.0 * this.ensemble.length + 1.0));
                        combinedVote.addValues(vote);
                    }
                }
            }
        }
        //combinedVote.normalize();
        return combinedVote.getArrayRef();
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables () [private]
Initiates the current chunk and class distribution variables.
Definition at line 420 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.currentWindow, moa.classifiers.AbstractClassifier.getModelContext(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
{
        if (this.currentWindow == null) {
            this.currentWindow = new int[this.windowSize];
        }
        if (this.classDistributions == null) {
            this.classDistributions = new long[this.getModelContext().classAttribute().numValues()];
        }
    }
boolean moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.isRandomizable ()
Determines whether the classifier is randomizable.
Implements moa.classifiers.Classifier.
Definition at line 178 of file OnlineAccuracyUpdatedEnsemble.java.
{
        return false;
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 122 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.AbstractClassifier.copy(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.learnerOption, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSizeOption.
{
        this.windowSize = (int)this.windowSizeOption.getValue();
        this.candidate = new ClassifierWithMemory(((Classifier) getPreparedClassOption(this.learnerOption)).copy(), this.windowSize);
        this.candidate.classifier.resetLearning();
        super.prepareForUseImpl(monitor, repository);
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 131 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.AbstractClassifier.copy(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.currentWindow, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.learnerOption, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.processedInstances, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSizeOption.
{
        this.currentWindow = null;
        this.windowSize = (int)this.windowSizeOption.getValue();
        this.classDistributions = null;
        this.processedInstances = 0;
        this.ensemble = new ClassifierWithMemory[0];
        this.candidate = new ClassifierWithMemory(((Classifier) getPreparedClassOption(this.learnerOption)).copy(), this.windowSize);
        this.candidate.classifier.resetLearning();
    }
void moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 143 of file OnlineAccuracyUpdatedEnsemble.java.
References moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.candidate, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.classDistributions, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ClassifierWithMemory.classifier, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.currentWindow, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.processedInstances, moa.classifiers.Classifier.trainOnInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights, and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize.
{
        this.initVariables();
        if(this.processedInstances < this.windowSize)
        {
            this.classDistributions[(int) inst.classValue()]++;
        }
        else
        {
            this.classDistributions[this.currentWindow[processedInstances % this.windowSize]]--;
            this.classDistributions[(int) inst.classValue()]++;
        }
        this.currentWindow[processedInstances % this.windowSize] = (int)inst.classValue();
        this.processedInstances++;
        this.computeMseR();
        if (this.processedInstances % this.windowSize == 0) {
            this.createNewClassifier(inst);
        } else {
            this.candidate.classifier.trainOnInstance(inst);
            for (int i = 0; i < this.ensemble.length; i++) {
                this.weights[i][0] = this.computeWeight(i, inst);
            }
        }
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i].classifier.trainOnInstance(inst);
        }
    }
Member Data Documentation
ClassifierWithMemory moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.candidate [protected]
Candidate classifier.
Definition at line 104 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
long [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.classDistributions [protected]
Class distributions.
Definition at line 89 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
int [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.currentWindow [protected]
Current window of instance class values.
Definition at line 109 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
ClassifierWithMemory [] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.ensemble [protected]
Ensemble classifiers.
Definition at line 94 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getSubClassifiers(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.learnerOption
Initial value:
 new ClassOption("learner", 'l', "Classifier to train.", Classifier.class,
            "trees.HoeffdingTree -e 2000000 -g 100 -c 0.01")
Type of classifier to use as a component classifier.
Definition at line 47 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl().
FlagOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.linearOption = new FlagOption("linearFunction", 'f', "When checked the algorithm uses a linear weighting function.")
Determines whether additional information should be sent to the output.
Definition at line 76 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier().
IntOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.maxByteSizeOption
Initial value:
 new IntOption("maxByteSize", 'm', "Maximum memory consumed by ensemble.",
            33554432, 0, Integer.MAX_VALUE)
Determines the maximum size of model (evaluated after every chunk).
Definition at line 65 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit().
IntOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.memberCountOption
Initial value:
 new IntOption("memberCount", 'n',
            "The maximum number of classifiers in an ensemble.", 10, 1, Integer.MAX_VALUE)
Number of component classifiers.
Definition at line 53 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelMeasurementsImpl().
double moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.mse_r = 0 [protected]
The mean square residual in a given moment, based on a window of latest examples.
Definition at line 114 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier().
int moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.processedInstances [protected]
Number of processed examples.
Definition at line 99 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
final long moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file OnlineAccuracyUpdatedEnsemble.java.
FlagOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.verboseOption = new FlagOption("verbose", 'v', "When checked the algorithm outputs additional information about component classifier weights.")
Determines whether additional information should be sent to the output.
Definition at line 71 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelMeasurementsImpl().
double [][] moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.weights [protected]
The weights of stored classifiers.
weights[x][0] = weight weights[x][1] = classifier number in learners
Definition at line 84 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelMeasurementsImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getPoorestClassifierIndex(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getVotesForInstance(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
int moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSize = 0 [protected]
Window size.
Definition at line 119 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.initVariables(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl().
FloatOption moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.windowSizeOption
Initial value:
 new FloatOption("windowSize", 'w',
            "The window size used for classifier creation and evaluation.", 500, 1, Integer.MAX_VALUE)
Chunk size.
Definition at line 59 of file OnlineAccuracyUpdatedEnsemble.java.
Referenced by moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), and moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/OnlineAccuracyUpdatedEnsemble.java