MOA: moa.cluster.Clustering Class Reference
moa.cluster.Clustering Class Reference
Public Member Functions
Clustering ()
Clustering (Cluster[] clusters)
Clustering (List<?extends Instance > points)
Clustering (ArrayList< DataPoint > points, double overlapThreshold, int initMinPoints)
Clustering (AutoExpandVector< Cluster > clusters)
void add (Cluster cluster)
add a cluster to the clustering
void remove (int index)
remove a cluster from the clustering
Cluster get (int index)
remove a cluster from the clustering
AutoExpandVector< Cluster > getClustering ()
AutoExpandVector< Cluster > getClusteringCopy ()
int size ()
int dimension ()
void getDescription (StringBuilder sb, int i)
Returns a string representation of this object.
double getMaxInclusionProbability (Instance point)
Static Public Member Functions
static HashMap< Integer, Integer > classValues (List<?extends Instance > points)
Private Attributes
AutoExpandVector< Cluster > clusters
Detailed Description
Definition at line 38 of file Clustering.java.
Constructor & Destructor Documentation
moa.cluster.Clustering.Clustering ()
Definition at line 42 of file Clustering.java.
References moa.cluster.Clustering.clusters.
{
        this.clusters = new AutoExpandVector<Cluster>();
    }
moa.cluster.Clustering.Clustering (Cluster[] clusters)
Definition at line 46 of file Clustering.java.
{
        this.clusters = new AutoExpandVector<Cluster>();
        for (int i = 0; i < clusters.length; i++) {
            this.clusters.add(clusters[i]);
        }
    }
moa.cluster.Clustering.Clustering (List<?extends Instance > points)
Definition at line 53 of file Clustering.java.
References moa.cluster.Clustering.classValues(), moa.cluster.Clustering.clusters, moa.cluster.Cluster.setGroundTruth(), moa.cluster.Cluster.setId(), and moa.cluster.Clustering.size().
{
        HashMap<Integer, Integer> labelMap = classValues(points);
        int dim = points.get(0).dataset().numAttributes()-1;
        int numClasses = labelMap.size();
        int noiseLabel;
        Attribute classLabel = points.get(0).dataset().classAttribute();
        int lastLabelIndex = classLabel.numValues() - 1;
        if (classLabel.value(lastLabelIndex) == "noise") {
            noiseLabel = lastLabelIndex;
        } else {
            noiseLabel = -1;
        }
        ArrayList<Instance>[] sorted_points = (ArrayList<Instance>[]) new ArrayList[numClasses];
        for (int i = 0; i < numClasses; i++) {
            sorted_points[i] = new ArrayList<Instance>();
        }
        for (Instance point : points) {
            int clusterid = (int)point.classValue();
            if(clusterid == noiseLabel) continue;
            sorted_points[labelMap.get(clusterid)].add((Instance)point);
        }
        this.clusters = new AutoExpandVector<Cluster>();
        for (int i = 0; i < numClasses; i++) {
            if(sorted_points[i].size()>0){
                SphereCluster s = new SphereCluster(sorted_points[i],dim);
                s.setId(sorted_points[i].get(0).classValue());
                s.setGroundTruth(sorted_points[i].get(0).classValue());
                clusters.add(s);
            }
        }
    }
moa.cluster.Clustering.Clustering (ArrayList< DataPoint > points, double overlapThreshold, int initMinPoints)
Definition at line 88 of file Clustering.java.
References moa.cluster.Clustering.clusters, moa.cluster.SphereCluster.getInclusionProbability(), and moa.cluster.SphereCluster.setWeight().
{
        HashMap<Integer, Integer> labelMap = Clustering.classValues(points);
        int dim = points.get(0).dataset().numAttributes()-1;
        int numClasses = labelMap.size();
        int num = 0;
        ArrayList<DataPoint>[] sorted_points = (ArrayList<DataPoint>[]) new ArrayList[numClasses];
        for (int i = 0; i < numClasses; i++) {
            sorted_points[i] = new ArrayList<DataPoint>();
        }
        for (DataPoint point : points) {
            int clusterid = (int)point.classValue();
            if(clusterid == -1) continue;
            sorted_points[labelMap.get(clusterid)].add(point);
            num++;
        }
        clusters = new AutoExpandVector<Cluster>();
        int microID = 0;
        for (int i = 0; i < numClasses; i++) {
            ArrayList<SphereCluster> microByClass = new ArrayList<SphereCluster>();
            ArrayList<DataPoint> pointInCluster = new ArrayList<DataPoint>();
            ArrayList<ArrayList<Instance>> pointInMicroClusters = new ArrayList();
            pointInCluster.addAll(sorted_points[i]);
            while(pointInCluster.size()>0){
                ArrayList<Instance> micro_points = new ArrayList<Instance>();
                for (int j = 0; j < initMinPoints && !pointInCluster.isEmpty(); j++) {
                    micro_points.add((Instance)pointInCluster.get(0));
                    pointInCluster.remove(0);
                }
                if(micro_points.size() > 0){
                    SphereCluster s = new SphereCluster(micro_points,dim);
                    for (int c = 0; c < microByClass.size(); c++) {
                        if(((SphereCluster)microByClass.get(c)).overlapRadiusDegree(s) > overlapThreshold ){
                            micro_points.addAll(pointInMicroClusters.get(c));
                            s = new SphereCluster(micro_points,dim);
                            pointInMicroClusters.remove(c);
                            microByClass.remove(c);
                            //System.out.println("Removing redundant cluster based on radius overlap"+c);
                        }
                    }
                    for (int j = 0; j < pointInCluster.size(); j++) {
                        Instance instance = pointInCluster.get(j);
                        if(s.getInclusionProbability(instance) > 0.8){
                            pointInCluster.remove(j);
                            micro_points.add(instance);
                        }
                    }
                    s.setWeight(micro_points.size());
                    microByClass.add(s);
                    pointInMicroClusters.add(micro_points);
                    microID++;
                }
            }
            //
            boolean changed = true;
            while(changed){
                changed = false;
                for(int c = 0; c < microByClass.size(); c++) {
                    for(int c1 = c+1; c1 < microByClass.size(); c1++) {
                        double overlap = microByClass.get(c).overlapRadiusDegree(microByClass.get(c1));
//                        System.out.println("Overlap C"+(clustering.size()+c)+" ->C"+(clustering.size()+c1)+": "+overlap);
                        if(overlap > overlapThreshold){
                            pointInMicroClusters.get(c).addAll(pointInMicroClusters.get(c1));
                            SphereCluster s = new SphereCluster(pointInMicroClusters.get(c),dim);
                            microByClass.set(c, s);
                            pointInMicroClusters.remove(c1);
                            microByClass.remove(c1);
                            changed = true;
                            break;
                        }
                    }
                }
            }
            for (int j = 0; j < microByClass.size(); j++) {
                microByClass.get(j).setGroundTruth(sorted_points[i].get(0).classValue());
                clusters.add(microByClass.get(j));
            }
        }
        for (int j = 0; j < clusters.size(); j++) {
            clusters.get(j).setId(j);
        }
    }
moa.cluster.Clustering.Clustering (AutoExpandVector< Cluster > clusters)
Definition at line 201 of file Clustering.java.
{
        this.clusters = clusters;
    }
Member Function Documentation
void moa.cluster.Clustering.add (Cluster cluster)
add a cluster to the clustering
Definition at line 209 of file Clustering.java.
References moa.cluster.Clustering.clusters.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.clusterers.CobWeb.CNode.computeTreeClustering(), moa.clusterers.KMeans.gaussianMeans(), moa.clusterers.macro.NonConvexCluster.getClustering(), moa.clusterers.clustree.ClusTree.getClustering(), moa.clusterers.streamkm.StreamKM.getClusteringResult(), moa.clusterers.outliers.MyBaseOutlierDetector.getClusteringResult(), moa.streams.clustering.RandomRBFGeneratorEvents.getGeneratingClusters(), moa.streams.clustering.RandomRBFGeneratorEvents.getMicroClustering(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.ClusterGenerator.joinClusters(), moa.clusterers.clustream.WithKmeans.kMeans(), moa.clusterers.clustream.Clustream.kMeans(), moa.clusterers.clustream.WithKmeans.kMeans_gta(), and moa.clusterers.clustream.WithKmeans.kMeans_rand().
{
        clusters.add(cluster);
    }
static HashMap<Integer, Integer> moa.cluster.Clustering.classValues (List<?extends Instance > points) [static]
Parameters:
points
Returns:
an array with the min and max class label value
Definition at line 180 of file Clustering.java.
Referenced by moa.cluster.Clustering.Clustering().
{
        HashMap<Integer,Integer> classes = new HashMap<Integer, Integer>();
        int workcluster = 0;
        boolean hasnoise = false;
        for (int i = 0; i < points.size(); i++) {
            int label = (int) points.get(i).classValue();
            if(label == -1){
                hasnoise = true;
            }
            else{
                if(!classes.containsKey(label)){
                    classes.put(label,workcluster);
                    workcluster++;
                }
            }
        }
        if(hasnoise)
            classes.put(-1,workcluster);
        return classes;
    }
int moa.cluster.Clustering.dimension ()
Returns:
the number of dimensions of this clustering
Definition at line 257 of file Clustering.java.
References moa.cluster.Clustering.clusters.
{
    assert (clusters.size() != 0);
    return clusters.get(0).getCenter().length;
    }
Cluster moa.cluster.Clustering.get (int index)
remove a cluster from the clustering
Definition at line 225 of file Clustering.java.
References moa.cluster.Clustering.clusters.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.StatisticalCollection.cindex(), moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.General.computeCompactness(), moa.evaluation.General.computeOverlap(), moa.gui.visualization.StreamPanel.drawClustering(), moa.evaluation.SSQ.evaluateClustering(), moa.evaluation.SilhouetteCoefficient.evaluateClustering(), moa.evaluation.General.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), moa.clusterers.KMeans.gaussianMeans(), moa.evaluation.CMM_GTAnalysis.GTCluster.getInclusionProbability(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), moa.clusterers.ClusterGenerator.joinClusters(), moa.clusterers.clustream.WithKmeans.kMeans_gta(), moa.clusterers.clustream.WithKmeans.kMeans_rand(), moa.evaluation.MembershipMatrix.MembershipMatrix(), moa.evaluation.CMM.missedError(), moa.clusterers.denstream.WithDBSCAN.nearestCluster(), moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs(), moa.gui.visualization.RunVisualizer.weka(), and moa.gui.visualization.RunOutlierVisualizer.weka().
{
        if(index < clusters.size()){
            return clusters.get(index);
        }
        return null;
    }
AutoExpandVector<Cluster> moa.cluster.Clustering.getClustering ()
Returns:
the Clustering as an AutoExpandVector
Definition at line 235 of file Clustering.java.
References moa.cluster.Clustering.clusters.
Referenced by moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.clusterers.macro.dbscan.DBScan.getClustering(), moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        return clusters;
    }
AutoExpandVector<Cluster> moa.cluster.Clustering.getClusteringCopy ()
Returns:
A deepcopy of the Clustering as an AutoExpandVector
Definition at line 242 of file Clustering.java.
References moa.cluster.Clustering.clusters.
{
        return (AutoExpandVector<Cluster>)clusters.copy();
    }
void moa.cluster.Clustering.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 263 of file Clustering.java.
{
        sb.append("Clustering Object");
    }
double moa.cluster.Clustering.getMaxInclusionProbability (Instance point)
Definition at line 269 of file Clustering.java.
References moa.cluster.Clustering.clusters.
{
        double maxInclusion = 0.0;
        for (int i = 0; i < clusters.size(); i++) {
            maxInclusion = Math.max(clusters.get(i).getInclusionProbability(point),
                    maxInclusion);
        }
        return maxInclusion;
    }
void moa.cluster.Clustering.remove (int index)
remove a cluster from the clustering
Definition at line 216 of file Clustering.java.
References moa.cluster.Clustering.clusters.
Referenced by moa.clusterers.ClusterGenerator.alterClustering().
{
        if(index < clusters.size()){
            clusters.remove(index);
        }
    }
int moa.cluster.Clustering.size ()
Returns:
the number of clusters
Definition at line 250 of file Clustering.java.
References moa.cluster.Clustering.clusters.
Referenced by moa.clusterers.ClusterGenerator.alterClustering(), moa.evaluation.StatisticalCollection.cindex(), moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.cluster.Clustering.Clustering(), moa.evaluation.CMM_GTAnalysis.CMM_GTAnalysis(), moa.evaluation.General.computeOverlap(), moa.gui.visualization.StreamPanel.drawClustering(), moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.evaluation.SSQ.evaluateClustering(), moa.evaluation.SilhouetteCoefficient.evaluateClustering(), moa.evaluation.General.evaluateClustering(), moa.evaluation.F1.evaluateClustering(), moa.evaluation.CMM.evaluateClustering(), moa.clusterers.KMeans.gaussianMeans(), moa.clusterers.macro.dbscan.DBScan.getClustering(), moa.clusterers.CobWeb.getClusteringResult(), moa.clusterers.ClusterGenerator.joinClusters(), moa.clusterers.clustream.WithKmeans.kMeans_gta(), moa.clusterers.clustream.WithKmeans.kMeans_rand(), moa.evaluation.MembershipMatrix.MembershipMatrix(), moa.clusterers.denstream.WithDBSCAN.nearestCluster(), moa.clusterers.macro.AbstractMacroClusterer.setClusterIDs(), moa.clusterers.clustream.Clustream.trainOnInstanceImpl(), moa.gui.visualization.RunVisualizer.weka(), and moa.gui.visualization.RunOutlierVisualizer.weka().
                      {
    return clusters.size();
    }
Member Data Documentation
AutoExpandVector<Cluster> moa.cluster.Clustering.clusters [private]
Definition at line 40 of file Clustering.java.
Referenced by moa.cluster.Clustering.add(), moa.cluster.Clustering.Clustering(), moa.cluster.Clustering.dimension(), moa.cluster.Clustering.get(), moa.cluster.Clustering.getClustering(), moa.cluster.Clustering.getClusteringCopy(), moa.cluster.Clustering.getMaxInclusionProbability(), moa.cluster.Clustering.remove(), and moa.cluster.Clustering.size().
The documentation for this class was generated from the following file:
main/java/moa/cluster/Clustering.java