MOA: moa.classifiers.rules.core.RuleActiveLearningNode Class Reference
moa.classifiers.rules.core.RuleActiveLearningNode Class Reference
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Public Member Functions
RuleActiveLearningNode (double[] initialClassObservations)
Create a new RuleActiveLearningNode.
RuleActiveLearningNode ()
RuleActiveLearningNode (Rule.Builder builder)
abstract void learnFromInstance (Instance inst)
void learnFromInstance (Instance inst, HoeffdingTree ht)
void updateStatistics (Instance instance)
AutoExpandVector
< AttributeClassObserver > getAttributeObservers ()
double[] getPrediction (Instance instance)
abstract double[] getPrediction (Instance instance, int predictionMode)
abstract int getLearnerToUse (Instance instance, int predictionMode)
abstract double computeError (Instance instance)
boolean updatePageHinckleyTest (double error)
long getInstancesSeen ()
abstract boolean isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly)
double computeProbability (double mean, double sd, double value)
int getSplitIndex ()
void setSplitIndex (int splitIndex)
AttributeSplitSuggestion getBestSuggestion ()
void setBestSuggestion (AttributeSplitSuggestion bestSuggestion)
double[] getStatisticsBranchSplit ()
void setStatisticsBranchSplit (double[] statisticsBranchSplit)
double[] getStatisticsNewRuleActiveLearningNode ()
void setStatisticsNewRuleActiveLearningNode (double[] statisticsNewRuleActiveLearningNode)
double[] getStatisticsOtherBranchSplit ()
void setStatisticsOtherBranchSplit (double[] statisticsOtherBranchSplit)
abstract boolean tryToExpand (double splitConfidence, double tieThreshold)
abstract void initialize (RuleActiveLearningNode oldLearningNode)
abstract double[] getSimplePrediction ()
DoubleVector getNodeStatistics ()
boolean updateChangeDetection (double error)
abstract double getCurrentError ()
Static Public Member Functions
static double computeHoeffdingBound (double range, double confidence, double n)
Protected Member Functions
AttributeClassObserver newNumericClassObserver ()
void debug (String string, int level)
Protected Attributes
PageHinkleyTest pageHinckleyTest
int predictionFunction
boolean changeDetection
Rule owner
DoubleVector nodeStatistics
AbstractAMRules amRules
AttributeSplitSuggestion bestSuggestion = null
int splitIndex = 0
double[] statisticsNewRuleActiveLearningNode = null
double[] statisticsBranchSplit = null
double[] statisticsOtherBranchSplit
Static Private Attributes
static final long serialVersionUID = 9129659494380381126L
Detailed Description
A modified ActiveLearningNode that uses a Perceptron as the leaf node model, and ensures that the class values sent to the attribute observers are not truncated to ints if regression is being performed.
Definition at line 38 of file RuleActiveLearningNode.java.
Constructor & Destructor Documentation
moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode (double[] initialClassObservations)
Create a new RuleActiveLearningNode.
Definition at line 59 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
{
        super(initialClassObservations);
        this.nodeStatistics = new DoubleVector(initialClassObservations);
    }
moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode ()
Definition at line 64 of file RuleActiveLearningNode.java.
{
        this(new double[0]);
    }
moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode (Rule.Builder builder)
Definition at line 71 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.amRules, moa.classifiers.rules.core.RuleActiveLearningNode.changeDetection, moa.classifiers.rules.core.RuleActiveLearningNode.owner, moa.classifiers.rules.core.RuleActiveLearningNode.pageHinckleyTest, and moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction.
{
        this(builder.statistics);
        this.changeDetection = builder.changeDetection;
        if (builder.changeDetection == false) {
            this.pageHinckleyTest = new PageHinkleyFading(builder.threshold, builder.alpha);
        }
        this.amRules = builder.amRules;
        this.predictionFunction = builder.predictionFunction;
        this.owner=builder.getOwner();
    }
Member Function Documentation
abstract double moa.classifiers.rules.core.RuleActiveLearningNode.computeError (Instance instance) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.Rule.computeError().
static double moa.classifiers.rules.core.RuleActiveLearningNode.computeHoeffdingBound (double range, double confidence, double n) [static]
Definition at line 293 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
                      {
        return Math.sqrt(((range * range) * Math.log(1.0 / confidence))
                / (2.0 * n));
    }
double moa.classifiers.rules.core.RuleActiveLearningNode.computeProbability (double mean, double sd, double value)
Definition at line 185 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly().
{
        double probability = 0.0;
      /* double diff = value - mean;
        if (sd > 0.0) {
            double k = (Math.abs(value - mean) / sd);
            if (k > 1.0) {
                probability = 1.0 / (k * k); // Chebyshev's inequality
            } else {
                probability = Math.exp(-(diff * diff / (2.0 * sd * sd)));
            }
        }*/
        if (sd > 0.0) {
            double k = (Math.abs(value - mean) / sd); // One tailed variant of Chebyshev's inequality
            probability= 1.0 / (1+k*k);
        }
        return probability;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.debug (String string, int level) [protected]
Definition at line 118 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.amRules, moa.options.IntOption.getValue(), and moa.classifiers.rules.AbstractAMRules.VerbosityOption.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
{
        if (this.amRules.VerbosityOption.getValue() >= level) {
            System.out.println(string);
        }
    }
AutoExpandVector<AttributeClassObserver> moa.classifiers.rules.core.RuleActiveLearningNode.getAttributeObservers ()
Definition at line 114 of file RuleActiveLearningNode.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.attributeObservers.
{
        return this.attributeObservers;
    }
AttributeSplitSuggestion moa.classifiers.rules.core.RuleActiveLearningNode.getBestSuggestion ()
Definition at line 228 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.bestSuggestion.
Referenced by moa.classifiers.rules.core.Rule.split().
{
        return bestSuggestion;
    }
abstract double moa.classifiers.rules.core.RuleActiveLearningNode.getCurrentError () [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.Rule.getCurrentError().
long moa.classifiers.rules.core.RuleActiveLearningNode.getInstancesSeen ()
Definition at line 167 of file RuleActiveLearningNode.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen().
Referenced by moa.classifiers.rules.core.Rule.getInstancesSeen(), and moa.classifiers.rules.core.Rule.printRule().
{
        return (long) this.getWeightSeen();
    }
abstract int moa.classifiers.rules.core.RuleActiveLearningNode.getLearnerToUse (Instance instance, int predictionMode) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction().
DoubleVector moa.classifiers.rules.core.RuleActiveLearningNode.getNodeStatistics ()
Definition at line 311 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule().
{
        return this.nodeStatistics;
    }
abstract double [] moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction (Instance instance, int predictionMode) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
double [] moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction (Instance instance)
Definition at line 127 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.getLearnerToUse(), and moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction.
Referenced by moa.classifiers.rules.core.Rule.getPrediction().
{
        int predictionMode = this.getLearnerToUse(instance, this.predictionFunction);
        return getPrediction(instance, predictionMode);
    }
abstract double [] moa.classifiers.rules.core.RuleActiveLearningNode.getSimplePrediction () [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.Rule.printRule().
int moa.classifiers.rules.core.RuleActiveLearningNode.getSplitIndex ()
Definition at line 212 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.splitIndex.
Referenced by moa.classifiers.rules.core.Rule.split().
{
        return splitIndex;
    }
double [] moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsBranchSplit ()
Definition at line 246 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.statisticsBranchSplit.
Referenced by moa.classifiers.rules.core.Rule.split().
{
        return statisticsBranchSplit;
    }
double [] moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsNewRuleActiveLearningNode ()
Definition at line 260 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.statisticsNewRuleActiveLearningNode.
Referenced by moa.classifiers.rules.core.Rule.split().
{
        return statisticsNewRuleActiveLearningNode;
    }
double [] moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsOtherBranchSplit ()
Definition at line 277 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.statisticsOtherBranchSplit.
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        return statisticsOtherBranchSplit;
    }
abstract void moa.classifiers.rules.core.RuleActiveLearningNode.initialize (RuleActiveLearningNode oldLearningNode) [pure virtual]
Referenced by moa.classifiers.rules.core.Rule.split().
abstract boolean moa.classifiers.rules.core.RuleActiveLearningNode.isAnomaly (Instance instance, double uniVariateAnomalyProbabilityThreshold, double multiVariateAnomalyProbabilityThreshold, int numberOfInstanceesForAnomaly) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.Rule.isAnomaly().
void moa.classifiers.rules.core.RuleActiveLearningNode.learnFromInstance (Instance inst, HoeffdingTree ht) [virtual]
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 93 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.learnFromInstance().
{
        learnFromInstance(inst);
    }
abstract void moa.classifiers.rules.core.RuleActiveLearningNode.learnFromInstance (Instance inst) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.learnFromInstance(), and moa.classifiers.rules.core.RuleActiveLearningNode.updateStatistics().
AttributeClassObserver moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver () [protected]
Definition at line 97 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.amRules, moa.AbstractMOAObject.copy(), moa.options.AbstractClassOption.getPreMaterializedObject(), and moa.classifiers.rules.AbstractAMRules.numericObserverOption.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.learnFromInstance().
{
        //return new FIMTDDNumericAttributeClassObserver();
        //return new FIMTDDNumericAttributeClassLimitObserver();
        return (AttributeClassObserver)((AttributeClassObserver)this.amRules.numericObserverOption.getPreMaterializedObject()).copy();
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.setBestSuggestion (AttributeSplitSuggestion bestSuggestion)
Definition at line 235 of file RuleActiveLearningNode.java.
{
        this.bestSuggestion = bestSuggestion;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.setSplitIndex (int splitIndex)
Definition at line 219 of file RuleActiveLearningNode.java.
{
        this.splitIndex = splitIndex;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.setStatisticsBranchSplit (double[] statisticsBranchSplit)
Definition at line 253 of file RuleActiveLearningNode.java.
{
        this.statisticsBranchSplit = statisticsBranchSplit;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.setStatisticsNewRuleActiveLearningNode (double[] statisticsNewRuleActiveLearningNode)
Definition at line 267 of file RuleActiveLearningNode.java.
{
        this.statisticsNewRuleActiveLearningNode = statisticsNewRuleActiveLearningNode;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.setStatisticsOtherBranchSplit (double[] statisticsOtherBranchSplit)
Definition at line 284 of file RuleActiveLearningNode.java.
{
        this.statisticsOtherBranchSplit = statisticsOtherBranchSplit;
    }
abstract boolean moa.classifiers.rules.core.RuleActiveLearningNode.tryToExpand (double splitConfidence, double tieThreshold) [pure virtual]
Implemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Referenced by moa.classifiers.rules.core.Rule.tryToExpand().
boolean moa.classifiers.rules.core.RuleActiveLearningNode.updateChangeDetection (double error)
Definition at line 315 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.changeDetection, moa.classifiers.rules.core.RuleActiveLearningNode.pageHinckleyTest, and moa.classifiers.rules.driftdetection.PageHinkleyTest.update().
Referenced by moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl().
{
        if(changeDetection==false){
            return  pageHinckleyTest.update(error);
        }
        else
            return false;
    }
boolean moa.classifiers.rules.core.RuleActiveLearningNode.updatePageHinckleyTest (double error)
Definition at line 156 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.changeDetection, moa.classifiers.rules.core.RuleActiveLearningNode.pageHinckleyTest, and moa.classifiers.rules.driftdetection.PageHinkleyTest.update().
Referenced by moa.classifiers.rules.core.Rule.updatePageHinckleyTest().
{
        boolean changeDetected = false;
        if (this.changeDetection == false) {
            changeDetected = pageHinckleyTest.update(error);
        }
        return changeDetected;
    }
void moa.classifiers.rules.core.RuleActiveLearningNode.updateStatistics (Instance instance)
Reimplemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Definition at line 107 of file RuleActiveLearningNode.java.
References moa.classifiers.rules.core.RuleActiveLearningNode.learnFromInstance().
Referenced by moa.classifiers.rules.core.Rule.updateStatistics().
{
        learnFromInstance(instance);
    }
Member Data Documentation
AbstractAMRules moa.classifiers.rules.core.RuleActiveLearningNode.amRules [protected]
Definition at line 68 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.core.RuleActiveRegressionNode.initialize(), moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver(), moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode().
AttributeSplitSuggestion moa.classifiers.rules.core.RuleActiveLearningNode.bestSuggestion = null [protected]
Definition at line 207 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions(), moa.classifiers.rules.core.RuleActiveLearningNode.getBestSuggestion(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
boolean moa.classifiers.rules.core.RuleActiveLearningNode.changeDetection [protected]
Definition at line 44 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode(), moa.classifiers.rules.core.RuleActiveLearningNode.updateChangeDetection(), and moa.classifiers.rules.core.RuleActiveLearningNode.updatePageHinckleyTest().
DoubleVector moa.classifiers.rules.core.RuleActiveLearningNode.nodeStatistics [protected]
Definition at line 54 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions(), moa.classifiers.rules.core.RuleActiveLearningNode.getNodeStatistics(), moa.classifiers.rules.core.RuleActiveRegressionNode.getWeightSeen(), moa.classifiers.rules.core.RuleActiveRegressionNode.initialize(), moa.classifiers.rules.core.RuleActiveRegressionNode.learnFromInstance(), moa.classifiers.rules.core.RuleActiveRegressionNode.normalize(), moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode().
Rule moa.classifiers.rules.core.RuleActiveLearningNode.owner [protected]
Definition at line 46 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse(), and moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode().
PageHinkleyTest moa.classifiers.rules.core.RuleActiveLearningNode.pageHinckleyTest [protected]
Definition at line 40 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode(), moa.classifiers.rules.core.RuleActiveLearningNode.updateChangeDetection(), and moa.classifiers.rules.core.RuleActiveLearningNode.updatePageHinckleyTest().
int moa.classifiers.rules.core.RuleActiveLearningNode.predictionFunction [protected]
Definition at line 42 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction(), moa.classifiers.rules.core.RuleActiveLearningNode.getPrediction(), moa.classifiers.rules.core.RuleActiveLearningNode.RuleActiveLearningNode(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.updateStatistics().
final long moa.classifiers.rules.core.RuleActiveLearningNode.serialVersionUID = 9129659494380381126L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Reimplemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Definition at line 48 of file RuleActiveLearningNode.java.
int moa.classifiers.rules.core.RuleActiveLearningNode.splitIndex = 0 [protected]
Definition at line 223 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getSplitIndex(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
double [] moa.classifiers.rules.core.RuleActiveLearningNode.statisticsBranchSplit = null [protected]
Definition at line 241 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsBranchSplit(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
double [] moa.classifiers.rules.core.RuleActiveLearningNode.statisticsNewRuleActiveLearningNode = null [protected]
Definition at line 239 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsNewRuleActiveLearningNode(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
double [] moa.classifiers.rules.core.RuleActiveLearningNode.statisticsOtherBranchSplit [protected]
Definition at line 272 of file RuleActiveLearningNode.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getStatisticsOtherBranchSplit(), and moa.classifiers.rules.core.RuleActiveRegressionNode.tryToExpand().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/RuleActiveLearningNode.java