MOA: moa.classifiers.core.driftdetection.ADWINChangeDetector Class Reference
moa.classifiers.core.driftdetection.ADWINChangeDetector Class Reference
Drift detection method based in ADWIN.
Public Member Functions
void input (double inputValue)
Adding a numeric value to the change detector<br>
.
void resetLearning ()
Resets this change detector.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
Public Attributes
FloatOption deltaAdwinOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
ADWIN adwin
Detailed Description
Drift detection method based in ADWIN.
ADaptive sliding WINdow is a change detector and estimator. It keeps a variable-length window of recently seen items, with the property that the window has the maximal length statistically consistent with the hypothesis "there has been no change in the average value inside the window".
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 36 of file ADWINChangeDetector.java.
Member Function Documentation
void moa.classifiers.core.driftdetection.ADWINChangeDetector.getDescription (StringBuilder sb, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 60 of file ADWINChangeDetector.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.driftdetection.ADWINChangeDetector.input (double inputValue) [virtual]
Adding a numeric value to the change detector<br>
.
The output of the change detector is modified after the insertion of a new item inside.
Parameters:
inputValue the number to insert into the change detector
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 44 of file ADWINChangeDetector.java.
References moa.classifiers.core.driftdetection.ADWINChangeDetector.adwin, moa.classifiers.core.driftdetection.AbstractChangeDetector.delay, moa.classifiers.core.driftdetection.AbstractChangeDetector.estimation, moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.classifiers.core.driftdetection.AbstractChangeDetector.isChangeDetected, moa.classifiers.core.driftdetection.AbstractChangeDetector.isWarningZone, moa.classifiers.core.driftdetection.ADWINChangeDetector.resetLearning(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        if (this.adwin == null) {
            resetLearning();
        }
        this.isChangeDetected = adwin.setInput(inputValue);
        this.isWarningZone = false;
        this.delay = 0.0;
        this.estimation = adwin.getEstimation();
    }
void moa.classifiers.core.driftdetection.ADWINChangeDetector.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 65 of file ADWINChangeDetector.java.
{
        // TODO Auto-generated method stub
    }
void moa.classifiers.core.driftdetection.ADWINChangeDetector.resetLearning ()
Resets this change detector.
It must be similar to starting a new change detector from scratch.
Reimplemented from moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 55 of file ADWINChangeDetector.java.
References moa.classifiers.core.driftdetection.ADWINChangeDetector.adwin, moa.classifiers.core.driftdetection.ADWINChangeDetector.deltaAdwinOption, and moa.options.FloatOption.getValue().
Referenced by moa.classifiers.core.driftdetection.ADWINChangeDetector.input().
{
        adwin = new ADWIN((double) this.deltaAdwinOption.getValue());
    }
Member Data Documentation
ADWIN moa.classifiers.core.driftdetection.ADWINChangeDetector.adwin [protected]
Definition at line 38 of file ADWINChangeDetector.java.
Referenced by moa.classifiers.core.driftdetection.ADWINChangeDetector.input(), and moa.classifiers.core.driftdetection.ADWINChangeDetector.resetLearning().
FloatOption moa.classifiers.core.driftdetection.ADWINChangeDetector.deltaAdwinOption
Initial value:
 new FloatOption("deltaAdwin", 'a',
            "Delta of Adwin change detection", 0.002, 0.0, 1.0)
Definition at line 40 of file ADWINChangeDetector.java.
Referenced by moa.classifiers.core.driftdetection.ADWINChangeDetector.resetLearning().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/ADWINChangeDetector.java