MOA: moa.core.SizeOf Class Reference
moa.core.SizeOf Class Reference
Helper class for Maxim Zakharenkov's SizeOf agent.
Static Public Member Functions
static long sizeOf (Object o)
Returns the size of the object.
static long fullSizeOf (Object o)
Returns the full size of the object.
Static Protected Member Functions
static synchronized boolean isPresent ()
Checks whteher the agent is present.
Static Protected Attributes
static Boolean m_Present
whether the agent is present.
Detailed Description
Helper class for Maxim Zakharenkov's SizeOf agent.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 31 of file SizeOf.java.
Member Function Documentation
static long moa.core.SizeOf.fullSizeOf (Object o) [static]
Returns the full size of the object.
Parameters:
o the object to get the size for
Returns:
the size of the object, or if the agent isn't present -1
Definition at line 74 of file SizeOf.java.
References moa.core.SizeOf.isPresent().
{
        if (isPresent()) {
            return SizeOfAgent.fullSizeOf(o);
        } else {
            return -1;
        }
    }
static synchronized boolean moa.core.SizeOf.isPresent () [static, protected]
Checks whteher the agent is present.
Returns:
true if the agent is present, false otherwise
Definition at line 41 of file SizeOf.java.
References moa.core.SizeOf.m_Present.
Referenced by moa.core.SizeOf.fullSizeOf(), and moa.core.SizeOf.sizeOf().
{
        if (m_Present == null) {
            try {
                SizeOfAgent.fullSizeOf(new Integer(1));
                m_Present = true;
            } catch (Throwable t) {
                m_Present = false;
            }
        }
        return m_Present;
    }
static long moa.core.SizeOf.sizeOf (Object o) [static]
Returns the size of the object.
Parameters:
o the object to get the size for
Returns:
the size of the object, or if the agent isn't present -1
Definition at line 60 of file SizeOf.java.
References moa.core.SizeOf.isPresent().
{
        if (isPresent()) {
            return SizeOfAgent.sizeOf(o);
        } else {
            return -1;
        }
    }
Member Data Documentation
Boolean moa.core.SizeOf.m_Present [static, protected]
whether the agent is present.
Definition at line 34 of file SizeOf.java.
Referenced by moa.core.SizeOf.isPresent().
The documentation for this class was generated from the following file:
main/java/moa/core/SizeOf.java