MOA: moa.core.GreenwaldKhannaQuantileSummary Class Reference
moa.core.GreenwaldKhannaQuantileSummary Class Reference
Class for representing summaries of Greenwald and Khanna quantiles.
Classes
class Tuple
Public Member Functions
GreenwaldKhannaQuantileSummary (int maxTuples)
void insert (double val)
long getWorstError ()
long findMaxDelta ()
void compress (long maxDelta)
double getQuantile (double quant)
long getTotalCount ()
double getPropotionBelow (double cutpoint)
long getCountBelow (double cutpoint)
double[] getSuggestedCutpoints ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Member Functions
static long[] computeBandBoundaries (long maxDelta)
Protected Member Functions
void insertTuple (Tuple t, int index)
void deleteTuple (int index)
void deleteTupleMostFull ()
void deleteMergeableTupleMostFull ()
int findIndexOfTupleGreaterThan (double val)
Protected Attributes
Tuple[] summary
int numTuples = 0
long numObservations = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for representing summaries of Greenwald and Khanna quantiles.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file GreenwaldKhannaQuantileSummary.java.
Constructor & Destructor Documentation
moa.core.GreenwaldKhannaQuantileSummary.GreenwaldKhannaQuantileSummary (int maxTuples)
Definition at line 64 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.summary.
{
        this.summary = new Tuple[maxTuples];
    }
Member Function Documentation
void moa.core.GreenwaldKhannaQuantileSummary.compress (long maxDelta)
Definition at line 166 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.computeBandBoundaries(), moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
{
        long[] bandBoundaries = computeBandBoundaries(maxDelta);
        for (int i = this.numTuples - 2; i >= 0; i--) {
            if (this.summary[i].delta >= this.summary[i + 1].delta) {
                int band = 0;
                while (this.summary[i].delta < bandBoundaries[band]) {
                    band++;
                }
                long belowBandThreshold = Long.MAX_VALUE;
                if (band > 0) {
                    belowBandThreshold = bandBoundaries[band - 1];
                }
                long mergeG = this.summary[i + 1].g + this.summary[i].g;
                int childI = i - 1;
                while (((mergeG + this.summary[i + 1].delta) < maxDelta)
                        && (childI >= 0)
                        && (this.summary[childI].delta >= belowBandThreshold)) {
                    mergeG += this.summary[childI].g;
                    childI--;
                }
                if (mergeG + this.summary[i + 1].delta < maxDelta) {
                    // merge
                    int numDeleted = i - childI;
                    this.summary[childI + 1] = new Tuple(this.summary[i + 1].v,
                            mergeG, this.summary[i + 1].delta);
                    // todo complete & test this multiple delete
                    System.arraycopy(this.summary, i + 2, this.summary,
                            childI + 2, this.numTuples - (i + 2));
                    for (int j = this.numTuples - numDeleted; j < this.numTuples; j++) {
                        this.summary[j] = null;
                    }
                    this.numTuples -= numDeleted;
                    i = childI + 1;
                }
            }
        }
    }
static long [] moa.core.GreenwaldKhannaQuantileSummary.computeBandBoundaries (long maxDelta) [static]
Definition at line 256 of file GreenwaldKhannaQuantileSummary.java.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.compress().
{
        ArrayList<Long> boundaryList = new ArrayList<Long>();
        boundaryList.add(new Long(maxDelta));
        int alpha = 1;
        while (true) {
            long boundary = (maxDelta - (2 << (alpha - 1)) - (maxDelta % (2 << (alpha - 1))));
            if (boundary >= 0) {
                boundaryList.add(new Long(boundary + 1));
            } else {
                break;
            }
            alpha++;
        }
        boundaryList.add(new Long(0));
        long[] boundaries = new long[boundaryList.size()];
        for (int i = 0; i < boundaries.length; i++) {
            boundaries[i] = boundaryList.get(i).longValue();
        }
        return boundaries;
    }
void moa.core.GreenwaldKhannaQuantileSummary.deleteMergeableTupleMostFull () [protected]
Definition at line 128 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.deleteTuple(), moa.core.GreenwaldKhannaQuantileSummary.Tuple.delta, moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.insert().
{
        long leastFullness = Long.MAX_VALUE;
        int leastFullIndex = 0;
        for (int i = 1; i < this.numTuples - 1; i++) {
            long fullness = this.summary[i].g + this.summary[i + 1].g
                    + this.summary[i + 1].delta;
            if ((this.summary[i].delta >= this.summary[i + 1].delta)
                    && (fullness < leastFullness)) {
                leastFullness = fullness;
                leastFullIndex = i;
            }
        }
        if (leastFullIndex > 0) {
            deleteTuple(leastFullIndex);
        }
    }
void moa.core.GreenwaldKhannaQuantileSummary.deleteTuple (int index) [protected]
Definition at line 102 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.deleteMergeableTupleMostFull(), and moa.core.GreenwaldKhannaQuantileSummary.deleteTupleMostFull().
{
        this.summary[index] = new Tuple(this.summary[index + 1].v,
                this.summary[index].g + this.summary[index + 1].g,
                this.summary[index + 1].delta);
        System.arraycopy(this.summary, index + 2, this.summary, index + 1,
                this.numTuples - index - 2);
        this.summary[this.numTuples - 1] = null;
        this.numTuples--;
    }
void moa.core.GreenwaldKhannaQuantileSummary.deleteTupleMostFull () [protected]
Definition at line 112 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.deleteTuple(), moa.core.GreenwaldKhannaQuantileSummary.Tuple.delta, moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
{
        long leastFullness = Long.MAX_VALUE;
        int leastFullIndex = 0;
        for (int i = 1; i < this.numTuples - 1; i++) {
            long fullness = this.summary[i].g + this.summary[i + 1].g
                    + this.summary[i + 1].delta;
            if (fullness < leastFullness) {
                leastFullness = fullness;
                leastFullIndex = i;
            }
        }
        if (leastFullIndex > 0) {
            deleteTuple(leastFullIndex);
        }
    }
int moa.core.GreenwaldKhannaQuantileSummary.findIndexOfTupleGreaterThan (double val) [protected]
Definition at line 243 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.insert().
{
        int high = this.numTuples, low = -1, probe;
        while (high - low > 1) {
            probe = (high + low) / 2;
            if (this.summary[probe].v > val) {
                high = probe;
            } else {
                low = probe;
            }
        }
        return high;
    }
long moa.core.GreenwaldKhannaQuantileSummary.findMaxDelta ()
Definition at line 156 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.Tuple.delta, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
{
        long maxDelta = 0;
        for (int i = 0; i < this.numTuples; i++) {
            if (this.summary[i].delta > maxDelta) {
                maxDelta = this.summary[i].delta;
            }
        }
        return maxDelta;
    }
long moa.core.GreenwaldKhannaQuantileSummary.getCountBelow (double cutpoint)
Definition at line 224 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit(), and moa.core.GreenwaldKhannaQuantileSummary.getPropotionBelow().
{
        long rank = 0;
        for (int i = 0; i < this.numTuples; i++) {
            if (this.summary[i].v > cutpoint) {
                break;
            }
            rank += this.summary[i].g;
        }
        return rank;
    }
void moa.core.GreenwaldKhannaQuantileSummary.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 277 of file GreenwaldKhannaQuantileSummary.java.
{
        // TODO Auto-generated method stub
    }
double moa.core.GreenwaldKhannaQuantileSummary.getPropotionBelow (double cutpoint)
Definition at line 220 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.getCountBelow(), and moa.core.GreenwaldKhannaQuantileSummary.numObservations.
{
        return (double) getCountBelow(cutpoint) / (double) this.numObservations;
    }
double moa.core.GreenwaldKhannaQuantileSummary.getQuantile (double quant)
Definition at line 204 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, moa.core.GreenwaldKhannaQuantileSummary.summary, and moa.core.GreenwaldKhannaQuantileSummary.Tuple.v.
{
        long r = (long) Math.ceil(quant * this.numObservations);
        long currRank = 0;
        for (int i = 0; i < this.numTuples - 1; i++) {
            currRank += this.summary[i].g;
            if (currRank + this.summary[i + 1].g > r) {
                return this.summary[i].v;
            }
        }
        return this.summary[this.numTuples - 1].v;
    }
double [] moa.core.GreenwaldKhannaQuantileSummary.getSuggestedCutpoints ()
Definition at line 235 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.numTuples, moa.core.GreenwaldKhannaQuantileSummary.summary, and moa.core.GreenwaldKhannaQuantileSummary.Tuple.v.
{
        double[] cutpoints = new double[this.numTuples];
        for (int i = 0; i < this.numTuples; i++) {
            cutpoints[i] = this.summary[i].v;
        }
        return cutpoints;
    }
long moa.core.GreenwaldKhannaQuantileSummary.getTotalCount ()
Definition at line 216 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.numObservations.
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getClassDistsResultingFromBinarySplit().
{
        return this.numObservations;
    }
long moa.core.GreenwaldKhannaQuantileSummary.getWorstError ()
Definition at line 145 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.Tuple.delta, moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
{
        long mostFullness = 0;
        for (int i = 1; i < this.numTuples - 1; i++) {
            long fullness = this.summary[i].g + this.summary[i].delta;
            if (fullness > mostFullness) {
                mostFullness = fullness;
            }
        }
        return mostFullness;
    }
void moa.core.GreenwaldKhannaQuantileSummary.insert (double val)
Definition at line 68 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.deleteMergeableTupleMostFull(), moa.core.GreenwaldKhannaQuantileSummary.Tuple.delta, moa.core.GreenwaldKhannaQuantileSummary.findIndexOfTupleGreaterThan(), moa.core.GreenwaldKhannaQuantileSummary.Tuple.g, moa.core.GreenwaldKhannaQuantileSummary.insertTuple(), moa.core.GreenwaldKhannaQuantileSummary.numObservations, moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeClass().
{
        int i = findIndexOfTupleGreaterThan(val);
        Tuple nextT = this.summary[i];
        if (nextT == null) {
            insertTuple(new Tuple(val, 1, 0), i);
        } else {
            insertTuple(new Tuple(val, 1, nextT.g + nextT.delta - 1), i);
        }
        if (this.numTuples == this.summary.length) {
            // use method 1
            deleteMergeableTupleMostFull();
            // if (mergeMethod == 1) {
            // deleteMergeableTupleMostFull();
            // } else if (mergeMethod == 2) {
            // deleteTupleMostFull();
            // } else {
            // long maxDelta = findMaxDelta();
            // compress(maxDelta);
            // while (numTuples == summary.length) {
            // maxDelta++;
            // compress(maxDelta);
            // }
            // }
        }
        this.numObservations++;
    }
void moa.core.GreenwaldKhannaQuantileSummary.insertTuple (Tuple t, int index) [protected]
Definition at line 95 of file GreenwaldKhannaQuantileSummary.java.
References moa.core.GreenwaldKhannaQuantileSummary.numTuples, and moa.core.GreenwaldKhannaQuantileSummary.summary.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.insert().
{
        System.arraycopy(this.summary, index, this.summary, index + 1,
                this.numTuples - index);
        this.summary[index] = t;
        this.numTuples++;
    }
Member Data Documentation
long moa.core.GreenwaldKhannaQuantileSummary.numObservations = 0 [protected]
Definition at line 62 of file GreenwaldKhannaQuantileSummary.java.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.getPropotionBelow(), moa.core.GreenwaldKhannaQuantileSummary.getTotalCount(), and moa.core.GreenwaldKhannaQuantileSummary.insert().
int moa.core.GreenwaldKhannaQuantileSummary.numTuples = 0 [protected]
Definition at line 60 of file GreenwaldKhannaQuantileSummary.java.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.compress(), moa.core.GreenwaldKhannaQuantileSummary.deleteMergeableTupleMostFull(), moa.core.GreenwaldKhannaQuantileSummary.deleteTuple(), moa.core.GreenwaldKhannaQuantileSummary.deleteTupleMostFull(), moa.core.GreenwaldKhannaQuantileSummary.findIndexOfTupleGreaterThan(), moa.core.GreenwaldKhannaQuantileSummary.findMaxDelta(), moa.core.GreenwaldKhannaQuantileSummary.getCountBelow(), moa.core.GreenwaldKhannaQuantileSummary.getQuantile(), moa.core.GreenwaldKhannaQuantileSummary.getSuggestedCutpoints(), moa.core.GreenwaldKhannaQuantileSummary.getWorstError(), moa.core.GreenwaldKhannaQuantileSummary.insert(), and moa.core.GreenwaldKhannaQuantileSummary.insertTuple().
final long moa.core.GreenwaldKhannaQuantileSummary.serialVersionUID = 1L [static, private]
Definition at line 35 of file GreenwaldKhannaQuantileSummary.java.
Tuple [] moa.core.GreenwaldKhannaQuantileSummary.summary [protected]
Definition at line 58 of file GreenwaldKhannaQuantileSummary.java.
Referenced by moa.core.GreenwaldKhannaQuantileSummary.compress(), moa.core.GreenwaldKhannaQuantileSummary.deleteMergeableTupleMostFull(), moa.core.GreenwaldKhannaQuantileSummary.deleteTuple(), moa.core.GreenwaldKhannaQuantileSummary.deleteTupleMostFull(), moa.core.GreenwaldKhannaQuantileSummary.findIndexOfTupleGreaterThan(), moa.core.GreenwaldKhannaQuantileSummary.findMaxDelta(), moa.core.GreenwaldKhannaQuantileSummary.getCountBelow(), moa.core.GreenwaldKhannaQuantileSummary.getQuantile(), moa.core.GreenwaldKhannaQuantileSummary.getSuggestedCutpoints(), moa.core.GreenwaldKhannaQuantileSummary.getWorstError(), moa.core.GreenwaldKhannaQuantileSummary.GreenwaldKhannaQuantileSummary(), moa.core.GreenwaldKhannaQuantileSummary.insert(), and moa.core.GreenwaldKhannaQuantileSummary.insertTuple().
The documentation for this class was generated from the following file:
main/java/moa/core/GreenwaldKhannaQuantileSummary.java