MOA: moa.gui.visualization.DataPoint Class Reference
moa.gui.visualization.DataPoint Class Reference
Public Member Functions
DataPoint (Instance nextInstance, Integer timestamp)
void updateWeight (int cur_timestamp, double decay_rate)
void setMeasureValue (String measureKey, double value)
void setMeasureValue (String measureKey, String value)
String getMeasureValue (String measureKey)
int getTimestamp ()
String getInfo (int x_dim, int y_dim)
double getDistance (DataPoint other)
boolean isNoise ()
double getNoiseLabel ()
Protected Attributes
int timestamp
int noiseLabel
Private Attributes
HashMap< String, String > measure_values
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 35 of file DataPoint.java.
Constructor & Destructor Documentation
moa.gui.visualization.DataPoint.DataPoint (Instance nextInstance, Integer timestamp)
Definition at line 44 of file DataPoint.java.
References moa.gui.visualization.DataPoint.measure_values, and moa.gui.visualization.DataPoint.noiseLabel.
{
        super(nextInstance);
        this.setDataset(nextInstance.dataset());
        this.timestamp = timestamp;
        measure_values = new HashMap<String, String>();
        Attribute classLabel = dataset().classAttribute();
        noiseLabel = classLabel.indexOfValue("noise");      // -1 returned if there is no noise
    }
Member Function Documentation
double moa.gui.visualization.DataPoint.getDistance (DataPoint other)
Definition at line 117 of file DataPoint.java.
Referenced by moa.evaluation.StatisticalCollection.cindex().
{
        double distance = 0.0;
        int numDims = numAttributes();
        if(classIndex()!=0) numDims--;
        for (int i = 0; i < numDims; i++) {
            double d = value(i) - other.value(i);
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
String moa.gui.visualization.DataPoint.getInfo (int x_dim, int y_dim)
Definition at line 83 of file DataPoint.java.
References moa.gui.visualization.DataPoint.measure_values, and moa.gui.visualization.DataPoint.timestamp.
Referenced by moa.gui.visualization.PointPanel.getObjectInfo(), and moa.gui.visualization.PointPanel.paintComponent().
{
        StringBuffer sb = new StringBuffer();
        sb.append("<html><table>");
        sb.append("<tr><td>Point</td><td>"+timestamp+"</td></tr>");
        for (int i = 0; i < m_AttValues.length-1; i++) {
            String label = "Dim "+i;
            if(i == x_dim)
                 label = "<b>X</b>";
            if(i == y_dim)
                 label = "<b>Y</b>";
            sb.append("<tr><td>"+label+"</td><td>"+value(i)+"</td></tr>");
        }
        sb.append("<tr><td>Decay</td><td>"+weight()+"</td></tr>");
        sb.append("<tr><td>True cluster</td><td>"+classValue()+"</td></tr>");
        sb.append("</table>");
        sb.append("<br>");
        sb.append("<b>Evaluation</b><br>");
        sb.append("<table>");
        TreeSet<String> sortedset;
        synchronized(measure_values){
            sortedset = new TreeSet<String>(measure_values.keySet());
        }
        Iterator miterator = sortedset.iterator();
         while(miterator.hasNext()) {
             String key = (String)miterator.next();
             sb.append("<tr><td>"+key+"</td><td>"+measure_values.get(key)+"</td></tr>");
         }
        sb.append("</table></html>");
        return sb.toString();
    }
String moa.gui.visualization.DataPoint.getMeasureValue (String measureKey)
Definition at line 70 of file DataPoint.java.
References moa.gui.visualization.DataPoint.measure_values.
Referenced by moa.gui.visualization.PointPanel.getErrorColor().
{
        if(measure_values.containsKey(measureKey))
            synchronized(measure_values){
                return measure_values.get(measureKey);
            }
        else
            return "";
    }
double moa.gui.visualization.DataPoint.getNoiseLabel ()
Definition at line 134 of file DataPoint.java.
References moa.gui.visualization.DataPoint.noiseLabel.
{
        return noiseLabel;
    }
int moa.gui.visualization.DataPoint.getTimestamp ()
Definition at line 79 of file DataPoint.java.
References moa.gui.visualization.DataPoint.timestamp.
Referenced by moa.evaluation.CMM_GTAnalysis.CMMPoint.CMMPoint(), moa.evaluation.CMM_GTAnalysis.getConnectionValue(), and moa.evaluation.CMM.misplacedError().
{
        return timestamp;
    }
boolean moa.gui.visualization.DataPoint.isNoise ()
Definition at line 130 of file DataPoint.java.
References moa.gui.visualization.DataPoint.noiseLabel.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), moa.evaluation.CMM.calculateMatching(), moa.gui.visualization.PointPanel.getColor(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), and moa.gui.visualization.PointPanel.paintComponent().
{
        return (int)classValue() == noiseLabel;
    }
void moa.gui.visualization.DataPoint.setMeasureValue (String measureKey, String value)
Definition at line 64 of file DataPoint.java.
References moa.gui.visualization.DataPoint.measure_values.
{
        synchronized(measure_values){
            measure_values.put(measureKey, value);
        }
    }
void moa.gui.visualization.DataPoint.setMeasureValue (String measureKey, double value)
Definition at line 58 of file DataPoint.java.
References moa.gui.visualization.DataPoint.measure_values.
Referenced by moa.evaluation.CMM_GTAnalysis.GTCluster.calculateClusterConnection(), moa.evaluation.CMM.calculateError(), moa.evaluation.CMM_GTAnalysis.calculateGTPointQualities(), moa.evaluation.CMM_GTAnalysis.GTCluster.calculateKnn(), moa.evaluation.SilhouetteCoefficient.evaluateClustering(), moa.evaluation.CMM_GTAnalysis.getNoiseSeparability(), moa.evaluation.CMM.misplacedError(), moa.evaluation.CMM.missedError(), and moa.evaluation.CMM.noiseError().
{
        synchronized(measure_values){
            measure_values.put(measureKey, Double.toString(value));
        }
    }
void moa.gui.visualization.DataPoint.updateWeight (int cur_timestamp, double decay_rate)
Definition at line 54 of file DataPoint.java.
References moa.gui.visualization.DataPoint.timestamp.
Referenced by moa.gui.visualization.PointPanel.paintComponent().
{
        setWeight(Math.pow(2,(-1.0)*decay_rate*(cur_timestamp-timestamp)));
    }
Member Data Documentation
HashMap<String, String> moa.gui.visualization.DataPoint.measure_values [private]
Definition at line 40 of file DataPoint.java.
Referenced by moa.gui.visualization.DataPoint.DataPoint(), moa.gui.visualization.DataPoint.getInfo(), moa.gui.visualization.DataPoint.getMeasureValue(), and moa.gui.visualization.DataPoint.setMeasureValue().
int moa.gui.visualization.DataPoint.noiseLabel [protected]
Definition at line 42 of file DataPoint.java.
Referenced by moa.gui.visualization.DataPoint.DataPoint(), moa.gui.visualization.DataPoint.getNoiseLabel(), moa.gui.visualization.PointPanel.getPointColorbyClass(), and moa.gui.visualization.DataPoint.isNoise().
final long moa.gui.visualization.DataPoint.serialVersionUID = 1L [static, private]
Definition at line 37 of file DataPoint.java.
int moa.gui.visualization.DataPoint.timestamp [protected]
Definition at line 39 of file DataPoint.java.
Referenced by moa.gui.visualization.OutlierEvent.compareTo(), moa.gui.visualization.OutlierEvent.equals(), moa.gui.visualization.DataPoint.getInfo(), moa.gui.visualization.DataPoint.getTimestamp(), and moa.gui.visualization.DataPoint.updateWeight().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/DataPoint.java