MOA: moa.core.utils.Converter Class Reference
moa.core.utils.Converter Class Reference
Converter.
Public Member Functions
int getL ()
Converter ()
Converter (int n)
Instances createTemplate (Instances i)
Instance formatInstance (Instance original)
List< Integer > getRelevantLabels (Instance x)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
Instances m_InstancesTemplate = null
int m_L = -1
Detailed Description
Converter.
This class can be used to convert a multi-label instance into a single-label instance.
Author:
Jesse Read (jesse@tsc.uc3m.es)
Version:
Revision
1
Definition at line 35 of file Converter.java.
Constructor & Destructor Documentation
moa.core.utils.Converter.Converter ()
Definition at line 45 of file Converter.java.
                       {
    }
moa.core.utils.Converter.Converter (int n)
Definition at line 48 of file Converter.java.
References moa.core.utils.Converter.m_L.
{
        m_L = n;
    }
Member Function Documentation
Instances moa.core.utils.Converter.createTemplate (Instances i)
Definition at line 52 of file Converter.java.
References moa.core.utils.Converter.m_InstancesTemplate.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance().
{
        this.m_InstancesTemplate = new Instances(i, 0, 0);
        return this.m_InstancesTemplate;
    }
Instance moa.core.utils.Converter.formatInstance (Instance original)
Definition at line 57 of file Converter.java.
References moa.core.utils.Converter.m_InstancesTemplate, and moa.core.utils.Converter.m_L.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance().
{
        //Copy the original instance
        Instance converted = (Instance) original.copy();
        converted.setDataset(null);
        //Delete all class attributes
        for (int j = 0; j < m_L; j++) {
            converted.deleteAttributeAt(0);
        }
        //Add one of those class attributes at the begginning
        converted.insertAttributeAt(0);
        //Hopefully setting the dataset will configure that attribute properly
        converted.setDataset(m_InstancesTemplate);
        return converted;
    }
void moa.core.utils.Converter.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 89 of file Converter.java.
{
        // TODO Auto-generated method stub
    }
int moa.core.utils.Converter.getL ()
Definition at line 41 of file Converter.java.
References moa.core.utils.Converter.m_L.
                      {
        return this.m_L;
    }
List<Integer> moa.core.utils.Converter.getRelevantLabels (Instance x)
Definition at line 78 of file Converter.java.
References moa.core.utils.Converter.m_L.
Referenced by moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance().
{
        List<Integer> classValues = new LinkedList<Integer>();
        //get all class attributes
        for (int j = 0; j < m_L; j++) {
            if (x.value(j) > 0.0) {
                classValues.add(j);
            }
        }
        return classValues;
    }
Member Data Documentation
Instances moa.core.utils.Converter.m_InstancesTemplate = null [protected]
Definition at line 37 of file Converter.java.
Referenced by moa.core.utils.Converter.createTemplate(), and moa.core.utils.Converter.formatInstance().
int moa.core.utils.Converter.m_L = -1 [protected]
Definition at line 39 of file Converter.java.
Referenced by moa.core.utils.Converter.Converter(), moa.core.utils.Converter.formatInstance(), moa.core.utils.Converter.getL(), and moa.core.utils.Converter.getRelevantLabels().
The documentation for this class was generated from the following file:
main/java/moa/core/utils/Converter.java