MOA: moa.clusterers.outliers.MCOD.ISBIndex Class Reference
moa.clusterers.outliers.MCOD.ISBIndex Class Reference
Classes
class ISBNode
class ISBSearchResult
Public Member Functions
ISBIndex (double radius, int k)
Vector< ISBSearchResult > RangeSearch (ISBNode node, double radius)
void Insert (ISBNode node)
void Remove (ISBNode node)
Package Functions
Vector< ISBNode > GetAllNodes ()
Vector< ISBNode > MapGetNodes (StreamObj obj)
int MapCountObjRefs (StreamObj obj)
void MapInsert (ISBNode node)
void MapDelete (ISBNode node)
Package Attributes
MTreeStreamObjects mtree
Map< Integer, Set< ISBNode > > mapNodes
double m_radius
int m_k
Detailed Description
Definition at line 26 of file ISBIndex.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.MCOD.ISBIndex.ISBIndex (double radius, int k)
Definition at line 142 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.ISBIndex.m_k, moa.clusterers.outliers.MCOD.ISBIndex.m_radius, moa.clusterers.outliers.MCOD.ISBIndex.mapNodes, and moa.clusterers.outliers.MCOD.ISBIndex.mtree.
{
        mtree = new MTreeStreamObjects();
        mapNodes = new HashMap<Integer, Set<ISBNode>>();
        m_radius = radius;
        m_k = k;
    }
Member Function Documentation
Vector<ISBNode> moa.clusterers.outliers.MCOD.ISBIndex.GetAllNodes () [package]
Definition at line 149 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.ISBIndex.mapNodes.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        Vector<ISBNode> v = new Vector<ISBNode>();
        Iterator it = mapNodes.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pairs = (Map.Entry) it.next();
            Set<ISBNode> setNodes = (Set<ISBNode>) pairs.getValue();
            for (ISBNode n : setNodes) {
                v.add(n);
            }
        }
        return v;
    }
void moa.clusterers.outliers.MCOD.ISBIndex.Insert (ISBNode node)
Definition at line 190 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.MTreeStreamObjects.add(), moa.clusterers.outliers.MCOD.ISBIndex.MapInsert(), moa.clusterers.outliers.MCOD.ISBIndex.mtree, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        // insert object of node at mtree
        mtree.add(node.obj);
        // insert node at map
        MapInsert(node);
    }
int moa.clusterers.outliers.MCOD.ISBIndex.MapCountObjRefs (StreamObj obj) [package]
Definition at line 223 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.StreamObj.equals(), moa.clusterers.outliers.MCOD.StreamObj.hashCode, moa.clusterers.outliers.MCOD.ISBIndex.mapNodes, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.Remove().
{
        int h = obj.hashCode();
        int iCount = 0;
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            ISBNode n;
            Iterator<ISBNode> i = s.iterator();
            while (i.hasNext()) {
                n = i.next();
                if (n.obj.equals(obj))
                    iCount++;
            }
        }
        return iCount;
    }
void moa.clusterers.outliers.MCOD.ISBIndex.MapDelete (ISBNode node) [package]
Definition at line 253 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.StreamObj.hashCode, moa.clusterers.outliers.MCOD.ISBIndex.mapNodes, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.Remove().
{
        int h = node.obj.hashCode();
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            s.remove(node);
            if (s.isEmpty()) { // ### added
                mapNodes.remove(h);
            }
        }
    }
Vector<ISBNode> moa.clusterers.outliers.MCOD.ISBIndex.MapGetNodes (StreamObj obj) [package]
Definition at line 207 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.StreamObj.equals(), moa.clusterers.outliers.MCOD.StreamObj.hashCode, moa.clusterers.outliers.MCOD.ISBIndex.mapNodes, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.RangeSearch().
{
        int h = obj.hashCode();
        Vector<ISBNode> v = new Vector<ISBNode>();
        if (mapNodes.containsKey(h)) {
            Set<ISBNode> s = mapNodes.get(h);
            ISBNode node;
            Iterator<ISBNode> i = s.iterator();
            while (i.hasNext()) {
                node = i.next();
                if (node.obj.equals(obj))
                    v.add(node);
            }
        }
        return v;
    }
void moa.clusterers.outliers.MCOD.ISBIndex.MapInsert (ISBNode node) [package]
Definition at line 239 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.StreamObj.hashCode, moa.clusterers.outliers.MCOD.ISBIndex.mapNodes, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.Insert().
{
        int h = node.obj.hashCode();
        Set<ISBNode> s;
        if (mapNodes.containsKey(h)) {
            s = mapNodes.get(h);
            s.add(node);
        }
        else {
            s = new HashSet<ISBNode>();
            s.add(node);
            mapNodes.put(h, s);
        }
    }
Vector<ISBSearchResult> moa.clusterers.outliers.MCOD.ISBIndex.RangeSearch (ISBNode node, double radius)
Definition at line 172 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.ISBIndex.MapGetNodes(), moa.clusterers.outliers.MCOD.ISBIndex.mtree, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        Vector<ISBSearchResult> results = new Vector<ISBSearchResult>();
        StreamObj obj;
        double d;
        MTreeStreamObjects.Query query = mtree.getNearestByRange(node.obj, radius);
        for (MTreeStreamObjects.ResultItem q : query) {
            // get next obj found within range
            obj = q.data;
            // get distance of obj from query
            d = q.distance;
            // get all nodes referencing obj
            Vector<ISBNode> nodes = MapGetNodes(obj);
            for (int i = 0; i < nodes.size(); i++)
                results.add(new ISBSearchResult(nodes.get(i), d));
        }
        return results;
    }
void moa.clusterers.outliers.MCOD.ISBIndex.Remove (ISBNode node)
Definition at line 197 of file ISBIndex.java.
References moa.clusterers.outliers.MCOD.ISBIndex.MapCountObjRefs(), moa.clusterers.outliers.MCOD.ISBIndex.MapDelete(), moa.clusterers.outliers.MCOD.ISBIndex.mtree, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.obj, and moa.clusterers.outliers.MCOD.MTreeStreamObjects.remove().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        // remove from map
        MapDelete(node);
        // check if stream object at mtree is still being referenced
        if (MapCountObjRefs(node.obj) <= 0) {
            // delete stream object from mtree
            mtree.remove(node.obj);
        }
    }
Member Data Documentation
int moa.clusterers.outliers.MCOD.ISBIndex.m_k [package]
Definition at line 140 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.ISBIndex().
double moa.clusterers.outliers.MCOD.ISBIndex.m_radius [package]
Definition at line 139 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.ISBIndex().
Map<Integer, Set<ISBNode> > moa.clusterers.outliers.MCOD.ISBIndex.mapNodes [package]
Definition at line 138 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.GetAllNodes(), moa.clusterers.outliers.MCOD.ISBIndex.ISBIndex(), moa.clusterers.outliers.MCOD.ISBIndex.MapCountObjRefs(), moa.clusterers.outliers.MCOD.ISBIndex.MapDelete(), moa.clusterers.outliers.MCOD.ISBIndex.MapGetNodes(), and moa.clusterers.outliers.MCOD.ISBIndex.MapInsert().
MTreeStreamObjects moa.clusterers.outliers.MCOD.ISBIndex.mtree [package]
Definition at line 137 of file ISBIndex.java.
Referenced by moa.clusterers.outliers.MCOD.ISBIndex.Insert(), moa.clusterers.outliers.MCOD.ISBIndex.ISBIndex(), moa.clusterers.outliers.MCOD.ISBIndex.RangeSearch(), and moa.clusterers.outliers.MCOD.ISBIndex.Remove().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/ISBIndex.java