MOA: moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node Class Reference
moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node Class Reference
Public Member Functions
Node (double val, double label, double weight)
void insertValue (double val, double label, double weight)
Insert a new value into the tree, updating both the sum of values and sum of squared values arrays.
Public Attributes
double cut_point
DoubleVector leftStatistics = new DoubleVector()
DoubleVector rightStatistics = new DoubleVector()
Node left
Node right
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 41 of file FIMTDDNumericAttributeClassObserver.java.
Constructor & Destructor Documentation
moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.Node (double val, double label, double weight)
Reimplemented in moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.
Definition at line 56 of file FIMTDDNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.cut_point, and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.leftStatistics.
Referenced by moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue().
{
            this.cut_point = val;
            this.leftStatistics.addToValue(0, 1);
            this.leftStatistics.addToValue(1, label);
            this.leftStatistics.addToValue(2, label * label);
        }
Member Function Documentation
void moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue (double val, double label, double weight)
Insert a new value into the tree, updating both the sum of values and sum of squared values arrays.
Reimplemented in moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.
Definition at line 67 of file FIMTDDNumericAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.cut_point, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.left, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.leftStatistics, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.Node(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.right, and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.rightStatistics.
Referenced by moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.observeAttributeClass().
{
        // If the new value equals the value stored in a node, update
            // the left (<=) node information
            if (val == this.cut_point) {
                this.leftStatistics.addToValue(0, 1);
                this.leftStatistics.addToValue(1, label);
                this.leftStatistics.addToValue(2, label * label);
            } // If the new value is less than the value in a node, update the
            // left distribution and send the value down to the left child node.
            // If no left child exists, create one
            else if (val <= this.cut_point) {
                this.leftStatistics.addToValue(0, 1);
                this.leftStatistics.addToValue(1, label);
                this.leftStatistics.addToValue(2, label * label);
                if (this.left == null) {
                    this.left = new Node(val, label, weight);
                } else {
                    this.left.insertValue(val, label, weight);
                }
            } // If the new value is greater than the value in a node, update the
            // right (>) distribution and send the value down to the right child node.
            // If no right child exists, create one
            else { // val > cut_point
                this.rightStatistics.addToValue(0, 1);
                this.rightStatistics.addToValue(1, label);
                this.rightStatistics.addToValue(2, label * label);
                if (this.right == null) {
                    this.right = new Node(val, label, weight);
                } else {
                    this.right.insertValue(val, label, weight);
                }
            }
        }
Member Data Documentation
double moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.cut_point
Definition at line 46 of file FIMTDDNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.Node().
Node moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.left
Definition at line 53 of file FIMTDDNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue().
DoubleVector moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.leftStatistics = new DoubleVector()
Definition at line 49 of file FIMTDDNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.Node().
Node moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.right
Definition at line 54 of file FIMTDDNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue().
DoubleVector moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.rightStatistics = new DoubleVector()
Definition at line 50 of file FIMTDDNumericAttributeClassObserver.java.
Referenced by moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.insertValue().
final long moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.Node.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.Node.
Definition at line 43 of file FIMTDDNumericAttributeClassObserver.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/FIMTDDNumericAttributeClassObserver.java