MOA: moa.gui.FloatOptionEditComponent Class Reference
moa.gui.FloatOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a float option.
Public Member Functions
FloatOptionEditComponent (FloatOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
Static Public Attributes
static final int SLIDER_RESOLUTION = 100000
Protected Member Functions
int floatValueToSliderValue (double floatValue)
double sliderValueToFloatValue (int sliderValue)
Protected Attributes
FloatOption editedOption
JSpinner spinner
JSlider slider
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a float option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 40 of file FloatOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.FloatOptionEditComponent.FloatOptionEditComponent (FloatOption option)
Definition at line 53 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.editedOption, moa.gui.FloatOptionEditComponent.floatValueToSliderValue(), moa.options.FloatOption.getMaxValue(), moa.options.FloatOption.getMinValue(), moa.options.FloatOption.getValue(), moa.gui.FloatOptionEditComponent.slider, moa.gui.FloatOptionEditComponent.SLIDER_RESOLUTION, moa.gui.FloatOptionEditComponent.sliderValueToFloatValue(), and moa.gui.FloatOptionEditComponent.spinner.
{
        this.editedOption = option;
        double minVal = option.getMinValue();
        double maxVal = option.getMaxValue();
        setLayout(new GridLayout(1, 0));
        this.spinner = new JSpinner(new SpinnerNumberModel(option.getValue(),
                minVal, maxVal, 0.001));
        add(this.spinner);
        if ((minVal > Double.NEGATIVE_INFINITY)
                && (maxVal < Double.POSITIVE_INFINITY)) {
            this.slider = new JSlider(0, SLIDER_RESOLUTION,
                    floatValueToSliderValue(option.getValue()));
            add(this.slider);
            this.slider.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    FloatOptionEditComponent.this.spinner.setValue(sliderValueToFloatValue(FloatOptionEditComponent.this.slider.getValue()));
                }
            });
            this.spinner.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    FloatOptionEditComponent.this.slider.setValue(floatValueToSliderValue(((Double) FloatOptionEditComponent.this.spinner.getValue()).doubleValue()));
                }
            });
        }
    }
Member Function Documentation
void moa.gui.FloatOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 98 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.editedOption, moa.options.FloatOption.setValue(), and moa.gui.FloatOptionEditComponent.spinner.
{
        this.editedOption.setValue(((Double) this.spinner.getValue()).doubleValue());
        // this.editedOption.setValue(Double.parseDouble(this.spinner.getValue().toString()));
    }
int moa.gui.FloatOptionEditComponent.floatValueToSliderValue (double floatValue) [protected]
Definition at line 83 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.editedOption, moa.options.FloatOption.getMaxValue(), moa.options.FloatOption.getMinValue(), and moa.gui.FloatOptionEditComponent.SLIDER_RESOLUTION.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent().
{
        double minVal = this.editedOption.getMinValue();
        double maxVal = this.editedOption.getMaxValue();
        return (int) Math.round((floatValue - minVal) / (maxVal - minVal)
                * SLIDER_RESOLUTION);
    }
Option moa.gui.FloatOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 104 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.FloatOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 109 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.spinner.
{
        this.spinner.setValue(FloatOption.cliStringToDouble(cliString));
    }
double moa.gui.FloatOptionEditComponent.sliderValueToFloatValue (int sliderValue) [protected]
Definition at line 90 of file FloatOptionEditComponent.java.
References moa.gui.FloatOptionEditComponent.editedOption, moa.options.FloatOption.getMaxValue(), moa.options.FloatOption.getMinValue(), and moa.gui.FloatOptionEditComponent.SLIDER_RESOLUTION.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent().
{
        double minVal = this.editedOption.getMinValue();
        double maxVal = this.editedOption.getMaxValue();
        return minVal
                + (((double) sliderValue / SLIDER_RESOLUTION) * (maxVal - minVal));
    }
Member Data Documentation
FloatOption moa.gui.FloatOptionEditComponent.editedOption [protected]
Definition at line 47 of file FloatOptionEditComponent.java.
Referenced by moa.gui.FloatOptionEditComponent.applyState(), moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), moa.gui.FloatOptionEditComponent.floatValueToSliderValue(), moa.gui.FloatOptionEditComponent.getEditedOption(), and moa.gui.FloatOptionEditComponent.sliderValueToFloatValue().
final long moa.gui.FloatOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 43 of file FloatOptionEditComponent.java.
JSlider moa.gui.FloatOptionEditComponent.slider [protected]
Definition at line 51 of file FloatOptionEditComponent.java.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent().
final int moa.gui.FloatOptionEditComponent.SLIDER_RESOLUTION = 100000 [static]
Definition at line 45 of file FloatOptionEditComponent.java.
Referenced by moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), moa.gui.FloatOptionEditComponent.floatValueToSliderValue(), and moa.gui.FloatOptionEditComponent.sliderValueToFloatValue().
JSpinner moa.gui.FloatOptionEditComponent.spinner [protected]
Definition at line 49 of file FloatOptionEditComponent.java.
Referenced by moa.gui.FloatOptionEditComponent.applyState(), moa.gui.FloatOptionEditComponent.FloatOptionEditComponent(), and moa.gui.FloatOptionEditComponent.setEditState().
The documentation for this class was generated from the following file:
main/java/moa/gui/FloatOptionEditComponent.java