MOA: moa.streams.generators.RandomRBFGenerator Class Reference
moa.streams.generators.RandomRBFGenerator Class Reference
Stream generator for a random radial basis function stream.
Classes
class Centroid
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
InstancesHeader getHeader ()
Gets the header of this stream.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
void restart ()
Restarts this stream.
Instance nextInstance ()
Gets the next instance from this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption modelRandomSeedOption
IntOption instanceRandomSeedOption
IntOption numClassesOption
IntOption numAttsOption
IntOption numCentroidsOption
Protected Member Functions
void generateHeader ()
void generateCentroids ()
Protected Attributes
InstancesHeader streamHeader
Centroid[] centroids
double[] centroidWeights
Random instanceRandom
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for a random radial basis function stream.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 45 of file RandomRBFGenerator.java.
Member Function Documentation
long moa.streams.generators.RandomRBFGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 105 of file RandomRBFGenerator.java.
{
        return -1;
    }
void moa.streams.generators.RandomRBFGenerator.generateCentroids () [protected]
Reimplemented in moa.streams.generators.RandomRBFGeneratorDrift.
Definition at line 165 of file RandomRBFGenerator.java.
References moa.streams.generators.RandomRBFGenerator.centroids, moa.streams.generators.RandomRBFGenerator.centroidWeights, moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.modelRandomSeedOption, moa.streams.generators.RandomRBFGenerator.numAttsOption, moa.streams.generators.RandomRBFGenerator.numCentroidsOption, and moa.streams.generators.RandomRBFGenerator.numClassesOption.
Referenced by moa.streams.generators.RandomRBFGenerator.prepareForUseImpl().
{
        Random modelRand = new Random(this.modelRandomSeedOption.getValue());
        this.centroids = new Centroid[this.numCentroidsOption.getValue()];
        this.centroidWeights = new double[this.centroids.length];
        for (int i = 0; i < this.centroids.length; i++) {
            this.centroids[i] = new Centroid();
            double[] randCentre = new double[this.numAttsOption.getValue()];
            for (int j = 0; j < randCentre.length; j++) {
                randCentre[j] = modelRand.nextDouble();
            }
            this.centroids[i].centre = randCentre;
            this.centroids[i].classLabel = modelRand.nextInt(this.numClassesOption.getValue());
            this.centroids[i].stdDev = modelRand.nextDouble();
            this.centroidWeights[i] = modelRand.nextDouble();
        }
    }
void moa.streams.generators.RandomRBFGenerator.generateHeader () [protected]
Definition at line 150 of file RandomRBFGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.numAttsOption, moa.streams.generators.RandomRBFGenerator.numClassesOption, and moa.streams.generators.RandomRBFGenerator.streamHeader.
Referenced by moa.streams.generators.RandomRBFGenerator.prepareForUseImpl().
{
        FastVector attributes = new FastVector();
        for (int i = 0; i < this.numAttsOption.getValue(); i++) {
            attributes.addElement(new Attribute("att" + (i + 1)));
        }
        FastVector classLabels = new FastVector();
        for (int i = 0; i < this.numClassesOption.getValue(); i++) {
            classLabels.addElement("class" + (i + 1));
        }
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
    }
void moa.streams.generators.RandomRBFGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Reimplemented in moa.streams.generators.RandomRBFGeneratorDrift.
Definition at line 183 of file RandomRBFGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.RandomRBFGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 100 of file RandomRBFGenerator.java.
References moa.streams.generators.RandomRBFGenerator.streamHeader.
Referenced by moa.streams.generators.RandomRBFGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.RandomRBFGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.streams.generators.RandomRBFGeneratorDrift.
Definition at line 49 of file RandomRBFGenerator.java.
{
        return "Generates a random radial basis function stream.";
    }
boolean moa.streams.generators.RandomRBFGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 110 of file RandomRBFGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.RandomRBFGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 115 of file RandomRBFGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.RandomRBFGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Reimplemented in moa.streams.generators.RandomRBFGeneratorDrift.
Definition at line 125 of file RandomRBFGenerator.java.
References moa.streams.generators.RandomRBFGenerator.Centroid.centre, moa.streams.generators.RandomRBFGenerator.centroids, moa.streams.generators.RandomRBFGenerator.centroidWeights, moa.streams.generators.RandomRBFGenerator.Centroid.classLabel, moa.streams.generators.RandomRBFGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.instanceRandom, moa.streams.generators.RandomRBFGenerator.numAttsOption, and moa.streams.generators.RandomRBFGenerator.Centroid.stdDev.
{
        Centroid centroid = this.centroids[MiscUtils.chooseRandomIndexBasedOnWeights(this.centroidWeights,
                this.instanceRandom)];
        int numAtts = this.numAttsOption.getValue();
        double[] attVals = new double[numAtts + 1];
        for (int i = 0; i < numAtts; i++) {
            attVals[i] = (this.instanceRandom.nextDouble() * 2.0) - 1.0;
        }
        double magnitude = 0.0;
        for (int i = 0; i < numAtts; i++) {
            magnitude += attVals[i] * attVals[i];
        }
        magnitude = Math.sqrt(magnitude);
        double desiredMag = this.instanceRandom.nextGaussian()
                * centroid.stdDev;
        double scale = desiredMag / magnitude;
        for (int i = 0; i < numAtts; i++) {
            attVals[i] = centroid.centre[i] + attVals[i] * scale;
        }
        Instance inst = new DenseInstance(1.0, attVals);
        inst.setDataset(getHeader());
        inst.setClassValue(centroid.classLabel);
        return inst;
    }
void moa.streams.generators.RandomRBFGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 91 of file RandomRBFGenerator.java.
References moa.streams.generators.RandomRBFGenerator.generateCentroids(), moa.streams.generators.RandomRBFGenerator.generateHeader(), moa.streams.generators.RandomRBFGenerator.restart(), and moa.tasks.TaskMonitor.setCurrentActivity().
{
        monitor.setCurrentActivity("Preparing random RBF...", -1.0);
        generateHeader();
        generateCentroids();
        restart();
    }
void moa.streams.generators.RandomRBFGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 120 of file RandomRBFGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.RandomRBFGenerator.instanceRandom, and moa.streams.generators.RandomRBFGenerator.instanceRandomSeedOption.
Referenced by moa.streams.generators.RandomRBFGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
    }
Member Data Documentation
Centroid [] moa.streams.generators.RandomRBFGenerator.centroids [protected]
Definition at line 84 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), moa.streams.generators.RandomRBFGenerator.generateCentroids(), moa.streams.generators.RandomRBFGeneratorDrift.nextInstance(), and moa.streams.generators.RandomRBFGenerator.nextInstance().
double [] moa.streams.generators.RandomRBFGenerator.centroidWeights [protected]
Definition at line 86 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.generateCentroids(), and moa.streams.generators.RandomRBFGenerator.nextInstance().
Random moa.streams.generators.RandomRBFGenerator.instanceRandom [protected]
Definition at line 88 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.nextInstance(), and moa.streams.generators.RandomRBFGenerator.restart().
IntOption moa.streams.generators.RandomRBFGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 58 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.restart().
IntOption moa.streams.generators.RandomRBFGenerator.modelRandomSeedOption
Initial value:
 new IntOption("modelRandomSeed",
            'r', "Seed for random generation of model.", 1)
Definition at line 55 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), and moa.streams.generators.RandomRBFGenerator.generateCentroids().
IntOption moa.streams.generators.RandomRBFGenerator.numAttsOption
Initial value:
 new IntOption("numAtts", 'a',
            "The number of attributes to generate.", 10, 0, Integer.MAX_VALUE)
Definition at line 65 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), moa.streams.generators.RandomRBFGenerator.generateCentroids(), moa.streams.generators.RandomRBFGenerator.generateHeader(), moa.streams.generators.RandomRBFGeneratorDrift.nextInstance(), and moa.streams.generators.RandomRBFGenerator.nextInstance().
IntOption moa.streams.generators.RandomRBFGenerator.numCentroidsOption
Initial value:
 new IntOption("numCentroids", 'n',
            "The number of centroids in the model.", 50, 1, Integer.MAX_VALUE)
Definition at line 68 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.generateCentroids().
IntOption moa.streams.generators.RandomRBFGenerator.numClassesOption
Initial value:
 new IntOption("numClasses", 'c',
            "The number of classes to generate.", 2, 2, Integer.MAX_VALUE)
Definition at line 62 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.generateCentroids(), and moa.streams.generators.RandomRBFGenerator.generateHeader().
final long moa.streams.generators.RandomRBFGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.streams.generators.RandomRBFGeneratorDrift.
Definition at line 53 of file RandomRBFGenerator.java.
InstancesHeader moa.streams.generators.RandomRBFGenerator.streamHeader [protected]
Definition at line 82 of file RandomRBFGenerator.java.
Referenced by moa.streams.generators.RandomRBFGenerator.generateHeader(), and moa.streams.generators.RandomRBFGenerator.getHeader().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/RandomRBFGenerator.java