MOA: moa.classifiers.rules.functions.Perceptron Class Reference
moa.classifiers.rules.functions.Perceptron Class Reference
Public Member Functions
Perceptron ()
Perceptron (Perceptron p)
void setWeights (double[] w)
double[] getWeights ()
int getInstancesSeen ()
void setInstancesSeen (int pInstancesSeen)
void resetLearningImpl ()
A method to reset the model.
void reset ()
void resetError ()
void trainOnInstanceImpl (Instance inst)
Update the model using the provided instance.
double normalizedPrediction (Instance inst)
double prediction (double[] instanceValues)
double[] normalizedInstance (Instance inst)
double computeSD (double squaredVal, double val, int size)
double updateWeights (Instance inst, double learningRatio)
void normalizeWeights ()
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
void setLearningRatio (double learningRatio)
double getCurrentError ()
Public Attributes
FlagOption constantLearningRatioDecayOption
FloatOption learningRatioOption
FloatOption learningRateDecayOption
FloatOption fadingFactorOption
DoubleVector perceptronattributeStatistics = new DoubleVector()
DoubleVector squaredperceptronattributeStatistics = new DoubleVector()
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
double fadingFactor
double learningRatio
double learningRateDecay
double[] weightAttribute
int perceptronInstancesSeen
int perceptronYSeen
double accumulatedError
boolean initialisePerceptron
double perceptronsumY
double squaredperceptronsumY
Private Member Functions
double prediction (Instance inst)
Output the prediction made by this perceptron on the given instance.
double denormalizedPrediction (double normalizedPrediction)
double normalizeActualClassValue (Instance inst)
Private Attributes
final double SD_THRESHOLD = 0.0000001
double nError
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 30 of file Perceptron.java.
Constructor & Destructor Documentation
moa.classifiers.rules.functions.Perceptron.Perceptron ()
Definition at line 80 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.initialisePerceptron.
    {
        this.initialisePerceptron = true;
    }
moa.classifiers.rules.functions.Perceptron.Perceptron (Perceptron p)
Definition at line 88 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.constantLearningRatioDecayOption, moa.classifiers.rules.functions.Perceptron.fadingFactor, moa.classifiers.rules.functions.Perceptron.fadingFactorOption, moa.classifiers.rules.functions.Perceptron.initialisePerceptron, moa.classifiers.rules.functions.Perceptron.learningRateDecay, moa.classifiers.rules.functions.Perceptron.learningRateDecayOption, moa.classifiers.rules.functions.Perceptron.learningRatio, moa.classifiers.rules.functions.Perceptron.learningRatioOption, moa.classifiers.rules.functions.Perceptron.nError, moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen, moa.classifiers.rules.functions.Perceptron.perceptronsumY, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY, and moa.classifiers.rules.functions.Perceptron.weightAttribute.
{
        super();
        this.constantLearningRatioDecayOption = p.constantLearningRatioDecayOption;
        this.learningRatioOption = p.learningRatioOption;
        this.learningRateDecayOption=p.learningRateDecayOption;
        this.fadingFactorOption = p.fadingFactorOption;
        this.nError = p.nError;
        this.fadingFactor = p.fadingFactor;
        this.learningRatio = p.learningRatio;
        this.learningRateDecay = p.learningRateDecay;
        if (p.weightAttribute!=null)
            this.weightAttribute = p.weightAttribute.clone();
        this.perceptronattributeStatistics = new DoubleVector(p.perceptronattributeStatistics);
        this.squaredperceptronattributeStatistics = new DoubleVector(p.squaredperceptronattributeStatistics);
        this.perceptronInstancesSeen = p.perceptronInstancesSeen;
        this.initialisePerceptron = p.initialisePerceptron;
        this.perceptronsumY = p.perceptronsumY;
        this.squaredperceptronsumY = p.squaredperceptronsumY;
        this.perceptronYSeen=p.perceptronYSeen;
    }
Member Function Documentation
double moa.classifiers.rules.functions.Perceptron.computeSD (double squaredVal, double val, int size)
Definition at line 261 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), and moa.classifiers.rules.functions.Perceptron.normalizedInstance().
{
        if (size > 1) {
            return  Math.sqrt((squaredVal - ((val * val) / size)) / (size - 1.0));
        }
        return 0.0;
    }
double moa.classifiers.rules.functions.Perceptron.denormalizedPrediction (double normalizedPrediction) [private]
Definition at line 219 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.computeSD(), moa.classifiers.rules.functions.Perceptron.initialisePerceptron, moa.classifiers.rules.functions.Perceptron.perceptronsumY, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.SD_THRESHOLD, and moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY.
Referenced by moa.classifiers.rules.functions.Perceptron.prediction(), and moa.classifiers.rules.functions.Perceptron.updateWeights().
{
        if (this.initialisePerceptron==false){
            double meanY = perceptronsumY / perceptronYSeen;
            double sdY = computeSD(squaredperceptronsumY, perceptronsumY, perceptronYSeen);
            if (sdY > SD_THRESHOLD)
                return normalizedPrediction * sdY + meanY;
            else
                return normalizedPrediction + meanY;
        }
        else
            return normalizedPrediction; //Perceptron may have been "reseted". Use old weights to predict
    }
double moa.classifiers.rules.functions.Perceptron.getCurrentError ()
Definition at line 360 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.accumulatedError, and moa.classifiers.rules.functions.Perceptron.nError.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getCurrentError(), and moa.classifiers.rules.core.RuleActiveRegressionNode.getLearnerToUse().
    {
        if (nError>0)
            return accumulatedError/nError;
        else
            return Double.MAX_VALUE;
    }
int moa.classifiers.rules.functions.Perceptron.getInstancesSeen ()
Definition at line 123 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), and moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly().
{
        return perceptronInstancesSeen;
    }
void moa.classifiers.rules.functions.Perceptron.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 339 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.weightAttribute.
{
        if(this.weightAttribute!=null){
            for(int i=0; i< this.weightAttribute.length-1; ++i)
            {
                if(this.weightAttribute[i]>=0 && i>0)
                    out.append(" +" + Math.round(this.weightAttribute[i]*1000)/1000.0 + " X" + i );
                else
                    out.append(" " + Math.round(this.weightAttribute[i]*1000)/1000.0 + " X" + i );
            }
            if(this.weightAttribute[this.weightAttribute.length-1]>=0 )
                out.append(" +" + Math.round(this.weightAttribute[this.weightAttribute.length-1]*1000)/1000.0);
            else
                out.append(" " + Math.round(this.weightAttribute[this.weightAttribute.length-1]*1000)/1000.0);
        }
    }
Measurement [] moa.classifiers.rules.functions.Perceptron.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 334 of file Perceptron.java.
{
        return null;
    }
double [] moa.classifiers.rules.functions.Perceptron.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 329 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.prediction().
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getPrediction().
{
        return new double[]{this.prediction(inst)};
    }
double [] moa.classifiers.rules.functions.Perceptron.getWeights ()
Definition at line 116 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.weightAttribute.
    {
        return this.weightAttribute;
    }
boolean moa.classifiers.rules.functions.Perceptron.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 324 of file Perceptron.java.
{
        return true;
    }
double moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue (Instance inst) [private]
Definition at line 310 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.computeSD(), moa.classifiers.rules.functions.Perceptron.perceptronsumY, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.SD_THRESHOLD, and moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY.
Referenced by moa.classifiers.rules.functions.Perceptron.updateWeights().
{
        double meanY = perceptronsumY / perceptronYSeen;
        double sdY = computeSD(squaredperceptronsumY, perceptronsumY, perceptronYSeen);
        double normalizedY = 0.0;
        if (sdY > SD_THRESHOLD){
            normalizedY = (inst.classValue() - meanY) / sdY;
        }else{
            normalizedY = inst.classValue() - meanY;
        }
        return normalizedY;
    }
double [] moa.classifiers.rules.functions.Perceptron.normalizedInstance (Instance inst)
Definition at line 246 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.computeSD(), moa.core.DoubleVector.getValue(), moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.SD_THRESHOLD, and moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics.
Referenced by moa.classifiers.rules.functions.Perceptron.normalizedPrediction(), moa.classifiers.rules.functions.Perceptron.prediction(), and moa.classifiers.rules.functions.Perceptron.updateWeights().
{
        // Normalize Instance
        double[] normalizedInstance = new double[inst.numAttributes()];
        for(int j = 0; j < inst.numAttributes() -1; j++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(j, inst);
            double mean = perceptronattributeStatistics.getValue(j) / perceptronYSeen;
            double sd = computeSD(squaredperceptronattributeStatistics.getValue(j), perceptronattributeStatistics.getValue(j), perceptronYSeen);
            if (sd > SD_THRESHOLD)
                normalizedInstance[j] = (inst.value(instAttIndex) - mean)/ sd;
            else
                normalizedInstance[j] = inst.value(instAttIndex) - mean;
        }
        return normalizedInstance;
    }
double moa.classifiers.rules.functions.Perceptron.normalizedPrediction (Instance inst)
Definition at line 212 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.normalizedInstance(), and moa.classifiers.rules.functions.Perceptron.prediction().
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.getNormalizedPrediction(), and moa.classifiers.rules.functions.Perceptron.prediction().
    {
        double[] normalizedInstance = normalizedInstance(inst);
        double normalizedPrediction = prediction(normalizedInstance);
        return normalizedPrediction;
    }
void moa.classifiers.rules.functions.Perceptron.normalizeWeights ()
Definition at line 299 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.weightAttribute.
{
        double sumWeights = 0.0;
        for (int j = 0; j < this.weightAttribute.length ; j++) {
            sumWeights += Math.abs(this.weightAttribute[j]);
        }
        for (int j = 0; j < this.weightAttribute.length; j++) {
            this.weightAttribute[j] = this.weightAttribute[j] / sumWeights;
        }
    }
double moa.classifiers.rules.functions.Perceptron.prediction (double[] instanceValues)
Definition at line 233 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.initialisePerceptron, moa.classifiers.rules.functions.Perceptron.prediction(), and moa.classifiers.rules.functions.Perceptron.weightAttribute.
    {
        double prediction = 0.0;
        if(this.initialisePerceptron == false)
        {
            for (int j = 0; j < instanceValues.length - 1; j++) {
                prediction += this.weightAttribute[j] * instanceValues[j];
            }
            prediction += this.weightAttribute[instanceValues.length - 1];
        }
        return prediction;
    }
double moa.classifiers.rules.functions.Perceptron.prediction (Instance inst) [private]
Output the prediction made by this perceptron on the given instance.
Definition at line 205 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), and moa.classifiers.rules.functions.Perceptron.normalizedPrediction().
Referenced by moa.classifiers.rules.functions.Perceptron.getVotesForInstance(), moa.classifiers.rules.functions.Perceptron.normalizedPrediction(), moa.classifiers.rules.functions.Perceptron.prediction(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), and moa.classifiers.rules.functions.Perceptron.updateWeights().
    {
        double[] normalizedInstance = normalizedInstance(inst);
        double normalizedPrediction = prediction(normalizedInstance);
        return denormalizedPrediction(normalizedPrediction);
    }
void moa.classifiers.rules.functions.Perceptron.reset ()
Definition at line 140 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.accumulatedError, moa.classifiers.rules.functions.Perceptron.nError, moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen, moa.classifiers.rules.functions.Perceptron.perceptronsumY, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics, and moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY.
Referenced by moa.classifiers.rules.functions.Perceptron.resetLearningImpl().
                       {
        this.nError=0.0;
        this.accumulatedError = 0.0;
        this.perceptronInstancesSeen = 0;
        this.perceptronattributeStatistics = new DoubleVector();
        this.squaredperceptronattributeStatistics = new DoubleVector();
        this.perceptronsumY = 0.0;
        this.squaredperceptronsumY = 0.0;
        this.perceptronYSeen=0;
    }
void moa.classifiers.rules.functions.Perceptron.resetError ()
Definition at line 151 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.accumulatedError, and moa.classifiers.rules.functions.Perceptron.nError.
{
        this.nError=0.0;
        this.accumulatedError = 0.0;
    }
void moa.classifiers.rules.functions.Perceptron.resetLearningImpl () [virtual]
A method to reset the model.
Implements moa.classifiers.AbstractClassifier.
Definition at line 135 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.initialisePerceptron, and moa.classifiers.rules.functions.Perceptron.reset().
{
        this.initialisePerceptron = true;
        this.reset();
    }
void moa.classifiers.rules.functions.Perceptron.setInstancesSeen (int pInstancesSeen)
Definition at line 127 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen.
{
        this.perceptronInstancesSeen = pInstancesSeen;
    }
void moa.classifiers.rules.functions.Perceptron.setLearningRatio (double learningRatio)
Definition at line 355 of file Perceptron.java.
{
        this.learningRatio=learningRatio;
    }
void moa.classifiers.rules.functions.Perceptron.setWeights (double[] w)
Definition at line 111 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.weightAttribute.
    {
        this.weightAttribute = w;
    }
void moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl (Instance inst) [virtual]
Update the model using the provided instance.
Implements moa.classifiers.AbstractClassifier.
Definition at line 159 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.accumulatedError, moa.core.DoubleVector.addToValue(), moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.rules.functions.Perceptron.constantLearningRatioDecayOption, moa.classifiers.rules.functions.Perceptron.fadingFactor, moa.classifiers.rules.functions.Perceptron.fadingFactorOption, moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.classifiers.rules.functions.Perceptron.initialisePerceptron, moa.options.FlagOption.isSet, moa.classifiers.rules.functions.Perceptron.learningRateDecay, moa.classifiers.rules.functions.Perceptron.learningRateDecayOption, moa.classifiers.rules.functions.Perceptron.learningRatio, moa.classifiers.rules.functions.Perceptron.learningRatioOption, moa.classifiers.rules.functions.Perceptron.nError, moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen, moa.classifiers.rules.functions.Perceptron.perceptronsumY, moa.classifiers.rules.functions.Perceptron.perceptronYSeen, moa.classifiers.rules.functions.Perceptron.prediction(), moa.classifiers.AbstractClassifier.randomSeedOption, moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics, moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY, moa.classifiers.rules.functions.Perceptron.updateWeights(), and moa.classifiers.rules.functions.Perceptron.weightAttribute.
{
        accumulatedError= Math.abs(this.prediction(inst)-inst.classValue()) + fadingFactor*accumulatedError;
        nError=1+fadingFactor*nError;
        // Initialise Perceptron if necessary
        if (this.initialisePerceptron == true) {
            this.fadingFactor=this.fadingFactorOption.getValue();
            this.classifierRandom.setSeed(randomSeedOption.getValue());
            this.initialisePerceptron = false; // not in resetLearningImpl() because it needs Instance!
            this.weightAttribute = new double[inst.numAttributes()];
            for (int j = 0; j < inst.numAttributes(); j++) {
                weightAttribute[j] = 2 * this.classifierRandom.nextDouble() - 1;
            }
            // Update Learning Rate
            learningRatio = learningRatioOption.getValue();
            this.learningRateDecay = learningRateDecayOption.getValue();
        }
        // Update attribute statistics
        this.perceptronInstancesSeen++;
        this.perceptronYSeen++;
        for(int j = 0; j < inst.numAttributes() -1; j++)
        {
            perceptronattributeStatistics.addToValue(j, inst.value(j));
            squaredperceptronattributeStatistics.addToValue(j, inst.value(j)*inst.value(j));
        }
        this.perceptronsumY += inst.classValue();
        this.squaredperceptronsumY += inst.classValue() * inst.classValue();
        if(constantLearningRatioDecayOption.isSet()==false){
            learningRatio = learningRatioOption.getValue() / (1+ perceptronInstancesSeen*learningRateDecay);
        }
        //double prediction = this.updateWeights(inst,learningRatio);
        //accumulatedError= Math.abs(prediction-inst.classValue()) + fadingFactor*accumulatedError;
        this.updateWeights(inst,learningRatio);
    }
double moa.classifiers.rules.functions.Perceptron.updateWeights (Instance inst, double learningRatio)
Definition at line 268 of file Perceptron.java.
References moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.rules.functions.Perceptron.prediction(), and moa.classifiers.rules.functions.Perceptron.weightAttribute.
Referenced by moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
{
        // Normalize Instance
        double[] normalizedInstance = normalizedInstance(inst);
        // Compute the Normalized Prediction of Perceptron
        double normalizedPredict= prediction(normalizedInstance);
        double normalizedY = normalizeActualClassValue(inst);
        double sumWeights = 0.0;
        double delta = normalizedY - normalizedPredict;
        for (int j = 0; j < inst.numAttributes() - 1; j++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(j, inst);
            if(inst.attribute(instAttIndex).isNumeric()) {
                this.weightAttribute[j] += learningRatio * delta * normalizedInstance[j];
                sumWeights += Math.abs(this.weightAttribute[j]);
            }
        }
        this.weightAttribute[inst.numAttributes() - 1] += learningRatio * delta;
        sumWeights += Math.abs(this.weightAttribute[inst.numAttributes() - 1]);
        if (sumWeights > inst.numAttributes()) { // Lasso regression
            for (int j = 0; j < inst.numAttributes() - 1; j++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(j, inst);
                if(inst.attribute(instAttIndex).isNumeric()) {
                    this.weightAttribute[j] = this.weightAttribute[j] / sumWeights;
                }
            }
            this.weightAttribute[inst.numAttributes() - 1]  = this.weightAttribute[inst.numAttributes() - 1] / sumWeights;
        }
        return denormalizedPrediction(normalizedPredict);
    }
Member Data Documentation
double moa.classifiers.rules.functions.Perceptron.accumulatedError [protected]
Definition at line 70 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.getCurrentError(), moa.classifiers.rules.functions.Perceptron.reset(), moa.classifiers.rules.functions.Perceptron.resetError(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
FlagOption moa.classifiers.rules.functions.Perceptron.constantLearningRatioDecayOption
Initial value:
 new FlagOption(
            "learningRatio_Decay_set_constant", 'd',
            "Learning Ratio Decay in Perceptron set to be constant. (The next parameter).")
Definition at line 36 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.fadingFactor [protected]
Definition at line 53 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.functions.Perceptron.fadingFactorOption
Initial value:
 new FloatOption(
            "fadingFactor", 'e',
            "Fading factor for the Perceptron accumulated error", 0.99, 0, 1)
Definition at line 48 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
boolean moa.classifiers.rules.functions.Perceptron.initialisePerceptron [protected]
Definition at line 73 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.prediction(), moa.classifiers.rules.functions.Perceptron.resetLearningImpl(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.learningRateDecay [protected]
Definition at line 57 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.functions.Perceptron.learningRateDecayOption
Initial value:
 new FloatOption(
            "learningRateDecay", 'm',
            " Learning Rate decay to use for training the Perceptron.", 0.001)
Definition at line 44 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.learningRatio [protected]
Definition at line 55 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
FloatOption moa.classifiers.rules.functions.Perceptron.learningRatioOption
Initial value:
 new FloatOption(
            "learningRatio", 'l',
            "Constante Learning Ratio to use for training the Perceptrons in the leaves.", 0.01)
Definition at line 40 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.core.RuleActiveRegressionNode.RuleActiveRegressionNode(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.nError [private]
Definition at line 52 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.getCurrentError(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), moa.classifiers.rules.functions.Perceptron.resetError(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
DoubleVector moa.classifiers.rules.functions.Perceptron.perceptronattributeStatistics = new DoubleVector()
Definition at line 63 of file Perceptron.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
int moa.classifiers.rules.functions.Perceptron.perceptronInstancesSeen [protected]
Definition at line 67 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.getInstancesSeen(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), moa.classifiers.rules.functions.Perceptron.setInstancesSeen(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.perceptronsumY [protected]
Definition at line 75 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
int moa.classifiers.rules.functions.Perceptron.perceptronYSeen [protected]
Definition at line 68 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
final double moa.classifiers.rules.functions.Perceptron.SD_THRESHOLD = 0.0000001 [private]
Definition at line 32 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), and moa.classifiers.rules.functions.Perceptron.normalizedInstance().
final long moa.classifiers.rules.functions.Perceptron.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 34 of file Perceptron.java.
DoubleVector moa.classifiers.rules.functions.Perceptron.squaredperceptronattributeStatistics = new DoubleVector()
Definition at line 64 of file Perceptron.java.
Referenced by moa.classifiers.rules.core.RuleActiveRegressionNode.debuganomaly(), moa.classifiers.rules.core.RuleActiveRegressionNode.isAnomaly(), moa.classifiers.rules.functions.Perceptron.normalizedInstance(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double moa.classifiers.rules.functions.Perceptron.squaredperceptronsumY [protected]
Definition at line 77 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.denormalizedPrediction(), moa.classifiers.rules.functions.Perceptron.normalizeActualClassValue(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.reset(), and moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl().
double [] moa.classifiers.rules.functions.Perceptron.weightAttribute [protected]
Definition at line 60 of file Perceptron.java.
Referenced by moa.classifiers.rules.functions.Perceptron.getModelDescription(), moa.classifiers.rules.functions.Perceptron.getWeights(), moa.classifiers.rules.functions.Perceptron.normalizeWeights(), moa.classifiers.rules.functions.Perceptron.Perceptron(), moa.classifiers.rules.functions.Perceptron.prediction(), moa.classifiers.rules.functions.Perceptron.setWeights(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), and moa.classifiers.rules.functions.Perceptron.updateWeights().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/functions/Perceptron.java