MOA: moa.gui.StringOptionEditComponent Class Reference
moa.gui.StringOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a string option.
Public Member Functions
StringOptionEditComponent (Option option)
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void applyState ()
This method applies the state.
Protected Attributes
Option editedOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a string option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file StringOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.StringOptionEditComponent.StringOptionEditComponent (Option option)
Definition at line 39 of file StringOptionEditComponent.java.
References moa.gui.StringOptionEditComponent.editedOption, moa.options.Option.getValueAsCLIString(), and moa.gui.StringOptionEditComponent.setEditState().
{
        this.editedOption = option;
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.StringOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 55 of file StringOptionEditComponent.java.
References moa.gui.StringOptionEditComponent.editedOption, and moa.options.Option.setValueViaCLIString().
{
        this.editedOption.setValueViaCLIString(getText().length() > 0 ? getText() : null);
    }
Option moa.gui.StringOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 45 of file StringOptionEditComponent.java.
References moa.gui.StringOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.StringOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 50 of file StringOptionEditComponent.java.
Referenced by moa.gui.StringOptionEditComponent.StringOptionEditComponent().
{
        setText(cliString);
    }
Member Data Documentation
Option moa.gui.StringOptionEditComponent.editedOption [protected]
Definition at line 37 of file StringOptionEditComponent.java.
Referenced by moa.gui.StringOptionEditComponent.applyState(), moa.gui.StringOptionEditComponent.getEditedOption(), and moa.gui.StringOptionEditComponent.StringOptionEditComponent().
final long moa.gui.StringOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 35 of file StringOptionEditComponent.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/StringOptionEditComponent.java