MOA: moa.classifiers.bayes.NaiveBayes Class Reference
moa.classifiers.bayes.NaiveBayes Class Reference
Naive Bayes incremental learner.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void manageMemory (int currentByteSize, int maxByteSize)
Static Public Member Functions
static double[] doNaiveBayesPrediction (Instance inst, DoubleVector observedClassDistribution, AutoExpandVector< AttributeClassObserver > attributeObservers)
static double[] doNaiveBayesPredictionLog (Instance inst, DoubleVector observedClassDistribution, AutoExpandVector< AttributeClassObserver > observers, AutoExpandVector< AttributeClassObserver > observers2)
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
Protected Attributes
DoubleVector observedClassDistribution
AutoExpandVector
< AttributeClassObserver > attributeObservers
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Naive Bayes incremental learner.
Performs classic bayesian prediction while making naive assumption that all inputs are independent.
Naive Bayes is a classiﬁer algorithm known for its simplicity and low computational cost. Given n different classes, the trained Naive Bayes classiﬁer predicts for every unlabelled instance I the class C to which it belongs with high accuracy.
Parameters:
-r : Seed for random behaviour of the classifier
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 47 of file NaiveBayes.java.
Member Function Documentation
static double [] moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction (Instance inst, DoubleVector observedClassDistribution, AutoExpandVector< AttributeClassObserver > attributeObservers) [static]
Definition at line 130 of file NaiveBayes.java.
References moa.core.DoubleVector.getValue(), moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.core.DoubleVector.numValues(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.probabilityOfAttributeValueGivenClass(), and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.bayes.NaiveBayes.getVotesForInstance().
{
        double[] votes = new double[observedClassDistribution.numValues()];
        double observedClassSum = observedClassDistribution.sumOfValues();
        for (int classIndex = 0; classIndex < votes.length; classIndex++) {
            votes[classIndex] = observedClassDistribution.getValue(classIndex)
                    / observedClassSum;
            for (int attIndex = 0; attIndex < inst.numAttributes() - 1; attIndex++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(attIndex,
                        inst);
                AttributeClassObserver obs = attributeObservers.get(attIndex);
                if ((obs != null) && !inst.isMissing(instAttIndex)) {
                    votes[classIndex] *= obs.probabilityOfAttributeValueGivenClass(inst.value(instAttIndex), classIndex);
                }
            }
        }
        // TODO: need logic to prevent underflow?
        return votes;
    }
static double [] moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog (Instance inst, DoubleVector observedClassDistribution, AutoExpandVector< AttributeClassObserver > observers, AutoExpandVector< AttributeClassObserver > observers2) [static]
Definition at line 152 of file NaiveBayes.java.
References moa.core.DoubleVector.getValue(), moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.core.DoubleVector.numValues(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.probabilityOfAttributeValueGivenClass(), and moa.core.DoubleVector.sumOfValues().
{
        AttributeClassObserver obs;
        double[] votes = new double[observedClassDistribution.numValues()];
        double observedClassSum = observedClassDistribution.sumOfValues();
        for (int classIndex = 0; classIndex < votes.length; classIndex++) {
            votes[classIndex] = Math.log10(observedClassDistribution.getValue(classIndex)
                    / observedClassSum);
            for (int attIndex = 0; attIndex < inst.numAttributes() - 1; attIndex++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(attIndex,
                        inst);
                if (inst.attribute(instAttIndex).isNominal()) {
                    obs = observers.get(attIndex);
                } else {
                    obs = observers2.get(attIndex);
                }
                if ((obs != null) && !inst.isMissing(instAttIndex)) {
                    votes[classIndex] += Math.log10(obs.probabilityOfAttributeValueGivenClass(inst.value(instAttIndex), classIndex));
                }
            }
        }
        return votes;
    }
void moa.classifiers.bayes.NaiveBayes.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 92 of file NaiveBayes.java.
References moa.classifiers.bayes.NaiveBayes.attributeObservers, moa.classifiers.AbstractClassifier.getAttributeNameString(), moa.classifiers.AbstractClassifier.getClassLabelString(), moa.classifiers.AbstractClassifier.getClassNameString(), moa.core.DoubleVector.getValue(), moa.core.DoubleVector.numValues(), moa.classifiers.bayes.NaiveBayes.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
{
        for (int i = 0; i < this.observedClassDistribution.numValues(); i++) {
            StringUtils.appendIndented(out, indent, "Observations for ");
            out.append(getClassNameString());
            out.append(" = ");
            out.append(getClassLabelString(i));
            out.append(":");
            StringUtils.appendNewlineIndented(out, indent + 1,
                    "Total observed weight = ");
            out.append(this.observedClassDistribution.getValue(i));
            out.append(" / prob = ");
            out.append(this.observedClassDistribution.getValue(i)
                    / this.observedClassDistribution.sumOfValues());
            for (int j = 0; j < this.attributeObservers.size(); j++) {
                StringUtils.appendNewlineIndented(out, indent + 1,
                        "Observations for ");
                out.append(getAttributeNameString(j));
                out.append(": ");
                // TODO: implement observer output
                out.append(this.attributeObservers.get(j));
            }
            StringUtils.appendNewline(out);
        }
    }
Measurement [] moa.classifiers.bayes.NaiveBayes.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 87 of file NaiveBayes.java.
{
        return null;
    }
String moa.classifiers.bayes.NaiveBayes.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 52 of file NaiveBayes.java.
{
        return "Naive Bayes classifier: performs classic bayesian prediction while making naive assumption that all inputs are independent.";
    }
double [] moa.classifiers.bayes.NaiveBayes.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 81 of file NaiveBayes.java.
References moa.classifiers.bayes.NaiveBayes.attributeObservers, moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), and moa.classifiers.bayes.NaiveBayes.observedClassDistribution.
{
        return doNaiveBayesPrediction(inst, this.observedClassDistribution,
                this.attributeObservers);
    }
boolean moa.classifiers.bayes.NaiveBayes.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 118 of file NaiveBayes.java.
{
        return false;
    }
void moa.classifiers.bayes.NaiveBayes.manageMemory (int currentByteSize, int maxByteSize)
Definition at line 180 of file NaiveBayes.java.
{
        // TODO Auto-generated method stub
    }
AttributeClassObserver moa.classifiers.bayes.NaiveBayes.newNominalClassObserver () [protected]
Definition at line 122 of file NaiveBayes.java.
Referenced by moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl().
{
        return new NominalAttributeClassObserver();
    }
AttributeClassObserver moa.classifiers.bayes.NaiveBayes.newNumericClassObserver () [protected]
Definition at line 126 of file NaiveBayes.java.
Referenced by moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl().
{
        return new GaussianNumericAttributeClassObserver();
    }
void moa.classifiers.bayes.NaiveBayes.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 60 of file NaiveBayes.java.
References moa.classifiers.bayes.NaiveBayes.attributeObservers, and moa.classifiers.bayes.NaiveBayes.observedClassDistribution.
{
        this.observedClassDistribution = new DoubleVector();
        this.attributeObservers = new AutoExpandVector<AttributeClassObserver>();
    }
void moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 66 of file NaiveBayes.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.bayes.NaiveBayes.attributeObservers, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.bayes.NaiveBayes.newNominalClassObserver(), moa.classifiers.bayes.NaiveBayes.newNumericClassObserver(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), and moa.classifiers.bayes.NaiveBayes.observedClassDistribution.
{
        this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
        for (int i = 0; i < inst.numAttributes() - 1; i++) {
            int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
            AttributeClassObserver obs = this.attributeObservers.get(i);
            if (obs == null) {
                obs = inst.attribute(instAttIndex).isNominal() ? newNominalClassObserver()
                        : newNumericClassObserver();
                this.attributeObservers.set(i, obs);
            }
            obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
        }
    }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.bayes.NaiveBayes.attributeObservers [protected]
Definition at line 57 of file NaiveBayes.java.
Referenced by moa.classifiers.bayes.NaiveBayes.getModelDescription(), moa.classifiers.bayes.NaiveBayes.getVotesForInstance(), moa.classifiers.bayes.NaiveBayes.resetLearningImpl(), and moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl().
DoubleVector moa.classifiers.bayes.NaiveBayes.observedClassDistribution [protected]
Definition at line 55 of file NaiveBayes.java.
Referenced by moa.classifiers.bayes.NaiveBayes.getModelDescription(), moa.classifiers.bayes.NaiveBayes.getVotesForInstance(), moa.classifiers.bayes.NaiveBayes.resetLearningImpl(), and moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl().
final long moa.classifiers.bayes.NaiveBayes.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 49 of file NaiveBayes.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/bayes/NaiveBayes.java