MOA: moa.classifiers.trees.ORTO.ORTOPerceptron Class Reference
moa.classifiers.trees.ORTO.ORTOPerceptron Class Reference
A Perceptron classifier modified to conform to the specifications of Ikonomovska et al.
Public Member Functions
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
ORTOPerceptron (ORTOPerceptron copy)
ORTOPerceptron ()
void setWeights (double[] w)
double[] getWeights ()
void resetLearningImpl ()
A method to reset the model.
void trainOnInstanceImpl (Instance inst, ORTO ft)
Update the model using the provided instance.
double prediction (Instance inst)
Output the prediction made by this perceptron on the given instance.
Protected Attributes
double[] weightAttribute
DoubleVector attributeStatistics = new DoubleVector()
DoubleVector squaredAttributeStatistics = new DoubleVector()
int instancesSeen = 0
boolean reset
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
A Perceptron classifier modified to conform to the specifications of Ikonomovska et al.
Definition at line 1040 of file ORTO.java.
Constructor & Destructor Documentation
moa.classifiers.trees.ORTO.ORTOPerceptron.ORTOPerceptron (ORTOPerceptron copy)
Definition at line 1061 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.getWeights(), and moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute.
{
                this.weightAttribute = copy.getWeights();
        }
moa.classifiers.trees.ORTO.ORTOPerceptron.ORTOPerceptron ()
Definition at line 1065 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.reset.
{
                this.reset = true;
        }
Member Function Documentation
void moa.classifiers.trees.ORTO.ORTOPerceptron.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 1057 of file ORTO.java.
{
        //TODO Auto-generated method stub
        }
double [] moa.classifiers.trees.ORTO.ORTOPerceptron.getWeights ()
Definition at line 1073 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.ORTOPerceptron().
{
            return this.weightAttribute;
        }
double moa.classifiers.trees.ORTO.ORTOPerceptron.prediction (Instance inst)
Output the prediction made by this perceptron on the given instance.
Definition at line 1141 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.reset, and moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.getError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPHError(), moa.classifiers.trees.ORTO.ActiveLearningNode.getPrediction(), and moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
        {
            double prediction = 0;
            if (this.reset == false) {
                for (int j = 0; j < inst.numAttributes() - 1; j++) {
                    if(inst.attribute(j).isNumeric())
                    {
                        prediction += this.weightAttribute[j] * inst.value(j);
                    }
                }
                prediction += this.weightAttribute[inst.numAttributes() - 1];
            }
            // Return prediction to 3dp
            return (double)Math.round(prediction * 1000) / 1000;
        }
void moa.classifiers.trees.ORTO.ORTOPerceptron.resetLearningImpl ()
A method to reset the model.
Definition at line 1080 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.reset.
{
            this.reset = true;
        }
void moa.classifiers.trees.ORTO.ORTOPerceptron.setWeights (double[] w)
Definition at line 1069 of file ORTO.java.
References moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute.
{
            this.weightAttribute = w;
        }
void moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl (Instance inst, ORTO ft)
Update the model using the provided instance.
Definition at line 1087 of file ORTO.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.ORTO.ORTOPerceptron.attributeStatistics, moa.classifiers.AbstractClassifier.classifierRandom, moa.core.DoubleVector.getValue(), moa.options.FloatOption.getValue(), moa.classifiers.trees.ORTO.initLearnRate, moa.classifiers.trees.ORTO.ORTOPerceptron.instancesSeen, moa.options.FlagOption.isSet, moa.classifiers.trees.ORTO.LearningRatioDecayOrConstOption, moa.classifiers.trees.ORTO.LearningRatioOption, moa.classifiers.trees.ORTO.learnRateDecay, moa.classifiers.trees.ORTO.ORTOPerceptron.prediction(), moa.classifiers.trees.ORTO.ORTOPerceptron.reset, moa.classifiers.trees.ORTO.ORTOPerceptron.squaredAttributeStatistics, and moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute.
Referenced by moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance().
{
            // Initialize Perceptron if necessary
            if (this.reset == true) {
                this.reset = false;
                this.weightAttribute = new double[inst.numAttributes()];
                this.instancesSeen = 0;
                this.attributeStatistics = new DoubleVector();
                this.squaredAttributeStatistics = new DoubleVector();
                for (int j = 0; j < inst.numAttributes(); j++) {
                    weightAttribute[j] = 2 * ft.classifierRandom.nextDouble() - 1;
                }
            }
            // Update attribute statistics
            instancesSeen++;
            for(int j = 0; j < inst.numAttributes() -1; j++)
            {
                attributeStatistics.addToValue(j, inst.value(j));
                squaredAttributeStatistics.addToValue(j, inst.value(j)*inst.value(j));
            }
            // Update weights
            double learningRatio = 0.0;
            if(ft.LearningRatioDecayOrConstOption.isSet()){
                learningRatio = ft.LearningRatioOption.getValue();
            } else {
                learningRatio = ft.initLearnRate / (1 + instancesSeen * ft.learnRateDecay);
            }
            // double learningRatio = ft.learningRatioOption.getValue();
            double actualClass = inst.classValue();
            double predictedClass = this.prediction(inst);
            // SET DELTA TO ACTUAL - PREDICTED, NOT PREDICTED - ACTUAL AS SAID IN PAPER
            double delta = actualClass - predictedClass;
            for (int j = 0; j < inst.numAttributes() - 1; j++) {
                if (inst.attribute(j).isNumeric()) {
                    // Update weights. Ensure attribute values are normalized first
                    double sd = Math.sqrt((squaredAttributeStatistics.getValue(j) - ((attributeStatistics.getValue(j) * attributeStatistics.getValue(j))/instancesSeen))/instancesSeen);
                    double instanceValue = 0;
                    if (sd > 0.0000001) { // Limit found in implementation by Ikonomovska et al (2011)
                        instanceValue = (inst.value(j) - (attributeStatistics.getValue(j)/instancesSeen))/(3*sd);
                    }
                    this.weightAttribute[j] += learningRatio * delta * instanceValue;
                }
            }
            this.weightAttribute[inst.numAttributes() - 1] += learningRatio * delta;
        }
Member Data Documentation
DoubleVector moa.classifiers.trees.ORTO.ORTOPerceptron.attributeStatistics = new DoubleVector() [protected]
Definition at line 1047 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
int moa.classifiers.trees.ORTO.ORTOPerceptron.instancesSeen = 0 [protected]
Definition at line 1051 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
boolean moa.classifiers.trees.ORTO.ORTOPerceptron.reset [protected]
Definition at line 1054 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.ORTOPerceptron(), moa.classifiers.trees.ORTO.ORTOPerceptron.prediction(), moa.classifiers.trees.ORTO.ORTOPerceptron.resetLearningImpl(), and moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
final long moa.classifiers.trees.ORTO.ORTOPerceptron.serialVersionUID = 1L [static, private]
Definition at line 1041 of file ORTO.java.
DoubleVector moa.classifiers.trees.ORTO.ORTOPerceptron.squaredAttributeStatistics = new DoubleVector() [protected]
Definition at line 1048 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
double [] moa.classifiers.trees.ORTO.ORTOPerceptron.weightAttribute [protected]
Definition at line 1044 of file ORTO.java.
Referenced by moa.classifiers.trees.ORTO.ORTOPerceptron.getWeights(), moa.classifiers.trees.ORTO.ORTOPerceptron.ORTOPerceptron(), moa.classifiers.trees.ORTO.ORTOPerceptron.prediction(), moa.classifiers.trees.ORTO.ORTOPerceptron.setWeights(), and moa.classifiers.trees.ORTO.ORTOPerceptron.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ORTO.java