MOA: moa.clusterers.clustree.ClusKernel Class Reference
moa.clusterers.clustree.ClusKernel Class Reference
Representation of an Entry in the tree.
Public Member Functions
ClusKernel (double[] point, int dim)
A constructor that makes a Kernel which just represents the given point.
void add (ClusKernel other)
Adds the given cluster to this cluster, without making this cluster older.
double calcDistance (ClusKernel other)
Calculate the distance to this other cluster.
double getWeight ()
See interface Cluster.
CFCluster getCF ()
double[] getCenter ()
double getInclusionProbability (Instance instance)
Returns the probability of the given point belonging to this cluster.
double getRadius ()
See interface Cluster.
double[] getVarianceVector ()
Static Public Attributes
static final double EPSILON = 0.00000001
Numeric epsilon.
static final double MIN_VARIANCE = 1e-50
Protected Member Functions
ClusKernel (int numberDimensions)
Constructor of the Cluster.
ClusKernel (ClusKernel other)
Instantiates a copy of the given cluster.
void aggregate (ClusKernel other, long timeDifference, double negLambda)
Make this cluster older bei weighting it and add to this cluster the given cluster.
void makeOlder (long timeDifference, double negLambda)
Make this cluster older.
boolean isEmpty ()
Check if this cluster is empty or not.
void clear ()
Remove all points from this cluster.
void overwriteOldCluster (ClusKernel other)
Overwrites the LS, SS and weightedN in this cluster to the values of the given cluster but adds N and classCount of the given cluster to this one.
Private Member Functions
double getTotalN ()
Returns the weighted number of points in the cluster.
double getDeviation ()
double calcNormalizedDistance (double[] point)
Calculate the normalized euclidean distance (Mahalanobis distance for distribution w/o covariances) to a point.
Private Attributes
double totalN
Counting of the number of N as normal N is weighted by how much time passes between updates.
Detailed Description
Representation of an Entry in the tree.
Definition at line 32 of file ClusKernel.java.
Constructor & Destructor Documentation
moa.clusterers.clustree.ClusKernel.ClusKernel (double[] point, int dim)
A constructor that makes a Kernel which just represents the given point.
Parameters:
point The point to be converted into a corresponding Kernel.
numberClasses The number of classes possible for points in this experiment(Tree).
Definition at line 54 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.totalN.
{
        super(point, dim);
        this.totalN = 1;
    }
moa.clusterers.clustree.ClusKernel.ClusKernel (int numberDimensions) [protected]
Constructor of the Cluster.
Parameters:
numberDimensions Dimensionality of the points added that can be added to this cluster
numberClasses The number of classes possible for points in this experiment(Tree).
Definition at line 66 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.totalN.
{
        super(numberDimensions);
        this.totalN = 0;
    }
moa.clusterers.clustree.ClusKernel.ClusKernel (ClusKernel other) [protected]
Instantiates a copy of the given cluster.
Parameters:
other The Cluster of which we make a copy.
Definition at line 75 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.getTotalN(), and moa.clusterers.clustree.ClusKernel.totalN.
{
        super(other);
        this.totalN = other.getTotalN();
    }
Member Function Documentation
void moa.clusterers.clustree.ClusKernel.add (ClusKernel other)
Adds the given cluster to this cluster, without making this cluster older.
Parameters:
other
Reimplemented from moa.cluster.CFCluster.
Definition at line 85 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.totalN.
Referenced by moa.clusterers.clustree.Entry.add(), moa.clusterers.clustree.ClusKernel.aggregate(), moa.clusterers.clustree.Entry.Entry(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.Entry.mergeWith(), and moa.clusterers.clustree.Entry.recalculateData().
{
        super.add(other);
        this.totalN += other.totalN;
    }
void moa.clusterers.clustree.ClusKernel.aggregate (ClusKernel other, long timeDifference, double negLambda) [protected]
Make this cluster older bei weighting it and add to this cluster the given cluster.
If we want to add somethin to the cluster, but don't want to weight it, we should use the function add(Cluster).
Parameters:
other The other cluster to be added to this one.
timeDifference The time elapsed between the last update of the Entry to which this cluster belongs and the update that caused the call to this function.
negLambda A parameter needed to weight the cluster.
See also:
add(tree.Kernel)
Definition at line 101 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.add(), and moa.clusterers.clustree.ClusKernel.makeOlder().
Referenced by moa.clusterers.clustree.Entry.aggregateCluster(), moa.clusterers.clustree.Entry.aggregateEntry(), and moa.clusterers.clustree.Entry.aggregateToBuffer().
{
        makeOlder(timeDifference, negLambda);
        add(other);
    }
double moa.clusterers.clustree.ClusKernel.calcDistance (ClusKernel other)
Calculate the distance to this other cluster.
The other cluster is normaly just a single data point(i.e. N = 1).
Parameters:
other The other cluster to which the distance is calculated.
Returns:
The distance between this cluster and the other.
Definition at line 137 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.getWeight(), and moa.cluster.CFCluster.LS.
Referenced by moa.clusterers.clustree.Entry.calcDistance(), moa.clusterers.clustree.ClusTree.findBestLeafNode(), moa.clusterers.outliers.AnyOut.AnyOutCore.improveObjectOnce(), and moa.clusterers.outliers.AnyOut.AnyOutCore.initObject().
{
        // TODO: (Fernando, Felix) Adapt the distance function to the new algorithmn.
        double N1 = this.getWeight();
        double N2 = other.getWeight();
        double[] thisLS = this.LS;
        double[] otherLS = other.LS;
        double res = 0.0;
        for (int i = 0; i < thisLS.length; i++) {
            double substracted = (thisLS[i] / N1) - (otherLS[i] / N2);
            res += substracted * substracted;
        }
        // TODO INFO: added sqrt to the computation [PK 10.09.10]
        return Math.sqrt(res);
    }
double moa.clusterers.clustree.ClusKernel.calcNormalizedDistance (double[] point) [private]
Calculate the normalized euclidean distance (Mahalanobis distance for distribution w/o covariances) to a point.
Parameters:
other The point to which the distance is calculated.
Returns:
The normalized distance to the cluster center.
TODO: check whether WEIGHTING is correctly applied to variances
Definition at line 324 of file ClusKernel.java.
References moa.cluster.SphereCluster.center, moa.clusterers.clustree.ClusKernel.getCenter(), and moa.clusterers.clustree.ClusKernel.getVarianceVector().
Referenced by moa.clusterers.clustree.ClusKernel.getInclusionProbability().
{
        double[] variance = getVarianceVector();
        double[] center = getCenter();
        double res = 0.0;
        for (int i = 0; i < center.length; i++) {
            double diff = center[i] - point[i];
            res += (diff * diff);// variance[i];
        }
        return Math.sqrt(res);
    }
void moa.clusterers.clustree.ClusKernel.clear () [protected]
Remove all points from this cluster.
Definition at line 176 of file ClusKernel.java.
References moa.cluster.CFCluster.LS, moa.cluster.CFCluster.N, moa.cluster.CFCluster.SS, and moa.clusterers.clustree.ClusKernel.totalN.
Referenced by moa.clusterers.clustree.Entry.clear(), moa.clusterers.clustree.Entry.emptyBuffer(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.Entry.recalculateData(), and moa.clusterers.clustree.Entry.shallowClear().
{
        this.totalN = 0;
        this.N = 0.0;
        Arrays.fill(this.LS, 0.0);
        Arrays.fill(this.SS, 0.0);
    }
double [] moa.clusterers.clustree.ClusKernel.getCenter () [virtual]
Returns:
this kernels' center
Reimplemented from moa.cluster.CFCluster.
Definition at line 216 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.getWeight(), moa.clusterers.clustree.ClusKernel.isEmpty(), and moa.cluster.CFCluster.LS.
Referenced by moa.clusterers.clustree.ClusKernel.calcNormalizedDistance(), moa.clusterers.outliers.AnyOut.AnyOutCore.getDensityOutlierScore(), and moa.clusterers.clustree.ClusTree.insertBreadthFirst().
{
        assert (!this.isEmpty());
        double res[] = new double[this.LS.length];
        double weightedSize = this.getWeight();
        for (int i = 0; i < res.length; i++) {
            res[i] = this.LS[i] / weightedSize;
        }
        return res;
    }
CFCluster moa.clusterers.clustree.ClusKernel.getCF () [virtual]
Implements moa.cluster.CFCluster.
Definition at line 208 of file ClusKernel.java.
{
        return this;
    }
double moa.clusterers.clustree.ClusKernel.getDeviation () [private]
Definition at line 278 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.getVarianceVector().
Referenced by moa.clusterers.clustree.ClusKernel.getRadius().
{
        double[] variance = getVarianceVector();
        double sumOfDeviation = 0.0;
        for (int i = 0; i < variance.length; i++) {
            double d = Math.sqrt(variance[i]);
            sumOfDeviation += d;
        }
        return sumOfDeviation / variance.length;
    }
double moa.clusterers.clustree.ClusKernel.getInclusionProbability (Instance instance) [virtual]
Returns the probability of the given point belonging to this cluster.
Parameters:
point
Returns:
a value between 0 and 1
Implements moa.cluster.CFCluster.
Definition at line 238 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.calcNormalizedDistance(), moa.cluster.SphereCluster.distance(), moa.clusterers.clustree.ClusKernel.EPSILON, moa.clusterers.clustree.ClusKernel.getRadius(), moa.cluster.CFCluster.LS, and moa.cluster.CFCluster.N.
{
        //trivial cluster
        if(N == 1){
            double distance = 0.0;
            for (int i = 0; i < LS.length; i++) {
                double d = LS[i] - instance.value(i);
                distance += d * d;
            }
            distance = Math.sqrt(distance);
            if( distance < EPSILON )
                return 1.0;
            return 0.0;
        }
        else{
            double dist = calcNormalizedDistance(instance.toDoubleArray());
            if(dist <= getRadius()){
                return 1;
            }
            else{
                return 0;
            }
//            double res = AuxiliaryFunctions.distanceProbabilty(dist, LS.length);
//            return res;
        }
    }
double moa.clusterers.clustree.ClusKernel.getRadius () [virtual]
See interface Cluster.
Returns:
The radius of the cluster.
See also:
Cluster.getRadius()
Implements moa.cluster.CFCluster.
Definition at line 270 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.getDeviation(), moa.cluster.CFCluster.N, and moa.cluster.CFCluster.radiusFactor.
Referenced by moa.clusterers.clustree.ClusKernel.getInclusionProbability().
{
        //trivial cluster
        if(N == 1) return 0;
        return getDeviation()*radiusFactor;
    }
double moa.clusterers.clustree.ClusKernel.getTotalN () [private]
Returns the weighted number of points in the cluster.
Returns:
The weighted number of points in the cluster.
Definition at line 160 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.totalN.
Referenced by moa.clusterers.clustree.ClusKernel.ClusKernel().
{
        return totalN;
    }
double [] moa.clusterers.clustree.ClusKernel.getVarianceVector ()
Definition at line 289 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.EPSILON, moa.clusterers.clustree.ClusKernel.getWeight(), moa.cluster.CFCluster.LS, moa.clusterers.clustree.ClusKernel.MIN_VARIANCE, and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.clustree.ClusKernel.calcNormalizedDistance(), moa.clusterers.outliers.AnyOut.AnyOutCore.getDensityOutlierScore(), and moa.clusterers.clustree.ClusKernel.getDeviation().
{
        double[] res = new double[this.LS.length];
        for (int i = 0; i < this.LS.length; i++) {
            double ls = this.LS[i];
            double ss = this.SS[i];
            double lsDivN = ls / this.getWeight();
            double lsDivNSquared = lsDivN * lsDivN;
            double ssDivN = ss / this.getWeight();
            res[i] = ssDivN - lsDivNSquared;
            // Due to numerical errors, small negative values can occur.
            // We correct this by settings them to almost zero.
            if (res[i] <= 0.0) {
                if (res[i] > -EPSILON) {
                    res[i] = MIN_VARIANCE;
                }
            }
            else{
            }
        }
        return res;
    }
double moa.clusterers.clustree.ClusKernel.getWeight () [virtual]
See interface Cluster.
Returns:
The weight.
See also:
Cluster.getWeight()
Reimplemented from moa.cluster.CFCluster.
Definition at line 202 of file ClusKernel.java.
References moa.cluster.CFCluster.N.
Referenced by moa.clusterers.clustree.ClusKernel.calcDistance(), moa.clusterers.clustree.ClusKernel.getCenter(), moa.clusterers.clustree.ClusKernel.getVarianceVector(), moa.clusterers.outliers.AnyOut.AnyOutCore.improveObjectOnce(), and moa.clusterers.clustree.Entry.isIrrelevant().
{
        return this.N;
    }
boolean moa.clusterers.clustree.ClusKernel.isEmpty () [protected]
Check if this cluster is empty or not.
Returns:
true if the cluster has no data points, false otherwise.
Definition at line 169 of file ClusKernel.java.
References moa.clusterers.clustree.ClusKernel.totalN.
Referenced by moa.clusterers.clustree.ClusKernel.getCenter(), moa.clusterers.clustree.Entry.initializeEntry(), moa.clusterers.clustree.ClusTree.insert(), moa.clusterers.clustree.ClusTree.insertHere(), moa.clusterers.clustree.Entry.isEmpty(), moa.clusterers.clustree.Entry.mergeWith(), and moa.clusterers.clustree.Entry.overwriteOldEntry().
{
        return this.totalN == 0;
    }
void moa.clusterers.clustree.ClusKernel.makeOlder (long timeDifference, double negLambda) [protected]
Make this cluster older.
This means multiplying weighted N, LS and SS with a weight factor given by the time difference and the parameter negLambda.
Parameters:
timeDifference The time elapsed between this current update and the last one.
negLambda
Definition at line 114 of file ClusKernel.java.
References moa.cluster.CFCluster.LS, moa.cluster.CFCluster.N, and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.clustree.ClusKernel.aggregate(), moa.clusterers.clustree.Entry.emptyBuffer(), and moa.clusterers.clustree.Entry.makeOlder().
{
        if (timeDifference == 0) {
            return;
        }
        //double weightFactor = AuxiliaryFunctions.weight(negLambda, timeDifference);
        assert (negLambda < 0);
        assert (timeDifference > 0);
        double weightFactor = Math.pow(2.0, negLambda * timeDifference);
        this.N *= weightFactor;
        for (int i = 0; i < LS.length; i++) {
            LS[i] *= weightFactor;
            SS[i] *= weightFactor;
        }
    }
void moa.clusterers.clustree.ClusKernel.overwriteOldCluster (ClusKernel other) [protected]
Overwrites the LS, SS and weightedN in this cluster to the values of the given cluster but adds N and classCount of the given cluster to this one.
This function is useful when the weight of an entry becomes to small, and we want to forget the information of the old points.
Parameters:
other The cluster that should overwrite the information.
Definition at line 190 of file ClusKernel.java.
References moa.cluster.CFCluster.LS, moa.cluster.CFCluster.N, moa.cluster.CFCluster.SS, and moa.clusterers.clustree.ClusKernel.totalN.
Referenced by moa.clusterers.clustree.Entry.overwriteOldEntry().
{
        this.totalN = other.totalN;
        this.N = other.N;
        //AuxiliaryFunctions.overwriteDoubleArray(this.LS, other.LS);
        //AuxiliaryFunctions.overwriteDoubleArray(this.SS, other.SS);
        assert (LS.length == other.LS.length);
        System.arraycopy(other.LS, 0, LS, 0, LS.length);
        assert (SS.length == other.SS.length);
        System.arraycopy(other.SS, 0, SS, 0, SS.length);
    }
Member Data Documentation
final double moa.clusterers.clustree.ClusKernel.EPSILON = 0.00000001 [static]
Numeric epsilon.
Definition at line 36 of file ClusKernel.java.
Referenced by moa.clusterers.clustree.ClusKernel.getInclusionProbability(), and moa.clusterers.clustree.ClusKernel.getVarianceVector().
final double moa.clusterers.clustree.ClusKernel.MIN_VARIANCE = 1e-50 [static]
Definition at line 37 of file ClusKernel.java.
Referenced by moa.clusterers.clustree.ClusKernel.getVarianceVector().
double moa.clusterers.clustree.ClusKernel.totalN [private]
Counting of the number of N as normal N is weighted by how much time passes between updates.
If weighted N is under a threshhold, we may consider the cluster irrelevant and we can delete it.
Definition at line 46 of file ClusKernel.java.
Referenced by moa.clusterers.clustree.ClusKernel.add(), moa.clusterers.clustree.ClusKernel.clear(), moa.clusterers.clustree.ClusKernel.ClusKernel(), moa.clusterers.clustree.ClusKernel.getTotalN(), moa.clusterers.clustree.ClusKernel.isEmpty(), and moa.clusterers.clustree.ClusKernel.overwriteOldCluster().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/clustree/ClusKernel.java