MOA: moa.gui.visualization.GraphCurve Class Reference
moa.gui.visualization.GraphCurve Class Reference
Public Member Functions
GraphCurve ()
Creates new form GraphCurve.
void setGraph (MeasureCollection measure0, MeasureCollection measure1, int selection)
void setYMinMaxValues (double min, double max)
Dimension getPreferredSize ()
Protected Member Functions
void paintComponent (Graphics g)
Package Functions
void setProcessFrequency (int processFrequency)
void setClusterEventsList (ArrayList< ClusterEvent > clusterEvents)
void setXResolution (double x_resolution)
Private Member Functions
void paintFullCurve (Graphics g, MeasureCollection m, int mSelect, Color color)
void paintEvents (Graphics g)
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
double min_value = 0
double max_value = 1
MeasureCollection measure0 = null
MeasureCollection measure1 = null
int measureSelected = 0
double x_resolution
int processFrequency
ArrayList< ClusterEvent > clusterEvents
Detailed Description
Definition at line 29 of file GraphCurve.java.
Constructor & Destructor Documentation
moa.gui.visualization.GraphCurve.GraphCurve ()
Creates new form GraphCurve.
Definition at line 43 of file GraphCurve.java.
References moa.gui.visualization.GraphCurve.initComponents().
{
        initComponents();
    }
Member Function Documentation
Dimension moa.gui.visualization.GraphCurve.getPreferredSize ()
Definition at line 146 of file GraphCurve.java.
{
        return super.getPreferredSize();
    }
void moa.gui.visualization.GraphCurve.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 161 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.GraphCurve().
{
        setOpaque(false);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.GraphCurve.paintComponent (Graphics g) [protected]
Definition at line 60 of file GraphCurve.java.
References moa.gui.visualization.GraphCurve.measure0, moa.gui.visualization.GraphCurve.measure1, moa.gui.visualization.GraphCurve.measureSelected, moa.gui.visualization.GraphCurve.paintEvents(), and moa.gui.visualization.GraphCurve.paintFullCurve().
{
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        if(measure0!=null && measure1!=null){
                paintFullCurve(g, measure0, measureSelected, Color.red);
                paintFullCurve(g, measure1, measureSelected, Color.blue);
        }
        else{
            if(measure0!=null){
                paintFullCurve(g, measure0, measureSelected, Color.red);
            }
        }
        paintEvents(g);
    }
void moa.gui.visualization.GraphCurve.paintEvents (Graphics g) [private]
Definition at line 125 of file GraphCurve.java.
References moa.gui.visualization.GraphCurve.clusterEvents, moa.gui.visualization.GraphCurve.processFrequency, and moa.gui.visualization.GraphCurve.x_resolution.
Referenced by moa.gui.visualization.GraphCurve.paintComponent().
{
       if(clusterEvents!=null){
            g.setColor(Color.DARK_GRAY);
            for (int i = 0; i < clusterEvents.size(); i++) {
                int x = (int)(clusterEvents.get(i).getTimestamp()/processFrequency/x_resolution);
                g.drawLine(x, 0, x, getHeight());
            }
        }
    }
void moa.gui.visualization.GraphCurve.paintFullCurve (Graphics g, MeasureCollection m, int mSelect, Color color) [private]
Definition at line 79 of file GraphCurve.java.
References moa.evaluation.MeasureCollection.getNumberOfValues(), moa.evaluation.MeasureCollection.getValue(), moa.gui.visualization.GraphCurve.max_value, and moa.gui.visualization.GraphCurve.x_resolution.
Referenced by moa.gui.visualization.GraphCurve.paintComponent().
{
            if (m.getNumberOfValues(mSelect)==0) return;
            boolean corrupted = false;
            int height = getHeight();
            int width = getWidth();
            int n = m.getNumberOfValues(mSelect);
            if(x_resolution > 1)
                n = (int)(n / (int)x_resolution);
            int[] x = new int[n];
            int[] y = new int[n];
            for (int i = 0; i < n; i ++) {
                if(x_resolution > 1){
                    //we need to compress the values
                    double sum_y = 0;
                    int counter = 0;
                    for (int j = 0; j < x_resolution; j++) {
                        if((i)*x_resolution+j<m.getNumberOfValues(mSelect)){
                            sum_y+= m.getValue(mSelect,i);
                            counter++;
                        }
                        sum_y/=counter;
                    }
                    x[i] = i;
                    y[i] = (int)(height-(sum_y/max_value)*height);
                }
                else{
                    //spreading one value
                    x[i] = (i)*(int)(1/x_resolution)+(int)(1/x_resolution/2);
                    double value = m.getValue(mSelect,i);
                    if(Double.isNaN(value)){
                        corrupted = true;
                        break;
                    }
                    y[i] = (int)(height-(value/max_value)*height);
                }
            }
            if(!corrupted){
                g.setColor(color);
                g.drawPolyline(x, y, n);
            }
    }
void moa.gui.visualization.GraphCurve.setClusterEventsList (ArrayList< ClusterEvent > clusterEvents) [package]
Definition at line 141 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCanvas.setClusterEventsList().
{
        this.clusterEvents = clusterEvents;
    }
void moa.gui.visualization.GraphCurve.setGraph (MeasureCollection measure0, MeasureCollection measure1, int selection)
Definition at line 48 of file GraphCurve.java.
References moa.gui.visualization.GraphCurve.measureSelected.
Referenced by moa.gui.visualization.GraphCanvas.setGraph().
{
       this.measure0 = measure0;
       this.measure1 = measure1;
       this.measureSelected = selection;
       repaint();
    }
void moa.gui.visualization.GraphCurve.setProcessFrequency (int processFrequency) [package]
Definition at line 55 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCanvas.setGraph().
{
        this.processFrequency = processFrequency;
    }
void moa.gui.visualization.GraphCurve.setXResolution (double x_resolution) [package]
Definition at line 150 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCanvas.updateXResolution().
{
        this.x_resolution = x_resolution;
    }
void moa.gui.visualization.GraphCurve.setYMinMaxValues (double min, double max)
Definition at line 136 of file GraphCurve.java.
References moa.gui.visualization.GraphCurve.max_value, and moa.gui.visualization.GraphCurve.min_value.
Referenced by moa.gui.visualization.GraphCanvas.updateYValues().
{
        min_value = min;
        max_value = max;
    }
Member Data Documentation
ArrayList<ClusterEvent> moa.gui.visualization.GraphCurve.clusterEvents [private]
Definition at line 39 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintEvents().
double moa.gui.visualization.GraphCurve.max_value = 1 [private]
Definition at line 31 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintFullCurve(), and moa.gui.visualization.GraphCurve.setYMinMaxValues().
MeasureCollection moa.gui.visualization.GraphCurve.measure0 = null [private]
Definition at line 32 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintComponent().
MeasureCollection moa.gui.visualization.GraphCurve.measure1 = null [private]
Definition at line 33 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintComponent().
int moa.gui.visualization.GraphCurve.measureSelected = 0 [private]
Definition at line 34 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintComponent(), and moa.gui.visualization.GraphCurve.setGraph().
double moa.gui.visualization.GraphCurve.min_value = 0 [private]
Definition at line 30 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.setYMinMaxValues().
int moa.gui.visualization.GraphCurve.processFrequency [private]
Definition at line 37 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintEvents().
double moa.gui.visualization.GraphCurve.x_resolution [private]
Definition at line 36 of file GraphCurve.java.
Referenced by moa.gui.visualization.GraphCurve.paintEvents(), and moa.gui.visualization.GraphCurve.paintFullCurve().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/GraphCurve.java