MOA: moa.classifiers.trees.ASHoeffdingTree Class Reference
moa.classifiers.trees.ASHoeffdingTree Class Reference
Adaptive Size Hoeffding Tree used in Bagging using trees of different size.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
void setMaxSize (int mSize)
void setResetTree ()
void deleteNode (Node node, int childIndex)
void resizeTree (Node node, int childIndex)
Protected Attributes
int maxSize = 10000
boolean resetTree = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Adaptive Size Hoeffding Tree used in Bagging using trees of different size.
The Adaptive-Size Hoeffding Tree (ASHT) is derived from the Hoeffding Tree algorithm with the following differences:
it has a maximum number of split nodes, or size
after one node splits, if the number of split nodes of the ASHT tree is higher than the maximum value, then it deletes some nodes to reduce its size
The intuition behind this method is as follows: smaller trees adapt more quickly to changes, and larger trees do better during periods with no or little change, simply because they were built on more data. Trees limited to size s will be reset about twice as often as trees with a size limit of 2s. This creates a set of different reset-speeds for an ensemble of such trees, and therefore a subset of trees that are a good approximation for the current rate of change. It is important to note that resets will happen all the time, even for stationary datasets, but this behaviour should not have a negative impact on the ensemble’s predictive performance. When the tree size exceeds the maximun size value, there are two different delete options:
delete the oldest node, the root, and all of its children except the one where the split has been made. After that, the root of the child not deleted becomes the new root
delete all the nodes of the tree, i.e., restart from a new root.
The maximum allowed size for the n-th ASHT tree is twice the maximum allowed size for the (n-1)-th tree. Moreover, each tree has a weight proportional to the inverse of the square of its error, and it monitors its error with an exponential weighted moving average (EWMA) with alpha = .01. The size of the first tree is 2.
With this new method, it is attempted to improve bagging performance by increasing tree diversity. It has been observed that boosting tends to produce a more diverse set of classifiers than bagging, and this has been cited as a factor in increased performance.
See more details in:
Albert Bifet, Geoff Holmes, Bernhard Pfahringer, Richard Kirkby, and Ricard Gavaldà. New ensemble methods for evolving data streams. In 15th ACM SIGKDD International Conference on Knowledge Discovery and Data Mining, 2009.
The learner must be ASHoeffdingTree, a Hoeffding Tree with a maximum size value.
Example:
OzaBagASHT -l ASHoeffdingTree -s 10 -u -r Parameters:
Same parameters as OzaBag
-f : the size of first classifier in the bag.
-u : Enable weight classifiers
-r : Reset trees when size is higher than the max
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 78 of file ASHoeffdingTree.java.
Member Function Documentation
void moa.classifiers.trees.ASHoeffdingTree.deleteNode (Node node, int childIndex)
Definition at line 156 of file ASHoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.decisionNodeCount, and moa.classifiers.trees.HoeffdingTree.inactiveLeafNodeCount.
Referenced by moa.classifiers.trees.ASHoeffdingTree.resizeTree().
{
        Node child = ((SplitNode) node).getChild(childIndex);
        //if (child != null) {
        //}
        if (child instanceof SplitNode) {
            for (int branch = 0; branch < ((SplitNode) child).numChildren(); branch++) {
                deleteNode(child, branch);
            }
            this.decisionNodeCount--;
        } else if (child instanceof InactiveLearningNode) {
            this.inactiveLeafNodeCount--;
        } else if (child instanceof ActiveLearningNode) {
            this.activeLeafNodeCount--;
        }
        child = null;
    }
String moa.classifiers.trees.ASHoeffdingTree.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 83 of file ASHoeffdingTree.java.
{
        return "Adaptive Size Hoeffding Tree used in Bagging using trees of different size.";
    }
void moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 92 of file ASHoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafByteSizeEstimate, moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.byteSizeEstimateOverheadFraction, moa.classifiers.trees.HoeffdingTree.decisionNodeCount, moa.classifiers.trees.HoeffdingTree.growthAllowed, moa.classifiers.trees.HoeffdingTree.inactiveLeafByteSizeEstimate, moa.classifiers.trees.HoeffdingTree.inactiveLeafNodeCount, and moa.classifiers.trees.HoeffdingTree.treeRoot.
Referenced by moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
        this.treeRoot = null;
        this.decisionNodeCount = 0;
        this.activeLeafNodeCount = 0;
        this.inactiveLeafNodeCount = 0;
        this.inactiveLeafByteSizeEstimate = 0.0;
        this.activeLeafByteSizeEstimate = 0.0;
        this.byteSizeEstimateOverheadFraction = 1.0;
        this.growthAllowed = true;
    }
void moa.classifiers.trees.ASHoeffdingTree.resizeTree (Node node, int childIndex)
Definition at line 173 of file ASHoeffdingTree.java.
References moa.classifiers.trees.ASHoeffdingTree.deleteNode().
Referenced by moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
        //Assume that this is root node
        if (node instanceof SplitNode) {
            for (int branch = 0; branch < ((SplitNode) node).numChildren(); branch++) {
                if (branch != childIndex) {
                    deleteNode(node, branch);
                }
            }
        }
    }
void moa.classifiers.trees.ASHoeffdingTree.setMaxSize (int mSize)
Definition at line 148 of file ASHoeffdingTree.java.
References moa.classifiers.trees.ASHoeffdingTree.maxSize.
{
        this.maxSize = mSize;
    }
void moa.classifiers.trees.ASHoeffdingTree.setResetTree ()
Definition at line 152 of file ASHoeffdingTree.java.
References moa.classifiers.trees.ASHoeffdingTree.resetTree.
{
        this.resetTree = true;
    }
void moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 104 of file ASHoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.trees.HoeffdingTree.decisionNodeCount, moa.classifiers.trees.HoeffdingTree.estimateModelByteSizes(), moa.classifiers.trees.HoeffdingTree.Node.filterInstanceToLeaf(), moa.classifiers.trees.HoeffdingTree.SplitNode.getChild(), moa.options.IntOption.getValue(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation(), moa.classifiers.trees.HoeffdingTree.gracePeriodOption, moa.classifiers.trees.HoeffdingTree.growthAllowed, moa.classifiers.trees.HoeffdingTree.LearningNode.learnFromInstance(), moa.classifiers.trees.ASHoeffdingTree.maxSize, moa.classifiers.trees.HoeffdingTree.memoryEstimatePeriodOption, moa.classifiers.trees.HoeffdingTree.newLearningNode(), moa.classifiers.trees.HoeffdingTree.FoundNode.node, moa.classifiers.trees.HoeffdingTree.FoundNode.parent, moa.classifiers.trees.HoeffdingTree.FoundNode.parentBranch, moa.classifiers.trees.ASHoeffdingTree.resetLearningImpl(), moa.classifiers.trees.ASHoeffdingTree.resetTree, moa.classifiers.trees.ASHoeffdingTree.resizeTree(), moa.classifiers.trees.HoeffdingTree.SplitNode.setChild(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation(), moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.trees.HoeffdingTree.treeRoot.
{
        if (this.treeRoot == null) {
            this.treeRoot = newLearningNode();
            this.activeLeafNodeCount = 1;
        }
        FoundNode foundNode = this.treeRoot.filterInstanceToLeaf(inst, null, -1);
        Node leafNode = foundNode.node;
        if (leafNode == null) {
            leafNode = newLearningNode();
            foundNode.parent.setChild(foundNode.parentBranch, leafNode);
            this.activeLeafNodeCount++;
        }
        if (leafNode instanceof LearningNode) {
            LearningNode learningNode = (LearningNode) leafNode;
            learningNode.learnFromInstance(inst, this);
            if (this.growthAllowed
                    && (learningNode instanceof ActiveLearningNode)) {
                ActiveLearningNode activeLearningNode = (ActiveLearningNode) learningNode;
                double weightSeen = activeLearningNode.getWeightSeen();
                if (weightSeen
                        - activeLearningNode.getWeightSeenAtLastSplitEvaluation() >= this.gracePeriodOption.getValue()) {
                    attemptToSplit(activeLearningNode, foundNode.parent,
                            foundNode.parentBranch);
                    //EXTENSION TO ASHT
                    // if size too big, resize tree ONLY Split Nodes
                    while (this.decisionNodeCount >= this.maxSize && this.treeRoot instanceof SplitNode) {
                        if (this.resetTree == false) {
                            resizeTree(this.treeRoot, ((SplitNode) this.treeRoot).instanceChildIndex(inst));
                            this.treeRoot = ((SplitNode) this.treeRoot).getChild(((SplitNode) this.treeRoot).instanceChildIndex(inst));
                        } else {
                            resetLearningImpl();
                        }
                    }
                    activeLearningNode.setWeightSeenAtLastSplitEvaluation(weightSeen);
                }
            }
        }
        if (this.trainingWeightSeenByModel
                % this.memoryEstimatePeriodOption.getValue() == 0) {
            estimateModelByteSizes();
        }
    }
Member Data Documentation
int moa.classifiers.trees.ASHoeffdingTree.maxSize = 10000 [protected]
Definition at line 87 of file ASHoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.setMaxSize(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
boolean moa.classifiers.trees.ASHoeffdingTree.resetTree = false [protected]
Definition at line 89 of file ASHoeffdingTree.java.
Referenced by moa.classifiers.trees.ASHoeffdingTree.setResetTree(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
final long moa.classifiers.trees.ASHoeffdingTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.
Definition at line 80 of file ASHoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/ASHoeffdingTree.java