MOA: moa.classifiers.meta.RandomRules Class Reference
moa.classifiers.meta.RandomRules Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
FloatOption numAttributesPercentageOption
FlagOption useBaggingOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
boolean isRegression
int[][] listAttributes
int numAttributes
InstancesHeader[] dataset
Private Member Functions
Instance transformInstance (Instance inst, int classifierIndex)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 40 of file RandomRules.java.
Member Function Documentation
void moa.classifiers.meta.RandomRules.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 114 of file RandomRules.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.RandomRules.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 119 of file RandomRules.java.
References moa.classifiers.meta.RandomRules.ensemble.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0)};
    }
String moa.classifiers.meta.RandomRules.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 43 of file RandomRules.java.
{
        return "RandomRules";
    }
Classifier [] moa.classifiers.meta.RandomRules.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 125 of file RandomRules.java.
References moa.classifiers.meta.RandomRules.ensemble.
{
        return this.ensemble; //.clone();
    }
double [] moa.classifiers.meta.RandomRules.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 92 of file RandomRules.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.RandomRules.ensemble, moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.RandomRules.isRegression, moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.sumOfValues(), and moa.classifiers.meta.RandomRules.transformInstance().
{
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(transformInstance(inst,i)));
            if (vote.sumOfValues() != 0.0) {
                if (this.isRegression == false)
                    vote.normalize();
                combinedVote.addValues(vote);
            }
        }
        if (this.isRegression == true){
            combinedVote.scaleValues(1.0/this.ensemble.length);
        }
        return combinedVote.getArrayRef();
    }
boolean moa.classifiers.meta.RandomRules.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 109 of file RandomRules.java.
{
        return true;
    }
void moa.classifiers.meta.RandomRules.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 66 of file RandomRules.java.
References moa.classifiers.meta.RandomRules.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.RandomRules.ensemble, moa.classifiers.meta.RandomRules.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.meta.RandomRules.isRegression, and moa.classifiers.Classifier.resetLearning().
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
        this.isRegression = (baseLearner instanceof Regressor);
    }
void moa.classifiers.meta.RandomRules.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 77 of file RandomRules.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.meta.RandomRules.ensemble, moa.options.FlagOption.isSet, moa.classifiers.Classifier.trainOnInstance(), moa.classifiers.meta.RandomRules.transformInstance(), and moa.classifiers.meta.RandomRules.useBaggingOption.
{
        for (int i = 0; i < this.ensemble.length; i++) {
            int k = 1;
            if ( this.useBaggingOption.isSet()) {
                k = MiscUtils.poisson(1.0, this.classifierRandom);
            }
                if (k > 0) {
                Instance weightedInst = transformInstance(inst,i);
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
        }
    }
Instance moa.classifiers.meta.RandomRules.transformInstance (Instance inst, int classifierIndex) [private]
Definition at line 133 of file RandomRules.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.meta.RandomRules.dataset, moa.classifiers.meta.RandomRules.ensemble, moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.FloatOption.getValue(), moa.classifiers.meta.RandomRules.listAttributes, moa.classifiers.meta.RandomRules.numAttributes, moa.classifiers.meta.RandomRules.numAttributesPercentageOption, and moa.classifiers.Classifier.setModelContext().
Referenced by moa.classifiers.meta.RandomRules.getVotesForInstance(), and moa.classifiers.meta.RandomRules.trainOnInstanceImpl().
{
        if (this.listAttributes == null) {
            this.numAttributes = (int) (this.numAttributesPercentageOption.getValue() * inst.numAttributes()/100.0);
            this.listAttributes = new int[this.numAttributes][this.ensemble.length];
            this.dataset = new InstancesHeader[this.ensemble.length];
            for (int ensembleIndex = 0; ensembleIndex < this.ensemble.length; ensembleIndex++) {
               for (int attributeIndex = 0; attributeIndex < this.numAttributes; attributeIndex++) {
                    boolean isUnique = false;
                    while (isUnique == false) {
                        this.listAttributes[attributeIndex][ensembleIndex] = this.classifierRandom.nextInt(inst.numAttributes() - 1);
                        isUnique = true;
                        for (int k = 0; k < attributeIndex; k++) {
                            if (this.listAttributes[attributeIndex][ensembleIndex] == this.listAttributes[k][ensembleIndex]) {
                                isUnique = false;
                                break;
                            }
                        }
                    }
                   //this.listAttributes[attributeIndex][ensembleIndex] = attributeIndex;
                }
                //Create Header
                FastVector attributes = new FastVector();
                for (int attributeIndex = 0; attributeIndex < this.numAttributes; attributeIndex++) {
                    attributes.addElement(inst.attribute(this.listAttributes[attributeIndex][ensembleIndex]));
                    System.out.print(this.listAttributes[attributeIndex][ensembleIndex]);
                }
                System.out.println("Number of attributes: "+this.numAttributes+ ","+inst.numAttributes());
                attributes.addElement(inst.classAttribute());
                this.dataset[ensembleIndex] =  new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
                this.dataset[ensembleIndex].setClassIndex(this.numAttributes);
                this.ensemble[ensembleIndex].setModelContext(this.dataset[ensembleIndex]);
            }
        }
        //Instance instance = new DenseInstance(this.numAttributes+1);
        //instance.setDataset(dataset[classifierIndex]);
        double[] attVals = new double[this.numAttributes + 1];
        for (int attributeIndex = 0; attributeIndex < this.numAttributes; attributeIndex++) {
                //instance.setValue(attributeIndex, inst.value(this.listAttributes[attributeIndex][classifierIndex]));
                attVals[attributeIndex] = inst.value(this.listAttributes[attributeIndex][classifierIndex]);
        }
        Instance instance = new DenseInstance(1.0, attVals);
        instance.setDataset(dataset[classifierIndex]);
        instance.setClassValue(inst.classValue());
       // System.out.println(inst.toString());
       // System.out.println(instance.toString());
       // System.out.println("============");
        return instance;
    }
Member Data Documentation
ClassOption moa.classifiers.meta.RandomRules.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "rules.AMRules")
Definition at line 49 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.resetLearningImpl().
InstancesHeader [] moa.classifiers.meta.RandomRules.dataset [protected]
Definition at line 131 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.transformInstance().
Classifier [] moa.classifiers.meta.RandomRules.ensemble [protected]
Definition at line 61 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.getModelMeasurementsImpl(), moa.classifiers.meta.RandomRules.getSubClassifiers(), moa.classifiers.meta.RandomRules.getVotesForInstance(), moa.classifiers.meta.RandomRules.resetLearningImpl(), moa.classifiers.meta.RandomRules.trainOnInstanceImpl(), and moa.classifiers.meta.RandomRules.transformInstance().
IntOption moa.classifiers.meta.RandomRules.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models in the bag.", 10, 1, Integer.MAX_VALUE)
Definition at line 52 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.resetLearningImpl().
boolean moa.classifiers.meta.RandomRules.isRegression [protected]
Definition at line 63 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.getVotesForInstance(), and moa.classifiers.meta.RandomRules.resetLearningImpl().
int [][] moa.classifiers.meta.RandomRules.listAttributes [protected]
Definition at line 129 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.transformInstance().
int moa.classifiers.meta.RandomRules.numAttributes [protected]
Definition at line 130 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.transformInstance().
FloatOption moa.classifiers.meta.RandomRules.numAttributesPercentageOption
Initial value:
 new FloatOption("numAttributesPercentage", 'n',
            "The number of attributes to use per model.", 63.2, 0, 100)
Definition at line 55 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.transformInstance().
final long moa.classifiers.meta.RandomRules.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 47 of file RandomRules.java.
FlagOption moa.classifiers.meta.RandomRules.useBaggingOption
Initial value:
 new FlagOption("useBagging", 'p',
            "Use Bagging.")
Definition at line 58 of file RandomRules.java.
Referenced by moa.classifiers.meta.RandomRules.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/RandomRules.java