MOA: moa.streams.generators.HyperplaneGenerator Class Reference
moa.streams.generators.HyperplaneGenerator Class Reference
Stream generator for Hyperplane data stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption instanceRandomSeedOption
IntOption numClassesOption
IntOption numAttsOption
IntOption numDriftAttsOption
FloatOption magChangeOption
IntOption noisePercentageOption
IntOption sigmaPercentageOption
int numberInstance
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
void generateHeader ()
Protected Attributes
InstancesHeader streamHeader
Random instanceRandom
double[] weights
int[] sigma
Private Member Functions
void addDrift ()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for Hyperplane data stream.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 44 of file HyperplaneGenerator.java.
Member Function Documentation
void moa.streams.generators.HyperplaneGenerator.addDrift () [private]
Definition at line 160 of file HyperplaneGenerator.java.
References moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.generators.HyperplaneGenerator.instanceRandom, moa.streams.generators.HyperplaneGenerator.magChangeOption, moa.streams.generators.HyperplaneGenerator.numDriftAttsOption, moa.streams.generators.HyperplaneGenerator.sigma, moa.streams.generators.HyperplaneGenerator.sigmaPercentageOption, and moa.streams.generators.HyperplaneGenerator.weights.
Referenced by moa.streams.generators.HyperplaneGenerator.nextInstance().
{
        for (int i = 0; i < this.numDriftAttsOption.getValue(); i++) {
            this.weights[i] += (double) ((double) sigma[i]) * ((double) this.magChangeOption.getValue());
            if (//this.weights[i] >= 1.0 || this.weights[i] <= 0.0 ||
                    (1 + (this.instanceRandom.nextInt(100))) <= this.sigmaPercentageOption.getValue()) {
                this.sigma[i] *= -1;
            }
        }
    }
long moa.streams.generators.HyperplaneGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 111 of file HyperplaneGenerator.java.
{
        return -1;
    }
void moa.streams.generators.HyperplaneGenerator.generateHeader () [protected]
Definition at line 94 of file HyperplaneGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.options.IntOption.getValue(), moa.streams.generators.HyperplaneGenerator.numAttsOption, moa.streams.generators.HyperplaneGenerator.numClassesOption, and moa.streams.generators.HyperplaneGenerator.streamHeader.
Referenced by moa.streams.generators.HyperplaneGenerator.prepareForUseImpl().
{
        FastVector attributes = new FastVector();
        for (int i = 0; i < this.numAttsOption.getValue(); i++) {
            attributes.addElement(new Attribute("att" + (i + 1)));
        }
        FastVector classLabels = new FastVector();
        for (int i = 0; i < this.numClassesOption.getValue(); i++) {
            classLabels.addElement("class" + (i + 1));
        }
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
    }
void moa.streams.generators.HyperplaneGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 182 of file HyperplaneGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.HyperplaneGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 116 of file HyperplaneGenerator.java.
References moa.streams.generators.HyperplaneGenerator.streamHeader.
Referenced by moa.streams.generators.HyperplaneGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.HyperplaneGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 48 of file HyperplaneGenerator.java.
{
        return "Generates a problem of predicting class of a rotating hyperplane.";
    }
boolean moa.streams.generators.HyperplaneGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 121 of file HyperplaneGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.HyperplaneGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 126 of file HyperplaneGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.HyperplaneGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 131 of file HyperplaneGenerator.java.
References moa.streams.generators.HyperplaneGenerator.addDrift(), moa.streams.generators.HyperplaneGenerator.getHeader(), moa.options.IntOption.getValue(), moa.streams.generators.HyperplaneGenerator.instanceRandom, moa.streams.generators.HyperplaneGenerator.noisePercentageOption, moa.streams.generators.HyperplaneGenerator.numAttsOption, and moa.streams.generators.HyperplaneGenerator.weights.
{
        int numAtts = this.numAttsOption.getValue();
        double[] attVals = new double[numAtts + 1];
        double sum = 0.0;
        double sumWeights = 0.0;
        for (int i = 0; i < numAtts; i++) {
            attVals[i] = this.instanceRandom.nextDouble();
            sum += this.weights[i] * attVals[i];
            sumWeights += this.weights[i];
        }
        int classLabel;
        if (sum >= sumWeights * 0.5) {
            classLabel = 1;
        } else {
            classLabel = 0;
        }
        //Add Noise
        if ((1 + (this.instanceRandom.nextInt(100))) <= this.noisePercentageOption.getValue()) {
            classLabel = (classLabel == 0 ? 1 : 0);
        }
        Instance inst = new DenseInstance(1.0, attVals);
        inst.setDataset(getHeader());
        inst.setClassValue(classLabel);
        addDrift();
        return inst;
    }
void moa.streams.generators.HyperplaneGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 87 of file HyperplaneGenerator.java.
References moa.streams.generators.HyperplaneGenerator.generateHeader(), moa.streams.generators.HyperplaneGenerator.restart(), and moa.tasks.TaskMonitor.setCurrentActivity().
{
        monitor.setCurrentActivity("Preparing hyperplane...", -1.0);
        generateHeader();
        restart();
    }
void moa.streams.generators.HyperplaneGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 171 of file HyperplaneGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.HyperplaneGenerator.instanceRandom, moa.streams.generators.HyperplaneGenerator.instanceRandomSeedOption, moa.streams.generators.HyperplaneGenerator.numAttsOption, moa.streams.generators.HyperplaneGenerator.numDriftAttsOption, moa.streams.generators.HyperplaneGenerator.sigma, and moa.streams.generators.HyperplaneGenerator.weights.
Referenced by moa.streams.generators.HyperplaneGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
        this.weights = new double[this.numAttsOption.getValue()];
        this.sigma = new int[this.numAttsOption.getValue()];
        for (int i = 0; i < this.numAttsOption.getValue(); i++) {
            this.weights[i] = this.instanceRandom.nextDouble();
            this.sigma[i] = (i < this.numDriftAttsOption.getValue() ? 1 : 0);
        }
    }
Member Data Documentation
Random moa.streams.generators.HyperplaneGenerator.instanceRandom [protected]
Definition at line 78 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), moa.streams.generators.HyperplaneGenerator.nextInstance(), and moa.streams.generators.HyperplaneGenerator.restart().
IntOption moa.streams.generators.HyperplaneGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 54 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.restart().
FloatOption moa.streams.generators.HyperplaneGenerator.magChangeOption
Initial value:
 new FloatOption("magChange", 't',
            "Magnitude of the change for every example", 0.0, 0.0, 1.0)
Definition at line 67 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift().
IntOption moa.streams.generators.HyperplaneGenerator.noisePercentageOption
Initial value:
 new IntOption("noisePercentage",
            'n', "Percentage of noise to add to the data.", 5, 0, 100)
Definition at line 70 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.nextInstance().
IntOption moa.streams.generators.HyperplaneGenerator.numAttsOption
Initial value:
 new IntOption("numAtts", 'a',
            "The number of attributes to generate.", 10, 0, Integer.MAX_VALUE)
Definition at line 61 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.generateHeader(), moa.streams.generators.HyperplaneGenerator.nextInstance(), and moa.streams.generators.HyperplaneGenerator.restart().
int moa.streams.generators.HyperplaneGenerator.numberInstance
Definition at line 84 of file HyperplaneGenerator.java.
IntOption moa.streams.generators.HyperplaneGenerator.numClassesOption
Initial value:
 new IntOption("numClasses", 'c',
            "The number of classes to generate.", 2, 2, Integer.MAX_VALUE)
Definition at line 58 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.generateHeader().
IntOption moa.streams.generators.HyperplaneGenerator.numDriftAttsOption
Initial value:
 new IntOption("numDriftAtts", 'k',
            "The number of attributes with drift.", 2, 0, Integer.MAX_VALUE)
Definition at line 64 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), and moa.streams.generators.HyperplaneGenerator.restart().
final long moa.streams.generators.HyperplaneGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 52 of file HyperplaneGenerator.java.
int [] moa.streams.generators.HyperplaneGenerator.sigma [protected]
Definition at line 82 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), and moa.streams.generators.HyperplaneGenerator.restart().
IntOption moa.streams.generators.HyperplaneGenerator.sigmaPercentageOption
Initial value:
 new IntOption("sigmaPercentage",
            's', "Percentage of probability that the direction of change is reversed.", 10, 0, 100)
Definition at line 73 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift().
InstancesHeader moa.streams.generators.HyperplaneGenerator.streamHeader [protected]
Definition at line 76 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.generateHeader(), and moa.streams.generators.HyperplaneGenerator.getHeader().
double [] moa.streams.generators.HyperplaneGenerator.weights [protected]
Definition at line 80 of file HyperplaneGenerator.java.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), moa.streams.generators.HyperplaneGenerator.nextInstance(), and moa.streams.generators.HyperplaneGenerator.restart().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/HyperplaneGenerator.java