MOA: moa.gui.BatchCmd Class Reference
moa.gui.BatchCmd Class Reference
Public Member Functions
BatchCmd (AbstractClusterer clusterer, ClusteringStream stream, MeasureCollection[] measures, int totalInstances)
void run ()
void changeCluster (ClusterEvent e)
Static Public Member Functions
static void main (String[] args)
static void runBatch (ClusteringStream stream, AbstractClusterer clusterer, int measureCollectionType, int amountInstances, String outputFile)
static void exportCSV (String filepath, ArrayList< ClusterEvent > clusterEvents, MeasureCollection[] measures, int horizon)
Public Attributes
boolean useMicroGT = false
Private Member Functions
ArrayList< ClusterEvent > getEventList ()
Static Private Member Functions
static ArrayList< Class > getMeasureSelection (int selection)
static MeasureCollection[] getMeasures (ArrayList< Class > measure_classes)
Private Attributes
ArrayList< ClusterEvent > clusterEvents
AbstractClusterer clusterer
ClusteringStream stream
MeasureCollection[] measures
int totalInstances
Detailed Description
Definition at line 55 of file BatchCmd.java.
Constructor & Destructor Documentation
moa.gui.BatchCmd.BatchCmd (AbstractClusterer clusterer, ClusteringStream stream, MeasureCollection[] measures, int totalInstances)
Definition at line 66 of file BatchCmd.java.
References moa.gui.BatchCmd.clusterEvents, and moa.options.AbstractOptionHandler.prepareForUse().
Referenced by moa.gui.BatchCmd.runBatch().
{
        this.clusterer = clusterer;
        this.stream = stream;
        this.totalInstances = totalInstances;
        this.measures = measures;
        if(stream instanceof RandomRBFGeneratorEvents){
            ((RandomRBFGeneratorEvents)stream).addClusterChangeListener(this);
            clusterEvents = new ArrayList<ClusterEvent>();
        }
        else{
            clusterEvents = null;
        }
        stream.prepareForUse();
        clusterer.prepareForUse();
    }
Member Function Documentation
void moa.gui.BatchCmd.changeCluster (ClusterEvent e)
Implements moa.streams.clustering.ClusterEventListener.
Definition at line 217 of file BatchCmd.java.
References moa.gui.BatchCmd.clusterEvents.
{
        if(clusterEvents!=null) clusterEvents.add(e);
    }
static void moa.gui.BatchCmd.exportCSV (String filepath, ArrayList< ClusterEvent > clusterEvents, MeasureCollection[] measures, int horizon) [static]
Definition at line 222 of file BatchCmd.java.
References moa.evaluation.MeasureCollection.getNumberOfValues(), and moa.evaluation.MeasureCollection.getNumMeasures().
Referenced by moa.gui.BatchCmd.runBatch().
{
        PrintWriter out = null;
        try {
            // Prepare an output file
            if (!filepath.endsWith(".csv")) {
                filepath += ".csv";
            }
            out = new PrintWriter(new BufferedWriter(new FileWriter(filepath)));
            String delimiter = ";";
            // Header
            int numValues = 0;
            out.write("Nr" + delimiter);
            out.write("Event" + delimiter);
            for (int m = 0; m < 1; m++) {   // TODO: Multiple group of measures
                for (int i = 0; i < measures.length; i++) {
                    for (int j = 0; j < measures[i].getNumMeasures(); j++) {
                        if (measures[i].isEnabled(j)) {
                            out.write(measures[i].getName(j) + delimiter);
                            numValues = measures[i].getNumberOfValues(j);
                        }
                    }
                }
            }
            out.write("\n");
            // Rows
            Iterator<ClusterEvent> eventIt = null;
            ClusterEvent event = null;
            if (clusterEvents != null) {
                if (clusterEvents.size() > 0) {
                    eventIt = clusterEvents.iterator();
                    event = eventIt.next();
                }
            }
            for (int v = 0; v < numValues; v++){
                // Nr
                out.write(v + delimiter);
                // Events
                if (event != null && event.getTimestamp() <= horizon) {
                    out.write(event.getType() + delimiter);
                    if (eventIt != null && eventIt.hasNext()) {
                        event = eventIt.next();
                    } else {
                        event = null;
                    }
                } else {
                    out.write(delimiter);
                }
                // Values
                for (int m = 0; m < 1; m++) {   // TODO: Multiple group of measures
                    for (int i = 0; i < measures.length; i++) {
                        for (int j = 0; j < measures[i].getNumMeasures(); j++) {
                            if (measures[i].isEnabled(j)) {
                                out.write(measures[i].getValue(j, v) + delimiter);
                            }
                        }
                    }
                }
                out.write("\n");
            }
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(RunVisualizer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }
ArrayList<ClusterEvent> moa.gui.BatchCmd.getEventList () [private]
Definition at line 83 of file BatchCmd.java.
References moa.gui.BatchCmd.clusterEvents.
Referenced by moa.gui.BatchCmd.runBatch().
{
        return clusterEvents;
    }
static MeasureCollection [] moa.gui.BatchCmd.getMeasures (ArrayList< Class > measure_classes) [static, private]
Definition at line 202 of file BatchCmd.java.
References moa.gui.BatchCmd.measures.
Referenced by moa.gui.BatchCmd.runBatch().
{
        MeasureCollection[] measures = new MeasureCollection[measure_classes.size()];
        for (int i = 0; i < measure_classes.size(); i++) {
            try {
                MeasureCollection m = (MeasureCollection)measure_classes.get(i).newInstance();
                measures[i] = m;
            } catch (Exception ex) {
                Logger.getLogger("Couldn't create Instance for "+measure_classes.get(i).getName());
                ex.printStackTrace();
            }
        }
        return measures;
    }
static ArrayList<Class> moa.gui.BatchCmd.getMeasureSelection (int selection) [static, private]
Definition at line 88 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.runBatch().
{
        ArrayList<Class>mclasses = new ArrayList<Class>();
        mclasses.add(EntropyCollection.class);
        mclasses.add(F1.class);
        mclasses.add(General.class);
        mclasses.add(SSQ.class);
        mclasses.add(SilhouetteCoefficient.class);
        mclasses.add(StatisticalCollection.class);
        return mclasses;
    }
static void moa.gui.BatchCmd.main (String[] args) [static]
Definition at line 102 of file BatchCmd.java.
References moa.gui.BatchCmd.clusterer, moa.gui.BatchCmd.runBatch(), and moa.gui.BatchCmd.stream.
{
        RandomRBFGeneratorEvents stream = new RandomRBFGeneratorEvents();
        AbstractClusterer clusterer = new WithKmeans();
        int measureCollectionType = 0;
        int amountInstances = 20000;
        String testfile = "d:\\data\\test.csv";
        runBatch(stream, clusterer, measureCollectionType, amountInstances, testfile);
    }
void moa.gui.BatchCmd.run ()
Definition at line 131 of file BatchCmd.java.
References moa.gui.BatchCmd.clusterer, moa.evaluation.MeasureCollection.evaluateClusteringPerformance(), moa.clusterers.AbstractClusterer.evaluateMicroClusteringOption, moa.clusterers.Clusterer.getClusteringResult(), moa.streams.clustering.ClusteringStream.getDecayHorizon(), moa.streams.clustering.ClusteringStream.getDecayThreshold(), moa.clusterers.AbstractClusterer.getMicroClusteringResult(), moa.streams.InstanceStream.hasMoreInstances(), moa.clusterers.AbstractClusterer.implementsMicroClusterer(), moa.options.FlagOption.isSet, moa.gui.BatchCmd.measures, moa.streams.InstanceStream.nextInstance(), moa.gui.BatchCmd.stream, moa.gui.BatchCmd.totalInstances, moa.clusterers.AbstractClusterer.trainOnInstanceImpl(), and moa.gui.BatchCmd.useMicroGT.
Referenced by moa.gui.BatchCmd.runBatch().
                     {
        ArrayList<DataPoint> pointBuffer0 = new ArrayList<DataPoint>();
        int m_timestamp = 0;
        int decayHorizon = stream.getDecayHorizon();
        double decay_threshold = stream.getDecayThreshold();
        double decay_rate = (-1*Math.log(decay_threshold)/decayHorizon);
        int counter = decayHorizon;
        while(m_timestamp < totalInstances && stream.hasMoreInstances()){
            m_timestamp++;
            counter--;
            Instance next = stream.nextInstance();
            DataPoint point0 = new DataPoint(next,m_timestamp);
            pointBuffer0.add(point0);
            Instance traininst0 = new DenseInstance(point0);
            if(clusterer instanceof ClusterGenerator)
                traininst0.setDataset(point0.dataset());
            else
                traininst0.deleteAttributeAt(point0.classIndex());
            clusterer.trainOnInstanceImpl(traininst0);
            if(counter <= 0){
                //                if(m_timestamp%(totalInstances/10) == 0)
                    //                    System.out.println("Thread"+threadID+":"+(m_timestamp*100/totalInstances)+"% ");
                for(DataPoint p:pointBuffer0)
                    p.updateWeight(m_timestamp, decay_rate);
                Clustering gtClustering0;
                Clustering clustering0 = null;
                gtClustering0 = new Clustering(pointBuffer0);
                if(useMicroGT && stream instanceof RandomRBFGeneratorEvents){
                    gtClustering0 = ((RandomRBFGeneratorEvents)stream).getMicroClustering();
                }
                clustering0 = clusterer.getClusteringResult();
                if(clusterer.implementsMicroClusterer()){
                    if(clusterer instanceof ClusterGenerator
                            && stream instanceof RandomRBFGeneratorEvents){
                        ((ClusterGenerator)clusterer).setSourceClustering(((RandomRBFGeneratorEvents)stream).getMicroClustering());
                    }
                    Clustering microC = clusterer.getMicroClusteringResult();
                    if(clusterer.evaluateMicroClusteringOption.isSet()){
                        clustering0 = microC;
                    }
                    else{
                        if(clustering0 == null && microC != null)
                            clustering0 = moa.clusterers.KMeans.gaussianMeans(gtClustering0, microC);
                    }
                }
                //evaluate
                for (int i = 0; i < measures.length; i++) {
                    try {
                        /*double sec =*/ measures[i].evaluateClusteringPerformance(clustering0, gtClustering0, pointBuffer0);
                        //System.out.println("Eval of "+measures[i].getClass().getSimpleName()+" at "+m_timestamp+" took "+sec);
                    } catch (Exception ex) { ex.printStackTrace(); }
                }
                pointBuffer0.clear();
                counter = decayHorizon;
            }
        }
    }
static void moa.gui.BatchCmd.runBatch (ClusteringStream stream, AbstractClusterer clusterer, int measureCollectionType, int amountInstances, String outputFile) [static]
Definition at line 113 of file BatchCmd.java.
References moa.gui.BatchCmd.BatchCmd(), moa.gui.BatchCmd.clusterEvents, moa.streams.clustering.ClusteringStream.decayHorizonOption, moa.gui.BatchCmd.exportCSV(), moa.gui.BatchCmd.getEventList(), moa.gui.BatchCmd.getMeasures(), moa.gui.BatchCmd.getMeasureSelection(), moa.options.IntOption.getValue(), moa.gui.BatchCmd.measures, and moa.gui.BatchCmd.run().
Referenced by moa.gui.BatchCmd.main().
{
        // create the measure collection
        MeasureCollection[] measures = getMeasures(getMeasureSelection(measureCollectionType));
        // run the batch job
        BatchCmd batch = new BatchCmd(clusterer, stream, measures, amountInstances);
        batch.run();
        // read events and horizon
        ArrayList<ClusterEvent> clusterEvents = batch.getEventList();
        int horizon = stream.decayHorizonOption.getValue();
        // write results to file
        exportCSV(outputFile, clusterEvents, measures, horizon);
    }
Member Data Documentation
AbstractClusterer moa.gui.BatchCmd.clusterer [private]
Definition at line 58 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.main(), and moa.gui.BatchCmd.run().
ArrayList<ClusterEvent> moa.gui.BatchCmd.clusterEvents [private]
Definition at line 57 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.BatchCmd(), moa.gui.BatchCmd.changeCluster(), moa.gui.BatchCmd.getEventList(), and moa.gui.BatchCmd.runBatch().
MeasureCollection [] moa.gui.BatchCmd.measures [private]
Definition at line 60 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.getMeasures(), moa.gui.BatchCmd.run(), and moa.gui.BatchCmd.runBatch().
ClusteringStream moa.gui.BatchCmd.stream [private]
Definition at line 59 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.main(), and moa.gui.BatchCmd.run().
int moa.gui.BatchCmd.totalInstances [private]
Definition at line 62 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.run().
boolean moa.gui.BatchCmd.useMicroGT = false
Definition at line 63 of file BatchCmd.java.
Referenced by moa.gui.BatchCmd.run().
The documentation for this class was generated from the following file:
main/java/moa/gui/BatchCmd.java