MOA: moa.clusterers.outliers.SimpleCOD.SimpleCOD Class Reference
moa.clusterers.outliers.SimpleCOD.SimpleCOD Class Reference
Public Member Functions
SimpleCOD ()
void Init ()
Public Attributes
FloatOption radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
IntOption kOption = new IntOption("k", 't', "Parameter k.", 50)
Protected Member Functions
void ProcessNewStreamObj (Instance inst)
Package Functions
void ProcessNewNode (ISBNode nodeNew, boolean bNewNode)
void AddToEventQueue (ISBNode x, ISBNode nodeMinExp)
void ProcessEventQueue (ISBNode nodeExpired)
void ProcessExpiredNode (ISBNode nodeExpired)
Detailed Description
Definition at line 35 of file SimpleCOD.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.SimpleCOD.SimpleCOD.SimpleCOD ()
Definition at line 39 of file SimpleCOD.java.
Referenced by moa.clusterers.outliers.SimpleCOD.Test.main().
    {
        // System.out.println("SimpleCOD: created");
    }
Member Function Documentation
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue (ISBNode x, ISBNode nodeMinExp) [package]
Definition at line 119 of file SimpleCOD.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.bWarning, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.eventQueue, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.Get_nn_before(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpirationTime(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.Insert(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeList().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
{
        if (bTrace) Println("AddToEventQueue x.id: " + x.id);
        if (nodeMinExp != null) {
            Long expTime = GetExpirationTime(nodeMinExp);
            eventQueue.Insert(x, expTime);
            if (bTrace) {
                Print("x.nn_before: "); PrintNodeList(x.Get_nn_before());
                Println("nodeMinExp: " + nodeMinExp.id + ", expTime = " + expTime);
                PrintEventQueue();
            }
        } else {
            if (bWarning) Println("AddToEventQueue: Cannot add x.id: " + x.id + " to event queue (nn_before is empty, count_after=" + x.count_after + ")");
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 45 of file SimpleCOD.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.eventQueue, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.FIRST_OBJ_ID, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB, moa.clusterers.outliers.SimpleCOD.SimpleCOD.kOption, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_k, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyInlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyOutlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_radius, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_WindowSize, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.radiusOption, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes, and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
                       {
        super.Init();
        m_WindowSize = windowSizeOption.getValue();
        m_radius = radiusOption.getValue();
        m_k = kOption.getValue();
        Println("Init SimpleCOD:");
        Println("   window_size: " + m_WindowSize);
        Println("   radius: " + m_radius);
        Println("   k: " + m_k);
        //bTrace = true;
        //bWarning = true;
        objId = FIRST_OBJ_ID; // init object identifier
        // create nodes list of window
        windowNodes = new Vector<ISBNode>();
        // create ISB
        ISB = new ISBIndex(m_radius, m_k);
        // create event queue
        eventQueue = new EventQueue();
        // init statistics
        m_nBothInlierOutlier = 0;
        m_nOnlyInlier = 0;
        m_nOnlyOutlier = 0;
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue (ISBNode nodeExpired) [package]
Definition at line 134 of file SimpleCOD.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.bOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.bWarning, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.eventQueue, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.ExtractMin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.FindMin(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.GetMinPrecNeigh(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsNodeIdInWin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_k, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventItem.node, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.RemovePrecNeigh(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.SaveOutlier(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventItem.timeStamp.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode().
{
        EventItem e = eventQueue.FindMin();
        while ((e != null) && (e.timeStamp <= GetWindowEnd())) {
            e = eventQueue.ExtractMin();
            ISBNode x = e.node;
            if (bTrace) Println("Process event queue: check node x: " + x.id);
            // node x must be in window
            if (IsNodeIdInWin(x.id)) {
                // remove nodeExpired from x.nn_before
                x.RemovePrecNeigh(nodeExpired);
                // get amount of neighbors of x
                int count = x.count_after + x.CountPrecNeighs(GetWindowStart());
                if (count < m_k) {
                    if (bTrace) Println("x is an outlier");
                    x.bOutlier = true;
                    SaveOutlier(x);
                } else {
                    if (bTrace) Println("x is an inlier, add to event queue");
                    x.bOutlier = false;
                    // get oldest preceding neighbor of x
                    ISBNode nodeMinExp = x.GetMinPrecNeigh(GetWindowStart());
                    // add x to event queue
                    AddToEventQueue(x, nodeMinExp);
                }
            } else {
                if (bWarning) Println("Process event queue: node x.id: " + x.id + " has expired!");
            }
            e = eventQueue.FindMin();
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode (ISBNode nodeExpired) [package]
Definition at line 165 of file SimpleCOD.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), moa.clusterers.outliers.SimpleCOD.ISBIndex.Remove(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveNode().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        if (nodeExpired != null) {
            if (bTrace) Println("\nnodeExpired: " + nodeExpired.id);
            ISB.Remove(nodeExpired); // remove nodeExpired from index
            RemoveNode(nodeExpired);
            ProcessEventQueue(nodeExpired);
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode (ISBNode nodeNew, boolean bNewNode) [package]
Definition at line 74 of file SimpleCOD.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.AddPrecNeigh(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.bOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.GetMinPrecNeigh(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_k, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_radius, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode(), moa.clusterers.outliers.SimpleCOD.ISBIndex.RangeSearch(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveOutlier(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.SaveOutlier().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        if (bTrace) { Print("ProcessNewNode: "); PrintNode(nodeNew); }
        if (bTrace) Println("Perform R range query");
        nRangeQueriesExecuted++;
        Vector<ISBSearchResult> resultNodes;
        resultNodes = ISB.RangeSearch(nodeNew, m_radius);
        for (ISBSearchResult sr : resultNodes) {
            double distance = sr.distance;
            ISBNode q = sr.node;
            if ( (nodeNew != q) && (distance <= m_radius) ) {
                if (bTrace) Println("nodeNew has neighbor q.id " + q.id);
                nodeNew.AddPrecNeigh(q);
                q.count_after++;
                if (q.bOutlier) {
                    int count = q.CountPrecNeighs(GetWindowStart()) + q.count_after;
                    if (count >= m_k) {
                        if (bTrace) Println("q.id " + q.id + " is now an inlier");
                        q.bOutlier = false;
                        RemoveOutlier(q);
                        // insert q to event queue
                        ISBNode nodeMinExp = q.GetMinPrecNeigh(GetWindowStart());
                        AddToEventQueue(q, nodeMinExp);
                    }
                }
            }
        }
        if (bTrace) Println("Check if nodeNew is an inlier or outlier");
        int count = nodeNew.CountPrecNeighs(GetWindowStart()) + nodeNew.count_after;
        if (count >= m_k) {
            if (bTrace) Println("nodeNew is an inlier");
            nodeNew.bOutlier = false;
            RemoveOutlier(nodeNew); // updates statistics
            // insert nodeNew to event queue
            ISBNode nodeMinExp = nodeNew.GetMinPrecNeigh(GetWindowStart());
            AddToEventQueue(nodeNew, nodeMinExp);
        } else {
            if (bTrace) Println("nodeNew is an outlier");
            nodeNew.bOutlier = true;
            SaveOutlier(nodeNew);
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 175 of file SimpleCOD.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.AddNode(), moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpiredNode(), moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues(), moa.clusterers.outliers.SimpleCOD.ISBIndex.Insert(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintISB(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), and moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress().
    {
        if (bShowProgress) ShowProgress("Processed " + (objId-1) + " stream objects.");
        // PrintInstance(inst);
        double[] values = getInstanceValues(inst);
        StreamObj obj = new StreamObj(values);
        if (bTrace) Println("\n- - - - - - - - - - - -\n");
        // create new ISB node
        ISBNode nodeNew = new ISBNode(inst, obj, objId);
        if (bTrace) { Print("New node: "); PrintNode(nodeNew); }
        objId++; // update object identifier (slide window)
        AddNode(nodeNew); // add nodeNew to window
        if (bTrace) PrintWindow();
        // insert new node to ISB index
        ISB.Insert(nodeNew);
        ProcessNewNode(nodeNew, true);
        ProcessExpiredNode(GetExpiredNode());
        if (bTrace) {
            PrintOutliers();
            PrintISB();
        }
    }
Member Data Documentation
IntOption moa.clusterers.outliers.SimpleCOD.SimpleCOD.kOption = new IntOption("k", 't', "Parameter k.", 50)
Definition at line 37 of file SimpleCOD.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.Test.main().
FloatOption moa.clusterers.outliers.SimpleCOD.SimpleCOD.radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
Definition at line 36 of file SimpleCOD.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.Test.main().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/SimpleCOD/SimpleCOD.java