MOA: moa.gui.visualization.StreamOutlierPanel Class Reference
moa.gui.visualization.StreamOutlierPanel Class Reference
Classes
class ImgPanel
class LabelAlgorithmPanel
Public Member Functions
StreamOutlierPanel (Color colorAlgorithmTitle)
void drawOutliers (Vector< Outlier > outliers, Color color)
void repaintOutliers ()
void setOutliersVisibility (boolean visibility)
void setPointsVisibility (boolean visibility)
void clearPoints ()
void clearEvents ()
void ApplyToCanvas (BufferedImage img)
void RedrawPointLayer ()
void drawPoint (DataPoint point, boolean bShowDecay, boolean bRedrawPointImg)
void drawEvent (OutlierEvent outlierEvent, boolean bRedrawPointImg)
void applyDrawDecay (float factor, boolean bRedrawPointImg)
void screenshot (String filename, boolean svg, boolean png)
OutlierPanel getHighlightedOutlierPanel ()
void setHighlightedOutlierPanel (OutlierPanel outlierpanel)
void setZoom (int x, int y, int zoom_delta, JScrollPane scrollPane)
int getActiveXDim ()
void setActiveXDim (int activeXDim)
int getActiveYDim ()
void setActiveYDim (int activeYDim)
void setVisualizer (RunOutlierVisualizer v)
void setOutlierDetector (MyBaseOutlierDetector outlierDetector)
void componentHidden (ComponentEvent e)
void componentMoved (ComponentEvent e)
void componentResized (ComponentEvent e)
void componentShown (ComponentEvent e)
Private Member Functions
JPanel getNewLayer ()
void drawPoint (DataPoint point, boolean bShowDecay, Color c, boolean bFill, boolean bRedrawPointImg)
void drawOutliers (JPanel layer, Vector< Outlier > outliers, Color color)
void initComponents ()
This method is called from within the constructor to initialize the form.
void formMouseClicked (java.awt.event.MouseEvent evt)
Private Attributes
OutlierPanel highlighted_outlier = null
double zoom_factor = 0.2
int zoom = 1
int width_org
int height_org
int activeXDim = 0
int activeYDim = 1
JPanel layerOutliers
LabelAlgorithmPanel layerAlgorithmTitle
RunOutlierVisualizer m_visualizer = null
MyBaseOutlierDetector m_outlierDetector = null
BufferedImage pointImg
BufferedImage canvasImg
ImgPanel layerCanvas
boolean bAntiAlias = false
int EVENTSIZE = 10
Detailed Description
Definition at line 40 of file StreamOutlierPanel.java.
Constructor & Destructor Documentation
moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel (Color colorAlgorithmTitle)
Definition at line 92 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.LabelAlgorithmPanel.color, moa.gui.visualization.StreamOutlierPanel.getNewLayer(), moa.gui.visualization.StreamOutlierPanel.initComponents(), moa.gui.visualization.StreamOutlierPanel.layerAlgorithmTitle, moa.gui.visualization.StreamOutlierPanel.layerCanvas, and moa.gui.visualization.StreamOutlierPanel.layerOutliers.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
        initComponents();
        layerAlgorithmTitle = new LabelAlgorithmPanel();
        layerAlgorithmTitle.color = colorAlgorithmTitle;
        add(layerAlgorithmTitle);
        layerOutliers = getNewLayer();
        add(layerOutliers);
        layerCanvas = new ImgPanel();
        add(layerCanvas);
        addComponentListener(this);
    }
Member Function Documentation
void moa.gui.visualization.StreamOutlierPanel.applyDrawDecay (float factor, boolean bRedrawPointImg)
Definition at line 247 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), moa.gui.visualization.StreamOutlierPanel.pointImg, and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData().
{
        //System.out.println("applyDrawDecay: factor="+factor);
        // 1)
        int v = Color.GRAY.getRed();
        //System.out.println("applyDrawDecay: v="+v);
        RescaleOp brightenOp = new RescaleOp(1f, (255-v)*factor, null);
        // 2)
        //RescaleOp brightenOp = new RescaleOp(1f + factor, 0, null);
        // 3)
        //RescaleOp brightenOp = new RescaleOp(1f, (255)*factor, null);
        pointImg = brightenOp.filter(pointImg, null);
        if (bRedrawPointImg) {
            ApplyToCanvas(pointImg);
            RedrawPointLayer();
        }
    }
void moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas (BufferedImage img)
Definition at line 149 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.canvasImg.
Referenced by moa.gui.visualization.StreamOutlierPanel.applyDrawDecay(), moa.gui.visualization.StreamOutlierPanel.clearEvents(), moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.StreamOutlierPanel.componentResized(), and moa.gui.visualization.StreamOutlierPanel.drawPoint().
{
        Graphics2D g = (Graphics2D) canvasImg.createGraphics();
        g.drawImage(img, 0, 0, this);
    }
void moa.gui.visualization.StreamOutlierPanel.clearEvents ()
Definition at line 144 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), and moa.gui.visualization.StreamOutlierPanel.pointImg.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawEvents().
{
        ApplyToCanvas(pointImg);
        //RedrawPointLayer();
    }
void moa.gui.visualization.StreamOutlierPanel.clearPoints ()
Definition at line 133 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), moa.gui.visualization.StreamOutlierPanel.pointImg, and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
Referenced by moa.gui.visualization.RunOutlierVisualizer._redraw(), moa.gui.visualization.RunOutlierVisualizer._redrawOnResize(), and moa.gui.visualization.RunOutlierVisualizer.drawPoints().
{
        Graphics2D imageGraphics = (Graphics2D) pointImg.createGraphics();
        imageGraphics.setColor(Color.WHITE);
        imageGraphics.setPaint(Color.WHITE);
        imageGraphics.fill(new Rectangle2D.Double(0, 0, getWidth(), getHeight()));
        ApplyToCanvas(pointImg);
        RedrawPointLayer();
    }
void moa.gui.visualization.StreamOutlierPanel.componentHidden (ComponentEvent e)
Definition at line 427 of file StreamOutlierPanel.java.
{
    }
void moa.gui.visualization.StreamOutlierPanel.componentMoved (ComponentEvent e)
Definition at line 431 of file StreamOutlierPanel.java.
{
    }
void moa.gui.visualization.StreamOutlierPanel.componentResized (ComponentEvent e)
Definition at line 435 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), moa.gui.visualization.StreamOutlierPanel.canvasImg, moa.gui.visualization.StreamOutlierPanel.layerAlgorithmTitle, moa.gui.visualization.StreamOutlierPanel.layerCanvas, moa.gui.visualization.StreamOutlierPanel.layerOutliers, moa.gui.visualization.StreamOutlierPanel.m_visualizer, moa.gui.visualization.StreamOutlierPanel.pointImg, moa.gui.visualization.RunOutlierVisualizer.redrawOnResize(), and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
{
        //System.out.println("componentResized");
        int heightAlgorithmTitle = 2;
        int size = Math.min(getWidth(), getHeight() - heightAlgorithmTitle);
        layerOutliers.setBounds(0, heightAlgorithmTitle, size, size);
        layerAlgorithmTitle.setBounds(0, 0, getWidth(), heightAlgorithmTitle);
        pointImg = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
        canvasImg = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
        layerCanvas.setBounds(0, heightAlgorithmTitle, size, size);
        Graphics2D imageGraphics = (Graphics2D) pointImg.getGraphics();
        imageGraphics.setColor(Color.white);
        imageGraphics.fillRect(0, 0, getWidth(), getHeight());
        imageGraphics.dispose();
        ApplyToCanvas(pointImg);
        RedrawPointLayer();
        if (m_visualizer != null) {
            m_visualizer.redrawOnResize();
        }
    }
void moa.gui.visualization.StreamOutlierPanel.componentShown (ComponentEvent e)
Definition at line 461 of file StreamOutlierPanel.java.
{
    }
void moa.gui.visualization.StreamOutlierPanel.drawEvent (OutlierEvent outlierEvent, boolean bRedrawPointImg)
Definition at line 221 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.bAntiAlias, moa.gui.visualization.StreamOutlierPanel.canvasImg, moa.gui.visualization.StreamOutlierPanel.EVENTSIZE, moa.gui.visualization.StreamOutlierPanel.getActiveXDim(), moa.gui.visualization.StreamOutlierPanel.getActiveYDim(), moa.gui.visualization.OutlierEvent.outlier, moa.gui.visualization.OutlierEvent.point, and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawEvents().
    {
        Graphics2D imageGraphics = (Graphics2D) canvasImg.createGraphics();
        if (bAntiAlias) {
            imageGraphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
        }
        int size = Math.min(getWidth(), getHeight());
        int x = (int) Math.round(outlierEvent.point.value(getActiveXDim()) * size);
        int y = (int) Math.round(outlierEvent.point.value(getActiveYDim()) * size);
        //System.out.println("drawPoint: size="+size+" x="+x+" y="+y);
        Color c = outlierEvent.outlier ? Color.RED : Color.BLACK;
        imageGraphics.setColor(c);
        int psize = EVENTSIZE;
        int poffset = EVENTSIZE / 2;
        imageGraphics.drawOval(x - poffset, y - poffset, psize, psize);
        if (bRedrawPointImg) {
            RedrawPointLayer();
        }
    }
void moa.gui.visualization.StreamOutlierPanel.drawOutliers (JPanel layer, Vector< Outlier > outliers, Color color) [private]
Definition at line 269 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.m_outlierDetector, and moa.gui.visualization.OutlierPanel.updateLocation().
{
        layer.removeAll();
        for (Outlier outlier : outliers) {
            double[] center = new double[outlier.inst.numValues() - 1]; // last value is the class
            for (int i = 0; i < outlier.inst.numValues() - 1; i++) {
                center[i] = outlier.inst.value(i);
            }
            SphereCluster cluster = new SphereCluster(center, 0);
            OutlierPanel outlierpanel = new OutlierPanel(m_outlierDetector, outlier, cluster, color, this);
            layer.add(outlierpanel);
            outlierpanel.updateLocation();
        }
        layer.repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.drawOutliers (Vector< Outlier > outliers, Color color)
Definition at line 115 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.layerOutliers.
{
        drawOutliers(layerOutliers, outliers, color);
    }
void moa.gui.visualization.StreamOutlierPanel.drawPoint (DataPoint point, boolean bShowDecay, boolean bRedrawPointImg)
Definition at line 207 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.drawPoint().
{
        drawPoint(point, bShowDecay, null, true, bRedrawPointImg);
    }
void moa.gui.visualization.StreamOutlierPanel.drawPoint (DataPoint point, boolean bShowDecay, Color c, boolean bFill, boolean bRedrawPointImg) [private]
Definition at line 160 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), moa.gui.visualization.StreamOutlierPanel.bAntiAlias, moa.gui.visualization.StreamOutlierPanel.getActiveXDim(), moa.gui.visualization.StreamOutlierPanel.getActiveYDim(), moa.gui.visualization.StreamOutlierPanel.pointImg, and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
Referenced by moa.gui.visualization.StreamOutlierPanel.drawPoint(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), and moa.gui.visualization.RunOutlierVisualizer.processData().
    {
        Graphics2D imageGraphics = (Graphics2D) pointImg.createGraphics();
        if (bAntiAlias) {
            imageGraphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
        }
        int size = Math.min(getWidth(), getHeight());
        int x = (int) Math.round(point.value(getActiveXDim()) * size);
        int y = (int) Math.round(point.value(getActiveYDim()) * size);
        //System.out.println("drawPoint: size="+size+" x="+x+" y="+y);
        if (c == null) {
            // fixed color of points
            c = Color.GRAY;
            // get a color by class of point
            // Color c = PointPanel.getPointColorbyClass((int)point.classValue(), 10);
        }
        if (bShowDecay) {
            int minValue = 40; // 20
            double w = point.weight();
            int alpha = (int) (255 * w + minValue);
            if (alpha > 255) alpha = 255;
            //System.out.println("alpha="+alpha+"w="+w);
            c = new Color(c.getRed(),c.getGreen(),c.getBlue(),alpha);
        }
        imageGraphics.setColor(c);
        int psize = PointPanel.POINTSIZE;
        int poffset = 2;
        imageGraphics.drawOval(x - poffset, y - poffset, psize, psize);
        if (bFill) imageGraphics.fillOval(x - poffset, y - poffset, psize, psize);
        if (bRedrawPointImg) {
            ApplyToCanvas(pointImg);
            RedrawPointLayer();
        }
    }
void moa.gui.visualization.StreamOutlierPanel.formMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 408 of file StreamOutlierPanel.java.
References moa.gui.visualization.OutlierPanel.highlight(), and moa.gui.visualization.StreamOutlierPanel.highlighted_outlier.
Referenced by moa.gui.visualization.StreamOutlierPanel.initComponents().
                                                                 {//GEN-FIRST:event_formMouseClicked
        if (highlighted_outlier != null){
            highlighted_outlier.highlight(false);
            highlighted_outlier = null;
        }
    }//GEN-LAST:event_formMouseClicked
int moa.gui.visualization.StreamOutlierPanel.getActiveXDim ()
Definition at line 364 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.activeXDim.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawEvent(), moa.gui.visualization.StreamOutlierPanel.drawPoint(), and moa.gui.visualization.OutlierPanel.updateLocation().
{
        return activeXDim;
    }
int moa.gui.visualization.StreamOutlierPanel.getActiveYDim ()
Definition at line 372 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.activeYDim.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawEvent(), moa.gui.visualization.StreamOutlierPanel.drawPoint(), and moa.gui.visualization.OutlierPanel.updateLocation().
{
        return activeYDim;
    }
OutlierPanel moa.gui.visualization.StreamOutlierPanel.getHighlightedOutlierPanel ()
Definition at line 324 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.highlighted_outlier.
{
        return highlighted_outlier;
    }
JPanel moa.gui.visualization.StreamOutlierPanel.getNewLayer () [private]
Definition at line 108 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel().
{
        JPanel layer = new JPanel();
        layer.setOpaque(false);
        layer.setLayout(null);
        return layer;
    }
void moa.gui.visualization.StreamOutlierPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 387 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.formMouseClicked().
Referenced by moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel().
{
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer ()
Definition at line 154 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.canvasImg, moa.gui.visualization.StreamOutlierPanel.layerCanvas, and moa.gui.visualization.StreamOutlierPanel.ImgPanel.setImage().
Referenced by moa.gui.visualization.StreamOutlierPanel.applyDrawDecay(), moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.StreamOutlierPanel.componentResized(), moa.gui.visualization.StreamOutlierPanel.drawEvent(), moa.gui.visualization.StreamOutlierPanel.drawPoint(), moa.gui.visualization.RunOutlierVisualizer.drawPoints(), and moa.gui.visualization.RunOutlierVisualizer.processData().
{
        //System.out.println("print?");
        layerCanvas.setImage(canvasImg);
        layerCanvas.repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.repaintOutliers ()
Definition at line 119 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.layerOutliers.
{
        layerOutliers.repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.screenshot (String filename, boolean svg, boolean png)
Definition at line 287 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.layerOutliers.
{
        if(layerOutliers.getComponentCount() == 0)
            return;
        BufferedImage image = new BufferedImage(getWidth(),getHeight(),BufferedImage.TYPE_INT_RGB);
        if(png){
            synchronized(getTreeLock()){
                Graphics g = image.getGraphics();
                paintAll(g);
                try {
                    ImageIO.write(image, "png", new File(filename+".png"));
                } catch (Exception e) { }
            }
        }
        if(svg){
            try {
                PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(filename+".svg")));
                int width = 500;
                out.write("<?xml version=\"1.0\"?>\n");
                out.write("<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n");
                out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\""+width+"\" height=\""+width+"\">\n");
                if(layerOutliers.isVisible()){
                    for(Component comp :layerOutliers.getComponents()){
                        if(comp instanceof ClusterPanel)
                            out.write(((ClusterPanel)comp).getSVGString(width));
                    }
                }
                out.write("</svg>");
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(StreamPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
void moa.gui.visualization.StreamOutlierPanel.setActiveXDim (int activeXDim)
Definition at line 368 of file StreamOutlierPanel.java.
{
        this.activeXDim = activeXDim;
    }
void moa.gui.visualization.StreamOutlierPanel.setActiveYDim (int activeYDim)
Definition at line 376 of file StreamOutlierPanel.java.
{
        this.activeYDim = activeYDim;
    }
void moa.gui.visualization.StreamOutlierPanel.setHighlightedOutlierPanel (OutlierPanel outlierpanel)
Definition at line 328 of file StreamOutlierPanel.java.
References moa.gui.visualization.OutlierPanel.highlight(), and moa.gui.visualization.StreamOutlierPanel.highlighted_outlier.
Referenced by moa.gui.visualization.OutlierPanel.formMouseClicked(), and moa.gui.visualization.RunOutlierVisualizer.run().
{
        //if (highlighted_outlier == outlierpanel)
        //    return;
        //System.out.println("setHighlightedOutlierPanel");
        // restore previous highlighted outlier
        if (highlighted_outlier != null)
            highlighted_outlier.highlight(false);
        highlighted_outlier = outlierpanel;
        if (highlighted_outlier != null)
            highlighted_outlier.highlight(true);
        repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.setOutlierDetector (MyBaseOutlierDetector outlierDetector)
Definition at line 422 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.m_outlierDetector.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        m_outlierDetector = outlierDetector;
    }
void moa.gui.visualization.StreamOutlierPanel.setOutliersVisibility (boolean visibility)
Definition at line 123 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.layerOutliers.
Referenced by moa.gui.visualization.RunOutlierVisualizer.setOutliersVisibility(), and moa.gui.visualization.RunOutlierVisualizer.showOutliers().
{
        layerOutliers.setVisible(visibility);
        layerOutliers.repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.setPointsVisibility (boolean visibility)
Definition at line 128 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.layerCanvas.
Referenced by moa.gui.visualization.RunOutlierVisualizer.setPointsVisibility().
{
        layerCanvas.setVisible(visibility);
        layerCanvas.repaint();
    }
void moa.gui.visualization.StreamOutlierPanel.setVisualizer (RunOutlierVisualizer v)
Definition at line 418 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.m_visualizer.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        m_visualizer = v;
    }
void moa.gui.visualization.StreamOutlierPanel.setZoom (int x, int y, int zoom_delta, JScrollPane scrollPane)
Definition at line 345 of file StreamOutlierPanel.java.
References moa.gui.visualization.StreamOutlierPanel.height_org, moa.gui.visualization.StreamOutlierPanel.width_org, moa.gui.visualization.StreamOutlierPanel.zoom, and moa.gui.visualization.StreamOutlierPanel.zoom_factor.
{
        if(zoom ==1){
            width_org = getWidth();
            height_org = getHeight();
        }
        zoom+=zoom_delta;
        if(zoom<1) zoom = 1;
        else{
            int size = (int)(Math.min(width_org, height_org)*zoom_factor*zoom);
            setSize(new Dimension(size*zoom, size*zoom));
            setPreferredSize(new Dimension(size*zoom, size*zoom));
            scrollPane.getViewport().setViewPosition(new Point((int)(x*zoom_factor*zoom+x),(int)( y*zoom_factor*zoom+y)));
        }
    }
Member Data Documentation
int moa.gui.visualization.StreamOutlierPanel.activeXDim = 0 [private]
Definition at line 46 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.getActiveXDim().
int moa.gui.visualization.StreamOutlierPanel.activeYDim = 1 [private]
Definition at line 47 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.getActiveYDim().
boolean moa.gui.visualization.StreamOutlierPanel.bAntiAlias = false [private]
Definition at line 59 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawEvent(), and moa.gui.visualization.StreamOutlierPanel.drawPoint().
BufferedImage moa.gui.visualization.StreamOutlierPanel.canvasImg [private]
Definition at line 57 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.ApplyToCanvas(), moa.gui.visualization.StreamOutlierPanel.componentResized(), moa.gui.visualization.StreamOutlierPanel.drawEvent(), and moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer().
int moa.gui.visualization.StreamOutlierPanel.EVENTSIZE = 10 [private]
Definition at line 60 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawEvent().
int moa.gui.visualization.StreamOutlierPanel.height_org [private]
Definition at line 45 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.setZoom().
OutlierPanel moa.gui.visualization.StreamOutlierPanel.highlighted_outlier = null [private]
Definition at line 41 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.formMouseClicked(), moa.gui.visualization.StreamOutlierPanel.getHighlightedOutlierPanel(), and moa.gui.visualization.StreamOutlierPanel.setHighlightedOutlierPanel().
LabelAlgorithmPanel moa.gui.visualization.StreamOutlierPanel.layerAlgorithmTitle [private]
Definition at line 50 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.componentResized(), and moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel().
ImgPanel moa.gui.visualization.StreamOutlierPanel.layerCanvas [private]
Definition at line 58 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.componentResized(), moa.gui.visualization.StreamOutlierPanel.RedrawPointLayer(), moa.gui.visualization.StreamOutlierPanel.setPointsVisibility(), and moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel().
JPanel moa.gui.visualization.StreamOutlierPanel.layerOutliers [private]
Definition at line 49 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.componentResized(), moa.gui.visualization.StreamOutlierPanel.drawOutliers(), moa.gui.visualization.StreamOutlierPanel.repaintOutliers(), moa.gui.visualization.StreamOutlierPanel.screenshot(), moa.gui.visualization.StreamOutlierPanel.setOutliersVisibility(), and moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel().
MyBaseOutlierDetector moa.gui.visualization.StreamOutlierPanel.m_outlierDetector = null [private]
Definition at line 53 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.drawOutliers(), and moa.gui.visualization.StreamOutlierPanel.setOutlierDetector().
RunOutlierVisualizer moa.gui.visualization.StreamOutlierPanel.m_visualizer = null [private]
Definition at line 52 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.componentResized(), and moa.gui.visualization.StreamOutlierPanel.setVisualizer().
BufferedImage moa.gui.visualization.StreamOutlierPanel.pointImg [private]
Definition at line 56 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.applyDrawDecay(), moa.gui.visualization.StreamOutlierPanel.clearEvents(), moa.gui.visualization.StreamOutlierPanel.clearPoints(), moa.gui.visualization.StreamOutlierPanel.componentResized(), and moa.gui.visualization.StreamOutlierPanel.drawPoint().
int moa.gui.visualization.StreamOutlierPanel.width_org [private]
Definition at line 44 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.setZoom().
int moa.gui.visualization.StreamOutlierPanel.zoom = 1 [private]
Definition at line 43 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.setZoom().
double moa.gui.visualization.StreamOutlierPanel.zoom_factor = 0.2 [private]
Definition at line 42 of file StreamOutlierPanel.java.
Referenced by moa.gui.visualization.StreamOutlierPanel.setZoom().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/StreamOutlierPanel.java