MOA: moa.tasks.EvaluatePrequential Class Reference
moa.tasks.EvaluatePrequential Class Reference
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
ClassOption evaluatorOption
IntOption instanceLimitOption
IntOption timeLimitOption
IntOption sampleFrequencyOption
IntOption memCheckFrequencyOption
FileOption dumpFileOption
FileOption outputPredictionFileOption
IntOption widthOption
FloatOption alphaOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 52 of file EvaluatePrequential.java.
Member Function Documentation
Object moa.tasks.EvaluatePrequential.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 111 of file EvaluatePrequential.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.tasks.EvaluatePrequential.alphaOption, moa.AbstractMOAObject.copy(), moa.tasks.EvaluatePrequential.dumpFileOption, moa.evaluation.LearningCurve.entryToString(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluatePrequential.evaluatorOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.EvaluatePrequential.instanceLimitOption, moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.EvaluatePrequential.learnerOption, moa.MOAObject.measureByteSize(), moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.tasks.EvaluatePrequential.outputPredictionFileOption, moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluatePrequential.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.EvaluatePrequential.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluatePrequential.timeLimitOption, moa.classifiers.Classifier.trainOnInstance(), and moa.tasks.EvaluatePrequential.widthOption.
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        LearningCurve learningCurve = new LearningCurve(
                "learning evaluation instances");
        //New for prequential methods
        if (evaluator instanceof WindowClassificationPerformanceEvaluator) {
            //((WindowClassificationPerformanceEvaluator) evaluator).setWindowWidth(widthOption.getValue());
            if (widthOption.getValue() != 1000) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (WindowClassificationPerformanceEvaluator -w " + widthOption.getValue() + ")");
                 return learningCurve;
            }
        }
        if (evaluator instanceof EWMAClassificationPerformanceEvaluator) {
            //((EWMAClassificationPerformanceEvaluator) evaluator).setalpha(alphaOption.getValue());
            if (alphaOption.getValue() != .01) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (EWMAClassificationPerformanceEvaluator -a " + alphaOption.getValue() + ")");
                return learningCurve;
            }
        }
        if (evaluator instanceof FadingFactorClassificationPerformanceEvaluator) {
            //((FadingFactorClassificationPerformanceEvaluator) evaluator).setalpha(alphaOption.getValue());
            if (alphaOption.getValue() != .01) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (FadingFactorClassificationPerformanceEvaluator -a " + alphaOption.getValue() + ")");
                return learningCurve;
            }
        }
        //End New for prequential methods
        learner.setModelContext(stream.getHeader());
        int maxInstances = this.instanceLimitOption.getValue();
        long instancesProcessed = 0;
        int maxSeconds = this.timeLimitOption.getValue();
        int secondsElapsed = 0;
        monitor.setCurrentActivity("Evaluating learner...", -1.0);
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        //File for output predictions
        File outputPredictionFile = this.outputPredictionFileOption.getFile();
        PrintStream outputPredictionResultStream = null;
        if (outputPredictionFile != null) {
            try {
                if (outputPredictionFile.exists()) {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile, true), true);
                } else {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open prediction result file: " + outputPredictionFile, ex);
            }
        }
        boolean firstDump = true;
        boolean preciseCPUTiming = TimingUtils.enablePreciseTiming();
        long evaluateStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        long lastEvaluateStartTime = evaluateStartTime;
        double RAMHours = 0.0;
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))
                && ((maxSeconds < 0) || (secondsElapsed < maxSeconds))) {
            Instance trainInst = stream.nextInstance();
            Instance testInst = (Instance) trainInst.copy();
            if (testInst.classIsMissing() == false){
                // Added for semisupervised setting: test only if we have the label
                double[] prediction = learner.getVotesForInstance(testInst);
                // Output prediction
                if (outputPredictionFile != null) {
                    outputPredictionResultStream.println(Utils.maxIndex(prediction) + "," + testInst.classValue());
                }
                evaluator.addResult(testInst, prediction);
            }
            learner.trainOnInstance(trainInst);
            instancesProcessed++;
            if (instancesProcessed % this.sampleFrequencyOption.getValue() == 0
                    || stream.hasMoreInstances() == false) {
                long evaluateTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
                double time = TimingUtils.nanoTimeToSeconds(evaluateTime - evaluateStartTime);
                double timeIncrement = TimingUtils.nanoTimeToSeconds(evaluateTime - lastEvaluateStartTime);
                double RAMHoursIncrement = learner.measureByteSize() / (1024.0 * 1024.0 * 1024.0); //GBs
                RAMHoursIncrement *= (timeIncrement / 3600.0); //Hours
                RAMHours += RAMHoursIncrement;
                lastEvaluateStartTime = evaluateTime;
                learningCurve.insertEntry(new LearningEvaluation(
                        new Measurement[]{
                            new Measurement(
                            "learning evaluation instances",
                            instancesProcessed),
                            new Measurement(
                            "evaluation time ("
                            + (preciseCPUTiming ? "cpu "
                            : "") + "seconds)",
                            time),
                            new Measurement(
                            "model cost (RAM-Hours)",
                            RAMHours)
                        },
                        evaluator, learner));
                if (immediateResultStream != null) {
                    if (firstDump) {
                        immediateResultStream.println(learningCurve.headerToString());
                        firstDump = false;
                    }
                    immediateResultStream.println(learningCurve.entryToString(learningCurve.numEntries() - 1));
                    immediateResultStream.flush();
                }
            }
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) instancesProcessed
                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.copy());
                }
                secondsElapsed = (int) TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                        - evaluateStartTime);
            }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
        if (outputPredictionResultStream != null) {
            outputPredictionResultStream.close();
        }
        return learningCurve;
    }
String moa.tasks.EvaluatePrequential.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 55 of file EvaluatePrequential.java.
{
        return "Evaluates a classifier on a stream by testing then training with each example in sequence.";
    }
Class<?> moa.tasks.EvaluatePrequential.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 106 of file EvaluatePrequential.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FloatOption moa.tasks.EvaluatePrequential.alphaOption
Initial value:
 new FloatOption("alpha",
            'a', "Fading factor or exponential smoothing factor", .01)
Definition at line 101 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
FileOption moa.tasks.EvaluatePrequential.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv results to.", null, "csv", true)
Definition at line 91 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
ClassOption moa.tasks.EvaluatePrequential.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "WindowClassificationPerformanceEvaluator")
Definition at line 68 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
IntOption moa.tasks.EvaluatePrequential.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            100000000, -1, Integer.MAX_VALUE)
Definition at line 73 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
ClassOption moa.tasks.EvaluatePrequential.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Definition at line 61 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
IntOption moa.tasks.EvaluatePrequential.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Definition at line 86 of file EvaluatePrequential.java.
FileOption moa.tasks.EvaluatePrequential.outputPredictionFileOption
Initial value:
 new FileOption("outputPredictionFile", 'o',
            "File to append output predictions to.", null, "pred", true)
Definition at line 94 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
IntOption moa.tasks.EvaluatePrequential.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            100000, 0, Integer.MAX_VALUE)
Definition at line 81 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
final long moa.tasks.EvaluatePrequential.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 59 of file EvaluatePrequential.java.
ClassOption moa.tasks.EvaluatePrequential.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 64 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
IntOption moa.tasks.EvaluatePrequential.timeLimitOption
Initial value:
 new IntOption("timeLimit", 't',
            "Maximum number of seconds to test/train for (-1 = no limit).", -1,
            -1, Integer.MAX_VALUE)
Definition at line 77 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
IntOption moa.tasks.EvaluatePrequential.widthOption
Initial value:
 new IntOption("width",
            'w', "Size of Window", 1000)
Definition at line 98 of file EvaluatePrequential.java.
Referenced by moa.tasks.EvaluatePrequential.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluatePrequential.java