MOA: moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap Class Reference
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap Class Reference
A class for a heap to store the nearest k neighbours to an instance.
Public Member Functions
MyHeap (int maxSize)
constructor.
int size ()
returns the size of the heap.
MyHeapElement peek ()
peeks at the first element.
MyHeapElement get () throws Exception
returns the first element and removes it from the heap.
void put (int i, double d) throws Exception
adds the value to the heap.
void putBySubstitute (int i, double d) throws Exception
Puts an element by substituting it in place of the top most element.
int noOfKthNearest ()
returns the number of k nearest.
void putKthNearest (int i, double d)
Stores kth nearest elements (if there are more than one).
MyHeapElement getKthNearest ()
returns the kth nearest element or null if none there.
int totalSize ()
returns the total size.
Protected Member Functions
void upheap ()
performs upheap operation for the heap to maintian its properties.
void downheap ()
performs downheap operation for the heap to maintian its properties.
Package Attributes
MyHeapElement m_heap [] = null
the heap.
MyHeapElement m_KthNearest [] = null
the kth nearest ones.
int m_KthNearestSize = 0
The number of kth nearest elements.
int initSize = 10
the initial size of the heap.
Detailed Description
A class for a heap to store the nearest k neighbours to an instance.
The heap also takes care of cases where multiple neighbours are the same distance away. i.e. the minimum size of the heap is k.
Author:
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 46 of file NearestNeighbourSearch.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.MyHeap (int maxSize)
constructor.
Parameters:
maxSize the maximum size of the heap
Definition at line 56 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
{
      if((maxSize%2)==0)
        maxSize++;
      m_heap = new MyHeapElement[maxSize+1];
      m_heap[0] = new MyHeapElement(0, 0);
    }
Member Function Documentation
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.downheap () [protected]
performs downheap operation for the heap to maintian its properties.
Definition at line 211 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.get().
{
      int i = 1;
      MyHeapElement temp;
      while( ( (2*i) <= m_heap[0].index &&
      m_heap[i].distance < m_heap[2*i].distance )
      ||
      ( (2*i+1) <= m_heap[0].index &&
      m_heap[i].distance < m_heap[2*i+1].distance) ) {
        if((2*i+1)<=m_heap[0].index) {
          if(m_heap[2*i].distance>m_heap[2*i+1].distance) {
            temp = m_heap[i];
            m_heap[i] = m_heap[2*i];
            i = 2*i;
            m_heap[i] = temp;
          }
          else {
            temp = m_heap[i];
            m_heap[i] = m_heap[2*i+1];
            i = 2*i+1;
            m_heap[i] = temp;
          }
        }
        else {
          temp = m_heap[i];
          m_heap[i] = m_heap[2*i];
          i = 2*i;
          m_heap[i] = temp;
        }
      }
    }
MyHeapElement moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.get () throws Exception
returns the first element and removes it from the heap.
Returns:
the first element
Exceptions:
Exception if no elements in heap
Definition at line 88 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.downheap(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
{
      if(m_heap[0].index==0)
        throw new Exception("No elements present in the heap");
      MyHeapElement r = m_heap[1];
      m_heap[1] = m_heap[m_heap[0].index];
      m_heap[0].index--;
      downheap();
      return r;
    }
MyHeapElement moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.getKthNearest ()
returns the kth nearest element or null if none there.
Returns:
the kth nearest element
Definition at line 185 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearest, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearestSize.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
{
      if(m_KthNearestSize==0)
        return null;
      m_KthNearestSize--;
      return m_KthNearest[m_KthNearestSize];
    }
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.noOfKthNearest ()
returns the number of k nearest.
Returns:
the number of k nearest
See also:
m_KthNearestSize
Definition at line 157 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearestSize.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.totalSize().
{
      return m_KthNearestSize;
    }
MyHeapElement moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.peek ()
peeks at the first element.
Returns:
the first element
Definition at line 78 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours().
{
      return m_heap[1];
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.put (int i, double d) throws Exception
adds the value to the heap.
Parameters:
i the index
d the distance
Exceptions:
Exception if the heap gets too large
Definition at line 105 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.upheap().
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute().
{
      if((m_heap[0].index+1)>(m_heap.length-1))
        throw new Exception("the number of elements cannot exceed the "+
        "initially set maximum limit");
      m_heap[0].index++;
      m_heap[m_heap[0].index] = new MyHeapElement(i, d);
      upheap();
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute (int i, double d) throws Exception
Puts an element by substituting it in place of the top most element.
Parameters:
i the index
d the distance
Exceptions:
Exception if distance is smaller than that of the head element
Definition at line 123 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.distance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.initSize, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearest, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearestSize, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.put(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest().
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours().
{
      MyHeapElement head = get();
      put(i, d);
      //      System.out.println("previous: "+head.distance+" current: "+m_heap[1].distance);
      if(head.distance == m_heap[1].distance) { //Utils.eq(head.distance, m_heap[1].distance)) {
        putKthNearest(head.index, head.distance);
      }
      else if(head.distance > m_heap[1].distance) { //Utils.gr(head.distance, m_heap[1].distance)) {
        m_KthNearest = null;
        m_KthNearestSize = 0;
        initSize = 10;
      }
      else if(head.distance < m_heap[1].distance) {
        throw new Exception("The substituted element is smaller than the "+
        "head element. put() should have been called "+
        "in place of putBySubstitute()");
      }
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest (int i, double d)
Stores kth nearest elements (if there are more than one).
Parameters:
i the index
d the distance
Definition at line 167 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.initSize, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearest, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearestSize.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute().
{
      if(m_KthNearest==null) {
        m_KthNearest = new MyHeapElement[initSize];
      }
      if(m_KthNearestSize>=m_KthNearest.length) {
        initSize += initSize;
        MyHeapElement temp[] = new MyHeapElement[initSize];
        System.arraycopy(m_KthNearest, 0, temp, 0, m_KthNearest.length);
        m_KthNearest = temp;
      }
      m_KthNearest[m_KthNearestSize++] = new MyHeapElement(i, d);
    }
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.size ()
returns the size of the heap.
Returns:
the size
Definition at line 69 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.totalSize().
                      {
      return m_heap[0].index;
    }
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.totalSize ()
returns the total size.
Returns:
the total size
Definition at line 247 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.noOfKthNearest(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.size().
{
      return size()+noOfKthNearest();
    }
void moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.upheap () [protected]
performs upheap operation for the heap to maintian its properties.
Definition at line 196 of file NearestNeighbourSearch.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.put().
{
      int i = m_heap[0].index;
      MyHeapElement temp;
      while( i > 1  && m_heap[i].distance>m_heap[i/2].distance) {
        temp = m_heap[i];
        m_heap[i] = m_heap[i/2];
        i = i/2;
        m_heap[i] = temp; //this is i/2 done here to avoid another division.
      }
    }
Member Data Documentation
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.initSize = 10 [package]
the initial size of the heap.
Definition at line 149 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest().
MyHeapElement moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_heap[] = null [package]
the heap.
Definition at line 49 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.downheap(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.get(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.MyHeap(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.peek(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.put(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.size(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.upheap().
MyHeapElement moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearest[] = null [package]
the kth nearest ones.
Definition at line 143 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.getKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest().
int moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.m_KthNearestSize = 0 [package]
The number of kth nearest elements.
Definition at line 146 of file NearestNeighbourSearch.java.
Referenced by moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.getKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.noOfKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putBySubstitute(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.putKthNearest().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/NearestNeighbourSearch.java