MOA: moa.core.StringUtils Class Reference
moa.core.StringUtils Class Reference
Class implementing some string utility methods.
Static Public Member Functions
static String doubleToString (double value, int fractionDigits)
static String doubleToString (double value, int minFractionDigits, int maxFractionDigits)
static void appendNewline (StringBuilder out)
static void appendIndent (StringBuilder out, int indent)
static void appendIndented (StringBuilder out, int indent, String s)
static void appendNewlineIndented (StringBuilder out, int indent, String s)
static String secondsToDHMSString (double seconds)
Static Public Attributes
static final String newline = System.getProperty("line.separator")
Detailed Description
Class implementing some string utility methods.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 30 of file StringUtils.java.
Member Function Documentation
static void moa.core.StringUtils.appendIndent (StringBuilder out, int indent) [static]
Definition at line 50 of file StringUtils.java.
Referenced by moa.core.StringUtils.appendIndented().
{
        for (int i = 0; i < indent; i++) {
            out.append(' ');
        }
    }
static void moa.core.StringUtils.appendIndented (StringBuilder out, int indent, String s) [static]
Definition at line 56 of file StringUtils.java.
References moa.core.StringUtils.appendIndent().
Referenced by moa.core.StringUtils.appendNewlineIndented().
{
        appendIndent(out, indent);
        out.append(s);
    }
static void moa.core.StringUtils.appendNewline (StringBuilder out) [static]
Definition at line 46 of file StringUtils.java.
References moa.core.StringUtils.newline.
Referenced by moa.core.StringUtils.appendNewlineIndented().
{
        out.append(newline);
    }
static void moa.core.StringUtils.appendNewlineIndented (StringBuilder out, int indent, String s) [static]
Definition at line 61 of file StringUtils.java.
References moa.core.StringUtils.appendIndented(), and moa.core.StringUtils.appendNewline().
                      {
        appendNewline(out);
        appendIndented(out, indent, s);
    }
static String moa.core.StringUtils.doubleToString (double value, int minFractionDigits, int maxFractionDigits) [static]
Definition at line 38 of file StringUtils.java.
{
        DecimalFormat numberFormat = new DecimalFormat();
        numberFormat.setMinimumFractionDigits(minFractionDigits);
        numberFormat.setMaximumFractionDigits(maxFractionDigits);
        return numberFormat.format(value);
    }
static String moa.core.StringUtils.doubleToString (double value, int fractionDigits) [static]
Definition at line 34 of file StringUtils.java.
Referenced by moa.core.StringUtils.secondsToDHMSString().
{
        return doubleToString(value, 0, fractionDigits);
    }
static String moa.core.StringUtils.secondsToDHMSString (double seconds) [static]
Definition at line 67 of file StringUtils.java.
References moa.core.StringUtils.doubleToString().
{
        if (seconds < 60) {
            return doubleToString(seconds, 2, 2) + 's';
        }
        long secs = (int) (seconds);
        long mins = secs / 60;
        long hours = mins / 60;
        long days = hours / 24;
        secs %= 60;
        mins %= 60;
        hours %= 24;
        StringBuilder result = new StringBuilder();
        if (days > 0) {
            result.append(days);
            result.append('d');
        }
        if ((hours > 0) || (days > 0)) {
            result.append(hours);
            result.append('h');
        }
        if ((hours > 0) || (days > 0) || (mins > 0)) {
            result.append(mins);
            result.append('m');
        }
        result.append(secs);
        result.append('s');
        return result.toString();
    }
Member Data Documentation
final String moa.core.StringUtils.newline = System.getProperty("line.separator") [static]
Definition at line 32 of file StringUtils.java.
Referenced by moa.core.StringUtils.appendNewline().
The documentation for this class was generated from the following file:
main/java/moa/core/StringUtils.java