MOA: moa.gui.WEKAClassOptionEditComponent Class Reference
moa.gui.WEKAClassOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a WEKA class option.
Public Member Functions
WEKAClassOptionEditComponent (WEKAClassOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void editObject ()
Protected Attributes
WEKAClassOption editedOption
JTextField textField = new JTextField()
JButton editButton = new JButton("Edit")
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a WEKA class option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
FracPete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 46 of file WEKAClassOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent (WEKAClassOption option)
Definition at line 58 of file WEKAClassOptionEditComponent.java.
References moa.gui.WEKAClassOptionEditComponent.editButton, moa.gui.WEKAClassOptionEditComponent.editedOption, moa.gui.WEKAClassOptionEditComponent.editObject(), moa.options.WEKAClassOption.getValueAsCLIString(), moa.gui.WEKAClassOptionEditComponent.setEditState(), and moa.gui.WEKAClassOptionEditComponent.textField.
{
        this.editedOption = option;
        this.textField.setEditable(false);
        setLayout(new BorderLayout());
        add(this.textField, BorderLayout.CENTER);
        add(this.editButton, BorderLayout.EAST);
        this.editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                editObject();
            }
        });
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.WEKAClassOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 75 of file WEKAClassOptionEditComponent.java.
References moa.gui.WEKAClassOptionEditComponent.editedOption, moa.options.WEKAClassOption.setValueViaCLIString(), and moa.gui.WEKAClassOptionEditComponent.textField.
{
        this.editedOption.setValueViaCLIString(this.textField.getText());
    }
void moa.gui.WEKAClassOptionEditComponent.editObject ()
Definition at line 89 of file WEKAClassOptionEditComponent.java.
References moa.gui.WEKAClassOptionEditComponent.editedOption, moa.options.AbstractClassOption.getRequiredType(), moa.options.WEKAClassOption.getValueAsCLIString(), and moa.gui.WEKAClassOptionEditComponent.setEditState().
Referenced by moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
{
        final GenericObjectEditor goe = new GenericObjectEditor(true);
        goe.setClassType(editedOption.getRequiredType());
        try {
            String[] options = Utils.splitOptions(editedOption.getValueAsCLIString());
            String classname = options[0];
            options[0] = "";
            Object obj = Class.forName(classname).newInstance();
            if (obj instanceof weka.core.OptionHandler) {
                ((weka.core.OptionHandler) obj).setOptions(options);
            }
            goe.setValue(obj);
            ((GOEPanel) goe.getCustomEditor()).addOkListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Object obj = goe.getValue();
                    String s = obj.getClass().getName();
                    if (obj instanceof weka.core.OptionHandler) {
                        s += " " + Utils.joinOptions(((weka.core.OptionHandler) obj).getOptions());
                    }
                    setEditState(s.trim());
                }
            });
            PropertyDialog dialog;
            if (PropertyDialog.getParentDialog(this) != null) {
                dialog = new PropertyDialog(PropertyDialog.getParentDialog(this), goe);
            } else {
                dialog = new PropertyDialog(PropertyDialog.getParentFrame(this), goe);
            }
            dialog.setModal(true);
            dialog.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
Option moa.gui.WEKAClassOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 80 of file WEKAClassOptionEditComponent.java.
References moa.gui.WEKAClassOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.WEKAClassOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 85 of file WEKAClassOptionEditComponent.java.
References moa.gui.WEKAClassOptionEditComponent.textField.
Referenced by moa.gui.WEKAClassOptionEditComponent.editObject(), and moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
{
        this.textField.setText(cliString);
    }
Member Data Documentation
JButton moa.gui.WEKAClassOptionEditComponent.editButton = new JButton("Edit") [protected]
Definition at line 56 of file WEKAClassOptionEditComponent.java.
Referenced by moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
WEKAClassOption moa.gui.WEKAClassOptionEditComponent.editedOption [protected]
Definition at line 52 of file WEKAClassOptionEditComponent.java.
Referenced by moa.gui.WEKAClassOptionEditComponent.applyState(), moa.gui.WEKAClassOptionEditComponent.editObject(), moa.gui.WEKAClassOptionEditComponent.getEditedOption(), and moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
final long moa.gui.WEKAClassOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 50 of file WEKAClassOptionEditComponent.java.
JTextField moa.gui.WEKAClassOptionEditComponent.textField = new JTextField() [protected]
Definition at line 54 of file WEKAClassOptionEditComponent.java.
Referenced by moa.gui.WEKAClassOptionEditComponent.applyState(), moa.gui.WEKAClassOptionEditComponent.setEditState(), and moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
The documentation for this class was generated from the following file:
main/java/moa/gui/WEKAClassOptionEditComponent.java