MOA: moa.streams.generators.AgrawalGenerator Class Reference
moa.streams.generators.AgrawalGenerator Class Reference
Stream generator for Agrawal dataset.
Classes
interface ClassFunction
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
InstancesHeader getHeader ()
Gets the header of this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
boolean isRestartable ()
Gets whether this stream can restart.
Instance nextInstance ()
Gets the next instance from this stream.
void restart ()
Restarts this stream.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
IntOption functionOption
IntOption instanceRandomSeedOption
FloatOption peturbFractionOption
FlagOption balanceClassesOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
double perturbValue (double val, double min, double max)
double perturbValue (double val, double range, double min, double max)
Protected Attributes
InstancesHeader streamHeader
Random instanceRandom
boolean nextClassShouldBeZero
Static Protected Attributes
static ClassFunction[] classificationFunctions
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream generator for Agrawal dataset.
Generator described in paper:
Rakesh Agrawal, Tomasz Imielinksi, and Arun Swami, "Database Mining: A Performance Perspective", IEEE Transactions on Knowledge and Data Engineering, 5(6), December 1993.
Public C source code available at:
http://www.almaden.ibm.com/cs/projects/iis/hdb/Projects/data_mining/datasets/syndata.html
Notes:
The built in functions are based on the paper (page 924), which turn out to be functions pred20 thru pred29 in the public C implementation. Perturbation function works like C implementation rather than description in paper.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 59 of file AgrawalGenerator.java.
Member Function Documentation
long moa.streams.generators.AgrawalGenerator.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implements moa.streams.InstanceStream.
Definition at line 313 of file AgrawalGenerator.java.
{
        return -1;
    }
void moa.streams.generators.AgrawalGenerator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 418 of file AgrawalGenerator.java.
{
        // TODO Auto-generated method stub
    }
InstancesHeader moa.streams.generators.AgrawalGenerator.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implements moa.streams.InstanceStream.
Definition at line 318 of file AgrawalGenerator.java.
References moa.streams.generators.AgrawalGenerator.streamHeader.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance().
{
        return this.streamHeader;
    }
String moa.streams.generators.AgrawalGenerator.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 63 of file AgrawalGenerator.java.
{
        return "Generates one of ten different pre-defined loan functions.";
    }
boolean moa.streams.generators.AgrawalGenerator.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implements moa.streams.InstanceStream.
Definition at line 323 of file AgrawalGenerator.java.
{
        return true;
    }
boolean moa.streams.generators.AgrawalGenerator.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implements moa.streams.InstanceStream.
Definition at line 328 of file AgrawalGenerator.java.
{
        return true;
    }
Instance moa.streams.generators.AgrawalGenerator.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implements moa.streams.InstanceStream.
Definition at line 333 of file AgrawalGenerator.java.
References moa.streams.generators.AgrawalGenerator.balanceClassesOption, moa.streams.generators.AgrawalGenerator.classificationFunctions, moa.streams.generators.AgrawalGenerator.ClassFunction.determineClass(), moa.streams.generators.AgrawalGenerator.functionOption, moa.streams.generators.AgrawalGenerator.getHeader(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.generators.AgrawalGenerator.instanceRandom, moa.options.FlagOption.isSet, moa.streams.generators.AgrawalGenerator.nextClassShouldBeZero, moa.streams.generators.AgrawalGenerator.perturbValue(), and moa.streams.generators.AgrawalGenerator.peturbFractionOption.
{
        double salary = 0, commission = 0, hvalue = 0, loan = 0;
        int age = 0, elevel = 0, car = 0, zipcode = 0, hyears = 0, group = 0;
        boolean desiredClassFound = false;
        while (!desiredClassFound) {
            // generate attributes
            salary = 20000.0 + 130000.0 * this.instanceRandom.nextDouble();
            commission = (salary >= 75000.0) ? 0
                    : (10000.0 + 65000.0 * this.instanceRandom.nextDouble());
            // true to c implementation:
            // if (instanceRandom.nextDouble() < 0.5 && salary < 75000.0)
            // commission = 10000.0 + 65000.0 * instanceRandom.nextDouble();
            age = 20 + this.instanceRandom.nextInt(61);
            elevel = this.instanceRandom.nextInt(5);
            car = this.instanceRandom.nextInt(20);
            zipcode = this.instanceRandom.nextInt(9);
            hvalue = (9.0 - zipcode) * 100000.0
                    * (0.5 + this.instanceRandom.nextDouble());
            hyears = 1 + this.instanceRandom.nextInt(30);
            loan = this.instanceRandom.nextDouble() * 500000.0;
            // determine class
            group = classificationFunctions[this.functionOption.getValue() - 1].determineClass(salary, commission, age, elevel, car,
                    zipcode, hvalue, hyears, loan);
            if (!this.balanceClassesOption.isSet()) {
                desiredClassFound = true;
            } else {
                // balance the classes
                if ((this.nextClassShouldBeZero && (group == 0))
                        || (!this.nextClassShouldBeZero && (group == 1))) {
                    desiredClassFound = true;
                    this.nextClassShouldBeZero = !this.nextClassShouldBeZero;
                } // else keep searching
            }
        }
        // perturb values
        if (this.peturbFractionOption.getValue() > 0.0) {
            salary = perturbValue(salary, 20000, 150000);
            if (commission > 0) {
                commission = perturbValue(commission, 10000, 75000);
            }
            age = (int) Math.round(perturbValue(age, 20, 80));
            hvalue = perturbValue(hvalue, (9.0 - zipcode) * 100000.0, 0, 135000);
            hyears = (int) Math.round(perturbValue(hyears, 1, 30));
            loan = perturbValue(loan, 0, 500000);
        }
        // construct instance
        InstancesHeader header = getHeader();
        Instance inst = new DenseInstance(header.numAttributes());
        inst.setValue(0, salary);
        inst.setValue(1, commission);
        inst.setValue(2, age);
        inst.setValue(3, elevel);
        inst.setValue(4, car);
        inst.setValue(5, zipcode);
        inst.setValue(6, hvalue);
        inst.setValue(7, hyears);
        inst.setValue(8, loan);
        inst.setDataset(header);
        inst.setClassValue(group);
        return inst;
    }
double moa.streams.generators.AgrawalGenerator.perturbValue (double val, double range, double min, double max) [protected]
Definition at line 399 of file AgrawalGenerator.java.
References moa.options.FloatOption.getValue(), moa.streams.generators.AgrawalGenerator.instanceRandom, and moa.streams.generators.AgrawalGenerator.peturbFractionOption.
{
        val += range * (2.0 * (this.instanceRandom.nextDouble() - 0.5))
                * this.peturbFractionOption.getValue();
        if (val < min) {
            val = min;
        } else if (val > max) {
            val = max;
        }
        return val;
    }
double moa.streams.generators.AgrawalGenerator.perturbValue (double val, double min, double max) [protected]
Definition at line 395 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance().
{
        return perturbValue(val, max - min, min, max);
    }
void moa.streams.generators.AgrawalGenerator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 277 of file AgrawalGenerator.java.
References moa.options.AbstractOptionHandler.getCLICreationString(), moa.streams.generators.AgrawalGenerator.restart(), and moa.streams.generators.AgrawalGenerator.streamHeader.
{
        // generate header
        FastVector attributes = new FastVector();
        attributes.addElement(new Attribute("salary"));
        attributes.addElement(new Attribute("commission"));
        attributes.addElement(new Attribute("age"));
        FastVector elevelLabels = new FastVector();
        for (int i = 0; i < 5; i++) {
            elevelLabels.addElement("level" + i);
        }
        attributes.addElement(new Attribute("elevel", elevelLabels));
        FastVector carLabels = new FastVector();
        for (int i = 0; i < 20; i++) {
            carLabels.addElement("car" + (i + 1));
        }
        attributes.addElement(new Attribute("car", carLabels));
        FastVector zipCodeLabels = new FastVector();
        for (int i = 0; i < 9; i++) {
            zipCodeLabels.addElement("zipcode" + (i + 1));
        }
        attributes.addElement(new Attribute("zipcode", zipCodeLabels));
        attributes.addElement(new Attribute("hvalue"));
        attributes.addElement(new Attribute("hyears"));
        attributes.addElement(new Attribute("loan"));
        FastVector classLabels = new FastVector();
        classLabels.addElement("groupA");
        classLabels.addElement("groupB");
        attributes.addElement(new Attribute("class", classLabels));
        this.streamHeader = new InstancesHeader(new Instances(
                getCLICreationString(InstanceStream.class), attributes, 0));
        this.streamHeader.setClassIndex(this.streamHeader.numAttributes() - 1);
        restart();
    }
void moa.streams.generators.AgrawalGenerator.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implements moa.streams.InstanceStream.
Definition at line 412 of file AgrawalGenerator.java.
References moa.options.IntOption.getValue(), moa.streams.generators.AgrawalGenerator.instanceRandom, moa.streams.generators.AgrawalGenerator.instanceRandomSeedOption, and moa.streams.generators.AgrawalGenerator.nextClassShouldBeZero.
Referenced by moa.streams.generators.AgrawalGenerator.prepareForUseImpl().
{
        this.instanceRandom = new Random(this.instanceRandomSeedOption.getValue());
        this.nextClassShouldBeZero = false;
    }
Member Data Documentation
FlagOption moa.streams.generators.AgrawalGenerator.balanceClassesOption
Initial value:
 new FlagOption("balanceClasses",
            'b', "Balance the number of instances of each class.")
Definition at line 82 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance().
ClassFunction [] moa.streams.generators.AgrawalGenerator.classificationFunctions [static, protected]
Definition at line 92 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance().
IntOption moa.streams.generators.AgrawalGenerator.functionOption
Initial value:
 new IntOption("function", 'f',
            "Classification function used, as defined in the original paper.",
            1, 1, 10)
Definition at line 69 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance().
Random moa.streams.generators.AgrawalGenerator.instanceRandom [protected]
Definition at line 272 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance(), moa.streams.generators.AgrawalGenerator.perturbValue(), and moa.streams.generators.AgrawalGenerator.restart().
IntOption moa.streams.generators.AgrawalGenerator.instanceRandomSeedOption
Initial value:
 new IntOption(
            "instanceRandomSeed", 'i',
            "Seed for random generation of instances.", 1)
Definition at line 73 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.restart().
boolean moa.streams.generators.AgrawalGenerator.nextClassShouldBeZero [protected]
Definition at line 274 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance(), and moa.streams.generators.AgrawalGenerator.restart().
FloatOption moa.streams.generators.AgrawalGenerator.peturbFractionOption
Initial value:
 new FloatOption("peturbFraction",
            'p',
            "The amount of peturbation (noise) introduced to numeric values.",
            0.05, 0.0, 1.0)
Definition at line 77 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.nextInstance(), and moa.streams.generators.AgrawalGenerator.perturbValue().
final long moa.streams.generators.AgrawalGenerator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 67 of file AgrawalGenerator.java.
InstancesHeader moa.streams.generators.AgrawalGenerator.streamHeader [protected]
Definition at line 270 of file AgrawalGenerator.java.
Referenced by moa.streams.generators.AgrawalGenerator.getHeader(), and moa.streams.generators.AgrawalGenerator.prepareForUseImpl().
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/AgrawalGenerator.java