MOA: moa.classifiers.lazy.neighboursearch.KDTree Class Reference
moa.classifiers.lazy.neighboursearch.KDTree Class Reference
Class implementing the KDTree search algorithm for nearest neighbour search.
Public Member Functions
KDTree ()
Creates a new instance of KDTree.
KDTree (Instances insts)
Creates a new instance of KDTree.
Instances kNearestNeighbours (Instance target, int k) throws Exception
Returns the k nearest neighbours of the supplied instance.
Instance nearestNeighbour (Instance target) throws Exception
Returns the nearest neighbour of the supplied target instance.
double[] getDistances () throws Exception
Returns the distances to the kNearest or 1 nearest neighbour currently found with either the kNearestNeighbours or the nearestNeighbour method.
void setInstances (Instances instances) throws Exception
Builds the KDTree on the given set of instances.
void update (Instance instance) throws Exception
Adds one instance to the KDTree.
void addInstanceInfo (Instance instance)
Adds one instance to KDTree loosly.
double measureTreeSize ()
Returns the size of the tree.
double measureNumLeaves ()
Returns the number of leaves.
double measureMaxDepth ()
Returns the depth of the tree.
Enumeration enumerateMeasures ()
Returns an enumeration of the additional measure names.
double getMeasure (String additionalMeasureName)
Returns the value of the named measure.
void setMeasurePerformance (boolean measurePerformance)
Sets whether to calculate the performance statistics or not.
void centerInstances (Instances centers, int[] assignments, double pc) throws Exception
Assigns instances to centers using KDTree.
void assignSubToCenters (KDTreeNode node, Instances centers, int[] centList, int[] assignments) throws Exception
Assigns instances of this node to center.
String minBoxRelWidthTipText ()
the GET and SET - functions ===============================================
void setMinBoxRelWidth (double i)
Sets the minimum relative box width.
double getMinBoxRelWidth ()
Gets the minimum relative box width.
String maxInstInLeafTipText ()
Tip text for this property.
void setMaxInstInLeaf (int i)
Sets the maximum number of instances in a leaf.
int getMaxInstInLeaf ()
Get the maximum number of instances in a leaf.
String normalizeNodeWidthTipText ()
Tip text for this property.
void setNormalizeNodeWidth (boolean n)
Sets the flag for normalizing the widths of a KDTree Node by the width of the dimension in the universe.
boolean getNormalizeNodeWidth ()
Gets the normalize flag.
DistanceFunction getDistanceFunction ()
returns the distance function currently in use.
void setDistanceFunction (DistanceFunction df) throws Exception
sets the distance function to use for nearest neighbour search.
String nodeSplitterTipText ()
Returns the tip text for this property.
KDTreeNodeSplitter getNodeSplitter ()
Returns the splitting method currently in use to split the nodes of the KDTree.
void setNodeSplitter (KDTreeNodeSplitter splitter)
Sets the splitting method to use to split the nodes of the KDTree.
String globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Static Public Attributes
static final int MIN = EuclideanDistance.R_MIN
The index of MIN value in attributes' range array.
static final int MAX = EuclideanDistance.R_MAX
The index of MAX value in attributes' range array.
static final int WIDTH = EuclideanDistance.R_WIDTH
The index of WIDTH (MAX-MIN) value in attributes' range array.
Protected Member Functions
void buildKDTree (Instances instances) throws Exception
Builds the KDTree on the supplied set of instances/points.
void splitNodes (KDTreeNode node, double[][] universe, int depth) throws Exception
Recursively splits nodes of a tree starting from the supplied node.
void findNearestNeighbours (Instance target, KDTreeNode node, int k, MyHeap heap, double distanceToParents) throws Exception
Returns (in the supplied heap object) the k nearest neighbours of the given instance starting from the give tree node.
void addInstanceToTree (Instance inst, KDTreeNode node) throws Exception
Recursively adds an instance to the tree starting from the supplied KDTreeNode.
void afterAddInstance (KDTreeNode node)
Corrects the start and end indices of a KDTreeNode after an instance is added to the tree.
void checkMissing (Instances instances) throws Exception
Checks if there is any instance with missing values.
void checkMissing (Instance ins) throws Exception
Checks if there is any missing value in the given instance.
double getMaxRelativeNodeWidth (double[][] nodeRanges, double[][] universe)
Returns the maximum attribute width of instances/points in a KDTreeNode relative to the whole dataset.
int widestDim (double[][] nodeRanges, double[][] universe)
Returns the widest dimension/attribute in a KDTreeNode (widest after normalizing).
void determineAssignments (KDTreeNode node, Instances centers, int[] candidates, int[] assignments, double pc) throws Exception
Assigns instances to the current centers called candidates.
int[] refineOwners (KDTreeNode node, Instances centers, int[] candidates) throws Exception
Refines the ownerlist.
double distanceToHrect (KDTreeNode node, Instance x) throws Exception
Returns the distance between a point and an hyperrectangle.
boolean clipToInsideHrect (KDTreeNode node, Instance x)
Finds the closest point in the hyper rectangle to a given point.
boolean candidateIsFullOwner (KDTreeNode node, Instance candidate, Instance competitor) throws Exception
Returns true if candidate is a full owner in respect to a competitor.
Protected Attributes
double[] m_DistanceList
Array holding the distances of the nearest neighbours.
int[] m_InstList
Indexlist of the instances of this kdtree.
KDTreeNode m_Root
The root node of the tree.
KDTreeNodeSplitter m_Splitter = new SlidingMidPointOfWidestSide()
The node splitter.
int m_NumNodes
Tree stats.
int m_NumLeaves
int m_MaxDepth
EuclideanDistance m_EuclideanDistance
The euclidean distance function to use.
double m_MinBoxRelWidth = 1.0E-2
minimal relative width of a KDTree rectangle.
int m_MaxInstInLeaf = 40
maximal number of instances in a leaf.
Package Functions
[instance initializer]
Package Attributes
boolean m_NormalizeNodeWidth = true
Properties' variables =====================================================.
Static Private Attributes
static final long serialVersionUID = 1505717283763272533L
For serialization.
Detailed Description
Class implementing the KDTree search algorithm for nearest neighbour search.
The connection to dataset is only a reference. For the tree structure the indexes are stored in an array.
Building the tree:
If a node has <maximal-inst-number> (option -L) instances no further splitting is done. Also if the split would leave one side empty, the branch is not split any further even if the instances in the resulting node are more than <maximal-inst-number> instances.
**PLEASE NOTE:** The algorithm can not handle missing values, so it is advisable to run ReplaceMissingValues filter if there are any missing values in the dataset.
For more information see:
Jerome H. Friedman, Jon Luis Bentley, Raphael Ari Finkel (1977). An Algorithm for Finding Best Matches in Logarithmic Expected Time. ACM Transactions on Mathematics Software. 3(3):209-226.
Andrew Moore (1991). A tutorial on kd-trees.
BibTeX:
 &#64;article{Friedman1977,
    author = {Jerome H. Friedman and Jon Luis Bentley and Raphael Ari Finkel},
    journal = {ACM Transactions on Mathematics Software},
    month = {September},
    number = {3},
    pages = {209-226},
    title = {An Algorithm for Finding Best Matches in Logarithmic Expected Time},
    volume = {3},
    year = {1977}
 }
 &#64;techreport{Moore1991,
    author = {Andrew Moore},
    booktitle = {University of Cambridge Computer Laboratory Technical Report No. 209},
    howpublished = {Extract from PhD Thesis},
    title = {A tutorial on kd-trees},
    year = {1991},
    HTTP = {Available from http://www.autonlab.org/autonweb/14665.html}
 }
Valid options are:
 -S <classname and options>
  Node splitting method to use.
  (default: weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide)
 -W <value>
  Set minimal width of a box
  (default: 1.0E-2).
 -L
  Maximal number of instances in a leaf
  (default: 40).
 -N
  Normalizing will be done
  (Select dimension for split, with normalising to universe).
Author:
Gabi Schmidberger (gabi[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Malcolm Ware (mfw4[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Ashraf M. Kibriya (amk14[at-the-rate]cs[dot]waikato[dot]ac[dot]nz)
Version:
Revision
8034
Definition at line 103 of file KDTree.java.
Constructor & Destructor Documentation
moa.classifiers.lazy.neighboursearch.KDTree.KDTree ()
Creates a new instance of KDTree.
Definition at line 144 of file KDTree.java.
                  {
    super();
  }
moa.classifiers.lazy.neighboursearch.KDTree.KDTree (Instances insts)
Creates a new instance of KDTree.
It also builds the tree on supplied set of Instances.
Parameters:
insts The instances/points on which the BallTree should be built on.
Definition at line 154 of file KDTree.java.
{
    super(insts);
  }
Member Function Documentation
moa.classifiers.lazy.neighboursearch.KDTree.[instance initializer] () [package]
void moa.classifiers.lazy.neighboursearch.KDTree.addInstanceInfo (Instance instance)
Adds one instance to KDTree loosly.
It only changes the ranges in EuclideanDistance, and does not affect the structure of the KDTree.
Parameters:
instance the new instance. Usually this is the test instance supplied to update the range of attributes in the distance function.
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 519 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.update().
{
    m_EuclideanDistance.updateRanges(instance);
  }
void moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree (Instance inst, KDTreeNode node) throws Exception [protected]
Recursively adds an instance to the tree starting from the supplied KDTreeNode.
NOTE: This should not be called by outside classes, outside classes should instead call update(Instance) method.
Parameters:
inst The instance to add to the tree
node The node to start the recursive search from, for the leaf node where the supplied instance would go.
Exceptions:
Exception If some error occurs while adding the instance.
Definition at line 440 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.afterAddInstance(), moa.classifiers.lazy.neighboursearch.KDTree.getMaxRelativeNodeWidth(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getRanges(), moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.m_InstList, moa.classifiers.lazy.neighboursearch.KDTree.m_MaxInstInLeaf, moa.classifiers.lazy.neighboursearch.KDTree.m_MinBoxRelWidth, moa.classifiers.lazy.neighboursearch.KDTree.m_NumNodes, moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.setInstanceList(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.splitNode(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.updateRanges(), and moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.update().
                       {
    if (node.isALeaf()) {
      int instList[] = new int[m_Instances.numInstances()];
      try {
        System.arraycopy(m_InstList, 0, instList, 0, node.m_End + 1); // m_InstList.squeezeIn(m_End,
                                                                      // index);
        if (node.m_End < m_InstList.length - 1)
          System.arraycopy(m_InstList, node.m_End + 1, instList,
              node.m_End + 2, m_InstList.length - node.m_End - 1);
        instList[node.m_End + 1] = m_Instances.numInstances() - 1;
      } catch (ArrayIndexOutOfBoundsException ex) {
        System.err.println("m_InstList.length: " + m_InstList.length
            + " instList.length: " + instList.length + "node.m_End+1: "
            + (node.m_End + 1) + "m_InstList.length-node.m_End+1: "
            + (m_InstList.length - node.m_End - 1));
        throw ex;
      }
      m_InstList = instList;
      node.m_End++;
      node.m_NodeRanges = m_EuclideanDistance.updateRanges(inst,
          node.m_NodeRanges);
      m_Splitter.setInstanceList(m_InstList);
      // split this leaf node if necessary
      double[][] universe = m_EuclideanDistance.getRanges();
      if (node.numInstances() > m_MaxInstInLeaf
          && getMaxRelativeNodeWidth(node.m_NodeRanges, universe) > m_MinBoxRelWidth) {
        m_Splitter.splitNode(node, m_NumNodes, node.m_NodeRanges, universe);
        m_NumNodes += 2;
      }
    }// end if node is a leaf
    else {
      if (m_EuclideanDistance.valueIsSmallerEqual(inst, node.m_SplitDim,
          node.m_SplitValue)) {
        addInstanceToTree(inst, node.m_Left);
        afterAddInstance(node.m_Right);
      } else
        addInstanceToTree(inst, node.m_Right);
      node.m_End++;
      node.m_NodeRanges = m_EuclideanDistance.updateRanges(inst,
          node.m_NodeRanges);
    }
  }
void moa.classifiers.lazy.neighboursearch.KDTree.afterAddInstance (KDTreeNode node) [protected]
Corrects the start and end indices of a KDTreeNode after an instance is added to the tree.
The start and end indices for the master index array (m_InstList) stored in the nodes need to be updated for all nodes in the subtree on the right of a node where the instance was added. NOTE: No outside class should call this method.
Parameters:
node KDTreeNode whose start and end indices need to be updated.
Definition at line 503 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.isALeaf(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_End, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Left, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Right, and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Start.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree().
{
    node.m_Start++;
    node.m_End++;
    if (!node.isALeaf()) {
      afterAddInstance(node.m_Left);
      afterAddInstance(node.m_Right);
    }
  }
void moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters (KDTreeNode node, Instances centers, int[] centList, int[] assignments) throws Exception
Assigns instances of this node to center.
Center to be assign to is decided by the distance function.
Parameters:
node The KDTreeNode whose instances are to be assigned.
centers all the input centers
centList the list of centers to work with
assignments index list of last assignments
Exceptions:
Exception If there is error assigning the instances.
Definition at line 910 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.EuclideanDistance.closestPoint(), moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, and moa.classifiers.lazy.neighboursearch.KDTree.m_InstList.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.determineAssignments().
{
    // todo: undecided situations
    int numCent = centList.length;
    // WARNING: assignments is "input/output-parameter"
    // should not be null and the following should not happen
    if (assignments == null) {
      assignments = new int[m_Instances.numInstances()];
      for (int i = 0; i < assignments.length; i++) {
        assignments[i] = -1;
      }
    }
    // set assignments for all instances of this node
    for (int i = node.m_Start; i <= node.m_End; i++) {
      int instIndex = m_InstList[i];
      Instance inst = m_Instances.instance(instIndex);
      // if (instList[i] == 664) System.out.println("664***");
      int newC = m_EuclideanDistance.closestPoint(inst, centers, centList);
      // int newC = clusterProcessedInstance(inst, centers);
      assignments[instIndex] = newC;
    }
  }
void moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree (Instances instances) throws Exception [protected]
Builds the KDTree on the supplied set of instances/points.
It is adviseable to run the replace missing attributes filter on the passed instances first. NOTE: This method should not be called from outside this class. Outside classes should call setInstances(Instances) instead.
Parameters:
instances The instances to build the tree on
Exceptions:
Exception if something goes wrong
Definition at line 169 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.checkMissing(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.getRanges(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.m_InstList, moa.classifiers.lazy.neighboursearch.KDTree.m_MaxDepth, moa.classifiers.lazy.neighboursearch.KDTree.m_NormalizeNodeWidth, moa.classifiers.lazy.neighboursearch.KDTree.m_NumLeaves, moa.classifiers.lazy.neighboursearch.KDTree.m_NumNodes, moa.classifiers.lazy.neighboursearch.KDTree.m_Root, moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.setEuclideanDistanceFunction(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.setInstanceList(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.setInstances(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.setInstances(), moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.setNodeWidthNormalization(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.setInstances().
{
    checkMissing(instances);
    if (m_EuclideanDistance == null)
      m_DistanceFunction = m_EuclideanDistance = new EuclideanDistance(
          instances);
    else
      m_EuclideanDistance.setInstances(instances);
    m_Instances = instances;
    int numInst = m_Instances.numInstances();
    // Make the global index list
    m_InstList = new int[numInst];
    for (int i = 0; i < numInst; i++) {
      m_InstList[i] = i;
    }
    double[][] universe = m_EuclideanDistance.getRanges();
    // initializing internal fields of KDTreeSplitter
    m_Splitter.setInstances(m_Instances);
    m_Splitter.setInstanceList(m_InstList);
    m_Splitter.setEuclideanDistanceFunction(m_EuclideanDistance);
    m_Splitter.setNodeWidthNormalization(m_NormalizeNodeWidth);
    // building tree
    m_NumNodes = m_NumLeaves = 1;
    m_MaxDepth = 0;
    m_Root = new KDTreeNode(m_NumNodes, 0, m_Instances.numInstances() - 1,
        universe);
    splitNodes(m_Root, universe, m_MaxDepth + 1);
  }
boolean moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner (KDTreeNode node, Instance candidate, Instance competitor) throws Exception [protected]
Returns true if candidate is a full owner in respect to a competitor.
The candidate has been the closer point to the current rectangle or even has been a point within the rectangle. The competitor is competing with the candidate for a few points out of the rectangle although it is a point further away from the rectangle then the candidate. The extrem point is the corner of the rectangle that is furthest away from the candidate towards the direction of the competitor.
If the distance candidate to this extreme point is smaller then the distance competitor to this extreme point, then it is proven that none of the points in the rectangle can be owned be the competitor and the candidate is full owner of the rectangle in respect to this competitor. See also D. Pelleg and A. Moore's paper 'Accelerating exact k-means Algorithms with Geometric Reasoning'.
Parameters:
node The current KDTreeNode / hyperrectangle.
candidate instance that is candidate to be owner
competitor instance that competes against the candidate
Returns:
true if candidate is full owner
Exceptions:
Exception If some problem occurs.
Definition at line 883 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.EuclideanDistance.distance(), moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.MAX, and moa.classifiers.lazy.neighboursearch.KDTree.MIN.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.refineOwners().
{
    // get extreme point
    Instance extreme = (Instance)candidate.copy();
    for (int i = 0; i < m_Instances.numAttributes(); i++) {
      if ((competitor.value(i) - candidate.value(i)) > 0) {
        extreme.setValue(i, node.m_NodeRanges[i][MAX]);
      } else {
        extreme.setValue(i, node.m_NodeRanges[i][MIN]);
      }
    }
    boolean isFullOwner = m_EuclideanDistance.distance(extreme, candidate) < m_EuclideanDistance
        .distance(extreme, competitor);
    return isFullOwner;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.centerInstances (Instances centers, int[] assignments, double pc) throws Exception
Assigns instances to centers using KDTree.
Parameters:
centers the current centers
assignments the centerindex for each instance
pc the threshold value for pruning.
Exceptions:
Exception If there is some problem assigning instances to centers.
Definition at line 701 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.determineAssignments(), and moa.classifiers.lazy.neighboursearch.KDTree.m_Root.
                       {
    int[] centList = new int[centers.numInstances()];
    for (int i = 0; i < centers.numInstances(); i++)
      centList[i] = i;
    determineAssignments(m_Root, centers, centList, assignments, pc);
  }
void moa.classifiers.lazy.neighboursearch.KDTree.checkMissing (Instance ins) throws Exception [protected]
Checks if there is any missing value in the given instance.
Parameters:
ins The instance to check missing values in.
Exceptions:
Exception If there is a missing value in the instance.
Definition at line 551 of file KDTree.java.
{
    for (int j = 0; j < ins.numValues(); j++) {
      if (ins.index(j) != ins.classIndex())
        if (ins.isMissingSparse(j)) {
          throw new Exception("ERROR: KDTree can not deal with missing "
              + "values. Please run ReplaceMissingValues filter "
              + "on the dataset before passing it on to the KDTree.");
        }
    }
  }
void moa.classifiers.lazy.neighboursearch.KDTree.checkMissing (Instances instances) throws Exception [protected]
Checks if there is any instance with missing values.
Throws an exception if there is, as KDTree does not handle missing values.
Parameters:
instances the instances to check
Exceptions:
Exception if missing values are encountered
Definition at line 530 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), and moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
{
    for (int i = 0; i < instances.numInstances(); i++) {
      Instance ins = instances.instance(i);
      for (int j = 0; j < ins.numValues(); j++) {
        if (ins.index(j) != ins.classIndex())
          if (ins.isMissingSparse(j)) {
            throw new Exception("ERROR: KDTree can not deal with missing "
                + "values. Please run ReplaceMissingValues filter "
                + "on the dataset before passing it on to the KDTree.");
          }
      }
    }
  }
boolean moa.classifiers.lazy.neighboursearch.KDTree.clipToInsideHrect (KDTreeNode node, Instance x) [protected]
Finds the closest point in the hyper rectangle to a given point.
Change the given point to this closest point by clipping of at all the dimensions to be clipped of. If the point is inside the rectangle it stays unchanged. The return value is true if the point was not changed, so the the return value is true if the point was inside the rectangle.
Parameters:
node The current KDTreeNode in whose hyperrectangle the closest point is to be found.
x a point
Returns:
true if the input point stayed unchanged.
Definition at line 842 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_NodeRanges, moa.classifiers.lazy.neighboursearch.KDTree.MAX, and moa.classifiers.lazy.neighboursearch.KDTree.MIN.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.distanceToHrect().
{
    boolean inside = true;
    for (int i = 0; i < m_Instances.numAttributes(); i++) {
      // TODO treat nominals differently!??
      if (x.value(i) < node.m_NodeRanges[i][MIN]) {
        x.setValue(i, node.m_NodeRanges[i][MIN]);
        inside = false;
      } else if (x.value(i) > node.m_NodeRanges[i][MAX]) {
        x.setValue(i, node.m_NodeRanges[i][MAX]);
        inside = false;
      }
    }
    return inside;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.determineAssignments (KDTreeNode node, Instances centers, int[] candidates, int[] assignments, double pc) throws Exception [protected]
Assigns instances to the current centers called candidates.
Parameters:
node The node to start assigning the instances from.
centers all the current centers.
candidates the current centers the method works on.
assignments the center index for each instance.
pc the threshold value for pruning.
Exceptions:
Exception If there is some problem assigning instances to centers.
Definition at line 722 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters(), moa.classifiers.lazy.neighboursearch.KDTree.m_InstList, and moa.classifiers.lazy.neighboursearch.KDTree.refineOwners().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.centerInstances().
{
    // reduce number of owners for current hyper rectangle
    int[] owners = refineOwners(node, centers, candidates);
    // only one owner
    if (owners.length == 1) {
      // all instances of this node are owned by one center
      for (int i = node.m_Start; i <= node.m_End; i++) {
        assignments[m_InstList[i]] // the assignment of this instance
        = owners[0]; // is the current owner
      }
    } else if (!node.isALeaf()) {
      // more than one owner and it is not a leaf
      determineAssignments(node.m_Left, centers, owners, assignments, pc);
      determineAssignments(node.m_Right, centers, owners, assignments, pc);
    } else {
      // this is a leaf and there are more than 1 owner
      // XMeans.
      assignSubToCenters(node, centers, owners, assignments);
    }
  }
double moa.classifiers.lazy.neighboursearch.KDTree.distanceToHrect (KDTreeNode node, Instance x) throws Exception [protected]
Returns the distance between a point and an hyperrectangle.
Parameters:
node The current node from whose hyperrectangle the distance is to be measured.
x the point
Returns:
the distance
Exceptions:
Exception If some problem occurs in determining the distance to the hyperrectangle.
Definition at line 819 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.clipToInsideHrect(), moa.classifiers.lazy.neighboursearch.EuclideanDistance.distance(), and moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.refineOwners().
{
    double distance = 0.0;
    Instance closestPoint = (Instance)x.copy();
    boolean inside;
    inside = clipToInsideHrect(node, closestPoint);
    if (!inside)
      distance = m_EuclideanDistance.distance(closestPoint, x);
    return distance;
  }
Enumeration moa.classifiers.lazy.neighboursearch.KDTree.enumerateMeasures ()
Returns an enumeration of the additional measure names.
Returns:
an enumeration of the measure names
Definition at line 653 of file KDTree.java.
{
    Vector<String> newVector = new Vector<String>();
    newVector.addElement("measureTreeSize");
    newVector.addElement("measureNumLeaves");
    newVector.addElement("measureMaxDepth");
    return newVector.elements();
  }
void moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours (Instance target, KDTreeNode node, int k, MyHeap heap, double distanceToParents) throws Exception [protected]
Returns (in the supplied heap object) the k nearest neighbours of the given instance starting from the give tree node.
>k neighbours are returned if there are more than one neighbours at the kth boundary. NOTE: This method should not be used from outside this class. Outside classes should call kNearestNeighbours(Instance, int).
Parameters:
target The instance to find the nearest neighbours for.
node The KDTreeNode to start the search from.
k The number of neighbours to find.
heap The MyHeap object to store/update the kNNs found during the search.
distanceToParents The distance of the supplied target to the parents of the supplied tree node.
Exceptions:
Exception if the nearest neighbour could not be found.
Definition at line 258 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.distance, moa.classifiers.lazy.neighboursearch.EuclideanDistance.distance(), moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.m_InstList, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Left, moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNode.m_Right, moa.classifiers.lazy.neighboursearch.EuclideanDistance.sqDifference(), and moa.classifiers.lazy.neighboursearch.EuclideanDistance.valueIsSmallerEqual().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
{
    if (node.isALeaf()) {
      double distance;
      // look at all the instances in this leaf
      for (int idx = node.m_Start; idx <= node.m_End; idx++) {
        if (target == m_Instances.instance(m_InstList[idx])) // for
                                                              // hold-one-out
                                                              // cross-validation
          continue;
        if (heap.size() < k) {
          distance = m_EuclideanDistance.distance(target, m_Instances
              .instance(m_InstList[idx]), Double.POSITIVE_INFINITY);
          heap.put(m_InstList[idx], distance);
        } else {
          MyHeapElement temp = heap.peek();
          distance = m_EuclideanDistance.distance(target, m_Instances
              .instance(m_InstList[idx]), temp.distance);
          if (distance < temp.distance) {
            heap.putBySubstitute(m_InstList[idx], distance);
          } else if (distance == temp.distance) {
            heap.putKthNearest(m_InstList[idx], distance);
          }
        }// end else heap.size==k
      }// end for
    } else {
      KDTreeNode nearer, further;
      boolean targetInLeft = m_EuclideanDistance.valueIsSmallerEqual(target,
          node.m_SplitDim, node.m_SplitValue);
      if (targetInLeft) {
        nearer = node.m_Left;
        further = node.m_Right;
      } else {
        nearer = node.m_Right;
        further = node.m_Left;
      }
      findNearestNeighbours(target, nearer, k, heap, distanceToParents);
      // ... now look in further half if maxDist reaches into it
      if (heap.size() < k) { // if haven't found the first k
        double distanceToSplitPlane = distanceToParents
            + m_EuclideanDistance.sqDifference(node.m_SplitDim, target
                .value(node.m_SplitDim), node.m_SplitValue);
        findNearestNeighbours(target, further, k, heap, distanceToSplitPlane);
        return;
      } else { // else see if ball centered at query intersects with the other
                // side.
        double distanceToSplitPlane = distanceToParents
            + m_EuclideanDistance.sqDifference(node.m_SplitDim, target
                .value(node.m_SplitDim), node.m_SplitValue);
        if (heap.peek().distance >= distanceToSplitPlane) {
          findNearestNeighbours(target, further, k, heap, distanceToSplitPlane);
        }
      }// end else
    }// end else_if an internal node
  }
DistanceFunction moa.classifiers.lazy.neighboursearch.KDTree.getDistanceFunction ()
returns the distance function currently in use.
Returns:
the distance function
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 1056 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance.
{
    return (DistanceFunction) m_EuclideanDistance;
  }
double [] moa.classifiers.lazy.neighboursearch.KDTree.getDistances () throws Exception [virtual]
Returns the distances to the kNearest or 1 nearest neighbour currently found with either the kNearestNeighbours or the nearestNeighbour method.
Returns:
array containing the distances of the nearestNeighbours. The length and ordering of the array is the same as that of the instances returned by nearestNeighbour functions.
Exceptions:
Exception if called before calling kNearestNeighbours or nearestNeighbours.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 386 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_DistanceList, and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances.
{
    if (m_Instances == null || m_DistanceList == null)
      throw new Exception("The tree has not been supplied with a set of "
          + "instances or getDistances() has been called "
          + "before calling kNearestNeighbours().");
    return m_DistanceList;
  }
int moa.classifiers.lazy.neighboursearch.KDTree.getMaxInstInLeaf ()
Get the maximum number of instances in a leaf.
Returns:
the maximum number of instances in a leaf
Definition at line 1014 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_MaxInstInLeaf.
{
    return m_MaxInstInLeaf;
  }
double moa.classifiers.lazy.neighboursearch.KDTree.getMaxRelativeNodeWidth (double nodeRanges[][], double universe[][]) [protected]
Returns the maximum attribute width of instances/points in a KDTreeNode relative to the whole dataset.
Parameters:
nodeRanges The attribute ranges of the KDTreeNode whose maximum relative width is to be determined.
universe The attribute ranges of the whole dataset (training instances + test instances so far encountered).
Returns:
The maximum relative width
Definition at line 574 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.widestDim(), and moa.classifiers.lazy.neighboursearch.KDTree.WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
{
    int widest = widestDim(nodeRanges, universe);
    if(widest < 0)
        return 0.0;
    else
        return nodeRanges[widest][WIDTH] / universe[widest][WIDTH];
  }
double moa.classifiers.lazy.neighboursearch.KDTree.getMeasure (String additionalMeasureName)
Returns the value of the named measure.
Parameters:
additionalMeasureName the name of the measure to query for its value.
Returns:
The value of the named measure
Exceptions:
IllegalArgumentException If the named measure is not supported.
Definition at line 670 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.measureMaxDepth(), moa.classifiers.lazy.neighboursearch.KDTree.measureNumLeaves(), and moa.classifiers.lazy.neighboursearch.KDTree.measureTreeSize().
{
    if (additionalMeasureName.compareToIgnoreCase("measureMaxDepth") == 0) {
      return measureMaxDepth();
    } else if (additionalMeasureName.compareToIgnoreCase("measureTreeSize") == 0) {
      return measureTreeSize();
    } else if (additionalMeasureName.compareToIgnoreCase("measureNumLeaves") == 0) {
      return measureNumLeaves();
    }  else {
      throw new IllegalArgumentException(additionalMeasureName
          + " not supported (KDTree)");
    }
  }
double moa.classifiers.lazy.neighboursearch.KDTree.getMinBoxRelWidth ()
Gets the minimum relative box width.
Returns:
the minimum relative box width
Definition at line 987 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_MinBoxRelWidth.
{
    return m_MinBoxRelWidth;
  }
KDTreeNodeSplitter moa.classifiers.lazy.neighboursearch.KDTree.getNodeSplitter ()
Returns the splitting method currently in use to split the nodes of the KDTree.
Returns:
The KDTreeNodeSplitter currently in use.
Definition at line 1089 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter.
{
    return m_Splitter;
  }
boolean moa.classifiers.lazy.neighboursearch.KDTree.getNormalizeNodeWidth ()
Gets the normalize flag.
Returns:
True if normalizing
Definition at line 1047 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_NormalizeNodeWidth.
{
    return m_NormalizeNodeWidth;
  }
String moa.classifiers.lazy.neighboursearch.KDTree.globalInfo ()
Returns a string describing this nearest neighbour search algorithm.
Returns:
a description of the algorithm for displaying in the explorer/experimenter gui
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 1108 of file KDTree.java.
{
    return
        "Class implementing the KDTree search algorithm for nearest "
      + "neighbour search.\n"
      + "The connection to dataset is only a reference. For the tree "
      + "structure the indexes are stored in an array. \n"
      + "Building the tree:\n"
      + "If a node has <maximal-inst-number> (option -L) instances no "
      + "further splitting is done. Also if the split would leave one "
      + "side empty, the branch is not split any further even if the "
      + "instances in the resulting node are more than "
      + "<maximal-inst-number> instances.\n"
      + "**PLEASE NOTE:** The algorithm can not handle missing values, so it "
      + "is advisable to run ReplaceMissingValues filter if there are any "
      + "missing values in the dataset.\n\n"
      + "For more information see:\n\n";
  }
Instances moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours (Instance target, int k) throws Exception [virtual]
Returns the k nearest neighbours of the supplied instance.
>k neighbours are returned if there are more than one neighbours at the kth boundary.
Parameters:
target The instance to find the nearest neighbours for.
k The number of neighbours to find.
Returns:
The k nearest neighbours (or >k if more there are than one neighbours at the kth boundary).
Exceptions:
Exception if the nearest neighbour could not be found.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 328 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.checkMissing(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.distance, moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.get(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.getKthNearest(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeapElement.index, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, moa.classifiers.lazy.neighboursearch.KDTree.m_DistanceList, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.m_Root, moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.noOfKthNearest(), moa.classifiers.lazy.neighboursearch.DistanceFunction.postProcessDistances(), and moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.MyHeap.size().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.nearestNeighbour().
{
    checkMissing(target);
    MyHeap heap = new MyHeap(k);
    findNearestNeighbours(target, m_Root, k, heap, 0.0);
    Instances neighbours = new Instances(m_Instances, (heap.size() + heap
        .noOfKthNearest()));
    m_DistanceList = new double[heap.size() + heap.noOfKthNearest()];
    int[] indices = new int[heap.size() + heap.noOfKthNearest()];
    int i = indices.length - 1;
    MyHeapElement h;
    while (heap.noOfKthNearest() > 0) {
      h = heap.getKthNearest();
      indices[i] = h.index;
      m_DistanceList[i] = h.distance;
      i--;
    }
    while (heap.size() > 0) {
      h = heap.get();
      indices[i] = h.index;
      m_DistanceList[i] = h.distance;
      i--;
    }
    m_DistanceFunction.postProcessDistances(m_DistanceList);
    for (int idx = 0; idx < indices.length; idx++) {
      neighbours.add(m_Instances.instance(indices[idx]));
    }
    return neighbours;
  }
String moa.classifiers.lazy.neighboursearch.KDTree.maxInstInLeafTipText ()
Tip text for this property.
Returns:
the tip text for this property
Definition at line 996 of file KDTree.java.
{
    return "The max number of instances in a leaf.";
  }
double moa.classifiers.lazy.neighboursearch.KDTree.measureMaxDepth ()
Returns the depth of the tree.
Returns:
The depth of the tree
Definition at line 644 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_MaxDepth.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getMeasure().
{
    return m_MaxDepth;
  }
double moa.classifiers.lazy.neighboursearch.KDTree.measureNumLeaves ()
Returns the number of leaves.
Returns:
the number of leaves
Definition at line 635 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_NumLeaves.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getMeasure().
{
    return m_NumLeaves;
  }
double moa.classifiers.lazy.neighboursearch.KDTree.measureTreeSize ()
Returns the size of the tree.
Returns:
the size of the tree
Definition at line 626 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_NumNodes.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getMeasure().
{
    return m_NumNodes;
  }
String moa.classifiers.lazy.neighboursearch.KDTree.minBoxRelWidthTipText ()
the GET and SET - functions ===============================================
Tip text for this property.
Returns:
the tip text for this property
Definition at line 966 of file KDTree.java.
{
    return "The minimum relative width of the box. A node is only made a leaf "
        + "if the width of the split dimension of the instances in a node "
        + "normalized over the width of the split dimension of all the "
        + "instances is less than or equal to this minimum relative width.";
  }
Instance moa.classifiers.lazy.neighboursearch.KDTree.nearestNeighbour (Instance target) throws Exception [virtual]
Returns the nearest neighbour of the supplied target instance.
Parameters:
target The instance to find the nearest neighbour for.
Returns:
The nearest neighbour from among the previously supplied training instances.
Exceptions:
Exception if the neighbours could not be found.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 371 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
{
    return (kNearestNeighbours(target, 1)).instance(0);
  }
String moa.classifiers.lazy.neighboursearch.KDTree.nodeSplitterTipText ()
Returns the tip text for this property.
Returns:
tip text for this property suitable for displaying in the explorer/experimenter gui
Definition at line 1079 of file KDTree.java.
{
    return "The the splitting method to split the nodes of the KDTree.";
  }
String moa.classifiers.lazy.neighboursearch.KDTree.normalizeNodeWidthTipText ()
Tip text for this property.
Returns:
the tip text for this property
Definition at line 1023 of file KDTree.java.
{
    return "Whether if the widths of the KDTree node should be normalized "
        + "by the width of the universe or not. "
        + "Where, width of the node is the range of the split attribute "
        + "based on the instances in that node, and width of the "
        + "universe is the range of the split attribute based on all the "
        + "instances (default: false).";
  }
int [] moa.classifiers.lazy.neighboursearch.KDTree.refineOwners (KDTreeNode node, Instances centers, int[] candidates) throws Exception [protected]
Refines the ownerlist.
Parameters:
node The current tree node.
centers all centers
candidates the indexes of those centers that are candidates.
Returns:
list of owners
Exceptions:
Exception If some problem occurs in refining.
Definition at line 755 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), and moa.classifiers.lazy.neighboursearch.KDTree.distanceToHrect().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.determineAssignments().
{
    int[] owners = new int[candidates.length];
    double minDistance = Double.POSITIVE_INFINITY;
    int ownerIndex = -1;
    Instance owner;
    int numCand = candidates.length;
    double[] distance = new double[numCand];
    boolean[] inside = new boolean[numCand];
    for (int i = 0; i < numCand; i++) {
      distance[i] = distanceToHrect(node, centers.instance(candidates[i]));
      inside[i] = (distance[i] == 0.0);
      if (distance[i] < minDistance) {
        minDistance = distance[i];
        ownerIndex = i;
      }
    }
    owner = (Instance)centers.instance(candidates[ownerIndex]).copy();
    // are there other owners
    // loop also goes over already found owner, keeps order
    // in owner list
    int index = 0;
    for (int i = 0; i < numCand; i++) {
      // 1. all centers that are points within rectangle are owners
      if ((inside[i])
      // 2. take all points with same distance to the rect. as the owner
          || (distance[i] == distance[ownerIndex])) {
        // add competitor to owners list
        owners[index++] = candidates[i];
      } else {
        Instance competitor = (Instance)centers.instance(candidates[i]).copy();
        if
        // 3. point has larger distance to rectangle but still can compete
        // with owner for some points in the rectangle
        (!candidateIsFullOwner(node, owner, competitor))
        {
          // also add competitor to owners list
          owners[index++] = candidates[i];
        }
      }
    }
    int[] result = new int[index];
    for (int i = 0; i < index; i++)
      result[i] = owners[i];
    return result;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setDistanceFunction (DistanceFunction df) throws Exception
sets the distance function to use for nearest neighbour search.
Parameters:
df the distance function to use
Exceptions:
Exception if not EuclideanDistance
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 1066 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_DistanceFunction, and moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance.
{
    if (!(df instanceof EuclideanDistance))
      throw new Exception("KDTree currently only works with "
          + "EuclideanDistanceFunction.");
    m_DistanceFunction = m_EuclideanDistance = (EuclideanDistance) df;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setInstances (Instances instances) throws Exception
Builds the KDTree on the given set of instances.
Parameters:
instances The insts on which the KDTree is to be built.
Exceptions:
Exception If some error occurs while building the KDTree
Reimplemented from moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 402 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree().
{
    super.setInstances(instances);
    buildKDTree(instances);
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setMaxInstInLeaf (int i)
Sets the maximum number of instances in a leaf.
Parameters:
i the maximum number of instances in a leaf
Definition at line 1005 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_MaxInstInLeaf.
{
    m_MaxInstInLeaf = i;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setMeasurePerformance (boolean measurePerformance)
Sets whether to calculate the performance statistics or not.
Parameters:
measurePerformance Should be true if performance statistics are to be measured.
Definition at line 688 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_MeasurePerformance.
{
    m_MeasurePerformance = measurePerformance;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setMinBoxRelWidth (double i)
Sets the minimum relative box width.
Parameters:
i the minimum relative box width
Definition at line 978 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_MinBoxRelWidth.
{
    m_MinBoxRelWidth = i;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setNodeSplitter (KDTreeNodeSplitter splitter)
Sets the splitting method to use to split the nodes of the KDTree.
Parameters:
splitter The KDTreeNodeSplitter to use.
Definition at line 1098 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter.
{
    m_Splitter = splitter;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.setNormalizeNodeWidth (boolean n)
Sets the flag for normalizing the widths of a KDTree Node by the width of the dimension in the universe.
Parameters:
n true to use normalizing.
Definition at line 1038 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.m_NormalizeNodeWidth.
{
    m_NormalizeNodeWidth = n;
  }
void moa.classifiers.lazy.neighboursearch.KDTree.splitNodes (KDTreeNode node, double universe[][], int depth) throws Exception [protected]
Recursively splits nodes of a tree starting from the supplied node.
The splitting stops for any node for which the number of instances/points falls below a given threshold (given by m_MaxInstInLeaf), or if the maximum relative width/range of the instances/points (i.e. max_i(max(att_i) - min(att_i))) falls below a given threshold (given by m_MinBoxRelWidth).
Parameters:
node The node to start splitting from.
universe The attribute ranges of the whole dataset.
depth The depth of the supplied node.
Exceptions:
Exception If there is some problem splitting.
Definition at line 219 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.getMaxRelativeNodeWidth(), moa.classifiers.lazy.neighboursearch.NormalizableDistance.initializeRanges(), moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance, moa.classifiers.lazy.neighboursearch.KDTree.m_InstList, moa.classifiers.lazy.neighboursearch.KDTree.m_MaxDepth, moa.classifiers.lazy.neighboursearch.KDTree.m_MaxInstInLeaf, moa.classifiers.lazy.neighboursearch.KDTree.m_MinBoxRelWidth, moa.classifiers.lazy.neighboursearch.KDTree.m_NumLeaves, moa.classifiers.lazy.neighboursearch.KDTree.m_NumNodes, moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter, and moa.classifiers.lazy.neighboursearch.kdtrees.KDTreeNodeSplitter.splitNode().
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree().
{
    double[][] nodeRanges = m_EuclideanDistance.initializeRanges(m_InstList,
                                                 node.m_Start, node.m_End);
    if (node.numInstances() <= m_MaxInstInLeaf
        || getMaxRelativeNodeWidth(nodeRanges, universe) <= m_MinBoxRelWidth)
      return;
    // splitting a node so it is no longer a leaf
    m_NumLeaves--;
    if (depth > m_MaxDepth)
      m_MaxDepth = depth;
    m_Splitter.splitNode(node, m_NumNodes, nodeRanges, universe);
    m_NumNodes += 2;
    m_NumLeaves += 2;
    splitNodes(node.m_Left, universe, depth + 1);
    splitNodes(node.m_Right, universe, depth + 1);
  }
void moa.classifiers.lazy.neighboursearch.KDTree.update (Instance instance) throws Exception [virtual]
Adds one instance to the KDTree.
This updates the KDTree structure to take into account the newly added training instance.
Parameters:
instance the instance to be added. Usually the newly added instance in the training set.
Exceptions:
Exception If the instance cannot be added.
Implements moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.
Definition at line 416 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.KDTree.addInstanceInfo(), moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, and moa.classifiers.lazy.neighboursearch.KDTree.m_Root.
                                                         { // better to change
                                                            // to addInstance
    if (m_Instances == null)
      throw new Exception("No instances supplied yet. Have to call "
          + "setInstances(instances) with a set of Instances " + "first.");
    addInstanceInfo(instance);
    addInstanceToTree(instance, m_Root);
  }
int moa.classifiers.lazy.neighboursearch.KDTree.widestDim (double nodeRanges[][], double universe[][]) [protected]
Returns the widest dimension/attribute in a KDTreeNode (widest after normalizing).
Parameters:
nodeRanges The attribute ranges of the KDTreeNode.
universe The attribute ranges of the whole dataset (training instances + test instances so far encountered).
Returns:
The index of the widest dimension/attribute.
Definition at line 594 of file KDTree.java.
References moa.classifiers.lazy.neighboursearch.NearestNeighbourSearch.m_Instances, moa.classifiers.lazy.neighboursearch.KDTree.m_NormalizeNodeWidth, and moa.classifiers.lazy.neighboursearch.KDTree.WIDTH.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getMaxRelativeNodeWidth().
{
    final int classIdx = m_Instances.classIndex();
    double widest = 0.0;
    int w = -1;
    if (m_NormalizeNodeWidth) {
      for (int i = 0; i < nodeRanges.length; i++) {
        double newWidest = nodeRanges[i][WIDTH] / universe[i][WIDTH];
        if (newWidest > widest) {
          if (i == classIdx)
            continue;
          widest = newWidest;
          w = i;
        }
      }
    } else {
      for (int i = 0; i < nodeRanges.length; i++) {
        if (nodeRanges[i][WIDTH] > widest) {
          if (i == classIdx)
            continue;
          widest = nodeRanges[i][WIDTH];
          w = i;
        }
      }
    }
    return w;
  }
Member Data Documentation
double [] moa.classifiers.lazy.neighboursearch.KDTree.m_DistanceList [protected]
Array holding the distances of the nearest neighbours.
It is filled up both by nearestNeighbour() and kNearestNeighbours().
Definition at line 113 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getDistances(), and moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
EuclideanDistance moa.classifiers.lazy.neighboursearch.KDTree.m_EuclideanDistance [protected]
The euclidean distance function to use.
Definition at line 943 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceInfo(), moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters(), moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), moa.classifiers.lazy.neighboursearch.KDTree.distanceToHrect(), moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours(), moa.classifiers.lazy.neighboursearch.KDTree.getDistanceFunction(), moa.classifiers.lazy.neighboursearch.KDTree.setDistanceFunction(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
int [] moa.classifiers.lazy.neighboursearch.KDTree.m_InstList [protected]
Indexlist of the instances of this kdtree.
Instances get sorted according to the splits. the nodes of the KDTree just hold their start and end indices
Definition at line 120 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.assignSubToCenters(), moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.determineAssignments(), moa.classifiers.lazy.neighboursearch.KDTree.findNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
int moa.classifiers.lazy.neighboursearch.KDTree.m_MaxDepth [protected]
Definition at line 129 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.measureMaxDepth(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
int moa.classifiers.lazy.neighboursearch.KDTree.m_MaxInstInLeaf = 40 [protected]
maximal number of instances in a leaf.
Definition at line 955 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.getMaxInstInLeaf(), moa.classifiers.lazy.neighboursearch.KDTree.setMaxInstInLeaf(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
double moa.classifiers.lazy.neighboursearch.KDTree.m_MinBoxRelWidth = 1.0E-2 [protected]
minimal relative width of a KDTree rectangle.
Definition at line 952 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.getMinBoxRelWidth(), moa.classifiers.lazy.neighboursearch.KDTree.setMinBoxRelWidth(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
boolean moa.classifiers.lazy.neighboursearch.KDTree.m_NormalizeNodeWidth = true [package]
Properties' variables =====================================================.
flag for normalizing.
Definition at line 940 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.getNormalizeNodeWidth(), moa.classifiers.lazy.neighboursearch.KDTree.setNormalizeNodeWidth(), and moa.classifiers.lazy.neighboursearch.KDTree.widestDim().
int moa.classifiers.lazy.neighboursearch.KDTree.m_NumLeaves [protected]
Definition at line 129 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.measureNumLeaves(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
int moa.classifiers.lazy.neighboursearch.KDTree.m_NumNodes [protected]
Tree stats.
Definition at line 129 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.measureTreeSize(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
KDTreeNode moa.classifiers.lazy.neighboursearch.KDTree.m_Root [protected]
The root node of the tree.
Definition at line 123 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.centerInstances(), moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.KDTree.update().
KDTreeNodeSplitter moa.classifiers.lazy.neighboursearch.KDTree.m_Splitter = new SlidingMidPointOfWidestSide() [protected]
The node splitter.
Definition at line 126 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.addInstanceToTree(), moa.classifiers.lazy.neighboursearch.KDTree.buildKDTree(), moa.classifiers.lazy.neighboursearch.KDTree.getNodeSplitter(), moa.classifiers.lazy.neighboursearch.KDTree.setNodeSplitter(), and moa.classifiers.lazy.neighboursearch.KDTree.splitNodes().
final int moa.classifiers.lazy.neighboursearch.KDTree.MAX = EuclideanDistance.R_MAX [static]
The index of MAX value in attributes' range array.
Definition at line 136 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), and moa.classifiers.lazy.neighboursearch.KDTree.clipToInsideHrect().
final int moa.classifiers.lazy.neighboursearch.KDTree.MIN = EuclideanDistance.R_MIN [static]
The index of MIN value in attributes' range array.
Definition at line 133 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.candidateIsFullOwner(), and moa.classifiers.lazy.neighboursearch.KDTree.clipToInsideHrect().
final long moa.classifiers.lazy.neighboursearch.KDTree.serialVersionUID = 1505717283763272533L [static, private]
For serialization.
Definition at line 107 of file KDTree.java.
final int moa.classifiers.lazy.neighboursearch.KDTree.WIDTH = EuclideanDistance.R_WIDTH [static]
The index of WIDTH (MAX-MIN) value in attributes' range array.
Definition at line 139 of file KDTree.java.
Referenced by moa.classifiers.lazy.neighboursearch.KDTree.getMaxRelativeNodeWidth(), and moa.classifiers.lazy.neighboursearch.KDTree.widestDim().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/KDTree.java