MOA: moa.clusterers.denstream.MicroCluster Class Reference
moa.clusterers.denstream.MicroCluster Class Reference
Public Member Functions
MicroCluster (double[] center, int dimensions, long creationTimestamp, double lambda, Timestamp currentTimestamp)
MicroCluster (Instance instance, int dimensions, long timestamp, double lambda, Timestamp currentTimestamp)
void insert (Instance instance, long timestamp)
long getLastEditTimestamp ()
double getWeight ()
See interface Cluster.
long getCreationTime ()
double[] getCenter ()
double getRadius ()
See interface Cluster.
double getRadius (long timestamp)
MicroCluster copy ()
This method produces a copy of this object.
double getInclusionProbability (Instance instance)
Returns the probability of the given point belonging to this cluster.
CFCluster getCF ()
Private Member Functions
double[] calcCF2 (long dt)
double[] calcCF1 (long dt)
double getWeight (long timestamp)
double[] getCenter (long timestamp)
Private Attributes
long lastEditT = -1
long creationTimestamp = -1
double lambda
Timestamp currentTimestamp
Detailed Description
Definition at line 25 of file MicroCluster.java.
Constructor & Destructor Documentation
moa.clusterers.denstream.MicroCluster.MicroCluster (double[] center, int dimensions, long creationTimestamp, double lambda, Timestamp currentTimestamp)
Definition at line 32 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lastEditT.
Referenced by moa.clusterers.denstream.MicroCluster.copy().
{
        super(center, dimensions);
        this.creationTimestamp = creationTimestamp;
        this.lastEditT = creationTimestamp;
        this.lambda = lambda;
        this.currentTimestamp = currentTimestamp;
    }
moa.clusterers.denstream.MicroCluster.MicroCluster (Instance instance, int dimensions, long timestamp, double lambda, Timestamp currentTimestamp)
Definition at line 40 of file MicroCluster.java.
{
        this(instance.toDoubleArray(), dimensions, timestamp, lambda, currentTimestamp);
    }
Member Function Documentation
double [] moa.clusterers.denstream.MicroCluster.calcCF1 (long dt) [private]
Definition at line 67 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lambda, and moa.cluster.CFCluster.LS.
Referenced by moa.clusterers.denstream.MicroCluster.getRadius().
{
        double[] cf1 = new double[LS.length];
        for (int i = 0; i < LS.length; i++) {
            cf1[i] = Math.pow(2, -lambda * dt) * LS[i];
        }
        return cf1;
    }
double [] moa.clusterers.denstream.MicroCluster.calcCF2 (long dt) [private]
Definition at line 59 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lambda, and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.denstream.MicroCluster.getRadius().
{
        double[] cf2 = new double[SS.length];
        for (int i = 0; i < SS.length; i++) {
            cf2[i] = Math.pow(2, -lambda * dt) * SS[i];
        }
        return cf2;
    }
MicroCluster moa.clusterers.denstream.MicroCluster.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Reimplemented from moa.AbstractMOAObject.
Definition at line 131 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.currentTimestamp, moa.clusterers.denstream.MicroCluster.getCreationTime(), moa.clusterers.denstream.MicroCluster.lambda, moa.clusterers.denstream.MicroCluster.lastEditT, moa.cluster.CFCluster.LS, moa.clusterers.denstream.MicroCluster.MicroCluster(), moa.cluster.CFCluster.N, moa.cluster.SphereCluster.setWeight(), and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.denstream.MicroCluster.getCF(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        MicroCluster copy = new MicroCluster(this.LS.clone(), this.LS.length, this.getCreationTime(), this.lambda, this.currentTimestamp);
        copy.setWeight(this.N + 1);
        copy.N = this.N;
        copy.SS = this.SS.clone();
        copy.LS = this.LS.clone();
        copy.lastEditT = this.lastEditT;
        return copy;
    }
double [] moa.clusterers.denstream.MicroCluster.getCenter (long timestamp) [private]
Definition at line 94 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.getWeight(), moa.clusterers.denstream.MicroCluster.lambda, moa.clusterers.denstream.MicroCluster.lastEditT, and moa.cluster.CFCluster.LS.
{
        long dt = timestamp - lastEditT;
        double w = getWeight(timestamp);
        double[] res = new double[LS.length];
        for (int i = 0; i < LS.length; i++) {
            res[i] = LS[i];
            res[i] *= Math.pow(2, -lambda * dt);
            res[i] /= w;
        }
        return res;
    }
double [] moa.clusterers.denstream.MicroCluster.getCenter () [virtual]
Returns:
this kernels' center
Reimplemented from moa.cluster.CFCluster.
Definition at line 90 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.currentTimestamp, and moa.clusterers.denstream.Timestamp.getTimestamp().
Referenced by moa.clusterers.denstream.WithDBSCAN.nearestCluster().
{
        return getCenter(currentTimestamp.getTimestamp());
    }
CFCluster moa.clusterers.denstream.MicroCluster.getCF () [virtual]
Implements moa.cluster.CFCluster.
Definition at line 150 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.copy(), moa.clusterers.denstream.MicroCluster.getWeight(), and moa.cluster.CFCluster.setN().
{
        CFCluster cf = copy();
        double w = getWeight();
        cf.setN(w);
        return cf;
    }
long moa.clusterers.denstream.MicroCluster.getCreationTime ()
Definition at line 85 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.creationTimestamp.
Referenced by moa.clusterers.denstream.MicroCluster.copy().
{
        return creationTimestamp;
    }
double moa.clusterers.denstream.MicroCluster.getInclusionProbability (Instance instance) [virtual]
Returns the probability of the given point belonging to this cluster.
Parameters:
point
Returns:
a value between 0 and 1
Implements moa.cluster.CFCluster.
Definition at line 142 of file MicroCluster.java.
References moa.cluster.SphereCluster.getCenterDistance(), and moa.clusterers.denstream.MicroCluster.getRadius().
{
        if (getCenterDistance(instance) <= getRadius()) {
            return 1.0;
        }
        return 0.0;
    }
long moa.clusterers.denstream.MicroCluster.getLastEditTimestamp ()
Definition at line 55 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lastEditT.
{
        return lastEditT;
    }
double moa.clusterers.denstream.MicroCluster.getRadius (long timestamp)
Definition at line 111 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.calcCF1(), moa.clusterers.denstream.MicroCluster.calcCF2(), moa.clusterers.denstream.MicroCluster.getWeight(), moa.clusterers.denstream.MicroCluster.lastEditT, and moa.cluster.CFCluster.SS.
{
        long dt = timestamp - lastEditT;
        double[] cf1 = calcCF1(dt);
        double[] cf2 = calcCF2(dt);
        double w = getWeight(timestamp);
        double max = 0;
        double sum = 0;
        for (int i = 0; i < SS.length; i++) {
            double x1 = cf2[i] / w;
            double x2 = Math.pow(cf1[i] / w, 2);
            //sum += Math.pow(x1 - x2,2);
            sum += (x1 - x2);
            if (Math.sqrt(x1 - x2) > max) {
                max = Math.sqrt(x1 - x2);
            }
        }
        return max;
    }
double moa.clusterers.denstream.MicroCluster.getRadius () [virtual]
See interface Cluster.
Returns:
The radius of the cluster.
Implements moa.cluster.CFCluster.
Definition at line 107 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.currentTimestamp, moa.clusterers.denstream.Timestamp.getTimestamp(), and moa.cluster.CFCluster.radiusFactor.
Referenced by moa.clusterers.denstream.MicroCluster.getInclusionProbability(), moa.clusterers.denstream.WithDBSCAN.nearestCluster(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        return getRadius(currentTimestamp.getTimestamp())*radiusFactor;
    }
double moa.clusterers.denstream.MicroCluster.getWeight (long timestamp) [private]
Definition at line 80 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lambda, moa.clusterers.denstream.MicroCluster.lastEditT, and moa.cluster.CFCluster.N.
{
        long dt = timestamp - lastEditT;
        return (N * Math.pow(2, -lambda * dt));
    }
double moa.clusterers.denstream.MicroCluster.getWeight () [virtual]
See interface Cluster.
Returns:
The weight.
See also:
Cluster.getWeight()
Reimplemented from moa.cluster.CFCluster.
Definition at line 76 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.currentTimestamp, and moa.clusterers.denstream.Timestamp.getTimestamp().
Referenced by moa.clusterers.denstream.MicroCluster.getCenter(), moa.clusterers.denstream.MicroCluster.getCF(), moa.clusterers.denstream.MicroCluster.getRadius(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        return getWeight(currentTimestamp.getTimestamp());
    }
void moa.clusterers.denstream.MicroCluster.insert (Instance instance, long timestamp)
Definition at line 44 of file MicroCluster.java.
References moa.clusterers.denstream.MicroCluster.lastEditT, moa.cluster.CFCluster.LS, moa.cluster.CFCluster.N, and moa.cluster.CFCluster.SS.
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        N++;
        super.setWeight(super.getWeight() + 1);
        this.lastEditT = timestamp;
        for (int i = 0; i < instance.numValues(); i++) {
            LS[i] += instance.value(i);
            SS[i] += instance.value(i) * instance.value(i);
        }
    }
Member Data Documentation
long moa.clusterers.denstream.MicroCluster.creationTimestamp = -1 [private]
Definition at line 28 of file MicroCluster.java.
Referenced by moa.clusterers.denstream.MicroCluster.getCreationTime().
Timestamp moa.clusterers.denstream.MicroCluster.currentTimestamp [private]
Definition at line 30 of file MicroCluster.java.
Referenced by moa.clusterers.denstream.MicroCluster.copy(), moa.clusterers.denstream.MicroCluster.getCenter(), moa.clusterers.denstream.MicroCluster.getRadius(), and moa.clusterers.denstream.MicroCluster.getWeight().
double moa.clusterers.denstream.MicroCluster.lambda [private]
Definition at line 29 of file MicroCluster.java.
Referenced by moa.clusterers.denstream.MicroCluster.calcCF1(), moa.clusterers.denstream.MicroCluster.calcCF2(), moa.clusterers.denstream.MicroCluster.copy(), moa.clusterers.denstream.MicroCluster.getCenter(), and moa.clusterers.denstream.MicroCluster.getWeight().
long moa.clusterers.denstream.MicroCluster.lastEditT = -1 [private]
Definition at line 27 of file MicroCluster.java.
Referenced by moa.clusterers.denstream.MicroCluster.copy(), moa.clusterers.denstream.MicroCluster.getCenter(), moa.clusterers.denstream.MicroCluster.getLastEditTimestamp(), moa.clusterers.denstream.MicroCluster.getRadius(), moa.clusterers.denstream.MicroCluster.getWeight(), moa.clusterers.denstream.MicroCluster.insert(), and moa.clusterers.denstream.MicroCluster.MicroCluster().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/denstream/MicroCluster.java