MOA: moa.classifiers.trees.HoeffdingOptionTree Class Reference
moa.classifiers.trees.HoeffdingOptionTree Class Reference
Hoeffding Option Tree.
Classes
class ActiveLearningNode
class FoundNode
class InactiveLearningNode
class LearningNode
class LearningNodeNB
class LearningNodeNBAdaptive
class Node
class SplitNode
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
int calcByteSize ()
int measureByteSize ()
Gets the memory size of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
int measureTreeDepth ()
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void enforceTrackerLimit ()
void estimateModelByteSizes ()
void deactivateAllLeaves ()
Static Public Member Functions
static double computeHoeffdingBound (double range, double confidence, double n)
Public Attributes
IntOption maxOptionPathsOption
IntOption maxByteSizeOption
ClassOption numericEstimatorOption
ClassOption nominalEstimatorOption
IntOption memoryEstimatePeriodOption
IntOption gracePeriodOption
ClassOption splitCriterionOption
FloatOption splitConfidenceOption
FloatOption secondarySplitConfidenceOption
FloatOption tieThresholdOption
FlagOption binarySplitsOption
FlagOption removePoorAttsOption
FlagOption noPrePruneOption
FileOption dumpFileOption
IntOption memoryStrategyOption
MultiChoiceOption leafpredictionOption
IntOption nbThresholdOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
AttributeClassObserver newNominalClassObserver ()
AttributeClassObserver newNumericClassObserver ()
void attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex)
void deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch)
void activateLearningNode (InactiveLearningNode toActivate, SplitNode parent, int parentBranch)
FoundNode[] findLearningNodes ()
void findLearningNodes (Node node, SplitNode parent, int parentBranch, List< FoundNode > found)
LearningNode newLearningNode ()
LearningNode newLearningNode (double[] initialClassObservations)
Protected Attributes
Node treeRoot
int decisionNodeCount
int activeLeafNodeCount
int inactiveLeafNodeCount
double inactiveLeafByteSizeEstimate
double activeLeafByteSizeEstimate
double byteSizeEstimateOverheadFraction
int maxPredictionPaths
Private Member Functions
void addToOptionTable (AttributeSplitSuggestion bestSuggestion, SplitNode parent)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Hoeffding Option Tree.
Hoeffding Option Trees are regular Hoeffding trees containing additional option nodes that allow several tests to be applied, leading to multiple Hoeffding trees as separate paths. They consist of a single structure that efﬁciently represents multiple trees. A particular example can travel down multiple paths of the tree, contributing, in different ways, to different options.
See for details:
B. Pfahringer, G. Holmes, and R. Kirkby. New options for hoeffding trees. In AI, pages 90–99, 2007.
Parameters:
-o : Maximum number of option paths per node
-m : Maximum memory consumed by the tree
-n : Numeric estimator to use :
Gaussian approximation evaluating 10 splitpoints
Gaussian approximation evaluating 100 splitpoints
Greenwald-Khanna quantile summary with 10 tuples
Greenwald-Khanna quantile summary with 100 tuples
Greenwald-Khanna quantile summary with 1000 tuples
VFML method with 10 bins
VFML method with 100 bins
VFML method with 1000 bins
Exhaustive binary tree
-e : How many instances between memory consumption checks
-g : The number of instances a leaf should observe between split attempts
-s : Split criterion to use. Example : InfoGainSplitCriterion
-c : The allowable error in split decision, values closer to 0 will take longer to decide
-w : The allowable error in secondary split decisions, values closer to 0 will take longer to decide
-t : Threshold below which a split will be forced to break ties
-b : Only allow binary splits
-z : Memory strategy to use
-r : Disable poor attributes
-p : Disable pre-pruning
-d : File to append option table to.
-l : Leaf prediction to use: MajorityClass (MC), Naive Bayes (NB) or NaiveBayes adaptive (NBAdaptive).
-q : The number of instances a leaf should observe before permitting Naive Bayes
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 98 of file HoeffdingOptionTree.java.
Member Function Documentation
void moa.classifiers.trees.HoeffdingOptionTree.activateLearningNode (InactiveLearningNode toActivate, SplitNode parent, int parentBranch) [protected]
Definition at line 1082 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild().
{
        Node newLeaf = newLearningNode(toActivate.getObservedClassDistribution());
        if (parent == null) {
            this.treeRoot = newLeaf;
        } else {
            if (parentBranch != -999) {
                parent.setChild(parentBranch, newLeaf);
            } else {
                parent.nextOption = newLeaf;
            }
        }
        this.activeLeafNodeCount++;
        this.inactiveLeafNodeCount--;
    }
void moa.classifiers.trees.HoeffdingOptionTree.addToOptionTable (AttributeSplitSuggestion bestSuggestion, SplitNode parent) [private]
Definition at line 920 of file HoeffdingOptionTree.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn(), moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest.getSplitValue(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.parent, and moa.classifiers.core.AttributeSplitSuggestion.splitTest.
{
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException("Unable to open dump file: "
                        + dumpFile, ex);
            }
            int splitAtt = bestSuggestion.splitTest.getAttsTestDependsOn()[0];
            double splitVal = -1.0;
            if (bestSuggestion.splitTest instanceof NumericAttributeBinaryTest) {
                NumericAttributeBinaryTest test = (NumericAttributeBinaryTest) bestSuggestion.splitTest;
                splitVal = test.getSplitValue();
            }
            int treeDepth = 0;
            while (parent != null) {
                parent = parent.parent;
                treeDepth++;
            }
            immediateResultStream.println(this.trainingWeightSeenByModel + ","
                    + treeDepth + "," + splitAtt + "," + splitVal);
            immediateResultStream.flush();
            immediateResultStream.close();
        }
    }
void moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit (ActiveLearningNode node, SplitNode parent, int parentIndex) [protected]
Definition at line 771 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.computeMeritOfExistingSplit(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.disableAttribute(), moa.classifiers.core.conditionaltests.InstanceConditionalTest.getAttsTestDependsOn(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution(), moa.classifiers.core.splitcriteria.SplitCriterion.getRangeOfMerit(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.core.AttributeSplitSuggestion.merit, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, moa.classifiers.core.AttributeSplitSuggestion.numSplits(), moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistributionIsPure(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.parent, moa.classifiers.core.AttributeSplitSuggestion.resultingClassDistributionFromSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild(), moa.classifiers.core.AttributeSplitSuggestion.splitTest, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
{
        if (!node.observedClassDistributionIsPure()) {
            SplitCriterion splitCriterion = (SplitCriterion) getPreparedClassOption(this.splitCriterionOption);
            AttributeSplitSuggestion[] bestSplitSuggestions = node.getBestSplitSuggestions(splitCriterion, this);
            Arrays.sort(bestSplitSuggestions);
            boolean shouldSplit = false;
            if (parentIndex != -999) {
                if (bestSplitSuggestions.length < 2) {
                    shouldSplit = bestSplitSuggestions.length > 0;
                } else {
                    double hoeffdingBound = computeHoeffdingBound(
                            splitCriterion.getRangeOfMerit(node.getObservedClassDistribution()),
                            this.splitConfidenceOption.getValue(), node.getWeightSeen());
                    AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                    AttributeSplitSuggestion secondBestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 2];
                    if ((bestSuggestion.merit - secondBestSuggestion.merit > hoeffdingBound)
                            || (hoeffdingBound < this.tieThresholdOption.getValue())) {
                        shouldSplit = true;
                    }
                    if ((this.removePoorAttsOption != null)
                            && this.removePoorAttsOption.isSet()) {
                        Set<Integer> poorAtts = new HashSet<Integer>();
                        // scan 1 - add any poor to set
                        for (int i = 0; i < bestSplitSuggestions.length; i++) {
                            if (bestSplitSuggestions[i].splitTest != null) {
                                int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                                if (splitAtts.length == 1) {
                                    if (bestSuggestion.merit
                                            - bestSplitSuggestions[i].merit > hoeffdingBound) {
                                        poorAtts.add(new Integer(splitAtts[0]));
                                    }
                                }
                            }
                        }
                        // scan 2 - remove good ones from set
                        for (int i = 0; i < bestSplitSuggestions.length; i++) {
                            if (bestSplitSuggestions[i].splitTest != null) {
                                int[] splitAtts = bestSplitSuggestions[i].splitTest.getAttsTestDependsOn();
                                if (splitAtts.length == 1) {
                                    if (bestSuggestion.merit
                                            - bestSplitSuggestions[i].merit < hoeffdingBound) {
                                        poorAtts.remove(new Integer(
                                                splitAtts[0]));
                                    }
                                }
                            }
                        }
                        for (int poorAtt : poorAtts) {
                            node.disableAttribute(poorAtt);
                        }
                    }
                }
            } else if (bestSplitSuggestions.length > 0) {
                double hoeffdingBound = computeHoeffdingBound(splitCriterion.getRangeOfMerit(node.getObservedClassDistribution()),
                        this.secondarySplitConfidenceOption.getValue(), node.getWeightSeen());
                AttributeSplitSuggestion bestSuggestion = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                // in option case, scan back through existing options to
                // find best
                SplitNode current = parent;
                double bestPreviousMerit = Double.NEGATIVE_INFINITY;
                double[] preDist = node.getObservedClassDistribution();
                while (true) {
                    double merit = current.computeMeritOfExistingSplit(
                            splitCriterion, preDist);
                    if (merit > bestPreviousMerit) {
                        bestPreviousMerit = merit;
                    }
                    if (current.optionCount != -999) {
                        break;
                    }
                    current = current.parent;
                }
                if (bestSuggestion.merit - bestPreviousMerit > hoeffdingBound) {
                    shouldSplit = true;
                }
            }
            if (shouldSplit) {
                AttributeSplitSuggestion splitDecision = bestSplitSuggestions[bestSplitSuggestions.length - 1];
                if (splitDecision.splitTest == null) {
                    // preprune - null wins
                    if (parentIndex != -999) {
                        deactivateLearningNode(node, parent, parentIndex);
                    }
                } else {
                    SplitNode newSplit = new SplitNode(splitDecision.splitTest,
                            node.getObservedClassDistribution());
                    newSplit.parent = parent;
                    // add option procedure
                    SplitNode optionHead = parent;
                    if (parent != null) {
                        while (optionHead.optionCount == -999) {
                            optionHead = optionHead.parent;
                        }
                    }
                    if ((parentIndex == -999) && (parent != null)) {
                        // adding a new option
                        newSplit.optionCount = -999;
                        optionHead.updateOptionCountBelow(1, this);
                        if (optionHead.parent != null) {
                            optionHead.parent.updateOptionCount(optionHead,
                                    this);
                        }
                        addToOptionTable(splitDecision, optionHead.parent);
                    } else {
                        // adding a regular leaf
                        if (optionHead == null) {
                            newSplit.optionCount = 1;
                        } else {
                            newSplit.optionCount = optionHead.optionCount;
                        }
                    }
                    int numOptions = 1;
                    if (optionHead != null) {
                        numOptions = optionHead.optionCount;
                    }
                    if (numOptions < this.maxOptionPathsOption.getValue()) {
                        newSplit.nextOption = node; // preserve leaf
                        // disable attribute just used
                        int[] splitAtts = splitDecision.splitTest.getAttsTestDependsOn();
                        for (int i : splitAtts) {
                            node.disableAttribute(i);
                        }
                    } else {
                        this.activeLeafNodeCount--;
                    }
                    for (int i = 0; i < splitDecision.numSplits(); i++) {
                        Node newChild = newLearningNode(splitDecision.resultingClassDistributionFromSplit(i));
                        newSplit.setChild(i, newChild);
                    }
                    this.decisionNodeCount++;
                    this.activeLeafNodeCount += splitDecision.numSplits();
                    if (parent == null) {
                        this.treeRoot = newSplit;
                    } else {
                        if (parentIndex != -999) {
                            parent.setChild(parentIndex, newSplit);
                        } else {
                            parent.nextOption = newSplit;
                        }
                    }
                }
                // manage memory
                enforceTrackerLimit();
            }
        }
    }
int moa.classifiers.trees.HoeffdingOptionTree.calcByteSize ()
Definition at line 621 of file HoeffdingOptionTree.java.
{
        int size = (int) SizeOf.sizeOf(this);
        if (this.treeRoot != null) {
            size += this.treeRoot.calcByteSizeIncludingSubtree();
        }
        return size;
    }
static double moa.classifiers.trees.HoeffdingOptionTree.computeHoeffdingBound (double range, double confidence, double n) [static]
Definition at line 755 of file HoeffdingOptionTree.java.
                      {
        return Math.sqrt(((range * range) * Math.log(1.0 / confidence))
                / (2.0 * n));
    }
void moa.classifiers.trees.HoeffdingOptionTree.deactivateAllLeaves ()
Definition at line 1055 of file HoeffdingOptionTree.java.
{
        FoundNode[] learningNodes = findLearningNodes();
        for (int i = 0; i < learningNodes.length; i++) {
            if (learningNodes[i].node instanceof ActiveLearningNode) {
                deactivateLearningNode(
                        (ActiveLearningNode) learningNodes[i].node,
                        learningNodes[i].parent, learningNodes[i].parentBranch);
            }
        }
    }
void moa.classifiers.trees.HoeffdingOptionTree.deactivateLearningNode (ActiveLearningNode toDeactivate, SplitNode parent, int parentBranch) [protected]
Definition at line 1066 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.getObservedClassDistribution(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild().
{
        Node newLeaf = new InactiveLearningNode(toDeactivate.getObservedClassDistribution());
        if (parent == null) {
            this.treeRoot = newLeaf;
        } else {
            if (parentBranch != -999) {
                parent.setChild(parentBranch, newLeaf);
            } else {
                parent.nextOption = newLeaf;
            }
        }
        this.activeLeafNodeCount--;
        this.inactiveLeafNodeCount++;
    }
void moa.classifiers.trees.HoeffdingOptionTree.enforceTrackerLimit ()
Definition at line 955 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getHeadOptionCount(), moa.classifiers.trees.HoeffdingOptionTree.FoundNode.node, moa.classifiers.trees.HoeffdingOptionTree.FoundNode.parent, and moa.classifiers.trees.HoeffdingOptionTree.FoundNode.parentBranch.
{
        if ((this.inactiveLeafNodeCount > 0)
                || ((this.activeLeafNodeCount * this.activeLeafByteSizeEstimate + this.inactiveLeafNodeCount
                * this.inactiveLeafByteSizeEstimate)
                * this.byteSizeEstimateOverheadFraction > this.maxByteSizeOption.getValue())) {
            FoundNode[] learningNodes = findLearningNodes();
            Arrays.sort(learningNodes, new Comparator<FoundNode>() {
                public int compare(FoundNode fn1, FoundNode fn2) {
                    if (HoeffdingOptionTree.this.memoryStrategyOption.getValue() == 0) {
                        // strategy 1 - every leaf treated equal
                        return Double.compare(fn1.node.calculatePromise(),
                                fn2.node.calculatePromise());
                    } else if (HoeffdingOptionTree.this.memoryStrategyOption.getValue() == 1) {
                        // strategy 2 - internal leaves penalised
                        double p1 = fn1.node.calculatePromise();
                        if (fn1.parentBranch == -999) {
                            p1 /= fn1.parent.getHeadOptionCount();
                        }
                        double p2 = fn2.node.calculatePromise();
                        if (fn2.parentBranch == -999) {
                            p1 /= fn2.parent.getHeadOptionCount();
                        }
                        return Double.compare(p1, p2);
                    } else {
                        // strategy 3 - all true leaves beat internal leaves
                        if (fn1.parentBranch == -999) {
                            if (fn2.parentBranch == -999) {
                                return Double.compare(fn1.node.calculatePromise(), fn2.node.calculatePromise());
                            }
                            return -1; // fn1 < fn2
                        }
                        if (fn2.parentBranch == -999) {
                            return 1; // fn1 > fn2
                        }
                        return Double.compare(fn1.node.calculatePromise(),
                                fn2.node.calculatePromise());
                    }
                }
            });
            int maxActive = 0;
            while (maxActive < learningNodes.length) {
                maxActive++;
                if ((maxActive * this.activeLeafByteSizeEstimate + (learningNodes.length - maxActive)
                        * this.inactiveLeafByteSizeEstimate)
                        * this.byteSizeEstimateOverheadFraction > this.maxByteSizeOption.getValue()) {
                    maxActive--;
                    break;
                }
            }
            int cutoff = learningNodes.length - maxActive;
            for (int i = 0; i < cutoff; i++) {
                if (learningNodes[i].node instanceof ActiveLearningNode) {
                    deactivateLearningNode(
                            (ActiveLearningNode) learningNodes[i].node,
                            learningNodes[i].parent,
                            learningNodes[i].parentBranch);
                }
            }
            for (int i = cutoff; i < learningNodes.length; i++) {
                if (learningNodes[i].node instanceof InactiveLearningNode) {
                    activateLearningNode(
                            (InactiveLearningNode) learningNodes[i].node,
                            learningNodes[i].parent,
                            learningNodes[i].parentBranch);
                }
            }
        }
    }
void moa.classifiers.trees.HoeffdingOptionTree.estimateModelByteSizes ()
Definition at line 1025 of file HoeffdingOptionTree.java.
{
        FoundNode[] learningNodes = findLearningNodes();
        long totalActiveSize = 0;
        long totalInactiveSize = 0;
        for (FoundNode foundNode : learningNodes) {
            if (foundNode.node instanceof ActiveLearningNode) {
                totalActiveSize += SizeOf.fullSizeOf(foundNode.node);
            } else {
                totalInactiveSize += SizeOf.fullSizeOf(foundNode.node);
            }
        }
        if (totalActiveSize > 0) {
            this.activeLeafByteSizeEstimate = (double) totalActiveSize
                    / this.activeLeafNodeCount;
        }
        if (totalInactiveSize > 0) {
            this.inactiveLeafByteSizeEstimate = (double) totalInactiveSize
                    / this.inactiveLeafNodeCount;
        }
        int actualModelSize = this.measureByteSize();
        double estimatedModelSize = (this.activeLeafNodeCount
                * this.activeLeafByteSizeEstimate + this.inactiveLeafNodeCount
                * this.inactiveLeafByteSizeEstimate);
        this.byteSizeEstimateOverheadFraction = actualModelSize
                / estimatedModelSize;
        if (actualModelSize > this.maxByteSizeOption.getValue()) {
            enforceTrackerLimit();
        }
    }
void moa.classifiers.trees.HoeffdingOptionTree.findLearningNodes (Node node, SplitNode parent, int parentBranch, List< FoundNode > found) [protected]
Definition at line 1104 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getChild(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.numChildren().
{
        if (node != null) {
            if (node instanceof LearningNode) {
                found.add(new FoundNode(node, parent, parentBranch));
            }
            if (node instanceof SplitNode) {
                SplitNode splitNode = (SplitNode) node;
                for (int i = 0; i < splitNode.numChildren(); i++) {
                    findLearningNodes(splitNode.getChild(i), splitNode, i,
                            found);
                }
                findLearningNodes(splitNode.nextOption, splitNode, -999, found);
            }
        }
    }
FoundNode [] moa.classifiers.trees.HoeffdingOptionTree.findLearningNodes () [protected]
Definition at line 1098 of file HoeffdingOptionTree.java.
{
        List<FoundNode> foundList = new LinkedList<FoundNode>();
        findLearningNodes(this.treeRoot, null, -1, foundList);
        return foundList.toArray(new FoundNode[foundList.size()]);
    }
void moa.classifiers.trees.HoeffdingOptionTree.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 746 of file HoeffdingOptionTree.java.
{
        this.treeRoot.describeSubtree(this, out, indent);
    }
Measurement [] moa.classifiers.trees.HoeffdingOptionTree.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 719 of file HoeffdingOptionTree.java.
{
        return new Measurement[]{
            new Measurement("tree size (nodes)", this.decisionNodeCount
            + this.activeLeafNodeCount + this.inactiveLeafNodeCount),
            new Measurement("tree size (leaves)", this.activeLeafNodeCount
            + this.inactiveLeafNodeCount),
            new Measurement("active learning leaves",
            this.activeLeafNodeCount),
            new Measurement("tree depth", measureTreeDepth()),
            new Measurement("active leaf byte size estimate",
            this.activeLeafByteSizeEstimate),
            new Measurement("inactive leaf byte size estimate",
            this.inactiveLeafByteSizeEstimate),
            new Measurement("byte size estimate overhead",
            this.byteSizeEstimateOverheadFraction),
            new Measurement("maximum prediction paths used",
            this.maxPredictionPaths)};
    }
String moa.classifiers.trees.HoeffdingOptionTree.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.
Definition at line 103 of file HoeffdingOptionTree.java.
{
        return "Hoeffding Option Tree: single tree that represents multiple trees.";
    }
double [] moa.classifiers.trees.HoeffdingOptionTree.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 688 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.addValues(), moa.core.DoubleVector.getArrayRef(), and moa.classifiers.trees.HoeffdingOptionTree.Node.getClassVotes().
{
        if (this.treeRoot != null) {
            FoundNode[] foundNodes = this.treeRoot.filterInstanceToLeaves(inst,
                    null, -1, false);
            DoubleVector result = new DoubleVector();
            int predictionPaths = 0;
            for (FoundNode foundNode : foundNodes) {
                if (foundNode.parentBranch != -999) {
                    Node leafNode = foundNode.node;
                    if (leafNode == null) {
                        leafNode = foundNode.parent;
                    }
                    double[] dist = leafNode.getClassVotes(inst, this);
                    //Albert: changed for weights
                    //double distSum = Utils.sum(dist);
                    //if (distSum > 0.0) {
                    //  Utils.normalize(dist, distSum);
                    //}
                    result.addValues(dist);
                    predictionPaths++;
                }
            }
            if (predictionPaths > this.maxPredictionPaths) {
                this.maxPredictionPaths++;
            }
            return result.getArrayRef();
        }
        return new double[0];
    }
boolean moa.classifiers.trees.HoeffdingOptionTree.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 751 of file HoeffdingOptionTree.java.
{
        return false;
    }
int moa.classifiers.trees.HoeffdingOptionTree.measureByteSize ()
Gets the memory size of this object.
Returns:
the memory size of this object
Reimplemented from moa.AbstractMOAObject.
Definition at line 630 of file HoeffdingOptionTree.java.
{
        return calcByteSize();
    }
int moa.classifiers.trees.HoeffdingOptionTree.measureTreeDepth ()
Definition at line 738 of file HoeffdingOptionTree.java.
{
        if (this.treeRoot != null) {
            return this.treeRoot.subtreeDepth();
        }
        return 0;
    }
LearningNode moa.classifiers.trees.HoeffdingOptionTree.newLearningNode (double[] initialClassObservations) [protected]
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.
Definition at line 1197 of file HoeffdingOptionTree.java.
{
        LearningNode ret;
        int predictionOption = this.leafpredictionOption.getChosenIndex();
        if (predictionOption == 0) { //MC
            ret = new ActiveLearningNode(initialClassObservations);
        } else if (predictionOption == 1) { //NB
            ret = new LearningNodeNB(initialClassObservations);
        } else { //NBAdaptive
            ret = new LearningNodeNBAdaptive(initialClassObservations);
        }
        if (ret == null) {
            System.out.println("error");
        }
        return ret;
    }
LearningNode moa.classifiers.trees.HoeffdingOptionTree.newLearningNode () [protected]
Definition at line 1193 of file HoeffdingOptionTree.java.
{
        return newLearningNode(new double[0]);
    }
AttributeClassObserver moa.classifiers.trees.HoeffdingOptionTree.newNominalClassObserver () [protected]
Definition at line 761 of file HoeffdingOptionTree.java.
References moa.options.OptionHandler.copy().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance().
{
        AttributeClassObserver nominalClassObserver = (AttributeClassObserver) getPreparedClassOption(this.nominalEstimatorOption);
        return (AttributeClassObserver) nominalClassObserver.copy();
    }
AttributeClassObserver moa.classifiers.trees.HoeffdingOptionTree.newNumericClassObserver () [protected]
Definition at line 766 of file HoeffdingOptionTree.java.
References moa.options.OptionHandler.copy().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance().
{
        AttributeClassObserver numericClassObserver = (AttributeClassObserver) getPreparedClassOption(this.numericEstimatorOption);
        return (AttributeClassObserver) numericClassObserver.copy();
    }
void moa.classifiers.trees.HoeffdingOptionTree.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 635 of file HoeffdingOptionTree.java.
{
        this.treeRoot = null;
        this.decisionNodeCount = 0;
        this.activeLeafNodeCount = 0;
        this.inactiveLeafNodeCount = 0;
        this.inactiveLeafByteSizeEstimate = 0.0;
        this.activeLeafByteSizeEstimate = 0.0;
        this.byteSizeEstimateOverheadFraction = 1.0;
        this.maxPredictionPaths = 0;
        if (this.leafpredictionOption.getChosenIndex() > 0) {
            this.removePoorAttsOption = null;
        }
    }
void moa.classifiers.trees.HoeffdingOptionTree.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 650 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation(), moa.classifiers.trees.HoeffdingOptionTree.LearningNode.learnFromInstance(), and moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation().
{
        if (this.treeRoot == null) {
            this.treeRoot = newLearningNode();
            this.activeLeafNodeCount = 1;
        }
        FoundNode[] foundNodes = this.treeRoot.filterInstanceToLeaves(inst,
                null, -1, true);
        for (FoundNode foundNode : foundNodes) {
            // option leaves will have a parentBranch of -999
            // option splits will have an option count of -999
            Node leafNode = foundNode.node;
            if (leafNode == null) {
                leafNode = newLearningNode();
                foundNode.parent.setChild(foundNode.parentBranch, leafNode);
                this.activeLeafNodeCount++;
            }
            if (leafNode instanceof LearningNode) {
                LearningNode learningNode = (LearningNode) leafNode;
                learningNode.learnFromInstance(inst, this);
                if (learningNode instanceof ActiveLearningNode) {
                    ActiveLearningNode activeLearningNode = (ActiveLearningNode) learningNode;
                    double weightSeen = activeLearningNode.getWeightSeen();
                    if (weightSeen
                            - activeLearningNode.getWeightSeenAtLastSplitEvaluation() >= this.gracePeriodOption.getValue()) {
                        attemptToSplit(activeLearningNode, foundNode.parent,
                                foundNode.parentBranch);
                        activeLearningNode.setWeightSeenAtLastSplitEvaluation(weightSeen);
                    }
                }
            }
        }
        if (this.trainingWeightSeenByModel
                % this.memoryEstimatePeriodOption.getValue() == 0) {
            estimateModelByteSizes();
        }
    }
Member Data Documentation
double moa.classifiers.trees.HoeffdingOptionTree.activeLeafByteSizeEstimate [protected]
Definition at line 615 of file HoeffdingOptionTree.java.
int moa.classifiers.trees.HoeffdingOptionTree.activeLeafNodeCount [protected]
Definition at line 609 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf().
FlagOption moa.classifiers.trees.HoeffdingOptionTree.binarySplitsOption
Initial value:
 new FlagOption("binarySplits", 'b',
            "Only allow binary splits.")
Definition at line 165 of file HoeffdingOptionTree.java.
double moa.classifiers.trees.HoeffdingOptionTree.byteSizeEstimateOverheadFraction [protected]
Definition at line 617 of file HoeffdingOptionTree.java.
int moa.classifiers.trees.HoeffdingOptionTree.decisionNodeCount [protected]
Definition at line 607 of file HoeffdingOptionTree.java.
FileOption moa.classifiers.trees.HoeffdingOptionTree.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'f',
            "File to append option table to.", null, "csv", true)
Definition at line 174 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.gracePeriodOption
Initial value:
 new IntOption(
            "gracePeriod",
            'g',
            "The number of instances a leaf should observe between split attempts.",
            200, 0, Integer.MAX_VALUE)
Definition at line 139 of file HoeffdingOptionTree.java.
double moa.classifiers.trees.HoeffdingOptionTree.inactiveLeafByteSizeEstimate [protected]
Definition at line 613 of file HoeffdingOptionTree.java.
int moa.classifiers.trees.HoeffdingOptionTree.inactiveLeafNodeCount [protected]
Definition at line 611 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf().
MultiChoiceOption moa.classifiers.trees.HoeffdingOptionTree.leafpredictionOption
Initial value:
 new MultiChoiceOption(
            "leafprediction", 'l', "Leaf prediction to use.", new String[]{
                "MC", "NB", "NBAdaptive"}, new String[]{
                "Majority class",
                "Naive Bayes",
                "Naive Bayes Adaptive"}, 2)
Definition at line 1121 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.maxByteSizeOption
Initial value:
 new IntOption("maxByteSize", 'm',
            "Maximum memory consumed by the tree.", 33554432, 0,
            Integer.MAX_VALUE)
Definition at line 111 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.maxOptionPathsOption
Initial value:
 new IntOption("maxOptionPaths",
            'o', "Maximum number of option paths per node.", 5, 1,
            Integer.MAX_VALUE)
Definition at line 107 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
int moa.classifiers.trees.HoeffdingOptionTree.maxPredictionPaths [protected]
Definition at line 619 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.memoryEstimatePeriodOption
Initial value:
 new IntOption(
            "memoryEstimatePeriod", 'e',
            "How many instances between memory consumption checks.", 1000000,
            0, Integer.MAX_VALUE)
Definition at line 134 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.memoryStrategyOption
Initial value:
 new IntOption("memStrategy", 'z',
            "Memory strategy to use.", 2)
Definition at line 177 of file HoeffdingOptionTree.java.
IntOption moa.classifiers.trees.HoeffdingOptionTree.nbThresholdOption
Initial value:
 new IntOption(
            "nbThreshold",
            'q',
            "The number of instances a leaf should observe before permitting Naive Bayes.",
            0, 0, Integer.MAX_VALUE)
Definition at line 1128 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB.getClassVotes().
ClassOption moa.classifiers.trees.HoeffdingOptionTree.nominalEstimatorOption
Initial value:
 new ClassOption("nominalEstimator",
            'd', "Nominal estimator to use.", DiscreteAttributeClassObserver.class,
            "NominalAttributeClassObserver")
Definition at line 130 of file HoeffdingOptionTree.java.
FlagOption moa.classifiers.trees.HoeffdingOptionTree.noPrePruneOption
Initial value:
 new FlagOption("noPrePrune", 'p',
            "Disable pre-pruning.")
Definition at line 171 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions().
ClassOption moa.classifiers.trees.HoeffdingOptionTree.numericEstimatorOption
Initial value:
 new ClassOption("numericEstimator",
            'n', "Numeric estimator to use.", NumericAttributeClassObserver.class,
            "GaussianNumericAttributeClassObserver")
Definition at line 126 of file HoeffdingOptionTree.java.
FlagOption moa.classifiers.trees.HoeffdingOptionTree.removePoorAttsOption
Initial value:
 new FlagOption("removePoorAtts",
            'r', "Disable poor attributes.")
Definition at line 168 of file HoeffdingOptionTree.java.
FloatOption moa.classifiers.trees.HoeffdingOptionTree.secondarySplitConfidenceOption
Initial value:
 new FloatOption(
            "secondarySplitConfidence",
            'w',
            "The allowable error in secondary split decisions, values closer to 0 will take longer to decide.",
            0.1, 0.0, 1.0)
Definition at line 155 of file HoeffdingOptionTree.java.
final long moa.classifiers.trees.HoeffdingOptionTree.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.trees.AdaHoeffdingOptionTree.
Definition at line 100 of file HoeffdingOptionTree.java.
FloatOption moa.classifiers.trees.HoeffdingOptionTree.splitConfidenceOption
Initial value:
 new FloatOption(
            "splitConfidence",
            'c',
            "The allowable error in split decision, values closer to 0 will take longer to decide.",
            0.0000001, 0.0, 1.0)
Definition at line 149 of file HoeffdingOptionTree.java.
ClassOption moa.classifiers.trees.HoeffdingOptionTree.splitCriterionOption
Initial value:
 new ClassOption("splitCriterion",
            's', "Split criterion to use.", SplitCriterion.class,
            "InfoGainSplitCriterion")
Definition at line 145 of file HoeffdingOptionTree.java.
FloatOption moa.classifiers.trees.HoeffdingOptionTree.tieThresholdOption
Initial value:
 new FloatOption("tieThreshold",
            't', "Threshold below which a split will be forced to break ties.",
            0.05, 0.0, 1.0)
Definition at line 161 of file HoeffdingOptionTree.java.
Node moa.classifiers.trees.HoeffdingOptionTree.treeRoot [protected]
Definition at line 605 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingOptionTree.java