MOA: moa.clusterers.outliers.Angiulli.ExactSTORM Class Reference
moa.clusterers.outliers.Angiulli.ExactSTORM Class Reference
Classes
class ISBNodeExact
Public Member Functions
ExactSTORM ()
String getObjectInfo (Object obj)
void Init ()
Public Attributes
FloatOption radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
IntOption kOption = new IntOption("k", 't', "Parameter k.", 50)
IntOption queryFreqOption = new IntOption("queryFreq", 'q', "Query frequency.", 1)
Protected Member Functions
void ProcessNewStreamObj (Instance inst)
Package Functions
void RemoveNode (ISBNode node)
void DeleteExpiredNode ()
void SearchOutliers ()
void UpdateNodeType (ISBNodeExact node)
void UpdateNodeStatistics (ISBNodeExact node)
Detailed Description
Definition at line 37 of file ExactSTORM.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.Angiulli.ExactSTORM.ExactSTORM ()
Definition at line 94 of file ExactSTORM.java.
    {
        // System.out.println("DistanceOutliersExact: created");
    }
Member Function Documentation
void moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode () [package]
Definition at line 175 of file ExactSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj().
{
        if (windowNodes.size() <= 0)
            return;
        // get oldest node
        ISBNode node = windowNodes.get(0);
        // check if node has expired
        if (node.id < GetWindowStart()) {
            if (bTrace) {
                Print("Delete expired node: ");
                PrintNode(node);
            }
            // remove node
            RemoveNode(node);
        }
    }
String moa.clusterers.outliers.Angiulli.ExactSTORM.getObjectInfo (Object obj)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 100 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after, moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.CountPrecNeighs(), moa.clusterers.outliers.Angiulli.StreamObj.dimensions(), moa.clusterers.outliers.Angiulli.StreamObj.get(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
{
        if (obj == null) return null;
        ISBNodeExact node = (ISBNodeExact) obj;
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        StringBuilder sb = new StringBuilder();
        // show node position
        for (int i = 0; i < node.obj.dimensions(); i++) {
            infoTitle.add("Dim" + (i+1));
            infoValue.add(String.format("%.3f", node.obj.get(i)));
        }
        // show node properties
        infoTitle.add("id");
        infoValue.add(String.format("%d", node.id));
        infoTitle.add("count_after");
        infoValue.add(String.format("%d", node.count_after));
        infoTitle.add("|nn_before|");
        infoValue.add(String.format("%d", node.CountPrecNeighs(GetWindowStart())));
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td><b>"+infoTitle.get(i)+":</b></td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.Init ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 138 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ExactSTORM.kOption, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_nBothInlierOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyInlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_QueryFreq, moa.clusterers.outliers.Angiulli.STORMBase.m_radius, moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize, moa.clusterers.outliers.Angiulli.STORMBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.ExactSTORM.queryFreqOption, moa.clusterers.outliers.Angiulli.ExactSTORM.radiusOption, moa.clusterers.outliers.Angiulli.STORMBase.windowNodes, and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
                       {
        super.Init();
        m_WindowSize = windowSizeOption.getValue();
        m_radius = radiusOption.getValue();
        m_k = kOption.getValue();
        m_QueryFreq = queryFreqOption.getValue();
        Println("Init DistanceOutliersExact:");
        Println("   window_size: " + m_WindowSize);
        Println("   radius: " + m_radius);
        Println("   k: " + m_k);
        Println("   query_freq: " + m_QueryFreq);
        objId = FIRST_OBJ_ID; // init object identifier
        // create fifo
        windowNodes = new Vector<ISBNode>();
        // create ISB
        ISB = new ISBIndex(m_radius, m_k);
        // init statistics
        m_nBothInlierOutlier = 0;
        m_nOnlyInlier = 0;
        m_nOnlyOutlier = 0;
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 193 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.AddPrecNeigh(), moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.STORMBase.CanSearch(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after, moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues(), moa.clusterers.outliers.Angiulli.ISBIndex.Insert(), moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_radius, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.Angiulli.STORMBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ISBIndex.RangeSearch(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
    {
        if (bShowProgress) ShowProgress("Processed " + objId + " stream objects.");
        // PrintInstance(inst);
        double[] values = getInstanceValues(inst);
        StreamObj obj = new StreamObj(values);
        if (bTrace) Println("\n- - - - - - - - - - - -\n");
        // create new ISB node
        ISBNodeExact nodeNew = new ISBNodeExact(inst, obj, objId, m_k);
        if (bTrace) {
            Print("New obj: ");
            PrintNode(nodeNew);
        }
        // update object identifier
        objId++;
        // delete a node if it has expired
        DeleteExpiredNode();
        // init nodeNew
        nodeNew.count_after = 1;
        // perform range query search
        if (bTrace) Println("Perform range query seach:");
        nRangeQueriesExecuted++;
        Vector<ISBIndex.ISBSearchResult> nodes = ISB.RangeSearch(nodeNew, m_radius);
        // process each returned node
        for (ISBSearchResult res : nodes) {
            ISBNodeExact n = (ISBNodeExact) res.node;
            if (bTrace)  {
                Printf("   Found at d=%.2f: ", res.distance);
                PrintNode(res.node);
            }
            n.count_after++;
            nodeNew.AddPrecNeigh(res.node.id);
        }
        if (bTrace) Println("Insert new node to ISB.");
        ISB.Insert(nodeNew);
        // insert node at window
        windowNodes.add(nodeNew);
        if (bTrace) PrintWindow();
        if (CanSearch()) {
            // invoke query function to detect outliers
            SearchOutliers();
        } else {
            // update statistics outlierness of new node
            UpdateNodeStatistics(nodeNew);
        }
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode (ISBNode node) [package]
Definition at line 164 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.inst, moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ISBIndex.Remove(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode().
{
        // remove node from ISB
        ISB.Remove(node);
        // remove from fifo
        windowNodes.remove(node);
        // remove from outliers
        RemoveExpiredOutlier(new Outlier(node.inst, node.id, node));
        // update statistics
        UpdateStatistics(node);
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers () [package]
Definition at line 251 of file ExactSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj().
{
        if (bTrace) Println("Invoke query: ");
        ISBNodeExact node;
        // process each node in the ISB (also in window)
        for (int i = 0; i < windowNodes.size(); i++) {
            node = (ISBNodeExact) windowNodes.get(i);
            if (bTrace) {
                Print("   Process node: ");
                PrintNode(node);
            }
            UpdateNodeType(node);
        }
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeStatistics (ISBNodeExact node) [package]
Definition at line 293 of file ExactSTORM.java.
References moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after, moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.CountPrecNeighs(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nInlier, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj().
{
        int succ_neighs = node.count_after;
        int prec_neighs = node.CountPrecNeighs(GetWindowStart());
        if (succ_neighs + prec_neighs < m_k) {
            node.nOutlier++; // update statistics
        } else {
            node.nInlier++; // update statistics
        }
    }
void moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType (ISBNodeExact node) [package]
Definition at line 265 of file ExactSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.count_after, moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.CountPrecNeighs(), moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.PrintPrecNeighs(), moa.clusterers.outliers.Angiulli.STORMBase.RemoveOutlier(), and moa.clusterers.outliers.Angiulli.STORMBase.SaveOutlier().
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers().
{
        int succ_neighs, prec_neighs;
        // get number of succeeding neighbors
        succ_neighs = node.count_after;
        if (bTrace) Println("      succ_neighs: " + succ_neighs);
        // get number of preceding neighbors with
        // non-expired objects determined
        prec_neighs = node.CountPrecNeighs(GetWindowStart());
        if (bTrace) {
            Println("      GetWindowStart(): " + GetWindowStart());
            node.PrintPrecNeighs();
            Println("      prec_neighs: " + prec_neighs);
        }
        // check if node is an outlier
        if (succ_neighs + prec_neighs < m_k) {
            SaveOutlier(node);
            if (bTrace) {
                Print("*** Outlier: ");
                PrintNode(node);
            }
        } else {
            RemoveOutlier(node);
        }
    }
Member Data Documentation
IntOption moa.clusterers.outliers.Angiulli.ExactSTORM.kOption = new IntOption("k", 't', "Parameter k.", 50)
Definition at line 91 of file ExactSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init().
IntOption moa.clusterers.outliers.Angiulli.ExactSTORM.queryFreqOption = new IntOption("queryFreq", 'q', "Query frequency.", 1)
Definition at line 92 of file ExactSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.TestSpeed.main(), and moa.clusterers.outliers.Angiulli.Test.main().
FloatOption moa.clusterers.outliers.Angiulli.ExactSTORM.radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
Definition at line 90 of file ExactSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ExactSTORM.Init().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/Angiulli/ExactSTORM.java