MOA: moa.gui.visualization.RunVisualizer Class Reference
moa.gui.visualization.RunVisualizer Class Reference
Public Member Functions
RunVisualizer (ClusteringVisualTab visualPanel, ClusteringSetupTab clusteringSetupTab)
void run ()
void runVisual ()
void drawClusterings (List< DataPoint > points0, List< DataPoint > points1)
void redraw ()
void stop ()
void setSpeed (int speed)
void actionPerformed (ActionEvent e)
void setPointLayerVisibility (boolean selected)
void setMicroLayerVisibility (boolean selected)
void setMacroVisibility (boolean selected)
void setGroundTruthVisibility (boolean selected)
void changeCluster (ClusterEvent e)
void exportCSV (String filepath)
void weka ()
Static Public Member Functions
static int getCurrentTimestamp ()
static void pause ()
static void resume ()
Static Public Attributes
static final int initialPauseInterval = 5000
the pause interval, being read from the gui at startup
Private Member Functions
void processClusterings (ArrayList< DataPoint > points0, ArrayList< DataPoint > points1)
void evaluateClustering (Clustering found_clustering, Clustering trueClustering, ArrayList< DataPoint > points, boolean algorithm0)
void work_pause ()
Private Attributes
int m_wait_frequency = 1000
factor to control the speed
int m_redrawInterval = 100
after how many instances do we repaint the streampanel? the GUI becomes very slow with small values
boolean stop = false
int m_processFrequency
final ClusteringStream m_stream0
int m_stream0_decayHorizon
double m_stream0_decay_threshold
double m_stream0_decay_rate
AbstractClusterer m_clusterer0
AbstractClusterer m_clusterer1
MeasureCollection[] m_measures0 = null
MeasureCollection[] m_measures1 = null
StreamPanel m_streampanel0
StreamPanel m_streampanel1
ClusteringVisualEvalPanel m_evalPanel
GraphCanvas m_graphcanvas
ClusteringVisualTab m_visualPanel
Clustering gtClustering0 = null
Clustering gtClustering1 = null
Clustering macro0 = null
Clustering macro1 = null
Clustering micro0 = null
Clustering micro1 = null
ArrayList< ClusterEvent > clusterEvents
final TextViewerPanel m_logPanel
Static Private Attributes
static boolean work
static int timestamp
static int lastPauseTimestamp
Detailed Description
Definition at line 56 of file RunVisualizer.java.
Constructor & Destructor Documentation
moa.gui.visualization.RunVisualizer.RunVisualizer (ClusteringVisualTab visualPanel, ClusteringSetupTab clusteringSetupTab)
Definition at line 135 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.clusterEvents, moa.gui.clustertab.ClusteringSetupTab.getClusterer0(), moa.gui.clustertab.ClusteringSetupTab.getClusterer1(), moa.streams.clustering.ClusteringStream.getDecayHorizon(), moa.streams.clustering.ClusteringStream.getDecayThreshold(), moa.gui.clustertab.ClusteringVisualTab.getEvalPanel(), moa.streams.clustering.ClusteringStream.getEvaluationFrequency(), moa.gui.clustertab.ClusteringVisualTab.getGraphCanvas(), moa.gui.clustertab.ClusteringVisualTab.getLeftStreamPanel(), moa.gui.clustertab.ClusteringSetupTab.getLogPanel(), moa.gui.clustertab.ClusteringSetupTab.getMeasures(), moa.gui.clustertab.ClusteringVisualTab.getRightStreamPanel(), moa.gui.clustertab.ClusteringSetupTab.getStream0(), moa.options.IntOption.getValue(), moa.gui.visualization.RunVisualizer.initialPauseInterval, moa.gui.visualization.RunVisualizer.lastPauseTimestamp, moa.gui.visualization.RunVisualizer.m_clusterer0, moa.gui.visualization.RunVisualizer.m_clusterer1, moa.gui.visualization.RunVisualizer.m_evalPanel, moa.gui.visualization.RunVisualizer.m_graphcanvas, moa.gui.visualization.RunVisualizer.m_logPanel, moa.gui.visualization.RunVisualizer.m_measures0, moa.gui.visualization.RunVisualizer.m_measures1, moa.gui.visualization.RunVisualizer.m_processFrequency, moa.gui.visualization.RunVisualizer.m_stream0, moa.gui.visualization.RunVisualizer.m_stream0_decay_rate, moa.gui.visualization.RunVisualizer.m_stream0_decay_threshold, moa.gui.visualization.RunVisualizer.m_stream0_decayHorizon, moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, moa.gui.visualization.RunVisualizer.m_visualPanel, moa.streams.clustering.ClusteringStream.numAttsOption, moa.options.AbstractOptionHandler.prepareForUse(), moa.gui.visualization.GraphCanvas.setClusterEventsList(), moa.gui.clustertab.ClusteringVisualTab.setDimensionComobBoxes(), moa.gui.visualization.GraphCanvas.setGraph(), moa.gui.clustertab.ClusteringVisualEvalPanel.setMeasures(), moa.gui.clustertab.ClusteringVisualTab.setPauseInterval(), moa.gui.visualization.RunVisualizer.timestamp, and moa.gui.visualization.RunVisualizer.work.
{
        m_visualPanel = visualPanel;
        m_streampanel0 = visualPanel.getLeftStreamPanel();
        m_streampanel1 = visualPanel.getRightStreamPanel();
        m_graphcanvas = visualPanel.getGraphCanvas();
        m_evalPanel = visualPanel.getEvalPanel();
        m_logPanel = clusteringSetupTab.getLogPanel();
        m_stream0 = clusteringSetupTab.getStream0();
        m_stream0_decayHorizon = m_stream0.getDecayHorizon();
        m_stream0_decay_threshold = m_stream0.getDecayThreshold();
        m_stream0_decay_rate = (Math.log(1.0/m_stream0_decay_threshold)/Math.log(2)/m_stream0_decayHorizon);
        timestamp = 0;
        lastPauseTimestamp = 0;
        work = true;
        if(m_stream0 instanceof RandomRBFGeneratorEvents){
            ((RandomRBFGeneratorEvents)m_stream0).addClusterChangeListener(this);
            clusterEvents = new ArrayList<ClusterEvent>();
            m_graphcanvas.setClusterEventsList(clusterEvents);
        }
        m_stream0.prepareForUse();
        m_clusterer0 = clusteringSetupTab.getClusterer0();
        m_clusterer0.prepareForUse();
        m_clusterer1 = clusteringSetupTab.getClusterer1();
        if(m_clusterer1!=null){
            m_clusterer1.prepareForUse();
        }
        m_measures0 = clusteringSetupTab.getMeasures();
        m_measures1 = clusteringSetupTab.getMeasures();
        /* TODO this option needs to move from the stream panel to the setup panel */
        m_processFrequency = m_stream0.getEvaluationFrequency();
        //get those values from the generator
        int dims = m_stream0.numAttsOption.getValue();
        visualPanel.setDimensionComobBoxes(dims);
        visualPanel.setPauseInterval(initialPauseInterval);
        m_evalPanel.setMeasures(m_measures0, m_measures1, this);
        m_graphcanvas.setGraph(m_measures0[0], m_measures1[0],0,m_processFrequency);
    }
Member Function Documentation
void moa.gui.visualization.RunVisualizer.actionPerformed (ActionEvent e)
Definition at line 454 of file RunVisualizer.java.
References moa.evaluation.MeasureCollection.getNumMeasures(), moa.gui.visualization.RunVisualizer.m_graphcanvas, moa.gui.visualization.RunVisualizer.m_measures0, moa.gui.visualization.RunVisualizer.m_measures1, moa.gui.visualization.RunVisualizer.m_processFrequency, and moa.gui.visualization.GraphCanvas.setGraph().
{
        //reacte on graph selection and find out which measure was selected
        int selected = Integer.parseInt(e.getActionCommand());
        int counter = selected;
        int m_select = 0;
        int m_select_offset = 0;
        boolean found = false;
        for (int i = 0; i < m_measures0.length; i++) {
            for (int j = 0; j < m_measures0[i].getNumMeasures(); j++) {
                if(m_measures0[i].isEnabled(j)){
                    counter--;
                    if(counter<0){
                        m_select = i;
                        m_select_offset = j;
                        found = true;
                        break;
                    }
                }
            }
            if(found) break;
        }
        m_graphcanvas.setGraph(m_measures0[m_select], m_measures1[m_select],m_select_offset,m_processFrequency);
    }
void moa.gui.visualization.RunVisualizer.changeCluster (ClusterEvent e)
Implements moa.streams.clustering.ClusterEventListener.
Definition at line 495 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.clusterEvents, moa.streams.clustering.ClusterEvent.getMessage(), and moa.streams.clustering.ClusterEvent.getType().
{
        if(clusterEvents!=null) clusterEvents.add(e);
        System.out.println(e.getType()+": "+e.getMessage());
    }
void moa.gui.visualization.RunVisualizer.drawClusterings (List< DataPoint > points0, List< DataPoint > points1)
Definition at line 395 of file RunVisualizer.java.
References moa.gui.visualization.StreamPanel.drawGTClustering(), moa.gui.visualization.StreamPanel.drawMacroClustering(), moa.gui.visualization.StreamPanel.drawMicroClustering(), moa.gui.visualization.RunVisualizer.gtClustering0, moa.gui.visualization.RunVisualizer.gtClustering1, moa.gui.visualization.RunVisualizer.m_clusterer1, moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, moa.gui.visualization.RunVisualizer.macro0, moa.gui.visualization.RunVisualizer.macro1, moa.gui.visualization.RunVisualizer.micro0, moa.gui.visualization.RunVisualizer.micro1, and moa.cluster.Clustering.size().
Referenced by moa.gui.visualization.RunVisualizer.processClusterings().
{
        if(macro0!= null && macro0.size() > 0)
                m_streampanel0.drawMacroClustering(macro0, points0, Color.RED);
        if(micro0!= null && micro0.size() > 0)
                m_streampanel0.drawMicroClustering(micro0, points0, Color.GREEN);
        if(gtClustering0!= null && gtClustering0.size() > 0)
            m_streampanel0.drawGTClustering(gtClustering0, points0, Color.BLACK);
        if(m_clusterer1!=null){
            if(macro1!= null && macro1.size() > 0)
                    m_streampanel1.drawMacroClustering(macro1, points1, Color.BLUE);
            if(micro1!= null && micro1.size() > 0)
                    m_streampanel1.drawMicroClustering(micro1, points1, Color.GREEN);
            if(gtClustering1!= null && gtClustering1.size() > 0)
                m_streampanel1.drawGTClustering(gtClustering1, points1, Color.BLACK);
        }
    }
void moa.gui.visualization.RunVisualizer.evaluateClustering (Clustering found_clustering, Clustering trueClustering, ArrayList< DataPoint > points, boolean algorithm0) [private]
Definition at line 356 of file RunVisualizer.java.
References moa.evaluation.MeasureCollection.addEmptyValue(), moa.evaluation.MeasureCollection.evaluateClusteringPerformance(), moa.evaluation.MeasureCollection.getNumMeasures(), moa.gui.visualization.RunVisualizer.m_clusterer1, moa.gui.visualization.RunVisualizer.m_evalPanel, moa.gui.visualization.RunVisualizer.m_graphcanvas, moa.gui.visualization.RunVisualizer.m_logPanel, moa.gui.visualization.RunVisualizer.m_measures0, moa.gui.visualization.RunVisualizer.m_measures1, moa.gui.TextViewerPanel.setText(), moa.cluster.Clustering.size(), moa.gui.clustertab.ClusteringVisualEvalPanel.update(), and moa.gui.visualization.GraphCanvas.updateCanvas().
Referenced by moa.gui.visualization.RunVisualizer.processClusterings().
{
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < m_measures0.length; i++) {
            if(algorithm0){
                if(found_clustering!=null && found_clustering.size() > 0){
                    try {
                        double msec = m_measures0[i].evaluateClusteringPerformance(found_clustering, trueClustering, points);
                        sb.append(m_measures0[i].getClass().getSimpleName()+" took "+msec+"ms (Mean:"+m_measures0[i].getMeanRunningTime()+")");
                        sb.append("\n");
                    } catch (Exception ex) { ex.printStackTrace(); }
                }
                else{
                    for(int j = 0; j < m_measures0[i].getNumMeasures(); j++){
                        m_measures0[i].addEmptyValue(j);
                    }
                }
            }
            else{
                if(m_clusterer1!=null && found_clustering!=null && found_clustering.size() > 0){
                    try {
                        double msec = m_measures1[i].evaluateClusteringPerformance(found_clustering, trueClustering, points);
                        sb.append(m_measures1[i].getClass().getSimpleName()+" took "+msec+"ms (Mean:"+m_measures1[i].getMeanRunningTime()+")");
                        sb.append("\n");
                    }
                    catch (Exception ex) { ex.printStackTrace(); }
                }
                else{
                    for(int j = 0; j < m_measures1[i].getNumMeasures(); j++){
                        m_measures1[i].addEmptyValue(j);
                    }
                }
            }
        }
        m_logPanel.setText(sb.toString());
        m_evalPanel.update();
        m_graphcanvas.updateCanvas();
    }
void moa.gui.visualization.RunVisualizer.exportCSV (String filepath)
Definition at line 502 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.clusterEvents, moa.evaluation.MeasureCollection.getNumberOfValues(), moa.evaluation.MeasureCollection.getNumMeasures(), moa.evaluation.MeasureCollection.getValue(), moa.gui.visualization.RunVisualizer.m_measures0, moa.gui.visualization.RunVisualizer.m_measures1, and moa.gui.visualization.RunVisualizer.m_stream0_decayHorizon.
{
        PrintWriter out = null;
        try {
            if(!filepath.endsWith(".csv"))
                filepath+=".csv";
            out = new PrintWriter(new BufferedWriter(new FileWriter(filepath)));
            String del = ";";
            Iterator<ClusterEvent> eventIt = null;
            ClusterEvent event = null;
            if(clusterEvents!=null && clusterEvents.size() > 0){
                eventIt = clusterEvents.iterator();
                event = eventIt.next();
            }
            //raw data
            MeasureCollection measurecol[][] = new MeasureCollection[2][];
            measurecol[0] = m_measures0;
            measurecol[1] = m_measures1;
            int numValues = 0;
            //header
            out.write("Nr"+del);
            out.write("Event"+del);
            for (int m = 0; m < 2; m++) {
                for (int i = 0; i < measurecol[m].length; i++) {
                    for (int j = 0; j < measurecol[m][i].getNumMeasures(); j++) {
                        if(measurecol[m][i].isEnabled(j)){
                            out.write(m+"-"+measurecol[m][i].getName(j)+del);
                            numValues = measurecol[m][i].getNumberOfValues(j);
                        }
                    }
                }
            }
            out.write("\n");
            //rows
            for (int v = 0; v < numValues; v++){
                //Nr
                out.write(v+del);
                //events
                if(event!=null && event.getTimestamp()<=m_stream0_decayHorizon*v){
                    out.write(event.getType()+del);
                    if(eventIt!= null && eventIt.hasNext()){
                        event=eventIt.next();
                    }
                    else
                        event = null;
                }
                else
                    out.write(del);
                //values
                for (int m = 0; m < 2; m++) {
                    for (int i = 0; i < measurecol[m].length; i++) {
                        for (int j = 0; j < measurecol[m][i].getNumMeasures(); j++) {
                            if(measurecol[m][i].isEnabled(j)){
                                    double value = measurecol[m][i].getValue(j, v);
                                    if(Double.isNaN(value))
                                        out.write(del);
                                    else
                                        out.write(value+del);
                            }
                        }
                    }
                }
                out.write("\n");
            }
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(RunVisualizer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }
static int moa.gui.visualization.RunVisualizer.getCurrentTimestamp () [static]
Definition at line 419 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.timestamp.
{
        return timestamp;
    }
static void moa.gui.visualization.RunVisualizer.pause () [static]
Definition at line 436 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.lastPauseTimestamp, moa.gui.visualization.RunVisualizer.timestamp, and moa.gui.visualization.RunVisualizer.work.
Referenced by moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
{
        work = false;
        lastPauseTimestamp = timestamp;
    }
void moa.gui.visualization.RunVisualizer.processClusterings (ArrayList< DataPoint > points0, ArrayList< DataPoint > points1) [private]
Definition at line 303 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.clusterers.AbstractClusterer.evaluateMicroClusteringOption, moa.clusterers.Clusterer.getClusteringResult(), moa.clusterers.AbstractClusterer.getMicroClusteringResult(), moa.gui.visualization.RunVisualizer.gtClustering0, moa.gui.visualization.RunVisualizer.gtClustering1, moa.clusterers.AbstractClusterer.implementsMicroClusterer(), moa.options.FlagOption.isSet, moa.gui.visualization.RunVisualizer.m_clusterer0, moa.gui.visualization.RunVisualizer.m_clusterer1, moa.gui.visualization.RunVisualizer.macro0, moa.gui.visualization.RunVisualizer.macro1, moa.gui.visualization.RunVisualizer.micro0, and moa.gui.visualization.RunVisualizer.micro1.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        gtClustering0 = new Clustering(points0);
        gtClustering1 = new Clustering(points1);
        Clustering evalClustering0 = null;
        Clustering evalClustering1 = null;
        //special case for ClusterGenerator
        if(gtClustering0!= null){
            if(m_clusterer0 instanceof ClusterGenerator)
                ((ClusterGenerator)m_clusterer0).setSourceClustering(gtClustering0);
            if(m_clusterer1 instanceof ClusterGenerator)
                ((ClusterGenerator)m_clusterer1).setSourceClustering(gtClustering1);
        }
        macro0 = m_clusterer0.getClusteringResult();
        evalClustering0 = macro0;
        //TODO: should we check if micro/macro is being drawn or needed for evaluation and skip otherwise to speed things up?
        if(m_clusterer0.implementsMicroClusterer()){
            micro0 = m_clusterer0.getMicroClusteringResult();
            if(macro0 == null && micro0 != null){
                //TODO: we need a Macro Clusterer Interface and the option for kmeans to use the non optimal centers
                macro0 = moa.clusterers.KMeans.gaussianMeans(gtClustering0, micro0);
            }
            if(m_clusterer0.evaluateMicroClusteringOption.isSet())
                evalClustering0 = micro0;
            else
                evalClustering0 = macro0;
        }
        if(m_clusterer1!=null){
            macro1 = m_clusterer1.getClusteringResult();
            evalClustering1 = macro1;
            if(m_clusterer1.implementsMicroClusterer()){
                micro1 = m_clusterer1.getMicroClusteringResult();
                if(macro1 == null && micro1 != null){
                        macro1 = moa.clusterers.KMeans.gaussianMeans(gtClustering1, micro1);
                }
                if(m_clusterer1.evaluateMicroClusteringOption.isSet())
                    evalClustering1 = micro1;
                else
                    evalClustering1 = macro1;
            }
        }
        evaluateClustering(evalClustering0, gtClustering0, points0, true);
        evaluateClustering(evalClustering1, gtClustering1, points1, false);
        drawClusterings(points0, points1);
    }
void moa.gui.visualization.RunVisualizer.redraw ()
Definition at line 413 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_streampanel0, and moa.gui.visualization.RunVisualizer.m_streampanel1.
{
        m_streampanel0.repaint();
        m_streampanel1.repaint();
    }
static void moa.gui.visualization.RunVisualizer.resume () [static]
Definition at line 441 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.work.
Referenced by moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer().
{
        work = true;
    }
void moa.gui.visualization.RunVisualizer.run ()
Definition at line 186 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.runVisual().
Referenced by moa.gui.visualization.RunVisualizer.work_pause().
                      {
            runVisual();
    }
void moa.gui.visualization.RunVisualizer.runVisual ()
Definition at line 191 of file RunVisualizer.java.
References moa.gui.visualization.StreamPanel.applyDrawDecay(), moa.gui.visualization.StreamPanel.drawPoint(), moa.gui.visualization.StreamPanel.drawPointPanels(), moa.gui.clustertab.ClusteringVisualTab.getPauseInterval(), moa.streams.InstanceStream.hasMoreInstances(), moa.gui.clustertab.ClusteringVisualTab.isEnabledDrawPoints(), moa.clusterers.AbstractClusterer.keepClassLabel(), moa.gui.visualization.RunVisualizer.lastPauseTimestamp, moa.gui.visualization.RunVisualizer.m_clusterer0, moa.gui.visualization.RunVisualizer.m_clusterer1, moa.gui.visualization.RunVisualizer.m_processFrequency, moa.gui.visualization.RunVisualizer.m_redrawInterval, moa.gui.visualization.RunVisualizer.m_stream0, moa.gui.visualization.RunVisualizer.m_stream0_decay_rate, moa.gui.visualization.RunVisualizer.m_stream0_decay_threshold, moa.gui.visualization.RunVisualizer.m_stream0_decayHorizon, moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, moa.gui.visualization.RunVisualizer.m_visualPanel, moa.gui.visualization.RunVisualizer.m_wait_frequency, moa.streams.InstanceStream.nextInstance(), moa.gui.visualization.RunVisualizer.processClusterings(), moa.gui.clustertab.ClusteringVisualTab.setProcessedPointsCounter(), moa.gui.visualization.RunVisualizer.stop(), moa.gui.visualization.RunVisualizer.timestamp, moa.gui.clustertab.ClusteringVisualTab.toggleVisualizer(), moa.clusterers.AbstractClusterer.trainOnInstanceImpl(), moa.gui.visualization.RunVisualizer.work, and moa.gui.visualization.RunVisualizer.work_pause().
Referenced by moa.gui.visualization.RunVisualizer.run().
{
        int processCounter = 0;
        int speedCounter = 0;
        LinkedList<DataPoint> pointBuffer0 = new LinkedList<DataPoint>();
        LinkedList<DataPoint> pointBuffer1 = new LinkedList<DataPoint>();
        ArrayList<DataPoint> pointarray0 = null;
        ArrayList<DataPoint> pointarray1 = null;
        while(work || processCounter!=0){
            if (m_stream0.hasMoreInstances()) {
                timestamp++;
                speedCounter++;
                processCounter++;
                if(timestamp%100 == 0){
                    m_visualPanel.setProcessedPointsCounter(timestamp);
                }
                Instance next0 = m_stream0.nextInstance();
                DataPoint point0 = new DataPoint(next0,timestamp);
                pointBuffer0.add(point0);
                while(pointBuffer0.size() > m_stream0_decayHorizon){
                    pointBuffer0.removeFirst();
                }
                DataPoint point1 = null;
                if(m_clusterer1!=null){
                    point1 = new DataPoint(next0,timestamp);
                    pointBuffer1.add(point1);
                    while(pointBuffer1.size() > m_stream0_decayHorizon){
                        pointBuffer1.removeFirst();
                    }
                }
                if(m_visualPanel.isEnabledDrawPoints()){
                    m_streampanel0.drawPoint(point0);
                    if(m_clusterer1!=null)
                        m_streampanel1.drawPoint(point1);
                    if(processCounter%m_redrawInterval==0){
                        m_streampanel0.applyDrawDecay(m_stream0_decayHorizon/(float)(m_redrawInterval));
                        if(m_clusterer1!=null)
                            m_streampanel1.applyDrawDecay(m_stream0_decayHorizon/(float)(m_redrawInterval));
                    }
                }
                Instance traininst0 = new DenseInstance(point0);
                if(m_clusterer0.keepClassLabel())
                    traininst0.setDataset(point0.dataset());
                else
                    traininst0.deleteAttributeAt(point0.classIndex());
                m_clusterer0.trainOnInstanceImpl(traininst0);
                if(m_clusterer1!=null){
                    Instance traininst1 = new DenseInstance(point1);
                    if(m_clusterer1.keepClassLabel())
                        traininst1.setDataset(point1.dataset());
                    else
                        traininst1.deleteAttributeAt(point1.classIndex());
                    m_clusterer1.trainOnInstanceImpl(traininst1);
                }
                if (processCounter >= m_processFrequency) {
                    processCounter = 0;
                    for(DataPoint p:pointBuffer0)
                        p.updateWeight(timestamp, m_stream0_decay_rate);
                    pointarray0 = new ArrayList<DataPoint>(pointBuffer0);
                    if(m_clusterer1!=null){
                        for(DataPoint p:pointBuffer1)
                            p.updateWeight(timestamp, m_stream0_decay_rate);
                        pointarray1 = new ArrayList<DataPoint>(pointBuffer1);
                    }
                    processClusterings(pointarray0, pointarray1);
                    int pauseInterval = m_visualPanel.getPauseInterval();
                    if(pauseInterval!=0 && lastPauseTimestamp+pauseInterval<=timestamp){
                        m_visualPanel.toggleVisualizer(true);
                    }
                }
            } else {
                System.out.println("DONE");
                return;
            }
            if(speedCounter > m_wait_frequency*30 && m_wait_frequency < 15){
                try {
                    synchronized (this) {
                        if(m_wait_frequency == 0)
                            wait(50);
                        else
                            wait(1);
                    }
                } catch (InterruptedException ex) {
                }
                speedCounter = 0;
            }
        }
        if(!stop){
            m_streampanel0.drawPointPanels(pointarray0, timestamp, m_stream0_decay_rate, m_stream0_decay_threshold);
            if(m_clusterer1!=null)
                m_streampanel1.drawPointPanels(pointarray1, timestamp, m_stream0_decay_rate, m_stream0_decay_threshold);
            work_pause();
        }
    }
void moa.gui.visualization.RunVisualizer.setGroundTruthVisibility (boolean selected)
Definition at line 490 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, and moa.gui.visualization.StreamPanel.setGroundTruthLayerVisibility().
{
        m_streampanel0.setGroundTruthLayerVisibility(selected);
        m_streampanel1.setGroundTruthLayerVisibility(selected);
    }
void moa.gui.visualization.RunVisualizer.setMacroVisibility (boolean selected)
Definition at line 486 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, and moa.gui.visualization.StreamPanel.setMacroLayerVisibility().
{
        m_streampanel0.setMacroLayerVisibility(selected);
        m_streampanel1.setMacroLayerVisibility(selected);
    }
void moa.gui.visualization.RunVisualizer.setMicroLayerVisibility (boolean selected)
Definition at line 482 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, and moa.gui.visualization.StreamPanel.setMicroLayerVisibility().
{
        m_streampanel0.setMicroLayerVisibility(selected);
        m_streampanel1.setMicroLayerVisibility(selected);
    }
void moa.gui.visualization.RunVisualizer.setPointLayerVisibility (boolean selected)
Definition at line 478 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_streampanel0, moa.gui.visualization.RunVisualizer.m_streampanel1, and moa.gui.visualization.StreamPanel.setPointVisibility().
{
        m_streampanel0.setPointVisibility(selected);
        m_streampanel1.setPointVisibility(selected);
    }
void moa.gui.visualization.RunVisualizer.setSpeed (int speed)
Definition at line 450 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.m_wait_frequency.
{
        m_wait_frequency = speed;
    }
void moa.gui.visualization.RunVisualizer.stop ()
Definition at line 445 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.work.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.work_pause().
                      {
        work = false;
        stop = true;
    }
void moa.gui.visualization.RunVisualizer.weka ()
Definition at line 579 of file RunVisualizer.java.
References moa.gui.TextViewerPanel.addText(), moa.clusterers.AbstractClusterer.evaluateMicroClusteringOption, moa.cluster.Clustering.get(), moa.cluster.Cluster.getCenter(), moa.cluster.Cluster.getWeight(), moa.clusterers.AbstractClusterer.implementsMicroClusterer(), moa.options.FlagOption.isSet, moa.gui.visualization.RunVisualizer.m_clusterer0, moa.gui.visualization.RunVisualizer.m_logPanel, moa.gui.visualization.RunVisualizer.macro0, moa.gui.visualization.RunVisualizer.micro0, and moa.cluster.Clustering.size().
                       {
        try{
            Class.forName("weka.gui.Logger");
        }
        catch (Exception e){
            m_logPanel.addText("Please add weka.jar to the classpath to use the Weka explorer.");
            return;
        }
        Clustering wekaClustering;
        if(m_clusterer0.implementsMicroClusterer() && m_clusterer0.evaluateMicroClusteringOption.isSet())
            wekaClustering = micro0;
        else
            wekaClustering = macro0;
        if(wekaClustering == null || wekaClustering.size()==0){
            m_logPanel.addText("Empty Clustering");
            return;
        }
        int dims = wekaClustering.get(0).getCenter().length;
        FastVector attributes = new FastVector();
        for(int i = 0; i < dims; i++)
                attributes.addElement( new Attribute("att" + i) );
        Instances instances = new Instances("trainset",attributes,0);
        for(int c = 0; c < wekaClustering.size(); c++){
            Cluster cluster = wekaClustering.get(c);
            Instance inst = new DenseInstance(cluster.getWeight(), cluster.getCenter());
            inst.setDataset(instances);
            instances.add(inst);
        }
        WekaExplorer explorer = new WekaExplorer(instances);
    }
void moa.gui.visualization.RunVisualizer.work_pause () [private]
Definition at line 423 of file RunVisualizer.java.
References moa.gui.visualization.RunVisualizer.run(), moa.gui.visualization.RunVisualizer.stop(), and moa.gui.visualization.RunVisualizer.work.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
{
        while(!work && !stop){
            try {
                synchronized (this) {
                    wait(1000);
                }
            } catch (InterruptedException ex) {
            }
       }
       run();
    }
Member Data Documentation
ArrayList<ClusterEvent> moa.gui.visualization.RunVisualizer.clusterEvents [private]
Definition at line 130 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.changeCluster(), moa.gui.visualization.RunVisualizer.exportCSV(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
Clustering moa.gui.visualization.RunVisualizer.gtClustering0 = null [private]
Definition at line 122 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), and moa.gui.visualization.RunVisualizer.processClusterings().
Clustering moa.gui.visualization.RunVisualizer.gtClustering1 = null [private]
Definition at line 123 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), and moa.gui.visualization.RunVisualizer.processClusterings().
final int moa.gui.visualization.RunVisualizer.initialPauseInterval = 5000 [static]
the pause interval, being read from the gui at startup
Definition at line 60 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.RunVisualizer().
int moa.gui.visualization.RunVisualizer.lastPauseTimestamp [static, private]
Definition at line 77 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.pause(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
AbstractClusterer moa.gui.visualization.RunVisualizer.m_clusterer0 [private]
Definition at line 100 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.processClusterings(), moa.gui.visualization.RunVisualizer.runVisual(), moa.gui.visualization.RunVisualizer.RunVisualizer(), and moa.gui.visualization.RunVisualizer.weka().
AbstractClusterer moa.gui.visualization.RunVisualizer.m_clusterer1 [private]
Definition at line 101 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.RunVisualizer.processClusterings(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
ClusteringVisualEvalPanel moa.gui.visualization.RunVisualizer.m_evalPanel [private]
Definition at line 112 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.evaluateClustering(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
GraphCanvas moa.gui.visualization.RunVisualizer.m_graphcanvas [private]
Definition at line 115 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.visualization.RunVisualizer.evaluateClustering(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
final TextViewerPanel moa.gui.visualization.RunVisualizer.m_logPanel [private]
Definition at line 133 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.RunVisualizer.RunVisualizer(), and moa.gui.visualization.RunVisualizer.weka().
MeasureCollection [] moa.gui.visualization.RunVisualizer.m_measures0 = null [private]
Definition at line 104 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.RunVisualizer.exportCSV(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
MeasureCollection [] moa.gui.visualization.RunVisualizer.m_measures1 = null [private]
Definition at line 105 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.visualization.RunVisualizer.evaluateClustering(), moa.gui.visualization.RunVisualizer.exportCSV(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
int moa.gui.visualization.RunVisualizer.m_processFrequency [private]
Definition at line 80 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.actionPerformed(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
int moa.gui.visualization.RunVisualizer.m_redrawInterval = 100 [private]
after how many instances do we repaint the streampanel? the GUI becomes very slow with small values
Definition at line 68 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual().
final ClusteringStream moa.gui.visualization.RunVisualizer.m_stream0 [private]
Definition at line 83 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
double moa.gui.visualization.RunVisualizer.m_stream0_decay_rate [private]
Definition at line 96 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
double moa.gui.visualization.RunVisualizer.m_stream0_decay_threshold [private]
Definition at line 91 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
int moa.gui.visualization.RunVisualizer.m_stream0_decayHorizon [private]
Definition at line 88 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.exportCSV(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
StreamPanel moa.gui.visualization.RunVisualizer.m_streampanel0 [private]
Definition at line 108 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.redraw(), moa.gui.visualization.RunVisualizer.runVisual(), moa.gui.visualization.RunVisualizer.RunVisualizer(), moa.gui.visualization.RunVisualizer.setGroundTruthVisibility(), moa.gui.visualization.RunVisualizer.setMacroVisibility(), moa.gui.visualization.RunVisualizer.setMicroLayerVisibility(), and moa.gui.visualization.RunVisualizer.setPointLayerVisibility().
StreamPanel moa.gui.visualization.RunVisualizer.m_streampanel1 [private]
Definition at line 109 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.redraw(), moa.gui.visualization.RunVisualizer.runVisual(), moa.gui.visualization.RunVisualizer.RunVisualizer(), moa.gui.visualization.RunVisualizer.setGroundTruthVisibility(), moa.gui.visualization.RunVisualizer.setMacroVisibility(), moa.gui.visualization.RunVisualizer.setMicroLayerVisibility(), and moa.gui.visualization.RunVisualizer.setPointLayerVisibility().
ClusteringVisualTab moa.gui.visualization.RunVisualizer.m_visualPanel [private]
Definition at line 118 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
int moa.gui.visualization.RunVisualizer.m_wait_frequency = 1000 [private]
factor to control the speed
Definition at line 63 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.setSpeed().
Clustering moa.gui.visualization.RunVisualizer.macro0 = null [private]
Definition at line 124 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.processClusterings(), and moa.gui.visualization.RunVisualizer.weka().
Clustering moa.gui.visualization.RunVisualizer.macro1 = null [private]
Definition at line 125 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), and moa.gui.visualization.RunVisualizer.processClusterings().
Clustering moa.gui.visualization.RunVisualizer.micro0 = null [private]
Definition at line 126 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), moa.gui.visualization.RunVisualizer.processClusterings(), and moa.gui.visualization.RunVisualizer.weka().
Clustering moa.gui.visualization.RunVisualizer.micro1 = null [private]
Definition at line 127 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.drawClusterings(), and moa.gui.visualization.RunVisualizer.processClusterings().
boolean moa.gui.visualization.RunVisualizer.stop = false [private]
Definition at line 73 of file RunVisualizer.java.
Referenced by moa.gui.clustertab.ClusteringVisualTab.stopVisualizer().
int moa.gui.visualization.RunVisualizer.timestamp [static, private]
Definition at line 76 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.getCurrentTimestamp(), moa.gui.visualization.RunVisualizer.pause(), moa.gui.visualization.RunVisualizer.runVisual(), and moa.gui.visualization.RunVisualizer.RunVisualizer().
boolean moa.gui.visualization.RunVisualizer.work [static, private]
Definition at line 72 of file RunVisualizer.java.
Referenced by moa.gui.visualization.RunVisualizer.pause(), moa.gui.visualization.RunVisualizer.resume(), moa.gui.visualization.RunVisualizer.runVisual(), moa.gui.visualization.RunVisualizer.RunVisualizer(), moa.gui.visualization.RunVisualizer.stop(), and moa.gui.visualization.RunVisualizer.work_pause().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/RunVisualizer.java