MOA: moa.gui.visualization.PointPanel Class Reference
moa.gui.visualization.PointPanel Class Reference
Public Member Functions
PointPanel (DataPoint point, StreamPanel streamPanel, double decayRate, double decayThreshold)
Type 1: Possibly be decayed, colored by class label.
PointPanel (DataPoint point, StreamPanel streamPanel, Color color)
Type 2: Never be decayed, single color.
void updateLocation ()
void highlight (boolean enabled)
String getObjectInfo ()
String getToolTipText ()
String getSVGString (int width)
void drawOnCanvas (Graphics2D imageGraphics)
Static Public Member Functions
static Color getPointColorbyClass (DataPoint point, float numClasses)
Protected Member Functions
void paintComponent (Graphics g)
Protected Attributes
int x_dim = 0
int y_dim = 1
Color col
Color default_color = Color.BLACK
int panel_size
int window_size
boolean highligted = false
double decayRate
double decayThreshold
int type
final int TYPE_PLAIN = 0
final int TYPE_CLUSTERED = 1
StreamPanel sp
Package Attributes
DataPoint point
Static Package Attributes
static final int POINTSIZE = 4
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
Color getErrorColor ()
Color getColor ()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 34 of file PointPanel.java.
Constructor & Destructor Documentation
moa.gui.visualization.PointPanel.PointPanel (DataPoint point, StreamPanel streamPanel, double decayRate, double decayThreshold)
Type 1: Possibly be decayed, colored by class label.
Parameters:
point
streamPanel
decayRate
decayThreshold
Definition at line 68 of file PointPanel.java.
References moa.gui.visualization.PointPanel.col, moa.gui.visualization.PointPanel.default_color, moa.gui.visualization.PointPanel.initComponents(), moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.POINTSIZE, moa.gui.visualization.PointPanel.sp, moa.gui.visualization.PointPanel.type, and moa.gui.visualization.PointPanel.TYPE_PLAIN.
{
        this.point = point;
        this.panel_size = POINTSIZE;
        this.decayRate = decayRate;
        this.decayThreshold = decayThreshold;
        this.col = default_color;
        this.sp = streamPanel;
        this.type = TYPE_PLAIN;
        setVisible(true);
        setOpaque(false);
        setSize(new Dimension(1, 1));
        setLocation(0, 0);
        initComponents();
    }
moa.gui.visualization.PointPanel.PointPanel (DataPoint point, StreamPanel streamPanel, Color color)
Type 2: Never be decayed, single color.
Parameters:
point
streamPanel
color
Definition at line 91 of file PointPanel.java.
References moa.gui.visualization.PointPanel.col, moa.gui.visualization.PointPanel.decayRate, moa.gui.visualization.PointPanel.decayThreshold, moa.gui.visualization.PointPanel.initComponents(), moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.POINTSIZE, moa.gui.visualization.PointPanel.sp, moa.gui.visualization.PointPanel.type, and moa.gui.visualization.PointPanel.TYPE_CLUSTERED.
{
        this.point = point;
        this.panel_size = POINTSIZE;
        this.decayRate = 0;         // Never be decayed
        this.decayThreshold = 0;
        this.col = color;
        this.sp = streamPanel;
        this.type = TYPE_CLUSTERED;
        setVisible(true);
        setOpaque(false);
        setSize(new Dimension(1, 1));
        setLocation(0,0);
        initComponents();
    }
Member Function Documentation
void moa.gui.visualization.PointPanel.drawOnCanvas (Graphics2D imageGraphics)
Definition at line 286 of file PointPanel.java.
References moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.type, moa.gui.visualization.PointPanel.TYPE_CLUSTERED, and moa.gui.visualization.PointPanel.TYPE_PLAIN.
{
        Point location = getLocation();
        if (type == TYPE_PLAIN) {
            imageGraphics.drawOval(location.x, location.y, panel_size, panel_size);
            imageGraphics.fillOval(location.x, location.y, panel_size, panel_size);
        } else if (type == TYPE_CLUSTERED) {
            imageGraphics.drawOval(location.x, location.y, panel_size, panel_size);
        }
    }
Color moa.gui.visualization.PointPanel.getColor () [private]
Definition at line 201 of file PointPanel.java.
References moa.gui.visualization.PointPanel.col, moa.gui.visualization.ClusterPanel.getClusterLabel(), moa.gui.visualization.StreamPanel.getHighlightedClusterPanel(), moa.gui.visualization.PointPanel.getPointColorbyClass(), moa.gui.visualization.DataPoint.isNoise(), moa.gui.visualization.PointPanel.point, moa.gui.visualization.PointPanel.sp, moa.gui.visualization.PointPanel.type, moa.gui.visualization.PointPanel.TYPE_CLUSTERED, and moa.gui.visualization.PointPanel.TYPE_PLAIN.
Referenced by moa.gui.visualization.PointPanel.getSVGString(), and moa.gui.visualization.PointPanel.paintComponent().
{
        Color color = null;
        if (type == TYPE_PLAIN) {
            ClusterPanel cp = sp.getHighlightedClusterPanel();
            if (cp != null) {
                if (cp.getClusterLabel() == point.classValue()) {
                    color = Color.BLUE;
                }
            }
            if (color == null) {
                int alpha = (int)(point.weight() * 200 + 55);
                float numCl = 10;
                Color c;
                if (point.isNoise()) {
                    c = Color.GRAY;
                } else {
                    c = getPointColorbyClass(point, numCl);
                }
                color = new Color(c.getRed(), c.getGreen(), c.getBlue(), alpha);
            }
        } else if (type == TYPE_CLUSTERED) {
            color = this.col;
        }
        return color;
    }
Color moa.gui.visualization.PointPanel.getErrorColor () [private]
Definition at line 184 of file PointPanel.java.
References moa.gui.visualization.DataPoint.getMeasureValue(), and moa.gui.visualization.PointPanel.point.
{
        String cmdvalue = point.getMeasureValue("CMM");
        Color color = null;
        if(!cmdvalue.equals("")){
            double err = Double.parseDouble(cmdvalue);
            if(err > 0.00001){
                if(err > 0.7) err = 1;
                int alpha = (int)(100+155*err);
                color = new Color(255, 0, 0, alpha);
            }
            if(err == 0.00001){
                color = new Color(255, 0, 0,100);
            }
        }
        return color;
    }
String moa.gui.visualization.PointPanel.getObjectInfo ()
Definition at line 252 of file PointPanel.java.
References moa.gui.visualization.DataPoint.getInfo(), moa.gui.visualization.PointPanel.point, moa.gui.visualization.PointPanel.x_dim, and moa.gui.visualization.PointPanel.y_dim.
{
        return point.getInfo(x_dim, y_dim);
    }
static Color moa.gui.visualization.PointPanel.getPointColorbyClass (DataPoint point, float numClasses) [static]
Definition at line 233 of file PointPanel.java.
References moa.gui.visualization.DataPoint.noiseLabel.
Referenced by moa.gui.visualization.PointPanel.getColor().
{
        Color c;
        int classValue = (int)point.classValue();
        if (classValue != point.noiseLabel) {
            c = new Color(Color.HSBtoRGB((float)((classValue+1)/numClasses), 1f, 240f/240));
        } else {
            c = Color.GRAY;
        }
        return c;
    }
String moa.gui.visualization.PointPanel.getSVGString (int width)
Definition at line 266 of file PointPanel.java.
References moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.point, moa.gui.visualization.PointPanel.window_size, moa.gui.visualization.PointPanel.x_dim, and moa.gui.visualization.PointPanel.y_dim.
Referenced by moa.gui.visualization.StreamPanel.screenshot().
{
        StringBuffer out = new StringBuffer();
        int x = (int)(point.value(x_dim)*window_size);
        int y = (int)(point.value(y_dim)*window_size);
        int radius = panel_size/2;
        //radius = 1;
        Color c = getColor();
        String color = "rgb("+c.getRed()+","+c.getGreen()+","+c.getBlue()+")";
        double trans = c.getAlpha()/255.0;
        out.append("<circle ");
        out.append("cx='"+x+"' cy='"+y+"' r='"+radius+"'");
        out.append(" stroke='"+color+"' stroke-width='0' fill='"+color+"' fill-opacity='"+trans+"' stroke-opacity='"+trans+"'/>");
        out.append("\n");
        return out.toString();
    }
String moa.gui.visualization.PointPanel.getToolTipText ()
Definition at line 257 of file PointPanel.java.
{
        return super.getToolTipText();
    }
void moa.gui.visualization.PointPanel.highlight (boolean enabled)
Definition at line 246 of file PointPanel.java.
References moa.gui.visualization.PointPanel.highligted.
{
        highligted = enabled;
        repaint();
    }
void moa.gui.visualization.PointPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 124 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.PointPanel().
{
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void moa.gui.visualization.PointPanel.paintComponent (Graphics g) [protected]
Definition at line 139 of file PointPanel.java.
References moa.gui.visualization.PointPanel.decayRate, moa.gui.visualization.PointPanel.decayThreshold, moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.DataPoint.getInfo(), moa.gui.visualization.DataPoint.isNoise(), moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.point, moa.gui.visualization.PointPanel.POINTSIZE, moa.gui.visualization.PointPanel.type, moa.gui.visualization.PointPanel.TYPE_CLUSTERED, moa.gui.visualization.PointPanel.TYPE_PLAIN, moa.gui.visualization.PointPanel.updateLocation(), moa.gui.visualization.DataPoint.updateWeight(), moa.gui.visualization.PointPanel.x_dim, and moa.gui.visualization.PointPanel.y_dim.
{
        if (type == TYPE_PLAIN) {
            point.updateWeight(RunVisualizer.getCurrentTimestamp(), decayRate);
            if (point.weight() < decayThreshold) {
                getParent().remove(this);
                return;
            }
        }
        Color color = getColor();
      //Color errcolor = getErrorColor();
        //if (errcolor == null) {
        //    errcolor = color;
            panel_size = POINTSIZE;
        //} else {
        //    panel_size = POINTSIZE + 2;
        //}
        updateLocation();
        /*g.setColor(errcolor);
        g.drawOval(0, 0, panel_size, panel_size);
        g.setColor(color);
        g.fillOval(0, 0, panel_size, panel_size);*/
        if (type == TYPE_PLAIN) {
            g.setColor(color);
            if (point.isNoise()) {
                g.setFont(g.getFont().deriveFont(9.0f));
                g.drawChars(new char[] {'x'}, 0, 1, 0, panel_size);
            } else {
                g.drawOval(0, 0, panel_size, panel_size);
                g.setColor(color);
                g.fillOval(0, 0, panel_size, panel_size);
            }
        } else if (type == TYPE_CLUSTERED) {
            g.setColor(color);
            g.drawOval(0, 0, panel_size, panel_size);
        }
        setToolTipText(point.getInfo(x_dim, y_dim));
    }
void moa.gui.visualization.PointPanel.updateLocation ()
Definition at line 107 of file PointPanel.java.
References moa.gui.visualization.StreamPanel.getActiveXDim(), moa.gui.visualization.StreamPanel.getActiveYDim(), moa.gui.visualization.PointPanel.panel_size, moa.gui.visualization.PointPanel.point, moa.gui.visualization.PointPanel.sp, moa.gui.visualization.PointPanel.window_size, moa.gui.visualization.PointPanel.x_dim, and moa.gui.visualization.PointPanel.y_dim.
Referenced by moa.gui.visualization.StreamPanel.drawNonConvexClustering(), moa.gui.visualization.StreamPanel.drawPointPanels(), and moa.gui.visualization.PointPanel.paintComponent().
{
        window_size = Math.min(sp.getWidth(), sp.getHeight());
        x_dim = sp.getActiveXDim();
        y_dim = sp.getActiveYDim();
        setSize(new Dimension(panel_size + 1, panel_size + 1));
        setLocation((int)(point.value(x_dim) * window_size - (panel_size / 2)), (int)(point.value(y_dim) * window_size - (panel_size / 2)));
    }
Member Data Documentation
Color moa.gui.visualization.PointPanel.col [protected]
Definition at line 43 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getColor(), and moa.gui.visualization.PointPanel.PointPanel().
double moa.gui.visualization.PointPanel.decayRate [protected]
Definition at line 50 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
double moa.gui.visualization.PointPanel.decayThreshold [protected]
Definition at line 51 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
Color moa.gui.visualization.PointPanel.default_color = Color.BLACK [protected]
Definition at line 44 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.PointPanel().
boolean moa.gui.visualization.PointPanel.highligted = false [protected]
Definition at line 48 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.highlight().
int moa.gui.visualization.PointPanel.panel_size [protected]
Definition at line 46 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.drawOnCanvas(), moa.gui.visualization.PointPanel.getSVGString(), moa.gui.visualization.PointPanel.paintComponent(), moa.gui.visualization.PointPanel.PointPanel(), and moa.gui.visualization.PointPanel.updateLocation().
DataPoint moa.gui.visualization.PointPanel.point [package]
Definition at line 39 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.getErrorColor(), moa.gui.visualization.PointPanel.getObjectInfo(), moa.gui.visualization.PointPanel.getSVGString(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.updateLocation().
final int moa.gui.visualization.PointPanel.POINTSIZE = 4 [static, package]
Definition at line 38 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
final long moa.gui.visualization.PointPanel.serialVersionUID = 1L [static, private]
Definition at line 36 of file PointPanel.java.
StreamPanel moa.gui.visualization.PointPanel.sp [protected]
Definition at line 57 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.PointPanel(), and moa.gui.visualization.PointPanel.updateLocation().
int moa.gui.visualization.PointPanel.type [protected]
Definition at line 53 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.drawOnCanvas(), moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
final int moa.gui.visualization.PointPanel.TYPE_CLUSTERED = 1 [protected]
Definition at line 55 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.drawOnCanvas(), moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
final int moa.gui.visualization.PointPanel.TYPE_PLAIN = 0 [protected]
Definition at line 54 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.drawOnCanvas(), moa.gui.visualization.PointPanel.getColor(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.PointPanel().
int moa.gui.visualization.PointPanel.window_size [protected]
Definition at line 47 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getSVGString(), and moa.gui.visualization.PointPanel.updateLocation().
int moa.gui.visualization.PointPanel.x_dim = 0 [protected]
Definition at line 41 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getObjectInfo(), moa.gui.visualization.PointPanel.getSVGString(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.updateLocation().
int moa.gui.visualization.PointPanel.y_dim = 1 [protected]
Definition at line 42 of file PointPanel.java.
Referenced by moa.gui.visualization.PointPanel.getObjectInfo(), moa.gui.visualization.PointPanel.getSVGString(), moa.gui.visualization.PointPanel.paintComponent(), and moa.gui.visualization.PointPanel.updateLocation().
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/PointPanel.java