MOA: moa.gui.OptionsConfigurationPanel Class Reference
moa.gui.OptionsConfigurationPanel Class Reference
This panel displays an options configuration.
Public Member Functions
OptionsConfigurationPanel (String purposeString, Options options)
String getHelpText ()
void showHelpDialog ()
void resetToDefaults ()
void applyChanges ()
Static Public Member Functions
static boolean showEditOptionsDialog (Component parent, String title, OptionHandler optionHandler)
static void main (String[] args)
Static Public Attributes
static final int FIXED_PANEL_WIDTH = 400
static final int MAX_PANEL_HEIGHT = 300
Static Protected Member Functions
static JPanel createLabelledOptionComponentListPanel (Option[] options, List< OptionEditComponent > editComponents)
Protected Attributes
Options options
List< OptionEditComponent > editComponents = new LinkedList<OptionEditComponent>()
JButton helpButton = new JButton("Help")
JButton resetButton = new JButton("Reset to defaults")
Static Private Member Functions
static void createAndShowGUI ()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays an options configuration.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 58 of file OptionsConfigurationPanel.java.
Constructor & Destructor Documentation
moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel (String purposeString, Options options)
Definition at line 74 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.createLabelledOptionComponentListPanel(), moa.gui.OptionsConfigurationPanel.editComponents, moa.gui.OptionsConfigurationPanel.FIXED_PANEL_WIDTH, moa.options.Options.getOptionArray(), moa.gui.OptionsConfigurationPanel.helpButton, moa.gui.OptionsConfigurationPanel.MAX_PANEL_HEIGHT, moa.gui.OptionsConfigurationPanel.resetButton, moa.gui.OptionsConfigurationPanel.resetToDefaults(), and moa.gui.OptionsConfigurationPanel.showHelpDialog().
Referenced by moa.gui.OptionsConfigurationPanel.createAndShowGUI(), and moa.gui.OptionsConfigurationPanel.showEditOptionsDialog().
{
        this.options = options;
        setLayout(new BorderLayout());
        if (purposeString != null) {
            JTextArea purposeTextArea = new JTextArea(purposeString, 3, 0);
            purposeTextArea.setEditable(false);
            purposeTextArea.setLineWrap(true);
            purposeTextArea.setWrapStyleWord(true);
            purposeTextArea.setEnabled(false);
            purposeTextArea.setBorder(BorderFactory.createTitledBorder("Purpose"));
            purposeTextArea.setBackground(getBackground());
            JScrollPane scrollPanePurpose = new JScrollPane(purposeTextArea,
            ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
            ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            scrollPanePurpose.setBorder(null);
            add(scrollPanePurpose, BorderLayout.NORTH);
        }
        JPanel optionsPanel = createLabelledOptionComponentListPanel(options.getOptionArray(), this.editComponents);
        JScrollPane scrollPane = new JScrollPane(optionsPanel,
                ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
                ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setBorder(null);
        int optionPanelHeight = (int) optionsPanel.getPreferredSize().getHeight();
        int scrollPaneHeight = (int) scrollPane.getPreferredSize().getHeight();
        scrollPane.setPreferredSize(new Dimension(FIXED_PANEL_WIDTH,
                scrollPaneHeight > MAX_PANEL_HEIGHT ? MAX_PANEL_HEIGHT
                : scrollPaneHeight));
        optionsPanel.setPreferredSize(new Dimension(0, optionPanelHeight));
        add(scrollPane, BorderLayout.CENTER);
        JPanel lowerButtons = new JPanel();
        lowerButtons.setLayout(new FlowLayout());
        lowerButtons.add(this.helpButton);
        lowerButtons.add(this.resetButton);
        add(lowerButtons, BorderLayout.SOUTH);
        this.helpButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                showHelpDialog();
            }
        });
        this.resetButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                resetToDefaults();
            }
        });
    }
Member Function Documentation
void moa.gui.OptionsConfigurationPanel.applyChanges ()
Definition at line 155 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.editComponents.
Referenced by moa.gui.OptionsConfigurationPanel.showEditOptionsDialog().
{
        for (OptionEditComponent editor : this.editComponents) {
            try {
                editor.applyState();
            } catch (Exception ex) {
                GUIUtils.showExceptionDialog(this, "Problem with option "
                        + editor.getEditedOption().getName(), ex);
            }
        }
    }
static void moa.gui.OptionsConfigurationPanel.createAndShowGUI () [static, private]
Definition at line 202 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.options, and moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
Referenced by moa.gui.OptionsConfigurationPanel.main().
{
        // Create and set up the window.
        JFrame frame = new JFrame("Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create and set up the content pane.
        Options options = new HoeffdingTree().getOptions();
        JPanel panel = new OptionsConfigurationPanel(null, options);
        // createLabelledOptionComponentListPanel(options
        // .getOptionArray(), null);
        panel.setOpaque(true); // content panes must be opaque
        frame.setContentPane(panel);
        // Display the window.
        frame.pack();
        // frame.setSize(400, 400);
        frame.setVisible(true);
    }
static JPanel moa.gui.OptionsConfigurationPanel.createLabelledOptionComponentListPanel (Option[] options, List< OptionEditComponent > editComponents) [static, protected]
Definition at line 166 of file OptionsConfigurationPanel.java.
References moa.options.Option.getEditComponent().
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
{
        JPanel panel = new JPanel();
        if ((options != null) && (options.length > 0)) {
            GridBagLayout gbLayout = new GridBagLayout();
            GridBagConstraints gbc = new GridBagConstraints();
            panel.setLayout(gbLayout);
            for (int i = 0; i < options.length; i++) {
                JLabel label = new JLabel(options[i].getName());
                label.setToolTipText(options[i].getPurpose());
                gbc.gridx = 0;
                gbc.fill = GridBagConstraints.NONE;
                gbc.anchor = GridBagConstraints.EAST;
                gbc.weightx = 0;
                gbc.insets = new Insets(5, 5, 5, 5);
                gbLayout.setConstraints(label, gbc);
                panel.add(label);
                JComponent editor = options[i].getEditComponent();
                label.setLabelFor(editor);
                if (editComponents != null) {
                    editComponents.add((OptionEditComponent) editor);
                }
                gbc.gridx = 1;
                gbc.fill = GridBagConstraints.HORIZONTAL;
                gbc.anchor = GridBagConstraints.CENTER;
                gbc.weightx = 1;
                gbc.insets = new Insets(5, 5, 5, 5);
                gbLayout.setConstraints(editor, gbc);
                panel.add(editor);
            }
        } else {
            panel.add(new JLabel("No options."));
        }
        return panel;
    }
String moa.gui.OptionsConfigurationPanel.getHelpText ()
Definition at line 137 of file OptionsConfigurationPanel.java.
References moa.options.Options.getHelpString(), and moa.gui.OptionsConfigurationPanel.options.
Referenced by moa.gui.OptionsConfigurationPanel.showHelpDialog().
{
        return this.options.getHelpString();
    }
static void moa.gui.OptionsConfigurationPanel.main (String[] args) [static]
Definition at line 222 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.createAndShowGUI().
{
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    createAndShowGUI();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
void moa.gui.OptionsConfigurationPanel.resetToDefaults ()
Definition at line 149 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.editComponents.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
{
        for (OptionEditComponent editor : this.editComponents) {
            editor.setEditState(editor.getEditedOption().getDefaultCLIString());
        }
    }
static boolean moa.gui.OptionsConfigurationPanel.showEditOptionsDialog (Component parent, String title, OptionHandler optionHandler) [static]
Definition at line 124 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.applyChanges(), moa.options.OptionHandler.getOptions(), moa.options.OptionHandler.getPurposeString(), and moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
{
        OptionsConfigurationPanel panel = new OptionsConfigurationPanel(
                optionHandler.getPurposeString(), optionHandler.getOptions());
        if (JOptionPane.showOptionDialog(parent, panel, title,
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                null, null) == JOptionPane.OK_OPTION) {
            panel.applyChanges();
            return true;
        }
        return false;
    }
void moa.gui.OptionsConfigurationPanel.showHelpDialog ()
Definition at line 141 of file OptionsConfigurationPanel.java.
References moa.gui.OptionsConfigurationPanel.getHelpText().
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
{
        JTextArea helpTextArea = new JTextArea(getHelpText(), 20, 80);
        helpTextArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        helpTextArea.setEditable(false);
        JOptionPane.showMessageDialog(this, new JScrollPane(helpTextArea),
                "Options Help", JOptionPane.INFORMATION_MESSAGE);
    }
Member Data Documentation
List<OptionEditComponent> moa.gui.OptionsConfigurationPanel.editComponents = new LinkedList<OptionEditComponent>() [protected]
Definition at line 68 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.applyChanges(), moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel(), and moa.gui.OptionsConfigurationPanel.resetToDefaults().
final int moa.gui.OptionsConfigurationPanel.FIXED_PANEL_WIDTH = 400 [static]
Definition at line 62 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
JButton moa.gui.OptionsConfigurationPanel.helpButton = new JButton("Help") [protected]
Definition at line 70 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
final int moa.gui.OptionsConfigurationPanel.MAX_PANEL_HEIGHT = 300 [static]
Definition at line 64 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
Options moa.gui.OptionsConfigurationPanel.options [protected]
Definition at line 66 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.createAndShowGUI(), and moa.gui.OptionsConfigurationPanel.getHelpText().
JButton moa.gui.OptionsConfigurationPanel.resetButton = new JButton("Reset to defaults") [protected]
Definition at line 72 of file OptionsConfigurationPanel.java.
Referenced by moa.gui.OptionsConfigurationPanel.OptionsConfigurationPanel().
final long moa.gui.OptionsConfigurationPanel.serialVersionUID = 1L [static, private]
Definition at line 60 of file OptionsConfigurationPanel.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/OptionsConfigurationPanel.java