MOA: moa.options.IntOption Class Reference
moa.options.IntOption Class Reference
Int option.
Public Member Functions
IntOption (String name, char cliChar, String purpose, int defaultVal)
IntOption (String name, char cliChar, String purpose, int defaultVal, int minVal, int maxVal)
void setValue (int v)
int getValue ()
int getMinValue ()
int getMaxValue ()
String getDefaultCLIString ()
Gets the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static int cliStringToInt (String s)
static String intToCLIString (int i)
Protected Attributes
int currentVal
int defaultVal
int minVal
int maxVal
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Int option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file IntOption.java.
Constructor & Destructor Documentation
moa.options.IntOption.IntOption (String name, char cliChar, String purpose, int defaultVal)
Definition at line 44 of file IntOption.java.
{
        this(name, cliChar, purpose, defaultVal, Integer.MIN_VALUE,
                Integer.MAX_VALUE);
    }
moa.options.IntOption.IntOption (String name, char cliChar, String purpose, int defaultVal, int minVal, int maxVal)
Definition at line 49 of file IntOption.java.
References moa.options.AbstractOption.resetToDefault().
{
        super(name, cliChar, purpose);
        this.defaultVal = defaultVal;
        this.minVal = minVal;
        this.maxVal = maxVal;
        resetToDefault();
    }
Member Function Documentation
static int moa.options.IntOption.cliStringToInt (String s) [static]
Definition at line 99 of file IntOption.java.
Referenced by moa.options.IntOption.setValueViaCLIString().
{
        return Integer.parseInt(s.trim());
    }
String moa.options.IntOption.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implements moa.options.Option.
Definition at line 85 of file IntOption.java.
References moa.options.IntOption.defaultVal, and moa.options.IntOption.intToCLIString().
{
        return intToCLIString(this.defaultVal);
    }
JComponent moa.options.IntOption.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Reimplemented from moa.options.AbstractOption.
Definition at line 108 of file IntOption.java.
{
        return new IntOptionEditComponent(this);
    }
int moa.options.IntOption.getMaxValue ()
Definition at line 80 of file IntOption.java.
References moa.options.IntOption.maxVal.
Referenced by moa.gui.IntOptionEditComponent.IntOptionEditComponent().
{
        return this.maxVal;
    }
int moa.options.IntOption.getMinValue ()
Definition at line 76 of file IntOption.java.
References moa.options.IntOption.minVal.
Referenced by moa.gui.IntOptionEditComponent.IntOptionEditComponent().
{
        return this.minVal;
    }
int moa.options.IntOption.getValue ()
Definition at line 72 of file IntOption.java.
References moa.options.IntOption.currentVal.
Referenced by moa.streams.generators.HyperplaneGenerator.addDrift(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMse(), moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMseR(), moa.classifiers.rules.RuleClassifier.createRule(), moa.tasks.Plot.createScript(), moa.classifiers.rules.core.RuleActiveLearningNode.debug(), moa.classifiers.rules.core.Rule.debug(), moa.classifiers.rules.AbstractAMRules.debug(), moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.MeasureStreamSpeed.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.EvaluateClustering.doMainTask(), moa.integration.SimpleClusterTest.doTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.streams.clustering.RandomRBFGeneratorEvents.eventScheduler(), moa.classifiers.rules.RuleClassifier.expandeRule(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.streams.generators.RandomRBFGeneratorDrift.generateCentroids(), moa.streams.generators.RandomRBFGenerator.generateCentroids(), moa.streams.generators.RandomTreeGenerator.generateHeader(), moa.streams.generators.RandomRBFGenerator.generateHeader(), moa.streams.generators.HyperplaneGenerator.generateHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.generateHeader(), moa.streams.generators.multilabel.MetaMultilabelGenerator.generateMultilabelHeader(), moa.streams.generators.RandomTreeGenerator.generateRandomTree(), moa.streams.generators.RandomTreeGenerator.generateRandomTreeNode(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.classifiers.trees.RandomHoeffdingTree.LearningNodeNB.getClassVotes(), moa.classifiers.trees.LimAttHoeffdingTree.LearningNodeNB.getClassVotes(), moa.classifiers.trees.HoeffdingTree.LearningNodeNB.getClassVotes(), moa.classifiers.trees.HoeffdingOptionTree.LearningNodeNB.getClassVotes(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes(), moa.clusterers.clustream.WithKmeans.getClusteringResult(), moa.streams.clustering.ClusteringStream.getDecayHorizon(), moa.streams.clustering.ClusteringStream.getEvaluationFrequency(), moa.streams.generators.multilabel.MultilabelArffFileStream.getHeader(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.getModelMeasurementsImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.getModelMeasurementsImpl(), moa.streams.clustering.RandomRBFGeneratorEvents.getNextEvent(), moa.streams.clustering.RandomRBFGeneratorEvents.getNoisePoint(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getSplitPointSuggestions(), moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.lazy.kNN.getVotesForInstance(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.classifiers.meta.TemporallyAugmentedClassifier.initHeader(), moa.streams.clustering.RandomRBFGeneratorEvents.initKernels(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.core.driftdetection.PageHinkleyDM.input(), moa.classifiers.core.driftdetection.GeometricMovingAverageDM.input(), moa.classifiers.core.driftdetection.EWMAChartDM.input(), moa.classifiers.core.driftdetection.DDM.input(), moa.classifiers.core.driftdetection.CusumDM.input(), moa.gui.IntOptionEditComponent.IntOptionEditComponent(), moa.classifiers.rules.AbstractAMRules.isAnomaly(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance(), moa.classifiers.trees.FIMTDD.FIMTDDSplitNode.learnFromInstance(), moa.DoTask.main(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), moa.clusterers.outliers.AbstractC.Test.main(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.classifiers.rules.AMRulesRegressor.newRule(), moa.streams.generators.STAGGERGenerator.nextInstance(), moa.streams.generators.SEAGenerator.nextInstance(), moa.streams.generators.RandomTreeGenerator.nextInstance(), moa.streams.generators.RandomRBFGeneratorDrift.nextInstance(), moa.streams.generators.RandomRBFGenerator.nextInstance(), moa.streams.generators.LEDGeneratorDrift.nextInstance(), moa.streams.generators.LEDGenerator.nextInstance(), moa.streams.generators.HyperplaneGenerator.nextInstance(), moa.streams.generators.AgrawalGenerator.nextInstance(), moa.streams.ConceptDriftStream.nextInstance(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.nextInstance(), moa.classifiers.rules.core.attributeclassobservers.FIMTDDNumericAttributeClassLimitObserver.observeAttributeClass(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.observeAttributeClass(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.observeAttributeClass(), moa.streams.generators.WaveformGeneratorDrift.prepareForUseImpl(), moa.streams.generators.LEDGeneratorDrift.prepareForUseImpl(), moa.streams.generators.cd.AbstractConceptDriftGenerator.prepareForUseImpl(), moa.streams.ConceptDriftStream.prepareForUseImpl(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), moa.recommender.predictor.BRISMFPredictor.prepareForUseImpl(), moa.clusterers.AbstractClusterer.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.AbstractClassifier.prepareForUseImpl(), moa.classifiers.trees.ORTO.ActiveLearningNode.processInstance(), moa.classifiers.trees.ORTO.OptionNode.processInstance(), moa.classifiers.trees.ORTO.SplitNode.processInstance(), moa.classifiers.trees.ORTO.removeExcessTrees(), moa.evaluation.WindowRegressionPerformanceEvaluator.reset(), moa.evaluation.WindowClassificationPerformanceEvaluator.reset(), moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator.reset(), moa.clusterers.outliers.AnyOut.AnyOutCore.resetLearning(), moa.clusterers.streamkm.StreamKM.resetLearningImpl(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), moa.clusterers.clustree.ClusTree.resetLearningImpl(), moa.clusterers.clustream.WithKmeans.resetLearningImpl(), moa.clusterers.clustream.Clustream.resetLearningImpl(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl(), moa.classifiers.meta.RandomRules.resetLearningImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), moa.classifiers.meta.OzaBagAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBag.resetLearningImpl(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), moa.classifiers.meta.OCBoost.resetLearningImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), moa.classifiers.lazy.kNNwithPAWandADWIN.resetLearningImpl(), moa.classifiers.lazy.kNNwithPAW.resetLearningImpl(), moa.streams.generators.WaveformGenerator.restart(), moa.streams.generators.STAGGERGenerator.restart(), moa.streams.generators.SEAGenerator.restart(), moa.streams.generators.RandomTreeGenerator.restart(), moa.streams.generators.RandomRBFGenerator.restart(), moa.streams.generators.multilabel.MetaMultilabelGenerator.restart(), moa.streams.generators.LEDGenerator.restart(), moa.streams.generators.HyperplaneGenerator.restart(), moa.streams.generators.cd.AbstractConceptDriftGenerator.restart(), moa.streams.generators.AgrawalGenerator.restart(), moa.streams.clustering.RandomRBFGeneratorEvents.restart(), moa.streams.clustering.FileStream.restart(), moa.streams.ArffFileStream.restart(), moa.streams.filters.AddNoiseFilter.restartImpl(), moa.gui.BatchCmd.runBatch(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.gui.visualization.RunVisualizer.RunVisualizer(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), moa.classifiers.meta.TemporallyAugmentedClassifier.toString(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk(), moa.clusterers.streamkm.StreamKM.trainOnInstanceImpl(), moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl(), moa.clusterers.ClusterGenerator.trainOnInstanceImpl(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), moa.classifiers.rules.AbstractAMRules.trainOnInstanceImpl(), moa.classifiers.meta.WEKAClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnInstanceImpl(), moa.classifiers.lazy.kNN.trainOnInstanceImpl(), moa.classifiers.rules.functions.Perceptron.trainOnInstanceImpl(), moa.classifiers.DecisionStumpTutorial.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImplPerceptron(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging(), moa.clusterers.outliers.AnyOut.AnyOutCore.updateConfidence(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow(), moa.classifiers.rules.AbstractAMRules.VerboseToConsole(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
{
        return this.currentVal;
    }
String moa.options.IntOption.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.Option.
Definition at line 90 of file IntOption.java.
References moa.options.IntOption.currentVal, and moa.options.IntOption.intToCLIString().
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), and moa.clusterers.denstream.WithDBSCAN.getParameterString().
{
        return intToCLIString(this.currentVal);
    }
static String moa.options.IntOption.intToCLIString (int i) [static]
Definition at line 103 of file IntOption.java.
Referenced by moa.options.IntOption.getDefaultCLIString(), and moa.options.IntOption.getValueAsCLIString().
{
        return Integer.toString(i);
    }
void moa.options.IntOption.setValue (int v)
Definition at line 58 of file IntOption.java.
References moa.options.IntOption.currentVal, moa.options.AbstractOption.getName(), moa.options.IntOption.maxVal, and moa.options.IntOption.minVal.
Referenced by moa.gui.IntOptionEditComponent.applyState(), moa.streams.ArffFileStream.ArffFileStream(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.classifiers.meta.AccuracyUpdatedEnsemble.enforceMemoryLimit(), moa.tasks.EvaluateModel.EvaluateModel(), moa.tasks.EvaluateModelRegression.EvaluateModelRegression(), moa.tasks.LearnModel.LearnModel(), moa.tasks.LearnModelRegression.LearnModelRegression(), moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream(), moa.streams.ConceptDriftStream.prepareForUseImpl(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer(), moa.clusterers.AbstractClusterer.setRandomSeed(), moa.classifiers.AbstractClassifier.setRandomSeed(), and moa.options.IntOption.setValueViaCLIString().
{
        if (v < this.minVal) {
            throw new IllegalArgumentException("Option " + getName()
                    + " cannot be less than " + this.minVal
                    + ", out of range: " + v);
        }
        if (v > this.maxVal) {
            throw new IllegalArgumentException("Option " + getName()
                    + " cannot be greater than " + this.maxVal
                    + ", out of range: " + v);
        }
        this.currentVal = v;
    }
void moa.options.IntOption.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.Option.
Definition at line 95 of file IntOption.java.
References moa.options.IntOption.cliStringToInt(), and moa.options.IntOption.setValue().
{
        setValue(cliStringToInt(s));
    }
Member Data Documentation
int moa.options.IntOption.currentVal [protected]
Definition at line 36 of file IntOption.java.
Referenced by moa.options.IntOption.getValue(), moa.options.IntOption.getValueAsCLIString(), and moa.options.IntOption.setValue().
int moa.options.IntOption.defaultVal [protected]
Definition at line 38 of file IntOption.java.
Referenced by moa.options.IntOption.getDefaultCLIString().
int moa.options.IntOption.maxVal [protected]
Definition at line 42 of file IntOption.java.
Referenced by moa.options.IntOption.getMaxValue(), and moa.options.IntOption.setValue().
int moa.options.IntOption.minVal [protected]
Definition at line 40 of file IntOption.java.
Referenced by moa.options.IntOption.getMinValue(), and moa.options.IntOption.setValue().
final long moa.options.IntOption.serialVersionUID = 1L [static, private]
Definition at line 34 of file IntOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/IntOption.java