MOA: moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator Class Reference
moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator Class Reference
Public Member Functions
Estimator (double a)
void add (double value)
double estimation ()
Protected Attributes
double alpha
double estimation
double b
Detailed Description
Definition at line 49 of file FadingFactorClassificationPerformanceEvaluator.java.
Constructor & Destructor Documentation
moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.Estimator (double a)
Definition at line 57 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.alpha, moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.b, and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation().
{
            alpha = a;
            estimation = 0.0;
            b = 0.0;
        }
Member Function Documentation
void moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.add (double value)
Definition at line 63 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.alpha, moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.b, and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation().
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.addResult().
{
            estimation = alpha * estimation + value;
            b = alpha * b + 1.0;
        }
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation ()
Definition at line 68 of file FadingFactorClassificationPerformanceEvaluator.java.
References moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.b.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.add(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.Estimator().
{
            return b > 0.0 ? estimation / b : 0;
        }
Member Data Documentation
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.alpha [protected]
Definition at line 51 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.add(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.Estimator().
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.b [protected]
Definition at line 55 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.add(), moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation(), and moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.Estimator().
double moa.evaluation.FadingFactorClassificationPerformanceEvaluator.Estimator.estimation [protected]
Definition at line 53 of file FadingFactorClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.FadingFactorClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/FadingFactorClassificationPerformanceEvaluator.java