MOA: moa.recommender.dataset.impl.FlixsterDataset Class Reference
moa.recommender.dataset.impl.FlixsterDataset Class Reference
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void init ()
boolean next ()
int curUserID ()
int curItemID ()
double curRating ()
String toString ()
Returns a description of the object.
void reset ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Public Attributes
FileOption fileOption
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Private Attributes
String strLine
BufferedReader br
Detailed Description
Definition at line 38 of file FlixsterDataset.java.
Member Function Documentation
int moa.recommender.dataset.impl.FlixsterDataset.curItemID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 85 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        return Integer.valueOf(split[1]);
    }
double moa.recommender.dataset.impl.FlixsterDataset.curRating ()
Implements moa.recommender.dataset.Dataset.
Definition at line 91 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        return Double.valueOf(split[2]);
    }
int moa.recommender.dataset.impl.FlixsterDataset.curUserID ()
Implements moa.recommender.dataset.Dataset.
Definition at line 79 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.strLine.
{
        String[] split = strLine.split("\\s+");
        return Integer.valueOf(split[0]);
    }
void moa.recommender.dataset.impl.FlixsterDataset.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 119 of file FlixsterDataset.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.recommender.dataset.impl.FlixsterDataset.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 52 of file FlixsterDataset.java.
{
        return "A Jester Dataset reader.";
    }
void moa.recommender.dataset.impl.FlixsterDataset.init ()
Definition at line 56 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.br, moa.recommender.dataset.impl.FlixsterDataset.fileOption, and moa.options.FileOption.getFile().
Referenced by moa.recommender.dataset.impl.FlixsterDataset.prepareForUseImpl(), and moa.recommender.dataset.impl.FlixsterDataset.reset().
                       {
        FileInputStream fstream = null;
        try {
            fstream = new FileInputStream(this.fileOption.getFile());
            DataInputStream in = new DataInputStream(fstream);
            br = new BufferedReader(new InputStreamReader(in));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MovielensDataset.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
boolean moa.recommender.dataset.impl.FlixsterDataset.next ()
Implements moa.recommender.dataset.Dataset.
Definition at line 69 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.br, and moa.recommender.dataset.impl.FlixsterDataset.strLine.
{
        try {
            return (strLine = br.readLine()) != null;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }
void moa.recommender.dataset.impl.FlixsterDataset.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 114 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.init().
{
        this.init();
    }
void moa.recommender.dataset.impl.FlixsterDataset.reset ()
Implements moa.recommender.dataset.Dataset.
Definition at line 101 of file FlixsterDataset.java.
References moa.recommender.dataset.impl.FlixsterDataset.br, and moa.recommender.dataset.impl.FlixsterDataset.init().
{
        try {
            br.close();
            //FileInputStream fstream = new FileInputStream("/home/alicia/datasets/flixster/ratings.txt");
            //DataInputStream in = new DataInputStream(fstream);
            //br = new BufferedReader(new InputStreamReader(in));
            this.init();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
String moa.recommender.dataset.impl.FlixsterDataset.toString ()
Returns a description of the object.
Returns:
a description of the object
Reimplemented from moa.AbstractMOAObject.
Definition at line 96 of file FlixsterDataset.java.
{
        return "Flixster";
    }
Member Data Documentation
BufferedReader moa.recommender.dataset.impl.FlixsterDataset.br [private]
Definition at line 40 of file FlixsterDataset.java.
Referenced by moa.recommender.dataset.impl.FlixsterDataset.init(), moa.recommender.dataset.impl.FlixsterDataset.next(), and moa.recommender.dataset.impl.FlixsterDataset.reset().
FileOption moa.recommender.dataset.impl.FlixsterDataset.fileOption
Initial value:
 new FileOption("file", 'f',
            "File to load.", "/home/alex/datasets/ratings.txt", "txt", false)
Definition at line 41 of file FlixsterDataset.java.
Referenced by moa.recommender.dataset.impl.FlixsterDataset.init().
String moa.recommender.dataset.impl.FlixsterDataset.strLine [private]
Definition at line 39 of file FlixsterDataset.java.
Referenced by moa.recommender.dataset.impl.FlixsterDataset.curItemID(), moa.recommender.dataset.impl.FlixsterDataset.curRating(), moa.recommender.dataset.impl.FlixsterDataset.curUserID(), and moa.recommender.dataset.impl.FlixsterDataset.next().
The documentation for this class was generated from the following file:
main/java/moa/recommender/dataset/impl/FlixsterDataset.java