MOA: moa.evaluation.BasicClassificationPerformanceEvaluator Class Reference
moa.evaluation.BasicClassificationPerformanceEvaluator Class Reference
Classification evaluator that performs basic incremental evaluation.
Public Member Functions
void reset ()
Resets this evaluator.
void reset (int numClasses)
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getFractionCorrectlyClassified ()
double getFractionIncorrectlyClassified ()
double getKappaStatistic ()
double getKappaTemporalStatistic ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
double weightObserved
double weightCorrect
double[] columnKappa
double[] rowKappa
int numClasses
Private Attributes
double weightCorrectNoChangeClassifier
int lastSeenClass
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Classification evaluator that performs basic incremental evaluation.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 35 of file BasicClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.BasicClassificationPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 74 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.columnKappa, moa.evaluation.BasicClassificationPerformanceEvaluator.lastSeenClass, moa.evaluation.BasicClassificationPerformanceEvaluator.reset(), moa.evaluation.BasicClassificationPerformanceEvaluator.rowKappa, moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, and moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
{
        double weight = inst.weight();
        int trueClass = (int) inst.classValue();
        if (weight > 0.0) {
            if (this.weightObserved == 0) {
                reset(inst.dataset().numClasses());
            }
            this.weightObserved += weight;
            int predictedClass = Utils.maxIndex(classVotes);
            if (predictedClass == trueClass) {
                this.weightCorrect += weight;
            }
            this.rowKappa[predictedClass] += weight;
            this.columnKappa[trueClass] += weight;
        }
        if (this.lastSeenClass == trueClass) {
            this.weightCorrectNoChangeClassifier += weight;
        }
        this.lastSeenClass = trueClass;
    }
void moa.evaluation.BasicClassificationPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 149 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified ()
Definition at line 114 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrect, and moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionIncorrectlyClassified(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved > 0.0 ? this.weightCorrect
                / this.weightObserved : 0.0;
    }
double moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionIncorrectlyClassified ()
Definition at line 119 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified().
{
        return 1.0 - getFractionCorrectlyClassified();
    }
double moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic ()
Definition at line 123 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.columnKappa, moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.BasicClassificationPerformanceEvaluator.numClasses, moa.evaluation.BasicClassificationPerformanceEvaluator.rowKappa, and moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        if (this.weightObserved > 0.0) {
            double p0 = getFractionCorrectlyClassified();
            double pc = 0.0;
            for (int i = 0; i < this.numClasses; i++) {
                pc += (this.rowKappa[i] / this.weightObserved)
                        * (this.columnKappa[i] / this.weightObserved);
            }
            return (p0 - pc) / (1.0 - pc);
        } else {
            return 0;
        }
    }
double moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaTemporalStatistic ()
Definition at line 137 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, and moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        if (this.weightObserved > 0.0) {
            double p0 = this.weightCorrect / this.weightObserved;
            double pc = this.weightCorrectNoChangeClassifier / this.weightObserved;
            return (p0 - pc) / (1.0 - pc);
        } else {
            return 0;
        }
    }
Measurement [] moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 96 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.getTotalWeightObserved().
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
            new Measurement("classified instances",
            getTotalWeightObserved()),
            new Measurement("classifications correct (percent)",
            getFractionCorrectlyClassified() * 100.0),
            new Measurement("Kappa Statistic (percent)",
            getKappaStatistic() * 100.0),
            new Measurement("Kappa Temporal Statistic (percent)",
            getKappaTemporalStatistic() * 100.0)
        };
    }
double moa.evaluation.BasicClassificationPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 110 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved;
    }
void moa.evaluation.BasicClassificationPerformanceEvaluator.reset (int numClasses)
Definition at line 59 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.columnKappa, moa.evaluation.BasicClassificationPerformanceEvaluator.lastSeenClass, moa.evaluation.BasicClassificationPerformanceEvaluator.rowKappa, moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrect, moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier, and moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved.
{
        this.numClasses = numClasses;
        this.rowKappa = new double[numClasses];
        this.columnKappa = new double[numClasses];
        for (int i = 0; i < this.numClasses; i++) {
            this.rowKappa[i] = 0.0;
            this.columnKappa[i] = 0.0;
        }
        this.weightObserved = 0.0;
        this.weightCorrect = 0.0;
        this.weightCorrectNoChangeClassifier = 0.0;
        this.lastSeenClass = 0;
    }
void moa.evaluation.BasicClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 55 of file BasicClassificationPerformanceEvaluator.java.
References moa.evaluation.BasicClassificationPerformanceEvaluator.numClasses.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult().
{
        reset(this.numClasses);
    }
Member Data Documentation
double [] moa.evaluation.BasicClassificationPerformanceEvaluator.columnKappa [protected]
Definition at line 44 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
int moa.evaluation.BasicClassificationPerformanceEvaluator.lastSeenClass [private]
Definition at line 52 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
int moa.evaluation.BasicClassificationPerformanceEvaluator.numClasses [protected]
Definition at line 48 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
double [] moa.evaluation.BasicClassificationPerformanceEvaluator.rowKappa [protected]
Definition at line 46 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
final long moa.evaluation.BasicClassificationPerformanceEvaluator.serialVersionUID = 1L [static, private]
Definition at line 38 of file BasicClassificationPerformanceEvaluator.java.
double moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrect [protected]
Definition at line 42 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
double moa.evaluation.BasicClassificationPerformanceEvaluator.weightCorrectNoChangeClassifier [private]
Definition at line 50 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaTemporalStatistic(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
double moa.evaluation.BasicClassificationPerformanceEvaluator.weightObserved [protected]
Definition at line 40 of file BasicClassificationPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicClassificationPerformanceEvaluator.addResult(), moa.evaluation.BasicClassificationPerformanceEvaluator.getFractionCorrectlyClassified(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaStatistic(), moa.evaluation.BasicClassificationPerformanceEvaluator.getKappaTemporalStatistic(), moa.evaluation.BasicClassificationPerformanceEvaluator.getTotalWeightObserved(), and moa.evaluation.BasicClassificationPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/BasicClassificationPerformanceEvaluator.java