MOA: moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver Class Reference
moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver Class Reference
Class for observing the class data distribution for a nominal attribute.
Public Member Functions
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
double totalWeightOfClassObservations ()
double weightOfObservedMissingValues ()
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
int getMaxAttValsObserved ()
double[][] getClassDistsResultingFromMultiwaySplit (int maxAttValsObserved)
double[][] getClassDistsResultingFromBinarySplit (int valIndex)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void observeAttributeTarget (double attVal, double target)
Public Attributes
AutoExpandVector< DoubleVector > attValDistPerClass = new AutoExpandVector<DoubleVector>()
Protected Member Functions
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
double totalWeightObserved = 0.0
double missingWeightObserved = 0.0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class for observing the class data distribution for a nominal attribute.
This observer monitors the class distribution of a given attribute. Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 42 of file NominalAttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 86 of file NominalAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getMaxAttValsObserved(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), and moa.classifiers.core.AttributeSplitSuggestion.merit.
{
        AttributeSplitSuggestion bestSuggestion = null;
        int maxAttValsObserved = getMaxAttValsObserved();
        if (!binaryOnly) {
            double[][] postSplitDists = getClassDistsResultingFromMultiwaySplit(maxAttValsObserved);
            double merit = criterion.getMeritOfSplit(preSplitDist,
                    postSplitDists);
            bestSuggestion = new AttributeSplitSuggestion(
                    new NominalAttributeMultiwayTest(attIndex), postSplitDists,
                    merit);
        }
        for (int valIndex = 0; valIndex < maxAttValsObserved; valIndex++) {
            double[][] postSplitDists = getClassDistsResultingFromBinarySplit(valIndex);
            double merit = criterion.getMeritOfSplit(preSplitDist,
                    postSplitDists);
            if ((bestSuggestion == null) || (merit > bestSuggestion.merit)) {
                bestSuggestion = new AttributeSplitSuggestion(
                        new NominalAttributeBinaryTest(attIndex, valIndex),
                        postSplitDists, merit);
            }
        }
        return bestSuggestion;
    }
double [][] moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit (int valIndex)
Definition at line 144 of file NominalAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass, moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.getValue(), and moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        DoubleVector equalsDist = new DoubleVector();
        DoubleVector notEqualDist = new DoubleVector();
        for (int i = 0; i < this.attValDistPerClass.size(); i++) {
            DoubleVector attValDist = this.attValDistPerClass.get(i);
            if (attValDist != null) {
                for (int j = 0; j < attValDist.numValues(); j++) {
                    if (j == valIndex) {
                        equalsDist.addToValue(i, attValDist.getValue(j));
                    } else {
                        notEqualDist.addToValue(i, attValDist.getValue(j));
                    }
                }
            }
        }
        return new double[][]{equalsDist.getArrayRef(),
                    notEqualDist.getArrayRef()};
    }
double [][] moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit (int maxAttValsObserved)
Definition at line 123 of file NominalAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass, moa.core.DoubleVector.getArrayRef(), moa.core.DoubleVector.getValue(), and moa.core.DoubleVector.numValues().
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        DoubleVector[] resultingDists = new DoubleVector[maxAttValsObserved];
        for (int i = 0; i < resultingDists.length; i++) {
            resultingDists[i] = new DoubleVector();
        }
        for (int i = 0; i < this.attValDistPerClass.size(); i++) {
            DoubleVector attValDist = this.attValDistPerClass.get(i);
            if (attValDist != null) {
                for (int j = 0; j < attValDist.numValues(); j++) {
                    resultingDists[j].addToValue(i, attValDist.getValue(j));
                }
            }
        }
        double[][] distributions = new double[maxAttValsObserved][];
        for (int i = 0; i < distributions.length; i++) {
            distributions[i] = resultingDists[i].getArrayRef();
        }
        return distributions;
    }
void moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 164 of file NominalAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
int moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getMaxAttValsObserved ()
Definition at line 112 of file NominalAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass.
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getBestEvaluatedSplitSuggestion().
{
        int maxAttValsObserved = 0;
        for (DoubleVector attValDist : this.attValDistPerClass) {
            if ((attValDist != null)
                    && (attValDist.numValues() > maxAttValsObserved)) {
                maxAttValsObserved = attValDist.numValues();
            }
        }
        return maxAttValsObserved;
    }
void moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 54 of file NominalAttributeClassObserver.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.missingWeightObserved, and moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.totalWeightObserved.
{
        if (Utils.isMissingValue(attVal)) {
            this.missingWeightObserved += weight;
        } else {
            int attValInt = (int) attVal;
            DoubleVector valDist = this.attValDistPerClass.get(classVal);
            if (valDist == null) {
                valDist = new DoubleVector();
                this.attValDistPerClass.set(classVal, valDist);
            }
            valDist.addToValue(attValInt, weight);
        }
        this.totalWeightObserved += weight;
    }
void moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 174 of file NominalAttributeClassObserver.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
void moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 169 of file NominalAttributeClassObserver.java.
{
        // TODO Auto-generated method stub
    }
double moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implements moa.classifiers.core.attributeclassobservers.AttributeClassObserver.
Definition at line 70 of file NominalAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass, moa.core.DoubleVector.getValue(), moa.core.DoubleVector.numValues(), and moa.core.DoubleVector.sumOfValues().
{
        DoubleVector obs = this.attValDistPerClass.get(classVal);
        return obs != null ? (obs.getValue((int) attVal) + 1.0)
                / (obs.sumOfValues() + obs.numValues()) : 0.0;
    }
double moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.totalWeightOfClassObservations ()
Definition at line 77 of file NominalAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.totalWeightObserved.
{
        return this.totalWeightObserved;
    }
double moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.weightOfObservedMissingValues ()
Definition at line 81 of file NominalAttributeClassObserver.java.
References moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.missingWeightObserved.
{
        return this.missingWeightObserved;
    }
Member Data Documentation
AutoExpandVector<DoubleVector> moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.attValDistPerClass = new AutoExpandVector<DoubleVector>()
Definition at line 51 of file NominalAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromBinarySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getClassDistsResultingFromMultiwaySplit(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getMaxAttValsObserved(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.probabilityOfAttributeValueGivenClass().
double moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.missingWeightObserved = 0.0 [protected]
Definition at line 49 of file NominalAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.weightOfObservedMissingValues().
final long moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 45 of file NominalAttributeClassObserver.java.
double moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.totalWeightObserved = 0.0 [protected]
Definition at line 47 of file NominalAttributeClassObserver.java.
Referenced by moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.observeAttributeClass(), and moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.totalWeightOfClassObservations().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/NominalAttributeClassObserver.java