MOA: moa.classifiers.meta.OzaBoostAdwin Class Reference
moa.classifiers.meta.OzaBoostAdwin Class Reference
Boosting for evolving data streams using ADWIN.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
double[] getVotesForInstanceBinary (Instance inst)
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption baseLearnerOption
IntOption ensembleSizeOption
FlagOption pureBoostOption
FloatOption deltaAdwinOption
FlagOption outputCodesOption
FlagOption sammeOption
Protected Member Functions
double getEnsembleMemberWeight (int i)
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
double[] scms
double[] swms
ADWIN[] ADError
int numberOfChangesDetected
int[][] matrixCodes
boolean initMatrixCodes = false
double logKm1 = 0.0
int Km1 = 1
boolean initKm1 = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Boosting for evolving data streams using ADWIN.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 40 of file OzaBoostAdwin.java.
Member Function Documentation
double moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight (int i) [protected]
Definition at line 200 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.logKm1, moa.classifiers.meta.OzaBoostAdwin.scms, and moa.classifiers.meta.OzaBoostAdwin.swms.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), and moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary().
{
        double em = this.swms[i] / (this.scms[i] + this.swms[i]);
        if ((em == 0.0) || (em > 0.5)) {
            return this.logKm1;
        }
        return Math.log((1.0 - em) / em) + this.logKm1;
    }
void moa.classifiers.meta.OzaBoostAdwin.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 262 of file OzaBoostAdwin.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.OzaBoostAdwin.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 267 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.ensemble, and moa.classifiers.meta.OzaBoostAdwin.numberOfChangesDetected.
{
        return new Measurement[]{new Measurement("ensemble size",
                    this.ensemble != null ? this.ensemble.length : 0),
                    new Measurement("change detections", this.numberOfChangesDetected)
                };
    }
String moa.classifiers.meta.OzaBoostAdwin.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 45 of file OzaBoostAdwin.java.
{
        return "Boosting for evolving data streams using ADWIN.";
    }
Classifier [] moa.classifiers.meta.OzaBoostAdwin.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 275 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 209 of file OzaBoostAdwin.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.OzaBoostAdwin.ensemble, moa.core.DoubleVector.getArrayRef(), moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary(), moa.options.FlagOption.isSet, moa.core.DoubleVector.normalize(), moa.classifiers.meta.OzaBoostAdwin.outputCodesOption, moa.core.DoubleVector.scaleValues(), and moa.core.DoubleVector.sumOfValues().
{
        if (this.outputCodesOption.isSet()) {
            return getVotesForInstanceBinary(inst);
        }
        DoubleVector combinedVote = new DoubleVector();
        for (int i = 0; i < this.ensemble.length; i++) {
            double memberWeight = getEnsembleMemberWeight(i);
            if (memberWeight > 0.0) {
                DoubleVector vote = new DoubleVector(this.ensemble[i].getVotesForInstance(inst));
                if (vote.sumOfValues() > 0.0) {
                    vote.normalize();
                    vote.scaleValues(memberWeight);
                    combinedVote.addValues(vote);
                }
            } else {
                break;
            }
        }
        return combinedVote.getArrayRef();
    }
double [] moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary (Instance inst)
Definition at line 230 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.ensemble, moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.initMatrixCodes, and moa.classifiers.meta.OzaBoostAdwin.matrixCodes.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance().
{
        double combinedVote[] = new double[(int) inst.numClasses()];
        Instance weightedInst = (Instance) inst.copy();
        if (this.initMatrixCodes == false) {
            for (int i = 0; i < this.ensemble.length; i++) {
                //Replace class by OC
                weightedInst.setClassValue((double) this.matrixCodes[i][(int) inst.classValue()]);
                double vote[];
                vote = this.ensemble[i].getVotesForInstance(weightedInst);
                //Binary Case
                int voteClass = 0;
                if (vote.length == 2) {
                    voteClass = (vote[1] > vote[0] ? 1 : 0);
                }
                //Update votes
                for (int j = 0; j < inst.numClasses(); j++) {
                    if (this.matrixCodes[i][j] == voteClass) {
                        combinedVote[j] += getEnsembleMemberWeight(i);
                    }
                }
            }
        }
        return combinedVote;
    }
boolean moa.classifiers.meta.OzaBoostAdwin.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 257 of file OzaBoostAdwin.java.
{
        return true;
    }
void moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 88 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.ADError, moa.classifiers.meta.OzaBoostAdwin.baseLearnerOption, moa.classifiers.Classifier.copy(), moa.classifiers.meta.OzaBoostAdwin.deltaAdwinOption, moa.classifiers.meta.OzaBoostAdwin.ensemble, moa.classifiers.meta.OzaBoostAdwin.ensembleSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.meta.OzaBoostAdwin.initKm1, moa.classifiers.meta.OzaBoostAdwin.initMatrixCodes, moa.options.FlagOption.isSet, moa.classifiers.meta.OzaBoostAdwin.numberOfChangesDetected, moa.classifiers.meta.OzaBoostAdwin.outputCodesOption, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OzaBoostAdwin.sammeOption, moa.classifiers.meta.OzaBoostAdwin.scms, and moa.classifiers.meta.OzaBoostAdwin.swms.
{
        this.ensemble = new Classifier[this.ensembleSizeOption.getValue()];
        Classifier baseLearner = (Classifier) getPreparedClassOption(this.baseLearnerOption);
        baseLearner.resetLearning();
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = baseLearner.copy();
        }
        this.scms = new double[this.ensemble.length];
        this.swms = new double[this.ensemble.length];
        this.ADError = new ADWIN[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ADError[i] = new ADWIN((double) this.deltaAdwinOption.getValue());
        }
        this.numberOfChangesDetected = 0;
        if (this.outputCodesOption.isSet()) {
            this.initMatrixCodes = true;
        }
        if (this.sammeOption.isSet()) {
            this.initKm1 = true;
        }
    }
void moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 112 of file OzaBoostAdwin.java.
References moa.classifiers.meta.OzaBoostAdwin.ADError, moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.Classifier.correctlyClassifies(), moa.classifiers.AbstractClassifier.correctlyClassifies(), moa.classifiers.meta.OzaBoostAdwin.deltaAdwinOption, moa.classifiers.meta.OzaBoostAdwin.ensemble, moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.options.FloatOption.getValue(), moa.classifiers.meta.OzaBoostAdwin.initKm1, moa.classifiers.meta.OzaBoostAdwin.initMatrixCodes, moa.options.FlagOption.isSet, moa.classifiers.meta.OzaBoostAdwin.Km1, moa.classifiers.meta.OzaBoostAdwin.logKm1, moa.classifiers.meta.OzaBoostAdwin.matrixCodes, moa.classifiers.meta.OzaBoostAdwin.numberOfChangesDetected, moa.classifiers.meta.OzaBoostAdwin.outputCodesOption, moa.classifiers.meta.OzaBoostAdwin.pureBoostOption, moa.classifiers.Classifier.resetLearning(), moa.classifiers.meta.OzaBoostAdwin.sammeOption, moa.classifiers.meta.OzaBoostAdwin.scms, moa.classifiers.meta.OzaBoostAdwin.swms, moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.Classifier.trainOnInstance().
{
        int numClasses = inst.numClasses();
        // Set log (k-1) and (k-1) for SAMME Method
        if (this.sammeOption.isSet()) {
            this.Km1 = numClasses - 1;
            this.logKm1 = Math.log(this.Km1);
            this.initKm1 = false;
        }
        //Output Codes
        if (this.initMatrixCodes == true) {
            this.matrixCodes = new int[this.ensemble.length][inst.numClasses()];
            for (int i = 0; i < this.ensemble.length; i++) {
                int numberOnes;
                int numberZeros;
                do { // until we have the same number of zeros and ones
                    numberOnes = 0;
                    numberZeros = 0;
                    for (int j = 0; j < numClasses; j++) {
                        int result = 0;
                        if (j == 1 && numClasses == 2) {
                            result = 1 - this.matrixCodes[i][0];
                        } else {
                            result = (this.classifierRandom.nextBoolean() ? 1 : 0);
                        }
                        this.matrixCodes[i][j] = result;
                        if (result == 1) {
                            numberOnes++;
                        } else {
                            numberZeros++;
                        }
                    }
                } while ((numberOnes - numberZeros) * (numberOnes - numberZeros) > (this.ensemble.length % 2));
            }
            this.initMatrixCodes = false;
        }
        boolean Change = false;
        double lambda_d = 1.0;
        Instance weightedInst = (Instance) inst.copy();
        for (int i = 0; i < this.ensemble.length; i++) {
            double k = this.pureBoostOption.isSet() ? lambda_d : MiscUtils.poisson(lambda_d * this.Km1, this.classifierRandom);
            if (k > 0.0) {
                if (this.outputCodesOption.isSet()) {
                    weightedInst.setClassValue((double) this.matrixCodes[i][(int) inst.classValue()]);
                }
                weightedInst.setWeight(inst.weight() * k);
                this.ensemble[i].trainOnInstance(weightedInst);
            }
            boolean correctlyClassifies = this.ensemble[i].correctlyClassifies(weightedInst);
            if (correctlyClassifies) {
                this.scms[i] += lambda_d;
                lambda_d *= this.trainingWeightSeenByModel / (2 * this.scms[i]);
            } else {
                this.swms[i] += lambda_d;
                lambda_d *= this.trainingWeightSeenByModel / (2 * this.swms[i]);
            }
            double ErrEstim = this.ADError[i].getEstimation();
            if (this.ADError[i].setInput(correctlyClassifies ? 0 : 1)) {
                if (this.ADError[i].getEstimation() > ErrEstim) {
                    Change = true;
                }
            }
        }
        if (Change) {
            numberOfChangesDetected++;
            double max = 0.0;
            int imax = -1;
            for (int i = 0; i < this.ensemble.length; i++) {
                if (max < this.ADError[i].getEstimation()) {
                    max = this.ADError[i].getEstimation();
                    imax = i;
                }
            }
            if (imax != -1) {
                this.ensemble[imax].resetLearning();
                //this.ensemble[imax].trainOnInstance(inst);
                this.ADError[imax] = new ADWIN((double) this.deltaAdwinOption.getValue());
                this.scms[imax] = 0;
                this.swms[imax] = 0;
            }
        }
    }
Member Data Documentation
ADWIN [] moa.classifiers.meta.OzaBoostAdwin.ADError [protected]
Definition at line 73 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
ClassOption moa.classifiers.meta.OzaBoostAdwin.baseLearnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "trees.HoeffdingTree")
Definition at line 49 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl().
FloatOption moa.classifiers.meta.OzaBoostAdwin.deltaAdwinOption
Initial value:
 new FloatOption("deltaAdwin", 'a',
            "Delta of Adwin change detection", 0.002, 0.0, 1.0)
Definition at line 58 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
Classifier [] moa.classifiers.meta.OzaBoostAdwin.ensemble [protected]
Definition at line 67 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getModelMeasurementsImpl(), moa.classifiers.meta.OzaBoostAdwin.getSubClassifiers(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
IntOption moa.classifiers.meta.OzaBoostAdwin.ensembleSizeOption
Initial value:
 new IntOption("ensembleSize", 's',
            "The number of models to boost.", 10, 1, Integer.MAX_VALUE)
Definition at line 52 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl().
boolean moa.classifiers.meta.OzaBoostAdwin.initKm1 = false [protected]
Definition at line 85 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
boolean moa.classifiers.meta.OzaBoostAdwin.initMatrixCodes = false [protected]
Definition at line 79 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
int moa.classifiers.meta.OzaBoostAdwin.Km1 = 1 [protected]
Definition at line 83 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
double moa.classifiers.meta.OzaBoostAdwin.logKm1 = 0.0 [protected]
Definition at line 81 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
int [][] moa.classifiers.meta.OzaBoostAdwin.matrixCodes [protected]
Definition at line 77 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
int moa.classifiers.meta.OzaBoostAdwin.numberOfChangesDetected [protected]
Definition at line 75 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getModelMeasurementsImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.OzaBoostAdwin.outputCodesOption
Initial value:
 new FlagOption("outputCodes", 'o',
            "Use Output Codes to use binary classifiers.")
Definition at line 61 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.OzaBoostAdwin.pureBoostOption
Initial value:
 new FlagOption("pureBoost", 'p',
            "Boost with weights only; no poisson.")
Definition at line 55 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
FlagOption moa.classifiers.meta.OzaBoostAdwin.sammeOption
Initial value:
 new FlagOption("same", 'e',
            "Use Samme Algorithm.")
Definition at line 64 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
double [] moa.classifiers.meta.OzaBoostAdwin.scms [protected]
Definition at line 69 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
final long moa.classifiers.meta.OzaBoostAdwin.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file OzaBoostAdwin.java.
double [] moa.classifiers.meta.OzaBoostAdwin.swms [protected]
Definition at line 71 of file OzaBoostAdwin.java.
Referenced by moa.classifiers.meta.OzaBoostAdwin.getEnsembleMemberWeight(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), and moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/OzaBoostAdwin.java