MOA: moa.classifiers.functions.MajorityClass Class Reference
moa.classifiers.functions.MajorityClass Class Reference
Majority class learner.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance i)
Predicts the class memberships for a given instance.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
DoubleVector observedClassDistribution
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Majority class learner.
This is the simplest classifier.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 34 of file MajorityClass.java.
Member Function Documentation
void moa.classifiers.functions.MajorityClass.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Definition at line 65 of file MajorityClass.java.
References moa.classifiers.AbstractClassifier.getClassLabelString(), moa.classifiers.AbstractClassifier.getClassNameString(), moa.core.DoubleVector.getValue(), moa.core.DoubleVector.maxIndex(), moa.core.DoubleVector.numValues(), and moa.classifiers.functions.MajorityClass.observedClassDistribution.
{
        StringUtils.appendIndented(out, indent, "Predicted majority ");
        out.append(getClassNameString());
        out.append(" = ");
        out.append(getClassLabelString(this.observedClassDistribution.maxIndex()));
        StringUtils.appendNewline(out);
        for (int i = 0; i < this.observedClassDistribution.numValues(); i++) {
            StringUtils.appendIndented(out, indent, "Observed weight of ");
            out.append(getClassLabelString(i));
            out.append(": ");
            out.append(this.observedClassDistribution.getValue(i));
            StringUtils.appendNewline(out);
        }
    }
Measurement [] moa.classifiers.functions.MajorityClass.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Definition at line 60 of file MajorityClass.java.
{
        return null;
    }
String moa.classifiers.functions.MajorityClass.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 39 of file MajorityClass.java.
{
        return "Majority class classifier: always predicts the class that has been observed most frequently the in the training data.";
    }
double [] moa.classifiers.functions.MajorityClass.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 55 of file MajorityClass.java.
References moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.functions.MajorityClass.observedClassDistribution.
{
        return this.observedClassDistribution.getArrayCopy();
    }
boolean moa.classifiers.functions.MajorityClass.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 80 of file MajorityClass.java.
{
        return false;
    }
void moa.classifiers.functions.MajorityClass.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 46 of file MajorityClass.java.
References moa.classifiers.functions.MajorityClass.observedClassDistribution.
{
        this.observedClassDistribution = new DoubleVector();
    }
void moa.classifiers.functions.MajorityClass.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Definition at line 51 of file MajorityClass.java.
References moa.core.DoubleVector.addToValue(), and moa.classifiers.functions.MajorityClass.observedClassDistribution.
{
        this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
    }
Member Data Documentation
DoubleVector moa.classifiers.functions.MajorityClass.observedClassDistribution [protected]
Definition at line 43 of file MajorityClass.java.
Referenced by moa.classifiers.functions.MajorityClass.getModelDescription(), moa.classifiers.functions.MajorityClass.getVotesForInstance(), moa.classifiers.functions.MajorityClass.resetLearningImpl(), and moa.classifiers.functions.MajorityClass.trainOnInstanceImpl().
final long moa.classifiers.functions.MajorityClass.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 36 of file MajorityClass.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/functions/MajorityClass.java