MOA: moa.gui.TaskTextViewerPanel Class Reference
moa.gui.TaskTextViewerPanel Class Reference
This panel displays text.
Public Member Functions
void initVisualEvalPanel ()
TaskTextViewerPanel ()
TaskTextViewerPanel (PreviewPanel.TypePanel typePanel, CDTaskManagerPanel taskManagerPanel)
void setText (String newText)
void setGraph (String preview)
void actionPerformed (ActionEvent e)
Public Attributes
java.awt.GridBagConstraints gridBagConstraints
Static Public Attributes
static String exportFileExtension = "txt"
Protected Member Functions
double round (double d)
MeasureCollection getNewMeasureCollection ()
Protected Attributes
JTextArea textArea
JScrollPane scrollPane
JButton exportButton
CDTaskManagerPanel taskManagerPanel
TypePanel typePanel
MeasureCollection[] acc1 = new MeasureCollection[1]
MeasureCollection[] acc2 = new MeasureCollection[1]
String secondLine = ""
Private Member Functions
double parseDouble (String s)
void scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt)
void buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt)
void buttonRunActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
javax.swing.JPanel topWrapper
javax.swing.JSplitPane jSplitPane1
javax.swing.JButton buttonRun
javax.swing.JButton buttonScreenshot
javax.swing.JButton buttonStop
javax.swing.JButton buttonZoomInX
javax.swing.JButton buttonZoomInY
javax.swing.JButton buttonZoomOutX
javax.swing.JButton buttonZoomOutY
javax.swing.JCheckBox checkboxDrawClustering
javax.swing.JCheckBox checkboxDrawGT
javax.swing.JCheckBox checkboxDrawMicro
javax.swing.JCheckBox checkboxDrawPoints
moa.gui.clustertab.ClusteringVisualEvalPanel clusteringVisualEvalPanel1
javax.swing.JComboBox comboX
javax.swing.JComboBox comboY
moa.gui.visualization.GraphCanvas graphCanvas
javax.swing.JPanel graphPanel
javax.swing.JPanel graphPanelControlBottom
javax.swing.JPanel graphPanelControlTop
javax.swing.JScrollPane graphScrollPanel
javax.swing.JLabel jLabel1
javax.swing.JLabel labelEvents
javax.swing.JLabel labelNumPause
javax.swing.JLabel labelX
javax.swing.JLabel labelY
javax.swing.JLabel label_processed_points
javax.swing.JLabel label_processed_points_value
javax.swing.JTextField numPauseAfterPoints
javax.swing.JPanel panelControl
javax.swing.JPanel panelEvalOutput
javax.swing.JPanel panelVisualWrapper
javax.swing.JScrollPane scrollPane0
javax.swing.JScrollPane scrollPane1
javax.swing.JSlider speedSlider
javax.swing.JSplitPane splitVisual
moa.gui.visualization.StreamPanel streamPanel0
moa.gui.visualization.StreamPanel streamPanel1
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays text.
Used to output the results of tasks.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 57 of file TaskTextViewerPanel.java.
Constructor & Destructor Documentation
moa.gui.TaskTextViewerPanel.TaskTextViewerPanel ()
Definition at line 92 of file TaskTextViewerPanel.java.
{
           this(TypePanel.CLASSIFICATION, null);
        }
moa.gui.TaskTextViewerPanel.TaskTextViewerPanel (PreviewPanel.TypePanel typePanel, CDTaskManagerPanel taskManagerPanel)
Definition at line 98 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.actionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomInX, moa.gui.TaskTextViewerPanel.buttonZoomInXActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomInY, moa.gui.TaskTextViewerPanel.buttonZoomInYActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomOutX, moa.gui.TaskTextViewerPanel.buttonZoomOutXActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomOutY, moa.gui.TaskTextViewerPanel.buttonZoomOutYActionPerformed(), moa.gui.TaskTextViewerPanel.exportButton, moa.gui.TaskTextViewerPanel.exportFileExtension, moa.gui.TaskTextViewerPanel.graphCanvas, moa.gui.TaskTextViewerPanel.graphPanel, moa.gui.TaskTextViewerPanel.graphPanelControlBottom, moa.gui.TaskTextViewerPanel.graphPanelControlTop, moa.gui.TaskTextViewerPanel.graphScrollPanel, moa.gui.TaskTextViewerPanel.gridBagConstraints, moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), moa.gui.TaskTextViewerPanel.jSplitPane1, moa.gui.TaskTextViewerPanel.labelEvents, moa.gui.TaskTextViewerPanel.panelEvalOutput, moa.gui.TaskTextViewerPanel.scrollPane, moa.gui.TaskTextViewerPanel.textArea, moa.gui.TaskTextViewerPanel.topWrapper, and moa.gui.TaskTextViewerPanel.typePanel.
{
        this.typePanel = typePanel;
        this.taskManagerPanel = taskManagerPanel;
        jSplitPane1 = new javax.swing.JSplitPane();
        topWrapper = new javax.swing.JPanel();
        this.textArea = new JTextArea();
        this.textArea.setEditable(false);
        this.textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        this.exportButton = new JButton("Export as .txt file...");
        this.exportButton.setEnabled(false);
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(1, 2));
        buttonPanel.add(this.exportButton);
        topWrapper.setLayout(new BorderLayout());
        this.scrollPane = new JScrollPane(this.textArea);
        topWrapper.add(this.scrollPane, BorderLayout.CENTER);
        topWrapper.add(buttonPanel, BorderLayout.SOUTH);
        this.exportButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setAcceptAllFileFilterUsed(true);
                fileChooser.addChoosableFileFilter(new FileExtensionFilter(
                        exportFileExtension));
                if (fileChooser.showSaveDialog(TaskTextViewerPanel.this) == JFileChooser.APPROVE_OPTION) {
                    File chosenFile = fileChooser.getSelectedFile();
                    String fileName = chosenFile.getPath();
                    if (!chosenFile.exists()
                            && !fileName.endsWith(exportFileExtension)) {
                        fileName = fileName + "." + exportFileExtension;
                    }
                    try {
                        PrintWriter out = new PrintWriter(new BufferedWriter(
                                new FileWriter(fileName)));
                        out.write(TaskTextViewerPanel.this.textArea.getText());
                        out.close();
                    } catch (IOException ioe) {
                        GUIUtils.showExceptionDialog(
                                TaskTextViewerPanel.this.exportButton,
                                "Problem saving file " + fileName, ioe);
                    }
                }
            }
        });
        //topWrapper.add(this.scrollPane);
        //topWrapper.add(buttonPanel);
        panelEvalOutput = new javax.swing.JPanel();
        //clusteringVisualEvalPanel1 = new moa.gui.clustertab.ClusteringVisualEvalPanel();
        graphPanel = new javax.swing.JPanel();
        graphPanelControlTop = new javax.swing.JPanel();
        buttonZoomInY = new javax.swing.JButton();
        buttonZoomOutY = new javax.swing.JButton();
        labelEvents = new javax.swing.JLabel();
        graphScrollPanel = new javax.swing.JScrollPane();
        graphCanvas = new moa.gui.visualization.GraphCanvas();
        // New EventClusters
        //clusterEvents = new  ArrayList<ClusterEvent>();
        //clusterEvents.add(new ClusterEvent(this,100,"Change", "Drift"));
        //graphCanvas.setClusterEventsList(clusterEvents);
        graphPanelControlBottom = new javax.swing.JPanel();
        buttonZoomInX = new javax.swing.JButton();
        buttonZoomOutX = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        //topWrapper.setPreferredSize(new java.awt.Dimension(688, 500));
        //topWrapper.setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setLeftComponent(topWrapper);
        panelEvalOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluation"));
        panelEvalOutput.setLayout(new java.awt.GridBagLayout());
        //clusteringVisualEvalPanel1.setMinimumSize(new java.awt.Dimension(280, 118));
        //clusteringVisualEvalPanel1.setPreferredSize(new java.awt.Dimension(290, 115));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        //panelEvalOutput.add(clusteringVisualEvalPanel1, gridBagConstraints);
        initVisualEvalPanel();
        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plot"));
        graphPanel.setPreferredSize(new java.awt.Dimension(530, 115));
        graphPanel.setLayout(new java.awt.GridBagLayout());
        graphPanelControlTop.setLayout(new java.awt.GridBagLayout());
        buttonZoomInY.setText("Zoom in Y");
        buttonZoomInY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomInY, gridBagConstraints);
        buttonZoomOutY.setText("Zoom out Y");
        buttonZoomOutY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomOutY, gridBagConstraints);
        labelEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(labelEvents, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        graphPanel.add(graphPanelControlTop, gridBagConstraints);
        graphCanvas.setPreferredSize(new java.awt.Dimension(500, 111));
        javax.swing.GroupLayout graphCanvasLayout = new javax.swing.GroupLayout(graphCanvas);
        graphCanvas.setLayout(graphCanvasLayout);
        graphCanvasLayout.setHorizontalGroup(
                graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 515, Short.MAX_VALUE));
        graphCanvasLayout.setVerticalGroup(
                graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 128, Short.MAX_VALUE));
        graphScrollPanel.setViewportView(graphCanvas);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        graphPanel.add(graphScrollPanel, gridBagConstraints);
        buttonZoomInX.setText("Zoom in X");
        buttonZoomInX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomInX);
        buttonZoomOutX.setText("Zoom out X");
        buttonZoomOutX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomOutX);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        graphPanel.add(graphPanelControlBottom, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        panelEvalOutput.add(graphPanel, gridBagConstraints);
        jSplitPane1.setRightComponent(panelEvalOutput);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);
       // acc1[0] = getNewMeasureCollection();
        //acc2[0] = getNewMeasureCollection();
        //clusteringVisualEvalPanel1.setMeasures(acc1, acc2, this);
        //this.graphCanvas.setGraph(acc1[0], acc2[0], 0, 1000);
    }
Member Function Documentation
void moa.gui.TaskTextViewerPanel.actionPerformed (ActionEvent e)
Definition at line 536 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.acc1, moa.gui.TaskTextViewerPanel.acc2, moa.evaluation.MeasureCollection.getNumMeasures(), and moa.gui.TaskTextViewerPanel.graphCanvas.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
{
        //reacte on graph selection and find out which measure was selected
        int selected = Integer.parseInt(e.getActionCommand());
        int counter = selected;
        int m_select = 0;
        int m_select_offset = 0;
        boolean found = false;
        for (int i = 0; i < acc1.length; i++) {
            for (int j = 0; j < acc1[i].getNumMeasures(); j++) {
                if (acc1[i].isEnabled(j)) {
                    counter--;
                    if (counter < 0) {
                        m_select = i;
                        m_select_offset = j;
                        found = true;
                        break;
                    }
                }
            }
            if (found) {
                break;
            }
        }
        this.graphCanvas.setGraph(acc1[m_select], acc2[m_select], m_select_offset, this.graphCanvas.getProcessFrequency());
        this.graphCanvas.forceAddEvents();
    }
void moa.gui.TaskTextViewerPanel.buttonRunActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 458 of file TaskTextViewerPanel.java.
                                                                          {//GEN-FIRST:event_buttonRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRunActionPerformed
void moa.gui.TaskTextViewerPanel.buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 438 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.graphCanvas.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
                                                                              {//GEN-FIRST:event_buttonZoomInXActionPerformed
        graphCanvas.scaleXResolution(false);
    }//GEN-LAST:event_buttonZoomInXActionPerformed
void moa.gui.TaskTextViewerPanel.buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 452 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.graphCanvas.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
                                                                              {//GEN-FIRST:event_buttonZoomInYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int) (graphCanvas.getHeight() * 1.2)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int) (graphCanvas.getHeight() * 1.2)));
        this.graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomInYActionPerformed
void moa.gui.TaskTextViewerPanel.buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 448 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.graphCanvas.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
                                                                               {//GEN-FIRST:event_buttonZoomOutXActionPerformed
        graphCanvas.scaleXResolution(true);
    }//GEN-LAST:event_buttonZoomOutXActionPerformed
void moa.gui.TaskTextViewerPanel.buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 442 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.graphCanvas.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
                                                                               {//GEN-FIRST:event_buttonZoomOutYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int) (graphCanvas.getHeight() * 0.8)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int) (graphCanvas.getHeight() * 0.8)));
        this.graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomOutYActionPerformed
MeasureCollection moa.gui.TaskTextViewerPanel.getNewMeasureCollection () [protected]
Definition at line 318 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.typePanel.
Referenced by moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.setGraph().
{
        /*if (this.taskManagerPanel != null) {
            return new ChangeDetectionMeasures();
        } else {
            return new Accuracy();
        }*/
        return this.typePanel.getMeasureCollection();
    }
void moa.gui.TaskTextViewerPanel.initVisualEvalPanel ()
Definition at line 78 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.acc1, moa.gui.TaskTextViewerPanel.acc2, moa.gui.TaskTextViewerPanel.clusteringVisualEvalPanel1, moa.gui.TaskTextViewerPanel.getNewMeasureCollection(), moa.gui.TaskTextViewerPanel.graphCanvas, moa.gui.TaskTextViewerPanel.gridBagConstraints, and moa.gui.TaskTextViewerPanel.panelEvalOutput.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
{
        acc1[0] = getNewMeasureCollection();
        acc2[0] = getNewMeasureCollection();
        if (clusteringVisualEvalPanel1 != null) {
            panelEvalOutput.remove(clusteringVisualEvalPanel1);
        }
        clusteringVisualEvalPanel1 = new moa.gui.clustertab.ClusteringVisualEvalPanel();
        clusteringVisualEvalPanel1.setMeasures(acc1, acc2, this);
        this.graphCanvas.setGraph(acc1[0], acc2[0], 0, 1000);
        this.graphCanvas.forceAddEvents();
        clusteringVisualEvalPanel1.setMinimumSize(new java.awt.Dimension(280, 118));
        clusteringVisualEvalPanel1.setPreferredSize(new java.awt.Dimension(290, 115));
         panelEvalOutput.add(clusteringVisualEvalPanel1, gridBagConstraints);
    }
double moa.gui.TaskTextViewerPanel.parseDouble (String s) [private]
Definition at line 426 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setGraph().
{
        double ret = 0;
        if (s.equals("?") == false) {
            ret = Double.parseDouble(s);
        }
        return ret;
    }
double moa.gui.TaskTextViewerPanel.round (double d) [protected]
Definition at line 314 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setGraph().
{
        return Math.abs(Math.rint(d * 100) / 100);
    }
void moa.gui.TaskTextViewerPanel.scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt) [private]
Definition at line 434 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.scrollPane0, and moa.gui.TaskTextViewerPanel.streamPanel0.
                                                                                {//GEN-FIRST:event_scrollPane0MouseWheelMoved
        streamPanel0.setZoom(evt.getX(), evt.getY(), (-1) * evt.getWheelRotation(), scrollPane0);
    }//GEN-LAST:event_scrollPane0MouseWheelMoved
void moa.gui.TaskTextViewerPanel.setGraph (String preview)
Definition at line 327 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.acc1, moa.gui.TaskTextViewerPanel.acc2, moa.evaluation.MeasureCollection.addValue(), moa.gui.TaskTextViewerPanel.clusteringVisualEvalPanel1, moa.tasks.ConceptDriftMainTask.getEventsList(), moa.gui.TaskTextViewerPanel.getNewMeasureCollection(), moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedCurrenTask(), moa.evaluation.MeasureCollection.getValue(), moa.gui.TaskTextViewerPanel.graphCanvas, moa.gui.TaskTextViewerPanel.parseDouble(), moa.gui.TaskTextViewerPanel.round(), moa.gui.TaskTextViewerPanel.secondLine, and moa.gui.TaskTextViewerPanel.taskManagerPanel.
Referenced by moa.gui.TaskTextViewerPanel.setText().
{
        //Change the graph when there is change in the text
        double processFrequency = 1000;
        if (preview != null && !preview.equals("")) {
            MeasureCollection oldAccuracy = acc1[0];
            acc1[0] = getNewMeasureCollection();
            Scanner scanner = new Scanner(preview);
            String firstLine = scanner.nextLine();
            boolean isSecondLine = true;
            boolean isPrequential = firstLine.startsWith("learning evaluation instances,evaluation time");
            boolean isHoldOut = firstLine.startsWith("evaluation instances,to");
            int accuracyColumn = 6;
            int kappaColumn = 4;
            int RamColumn = 2;
            int timeColumn = 1;
            int memoryColumn = 9;
            int kappaTempColumn = 5;
            if (this.taskManagerPanel instanceof CDTaskManagerPanel) {
                accuracyColumn = 6;
                kappaColumn = 4;
                RamColumn = 2;
                timeColumn = 1;
                memoryColumn = 9;
            } else if (isPrequential || isHoldOut) {
                accuracyColumn = 4;
                kappaColumn = 5;
                RamColumn = 2;
                timeColumn = 1;
                memoryColumn = 7;
                kappaTempColumn = 5;
                String[] tokensFirstLine = firstLine.split(",");
                int i = 0;
                for (String s : tokensFirstLine) {
                    if (s.equals("classifications correct (percent)")) {
                        accuracyColumn = i;
                    } else if (s.equals("Kappa Statistic (percent)")) {
                        kappaColumn = i;
                    } else if (s.equals("Kappa Temporal Statistic (percent)")) {
                        kappaTempColumn = i;
                    } else if (s.equals("model cost (RAM-Hours)")) {
                        RamColumn = i;
                    } else if (s.equals("evaluation time (cpu seconds)")
                            || s.equals("total train time")) {
                        timeColumn = i;
                    } else if (s.equals("model serialized size (bytes)")) {
                        memoryColumn = i;
                    }
                    i++;
                }
            }
            if (isPrequential || isHoldOut || this.taskManagerPanel instanceof CDTaskManagerPanel) {
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    String[] tokens = line.split(",");
                    this.acc1[0].addValue(0, round(parseDouble(tokens[accuracyColumn])));
                    this.acc1[0].addValue(1, round(parseDouble(tokens[kappaColumn])));
                    this.acc1[0].addValue(2, round(parseDouble(tokens[kappaTempColumn])));
                    if (!isHoldOut) {
                        this.acc1[0].addValue(3, Math.abs(parseDouble(tokens[RamColumn])));
                    }
                    this.acc1[0].addValue(4, round(parseDouble(tokens[timeColumn])));
                    this.acc1[0].addValue(5, round(parseDouble(tokens[memoryColumn]) / (1024 * 1024)));
                    if (isSecondLine == true) {
                        processFrequency = Math.abs(parseDouble(tokens[0]));
                        isSecondLine = false;
                        if (acc1[0].getValue(0, 0) != oldAccuracy.getValue(0, 0)) { //(!line.equals(secondLine)) {
                            //If we are in a new task, compare with the previous
                            secondLine = line;
                            if (processFrequency == this.graphCanvas.getProcessFrequency()) {
                                acc2[0] = oldAccuracy;
                            }
                        }
                    }
                }
            } else {
                this.acc2[0] = getNewMeasureCollection();
            }
        } else {
            this.acc1[0] = getNewMeasureCollection();
            this.acc2[0] = getNewMeasureCollection();
        }
        if (this.taskManagerPanel instanceof CDTaskManagerPanel) {
            ConceptDriftMainTask cdTask = this.taskManagerPanel.getSelectedCurrenTask();
            ArrayList<ClusterEvent> clusterEvents = cdTask.getEventsList();
            this.graphCanvas.setClusterEventsList(clusterEvents);
        }
        this.graphCanvas.setGraph(acc1[0], acc2[0], this.graphCanvas.getMeasureSelected(), (int) processFrequency);
        this.graphCanvas.updateCanvas(true);
        this.graphCanvas.forceAddEvents();
        this.clusteringVisualEvalPanel1.update();
    }
void moa.gui.TaskTextViewerPanel.setText (String newText)
Definition at line 300 of file TaskTextViewerPanel.java.
References moa.gui.TaskTextViewerPanel.exportButton, moa.gui.TaskTextViewerPanel.scrollPane, moa.gui.TaskTextViewerPanel.setGraph(), and moa.gui.TaskTextViewerPanel.textArea.
Referenced by moa.gui.PreviewPanel.setLatestPreview().
{
        Point p = this.scrollPane.getViewport().getViewPosition();
        this.textArea.setText(newText);
        this.scrollPane.getViewport().setViewPosition(p);
        this.exportButton.setEnabled(newText != null);
        setGraph(newText);
    }
Member Data Documentation
MeasureCollection [] moa.gui.TaskTextViewerPanel.acc1 = new MeasureCollection[1] [protected]
Definition at line 308 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.actionPerformed(), moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.setGraph().
MeasureCollection [] moa.gui.TaskTextViewerPanel.acc2 = new MeasureCollection[1] [protected]
Definition at line 310 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.actionPerformed(), moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.setGraph().
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonRun [private]
Definition at line 463 of file TaskTextViewerPanel.java.
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonScreenshot [private]
Definition at line 465 of file TaskTextViewerPanel.java.
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonStop [private]
Definition at line 467 of file TaskTextViewerPanel.java.
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonZoomInX [private]
Definition at line 469 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonZoomInY [private]
Definition at line 471 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonZoomOutX [private]
Definition at line 473 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JButton moa.gui.TaskTextViewerPanel.buttonZoomOutY [private]
Definition at line 475 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JCheckBox moa.gui.TaskTextViewerPanel.checkboxDrawClustering [private]
Definition at line 477 of file TaskTextViewerPanel.java.
javax.swing.JCheckBox moa.gui.TaskTextViewerPanel.checkboxDrawGT [private]
Definition at line 479 of file TaskTextViewerPanel.java.
javax.swing.JCheckBox moa.gui.TaskTextViewerPanel.checkboxDrawMicro [private]
Definition at line 481 of file TaskTextViewerPanel.java.
javax.swing.JCheckBox moa.gui.TaskTextViewerPanel.checkboxDrawPoints [private]
Definition at line 483 of file TaskTextViewerPanel.java.
moa.gui.clustertab.ClusteringVisualEvalPanel moa.gui.TaskTextViewerPanel.clusteringVisualEvalPanel1 [private]
Definition at line 485 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.setGraph().
javax.swing.JComboBox moa.gui.TaskTextViewerPanel.comboX [private]
Definition at line 487 of file TaskTextViewerPanel.java.
javax.swing.JComboBox moa.gui.TaskTextViewerPanel.comboY [private]
Definition at line 489 of file TaskTextViewerPanel.java.
JButton moa.gui.TaskTextViewerPanel.exportButton [protected]
Definition at line 67 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setText(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
String moa.gui.TaskTextViewerPanel.exportFileExtension = "txt" [static]
Definition at line 61 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
moa.gui.visualization.GraphCanvas moa.gui.TaskTextViewerPanel.graphCanvas [private]
Definition at line 491 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.actionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomInXActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomInYActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomOutXActionPerformed(), moa.gui.TaskTextViewerPanel.buttonZoomOutYActionPerformed(), moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), moa.gui.TaskTextViewerPanel.setGraph(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JPanel moa.gui.TaskTextViewerPanel.graphPanel [private]
Definition at line 493 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JPanel moa.gui.TaskTextViewerPanel.graphPanelControlBottom [private]
Definition at line 495 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JPanel moa.gui.TaskTextViewerPanel.graphPanelControlTop [private]
Definition at line 497 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JScrollPane moa.gui.TaskTextViewerPanel.graphScrollPanel [private]
Definition at line 499 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
java.awt.GridBagConstraints moa.gui.TaskTextViewerPanel.gridBagConstraints
Definition at line 96 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JLabel moa.gui.TaskTextViewerPanel.jLabel1 [private]
Definition at line 501 of file TaskTextViewerPanel.java.
javax.swing.JSplitPane moa.gui.TaskTextViewerPanel.jSplitPane1 [private]
Definition at line 71 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JLabel moa.gui.TaskTextViewerPanel.label_processed_points [private]
Definition at line 511 of file TaskTextViewerPanel.java.
javax.swing.JLabel moa.gui.TaskTextViewerPanel.label_processed_points_value [private]
Definition at line 513 of file TaskTextViewerPanel.java.
javax.swing.JLabel moa.gui.TaskTextViewerPanel.labelEvents [private]
Definition at line 503 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JLabel moa.gui.TaskTextViewerPanel.labelNumPause [private]
Definition at line 505 of file TaskTextViewerPanel.java.
javax.swing.JLabel moa.gui.TaskTextViewerPanel.labelX [private]
Definition at line 507 of file TaskTextViewerPanel.java.
javax.swing.JLabel moa.gui.TaskTextViewerPanel.labelY [private]
Definition at line 509 of file TaskTextViewerPanel.java.
javax.swing.JTextField moa.gui.TaskTextViewerPanel.numPauseAfterPoints [private]
Definition at line 515 of file TaskTextViewerPanel.java.
javax.swing.JPanel moa.gui.TaskTextViewerPanel.panelControl [private]
Definition at line 517 of file TaskTextViewerPanel.java.
javax.swing.JPanel moa.gui.TaskTextViewerPanel.panelEvalOutput [private]
Definition at line 519 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.initVisualEvalPanel(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JPanel moa.gui.TaskTextViewerPanel.panelVisualWrapper [private]
Definition at line 521 of file TaskTextViewerPanel.java.
JScrollPane moa.gui.TaskTextViewerPanel.scrollPane [protected]
Definition at line 65 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setText(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JScrollPane moa.gui.TaskTextViewerPanel.scrollPane0 [private]
Definition at line 523 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.scrollPane0MouseWheelMoved().
javax.swing.JScrollPane moa.gui.TaskTextViewerPanel.scrollPane1 [private]
Definition at line 525 of file TaskTextViewerPanel.java.
String moa.gui.TaskTextViewerPanel.secondLine = "" [protected]
Definition at line 312 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setGraph().
final long moa.gui.TaskTextViewerPanel.serialVersionUID = 1L [static, private]
Definition at line 59 of file TaskTextViewerPanel.java.
javax.swing.JSlider moa.gui.TaskTextViewerPanel.speedSlider [private]
Definition at line 527 of file TaskTextViewerPanel.java.
javax.swing.JSplitPane moa.gui.TaskTextViewerPanel.splitVisual [private]
Definition at line 529 of file TaskTextViewerPanel.java.
moa.gui.visualization.StreamPanel moa.gui.TaskTextViewerPanel.streamPanel0 [private]
Definition at line 531 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.scrollPane0MouseWheelMoved().
moa.gui.visualization.StreamPanel moa.gui.TaskTextViewerPanel.streamPanel1 [private]
Definition at line 533 of file TaskTextViewerPanel.java.
CDTaskManagerPanel moa.gui.TaskTextViewerPanel.taskManagerPanel [protected]
Definition at line 74 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setGraph().
JTextArea moa.gui.TaskTextViewerPanel.textArea [protected]
Definition at line 63 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.setText(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
javax.swing.JPanel moa.gui.TaskTextViewerPanel.topWrapper [private]
Definition at line 69 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
TypePanel moa.gui.TaskTextViewerPanel.typePanel [protected]
Definition at line 76 of file TaskTextViewerPanel.java.
Referenced by moa.gui.TaskTextViewerPanel.getNewMeasureCollection(), and moa.gui.TaskTextViewerPanel.TaskTextViewerPanel().
The documentation for this class was generated from the following file:
main/java/moa/gui/TaskTextViewerPanel.java