MOA: moa.gui.conceptdrift.CDTaskManagerPanel Class Reference
moa.gui.conceptdrift.CDTaskManagerPanel Class Reference
This panel displays the running tasks.
Classes
class ProgressCellRenderer
class TaskTableModel
Public Member Functions
CDTaskManagerPanel ()
void setPreviewPanel (PreviewPanel previewPanel)
void setTaskString (String cliString)
void setTaskString (String cliString, boolean storePreference)
void runTask (Task task)
void taskSelectionChanged ()
TaskThread[] getSelectedTasks ()
void pauseSelectedTasks ()
void resumeSelectedTasks ()
void cancelSelectedTasks ()
void deleteSelectedTasks ()
void copyClipBoardConfiguration ()
void saveLogSelectedTasks ()
ConceptDriftMainTask getCurrenTask ()
ConceptDriftMainTask getSelectedCurrenTask ()
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final int MILLISECS_BETWEEN_REFRESH = 600
static String exportFileExtension = "log"
Protected Attributes
ConceptDriftMainTask currentTask = new EvaluateConceptDrift()
List< TaskThread > taskList = new ArrayList<TaskThread>()
JButton configureTaskButton = new JButton("Configure")
JTextField taskDescField = new JTextField()
JButton runTaskButton = new JButton("Run")
TaskTableModel taskTableModel
JTable taskTable
JButton pauseTaskButton = new JButton("Pause")
JButton resumeTaskButton = new JButton("Resume")
JButton cancelTaskButton = new JButton("Cancel")
JButton deleteTaskButton = new JButton("Delete")
PreviewPanel previewPanel
Static Private Member Functions
static void createAndShowGUI ()
Private Attributes
Preferences prefs
final String PREF_NAME = "currentTask"
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This panel displays the running tasks.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 77 of file CDTaskManagerPanel.java.
Constructor & Destructor Documentation
moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel ()
Definition at line 218 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.cancelSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.cancelTaskButton, moa.gui.conceptdrift.CDTaskManagerPanel.configureTaskButton, moa.gui.conceptdrift.CDTaskManagerPanel.copyClipBoardConfiguration(), moa.gui.conceptdrift.CDTaskManagerPanel.currentTask, moa.gui.conceptdrift.CDTaskManagerPanel.deleteSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.deleteTaskButton, moa.options.AbstractOptionHandler.getCLICreationString(), moa.gui.conceptdrift.CDTaskManagerPanel.MILLISECS_BETWEEN_REFRESH, moa.gui.conceptdrift.CDTaskManagerPanel.pauseSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.pauseTaskButton, moa.gui.conceptdrift.CDTaskManagerPanel.PREF_NAME, moa.gui.conceptdrift.CDTaskManagerPanel.prefs, moa.gui.conceptdrift.CDTaskManagerPanel.resumeSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.resumeTaskButton, moa.gui.conceptdrift.CDTaskManagerPanel.runTask(), moa.gui.conceptdrift.CDTaskManagerPanel.runTaskButton, moa.gui.conceptdrift.CDTaskManagerPanel.saveLogSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString(), moa.gui.conceptdrift.CDTaskManagerPanel.taskDescField, moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged(), moa.gui.conceptdrift.CDTaskManagerPanel.taskTable, and moa.gui.conceptdrift.CDTaskManagerPanel.taskTableModel.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.createAndShowGUI().
{
        // Read current task preference
        prefs = Preferences.userRoot().node(this.getClass().getName());
        currentTask = new EvaluateConceptDrift();
        String taskText = this.currentTask.getCLICreationString(ConceptDriftMainTask.class);
        String propertyValue = prefs.get(PREF_NAME, taskText);
        //this.taskDescField.setText(propertyValue);
        setTaskString(propertyValue, false); //Not store preference
        this.taskDescField.setEditable(false);
        final Component comp = this.taskDescField;
        this.taskDescField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    if ((evt.getButton() == MouseEvent.BUTTON3)
                            || ((evt.getButton() == MouseEvent.BUTTON1) && evt.isAltDown() && evt.isShiftDown())) {
                        JPopupMenu menu = new JPopupMenu();
                        JMenuItem item;
                        item = new JMenuItem("Copy configuration to clipboard");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                copyClipBoardConfiguration();
                            }
                        });
                        menu.add(item);
                        item = new JMenuItem("Save selected tasks to file");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent arg0) {
                                saveLogSelectedTasks();
                            }
                        });
                        menu.add(item);
                        item = new JMenuItem("Enter configuration...");
                        item.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent arg0) {
                                String newTaskString = JOptionPane.showInputDialog("Insert command line");
                                if (newTaskString != null) {
                                    setTaskString(newTaskString);
                                }
                            }
                        });
                        menu.add(item);
                        menu.show(comp, evt.getX(), evt.getY());
                    }
                }
            }
        });
        JPanel configPanel = new JPanel();
        configPanel.setLayout(new BorderLayout());
        configPanel.add(this.configureTaskButton, BorderLayout.WEST);
        configPanel.add(this.taskDescField, BorderLayout.CENTER);
        configPanel.add(this.runTaskButton, BorderLayout.EAST);
        this.taskTableModel = new TaskTableModel();
        this.taskTable = new JTable(this.taskTableModel);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        this.taskTable.getColumnModel().getColumn(1).setCellRenderer(
                centerRenderer);
        this.taskTable.getColumnModel().getColumn(2).setCellRenderer(
                centerRenderer);
        this.taskTable.getColumnModel().getColumn(4).setCellRenderer(
                new ProgressCellRenderer());
        JPanel controlPanel = new JPanel();
        controlPanel.add(this.pauseTaskButton);
        controlPanel.add(this.resumeTaskButton);
        controlPanel.add(this.cancelTaskButton);
        controlPanel.add(this.deleteTaskButton);
        setLayout(new BorderLayout());
        add(configPanel, BorderLayout.NORTH);
        add(new JScrollPane(this.taskTable), BorderLayout.CENTER);
        add(controlPanel, BorderLayout.SOUTH);
        this.taskTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
                    @Override
                    public void valueChanged(ListSelectionEvent arg0) {
                        taskSelectionChanged();
                    }
                });
        this.configureTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                String newTaskString = ClassOptionSelectionPanel.showSelectClassDialog(CDTaskManagerPanel.this,
                        "Configure task", ConceptDriftMainTask.class,
                        CDTaskManagerPanel.this.currentTask.getCLICreationString(ConceptDriftMainTask.class),
                        null);
                setTaskString(newTaskString);
            }
        });
        this.runTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                runTask((Task) CDTaskManagerPanel.this.currentTask.copy());
            }
        });
        this.pauseTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                pauseSelectedTasks();
            }
        });
        this.resumeTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                resumeSelectedTasks();
            }
        });
        this.cancelTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                cancelSelectedTasks();
            }
        });
        this.deleteTaskButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                deleteSelectedTasks();
            }
        });
        javax.swing.Timer updateListTimer = new javax.swing.Timer(
                MILLISECS_BETWEEN_REFRESH, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CDTaskManagerPanel.this.taskTable.repaint();
            }
        });
        updateListTimer.start();
        setPreferredSize(new Dimension(0, 200));
    }
Member Function Documentation
void moa.gui.conceptdrift.CDTaskManagerPanel.cancelSelectedTasks ()
Definition at line 438 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.cancelTask();
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.copyClipBoardConfiguration ()
Definition at line 454 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.taskDescField.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        StringSelection selection = new StringSelection(this.taskDescField.getText().trim());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }
static void moa.gui.conceptdrift.CDTaskManagerPanel.createAndShowGUI () [static, private]
Definition at line 493 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.main().
{
        // Create and set up the window.
        JFrame frame = new JFrame("Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create and set up the content pane.
        JPanel panel = new CDTaskManagerPanel();
        panel.setOpaque(true); // content panes must be opaque
        frame.setContentPane(panel);
        // Display the window.
        frame.pack();
        // frame.setSize(400, 400);
        frame.setVisible(true);
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.deleteSelectedTasks ()
Definition at line 445 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.taskList, and moa.gui.conceptdrift.CDTaskManagerPanel.taskTableModel.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.cancelTask();
            this.taskList.remove(thread);
        }
        this.taskTableModel.fireTableDataChanged();
    }
ConceptDriftMainTask moa.gui.conceptdrift.CDTaskManagerPanel.getCurrenTask ()
Definition at line 526 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.currentTask.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedCurrenTask().
{
        return  (ConceptDriftMainTask) this.currentTask; //this.getSelectedTasks()[0].getTask();//this.currentTask;
    }
ConceptDriftMainTask moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedCurrenTask ()
Definition at line 531 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getCurrenTask(), moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks(), and moa.tasks.TaskThread.getTask().
Referenced by moa.gui.TaskTextViewerPanel.setGraph().
{
        if (this.getSelectedTasks().length > 0) {
            return  (ConceptDriftMainTask) this.getSelectedTasks()[0].getTask();//this.currentTask;
        }
        else {
            return getCurrenTask();
        }
    }
TaskThread [] moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks ()
Definition at line 415 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.taskList, and moa.gui.conceptdrift.CDTaskManagerPanel.taskTable.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.cancelSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.deleteSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedCurrenTask(), moa.gui.conceptdrift.CDTaskManagerPanel.pauseSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.resumeSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.saveLogSelectedTasks(), and moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged().
{
        int[] selectedRows = this.taskTable.getSelectedRows();
        TaskThread[] selectedTasks = new TaskThread[selectedRows.length];
        for (int i = 0; i < selectedRows.length; i++) {
            selectedTasks[i] = this.taskList.get(selectedRows[i]);
        }
        return selectedTasks;
    }
static void moa.gui.conceptdrift.CDTaskManagerPanel.main (String[] args) [static]
Definition at line 510 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.createAndShowGUI().
{
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    createAndShowGUI();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.pauseSelectedTasks ()
Definition at line 424 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.pauseTask();
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.resumeSelectedTasks ()
Definition at line 431 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            thread.resumeTask();
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.runTask (Task task)
Definition at line 395 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.taskList, moa.gui.conceptdrift.CDTaskManagerPanel.taskTable, and moa.gui.conceptdrift.CDTaskManagerPanel.taskTableModel.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread thread = new TaskThread(task);
        this.taskList.add(0, thread);
        this.taskTableModel.fireTableDataChanged();
        this.taskTable.setRowSelectionInterval(0, 0);
        thread.start();
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.saveLogSelectedTasks ()
Definition at line 462 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.exportFileExtension, and moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        String tasksLog = "";
        TaskThread[] selectedTasks = getSelectedTasks();
        for (TaskThread thread : selectedTasks) {
            tasksLog += ((OptionHandler) thread.getTask()).getCLICreationString(ConceptDriftMainTask.class) + "\n";
        }
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        fileChooser.addChoosableFileFilter(new FileExtensionFilter(
                exportFileExtension));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File chosenFile = fileChooser.getSelectedFile();
            String fileName = chosenFile.getPath();
            if (!chosenFile.exists()
                    && !fileName.endsWith(exportFileExtension)) {
                fileName = fileName + "." + exportFileExtension;
            }
            try {
                PrintWriter out = new PrintWriter(new BufferedWriter(
                        new FileWriter(fileName)));
                out.write(tasksLog);
                out.close();
            } catch (IOException ioe) {
                GUIUtils.showExceptionDialog(
                        this,
                        "Problem saving file " + fileName, ioe);
            }
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.setPreviewPanel (PreviewPanel previewPanel)
Definition at line 372 of file CDTaskManagerPanel.java.
Referenced by moa.gui.ConceptDriftTabPanel.ConceptDriftTabPanel().
{
        this.previewPanel = previewPanel;
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString (String cliString, boolean storePreference)
Definition at line 380 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.currentTask, moa.options.AbstractOptionHandler.getCLICreationString(), moa.gui.conceptdrift.CDTaskManagerPanel.PREF_NAME, moa.gui.conceptdrift.CDTaskManagerPanel.prefs, and moa.gui.conceptdrift.CDTaskManagerPanel.taskDescField.
{
        try {
            this.currentTask = (ConceptDriftMainTask) ClassOption.cliStringToObject(
                    cliString, ConceptDriftMainTask.class, null);
            String taskText = this.currentTask.getCLICreationString(ConceptDriftMainTask.class);
            this.taskDescField.setText(taskText);
            if (storePreference == true){
            //Save task text as a preference
            prefs.put(PREF_NAME, taskText);
            }
        } catch (Exception ex) {
            GUIUtils.showExceptionDialog(this, "Problem with task", ex);
        }
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString (String cliString)
Definition at line 376 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), and moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged().
{
        setTaskString(cliString, true);
    }
void moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged ()
Definition at line 403 of file CDTaskManagerPanel.java.
References moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.previewPanel, moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
{
        TaskThread[] selectedTasks = getSelectedTasks();
        if (selectedTasks.length == 1) {
            setTaskString(((OptionHandler) selectedTasks[0].getTask()).getCLICreationString(ConceptDriftMainTask.class));
            if (this.previewPanel != null) {
                this.previewPanel.setTaskThreadToPreview(selectedTasks[0]);
            }
        } else {
            this.previewPanel.setTaskThreadToPreview(null);
        }
    }
Member Data Documentation
JButton moa.gui.conceptdrift.CDTaskManagerPanel.cancelTaskButton = new JButton("Cancel") [protected]
Definition at line 208 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
JButton moa.gui.conceptdrift.CDTaskManagerPanel.configureTaskButton = new JButton("Configure") [protected]
Definition at line 194 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
ConceptDriftMainTask moa.gui.conceptdrift.CDTaskManagerPanel.currentTask = new EvaluateConceptDrift() [protected]
Definition at line 190 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), moa.gui.conceptdrift.CDTaskManagerPanel.getCurrenTask(), and moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString().
JButton moa.gui.conceptdrift.CDTaskManagerPanel.deleteTaskButton = new JButton("Delete") [protected]
Definition at line 210 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
String moa.gui.conceptdrift.CDTaskManagerPanel.exportFileExtension = "log" [static]
Definition at line 83 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.saveLogSelectedTasks().
final int moa.gui.conceptdrift.CDTaskManagerPanel.MILLISECS_BETWEEN_REFRESH = 600 [static]
Definition at line 81 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
JButton moa.gui.conceptdrift.CDTaskManagerPanel.pauseTaskButton = new JButton("Pause") [protected]
Definition at line 204 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
final String moa.gui.conceptdrift.CDTaskManagerPanel.PREF_NAME = "currentTask" [private]
Definition at line 216 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), and moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString().
Preferences moa.gui.conceptdrift.CDTaskManagerPanel.prefs [private]
Definition at line 214 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), and moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString().
PreviewPanel moa.gui.conceptdrift.CDTaskManagerPanel.previewPanel [protected]
Definition at line 212 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.taskSelectionChanged().
JButton moa.gui.conceptdrift.CDTaskManagerPanel.resumeTaskButton = new JButton("Resume") [protected]
Definition at line 206 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
JButton moa.gui.conceptdrift.CDTaskManagerPanel.runTaskButton = new JButton("Run") [protected]
Definition at line 198 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel().
final long moa.gui.conceptdrift.CDTaskManagerPanel.serialVersionUID = 1L [static, private]
Definition at line 79 of file CDTaskManagerPanel.java.
JTextField moa.gui.conceptdrift.CDTaskManagerPanel.taskDescField = new JTextField() [protected]
Definition at line 196 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), moa.gui.conceptdrift.CDTaskManagerPanel.copyClipBoardConfiguration(), and moa.gui.conceptdrift.CDTaskManagerPanel.setTaskString().
List<TaskThread> moa.gui.conceptdrift.CDTaskManagerPanel.taskList = new ArrayList<TaskThread>() [protected]
Definition at line 192 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.deleteSelectedTasks(), moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks(), and moa.gui.conceptdrift.CDTaskManagerPanel.runTask().
JTable moa.gui.conceptdrift.CDTaskManagerPanel.taskTable [protected]
Definition at line 202 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedTasks(), and moa.gui.conceptdrift.CDTaskManagerPanel.runTask().
TaskTableModel moa.gui.conceptdrift.CDTaskManagerPanel.taskTableModel [protected]
Definition at line 200 of file CDTaskManagerPanel.java.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.CDTaskManagerPanel(), moa.gui.conceptdrift.CDTaskManagerPanel.deleteSelectedTasks(), and moa.gui.conceptdrift.CDTaskManagerPanel.runTask().
The documentation for this class was generated from the following file:
main/java/moa/gui/conceptdrift/CDTaskManagerPanel.java