MOA: moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel Class Reference
moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel Class Reference
Public Member Functions
String getColumnName (int col)
int getColumnCount ()
int getRowCount ()
Object getValueAt (int row, int col)
boolean isCellEditable (int row, int col)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 135 of file CDTaskManagerPanel.java.
Member Function Documentation
int moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getColumnCount ()
Definition at line 157 of file CDTaskManagerPanel.java.
{
            return 5;
        }
String moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getColumnName (int col)
Definition at line 140 of file CDTaskManagerPanel.java.
{
            switch (col) {
                case 0:
                    return "command";
                case 1:
                    return "status";
                case 2:
                    return "time elapsed";
                case 3:
                    return "current activity";
                case 4:
                    return "% complete";
            }
            return null;
        }
int moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getRowCount ()
Definition at line 162 of file CDTaskManagerPanel.java.
{
            return CDTaskManagerPanel.this.taskList.size();
        }
Object moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt (int row, int col)
Definition at line 167 of file CDTaskManagerPanel.java.
References moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.getCurrentActivityFracComplete(), moa.tasks.TaskThread.getCurrentActivityString(), moa.tasks.TaskThread.getCurrentStatusString(), and moa.tasks.TaskThread.getTask().
{
            TaskThread thread = CDTaskManagerPanel.this.taskList.get(row);
            switch (col) {
                case 0:
                    return ((OptionHandler) thread.getTask()).getCLICreationString(ConceptDriftMainTask.class);
                case 1:
                    return thread.getCurrentStatusString();
                case 2:
                    return StringUtils.secondsToDHMSString(thread.getCPUSecondsElapsed());
                case 3:
                    return thread.getCurrentActivityString();
                case 4:
                    return new Double(thread.getCurrentActivityFracComplete());
            }
            return null;
        }
boolean moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.isCellEditable (int row, int col)
Definition at line 185 of file CDTaskManagerPanel.java.
{
            return false;
        }
Member Data Documentation
final long moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.serialVersionUID = 1L [static, private]
Definition at line 137 of file CDTaskManagerPanel.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/conceptdrift/CDTaskManagerPanel.java