MOA: moa.gui.outliertab.OutlierVisualTab Class Reference
moa.gui.outliertab.OutlierVisualTab Class Reference
Public Member Functions
OutlierVisualTab ()
Creates new form OutlierVisualTab.
void setOutlierSetupTab (OutlierSetupTab outlierSetupTab)
void setDimensionComobBoxes (int numDimensions)
StreamOutlierPanel getLeftStreamPanel ()
StreamOutlierPanel getRightStreamPanel ()
GraphCanvas getGraphCanvas ()
OutlierVisualEvalPanel getEvalPanel ()
boolean isEnabledDrawPoints ()
boolean isEnabledDrawOutliers ()
void setProcessedPointsCounter (int value)
int getPauseInterval ()
void setPauseInterval (int pause)
void repaint ()
void componentResized (ComponentEvent ce)
void componentMoved (ComponentEvent ce)
void componentShown (ComponentEvent ce)
void componentHidden (ComponentEvent ce)
void toggleVisualizer (boolean internal)
void stopVisualizer ()
int GetSpeed ()
boolean getPointVisibility ()
boolean getOutliersVisibility ()
boolean getWaitWinFull ()
void actionPerformed (ActionEvent e)
Private Member Functions
void resetComponents ()
void createVisualiterThread ()
void UpdateSplitVisualDivider ()
void initComponents ()
This method is called from within the constructor to initialize the form.
void buttonRedrawMouseClicked (java.awt.event.MouseEvent evt)
void buttonScreenshotMouseClicked (java.awt.event.MouseEvent evt)
void buttonRunMouseClicked (java.awt.event.MouseEvent evt)
void speedSliderMouseDragged (java.awt.event.MouseEvent evt)
void scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt)
void buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt)
void buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawPointsActionPerformed (java.awt.event.ActionEvent evt)
void checkboxDrawOutlierActionPerformed (java.awt.event.ActionEvent evt)
void checkboxWaitWinFullActionPerformed (java.awt.event.ActionEvent evt)
void comboXActionPerformed (java.awt.event.ActionEvent evt)
void comboYActionPerformed (java.awt.event.ActionEvent evt)
void buttonStopActionPerformed (java.awt.event.ActionEvent evt)
void buttonRunActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
RunOutlierVisualizer visualizer = null
Thread visualizerThread = null
Boolean running = false
OutlierSetupTab outlierSetupTab = null
String exportFile
String screenshotFilebase
javax.swing.JButton buttonRun
javax.swing.JButton buttonScreenshot
javax.swing.JButton buttonRedraw
javax.swing.JButton buttonStop
javax.swing.JButton buttonZoomInX
javax.swing.JButton buttonZoomInY
javax.swing.JButton buttonZoomOutX
javax.swing.JButton buttonZoomOutY
javax.swing.JCheckBox checkboxDrawOutliers
javax.swing.JCheckBox checkboxDrawPoints
javax.swing.JCheckBox checkboxWaitWinFull
javax.swing.JComboBox comboX
javax.swing.JComboBox comboY
moa.gui.visualization.GraphCanvas graphCanvas
javax.swing.JPanel graphPanel
javax.swing.JPanel graphPanelControlBottom
javax.swing.JPanel graphPanelControlTop
javax.swing.JScrollPane graphScrollPanel
javax.swing.JLabel jLabel1
javax.swing.JSplitPane jSplitPane1
javax.swing.JLabel labelEvents
javax.swing.JLabel labelNumPause
javax.swing.JLabel labelX
javax.swing.JLabel labelY
javax.swing.JLabel label_processed_points
javax.swing.JLabel label_processed_points_value
javax.swing.JTextField numPauseAfterPoints
javax.swing.JPanel panelControl
javax.swing.JPanel panelEvalOutput
javax.swing.JPanel panelVisualWrapper
javax.swing.JScrollPane scrollPane0
javax.swing.JScrollPane scrollPane1
javax.swing.JSlider speedSlider
javax.swing.JSplitPane splitVisual
moa.gui.visualization.StreamOutlierPanel streamPanel0
moa.gui.visualization.StreamOutlierPanel streamPanel1
javax.swing.JPanel topWrapper
Detailed Description
Definition at line 37 of file OutlierVisualTab.java.
Constructor & Destructor Documentation
moa.gui.outliertab.OutlierVisualTab.OutlierVisualTab ()
Creates new form OutlierVisualTab.
Definition at line 46 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.resetComponents().
Referenced by moa.gui.outliertab.OutlierTabPanel.initComponents().
{
        resetComponents();
    }
Member Function Documentation
void moa.gui.outliertab.OutlierVisualTab.actionPerformed (ActionEvent e)
Definition at line 849 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
        if (visualizer == null) return;
        if(e.getSource() instanceof JButton){
            if(e.getActionCommand().equals("csv export")){
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setAcceptAllFileFilterUsed(true);
                fileChooser.addChoosableFileFilter(new FileExtensionFilter("csv"));
                if(exportFile!=null)
                    fileChooser.setSelectedFile(new File(exportFile));
                if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    exportFile = fileChooser.getSelectedFile().getPath();
                    visualizer.exportCSV(exportFile);
                }
            }
            if(e.getActionCommand().equals("weka export")){
                visualizer.weka();
            }
        }
    }
void moa.gui.outliertab.OutlierVisualTab.buttonRedrawMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 686 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                         {//GEN-FIRST:event_buttonRedrawMouseClicked
        if (visualizer != null)
            visualizer.redraw();
    }//GEN-LAST:event_buttonScreenshotMouseClicked
void moa.gui.outliertab.OutlierVisualTab.buttonRunActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 802 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                          {//GEN-FIRST:event_buttonRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRunActionPerformed
void moa.gui.outliertab.OutlierVisualTab.buttonRunMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 702 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                      {//GEN-FIRST:event_buttonRunMouseClicked
        toggleVisualizer(true);
    }//GEN-LAST:event_buttonRunMouseClicked
void moa.gui.outliertab.OutlierVisualTab.buttonScreenshotMouseClicked (java.awt.event.MouseEvent evt) [private]
Definition at line 691 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                             {//GEN-FIRST:event_buttonScreenshotMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(true);
        if(screenshotFilebase!=null)
            fileChooser.setSelectedFile(new File(screenshotFilebase));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            screenshotFilebase = fileChooser.getSelectedFile().getPath();
            streamPanel0.screenshot(screenshotFilebase+"_"+label_processed_points_value.getText()+"_0", true, true);
        }
    }//GEN-LAST:event_buttonScreenshotMouseClicked
void moa.gui.outliertab.OutlierVisualTab.buttonStopActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 797 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                           {//GEN-FIRST:event_buttonStopActionPerformed
        stopVisualizer();
        outlierSetupTab.stopRun();
    }//GEN-LAST:event_buttonStopActionPerformed
void moa.gui.outliertab.OutlierVisualTab.buttonZoomInXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 722 of file OutlierVisualTab.java.
                                                                              {//GEN-FIRST:event_buttonZoomInXActionPerformed
        graphCanvas.scaleXResolution(false);
        graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomInXActionPerformed
void moa.gui.outliertab.OutlierVisualTab.buttonZoomInYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 738 of file OutlierVisualTab.java.
                                                                              {//GEN-FIRST:event_buttonZoomInYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*1.2)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*1.2)));
        graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomInYActionPerformed
void moa.gui.outliertab.OutlierVisualTab.buttonZoomOutXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 733 of file OutlierVisualTab.java.
                                                                               {//GEN-FIRST:event_buttonZoomOutXActionPerformed
        graphCanvas.scaleXResolution(true);
        graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomOutXActionPerformed
void moa.gui.outliertab.OutlierVisualTab.buttonZoomOutYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 727 of file OutlierVisualTab.java.
                                                                               {//GEN-FIRST:event_buttonZoomOutYActionPerformed
        graphCanvas.setSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*0.8)));
        graphCanvas.setPreferredSize(new Dimension(graphCanvas.getWidth(), (int)(graphCanvas.getHeight()*0.8)));
        graphCanvas.updateCanvas(true);
    }//GEN-LAST:event_buttonZoomOutYActionPerformed
void moa.gui.outliertab.OutlierVisualTab.checkboxDrawOutlierActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 757 of file OutlierVisualTab.java.
                                                                                    {//GEN-FIRST:event_checkboxDrawOutlierActionPerformed
        if (visualizer == null) return;
        if (running) {
            // outliers layer is hidden when running
            return;
        }
        // visualizer.redrawOutliers();
        visualizer.setOutliersVisibility(checkboxDrawOutliers.isSelected());
    }//GEN-LAST:event_checkboxDrawOutlierActionPerformed
void moa.gui.outliertab.OutlierVisualTab.checkboxDrawPointsActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 752 of file OutlierVisualTab.java.
                                                                                   {//GEN-FIRST:event_checkboxDrawPointsActionPerformed
        if (visualizer == null) return;
        visualizer.setPointsVisibility(checkboxDrawPoints.isSelected());
    }//GEN-LAST:event_checkboxDrawPointsActionPerformed
void moa.gui.outliertab.OutlierVisualTab.checkboxWaitWinFullActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 772 of file OutlierVisualTab.java.
                                                                                    {//GEN-FIRST:event_checkboxWaitWinFullActionPerformed
        if (visualizer == null) return;
        visualizer.setWaitWinFull(checkboxWaitWinFull.isSelected());
    }//GEN-LAST:checkboxWaitWinFullActionPerformed
void moa.gui.outliertab.OutlierVisualTab.comboXActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 777 of file OutlierVisualTab.java.
                                                                       {//GEN-FIRST:event_comboXActionPerformed
        if (visualizer == null) return;
        JComboBox cb = (JComboBox)evt.getSource();
        int dim = cb.getSelectedIndex();
        streamPanel0.setActiveXDim(dim);
        streamPanel1.setActiveXDim(dim);
        if(visualizer!=null)
            visualizer.redraw();
    }//GEN-LAST:event_comboXActionPerformed
void moa.gui.outliertab.OutlierVisualTab.comboYActionPerformed (java.awt.event.ActionEvent evt) [private]
Definition at line 787 of file OutlierVisualTab.java.
                                                                       {//GEN-FIRST:event_comboYActionPerformed
        if (visualizer == null) return;
        JComboBox cb = (JComboBox)evt.getSource();
        int dim = cb.getSelectedIndex();
        streamPanel0.setActiveYDim(dim);
        streamPanel1.setActiveYDim(dim);
        if(visualizer!=null)
            visualizer.redraw();
    }//GEN-LAST:event_comboYActionPerformed
void moa.gui.outliertab.OutlierVisualTab.componentHidden (ComponentEvent ce)
Definition at line 141 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
    }
void moa.gui.outliertab.OutlierVisualTab.componentMoved (ComponentEvent ce)
Definition at line 133 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
    }
void moa.gui.outliertab.OutlierVisualTab.componentResized (ComponentEvent ce)
Definition at line 129 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
    }
void moa.gui.outliertab.OutlierVisualTab.componentShown (ComponentEvent ce)
Definition at line 137 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
{
    }
void moa.gui.outliertab.OutlierVisualTab.createVisualiterThread () [private]
Definition at line 65 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.outlierSetupTab, moa.gui.outliertab.OutlierVisualTab.visualizer, and moa.gui.outliertab.OutlierVisualTab.visualizerThread.
Referenced by moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
{
        visualizer = new RunOutlierVisualizer(this, outlierSetupTab);
        visualizerThread = new Thread(visualizer);
    }
OutlierVisualEvalPanel moa.gui.outliertab.OutlierVisualTab.getEvalPanel ()
Definition at line 93 of file OutlierVisualTab.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return null;
    }
GraphCanvas moa.gui.outliertab.OutlierVisualTab.getGraphCanvas ()
Definition at line 89 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.graphCanvas.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return graphCanvas;
    }
StreamOutlierPanel moa.gui.outliertab.OutlierVisualTab.getLeftStreamPanel ()
Definition at line 81 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.streamPanel0.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return streamPanel0;
    }
boolean moa.gui.outliertab.OutlierVisualTab.getOutliersVisibility ()
Definition at line 748 of file OutlierVisualTab.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        return checkboxDrawOutliers.isSelected();
    }
int moa.gui.outliertab.OutlierVisualTab.getPauseInterval ()
Definition at line 109 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.numPauseAfterPoints.
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        return Integer.parseInt(numPauseAfterPoints.getText());
    }
boolean moa.gui.outliertab.OutlierVisualTab.getPointVisibility ()
Definition at line 744 of file OutlierVisualTab.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        return checkboxDrawPoints.isSelected();
    }
StreamOutlierPanel moa.gui.outliertab.OutlierVisualTab.getRightStreamPanel ()
Definition at line 85 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.streamPanel1.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        return streamPanel1;
    }
int moa.gui.outliertab.OutlierVisualTab.GetSpeed ()
Definition at line 714 of file OutlierVisualTab.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        return speedSlider.getValue();
    }
boolean moa.gui.outliertab.OutlierVisualTab.getWaitWinFull ()
Definition at line 768 of file OutlierVisualTab.java.
Referenced by moa.gui.visualization.RunOutlierVisualizer.updateSettings().
{
        return checkboxWaitWinFull.isSelected();
    }
void moa.gui.outliertab.OutlierVisualTab.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 186 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.actionPerformed(), moa.gui.outliertab.OutlierVisualTab.buttonRedraw, moa.gui.outliertab.OutlierVisualTab.buttonRedrawMouseClicked(), moa.gui.outliertab.OutlierVisualTab.buttonRun, moa.gui.outliertab.OutlierVisualTab.buttonRunActionPerformed(), moa.gui.outliertab.OutlierVisualTab.buttonRunMouseClicked(), moa.gui.outliertab.OutlierVisualTab.buttonScreenshot, moa.gui.outliertab.OutlierVisualTab.buttonScreenshotMouseClicked(), moa.gui.outliertab.OutlierVisualTab.buttonStop, moa.gui.outliertab.OutlierVisualTab.buttonStopActionPerformed(), moa.gui.outliertab.OutlierVisualTab.buttonZoomInX, moa.gui.outliertab.OutlierVisualTab.buttonZoomInY, moa.gui.outliertab.OutlierVisualTab.buttonZoomOutX, moa.gui.outliertab.OutlierVisualTab.buttonZoomOutY, moa.gui.outliertab.OutlierVisualTab.checkboxDrawOutliers, moa.gui.outliertab.OutlierVisualTab.checkboxDrawPoints, moa.gui.outliertab.OutlierVisualTab.checkboxWaitWinFull, moa.gui.outliertab.OutlierVisualTab.comboX, moa.gui.outliertab.OutlierVisualTab.comboY, moa.gui.outliertab.OutlierVisualTab.componentHidden(), moa.gui.outliertab.OutlierVisualTab.componentMoved(), moa.gui.outliertab.OutlierVisualTab.componentResized(), moa.gui.outliertab.OutlierVisualTab.componentShown(), moa.gui.visualization.GraphCanvas.GraphCanvas(), moa.gui.outliertab.OutlierVisualTab.graphCanvas, moa.gui.outliertab.OutlierVisualTab.graphPanel, moa.gui.outliertab.OutlierVisualTab.graphPanelControlBottom, moa.gui.outliertab.OutlierVisualTab.graphPanelControlTop, moa.gui.outliertab.OutlierVisualTab.graphScrollPanel, moa.gui.outliertab.OutlierVisualTab.jLabel1, moa.gui.outliertab.OutlierVisualTab.jSplitPane1, moa.gui.outliertab.OutlierVisualTab.label_processed_points, moa.gui.outliertab.OutlierVisualTab.label_processed_points_value, moa.gui.outliertab.OutlierVisualTab.labelEvents, moa.gui.outliertab.OutlierVisualTab.labelNumPause, moa.gui.outliertab.OutlierVisualTab.labelX, moa.gui.outliertab.OutlierVisualTab.labelY, moa.gui.outliertab.OutlierVisualTab.numPauseAfterPoints, moa.gui.outliertab.OutlierVisualTab.panelControl, moa.gui.outliertab.OutlierVisualTab.panelEvalOutput, moa.gui.outliertab.OutlierVisualTab.panelVisualWrapper, moa.gui.outliertab.OutlierVisualTab.scrollPane0, moa.gui.outliertab.OutlierVisualTab.scrollPane0MouseWheelMoved(), moa.gui.outliertab.OutlierVisualTab.scrollPane1, moa.gui.outliertab.OutlierVisualTab.speedSlider, moa.gui.outliertab.OutlierVisualTab.speedSliderMouseDragged(), moa.gui.outliertab.OutlierVisualTab.splitVisual, moa.gui.visualization.StreamOutlierPanel.StreamOutlierPanel(), moa.gui.outliertab.OutlierVisualTab.streamPanel0, moa.gui.outliertab.OutlierVisualTab.streamPanel1, moa.gui.outliertab.OutlierVisualTab.topWrapper, and moa.gui.outliertab.OutlierVisualTab.UpdateSplitVisualDivider().
Referenced by moa.gui.outliertab.OutlierVisualTab.resetComponents().
{
        java.awt.GridBagConstraints gridBagConstraints;
        jSplitPane1 = new javax.swing.JSplitPane();
        topWrapper = new javax.swing.JPanel();
        panelVisualWrapper = new javax.swing.JPanel();
        splitVisual = new javax.swing.JSplitPane();
        scrollPane1 = new javax.swing.JScrollPane();
        scrollPane0 = new javax.swing.JScrollPane();
        streamPanel0 = new moa.gui.visualization.StreamOutlierPanel(Color.RED);
        streamPanel1 = new moa.gui.visualization.StreamOutlierPanel(Color.BLUE);
        panelControl = new javax.swing.JPanel();
        buttonRun = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonRedraw = new javax.swing.JButton();
        buttonScreenshot = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        comboX = new javax.swing.JComboBox();
        labelX = new javax.swing.JLabel();
        comboY = new javax.swing.JComboBox();
        labelY = new javax.swing.JLabel();
        checkboxDrawPoints = new javax.swing.JCheckBox();
        checkboxDrawOutliers = new javax.swing.JCheckBox();
        checkboxWaitWinFull = new javax.swing.JCheckBox();
        label_processed_points = new javax.swing.JLabel();
        label_processed_points_value = new javax.swing.JLabel();
        labelNumPause = new javax.swing.JLabel();
        numPauseAfterPoints = new javax.swing.JTextField();
        panelEvalOutput = new javax.swing.JPanel();
        // outlierVisualEvalPanel1 = new moa.gui.outliertab.OutlierVisualEvalPanel();
        graphPanel = new javax.swing.JPanel();
        graphPanelControlTop = new javax.swing.JPanel();
        buttonZoomInY = new javax.swing.JButton();
        buttonZoomOutY = new javax.swing.JButton();
        labelEvents = new javax.swing.JLabel();
        graphScrollPanel = new javax.swing.JScrollPane();
        graphCanvas = new moa.gui.visualization.GraphCanvas();
        graphPanelControlBottom = new javax.swing.JPanel();
        buttonZoomInX = new javax.swing.JButton();
        buttonZoomOutX = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        topWrapper.setPreferredSize(new java.awt.Dimension(688, 500));
        topWrapper.setLayout(new java.awt.GridBagLayout());
        //panelVisualWrapper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelVisualWrapper.setLayout(new java.awt.BorderLayout());
        splitVisual.setDividerLocation(400);
        splitVisual.setResizeWeight(1.0);
        scrollPane0.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrollPane0MouseWheelMoved(evt);
            }
        });
        streamPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        javax.swing.GroupLayout streamPanel1Layout = new javax.swing.GroupLayout(streamPanel1);
        streamPanel1.setLayout(streamPanel1Layout);
        streamPanel1Layout.setHorizontalGroup(
            streamPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        streamPanel1Layout.setVerticalGroup(
            streamPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        scrollPane1.setViewportView(streamPanel1);
        splitVisual.setRightComponent(scrollPane1);
        scrollPane0.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrollPane0MouseWheelMoved(evt);
            }
        });
        streamPanel0.setPreferredSize(new java.awt.Dimension(400, 250));
        javax.swing.GroupLayout streamPanel0Layout = new javax.swing.GroupLayout(streamPanel0);
        streamPanel0.setLayout(streamPanel0Layout);
        streamPanel0Layout.setHorizontalGroup(
            streamPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        streamPanel0Layout.setVerticalGroup(
            streamPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        scrollPane0.setViewportView(streamPanel0);
        splitVisual.setLeftComponent(scrollPane0);
        splitVisual.addComponentListener(new ComponentListener() {
            @Override
            public void componentResized(ComponentEvent ce) {
                UpdateSplitVisualDivider();
            }
            @Override
            public void componentMoved(ComponentEvent ce) {
            }
            @Override
            public void componentShown(ComponentEvent ce) {
            }
            @Override
            public void componentHidden(ComponentEvent ce) {
            }
        });
        panelVisualWrapper.add(splitVisual, java.awt.BorderLayout.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        topWrapper.add(panelVisualWrapper, gridBagConstraints);
        panelControl.setMinimumSize(new java.awt.Dimension(600, 76));
        panelControl.setPreferredSize(new java.awt.Dimension(2000, 76));
        panelControl.setLayout(new java.awt.GridBagLayout());
        int iBtnHeight = 27;
        int iInsetW = 2;
        int iInsetH = 2;
        buttonRun.setText("Start");
        buttonRun.setMinimumSize(new java.awt.Dimension(90, iBtnHeight));
        buttonRun.setPreferredSize(new java.awt.Dimension(90, iBtnHeight));
        buttonRun.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRunMouseClicked(evt);
            }
        });
        buttonRun.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(iInsetW, iInsetH, iInsetW, iInsetH);
        panelControl.add(buttonRun, gridBagConstraints);
        buttonStop.setText("Stop");
        buttonStop.setMinimumSize(new java.awt.Dimension(90, iBtnHeight));
        buttonStop.setPreferredSize(new java.awt.Dimension(90, iBtnHeight));
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(iInsetW, iInsetH, iInsetW, iInsetH);
        panelControl.add(buttonStop, gridBagConstraints);
        buttonRedraw.setText("Redraw");
        buttonRedraw.setMinimumSize(new java.awt.Dimension(100, iBtnHeight));
        buttonRedraw.setPreferredSize(new java.awt.Dimension(100, iBtnHeight));
        buttonRedraw.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRedrawMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(iInsetW, iInsetH, iInsetW, iInsetH);
        panelControl.add(buttonRedraw, gridBagConstraints);
        buttonScreenshot.setText("Screenshot");
        buttonScreenshot.setMinimumSize(new java.awt.Dimension(100, iBtnHeight));
        buttonScreenshot.setPreferredSize(new java.awt.Dimension(100, iBtnHeight));
        buttonScreenshot.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonScreenshotMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(iInsetW, iInsetH, iInsetW, iInsetH);
        panelControl.add(buttonScreenshot, gridBagConstraints);
        speedSlider.setValue(100);
        speedSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualisation Speed"));
        speedSlider.setMinimumSize(new java.awt.Dimension(160, 68));
        speedSlider.setPreferredSize(new java.awt.Dimension(170, 68));
        speedSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                speedSliderMouseDragged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 1, 5);
        panelControl.add(speedSlider, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelControl.add(jLabel1, gridBagConstraints);
        comboX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dim 1", "Dim 2", "Dim 3", "Dim 4" }));
        comboX.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboXActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(comboX, gridBagConstraints);
        labelX.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 5);
        panelControl.add(labelX, gridBagConstraints);
        comboY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dim 1", "Dim 2", "Dim 3", "Dim 4" }));
        comboY.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(comboY, gridBagConstraints);
        labelY.setText("Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 5);
        panelControl.add(labelY, gridBagConstraints);
        checkboxDrawPoints.setSelected(true);
        checkboxDrawPoints.setText("Points");
        checkboxDrawPoints.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawPoints.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawPointsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(checkboxDrawPoints, gridBagConstraints);
        checkboxDrawOutliers.setSelected(true);
        checkboxDrawOutliers.setText("Outliers");
        checkboxDrawOutliers.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxDrawOutliers.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDrawOutlierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        panelControl.add(checkboxDrawOutliers, gridBagConstraints);
        checkboxWaitWinFull.setSelected(true);
        checkboxWaitWinFull.setText("WaitWinFull");
        checkboxWaitWinFull.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkboxWaitWinFull.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxWaitWinFullActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 0);
        panelControl.add(checkboxWaitWinFull, gridBagConstraints);
        label_processed_points.setText("Processed:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panelControl.add(label_processed_points, gridBagConstraints);
        label_processed_points_value.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelControl.add(label_processed_points_value, gridBagConstraints);
        labelNumPause.setText("Pause in:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panelControl.add(labelNumPause, gridBagConstraints);
        numPauseAfterPoints.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPauseAfterPoints.setText(Integer.toString(RunOutlierVisualizer.initialPauseInterval));
        numPauseAfterPoints.setMinimumSize(new java.awt.Dimension(70, 25));
        numPauseAfterPoints.setPreferredSize(new java.awt.Dimension(70, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelControl.add(numPauseAfterPoints, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        topWrapper.add(panelControl, gridBagConstraints);
        jSplitPane1.setLeftComponent(topWrapper);
        panelEvalOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluation"));
        panelEvalOutput.setLayout(new java.awt.GridBagLayout());
        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Process time per object"));
        graphPanel.setPreferredSize(new java.awt.Dimension(530, 115));
        graphPanel.setLayout(new java.awt.GridBagLayout());
        graphPanelControlTop.setLayout(new java.awt.GridBagLayout());
        buttonZoomInY.setText("Zoom in Y");
        buttonZoomInY.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomInY, gridBagConstraints);
        buttonZoomOutY.setText("Zoom out Y");
        buttonZoomOutY.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutYActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(buttonZoomOutY, gridBagConstraints);
        labelEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        graphPanelControlTop.add(labelEvents, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        graphPanel.add(graphPanelControlTop, gridBagConstraints);
        graphCanvas.setPreferredSize(new java.awt.Dimension(500, 111));
        javax.swing.GroupLayout graphCanvasLayout = new javax.swing.GroupLayout(graphCanvas);
        graphCanvas.setLayout(graphCanvasLayout);
        graphCanvasLayout.setHorizontalGroup(
            graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        graphCanvasLayout.setVerticalGroup(
            graphCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        graphScrollPanel.setViewportView(graphCanvas);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        graphPanel.add(graphScrollPanel, gridBagConstraints);
        buttonZoomInX.setText("Zoom in X");
        buttonZoomInX.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomInXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomInX);
        buttonZoomOutX.setText("Zoom out X");
        buttonZoomOutX.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZoomOutXActionPerformed(evt);
            }
        });
        graphPanelControlBottom.add(buttonZoomOutX);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        graphPanel.add(graphPanelControlBottom, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        panelEvalOutput.add(graphPanel, gridBagConstraints);
        panelEvalOutput.addComponentListener(new ComponentListener() {
            @Override
            public void componentResized(ComponentEvent ce) {
                //System.out.println("panelEvalOutput componentResized");
                graphCanvas.updateCanvas(true);
            }
            @Override
            public void componentMoved(ComponentEvent ce) {
            }
            @Override
            public void componentShown(ComponentEvent ce) {
            }
            @Override
            public void componentHidden(ComponentEvent ce) {
            }
        });
        jSplitPane1.setRightComponent(panelEvalOutput);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);
        //add(topWrapper, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
boolean moa.gui.outliertab.OutlierVisualTab.isEnabledDrawOutliers ()
Definition at line 101 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.checkboxDrawOutliers.
Referenced by moa.gui.visualization.RunOutlierVisualizer.showOutliers().
{
        return checkboxDrawOutliers.isSelected();
    }
boolean moa.gui.outliertab.OutlierVisualTab.isEnabledDrawPoints ()
Definition at line 97 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.checkboxDrawPoints.
{
        return checkboxDrawPoints.isSelected();
    }
void moa.gui.outliertab.OutlierVisualTab.repaint ()
Definition at line 123 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.UpdateSplitVisualDivider().
{
        super.repaint();
        UpdateSplitVisualDivider();
    }
void moa.gui.outliertab.OutlierVisualTab.resetComponents () [private]
Definition at line 50 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.comboY, moa.gui.outliertab.OutlierVisualTab.graphCanvas, moa.gui.outliertab.OutlierVisualTab.graphScrollPanel, moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.visualization.GraphCanvas.setViewport().
Referenced by moa.gui.outliertab.OutlierVisualTab.OutlierVisualTab(), and moa.gui.outliertab.OutlierVisualTab.stopVisualizer().
{
        initComponents();
        comboY.setSelectedIndex(1);
        graphCanvas.setViewport(graphScrollPanel.getViewport());
        //TODO this needs to only affect the visual Panel
        ToolTipManager.sharedInstance().setDismissDelay(20000);
        ToolTipManager.sharedInstance().setInitialDelay(100);
    }
void moa.gui.outliertab.OutlierVisualTab.scrollPane0MouseWheelMoved (java.awt.event.MouseWheelEvent evt) [private]
Definition at line 718 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                                {//GEN-FIRST:event_scrollPane0MouseWheelMoved
        streamPanel0.setZoom(evt.getX(),evt.getY(),(-1)*evt.getWheelRotation(),scrollPane0);
    }//GEN-LAST:event_scrollPane0MouseWheelMoved
void moa.gui.outliertab.OutlierVisualTab.setDimensionComobBoxes (int numDimensions)
Definition at line 70 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.comboX, and moa.gui.outliertab.OutlierVisualTab.comboY.
Referenced by moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
{
        String[] dimensions = new String[numDimensions];
        for (int i = 0; i < dimensions.length; i++) {
            dimensions[i] = "Dim "+(i+1);
        }
        comboX.setModel(new javax.swing.DefaultComboBoxModel(dimensions));
        comboY.setModel(new javax.swing.DefaultComboBoxModel(dimensions));
        comboY.setSelectedIndex(1);
    }
void moa.gui.outliertab.OutlierVisualTab.setOutlierSetupTab (OutlierSetupTab outlierSetupTab)
Definition at line 60 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierTabPanel.OutlierTabPanel().
{
        this.outlierSetupTab = outlierSetupTab;
    }
void moa.gui.outliertab.OutlierVisualTab.setPauseInterval (int pause)
Definition at line 113 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.numPauseAfterPoints.
{
        numPauseAfterPoints.setText(Integer.toString(pause));
    }
void moa.gui.outliertab.OutlierVisualTab.setProcessedPointsCounter (int value)
Definition at line 105 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.label_processed_points_value.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData().
{
        label_processed_points_value.setText(Integer.toString(value));
    }
void moa.gui.outliertab.OutlierVisualTab.speedSliderMouseDragged (java.awt.event.MouseEvent evt) [private]
Definition at line 706 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
                                                                        {//GEN-FIRST:event_speedSliderMouseDragged
        if (speedSlider == null) return;
        if (visualizer == null)  return;
        visualizer.setSpeed(speedSlider.getValue());
    }//GEN-LAST:event_speedSliderMouseDragged
void moa.gui.outliertab.OutlierVisualTab.stopVisualizer ()
Definition at line 167 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.resetComponents(), moa.gui.outliertab.OutlierVisualTab.running, moa.gui.visualization.RunOutlierVisualizer.stop(), moa.gui.outliertab.OutlierVisualTab.visualizer, and moa.gui.outliertab.OutlierVisualTab.visualizerThread.
Referenced by moa.gui.outliertab.OutlierTabPanel.stop().
{
        if (visualizer == null) return;
        visualizer.stop();
        running = false;
        visualizer = null;
        visualizerThread = null;
        removeAll();
        resetComponents();
    }
void moa.gui.outliertab.OutlierVisualTab.toggleVisualizer (boolean internal)
Definition at line 144 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.buttonRun, moa.gui.outliertab.OutlierVisualTab.createVisualiterThread(), moa.gui.outliertab.OutlierVisualTab.outlierSetupTab, moa.gui.visualization.RunOutlierVisualizer.pause(), moa.gui.visualization.RunOutlierVisualizer.resume(), moa.gui.outliertab.OutlierVisualTab.running, moa.gui.outliertab.OutlierSetupTab.toggleRunMode(), moa.gui.outliertab.OutlierVisualTab.visualizer, and moa.gui.outliertab.OutlierVisualTab.visualizerThread.
Referenced by moa.gui.visualization.RunOutlierVisualizer.processData(), and moa.gui.outliertab.OutlierTabPanel.toggle().
{
        if(visualizer == null)
            createVisualiterThread();
        if(!visualizerThread.isAlive()){
            visualizerThread.start();
        }
        //pause
        if(running){
            running = false;
            visualizer.pause();
            buttonRun.setText("Resume");
        }
        else{
            running = true;
            visualizer.resume();
            buttonRun.setText("Pause");
        }
        if(internal)
            outlierSetupTab.toggleRunMode();
    }
void moa.gui.outliertab.OutlierVisualTab.UpdateSplitVisualDivider () [private]
Definition at line 117 of file OutlierVisualTab.java.
References moa.gui.outliertab.OutlierVisualTab.splitVisual.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.repaint().
{
        if(splitVisual != null)
            splitVisual.setDividerLocation(splitVisual.getWidth()/2);
    }
Member Data Documentation
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonRedraw [private]
Definition at line 810 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonRun [private]
Definition at line 808 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonScreenshot [private]
Definition at line 809 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonStop [private]
Definition at line 811 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonZoomInX [private]
Definition at line 812 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonZoomInY [private]
Definition at line 813 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonZoomOutX [private]
Definition at line 814 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JButton moa.gui.outliertab.OutlierVisualTab.buttonZoomOutY [private]
Definition at line 815 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JCheckBox moa.gui.outliertab.OutlierVisualTab.checkboxDrawOutliers [private]
Definition at line 816 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.isEnabledDrawOutliers().
javax.swing.JCheckBox moa.gui.outliertab.OutlierVisualTab.checkboxDrawPoints [private]
Definition at line 817 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.isEnabledDrawPoints().
javax.swing.JCheckBox moa.gui.outliertab.OutlierVisualTab.checkboxWaitWinFull [private]
Definition at line 818 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JComboBox moa.gui.outliertab.OutlierVisualTab.comboX [private]
Definition at line 820 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.setDimensionComobBoxes().
javax.swing.JComboBox moa.gui.outliertab.OutlierVisualTab.comboY [private]
Definition at line 821 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), moa.gui.outliertab.OutlierVisualTab.resetComponents(), and moa.gui.outliertab.OutlierVisualTab.setDimensionComobBoxes().
String moa.gui.outliertab.OutlierVisualTab.exportFile [private]
Definition at line 42 of file OutlierVisualTab.java.
moa.gui.visualization.GraphCanvas moa.gui.outliertab.OutlierVisualTab.graphCanvas [private]
Definition at line 822 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.getGraphCanvas(), moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.resetComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.graphPanel [private]
Definition at line 823 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.graphPanelControlBottom [private]
Definition at line 824 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.graphPanelControlTop [private]
Definition at line 825 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JScrollPane moa.gui.outliertab.OutlierVisualTab.graphScrollPanel [private]
Definition at line 826 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.resetComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.jLabel1 [private]
Definition at line 827 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JSplitPane moa.gui.outliertab.OutlierVisualTab.jSplitPane1 [private]
Definition at line 828 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.label_processed_points [private]
Definition at line 833 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.label_processed_points_value [private]
Definition at line 834 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.setProcessedPointsCounter().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.labelEvents [private]
Definition at line 829 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.labelNumPause [private]
Definition at line 830 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.labelX [private]
Definition at line 831 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JLabel moa.gui.outliertab.OutlierVisualTab.labelY [private]
Definition at line 832 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JTextField moa.gui.outliertab.OutlierVisualTab.numPauseAfterPoints [private]
Definition at line 835 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.getPauseInterval(), moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.setPauseInterval().
OutlierSetupTab moa.gui.outliertab.OutlierVisualTab.outlierSetupTab = null [private]
Definition at line 41 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.createVisualiterThread(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.panelControl [private]
Definition at line 836 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.panelEvalOutput [private]
Definition at line 837 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.panelVisualWrapper [private]
Definition at line 838 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
Boolean moa.gui.outliertab.OutlierVisualTab.running = false [private]
Definition at line 40 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.stopVisualizer(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
String moa.gui.outliertab.OutlierVisualTab.screenshotFilebase [private]
Definition at line 43 of file OutlierVisualTab.java.
javax.swing.JScrollPane moa.gui.outliertab.OutlierVisualTab.scrollPane0 [private]
Definition at line 839 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JScrollPane moa.gui.outliertab.OutlierVisualTab.scrollPane1 [private]
Definition at line 840 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JSlider moa.gui.outliertab.OutlierVisualTab.speedSlider [private]
Definition at line 841 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JSplitPane moa.gui.outliertab.OutlierVisualTab.splitVisual [private]
Definition at line 842 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents(), and moa.gui.outliertab.OutlierVisualTab.UpdateSplitVisualDivider().
moa.gui.visualization.StreamOutlierPanel moa.gui.outliertab.OutlierVisualTab.streamPanel0 [private]
Definition at line 843 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.getLeftStreamPanel(), and moa.gui.outliertab.OutlierVisualTab.initComponents().
moa.gui.visualization.StreamOutlierPanel moa.gui.outliertab.OutlierVisualTab.streamPanel1 [private]
Definition at line 844 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.getRightStreamPanel(), and moa.gui.outliertab.OutlierVisualTab.initComponents().
javax.swing.JPanel moa.gui.outliertab.OutlierVisualTab.topWrapper [private]
Definition at line 845 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.initComponents().
RunOutlierVisualizer moa.gui.outliertab.OutlierVisualTab.visualizer = null [private]
Definition at line 38 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.createVisualiterThread(), moa.gui.outliertab.OutlierVisualTab.stopVisualizer(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
Thread moa.gui.outliertab.OutlierVisualTab.visualizerThread = null [private]
Definition at line 39 of file OutlierVisualTab.java.
Referenced by moa.gui.outliertab.OutlierVisualTab.createVisualiterThread(), moa.gui.outliertab.OutlierVisualTab.stopVisualizer(), and moa.gui.outliertab.OutlierVisualTab.toggleVisualizer().
The documentation for this class was generated from the following file:
main/java/moa/gui/outliertab/OutlierVisualTab.java