MOA: moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator Class Reference
moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator Class Reference
Public Member Functions
Estimator (int sizeWindow)
void add (double value)
double total ()
Protected Attributes
double[] window
int posWindow
int lenWindow
int SizeWindow
double sum
Detailed Description
Definition at line 53 of file WindowRegressionPerformanceEvaluator.java.
Constructor & Destructor Documentation
moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.Estimator (int sizeWindow)
Definition at line 65 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.posWindow, moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.SizeWindow, and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.window.
{
            window = new double[sizeWindow];
            SizeWindow = sizeWindow;
            posWindow = 0;
        }
Member Function Documentation
void moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add (double value)
Definition at line 71 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.posWindow, moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.SizeWindow, moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.sum, and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.window.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult().
{
            sum -= window[posWindow];
            sum += value;
            window[posWindow] = value;
            posWindow++;
            if (posWindow == SizeWindow) {
                posWindow = 0;
            }
        }
double moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.total ()
Definition at line 81 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.sum.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.getMeanError(), moa.evaluation.WindowRegressionPerformanceEvaluator.getSquareError(), and moa.evaluation.WindowRegressionPerformanceEvaluator.getTotalWeightObserved().
{
            return sum;
        }
Member Data Documentation
int moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.lenWindow [protected]
Definition at line 59 of file WindowRegressionPerformanceEvaluator.java.
int moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.posWindow [protected]
Definition at line 57 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add(), and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.Estimator().
int moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.SizeWindow [protected]
Definition at line 61 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add(), and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.Estimator().
double moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.sum [protected]
Definition at line 63 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add(), and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.total().
double [] moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.window [protected]
Definition at line 55 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add(), and moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.Estimator().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/WindowRegressionPerformanceEvaluator.java