MOA: moa.options.WEKAClassOption Class Reference
moa.options.WEKAClassOption Class Reference
WEKA class option.
Public Member Functions
WEKAClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
WEKAClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
JComponent getEditComponent ()
Gets the GUI component to edit.
Static Public Member Functions
static String objectToCLIString (Object obj, Class<?> requiredType)
static Object cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
WEKA class option.
This option is used to access options in WEKA. For example, WEKAClassifier uses it to set the base learner.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
FracPete (fracpete at waikato dot ac dot nz)
Version:
$Revision$
Definition at line 42 of file WEKAClassOption.java.
Constructor & Destructor Documentation
moa.options.WEKAClassOption.WEKAClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString)
Definition at line 46 of file WEKAClassOption.java.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString);
    }
moa.options.WEKAClassOption.WEKAClassOption (String name, char cliChar, String purpose, Class<?> requiredType, String defaultCLIString, String nullString)
Definition at line 51 of file WEKAClassOption.java.
{
        super(name, cliChar, purpose, requiredType, defaultCLIString, nullString);
    }
Member Function Documentation
static Object moa.options.WEKAClassOption.cliStringToObject (String cliString, Class<?> requiredType, Option[] externalOptions) throws Exception [static]
Definition at line 105 of file WEKAClassOption.java.
References moa.options.AbstractClassOption.FILE_PREFIX_STRING, moa.options.AbstractClassOption.INMEM_PREFIX_STRING, and moa.options.AbstractClassOption.requiredType.
Referenced by moa.options.WEKAClassOption.setValueViaCLIString().
{
        if (cliString.startsWith(FILE_PREFIX_STRING)) {
            return new File(cliString.substring(FILE_PREFIX_STRING.length()));
        }
        if (cliString.startsWith(INMEM_PREFIX_STRING)) {
            return cliString.substring(INMEM_PREFIX_STRING.length());
        }
        cliString = cliString.trim();
        int firstSpaceIndex = cliString.indexOf(' ', 0);
        String className;
        String WEKAClassOptions;
        if (firstSpaceIndex > 0) {
            className = cliString.substring(0, firstSpaceIndex);
            WEKAClassOptions = cliString.substring(firstSpaceIndex + 1, cliString.length());
            WEKAClassOptions = WEKAClassOptions.trim();
        } else {
            className = cliString;
            WEKAClassOptions = "";
        }
        Class<?> classObject;
        try {
            classObject = Class.forName(className);
        } catch (Throwable t1) {
            try {
                // try prepending default package
                classObject = Class.forName(requiredType.getPackage().getName() + "." + className);
            } catch (Throwable t2) {
                try {
                    // try prepending task package
                    classObject = Class.forName(Task.class.getPackage().getName()   + "." + className);
                } catch (Throwable t3) {
                    throw new Exception("Class not found: " + className);
                }
            }
        }
        Object classInstance;
        try {
            classInstance = classObject.newInstance();
        } catch (Exception ex) {
            throw new Exception("Problem creating instance of class: "
                    + className, ex);
        }
        if (requiredType.isInstance(classInstance)
                || ((classInstance instanceof Task) && requiredType.isAssignableFrom(((Task) classInstance).getTaskResultType()))) {
            Vector<String> options = new Vector<String>();
            if (externalOptions != null) {
                for (Option option : externalOptions) {
                    options.add(option.getValueAsCLIString());
                }
            }
            else {
                String[] optionsTmp = Utils.splitOptions(cliString);
                for (int i = 1; i < optionsTmp.length; i++)
                    options.add(optionsTmp[i]);
            }
            if (classInstance instanceof weka.core.OptionHandler) {
                try {
                    ((weka.core.OptionHandler) classInstance).setOptions(options.toArray(new String[options.size()]));
                } catch (Exception ex) {
                    Enumeration enm = ((weka.core.OptionHandler) classInstance).listOptions();
                    StringBuffer optionsText = new StringBuffer();
                    while (enm.hasMoreElements()) {
                        weka.core.Option option = (weka.core.Option) enm.nextElement();
                        optionsText.append(option.synopsis() + '\n');
                        optionsText.append(option.description() + "\n");
                    }
                    throw new Exception("Problem with options to '"
                            + className
                            + "'."
                            + "\n\nValid options for "
                            + className
                            + ":\n"
                            + optionsText.toString(), ex);
                }
          }
        } else {
            throw new Exception("Class named '" + className
                    + "' is not an instance of " + requiredType.getName() + ".");
        }
        return classInstance;
    }
JComponent moa.options.WEKAClassOption.getEditComponent () [virtual]
Gets the GUI component to edit.
Returns:
the component to edit
Implements moa.options.AbstractClassOption.
Definition at line 189 of file WEKAClassOption.java.
{
        return new WEKAClassOptionEditComponent(this);
    }
String moa.options.WEKAClassOption.getValueAsCLIString () [virtual]
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 57 of file WEKAClassOption.java.
References moa.options.AbstractClassOption.currentValue, and moa.options.AbstractClassOption.nullString.
Referenced by moa.gui.WEKAClassOptionEditComponent.editObject(), moa.classifiers.meta.WEKAClassifier.resetLearningImpl(), and moa.gui.WEKAClassOptionEditComponent.WEKAClassOptionEditComponent().
{
        if ((this.currentValue == null) && (this.nullString != null)) {
            return this.nullString;
        }
        String result = currentValue.getClass().getName();
        if (currentValue instanceof weka.core.OptionHandler)
            result += " " + Utils.joinOptions(((weka.core.OptionHandler) currentValue).getOptions());
        result = result.trim();
        return result;
    }
static String moa.options.WEKAClassOption.objectToCLIString (Object obj, Class<?> requiredType) [static]
Definition at line 85 of file WEKAClassOption.java.
References moa.options.AbstractClassOption.classToCLIString(), moa.options.AbstractClassOption.FILE_PREFIX_STRING, and moa.options.AbstractClassOption.INMEM_PREFIX_STRING.
{
        if (obj == null) {
            return "";
        }
        if (obj instanceof File) {
            return (FILE_PREFIX_STRING + ((File) obj).getPath());
        }
        if (obj instanceof String) {
            return (INMEM_PREFIX_STRING + obj);
        }
        String className = classToCLIString(obj.getClass(), requiredType);
        if (obj instanceof weka.core.OptionHandler) {
            String subOptions = Utils.joinOptions(((weka.core.OptionHandler) obj).getOptions());
            if (subOptions.length() > 0) {
                return new String(className + " " + subOptions).trim();
            }
        }
        return className;
    }
void moa.options.WEKAClassOption.setValueViaCLIString (String s) [virtual]
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implements moa.options.AbstractClassOption.
Definition at line 71 of file WEKAClassOption.java.
References moa.options.WEKAClassOption.cliStringToObject(), moa.options.AbstractClassOption.currentValue, moa.options.AbstractOption.getName(), moa.options.AbstractClassOption.nullString, and moa.options.AbstractClassOption.requiredType.
Referenced by moa.gui.WEKAClassOptionEditComponent.applyState().
{
        if ((this.nullString != null)
                && ((s == null) || (s.length() == 0) || s
                        .equals(this.nullString))) {
            this.currentValue = null;
        } else {
            try {
                this.currentValue = cliStringToObject(s, this.requiredType, null);
            } catch (Exception e) {
                throw new IllegalArgumentException("Problems with option: " + getName(), e);
            }
        }
    }
Member Data Documentation
final long moa.options.WEKAClassOption.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractClassOption.
Definition at line 44 of file WEKAClassOption.java.
The documentation for this class was generated from the following file:
main/java/moa/options/WEKAClassOption.java