MOA: moa.tasks.TaskThread Class Reference
moa.tasks.TaskThread Class Reference
Task Thread.
Public Types
enum Status {
NOT_STARTED, RUNNING, PAUSED, CANCELLING,
CANCELLED, COMPLETED, FAILED
}
Public Member Functions
TaskThread (Task toRun)
TaskThread (Task toRun, ObjectRepository repository)
void run ()
synchronized void pauseTask ()
synchronized void resumeTask ()
synchronized void cancelTask ()
double getCPUSecondsElapsed ()
Task getTask ()
String getCurrentStatusString ()
String getCurrentActivityString ()
double getCurrentActivityFracComplete ()
boolean isComplete ()
Object getFinalResult ()
void addTaskCompletionListener (TaskCompletionListener tcl)
void removeTaskCompletionListener (TaskCompletionListener tcl)
void getPreview (ResultPreviewListener previewer)
Object getLatestResultPreview ()
double getLatestPreviewGrabTimeSeconds ()
Protected Member Functions
void fireTaskCompleted ()
Protected Attributes
Task runningTask
volatile Status currentStatus
TaskMonitor taskMonitor
ObjectRepository repository
Object finalResult
long taskStartTime
long taskEndTime
double latestPreviewGrabTime = 0.0
Package Attributes
CopyOnWriteArraySet
< TaskCompletionListener > completionListeners = new CopyOnWriteArraySet<TaskCompletionListener>()
Detailed Description
Task Thread.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file TaskThread.java.
Member Enumeration Documentation
enum moa::tasks::TaskThread::Status
Enumerator:
NOT_STARTED
RUNNING
PAUSED
CANCELLING
CANCELLED
COMPLETED
FAILED
Definition at line 35 of file TaskThread.java.
{
        NOT_STARTED, RUNNING, PAUSED, CANCELLING, CANCELLED, COMPLETED, FAILED
    }
Constructor & Destructor Documentation
moa.tasks.TaskThread.TaskThread (Task toRun)
Definition at line 58 of file TaskThread.java.
{
        this(toRun, null);
    }
moa.tasks.TaskThread.TaskThread (Task toRun, ObjectRepository repository)
Definition at line 62 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskThread.runningTask, moa.tasks.TaskMonitor.setCurrentActivityDescription(), and moa.tasks.TaskThread.taskMonitor.
{
        this.runningTask = toRun;
        this.repository = repository;
        this.currentStatus = Status.NOT_STARTED;
        this.taskMonitor = new StandardTaskMonitor();
        this.taskMonitor.setCurrentActivityDescription("Running task " + toRun);
    }
Member Function Documentation
void moa.tasks.TaskThread.addTaskCompletionListener (TaskCompletionListener tcl)
Definition at line 179 of file TaskThread.java.
References moa.tasks.TaskThread.completionListeners.
{
        this.completionListeners.add(tcl);
    }
synchronized void moa.tasks.TaskThread.cancelTask ()
Definition at line 103 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskMonitor.requestCancel(), and moa.tasks.TaskThread.taskMonitor.
{
        if ((this.currentStatus == Status.RUNNING)
                || (this.currentStatus == Status.PAUSED)) {
            this.taskMonitor.requestCancel();
            this.currentStatus = Status.CANCELLING;
        }
    }
void moa.tasks.TaskThread.fireTaskCompleted () [protected]
Definition at line 187 of file TaskThread.java.
References moa.tasks.TaskThread.completionListeners.
Referenced by moa.tasks.TaskThread.run().
{
        for (TaskCompletionListener listener : this.completionListeners) {
            listener.taskCompleted(this);
        }
    }
double moa.tasks.TaskThread.getCPUSecondsElapsed ()
Definition at line 111 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskThread.isComplete(), moa.tasks.TaskThread.taskEndTime, and moa.tasks.TaskThread.taskStartTime.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.tasks.TaskThread.getPreview(), moa.gui.TaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt(), and moa.DoTask.main().
{
        double secondsElapsed = 0.0;
        if (this.currentStatus == Status.NOT_STARTED) {
            secondsElapsed = 0.0;
        } else if (isComplete()) {
            secondsElapsed = TimingUtils.nanoTimeToSeconds(this.taskEndTime
                    - this.taskStartTime);
        } else {
            secondsElapsed = TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfThread(getId())
                    - this.taskStartTime);
        }
        return secondsElapsed > 0.0 ? secondsElapsed : 0.0;
    }
double moa.tasks.TaskThread.getCurrentActivityFracComplete ()
Definition at line 154 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskMonitor.getCurrentActivityFractionComplete(), and moa.tasks.TaskThread.taskMonitor.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.gui.TaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt(), and moa.DoTask.main().
{
        switch (this.currentStatus) {
            case NOT_STARTED:
                return 0.0;
            case RUNNING:
            case PAUSED:
            case CANCELLING:
                return this.taskMonitor.getCurrentActivityFractionComplete();
            case CANCELLED:
            case COMPLETED:
            case FAILED:
                return 1.0;
        }
        return 0.0;
    }
String moa.tasks.TaskThread.getCurrentActivityString ()
Definition at line 149 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskMonitor.getCurrentActivityDescription(), moa.tasks.TaskThread.isComplete(), and moa.tasks.TaskThread.taskMonitor.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.gui.TaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt(), and moa.DoTask.main().
{
        return (isComplete() || (this.currentStatus == Status.NOT_STARTED)) ? ""
                : this.taskMonitor.getCurrentActivityDescription();
    }
String moa.tasks.TaskThread.getCurrentStatusString ()
Definition at line 129 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.gui.TaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt(), and moa.DoTask.main().
{
        switch (this.currentStatus) {
            case NOT_STARTED:
                return "not started";
            case RUNNING:
                return "running";
            case PAUSED:
                return "paused";
            case CANCELLING:
                return "cancelling";
            case CANCELLED:
                return "cancelled";
            case COMPLETED:
                return "completed";
            case FAILED:
                return "failed";
        }
        return "unknown";
    }
Object moa.tasks.TaskThread.getFinalResult ()
Definition at line 175 of file TaskThread.java.
References moa.tasks.TaskThread.finalResult.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.DoTask.main(), and moa.gui.PreviewPanel.setLatestPreview().
{
        return this.finalResult;
    }
double moa.tasks.TaskThread.getLatestPreviewGrabTimeSeconds ()
Definition at line 202 of file TaskThread.java.
References moa.tasks.TaskThread.latestPreviewGrabTime.
Referenced by moa.gui.PreviewPanel.setLatestPreview().
{
        return this.latestPreviewGrabTime;
    }
Object moa.tasks.TaskThread.getLatestResultPreview ()
Definition at line 198 of file TaskThread.java.
References moa.tasks.TaskMonitor.getLatestResultPreview(), and moa.tasks.TaskThread.taskMonitor.
Referenced by moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        return this.taskMonitor.getLatestResultPreview();
    }
void moa.tasks.TaskThread.getPreview (ResultPreviewListener previewer)
Definition at line 193 of file TaskThread.java.
References moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.latestPreviewGrabTime, moa.tasks.TaskMonitor.requestResultPreview(), and moa.tasks.TaskThread.taskMonitor.
Referenced by moa.gui.PreviewPanel.refresh().
{
        this.taskMonitor.requestResultPreview(previewer);
        this.latestPreviewGrabTime = getCPUSecondsElapsed();
    }
Task moa.tasks.TaskThread.getTask ()
Definition at line 125 of file TaskThread.java.
References moa.tasks.TaskThread.runningTask.
Referenced by moa.gui.conceptdrift.CDTaskManagerPanel.getSelectedCurrenTask(), moa.gui.TaskManagerPanel.TaskTableModel.getValueAt(), moa.gui.RegressionTaskManagerPanel.TaskTableModel.getValueAt(), and moa.gui.conceptdrift.CDTaskManagerPanel.TaskTableModel.getValueAt().
{
        return this.runningTask;
    }
boolean moa.tasks.TaskThread.isComplete ()
Definition at line 170 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus.
Referenced by moa.integration.SimpleClusterTest.doTask(), moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.getCurrentActivityString(), moa.DoTask.main(), moa.gui.PreviewPanel.refresh(), moa.gui.PreviewPanel.setLatestPreview(), and moa.gui.PreviewPanel.setTaskThreadToPreview().
{
        return ((this.currentStatus == Status.CANCELLED)
                || (this.currentStatus == Status.COMPLETED) || (this.currentStatus == Status.FAILED));
    }
synchronized void moa.tasks.TaskThread.pauseTask ()
Definition at line 89 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskMonitor.requestPause(), and moa.tasks.TaskThread.taskMonitor.
{
        if (this.currentStatus == Status.RUNNING) {
            this.taskMonitor.requestPause();
            this.currentStatus = Status.PAUSED;
        }
    }
void moa.tasks.TaskThread.removeTaskCompletionListener (TaskCompletionListener tcl)
Definition at line 183 of file TaskThread.java.
References moa.tasks.TaskThread.completionListeners.
{
        this.completionListeners.remove(tcl);
    }
synchronized void moa.tasks.TaskThread.resumeTask ()
Definition at line 96 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.TaskMonitor.requestResume(), and moa.tasks.TaskThread.taskMonitor.
{
        if (this.currentStatus == Status.PAUSED) {
            this.taskMonitor.requestResume();
            this.currentStatus = Status.RUNNING;
        }
    }
void moa.tasks.TaskThread.run ()
Definition at line 71 of file TaskThread.java.
References moa.tasks.TaskThread.currentStatus, moa.tasks.Task.doTask(), moa.tasks.TaskThread.finalResult, moa.tasks.TaskThread.fireTaskCompleted(), moa.tasks.TaskMonitor.isCancelled(), moa.tasks.TaskThread.repository, moa.tasks.TaskThread.runningTask, moa.tasks.TaskMonitor.setLatestResultPreview(), moa.tasks.TaskThread.taskEndTime, moa.tasks.TaskThread.taskMonitor, and moa.tasks.TaskThread.taskStartTime.
                      {
        TimingUtils.enablePreciseTiming();
        this.taskStartTime = TimingUtils.getNanoCPUTimeOfThread(getId());
        try {
            this.currentStatus = Status.RUNNING;
            this.finalResult = this.runningTask.doTask(this.taskMonitor,
                    this.repository);
            this.currentStatus = this.taskMonitor.isCancelled() ? Status.CANCELLED
                    : Status.COMPLETED;
        } catch (Throwable ex) {
            this.currentStatus = Status.FAILED;
            this.finalResult = new FailedTaskReport(ex);
        }
        this.taskEndTime = TimingUtils.getNanoCPUTimeOfThread(getId());
        fireTaskCompleted();
        this.taskMonitor.setLatestResultPreview(null); // free preview memory
    }
Member Data Documentation
CopyOnWriteArraySet<TaskCompletionListener> moa.tasks.TaskThread.completionListeners = new CopyOnWriteArraySet<TaskCompletionListener>() [package]
Definition at line 56 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.addTaskCompletionListener(), moa.tasks.TaskThread.fireTaskCompleted(), and moa.tasks.TaskThread.removeTaskCompletionListener().
volatile Status moa.tasks.TaskThread.currentStatus [protected]
Definition at line 42 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.cancelTask(), moa.tasks.TaskThread.getCPUSecondsElapsed(), moa.tasks.TaskThread.getCurrentActivityFracComplete(), moa.tasks.TaskThread.getCurrentActivityString(), moa.tasks.TaskThread.getCurrentStatusString(), moa.tasks.TaskThread.isComplete(), moa.tasks.TaskThread.pauseTask(), moa.tasks.TaskThread.resumeTask(), moa.tasks.TaskThread.run(), and moa.tasks.TaskThread.TaskThread().
Object moa.tasks.TaskThread.finalResult [protected]
Definition at line 48 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.getFinalResult(), and moa.tasks.TaskThread.run().
double moa.tasks.TaskThread.latestPreviewGrabTime = 0.0 [protected]
Definition at line 54 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.getLatestPreviewGrabTimeSeconds(), and moa.tasks.TaskThread.getPreview().
ObjectRepository moa.tasks.TaskThread.repository [protected]
Definition at line 46 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.run().
Task moa.tasks.TaskThread.runningTask [protected]
Definition at line 40 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.getTask(), moa.tasks.TaskThread.run(), and moa.tasks.TaskThread.TaskThread().
long moa.tasks.TaskThread.taskEndTime [protected]
Definition at line 52 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.getCPUSecondsElapsed(), and moa.tasks.TaskThread.run().
TaskMonitor moa.tasks.TaskThread.taskMonitor [protected]
Definition at line 44 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.cancelTask(), moa.tasks.TaskThread.getCurrentActivityFracComplete(), moa.tasks.TaskThread.getCurrentActivityString(), moa.tasks.TaskThread.getLatestResultPreview(), moa.tasks.TaskThread.getPreview(), moa.tasks.TaskThread.pauseTask(), moa.tasks.TaskThread.resumeTask(), moa.tasks.TaskThread.run(), and moa.tasks.TaskThread.TaskThread().
long moa.tasks.TaskThread.taskStartTime [protected]
Definition at line 50 of file TaskThread.java.
Referenced by moa.tasks.TaskThread.getCPUSecondsElapsed(), and moa.tasks.TaskThread.run().
The documentation for this class was generated from the following file:
main/java/moa/tasks/TaskThread.java