MOA: moa.evaluation.WindowRegressionPerformanceEvaluator Class Reference
moa.evaluation.WindowRegressionPerformanceEvaluator Class Reference
Regression evaluator that updates evaluation results using a sliding window.
Classes
class Estimator
Public Member Functions
void reset ()
Resets this evaluator.
void reset (int numClasses)
void addResult (Instance inst, double[] prediction)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getMeanError ()
double getSquareError ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Public Attributes
IntOption widthOption
Protected Attributes
double TotalweightObserved = 0
Estimator weightObserved
Estimator squareError
Estimator averageError
int numClasses
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Regression evaluator that updates evaluation results using a sliding window.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 35 of file WindowRegressionPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.WindowRegressionPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 104 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.add(), moa.evaluation.WindowRegressionPerformanceEvaluator.averageError, moa.evaluation.WindowRegressionPerformanceEvaluator.reset(), moa.evaluation.WindowRegressionPerformanceEvaluator.squareError, moa.evaluation.WindowRegressionPerformanceEvaluator.TotalweightObserved, and moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved.
{
        double weight = inst.weight();
        if (weight > 0.0) {
            if (TotalweightObserved == 0) {
                reset(inst.dataset().numClasses());
            }
            this.TotalweightObserved += weight;
            this.weightObserved.add(weight);
            if (prediction.length > 0) {
                this.squareError.add((inst.classValue() - prediction[0]) * (inst.classValue() - prediction[0]));
                this.averageError.add(Math.abs(inst.classValue() - prediction[0]));
            }
            //System.out.println(inst.classValue()+", "+prediction[0]);
        }
    }
void moa.evaluation.WindowRegressionPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 147 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.WindowRegressionPerformanceEvaluator.getMeanError ()
Definition at line 136 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.averageError, moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.total(), and moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved.total() > 0.0 ? this.averageError.total()
                / this.weightObserved.total() : 0.0;
    }
Measurement [] moa.evaluation.WindowRegressionPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 122 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.getMeanError(), moa.evaluation.WindowRegressionPerformanceEvaluator.getSquareError(), and moa.evaluation.WindowRegressionPerformanceEvaluator.getTotalWeightObserved().
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.getDescription().
{
        return new Measurement[]{
                    new Measurement("classified instances",
                    getTotalWeightObserved()),
                    new Measurement("mean absolute error",
                    getMeanError()),
                    new Measurement("root mean squared error",
                    getSquareError())};
    }
double moa.evaluation.WindowRegressionPerformanceEvaluator.getSquareError ()
Definition at line 141 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.squareError, moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.total(), and moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.getPerformanceMeasurements().
{
        return Math.sqrt(this.weightObserved.total() > 0.0 ? this.squareError.total()
                / this.weightObserved.total() : 0.0);
    }
double moa.evaluation.WindowRegressionPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 132 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.Estimator.total(), and moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved.total();
    }
void moa.evaluation.WindowRegressionPerformanceEvaluator.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 153 of file WindowRegressionPerformanceEvaluator.java.
{
    }
void moa.evaluation.WindowRegressionPerformanceEvaluator.reset (int numClasses)
Definition at line 95 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.averageError, moa.options.IntOption.getValue(), moa.evaluation.WindowRegressionPerformanceEvaluator.squareError, moa.evaluation.WindowRegressionPerformanceEvaluator.TotalweightObserved, moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved, and moa.evaluation.WindowRegressionPerformanceEvaluator.widthOption.
{
        this.numClasses = numClasses;
        this.weightObserved = new Estimator(this.widthOption.getValue());
        this.squareError = new Estimator(this.widthOption.getValue());
        this.averageError = new Estimator(this.widthOption.getValue());
        this.TotalweightObserved = 0;
    }
void moa.evaluation.WindowRegressionPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 91 of file WindowRegressionPerformanceEvaluator.java.
References moa.evaluation.WindowRegressionPerformanceEvaluator.numClasses.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult().
{
        reset(this.numClasses);
    }
Member Data Documentation
Estimator moa.evaluation.WindowRegressionPerformanceEvaluator.averageError [protected]
Definition at line 49 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult(), moa.evaluation.WindowRegressionPerformanceEvaluator.getMeanError(), and moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
int moa.evaluation.WindowRegressionPerformanceEvaluator.numClasses [protected]
Definition at line 51 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
final long moa.evaluation.WindowRegressionPerformanceEvaluator.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 38 of file WindowRegressionPerformanceEvaluator.java.
Estimator moa.evaluation.WindowRegressionPerformanceEvaluator.squareError [protected]
Definition at line 47 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult(), moa.evaluation.WindowRegressionPerformanceEvaluator.getSquareError(), and moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
double moa.evaluation.WindowRegressionPerformanceEvaluator.TotalweightObserved = 0 [protected]
Definition at line 43 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult(), and moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
Estimator moa.evaluation.WindowRegressionPerformanceEvaluator.weightObserved [protected]
Definition at line 45 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.addResult(), moa.evaluation.WindowRegressionPerformanceEvaluator.getMeanError(), moa.evaluation.WindowRegressionPerformanceEvaluator.getSquareError(), moa.evaluation.WindowRegressionPerformanceEvaluator.getTotalWeightObserved(), and moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
IntOption moa.evaluation.WindowRegressionPerformanceEvaluator.widthOption
Initial value:
 new IntOption("width",
            'w', "Size of Window", 1000)
Definition at line 40 of file WindowRegressionPerformanceEvaluator.java.
Referenced by moa.evaluation.WindowRegressionPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/WindowRegressionPerformanceEvaluator.java