MOA: moa.classifiers.meta.DACC Class Reference
moa.classifiers.meta.DACC Class Reference
Dynamic Adaptation to Concept Changes.
Classes
class Pair
This helper class is used to sort an array of pairs of integers: val and index.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
void resetLearningImpl ()
Resets this classifier.
void trainOnInstanceImpl (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
void discardModel (int index)
Resets a classifier in the ensemble.
void getModelDescription (StringBuilder out, int indent)
Returns a string representation of the model.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Public Attributes
ClassOption learnerOption
Base classifier.
FloatOption memberCountOption = new FloatOption("ensembleSize", 'n', "The maximum number of classifiers in an ensemble.", 20, 1, Integer.MAX_VALUE)
Ensemble size.
FloatOption maturityOption
Maturity age of classifiers.
FloatOption evaluationSizeOption
Size of the evaluation window for weights computing.
MultiChoiceOption combinationOption
Combination functions: MAX and WVD (MAX leads to a faster reactivity to the change, WVD is more robust to noise).
Protected Member Functions
void initVariables ()
Initializes the method variables.
void trainAndClassify (Instance inst)
Receives a training instance from the stream and updates the adaptive classifiers accordingly.
double updateEvaluationWindow (int index, int val)
Updates the evaluation window of a classifier and returns the updated weight value.
Pair[] getHalf (boolean bestHalf)
Returns the best (or worst) half of classifiers in the adaptive ensemble.
ArrayList< Integer > getMAXIndexes ()
Returns the classifiers that vote for the final prediction when the MAX combination function is selected.
ArrayList< Integer > getWVDIndexes ()
Returns the classifiers that vote for the final prediction when the WVD combination function is selected.
int getNbActiveClassifiers ()
Returns the number of classifiers used for prediction which includes the adaptive learners and the snapshots in ADACC.
int getNbAdaptiveClassifiers ()
Returns the number of adaptive classifiers in the ensemble which excludes the static snapshots in ADACC.
Measurement[] getModelMeasurementsImpl ()
Gets the current measurements of this classifier.
Protected Attributes
Classifier[] ensemble
Ensemble of classifiers.
Pair[] ensembleWeights
Weights of classifiers.
double[] ensembleAges
Age of classifiers (to compare with maturity age).
int[][] ensembleWindows
Evaluation windows (recent classification errors).
int nbInstances = 0
Number of instances from the stream.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Dynamic Adaptation to Concept Changes.
Ensemble method for data streams that adapts to concept changes.
Reference: JABER, G., CORNUEJOLS, A., and TARROUX, P. A New On-Line Learning Method for Coping with Recurring Concepts: The ADACC System. In : Neural Information Processing. Springer Berlin Heidelberg, 2013. p. 595-604.
Author:
Ghazal Jaber (ghazal.jaber@gmail.com)
Definition at line 48 of file DACC.java.
Member Function Documentation
void moa.classifiers.meta.DACC.discardModel (int index)
Resets a classifier in the ensemble.
Parameters:
index the index of the classifier in the ensemble
Definition at line 229 of file DACC.java.
References moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWeights, moa.classifiers.meta.DACC.ensembleWindows, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.FloatOption.getValue(), moa.classifiers.Classifier.resetLearning(), and moa.classifiers.meta.DACC.Pair.val.
Referenced by moa.classifiers.meta.DACC.trainAndClassify().
{
        this.ensemble[index].resetLearning();
        this.ensembleWeights[index].val = 0;
        this.ensembleAges[index] = 0;
        this.ensembleWindows[index]=new int[(int)this.evaluationSizeOption.getValue()];
    }
Pair [] moa.classifiers.meta.DACC.getHalf (boolean bestHalf) [protected]
Returns the best (or worst) half of classifiers in the adaptive ensemble.
The best classifiers are used to compute the stability index in ADACC. The worst classifiers are returned in order to select a classifier for deletion.
Parameters:
bestHalf boolean value set to true (false) if we want to return the best (worst) half of adaptive classifiers.
horizon
Returns:
an array containing the weight values of the corresponding classifiers and their indexes in the ensemble.
Definition at line 275 of file DACC.java.
References moa.classifiers.meta.DACC.ensembleWeights, and moa.classifiers.meta.DACC.getNbAdaptiveClassifiers().
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), and moa.classifiers.meta.DACC.trainAndClassify().
{
        Pair[] newEnsembleWeights = new Pair[getNbAdaptiveClassifiers()];
        System.arraycopy(ensembleWeights, 0, newEnsembleWeights, 0, newEnsembleWeights.length);
        if (bestHalf)
            Arrays.sort(newEnsembleWeights,Collections.reverseOrder());
        else
            Arrays.sort(newEnsembleWeights);
        Pair[] result = new Pair[(int)Math.floor(newEnsembleWeights.length/2)];
        System.arraycopy(newEnsembleWeights, 0, result, 0, result.length);
        return result;
    }
ArrayList<Integer> moa.classifiers.meta.DACC.getMAXIndexes () [protected]
Returns the classifiers that vote for the final prediction when the MAX combination function is selected.
Returns:
the classifiers with the highest weight value
Definition at line 297 of file DACC.java.
References moa.classifiers.meta.DACC.ensembleWeights, and moa.classifiers.meta.DACC.getNbActiveClassifiers().
Referenced by moa.classifiers.meta.DACC.getVotesForInstance().
{
        ArrayList<Integer> maxWIndex=new ArrayList<Integer>();
        Pair[] newEnsembleWeights = new Pair[getNbActiveClassifiers()];
        System.arraycopy(ensembleWeights, 0, newEnsembleWeights, 0, newEnsembleWeights.length);
        Arrays.sort(newEnsembleWeights);
        double maxWVal = newEnsembleWeights[newEnsembleWeights.length-1].val;
        for (int i = newEnsembleWeights.length-1 ; i>=0 ; i--){
            if (newEnsembleWeights[i].val!=maxWVal)
                break;
            else
                maxWIndex.add(newEnsembleWeights[i].index);
        }
        return maxWIndex;
    }
void moa.classifiers.meta.DACC.getModelDescription (StringBuilder out, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 366 of file DACC.java.
{
        // TODO Auto-generated method stub
    }
Measurement [] moa.classifiers.meta.DACC.getModelMeasurementsImpl () [protected, virtual]
Gets the current measurements of this classifier.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Returns:
an array of measurements to be used in evaluation tasks
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 371 of file DACC.java.
References moa.classifiers.meta.DACC.combinationOption, moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), and moa.classifiers.meta.DACC.maturityOption.
{
        Measurement[] measurements  = new Measurement[4];
        measurements[0] = new Measurement("size ",
                    this.ensemble.length);
        measurements[1] = new Measurement("maturity ",
                   this.maturityOption.getValue());
        measurements[2] = new Measurement("evalsize ",
                   this.evaluationSizeOption.getValue());
        measurements[3] = new Measurement("cmb ",
                   this.combinationOption.getChosenIndex());
       return measurements;
    }
int moa.classifiers.meta.DACC.getNbActiveClassifiers () [protected]
Returns the number of classifiers used for prediction which includes the adaptive learners and the snapshots in ADACC.
Returns:
the number of classifiers used for prediction
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 352 of file DACC.java.
References moa.classifiers.meta.DACC.ensemble.
Referenced by moa.classifiers.meta.DACC.getMAXIndexes(), moa.classifiers.meta.DACC.getWVDIndexes(), and moa.classifiers.meta.DACC.trainAndClassify().
{
        return this.ensemble.length;
    }
int moa.classifiers.meta.DACC.getNbAdaptiveClassifiers () [protected]
Returns the number of adaptive classifiers in the ensemble which excludes the static snapshots in ADACC.
Returns:
the number of adaptive classifiers
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 361 of file DACC.java.
References moa.classifiers.meta.DACC.ensemble.
Referenced by moa.classifiers.meta.DACC.getHalf(), and moa.classifiers.meta.DACC.trainAndClassify().
{
        return this.ensemble.length;
    }
String moa.classifiers.meta.DACC.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 53 of file DACC.java.
{
        return "Dynamic Adaptation to Concept Changes for data streams.";
    }
Classifier [] moa.classifiers.meta.DACC.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Reimplemented from moa.classifiers.AbstractClassifier.
Definition at line 390 of file DACC.java.
References moa.classifiers.meta.DACC.ensemble.
{
        return this.ensemble.clone();
    }
double [] moa.classifiers.meta.DACC.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implements moa.classifiers.Classifier.
Definition at line 139 of file DACC.java.
References moa.core.DoubleVector.addValues(), moa.classifiers.meta.DACC.combinationOption, moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleWeights, moa.core.DoubleVector.getArrayRef(), moa.options.MultiChoiceOption.getChosenIndex(), moa.classifiers.meta.DACC.getMAXIndexes(), moa.classifiers.Classifier.getVotesForInstance(), moa.classifiers.meta.DACC.getWVDIndexes(), moa.core.DoubleVector.normalize(), moa.core.DoubleVector.scaleValues(), moa.core.DoubleVector.sumOfValues(), moa.classifiers.AbstractClassifier.trainingWeightSeenByModel(), and moa.classifiers.meta.DACC.Pair.val.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex().
{
        DoubleVector combinedVote = new DoubleVector();
        ArrayList<Integer> arr;
        int cmb = this.combinationOption.getChosenIndex();
        if (cmb == 0)
            arr = getMAXIndexes();
        else
            arr = getWVDIndexes();
        if (this.trainingWeightSeenByModel > 0.0) {
             for (int i = 0; i < arr.size(); i++) {
                if (this.ensembleWeights[arr.get(i)].val > 0.0) {
                    DoubleVector vote = new DoubleVector(this.ensemble[arr.get(i)].getVotesForInstance(inst));
                    if (vote.sumOfValues() > 0.0) {
                        vote.normalize();
                        vote.scaleValues(this.ensembleWeights[arr.get(i)].val);
                        combinedVote.addValues(vote);
                    }
                }
            }
        }
        return combinedVote.getArrayRef();
    }
ArrayList<Integer> moa.classifiers.meta.DACC.getWVDIndexes () [protected]
Returns the classifiers that vote for the final prediction when the WVD combination function is selected.
Returns:
the classifiers whose weights lie in the higher half of the ensemble's weight interval.
Definition at line 323 of file DACC.java.
References moa.classifiers.meta.DACC.ensembleWeights, and moa.classifiers.meta.DACC.getNbActiveClassifiers().
Referenced by moa.classifiers.meta.DACC.getVotesForInstance().
{
        ArrayList<Integer> maxWIndex = new ArrayList<Integer>();
        Pair[] newEnsembleWeights = new Pair[getNbActiveClassifiers()];
        System.arraycopy(ensembleWeights, 0, newEnsembleWeights, 0, newEnsembleWeights.length);
        Arrays.sort(newEnsembleWeights);
        double minWVal = newEnsembleWeights[0].val;
        double maxWVal = newEnsembleWeights[newEnsembleWeights.length-1].val;
        double med = (maxWVal-minWVal)*1.0/2;
        for (int i = newEnsembleWeights.length-1 ; i>=0 ; i--)
            if (newEnsembleWeights[i].val < med)
                break;
            else
                maxWIndex.add(newEnsembleWeights[i].index);
        return maxWIndex;
    }
void moa.classifiers.meta.DACC.initVariables () [protected]
Initializes the method variables.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 107 of file DACC.java.
References moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWindows, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.FloatOption.getValue(), and moa.classifiers.meta.DACC.memberCountOption.
Referenced by moa.classifiers.meta.DACC.resetLearningImpl().
{
        int ensembleSize = (int)this.memberCountOption.getValue();
        this.ensemble = new Classifier[ensembleSize];
        this.ensembleAges = new double[ensembleSize];
        this.ensembleWindows = new int[ensembleSize][(int)this.evaluationSizeOption.getValue()];
    }
boolean moa.classifiers.meta.DACC.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implements moa.classifiers.Classifier.
Definition at line 385 of file DACC.java.
{
        return true;
    }
void moa.classifiers.meta.DACC.resetLearningImpl () [virtual]
Resets this classifier.
It must be similar to starting a new classifier from scratch.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Implements moa.classifiers.AbstractClassifier.
Definition at line 115 of file DACC.java.
References moa.classifiers.Classifier.copy(), moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWeights, moa.classifiers.meta.DACC.ensembleWindows, moa.classifiers.meta.DACC.evaluationSizeOption, moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.DACC.learnerOption, and moa.classifiers.Classifier.resetLearning().
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        learner.resetLearning();
        initVariables();
        this.ensembleWeights = new Pair[this.ensemble.length];
        for (int i = 0; i < this.ensemble.length; i++) {
            this.ensemble[i] = learner.copy();
            this.ensembleAges[i] = 0;
            this.ensembleWeights[i] = new Pair(0.0,i);
            this.ensembleWindows[i] = new int[(int)this.evaluationSizeOption.getValue()];
        }
    }
void moa.classifiers.meta.DACC.trainAndClassify (Instance inst) [protected]
Receives a training instance from the stream and updates the adaptive classifiers accordingly.
Parameters:
inst the instance from the stream
Definition at line 176 of file DACC.java.
References moa.classifiers.AbstractClassifier.classifierRandom, moa.classifiers.Classifier.correctlyClassifies(), moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.DACC.ensemble, moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWeights, moa.classifiers.meta.DACC.getHalf(), moa.classifiers.meta.DACC.getNbActiveClassifiers(), moa.classifiers.meta.DACC.getNbAdaptiveClassifiers(), moa.options.FloatOption.getValue(), moa.classifiers.meta.DACC.maturityOption, moa.classifiers.meta.DACC.nbInstances, moa.classifiers.AbstractClassifier.trainOnInstance(), moa.classifiers.meta.DACC.updateEvaluationWindow(), and moa.classifiers.meta.DACC.Pair.val.
Referenced by moa.classifiers.meta.DACC.trainOnInstanceImpl(), and moa.classifiers.meta.ADACC.trainOnInstanceImpl().
{
        nbInstances++;
        boolean mature = true;
        boolean unmature = true;
        for (int i = 0; i < getNbActiveClassifiers(); i++) {
            // check if all adaptive learners are mature
            if (this.ensembleAges[i] < this.maturityOption.getValue() && i<getNbAdaptiveClassifiers())
                mature = false;
            // check if all adaptive learners are not mature
            if (this.ensembleAges[i] >= this.maturityOption.getValue() && i<getNbAdaptiveClassifiers())
                unmature = false;
            if (this.nbInstances >= this.ensembleWeights[i].index + 1){
                // train adaptive learners
                if (i < getNbAdaptiveClassifiers())
                    this.ensemble[i].trainOnInstance(inst);
                int val = this.ensemble[i].correctlyClassifies(inst)?1:0;
                double sum = updateEvaluationWindow(i, val);
                this.ensembleWeights[i].val = sum;
                this.ensembleAges[i] = this.ensembleAges[i]+1;
            }
        }
        // if all adaptive learners are not mature --> set weights to one
        if (unmature)
            for (int i = 0; i < getNbAdaptiveClassifiers(); i++)
                this.ensembleWeights[i].val=1;
        // if all adaptive learners are mature --> delete one learner
        if (mature){
            Pair[] learners = getHalf(false);
            if (learners.length > 0){
                double rand = classifierRandom.nextInt(learners.length);
                discardModel(learners[(int)rand].index);
            }
        }
    }
void moa.classifiers.meta.DACC.trainOnInstanceImpl (Instance inst) [virtual]
Trains this classifier incrementally using the given instance.
The reason for ...Impl methods: ease programmer burden by not requiring them to remember calls to super in overridden methods. Note that this will produce compiler errors if not overridden.
Parameters:
inst the instance to be used for training
Implements moa.classifiers.AbstractClassifier.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 134 of file DACC.java.
References moa.classifiers.meta.DACC.trainAndClassify().
{
        trainAndClassify(inst);
    }
double moa.classifiers.meta.DACC.updateEvaluationWindow (int index, int val) [protected]
Updates the evaluation window of a classifier and returns the updated weight value.
Parameters:
index the index of the classifier in the ensemble
val the last evaluation record of the classifier
Returns:
the updated weight value of the classifier
Definition at line 243 of file DACC.java.
References moa.classifiers.meta.DACC.ensembleAges, moa.classifiers.meta.DACC.ensembleWindows, moa.options.FloatOption.getValue(), and moa.classifiers.meta.DACC.maturityOption.
Referenced by moa.classifiers.meta.DACC.trainAndClassify().
{
        int[] newEnsembleWindows = new int[this.ensembleWindows[index].length];
        int wsize = (int)Math.min(this.evaluationSizeOption.getValue(),this.ensembleAges[index]+1);
        int sum = 0;
        for (int i = 0; i < wsize-1 ; i++){
            newEnsembleWindows[i+1] = this.ensembleWindows[index][i];
            sum = sum + this.ensembleWindows[index][i];
        }
        newEnsembleWindows[0] = val;
        this.ensembleWindows[index] = newEnsembleWindows;
        if (this.ensembleAges[index] >= this.maturityOption.getValue())
            return (sum + val) * 1.0/wsize;
        else
            return 0;
    }
Member Data Documentation
MultiChoiceOption moa.classifiers.meta.DACC.combinationOption
Initial value:
 new MultiChoiceOption("cmb", 'c', "The combination function.",
            new String[]{"MAX","WVD"} , new String[] {"Maximum","Weighted Vote of the best"},
            0)
Combination functions: MAX and WVD (MAX leads to a faster reactivity to the change, WVD is more robust to noise).
Definition at line 79 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), and moa.classifiers.meta.DACC.getVotesForInstance().
Classifier [] moa.classifiers.meta.DACC.ensemble [protected]
Ensemble of classifiers.
Definition at line 85 of file DACC.java.
Referenced by moa.classifiers.meta.ADACC.computeStabilityIndex(), moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.ADACC.getBestAdaptiveClassifier(), moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.DACC.getNbActiveClassifiers(), moa.classifiers.meta.ADACC.getNbActiveClassifiers(), moa.classifiers.meta.DACC.getNbAdaptiveClassifiers(), moa.classifiers.meta.ADACC.getNbAdaptiveClassifiers(), moa.classifiers.meta.DACC.getSubClassifiers(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.meta.ADACC.takeSnapshot(), and moa.classifiers.meta.DACC.trainAndClassify().
double [] moa.classifiers.meta.DACC.ensembleAges [protected]
Age of classifiers (to compare with maturity age).
Definition at line 93 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.meta.DACC.trainAndClassify(), and moa.classifiers.meta.DACC.updateEvaluationWindow().
Pair [] moa.classifiers.meta.DACC.ensembleWeights [protected]
Weights of classifiers.
Definition at line 89 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.ADACC.getBestAdaptiveClassifier(), moa.classifiers.meta.DACC.getHalf(), moa.classifiers.meta.DACC.getMAXIndexes(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.meta.DACC.getWVDIndexes(), moa.classifiers.meta.DACC.resetLearningImpl(), and moa.classifiers.meta.DACC.trainAndClassify().
int [][] moa.classifiers.meta.DACC.ensembleWindows [protected]
Evaluation windows (recent classification errors).
Definition at line 97 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.ADACC.initVariables(), moa.classifiers.meta.DACC.resetLearningImpl(), and moa.classifiers.meta.DACC.updateEvaluationWindow().
FloatOption moa.classifiers.meta.DACC.evaluationSizeOption
Initial value:
 new FloatOption("evalSize", 'e',
            "The size of the evaluation window.", 20, 1, 1000)
Size of the evaluation window for weights computing.
Definition at line 74 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.discardModel(), moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.DACC.initVariables(), moa.classifiers.meta.ADACC.initVariables(), and moa.classifiers.meta.DACC.resetLearningImpl().
ClassOption moa.classifiers.meta.DACC.learnerOption
Initial value:
 new ClassOption("baseLearner", 'l',
            "Classifier to train.", Classifier.class, "bayes.NaiveBayes")
Base classifier.
Definition at line 60 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.resetLearningImpl().
FloatOption moa.classifiers.meta.DACC.maturityOption
Initial value:
 new FloatOption("maturity", 'a',
            "The maturity age.", 20, 0, 100)
Maturity age of classifiers.
Definition at line 69 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.getModelMeasurementsImpl(), moa.classifiers.meta.ADACC.getModelMeasurementsImpl(), moa.classifiers.meta.DACC.trainAndClassify(), and moa.classifiers.meta.DACC.updateEvaluationWindow().
FloatOption moa.classifiers.meta.DACC.memberCountOption = new FloatOption("ensembleSize", 'n', "The maximum number of classifiers in an ensemble.", 20, 1, Integer.MAX_VALUE)
Ensemble size.
Definition at line 65 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.initVariables(), and moa.classifiers.meta.ADACC.initVariables().
int moa.classifiers.meta.DACC.nbInstances = 0 [protected]
Number of instances from the stream.
Definition at line 101 of file DACC.java.
Referenced by moa.classifiers.meta.DACC.trainAndClassify(), and moa.classifiers.meta.ADACC.trainOnInstanceImpl().
final long moa.classifiers.meta.DACC.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Reimplemented in moa.classifiers.meta.ADACC.
Definition at line 50 of file DACC.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/DACC.java