MOA: moa.gui.outliertab.OutlierEvalPanel Class Reference
moa.gui.outliertab.OutlierEvalPanel Class Reference
Public Member Functions
OutlierEvalPanel ()
Creates new form ClusteringEvalPanel.
MeasureCollection[] getSelectedMeasures ()
Package Attributes
Class<?>[] measure_classes = null
ArrayList< JLabel > labels = null
ArrayList< JCheckBox > checkboxes = null
Private Member Functions
void addComponents ()
Class<?>[] findMeasureClasses ()
void initComponents ()
This method is called from within the constructor to initialize the form.
Private Attributes
javax.swing.JPanel contentPanel
javax.swing.JScrollPane scrollPane
Detailed Description
Definition at line 34 of file OutlierEvalPanel.java.
Constructor & Destructor Documentation
moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel ()
Creates new form ClusteringEvalPanel.
Definition at line 43 of file OutlierEvalPanel.java.
References moa.gui.outliertab.OutlierEvalPanel.addComponents(), moa.gui.outliertab.OutlierEvalPanel.checkboxes, moa.gui.outliertab.OutlierEvalPanel.findMeasureClasses(), moa.gui.outliertab.OutlierEvalPanel.initComponents(), moa.gui.outliertab.OutlierEvalPanel.labels, and moa.gui.outliertab.OutlierEvalPanel.measure_classes.
Referenced by moa.gui.outliertab.OutlierSetupTab.initComponents().
{
        initComponents();
        measure_classes = findMeasureClasses();
        labels = new ArrayList<JLabel>();
        checkboxes = new ArrayList<JCheckBox>();
        addComponents();
    }
Member Function Documentation
void moa.gui.outliertab.OutlierEvalPanel.addComponents () [private]
Definition at line 51 of file OutlierEvalPanel.java.
References moa.gui.outliertab.OutlierEvalPanel.checkboxes, moa.gui.outliertab.OutlierEvalPanel.contentPanel, moa.evaluation.MeasureCollection.getName(), moa.evaluation.MeasureCollection.getNumMeasures(), moa.evaluation.MeasureCollection.isEnabled(), moa.gui.outliertab.OutlierEvalPanel.labels, and moa.gui.outliertab.OutlierEvalPanel.measure_classes.
Referenced by moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
{
        GridBagConstraints gb = new GridBagConstraints();
        gb.insets = new java.awt.Insets(4, 7, 4, 7);
        int counter = 0;
        for (int i = 0; i < measure_classes.length; i++) {
            try {
                MeasureCollection m = (MeasureCollection) measure_classes[i].newInstance();
                for (int j = 0; j < m.getNumMeasures(); j++) {
                    String t = m.getName(j);
                    JLabel l = new JLabel(m.getName(j));
                    l.setPreferredSize(new java.awt.Dimension(100, 14));
                    //labels[i].setToolTipText("");
                    gb.gridx = 0;
                    gb.gridy = counter;
                    labels.add(l);
                    contentPanel.add(l, gb);
                    JCheckBox cb = new JCheckBox();
                    if (m.isEnabled(j)) {
                        cb.setSelected(true);
                    } else {
                        cb.setSelected(false);
                    }
                    gb.gridx = 1;
                    checkboxes.add(cb);
                    contentPanel.add(cb, gb);
                    counter++;
                }
            } catch (Exception ex) {
                System.out.println("Couldn't create Instance for " + measure_classes[i].getName());
            }
        }
        JLabel dummy = new JLabel();
        gb.gridx = 0;
        gb.gridy++;
        gb.gridwidth = 3;
        gb.weightx = 1;
        gb.weighty = 1;
        add(dummy, gb);
    }
Class<?> [] moa.gui.outliertab.OutlierEvalPanel.findMeasureClasses () [private]
Definition at line 96 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
{
        AutoExpandVector<Class<?>> finalClasses = new AutoExpandVector<Class<?>>();
        Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("moa.evaluation",
                OutlierPerformance.class);
        for (Class<?> foundClass : classesFound) {
            finalClasses.add(foundClass);
        }
        return finalClasses.toArray(new Class<?>[finalClasses.size()]);
    }
MeasureCollection [] moa.gui.outliertab.OutlierEvalPanel.getSelectedMeasures ()
Definition at line 106 of file OutlierEvalPanel.java.
References moa.gui.outliertab.OutlierEvalPanel.measure_classes.
Referenced by moa.gui.outliertab.OutlierSetupTab.getMeasures().
{
        ArrayList<MeasureCollection> measuresSelect = new ArrayList<MeasureCollection>();
        for (int i = 0; i < measure_classes.length; i++) {
            try {
                MeasureCollection m = (MeasureCollection) measure_classes[i].newInstance();
                measuresSelect.add(m);
            } catch (Exception ex) {
                System.out.println("Couldn't create Instance for " + measure_classes[i].getName());
            }
        }
        MeasureCollection[] measures = new MeasureCollection[measuresSelect.size()];
        for (int i = 0; i < measures.length; i++) {
            measures[i] = measuresSelect.get(i);
        }
        return measures;
    }
void moa.gui.outliertab.OutlierEvalPanel.initComponents () [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 131 of file OutlierEvalPanel.java.
References moa.gui.outliertab.OutlierEvalPanel.contentPanel, and moa.gui.outliertab.OutlierEvalPanel.scrollPane.
Referenced by moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
{
        java.awt.GridBagConstraints gridBagConstraints;
        scrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluation Measures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        setLayout(new java.awt.GridBagLayout());
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(100, 225));
        contentPanel.setLayout(new java.awt.GridBagLayout());
        scrollPane.setViewportView(contentPanel);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
Member Data Documentation
ArrayList<JCheckBox> moa.gui.outliertab.OutlierEvalPanel.checkboxes = null [package]
Definition at line 40 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), and moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
javax.swing.JPanel moa.gui.outliertab.OutlierEvalPanel.contentPanel [private]
Definition at line 156 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), and moa.gui.outliertab.OutlierEvalPanel.initComponents().
ArrayList<JLabel> moa.gui.outliertab.OutlierEvalPanel.labels = null [package]
Definition at line 38 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), and moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
Class<?> [] moa.gui.outliertab.OutlierEvalPanel.measure_classes = null [package]
Definition at line 36 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.addComponents(), moa.gui.outliertab.OutlierEvalPanel.getSelectedMeasures(), and moa.gui.outliertab.OutlierEvalPanel.OutlierEvalPanel().
javax.swing.JScrollPane moa.gui.outliertab.OutlierEvalPanel.scrollPane [private]
Definition at line 157 of file OutlierEvalPanel.java.
Referenced by moa.gui.outliertab.OutlierEvalPanel.initComponents().
The documentation for this class was generated from the following file:
main/java/moa/gui/outliertab/OutlierEvalPanel.java