MOA: moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode Class Reference
moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode Class Reference
Public Member Functions
LimAttLearningNode (double[] initialClassObservations)
void setlistAttributes (int[] list)
void learnFromInstance (Instance inst, HoeffdingTree ht)
Protected Attributes
double weightSeenAtLastSplitEvaluation
int[] listAttributes
int numAttributes
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 70 of file LimAttHoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.LimAttLearningNode (double[] initialClassObservations)
Definition at line 80 of file LimAttHoeffdingTree.java.
{
            super(initialClassObservations);
        }
Member Function Documentation
void moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance (Instance inst, HoeffdingTree ht)
Reimplemented in moa.classifiers.trees.LimAttHoeffdingTree.LearningNodeNBAdaptive.
Definition at line 90 of file LimAttHoeffdingTree.java.
References moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.listAttributes, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.HoeffdingTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingTree.newNumericClassObserver(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.numAttributes, moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), and moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.setlistAttributes().
{
            this.observedClassDistribution.addToValue((int) inst.classValue(),
                    inst.weight());
            if (this.listAttributes == null) {
                setlistAttributes(((LimAttHoeffdingTree) ht).listAttributes);
            }
            for (int j = 0; j < this.numAttributes; j++) {
                int i = this.listAttributes[j];
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? ht.newNominalClassObserver() : ht.newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
                obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
            }
        }
void moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.setlistAttributes (int[] list)
Definition at line 84 of file LimAttHoeffdingTree.java.
References moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.listAttributes, and moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.numAttributes.
Referenced by moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance().
{
            this.listAttributes = list;
            this.numAttributes = list.length;
        }
Member Data Documentation
int [] moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.listAttributes [protected]
Definition at line 76 of file LimAttHoeffdingTree.java.
Referenced by moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), and moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.setlistAttributes().
int moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.numAttributes [protected]
Definition at line 78 of file LimAttHoeffdingTree.java.
Referenced by moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), and moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.setlistAttributes().
final long moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.trees.LimAttHoeffdingTree.LearningNodeNB, and moa.classifiers.trees.LimAttHoeffdingTree.LearningNodeNBAdaptive.
Definition at line 72 of file LimAttHoeffdingTree.java.
double moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.weightSeenAtLastSplitEvaluation [protected]
Definition at line 74 of file LimAttHoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/LimAttHoeffdingTree.java