MOA: moa.test.DiffUtils Class Reference
moa.test.DiffUtils Class Reference
A helper class for generating diffs between two files, lists of strings.
Classes
class Filler
A helper class for the side-by-side diff.
class SideBySideDiff
Container object for a side-by-side diff.
Static Public Member Functions
static boolean isDifferent (File file1, File file2)
Returns whether the two files differ.
static boolean isDifferent (String[] list1, String[] list2)
Returns whether the two lists differ.
static boolean isDifferent (List< String > list1, List< String > list2)
Returns whether the two lists differ.
static String unified (File file1, File file2)
Generates a unified diff for the two files.
static String unified (List< String > list1, List< String > list2)
Generates a unified diff for the two lists.
static SideBySideDiff sideBySide (File file1, File file2)
Generates a side-by-side diff for the two files.
static SideBySideDiff sideBySide (String[] list1, String[] list2)
Generates a side-by-side diff for the two lists.
static SideBySideDiff sideBySide (List< String > list1, List< String > list2)
Generates a side-by-side diff for the two lists.
static void main (String[] args) throws Exception
Usage: DiffUtils <unified|side-by-side|brief> <file1> <file2>.
Static Public Attributes
static final char INDICATOR_CHANGED = 'c'
the indicator for "changed".
static final char INDICATOR_ADDED = 'a'
the indicator for "added".
static final char INDICATOR_DELETED = 'd'
the indicator for "deleted".
static final char INDICATOR_SAME = ' '
the indicator for "same".
static final String SOURCE = "<"
the source indicator.
static final String DESTINATION = ">"
the destination indicator.
static final String SEPARATOR_UNIFIED = "---"
the separator for the unified output.
static final String SEPARATOR_SIDEBYSIDE = " | "
the separator for the side-by-side output on the command-line.
static final String OPTION_UNIFIED = "unified"
the unified option.
static final String OPTION_SIDEBYSIDE = "side-by-side"
the side-by-side option.
static final String OPTION_BRIEF = "brief"
the brief option.
static final int SIDEBYSIDE_SIZE = 5
the number of array elements in side-by-side diff.
static final int SIDEBYSIDE_FIRST = 0
the index for the first file in side-by-side diff.
static final int SIDEBYSIDE_SECOND = 1
the index for the second file in side-by-side diff.
static final int SIDEBYSIDE_INDICATOR = 2
the index for the indicator list in side-by-side diff.
static final int SIDEBYSIDE_STARTPOS = 3
the index for the list of start positions of deltas in side-by-side diff.
static final int SIDEBYSIDE_ENDPOS = 4
the index for the list of end positions of deltas in side-by-side diff.
Static Protected Member Functions
static List< String > loadFromFile (File file)
Loads the file.
static String toString (String ind, List lines)
Assembles the lines into a string.
static String createRange (Chunk chunk)
Creates a range string.
static void addToList (int from, int to, List< String > source, List dest)
Adds the specified contents of the source list to the destination list.
static void addToList (int from, int to, Object obj, List dest)
Adds the object to the destination list.
Detailed Description
A helper class for generating diffs between two files, lists of strings.
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
Revision
6358
Definition at line 40 of file DiffUtils.java.
Member Function Documentation
static void moa.test.DiffUtils.addToList (int from, int to, Object obj, List dest) [static, protected]
Adds the object to the destination list.
Parameters:
from the starting index
to the ending index (included)
dest the destination of the data
Definition at line 565 of file DiffUtils.java.
{
    for (int i = from; i <= to; i++)
      dest.add(obj);
  }
static void moa.test.DiffUtils.addToList (int from, int to, List< String > source, List dest) [static, protected]
Adds the specified contents of the source list to the destination list.
Parameters:
from the starting index
to the ending index (included)
source the source list
dest the destination of the data
Definition at line 553 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide().
{
    for (int i = from; i <= to; i++)
      dest.add(source.get(i));
  }
static String moa.test.DiffUtils.createRange (Chunk chunk) [static, protected]
Creates a range string.
Parameters:
chunk the chunk to create the range string for
Returns:
the range string
Definition at line 482 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.unified().
{
    if (chunk.size() == 1)
      return (chunk.getPosition() + 1) + "";
    else
      return (chunk.getPosition() + 1) + "," + (chunk.getPosition() + chunk.size());
  }
static boolean moa.test.DiffUtils.isDifferent (List< String > list1, List< String > list2) [static]
Returns whether the two lists differ.
Parameters:
file1 the first text file
file2 the second text file
Returns:
the side-by-side diff (first file: index 0, second file: index 1, indicator:)
Definition at line 437 of file DiffUtils.java.
{
    boolean result;
    Patch   patch;
    patch  = difflib.DiffUtils.diff(list1, list2);
    result = (patch.getDeltas().size() > 0);
    return result;
  }
static boolean moa.test.DiffUtils.isDifferent (String[] list1, String[] list2) [static]
Returns whether the two lists differ.
Parameters:
file1 the first list
file2 the second list
Returns:
true if different
Definition at line 426 of file DiffUtils.java.
References moa.test.DiffUtils.isDifferent().
{
    return isDifferent(Arrays.asList(list1), Arrays.asList(list2));
  }
static boolean moa.test.DiffUtils.isDifferent (File file1, File file2) [static]
Returns whether the two files differ.
Parameters:
file1 the first text file
file2 the second text file
Returns:
true if different
Definition at line 415 of file DiffUtils.java.
References moa.test.DiffUtils.loadFromFile().
Referenced by moa.test.DiffUtils.isDifferent(), and moa.test.DiffUtils.main().
{
    return isDifferent(loadFromFile(file1), loadFromFile(file2));
  }
static List<String> moa.test.DiffUtils.loadFromFile (File file) [static, protected]
Loads the file.
If file points to a directory, an empty vector is returned instead.
Parameters:
file the file to load
Returns:
the content of the file, empty vector if directory
Definition at line 401 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.isDifferent(), moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.unified().
{
    if (file.isDirectory())
      return new ArrayList<String>();
    else
      return FileUtils.loadFromFile(file);
  }
static void moa.test.DiffUtils.main (String[] args) throws Exception [static]
Usage: DiffUtils <unified|side-by-side|brief> <file1> <file2>.
Parameters:
args the files to compare
Exceptions:
Exception if comparison fails
Definition at line 661 of file DiffUtils.java.
References moa.test.DiffUtils.isDifferent(), moa.test.DiffUtils.OPTION_BRIEF, moa.test.DiffUtils.OPTION_SIDEBYSIDE, moa.test.DiffUtils.OPTION_UNIFIED, moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.unified().
{
    if (args.length == 3) {
      File file1 = new File(args[1]);
      if (file1.isDirectory()) {
    System.err.println("File '" + file1 + "' is a directory!");
    return;
      }
      if (!file1.exists()) {
    System.err.println("File '" + file1 + "' does not exist!");
    return;
      }
      File file2 = new File(args[2]);
      if (file2.isDirectory()) {
    System.err.println("File '" + file2 + "' is a directory!");
    return;
      }
      if (!file2.exists()) {
    System.err.println("File '" + file2 + "' does not exist!");
    return;
      }
      if (args[0].equals(OPTION_UNIFIED)) {
    System.out.println(unified(file1, file2));
      }
      else if (args[0].equals(OPTION_SIDEBYSIDE)) {
    System.out.println(sideBySide(file1, file2));
      }
      else if (args[0].equals(OPTION_BRIEF)) {
    if (isDifferent(file1, file2))
      System.out.println("Files " + file1 + " and " + file2 + " differ");
      }
      else {
    System.err.println("Only '" + OPTION_UNIFIED + "', '" + OPTION_SIDEBYSIDE + "' and '" + OPTION_BRIEF + "' are available as options!");
    return;
      }
    }
    else {
      System.err.println("\nUsage: " + DiffUtils.class.getName() + " <" + OPTION_UNIFIED + "|" + OPTION_SIDEBYSIDE + "|" + OPTION_BRIEF + "> <file1> <file2>\n");
      return;
    }
  }
static SideBySideDiff moa.test.DiffUtils.sideBySide (List< String > list1, List< String > list2) [static]
Generates a side-by-side diff for the two lists.
Parameters:
file1 the first text file
file2 the second text file
Returns:
the side-by-side diff
Definition at line 577 of file DiffUtils.java.
References moa.test.DiffUtils.addToList(), moa.test.DiffUtils.INDICATOR_ADDED, moa.test.DiffUtils.INDICATOR_CHANGED, moa.test.DiffUtils.INDICATOR_DELETED, moa.test.DiffUtils.INDICATOR_SAME, moa.test.DiffUtils.SIDEBYSIDE_ENDPOS, moa.test.DiffUtils.SIDEBYSIDE_FIRST, moa.test.DiffUtils.SIDEBYSIDE_INDICATOR, moa.test.DiffUtils.SIDEBYSIDE_SECOND, moa.test.DiffUtils.SIDEBYSIDE_SIZE, and moa.test.DiffUtils.SIDEBYSIDE_STARTPOS.
{
    List[]  result;
    Patch   patch;
    int     from;
    int     to;
    int     sizeDiff;
    result                       = new List[SIDEBYSIDE_SIZE];
    result[SIDEBYSIDE_FIRST]     = new ArrayList();
    result[SIDEBYSIDE_SECOND]    = new ArrayList();
    result[SIDEBYSIDE_INDICATOR] = new ArrayList();
    result[SIDEBYSIDE_STARTPOS]  = new ArrayList();
    result[SIDEBYSIDE_ENDPOS]    = new ArrayList();
    patch                        = difflib.DiffUtils.diff(list1, list2);
    // the same?
    if (patch.getDeltas().size() == 0) {
      result[SIDEBYSIDE_FIRST].addAll(list1);
      result[SIDEBYSIDE_SECOND].addAll(list2);
      addToList(0, list1.size() - 1, INDICATOR_SAME, result[SIDEBYSIDE_INDICATOR]);
      return new SideBySideDiff(result);
    }
    to = 0;
    for (Delta delta: patch.getDeltas()) {
      from = to;
      // common content
      to = delta.getOriginal().getPosition() - 1;
      addToList(from, to, list1,          result[SIDEBYSIDE_FIRST]);
      addToList(from, to, list1,          result[SIDEBYSIDE_SECOND]);
      addToList(from, to, INDICATOR_SAME, result[SIDEBYSIDE_INDICATOR]);
      // start pos of delta
      result[SIDEBYSIDE_STARTPOS].add(result[SIDEBYSIDE_FIRST].size());
      if (delta instanceof InsertDelta) {
    // added content
    addToList(0, delta.getRevised().size() - 1, new Filler(), result[SIDEBYSIDE_FIRST]);
    result[SIDEBYSIDE_SECOND].addAll(delta.getRevised().getLines());
    addToList(0, delta.getRevised().size() - 1, INDICATOR_ADDED, result[SIDEBYSIDE_INDICATOR]);
    to = delta.getOriginal().getPosition() + delta.getOriginal().size();
      }
      else if (delta instanceof DeleteDelta) {
    // deleted content
    result[SIDEBYSIDE_FIRST].addAll(delta.getOriginal().getLines());
    addToList(0, delta.getOriginal().size() - 1, new Filler(), result[SIDEBYSIDE_SECOND]);
    addToList(0, delta.getOriginal().size() - 1, INDICATOR_DELETED, result[SIDEBYSIDE_INDICATOR]);
    to = delta.getOriginal().getPosition() + delta.getOriginal().size();
      }
      else {
    // changed content
    result[SIDEBYSIDE_FIRST].addAll(delta.getOriginal().getLines());
    result[SIDEBYSIDE_SECOND].addAll(delta.getRevised().getLines());
    addToList(1, Math.max(delta.getOriginal().size(), delta.getRevised().size()), INDICATOR_CHANGED, result[SIDEBYSIDE_INDICATOR]);
    // filler necessary?
    sizeDiff = delta.getRevised().size() - delta.getOriginal().size();
    if (sizeDiff > 0)
      addToList(1, sizeDiff, new Filler(), result[SIDEBYSIDE_FIRST]);
    if (sizeDiff < 0)
      addToList(1, -sizeDiff, new Filler(), result[SIDEBYSIDE_SECOND]);
    to = delta.getOriginal().getPosition() + delta.getOriginal().size();
      }
      // end pos of delta
      result[SIDEBYSIDE_ENDPOS].add(result[SIDEBYSIDE_FIRST].size());
    }
    // trailing common content?
    if (to < list1.size()) {
      addToList(to, list1.size() - 1, list1,          result[SIDEBYSIDE_FIRST]);
      addToList(to, list1.size() - 1, list1,          result[SIDEBYSIDE_SECOND]);
      addToList(to, list1.size() - 1, INDICATOR_SAME, result[SIDEBYSIDE_INDICATOR]);
    }
    return new SideBySideDiff(result);
  }
static SideBySideDiff moa.test.DiffUtils.sideBySide (String[] list1, String[] list2) [static]
Generates a side-by-side diff for the two lists.
Parameters:
file1 the first list
file2 the second list
Returns:
the side-by-side diff
Definition at line 541 of file DiffUtils.java.
References moa.test.DiffUtils.sideBySide().
{
    return sideBySide(Arrays.asList(list1), Arrays.asList(list2));
  }
static SideBySideDiff moa.test.DiffUtils.sideBySide (File file1, File file2) [static]
Generates a side-by-side diff for the two files.
Parameters:
file1 the first text file
file2 the second text file
Returns:
the side-by-side diff
Definition at line 530 of file DiffUtils.java.
References moa.test.DiffUtils.loadFromFile().
Referenced by moa.test.DiffUtils.main(), and moa.test.DiffUtils.sideBySide().
{
    return sideBySide(loadFromFile(file1), loadFromFile(file2));
  }
static String moa.test.DiffUtils.toString (String ind, List lines) [static, protected]
Assembles the lines into a string.
Parameters:
ind the indicator string
lines the underlying lines
Returns:
the generated string
Definition at line 454 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.unified().
{
    StringBuilder   result;
    result = new StringBuilder();
    for (Object line: lines)
      result.append(ind + " " + line + "\n");
    return result.toString();
  }
static String moa.test.DiffUtils.unified (List< String > list1, List< String > list2) [static]
Generates a unified diff for the two lists.
Parameters:
file1 the first list
file2 the second list
Returns:
the unified diff
Definition at line 496 of file DiffUtils.java.
References moa.test.DiffUtils.createRange(), moa.test.DiffUtils.DESTINATION, moa.test.DiffUtils.SEPARATOR_UNIFIED, moa.test.DiffUtils.SOURCE, and moa.test.DiffUtils.toString().
{
    StringBuilder   result;
    Patch       patch;
    patch  = difflib.DiffUtils.diff(list1, list2);
    result = new StringBuilder();
    for (Delta delta: patch.getDeltas()) {
      if (delta instanceof InsertDelta) {
    result.append(delta.getOriginal().getPosition() + "a" + createRange(delta.getRevised()) + "\n");
    result.append(toString(DESTINATION, delta.getRevised().getLines()));
      }
      else if (delta instanceof DeleteDelta) {
    result.append(createRange(delta.getOriginal()) + "d" + delta.getRevised().getPosition() + "\n");
    result.append(toString(SOURCE, delta.getOriginal().getLines()));
      }
      else {
    result.append(createRange(delta.getOriginal()) + "c");
    result.append(createRange(delta.getRevised()) + "\n");
    result.append(toString(SOURCE, delta.getOriginal().getLines()));
    result.append(SEPARATOR_UNIFIED + "\n");
    result.append(toString(DESTINATION, delta.getRevised().getLines()));
      }
    }
    return result.toString();
  }
static String moa.test.DiffUtils.unified (File file1, File file2) [static]
Generates a unified diff for the two files.
Parameters:
file1 the first text file
file2 the second text file
Returns:
the unified diff
Definition at line 472 of file DiffUtils.java.
References moa.test.DiffUtils.loadFromFile().
Referenced by moa.test.DiffUtils.main().
{
    return unified(loadFromFile(file1), loadFromFile(file2));
  }
Member Data Documentation
final String moa.test.DiffUtils.DESTINATION = ">" [static]
the destination indicator.
Definition at line 58 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.unified().
final char moa.test.DiffUtils.INDICATOR_ADDED = 'a' [static]
the indicator for "added".
Definition at line 46 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide().
final char moa.test.DiffUtils.INDICATOR_CHANGED = 'c' [static]
the indicator for "changed".
Definition at line 43 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide().
final char moa.test.DiffUtils.INDICATOR_DELETED = 'd' [static]
the indicator for "deleted".
Definition at line 49 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide().
final char moa.test.DiffUtils.INDICATOR_SAME = ' ' [static]
the indicator for "same".
Definition at line 52 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide().
final String moa.test.DiffUtils.OPTION_BRIEF = "brief" [static]
the brief option.
Definition at line 73 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.main().
final String moa.test.DiffUtils.OPTION_SIDEBYSIDE = "side-by-side" [static]
the side-by-side option.
Definition at line 70 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.main().
final String moa.test.DiffUtils.OPTION_UNIFIED = "unified" [static]
the unified option.
Definition at line 67 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.main().
final String moa.test.DiffUtils.SEPARATOR_SIDEBYSIDE = " | " [static]
the separator for the side-by-side output on the command-line.
Definition at line 64 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.toString().
final String moa.test.DiffUtils.SEPARATOR_UNIFIED = "---" [static]
the separator for the unified output.
Definition at line 61 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.unified().
final int moa.test.DiffUtils.SIDEBYSIDE_ENDPOS = 4 [static]
the index for the list of end positions of deltas in side-by-side diff.
Definition at line 91 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.deltaToLine(), moa.test.DiffUtils.SideBySideDiff.lineToDelta(), and moa.test.DiffUtils.sideBySide().
final int moa.test.DiffUtils.SIDEBYSIDE_FIRST = 0 [static]
the index for the first file in side-by-side diff.
Definition at line 79 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.getLeft(), moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.SideBySideDiff.toString().
final int moa.test.DiffUtils.SIDEBYSIDE_INDICATOR = 2 [static]
the index for the indicator list in side-by-side diff.
Definition at line 85 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.getIndicator(), moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.SideBySideDiff.toString().
final int moa.test.DiffUtils.SIDEBYSIDE_SECOND = 1 [static]
the index for the second file in side-by-side diff.
Definition at line 82 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.getRight(), moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.SideBySideDiff.toString().
final int moa.test.DiffUtils.SIDEBYSIDE_SIZE = 5 [static]
the number of array elements in side-by-side diff.
Definition at line 76 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.sideBySide(), and moa.test.DiffUtils.SideBySideDiff.SideBySideDiff().
final int moa.test.DiffUtils.SIDEBYSIDE_STARTPOS = 3 [static]
the index for the list of start positions of deltas in side-by-side diff.
Definition at line 88 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.SideBySideDiff.deltaToLine(), moa.test.DiffUtils.SideBySideDiff.differences(), moa.test.DiffUtils.SideBySideDiff.getNextDelta(), moa.test.DiffUtils.SideBySideDiff.getStartPos(), moa.test.DiffUtils.SideBySideDiff.hasDifferences(), moa.test.DiffUtils.SideBySideDiff.lineToDelta(), and moa.test.DiffUtils.sideBySide().
final String moa.test.DiffUtils.SOURCE = "<" [static]
the source indicator.
Definition at line 55 of file DiffUtils.java.
Referenced by moa.test.DiffUtils.unified().
The documentation for this class was generated from the following file:
test/java/moa/test/DiffUtils.java