MOA: moa.classifiers.trees.HoeffdingTree.ActiveLearningNode Class Reference
moa.classifiers.trees.HoeffdingTree.ActiveLearningNode Class Reference
Public Member Functions
ActiveLearningNode (double[] initialClassObservations)
int calcByteSize ()
void learnFromInstance (Instance inst, HoeffdingTree ht)
double getWeightSeen ()
double getWeightSeenAtLastSplitEvaluation ()
void setWeightSeenAtLastSplitEvaluation (double weight)
AttributeSplitSuggestion[] getBestSplitSuggestions (SplitCriterion criterion, HoeffdingTree ht)
void disableAttribute (int attIndex)
Protected Attributes
double weightSeenAtLastSplitEvaluation
AutoExpandVector
< AttributeClassObserver > attributeObservers = new AutoExpandVector<AttributeClassObserver>()
boolean isInitialized
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 384 of file HoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.ActiveLearningNode (double[] initialClassObservations)
Definition at line 394 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.isInitialized, and moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
{
            super(initialClassObservations);
            this.weightSeenAtLastSplitEvaluation = getWeightSeen();
            this.isInitialized = false;
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.HoeffdingTree.Node.
Definition at line 401 of file HoeffdingTree.java.
{
            return super.calcByteSize()
                    + (int) (SizeOf.fullSizeOf(this.attributeObservers));
        }
void moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.disableAttribute (int attIndex)
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, and moa.classifiers.trees.HoeffdingTree.LearningNodeNB.
Definition at line 461 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.attemptToSplit(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
            this.attributeObservers.set(attIndex,
                    new NullAttributeClassObserver());
        }
AttributeSplitSuggestion [] moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions (SplitCriterion criterion, HoeffdingTree ht)
Definition at line 437 of file HoeffdingTree.java.
References moa.core.DoubleVector.getArrayCopy(), moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit(), moa.options.FlagOption.isSet, moa.classifiers.trees.HoeffdingTree.noPrePruneOption, and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingTree.attemptToSplit(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
            List<AttributeSplitSuggestion> bestSuggestions = new LinkedList<AttributeSplitSuggestion>();
            double[] preSplitDist = this.observedClassDistribution.getArrayCopy();
            if (!ht.noPrePruneOption.isSet()) {
                // add null split as an option
                bestSuggestions.add(new AttributeSplitSuggestion(null,
                        new double[0][], criterion.getMeritOfSplit(
                        preSplitDist,
                        new double[][]{preSplitDist})));
            }
            for (int i = 0; i < this.attributeObservers.size(); i++) {
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs != null) {
                    AttributeSplitSuggestion bestSuggestion = obs.getBestEvaluatedSplitSuggestion(criterion,
                            preSplitDist, i, ht.binarySplitsOption.isSet());
                    if (bestSuggestion != null) {
                        bestSuggestions.add(bestSuggestion);
                    }
                }
            }
            return bestSuggestions.toArray(new AttributeSplitSuggestion[bestSuggestions.size()]);
        }
double moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen ()
Reimplemented in moa.classifiers.rules.core.RuleActiveRegressionNode.
Definition at line 425 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes(), moa.classifiers.rules.core.RuleActiveLearningNode.getInstancesSeen(), moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            return this.observedClassDistribution.sumOfValues();
        }
double moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation ()
Definition at line 429 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
Referenced by moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            return this.weightSeenAtLastSplitEvaluation;
        }
void moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance (Instance inst, HoeffdingTree ht) [virtual]
Implements moa.classifiers.trees.HoeffdingTree.LearningNode.
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.rules.core.RuleActiveLearningNode, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Definition at line 407 of file HoeffdingTree.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.attributeObservers, moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.isInitialized, moa.classifiers.AbstractClassifier.modelAttIndexToInstanceAttIndex(), moa.classifiers.trees.HoeffdingTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingTree.newNumericClassObserver(), moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass(), and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
{
            if (this.isInitialized == false) {
                this.attributeObservers = new AutoExpandVector<AttributeClassObserver>(inst.numAttributes());
                this.isInitialized = true;
            }
            this.observedClassDistribution.addToValue((int) inst.classValue(),
                    inst.weight());
            for (int i = 0; i < inst.numAttributes() - 1; i++) {
                int instAttIndex = modelAttIndexToInstanceAttIndex(i, inst);
                AttributeClassObserver obs = this.attributeObservers.get(i);
                if (obs == null) {
                    obs = inst.attribute(instAttIndex).isNominal() ? ht.newNominalClassObserver() : ht.newNumericClassObserver();
                    this.attributeObservers.set(i, obs);
                }
                obs.observeAttributeClass(inst.value(instAttIndex), (int) inst.classValue(), inst.weight());
            }
        }
void moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation (double weight)
Definition at line 433 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation.
Referenced by moa.classifiers.trees.HoeffdingTree.trainOnInstanceImpl(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            this.weightSeenAtLastSplitEvaluation = weight;
        }
Member Data Documentation
AutoExpandVector<AttributeClassObserver> moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.attributeObservers = new AutoExpandVector<AttributeClassObserver>() [protected]
Definition at line 390 of file HoeffdingTree.java.
Referenced by moa.classifiers.rules.core.RuleActiveLearningNode.getAttributeObservers(), moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), and moa.classifiers.rules.core.RuleActiveRegressionNode.learnFromInstance().
boolean moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.isInitialized [protected]
Definition at line 392 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.ActiveLearningNode(), and moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance().
final long moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingTree.LearningNode.
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.rules.core.RuleActiveLearningNode, moa.classifiers.rules.core.RuleActiveRegressionNode, moa.classifiers.trees.HoeffdingTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Definition at line 386 of file HoeffdingTree.java.
double moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.weightSeenAtLastSplitEvaluation [protected]
Definition at line 388 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.ActiveLearningNode(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeenAtLastSplitEvaluation(), and moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.setWeightSeenAtLastSplitEvaluation().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingTree.java