MOA: moa.clusterers.outliers.AnyOut.AnyOut Class Reference
moa.clusterers.outliers.AnyOut.AnyOut Class Reference
Public Member Functions
AnyOut ()
void resetLearningImpl ()
String getPurposeString ()
Gets the purpose of this object.
Options getOptions ()
Gets the options of this object.
String getObjectInfo (Object o)
String getStatistics ()
Protected Member Functions
void Init ()
void ProcessNewStreamObj (Instance i)
boolean IsNodeIdInWin (long id)
Private Member Functions
int getWindowEnd ()
int getWindowStart ()
Private Attributes
final int FIRST_OBJ_ID = 0
final double minDepth = 0.5
final double maxDepth = 0.9
AnyOutCore anyout
int idCounter
int windowSize
ArrayList< DataObject > objects
DataSet trainingSet
int trainingCount
int trainingSetSize
int truePositive
int falsePositive
int totalOutliers
int outlierClass
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 31 of file AnyOut.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.AnyOut.AnyOut.AnyOut ()
Definition at line 48 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.anyout.
                    {
        anyout = new AnyOutCore();
    }
Member Function Documentation
String moa.clusterers.outliers.AnyOut.AnyOut.getObjectInfo (Object o)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 178 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.anyout, moa.clusterers.outliers.AnyOut.AnyOutCore.getConfidence(), moa.clusterers.outliers.AnyOut.util.DataObject.getFeatures(), moa.clusterers.outliers.AnyOut.util.DataObject.getId(), and moa.clusterers.outliers.AnyOut.AnyOutCore.getOutlierScore().
{
        DataObject obj = (DataObject) o;
        double[] features = obj.getFeatures();
        int id = obj.getId();
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        sb.append("<table>");
        sb.append("<tr><td><b>ID:</b></td><td>" + id + "</td></tr>");
        sb.append("<tr><td><b>X, Y:</b></td><td>" + String.format("%.4f", features[0]) + ", " + String.format("%.4f", features[1]) + "</td></tr>");
        sb.append("<tr><td><b>Oscore:</b></td><td>" + String.format("%.4f", anyout.getOutlierScore(id)) + "</td></tr>");
        sb.append("<tr><td><b>Conf:</b></td><td>" + String.format("%.4f", anyout.getConfidence(id)) + "</td></tr>");
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
Options moa.clusterers.outliers.AnyOut.AnyOut.getOptions ()
Gets the options of this object.
Returns:
the options of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 154 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.anyout, and moa.options.AbstractOptionHandler.getOptions().
{
        return anyout.getOptions();
    }
String moa.clusterers.outliers.AnyOut.AnyOut.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 149 of file AnyOut.java.
{
        return "Anyout: Anytime Outlier Detector based on ClusTree";
    }
String moa.clusterers.outliers.AnyOut.AnyOut.getStatistics ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 196 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.falsePositive, moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, moa.clusterers.outliers.AnyOut.AnyOut.totalOutliers, and moa.clusterers.outliers.AnyOut.AnyOut.truePositive.
{
        StringBuilder sb = new StringBuilder();
        int sum = truePositive + falsePositive;
        sb.append("Statistics:\n\n");
        sb.append(String.format("  Outliers found: %d (%.1f%%)\n", sum, (100 * sum) / (double)totalOutliers));
        sb.append(String.format("  True positive found: %d (%.1f%%)\n", truePositive, (100 * truePositive) / (double)totalOutliers));
        sb.append(String.format("  False positive found: %d (%.1f%%)\n", falsePositive, (100 * falsePositive) / (double)totalOutliers));
        sb.append("\n");
        sb.append("  Max memory usage: " + iMaxMemUsage + " MB\n");
        sb.append("  Total process time: " + String.format("%.2f ms", nTotalRunTime / 1000.0) + "\n");
        return sb.toString();
    }
int moa.clusterers.outliers.AnyOut.AnyOut.getWindowEnd () [private]
Definition at line 158 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.idCounter.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getWindowStart(), and moa.clusterers.outliers.AnyOut.AnyOut.IsNodeIdInWin().
{
        return idCounter - 1;
    }
int moa.clusterers.outliers.AnyOut.AnyOut.getWindowStart () [private]
Definition at line 162 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.FIRST_OBJ_ID, moa.clusterers.outliers.AnyOut.AnyOut.getWindowEnd(), and moa.clusterers.outliers.AnyOut.AnyOut.windowSize.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.IsNodeIdInWin().
{
        int x = getWindowEnd() - windowSize + 1;
        if (x < FIRST_OBJ_ID)
            x = FIRST_OBJ_ID;
        return x;
    }
void moa.clusterers.outliers.AnyOut.AnyOut.Init () [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 59 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.anyout, moa.clusterers.outliers.AnyOut.AnyOut.falsePositive, moa.clusterers.outliers.AnyOut.AnyOut.FIRST_OBJ_ID, moa.options.IntOption.getValue(), moa.clusterers.clustree.ClusTree.horizonOption, moa.clusterers.outliers.AnyOut.AnyOut.idCounter, moa.clusterers.outliers.AnyOut.AnyOut.objects, moa.clusterers.outliers.AnyOut.AnyOut.outlierClass, moa.clusterers.outliers.AnyOut.AnyOut.totalOutliers, moa.clusterers.outliers.AnyOut.AnyOut.trainingCount, moa.clusterers.outliers.AnyOut.AnyOut.trainingSetSize, moa.clusterers.outliers.AnyOut.AnyOutCore.trainingSetSizeOption, moa.clusterers.outliers.AnyOut.AnyOut.truePositive, and moa.clusterers.outliers.AnyOut.AnyOut.windowSize.
{
        trainingCount = 0;
        truePositive = 0;
        falsePositive = 0;
        totalOutliers = 0;
        outlierClass = -1;
        trainingSetSize = anyout.trainingSetSizeOption.getValue();
        idCounter = FIRST_OBJ_ID;
        windowSize = anyout.horizonOption.getValue();
        objects = new ArrayList<DataObject>();
        super.Init();
    }
boolean moa.clusterers.outliers.AnyOut.AnyOut.IsNodeIdInWin (long id) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 170 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.getWindowEnd(), and moa.clusterers.outliers.AnyOut.AnyOut.getWindowStart().
{
        if ((getWindowStart() <= id) && (id <= getWindowEnd()) )
            return true;
        else
            return false;
    }
void moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj (Instance i) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 73 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.AnyOut.AnyOut.anyout, moa.clusterers.outliers.AnyOut.util.DataSet.clear(), moa.clusterers.outliers.AnyOut.AnyOut.falsePositive, moa.clusterers.outliers.AnyOut.util.DataObject.getClassLabel(), moa.clusterers.outliers.AnyOut.util.DataObject.getFeatures(), moa.clusterers.outliers.AnyOut.util.DataObject.getId(), moa.clusterers.outliers.AnyOut.util.DataObject.getInstance(), moa.clusterers.outliers.AnyOut.AnyOut.idCounter, moa.clusterers.outliers.AnyOut.AnyOutCore.improveObjectOnce(), moa.clusterers.outliers.AnyOut.AnyOutCore.initObject(), moa.clusterers.outliers.AnyOut.AnyOutCore.isOutlier(), moa.clusterers.outliers.AnyOut.AnyOutCore.learnObject(), moa.clusterers.outliers.AnyOut.AnyOut.maxDepth, moa.clusterers.outliers.AnyOut.AnyOut.minDepth, moa.clusterers.outliers.AnyOut.AnyOutCore.moreImprovementsPossible(), moa.clusterers.outliers.AnyOut.AnyOut.objects, moa.clusterers.outliers.AnyOut.AnyOut.outlierClass, moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), moa.clusterers.outliers.AnyOut.AnyOutCore.removeObject(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveOutlier(), moa.clusterers.outliers.AnyOut.AnyOut.totalOutliers, moa.clusterers.outliers.AnyOut.AnyOutCore.train(), moa.clusterers.outliers.AnyOut.AnyOut.trainingCount, moa.clusterers.outliers.AnyOut.AnyOut.trainingSet, moa.clusterers.outliers.AnyOut.AnyOut.trainingSetSize, moa.clusterers.outliers.AnyOut.AnyOut.truePositive, and moa.clusterers.outliers.AnyOut.AnyOut.windowSize.
{
        if (trainingSetSize >= trainingCount) {
            if (trainingSet == null) {
                trainingSet = new DataSet(i.numAttributes()-1);
            }
            //fill training set
            DataObject o = new DataObject(idCounter++, i);
            trainingSet.addObject(o);
            trainingCount++;
        } else {
            // Train once.
            if (trainingSetSize != -1) {
                anyout.train(trainingSet);
                trainingSet.clear();
                trainingSetSize = -1;
                outlierClass = i.classAttribute().numValues() - 1;
            }
            // Create DataObject from instance.
            DataObject o = new DataObject(idCounter++, i);
            objects.add(o);
            // Count ground truth.
            if (o.getClassLabel() == outlierClass) {
                totalOutliers += 1;
            }
            // Update window objects.
            if (objects.size() > windowSize) {
                DataObject obj = objects.get(0);
                objects.remove(0);
                anyout.removeObject(obj.getId());
                RemoveExpiredOutlier(new Outlier(obj.getInstance(), obj.getId(), obj));
            }
            // Calculate scores for the object.
            anyout.initObject(o.getId(), o.getFeatures());
            // Simulate anyout characteristics.
            double depth = Math.random();
            if (depth < minDepth) {
                depth = minDepth;
            } else if (depth > maxDepth) {
                depth = maxDepth;
            }
            while (anyout.moreImprovementsPossible(o.getId(), depth)){
                anyout.improveObjectOnce(o.getId());
            }
            // Learn object into ClusTree.
            anyout.learnObject(o.getFeatures());
            // Evaluation of the window objects.
            for (DataObject obj : objects){
                int id = obj.getId();
                if(anyout.isOutlier(id)) {
                    if(obj.isOutiler() == false) { // not already outlier.
                        // Statistics gathering.
                        if(obj.getClassLabel() == outlierClass) {
                            truePositive += 1;
                        }  else {
                            falsePositive += 1;
                        }
                        AddOutlier(new Outlier(obj.getInstance(), id, obj));
                        obj.setOutiler(true);
                    }
                } else {
                    RemoveOutlier(new Outlier(obj.getInstance(), id, obj));
                    obj.setOutiler(false);
                }
            }
        }
    }
void moa.clusterers.outliers.AnyOut.AnyOut.resetLearningImpl () [virtual]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 53 of file AnyOut.java.
References moa.clusterers.outliers.AnyOut.AnyOut.anyout, and moa.clusterers.outliers.AnyOut.AnyOutCore.resetLearning().
{
        anyout.resetLearning();
        super.resetLearningImpl();
    }
Member Data Documentation
AnyOutCore moa.clusterers.outliers.AnyOut.AnyOut.anyout [private]
Definition at line 38 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.AnyOut(), moa.clusterers.outliers.AnyOut.AnyOut.getObjectInfo(), moa.clusterers.outliers.AnyOut.AnyOut.getOptions(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj(), and moa.clusterers.outliers.AnyOut.AnyOut.resetLearningImpl().
int moa.clusterers.outliers.AnyOut.AnyOut.falsePositive [private]
Definition at line 45 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getStatistics(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
final int moa.clusterers.outliers.AnyOut.AnyOut.FIRST_OBJ_ID = 0 [private]
Definition at line 34 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getWindowStart(), and moa.clusterers.outliers.AnyOut.AnyOut.Init().
int moa.clusterers.outliers.AnyOut.AnyOut.idCounter [private]
Definition at line 39 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getWindowEnd(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
final double moa.clusterers.outliers.AnyOut.AnyOut.maxDepth = 0.9 [private]
Definition at line 36 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
final double moa.clusterers.outliers.AnyOut.AnyOut.minDepth = 0.5 [private]
Definition at line 35 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
ArrayList<DataObject> moa.clusterers.outliers.AnyOut.AnyOut.objects [private]
Definition at line 41 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
int moa.clusterers.outliers.AnyOut.AnyOut.outlierClass [private]
Definition at line 46 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
final long moa.clusterers.outliers.AnyOut.AnyOut.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 32 of file AnyOut.java.
int moa.clusterers.outliers.AnyOut.AnyOut.totalOutliers [private]
Definition at line 45 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getStatistics(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
int moa.clusterers.outliers.AnyOut.AnyOut.trainingCount [private]
Definition at line 43 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
DataSet moa.clusterers.outliers.AnyOut.AnyOut.trainingSet [private]
Definition at line 42 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
int moa.clusterers.outliers.AnyOut.AnyOut.trainingSetSize [private]
Definition at line 44 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
int moa.clusterers.outliers.AnyOut.AnyOut.truePositive [private]
Definition at line 45 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getStatistics(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
int moa.clusterers.outliers.AnyOut.AnyOut.windowSize [private]
Definition at line 40 of file AnyOut.java.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getWindowStart(), moa.clusterers.outliers.AnyOut.AnyOut.Init(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AnyOut/AnyOut.java