MOA: moa.clusterers.WekaClusteringAlgorithm Class Reference
moa.clusterers.WekaClusteringAlgorithm Class Reference
Public Member Functions
WekaClusteringAlgorithm ()
void resetLearningImpl ()
void trainOnInstanceImpl (Instance inst)
Clustering getClusteringResult ()
Instances getDataset (int numdim, int numclass)
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
double[] getVotesForInstance (Instance inst)
boolean keepClassLabel ()
String getPurposeString ()
Gets the purpose of this object.
Public Attributes
IntOption horizonOption
MultiChoiceOption wekaAlgorithmOption
StringOption parameterOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Private Member Functions
Class<?>[] findWekaClustererClasses ()
Private Attributes
Class<?>[] clustererClasses
Instances instances
weka.clusterers.AbstractClusterer clusterer
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 40 of file WekaClusteringAlgorithm.java.
Constructor & Destructor Documentation
moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm ()
Definition at line 57 of file WekaClusteringAlgorithm.java.
References moa.clusterers.WekaClusteringAlgorithm.clustererClasses, moa.clusterers.WekaClusteringAlgorithm.findWekaClustererClasses(), moa.clusterers.WekaClusteringAlgorithm.horizonOption, moa.clusterers.WekaClusteringAlgorithm.parameterOption, and moa.clusterers.WekaClusteringAlgorithm.wekaAlgorithmOption.
{
        clustererClasses = findWekaClustererClasses();
        String[] optionLabels = new String[clustererClasses.length];
        String[] optionDescriptions = new String[clustererClasses.length];
        for (int i = 0; i < clustererClasses.length; i++) {
            optionLabels[i] = clustererClasses[i].getSimpleName();
            optionDescriptions[i] = clustererClasses[i].getName();
//          We do have the parameter option info, but not really a place to show it somewhere
/*
            //System.out.println(clustererClasses[i].getSimpleName());
            for (Class c : clustererClasses[i].getInterfaces()) {
                    if (c.equals(weka.core.OptionHandler.class)) {
                        try {
                            Enumeration options = ((weka.core.OptionHandler)clustererClasses[i].newInstance()).listOptions();
                            while(options.hasMoreElements()){
                                weka.core.Option o = (weka.core.Option)options.nextElement();
                                System.out.print(o.synopsis()+" ");
                            }
                        } catch (InstantiationException e) {
                            e.printStackTrace();
                        } catch (IllegalAccessException e) {
                            e.printStackTrace();
                        }
                    }
                }
*/
        }
        if(clustererClasses!=null && clustererClasses.length > 0){
            wekaAlgorithmOption = new MultiChoiceOption("clusterer", 'w',
                    "Weka cluster algorithm to use.",
                    optionLabels, optionDescriptions, 6);
        }
        else{
            horizonOption = null;
            parameterOption = null;
        }
    }
Member Function Documentation
Class<?> [] moa.clusterers.WekaClusteringAlgorithm.findWekaClustererClasses () [private]
Definition at line 179 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm().
{
        AutoExpandVector<Class<?>> finalClasses = new AutoExpandVector<Class<?>>();
        Class<?>[] classesFound = AutoClassDiscovery.findClassesOfType("weka.clusterers",
                weka.clusterers.AbstractClusterer.class);
        for (Class<?> foundClass : classesFound) {
                finalClasses.add(foundClass);
        }
        return finalClasses.toArray(new Class<?>[finalClasses.size()]);
}
Clustering moa.clusterers.WekaClusteringAlgorithm.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 127 of file WekaClusteringAlgorithm.java.
References moa.clusterers.WekaClusteringAlgorithm.clusterer, moa.clusterers.AbstractClusterer.clustering, moa.clusterers.WekaClusteringAlgorithm.getDataset(), and moa.clusterers.WekaClusteringAlgorithm.instances.
{
        Clustering clustering = null;
        try {
            clusterer.buildClusterer(instances);
            int numClusters = clusterer.numberOfClusters();
            Instances dataset = getDataset(instances.numAttributes(), numClusters);
            Instances newInstances = new Instances(dataset);
            for (int i = 0; i < instances.numInstances(); i++) {
                Instance inst = instances.get(i);
                int cnum = clusterer.clusterInstance(inst);
                Instance newInst = new DenseInstance(inst);
                newInst.insertAttributeAt(inst.numAttributes());
                newInst.setDataset(dataset);
                newInst.setClassValue(cnum);
                newInstances.add(newInst);
            }
            clustering = new Clustering(newInstances);
        } catch (Exception e) {
            e.printStackTrace();
        }
        instances = null;
        return clustering;
    }
Instances moa.clusterers.WekaClusteringAlgorithm.getDataset (int numdim, int numclass)
Definition at line 157 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.getClusteringResult(), and moa.clusterers.WekaClusteringAlgorithm.trainOnInstanceImpl().
{
        FastVector attributes = new FastVector();
        for (int i = 0; i < numdim; i++) {
            attributes.addElement(new Attribute("att" + (i + 1)));
        }
        if(numclass > 0){
            FastVector classLabels = new FastVector();
            for (int i = 0; i < numclass; i++) {
                classLabels.addElement("class" + (i + 1));
            }
            attributes.addElement(new Attribute("class", classLabels));
        }
        Instances myDataset = new Instances("horizion", attributes, 0);
        if(numclass > 0){
            myDataset.setClassIndex(myDataset.numAttributes() - 1);
        }
        return myDataset;
    }
void moa.clusterers.WekaClusteringAlgorithm.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 196 of file WekaClusteringAlgorithm.java.
{
    }
Measurement [] moa.clusterers.WekaClusteringAlgorithm.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 191 of file WekaClusteringAlgorithm.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.clusterers.WekaClusteringAlgorithm.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 213 of file WekaClusteringAlgorithm.java.
References moa.clusterers.WekaClusteringAlgorithm.clustererClasses.
{
        String purpose = "MOA Clusterer: " + getClass().getCanonicalName();
        if(clustererClasses==null || clustererClasses.length == 0)
            purpose+="\nPlease add weka.jar to the classpath to use Weka clustering algorithms.";
        return purpose;
    }
double [] moa.clusterers.WekaClusteringAlgorithm.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 203 of file WekaClusteringAlgorithm.java.
{
        return null;
    }
boolean moa.clusterers.WekaClusteringAlgorithm.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 199 of file WekaClusteringAlgorithm.java.
{
        return false;
    }
boolean moa.clusterers.WekaClusteringAlgorithm.keepClassLabel ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 208 of file WekaClusteringAlgorithm.java.
{
        return false;
    }
void moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 102 of file WekaClusteringAlgorithm.java.
References moa.clusterers.WekaClusteringAlgorithm.clusterer, moa.clusterers.WekaClusteringAlgorithm.clustererClasses, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.StringOption.getValue(), moa.clusterers.WekaClusteringAlgorithm.instances, moa.options.AbstractOptionHandler.options, moa.clusterers.WekaClusteringAlgorithm.parameterOption, and moa.clusterers.WekaClusteringAlgorithm.wekaAlgorithmOption.
{
        try {
            instances = null;
            String clistring = clustererClasses[wekaAlgorithmOption.getChosenIndex()].getName();
            clusterer = (weka.clusterers.AbstractClusterer) ClassOption.cliStringToObject(clistring, weka.clusterers.Clusterer.class, null);
            String rawOptions = parameterOption.getValue();
            String[] options = rawOptions.split(" ");
            if(clusterer instanceof weka.core.OptionHandler){
                ((weka.core.OptionHandler)clusterer).setOptions(options);
                Utils.checkForRemainingOptions(options);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
void moa.clusterers.WekaClusteringAlgorithm.trainOnInstanceImpl (Instance inst) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 120 of file WekaClusteringAlgorithm.java.
References moa.clusterers.WekaClusteringAlgorithm.getDataset(), and moa.clusterers.WekaClusteringAlgorithm.instances.
{
        if(instances == null){
            instances =  getDataset(inst.numAttributes(), 0);
        }
        instances.add(inst);
    }
Member Data Documentation
weka.clusterers.AbstractClusterer moa.clusterers.WekaClusteringAlgorithm.clusterer [private]
Definition at line 55 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.getClusteringResult(), and moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl().
Class<?> [] moa.clusterers.WekaClusteringAlgorithm.clustererClasses [private]
Definition at line 53 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.getPurposeString(), moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), and moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm().
IntOption moa.clusterers.WekaClusteringAlgorithm.horizonOption
Initial value:
 new IntOption("horizon",
            'h', "Range of the window.", 1000)
Definition at line 44 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm().
Instances moa.clusterers.WekaClusteringAlgorithm.instances [private]
Definition at line 54 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.getClusteringResult(), moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), and moa.clusterers.WekaClusteringAlgorithm.trainOnInstanceImpl().
StringOption moa.clusterers.WekaClusteringAlgorithm.parameterOption
Initial value:
 new StringOption("parameter", 'p',
            "Parameters that will be passed to the weka algorithm. (e.g. '-N 5' for using SimpleKmeans with 5 clusters)", "-N 5 -S 8")
Definition at line 49 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), and moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm().
final long moa.clusterers.WekaClusteringAlgorithm.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 42 of file WekaClusteringAlgorithm.java.
MultiChoiceOption moa.clusterers.WekaClusteringAlgorithm.wekaAlgorithmOption
Definition at line 47 of file WekaClusteringAlgorithm.java.
Referenced by moa.clusterers.WekaClusteringAlgorithm.resetLearningImpl(), and moa.clusterers.WekaClusteringAlgorithm.WekaClusteringAlgorithm().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/WekaClusteringAlgorithm.java