MOA: moa.classifiers.rules.AMRulesRegressor Class Reference
moa.classifiers.rules.AMRulesRegressor Class Reference
Public Member Functions
RuleActiveLearningNode newRuleActiveLearningNode (Builder builder)
RuleActiveLearningNode newRuleActiveLearningNode (double[] initialClassObservations)
void getModelDescription (StringBuilder out, int indent)
print GUI learn model
void resetLearningImpl ()
This method initializes and resets the algorithm.
boolean isRandomizable ()
description of the Methods used.
ErrorWeightedVote newErrorWeightedVote ()
Public Attributes
FlagOption constantLearningRatioDecayOption
FloatOption learningRatioOption
MultiChoiceOption predictionFunctionOption
ClassOption votingTypeOption
Protected Member Functions
Rule newRule (int ID, RuleActiveLearningNode node, double[] statistics)
Rule.Builder() to build an object with the parameters.
Private Member Functions
Rule newRule (int ID)
Static Private Attributes
static final long serialVersionUID = 5988040868275521928L
Detailed Description
Definition at line 78 of file AMRulesRegressor.java.
Member Function Documentation
void moa.classifiers.rules.AMRulesRegressor.getModelDescription (StringBuilder out, int indent) [virtual]
print GUI learn model
Reimplemented from moa.classifiers.rules.AbstractAMRules.
Definition at line 152 of file AMRulesRegressor.java.
References moa.options.MultiChoiceOption.getChosenLabel(), and moa.classifiers.rules.AMRulesRegressor.predictionFunctionOption.
{
        super.getModelDescription(out, indent);
        StringUtils.appendIndented(out, indent, "The prediction function used: "+this.predictionFunctionOption.getChosenLabel());
        StringUtils.appendNewline(out);
    }
boolean moa.classifiers.rules.AMRulesRegressor.isRandomizable () [virtual]
description of the Methods used.
isRandomizable resetLearningImpl newRule // to build an object with the parameters. trainOnInstanceImpl isAnomaly getVotesForInstance getModelMeasurementsImpl getModelDescription // to printout to MOA GUI debug // use debug('string') to printout to console
Implements moa.classifiers.rules.AbstractAMRules.
Definition at line 184 of file AMRulesRegressor.java.
{
        return true;
    }
ErrorWeightedVote moa.classifiers.rules.AMRulesRegressor.newErrorWeightedVote () [virtual]
Implements moa.classifiers.rules.AbstractAMRules.
Definition at line 190 of file AMRulesRegressor.java.
References moa.classifiers.AbstractClassifier.copy(), moa.options.AbstractClassOption.getPreMaterializedObject(), and moa.classifiers.rules.AMRulesRegressor.votingTypeOption.
{
        return  (ErrorWeightedVote)((ErrorWeightedVote) votingTypeOption.getPreMaterializedObject()).copy();
    }
Rule moa.classifiers.rules.AMRulesRegressor.newRule (int ID) [private]
Definition at line 169 of file AMRulesRegressor.java.
References moa.classifiers.rules.AbstractAMRules.DriftDetectionOption, moa.classifiers.rules.core.Rule.getBuilder(), moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.options.FlagOption.isSet, moa.classifiers.rules.AbstractAMRules.pageHinckleyAlphaOption, moa.classifiers.rules.AbstractAMRules.pageHinckleyThresholdOption, moa.classifiers.rules.AMRulesRegressor.predictionFunctionOption, moa.classifiers.rules.core.Rule.Builder.setOwner(), and moa.classifiers.rules.AbstractAMRules.statistics.
{
        Rule r=new Rule.Builder().
                threshold(this.pageHinckleyThresholdOption.getValue()).
                alpha(this.pageHinckleyAlphaOption.getValue()).
                changeDetection(this.DriftDetectionOption.isSet()).
                predictionFunction(this.predictionFunctionOption.getChosenIndex()).
                statistics(new double[3]).
                id(ID).
                amRules(this).build();
        r.getBuilder().setOwner(r);
        return r;
    }
Rule moa.classifiers.rules.AMRulesRegressor.newRule (int ID, RuleActiveLearningNode learningNode, double[] statistics) [protected, virtual]
Rule.Builder() to build an object with the parameters.
If you have an algorithm with many parameters, especially if some of them are optional, it can be beneficial to define an object that represents all of the parameters.
Returns:
Implements moa.classifiers.rules.AbstractAMRules.
Definition at line 112 of file AMRulesRegressor.java.
References moa.classifiers.rules.core.Rule.getLearningNode(), moa.classifiers.rules.core.RuleActiveLearningNode.getNodeStatistics(), moa.core.DoubleVector.getValue(), moa.options.FloatOption.getValue(), and moa.classifiers.rules.AMRulesRegressor.learningRatioOption.
Referenced by moa.classifiers.rules.AMRulesRegressor.resetLearningImpl().
{
        Rule r=newRule(ID);
        if (node!=null)
        {
            if(((RuleActiveRegressionNode)node).getPerceptron()!=null)
            {
                ((RuleActiveRegressionNode)r.getLearningNode()).setPerceptron(new Perceptron(((RuleActiveRegressionNode)node).getPerceptron()));
                ((RuleActiveRegressionNode)r.getLearningNode()).getPerceptron().setLearningRatio(this.learningRatioOption.getValue());
            }
            if (statistics==null)
            {
                double mean;
                if(node.getNodeStatistics().getValue(0)>0){
                    mean=node.getNodeStatistics().getValue(1)/node.getNodeStatistics().getValue(0);
                    ((RuleActiveRegressionNode)r.getLearningNode()).getTargetMean().reset(mean, 1);
                }
            }
        }
        if (statistics!=null && ((RuleActiveRegressionNode)r.getLearningNode()).getTargetMean()!=null)
        {
            double mean;
            if(statistics[0]>0){
                mean=statistics[1]/statistics[0];
                ((RuleActiveRegressionNode)r.getLearningNode()).getTargetMean().reset(mean, (long)statistics[0]);
            }
        }
        return r;
    }
RuleActiveLearningNode moa.classifiers.rules.AMRulesRegressor.newRuleActiveLearningNode (double[] initialClassObservations) [virtual]
Implements moa.classifiers.rules.AbstractAMRules.
Definition at line 147 of file AMRulesRegressor.java.
{
            return new RuleActiveRegressionNode(initialClassObservations);
    }
RuleActiveLearningNode moa.classifiers.rules.AMRulesRegressor.newRuleActiveLearningNode (Builder builder) [virtual]
Implements moa.classifiers.rules.AbstractAMRules.
Definition at line 143 of file AMRulesRegressor.java.
{
            return new RuleActiveRegressionNode(builder);
        }
void moa.classifiers.rules.AMRulesRegressor.resetLearningImpl () [virtual]
This method initializes and resets the algorithm.
Reimplemented from moa.classifiers.rules.AbstractAMRules.
Definition at line 162 of file AMRulesRegressor.java.
References moa.classifiers.rules.AbstractAMRules.defaultRule, moa.classifiers.rules.AMRulesRegressor.newRule(), moa.classifiers.rules.AbstractAMRules.ruleNumberID, and moa.classifiers.rules.AbstractAMRules.statistics.
{
        this.statistics= new double[]{0.0,0,0};
        this.ruleNumberID=0;
        this.defaultRule = newRule(++this.ruleNumberID);
    }
Member Data Documentation
FlagOption moa.classifiers.rules.AMRulesRegressor.constantLearningRatioDecayOption
Initial value:
 new FlagOption(
            "learningRatio_Decay_set_constant", 'd',
            "Learning Ratio Decay in Perceptron set to be constant. (The next parameter).")
Definition at line 89 of file AMRulesRegressor.java.
FloatOption moa.classifiers.rules.AMRulesRegressor.learningRatioOption
Initial value:
 new FloatOption(
            "learningRatio", 's',
            "Constante Learning Ratio to use for training the Perceptrons in the leaves.", 0.025)
Definition at line 93 of file AMRulesRegressor.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule().
MultiChoiceOption moa.classifiers.rules.AMRulesRegressor.predictionFunctionOption
Initial value:
 new MultiChoiceOption(
            "predictionFunctionOption", 'P', "The prediction function to use.", new String[]{
                    "Adaptative","Perceptron", "Target Mean"}, new String[]{
                    "Adaptative","Perceptron", "Target Mean"}, 0)
Definition at line 97 of file AMRulesRegressor.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.getModelDescription(), and moa.classifiers.rules.AMRulesRegressor.newRule().
final long moa.classifiers.rules.AMRulesRegressor.serialVersionUID = 5988040868275521928L [static, private]
Reimplemented from moa.classifiers.rules.AbstractAMRules.
Definition at line 85 of file AMRulesRegressor.java.
ClassOption moa.classifiers.rules.AMRulesRegressor.votingTypeOption
Initial value:
 new ClassOption("votingType",
            'V', "Voting Type.",
            ErrorWeightedVote.class,
            "InverseErrorWeightedVote")
Definition at line 102 of file AMRulesRegressor.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newErrorWeightedVote().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/AMRulesRegressor.java