MOA: moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node Class Reference
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node Class Reference
Public Member Functions
Node (double val, double target)
void insertValue (double val, double target)
Public Attributes
double cut_point
double[] lessThan
double[] greaterThan
Node left
Node right
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 45 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Constructor & Destructor Documentation
moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.Node (double val, double target)
Definition at line 59 of file BinaryTreeNumericAttributeClassObserverRegression.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.cut_point, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.greaterThan, and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.lessThan.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue().
{
            this.cut_point = val;
            this.lessThan = new double[3];
            this.greaterThan = new double[3];
            this.lessThan[0] = target; //The sum of their target attribute values.
            this.lessThan[1] = target * target; //The sum of the squared target attribute values.
            this.lessThan[2] = 1.0; //A counter of the number of instances that have reached the node.
            this.greaterThan[0] = 0.0;
            this.greaterThan[1] = 0.0;
            this.greaterThan[2] = 0.0;
      }
Member Function Documentation
void moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue (double val, double target)
Definition at line 71 of file BinaryTreeNumericAttributeClassObserverRegression.java.
References moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.cut_point, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.greaterThan, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.left, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.lessThan, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.Node(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.right.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.observeAttributeTarget().
{
            if (val == this.cut_point) {
                 this.lessThan[0] = this.lessThan[0] + target;
                 this.lessThan[1] = this.lessThan[1] + (target * target);
                 this.lessThan[2] = this.lessThan[2] + 1;
            } else if (val <= this.cut_point) {
                 this.lessThan[0] = this.lessThan[0] + target;
                 this.lessThan[1] = this.lessThan[1] + (target * target);
                 this.lessThan[2] = this.lessThan[2] + 1;
                if (this.left == null) {
                    this.left = new Node(val, target);
                } else {
                    this.left.insertValue(val, target);
                }
            } else {
                 this.greaterThan[0] = this.greaterThan[0] + target;
                 this.greaterThan[1] = this.greaterThan[1] + (target*target);
                 this.greaterThan[2] = this.greaterThan[2] + 1;
                if (this.right == null) {
                   this.right = new Node(val, target);
                } else {
                   this.right.insertValue(val, target);
                }
            }
        }
Member Data Documentation
double moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.cut_point
Definition at line 49 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.Node().
double [] moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.greaterThan
Definition at line 53 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.Node().
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.left
Definition at line 55 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue().
double [] moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.lessThan
Definition at line 51 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.Node().
Node moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.right
Definition at line 57 of file BinaryTreeNumericAttributeClassObserverRegression.java.
Referenced by moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.insertValue().
final long moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression.Node.serialVersionUID = 1L [static, private]
Definition at line 47 of file BinaryTreeNumericAttributeClassObserverRegression.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/BinaryTreeNumericAttributeClassObserverRegression.java