MOA: moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster Class Reference
moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster Class Reference
Public Member Functions
GeneratorCluster (int label)
GeneratorCluster (int label, SphereCluster cluster)
int getWorkID ()
Package Functions
void setDesitnation (double[] destination)
void setMoveVector (double[] vector)
Package Attributes
SphereCluster generator
int kill = -1
boolean merging = false
double[] moveVector
int totalMovementSteps
int currentMovementSteps
boolean isSplitting = false
LinkedList< DataPoint > points = new LinkedList<DataPoint>()
ArrayList< SphereCluster > microClusters = new ArrayList<SphereCluster>()
ArrayList< ArrayList< DataPoint > > microClustersPoints = new ArrayList()
ArrayList< Integer > microClustersDecay = new ArrayList()
Private Member Functions
void updateKernel ()
void addInstance (Instance instance)
void move ()
String tryMerging (GeneratorCluster merge)
String splitKernel ()
String fadeOut ()
Detailed Description
Definition at line 122 of file RandomRBFGeneratorEvents.java.
Constructor & Destructor Documentation
moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster (int label)
Definition at line 145 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.densityRangeOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.kernelRadiiOption, moa.streams.clustering.RandomRBFGeneratorEvents.kernelRadiiRangeOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.kill, moa.streams.clustering.RandomRBFGeneratorEvents.maxOverlapFitRuns, moa.streams.clustering.ClusteringStream.numAttsOption, moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), moa.cluster.Cluster.setId(), and moa.cluster.SphereCluster.setWeight().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
{
            boolean outofbounds = true;
            int tryCounter = 0;
            while(outofbounds && tryCounter < maxOverlapFitRuns){
                tryCounter++;
                outofbounds = false;
                double[] center = new double [numAttsOption.getValue()];
                double radius = kernelRadiiOption.getValue()+(instanceRandom.nextBoolean()?-1:1)*kernelRadiiRangeOption.getValue()*instanceRandom.nextDouble();
                while(radius <= 0){
                    radius = kernelRadiiOption.getValue()+(instanceRandom.nextBoolean()?-1:1)*kernelRadiiRangeOption.getValue()*instanceRandom.nextDouble();
                }
                for (int j = 0; j < numAttsOption.getValue(); j++) {
                     center[j] = instanceRandom.nextDouble();
                     if(center[j]- radius < 0 || center[j] + radius > 1){
                        outofbounds = true;
                        break;
                     }
                }
                generator = new SphereCluster(center, radius);
            }
            if(tryCounter < maxOverlapFitRuns){
                generator.setId(label);
                double avgWeight = 1.0/numClusterOption.getValue();
                double weight = avgWeight + (instanceRandom.nextBoolean()?-1:1)*avgWeight*densityRangeOption.getValue()*instanceRandom.nextDouble();
                generator.setWeight(weight);
                setDesitnation(null);
            }
            else{
                generator = null;
                kill = 0;
                System.out.println("Tried "+maxOverlapFitRuns+" times to create kernel. Reduce average radii." );
            }
        }
moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster (int label, SphereCluster cluster)
Definition at line 179 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), and moa.cluster.Cluster.setId().
{
            this.generator = cluster;
            cluster.setId(label);
            setDesitnation(null);
        }
Member Function Documentation
void moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance (Instance instance) [private]
Definition at line 220 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getCenterDistance(), moa.cluster.SphereCluster.getRadius(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClusters, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersDecay, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersPoints, moa.streams.clustering.ClusteringStream.numAttsOption, moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.points, and moa.cluster.Cluster.setGroundTruth().
{
            DataPoint point = new DataPoint(instance, numGeneratedInstances);
            points.add(point);
            int minMicroIndex = -1;
            double minHullDist = Double.MAX_VALUE;
            boolean inserted = false;
            //we favour more recently build clusters so we can remove earlier cluster sooner
            for (int m = microClusters.size()-1; m >=0 ; m--) {
                SphereCluster micro = microClusters.get(m);
                double hulldist = micro.getCenterDistance(point)-micro.getRadius();
                //point fits into existing cluster
                if(hulldist <= 0){
                    microClustersPoints.get(m).add(point);
                    microClustersDecay.set(m, numGeneratedInstances);
                    inserted = true;
                    break;
                }
                //if not, check if its at least the closest cluster
                else{
                    if(hulldist < minHullDist){
                        minMicroIndex = m;
                        minHullDist = hulldist;
                    }
                }
            }
            //Reseting index choice for alternative cluster building
            int alt = 1;
            if(alt == 1)
                minMicroIndex = -1;
            if(!inserted){
                //add to closest cluster and expand cluster
                if(minMicroIndex!=-1){
                    microClustersPoints.get(minMicroIndex).add(point);
                    //we should keep the miniball instances and just check in
                    //new points instead of rebuilding the whole thing
                    SphereCluster s = new SphereCluster(microClustersPoints.get(minMicroIndex),numAttsOption.getValue());
                    //check if current microcluster is bigger then generating cluster
                    if(s.getRadius() > generator.getRadius()){
                        //remove previously added point
                        microClustersPoints.get(minMicroIndex).remove(microClustersPoints.get(minMicroIndex).size()-1);
                        minMicroIndex = -1;
                    }
                    else{
                        microClusters.set(minMicroIndex, s);
                        microClustersDecay.set(minMicroIndex, numGeneratedInstances);
                    }
                }
                //minMicroIndex might have been reset above
                //create new micro cluster
                if(minMicroIndex == -1){
                    ArrayList<DataPoint> microPoints = new ArrayList<DataPoint>();
                    microPoints.add(point);
                    SphereCluster s;
                    if(alt == 0)
                        s = new SphereCluster(microPoints,numAttsOption.getValue());
                    else
                        s = new SphereCluster(generator.getCenter(),generator.getRadius(),1);
                    microClusters.add(s);
                    microClustersPoints.add(microPoints);
                    microClustersDecay.add(numGeneratedInstances);
                    int id = 0;
                    while(id < kernels.size()){
                        if(kernels.get(id) == this)
                            break;
                        id++;
                    }
                    s.setGroundTruth(id);
                }
            }
        }
String moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut () [private]
Definition at line 442 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.ClusteringStream.decayHorizonOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.Cluster.getId(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.kill, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, and moa.cluster.SphereCluster.setWeight().
{
            kill = decayHorizonOption.getValue();
            generator.setWeight(0.0);
            numActiveKernels--;
            normalizeWeights();
            return "Fading out C"+generator.getId();
        }
int moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.getWorkID ()
Definition at line 185 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.kernels.
{
            for(int c = 0; c < kernels.size(); c++){
                if(kernels.get(c).equals(this))
                    return c;
            }
            return -1;
        }
void moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move () [private]
Definition at line 295 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.currentMovementSteps, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.SphereCluster.getCenter(), moa.cluster.SphereCluster.getRadius(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.isSplitting, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.merging, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.moveVector, moa.cluster.SphereCluster.setCenter(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.totalMovementSteps.
{
            if(currentMovementSteps < totalMovementSteps){
                currentMovementSteps++;
                if( moveVector == null){
                    return;
                }
                else{
                    double[] center = generator.getCenter();
                    boolean outofbounds = true;
                    while(outofbounds){
                        double radius = generator.getRadius();
                        outofbounds = false;
                        center = generator.getCenter();
                        for ( int d = 0; d < center.length; d++ ) {
                            center[d]+= moveVector[d];
                            if(center[d]- radius < 0 || center[d] + radius > 1){
                                outofbounds = true;
                                setDesitnation(null);
                                break;
                            }
                        }
                    }
                    generator.setCenter(center);
                }
            }
            else{
                if(!merging){
                    setDesitnation(null);
                    isSplitting = false;
                }
            }
        }
void moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation (double[] destination) [package]
Definition at line 328 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.SphereCluster.getCenter(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.ClusteringStream.numAttsOption, and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move().
{
            if(destination == null){
                destination = new double [numAttsOption.getValue()];
                for (int j = 0; j < numAttsOption.getValue(); j++) {
                     destination[j] = instanceRandom.nextDouble();
                }
            }
            double[] center = generator.getCenter();
            int dim = center.length;
            double[] v = new double[dim];
            for ( int d = 0; d < dim; d++ ) {
                v[d]=destination[d]-center[d];
            }
            setMoveVector(v);
        }
void moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector (double[] vector) [package]
Definition at line 347 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.currentMovementSteps, moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.kernelMovePointFrequency, moa.streams.clustering.RandomRBFGeneratorEvents.maxDistanceMoveThresholdByStep, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.moveVector, moa.streams.clustering.RandomRBFGeneratorEvents.speedOption, moa.streams.clustering.RandomRBFGeneratorEvents.speedRangeOption, and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.totalMovementSteps.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation().
{
            //we are ignoring the steps, otherwise we have to change
            //speed of the kernels, do we want that?
            moveVector = vector;
            int speedInPoints  = speedOption.getValue();
            if(speedRangeOption.getValue() > 0)
                    speedInPoints +=(instanceRandom.nextBoolean()?-1:1)*instanceRandom.nextInt(speedRangeOption.getValue());
            if(speedInPoints  < 1) speedInPoints  = speedOption.getValue();
            double length = 0;
            for ( int d = 0; d < moveVector.length; d++ ) {
                length+=Math.pow(vector[d],2);
            }
            length = Math.sqrt(length);
            totalMovementSteps = (int)(length/(maxDistanceMoveThresholdByStep*kernelMovePointFrequency)*speedInPoints);
            for ( int d = 0; d < moveVector.length; d++ ) {
                moveVector[d]/=(double)totalMovementSteps;
            }
            currentMovementSteps = 0;
//            if(debug){
//                System.out.println("Setting new direction for C"+generator.getId()+": distance "
//                        +length+" in "+totalMovementSteps+" steps");
//            }
        }
String moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel () [private]
Definition at line 416 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.RandomRBFGeneratorEvents.clusterIdCounter, moa.streams.clustering.RandomRBFGeneratorEvents.densityRangeOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.cluster.SphereCluster.getCenter(), moa.cluster.Cluster.getId(), moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.instanceRandom, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.isSplitting, moa.streams.clustering.RandomRBFGeneratorEvents.kernelRadiiOption, moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, and moa.streams.clustering.RandomRBFGeneratorEvents.numClusterOption.
{
            isSplitting = true;
            //todo radius range
            double radius = kernelRadiiOption.getValue();
            double avgWeight = 1.0/numClusterOption.getValue();
            double weight = avgWeight + avgWeight*densityRangeOption.getValue()*instanceRandom.nextDouble();
            SphereCluster spcluster = null;
            double[] center = generator.getCenter();
            spcluster = new SphereCluster(center, radius, weight);
            if(spcluster !=null){
                GeneratorCluster gc = new GeneratorCluster(clusterIdCounter++, spcluster);
                gc.isSplitting = true;
                kernels.add(gc);
                normalizeWeights();
                numActiveKernels++;
                return "Split from Kernel "+generator.getId();
            }
            else{
                System.out.println("Tried to split new kernel from C"+generator.getId()+
                        ". Not enough room for new cluster, decrease average radii, number of clusters or enable overlap.");
                return "";
            }
        }
String moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging (GeneratorCluster merge) [private]
Definition at line 376 of file RandomRBFGeneratorEvents.java.
References moa.cluster.SphereCluster.combine(), moa.streams.clustering.ClusteringStream.decayHorizonOption, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator, moa.cluster.Cluster.getId(), moa.cluster.SphereCluster.getRadius(), moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.kill, moa.streams.clustering.RandomRBFGeneratorEvents.merge_threshold, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterA, moa.streams.clustering.RandomRBFGeneratorEvents.mergeClusterB, moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernelsOverlapping, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.merging, moa.streams.clustering.RandomRBFGeneratorEvents.normalizeWeights(), moa.streams.clustering.RandomRBFGeneratorEvents.numActiveKernels, moa.cluster.SphereCluster.overlapRadiusDegree(), moa.cluster.SphereCluster.setRadius(), and moa.cluster.SphereCluster.setWeight().
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels().
{
           String message = "";
           double overlapDegree = generator.overlapRadiusDegree(merge.generator);
           if(overlapDegree > merge_threshold){
                SphereCluster mcluster = merge.generator;
                double radius = Math.max(generator.getRadius(), mcluster.getRadius());
                generator.combine(mcluster);
//                //adjust radius, get bigger and bigger with high dim data
                generator.setRadius(radius);
//                double[] center = generator.getCenter();
//                double[] mcenter = mcluster.getCenter();
//                double weight = generator.getWeight();
//                double mweight = generator.getWeight();
//                generator.setWeight(weight + mweight);
                message  = "Clusters merging: "+mergeClusterB.generator.getId()+" into "+mergeClusterA.generator.getId();
                //clean up and restet merging stuff
                //mark kernel so it gets killed when it doesn't contain any more instances
                merge.kill = decayHorizonOption.getValue();
                //set weight to 0 so no new instances will be created in the cluster
                mcluster.setWeight(0.0);
                normalizeWeights();
                numActiveKernels--;
                mergeClusterB = mergeClusterA = null;
                merging = false;
                mergeKernelsOverlapping = false;
            }
           else{
               if(overlapDegree > 0 && !mergeKernelsOverlapping){
                   mergeKernelsOverlapping = true;
                   message = "Merge overlapping started";
               }
           }
           return message;
        }
void moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel () [private]
Definition at line 193 of file RandomRBFGeneratorEvents.java.
References moa.streams.clustering.ClusteringStream.decayHorizonOption, moa.options.IntOption.getValue(), moa.streams.clustering.RandomRBFGeneratorEvents.kernels, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.kill, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClusters, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersDecay, moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersPoints, moa.streams.clustering.RandomRBFGeneratorEvents.numGeneratedInstances, and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.points.
{
            if(kill == 0){
                kernels.remove(this);
            }
            if(kill > 0){
                kill--;
            }
            //we could be lot more precise if we would keep track of timestamps of points
            //then we could remove all old points and rebuild the cluster on up to date point base
            //BUT worse the effort??? so far we just want to avoid overlap with this, so its more
            //konservative as needed. Only needs to change when we need a thighter representation
            for (int m = 0; m < microClusters.size(); m++) {
                if(numGeneratedInstances-microClustersDecay.get(m) > decayHorizonOption.getValue()){
                    microClusters.remove(m);
                    microClustersPoints.remove(m);
                    microClustersDecay.remove(m);
                }
            }
            if(!points.isEmpty() && numGeneratedInstances-points.getFirst().getTimestamp() >= decayHorizonOption.getValue()){
//                if(debug)
//                    System.out.println("Cleaning up macro cluster "+generator.getId());
                points.removeFirst();
            }
        }
Member Data Documentation
int moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.currentMovementSteps [package]
Definition at line 136 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
SphereCluster moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.generator [package]
Definition at line 131 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setDesitnation(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
boolean moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.isSplitting = false [package]
Definition at line 137 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.splitKernel().
int moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.kill = -1 [package]
Definition at line 132 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.fadeOut(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.GeneratorCluster(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
boolean moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.merging = false [package]
Definition at line 133 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.mergeKernels(), moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.tryMerging().
ArrayList<SphereCluster> moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClusters = new ArrayList<SphereCluster>() [package]
Definition at line 140 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
ArrayList<Integer> moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersDecay = new ArrayList() [package]
Definition at line 142 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
ArrayList<ArrayList<DataPoint> > moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.microClustersPoints = new ArrayList() [package]
Definition at line 141 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
double [] moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.moveVector [package]
Definition at line 134 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
LinkedList<DataPoint> moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.points = new LinkedList<DataPoint>() [package]
Definition at line 139 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.addInstance(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.updateKernel().
int moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.totalMovementSteps [package]
Definition at line 135 of file RandomRBFGeneratorEvents.java.
Referenced by moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.move(), and moa.streams.clustering.RandomRBFGeneratorEvents.GeneratorCluster.setMoveVector().
The documentation for this class was generated from the following file:
main/java/moa/streams/clustering/RandomRBFGeneratorEvents.java