MOA: moa.clusterers.outliers.AnyOut.util.DataObject Class Reference
moa.clusterers.outliers.AnyOut.util.DataObject Class Reference
This object encapsulates a data point.
Public Member Functions
double[] getFeatures ()
Returns the features (label attribute excluded).
int getId ()
Returns the id for the DataObject.
void setId (int id)
int getClassLabel ()
Return the label for the DataObject.
Instance getInstance ()
Return the Instance of the DataObject.
DataObject (int idCounter, Instance inst)
Standard constructor for DataObject.
int getNrOfDimensions ()
Returns the number of features (label attribute excluded).
String toString ()
Returns a String representation of the point.
void setOutiler (boolean val)
boolean isOutiler ()
Private Attributes
int id
Instance inst
double[] features
int classLabel
boolean isOutiler
Detailed Description
This object encapsulates a data point.
Author:
Fernando Sanchez Villaamil
Definition at line 31 of file DataObject.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.AnyOut.util.DataObject.DataObject (int idCounter, Instance inst)
Standard constructor for DataObject.
Parameters:
idCounter The id for the DataObject.
features The feature as a double[]
classLabel The label id for the DataObject.
Definition at line 82 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.classLabel, moa.clusterers.outliers.AnyOut.util.DataObject.features, and moa.clusterers.outliers.AnyOut.util.DataObject.isOutiler().
{
        this.id = idCounter;
        this.inst = inst;
        this.features = inst.toDoubleArray();
        this.classLabel = (int)inst.classValue();
        this.isOutiler = false;
    }
Member Function Documentation
int moa.clusterers.outliers.AnyOut.util.DataObject.getClassLabel ()
Return the label for the DataObject.
Returns:
An int which codes the label.
Definition at line 65 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.classLabel.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
{
        return classLabel;
    }
double [] moa.clusterers.outliers.AnyOut.util.DataObject.getFeatures ()
Returns the features (label attribute excluded).
Returns:
An array double[] with the features.
Definition at line 43 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.features.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getObjectInfo(), moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.mergeDataSets(), moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj(), and moa.clusterers.outliers.AnyOut.util.EMTopDownTreeBuilder.splitDataSetUsingMeanShift().
{
        double[] filteredFeatures = new double[features.length-1];
        for (int i = 0; i<filteredFeatures.length; i++)
            filteredFeatures[i]=features[i];
        return filteredFeatures;
    }
int moa.clusterers.outliers.AnyOut.util.DataObject.getId ()
Returns the id for the DataObject.
Returns:
An int with the id of the DataObject.
Definition at line 54 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.id.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.getObjectInfo(), and moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
                       {
        return id;
    }
Instance moa.clusterers.outliers.AnyOut.util.DataObject.getInstance ()
Return the Instance of the DataObject.
Returns:
An Instance.
Definition at line 73 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.inst.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
{
        return inst;
    }
int moa.clusterers.outliers.AnyOut.util.DataObject.getNrOfDimensions ()
Returns the number of features (label attribute excluded).
Returns:
The number of features in the point.
Definition at line 94 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.features.
Referenced by moa.clusterers.outliers.AnyOut.util.DataSet.addObject(), and moa.clusterers.outliers.AnyOut.util.DataSet.DataSet().
{
        return this.features.length-1;
    }
boolean moa.clusterers.outliers.AnyOut.util.DataObject.isOutiler ()
Definition at line 127 of file DataObject.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataObject.DataObject(), and moa.clusterers.outliers.AnyOut.util.DataObject.setOutiler().
{
        return isOutiler;
    }
void moa.clusterers.outliers.AnyOut.util.DataObject.setId (int id)
Definition at line 57 of file DataObject.java.
{
        this.id=id;
    }
void moa.clusterers.outliers.AnyOut.util.DataObject.setOutiler (boolean val)
Definition at line 123 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.isOutiler().
{
        isOutiler = val;
    }
String moa.clusterers.outliers.AnyOut.util.DataObject.toString ()
Returns a String representation of the point.
The features are written comma separated between parenthesis and the label id is written after the closing parenthesis surrounded by squared brackets.
Returns:
A String representation of the point.
Definition at line 105 of file DataObject.java.
References moa.clusterers.outliers.AnyOut.util.DataObject.classLabel, and moa.clusterers.outliers.AnyOut.util.DataObject.features.
{
        String res = "(";
        for (int i = 0; i < features.length; i++) {
            double d = features[i];
            res += d;
            if (i != features.length - 1)
                res += ",";
        }
        res += ")";
        res += "[" + this.classLabel + "]";
        return res;
    }
Member Data Documentation
int moa.clusterers.outliers.AnyOut.util.DataObject.classLabel [private]
Definition at line 36 of file DataObject.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataObject.DataObject(), moa.clusterers.outliers.AnyOut.util.DataObject.getClassLabel(), and moa.clusterers.outliers.AnyOut.util.DataObject.toString().
double [] moa.clusterers.outliers.AnyOut.util.DataObject.features [private]
Definition at line 35 of file DataObject.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataObject.DataObject(), moa.clusterers.outliers.AnyOut.util.DataObject.getFeatures(), moa.clusterers.outliers.AnyOut.util.DataObject.getNrOfDimensions(), and moa.clusterers.outliers.AnyOut.util.DataObject.toString().
int moa.clusterers.outliers.AnyOut.util.DataObject.id [private]
Definition at line 33 of file DataObject.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataObject.getId().
Instance moa.clusterers.outliers.AnyOut.util.DataObject.inst [private]
Definition at line 34 of file DataObject.java.
Referenced by moa.clusterers.outliers.AnyOut.util.DataObject.getInstance().
boolean moa.clusterers.outliers.AnyOut.util.DataObject.isOutiler [private]
Definition at line 37 of file DataObject.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/AnyOut/util/DataObject.java