MOA: moa.test.MoaTestCase Class Reference
moa.test.MoaTestCase Class Reference
Ancestor for all test cases.
Public Member Functions
MoaTestCase (String name)
Constructs the test case.
void testSerializable ()
For classes (with default constructor) that are serializable, are tested whether they are truly serializable.
Static Public Member Functions
static String doubleToString (double value, int afterDecimalPoint)
Rounds a double and converts it into String.
static void runTest (Test suite)
Runs the specified suite.
Static Public Attributes
static final String PROPERTY_HEADLESS = "moa.test.headless"
property indicating whether tests should be run in headless mode.
static final String PROPERTY_NOREGRESSION = "moa.test.noregression"
property indicating whether regression tests should not be executed.
Protected Member Functions
Class getTestedClass ()
Tries to load the class based on the test class's name.
boolean canHandleHeadless ()
Returns whether the test can be executed in a headless environment.
void setUp () throws Exception
Called by JUnit before each test method.
void runTest () throws Throwable
Override to run the test and assert its state.
void tearDown () throws Exception
Called by JUnit after each test method.
AbstractTestHelper newTestHelper ()
Returns the test helper class to use.
Object getInstance (Class cls, Class intf, boolean fail)
Tries to obtain an instance of the given class.
Object deepCopy (Object o)
Creates a deep copy of the given object (must be serializable!).
void performSerializableTest (Class cls)
Performs a serializable test on the given class.
Protected Attributes
boolean m_NoRegressionTest
whether to execute any regression test.
Regression m_Regression
the helper class for regression.
AbstractTestHelper m_TestHelper
the test class to use.
boolean m_Headless
whether to run tests in headless mode.
Detailed Description
Ancestor for all test cases.
Any regression test can be skipped as follows:
-Dmoa.test.noregression=true
Author:
fracpete (fracpete at waikato dot ac dot nz)
Version:
Revision
8349
Definition at line 38 of file MoaTestCase.java.
Constructor & Destructor Documentation
moa.test.MoaTestCase.MoaTestCase (String name)
Constructs the test case.
Called by subclasses.
Parameters:
name the name of the test
Definition at line 64 of file MoaTestCase.java.
{
    super(name);
  }
Member Function Documentation
boolean moa.test.MoaTestCase.canHandleHeadless () [protected]
Returns whether the test can be executed in a headless environment.
If not then the test gets skipped.
Returns:
true if OK to run in headless mode
Definition at line 97 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.runTest().
{
    return true;
  }
Object moa.test.MoaTestCase.deepCopy (Object o) [protected]
Creates a deep copy of the given object (must be serializable!).
Returns null in case of an error.
Parameters:
o the object to copy
Returns:
the deep copy
Definition at line 209 of file MoaTestCase.java.
References moa.test.SerializedObject.getObject().
Referenced by moa.test.MoaTestCase.performSerializableTest().
{
    Object      result;
    SerializedObject    so;
    try {
      so     = new SerializedObject((Serializable) o);
      result = so.getObject();
    }
    catch (Exception e) {
      System.err.println("Failed to serialize " + o.getClass().getName() + ":");
      e.printStackTrace();
      result = null;
    }
    return result;
  }
static String moa.test.MoaTestCase.doubleToString (double value, int afterDecimalPoint) [static]
Rounds a double and converts it into String.
Parameters:
value the double value
afterDecimalPoint the (maximum) number of digits permitted after the decimal point
Returns:
the double as a formatted string
Definition at line 234 of file MoaTestCase.java.
{
    StringBuilder   builder;
    double      temp;
    int         dotPosition;
    int         currentPos;
    long        precisionValue;
    char        separator;
    temp = value * Math.pow(10.0, afterDecimalPoint);
    if (Math.abs(temp) < Long.MAX_VALUE) {
      precisionValue =  (temp > 0) ? (long)(temp + 0.5)
      : -(long)(Math.abs(temp) + 0.5);
      if (precisionValue == 0)
    builder = new StringBuilder(String.valueOf(0));
      else
    builder = new StringBuilder(String.valueOf(precisionValue));
      if (afterDecimalPoint == 0)
    return builder.toString();
      separator   = '.';
      dotPosition = builder.length() - afterDecimalPoint;
      while (((precisionValue < 0) && (dotPosition < 1)) || (dotPosition < 0)) {
    if (precisionValue < 0)
      builder.insert(1, '0');
    else
      builder.insert(0, '0');
    dotPosition++;
      }
      builder.insert(dotPosition, separator);
      if ((precisionValue < 0) && (builder.charAt(1) == separator))
    builder.insert(1, '0');
      else if (builder.charAt(0) == separator)
    builder.insert(0, '0');
      currentPos = builder.length() - 1;
      while ((currentPos > dotPosition) && (builder.charAt(currentPos) == '0'))
    builder.setCharAt(currentPos--, ' ');
      if (builder.charAt(currentPos) == separator)
    builder.setCharAt(currentPos, ' ');
      return builder.toString().trim();
    }
    return new String("" + value);
  }
Object moa.test.MoaTestCase.getInstance (Class cls, Class intf, boolean fail) [protected]
Tries to obtain an instance of the given class.
Parameters:
cls the class to obtain an instance from
intf the required interface that the class must implement
fail if true, errors/exceptions will result in a test fail
Definition at line 170 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.performSerializableTest().
{
    Object      result;
    Constructor     constr;
    if (!intf.isAssignableFrom(cls))
      return null;
    // default constructor?
    constr = null;
    try {
      constr = cls.getConstructor(new Class[0]);
    }
    catch (NoSuchMethodException e) {
      if (fail)
    fail("No default constructor, requires custom test method: " + cls.getName());
      return null;
    }
    // create instance
    result = null;
    try {
      result = constr.newInstance(new Object[0]);
    }
    catch (Exception e) {
      if (fail)
    fail("Failed to instantiate object using default constructor: " + cls.getName());
      return null;
    }
    return result;
  }
Class moa.test.MoaTestCase.getTestedClass () [protected]
Tries to load the class based on the test class's name.
Returns:
the class that is being tested or null if none could be determined
Definition at line 74 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp().
{
    Class   result;
    result = null;
    if (getClass().getName().endsWith("Test")) {
      try {
    result = Class.forName(getClass().getName().replaceAll("Test$", ""));
      }
      catch (Exception e) {
    result = null;
      }
    }
    return result;
  }
AbstractTestHelper moa.test.MoaTestCase.newTestHelper () [protected]
Returns the test helper class to use.
Returns:
the helper class instance
Reimplemented in moa.classifiers.AbstractClassifierTestCase.
Definition at line 159 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp().
{
    return new TestHelper(this, "");
  }
void moa.test.MoaTestCase.performSerializableTest (Class cls) [protected]
Performs a serializable test on the given class.
Parameters:
cls the class to test
Definition at line 288 of file MoaTestCase.java.
References moa.test.MoaTestCase.deepCopy(), and moa.test.MoaTestCase.getInstance().
Referenced by moa.test.MoaTestCase.testSerializable().
{
    Object      obj;
    obj = getInstance(cls, Serializable.class, true);
    if (obj == null)
      return;
    assertNotNull("Serialization failed", deepCopy(obj));
  }
static void moa.test.MoaTestCase.runTest (Test suite) [static]
Runs the specified suite.
Used for running the test from commandline.
Parameters:
suite the suite to run
Definition at line 312 of file MoaTestCase.java.
{
    TestRunner.run(suite);
  }
void moa.test.MoaTestCase.runTest () throws Throwable [protected]
Override to run the test and assert its state.
Checks whether the test or test-method is platform-specific.
Exceptions:
Throwable if any exception is thrown
Definition at line 128 of file MoaTestCase.java.
References moa.test.MoaTestCase.canHandleHeadless(), and moa.test.MoaTestCase.m_Headless.
Referenced by moa.classifiers.trees.RandomHoeffdingTreeTest.main(), moa.classifiers.trees.ORTOTest.main(), moa.classifiers.trees.LimAttHoeffdingTreeTest.main(), moa.classifiers.trees.HoeffdingTreeTest.main(), moa.classifiers.trees.HoeffdingOptionTreeTest.main(), moa.classifiers.trees.HoeffdingAdaptiveTreeTest.main(), moa.classifiers.trees.FIMTDDTest.main(), moa.classifiers.trees.DecisionStumpTest.main(), moa.classifiers.trees.ASHoeffdingTreeTest.main(), moa.classifiers.trees.AdaHoeffdingOptionTreeTest.main(), moa.classifiers.rules.RuleClassifierTest.main(), moa.classifiers.rules.RuleClassifierNBayesTest.main(), moa.classifiers.rules.AMRulesRegressorTest.main(), moa.classifiers.meta.WEKAClassifierTest.main(), moa.classifiers.meta.WeightedMajorityAlgorithmTest.main(), moa.classifiers.meta.TemporallyAugmentedClassifierTest.main(), moa.classifiers.meta.OzaBoostTest.main(), moa.classifiers.meta.OzaBoostAdwinTest.main(), moa.classifiers.meta.OzaBagTest.main(), moa.classifiers.meta.OzaBagASHTTest.main(), moa.classifiers.meta.OzaBagAdwinTest.main(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest.main(), moa.classifiers.meta.OCBoostTest.main(), moa.classifiers.meta.LimAttClassifierTest.main(), moa.classifiers.meta.LeveragingBagTest.main(), moa.classifiers.meta.AccuracyWeightedEnsembleTest.main(), moa.classifiers.meta.AccuracyUpdatedEnsembleTest.main(), moa.classifiers.functions.SPegasosTest.main(), moa.classifiers.functions.SGDTest.main(), moa.classifiers.functions.PerceptronTest.main(), moa.classifiers.functions.NoChangeTest.main(), moa.classifiers.functions.MajorityClassTest.main(), moa.classifiers.drift.SingleClassifierDriftTest.main(), moa.classifiers.drift.DriftDetectionMethodClassifierTest.main(), moa.classifiers.bayes.NaiveBayesTest.main(), moa.classifiers.bayes.NaiveBayesMultinomialTest.main(), and moa.classifiers.active.ActiveClassifierTest.main().
{
    boolean     proceed;
    proceed = true;
    if (m_Headless && !canHandleHeadless())
      proceed = false;
    if (proceed)
      super.runTest();
    else
      System.out.println("Skipped");
  }
void moa.test.MoaTestCase.setUp () throws Exception [protected]
Called by JUnit before each test method.
Exceptions:
Exception if an error occurs.
Reimplemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Definition at line 107 of file MoaTestCase.java.
References moa.test.MoaTestCase.getTestedClass(), moa.test.MoaTestCase.m_Headless, moa.test.MoaTestCase.m_NoRegressionTest, moa.test.MoaTestCase.m_Regression, moa.test.MoaTestCase.m_TestHelper, moa.test.MoaTestCase.newTestHelper(), moa.test.MoaTestCase.PROPERTY_HEADLESS, and moa.test.MoaTestCase.PROPERTY_NOREGRESSION.
{
    Class   cls;
    super.setUp();
    cls = getTestedClass();
    if (cls != null)
      m_Regression = new Regression(cls);
    m_TestHelper       = newTestHelper();
    m_Headless         = Boolean.getBoolean(PROPERTY_HEADLESS);
    m_NoRegressionTest = Boolean.getBoolean(PROPERTY_NOREGRESSION);
  }
void moa.test.MoaTestCase.tearDown () throws Exception [protected]
Called by JUnit after each test method.
Exceptions:
Exception if tear-down fails
Reimplemented in moa.classifiers.AbstractMultipleClassifierTestCase, and moa.classifiers.AbstractMultipleRegressorTestCase.
Definition at line 148 of file MoaTestCase.java.
References moa.test.MoaTestCase.m_Regression.
{
    m_Regression = null;
    super.tearDown();
  }
void moa.test.MoaTestCase.testSerializable ()
For classes (with default constructor) that are serializable, are tested whether they are truly serializable.
Definition at line 302 of file MoaTestCase.java.
References moa.test.Regression.getRegressionClass(), moa.test.MoaTestCase.m_Regression, and moa.test.MoaTestCase.performSerializableTest().
{
    if (m_Regression != null)
      performSerializableTest(m_Regression.getRegressionClass());
  }
Member Data Documentation
boolean moa.test.MoaTestCase.m_Headless [protected]
whether to run tests in headless mode.
Definition at line 57 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.runTest(), and moa.test.MoaTestCase.setUp().
boolean moa.test.MoaTestCase.m_NoRegressionTest [protected]
whether to execute any regression test.
Definition at line 48 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp(), and moa.classifiers.AbstractClassifierTestCase.testRegression().
Regression moa.test.MoaTestCase.m_Regression [protected]
the helper class for regression.
Definition at line 51 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp(), moa.test.MoaTestCase.tearDown(), moa.classifiers.AbstractClassifierTestCase.testRegression(), and moa.test.MoaTestCase.testSerializable().
AbstractTestHelper moa.test.MoaTestCase.m_TestHelper [protected]
the test class to use.
Definition at line 54 of file MoaTestCase.java.
Referenced by moa.classifiers.AbstractClassifierTestCase.save(), moa.test.MoaTestCase.setUp(), moa.classifiers.AbstractMultipleRegressorTestCase.setUp(), moa.classifiers.AbstractMultipleClassifierTestCase.setUp(), moa.classifiers.AbstractMultipleRegressorTestCase.tearDown(), moa.classifiers.AbstractMultipleClassifierTestCase.tearDown(), and moa.classifiers.AbstractClassifierTestCase.testRegression().
final String moa.test.MoaTestCase.PROPERTY_HEADLESS = "moa.test.headless" [static]
property indicating whether tests should be run in headless mode.
Definition at line 42 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp().
final String moa.test.MoaTestCase.PROPERTY_NOREGRESSION = "moa.test.noregression" [static]
property indicating whether regression tests should not be executed.
Definition at line 45 of file MoaTestCase.java.
Referenced by moa.test.MoaTestCase.setUp().
The documentation for this class was generated from the following file:
test/java/moa/test/MoaTestCase.java