MOA: moa.tasks.EvaluatePrequentialRegression Class Reference
moa.tasks.EvaluatePrequentialRegression Class Reference
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption learnerOption
ClassOption streamOption
ClassOption evaluatorOption
IntOption instanceLimitOption
IntOption timeLimitOption
IntOption sampleFrequencyOption
IntOption memCheckFrequencyOption
FileOption dumpFileOption
FileOption outputPredictionFileOption
IntOption widthOption
FloatOption alphaOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a classifier on a stream by testing then training with each example in sequence.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 53 of file EvaluatePrequentialRegression.java.
Member Function Documentation
Object moa.tasks.EvaluatePrequentialRegression.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 112 of file EvaluatePrequentialRegression.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.tasks.EvaluatePrequentialRegression.alphaOption, moa.AbstractMOAObject.copy(), moa.tasks.EvaluatePrequentialRegression.dumpFileOption, moa.evaluation.LearningCurve.entryToString(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluatePrequentialRegression.evaluatorOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.evaluation.LearningCurve.headerToString(), moa.evaluation.LearningCurve.insertEntry(), moa.tasks.EvaluatePrequentialRegression.instanceLimitOption, moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.EvaluatePrequentialRegression.learnerOption, moa.MOAObject.measureByteSize(), moa.streams.InstanceStream.nextInstance(), moa.evaluation.LearningCurve.numEntries(), moa.tasks.EvaluatePrequentialRegression.outputPredictionFileOption, moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.EvaluatePrequentialRegression.sampleFrequencyOption, moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.classifiers.Classifier.setModelContext(), moa.tasks.EvaluatePrequentialRegression.streamOption, moa.tasks.TaskMonitor.taskShouldAbort(), moa.tasks.EvaluatePrequentialRegression.timeLimitOption, moa.classifiers.Classifier.trainOnInstance(), and moa.tasks.EvaluatePrequentialRegression.widthOption.
{
        Classifier learner = (Classifier) getPreparedClassOption(this.learnerOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        RegressionPerformanceEvaluator evaluator = (RegressionPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        LearningCurve learningCurve = new LearningCurve(
                "learning evaluation instances");
        //New for prequential methods
        if (evaluator instanceof WindowClassificationPerformanceEvaluator) {
            //((WindowClassificationPerformanceEvaluator) evaluator).setWindowWidth(widthOption.getValue());
            if (widthOption.getValue() != 1000) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (WindowClassificationPerformanceEvaluator -w " + widthOption.getValue() + ")");
                 return learningCurve;
            }
        }
        if (evaluator instanceof EWMAClassificationPerformanceEvaluator) {
            //((EWMAClassificationPerformanceEvaluator) evaluator).setalpha(alphaOption.getValue());
            if (alphaOption.getValue() != .01) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (EWMAClassificationPerformanceEvaluator -a " + alphaOption.getValue() + ")");
                return learningCurve;
            }
        }
        if (evaluator instanceof FadingFactorClassificationPerformanceEvaluator) {
            //((FadingFactorClassificationPerformanceEvaluator) evaluator).setalpha(alphaOption.getValue());
            if (alphaOption.getValue() != .01) {
                System.out.println("DEPRECATED! Use EvaluatePrequential -e (FadingFactorClassificationPerformanceEvaluator -a " + alphaOption.getValue() + ")");
                return learningCurve;
            }
        }
        //End New for prequential methods
        learner.setModelContext(stream.getHeader());
        int maxInstances = this.instanceLimitOption.getValue();
        long instancesProcessed = 0;
        int maxSeconds = this.timeLimitOption.getValue();
        int secondsElapsed = 0;
        monitor.setCurrentActivity("Evaluating learner...", -1.0);
        File dumpFile = this.dumpFileOption.getFile();
        PrintStream immediateResultStream = null;
        if (dumpFile != null) {
            try {
                if (dumpFile.exists()) {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile, true), true);
                } else {
                    immediateResultStream = new PrintStream(
                            new FileOutputStream(dumpFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open immediate result file: " + dumpFile, ex);
            }
        }
        //File for output predictions
        File outputPredictionFile = this.outputPredictionFileOption.getFile();
        PrintStream outputPredictionResultStream = null;
        if (outputPredictionFile != null) {
            try {
                if (outputPredictionFile.exists()) {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile, true), true);
                } else {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open prediction result file: " + outputPredictionFile, ex);
            }
        }
        boolean firstDump = true;
        boolean preciseCPUTiming = TimingUtils.enablePreciseTiming();
        long evaluateStartTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
        long lastEvaluateStartTime = evaluateStartTime;
        double RAMHours = 0.0;
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))
                && ((maxSeconds < 0) || (secondsElapsed < maxSeconds))) {
            Instance trainInst = stream.nextInstance();
            Instance testInst = (Instance) trainInst.copy();
            double trueClass =  trainInst.classValue();
            //testInst.setClassMissing();
            double[] prediction = learner.getVotesForInstance(testInst);
            // Output prediction
            if (outputPredictionFile != null) {
                outputPredictionResultStream.println(prediction[0] + "," + trueClass);
            }
            //evaluator.addClassificationAttempt(trueClass, prediction, testInst.weight());
            evaluator.addResult(testInst, prediction);
            learner.trainOnInstance(trainInst);
            instancesProcessed++;
            if (instancesProcessed % this.sampleFrequencyOption.getValue() == 0
                    || stream.hasMoreInstances() == false) {
                long evaluateTime = TimingUtils.getNanoCPUTimeOfCurrentThread();
                double time = TimingUtils.nanoTimeToSeconds(evaluateTime - evaluateStartTime);
                double timeIncrement = TimingUtils.nanoTimeToSeconds(evaluateTime - lastEvaluateStartTime);
                double RAMHoursIncrement = learner.measureByteSize() / (1024.0 * 1024.0 * 1024.0); //GBs
                RAMHoursIncrement *= (timeIncrement / 3600.0); //Hours
                RAMHours += RAMHoursIncrement;
                lastEvaluateStartTime = evaluateTime;
                learningCurve.insertEntry(new LearningEvaluation(
                        new Measurement[]{
                            new Measurement(
                            "learning evaluation instances",
                            instancesProcessed),
                            new Measurement(
                            "evaluation time ("
                            + (preciseCPUTiming ? "cpu "
                            : "") + "seconds)",
                            time),
                            new Measurement(
                            "model cost (RAM-Hours)",
                            RAMHours)
                        },
                        evaluator, learner));
                if (immediateResultStream != null) {
                    if (firstDump) {
                        immediateResultStream.println(learningCurve.headerToString());
                        firstDump = false;
                    }
                    immediateResultStream.println(learningCurve.entryToString(learningCurve.numEntries() - 1));
                    immediateResultStream.flush();
                }
            }
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) instancesProcessed
                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(learningCurve.copy());
                }
                secondsElapsed = (int) TimingUtils.nanoTimeToSeconds(TimingUtils.getNanoCPUTimeOfCurrentThread()
                        - evaluateStartTime);
            }
        }
        if (immediateResultStream != null) {
            immediateResultStream.close();
        }
        if (outputPredictionResultStream != null) {
            outputPredictionResultStream.close();
        }
        return learningCurve;
    }
String moa.tasks.EvaluatePrequentialRegression.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 56 of file EvaluatePrequentialRegression.java.
{
        return "Evaluates a classifier on a stream by testing then training with each example in sequence.";
    }
Class<?> moa.tasks.EvaluatePrequentialRegression.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 107 of file EvaluatePrequentialRegression.java.
{
        return LearningCurve.class;
    }
Member Data Documentation
FloatOption moa.tasks.EvaluatePrequentialRegression.alphaOption
Initial value:
 new FloatOption("alpha",
            'a', "Fading factor or exponential smoothing factor", .01)
Definition at line 102 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
FileOption moa.tasks.EvaluatePrequentialRegression.dumpFileOption
Initial value:
 new FileOption("dumpFile", 'd',
            "File to append intermediate csv results to.", null, "csv", true)
Definition at line 92 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
ClassOption moa.tasks.EvaluatePrequentialRegression.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            RegressionPerformanceEvaluator.class,
            "WindowRegressionPerformanceEvaluator")
Definition at line 69 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
IntOption moa.tasks.EvaluatePrequentialRegression.instanceLimitOption
Initial value:
 new IntOption("instanceLimit", 'i',
            "Maximum number of instances to test/train on  (-1 = no limit).",
            100000000, -1, Integer.MAX_VALUE)
Definition at line 74 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
ClassOption moa.tasks.EvaluatePrequentialRegression.learnerOption
Initial value:
 new ClassOption("learner", 'l',
            "Classifier to train.", Regressor.class, "trees.FIMTDD")
Definition at line 62 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
IntOption moa.tasks.EvaluatePrequentialRegression.memCheckFrequencyOption
Initial value:
 new IntOption(
            "memCheckFrequency", 'q',
            "How many instances between memory bound checks.", 100000, 0,
            Integer.MAX_VALUE)
Definition at line 87 of file EvaluatePrequentialRegression.java.
FileOption moa.tasks.EvaluatePrequentialRegression.outputPredictionFileOption
Initial value:
 new FileOption("outputPredictionFile", 'o',
            "File to append output predictions to.", null, "pred", true)
Definition at line 95 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
IntOption moa.tasks.EvaluatePrequentialRegression.sampleFrequencyOption
Initial value:
 new IntOption("sampleFrequency",
            'f',
            "How many instances between samples of the learning performance.",
            100000, 0, Integer.MAX_VALUE)
Definition at line 82 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
final long moa.tasks.EvaluatePrequentialRegression.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 60 of file EvaluatePrequentialRegression.java.
ClassOption moa.tasks.EvaluatePrequentialRegression.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to learn from.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 65 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
IntOption moa.tasks.EvaluatePrequentialRegression.timeLimitOption
Initial value:
 new IntOption("timeLimit", 't',
            "Maximum number of seconds to test/train for (-1 = no limit).", -1,
            -1, Integer.MAX_VALUE)
Definition at line 78 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
IntOption moa.tasks.EvaluatePrequentialRegression.widthOption
Initial value:
 new IntOption("width",
            'w', "Size of Window", 1000)
Definition at line 99 of file EvaluatePrequentialRegression.java.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluatePrequentialRegression.java