MOA: moa.classifiers.trees.HoeffdingTree.Node Class Reference
moa.classifiers.trees.HoeffdingTree.Node Class Reference
Public Member Functions
Node (double[] classObservations)
int calcByteSize ()
int calcByteSizeIncludingSubtree ()
boolean isLeaf ()
FoundNode filterInstanceToLeaf (Instance inst, SplitNode parent, int parentBranch)
double[] getObservedClassDistribution ()
double[] getClassVotes (Instance inst, HoeffdingTree ht)
boolean observedClassDistributionIsPure ()
void describeSubtree (HoeffdingTree ht, StringBuilder out, int indent)
int subtreeDepth ()
double calculatePromise ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
DoubleVector observedClassDistribution
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 181 of file HoeffdingTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingTree.Node.Node (double[] classObservations)
Definition at line 187 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
{
            this.observedClassDistribution = new DoubleVector(classObservations);
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingTree.Node.calcByteSize ()
Reimplemented in moa.classifiers.trees.HoeffdingTree.SplitNode, and moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.
Definition at line 191 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.calcByteSizeIncludingSubtree().
{
            return (int) (SizeOf.sizeOf(this) + SizeOf.fullSizeOf(this.observedClassDistribution));
        }
int moa.classifiers.trees.HoeffdingTree.Node.calcByteSizeIncludingSubtree ()
Reimplemented in moa.classifiers.trees.HoeffdingTree.SplitNode.
Definition at line 195 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.calcByteSize().
{
            return calcByteSize();
        }
double moa.classifiers.trees.HoeffdingTree.Node.calculatePromise ()
Definition at line 236 of file HoeffdingTree.java.
References moa.core.DoubleVector.getValue(), moa.core.DoubleVector.maxIndex(), moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution, and moa.core.DoubleVector.sumOfValues().
Referenced by moa.classifiers.trees.HoeffdingTree.enforceTrackerLimit().
{
            double totalSeen = this.observedClassDistribution.sumOfValues();
            return totalSeen > 0.0 ? (totalSeen - this.observedClassDistribution.getValue(this.observedClassDistribution.maxIndex()))
                    : 0.0;
        }
void moa.classifiers.trees.HoeffdingTree.Node.describeSubtree (HoeffdingTree ht, StringBuilder out, int indent)
Reimplemented in moa.classifiers.trees.HoeffdingTree.SplitNode.
Definition at line 220 of file HoeffdingTree.java.
References moa.classifiers.AbstractClassifier.getClassLabelString(), moa.classifiers.AbstractClassifier.getClassNameString(), moa.core.DoubleVector.getSingleLineDescription(), moa.core.DoubleVector.numValues(), moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution, and moa.classifiers.trees.HoeffdingTree.treeRoot.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.describeSubtree(), and moa.classifiers.trees.HoeffdingTree.Node.getDescription().
{
            StringUtils.appendIndented(out, indent, "Leaf ");
            out.append(ht.getClassNameString());
            out.append(" = ");
            out.append(ht.getClassLabelString(this.observedClassDistribution.maxIndex()));
            out.append(" weights: ");
            this.observedClassDistribution.getSingleLineDescription(out,
                    ht.treeRoot.observedClassDistribution.numValues());
            StringUtils.appendNewline(out);
        }
FoundNode moa.classifiers.trees.HoeffdingTree.Node.filterInstanceToLeaf (Instance inst, SplitNode parent, int parentBranch)
Definition at line 203 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.SplitNode.filterInstanceToLeaf(), moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance(), and moa.classifiers.trees.ASHoeffdingTree.trainOnInstanceImpl().
{
            return new FoundNode(this, parent, parentBranch);
        }
double [] moa.classifiers.trees.HoeffdingTree.Node.getClassVotes (Instance inst, HoeffdingTree ht)
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.trees.HoeffdingTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Definition at line 212 of file HoeffdingTree.java.
References moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingTree.getVotesForInstance(), moa.classifiers.trees.HoeffdingAdaptiveTree.getVotesForInstance(), and moa.classifiers.multilabel.MultilabelHoeffdingTree.getVotesForInstance().
{
            return this.observedClassDistribution.getArrayCopy();
        }
void moa.classifiers.trees.HoeffdingTree.Node.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 243 of file HoeffdingTree.java.
References moa.classifiers.trees.HoeffdingTree.Node.describeSubtree().
{
            describeSubtree(null, sb, indent);
        }
double [] moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution ()
Definition at line 208 of file HoeffdingTree.java.
References moa.core.DoubleVector.getArrayCopy(), and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingTree.activateLearningNode(), moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit(), and moa.classifiers.trees.HoeffdingTree.deactivateLearningNode().
{
            return this.observedClassDistribution.getArrayCopy();
        }
boolean moa.classifiers.trees.HoeffdingTree.Node.isLeaf ()
Reimplemented in moa.classifiers.trees.HoeffdingTree.SplitNode.
Definition at line 199 of file HoeffdingTree.java.
{
            return true;
        }
boolean moa.classifiers.trees.HoeffdingTree.Node.observedClassDistributionIsPure ()
Definition at line 216 of file HoeffdingTree.java.
References moa.core.DoubleVector.numNonZeroEntries(), and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution.
Referenced by moa.classifiers.trees.HoeffdingTree.attemptToSplit(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
{
            return this.observedClassDistribution.numNonZeroEntries() < 2;
        }
int moa.classifiers.trees.HoeffdingTree.Node.subtreeDepth ()
Reimplemented in moa.classifiers.trees.HoeffdingTree.SplitNode.
Definition at line 232 of file HoeffdingTree.java.
{
            return 0;
        }
Member Data Documentation
DoubleVector moa.classifiers.trees.HoeffdingTree.Node.observedClassDistribution [protected]
Definition at line 185 of file HoeffdingTree.java.
Referenced by moa.classifiers.trees.HoeffdingTree.Node.calcByteSize(), moa.classifiers.trees.HoeffdingTree.Node.calculatePromise(), moa.classifiers.trees.HoeffdingTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingTree.Node.getClassVotes(), moa.classifiers.trees.HoeffdingTree.Node.getObservedClassDistribution(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getWeightSeen(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.InactiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.Node.Node(), and moa.classifiers.trees.HoeffdingTree.Node.observedClassDistributionIsPure().
final long moa.classifiers.trees.HoeffdingTree.Node.serialVersionUID = 1L [static, private]
Reimplemented in moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier, moa.classifiers.rules.core.RuleActiveLearningNode, moa.classifiers.rules.core.RuleActiveRegressionNode, moa.classifiers.rules.nodes.RuleSplitNode, moa.classifiers.trees.HoeffdingTree.SplitNode, moa.classifiers.trees.HoeffdingTree.LearningNode, moa.classifiers.trees.HoeffdingTree.InactiveLearningNode, moa.classifiers.trees.HoeffdingTree.ActiveLearningNode, moa.classifiers.trees.HoeffdingTree.LearningNodeNB, and moa.classifiers.trees.HoeffdingTree.LearningNodeNBAdaptive.
Definition at line 183 of file HoeffdingTree.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingTree.java