MOA: moa.AbstractMOAObject Class Reference
moa.AbstractMOAObject Class Reference
Abstract MOA Object.
Public Member Functions
MOAObject copy ()
This method produces a copy of this object.
int measureByteSize ()
Gets the memory size of this object.
String toString ()
Returns a description of the object.
Static Public Member Functions
static MOAObject copy (MOAObject obj)
This method produces a copy of an object.
static int measureByteSize (MOAObject obj)
Gets the memory size of an object.
Detailed Description
Abstract MOA Object.
All classes that are serializable, copiable, can measure its size, and can give a description, extend this class.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file AbstractMOAObject.java.
Member Function Documentation
static MOAObject moa.AbstractMOAObject.copy (MOAObject obj) [static]
This method produces a copy of an object.
Parameters:
obj object to copy
Returns:
a copy of the object
Definition at line 62 of file AbstractMOAObject.java.
{
        try {
            return (MOAObject) SerializeUtils.copyObject(obj);
        } catch (Exception e) {
            throw new RuntimeException("Object copy failed.", e);
        }
    }
MOAObject moa.AbstractMOAObject.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Implements moa.MOAObject.
Reimplemented in moa.classifiers.AbstractClassifier, moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.clusterers.AbstractClusterer, moa.clusterers.denstream.MicroCluster, moa.options.AbstractOption, and moa.options.AbstractOptionHandler.
Definition at line 35 of file AbstractMOAObject.java.
Referenced by moa.clusterers.clustream.WithKmeans.cleanUpKMeans(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.clusterers.KMeans.gaussianMeans(), moa.cluster.SphereCluster.getCenter(), and moa.classifiers.rules.core.RuleActiveLearningNode.newNumericClassObserver().
{
        return copy(this);
    }
static int moa.AbstractMOAObject.measureByteSize (MOAObject obj) [static]
Gets the memory size of an object.
Parameters:
obj object to measure the memory size
Returns:
the memory size of this object
Definition at line 76 of file AbstractMOAObject.java.
{
        return (int) SizeOf.fullSizeOf(obj);
    }
int moa.AbstractMOAObject.measureByteSize ()
Gets the memory size of this object.
Returns:
the memory size of this object
Implements moa.MOAObject.
Reimplemented in moa.classifiers.trees.HoeffdingOptionTree, and moa.classifiers.trees.HoeffdingTree.
Definition at line 40 of file AbstractMOAObject.java.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.calcByteSize(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.calcByteSizeIncludingSubtree(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.clusterers.AbstractClusterer.getModelMeasurements(), and moa.classifiers.AbstractClassifier.getModelMeasurements().
{
        return measureByteSize(this);
    }
String moa.AbstractMOAObject.toString ()
Returns a description of the object.
Returns:
a description of the object
Reimplemented in moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate, moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Definition at line 50 of file AbstractMOAObject.java.
References moa.MOAObject.getDescription().
Referenced by moa.recommender.predictor.BRISMFPredictor.getDescription(), moa.recommender.predictor.BaselinePredictor.getDescription(), moa.core.Measurement.getMeasurementsDescription(), and moa.classifiers.rules.core.Rule.printRule().
{
        StringBuilder sb = new StringBuilder();
        getDescription(sb, 0);
        return sb.toString();
    }
The documentation for this class was generated from the following file:
main/java/moa/AbstractMOAObject.java