MOA: moa.classifiers.rules.RuleClassifierNBayes Class Reference
moa.classifiers.rules.RuleClassifierNBayes Class Reference
This classifier learn ordered and unordered rule set from data stream with naive Bayes learners.
Public Member Functions
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
Public Attributes
IntOption nbThresholdOption
Protected Member Functions
double[] firstHitNB (Instance inst)
double[] weightedMaxNB (Instance inst)
double[] weightedSumNB (Instance inst)
double[] normalize (double[] votes)
double[] exponential (double[] votes)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This classifier learn ordered and unordered rule set from data stream with naive Bayes learners.
This algorithm also does the detection of anomalies.
Learning Decision RuleClassifications from Data Streams, IJCAI 2011, J. Gama, P. Kosina
Parameters:
-q: The number of instances a leaf should observe before permitting Naive Bayes.
-p: Minimum value of p
-t: Tie Threshold
-c: Split Confidence
-g: GracePeriod, the number of instances a leaf should observe between split attempts
-o: Prediction function to use. Ex:FirstHit
-r: Learn ordered or unordered rule
Author:
P. Kosina, E. Almeida, J. Gama
Version:
Revision
2
Definition at line 50 of file RuleClassifierNBayes.java.
Member Function Documentation
double [] moa.classifiers.rules.RuleClassifierNBayes.exponential (double[] votes) [protected]
Definition at line 236 of file RuleClassifierNBayes.java.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
{
        for (int i = 0; i < votes.length; i++) {
            votes[i] = Math.exp(votes[i]);
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifierNBayes.firstHitNB (Instance inst) [protected]
Definition at line 78 of file RuleClassifierNBayes.java.
References moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, moa.classifiers.rules.RuleClassifierNBayes.exponential(), moa.options.IntOption.getValue(), moa.classifiers.rules.RuleClassifierNBayes.nbThresholdOption, moa.classifiers.rules.RuleClassifierNBayes.normalize(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.getVotesForInstance().
{
        int countFired = 0;
        boolean fired = false;
        double[] votes = new double[this.numClass];
        for (int j = 0; j < this.ruleSet.size(); j++) {
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired + 1;
                if (this.ruleSet.get(j).obserClassDistrib.sumOfValues() >= this.nbThresholdOption.getValue()) {
                    votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.ruleSet.get(j).obserClassDistrib, this.ruleSet.get(j).observers, this.ruleSet.get(j).observersGauss);
                    votes = exponential(votes);
                    votes = normalize(votes);
                    } else {
                        for (int z = 0; z < this.numClass; z++) {
                            votes[z] = this.ruleSet.get(j).obserClassDistrib.getValue(z)
                                    / this.ruleSet.get(j).obserClassDistrib.sumOfValues();
                            }
                        }
                break;
                }
            }
        if (countFired > 0) {
            fired = true;
            } else {
                fired = false;
                }
        if (fired == false) {
            if (super.getWeightSeen() >= this.nbThresholdOption.getValue()) {
                votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.observedClassDistribution, this.attributeObservers, this.attributeObserversGauss);
                votes = exponential(votes);
                votes = normalize(votes);
                } else {
                    votes = super.oberversDistribProb(inst, this.observedClassDistribution);
                    }
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifierNBayes.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Reimplemented from moa.classifiers.rules.RuleClassifier.
Definition at line 61 of file RuleClassifierNBayes.java.
References moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
{
        double[] votes = new double[numClass];
        switch (super.predictionFunctionOption.getChosenIndex()) {
        case 0:
            votes = firstHitNB(inst);
            break;
        case 1:
            votes = weightedSumNB(inst);
            break;
        case 2:
            votes = weightedMaxNB(inst);
            break;
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifierNBayes.normalize (double[] votes) [protected]
Definition at line 225 of file RuleClassifierNBayes.java.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
{
        double sum=0;
        for (int i = 0; i < votes.length; i++) {
            sum = sum + votes[i];
            }
        for (int j = 0; j < votes.length; j++) {
            votes[j] = votes[j] / sum;
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB (Instance inst) [protected]
Definition at line 115 of file RuleClassifierNBayes.java.
References moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, moa.classifiers.rules.RuleClassifierNBayes.exponential(), moa.options.IntOption.getValue(), moa.classifiers.rules.RuleClassifierNBayes.nbThresholdOption, moa.classifiers.rules.RuleClassifierNBayes.normalize(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.getVotesForInstance().
{
        int countFired = 0;
        int count = 0;
        boolean fired = false;
        double highest = 0.0;
        double[] votes = new double[this.numClass];
        ArrayList<Double> ruleSetVotes = new ArrayList<Double>();
        ArrayList<ArrayList<Double>> majorityProb = new ArrayList<ArrayList<Double>>();
        for (int j = 0; j < this.ruleSet.size(); j++) {
            ArrayList<Double> ruleClassDistribProb=new ArrayList<Double>();
            if(this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired + 1;
                if (this.ruleSet.get(j).obserClassDistrib.sumOfValues() >= this.nbThresholdOption.getValue()) {
                    votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.ruleSet.get(j).obserClassDistrib, this.ruleSet.get(j).observers, this.ruleSet.get(j).observersGauss);
                    votes = exponential(votes);
                    votes = normalize(votes);
                    } else {
                        count = count + 1;
                        for (int z = 0; z < this.numClass; z++){
                            ruleSetVotes.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                            ruleClassDistribProb.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                            }
                        majorityProb.add(ruleClassDistribProb);
                        }
                }
            }
        if (count > 0) {
            Collections.sort(ruleSetVotes);
            highest = ruleSetVotes.get(ruleSetVotes.size() - 1);
            for (int t = 0; t < majorityProb.size(); t++) {
                for (int m = 0; m < majorityProb.get(t).size(); m++) {
                    if(majorityProb.get(t).get(m) == highest){
                        for(int h = 0; h < majorityProb.get(t).size(); h++){
                            votes[h]=majorityProb.get(t).get(h);
                            }
                        break;
                        }
                    }
                }
            }
        if (countFired > 0) {
            fired=true;
            }  else {
                fired=false;
                }
        if (fired == false) {
            if(super.getWeightSeen() >= this.nbThresholdOption.getValue()) {
                votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.observedClassDistribution, this.attributeObservers, this.attributeObserversGauss);
                votes = exponential(votes);
                votes = normalize(votes);
                } else {
                    votes = super.oberversDistribProb(inst, this.observedClassDistribution);
                    }
            }
        return votes;
        }
double [] moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB (Instance inst) [protected]
Definition at line 172 of file RuleClassifierNBayes.java.
References moa.classifiers.rules.RuleClassifier.attributeObservers, moa.classifiers.rules.RuleClassifier.attributeObserversGauss, moa.classifiers.rules.RuleClassifierNBayes.exponential(), moa.options.IntOption.getValue(), moa.classifiers.rules.RuleClassifierNBayes.nbThresholdOption, moa.classifiers.rules.RuleClassifierNBayes.normalize(), moa.classifiers.rules.RuleClassifier.numClass, moa.classifiers.rules.RuleClassifier.observedClassDistribution, and moa.classifiers.rules.RuleClassifier.ruleSet.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.getVotesForInstance().
{
        int countFired = 0;
        int count = 0;
        boolean fired = false;
        double[] votes = new double[this.numClass];
        ArrayList<Double> weightSum = new ArrayList<Double>();
        ArrayList<ArrayList<Double>> majorityProb = new ArrayList<ArrayList<Double>>();
        for ( int j = 0; j < this.ruleSet.size(); j++) {
            ArrayList<Double> ruleClassDistribProb=new ArrayList<Double>();
            if (this.ruleSet.get(j).ruleEvaluate(inst) == true) {
                countFired = countFired + 1;
                if (this.ruleSet.get(j).obserClassDistrib.sumOfValues() >= this.nbThresholdOption.getValue()) {
                    votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.ruleSet.get(j).obserClassDistrib, ruleSet.get(j).observers, this.ruleSet.get(j).observersGauss);
                    votes = exponential(votes);
                    votes = normalize(votes);
                    } else {
                        count=count+1;
                        for (int z = 0; z < this.numClass; z++) {
                            ruleClassDistribProb.add(this.ruleSet.get(j).obserClassDistrib.getValue(z) / this.ruleSet.get(j).obserClassDistrib.sumOfValues());
                            }
                        majorityProb.add(ruleClassDistribProb);
                        }
                }
            }
         if(count > 0) {
             for (int m = 0; m < majorityProb.get(0).size(); m++) {
                 double sum = 0.0;
                 for (int t = 0; t < majorityProb.size(); t++){
                     sum = sum + majorityProb.get(t).get(m);
                     }
                 weightSum.add(sum);
                 }
             for (int h = 0; h < weightSum.size(); h++) {
                 votes[h] = weightSum.get(h) / majorityProb.size();
                 }
             }
         if(countFired>0){
             fired = true;
             } else {
                 fired=false;
                 }
         if (fired == false) {
             if (super.getWeightSeen() >= this.nbThresholdOption.getValue()) {
                 votes = NaiveBayes.doNaiveBayesPredictionLog(inst, this.observedClassDistribution, this.attributeObservers, this.attributeObserversGauss);
                 votes = exponential(votes);
                 votes = normalize(votes);
                 } else {
                     votes = super.oberversDistribProb(inst, this.observedClassDistribution);
                     }
             }
         return votes;
         }
Member Data Documentation
IntOption moa.classifiers.rules.RuleClassifierNBayes.nbThresholdOption
Initial value:
 new IntOption(
            "nbThreshold",
            'q',
            "The number of instances a leaf should observe before permitting Naive Bayes.",
            0, 0, Integer.MAX_VALUE)
Definition at line 54 of file RuleClassifierNBayes.java.
Referenced by moa.classifiers.rules.RuleClassifierNBayes.firstHitNB(), moa.classifiers.rules.RuleClassifierNBayes.weightedMaxNB(), and moa.classifiers.rules.RuleClassifierNBayes.weightedSumNB().
final long moa.classifiers.rules.RuleClassifierNBayes.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.rules.RuleClassifier.
Definition at line 52 of file RuleClassifierNBayes.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/RuleClassifierNBayes.java