MOA: moa.classifiers.rules.core.Rule.Builder Class Reference
moa.classifiers.rules.core.Rule.Builder Class Reference
Public Member Functions
AbstractAMRules getAMRules ()
Builder ()
Builder changeDetection (boolean changeDetection)
Builder threshold (double threshold)
Builder alpha (double alpha)
Builder predictionFunction (int predictionFunction)
Builder statistics (double[] statistics)
Builder owner (Rule owner)
Builder amRules (AbstractAMRules amRules)
Builder id (int id)
Rule build ()
Rule getOwner ()
void setOwner (Rule owner)
Public Attributes
FlagOption constantLearningRatioDecayOption
FloatOption learningRatioOption
int id
AbstractAMRules amRules
Protected Attributes
boolean changeDetection
boolean usePerceptron
double threshold
double alpha
int predictionFunction
double[] statistics
double lastTargetMean
Private Attributes
Rule owner
Static Private Attributes
static final long serialVersionUID = 1712887264918475622L
Detailed Description
Definition at line 139 of file Rule.java.
Constructor & Destructor Documentation
moa.classifiers.rules.core.Rule.Builder.Builder ()
Definition at line 162 of file Rule.java.
{
        }
Member Function Documentation
Builder moa.classifiers.rules.core.Rule.Builder.alpha (double alpha)
Definition at line 175 of file Rule.java.
{
            this.alpha = alpha;
            return this;
        }
Builder moa.classifiers.rules.core.Rule.Builder.amRules (AbstractAMRules amRules)
Definition at line 195 of file Rule.java.
{
            this.amRules = amRules;
            return this;
        }
Rule moa.classifiers.rules.core.Rule.Builder.build ()
Definition at line 204 of file Rule.java.
References moa.classifiers.rules.core.Rule.Rule().
{
            return new Rule(this);
        }
Builder moa.classifiers.rules.core.Rule.Builder.changeDetection (boolean changeDetection)
Definition at line 165 of file Rule.java.
{
            this.changeDetection = changeDetection;
            return this;
        }
AbstractAMRules moa.classifiers.rules.core.Rule.Builder.getAMRules ()
Definition at line 158 of file Rule.java.
References moa.classifiers.rules.core.Rule.Builder.amRules.
Referenced by moa.classifiers.rules.core.Rule.Rule().
{
            return amRules;
        }
Rule moa.classifiers.rules.core.Rule.Builder.getOwner ()
Definition at line 208 of file Rule.java.
References moa.classifiers.rules.core.Rule.Builder.owner.
{
            return owner;
        }
Builder moa.classifiers.rules.core.Rule.Builder.id (int id)
Definition at line 200 of file Rule.java.
{
            this.id = id;
            return this;
        }
Builder moa.classifiers.rules.core.Rule.Builder.owner (Rule owner)
Definition at line 190 of file Rule.java.
References moa.classifiers.rules.core.Rule.Builder.setOwner().
{
            this.setOwner(owner);
            return this;
        }
Builder moa.classifiers.rules.core.Rule.Builder.predictionFunction (int predictionFunction)
Definition at line 180 of file Rule.java.
{
            this.predictionFunction = predictionFunction;
            return this;
        }
void moa.classifiers.rules.core.Rule.Builder.setOwner (Rule owner)
Definition at line 212 of file Rule.java.
Referenced by moa.classifiers.rules.AMRulesRegressor.newRule(), moa.classifiers.rules.core.Rule.Builder.owner(), and moa.classifiers.rules.core.Rule.Rule().
{
            this.owner = owner;
        }
Builder moa.classifiers.rules.core.Rule.Builder.statistics (double[] statistics)
Definition at line 185 of file Rule.java.
{
            this.statistics = statistics;
            return this;
        }
Builder moa.classifiers.rules.core.Rule.Builder.threshold (double threshold)
Definition at line 170 of file Rule.java.
{
            this.threshold = threshold;
            return this;
        }
Member Data Documentation
double moa.classifiers.rules.core.Rule.Builder.alpha [protected]
Definition at line 145 of file Rule.java.
AbstractAMRules moa.classifiers.rules.core.Rule.Builder.amRules
Definition at line 156 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.Builder.getAMRules().
boolean moa.classifiers.rules.core.Rule.Builder.changeDetection [protected]
Definition at line 142 of file Rule.java.
FlagOption moa.classifiers.rules.core.Rule.Builder.constantLearningRatioDecayOption
Definition at line 153 of file Rule.java.
int moa.classifiers.rules.core.Rule.Builder.id
Definition at line 155 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.Rule().
double moa.classifiers.rules.core.Rule.Builder.lastTargetMean [protected]
Definition at line 150 of file Rule.java.
FloatOption moa.classifiers.rules.core.Rule.Builder.learningRatioOption
Definition at line 154 of file Rule.java.
Rule moa.classifiers.rules.core.Rule.Builder.owner [private]
Definition at line 151 of file Rule.java.
Referenced by moa.classifiers.rules.core.Rule.Builder.getOwner().
int moa.classifiers.rules.core.Rule.Builder.predictionFunction [protected]
Definition at line 146 of file Rule.java.
final long moa.classifiers.rules.core.Rule.Builder.serialVersionUID = 1712887264918475622L [static, private]
Definition at line 141 of file Rule.java.
double [] moa.classifiers.rules.core.Rule.Builder.statistics [protected]
Definition at line 148 of file Rule.java.
double moa.classifiers.rules.core.Rule.Builder.threshold [protected]
Definition at line 144 of file Rule.java.
boolean moa.classifiers.rules.core.Rule.Builder.usePerceptron [protected]
Definition at line 143 of file Rule.java.
The documentation for this class was generated from the following file:
main/java/moa/classifiers/rules/core/Rule.java