MOA: moa.clusterers.outliers.MyBaseOutlierDetector Class Reference
moa.clusterers.outliers.MyBaseOutlierDetector Class Reference
Classes
class MyProgressInfo
class Outlier
class OutlierNotifier
interface PrintMsg
interface ProgressInfo
class StdPrintMsg
Public Member Functions
double getTimePerObj ()
String getObjectInfo (Object obj)
String getStatistics ()
double[] getInstanceValues (Instance inst)
void PrintInstance (Instance inst)
void resetLearningImpl ()
void trainOnInstanceImpl (Instance inst)
void processNewInstanceImpl (Instance inst)
void PrintOutliers ()
Set< Outlier > GetOutliersFound ()
Clustering getClusteringResult ()
Vector< Outlier > getOutliersResult ()
boolean implementsMicroClusterer ()
Clustering getMicroClusteringResult ()
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
boolean keepClassLabel ()
double[] getVotesForInstance (Instance inst)
void SetShowProgress (boolean b)
void SetTrace (boolean b)
void SetProgressInterval (int iProgressInterval)
void SetMessagePrinter (PrintMsg logPrinter)
void SetUserInfo (boolean bShowProgress, boolean bTrace, PrintMsg logPrinter, int iProgressInterval)
Public Attributes
IntOption windowSizeOption = new IntOption("windowSize", 'w', "Size of the window.", 1000)
OutlierNotifier outlierNotifier = null
boolean bStopAlgorithm = false
Protected Member Functions
void UpdateMaxMemUsage ()
void Init ()
void ProcessNewStreamObj (Instance inst)
boolean IsNodeIdInWin (long id)
void AddOutlier (Outlier newOutlier)
boolean RemoveExpiredOutlier (Outlier outlier)
boolean RemoveOutlier (Outlier outlier)
Measurement[] getModelMeasurementsImpl ()
void ShowProgress (String sMsg)
void ShowProgress (String sMsg, boolean bShowAlways)
void Println (String s)
void Print (String s)
void Printf (String fmt, Object...args)
int GetMemoryUsage ()
Protected Attributes
Random random
int iMaxMemUsage = 0
int nRangeQueriesExecuted = 0
Long nTotalRunTime = 0L
double nTimePerObj
ProgressInfo myProgressInfo
PrintMsg myOut
boolean bTrace = false
boolean bShowProgress = false
Private Member Functions
void ShowTimePerObj ()
Private Attributes
Clustering myClusters = null
TreeSet< Outlier > outliersFound
Long m_timePreObjSum
int nProcessed
Long _msPrev = 0L
Long _msNow = 0L
Static Private Attributes
static final int m_timePreObjInterval = 100
Detailed Description
Definition at line 38 of file MyBaseOutlierDetector.java.
Member Function Documentation
void moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier (Outlier newOutlier) [protected]
Definition at line 223 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.OutlierNotifier.OnOutlier(), moa.clusterers.outliers.MyBaseOutlierDetector.outlierNotifier, and moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.SaveOutlier(), moa.clusterers.outliers.MCOD.MCODBase.SaveOutlier(), moa.clusterers.outliers.Angiulli.STORMBase.SaveOutlier(), and moa.clusterers.outliers.AbstractC.AbstractCBase.SaveOutlier().
{
        boolean bNewAdd = outliersFound.add(newOutlier);
        if ((outlierNotifier != null) && bNewAdd) {
            outlierNotifier.OnOutlier(newOutlier);
        }
    }
Clustering moa.clusterers.outliers.MyBaseOutlierDetector.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 198 of file MyBaseOutlierDetector.java.
References moa.cluster.Clustering.add(), moa.clusterers.outliers.MyBaseOutlierDetector.IsNodeIdInWin(), moa.clusterers.outliers.MyBaseOutlierDetector.myClusters, and moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
{
        myClusters = new Clustering();
        for (Outlier o : outliersFound) {
            if (IsNodeIdInWin(o.id)) {
                double[] center = new double[o.inst.numValues() - 1];
                for (int i = 0; i < o.inst.numValues() - 1; i++) {
                    center[i] = o.inst.value(i);
                }
                Cluster c = new SphereCluster(center, 0);
                myClusters.add(c);
            }
        }
        return myClusters;
    }
double [] moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues (Instance inst)
Definition at line 109 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        double[] values = new double[inst.numValues() - 1]; // last attribute is the class
        for (int i = 0; i < inst.numValues() - 1; i++) {
            values[i] = inst.value(i);
        }
        return values;
    }
int moa.clusterers.outliers.MyBaseOutlierDetector.GetMemoryUsage () [protected]
Definition at line 468 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.UpdateMaxMemUsage().
{
        int iMemory = (int) ((Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / (1024 * 1024));
        return iMemory;
    }
Clustering moa.clusterers.outliers.MyBaseOutlierDetector.getMicroClusteringResult ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 249 of file MyBaseOutlierDetector.java.
{
        return null;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 259 of file MyBaseOutlierDetector.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
Measurement [] moa.clusterers.outliers.MyBaseOutlierDetector.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 254 of file MyBaseOutlierDetector.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
String moa.clusterers.outliers.MyBaseOutlierDetector.getObjectInfo (Object obj)
Reimplemented in moa.clusterers.outliers.AbstractC.AbstractCBase, moa.clusterers.outliers.Angiulli.ApproxSTORM, moa.clusterers.outliers.Angiulli.ExactSTORM, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MCOD.MCODBase, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.
Definition at line 101 of file MyBaseOutlierDetector.java.
Referenced by moa.gui.visualization.OutlierPanel.getInfo().
{
        throw new UnsupportedOperationException("Not yet implemented");
    }
Set<Outlier> moa.clusterers.outliers.MyBaseOutlierDetector.GetOutliersFound ()
Definition at line 189 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
{
        return outliersFound;
    }
Vector<Outlier> moa.clusterers.outliers.MyBaseOutlierDetector.getOutliersResult ()
Definition at line 213 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.IsNodeIdInWin(), and moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
Referenced by moa.gui.visualization.RunOutlierVisualizer.drawOutliers().
{
        Vector<Outlier> outliers = new Vector<Outlier>();
        for (Outlier o : outliersFound) {
            if (IsNodeIdInWin(o.id)) {
                outliers.add(o);
            }
        }
        return outliers;
    }
String moa.clusterers.outliers.MyBaseOutlierDetector.getStatistics ()
Reimplemented in moa.clusterers.outliers.AbstractC.AbstractCBase, moa.clusterers.outliers.Angiulli.STORMBase, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MCOD.MCODBase, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.
Definition at line 105 of file MyBaseOutlierDetector.java.
{
        throw new UnsupportedOperationException("Not yet implemented");
    }
double moa.clusterers.outliers.MyBaseOutlierDetector.getTimePerObj ()
Definition at line 97 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.nTimePerObj.
{
        return nTimePerObj;
    }
double [] moa.clusterers.outliers.MyBaseOutlierDetector.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 274 of file MyBaseOutlierDetector.java.
{
        return null;
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.implementsMicroClusterer ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 244 of file MyBaseOutlierDetector.java.
{
        return false;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.Init () [protected]
Reimplemented in moa.clusterers.outliers.AbstractC.AbstractC, moa.clusterers.outliers.Angiulli.ApproxSTORM, moa.clusterers.outliers.Angiulli.ExactSTORM, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MCOD.MCOD, and moa.clusterers.outliers.SimpleCOD.SimpleCOD.
Definition at line 131 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.m_timePreObjSum, moa.clusterers.outliers.MyBaseOutlierDetector.nProcessed, moa.clusterers.outliers.MyBaseOutlierDetector.nTimePerObj, moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound, moa.clusterers.outliers.MyBaseOutlierDetector.random, moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg.RedirectToDisplay(), and moa.clusterers.outliers.MyBaseOutlierDetector.SetUserInfo().
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.resetLearningImpl().
{
        random = new Random(System.currentTimeMillis());
        outliersFound = new TreeSet<Outlier>();
        m_timePreObjSum = 0L;
        nProcessed = 0;
        nTimePerObj = 0L;
        StdPrintMsg printer = new StdPrintMsg();
        printer.RedirectToDisplay();
        //timePerObjInfo = new MyTimePerObjInfo();
        //timePerObjInfo.Init();
        SetUserInfo(true, false, printer, 1000);
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.IsNodeIdInWin (long id) [protected]
Reimplemented in moa.clusterers.outliers.AbstractC.AbstractCBase, moa.clusterers.outliers.Angiulli.STORMBase, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MCOD.MCODBase, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.
Definition at line 193 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.getClusteringResult(), and moa.clusterers.outliers.MyBaseOutlierDetector.getOutliersResult().
{
        throw new UnsupportedOperationException("Not yet implemented");
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 264 of file MyBaseOutlierDetector.java.
{
        return false;
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.keepClassLabel ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 269 of file MyBaseOutlierDetector.java.
{
        return true;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.Print (String s) [protected]
Definition at line 458 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myOut, and moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.print().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.Print_lt_cnt(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintInstance(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintISB(), moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode(), moa.clusterers.outliers.MCOD.MCODBase.PrintNode(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintNode(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeList(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeSet(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeSet(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeVector(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeVector(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.PrintPrecNeighs(), moa.clusterers.outliers.Angiulli.ApproxSTORM.PrintSafeInliers(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        if (myOut != null)
            myOut.print(s);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.Printf (String fmt, Object... args) [protected]
Definition at line 463 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myOut, and moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.printf().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue(), moa.clusterers.outliers.MCOD.MCODBase.PrintEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintInstance(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        if (myOut != null)
            myOut.printf(fmt, args);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.PrintInstance (Instance inst)
Definition at line 117 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
{
        Print("instance: [ ");
        for (int i = 0; i < inst.numValues() - 1; i++) { // last value is the class
            Printf("%.2f ", inst.value(i));
        }
        Print("] ");
        Println("");
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.Println (String s) [protected]
Definition at line 453 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myOut, and moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.println().
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns(), moa.clusterers.outliers.AbstractC.AbstractCBase.Print_lt_cnt(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue(), moa.clusterers.outliers.MCOD.MCODBase.PrintEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintInstance(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintISB(), moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode(), moa.clusterers.outliers.MCOD.MCODBase.PrintNode(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintNode(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeList(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeSet(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeSet(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeVector(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeVector(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), moa.clusterers.outliers.Angiulli.ExactSTORM.ISBNodeExact.PrintPrecNeighs(), moa.clusterers.outliers.Angiulli.ApproxSTORM.PrintSafeInliers(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.AbstractC.AbstractCBase.PrintWindow(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.ShowTimePerObj(), moa.clusterers.outliers.AbstractC.AbstractC.UpdateNeighbors(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
{
        if (myOut != null)
            myOut.println(s);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers ()
Definition at line 181 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
{
        Print("Outliers: ");
        for (Outlier o : outliersFound) {
            Printf("[%d] ", o.id);
        }
        Println("");
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl (Instance inst)
Definition at line 153 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.m_timePreObjInterval, moa.clusterers.outliers.MyBaseOutlierDetector.m_timePreObjSum, moa.clusterers.outliers.MyBaseOutlierDetector.nProcessed, moa.clusterers.outliers.MyBaseOutlierDetector.nTimePerObj, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, moa.clusterers.outliers.MyBaseOutlierDetector.ProcessNewStreamObj(), moa.clusterers.outliers.MyBaseOutlierDetector.ShowTimePerObj(), and moa.clusterers.outliers.MyBaseOutlierDetector.UpdateMaxMemUsage().
Referenced by moa.clusterers.outliers.TestSpeed.main(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), moa.clusterers.outliers.AbstractC.Test.main(), moa.gui.visualization.RunOutlierVisualizer.MeasuredProcessStreamObj(), and moa.clusterers.outliers.MyBaseOutlierDetector.trainOnInstanceImpl().
{
        Long nsNow = System.nanoTime();
        ProcessNewStreamObj(inst);
        UpdateMaxMemUsage();
        nTotalRunTime += (System.nanoTime() - nsNow) / (1024 * 1024);
        // update process time per object
        nProcessed++;
        m_timePreObjSum += System.nanoTime() - nsNow;
        if (nProcessed % m_timePreObjInterval == 0) {
            nTimePerObj = ((double) m_timePreObjSum) / ((double) m_timePreObjInterval);
            if (bShowProgress) ShowTimePerObj();
            // init
            m_timePreObjSum = 0L;
        }
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented in moa.clusterers.outliers.AbstractC.AbstractC, moa.clusterers.outliers.Angiulli.ApproxSTORM, moa.clusterers.outliers.Angiulli.ExactSTORM, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.outliers.MCOD.MCOD, and moa.clusterers.outliers.SimpleCOD.SimpleCOD.
Definition at line 177 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
{
        throw new UnsupportedOperationException("Not yet implemented");
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier (Outlier outlier) [protected]
Definition at line 230 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveNode(), moa.clusterers.outliers.MCOD.MCODBase.RemoveNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.RemoveNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), and moa.clusterers.outliers.AbstractC.AbstractCBase.RemoveNode().
{
        boolean bFound = outliersFound.remove(outlier);
        return bFound;
    }
boolean moa.clusterers.outliers.MyBaseOutlierDetector.RemoveOutlier (Outlier outlier) [protected]
Definition at line 235 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.OutlierNotifier.OnInlier(), moa.clusterers.outliers.MyBaseOutlierDetector.outlierNotifier, and moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound.
Referenced by moa.clusterers.outliers.AnyOut.AnyOut.ProcessNewStreamObj().
{
        boolean bFound = outliersFound.remove(outlier);
        if ((outlierNotifier != null) && bFound) {
            outlierNotifier.OnInlier(outlier);
        }
        return bFound;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Reimplemented in moa.clusterers.outliers.AnyOut.AnyOut.
Definition at line 127 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Init().
{
        Init();
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.SetMessagePrinter (PrintMsg logPrinter)
Definition at line 299 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myOut.
{
        myOut = logPrinter;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.SetProgressInterval (int iProgressInterval)
Definition at line 295 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myProgressInfo.
{
        myProgressInfo = new MyProgressInfo(iProgressInterval);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.SetShowProgress (boolean b)
Definition at line 287 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress.
{
        bShowProgress = b;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.SetTrace (boolean b)
Definition at line 291 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace.
{
        bTrace = b;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.SetUserInfo (boolean bShowProgress, boolean bTrace, PrintMsg logPrinter, int iProgressInterval)
Definition at line 303 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.myOut, and moa.clusterers.outliers.MyBaseOutlierDetector.myProgressInfo.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Init(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
    {
        this.bShowProgress = bShowProgress;
        this.bTrace = bTrace;
        myProgressInfo = new MyProgressInfo(iProgressInterval);
        myOut = logPrinter;
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress (String sMsg, boolean bShowAlways) [protected]
Definition at line 397 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector._msNow, moa.clusterers.outliers.MyBaseOutlierDetector._msPrev, moa.clusterers.outliers.MyBaseOutlierDetector.ProgressInfo.GetInterval(), moa.clusterers.outliers.MyBaseOutlierDetector.myProgressInfo, and moa.clusterers.outliers.MyBaseOutlierDetector.ProgressInfo.ShowProgress().
{
        if (bShowAlways || (_msNow - _msPrev >= myProgressInfo.GetInterval())) {
            // call user progress function
            myProgressInfo.ShowProgress(sMsg);
            _msNow = System.currentTimeMillis();
            _msPrev = _msNow;
        } else {
            _msNow = System.currentTimeMillis();
        }
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress (String sMsg) [protected]
Definition at line 392 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
    {
        ShowProgress(sMsg, false);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.ShowTimePerObj () [private]
Definition at line 172 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.nTimePerObj, and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
{
        double ms = nTimePerObj / (1000.0 * 1000.0);
        Println("Process time per object (ms): " + String.format("%.3f", ms));
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.trainOnInstanceImpl (Instance inst) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 149 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
{
        processNewInstanceImpl(inst);
    }
void moa.clusterers.outliers.MyBaseOutlierDetector.UpdateMaxMemUsage () [protected]
Definition at line 92 of file MyBaseOutlierDetector.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.GetMemoryUsage(), and moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
{
        int x = GetMemoryUsage();
        if (iMaxMemUsage < x) iMaxMemUsage = x;
    }
Member Data Documentation
Long moa.clusterers.outliers.MyBaseOutlierDetector._msNow = 0L [private]
Definition at line 285 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress().
Long moa.clusterers.outliers.MyBaseOutlierDetector._msPrev = 0L [private]
Definition at line 285 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress().
boolean moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress = false [protected]
Definition at line 282 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), and moa.clusterers.outliers.MyBaseOutlierDetector.SetShowProgress().
boolean moa.clusterers.outliers.MyBaseOutlierDetector.bStopAlgorithm = false
Definition at line 283 of file MyBaseOutlierDetector.java.
boolean moa.clusterers.outliers.MyBaseOutlierDetector.bTrace = false [protected]
Definition at line 281 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.Angiulli.ExactSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.AbstractC.AbstractC.OutputPatterns(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ExactSTORM.SearchOutliers(), moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.SetTrace(), moa.clusterers.outliers.AbstractC.AbstractC.UpdateNeighbors(), moa.clusterers.outliers.Angiulli.ExactSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType().
int moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage = 0 [protected]
Definition at line 81 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.AnyOut.AnyOut.getStatistics(), moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), and moa.clusterers.outliers.MyBaseOutlierDetector.UpdateMaxMemUsage().
final int moa.clusterers.outliers.MyBaseOutlierDetector.m_timePreObjInterval = 100 [static, private]
Definition at line 90 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
Long moa.clusterers.outliers.MyBaseOutlierDetector.m_timePreObjSum [private]
Definition at line 88 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Init(), and moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
Clustering moa.clusterers.outliers.MyBaseOutlierDetector.myClusters = null [private]
Definition at line 86 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.getClusteringResult().
PrintMsg moa.clusterers.outliers.MyBaseOutlierDetector.myOut [protected]
Definition at line 280 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MyBaseOutlierDetector.SetMessagePrinter(), moa.clusterers.outliers.MyBaseOutlierDetector.SetUserInfo(), and moa.clusterers.outliers.MyBaseOutlierDetector.MyProgressInfo.ShowProgress().
ProgressInfo moa.clusterers.outliers.MyBaseOutlierDetector.myProgressInfo [protected]
Definition at line 279 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.SetProgressInterval(), moa.clusterers.outliers.MyBaseOutlierDetector.SetUserInfo(), and moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress().
int moa.clusterers.outliers.MyBaseOutlierDetector.nProcessed [private]
Definition at line 89 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Init(), and moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
int moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted = 0 [protected]
Definition at line 82 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.Angiulli.ExactSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), and moa.clusterers.outliers.AbstractC.AbstractC.ProcessNewStreamObj().
double moa.clusterers.outliers.MyBaseOutlierDetector.nTimePerObj [protected]
Definition at line 84 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.getTimePerObj(), moa.clusterers.outliers.MyBaseOutlierDetector.Init(), moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl(), and moa.clusterers.outliers.MyBaseOutlierDetector.ShowTimePerObj().
Long moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime = 0L [protected]
Definition at line 83 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.MCOD.MCODBase.getStatistics(), moa.clusterers.outliers.AnyOut.AnyOut.getStatistics(), moa.clusterers.outliers.Angiulli.STORMBase.getStatistics(), moa.clusterers.outliers.AbstractC.AbstractCBase.getStatistics(), and moa.clusterers.outliers.MyBaseOutlierDetector.processNewInstanceImpl().
OutlierNotifier moa.clusterers.outliers.MyBaseOutlierDetector.outlierNotifier = null
Definition at line 78 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveOutlier(), and moa.gui.visualization.RunOutlierVisualizer.RunOutlierVisualizer().
TreeSet<Outlier> moa.clusterers.outliers.MyBaseOutlierDetector.outliersFound [private]
Definition at line 87 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.MyBaseOutlierDetector.getClusteringResult(), moa.clusterers.outliers.MyBaseOutlierDetector.GetOutliersFound(), moa.clusterers.outliers.MyBaseOutlierDetector.getOutliersResult(), moa.clusterers.outliers.MyBaseOutlierDetector.Init(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), and moa.clusterers.outliers.MyBaseOutlierDetector.RemoveOutlier().
Random moa.clusterers.outliers.MyBaseOutlierDetector.random [protected]
Definition at line 80 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Init().
IntOption moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption = new IntOption("windowSize", 'w', "Size of the window.", 1000)
Definition at line 76 of file MyBaseOutlierDetector.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.MCOD.MCOD.Init(), moa.clusterers.outliers.Angiulli.ExactSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.AbstractC.AbstractC.Init(), moa.clusterers.outliers.SimpleCOD.Test.main(), moa.clusterers.outliers.MCOD.Test.main(), moa.clusterers.outliers.Angiulli.Test.main(), and moa.clusterers.outliers.AbstractC.Test.main().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MyBaseOutlierDetector.java