MOA: moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg Class Reference
moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg Class Reference
Public Member Functions
void println (String s)
void print (String s)
void printf (String fmt, Object...args)
Detailed Description
Definition at line 148 of file RunOutlierVisualizer.java.
Member Function Documentation
void moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.print (String s)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 155 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), and moa.gui.visualization.RunOutlierVisualizer.m_logPanel.
{
            m_logPanel.addText(s);
        }
void moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.printf (String fmt, Object... args)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 160 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), and moa.gui.visualization.RunOutlierVisualizer.m_logPanel.
{
            m_logPanel.addText(String.format(fmt, args));
        }
void moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.println (String s)
Implements moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.
Definition at line 150 of file RunOutlierVisualizer.java.
References moa.gui.TextViewerPanel.addText(), and moa.gui.visualization.RunOutlierVisualizer.m_logPanel.
{
            m_logPanel.addText(s);
        }
The documentation for this class was generated from the following file:
main/java/moa/gui/visualization/RunOutlierVisualizer.java