MOA: moa.classifiers.core.driftdetection.HDDM_W_Test Class Reference
moa.classifiers.core.driftdetection.HDDM_W_Test Class Reference
Classes
class SampleInfo
Public Member Functions
HDDM_W_Test ()
void resetLearning ()
Resets this change detector.
void input (boolean prediction)
void input (double value)
Adding a numeric value to the change detector<br>
.
boolean detectMeanIncrement (SampleInfo sample1, SampleInfo sample2, double confidence)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
Public Attributes
FloatOption driftConfidenceOption
FloatOption warningConfidenceOption
FloatOption lambdaOption
MultiChoiceOption oneSidedTestOption
Protected Member Functions
boolean monitorMeanIncr (double valor, double confidence)
boolean monitorMeanDecr (double valor, double confidence)
void prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository)
This method describes the implementation of how to prepare this object for use.
Protected Attributes
double incrCutPoint
double decrCutPoint
double lambda
double warningConfidence
double driftConfidence
boolean oneSidedTest
int width
Static Protected Attributes
static final long serialVersionUID = 1L
Package Functions
void updateIncrStatistics (double valor, double confidence)
void updateDecrStatistics (double valor, double confidence)
Static Private Attributes
static SampleInfo sample1_IncrMonitoring
static SampleInfo sample2_IncrMonitoring
static SampleInfo sample1_DecrMonitoring
static SampleInfo sample2_DecrMonitoring
static SampleInfo total
Detailed Description
Online drift detection method based on McDiarmid's bounds. HDDMW-test uses the EWMA statistic as estimator. It receives as input a stream of real values and returns the estimated status of the stream: STABLE, WARNING or DRIFT.
I. Frias-Blanco, J. del Campo-Avila, G. Ramos-Jimenez, R. Morales-Bueno, A. Ortiz-Diaz, and Y. Caballero-Mota, Online and non-parametric drift detection methods based on Hoeffding's bound, IEEE Transactions on Knowledge and Data Engineering, 2014. DOI 10.1109/TKDE.2014.2345382.
Parameters:
-d : Confidence to the drift
-w : Confidence to the warning
-m : Controls how much weight is given to more recent data compared to older data. Smaller values mean less weight given to recent data
-t : Option to monitor error increments and decrements (two-sided) or only increments (one-sided)
Author:
Isvani Frias-Blanco (ifriasb@udg.co.cu)
Definition at line 49 of file HDDM_W_Test.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.HDDM_W_Test.HDDM_W_Test ()
Definition at line 91 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
{
        resetLearning();
    }
Member Function Documentation
boolean moa.classifiers.core.driftdetection.HDDM_W_Test.detectMeanIncrement (SampleInfo sample1, SampleInfo sample2, double confidence)
Definition at line 148 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.EWMA_Estimator, and moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.independentBoundedConditionSum.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanDecr(), and moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanIncr().
{
        if (sample1.EWMA_Estimator < 0 || sample2.EWMA_Estimator < 0) {
            return false;
        }
        double bound = Math.sqrt((sample1.independentBoundedConditionSum + sample2.independentBoundedConditionSum) * Math.log(1 / confidence) / 2);
        return sample2.EWMA_Estimator - sample1.EWMA_Estimator > bound;
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.getDescription (StringBuilder sb, int indent) [virtual]
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 212 of file HDDM_W_Test.java.
{
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.input (double inputValue) [virtual]
Adding a numeric value to the change detector<br>
.
The output of the change detector is modified after the insertion of a new item inside.
Parameters:
inputValue the number to insert into the change detector
Implements moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 119 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidence, moa.classifiers.core.driftdetection.AbstractChangeDetector.estimation, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.EWMA_Estimator, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.independentBoundedConditionSum, moa.classifiers.core.driftdetection.AbstractChangeDetector.isChangeDetected, moa.classifiers.core.driftdetection.AbstractChangeDetector.isWarningZone, moa.classifiers.core.driftdetection.HDDM_W_Test.lambda, moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanDecr(), moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanIncr(), moa.classifiers.core.driftdetection.HDDM_W_Test.oneSidedTest, moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.classifiers.core.driftdetection.HDDM_W_Test.total, moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics(), moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics(), moa.classifiers.core.driftdetection.HDDM_W_Test.warningConfidence, and moa.classifiers.core.driftdetection.HDDM_W_Test.width.
{
        double auxDecayRate = 1.0 - lambda;
        this.width++;
        if (total.EWMA_Estimator < 0) {
            total.EWMA_Estimator = value;
            total.independentBoundedConditionSum = 1;
        } else {
            total.EWMA_Estimator = lambda * value + auxDecayRate * total.EWMA_Estimator;
            total.independentBoundedConditionSum = lambda * lambda + auxDecayRate * auxDecayRate * total.independentBoundedConditionSum;
        }
        updateIncrStatistics(value, driftConfidence);
        if (monitorMeanIncr(value, driftConfidence)) {
            resetLearning();
            this.isChangeDetected = true;
            this.isWarningZone = false;
        } else if (monitorMeanIncr(value, warningConfidence)) {
            this.isChangeDetected = false;
            this.isWarningZone = true;
        } else {
            this.isChangeDetected = false;
            this.isWarningZone = false;
        }
        updateDecrStatistics(value, driftConfidence);
        if (!oneSidedTest && monitorMeanDecr(value, driftConfidence)) {
            resetLearning();
        }
        this.estimation = this.total.EWMA_Estimator;
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.input (boolean prediction)
Definition at line 113 of file HDDM_W_Test.java.
{
        double value = prediction == false ? 1.0 : 0.0;
        input(value);
    }
boolean moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanDecr (double valor, double confidence) [protected]
Definition at line 203 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.detectMeanIncrement(), moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_DecrMonitoring, and moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_DecrMonitoring.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input().
{
        return detectMeanIncrement(sample2_DecrMonitoring, sample1_DecrMonitoring, confidence);
    }
boolean moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanIncr (double valor, double confidence) [protected]
Definition at line 179 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.detectMeanIncrement(), moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_IncrMonitoring, and moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_IncrMonitoring.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input().
{
        return detectMeanIncrement(sample1_IncrMonitoring, sample2_IncrMonitoring, confidence);
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.prepareForUseImpl (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method describes the implementation of how to prepare this object for use.
All classes that extends this class have to implement prepareForUseImpl and not prepareForUse since prepareForUse calls prepareForUseImpl.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implements moa.options.AbstractOptionHandler.
Definition at line 208 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
{
        resetLearning();
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning ()
Resets this change detector.
It must be similar to starting a new change detector from scratch.
Reimplemented from moa.classifiers.core.driftdetection.AbstractChangeDetector.
Definition at line 96 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.decrCutPoint, moa.classifiers.core.driftdetection.AbstractChangeDetector.delay, moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidence, moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidenceOption, moa.options.MultiChoiceOption.getChosenIndex(), moa.options.FloatOption.getValue(), moa.classifiers.core.driftdetection.HDDM_W_Test.incrCutPoint, moa.classifiers.core.driftdetection.HDDM_W_Test.lambda, moa.classifiers.core.driftdetection.HDDM_W_Test.lambdaOption, moa.classifiers.core.driftdetection.HDDM_W_Test.oneSidedTest, moa.classifiers.core.driftdetection.HDDM_W_Test.oneSidedTestOption, moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_DecrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_IncrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_DecrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_IncrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.total, moa.classifiers.core.driftdetection.HDDM_W_Test.warningConfidence, moa.classifiers.core.driftdetection.HDDM_W_Test.warningConfidenceOption, and moa.classifiers.core.driftdetection.HDDM_W_Test.width.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.HDDM_W_Test(), moa.classifiers.core.driftdetection.HDDM_W_Test.input(), and moa.classifiers.core.driftdetection.HDDM_W_Test.prepareForUseImpl().
{
        super.resetLearning();
        this.total = new SampleInfo();
        this.sample1_DecrMonitoring = new SampleInfo();
        this.sample1_IncrMonitoring = new SampleInfo();
        this.sample2_DecrMonitoring = new SampleInfo();
        this.sample2_IncrMonitoring = new SampleInfo();
        this.incrCutPoint = Double.MAX_VALUE;
        this.decrCutPoint = Double.MIN_VALUE;
        this.lambda = this.lambdaOption.getValue();
        this.driftConfidence = this.driftConfidenceOption.getValue();
        this.warningConfidence = this.warningConfidenceOption.getValue();
        this.oneSidedTest = this.oneSidedTestOption.getChosenIndex() == 0;
        this.width = 0;
        this.delay = 0;
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics (double valor, double confidence) [package]
Definition at line 183 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.HDDM_W_Test.decrCutPoint, moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidence, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.EWMA_Estimator, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.independentBoundedConditionSum, moa.classifiers.core.driftdetection.HDDM_W_Test.lambda, moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_DecrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_DecrMonitoring, and moa.classifiers.core.driftdetection.HDDM_W_Test.total.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input().
{
            double auxDecay = 1.0 - lambda;
            double epsilon = Math.sqrt(total.independentBoundedConditionSum * Math.log(1.0 / driftConfidence) / 2);
            if (total.EWMA_Estimator - epsilon > decrCutPoint) {
                decrCutPoint = total.EWMA_Estimator - epsilon;
                sample1_DecrMonitoring.EWMA_Estimator = total.EWMA_Estimator;
                sample1_DecrMonitoring.independentBoundedConditionSum = total.independentBoundedConditionSum;
                sample2_DecrMonitoring = new SampleInfo();
            } else {
                if (sample2_DecrMonitoring.EWMA_Estimator < 0) {
                    sample2_DecrMonitoring.EWMA_Estimator = valor;
                    sample2_DecrMonitoring.independentBoundedConditionSum = 1;
                } else {
                    sample2_DecrMonitoring.EWMA_Estimator = lambda * valor + auxDecay * sample2_DecrMonitoring.EWMA_Estimator;
                    sample2_DecrMonitoring.independentBoundedConditionSum = lambda * lambda + auxDecay * auxDecay * sample2_DecrMonitoring.independentBoundedConditionSum;
                }
            }
    }
void moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics (double valor, double confidence) [package]
Definition at line 156 of file HDDM_W_Test.java.
References moa.classifiers.core.driftdetection.AbstractChangeDetector.delay, moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidence, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.EWMA_Estimator, moa.classifiers.core.driftdetection.HDDM_W_Test.incrCutPoint, moa.classifiers.core.driftdetection.HDDM_W_Test.SampleInfo.independentBoundedConditionSum, moa.classifiers.core.driftdetection.HDDM_W_Test.lambda, moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_IncrMonitoring, moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_IncrMonitoring, and moa.classifiers.core.driftdetection.HDDM_W_Test.total.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input().
{
            double auxDecay = 1.0 - lambda;
            double bound = Math.sqrt(total.independentBoundedConditionSum * Math.log(1.0 / driftConfidence) / 2);
            if (total.EWMA_Estimator + bound < incrCutPoint) {
                incrCutPoint = total.EWMA_Estimator + bound;
                sample1_IncrMonitoring.EWMA_Estimator = total.EWMA_Estimator;
                sample1_IncrMonitoring.independentBoundedConditionSum = total.independentBoundedConditionSum;
                sample2_IncrMonitoring = new SampleInfo();
                this.delay = 0;
            } else {
                this.delay++;
                if (sample2_IncrMonitoring.EWMA_Estimator < 0) {
                    sample2_IncrMonitoring.EWMA_Estimator = valor;
                    sample2_IncrMonitoring.independentBoundedConditionSum = 1;
                } else {
                    sample2_IncrMonitoring.EWMA_Estimator = lambda * valor + auxDecay * sample2_IncrMonitoring.EWMA_Estimator;
                    sample2_IncrMonitoring.independentBoundedConditionSum = lambda * lambda + auxDecay * auxDecay * sample2_IncrMonitoring.independentBoundedConditionSum;
                }
            }
    }
Member Data Documentation
double moa.classifiers.core.driftdetection.HDDM_W_Test.decrCutPoint [protected]
Definition at line 84 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics().
double moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidence [protected]
Definition at line 87 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
FloatOption moa.classifiers.core.driftdetection.HDDM_W_Test.driftConfidenceOption
Initial value:
 new FloatOption("driftConfidence", 'd',
            "Confidence to the drift",
            0.001, 0, 1)
Definition at line 52 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
double moa.classifiers.core.driftdetection.HDDM_W_Test.incrCutPoint [protected]
Definition at line 84 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
double moa.classifiers.core.driftdetection.HDDM_W_Test.lambda [protected]
Definition at line 85 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
FloatOption moa.classifiers.core.driftdetection.HDDM_W_Test.lambdaOption
Initial value:
 new FloatOption("lambda",
            'm', "Controls how much weight is given to more recent data compared to older data. Smaller values mean less weight given to recent data.",
            0.050, 0, 1)
Definition at line 58 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
boolean moa.classifiers.core.driftdetection.HDDM_W_Test.oneSidedTest [protected]
Definition at line 88 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), and moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
MultiChoiceOption moa.classifiers.core.driftdetection.HDDM_W_Test.oneSidedTestOption
Initial value:
 new MultiChoiceOption(
            "typeOfTest", 't',
            "Monitors error increments and decrements (two-sided) or only increments (one-sided)", new String[]{
        "One-sided", "Two-sided"}, new String[]{
        "One-sided", "Two-sided"},
            0)
Definition at line 61 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
SampleInfo moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_DecrMonitoring [static, private]
Definition at line 79 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanDecr(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics().
SampleInfo moa.classifiers.core.driftdetection.HDDM_W_Test.sample1_IncrMonitoring [static, private]
Definition at line 79 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanIncr(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
SampleInfo moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_DecrMonitoring [static, private]
Definition at line 79 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanDecr(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics().
SampleInfo moa.classifiers.core.driftdetection.HDDM_W_Test.sample2_IncrMonitoring [static, private]
Definition at line 79 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.monitorMeanIncr(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
final long moa.classifiers.core.driftdetection.HDDM_W_Test.serialVersionUID = 1L [static, protected]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 51 of file HDDM_W_Test.java.
SampleInfo moa.classifiers.core.driftdetection.HDDM_W_Test.total [static, private]
Definition at line 79 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning(), moa.classifiers.core.driftdetection.HDDM_W_Test.updateDecrStatistics(), and moa.classifiers.core.driftdetection.HDDM_W_Test.updateIncrStatistics().
double moa.classifiers.core.driftdetection.HDDM_W_Test.warningConfidence [protected]
Definition at line 86 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), and moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
FloatOption moa.classifiers.core.driftdetection.HDDM_W_Test.warningConfidenceOption
Initial value:
 new FloatOption("warningConfidence", 'w',
            "Confidence to the warning",
            0.005, 0, 1)
Definition at line 55 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
int moa.classifiers.core.driftdetection.HDDM_W_Test.width [protected]
Definition at line 89 of file HDDM_W_Test.java.
Referenced by moa.classifiers.core.driftdetection.HDDM_W_Test.input(), and moa.classifiers.core.driftdetection.HDDM_W_Test.resetLearning().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/HDDM_W_Test.java