MOA: moa.tasks.WriteStreamToARFFFile Class Reference
moa.tasks.WriteStreamToARFFFile Class Reference
Task to output a stream to an ARFF file.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Class<?> getTaskResultType ()
Gets the result type of this task.
Public Attributes
ClassOption streamOption
FileOption arffFileOption
IntOption maxInstancesOption
FlagOption suppressHeaderOption
Protected Member Functions
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task to output a stream to an ARFF file.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 40 of file WriteStreamToARFFFile.java.
Member Function Documentation
Object moa.tasks.WriteStreamToARFFFile.doMainTask (TaskMonitor monitor, ObjectRepository repository) [protected, virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 64 of file WriteStreamToARFFFile.java.
References moa.tasks.WriteStreamToARFFFile.arffFileOption, moa.options.FileOption.getFile(), moa.streams.InstanceStream.getHeader(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.streams.InstanceStream.hasMoreInstances(), moa.options.FlagOption.isSet, moa.tasks.WriteStreamToARFFFile.maxInstancesOption, moa.streams.InstanceStream.nextInstance(), moa.tasks.TaskMonitor.setCurrentActivityDescription(), moa.tasks.WriteStreamToARFFFile.streamOption, and moa.tasks.WriteStreamToARFFFile.suppressHeaderOption.
{
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        File destFile = this.arffFileOption.getFile();
        if (destFile != null) {
            try {
                Writer w = new BufferedWriter(new FileWriter(destFile));
                monitor.setCurrentActivityDescription("Writing stream to ARFF");
                if (!this.suppressHeaderOption.isSet()) {
                    w.write(stream.getHeader().toString());
                    w.write("\n");
                }
                int numWritten = 0;
                while ((numWritten < this.maxInstancesOption.getValue())
                        && stream.hasMoreInstances()) {
                    w.write(stream.nextInstance().toString());
                    w.write("\n");
                    numWritten++;
                }
                w.close();
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Failed writing to file " + destFile, ex);
            }
            return "Stream written to ARFF file " + destFile;
        }
        throw new IllegalArgumentException("No destination file to write to.");
    }
String moa.tasks.WriteStreamToARFFFile.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 43 of file WriteStreamToARFFFile.java.
{
        return "Outputs a stream to an ARFF file.";
    }
Class<?> moa.tasks.WriteStreamToARFFFile.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 93 of file WriteStreamToARFFFile.java.
{
        return String.class;
    }
Member Data Documentation
FileOption moa.tasks.WriteStreamToARFFFile.arffFileOption
Initial value:
 new FileOption("arffFile", 'f',
            "Destination ARFF file.", null, "arff", true)
Definition at line 53 of file WriteStreamToARFFFile.java.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask().
IntOption moa.tasks.WriteStreamToARFFFile.maxInstancesOption
Initial value:
 new IntOption("maxInstances", 'm',
            "Maximum number of instances to write to file.", 10000000, 0,
            Integer.MAX_VALUE)
Definition at line 56 of file WriteStreamToARFFFile.java.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask().
final long moa.tasks.WriteStreamToARFFFile.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 47 of file WriteStreamToARFFFile.java.
ClassOption moa.tasks.WriteStreamToARFFFile.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to write.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 49 of file WriteStreamToARFFFile.java.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask().
FlagOption moa.tasks.WriteStreamToARFFFile.suppressHeaderOption
Initial value:
 new FlagOption("suppressHeader",
            'h', "Suppress header from output.")
Definition at line 60 of file WriteStreamToARFFFile.java.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask().
The documentation for this class was generated from the following file:
main/java/moa/tasks/WriteStreamToARFFFile.java