MOA: moa.classifiers.core.driftdetection.ADWIN Class Reference
moa.classifiers.core.driftdetection.ADWIN Class Reference
ADaptive sliding WINdow method.
Classes
class List
class ListItem
Public Member Functions
boolean getChange ()
void resetChange ()
int getBucketsUsed ()
int getWidth ()
void setClock (int intClock)
int getClock ()
boolean getWarning ()
boolean getDetect ()
int getNumberDetections ()
double getTotal ()
double getEstimation ()
double getVariance ()
double getWidthT ()
int deleteElement ()
void compressBuckets ()
boolean setInput (double intEntrada)
boolean setInput (double intEntrada, double delta)
ADWIN ()
ADWIN (double d)
ADWIN (int cl)
String getEstimatorInfo ()
void setW (int W0)
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Static Public Attributes
static final double DELTA = .002
static final int MAXBUCKETS = 5
Private Member Functions
void initBuckets ()
void insertElement (double Value)
void insertElementBucket (double Variance, double Value, ListItem Node)
int bucketSize (int Row)
boolean blnCutexpression (int n0, int n1, double u0, double u1, double v0, double v1, double absvalue, double delta)
Private Attributes
double mdbldelta = .002
int mintTime = 0
int mintClock = 32
double mdblWidth = 0
int lastBucketRow = 0
double TOTAL = 0
double VARIANCE = 0
int WIDTH = 0
int BucketNumber = 0
int Detect = 0
int numberDetections = 0
int DetectTwice = 0
boolean blnBucketDeleted = false
int BucketNumberMAX = 0
int mintMinWinLength = 5
List listRowBuckets
Static Private Attributes
static final int mintMinimLongitudWindow = 10
Detailed Description
ADaptive sliding WINdow method.
This method is a change detector and estimator. It keeps a variable-length window of recently seen items, with the property that the window has the maximal length statistically consistent with the hypothesis "there has been no change in the average value inside the window".
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 35 of file ADWIN.java.
Constructor & Destructor Documentation
moa.classifiers.core.driftdetection.ADWIN.ADWIN ()
Definition at line 572 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.DELTA, moa.classifiers.core.driftdetection.ADWIN.Detect, moa.classifiers.core.driftdetection.ADWIN.DetectTwice, moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.mdbldelta, and moa.classifiers.core.driftdetection.ADWIN.numberDetections.
                   {
        mdbldelta = DELTA;
        initBuckets();
        Detect = 0;
        numberDetections = 0;
        DetectTwice = 0;
    }
moa.classifiers.core.driftdetection.ADWIN.ADWIN (double d)
Definition at line 581 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.Detect, moa.classifiers.core.driftdetection.ADWIN.DetectTwice, moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.mdbldelta, and moa.classifiers.core.driftdetection.ADWIN.numberDetections.
{
        mdbldelta = d;
        initBuckets();
        Detect = 0;
        numberDetections = 0;
        DetectTwice = 0;
    }
moa.classifiers.core.driftdetection.ADWIN.ADWIN (int cl)
Definition at line 589 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.DELTA, moa.classifiers.core.driftdetection.ADWIN.Detect, moa.classifiers.core.driftdetection.ADWIN.DetectTwice, moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.mdbldelta, moa.classifiers.core.driftdetection.ADWIN.mintClock, and moa.classifiers.core.driftdetection.ADWIN.numberDetections.
{
        mdbldelta = DELTA;
        initBuckets();
        Detect = 0;
        numberDetections = 0;
        DetectTwice = 0;
        mintClock = cl;
    }
Member Function Documentation
boolean moa.classifiers.core.driftdetection.ADWIN.blnCutexpression (int n0, int n1, double u0, double u1, double v0, double v1, double absvalue, double delta) [private]
Definition at line 561 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.getVariance(), moa.classifiers.core.driftdetection.ADWIN.getWidth(), and moa.classifiers.core.driftdetection.ADWIN.mintMinWinLength.
Referenced by moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        int n = getWidth();
        double dd = Math.log(2 * Math.log(n) / delta);     // -- ull perque el ln n va al numerador.
        // Formula Gener 2008
        double v = getVariance();
        double m = ((double) 1 / ((n0 - mintMinWinLength + 1))) + ((double) 1 / ((n1 - mintMinWinLength + 1)));
        double epsilon = Math.sqrt(2 * m * v * dd) + (double) 2 / 3 * dd * m;
        return (Math.abs(absvalue) > epsilon);
    }
int moa.classifiers.core.driftdetection.ADWIN.bucketSize (int Row) [private]
Definition at line 406 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        return (int) Math.pow(2, Row);
    }
void moa.classifiers.core.driftdetection.ADWIN.compressBuckets ()
Definition at line 432 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.List.addToTail(), moa.classifiers.core.driftdetection.ADWIN.BucketNumber, moa.classifiers.core.driftdetection.ADWIN.bucketSize(), moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.ListItem.compressBucketsRow(), moa.classifiers.core.driftdetection.ADWIN.List.head, moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket(), moa.classifiers.core.driftdetection.ADWIN.lastBucketRow, moa.classifiers.core.driftdetection.ADWIN.listRowBuckets, moa.classifiers.core.driftdetection.ADWIN.MAXBUCKETS, moa.classifiers.core.driftdetection.ADWIN.ListItem.next, moa.classifiers.core.driftdetection.ADWIN.ListItem.Total(), and moa.classifiers.core.driftdetection.ADWIN.ListItem.Variance().
Referenced by moa.classifiers.core.driftdetection.ADWIN.insertElement().
{
        //Traverse the list of buckets in increasing order
        int n1, n2;
        double u2, u1, incVariance;
        ListItem cursor;
        ListItem nextNode;
        cursor = listRowBuckets.head();
        int i = 0;
        do {
            //Find the number of buckets in a row
            int k = cursor.bucketSizeRow;
            //If the row is full, merge buckets
            if (k == MAXBUCKETS + 1) {
                nextNode = cursor.next();
                if (nextNode == null) {
                    listRowBuckets.addToTail();
                    nextNode = cursor.next();
                    lastBucketRow++;
                }
                n1 = bucketSize(i);
                n2 = bucketSize(i);
                u1 = cursor.Total(0) / n1;
                u2 = cursor.Total(1) / n2;
                incVariance = n1 * n2 * (u1 - u2) * (u1 - u2) / (n1 + n2);
                nextNode.insertBucket(cursor.Total(0) + cursor.Total(1), cursor.Variance(0) + cursor.Variance(1) + incVariance);
                BucketNumber++;
                cursor.compressBucketsRow(2);
                if (nextNode.bucketSizeRow <= MAXBUCKETS) {
                    break;
                }
            } else {
                break;
            }
            cursor = cursor.next();
            i++;
        } while (cursor != null);
    }
int moa.classifiers.core.driftdetection.ADWIN.deleteElement ()
Definition at line 410 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.BucketNumber, moa.classifiers.core.driftdetection.ADWIN.bucketSize(), moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.lastBucketRow, moa.classifiers.core.driftdetection.ADWIN.listRowBuckets, moa.classifiers.core.driftdetection.ADWIN.ListItem.RemoveBucket(), moa.classifiers.core.driftdetection.ADWIN.List.removeFromTail(), moa.classifiers.core.driftdetection.ADWIN.List.tail, moa.classifiers.core.driftdetection.ADWIN.ListItem.Total(), moa.classifiers.core.driftdetection.ADWIN.TOTAL, moa.classifiers.core.driftdetection.ADWIN.VARIANCE, moa.classifiers.core.driftdetection.ADWIN.ListItem.Variance(), and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        //LIST
        //Update statistics
        ListItem Node;
        Node = listRowBuckets.tail();
        int n1 = bucketSize(lastBucketRow);
        WIDTH -= n1;
        TOTAL -= Node.Total(0);
        double u1 = Node.Total(0) / n1;
        double incVariance = Node.Variance(0) + n1 * WIDTH * (u1 - TOTAL / WIDTH) * (u1 - TOTAL / WIDTH) / (n1 + WIDTH);
        VARIANCE -= incVariance;
        //Delete Bucket
        Node.RemoveBucket();
        BucketNumber--;
        if (Node.bucketSizeRow == 0) {
            listRowBuckets.removeFromTail();
            lastBucketRow--;
        }
        return n1;
    }
int moa.classifiers.core.driftdetection.ADWIN.getBucketsUsed ()
Definition at line 331 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.BucketNumberMAX.
{
        return BucketNumberMAX;
    }
boolean moa.classifiers.core.driftdetection.ADWIN.getChange ()
Definition at line 323 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.blnBucketDeleted.
{
        return blnBucketDeleted;
    }
int moa.classifiers.core.driftdetection.ADWIN.getClock ()
Definition at line 343 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.mintClock.
{
        return mintClock;
    }
void moa.classifiers.core.driftdetection.ADWIN.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 606 of file ADWIN.java.
{
    }
boolean moa.classifiers.core.driftdetection.ADWIN.getDetect ()
Definition at line 351 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.Detect, and moa.classifiers.core.driftdetection.ADWIN.mintTime.
{
        return (Detect == mintTime);
    }
double moa.classifiers.core.driftdetection.ADWIN.getEstimation ()
Definition at line 363 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.TOTAL, and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorEstimation(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorEstimation(), moa.classifiers.core.driftdetection.ADWINChangeDetector.input(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
{
        return TOTAL / WIDTH;
    }
String moa.classifiers.core.driftdetection.ADWIN.getEstimatorInfo ()
Definition at line 598 of file ADWIN.java.
{
        return "ADWIN;;";
    }
int moa.classifiers.core.driftdetection.ADWIN.getNumberDetections ()
Definition at line 355 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.numberDetections.
{
        return numberDetections;
    }
double moa.classifiers.core.driftdetection.ADWIN.getTotal ()
Definition at line 359 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.TOTAL.
Referenced by moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        return TOTAL;
    }
double moa.classifiers.core.driftdetection.ADWIN.getVariance ()
Definition at line 367 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.VARIANCE, and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.core.driftdetection.ADWIN.blnCutexpression().
{
        return VARIANCE / WIDTH;
    }
boolean moa.classifiers.core.driftdetection.ADWIN.getWarning ()
Definition at line 347 of file ADWIN.java.
{
        return false;
    }
int moa.classifiers.core.driftdetection.ADWIN.getWidth ()
Definition at line 335 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.core.driftdetection.ADWIN.blnCutexpression(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.getErrorWidth(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.getErrorWidth(), moa.classifiers.core.driftdetection.ADWIN.setInput(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
{
        return WIDTH;
    }
double moa.classifiers.core.driftdetection.ADWIN.getWidthT ()
Definition at line 371 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.mdblWidth.
{
        return mdblWidth;
    }
void moa.classifiers.core.driftdetection.ADWIN.initBuckets () [private]
Definition at line 375 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.BucketNumber, moa.classifiers.core.driftdetection.ADWIN.lastBucketRow, moa.classifiers.core.driftdetection.ADWIN.listRowBuckets, moa.classifiers.core.driftdetection.ADWIN.TOTAL, moa.classifiers.core.driftdetection.ADWIN.VARIANCE, and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN().
{
        //Init buckets
        listRowBuckets = new List();
        lastBucketRow = 0;
        TOTAL = 0;
        VARIANCE = 0;
        WIDTH = 0;
        BucketNumber = 0;
    }
void moa.classifiers.core.driftdetection.ADWIN.insertElement (double Value) [private]
Definition at line 385 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.List.head, moa.classifiers.core.driftdetection.ADWIN.insertElementBucket(), moa.classifiers.core.driftdetection.ADWIN.listRowBuckets, moa.classifiers.core.driftdetection.ADWIN.TOTAL, moa.classifiers.core.driftdetection.ADWIN.VARIANCE, and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
Referenced by moa.classifiers.core.driftdetection.ADWIN.setInput().
{
        WIDTH++;
        insertElementBucket(0, Value, listRowBuckets.head());
        double incVariance = 0;
        if (WIDTH > 1) {
            incVariance = (WIDTH - 1) * (Value - TOTAL / (WIDTH - 1)) * (Value - TOTAL / (WIDTH - 1)) / WIDTH;
        }
        VARIANCE += incVariance;
        TOTAL += Value;
        compressBuckets();
    }
void moa.classifiers.core.driftdetection.ADWIN.insertElementBucket (double Variance, double Value, ListItem Node) [private]
Definition at line 397 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.BucketNumber, moa.classifiers.core.driftdetection.ADWIN.BucketNumberMAX, and moa.classifiers.core.driftdetection.ADWIN.ListItem.insertBucket().
Referenced by moa.classifiers.core.driftdetection.ADWIN.insertElement().
{
        //Insert new bucket
        Node.insertBucket(Value, Variance);
        BucketNumber++;
        if (BucketNumber > BucketNumberMAX) {
            BucketNumberMAX = BucketNumber;
        }
    }
void moa.classifiers.core.driftdetection.ADWIN.resetChange ()
Definition at line 327 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.blnBucketDeleted.
{
        blnBucketDeleted = false;
    }
void moa.classifiers.core.driftdetection.ADWIN.setClock (int intClock)
Definition at line 339 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.mintClock.
{
        mintClock = intClock;
    }
boolean moa.classifiers.core.driftdetection.ADWIN.setInput (double intEntrada, double delta)
Definition at line 475 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.blnBucketDeleted, moa.classifiers.core.driftdetection.ADWIN.blnCutexpression(), moa.classifiers.core.driftdetection.ADWIN.bucketSize(), moa.classifiers.core.driftdetection.ADWIN.ListItem.bucketSizeRow, moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.Detect, moa.classifiers.core.driftdetection.ADWIN.DetectTwice, moa.classifiers.core.driftdetection.ADWIN.getTotal(), moa.classifiers.core.driftdetection.ADWIN.getWidth(), moa.classifiers.core.driftdetection.ADWIN.insertElement(), moa.classifiers.core.driftdetection.ADWIN.lastBucketRow, moa.classifiers.core.driftdetection.ADWIN.listRowBuckets, moa.classifiers.core.driftdetection.ADWIN.mdblWidth, moa.classifiers.core.driftdetection.ADWIN.mintClock, moa.classifiers.core.driftdetection.ADWIN.mintMinimLongitudWindow, moa.classifiers.core.driftdetection.ADWIN.mintMinWinLength, moa.classifiers.core.driftdetection.ADWIN.mintTime, moa.classifiers.core.driftdetection.ADWIN.numberDetections, moa.classifiers.core.driftdetection.ADWIN.ListItem.previous, moa.classifiers.core.driftdetection.ADWIN.List.tail, moa.classifiers.core.driftdetection.ADWIN.ListItem.Total(), moa.classifiers.core.driftdetection.ADWIN.ListItem.Variance(), moa.classifiers.core.driftdetection.ADWIN.VARIANCE, and moa.classifiers.core.driftdetection.ADWIN.WIDTH.
{
        boolean blnChange = false;
        boolean blnExit = false;
        ListItem cursor;
        mintTime++;
        //1,2)Increment window in one element
        insertElement(intEntrada);
        blnBucketDeleted = false;
        //3)Reduce  window
        if (mintTime % mintClock == 0 && getWidth() > mintMinimLongitudWindow) {
            boolean blnReduceWidth = true; // Diference
            while (blnReduceWidth) // Diference
            {
                blnReduceWidth = false; // Diference
                blnExit = false;
                int n0 = 0;
                int n1 = WIDTH;
                double u0 = 0;
                double u1 = getTotal();
                double v0 = 0;
                double v1 = VARIANCE;
                double n2 = 0;
                double u2 = 0;
                cursor = listRowBuckets.tail();
                int i = lastBucketRow;
                do {
                    for (int k = 0; k <= (cursor.bucketSizeRow - 1); k++) {
                        n2 = bucketSize(i);
                        u2 = cursor.Total(k);
                        if (n0 > 0) {
                            v0 += cursor.Variance(k) + (double) n0 * n2 * (u0 / n0 - u2 / n2) * (u0 / n0 - u2 / n2) / (n0 + n2);
                        }
                        if (n1 > 0) {
                            v1 -= cursor.Variance(k) + (double) n1 * n2 * (u1 / n1 - u2 / n2) * (u1 / n1 - u2 / n2) / (n1 + n2);
                        }
                        n0 += bucketSize(i);
                        n1 -= bucketSize(i);
                        u0 += cursor.Total(k);
                        u1 -= cursor.Total(k);
                        if (i == 0 && k == cursor.bucketSizeRow - 1) {
                            blnExit = true;
                            break;
                        }
                        double absvalue = (double) (u0 / n0) - (u1 / n1);       //n1<WIDTH-mintMinWinLength-1
                        if ((n1 > mintMinWinLength + 1 && n0 > mintMinWinLength + 1) && // Diference NEGATIVE
                                //if(
                                blnCutexpression(n0, n1, u0, u1, v0, v1, absvalue, delta)) {
                            blnBucketDeleted = true;
                            Detect = mintTime;
                            if (Detect == 0) {
                                Detect = mintTime;
                                //blnFirst=true;
                                //blnWarning=true;
                            } else if (DetectTwice == 0) {
                                DetectTwice = mintTime;
                                //blnDetect=true;
                            }
                            blnReduceWidth = true; // Diference
                            blnChange = true;
                            if (getWidth() > 0) { //Reduce width of the window
                                //while (n0>0)  // Diference NEGATIVE
                                n0 -= deleteElement();
                                blnExit = true;
                                break;
                            }
                        } //End if
                    }//Next k
                    cursor = cursor.previous();
                    i--;
                } while (((!blnExit && cursor != null)));
            }//End While // Diference
        }//End if
        mdblWidth += getWidth();
        if (blnChange) {
            numberDetections++;
        }
        return blnChange;
    }
boolean moa.classifiers.core.driftdetection.ADWIN.setInput (double intEntrada)
Definition at line 471 of file ADWIN.java.
References moa.classifiers.core.driftdetection.ADWIN.mdbldelta.
Referenced by moa.classifiers.core.driftdetection.ADWINChangeDetector.input(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingAdaptiveTree.AdaSplitNode.learnFromInstance(), and moa.classifiers.lazy.kNNwithPAWandADWIN.trainOnInstanceImpl().
{
        return setInput(intEntrada, mdbldelta);
    }
void moa.classifiers.core.driftdetection.ADWIN.setW (int W0)
Definition at line 602 of file ADWIN.java.
{
    }
Member Data Documentation
boolean moa.classifiers.core.driftdetection.ADWIN.blnBucketDeleted = false [private]
Definition at line 315 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.getChange(), moa.classifiers.core.driftdetection.ADWIN.resetChange(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.BucketNumber = 0 [private]
Definition at line 307 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), and moa.classifiers.core.driftdetection.ADWIN.insertElementBucket().
int moa.classifiers.core.driftdetection.ADWIN.BucketNumberMAX = 0 [private]
Definition at line 317 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.getBucketsUsed(), and moa.classifiers.core.driftdetection.ADWIN.insertElementBucket().
final double moa.classifiers.core.driftdetection.ADWIN.DELTA = .002 [static]
Definition at line 284 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN().
int moa.classifiers.core.driftdetection.ADWIN.Detect = 0 [private]
Definition at line 309 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN(), moa.classifiers.core.driftdetection.ADWIN.getDetect(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.DetectTwice = 0 [private]
Definition at line 313 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.lastBucketRow = 0 [private]
Definition at line 299 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
List moa.classifiers.core.driftdetection.ADWIN.listRowBuckets [private]
Definition at line 321 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets(), moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.insertElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
final int moa.classifiers.core.driftdetection.ADWIN.MAXBUCKETS = 5 [static]
Definition at line 297 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.compressBuckets().
double moa.classifiers.core.driftdetection.ADWIN.mdbldelta = .002 [private]
Definition at line 288 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
double moa.classifiers.core.driftdetection.ADWIN.mdblWidth = 0 [private]
Definition at line 294 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.getWidthT(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.mintClock = 32 [private]
Definition at line 292 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN(), moa.classifiers.core.driftdetection.ADWIN.getClock(), moa.classifiers.core.driftdetection.ADWIN.setClock(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
final int moa.classifiers.core.driftdetection.ADWIN.mintMinimLongitudWindow = 10 [static, private]
Definition at line 286 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.mintMinWinLength = 5 [private]
Definition at line 319 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.blnCutexpression(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.mintTime = 0 [private]
Definition at line 290 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.getDetect(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.numberDetections = 0 [private]
Definition at line 311 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.ADWIN(), moa.classifiers.core.driftdetection.ADWIN.getNumberDetections(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
double moa.classifiers.core.driftdetection.ADWIN.TOTAL = 0 [private]
Definition at line 301 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.classifiers.core.driftdetection.ADWIN.getTotal(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), and moa.classifiers.core.driftdetection.ADWIN.insertElement().
double moa.classifiers.core.driftdetection.ADWIN.VARIANCE = 0 [private]
Definition at line 303 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.getVariance(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.insertElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
int moa.classifiers.core.driftdetection.ADWIN.WIDTH = 0 [private]
Definition at line 305 of file ADWIN.java.
Referenced by moa.classifiers.core.driftdetection.ADWIN.deleteElement(), moa.classifiers.core.driftdetection.ADWIN.getEstimation(), moa.classifiers.core.driftdetection.ADWIN.getVariance(), moa.classifiers.core.driftdetection.ADWIN.getWidth(), moa.classifiers.core.driftdetection.ADWIN.initBuckets(), moa.classifiers.core.driftdetection.ADWIN.insertElement(), and moa.classifiers.core.driftdetection.ADWIN.setInput().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/core/driftdetection/ADWIN.java