MOA: moa.clusterers.outliers.SimpleCOD.SimpleCODBase Class Reference
moa.clusterers.outliers.SimpleCOD.SimpleCODBase Class Reference
Classes
class EventItem
class EventQueue
Public Member Functions
String getObjectInfo (Object obj)
String getStatistics ()
void PrintNodeSet (Set< ISBNode > set)
void PrintNodeVector (Vector< ISBNode > vector)
void PrintNodeList (List< ISBNode > list)
void PrintEventQueue ()
void PrintISB ()
Public Attributes
boolean bWarning = false
int m_nBothInlierOutlier
int m_nOnlyInlier
int m_nOnlyOutlier
Protected Member Functions
boolean IsNodeIdInWin (long id)
Protected Attributes
Long objId
Vector< ISBNode > windowNodes
EventQueue eventQueue
ISBIndex ISB
int m_WindowSize
double m_radius
int m_k
Static Protected Attributes
static final Long FIRST_OBJ_ID = 1L
Package Functions
Long GetWindowEnd ()
Long GetWindowStart ()
boolean IsWinFull ()
Long GetExpirationTime (ISBNode node)
void SaveOutlier (ISBNode node)
void RemoveOutlier (ISBNode node)
void AddNode (ISBNode node)
void RemoveNode (ISBNode node)
void UpdateStatistics (ISBNode node)
ISBNode GetExpiredNode ()
double GetEuclideanDist (ISBNode n1, ISBNode n2)
void PrintWindow ()
void PrintNode (ISBNode n)
Detailed Description
Definition at line 26 of file SimpleCODBase.java.
Member Function Documentation
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.AddNode (ISBNode node) [package]
Definition at line 214 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        windowNodes.add(node);
    }
double moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetEuclideanDist (ISBNode n1, ISBNode n2) [package]
Definition at line 246 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), moa.clusterers.outliers.SimpleCOD.StreamObj.get(), and moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.obj.
    {
        double diff;
        double sum = 0;
        int d = n1.obj.dimensions();
        for (int i = 0; i < d; i++) {
            diff = n1.obj.get(i) - n2.obj.get(i);
            sum += Math.pow(diff, 2);
        }
        return Math.sqrt(sum);
    }
Long moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpirationTime (ISBNode node) [package]
Definition at line 190 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_WindowSize.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue().
{
        return node.id + m_WindowSize;
    }
ISBNode moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpiredNode () [package]
Definition at line 234 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        if (windowNodes.size() <= 0)
            return null;
        // get oldest node
        ISBNode node = windowNodes.get(0);
        // check if node has expired
        if (node.id < GetWindowStart()) {
            return node;
        }
        return null;
    }
String moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getObjectInfo (Object obj)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 101 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), moa.clusterers.outliers.SimpleCOD.StreamObj.get(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, and moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.obj.
{
        if (obj == null) return null;
        ISBNode node = (ISBNode) obj;
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        StringBuilder sb = new StringBuilder();
        // show node position
        for (int i = 0; i < node.obj.dimensions(); i++) {
            infoTitle.add("Dim" + (i+1));
            infoValue.add(String.format("%.3f", node.obj.get(i)));
        }
        // show node properties
        infoTitle.add("id");
        infoValue.add(String.format("%d", node.id));
        infoTitle.add("count_after");
        infoValue.add(String.format("%d", node.count_after));
        infoTitle.add("|nn_before|");
        infoValue.add(String.format("%d", node.CountPrecNeighs(GetWindowStart())));
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td><b>"+infoTitle.get(i)+":</b></td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
String moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 139 of file SimpleCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.iMaxMemUsage, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyInlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyOutlier, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.nTotalRunTime, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes.
{
        StringBuilder sb = new StringBuilder();
        sb.append("Statistics:\n\n");
        // get counters of expired nodes
        int nBothInlierOutlier = m_nBothInlierOutlier;
        int nOnlyInlier = m_nOnlyInlier;
        int nOnlyOutlier = m_nOnlyOutlier;
        // add counters of non expired nodes
        for (ISBNode node : windowNodes) {
            if ((node.nInlier > 0) && (node.nOutlier > 0))
                nBothInlierOutlier++;
            else if (node.nInlier > 0)
                nOnlyInlier++;
            else
                nOnlyOutlier++;
        }
        int sum = nBothInlierOutlier + nOnlyInlier + nOnlyOutlier;
        if (sum > 0) {
            sb.append(String.format("  Nodes always inlier: %d (%.1f%%)\n", nOnlyInlier, (100 * nOnlyInlier) / (double)sum));
            sb.append(String.format("  Nodes always outlier: %d (%.1f%%)\n", nOnlyOutlier, (100 * nOnlyOutlier) / (double)sum));
            sb.append(String.format("  Nodes both inlier and outlier: %d (%.1f%%)\n", nBothInlierOutlier, (100 * nBothInlierOutlier) / (double)sum));
            sb.append("  (Sum: " + sum + ")\n");
        }
        sb.append("\n  Total range queries: " + nRangeQueriesExecuted + "\n");
        sb.append("  Max memory usage: " + iMaxMemUsage + " MB\n");
        sb.append("  Total process time: " + String.format("%.2f ms", nTotalRunTime / 1000.0) + "\n");
        return sb.toString();
    }
Long moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd () [package]
Definition at line 175 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.objId.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsNodeIdInWin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsWinFull(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
{
        return objId - 1;
    }
Long moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart () [package]
Definition at line 179 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.FIRST_OBJ_ID, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_WindowSize.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getObjectInfo(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsNodeIdInWin(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
{
        Long x = GetWindowEnd() - m_WindowSize + 1;
        if (x < FIRST_OBJ_ID)
            x = FIRST_OBJ_ID;
        return x;
    }
boolean moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsNodeIdInWin (long id) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 205 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
{
        int toleranceStart = 1;
        Long start = GetWindowStart() - toleranceStart;
        if ( (start <= id) && (id <= GetWindowEnd()) )
            return true;
        else
            return false;
    }
boolean moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsWinFull () [package]
Definition at line 186 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.FIRST_OBJ_ID, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_WindowSize.
{
        return (GetWindowEnd() >= FIRST_OBJ_ID + m_WindowSize - 1);
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue ()
Definition at line 300 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.eventQueue, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventItem.node, moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventQueue.setEvents, and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.EventItem.timeStamp.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue().
{
        Println("event queue: ");
        for (EventItem n : eventQueue.setEvents) {
            Printf("  id=%d, exp=%d\n", n.node.id, n.timeStamp);
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintISB ()
Definition at line 307 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.GetAllNodes(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        Print("PD: ");
        for (ISBNode n : ISB.GetAllNodes()) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode (ISBNode n) [package]
Definition at line 268 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.StreamObj.dimensions(), moa.clusterers.outliers.SimpleCOD.StreamObj.get(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.obj, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
{
        Print("id=" + n.id + " (");
        int dim = n.obj.dimensions();
        for (int d = 0; d < dim; d++) {
            Print(Double.toString(n.obj.get(d)));
            if (d < dim - 1)
                Print(", ");
        }
        Println(")");
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeList (List< ISBNode > list)
Definition at line 293 of file SimpleCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue().
{
        for (ISBNode n : list) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeSet (Set< ISBNode > set)
Definition at line 279 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
{
        for (ISBNode n : set) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNodeVector (Vector< ISBNode > vector)
Definition at line 286 of file SimpleCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.Print(), and moa.clusterers.outliers.MyBaseOutlierDetector.Println().
{
        for (ISBNode n : vector) {
            Print(n.id + " ");
        }
        Println("");
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow () [package]
Definition at line 258 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintNode(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
                       {
        Println("Window [" + GetWindowStart() + "-" + GetWindowEnd() + "]: ");
        ISBNode node;
        for (int i = 0; i < windowNodes.size(); i++) {
            node = windowNodes.get(i);
            Print("   Node: ");
            PrintNode(node);
        }
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveNode (ISBNode node) [package]
Definition at line 218 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.inst, moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.UpdateStatistics(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode().
{
        windowNodes.remove(node);
        RemoveExpiredOutlier(new Outlier(node.inst, node.id, node)); // ### remove when expired?
        // update statistics
        UpdateStatistics(node);
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveOutlier (ISBNode node) [package]
Definition at line 199 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.nInlier.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
{
        RemoveOutlier(new Outlier(node.inst, node.id, node));
        node.nInlier++; // update statistics
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.SaveOutlier (ISBNode node) [package]
Definition at line 194 of file SimpleCODBase.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.AddOutlier(), moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.inst, and moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
{
        AddOutlier(new Outlier(node.inst, node.id, node));
        node.nOutlier++; // update statistics
    }
void moa.clusterers.outliers.SimpleCOD.SimpleCODBase.UpdateStatistics (ISBNode node) [package]
Definition at line 225 of file SimpleCODBase.java.
References moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyInlier, moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyOutlier, moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.nInlier, and moa.clusterers.outliers.SimpleCOD.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveNode().
{
        if ((node.nInlier > 0) && (node.nOutlier > 0))
            m_nBothInlierOutlier++;
        else if (node.nInlier > 0)
            m_nOnlyInlier++;
        else
            m_nOnlyOutlier++;
    }
Member Data Documentation
boolean moa.clusterers.outliers.SimpleCOD.SimpleCODBase.bWarning = false
Definition at line 93 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
EventQueue moa.clusterers.outliers.SimpleCOD.SimpleCODBase.eventQueue [protected]
Definition at line 87 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.AddToEventQueue(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue().
final Long moa.clusterers.outliers.SimpleCOD.SimpleCODBase.FIRST_OBJ_ID = 1L [static, protected]
Definition at line 81 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsWinFull().
ISBIndex moa.clusterers.outliers.SimpleCOD.SimpleCODBase.ISB [protected]
Definition at line 89 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintISB(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
int moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_k [protected]
Definition at line 92 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessEventQueue(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
int moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nBothInlierOutlier
Definition at line 96 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.UpdateStatistics().
int moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyInlier
Definition at line 97 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.UpdateStatistics().
int moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_nOnlyOutlier
Definition at line 98 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.UpdateStatistics().
double moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_radius [protected]
Definition at line 91 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewNode().
int moa.clusterers.outliers.SimpleCOD.SimpleCODBase.m_WindowSize [protected]
Definition at line 90 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpirationTime(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowStart(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.IsWinFull().
Long moa.clusterers.outliers.SimpleCOD.SimpleCODBase.objId [protected]
Definition at line 84 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetWindowEnd(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), and moa.clusterers.outliers.SimpleCOD.SimpleCOD.ProcessNewStreamObj().
Vector<ISBNode> moa.clusterers.outliers.SimpleCOD.SimpleCODBase.windowNodes [protected]
Definition at line 86 of file SimpleCODBase.java.
Referenced by moa.clusterers.outliers.SimpleCOD.SimpleCODBase.AddNode(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.GetExpiredNode(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.getStatistics(), moa.clusterers.outliers.SimpleCOD.SimpleCOD.Init(), moa.clusterers.outliers.SimpleCOD.SimpleCODBase.PrintWindow(), and moa.clusterers.outliers.SimpleCOD.SimpleCODBase.RemoveNode().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/SimpleCOD/SimpleCODBase.java