MOA: moa.core.AutoClassDiscovery Class Reference
moa.core.AutoClassDiscovery Class Reference
Class for discovering classes via reflection in the java class path.
Static Public Member Functions
static String[] findClassNames (String packageNameToSearch)
static Class[] findClassesOfType (String packageNameToSearch, Class<?> typeDesired)
static boolean isPublicConcreteClassOfType (String className, Class<?> typeDesired)
static boolean hasEmptyConstructor (Class<?> type)
Static Protected Member Functions
static String[] findClassesInDirectoryRecursive (File root, String packagePath)
Static Protected Attributes
static final Map< String, String[]> cachedClassNames = new HashMap<String, String[]>()
Detailed Description
Class for discovering classes via reflection in the java class path.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 42 of file AutoClassDiscovery.java.
Member Function Documentation
static String [] moa.core.AutoClassDiscovery.findClassesInDirectoryRecursive (File root, String packagePath) [static, protected]
Definition at line 145 of file AutoClassDiscovery.java.
Referenced by moa.core.AutoClassDiscovery.findClassNames().
{
        HashSet<String> classNames = new HashSet<String>();
        if (root.isDirectory()) {
            String[] list = root.list();
            for (String string : list) {
                if (string.endsWith(".class")) {
                    classNames.add(packagePath
                            + string.substring(0, string.length()
                            - ".class".length()));
                } else {
                    File testDir = new File(root.getPath() + File.separatorChar
                            + string);
                    if (testDir.isDirectory()) {
                        String[] names = findClassesInDirectoryRecursive(
                                testDir, packagePath + string + ".");
                        classNames.addAll(Arrays.asList(names));
                    }
                }
            }
        }
        return classNames.toArray(new String[classNames.size()]);
    }
static Class [] moa.core.AutoClassDiscovery.findClassesOfType (String packageNameToSearch, Class<?> typeDesired) [static]
Definition at line 169 of file AutoClassDiscovery.java.
References moa.core.AutoClassDiscovery.findClassNames(), and moa.core.AutoClassDiscovery.isPublicConcreteClassOfType().
{
        ArrayList<Class<?>> classesFound = new ArrayList<Class<?>>();
        String[] classNames = findClassNames(packageNameToSearch);
        for (String className : classNames) {
            String fullName = packageNameToSearch.length() > 0 ? (packageNameToSearch
                    + "." + className)
                    : className;
            if (isPublicConcreteClassOfType(fullName, typeDesired)) {
                try {
                    classesFound.add(Class.forName(fullName));
                } catch (Exception ignored) {
                    // ignore classes that we cannot instantiate
                }
            }
        }
        return classesFound.toArray(new Class[classesFound.size()]);
    }
static String [] moa.core.AutoClassDiscovery.findClassNames (String packageNameToSearch) [static]
Definition at line 46 of file AutoClassDiscovery.java.
References moa.core.AutoClassDiscovery.cachedClassNames, and moa.core.AutoClassDiscovery.findClassesInDirectoryRecursive().
Referenced by moa.core.AutoClassDiscovery.findClassesOfType().
{
        String[] cached = cachedClassNames.get(packageNameToSearch);
        if (cached == null) {
            HashSet<String> classNames = new HashSet<String>();
            /*StringTokenizer pathTokens = new StringTokenizer(System
            .getProperty("java.class.path"), File.pathSeparator);*/
            String packageDirName = packageNameToSearch.replace('.',
                    File.separatorChar);
            String packageJarName = packageNameToSearch.length() > 0 ? (packageNameToSearch.replace('.', '/') + "/")
                    : "";
            String part = "";
            AutoClassDiscovery adc = new AutoClassDiscovery();
            URLClassLoader sysLoader = (URLClassLoader) adc.getClass().getClassLoader();
            URL[] cl_urls = sysLoader.getURLs();
            for (int i = 0; i < cl_urls.length; i++) {
                part = cl_urls[i].toString();
                if (part.startsWith("file:")) {
                    part = part.replace(" ", "%20");
                    try {
                        File temp = new File(new java.net.URI(part));
                        part = temp.getAbsolutePath();
                    } catch (URISyntaxException e) {
                        e.printStackTrace();
                    }
                }
                // find classes
                ArrayList<File> files = new ArrayList<File>();
                File dir = new File(part);
                if (dir.isDirectory()) {
                    File root = new File(dir.toString() + File.separatorChar + packageDirName);
                    String[] names = findClassesInDirectoryRecursive(root, "");
                    classNames.addAll(Arrays.asList(names));
                } else {
                    try {
                        JarFile jar = new JarFile(part);
                        Enumeration<JarEntry> jarEntries = jar.entries();
                        while (jarEntries.hasMoreElements()) {
                            String jarEntry = jarEntries.nextElement().getName();
                            if (jarEntry.startsWith(packageJarName)) {
                                String relativeName = jarEntry.substring(packageJarName.length());
                                if (relativeName.endsWith(".class")) {
                                    relativeName = relativeName.replace('/',
                                            '.');
                                    classNames.add(relativeName.substring(0,
                                            relativeName.length()
                                            - ".class".length()));
                                }
                            }
                        }
                    } catch (IOException ignored) {
                        // ignore unreadable files
                    }
                }
            }
            /*while (pathTokens.hasMoreElements()) {
            String pathToSearch = pathTokens.nextElement().toString();
            if (pathToSearch.endsWith(".jar")) {
            try {
            JarFile jar = new JarFile(pathToSearch);
            Enumeration<JarEntry> jarEntries = jar.entries();
            while (jarEntries.hasMoreElements()) {
            String jarEntry = jarEntries.nextElement()
            .getName();
            if (jarEntry.startsWith(packageJarName)) {
            String relativeName = jarEntry
            .substring(packageJarName.length());
            if (relativeName.endsWith(".class")) {
            relativeName = relativeName.replace('/',
            '.');
            classNames.add(relativeName.substring(0,
            relativeName.length()
            - ".class".length()));
            }
            }
            }
            } catch (IOException ignored) {
            // ignore unreadable files
            }
            } else {
            File root = new File(pathToSearch + File.separatorChar
            + packageDirName);
            String[] names = findClassesInDirectoryRecursive(root, "");
            for (String name : names) {
            classNames.add(name);
            }
            }
            } */
            cached = classNames.toArray(new String[classNames.size()]);
            Arrays.sort(cached);
            cachedClassNames.put(packageNameToSearch, cached);
        }
        return cached;
    }
static boolean moa.core.AutoClassDiscovery.hasEmptyConstructor (Class<?> type) [static]
Definition at line 202 of file AutoClassDiscovery.java.
Referenced by moa.core.AutoClassDiscovery.isPublicConcreteClassOfType().
{
        try {
            type.getConstructor();
            return true;
        } catch (Exception ignored) {
            return false;
        }
    }
static boolean moa.core.AutoClassDiscovery.isPublicConcreteClassOfType (String className, Class<?> typeDesired) [static]
Definition at line 188 of file AutoClassDiscovery.java.
References moa.core.AutoClassDiscovery.hasEmptyConstructor().
Referenced by moa.core.AutoClassDiscovery.findClassesOfType().
{
        Class<?> testClass = null;
        try {
            testClass = Class.forName(className);
        } catch (Exception e) {
            return false;
        }
        int classModifiers = testClass.getModifiers();
        return (java.lang.reflect.Modifier.isPublic(classModifiers)
                && !java.lang.reflect.Modifier.isAbstract(classModifiers)
                && typeDesired.isAssignableFrom(testClass) && hasEmptyConstructor(testClass));
    }
Member Data Documentation
final Map<String, String[]> moa.core.AutoClassDiscovery.cachedClassNames = new HashMap<String, String[]>() [static, protected]
Definition at line 44 of file AutoClassDiscovery.java.
Referenced by moa.core.AutoClassDiscovery.findClassNames().
The documentation for this class was generated from the following file:
main/java/moa/core/AutoClassDiscovery.java