MOA: moa.clusterers.CobWeb Class Reference
moa.clusterers.CobWeb Class Reference
Class implementing the Cobweb and Classit clustering algorithms.
Classes
class CNode
Inner class handling node operations for Cobweb.
Public Member Functions
void resetLearningImpl ()
void trainOnInstanceImpl (Instance newInstance)
Adds an instance to the clusterer.
double[] getVotesForInstance (Instance instance)
Classifies a given instance.
int numberOfClusters ()
Returns the number of clusters.
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
String graph ()
Generates the graph string of the Cobweb tree.
void setAcuity (double a)
set the acuity.
double getAcuity ()
get the acuity value
void setCutoff (double c)
set the cutoff
double getCutoff ()
get the cutoff
boolean getSaveInstanceData ()
Get the value of saveInstances.
void setSaveInstanceData (boolean newsaveInstances)
Set the value of saveInstances.
Clustering getClusteringResult ()
Public Attributes
FloatOption acuityOption
FloatOption cutoffOption
IntOption randomSeedOption
Static Public Attributes
static final String classifierPurposeString = "Cobweb and Classit clustering algorithms: it always compares the best host, adding a new leaf, merging the two best hosts, and splitting the best host when considering where to place a new instance.."
Protected Member Functions
void determineNumberOfClusters ()
determines the number of clusters if necessary
Measurement[] getModelMeasurementsImpl ()
Protected Attributes
double m_acuity = 1.0
Acuity (minimum standard deviation).
double m_cutoff = 0.002
Cutoff (minimum category utility).
CNode m_cobwebTree = null
Holds the root of the Cobweb tree.
int m_numberOfClusters = -1
Number of clusters (nodes in the tree).
boolean m_numberOfClustersDetermined = false
whether the number of clusters was already determined
int m_numberSplits
the number of splits that happened
int m_numberMerges
the number of merges that happened
boolean m_saveInstances = false
Output instances in graph representation of Cobweb tree (Allows instances at nodes in the tree to be visualized in the Explorer).
Static Protected Attributes
static final double m_normal = 1.0 / (2 * Math.sqrt(Math.PI))
Normal constant.
Package Functions
[instance initializer]
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class implementing the Cobweb and Classit clustering algorithms.
See: http://en.wikipedia.org/wiki/Cobweb_%28clustering%29
Citation: D. Fisher (1987). Knowledge acquisition via incremental conceptual clustering. Machine Learning. 2(2):139-172.
Definition at line 46 of file CobWeb.java.
Member Function Documentation
moa.clusterers.CobWeb.[instance initializer] () [package]
void moa.clusterers.CobWeb.determineNumberOfClusters () [protected]
determines the number of clusters if necessary
See also:
m_numberOfClusters
m_numberOfClustersDetermined
Definition at line 852 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.assignClusterNums(), moa.clusterers.CobWeb.m_cobwebTree, moa.clusterers.CobWeb.m_numberOfClusters, and moa.clusterers.CobWeb.m_numberOfClustersDetermined.
Referenced by moa.clusterers.CobWeb.CNode.computeTreeClustering(), moa.clusterers.CobWeb.CNode.dumpTree(), moa.clusterers.CobWeb.getVotesForInstance(), and moa.clusterers.CobWeb.numberOfClusters().
{
        if (!m_numberOfClustersDetermined
                && (m_cobwebTree != null)) {
            int[] numClusts = new int[1];
            numClusts[0] = 0;
            //  try {
            m_cobwebTree.assignClusterNums(numClusts);
            // }
            // catch (Exception e) {
//  e.printStackTrace();
//  numClusts[0] = 0;
            // }
            m_numberOfClusters = numClusts[0];
            m_numberOfClustersDetermined = true;
        }
    }
double moa.clusterers.CobWeb.getAcuity ()
get the acuity value
Returns:
the acuity
Definition at line 937 of file CobWeb.java.
References moa.clusterers.CobWeb.m_acuity.
{
        return m_acuity;
    }
Clustering moa.clusterers.CobWeb.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 977 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.computeTreeClustering(), moa.clusterers.CobWeb.m_cobwebTree, moa.clusterers.CobWeb.numberOfClusters(), and moa.cluster.Clustering.size().
{
        //throw new UnsupportedOperationException("Not supported yet.");
    Clustering result = new Clustering();
        if (m_cobwebTree == null) {
            //StringUtils.appendIndented(out, indent, "Cobweb hasn't been built yet!");
            //StringUtils.appendNewline(out);
        } else {
            m_cobwebTree.computeTreeClustering(0,result);
        System.out.println("After Number of clusters: "+numberOfClusters() );
    }
    System.out.println("Number of clusters: "+result.size());
    return result;
    }
double moa.clusterers.CobWeb.getCutoff ()
get the cutoff
Returns:
the cutoff
Definition at line 953 of file CobWeb.java.
References moa.clusterers.CobWeb.m_cutoff.
{
        return m_cutoff;
    }
void moa.clusterers.CobWeb.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 890 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.dumpTree(), moa.clusterers.CobWeb.m_cobwebTree, moa.clusterers.CobWeb.m_numberMerges, moa.clusterers.CobWeb.m_numberSplits, and moa.clusterers.CobWeb.numberOfClusters().
{
        StringBuffer text = new StringBuffer();
        if (m_cobwebTree == null) {
            StringUtils.appendIndented(out, indent, "Cobweb hasn't been built yet!");
            StringUtils.appendNewline(out);
        } else {
            m_cobwebTree.dumpTree(0, text);
            StringUtils.appendIndented(out, indent, "CobWeb - ");
            out.append("Number of merges: "
                    + m_numberMerges + "\nNumber of splits: "
                    + m_numberSplits + "\nNumber of clusters: "
                    + numberOfClusters() + "\n" + text.toString());
            StringUtils.appendNewline(out);
        }
    }
Measurement [] moa.clusterers.CobWeb.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 885 of file CobWeb.java.
{
        return null;
    }
boolean moa.clusterers.CobWeb.getSaveInstanceData ()
Get the value of saveInstances.
Returns:
Value of saveInstances.
Definition at line 962 of file CobWeb.java.
References moa.clusterers.CobWeb.m_saveInstances.
{
        return m_saveInstances;
    }
double [] moa.clusterers.CobWeb.getVotesForInstance (Instance instance)
Classifies a given instance.
Parameters:
instance the instance to be assigned to a cluster
Returns:
the number of the assigned cluster as an interger if the class is enumerated, otherwise the predicted value
Exceptions:
Exception if instance could not be classified successfully
Implements moa.clusterers.Clusterer.
Definition at line 815 of file CobWeb.java.
References moa.clusterers.CobWeb.determineNumberOfClusters(), moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.CNode.m_children, moa.clusterers.CobWeb.CNode.m_clusterNum, moa.clusterers.CobWeb.m_cobwebTree, moa.clusterers.CobWeb.m_numberOfClusters, and moa.clusterers.CobWeb.CNode.updateStats().
{
        //public int clusterInstance(Instance instance) {//throws Exception {
        CNode host = m_cobwebTree;
        CNode temp = null;
        determineNumberOfClusters();
        if (this.m_numberOfClusters < 1) {
            return (new double[0]);
        }
        double[] ret = new double[this.m_numberOfClusters];
        do {
            if (host.m_children == null) {
                temp = null;
                break;
            }
            host.updateStats(instance, false);
            temp = host.findHost(instance, true);
            host.updateStats(instance, true);
            if (temp != null) {
                host = temp;
            }
        } while (temp != null);
        ret[host.m_clusterNum] = 1.0;
        return ret;
    }
String moa.clusterers.CobWeb.graph ()
Generates the graph string of the Cobweb tree.
Returns:
a String value
Exceptions:
Exception if an error occurs
Definition at line 916 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.graphTree(), and moa.clusterers.CobWeb.m_cobwebTree.
                          {// throws Exception {
        StringBuffer text = new StringBuffer();
        text.append("digraph CobwebTree {\n");
        m_cobwebTree.graphTree(text);
        text.append("}\n");
        return text.toString();
    }
boolean moa.clusterers.CobWeb.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 906 of file CobWeb.java.
{
        return false;
    }
int moa.clusterers.CobWeb.numberOfClusters ()
Returns the number of clusters.
Returns:
the number of clusters
Definition at line 875 of file CobWeb.java.
References moa.clusterers.CobWeb.determineNumberOfClusters(), and moa.clusterers.CobWeb.m_numberOfClusters.
Referenced by moa.clusterers.CobWeb.getClusteringResult(), and moa.clusterers.CobWeb.getModelDescription().
{
        determineNumberOfClusters();
        return m_numberOfClusters;
    }
void moa.clusterers.CobWeb.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 779 of file CobWeb.java.
References moa.clusterers.CobWeb.acuityOption, moa.clusterers.CobWeb.cutoffOption, moa.options.FloatOption.getValue(), moa.clusterers.CobWeb.m_cobwebTree, moa.clusterers.CobWeb.m_numberMerges, moa.clusterers.CobWeb.m_numberOfClusters, moa.clusterers.CobWeb.m_numberSplits, moa.clusterers.CobWeb.setAcuity(), and moa.clusterers.CobWeb.setCutoff().
{
        setAcuity(this.acuityOption.getValue());
        setCutoff(this.cutoffOption.getValue());
        m_numberOfClusters = -1;
        m_cobwebTree = null;
        m_numberSplits = 0;
        m_numberMerges = 0;
    }
void moa.clusterers.CobWeb.setAcuity (double a)
set the acuity.
Parameters:
a the acuity value
Definition at line 929 of file CobWeb.java.
References moa.clusterers.CobWeb.m_acuity.
Referenced by moa.clusterers.CobWeb.resetLearningImpl().
{
        m_acuity = a;
    }
void moa.clusterers.CobWeb.setCutoff (double c)
set the cutoff
Parameters:
c the cutof
Definition at line 945 of file CobWeb.java.
References moa.clusterers.CobWeb.m_cutoff.
Referenced by moa.clusterers.CobWeb.resetLearningImpl().
{
        m_cutoff = c;
    }
void moa.clusterers.CobWeb.setSaveInstanceData (boolean newsaveInstances)
Set the value of saveInstances.
Parameters:
newsaveInstances Value to assign to saveInstances.
Definition at line 972 of file CobWeb.java.
References moa.clusterers.CobWeb.m_saveInstances.
{
        m_saveInstances = newsaveInstances;
    }
void moa.clusterers.CobWeb.trainOnInstanceImpl (Instance newInstance) [virtual]
Adds an instance to the clusterer.
Parameters:
newInstance the instance to be added
Exceptions:
Exception if something goes wrong
Implements moa.clusterers.AbstractClusterer.
Definition at line 796 of file CobWeb.java.
References moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.m_cobwebTree, and moa.clusterers.CobWeb.m_numberOfClustersDetermined.
                                                          { //throws Exception {
        m_numberOfClustersDetermined = false;
        if (m_cobwebTree == null) {
            m_cobwebTree = new CNode(newInstance.numAttributes(), newInstance);
        } else {
            m_cobwebTree.addInstance(newInstance);
        }
    }
Member Data Documentation
FloatOption moa.clusterers.CobWeb.acuityOption
Initial value:
 new FloatOption("acuity",
            'a', "Acuity (minimum standard deviation)", 1.0, 0.0, 90.0)
Definition at line 49 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.resetLearningImpl().
final String moa.clusterers.CobWeb.classifierPurposeString = "Cobweb and Classit clustering algorithms: it always compares the best host, adding a new leaf, merging the two best hosts, and splitting the best host when considering where to place a new instance.." [static]
Definition at line 776 of file CobWeb.java.
FloatOption moa.clusterers.CobWeb.cutoffOption
Initial value:
 new FloatOption("cutoff",
            'c', "Cutoff (minimum category utility)", 0.002, 0.0, 90.0)
Definition at line 51 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.resetLearningImpl().
double moa.clusterers.CobWeb.m_acuity = 1.0 [protected]
Acuity (minimum standard deviation).
Definition at line 746 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.getAcuity(), moa.clusterers.CobWeb.CNode.getStandardDev(), and moa.clusterers.CobWeb.setAcuity().
CNode moa.clusterers.CobWeb.m_cobwebTree = null [protected]
Holds the root of the Cobweb tree.
Definition at line 754 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.determineNumberOfClusters(), moa.clusterers.CobWeb.getClusteringResult(), moa.clusterers.CobWeb.getModelDescription(), moa.clusterers.CobWeb.getVotesForInstance(), moa.clusterers.CobWeb.graph(), moa.clusterers.CobWeb.resetLearningImpl(), and moa.clusterers.CobWeb.trainOnInstanceImpl().
double moa.clusterers.CobWeb.m_cutoff = 0.002 [protected]
Cutoff (minimum category utility).
Definition at line 750 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.addInstance(), moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.getCutoff(), and moa.clusterers.CobWeb.setCutoff().
final double moa.clusterers.CobWeb.m_normal = 1.0 / (2 * Math.sqrt(Math.PI)) [static, protected]
Normal constant.
Definition at line 742 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.categoryUtilityChild().
int moa.clusterers.CobWeb.m_numberMerges [protected]
the number of merges that happened
Definition at line 769 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.getModelDescription(), and moa.clusterers.CobWeb.resetLearningImpl().
int moa.clusterers.CobWeb.m_numberOfClusters = -1 [protected]
Number of clusters (nodes in the tree).
Must never be queried directly, only via the method numberOfClusters(). Otherwise it's not guaranteed that it contains the correct value.
See also:
numberOfClusters()
m_numberOfClustersDetermined
Definition at line 763 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.determineNumberOfClusters(), moa.clusterers.CobWeb.getVotesForInstance(), moa.clusterers.CobWeb.numberOfClusters(), and moa.clusterers.CobWeb.resetLearningImpl().
boolean moa.clusterers.CobWeb.m_numberOfClustersDetermined = false [protected]
whether the number of clusters was already determined
Definition at line 765 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.determineNumberOfClusters(), and moa.clusterers.CobWeb.trainOnInstanceImpl().
int moa.clusterers.CobWeb.m_numberSplits [protected]
the number of splits that happened
Definition at line 767 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.CNode.findHost(), moa.clusterers.CobWeb.getModelDescription(), and moa.clusterers.CobWeb.resetLearningImpl().
boolean moa.clusterers.CobWeb.m_saveInstances = false [protected]
Output instances in graph representation of Cobweb tree (Allows instances at nodes in the tree to be visualized in the Explorer).
Definition at line 774 of file CobWeb.java.
Referenced by moa.clusterers.CobWeb.getSaveInstanceData(), moa.clusterers.CobWeb.CNode.graphTree(), and moa.clusterers.CobWeb.setSaveInstanceData().
IntOption moa.clusterers.CobWeb.randomSeedOption
Initial value:
 new IntOption("randomSeed", 'r',
            "Seed for random noise.", 1)
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 53 of file CobWeb.java.
final long moa.clusterers.CobWeb.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 48 of file CobWeb.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/CobWeb.java