MOA: moa.evaluation.BasicConceptDriftPerformanceEvaluator Class Reference
moa.evaluation.BasicConceptDriftPerformanceEvaluator Class Reference
Public Member Functions
void reset ()
Resets this evaluator.
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
double getTotalWeightObserved ()
double getNumberDetections ()
double getInputValues ()
double getPredictionError ()
double getNumberChanges ()
double getNumberChangesOccurred ()
double getNumberWarnings ()
double getTotalDelay ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
double weightObserved
double numberDetections
double numberDetectionsOccurred
double numberChanges
double numberWarnings
double delay
double errorPrediction
double totalDelay
boolean isWarningZone
double inputValues
Private Attributes
boolean hasChangeOccurred = false
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 26 of file BasicConceptDriftPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 69 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.delay, moa.evaluation.BasicConceptDriftPerformanceEvaluator.errorPrediction, moa.evaluation.BasicConceptDriftPerformanceEvaluator.hasChangeOccurred, moa.evaluation.BasicConceptDriftPerformanceEvaluator.inputValues, moa.evaluation.BasicConceptDriftPerformanceEvaluator.isWarningZone, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberChanges, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetections, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetectionsOccurred, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberWarnings, moa.evaluation.BasicConceptDriftPerformanceEvaluator.totalDelay, and moa.evaluation.BasicConceptDriftPerformanceEvaluator.weightObserved.
{
        //classVotes[0] -> is Change
        //classVotes[1] -> is in Warning Zone
        //classVotes[2] -> delay
        //classVotes[3] -> estimation
        this.inputValues = inst.value(2);
        if (inst.weight() > 0.0 && classVotes.length == 4) {
            if (inst.numAttributes() > 1) {
                //if there is ground truth we monitor delay
                this.delay++;
            }
            this.weightObserved += inst.weight();
            if ( classVotes[0] == 1.0) {
                //Change detected
                //System.out.println("Change detected with delay "+ this.delay );
                this.numberDetections += inst.weight();
                if (this.hasChangeOccurred == true) {
                    this.totalDelay += this.delay - classVotes[2];
                    this.numberDetectionsOccurred += inst.weight();
                    this.hasChangeOccurred = false;
                }
            }
            if (this.hasChangeOccurred && classVotes[1] == 1.0) {
                //Warning detected
                //System.out.println("Warning detected at "+getTotalWeightObserved());
                if (this.isWarningZone == false) {
                    this.numberWarnings += inst.weight();
                    this.isWarningZone = true;
                }
            } else {
                this.isWarningZone = false;
            }
            if (inst.numAttributes() > 1) {
                if (inst.value(inst.numAttributes() - 2) == 1.0) {//Attribute 1
                    //Ground truth Change
                    this.numberChanges += inst.weight();
                    this.delay = 0;
                    this.hasChangeOccurred = true;
                }
            }
            //Compute error prediction
            if (classVotes.length > 1) {
                this.errorPrediction += Math.abs(classVotes[3] - inst.value(0));
            }
        }
    }
void moa.evaluation.BasicConceptDriftPerformanceEvaluator.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 195 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        Measurement.getMeasurementsDescription(getPerformanceMeasurements(),
                sb, indent);
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getInputValues ()
Definition at line 170 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.inputValues.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.inputValues;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChanges ()
Definition at line 178 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberChanges.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.numberChanges;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChangesOccurred ()
Definition at line 182 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetectionsOccurred.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return  this.numberDetectionsOccurred;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberDetections ()
Definition at line 166 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetections.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.numberDetections;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberWarnings ()
Definition at line 186 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberWarnings.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.numberWarnings;
    }
Measurement [] moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 118 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.getInputValues(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChanges(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChangesOccurred(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberDetections(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberWarnings(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPredictionError(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalDelay(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalWeightObserved().
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getDescription().
{
        Measurement[] measurement;
        //if (totalDelay == 0.0) { //No Ground Truth
            measurement = new Measurement[]{
                new Measurement("learned instances",
                getTotalWeightObserved()),
                new Measurement("detected changes",
                getNumberDetections()),
                new Measurement("detected warnings",
                getNumberWarnings()),
                new Measurement("prediction error (average)",
                getPredictionError() / getTotalWeightObserved()),
                new Measurement("true changes",
                getNumberChanges()),
                new Measurement("delay detection (average)",
                getTotalDelay() / getNumberChanges()),
                new Measurement("true changes detected",
                getNumberChangesOccurred()),
                new Measurement("input values",
                getInputValues())
            };
       /* } else {
            measurement = new Measurement[]{
                new Measurement("learned instances",
                getTotalWeightObserved()),
                new Measurement("detected changes",
                getNumberDetections()),
                new Measurement("detected warnings",
                getNumberWarnings()),
                new Measurement("prediction error (average)",
                getPredictionError() / getTotalWeightObserved()),
                new Measurement("true changes",
                getNumberChanges()),
                new Measurement("delay detection (average)",
                getTotalDelay() / getNumberChanges()),
                new Measurement("true changes detected",
                getNumberChangesOccurred()),
                new Measurement("input values",
                getInputValues())
            };
        }*/
        return measurement;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPredictionError ()
Definition at line 174 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.errorPrediction.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.errorPrediction;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalDelay ()
Definition at line 190 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.totalDelay.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.totalDelay;
    }
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalWeightObserved ()
Definition at line 162 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.weightObserved.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPerformanceMeasurements().
{
        return this.weightObserved > 0 ? this.weightObserved : 1.0;
    }
void moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implements moa.evaluation.ClassificationPerformanceEvaluator.
Definition at line 52 of file BasicConceptDriftPerformanceEvaluator.java.
References moa.evaluation.BasicConceptDriftPerformanceEvaluator.delay, moa.evaluation.BasicConceptDriftPerformanceEvaluator.errorPrediction, moa.evaluation.BasicConceptDriftPerformanceEvaluator.hasChangeOccurred, moa.evaluation.BasicConceptDriftPerformanceEvaluator.inputValues, moa.evaluation.BasicConceptDriftPerformanceEvaluator.isWarningZone, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberChanges, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetections, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetectionsOccurred, moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberWarnings, moa.evaluation.BasicConceptDriftPerformanceEvaluator.totalDelay, and moa.evaluation.BasicConceptDriftPerformanceEvaluator.weightObserved.
{
        this.weightObserved = 0.0;
        this.numberDetections = 0.0;
        this.numberDetectionsOccurred = 0.0;
        this.errorPrediction = 0.0;
        this.numberChanges = 0.0;
        this.numberWarnings = 0.0;
        this.delay = 0.0;
        this.totalDelay = 0.0;
        this.isWarningZone = false;
        this.inputValues = 0.0;
        this.hasChangeOccurred = false;
    }
Member Data Documentation
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.delay [protected]
Definition at line 41 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.errorPrediction [protected]
Definition at line 43 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getPredictionError(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
boolean moa.evaluation.BasicConceptDriftPerformanceEvaluator.hasChangeOccurred = false [private]
Definition at line 66 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.inputValues [protected]
Definition at line 49 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getInputValues(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
boolean moa.evaluation.BasicConceptDriftPerformanceEvaluator.isWarningZone [protected]
Definition at line 47 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberChanges [protected]
Definition at line 37 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChanges(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetections [protected]
Definition at line 33 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberDetections(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberDetectionsOccurred [protected]
Definition at line 35 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberChangesOccurred(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.numberWarnings [protected]
Definition at line 39 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getNumberWarnings(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
final long moa.evaluation.BasicConceptDriftPerformanceEvaluator.serialVersionUID = 1L [static, private]
Definition at line 29 of file BasicConceptDriftPerformanceEvaluator.java.
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.totalDelay [protected]
Definition at line 45 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalDelay(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
double moa.evaluation.BasicConceptDriftPerformanceEvaluator.weightObserved [protected]
Definition at line 31 of file BasicConceptDriftPerformanceEvaluator.java.
Referenced by moa.evaluation.BasicConceptDriftPerformanceEvaluator.addResult(), moa.evaluation.BasicConceptDriftPerformanceEvaluator.getTotalWeightObserved(), and moa.evaluation.BasicConceptDriftPerformanceEvaluator.reset().
The documentation for this class was generated from the following file:
main/java/moa/evaluation/BasicConceptDriftPerformanceEvaluator.java