MOA: moa.clusterers.outliers.MCOD.MTreeMicroClusters Class Reference
moa.clusterers.outliers.MCOD.MTreeMicroClusters Class Reference
Public Member Functions
void add (MicroCluster data)
boolean remove (MicroCluster data)
Package Functions
MTreeMicroClusters ()
DistanceFunction<?super
MicroCluster > getDistanceFunction ()
Static Private Attributes
static final PromotionFunction
< MicroCluster > nonRandomPromotion
Detailed Description
Definition at line 33 of file MTreeMicroClusters.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.MCOD.MTreeMicroClusters.MTreeMicroClusters () [package]
Definition at line 43 of file MTreeMicroClusters.java.
References moa.clusterers.outliers.MCOD.MTreeMicroClusters.nonRandomPromotion.
{
        super(2, DistanceFunctions.EUCLIDEAN,
                new ComposedSplitFunction<MicroCluster>(
                nonRandomPromotion,
                new PartitionFunctions.BalancedPartition<MicroCluster>()));
    }
Member Function Documentation
void moa.clusterers.outliers.MCOD.MTreeMicroClusters.add (MicroCluster data)
Definition at line 50 of file MTreeMicroClusters.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.AddMicroCluster(), and moa.clusterers.outliers.MCOD.MCODBase.RangeSearchMC().
{
        super.add(data);
        _check();
    }
DistanceFunction<? super MicroCluster> moa.clusterers.outliers.MCOD.MTreeMicroClusters.getDistanceFunction () [package]
Definition at line 61 of file MTreeMicroClusters.java.
{
        return distanceFunction;
    }
boolean moa.clusterers.outliers.MCOD.MTreeMicroClusters.remove (MicroCluster data)
Definition at line 55 of file MTreeMicroClusters.java.
Referenced by moa.clusterers.outliers.MCOD.MCODBase.RemoveMicroCluster().
{
        boolean result = super.remove(data);
        _check();
        return result;
    }
Member Data Documentation
final PromotionFunction<MicroCluster> moa.clusterers.outliers.MCOD.MTreeMicroClusters.nonRandomPromotion [static, private]
Initial value:
 new PromotionFunction<MicroCluster>() {
        @Override
        public Pair<MicroCluster> process(Set<MicroCluster> dataSet, DistanceFunction<? super MicroCluster> distanceFunction) {
            return Utils.minMax(dataSet);
        }
    }
Definition at line 35 of file MTreeMicroClusters.java.
Referenced by moa.clusterers.outliers.MCOD.MTreeMicroClusters.MTreeMicroClusters().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/MTreeMicroClusters.java