MOA: moa.gui.MultiChoiceOptionEditComponent Class Reference
moa.gui.MultiChoiceOptionEditComponent Class Reference
An OptionEditComponent that lets the user edit a multi choice option.
Public Member Functions
MultiChoiceOptionEditComponent (MultiChoiceOption option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
Protected Attributes
MultiChoiceOption editedOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
An OptionEditComponent that lets the user edit a multi choice option.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file MultiChoiceOptionEditComponent.java.
Constructor & Destructor Documentation
moa.gui.MultiChoiceOptionEditComponent.MultiChoiceOptionEditComponent (MultiChoiceOption option)
Definition at line 40 of file MultiChoiceOptionEditComponent.java.
References moa.gui.MultiChoiceOptionEditComponent.editedOption, moa.options.MultiChoiceOption.getChosenIndex(), and moa.options.MultiChoiceOption.getOptionLabels().
{
        super(option.getOptionLabels());
        this.editedOption = option;
        setSelectedIndex(option.getChosenIndex());
    }
Member Function Documentation
void moa.gui.MultiChoiceOptionEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 47 of file MultiChoiceOptionEditComponent.java.
References moa.gui.MultiChoiceOptionEditComponent.editedOption, and moa.options.MultiChoiceOption.setChosenIndex().
{
        this.editedOption.setChosenIndex(getSelectedIndex());
    }
Option moa.gui.MultiChoiceOptionEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 52 of file MultiChoiceOptionEditComponent.java.
References moa.gui.MultiChoiceOptionEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.MultiChoiceOptionEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 57 of file MultiChoiceOptionEditComponent.java.
References moa.options.AbstractOption.copy(), moa.gui.MultiChoiceOptionEditComponent.editedOption, moa.options.MultiChoiceOption.getChosenIndex(), and moa.options.MultiChoiceOption.setValueViaCLIString().
{
        MultiChoiceOption tempOpt = (MultiChoiceOption) this.editedOption.copy();
        tempOpt.setValueViaCLIString(cliString);
        setSelectedIndex(tempOpt.getChosenIndex());
    }
Member Data Documentation
MultiChoiceOption moa.gui.MultiChoiceOptionEditComponent.editedOption [protected]
Definition at line 38 of file MultiChoiceOptionEditComponent.java.
Referenced by moa.gui.MultiChoiceOptionEditComponent.applyState(), moa.gui.MultiChoiceOptionEditComponent.getEditedOption(), moa.gui.MultiChoiceOptionEditComponent.MultiChoiceOptionEditComponent(), and moa.gui.MultiChoiceOptionEditComponent.setEditState().
final long moa.gui.MultiChoiceOptionEditComponent.serialVersionUID = 1L [static, private]
Definition at line 36 of file MultiChoiceOptionEditComponent.java.
The documentation for this class was generated from the following file:
main/java/moa/gui/MultiChoiceOptionEditComponent.java