MOA: moa.streams.generators.multilabel.MultilabelArffFileStream Class Reference
moa.streams.generators.multilabel.MultilabelArffFileStream Class Reference
Stream reader for ARFF files of multilabel data.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
MultilabelArffFileStream ()
MultilabelArffFileStream (String arffFileName, int numLabels)
InstancesHeader getHeader ()
Gets the header of this stream.
Public Attributes
IntOption numLabelsOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Stream reader for ARFF files of multilabel data.
Author:
Jesse Read (jmr30@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file MultilabelArffFileStream.java.
Constructor & Destructor Documentation
moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream ()
Definition at line 45 of file MultilabelArffFileStream.java.
{
    }
moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream (String arffFileName, int numLabels)
Definition at line 48 of file MultilabelArffFileStream.java.
References moa.streams.ArffFileStream.arffFileOption, moa.streams.generators.multilabel.MultilabelArffFileStream.numLabelsOption, moa.streams.ArffFileStream.restart(), moa.options.IntOption.setValue(), and moa.options.StringOption.setValue().
{
        this.arffFileOption.setValue(arffFileName);
        this.numLabelsOption.setValue(numLabels);
        restart();
    }
Member Function Documentation
InstancesHeader moa.streams.generators.multilabel.MultilabelArffFileStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Reimplemented from moa.streams.ArffFileStream.
Definition at line 55 of file MultilabelArffFileStream.java.
References moa.options.IntOption.getValue(), moa.streams.ArffFileStream.instances, and moa.streams.generators.multilabel.MultilabelArffFileStream.numLabelsOption.
{
        return new MultilabelInstancesHeader(this.instances, numLabelsOption.getValue());
    }
String moa.streams.generators.multilabel.MultilabelArffFileStream.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.streams.ArffFileStream.
Definition at line 36 of file MultilabelArffFileStream.java.
{
        return "A stream read from an ARFF file.";
    }
Member Data Documentation
IntOption moa.streams.generators.multilabel.MultilabelArffFileStream.numLabelsOption
Initial value:
 new IntOption("numLabels", 'l',
            "The number of labels. e.g. n = 10 : the first 10 binary attributes are the labels; n = -10 the last 10 binary attributes are the labels.", -1, -1, Integer.MAX_VALUE)
Definition at line 42 of file MultilabelArffFileStream.java.
Referenced by moa.streams.generators.multilabel.MultilabelArffFileStream.getHeader(), and moa.streams.generators.multilabel.MultilabelArffFileStream.MultilabelArffFileStream().
final long moa.streams.generators.multilabel.MultilabelArffFileStream.serialVersionUID = 1L [static, private]
Reimplemented from moa.streams.ArffFileStream.
Definition at line 40 of file MultilabelArffFileStream.java.
The documentation for this class was generated from the following file:
main/java/moa/streams/generators/multilabel/MultilabelArffFileStream.java