MOA: moa.tasks.EvaluateModel Class Reference
moa.tasks.EvaluateModel Class Reference
Task for evaluating a static model on a stream.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
EvaluateModel ()
EvaluateModel (Classifier model, InstanceStream stream, ClassificationPerformanceEvaluator evaluator, int maxInstances)
Class<?> getTaskResultType ()
Gets the result type of this task.
Object doMainTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Public Attributes
ClassOption modelOption
ClassOption streamOption
ClassOption evaluatorOption
IntOption maxInstancesOption
FileOption outputPredictionFileOption
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Task for evaluating a static model on a stream.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 42 of file EvaluateModel.java.
Constructor & Destructor Documentation
moa.tasks.EvaluateModel.EvaluateModel ()
Definition at line 70 of file EvaluateModel.java.
{
    }
moa.tasks.EvaluateModel.EvaluateModel (Classifier model, InstanceStream stream, ClassificationPerformanceEvaluator evaluator, int maxInstances)
Definition at line 73 of file EvaluateModel.java.
References moa.tasks.EvaluateModel.evaluatorOption, moa.tasks.EvaluateModel.maxInstancesOption, moa.tasks.EvaluateModel.modelOption, moa.options.AbstractClassOption.setCurrentObject(), moa.options.IntOption.setValue(), and moa.tasks.EvaluateModel.streamOption.
{
        this.modelOption.setCurrentObject(model);
        this.streamOption.setCurrentObject(stream);
        this.evaluatorOption.setCurrentObject(evaluator);
        this.maxInstancesOption.setValue(maxInstances);
    }
Member Function Documentation
Object moa.tasks.EvaluateModel.doMainTask (TaskMonitor monitor, ObjectRepository repository) [virtual]
This method performs this task.
AbstractTask implements doTask, that uses doTaskImpl. MainTask implements doTaskImpl using doMainTask so its extensions only need to implement doMainTask.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implements moa.tasks.MainTask.
Definition at line 87 of file EvaluateModel.java.
References moa.evaluation.ClassificationPerformanceEvaluator.addResult(), moa.streams.InstanceStream.estimatedRemainingInstances(), moa.tasks.EvaluateModel.evaluatorOption, moa.options.FileOption.getFile(), moa.options.AbstractOptionHandler.getPreparedClassOption(), moa.options.IntOption.getValue(), moa.classifiers.Classifier.getVotesForInstance(), moa.streams.InstanceStream.hasMoreInstances(), moa.tasks.MainTask.INSTANCES_BETWEEN_MONITOR_UPDATES, moa.tasks.EvaluateModel.maxInstancesOption, moa.tasks.EvaluateModel.modelOption, moa.streams.InstanceStream.nextInstance(), moa.tasks.EvaluateModel.outputPredictionFileOption, moa.tasks.TaskMonitor.resultPreviewRequested(), moa.tasks.TaskMonitor.setCurrentActivity(), moa.tasks.TaskMonitor.setCurrentActivityFractionComplete(), moa.tasks.TaskMonitor.setLatestResultPreview(), moa.tasks.EvaluateModel.streamOption, and moa.tasks.TaskMonitor.taskShouldAbort().
{
        Classifier model = (Classifier) getPreparedClassOption(this.modelOption);
        InstanceStream stream = (InstanceStream) getPreparedClassOption(this.streamOption);
        ClassificationPerformanceEvaluator evaluator = (ClassificationPerformanceEvaluator) getPreparedClassOption(this.evaluatorOption);
        int maxInstances = this.maxInstancesOption.getValue();
        long instancesProcessed = 0;
        monitor.setCurrentActivity("Evaluating model...", -1.0);
        //File for output predictions
        File outputPredictionFile = this.outputPredictionFileOption.getFile();
        PrintStream outputPredictionResultStream = null;
        if (outputPredictionFile != null) {
            try {
                if (outputPredictionFile.exists()) {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile, true), true);
                } else {
                    outputPredictionResultStream = new PrintStream(
                            new FileOutputStream(outputPredictionFile), true);
                }
            } catch (Exception ex) {
                throw new RuntimeException(
                        "Unable to open prediction result file: " + outputPredictionFile, ex);
            }
        }
        while (stream.hasMoreInstances()
                && ((maxInstances < 0) || (instancesProcessed < maxInstances))) {
            Instance testInst = (Instance) stream.nextInstance().copy();
            int trueClass = (int) testInst.classValue();
            //testInst.setClassMissing();
            double[] prediction = model.getVotesForInstance(testInst);
            //evaluator.addClassificationAttempt(trueClass, prediction, testInst
            //      .weight());
            if (outputPredictionFile != null) {
                outputPredictionResultStream.println(Utils.maxIndex(prediction) + "," + trueClass);
            }
            evaluator.addResult(testInst, prediction);
            instancesProcessed++;
            if (instancesProcessed % INSTANCES_BETWEEN_MONITOR_UPDATES == 0) {
                if (monitor.taskShouldAbort()) {
                    return null;
                }
                long estimatedRemainingInstances = stream.estimatedRemainingInstances();
                if (maxInstances > 0) {
                    long maxRemaining = maxInstances - instancesProcessed;
                    if ((estimatedRemainingInstances < 0)
                            || (maxRemaining < estimatedRemainingInstances)) {
                        estimatedRemainingInstances = maxRemaining;
                    }
                }
                monitor.setCurrentActivityFractionComplete(estimatedRemainingInstances < 0 ? -1.0
                        : (double) instancesProcessed
                        / (double) (instancesProcessed + estimatedRemainingInstances));
                if (monitor.resultPreviewRequested()) {
                    monitor.setLatestResultPreview(new LearningEvaluation(
                            evaluator, model));
                }
            }
        }
        if (outputPredictionResultStream != null) {
            outputPredictionResultStream.close();
        }
        return new LearningEvaluation(evaluator, model);
    }
String moa.tasks.EvaluateModel.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 45 of file EvaluateModel.java.
{
        return "Evaluates a static model on a stream.";
    }
Class<?> moa.tasks.EvaluateModel.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implements moa.tasks.Task.
Definition at line 82 of file EvaluateModel.java.
{
        return LearningEvaluation.class;
    }
Member Data Documentation
ClassOption moa.tasks.EvaluateModel.evaluatorOption
Initial value:
 new ClassOption("evaluator", 'e',
            "Classification performance evaluation method.",
            ClassificationPerformanceEvaluator.class,
            "BasicClassificationPerformanceEvaluator")
Definition at line 58 of file EvaluateModel.java.
Referenced by moa.tasks.EvaluateModel.doMainTask(), and moa.tasks.EvaluateModel.EvaluateModel().
IntOption moa.tasks.EvaluateModel.maxInstancesOption
Initial value:
 new IntOption("maxInstances", 'i',
            "Maximum number of instances to test.", 1000000, 0,
            Integer.MAX_VALUE)
Definition at line 63 of file EvaluateModel.java.
Referenced by moa.tasks.EvaluateModel.doMainTask(), and moa.tasks.EvaluateModel.EvaluateModel().
ClassOption moa.tasks.EvaluateModel.modelOption
Initial value:
 new ClassOption("model", 'm',
            "Classifier to evaluate.", Classifier.class, "LearnModel")
Definition at line 51 of file EvaluateModel.java.
Referenced by moa.tasks.EvaluateModel.doMainTask(), and moa.tasks.EvaluateModel.EvaluateModel().
FileOption moa.tasks.EvaluateModel.outputPredictionFileOption
Initial value:
 new FileOption("outputPredictionFile", 'o',
            "File to append output predictions to.", null, "pred", true)
Definition at line 67 of file EvaluateModel.java.
Referenced by moa.tasks.EvaluateModel.doMainTask().
final long moa.tasks.EvaluateModel.serialVersionUID = 1L [static, private]
Reimplemented from moa.tasks.MainTask.
Definition at line 49 of file EvaluateModel.java.
ClassOption moa.tasks.EvaluateModel.streamOption
Initial value:
 new ClassOption("stream", 's',
            "Stream to evaluate on.", InstanceStream.class,
            "generators.RandomTreeGenerator")
Definition at line 54 of file EvaluateModel.java.
Referenced by moa.tasks.EvaluateModel.doMainTask(), and moa.tasks.EvaluateModel.EvaluateModel().
The documentation for this class was generated from the following file:
main/java/moa/tasks/EvaluateModel.java