MOA: moa.evaluation.CMM Class Reference
moa.evaluation.CMM Class Reference
Public Member Functions
void evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception
String getParameterString ()
Public Attributes
boolean debug = false
enable/disable debug mode
boolean enableClassMerge = true
enable/disable class merge (main feature of ground truth analysis)
boolean enableModelError = true
enable/disable model error when enabled errors that are caused by the underling cluster model will not be counted
Protected Member Functions
String[] getNames ()
boolean[] getDefaultEnabled ()
Private Member Functions
void calculateMatching ()
calculates the CMM specific matching between found clusters and ground truth clusters
void calculateError ()
Calculate the actual error values.
double noiseError (CMMPoint cmdp, int assignedClusterID)
double missedError (CMMPoint cmdp, boolean useHullDistance)
double misplacedError (CMMPoint cmdp, int assignedClusterID)
Private Attributes
Clustering clustering
found clustering
CMM_GTAnalysis gtAnalysis
the ground truth analysis
int numPoints
number of points within the horizon
int numFClusters
number of clusters in the found clustering
int numGT0Classes
number of cluster in the adjusted groundtruth clustering that was calculated through the groundtruth analysis
int matchMap []
match found clusters to GT clusters
double[][] pointInclusionProbFC
pointInclusionProbFC[p][C] contains the probability of point p being included in cluster C
double pointInclusionProbThreshold = 0.5
threshold that defines when a point is being considered belonging to a cluster
double lamdaMissed = 1
parameterize the error weight of missed points (default 1)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 37 of file CMM.java.
Member Function Documentation
void moa.evaluation.CMM.calculateError () [private]
Calculate the actual error values.
mainly iterate over all points and find the right error value for the point. within the same run calculate various other stuff like coverage etc...
Definition at line 279 of file CMM.java.
References moa.evaluation.MeasureCollection.addValue(), moa.evaluation.CMM_GTAnalysis.CMMPoint.connectivity, moa.evaluation.CMM.debug, moa.evaluation.CMM_GTAnalysis.getPoint(), moa.evaluation.CMM.gtAnalysis, moa.gui.visualization.DataPoint.isNoise(), moa.evaluation.CMM.matchMap, moa.evaluation.CMM.misplacedError(), moa.evaluation.CMM.missedError(), moa.evaluation.CMM.noiseError(), moa.evaluation.CMM.numFClusters, moa.evaluation.CMM.numPoints, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.evaluation.CMM.pointInclusionProbFC, moa.evaluation.CMM.pointInclusionProbThreshold, moa.gui.visualization.DataPoint.setMeasureValue(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
Referenced by moa.evaluation.CMM.evaluateClustering().
{
        int totalErrorCount = 0;
        int totalRedundancy = 0;
        int trueCoverage = 0;
        int totalCoverage = 0;
        int numNoise = 0;
        double errorNoise = 0;
        double errorNoiseMax = 0;
        double errorMissed = 0;
        double errorMissedMax = 0;
        double errorMisplaced = 0;
        double errorMisplacedMax = 0;
        double totalError = 0.0;
        double totalErrorMax = 0.0;
        for (int p = 0; p < numPoints; p++) {
            CMMPoint cmdp = gtAnalysis.getPoint(p);
            double weight = cmdp.weight();
            //noise counter
            if(cmdp.isNoise()){
                numNoise++;
                //this is always 1
                errorNoiseMax+=cmdp.connectivity*weight;
            }
            else{
                errorMissedMax+=cmdp.connectivity*weight;
                errorMisplacedMax+=cmdp.connectivity*weight;
            }
            //sum up maxError as the individual errors are the quality weighted between 0-1
            totalErrorMax+=cmdp.connectivity*weight;
            double err = 0;
            int coverage = 0;
            //check every FCluster
            for (int c = 0; c < numFClusters; c++) {
                //contained in cluster c?
                if(pointInclusionProbFC[p][c] >= pointInclusionProbThreshold){
                    coverage++;
                    if(!cmdp.isNoise()){
                        //PLACED CORRECTLY
                        if(matchMap[c] == cmdp.workclass()){
                        }
                        //MISPLACED
                        else{
                            double errvalue = misplacedError(cmdp, c);
                            if(errvalue > err)
                                err = errvalue;
                        }
                    }
                    else{
                        //NOISE
                        double errvalue = noiseError(cmdp, c);
                        if(errvalue > err) err = errvalue;
                    }
                }
            }
            //not in any cluster
            if(coverage == 0){
                //MISSED
                if(!cmdp.isNoise()){
                    err = missedError(cmdp,true);
                    errorMissed+= weight*err;
                }
                //NOISE
                else{
                }
            }
            else{
                if(!cmdp.isNoise()){
                    errorMisplaced+= err*weight;
                }
                else{
                    errorNoise+= err*weight;
                }
            }
            /* processing of other evaluation values */
            totalError+= err*weight;
            if(err!=0)totalErrorCount++;
            if(coverage>0) totalCoverage++;  //points covered by clustering (incl. noise)
            if(coverage>0 && !cmdp.isNoise()) trueCoverage++; //points covered by clustering, don't count noise
            if(coverage>1) totalRedundancy++; //include noise
            cmdp.p.setMeasureValue("CMM",err);
            cmdp.p.setMeasureValue("Redundancy", coverage);
        }
        addValue("CMM", (totalErrorMax!=0)?1-totalError/totalErrorMax:1);
        addValue("CMM Missed", (errorMissedMax!=0)?1-errorMissed/errorMissedMax:1);
        addValue("CMM Misplaced", (errorMisplacedMax!=0)?1-errorMisplaced/errorMisplacedMax:1);
        addValue("CMM Noise", (errorNoiseMax!=0)?1-errorNoise/errorNoiseMax:1);
        addValue("CMM Basic", 1-((double)totalErrorCount/(double)numPoints));
        if(debug){
            System.out.println("-------------");
        }
    }
void moa.evaluation.CMM.calculateMatching () [private]
calculates the CMM specific matching between found clusters and ground truth clusters
found cluster frequencies
ground truth cluster frequencies
Definition at line 148 of file CMM.java.
References moa.evaluation.CMM.clustering, moa.evaluation.CMM.debug, moa.cluster.Clustering.get(), moa.evaluation.CMM_GTAnalysis.getGT0Cluster(), moa.cluster.Cluster.getId(), moa.cluster.Cluster.getInclusionProbability(), moa.evaluation.CMM_GTAnalysis.getPoint(), moa.cluster.Cluster.getWeight(), moa.evaluation.CMM.gtAnalysis, moa.gui.visualization.DataPoint.isNoise(), moa.evaluation.CMM.matchMap, moa.evaluation.CMM.numFClusters, moa.evaluation.CMM.numGT0Classes, moa.evaluation.CMM.numPoints, moa.evaluation.CMM.pointInclusionProbFC, moa.evaluation.CMM.pointInclusionProbThreshold, moa.cluster.Cluster.setMeasureValue(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
Referenced by moa.evaluation.CMM.evaluateClustering().
{
        int[][] mapFC = new int[numFClusters][numGT0Classes];
        int[][] mapGT = new int[numGT0Classes][numGT0Classes];
        int [] sumsFC = new int[numFClusters];
        //calculate fuzzy mapping from
        pointInclusionProbFC = new double[numPoints][numFClusters];
        for (int p = 0; p < numPoints; p++) {
            CMMPoint cmdp = gtAnalysis.getPoint(p);
            //found cluster frequencies
            for (int fc = 0; fc < numFClusters; fc++) {
                Cluster cl = clustering.get(fc);
                pointInclusionProbFC[p][fc] = cl.getInclusionProbability(cmdp);
                if (pointInclusionProbFC[p][fc] >= pointInclusionProbThreshold) {
                    //make sure we don't count points twice that are contained in two merged clusters
                    if(cmdp.isNoise()) continue;
                    mapFC[fc][cmdp.workclass()]++;
                    sumsFC[fc]++;
                }
            }
            //ground truth cluster frequencies
            if(!cmdp.isNoise()){
                for(int hc = 0; hc < numGT0Classes;hc++){
                    if(hc == cmdp.workclass()){
                        mapGT[hc][hc]++;
                    }
                    else{
                        if(gtAnalysis.getGT0Cluster(hc).getInclusionProbability(cmdp) >= 1){
                            mapGT[hc][cmdp.workclass()]++;
                        }
                    }
                }
            }
        }
        //assign each found cluster to a hidden cluster
        matchMap = new int[numFClusters];
        for (int fc = 0; fc < numFClusters; fc++) {
            int matchIndex = -1;
            //check if we only have one entry anyway
            for (int hc0 = 0; hc0 < numGT0Classes; hc0++) {
                if(mapFC[fc][hc0]!=0){
                    if(matchIndex == -1)
                        matchIndex = hc0;
                    else{
                        matchIndex = -1;
                        break;
                    }
                }
            }
            //more then one entry, so look for most similar frequency profile
            int minDiff = Integer.MAX_VALUE;
            if(sumsFC[fc]!=0 && matchIndex == -1){
                ArrayList<Integer> fitCandidates = new ArrayList<Integer>();
                for (int hc0 = 0; hc0 < numGT0Classes; hc0++) {
                    int errDiff = 0;
                    for (int hc1 = 0; hc1 < numGT0Classes; hc1++) {
                        //fc profile doesn't fit into current hc profile
                        double freq_diff = mapFC[fc][hc1] - mapGT[hc0][hc1];
                        if(freq_diff > 0){
                            errDiff+= freq_diff;
                        }
                    }
                    if(errDiff == 0){
                        fitCandidates.add(hc0);
                    }
                    if(errDiff < minDiff){
                        minDiff = errDiff;
                        matchIndex = hc0;
                    }
                    if(debug){
                        //System.out.println("FC"+fc+"("+Arrays.toString(mapFC[fc])+") - HC0_"+hc0+"("+Arrays.toString(mapGT[hc0])+"):"+errDiff);
                    }
                }
                //if we have a fitting profile overwrite the min error choice
                //if we have multiple fit candidates, use majority vote of corresponding classes
                if(fitCandidates.size()!=0){
                    int bestGTfit = fitCandidates.get(0);
                    for(int i = 1; i < fitCandidates.size(); i++){
                        int GTfit = fitCandidates.get(i);
                        if(mapFC[fc][GTfit] > mapFC[fc][bestGTfit])
                            bestGTfit=fitCandidates.get(i);
                    }
                    matchIndex = bestGTfit;
                }
            }
            matchMap[fc] = matchIndex;
            int realMatch = -1;
            if(matchIndex==-1){
                if(debug)
                    System.out.println("No cluster match: needs to be implemented?");
            }
            else{
                realMatch = gtAnalysis.getGT0Cluster(matchMap[fc]).getLabel();
            }
            clustering.get(fc).setMeasureValue("CMM Match", "C"+realMatch);
            clustering.get(fc).setMeasureValue("CMM Workclass", "C"+matchMap[fc]);
        }
        //print matching table
        if(debug){
            for (int i = 0; i < numFClusters; i++) {
                    System.out.print("C"+((int)clustering.get(i).getId()) + " N:"+((int)clustering.get(i).getWeight())+"  |  ");
                    for (int j = 0; j < numGT0Classes; j++) {
                          System.out.print(mapFC[i][j] + " ");
                    }
                    System.out.print(" = "+sumsFC[i] + " | ");
                    String match = "-";
                    if (matchMap[i]!=-1) {
                        match = Integer.toString(gtAnalysis.getGT0Cluster(matchMap[i]).getLabel());
                    }
                    System.out.println(" --> " + match + "(work:"+matchMap[i]+")");
             }
        }
    }
void moa.evaluation.CMM.evaluateClustering (Clustering clustering, Clustering trueClustering, ArrayList< DataPoint > points) throws Exception [virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 123 of file CMM.java.
References moa.evaluation.MeasureCollection.addValue(), moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.clustering, moa.evaluation.CMM.enableClassMerge, moa.evaluation.CMM_GTAnalysis.getClassSeparability(), moa.evaluation.CMM_GTAnalysis.getModelQuality(), moa.evaluation.CMM_GTAnalysis.getNoiseSeparability(), moa.evaluation.CMM_GTAnalysis.getNumberOfGT0Classes(), moa.evaluation.CMM.gtAnalysis, moa.evaluation.CMM.numFClusters, moa.evaluation.CMM.numGT0Classes, moa.evaluation.CMM.numPoints, and moa.cluster.Clustering.size().
{
        this.clustering = clustering;
        numPoints = points.size();
        numFClusters = clustering.size();
        gtAnalysis = new CMM_GTAnalysis(trueClustering, points, enableClassMerge);
        numGT0Classes = gtAnalysis.getNumberOfGT0Classes();
        addValue("CA Seperability",gtAnalysis.getClassSeparability());
        addValue("CA Noise",gtAnalysis.getNoiseSeparability());
        addValue("CA Modell",gtAnalysis.getModelQuality());
        /* init the matching and point distances */
        calculateMatching();
        /* calculate the actual error */
        calculateError();
    }
boolean [] moa.evaluation.CMM.getDefaultEnabled () [protected]
Reimplemented from moa.evaluation.MeasureCollection.
Definition at line 116 of file CMM.java.
{
        boolean [] defaults = {false, false, false, false, false, false, false, false};
        return defaults;
    }
String [] moa.evaluation.CMM.getNames () [protected, virtual]
Implements moa.evaluation.MeasureCollection.
Definition at line 109 of file CMM.java.
References moa.evaluation.MeasureCollection.names.
{
        String[] names = {"CMM","CMM Basic","CMM Missed","CMM Misplaced","CMM Noise",
                            "CA Seperability", "CA Noise", "CA Modell"};
        return names;
    }
String moa.evaluation.CMM.getParameterString ()
Definition at line 497 of file CMM.java.
References moa.evaluation.CMM_GTAnalysis.getParameterString(), moa.evaluation.CMM.gtAnalysis, and moa.evaluation.CMM.lamdaMissed.
{
        String para = gtAnalysis.getParameterString();
        para+="lambdaMissed="+lamdaMissed+";";
        return para;
    }
double moa.evaluation.CMM.misplacedError (CMMPoint cmdp, int assignedClusterID) [private]
Definition at line 459 of file CMM.java.
References moa.evaluation.CMM_GTAnalysis.CMMPoint.connectivity, moa.evaluation.CMM.enableModelError, moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.evaluation.CMM_GTAnalysis.getGT0Cluster(), moa.gui.visualization.DataPoint.getTimestamp(), moa.evaluation.CMM.gtAnalysis, moa.evaluation.CMM.matchMap, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.evaluation.CMM.pointInclusionProbThreshold, moa.gui.visualization.DataPoint.setMeasureValue(), moa.evaluation.CMM_GTAnalysis.CMMPoint.trueClass, and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
Referenced by moa.evaluation.CMM.calculateError().
{
        double weight = 0;
        int gtAssignedID = matchMap[assignedClusterID];
        //TODO take care of noise cluster?
        if(gtAssignedID ==-1){
            System.out.println("Point "+cmdp.getTimestamp()+" from gtcluster "+cmdp.trueClass+" assigned to noise cluster "+assignedClusterID);
            return 1;
        }
        if(gtAssignedID == cmdp.workclass())
            return 0;
        else{
            //assigned and real GT0 cluster are not connected, but does the model have the
            //chance of separating this point after all?
            if(enableModelError && gtAnalysis.getGT0Cluster(gtAssignedID).getInclusionProbability(cmdp) >= pointInclusionProbThreshold){
                weight = 0;
                cmdp.p.setMeasureValue("CMM Type","missplaced - byModel");
            }
            else{
                //point was mapped onto wrong cluster (assigned), so check how far away
                //the nearest point is within the wrongly assigned cluster
                weight = 1 - gtAnalysis.getConnectionValue(cmdp, gtAssignedID);
            }
        }
        double err_value;
        //set to MIN_ERROR so we can still track the error
        if(weight == 0){
            err_value= 0.00001;
        }
        else{
            err_value = weight*cmdp.connectivity;
            cmdp.p.setMeasureValue("CMM Type","missplaced");
        }
        return err_value;
    }
double moa.evaluation.CMM.missedError (CMMPoint cmdp, boolean useHullDistance) [private]
Definition at line 414 of file CMM.java.
References moa.evaluation.CMM.clustering, moa.evaluation.CMM_GTAnalysis.CMMPoint.connectivity, moa.cluster.Clustering.get(), moa.cluster.SphereCluster.getCenterDistance(), moa.cluster.SphereCluster.getRadius(), moa.evaluation.CMM.lamdaMissed, moa.evaluation.CMM.matchMap, moa.evaluation.CMM.numFClusters, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.gui.visualization.DataPoint.setMeasureValue(), and moa.evaluation.CMM_GTAnalysis.CMMPoint.workclass().
Referenced by moa.evaluation.CMM.calculateError().
{
        cmdp.p.setMeasureValue("CMM Type","missed");
        if(!useHullDistance){
            return cmdp.connectivity;
        }
        else{
            //main idea: look at relative distance of missed point to cluster
            double minHullDist = 1;
            for (int fc = 0; fc < numFClusters; fc++){
                //if fc is mappend onto the class of the point, check it for its hulldist
                if(matchMap[fc]!=-1 && matchMap[fc] == cmdp.workclass()){
                    if(clustering.get(fc) instanceof SphereCluster){
                        SphereCluster sc = (SphereCluster)clustering.get(fc);
                        double distanceFC = sc.getCenterDistance(cmdp);
                        double radius = sc.getRadius();
                        double hullDist = (distanceFC-radius)/(distanceFC+radius);
                        if(hullDist < minHullDist)
                            minHullDist = hullDist;
                    }
                    else{
                        double min = 1;
                        double max = 1;
                        //TODO: distance for random shape
                        //generate X points from the cluster with clustering.get(fc).sample(null)
                        //and find Min and Max values
                        double hullDist = min/max;
                        if(hullDist < minHullDist)
                            minHullDist = hullDist;
                    }
                }
            }
            //use distance as weight
            if(minHullDist>1) minHullDist = 1;
            double weight = (1-Math.exp(-lamdaMissed*minHullDist));
            cmdp.p.setMeasureValue("HullDistWeight",weight);
            return weight*cmdp.connectivity;
        }
    }
double moa.evaluation.CMM.noiseError (CMMPoint cmdp, int assignedClusterID) [private]
Definition at line 388 of file CMM.java.
References moa.evaluation.CMM.enableModelError, moa.evaluation.CMM_GTAnalysis.getConnectionValue(), moa.evaluation.CMM_GTAnalysis.getGT0Cluster(), moa.evaluation.CMM.gtAnalysis, moa.evaluation.CMM.matchMap, moa.evaluation.CMM_GTAnalysis.CMMPoint.p, moa.evaluation.CMM.pointInclusionProbThreshold, and moa.gui.visualization.DataPoint.setMeasureValue().
Referenced by moa.evaluation.CMM.calculateError().
{
        int gtAssignedID = matchMap[assignedClusterID];
        double error;
        //Cluster wasn't matched, so just contains noise
        //TODO: Noiscluster?
        //also happens when we decrease the radius and there is only a noise point in the center
        if(gtAssignedID==-1){
            error = 1;
            cmdp.p.setMeasureValue("CMM Type","noise - cluster");
        }
        else{
            if(enableModelError && gtAnalysis.getGT0Cluster(gtAssignedID).getInclusionProbability(cmdp) >= pointInclusionProbThreshold){
                //set to MIN_ERROR so we can still track the error
                error = 0.00001;
                cmdp.p.setMeasureValue("CMM Type","noise - byModel");
            }
            else{
                error = 1 - gtAnalysis.getConnectionValue(cmdp, gtAssignedID);
                cmdp.p.setMeasureValue("CMM Type","noise");
            }
        }
        return error;
    }
Member Data Documentation
Clustering moa.evaluation.CMM.clustering [private]
found clustering
Definition at line 45 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.evaluateClustering(), and moa.evaluation.CMM.missedError().
boolean moa.evaluation.CMM.debug = false
enable/disable debug mode
Reimplemented from moa.evaluation.MeasureCollection.
Definition at line 93 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), and moa.evaluation.CMM.calculateMatching().
boolean moa.evaluation.CMM.enableClassMerge = true
enable/disable class merge (main feature of ground truth analysis)
Definition at line 99 of file CMM.java.
Referenced by moa.evaluation.CMM.evaluateClustering().
boolean moa.evaluation.CMM.enableModelError = true
enable/disable model error when enabled errors that are caused by the underling cluster model will not be counted
Definition at line 105 of file CMM.java.
Referenced by moa.evaluation.CMM.misplacedError(), and moa.evaluation.CMM.noiseError().
CMM_GTAnalysis moa.evaluation.CMM.gtAnalysis [private]
the ground truth analysis
Definition at line 50 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.evaluateClustering(), moa.evaluation.CMM.getParameterString(), moa.evaluation.CMM.misplacedError(), and moa.evaluation.CMM.noiseError().
double moa.evaluation.CMM.lamdaMissed = 1 [private]
parameterize the error weight of missed points (default 1)
Definition at line 87 of file CMM.java.
Referenced by moa.evaluation.CMM.getParameterString(), and moa.evaluation.CMM.missedError().
int moa.evaluation.CMM.matchMap[] [private]
match found clusters to GT clusters
Definition at line 71 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.misplacedError(), moa.evaluation.CMM.missedError(), and moa.evaluation.CMM.noiseError().
int moa.evaluation.CMM.numFClusters [private]
number of clusters in the found clustering
Definition at line 60 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.evaluateClustering(), and moa.evaluation.CMM.missedError().
int moa.evaluation.CMM.numGT0Classes [private]
number of cluster in the adjusted groundtruth clustering that was calculated through the groundtruth analysis
Definition at line 66 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateMatching(), and moa.evaluation.CMM.evaluateClustering().
int moa.evaluation.CMM.numPoints [private]
number of points within the horizon
Definition at line 55 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), and moa.evaluation.CMM.evaluateClustering().
double [][] moa.evaluation.CMM.pointInclusionProbFC [private]
pointInclusionProbFC[p][C] contains the probability of point p being included in cluster C
Definition at line 77 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), and moa.evaluation.CMM.calculateMatching().
double moa.evaluation.CMM.pointInclusionProbThreshold = 0.5 [private]
threshold that defines when a point is being considered belonging to a cluster
Definition at line 82 of file CMM.java.
Referenced by moa.evaluation.CMM.calculateError(), moa.evaluation.CMM.calculateMatching(), moa.evaluation.CMM.misplacedError(), and moa.evaluation.CMM.noiseError().
final long moa.evaluation.CMM.serialVersionUID = 1L [static, private]
Definition at line 40 of file CMM.java.
The documentation for this class was generated from the following file:
main/java/moa/evaluation/CMM.java