MOA: moa.gui.ClassOptionWithNamesEditComponent Class Reference
moa.gui.ClassOptionWithNamesEditComponent Class Reference
Public Member Functions
ClassOptionWithNamesEditComponent (ClassOptionWithNames option)
void applyState ()
This method applies the state.
Option getEditedOption ()
Gets the option of this component.
void setEditState (String cliString)
Sets the state of the component.
void editObject ()
void addChangeListener (ChangeListener l)
Adds the listener to the internal set of listeners.
void removeChangeListener (ChangeListener l)
Removes the listener from the internal set of listeners.
Protected Member Functions
void notifyChangeListeners ()
Notifies all registered change listeners that the options have changed.
Protected Attributes
ClassOptionWithNames editedOption
JTextField textField = new JTextField()
JButton editButton = new JButton("Edit")
HashSet< ChangeListener > changeListeners = new HashSet<ChangeListener>()
listeners that listen to changes to the chosen option.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 29 of file ClassOptionWithNamesEditComponent.java.
Constructor & Destructor Documentation
moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent (ClassOptionWithNames option)
Definition at line 42 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.editButton, moa.gui.ClassOptionWithNamesEditComponent.editedOption, moa.gui.ClassOptionWithNamesEditComponent.editObject(), moa.options.ClassOptionWithNames.getValueAsCLIString(), moa.gui.ClassOptionWithNamesEditComponent.notifyChangeListeners(), moa.gui.ClassOptionWithNamesEditComponent.setEditState(), and moa.gui.ClassOptionWithNamesEditComponent.textField.
{
        this.editedOption = option;
        this.textField.setEditable(false);
        this.textField.getDocument().addDocumentListener(new DocumentListener() {
            public void removeUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
            public void insertUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
            public void changedUpdate(DocumentEvent e) {
                notifyChangeListeners();
            }
        });
        setLayout(new BorderLayout());
        add(this.textField, BorderLayout.CENTER);
        add(this.editButton, BorderLayout.EAST);
        this.editButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                editObject();
            }
        });
        setEditState(this.editedOption.getValueAsCLIString());
    }
Member Function Documentation
void moa.gui.ClassOptionWithNamesEditComponent.addChangeListener (ChangeListener l)
Adds the listener to the internal set of listeners.
Gets notified when the option string changes.
Parameters:
l the listener to add
Definition at line 97 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.changeListeners.
{
        changeListeners.add(l);
    }
void moa.gui.ClassOptionWithNamesEditComponent.applyState ()
This method applies the state.
Implements moa.gui.OptionEditComponent.
Definition at line 72 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.editedOption, moa.options.ClassOptionWithNames.setValueViaCLIString(), and moa.gui.ClassOptionWithNamesEditComponent.textField.
{
        this.editedOption.setValueViaCLIString(this.textField.getText());
    }
void moa.gui.ClassOptionWithNamesEditComponent.editObject ()
Definition at line 84 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.editedOption, moa.options.ClassOptionWithNames.getClassNames(), moa.options.AbstractClassOption.getNullString(), moa.options.AbstractClassOption.getRequiredType(), moa.gui.ClassOptionWithNamesEditComponent.setEditState(), and moa.gui.ClassOptionWithNamesEditComponent.textField.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent().
{
        setEditState(ClassOptionWithNamesSelectionPanel.showSelectClassDialog(this,
                "Editing option: " + this.editedOption.getName(),
                this.editedOption.getRequiredType(), this.textField.getText(),
                this.editedOption.getNullString(), this.editedOption.getClassNames()));
    }
Option moa.gui.ClassOptionWithNamesEditComponent.getEditedOption ()
Gets the option of this component.
Returns:
the option of this component
Implements moa.gui.OptionEditComponent.
Definition at line 76 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.editedOption.
{
        return this.editedOption;
    }
void moa.gui.ClassOptionWithNamesEditComponent.notifyChangeListeners () [protected]
Notifies all registered change listeners that the options have changed.
Definition at line 113 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.changeListeners.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent().
{
        ChangeEvent e = new ChangeEvent(this);
        for (ChangeListener l : changeListeners) {
            l.stateChanged(e);
        }
    }
void moa.gui.ClassOptionWithNamesEditComponent.removeChangeListener (ChangeListener l)
Removes the listener from the internal set of listeners.
Parameters:
l the listener to remove
Definition at line 106 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.changeListeners.
{
        changeListeners.remove(l);
    }
void moa.gui.ClassOptionWithNamesEditComponent.setEditState (String cliString)
Sets the state of the component.
Parameters:
cliString the state of the component
Implements moa.gui.OptionEditComponent.
Definition at line 80 of file ClassOptionWithNamesEditComponent.java.
References moa.gui.ClassOptionWithNamesEditComponent.textField.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent(), and moa.gui.ClassOptionWithNamesEditComponent.editObject().
{
        this.textField.setText(cliString);
    }
Member Data Documentation
HashSet<ChangeListener> moa.gui.ClassOptionWithNamesEditComponent.changeListeners = new HashSet<ChangeListener>() [protected]
listeners that listen to changes to the chosen option.
Definition at line 40 of file ClassOptionWithNamesEditComponent.java.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.addChangeListener(), moa.gui.ClassOptionWithNamesEditComponent.notifyChangeListeners(), and moa.gui.ClassOptionWithNamesEditComponent.removeChangeListener().
JButton moa.gui.ClassOptionWithNamesEditComponent.editButton = new JButton("Edit") [protected]
Definition at line 37 of file ClassOptionWithNamesEditComponent.java.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent().
ClassOptionWithNames moa.gui.ClassOptionWithNamesEditComponent.editedOption [protected]
Definition at line 33 of file ClassOptionWithNamesEditComponent.java.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.applyState(), moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent(), moa.gui.ClassOptionWithNamesEditComponent.editObject(), and moa.gui.ClassOptionWithNamesEditComponent.getEditedOption().
final long moa.gui.ClassOptionWithNamesEditComponent.serialVersionUID = 1L [static, private]
Definition at line 31 of file ClassOptionWithNamesEditComponent.java.
JTextField moa.gui.ClassOptionWithNamesEditComponent.textField = new JTextField() [protected]
Definition at line 35 of file ClassOptionWithNamesEditComponent.java.
Referenced by moa.gui.ClassOptionWithNamesEditComponent.applyState(), moa.gui.ClassOptionWithNamesEditComponent.ClassOptionWithNamesEditComponent(), moa.gui.ClassOptionWithNamesEditComponent.editObject(), and moa.gui.ClassOptionWithNamesEditComponent.setEditState().
The documentation for this class was generated from the following file:
main/java/moa/gui/ClassOptionWithNamesEditComponent.java