MOA: moa.clusterers.outliers.Angiulli.ApproxSTORM Class Reference
moa.clusterers.outliers.Angiulli.ApproxSTORM Class Reference
Classes
class ISBNodeAppr
Public Member Functions
String getObjectInfo (Object obj)
ApproxSTORM ()
void Init ()
Public Attributes
FloatOption radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
IntOption kOption = new IntOption("k", 't', "Parameter k.", 50)
IntOption queryFreqOption = new IntOption("queryFreq", 'q', "Query frequency.", 1)
FloatOption pOption = new FloatOption("p", 'p', "Parameter p.", 0.1)
Protected Member Functions
void ProcessNewStreamObj (Instance inst)
Package Functions
void AddSafeInlier (ISBNode node)
ISBNode GetSafeInlier (int idx)
boolean IsSafeInlier (ISBNodeAppr node)
void PrintSafeInliers ()
void RemoveNode (ISBNode node)
void RemoveSafeInlier (ISBNode node)
void DeleteExpiredNode ()
void SearchOutliers ()
void UpdateNodeType (ISBNodeAppr node)
void UpdateNodeStatistics (ISBNodeAppr node)
Package Attributes
Set< ISBNode > safe_inliers
int m_FractWindowSize
Random m_Random
Detailed Description
Definition at line 35 of file ApproxSTORM.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.Angiulli.ApproxSTORM.ApproxSTORM ()
Definition at line 96 of file ApproxSTORM.java.
    {
        // System.out.println("DistanceOutliersAppr: created");
    }
Member Function Documentation
void moa.clusterers.outliers.Angiulli.ApproxSTORM.AddSafeInlier (ISBNode node) [package]
Definition at line 133 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        safe_inliers.add(node);
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode () [package]
Definition at line 182 of file ApproxSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowStart(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        if (windowNodes.size() <= 0)
            return;
        // get oldest node
        ISBNode node = windowNodes.get(0);
        // check if node has expired
        if (node.id < GetWindowStart()) {
            if (bTrace) {
                Print("Delete expired node: ");
                PrintNode(node);
            }
            // remove node
            RemoveNode(node);
        }
    }
String moa.clusterers.outliers.Angiulli.ApproxSTORM.getObjectInfo (Object obj)
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 59 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_after, moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_before, moa.clusterers.outliers.Angiulli.StreamObj.dimensions(), moa.clusterers.outliers.Angiulli.StreamObj.get(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.obj.
{
        if (obj == null) return null;
        ISBNodeAppr node = (ISBNodeAppr) obj;
        ArrayList<String> infoTitle = new ArrayList<String>();
        ArrayList<String> infoValue = new ArrayList<String>();
        StringBuilder sb = new StringBuilder();
        // show node position
        for (int i = 0; i < node.obj.dimensions(); i++) {
            infoTitle.add("Dim" + (i+1));
            infoValue.add(String.format("%.3f", node.obj.get(i)));
        }
        // show node properties
        infoTitle.add("id");
        infoValue.add(String.format("%d", node.id));
        infoTitle.add("count_after");
        infoValue.add(String.format("%d", node.count_after));
        infoTitle.add("count_before");
        infoValue.add(String.format("%d", node.count_before));
        sb.append("<html>");
        sb.append("<table>");
        int i = 0;
        while(i < infoTitle.size() && i < infoValue.size()){
            sb.append("<tr><td><b>"+infoTitle.get(i)+":</b></td><td>"+infoValue.get(i)+"</td></tr>");
            i++;
        }
        sb.append("</table>");
        sb.append("</html>");
        return sb.toString();
    }
ISBNode moa.clusterers.outliers.Angiulli.ApproxSTORM.GetSafeInlier (int idx) [package]
Definition at line 137 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        ISBNode node = null;
        Iterator it = safe_inliers.iterator();
        while (idx >= 0) {
            node = (ISBNodeAppr)it.next();
            idx--;
        }
        return node;
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.Init ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 102 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.STORMBase.FIRST_OBJ_ID, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ApproxSTORM.kOption, moa.clusterers.outliers.Angiulli.ApproxSTORM.m_FractWindowSize, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_nBothInlierOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyInlier, moa.clusterers.outliers.Angiulli.STORMBase.m_nOnlyOutlier, moa.clusterers.outliers.Angiulli.STORMBase.m_QueryFreq, moa.clusterers.outliers.Angiulli.STORMBase.m_radius, moa.clusterers.outliers.Angiulli.ApproxSTORM.m_Random, moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize, moa.clusterers.outliers.Angiulli.STORMBase.objId, moa.clusterers.outliers.Angiulli.ApproxSTORM.pOption, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.ApproxSTORM.queryFreqOption, moa.clusterers.outliers.Angiulli.ApproxSTORM.radiusOption, moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers, moa.clusterers.outliers.Angiulli.STORMBase.windowNodes, and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
                       {
        super.Init();
        m_WindowSize = windowSizeOption.getValue();
        m_radius = radiusOption.getValue();
        m_k = kOption.getValue();
        m_QueryFreq = queryFreqOption.getValue();
        m_FractWindowSize = (int) (pOption.getValue() * m_WindowSize);
        Println("Init DistanceOutliersAppr:");
        Println("   window_size: " + m_WindowSize);
        Println("   radius: " + m_radius);
        Println("   k: " + m_k);
        Println("   query_freq: " + m_QueryFreq);
        m_Random = new Random();
        objId = FIRST_OBJ_ID; // init object identifier
        // create fifo
        windowNodes = new Vector<ISBNode>();
        // create ISB
        ISB = new ISBIndex(m_radius, m_k);
        // create safe_inliers list
        safe_inliers = new HashSet<ISBNode>();
        // init statistics
        m_nBothInlierOutlier = 0;
        m_nOnlyInlier = 0;
        m_nOnlyOutlier = 0;
    }
boolean moa.clusterers.outliers.Angiulli.ApproxSTORM.IsSafeInlier (ISBNodeAppr node) [package]
Definition at line 147 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_after, and moa.clusterers.outliers.Angiulli.STORMBase.m_k.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        return node.count_after >= m_k;
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.PrintSafeInliers () [package]
Definition at line 151 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        Print("Safe inliers: ");
        ISBNode node;
        Iterator it = safe_inliers.iterator();
        while (it.hasNext()) {
            node = (ISBNode) it.next();
            Print(node.id + " ");
        }
        Println(" ");
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 200 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.AddSafeInlier(), moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.STORMBase.CanSearch(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_after, moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_before, moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.fract_before, moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues(), moa.clusterers.outliers.Angiulli.ApproxSTORM.GetSafeInlier(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.Insert(), moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ApproxSTORM.IsSafeInlier(), moa.clusterers.outliers.Angiulli.ApproxSTORM.m_FractWindowSize, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_radius, moa.clusterers.outliers.Angiulli.ApproxSTORM.m_Random, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.Angiulli.STORMBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.PrintSafeInliers(), moa.clusterers.outliers.Angiulli.STORMBase.PrintWindow(), moa.clusterers.outliers.Angiulli.ISBIndex.RangeSearch(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveSafeInlier(), moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers, moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers(), moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress(), moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeStatistics(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
    {
        if (bShowProgress) ShowProgress("Processed " + objId + " stream objects.");
        // PrintInstance(inst);
        double[] values = getInstanceValues(inst);
        StreamObj obj = new StreamObj(values);
        if (bTrace) Println("\n- - - - - - - - - - - -\n");
        // delete a node if it has expired
        DeleteExpiredNode();
        // create new ISB node
        ISBNodeAppr nodeNew = new ISBNodeAppr(inst, obj, objId, m_k);
        if (bTrace) {
            Print("New obj: ");
            PrintNode(nodeNew);
        }
        // update object identifier
        objId++;
        // init nodeNew
        nodeNew.count_after = 1L;
        nodeNew.count_before = 0L;
        // perform range query search
        if (bTrace) Println("Perform range query seach:");
        nRangeQueriesExecuted++;
        Vector<ISBIndex.ISBSearchResult> nodes = ISB.RangeSearch(nodeNew, m_radius);
        // process each returned node
        int nSafeInliers;
        Long count_si_before = 0L;
        for (ISBSearchResult res : nodes) {
            ISBNodeAppr n = (ISBNodeAppr) res.node;
            if (bTrace) {
                Printf("   Found at d=%.2f: ", res.distance);
                PrintNode(res.node);
            }
            n.count_after++;
            if (IsSafeInlier(n)) {
                if (bTrace) Println("   Safe inlier: id=" + n.id);
                AddSafeInlier(n);
                count_si_before++;
            }
            nSafeInliers = safe_inliers.size();
            if (nSafeInliers > m_FractWindowSize) {
                // get a random safe inlier: 0 <= idx < nSafeInliers
                int idx = m_Random.nextInt(nSafeInliers);
                ISBNode si = GetSafeInlier(idx);
                if (bTrace) Println("   Remove random safe inlier: id=" + si.id);
                // remove node from ISB and safe-inliers-list
                RemoveSafeInlier(si);
            }
            nodeNew.count_before++;
        }
        // Set fract_before of curr_node which is determined as the ratio
        // between the number of preceding neighbors of curr_node in ISB
        // which are safe inliers and the total number of safe inliers in
        // ISB, at the arrival time of curr_node.
        nSafeInliers = safe_inliers.size();
        if (nSafeInliers > 0) {
            nodeNew.fract_before = (double)count_si_before / (double)nSafeInliers;
        }
        else {
            if (bTrace) Println("Set fract before: no safe inliers yet, set 0.");
            nodeNew.fract_before = 0;
        }
        if (bTrace) {
            Println("Node: ");
            Println("   count_after=" + nodeNew.count_after);
            Println("   count_before=" + nodeNew.count_before);
            Printf("   fract_before=%.3f\n", nodeNew.fract_before);
            Println("Insert new node to ISB.");
        }
        // insert node to ISB
        ISB.Insert(nodeNew);
        // insert node at window
        windowNodes.add(nodeNew);
        if (bTrace) {
            PrintWindow();
            PrintSafeInliers();
        }
        if (CanSearch()) {
            // invoke query function to detect outliers
            SearchOutliers();
        } else {
            // update statistics outlierness of new node
            UpdateNodeStatistics(nodeNew);
        }
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode (ISBNode node) [package]
Definition at line 162 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.inst, moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ISBIndex.Remove(), moa.clusterers.outliers.MyBaseOutlierDetector.RemoveExpiredOutlier(), moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers, moa.clusterers.outliers.Angiulli.STORMBase.UpdateStatistics(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.DeleteExpiredNode().
{
        // remove node from ISB
        ISB.Remove(node);
        // remove from fifo
        windowNodes.remove(node);
        // remove node from safe_inliers
        safe_inliers.remove(node);
        // remove from outliers
        RemoveExpiredOutlier(new Outlier(node.inst, node.id, node));
        // update statistics
        UpdateStatistics(node);
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveSafeInlier (ISBNode node) [package]
Definition at line 175 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.STORMBase.ISB, moa.clusterers.outliers.Angiulli.ISBIndex.Remove(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        // remove node from ISB
        ISB.Remove(node);
        // remove node from safe_inliers
        safe_inliers.remove(node);
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers () [package]
Definition at line 305 of file ApproxSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType(), and moa.clusterers.outliers.Angiulli.STORMBase.windowNodes.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        if (bTrace) Println("Invoke query: ");
        ISBNodeAppr node;
        // process each node in the ISB (also in window)
        for (int i = 0; i < windowNodes.size(); i++) {
            node = (ISBNodeAppr) windowNodes.get(i);
            if (bTrace) {
                Print("   Process node: ");
                PrintNode(node);
            }
            UpdateNodeType(node);
        }
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeStatistics (ISBNodeAppr node) [package]
Definition at line 342 of file ApproxSTORM.java.
References moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_after, moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.fract_before, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize, moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nInlier, and moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
{
        double succ_neighs = node.count_after;
        double prec_neighs = node.fract_before * (double)Math.abs((node.id + m_WindowSize) - GetWindowEnd());
        if (succ_neighs + prec_neighs < m_k) {
            node.nOutlier++; // update statistics
        } else {
            node.nInlier++; // update statistics
        }
    }
void moa.clusterers.outliers.Angiulli.ApproxSTORM.UpdateNodeType (ISBNodeAppr node) [package]
Definition at line 319 of file ApproxSTORM.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.count_after, moa.clusterers.outliers.Angiulli.ApproxSTORM.ISBNodeAppr.fract_before, moa.clusterers.outliers.Angiulli.STORMBase.GetWindowEnd(), moa.clusterers.outliers.Angiulli.ISBIndex.ISBNode.id, moa.clusterers.outliers.Angiulli.STORMBase.m_k, moa.clusterers.outliers.Angiulli.STORMBase.m_WindowSize, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.Angiulli.STORMBase.PrintNode(), moa.clusterers.outliers.Angiulli.STORMBase.RemoveOutlier(), and moa.clusterers.outliers.Angiulli.STORMBase.SaveOutlier().
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.SearchOutliers().
{
        double succ_neighs, prec_neighs;
        // get number of succeeding neighbors
        succ_neighs = node.count_after;
        if (bTrace) Println("      succ_neighs: " + succ_neighs);
        // get number of preceding neighbors
        prec_neighs = node.fract_before * (double)Math.abs((node.id + m_WindowSize) - GetWindowEnd());
        if (bTrace) Println("      prec_neighs: " + prec_neighs);
        // check if node is an outlier
        if (succ_neighs + prec_neighs < m_k) {
            SaveOutlier(node);
            if (bTrace) {
                Print("*** Outlier: ");
                PrintNode(node);
            }
        } else {
            RemoveOutlier(node);
        }
    }
Member Data Documentation
IntOption moa.clusterers.outliers.Angiulli.ApproxSTORM.kOption = new IntOption("k", 't', "Parameter k.", 50)
Definition at line 50 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init().
int moa.clusterers.outliers.Angiulli.ApproxSTORM.m_FractWindowSize [package]
Definition at line 55 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
Random moa.clusterers.outliers.Angiulli.ApproxSTORM.m_Random [package]
Definition at line 56 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj().
FloatOption moa.clusterers.outliers.Angiulli.ApproxSTORM.pOption = new FloatOption("p", 'p', "Parameter p.", 0.1)
Definition at line 52 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init().
IntOption moa.clusterers.outliers.Angiulli.ApproxSTORM.queryFreqOption = new IntOption("queryFreq", 'q', "Query frequency.", 1)
Definition at line 51 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init().
FloatOption moa.clusterers.outliers.Angiulli.ApproxSTORM.radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
Definition at line 49 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.Init().
Set<ISBNode> moa.clusterers.outliers.Angiulli.ApproxSTORM.safe_inliers [package]
Definition at line 54 of file ApproxSTORM.java.
Referenced by moa.clusterers.outliers.Angiulli.ApproxSTORM.AddSafeInlier(), moa.clusterers.outliers.Angiulli.ApproxSTORM.GetSafeInlier(), moa.clusterers.outliers.Angiulli.ApproxSTORM.Init(), moa.clusterers.outliers.Angiulli.ApproxSTORM.PrintSafeInliers(), moa.clusterers.outliers.Angiulli.ApproxSTORM.ProcessNewStreamObj(), moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveNode(), and moa.clusterers.outliers.Angiulli.ApproxSTORM.RemoveSafeInlier().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/Angiulli/ApproxSTORM.java