MOA: moa.classifiers.trees.HoeffdingOptionTree.SplitNode Class Reference
moa.classifiers.trees.HoeffdingOptionTree.SplitNode Class Reference
Public Member Functions
int calcByteSize ()
int calcByteSizeIncludingSubtree ()
SplitNode (InstanceConditionalTest splitTest, double[] classObservations)
int numChildren ()
void setChild (int index, Node child)
Node getChild (int index)
int instanceChildIndex (Instance inst)
boolean isLeaf ()
void filterInstanceToLeaves (Instance inst, SplitNode myparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
void describeSubtree (HoeffdingOptionTree ht, StringBuilder out, int indent)
int subtreeDepth ()
double computeMeritOfExistingSplit (SplitCriterion splitCriterion, double[] preDist)
void updateOptionCount (SplitNode source, HoeffdingOptionTree hot)
void updateOptionCountBelow (int delta, HoeffdingOptionTree hot)
int getHeadOptionCount ()
Protected Attributes
InstanceConditionalTest splitTest
SplitNode parent
Node nextOption
int optionCount
AutoExpandVector< Node > children = new AutoExpandVector<Node>()
Private Member Functions
void killOptionLeaf (HoeffdingOptionTree hot)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 275 of file HoeffdingOptionTree.java.
Constructor & Destructor Documentation
moa.classifiers.trees.HoeffdingOptionTree.SplitNode.SplitNode (InstanceConditionalTest splitTest, double[] classObservations)
Definition at line 309 of file HoeffdingOptionTree.java.
{
            super(classObservations);
            this.splitTest = splitTest;
        }
Member Function Documentation
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSize ()
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 290 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSizeIncludingSubtree().
{
            return super.calcByteSize()
                    + (int) (SizeOf.sizeOf(this.children) + SizeOf.fullSizeOf(this.splitTest));
        }
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSizeIncludingSubtree ()
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 296 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSize(), moa.classifiers.trees.HoeffdingOptionTree.Node.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption.
{
            int byteSize = calcByteSize();
            for (Node child : this.children) {
                if (child != null) {
                    byteSize += child.calcByteSizeIncludingSubtree();
                }
            }
            if (this.nextOption != null) {
                byteSize += this.nextOption.calcByteSizeIncludingSubtree();
            }
            return byteSize;
        }
double moa.classifiers.trees.HoeffdingOptionTree.SplitNode.computeMeritOfExistingSplit (SplitCriterion splitCriterion, double[] preDist)
Definition at line 394 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children, and moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit().
{
            double[][] postDists = new double[this.children.size()][];
            for (int i = 0; i < this.children.size(); i++) {
                if (this.children.get(i) != null) {
                    postDists[i] = this.children.get(i).getObservedClassDistribution();
                } else {
                    System.out.println("error");
                }
            }
            return splitCriterion.getMeritOfSplit(preDist, postDists);
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree (HoeffdingOptionTree ht, StringBuilder out, int indent)
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 364 of file HoeffdingOptionTree.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.describeConditionForBranch(), moa.classifiers.trees.HoeffdingOptionTree.Node.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getChild(), moa.classifiers.AbstractClassifier.getModelContext(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.numChildren(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.splitTest.
{
            for (int branch = 0; branch < numChildren(); branch++) {
                Node child = getChild(branch);
                if (child != null) {
                    StringUtils.appendIndented(out, indent, "if ");
                    out.append(this.splitTest.describeConditionForBranch(branch,
                            ht.getModelContext()));
                    out.append(": ");
                    out.append("** option count = " + this.optionCount);
                    StringUtils.appendNewline(out);
                    child.describeSubtree(ht, out, indent + 2);
                }
            }
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves (Instance inst, SplitNode myparent, int parentBranch, List< FoundNode > foundNodes, boolean updateSplitterCounts)
Definition at line 341 of file HoeffdingOptionTree.java.
References moa.core.DoubleVector.addToValue(), moa.classifiers.trees.HoeffdingOptionTree.Node.filterInstanceToLeaves(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getChild(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.instanceChildIndex(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, and moa.classifiers.trees.HoeffdingOptionTree.Node.observedClassDistribution.
{
            if (updateSplitterCounts) {
                this.observedClassDistribution.addToValue((int) inst.classValue(), inst.weight());
            }
            int childIndex = instanceChildIndex(inst);
            if (childIndex >= 0) {
                Node child = getChild(childIndex);
                if (child != null) {
                    child.filterInstanceToLeaves(inst, this, childIndex,
                            foundNodes, updateSplitterCounts);
                } else {
                    foundNodes.add(new FoundNode(null, this, childIndex));
                }
            }
            if (this.nextOption != null) {
                this.nextOption.filterInstanceToLeaves(inst, this, -999,
                        foundNodes, updateSplitterCounts);
            }
        }
Node moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getChild (int index)
Definition at line 327 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves(), and moa.classifiers.trees.HoeffdingOptionTree.findLearningNodes().
{
            return this.children.get(index);
        }
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getHeadOptionCount ()
Definition at line 493 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.parent.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.enforceTrackerLimit().
{
            SplitNode sn = this;
            while (sn.optionCount == -999) {
                sn = sn.parent;
            }
            return sn.optionCount;
        }
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.instanceChildIndex (Instance inst)
Definition at line 331 of file HoeffdingOptionTree.java.
References moa.classifiers.core.conditionaltests.InstanceConditionalTest.branchForInstance(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves().
{
            return this.splitTest.branchForInstance(inst);
        }
boolean moa.classifiers.trees.HoeffdingOptionTree.SplitNode.isLeaf ()
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 336 of file HoeffdingOptionTree.java.
{
            return false;
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf (HoeffdingOptionTree hot) [private]
Definition at line 481 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.activeLeafNodeCount, moa.classifiers.trees.HoeffdingOptionTree.inactiveLeafNodeCount, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
{
            if (this.nextOption instanceof SplitNode) {
                ((SplitNode) this.nextOption).killOptionLeaf(hot);
            } else if (this.nextOption instanceof ActiveLearningNode) {
                this.nextOption = null;
                hot.activeLeafNodeCount--;
            } else if (this.nextOption instanceof InactiveLearningNode) {
                this.nextOption = null;
                hot.inactiveLeafNodeCount--;
            }
        }
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.numChildren ()
Definition at line 315 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), and moa.classifiers.trees.HoeffdingOptionTree.findLearningNodes().
{
            return this.children.size();
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild (int index, Node child)
Definition at line 319 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children, moa.classifiers.core.conditionaltests.InstanceConditionalTest.maxBranches(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.splitTest.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.activateLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), and moa.classifiers.trees.HoeffdingOptionTree.deactivateLearningNode().
{
            if ((this.splitTest.maxBranches() >= 0)
                    && (index >= this.splitTest.maxBranches())) {
                throw new IndexOutOfBoundsException();
            }
            this.children.set(index, child);
        }
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.subtreeDepth ()
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 381 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children.
{
            int maxChildDepth = 0;
            for (Node child : this.children) {
                if (child != null) {
                    int depth = child.subtreeDepth();
                    if (depth > maxChildDepth) {
                        maxChildDepth = depth;
                    }
                }
            }
            return maxChildDepth + 1;
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount (SplitNode source, HoeffdingOptionTree hot)
Definition at line 407 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children, moa.options.IntOption.getValue(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf(), moa.classifiers.trees.HoeffdingOptionTree.maxOptionPathsOption, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.parent, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount().
{
            if (this.optionCount == -999) {
                this.parent.updateOptionCount(source, hot);
            } else {
                int maxChildCount = -999;
                SplitNode curr = this;
                while (curr != null) {
                    for (Node child : curr.children) {
                        if (child instanceof SplitNode) {
                            SplitNode splitChild = (SplitNode) child;
                            if (splitChild.optionCount > maxChildCount) {
                                maxChildCount = splitChild.optionCount;
                            }
                        }
                    }
                    if ((curr.nextOption != null)
                            && (curr.nextOption instanceof SplitNode)) {
                        curr = (SplitNode) curr.nextOption;
                    } else {
                        curr = null;
                    }
                }
                if (maxChildCount > this.optionCount) { // currently only works
                    // one
                    // way - adding, not
                    // removing
                    int delta = maxChildCount - this.optionCount;
                    this.optionCount = maxChildCount;
                    if (this.optionCount >= hot.maxOptionPathsOption.getValue()) {
                        killOptionLeaf(hot);
                    }
                    curr = this;
                    while (curr != null) {
                        for (Node child : curr.children) {
                            if (child instanceof SplitNode) {
                                SplitNode splitChild = (SplitNode) child;
                                if (splitChild != source) {
                                    splitChild.updateOptionCountBelow(delta,
                                            hot);
                                }
                            }
                        }
                        if ((curr.nextOption != null)
                                && (curr.nextOption instanceof SplitNode)) {
                            curr = (SplitNode) curr.nextOption;
                        } else {
                            curr = null;
                        }
                    }
                    if (this.parent != null) {
                        this.parent.updateOptionCount(this, hot);
                    }
                }
            }
        }
void moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow (int delta, HoeffdingOptionTree hot)
Definition at line 463 of file HoeffdingOptionTree.java.
References moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children, moa.options.IntOption.getValue(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf(), moa.classifiers.trees.HoeffdingOptionTree.maxOptionPathsOption, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption, moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount, and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
{
            if (this.optionCount != -999) {
                this.optionCount += delta;
                if (this.optionCount >= hot.maxOptionPathsOption.getValue()) {
                    killOptionLeaf(hot);
                }
            }
            for (Node child : this.children) {
                if (child instanceof SplitNode) {
                    SplitNode splitChild = (SplitNode) child;
                    splitChild.updateOptionCountBelow(delta, hot);
                }
            }
            if (this.nextOption instanceof SplitNode) {
                ((SplitNode) this.nextOption).updateOptionCountBelow(delta, hot);
            }
        }
Member Data Documentation
AutoExpandVector<Node> moa.classifiers.trees.HoeffdingOptionTree.SplitNode.children = new AutoExpandVector<Node>() [protected]
Definition at line 287 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.computeMeritOfExistingSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getChild(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.numChildren(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.subtreeDepth(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
Node moa.classifiers.trees.HoeffdingOptionTree.SplitNode.nextOption [protected]
Definition at line 283 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.activateLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSizeIncludingSubtree(), moa.classifiers.trees.HoeffdingOptionTree.deactivateLearningNode(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.filterInstanceToLeaves(), moa.classifiers.trees.HoeffdingOptionTree.findLearningNodes(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.killOptionLeaf(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
int moa.classifiers.trees.HoeffdingOptionTree.SplitNode.optionCount [protected]
Definition at line 285 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getHeadOptionCount(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCountBelow().
SplitNode moa.classifiers.trees.HoeffdingOptionTree.SplitNode.parent [protected]
Definition at line 281 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.addToOptionTable(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.getHeadOptionCount(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.updateOptionCount().
final long moa.classifiers.trees.HoeffdingOptionTree.SplitNode.serialVersionUID = 1L [static, private]
Reimplemented from moa.classifiers.trees.HoeffdingOptionTree.Node.
Definition at line 277 of file HoeffdingOptionTree.java.
InstanceConditionalTest moa.classifiers.trees.HoeffdingOptionTree.SplitNode.splitTest [protected]
Definition at line 279 of file HoeffdingOptionTree.java.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.calcByteSize(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.describeSubtree(), moa.classifiers.trees.HoeffdingOptionTree.SplitNode.instanceChildIndex(), and moa.classifiers.trees.HoeffdingOptionTree.SplitNode.setChild().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/trees/HoeffdingOptionTree.java