MOA: moa.clusterers.outliers.MCOD.MCOD Class Reference
moa.clusterers.outliers.MCOD.MCOD Class Reference
Public Member Functions
MCOD ()
void Init ()
Public Attributes
FloatOption radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
IntOption kOption = new IntOption("k", 't', "Parameter k.", 50)
Protected Member Functions
void ProcessNewStreamObj (Instance inst)
Package Functions
void SetNodeType (ISBNode node, NodeType type)
void AddNeighbor (ISBNode node, ISBNode q, boolean bUpdateState)
void ProcessNewNode (ISBNode nodeNew, boolean bNewNode)
void AddToEventQueue (ISBNode x, ISBNode nodeMinExp)
void ProcessEventQueue (ISBNode nodeExpired)
void ProcessExpiredNode (ISBNode nodeExpired)
Detailed Description
Definition at line 39 of file MCOD.java.
Constructor & Destructor Documentation
moa.clusterers.outliers.MCOD.MCOD.MCOD ()
Definition at line 43 of file MCOD.java.
Referenced by moa.clusterers.outliers.MCOD.Test.main().
    {
        // System.out.println("MCOD: created");
    }
Member Function Documentation
void moa.clusterers.outliers.MCOD.MCOD.AddNeighbor (ISBNode node, ISBNode q, boolean bUpdateState) [package]
Definition at line 91 of file MCOD.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.AddPrecNeigh(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.MCODBase.bWarning, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.GetMinPrecNeigh(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.MCODBase.IsNodeIdInWin(), moa.clusterers.outliers.MCOD.MCODBase.m_k, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nodeType, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.RemoveOutlier(), and moa.clusterers.outliers.MCOD.MCOD.SetNodeType().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        if (bTrace) Println("AddNeighbor: node.id: " + node.id + ", q.id: " + q.id);
        // check if q still in window
        if (IsNodeIdInWin(q.id) == false) {
            if (bWarning) Println("AddNeighbor: node.id: " + node.id + ", q.id: " + q.id + " (expired)");
            return;
        }
        if (q.id < node.id) {
            node.AddPrecNeigh(q);
        } else {
            node.count_after++;
        }
        if (bUpdateState) {
            // check if node inlier or outlier
            int count = node.count_after + node.CountPrecNeighs(GetWindowStart());
            if ((node.nodeType == NodeType.OUTLIER) && (count >= m_k)) {
                // remove node from outliers
                if (bTrace) Println("Remove node from outliers");
                RemoveOutlier(node);
                // add node to inlier set PD
                SetNodeType(node, NodeType.INLIER_PD);
                // insert node to event queue
                ISBNode nodeMinExp = node.GetMinPrecNeigh(GetWindowStart());
                AddToEventQueue(node, nodeMinExp);
            }
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue (ISBNode x, ISBNode nodeMinExp) [package]
Definition at line 291 of file MCOD.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.MCODBase.bWarning, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.MCOD.MCODBase.eventQueue, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.Get_nn_before(), moa.clusterers.outliers.MCOD.MCODBase.GetExpirationTime(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.MCODBase.EventQueue.Insert(), moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MCOD.MCODBase.PrintEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), and moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList().
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        if (bTrace) Println("AddToEventQueue x.id: " + x.id);
        if (nodeMinExp != null) {
            Long expTime = GetExpirationTime(nodeMinExp);
            eventQueue.Insert(x, expTime);
            if (bTrace) {
                Print("x.nn_before: "); PrintNodeList(x.Get_nn_before());
                Println("nodeMinExp: " + nodeMinExp.id + ", expTime = " + expTime);
                PrintEventQueue();
            }
        } else {
            if (bWarning) Println("AddToEventQueue: Cannot add x.id: " + x.id + " to event queue (nn_before is empty, count_after=" + x.count_after + ")");
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.Init ()
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 49 of file MCOD.java.
References moa.clusterers.outliers.MCOD.MCODBase.eventQueue, moa.clusterers.outliers.MCOD.MCODBase.FIRST_OBJ_ID, moa.options.FloatOption.getValue(), moa.options.IntOption.getValue(), moa.clusterers.outliers.MCOD.MCODBase.ISB_PD, moa.clusterers.outliers.MCOD.MCOD.kOption, moa.clusterers.outliers.MCOD.MCODBase.m_k, moa.clusterers.outliers.MCOD.MCODBase.m_nBothInlierOutlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyInlier, moa.clusterers.outliers.MCOD.MCODBase.m_nOnlyOutlier, moa.clusterers.outliers.MCOD.MCODBase.m_radius, moa.clusterers.outliers.MCOD.MCODBase.m_WindowSize, moa.clusterers.outliers.MCOD.MCODBase.mtreeMC, moa.clusterers.outliers.MCOD.MCODBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCOD.radiusOption, moa.clusterers.outliers.MCOD.MCODBase.setMC, moa.clusterers.outliers.MCOD.MCODBase.windowNodes, and moa.clusterers.outliers.MyBaseOutlierDetector.windowSizeOption.
                       {
        super.Init();
        m_WindowSize = windowSizeOption.getValue();
        m_radius = radiusOption.getValue();
        m_k = kOption.getValue();
        Println("Init MCOD:");
        Println("   window_size: " + m_WindowSize);
        Println("   radius: " + m_radius);
        Println("   k: " + m_k);
        //bTrace = true;
        //bWarning = true;
        objId = FIRST_OBJ_ID; // init object identifier
        // create nodes list of window
        windowNodes = new Vector<ISBNode>();
        // create ISB
        ISB_PD = new ISBIndex(m_radius, m_k);
        // create helper sets for micro-cluster management
        setMC = new TreeSet<MicroCluster>();
        // micro-cluster index
        mtreeMC = new MTreeMicroClusters();
        // create event queue
        eventQueue = new EventQueue();
        // init statistics
        m_nBothInlierOutlier = 0;
        m_nOnlyInlier = 0;
        m_nOnlyOutlier = 0;
    }
void moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue (ISBNode nodeExpired) [package]
Definition at line 306 of file MCOD.java.
References moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.MCODBase.bWarning, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.MCOD.MCODBase.eventQueue, moa.clusterers.outliers.MCOD.MCODBase.EventQueue.ExtractMin(), moa.clusterers.outliers.MCOD.MCODBase.EventQueue.FindMin(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.GetMinPrecNeigh(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowEnd(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.MCODBase.IsNodeIdInWin(), moa.clusterers.outliers.MCOD.MCODBase.m_k, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.mc, moa.clusterers.outliers.MCOD.MCODBase.EventItem.node, moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.RemovePrecNeigh(), moa.clusterers.outliers.MCOD.MCODBase.SaveOutlier(), moa.clusterers.outliers.MCOD.MCOD.SetNodeType(), and moa.clusterers.outliers.MCOD.MCODBase.EventItem.timeStamp.
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode().
{
        EventItem e = eventQueue.FindMin();
        while ((e != null) && (e.timeStamp <= GetWindowEnd())) {
            e = eventQueue.ExtractMin();
            ISBNode x = e.node;
            if (bTrace) Println("Process event queue: check node x: " + x.id);
            // node x must be in window and not in any micro-cluster
            boolean bValid = ( IsNodeIdInWin(x.id) && (x.mc == null) );
            if (bValid) {
                // remove nodeExpired from x.nn_before
                x.RemovePrecNeigh(nodeExpired);
                // get amount of neighbors of x
                int count = x.count_after + x.CountPrecNeighs(GetWindowStart());
                if (count < m_k) {
                    if (bTrace) Println("x is an outlier");
                    SetNodeType(x, NodeType.OUTLIER);
                    SaveOutlier(x);
                } else {
                    if (bTrace) Println("x is an inlier, add to event queue");
                    // get oldest preceding neighbor of x
                    ISBNode nodeMinExp = x.GetMinPrecNeigh(GetWindowStart());
                    // add x to event queue
                    AddToEventQueue(x, nodeMinExp);
                }
            } else {
                if (bWarning) Println("Process event queue: node x.id: " + x.id + " is not valid!");
            }
            e = eventQueue.FindMin();
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode (ISBNode nodeExpired) [package]
Definition at line 337 of file MCOD.java.
References moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.MicroCluster.GetNodesCount(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.InitNode(), moa.clusterers.outliers.MCOD.MCODBase.ISB_PD, moa.clusterers.outliers.MCOD.MCODBase.m_k, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.mc, moa.clusterers.outliers.MCOD.MicroCluster.mcc, moa.clusterers.outliers.MCOD.MicroCluster.nodes, moa.clusterers.outliers.MCOD.MCODBase.nodesReinsert, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.ISBIndex.Remove(), moa.clusterers.outliers.MCOD.MCODBase.RemoveMicroCluster(), moa.clusterers.outliers.MCOD.MCODBase.RemoveNode(), and moa.clusterers.outliers.MCOD.MicroCluster.RemoveNode().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        if (nodeExpired != null) {
            if (bTrace) Println("\nnodeExpired: " + nodeExpired.id);
            MicroCluster mc = nodeExpired.mc;
            if (mc != null) {
                if (bTrace) Println("nodeExpired belongs to mc: " + mc.mcc.id);
                mc.RemoveNode(nodeExpired);
                if (bTrace) { Print("mc.nodes: "); PrintNodeList(mc.nodes); }
                if (bTrace) Println("Check if mc has enough objects");
                if (mc.GetNodesCount() < m_k) {
                    // remove micro-cluster mc
                    if (bTrace) Println("Remove mc");
                    RemoveMicroCluster(mc);
                    // insert nodes of mc to set nodesReinsert
                    nodesReinsert = new TreeSet<ISBNode>();
                    for (ISBNode q : mc.nodes) {
                        nodesReinsert.add(q);
                    }
                    // treat each node of mc as new node
                    for (ISBNode q : mc.nodes) {
                        if (bTrace) Println("\nTreat as new node q: " + q.id);
                        q.InitNode();
                        ProcessNewNode(q, false);
                    }
                }
            } else {
                // nodeExpired belongs to set PD
                // remove nodeExpired from PD index
                ISB_PD.Remove(nodeExpired);
            }
            RemoveNode(nodeExpired);
            ProcessEventQueue(nodeExpired);
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode (ISBNode nodeNew, boolean bNewNode) [package]
Definition at line 122 of file MCOD.java.
References moa.clusterers.outliers.MCOD.MCODBase.AddMicroCluster(), moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MicroCluster.AddNode(), moa.clusterers.outliers.MCOD.MCOD.AddToEventQueue(), moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.count_after, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.CountPrecNeighs(), moa.clusterers.outliers.MCOD.MicroCluster.get(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.Get_nn_before(), moa.clusterers.outliers.MCOD.ISBIndex.GetAllNodes(), moa.clusterers.outliers.MCOD.MCODBase.GetEuclideanDist(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.GetMinPrecNeigh(), moa.clusterers.outliers.MCOD.MCODBase.GetWindowStart(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.id, moa.clusterers.outliers.MCOD.ISBIndex.Insert(), moa.clusterers.outliers.MCOD.MCODBase.ISB_PD, moa.clusterers.outliers.MCOD.MCODBase.m_k, moa.clusterers.outliers.MCOD.MCODBase.m_radius, moa.clusterers.outliers.MCOD.MCODBase.m_theta, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.mc, moa.clusterers.outliers.MCOD.MicroCluster.mcc, moa.clusterers.outliers.MCOD.MicroCluster.nodes, moa.clusterers.outliers.MCOD.MCODBase.nodesReinsert, moa.clusterers.outliers.MyBaseOutlierDetector.nRangeQueriesExecuted, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Printf(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet(), moa.clusterers.outliers.MCOD.MCODBase.PrintNode(), moa.clusterers.outliers.MCOD.MCODBase.PrintNodeList(), moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), moa.clusterers.outliers.MCOD.ISBIndex.RangeSearch(), moa.clusterers.outliers.MCOD.MCODBase.RangeSearchMC(), moa.clusterers.outliers.MCOD.ISBIndex.Remove(), moa.clusterers.outliers.MCOD.MCODBase.RemoveOutlier(), moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.Rmc, moa.clusterers.outliers.MCOD.MCODBase.SaveOutlier(), and moa.clusterers.outliers.MCOD.MCOD.SetNodeType().
Referenced by moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj().
{
        if (bTrace) { Print("ProcessNewNode: "); PrintNode(nodeNew); }
        if (bTrace) Println("Perform 3R/2 range query to cluster centers w.r.t new node");
        Vector<SearchResultMC> resultsMC;
        // results are sorted ascenting by distance
        resultsMC = RangeSearchMC(nodeNew, 1.5 * m_radius);
        if (bTrace) {
            Println("MC query found: ");
            for (SearchResultMC sr : resultsMC) {
                Printf("  (%.1f) mcc: ", sr.distance); PrintNode(sr.mc.mcc);
            }
        }
        if (bTrace) Println("Get closest micro-cluster");
        MicroCluster mcClosest = null;
        if (resultsMC.size() > 0) {
            mcClosest = resultsMC.get(0).mc;
            if (bTrace) Println("Closest mcc: " + mcClosest.mcc.id);
        }
        // check if nodeNew can be insterted to closest micro-cluster
        boolean bFoundMC = false;
        if (mcClosest != null) {
            double d = GetEuclideanDist(nodeNew, mcClosest.mcc);
            if (d <= m_radius / 2) {
                bFoundMC = true;
            } else {
                if (bTrace) Println("Not close enough to closest mcc");
            }
        }
        if (bFoundMC) {
            if (bTrace) Println("Add new node to micro-cluster");
            nodeNew.mc = mcClosest;
            SetNodeType(nodeNew, NodeType.INLIER_MC);
            mcClosest.AddNode(nodeNew);
            if (bTrace) { Print("mcClosest.nodes: "); PrintNodeList(mcClosest.nodes); }
            if (bTrace) Println("Update neighbors of set PD");
            Vector<ISBNode> nodes;
            nodes = ISB_PD.GetAllNodes();
            for (ISBNode q : nodes) {
                if (q.Rmc.contains(mcClosest)) {
                    if (GetEuclideanDist(q, nodeNew) <= m_radius) {
                        if (bNewNode) {
                            // update q.count_after and its' outlierness
                            AddNeighbor(q, nodeNew, true);
                        } else {
                            if (nodesReinsert.contains(q)) {
                                // update q.count_after or q.nn_before and its' outlierness
                                AddNeighbor(q, nodeNew, true);
                            }
                        }
                    }
                }
            }
        }
        else {
            // No close enough micro-cluster found.
            // Perform 3R/2 range query to nodes in set PD.
            if (bTrace) Println("Perform 3R/2 range query to nodes in set PD");
            nRangeQueriesExecuted++;
            // create helper sets for micro-cluster management
            ArrayList<ISBNode> setNC = new ArrayList<ISBNode>();
            ArrayList<ISBNode> setNNC = new ArrayList<ISBNode>();
            Vector<ISBSearchResult> resultNodes;
            resultNodes = ISB_PD.RangeSearch(nodeNew, 1.5 * m_radius); // 1.5 ###
            for (ISBSearchResult sr : resultNodes) {
                ISBNode q = sr.node;
                if (sr.distance <= m_radius) {
                    // add q to neighs of nodeNew
                    AddNeighbor(nodeNew, q, false);
                    if (bNewNode) {
                        // update q.count_after and its' outlierness
                        AddNeighbor(q, nodeNew, true);
                    } else {
                        if (nodesReinsert.contains(q)) {
                            // update q.count_after or q.nn_before and its' outlierness
                            AddNeighbor(q, nodeNew, true);
                        }
                    }
                }
                if (sr.distance <= m_radius / 2.0) {
                    setNC.add(q);
                } else {
                    setNNC.add(q);
                }
            }
            if (bTrace) {
                Print("Prec neighs of new node: "); PrintNodeList(nodeNew.Get_nn_before());
                Print("NC: "); PrintNodeList(setNC);
                Print("NNC: "); PrintNodeList(setNNC);
            }
            // check if size of set NC big enough to create cluster
            if (bTrace) Println("Check size of set NC");
            if (setNC.size() >= m_theta * m_k) {
                // create new micro-cluster with center nodeNew
                if (bTrace) Println("Create new micro-cluster");
                MicroCluster mcNew = new MicroCluster(nodeNew);
                AddMicroCluster(mcNew);
                nodeNew.mc = mcNew;
                SetNodeType(nodeNew, NodeType.INLIER_MC);
                if (bTrace) Println("Add to new mc nodes within range R/2");
                for (ISBNode q : setNC) {
                    q.mc = mcNew;
                    mcNew.AddNode(q);
                    // move q from set PD to set inlier-mc
                    SetNodeType(q, NodeType.INLIER_MC);
                    ISB_PD.Remove(q);
                    RemoveOutlier(q); // needed? ###
                }
                if (bTrace) {
                    Print("mcNew.nodes: "); PrintNodeList(mcNew.nodes);
                    PrintPD();
                }
                if (bTrace) Println("Update Rmc lists of nodes of PD in range 3R/2 from mcNew");
                for (ISBNode q : setNNC) {
                    q.Rmc.add(mcNew);
                    if (bTrace) { Print(q.id + ".Rmc: "); PrintMCSet(q.Rmc); }
                }
            } else {
                if (bTrace) Println("Add to nodeNew neighs nodes of near micro-clusters");
                for (SearchResultMC sr : resultsMC) {
                    for (ISBNode q : sr.mc.nodes) {
                        if (GetEuclideanDist(q, nodeNew) <= m_radius) {
                            // add q to neighs of nodeNew
                            AddNeighbor(nodeNew, q, false);
                        }
                    }
                }
                if (bTrace) {
                    Println("nodeNew.count_after = " + nodeNew.count_after);
                    Print("nodeNew.nn_before: "); PrintNodeList(nodeNew.Get_nn_before());
                }
                if (bTrace) Println("Insert nodeNew to index of nodes of PD");
                ISB_PD.Insert(nodeNew);
                if (bTrace) PrintPD();
                // check if nodeNew is an inlier or outlier
                // use both nn_before and count_after for case bNewNode=false
                int count = nodeNew.CountPrecNeighs(GetWindowStart()) + nodeNew.count_after;
                if (count >= m_k) {
                    if (bTrace) Println("nodeNew is an inlier");
                    SetNodeType(nodeNew, NodeType.INLIER_PD);
                    // insert nodeNew to event queue
                    ISBNode nodeMinExp = nodeNew.GetMinPrecNeigh(GetWindowStart());
                    AddToEventQueue(nodeNew, nodeMinExp);
                } else {
                    if (bTrace) Println("nodeNew is an outlier");
                    SetNodeType(nodeNew, NodeType.OUTLIER);
                    SaveOutlier(nodeNew);
                }
                if (bTrace) Println("Update nodeNew.Rmc");
                for (SearchResultMC sr : resultsMC) {
                    nodeNew.Rmc.add(sr.mc);
                }
                if (bTrace) { Print("nodeNew.Rmc: "); PrintMCSet(nodeNew.Rmc); }
            }
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.ProcessNewStreamObj (Instance inst) [protected]
Reimplemented from moa.clusterers.outliers.MyBaseOutlierDetector.
Definition at line 377 of file MCOD.java.
References moa.clusterers.outliers.MCOD.MCODBase.AddNode(), moa.clusterers.outliers.MyBaseOutlierDetector.bShowProgress, moa.clusterers.outliers.MyBaseOutlierDetector.bTrace, moa.clusterers.outliers.MCOD.MCODBase.GetExpiredNode(), moa.clusterers.outliers.MyBaseOutlierDetector.getInstanceValues(), moa.clusterers.outliers.MCOD.MCODBase.objId, moa.clusterers.outliers.MyBaseOutlierDetector.Print(), moa.clusterers.outliers.MyBaseOutlierDetector.Println(), moa.clusterers.outliers.MCOD.MCODBase.PrintMCSet(), moa.clusterers.outliers.MCOD.MCODBase.PrintNode(), moa.clusterers.outliers.MyBaseOutlierDetector.PrintOutliers(), moa.clusterers.outliers.MCOD.MCODBase.PrintPD(), moa.clusterers.outliers.MCOD.MCODBase.PrintWindow(), moa.clusterers.outliers.MCOD.MCOD.ProcessExpiredNode(), moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode(), moa.clusterers.outliers.MCOD.MCODBase.setMC, and moa.clusterers.outliers.MyBaseOutlierDetector.ShowProgress().
    {
        if (bShowProgress) ShowProgress("Processed " + (objId-1) + " stream objects.");
        // PrintInstance(inst);
        double[] values = getInstanceValues(inst);
        StreamObj obj = new StreamObj(values);
        if (bTrace) Println("\n- - - - - - - - - - - -\n");
        // create new ISB node
        ISBNode nodeNew = new ISBNode(inst, obj, objId);
        if (bTrace) { Print("New node: "); PrintNode(nodeNew); }
        objId++; // update object identifier (slide window)
        AddNode(nodeNew); // add nodeNew to window
        if (bTrace) PrintWindow();
        ProcessNewNode(nodeNew, true);
        ProcessExpiredNode(GetExpiredNode());
        if (bTrace) {
            Print("Micro-clusters: "); PrintMCSet(setMC);
            PrintOutliers();
            PrintPD();
        }
    }
void moa.clusterers.outliers.MCOD.MCOD.SetNodeType (ISBNode node, NodeType type) [package]
Definition at line 82 of file MCOD.java.
References moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nInlier, moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nodeType, and moa.clusterers.outliers.MCOD.ISBIndex.ISBNode.nOutlier.
Referenced by moa.clusterers.outliers.MCOD.MCOD.AddNeighbor(), moa.clusterers.outliers.MCOD.MCOD.ProcessEventQueue(), and moa.clusterers.outliers.MCOD.MCOD.ProcessNewNode().
{
        node.nodeType = type;
        // update statistics
        if (type == NodeType.OUTLIER)
            node.nOutlier++;
        else
            node.nInlier++;
    }
Member Data Documentation
IntOption moa.clusterers.outliers.MCOD.MCOD.kOption = new IntOption("k", 't', "Parameter k.", 50)
Definition at line 41 of file MCOD.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.Init().
FloatOption moa.clusterers.outliers.MCOD.MCOD.radiusOption = new FloatOption("radius", 'r', "Search radius.", 0.1)
Definition at line 40 of file MCOD.java.
Referenced by moa.clusterers.outliers.MCOD.MCOD.Init().
The documentation for this class was generated from the following file:
main/java/moa/clusterers/outliers/MCOD/MCOD.java