MOA: moa.classifiers.meta.LimAttClassifier.CombinationGenerator Class Reference
moa.classifiers.meta.LimAttClassifier.CombinationGenerator Class Reference
Public Member Functions
CombinationGenerator (int n, int r)
void reset ()
BigInteger getNumLeft ()
boolean hasMore ()
BigInteger getTotal ()
int[] getNext ()
Private Member Functions
BigInteger getFactorial (int n)
Private Attributes
int[] a
int n
int r
BigInteger numLeft
BigInteger total
Detailed Description
Definition at line 97 of file LimAttClassifier.java.
Constructor & Destructor Documentation
moa.classifiers.meta.LimAttClassifier.CombinationGenerator.CombinationGenerator (int n, int r)
Definition at line 112 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.a, moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getFactorial(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.reset(), and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.total.
{
            if (r > n) {
                throw new IllegalArgumentException();
            }
            if (n < 1) {
                throw new IllegalArgumentException();
            }
            this.n = n;
            this.r = r;
            a = new int[r];
            BigInteger nFact = getFactorial(n);
            BigInteger rFact = getFactorial(r);
            BigInteger nminusrFact = getFactorial(n - r);
            total = nFact.divide(rFact.multiply(nminusrFact));
            reset();
        }
Member Function Documentation
BigInteger moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getFactorial (int n) [private]
Definition at line 163 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.CombinationGenerator().
{
            BigInteger fact = BigInteger.ONE;
            for (int i = n; i > 1; i--) {
                fact = fact.multiply(new BigInteger(Integer.toString(i)));
            }
            return fact;
        }
int [] moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext ()
Definition at line 174 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.a, moa.classifiers.meta.LimAttClassifier.CombinationGenerator.n, moa.classifiers.meta.LimAttClassifier.CombinationGenerator.numLeft, moa.classifiers.meta.LimAttClassifier.CombinationGenerator.r, and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.total.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
{
            if (numLeft.equals(total)) {
                numLeft = numLeft.subtract(BigInteger.ONE);
                int[] b = new int[a.length];
                for (int k = 0; k < a.length; k++) {
                    b[k] = a[k];
                }
                return b;
            }
            int i = r - 1;
            while (a[i] == n - r + i) {
                i--;
            }
            a[i] = a[i] + 1;
            for (int j = i + 1; j < r; j++) {
                a[j] = a[i] + j - i;
            }
            numLeft = numLeft.subtract(BigInteger.ONE);
            int[] b = new int[a.length];
            for (int k = 0; k < a.length; k++) {
                b[k] = a[k];
            }
            return b;
        }
BigInteger moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNumLeft ()
Definition at line 142 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.numLeft.
{
            return numLeft;
        }
BigInteger moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getTotal ()
Definition at line 156 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.total.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
{
            return total;
        }
boolean moa.classifiers.meta.LimAttClassifier.CombinationGenerator.hasMore ()
Definition at line 149 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.numLeft.
Referenced by moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
{
            return numLeft.compareTo(BigInteger.ZERO) == 1;
        }
void moa.classifiers.meta.LimAttClassifier.CombinationGenerator.reset ()
Definition at line 132 of file LimAttClassifier.java.
References moa.classifiers.meta.LimAttClassifier.CombinationGenerator.a, moa.classifiers.meta.LimAttClassifier.CombinationGenerator.numLeft, and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.total.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.CombinationGenerator().
{
            for (int i = 0; i < a.length; i++) {
                a[i] = i;
            }
            numLeft = new BigInteger(total.toString());
        }
Member Data Documentation
int [] moa.classifiers.meta.LimAttClassifier.CombinationGenerator.a [private]
Definition at line 99 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.CombinationGenerator(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext(), and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.reset().
int moa.classifiers.meta.LimAttClassifier.CombinationGenerator.n [private]
Definition at line 101 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext().
BigInteger moa.classifiers.meta.LimAttClassifier.CombinationGenerator.numLeft [private]
Definition at line 105 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNumLeft(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.hasMore(), and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.reset().
int moa.classifiers.meta.LimAttClassifier.CombinationGenerator.r [private]
Definition at line 103 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext().
BigInteger moa.classifiers.meta.LimAttClassifier.CombinationGenerator.total [private]
Definition at line 107 of file LimAttClassifier.java.
Referenced by moa.classifiers.meta.LimAttClassifier.CombinationGenerator.CombinationGenerator(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getNext(), moa.classifiers.meta.LimAttClassifier.CombinationGenerator.getTotal(), and moa.classifiers.meta.LimAttClassifier.CombinationGenerator.reset().
The documentation for this class was generated from the following file:
main/java/moa/classifiers/meta/LimAttClassifier.java