MOA: moa.clusterers.denstream.WithDBSCAN Class Reference
moa.clusterers.denstream.WithDBSCAN Class Reference
Classes
class DenPoint
Public Member Functions
void resetLearningImpl ()
void initialDBScan ()
void trainOnInstanceImpl (Instance inst)
Clustering getClusteringResult ()
boolean implementsMicroClusterer ()
Clustering getMicroClusteringResult ()
void getModelDescription (StringBuilder out, int indent)
boolean isRandomizable ()
double[] getVotesForInstance (Instance inst)
String getParameterString ()
Public Attributes
IntOption horizonOption
FloatOption epsilonOption
FloatOption betaOption
FloatOption muOption
IntOption initPointsOption
FloatOption offlineOption
FloatOption lambdaOption
IntOption speedOption
Protected Member Functions
Measurement[] getModelMeasurementsImpl ()
Protected Attributes
int numInitPoints
int numProcessedPerUnit
int processingSpeed
Package Attributes
double lambda
double epsilon
int minPoints
double mu
double beta
Clustering p_micro_cluster
Clustering o_micro_cluster
ArrayList< DenPoint > initBuffer
boolean initialized
Timestamp currentTimestamp
long tp
Private Member Functions
void expandCluster (MicroCluster mc, ArrayList< DenPoint > points, ArrayList< Integer > neighbourhood)
ArrayList< Integer > getNeighbourhoodIDs (DenPoint point, ArrayList< DenPoint > points, double eps)
MicroCluster nearestCluster (DenPoint p, Clustering cl)
double distance (double[] pointA, double[] pointB)
Private Attributes
double weightThreshold = 0.01
long timestamp = 0
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 39 of file WithDBSCAN.java.
Member Function Documentation
double moa.clusterers.denstream.WithDBSCAN.distance (double[] pointA, double[] pointB) [private]
Definition at line 283 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getNeighbourhoodIDs(), and moa.clusterers.denstream.WithDBSCAN.nearestCluster().
{
        double distance = 0.0;
        for (int i = 0; i < pointA.length; i++) {
            double d = pointA[i] - pointB[i];
            distance += d * d;
        }
        return Math.sqrt(distance);
    }
void moa.clusterers.denstream.WithDBSCAN.expandCluster (MicroCluster mc, ArrayList< DenPoint > points, ArrayList< Integer > neighbourhood) [private]
Definition at line 232 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.DenPoint.covered, moa.clusterers.denstream.WithDBSCAN.epsilon, moa.clusterers.denstream.WithDBSCAN.getNeighbourhoodIDs(), moa.clusterers.denstream.WithDBSCAN.initBuffer, moa.clusterers.denstream.MicroCluster.insert(), moa.clusterers.denstream.WithDBSCAN.minPoints, and moa.clusterers.denstream.WithDBSCAN.timestamp.
Referenced by moa.clusterers.denstream.WithDBSCAN.initialDBScan().
{
        for (int p : neighbourhood) {
            DenPoint npoint = points.get(p);
            if (!npoint.covered) {
                npoint.covered = true;
                mc.insert(npoint, timestamp);
                ArrayList<Integer> neighbourhood2 = getNeighbourhoodIDs(npoint,
                        initBuffer, epsilon);
                if (neighbourhood.size() > minPoints) {
                    expandCluster(mc, points, neighbourhood2);
                }
            }
        }
    }
Clustering moa.clusterers.denstream.WithDBSCAN.getClusteringResult ()
Implements moa.clusterers.Clusterer.
Definition at line 292 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.epsilon, moa.clusterers.macro.dbscan.DBScan.getClustering(), moa.options.FloatOption.getValue(), moa.clusterers.denstream.WithDBSCAN.minPoints, moa.clusterers.denstream.WithDBSCAN.offlineOption, and moa.clusterers.denstream.WithDBSCAN.p_micro_cluster.
{
        DBScan dbscan = new DBScan(p_micro_cluster,offlineOption.getValue() * epsilon, minPoints);
        return dbscan.getClustering(p_micro_cluster);
    }
Clustering moa.clusterers.denstream.WithDBSCAN.getMicroClusteringResult ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 303 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.p_micro_cluster.
{
        return p_micro_cluster;
    }
void moa.clusterers.denstream.WithDBSCAN.getModelDescription (StringBuilder out, int indent) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 313 of file WithDBSCAN.java.
{
    }
Measurement [] moa.clusterers.denstream.WithDBSCAN.getModelMeasurementsImpl () [protected, virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 308 of file WithDBSCAN.java.
{
        throw new UnsupportedOperationException("Not supported yet.");
    }
ArrayList<Integer> moa.clusterers.denstream.WithDBSCAN.getNeighbourhoodIDs (DenPoint point, ArrayList< DenPoint > points, double eps) [private]
Definition at line 248 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.DenPoint.covered, and moa.clusterers.denstream.WithDBSCAN.distance().
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), and moa.clusterers.denstream.WithDBSCAN.initialDBScan().
{
        ArrayList<Integer> neighbourIDs = new ArrayList<Integer>();
        for (int p = 0; p < points.size(); p++) {
            DenPoint npoint = points.get(p);
            if (!npoint.covered) {
                double dist = distance(point.toDoubleArray(), points.get(p)
                        .toDoubleArray());
                if (dist < eps) {
                    neighbourIDs.add(p);
                }
            }
        }
        return neighbourIDs;
    }
String moa.clusterers.denstream.WithDBSCAN.getParameterString ()
Definition at line 324 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.betaOption, moa.clusterers.denstream.WithDBSCAN.epsilonOption, moa.options.AbstractOption.getCLIChar(), moa.options.FloatOption.getValueAsCLIString(), moa.options.IntOption.getValueAsCLIString(), moa.clusterers.denstream.WithDBSCAN.horizonOption, moa.clusterers.denstream.WithDBSCAN.initPointsOption, moa.clusterers.denstream.WithDBSCAN.lambdaOption, and moa.clusterers.denstream.WithDBSCAN.muOption.
{
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getSimpleName() + " ");
        sb.append("-" + horizonOption.getCLIChar() + " ");
        sb.append(horizonOption.getValueAsCLIString() + " ");
        sb.append("-" + epsilonOption.getCLIChar() + " ");
        sb.append(epsilonOption.getValueAsCLIString() + " ");
        sb.append("-" + betaOption.getCLIChar() + " ");
        sb.append(betaOption.getValueAsCLIString() + " ");
        sb.append("-" + muOption.getCLIChar() + " ");
        sb.append(muOption.getValueAsCLIString() + " ");
        sb.append("-" + lambdaOption.getCLIChar() + " ");
        sb.append(lambdaOption.getValueAsCLIString() + " ");
        sb.append("-" + initPointsOption.getCLIChar() + " ");
        // NO " " at the end! results in errors on windows systems
        sb.append(initPointsOption.getValueAsCLIString());
        return sb.toString();
    }
double [] moa.clusterers.denstream.WithDBSCAN.getVotesForInstance (Instance inst)
Implements moa.clusterers.Clusterer.
Definition at line 320 of file WithDBSCAN.java.
{
        return null;
    }
boolean moa.clusterers.denstream.WithDBSCAN.implementsMicroClusterer ()
Reimplemented from moa.clusterers.AbstractClusterer.
Definition at line 298 of file WithDBSCAN.java.
{
        return true;
    }
void moa.clusterers.denstream.WithDBSCAN.initialDBScan ()
Definition at line 125 of file WithDBSCAN.java.
References moa.cluster.Clustering.add(), moa.clusterers.denstream.WithDBSCAN.DenPoint.covered, moa.clusterers.denstream.WithDBSCAN.currentTimestamp, moa.clusterers.denstream.WithDBSCAN.epsilon, moa.clusterers.denstream.WithDBSCAN.expandCluster(), moa.clusterers.denstream.WithDBSCAN.getNeighbourhoodIDs(), moa.clusterers.denstream.WithDBSCAN.initBuffer, moa.clusterers.denstream.WithDBSCAN.lambda, moa.clusterers.denstream.WithDBSCAN.minPoints, moa.clusterers.denstream.WithDBSCAN.p_micro_cluster, and moa.clusterers.denstream.WithDBSCAN.timestamp.
Referenced by moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        for (int p = 0; p < initBuffer.size(); p++) {
            DenPoint point = initBuffer.get(p);
            if (!point.covered) {
                point.covered = true;
                ArrayList<Integer> neighbourhood = getNeighbourhoodIDs(point,
                        initBuffer, epsilon);
                if (neighbourhood.size() > minPoints) {
                    MicroCluster mc = new MicroCluster(point,
                            point.numAttributes(), timestamp, lambda,
                            currentTimestamp);
                    expandCluster(mc, initBuffer, neighbourhood);
                    p_micro_cluster.add(mc);
                } else {
                    point.covered = false;
                }
            }
        }
    }
boolean moa.clusterers.denstream.WithDBSCAN.isRandomizable ()
Implements moa.clusterers.Clusterer.
Definition at line 316 of file WithDBSCAN.java.
{
        return true;
    }
MicroCluster moa.clusterers.denstream.WithDBSCAN.nearestCluster (DenPoint p, Clustering cl) [private]
Definition at line 264 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.distance(), moa.cluster.Clustering.get(), moa.clusterers.denstream.MicroCluster.getCenter(), moa.clusterers.denstream.MicroCluster.getRadius(), moa.cluster.Clustering.size(), and moa.clusterers.denstream.WithDBSCAN.timestamp.
Referenced by moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
{
        MicroCluster min = null;
        double minDist = 0;
        for (int c = 0; c < cl.size(); c++) {
            MicroCluster x = (MicroCluster) cl.get(c);
            if (min == null) {
                min = x;
            }
            double dist = distance(p.toDoubleArray(), x.getCenter());
            dist -= x.getRadius(timestamp);
            if (dist < minDist) {
                minDist = dist;
                min = x;
            }
        }
        return min;
    }
void moa.clusterers.denstream.WithDBSCAN.resetLearningImpl () [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 102 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.beta, moa.clusterers.denstream.WithDBSCAN.betaOption, moa.clusterers.denstream.WithDBSCAN.currentTimestamp, moa.clusterers.denstream.WithDBSCAN.epsilon, moa.clusterers.denstream.WithDBSCAN.epsilonOption, moa.options.IntOption.getValue(), moa.options.FloatOption.getValue(), moa.clusterers.denstream.WithDBSCAN.initBuffer, moa.clusterers.denstream.WithDBSCAN.initialized, moa.clusterers.denstream.WithDBSCAN.lambda, moa.clusterers.denstream.WithDBSCAN.lambdaOption, moa.clusterers.denstream.WithDBSCAN.minPoints, moa.clusterers.denstream.WithDBSCAN.mu, moa.clusterers.denstream.WithDBSCAN.muOption, moa.clusterers.denstream.WithDBSCAN.numProcessedPerUnit, moa.clusterers.denstream.WithDBSCAN.o_micro_cluster, moa.clusterers.denstream.WithDBSCAN.p_micro_cluster, moa.clusterers.denstream.WithDBSCAN.processingSpeed, moa.clusterers.denstream.WithDBSCAN.speedOption, and moa.clusterers.denstream.WithDBSCAN.tp.
{
        // init DenStream
        currentTimestamp = new Timestamp();
//      lambda = -Math.log(weightThreshold) / Math.log(2)
//                      / (double) horizonOption.getValue();
        lambda = lambdaOption.getValue();
        epsilon = epsilonOption.getValue();
        minPoints = (int) muOption.getValue();// minPointsOption.getValue();
        mu = (int) muOption.getValue();
        beta = betaOption.getValue();
        initialized = false;
        p_micro_cluster = new Clustering();
        o_micro_cluster = new Clustering();
        initBuffer = new ArrayList<DenPoint>();
        tp = Math.round(1 / lambda * Math.log((beta * mu) / (beta * mu - 1))) + 1;
        numProcessedPerUnit = 0;
        processingSpeed = speedOption.getValue();
    }
void moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl (Instance inst) [virtual]
Implements moa.clusterers.AbstractClusterer.
Definition at line 146 of file WithDBSCAN.java.
References moa.clusterers.denstream.WithDBSCAN.beta, moa.clusterers.denstream.MicroCluster.copy(), moa.clusterers.denstream.WithDBSCAN.currentTimestamp, moa.clusterers.denstream.WithDBSCAN.epsilon, moa.cluster.Clustering.getClustering(), moa.clusterers.denstream.MicroCluster.getRadius(), moa.options.IntOption.getValue(), moa.clusterers.denstream.MicroCluster.getWeight(), moa.clusterers.denstream.WithDBSCAN.initBuffer, moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.initialized, moa.clusterers.denstream.WithDBSCAN.initPointsOption, moa.clusterers.denstream.MicroCluster.insert(), moa.clusterers.denstream.WithDBSCAN.lambda, moa.clusterers.denstream.WithDBSCAN.mu, moa.clusterers.denstream.WithDBSCAN.nearestCluster(), moa.clusterers.denstream.WithDBSCAN.numProcessedPerUnit, moa.clusterers.denstream.WithDBSCAN.o_micro_cluster, moa.clusterers.denstream.WithDBSCAN.p_micro_cluster, moa.clusterers.denstream.WithDBSCAN.processingSpeed, moa.clusterers.denstream.Timestamp.setTimestamp(), moa.clusterers.denstream.WithDBSCAN.timestamp, and moa.clusterers.denstream.WithDBSCAN.tp.
{
        DenPoint point = new DenPoint(inst, timestamp);
        numProcessedPerUnit++;
        /* Controlling the stream speed */
        if (numProcessedPerUnit % processingSpeed == 0) {
            timestamp++;
            currentTimestamp.setTimestamp(timestamp);
        }
        // ////////////////
        // Initialization//
        // ////////////////
        if (!initialized) {
            initBuffer.add(point);
            if (initBuffer.size() >= initPointsOption.getValue()) {
                initialDBScan();
                initialized = true;
            }
        } else {
            // ////////////
            // Merging(p)//
            // ////////////
            boolean merged = false;
            if (p_micro_cluster.getClustering().size() != 0) {
                MicroCluster x = nearestCluster(point, p_micro_cluster);
                MicroCluster xCopy = x.copy();
                xCopy.insert(point, timestamp);
                if (xCopy.getRadius(timestamp) <= epsilon) {
                    x.insert(point, timestamp);
                    merged = true;
                }
            }
            if (!merged && (o_micro_cluster.getClustering().size() != 0)) {
                MicroCluster x = nearestCluster(point, o_micro_cluster);
                MicroCluster xCopy = x.copy();
                xCopy.insert(point, timestamp);
                if (xCopy.getRadius(timestamp) <= epsilon) {
                    x.insert(point, timestamp);
                    merged = true;
                    if (x.getWeight() > beta * mu) {
                        o_micro_cluster.getClustering().remove(x);
                        p_micro_cluster.getClustering().add(x);
                    }
                }
            }
            if (!merged) {
                o_micro_cluster.getClustering().add(
                        new MicroCluster(point.toDoubleArray(), point
                                .toDoubleArray().length, timestamp, lambda,
                                currentTimestamp));
            }
            // //////////////////////////
            // Periodic cluster removal//
            // //////////////////////////
            if (timestamp % tp == 0) {
                ArrayList<MicroCluster> removalList = new ArrayList<MicroCluster>();
                for (Cluster c : p_micro_cluster.getClustering()) {
                    if (((MicroCluster) c).getWeight() < beta * mu) {
                        removalList.add((MicroCluster) c);
                    }
                }
                for (Cluster c : removalList) {
                    p_micro_cluster.getClustering().remove(c);
                }
                for (Cluster c : o_micro_cluster.getClustering()) {
                    long t0 = ((MicroCluster) c).getCreationTime();
                    double xsi1 = Math
                            .pow(2, (-lambda * (timestamp - t0 + tp))) - 1;
                    double xsi2 = Math.pow(2, -lambda * tp) - 1;
                    double xsi = xsi1 / xsi2;
                    if (((MicroCluster) c).getWeight() < xsi) {
                        removalList.add((MicroCluster) c);
                    }
                }
                for (Cluster c : removalList) {
                    o_micro_cluster.getClustering().remove(c);
                }
            }
        }
    }
Member Data Documentation
double moa.clusterers.denstream.WithDBSCAN.beta [package]
Definition at line 72 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
FloatOption moa.clusterers.denstream.WithDBSCAN.betaOption
Initial value:
 new FloatOption("beta", 'b', "", 0.2, 0,
            1)
Definition at line 50 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString(), and moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
Timestamp moa.clusterers.denstream.WithDBSCAN.currentTimestamp [package]
Definition at line 80 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
double moa.clusterers.denstream.WithDBSCAN.epsilon [package]
Definition at line 69 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), moa.clusterers.denstream.WithDBSCAN.getClusteringResult(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
FloatOption moa.clusterers.denstream.WithDBSCAN.epsilonOption
Initial value:
 new FloatOption("epsilon", 'e',
            "Defines the epsilon neighbourhood", 0.02, 0, 1)
Definition at line 45 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString(), and moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
IntOption moa.clusterers.denstream.WithDBSCAN.horizonOption
Initial value:
 new IntOption("horizon", 'h',
            "Range of the window.", 1000)
Definition at line 43 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString().
ArrayList<DenPoint> moa.clusterers.denstream.WithDBSCAN.initBuffer [package]
Definition at line 76 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
boolean moa.clusterers.denstream.WithDBSCAN.initialized [package]
Definition at line 78 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
IntOption moa.clusterers.denstream.WithDBSCAN.initPointsOption
Initial value:
 new IntOption("initPoints", 'i',
            "Number of points to use for initialization.", 1000)
Definition at line 54 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
double moa.clusterers.denstream.WithDBSCAN.lambda [package]
Definition at line 68 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
FloatOption moa.clusterers.denstream.WithDBSCAN.lambdaOption
Initial value:
 new FloatOption("lambda", 'l', "",
             0.25,
             0, 1)
Definition at line 60 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString(), and moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
int moa.clusterers.denstream.WithDBSCAN.minPoints [package]
Definition at line 70 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), moa.clusterers.denstream.WithDBSCAN.getClusteringResult(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), and moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
double moa.clusterers.denstream.WithDBSCAN.mu [package]
Definition at line 71 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
FloatOption moa.clusterers.denstream.WithDBSCAN.muOption
Initial value:
 new FloatOption("mu", 'm', "", 1, 0,
            Double.MAX_VALUE)
Definition at line 52 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getParameterString(), and moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
int moa.clusterers.denstream.WithDBSCAN.numInitPoints [protected]
Definition at line 84 of file WithDBSCAN.java.
int moa.clusterers.denstream.WithDBSCAN.numProcessedPerUnit [protected]
Definition at line 85 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
Clustering moa.clusterers.denstream.WithDBSCAN.o_micro_cluster [package]
Definition at line 75 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
FloatOption moa.clusterers.denstream.WithDBSCAN.offlineOption
Initial value:
 new FloatOption("offline", 'o',
     "offline multiplier for epsilion.", 2, 2, 20)
Definition at line 57 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getClusteringResult().
Clustering moa.clusterers.denstream.WithDBSCAN.p_micro_cluster [package]
Definition at line 74 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.getClusteringResult(), moa.clusterers.denstream.WithDBSCAN.getMicroClusteringResult(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
int moa.clusterers.denstream.WithDBSCAN.processingSpeed [protected]
Definition at line 86 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
final long moa.clusterers.denstream.WithDBSCAN.serialVersionUID = 1L [static, private]
Reimplemented from moa.options.AbstractOptionHandler.
Definition at line 41 of file WithDBSCAN.java.
IntOption moa.clusterers.denstream.WithDBSCAN.speedOption
Initial value:
 new IntOption("processingSpeed", 's',
                "Number of incoming points per time unit.", 100, 1, 1000)
Definition at line 64 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl().
long moa.clusterers.denstream.WithDBSCAN.timestamp = 0 [private]
Definition at line 79 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.expandCluster(), moa.clusterers.denstream.WithDBSCAN.initialDBScan(), moa.clusterers.denstream.WithDBSCAN.nearestCluster(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
long moa.clusterers.denstream.WithDBSCAN.tp [package]
Definition at line 81 of file WithDBSCAN.java.
Referenced by moa.clusterers.denstream.WithDBSCAN.resetLearningImpl(), and moa.clusterers.denstream.WithDBSCAN.trainOnInstanceImpl().
double moa.clusterers.denstream.WithDBSCAN.weightThreshold = 0.01 [private]
Definition at line 67 of file WithDBSCAN.java.
The documentation for this class was generated from the following file:
main/java/moa/clusterers/denstream/WithDBSCAN.java