MOA: moa.evaluation.LearningEvaluation Class Reference
moa.evaluation.LearningEvaluation Class Reference
Class that stores an array of evaluation measurements.
Public Member Functions
LearningEvaluation (Measurement[] measurements)
LearningEvaluation (Measurement[] evaluationMeasurements, ClassificationPerformanceEvaluator cpe, Classifier model)
LearningEvaluation (ClassificationPerformanceEvaluator cpe, Classifier model)
LearningEvaluation (Measurement[] evaluationMeasurements, LearningPerformanceEvaluator cpe, Clusterer model)
Measurement[] getMeasurements ()
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Protected Attributes
Measurement[] measurements
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Class that stores an array of evaluation measurements.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 37 of file LearningEvaluation.java.
Constructor & Destructor Documentation
moa.evaluation.LearningEvaluation.LearningEvaluation (Measurement[] measurements)
Definition at line 43 of file LearningEvaluation.java.
{
        this.measurements = measurements.clone();
    }
moa.evaluation.LearningEvaluation.LearningEvaluation (Measurement[] evaluationMeasurements, ClassificationPerformanceEvaluator cpe, Classifier model)
Definition at line 47 of file LearningEvaluation.java.
References moa.classifiers.Classifier.getModelMeasurements(), moa.evaluation.ClassificationPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.LearningEvaluation.measurements.
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        if (evaluationMeasurements != null){
            measurementList.addAll(Arrays.asList(evaluationMeasurements));
        }
        measurementList.addAll(Arrays.asList(cpe.getPerformanceMeasurements()));
        measurementList.addAll(Arrays.asList(model.getModelMeasurements()));
        this.measurements = measurementList.toArray(new Measurement[measurementList.size()]);
    }
moa.evaluation.LearningEvaluation.LearningEvaluation (ClassificationPerformanceEvaluator cpe, Classifier model)
Definition at line 58 of file LearningEvaluation.java.
{
        this(null,cpe,model);
    }
moa.evaluation.LearningEvaluation.LearningEvaluation (Measurement[] evaluationMeasurements, LearningPerformanceEvaluator cpe, Clusterer model)
Definition at line 64 of file LearningEvaluation.java.
References moa.clusterers.Clusterer.getModelMeasurements(), moa.evaluation.LearningPerformanceEvaluator.getPerformanceMeasurements(), and moa.evaluation.LearningEvaluation.measurements.
{
        List<Measurement> measurementList = new LinkedList<Measurement>();
        measurementList.addAll(Arrays.asList(evaluationMeasurements));
        measurementList.addAll(Arrays.asList(cpe.getPerformanceMeasurements()));
        measurementList.addAll(Arrays.asList(model.getModelMeasurements()));
        this.measurements = measurementList.toArray(new Measurement[measurementList.size()]);
    }
Member Function Documentation
void moa.evaluation.LearningEvaluation.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Definition at line 78 of file LearningEvaluation.java.
References moa.evaluation.LearningEvaluation.measurements.
{
        Measurement.getMeasurementsDescription(this.measurements, sb, indent);
    }
Measurement [] moa.evaluation.LearningEvaluation.getMeasurements ()
Definition at line 73 of file LearningEvaluation.java.
References moa.evaluation.LearningEvaluation.measurements.
Referenced by moa.evaluation.LearningCurve.insertEntry().
{
        return this.measurements.clone();
    }
Member Data Documentation
Measurement [] moa.evaluation.LearningEvaluation.measurements [protected]
Definition at line 41 of file LearningEvaluation.java.
Referenced by moa.evaluation.LearningEvaluation.getDescription(), moa.evaluation.LearningEvaluation.getMeasurements(), and moa.evaluation.LearningEvaluation.LearningEvaluation().
final long moa.evaluation.LearningEvaluation.serialVersionUID = 1L [static, private]
Definition at line 39 of file LearningEvaluation.java.
The documentation for this class was generated from the following file:
main/java/moa/evaluation/LearningEvaluation.java