MOA: moa.classifiers.core.splitcriteria.SplitCriterion Interface Reference
moa.classifiers.core.splitcriteria.SplitCriterion Interface Reference
Interface for computing splitting criteria.
Public Member Functions
double getMeritOfSplit (double[] preSplitDist, double[][] postSplitDists)
Computes the merit of splitting for a given ditribution before the split and after it.
double getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
Detailed Description
Interface for computing splitting criteria.
with respect to distributions of class values. The split criterion is used as a parameter on decision trees and decision stumps. The two split criteria most used are Information Gain and Gini.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 35 of file SplitCriterion.java.
Member Function Documentation
double moa.classifiers.core.splitcriteria.SplitCriterion.getMeritOfSplit (double[] preSplitDist, double postSplitDists[][])
Computes the merit of splitting for a given ditribution before the split and after it.
Parameters:
preSplitDist the class distribution before the split
postSplitDist the class distribution after the split
Returns:
value of the merit of splitting
Implemented in moa.classifiers.core.splitcriteria.GiniSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterion, moa.classifiers.core.splitcriteria.VarianceReductionSplitCriterion, and moa.classifiers.rules.core.splitcriteria.SDRSplitCriterionAMRules.
Referenced by moa.classifiers.trees.HoeffdingOptionTree.SplitNode.computeMeritOfExistingSplit(), moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver.getBestEvaluatedSplitSuggestion(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.getBestSplitSuggestions(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.removeBadSplitNodes(), moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver.searchForBestSplitOption(), and moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver.searchForBestSplitOption().
double moa.classifiers.core.splitcriteria.SplitCriterion.getRangeOfMerit (double[] preSplitDist)
Computes the range of splitting merit.
Parameters:
preSplitDist the class distribution before the split
Returns:
value of the range of splitting merit
Implemented in moa.classifiers.core.splitcriteria.GiniSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterion, moa.classifiers.core.splitcriteria.VarianceReductionSplitCriterion, and moa.classifiers.rules.core.splitcriteria.SDRSplitCriterionAMRules.
Referenced by moa.classifiers.trees.HoeffdingTree.attemptToSplit(), moa.classifiers.trees.HoeffdingOptionTree.attemptToSplit(), and moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.attemptToSplit().
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/core/splitcriteria/SplitCriterion.java