MOA: moa.tasks.TaskMonitor Interface Reference
moa.tasks.TaskMonitor Interface Reference
Interface representing a task monitor.
Public Member Functions
void setCurrentActivity (String activityDescription, double fracComplete)
Sets the description and the percentage done of the current activity.
void setCurrentActivityDescription (String activity)
Sets the description of the current activity.
void setCurrentActivityFractionComplete (double fracComplete)
Sets the percentage done of the current activity.
boolean taskShouldAbort ()
Gets whether the task should abort.
boolean resultPreviewRequested ()
Gets whether there is a request for preview the task result.
void setLatestResultPreview (Object latestPreview)
Sets the current result to preview.
String getCurrentActivityDescription ()
Gets the description of the current activity.
double getCurrentActivityFractionComplete ()
Gets the percentage done of the current activity.
void requestPause ()
Requests the task monitored to pause.
void requestResume ()
Requests the task monitored to resume.
void requestCancel ()
Requests the task monitored to cancel.
boolean isPaused ()
Gets whether the task monitored is paused.
boolean isCancelled ()
Gets whether the task monitored is cancelled.
void requestResultPreview ()
Requests to preview the task result.
void requestResultPreview (ResultPreviewListener toInform)
Requests to preview the task result.
Object getLatestResultPreview ()
Gets the current result to preview.
Detailed Description
Interface representing a task monitor.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 28 of file TaskMonitor.java.
Member Function Documentation
String moa.tasks.TaskMonitor.getCurrentActivityDescription ()
Gets the description of the current activity.
Returns:
the description of the current activity
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.getCurrentActivityString().
double moa.tasks.TaskMonitor.getCurrentActivityFractionComplete ()
Gets the percentage done of the current activity.
Returns:
the percentage done of the current activity
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.getCurrentActivityFracComplete().
Object moa.tasks.TaskMonitor.getLatestResultPreview ()
Gets the current result to preview.
Returns:
the result to preview
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.getLatestResultPreview().
boolean moa.tasks.TaskMonitor.isCancelled ()
Gets whether the task monitored is cancelled.
Returns:
true if the task is cancelled
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.run().
boolean moa.tasks.TaskMonitor.isPaused ()
Gets whether the task monitored is paused.
Returns:
true if the task is paused
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
void moa.tasks.TaskMonitor.requestCancel ()
Requests the task monitored to cancel.
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.cancelTask().
void moa.tasks.TaskMonitor.requestPause ()
Requests the task monitored to pause.
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.pauseTask().
void moa.tasks.TaskMonitor.requestResultPreview (ResultPreviewListener toInform)
Requests to preview the task result.
Parameters:
toInform the listener of the changes in the preview of the result
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
void moa.tasks.TaskMonitor.requestResultPreview ()
Requests to preview the task result.
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.getPreview().
void moa.tasks.TaskMonitor.requestResume ()
Requests the task monitored to resume.
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.TaskThread.resumeTask().
boolean moa.tasks.TaskMonitor.resultPreviewRequested ()
Gets whether there is a request for preview the task result.
Returns:
true if there is a request for preview the task result
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), and moa.tasks.EvaluateConceptDrift.doMainTask().
void moa.tasks.TaskMonitor.setCurrentActivity (String activityDescription, double fracComplete)
Sets the description and the percentage done of the current activity.
Parameters:
activity the description of the current activity
fracComplete the percentage done of the current activity
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.Plot.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.AbstractTask.doTask(), moa.tasks.MainTask.doTaskImpl(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.options.AbstractOptionHandler.prepareClassOptions(), moa.streams.MultiFilteredStream.prepareForUseImpl(), moa.streams.generators.RandomTreeGenerator.prepareForUseImpl(), moa.streams.generators.RandomRBFGenerator.prepareForUseImpl(), moa.streams.generators.HyperplaneGenerator.prepareForUseImpl(), moa.streams.FilteredStream.prepareForUseImpl(), moa.streams.clustering.RandomRBFGeneratorEvents.prepareForUseImpl(), moa.classifiers.meta.WeightedMajorityAlgorithm.prepareForUseImpl(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl().
void moa.tasks.TaskMonitor.setCurrentActivityDescription (String activity)
Sets the description of the current activity.
Parameters:
activity the description of the current activity
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), and moa.tasks.TaskThread.TaskThread().
void moa.tasks.TaskMonitor.setCurrentActivityFractionComplete (double fracComplete)
Sets the percentage done of the current activity.
Parameters:
fracComplete the percentage done of the current activity
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), and moa.tasks.CacheShuffledStream.doTaskImpl().
void moa.tasks.TaskMonitor.setLatestResultPreview (Object latestPreview)
Sets the current result to preview.
Parameters:
latestPreview the result to preview
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), and moa.tasks.TaskThread.run().
boolean moa.tasks.TaskMonitor.taskShouldAbort ()
Gets whether the task should abort.
Returns:
true if the task should abort
Implemented in moa.tasks.NullMonitor, and moa.tasks.StandardTaskMonitor.
Referenced by moa.tasks.Plot.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateOnlineRecommender.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.AbstractTask.doTask(), moa.tasks.MainTask.doTaskImpl(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.options.AbstractOptionHandler.prepareClassOptions(), moa.streams.MultiFilteredStream.prepareForUseImpl(), moa.streams.FilteredStream.prepareForUseImpl(), moa.classifiers.meta.WeightedMajorityAlgorithm.prepareForUseImpl(), and moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.prepareForUseImpl().
The documentation for this interface was generated from the following file:
main/java/moa/tasks/TaskMonitor.java