MOA: moa.classifiers.Classifier Interface Reference
moa.classifiers.Classifier Interface Reference
Classifier interface for incremental classification models.
Public Member Functions
void setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
InstancesHeader getModelContext ()
Gets the reference to the header of the data stream.
boolean isRandomizable ()
Gets whether this classifier needs a random seed.
void setRandomSeed (int s)
Sets the seed for random number generation.
boolean trainingHasStarted ()
Gets whether training has started.
double trainingWeightSeenByModel ()
Gets the sum of the weights of the instances that have been used by this classifier during the training in trainOnInstance.
void resetLearning ()
Resets this classifier.
void trainOnInstance (Instance inst)
Trains this classifier incrementally using the given instance.
double[] getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
boolean correctlyClassifies (Instance inst)
Gets whether this classifier correctly classifies an instance.
Measurement[] getModelMeasurements ()
Gets the current measurements of this classifier.
Classifier[] getSubClassifiers ()
Gets the classifiers of this ensemble.
Classifier copy ()
Produces a copy of this classifier.
Detailed Description
Classifier interface for incremental classification models.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 35 of file Classifier.java.
Member Function Documentation
Classifier moa.classifiers.Classifier.copy ()
Produces a copy of this classifier.
Returns:
the copy of this classifier
Implements moa.MOAObject.
Implemented in moa.classifiers.AbstractClassifier.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.addToStored(), moa.classifiers.meta.AccuracyUpdatedEnsemble.addToStored(), moa.classifiers.meta.AccuracyWeightedEnsemble.computeCandidateWeight(), moa.classifiers.AbstractClassifier.copy(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.classifiers.meta.ADACC.getBestAdaptiveClassifier(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.LearningNodeClassifier(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.RandomRules.resetLearningImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), moa.classifiers.meta.OzaBagAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBag.resetLearningImpl(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), moa.classifiers.meta.OCBoost.resetLearningImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), moa.classifiers.meta.ADACC.takeSnapshot(), moa.classifiers.AbstractClassifierTestCase.testRegression(), and moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl().
boolean moa.classifiers.Classifier.correctlyClassifies (Instance inst)
Gets whether this classifier correctly classifies an instance.
Uses getVotesForInstance to obtain the prediction and the instance to obtain its true class.
Parameters:
inst the instance to be classified
Returns:
true if the instance is correctly classified
Implemented in moa.classifiers.AbstractClassifier.
Referenced by moa.classifiers.meta.DACC.trainAndClassify(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl().
InstancesHeader moa.classifiers.Classifier.getModelContext ()
Gets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Returns:
the reference to the data stream header
Implemented in moa.classifiers.AbstractClassifier.
Measurement [] moa.classifiers.Classifier.getModelMeasurements ()
Gets the current measurements of this classifier.
Returns:
an array of measurements to be used in evaluation tasks
Implemented in moa.classifiers.AbstractClassifier.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.classifiers.AbstractClassifierTestCase.inspect(), and moa.evaluation.LearningEvaluation.LearningEvaluation().
Classifier [] moa.classifiers.Classifier.getSubClassifiers ()
Gets the classifiers of this ensemble.
Returns null if this classifier is a single classifier.
Returns:
an array of the classifiers of the ensemble
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, and moa.classifiers.meta.WeightedMajorityAlgorithm.
double [] moa.classifiers.Classifier.getVotesForInstance (Instance inst)
Predicts the class memberships for a given instance.
If an instance is unclassified, the returned array elements must be all zero.
Parameters:
inst the instance to be classified
Returns:
an array containing the estimated membership probabilities of the test instance in each class
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.meta.MLOzaBag, moa.classifiers.multilabel.meta.MLOzaBagAdwin, moa.classifiers.multilabel.MultilabelHoeffdingTree, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.functions.FadingTargetMean, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.rules.RuleClassifierNBayes, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.ORTO, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.meta.AccuracyUpdatedEnsemble.computeMse(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.computeWeight(), moa.classifiers.meta.AccuracyWeightedEnsemble.computeWeight(), moa.classifiers.AbstractClassifier.correctlyClassifies(), weka.classifiers.meta.MOA.distributionForInstance(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.getClassVotes(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.getVotesForInstance(), moa.classifiers.multilabel.meta.MLOzaBag.getVotesForInstance(), moa.classifiers.meta.TemporallyAugmentedClassifier.getVotesForInstance(), moa.classifiers.meta.LimAttClassifier.getVotesForInstance(), moa.classifiers.meta.DACC.getVotesForInstance(), moa.classifiers.drift.DriftDetectionMethodClassifier.getVotesForInstance(), moa.classifiers.active.ActiveClassifier.getVotesForInstance(), moa.classifiers.meta.OzaBoostAdwin.getVotesForInstanceBinary(), moa.classifiers.meta.LeveragingBag.getVotesForInstanceBinary(), moa.classifiers.AbstractClassifierTestCase.inspect(), moa.classifiers.meta.ADACC.takeSnapshot(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), and moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl().
boolean moa.classifiers.Classifier.isRandomizable ()
Gets whether this classifier needs a random seed.
Examples of methods that needs a random seed are bagging and boosting.
Returns:
true if the classifier needs a random seed.
Implemented in moa.classifiers.DecisionStumpTutorial, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyUpdatedEnsemble, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.meta.MLOzaBag, moa.classifiers.rules.AbstractAMRules, moa.classifiers.rules.AMRulesRegressor, moa.classifiers.rules.functions.Perceptron, moa.classifiers.rules.functions.TargetMean, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.LimAttHoeffdingTree, moa.classifiers.trees.ORTO, moa.classifiers.trees.RandomHoeffdingTree, and moa.learners.ChangeDetectorLearner.
Referenced by moa.classifiers.AbstractClassifier.AbstractClassifier(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), and moa.classifiers.AbstractClassifier.resetLearning().
void moa.classifiers.Classifier.resetLearning ()
Resets this classifier.
It must be similar to starting a new classifier from scratch.
Implemented in moa.classifiers.AbstractClassifier.
Referenced by weka.classifiers.meta.MOA.buildClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.createNewClassifier(), moa.classifiers.meta.DACC.discardModel(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.MultilabelLearningNodeClassifier(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.prepareForUseImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.processChunk(), moa.classifiers.multilabel.meta.MLOzaBag.resetLearningImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.resetLearningImpl(), moa.classifiers.meta.RandomRules.resetLearningImpl(), moa.classifiers.meta.OzaBoostAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBoost.resetLearningImpl(), moa.classifiers.meta.OzaBagASHT.resetLearningImpl(), moa.classifiers.meta.OzaBagAdwin.resetLearningImpl(), moa.classifiers.meta.OzaBag.resetLearningImpl(), moa.classifiers.meta.OnlineSmoothBoost.resetLearningImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.meta.OCBoost.resetLearningImpl(), moa.classifiers.meta.LeveragingBag.resetLearningImpl(), moa.classifiers.meta.DACC.resetLearningImpl(), moa.classifiers.meta.AccuracyWeightedEnsemble.resetLearningImpl(), moa.classifiers.meta.AccuracyUpdatedEnsemble.resetLearningImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.resetLearningImpl(), moa.classifiers.active.ActiveClassifier.resetLearningImpl(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.setModelContext(), moa.classifiers.multilabel.meta.MLOzaBag.setModelContext(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
void moa.classifiers.Classifier.setModelContext (InstancesHeader ih)
Sets the reference to the header of the data stream.
The header of the data stream is extended from WEKA Instances. This header is needed to know the number of classes and attributes
Parameters:
ih the reference to the data stream header
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.lazy.kNN, moa.classifiers.multilabel.MajorityLabelset, moa.classifiers.multilabel.MEKAClassifier, moa.classifiers.multilabel.meta.MLOzaBag, moa.classifiers.multilabel.meta.MLOzaBagAdwin, and moa.classifiers.multilabel.MultilabelHoeffdingTree.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.setModelContext(), moa.classifiers.multilabel.meta.MLOzaBag.setModelContext(), moa.classifiers.AbstractClassifierTestCase.testRegression(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), and moa.classifiers.meta.RandomRules.transformInstance().
void moa.classifiers.Classifier.setRandomSeed (int s)
Sets the seed for random number generation.
Parameters:
s the seed
Implemented in moa.classifiers.AbstractClassifier.
Referenced by moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask().
boolean moa.classifiers.Classifier.trainingHasStarted ()
Gets whether training has started.
Returns:
true if training has started
Implemented in moa.classifiers.AbstractClassifier.
double moa.classifiers.Classifier.trainingWeightSeenByModel ()
Gets the sum of the weights of the instances that have been used by this classifier during the training in trainOnInstance.
Returns:
the weight of the instances that have been used training
Implemented in moa.classifiers.AbstractClassifier.
void moa.classifiers.Classifier.trainOnInstance (Instance inst)
Trains this classifier incrementally using the given instance.
Parameters:
inst the instance to be used for training
Implemented in moa.classifiers.AbstractClassifier.
Referenced by moa.classifiers.meta.AccuracyWeightedEnsemble.computeCandidateWeight(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.classifiers.AbstractClassifierTestCase.inspect(), moa.classifiers.active.ActiveClassifier.labelFixed(), moa.classifiers.active.ActiveClassifier.labelRandom(), moa.classifiers.active.ActiveClassifier.labelSelSampling(), moa.classifiers.active.ActiveClassifier.labelVar(), moa.classifiers.multilabel.HoeffdingTreeClassifLeaves.LearningNodeClassifier.learnFromInstance(), moa.classifiers.meta.AccuracyWeightedEnsemble.processChunk(), moa.classifiers.meta.AccuracyUpdatedEnsemble.trainOnChunk(), moa.classifiers.multilabel.meta.MLOzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.TemporallyAugmentedClassifier.trainOnInstanceImpl(), moa.classifiers.meta.RandomRules.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoostAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBoost.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagASHT.trainOnInstanceImpl(), moa.classifiers.meta.OzaBagAdwin.trainOnInstanceImpl(), moa.classifiers.meta.OzaBag.trainOnInstanceImpl(), moa.classifiers.meta.OnlineSmoothBoost.trainOnInstanceImpl(), moa.classifiers.meta.OnlineAccuracyUpdatedEnsemble.trainOnInstanceImpl(), moa.classifiers.meta.OCBoost.trainOnInstanceImpl(), moa.classifiers.meta.LimAttClassifier.trainOnInstanceImpl(), moa.classifiers.meta.LeveragingBag.trainOnInstanceImpl(), moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl(), moa.classifiers.active.ActiveClassifier.trainOnInstanceImpl(), and weka.classifiers.meta.MOA.updateClassifier().
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/Classifier.java