MOA: moa.options.OptionHandler Interface Reference
moa.options.OptionHandler Interface Reference
Interface representing an object that handles options or parameters.
Public Member Functions
String getPurposeString ()
Gets the purpose of this object.
Options getOptions ()
Gets the options of this object.
void prepareForUse ()
This method prepares this object for use.
void prepareForUse (TaskMonitor monitor, ObjectRepository repository)
This method prepares this object for use.
OptionHandler copy ()
This method produces a copy of this object.
String getCLICreationString (Class<?> expectedType)
Gets the Command Line Interface text to create the object.
Detailed Description
Interface representing an object that handles options or parameters.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file OptionHandler.java.
Member Function Documentation
OptionHandler moa.options.OptionHandler.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Implements moa.MOAObject.
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.Classifier, moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ChangeDetector, moa.clusterers.AbstractClusterer, moa.clusterers.Clusterer, and moa.options.AbstractOptionHandler.
Referenced by moa.options.AbstractOptionHandler.copy(), moa.classifiers.trees.HoeffdingTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingOptionTree.newNominalClassObserver(), moa.classifiers.trees.HoeffdingTree.newNumericClassObserver(), and moa.classifiers.trees.HoeffdingOptionTree.newNumericClassObserver().
String moa.options.OptionHandler.getCLICreationString (Class<?> expectedType)
Gets the Command Line Interface text to create the object.
Returns:
the Command Line Interface text to create the object
Implemented in moa.options.AbstractOptionHandler.
Options moa.options.OptionHandler.getOptions ()
Gets the options of this object.
Returns:
the options of this object
Implemented in moa.clusterers.outliers.AnyOut.AnyOut, and moa.options.AbstractOptionHandler.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged(), moa.gui.ClassOptionSelectionPanel.classChoiceChanged(), and moa.gui.OptionsConfigurationPanel.showEditOptionsDialog().
String moa.options.OptionHandler.getPurposeString ()
Gets the purpose of this object.
Returns:
the string with the purpose of this object
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.active.ActiveClassifier, moa.classifiers.bayes.NaiveBayes, moa.classifiers.bayes.NaiveBayesMultinomial, moa.classifiers.drift.DriftDetectionMethodClassifier, moa.classifiers.functions.MajorityClass, moa.classifiers.functions.NoChange, moa.classifiers.functions.Perceptron, moa.classifiers.functions.SGD, moa.classifiers.functions.SGDMultiClass, moa.classifiers.functions.SPegasos, moa.classifiers.lazy.kNN, moa.classifiers.lazy.kNNwithPAW, moa.classifiers.lazy.kNNwithPAWandADWIN, moa.classifiers.meta.AccuracyWeightedEnsemble, moa.classifiers.meta.ADACC, moa.classifiers.meta.DACC, moa.classifiers.meta.LeveragingBag, moa.classifiers.meta.LimAttClassifier, moa.classifiers.meta.OCBoost, moa.classifiers.meta.OnlineSmoothBoost, moa.classifiers.meta.OzaBag, moa.classifiers.meta.OzaBagAdwin, moa.classifiers.meta.OzaBagASHT, moa.classifiers.meta.OzaBoost, moa.classifiers.meta.OzaBoostAdwin, moa.classifiers.meta.RandomRules, moa.classifiers.meta.TemporallyAugmentedClassifier, moa.classifiers.meta.WeightedMajorityAlgorithm, moa.classifiers.meta.WEKAClassifier, moa.classifiers.rules.RuleClassifier, moa.classifiers.trees.AdaHoeffdingOptionTree, moa.classifiers.trees.ASHoeffdingTree, moa.classifiers.trees.DecisionStump, moa.classifiers.trees.FIMTDD, moa.classifiers.trees.HoeffdingAdaptiveTree, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, moa.classifiers.trees.LimAttHoeffdingTree, moa.classifiers.trees.ORTO, moa.classifiers.trees.RandomHoeffdingTree, moa.clusterers.AbstractClusterer, moa.clusterers.outliers.AnyOut.AnyOut, moa.clusterers.WekaClusteringAlgorithm, moa.options.AbstractOptionHandler, moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, moa.recommender.dataset.impl.MovielensDataset, moa.streams.ArffFileStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.multilabel.MultilabelArffFileStream, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomRBFGeneratorDrift, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, moa.streams.MultiFilteredStream, moa.tasks.CacheShuffledStream, moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.classChoiceChanged(), moa.gui.ClassOptionSelectionPanel.classChoiceChanged(), and moa.gui.OptionsConfigurationPanel.showEditOptionsDialog().
void moa.options.OptionHandler.prepareForUse (TaskMonitor monitor, ObjectRepository repository)
This method prepares this object for use.
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Implemented in moa.options.AbstractOptionHandler.
void moa.options.OptionHandler.prepareForUse ()
This method prepares this object for use.
Implemented in moa.options.AbstractOptionHandler.
Referenced by moa.classifiers.AbstractClassifierTestCase.inspect(), and moa.classifiers.AbstractClassifierTestCase.testRegression().
The documentation for this interface was generated from the following file:
main/java/moa/options/OptionHandler.java