MOA: moa.evaluation.ClassificationPerformanceEvaluator Interface Reference
moa.evaluation.ClassificationPerformanceEvaluator Interface Reference
Interface implemented by learner evaluators to monitor the results of the learning process.
Public Member Functions
void reset ()
Resets this evaluator.
void addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Measurement[] getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Detailed Description
Interface implemented by learner evaluators to monitor the results of the learning process.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 33 of file ClassificationPerformanceEvaluator.java.
Member Function Documentation
void moa.evaluation.ClassificationPerformanceEvaluator.addResult (Instance inst, double[] classVotes)
Adds a learning result to this evaluator.
Parameters:
inst the instance to be classified
classVotes an array containing the estimated membership probabilities of the test instance in each class
Returns:
an array of measurements monitored in this evaluator
Implemented in moa.evaluation.BasicClassificationPerformanceEvaluator, moa.evaluation.BasicConceptDriftPerformanceEvaluator, moa.evaluation.BasicRegressionPerformanceEvaluator, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, and moa.evaluation.WindowRegressionPerformanceEvaluator.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), and moa.classifiers.AbstractClassifierTestCase.inspect().
Measurement [] moa.evaluation.ClassificationPerformanceEvaluator.getPerformanceMeasurements ()
Gets the current measurements monitored by this evaluator.
Returns:
an array of measurements monitored by this evaluator
Implemented in moa.evaluation.BasicClassificationPerformanceEvaluator, moa.evaluation.BasicConceptDriftPerformanceEvaluator, moa.evaluation.BasicRegressionPerformanceEvaluator, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, and moa.evaluation.WindowRegressionPerformanceEvaluator.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.classifiers.AbstractClassifierTestCase.inspect(), and moa.evaluation.LearningEvaluation.LearningEvaluation().
void moa.evaluation.ClassificationPerformanceEvaluator.reset ()
Resets this evaluator.
It must be similar to starting a new evaluator from scratch.
Implemented in moa.evaluation.BasicClassificationPerformanceEvaluator, moa.evaluation.BasicConceptDriftPerformanceEvaluator, moa.evaluation.BasicRegressionPerformanceEvaluator, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, and moa.evaluation.WindowRegressionPerformanceEvaluator.
Referenced by moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask().
The documentation for this interface was generated from the following file:
main/java/moa/evaluation/ClassificationPerformanceEvaluator.java