MOA: moa.streams.InstanceStream Interface Reference
moa.streams.InstanceStream Interface Reference
Interface representing a data stream of instances.
Public Member Functions
InstancesHeader getHeader ()
Gets the header of this stream.
long estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
boolean hasMoreInstances ()
Gets whether this stream has more instances to output.
Instance nextInstance ()
Gets the next instance from this stream.
boolean isRestartable ()
Gets whether this stream can restart.
void restart ()
Restarts this stream.
Detailed Description
Interface representing a data stream of instances.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file InstanceStream.java.
Member Function Documentation
long moa.streams.InstanceStream.estimatedRemainingInstances ()
Gets the estimated number of remaining instances in this stream.
Returns:
the estimated number of instances to get from this stream
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AbstractStreamFilter, moa.streams.filters.CacheFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, and moa.streams.MultiFilteredStream.
Referenced by weka.datagenerators.classifiers.classification.MOA.defineDataFormat(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.streams.MultiFilteredStream.estimatedRemainingInstances(), moa.streams.filters.AbstractStreamFilter.estimatedRemainingInstances(), moa.streams.FilteredStream.estimatedRemainingInstances(), and moa.streams.ConceptDriftStream.estimatedRemainingInstances().
InstancesHeader moa.streams.InstanceStream.getHeader ()
Gets the header of this stream.
This is useful to know attributes and classes. InstancesHeader is an extension of weka.Instances.
Returns:
the header of this stream
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.multilabel.MultilabelArffFileStream, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, and moa.streams.MultiFilteredStream.
Referenced by weka.datagenerators.classifiers.classification.MOA.defineDataFormat(), moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), moa.streams.MultiFilteredStream.getHeader(), moa.streams.filters.ReplacingMissingValuesFilter.getHeader(), moa.streams.filters.CacheFilter.getHeader(), moa.streams.filters.AddNoiseFilter.getHeader(), moa.streams.FilteredStream.getHeader(), moa.streams.ConceptDriftStream.getHeader(), moa.streams.filters.CacheFilter.init(), moa.streams.ConceptDriftRealStream.prepareForUseImpl(), and moa.streams.generators.multilabel.MetaMultilabelGenerator.restart().
boolean moa.streams.InstanceStream.hasMoreInstances ()
Gets whether this stream has more instances to output.
This is useful when reading streams from files.
Returns:
true if this stream has more instances to output
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AbstractStreamFilter, moa.streams.filters.CacheFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, and moa.streams.MultiFilteredStream.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), weka.datagenerators.classifiers.classification.MOA.generateExample(), moa.streams.MultiFilteredStream.hasMoreInstances(), moa.streams.filters.AbstractStreamFilter.hasMoreInstances(), moa.streams.FilteredStream.hasMoreInstances(), moa.streams.ConceptDriftStream.hasMoreInstances(), moa.streams.filters.CacheFilter.init(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.gui.BatchCmd.run(), and moa.gui.visualization.RunVisualizer.runVisual().
boolean moa.streams.InstanceStream.isRestartable ()
Gets whether this stream can restart.
Returns:
true if this stream can restart
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AbstractStreamFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, and moa.streams.MultiFilteredStream.
Referenced by moa.streams.MultiFilteredStream.isRestartable(), moa.streams.filters.AbstractStreamFilter.isRestartable(), moa.streams.FilteredStream.isRestartable(), moa.streams.ConceptDriftStream.isRestartable(), and moa.streams.ConceptDriftRealStream.isRestartable().
Instance moa.streams.InstanceStream.nextInstance ()
Gets the next instance from this stream.
Returns:
the next instance of this stream
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomRBFGeneratorDrift, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, and moa.streams.MultiFilteredStream.
Referenced by moa.tasks.WriteStreamToARFFFile.doMainTask(), moa.tasks.MeasureStreamSpeed.doMainTask(), moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.tasks.EvaluateModelRegression.doMainTask(), moa.tasks.EvaluateModel.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), moa.tasks.EvaluateConceptDrift.doMainTask(), moa.tasks.CacheShuffledStream.doTaskImpl(), weka.datagenerators.classifiers.classification.MOA.generateExample(), moa.streams.generators.multilabel.MetaMultilabelGenerator.getNextWithBinary(), moa.streams.filters.CacheFilter.init(), moa.streams.MultiFilteredStream.nextInstance(), moa.streams.filters.ReplacingMissingValuesFilter.nextInstance(), moa.streams.filters.AddNoiseFilter.nextInstance(), moa.streams.FilteredStream.nextInstance(), moa.streams.ConceptDriftStream.nextInstance(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.gui.visualization.RunOutlierVisualizer.processData(), moa.streams.ConceptDriftRealStream.restart(), moa.gui.BatchCmd.run(), and moa.gui.visualization.RunVisualizer.runVisual().
void moa.streams.InstanceStream.restart ()
Restarts this stream.
It must be similar to starting a new stream from scratch.
Implemented in moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AbstractStreamFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, and moa.streams.MultiFilteredStream.
Referenced by moa.tasks.LearnModelRegression.doMainTask(), moa.tasks.LearnModel.doMainTask(), moa.tasks.EvaluatePeriodicHeldOutTest.doMainTask(), moa.streams.ConceptDriftRealStream.nextInstance(), moa.streams.MultiFilteredStream.restart(), moa.streams.generators.multilabel.MetaMultilabelGenerator.restart(), moa.streams.filters.AbstractStreamFilter.restart(), moa.streams.FilteredStream.restart(), moa.streams.ConceptDriftStream.restart(), and moa.streams.ConceptDriftRealStream.restart().
The documentation for this interface was generated from the following file:
main/java/moa/streams/InstanceStream.java