MOA: moa.classifiers.core.attributeclassobservers.AttributeClassObserver Interface Reference
moa.classifiers.core.attributeclassobservers.AttributeClassObserver Interface Reference
Interface for observing the class data distribution for an attribute.
Public Member Functions
void observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
double probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
AttributeSplitSuggestion getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
void observeAttributeTarget (double attVal, double target)
Detailed Description
Interface for observing the class data distribution for an attribute.
This observer monitors the class distribution of a given attribute. Used in naive Bayes and decision trees to monitor data statistics on leaves.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 34 of file AttributeClassObserver.java.
Member Function Documentation
AttributeSplitSuggestion moa.classifiers.core.attributeclassobservers.AttributeClassObserver.getBestEvaluatedSplitSuggestion (SplitCriterion criterion, double[] preSplitDist, int attIndex, boolean binaryOnly)
Gets the best split suggestion given a criterion and a class distribution.
Parameters:
criterion the split criterion to use
preSplitDist the class distribution before the split
attIndex the attribute index
binaryOnly true to use binary splits
Returns:
suggestion of best attribute split
Implemented in moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.
Referenced by moa.classifiers.trees.DecisionStump.findBestSplit(), moa.classifiers.trees.ORTO.ActiveLearningNode.getBestSplitSuggestions(), and moa.classifiers.rules.core.RuleActiveRegressionNode.getBestSplitSuggestions().
void moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeClass (double attVal, int classVal, double weight)
Updates statistics of this observer given an attribute value, a class and the weight of the instance observed.
Parameters:
attVal the value of the attribute
classVal the class
weight the weight of the instance
Implemented in moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.
Referenced by moa.classifiers.trees.RandomHoeffdingTree.RandomLearningNode.learnFromInstance(), moa.classifiers.trees.LimAttHoeffdingTree.LimAttLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.HoeffdingOptionTree.ActiveLearningNode.learnFromInstance(), moa.classifiers.trees.FIMTDD.FIMTDDActiveLearningNode.learnFromInstance(), moa.classifiers.multilabel.MultilabelHoeffdingTree.MultilabelLearningNodeClassifier.learnFromInstance(), moa.classifiers.trees.DecisionStump.trainOnInstanceImpl(), moa.classifiers.rules.RuleClassifier.trainOnInstanceImpl(), and moa.classifiers.bayes.NaiveBayes.trainOnInstanceImpl().
void moa.classifiers.core.attributeclassobservers.AttributeClassObserver.observeAttributeTarget (double attVal, double target)
Implemented in moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.
double moa.classifiers.core.attributeclassobservers.AttributeClassObserver.probabilityOfAttributeValueGivenClass (double attVal, int classVal)
Gets the probability for an attribute value given a class.
Parameters:
attVal the attribute value
classVal the class
Returns:
probability for an attribute value given a class
Implemented in moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, and moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver.
Referenced by moa.classifiers.bayes.NaiveBayes.doNaiveBayesPrediction(), and moa.classifiers.bayes.NaiveBayes.doNaiveBayesPredictionLog().
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/core/attributeclassobservers/AttributeClassObserver.java