MOA: moa.clusterers.Clusterer Interface Reference
moa.clusterers.Clusterer Interface Reference
Public Member Functions
void setModelContext (InstancesHeader ih)
InstancesHeader getModelContext ()
boolean isRandomizable ()
void setRandomSeed (int s)
boolean trainingHasStarted ()
double trainingWeightSeenByModel ()
void resetLearning ()
void trainOnInstance (Instance inst)
double[] getVotesForInstance (Instance inst)
Measurement[] getModelMeasurements ()
Clusterer[] getSubClusterers ()
Clusterer copy ()
This method produces a copy of this object.
Clustering getClusteringResult ()
boolean implementsMicroClusterer ()
Clustering getMicroClusteringResult ()
boolean keepClassLabel ()
Detailed Description
Definition at line 30 of file Clusterer.java.
Member Function Documentation
Clusterer moa.clusterers.Clusterer.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Implements moa.MOAObject.
Implemented in moa.clusterers.AbstractClusterer.
Referenced by moa.clusterers.AbstractClusterer.copy().
Clustering moa.clusterers.Clusterer.getClusteringResult ()
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.gui.visualization.RunVisualizer.processClusterings(), and moa.gui.BatchCmd.run().
Clustering moa.clusterers.Clusterer.getMicroClusteringResult ()
Implemented in moa.clusterers.AbstractClusterer, moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.denstream.WithDBSCAN, and moa.clusterers.outliers.MyBaseOutlierDetector.
InstancesHeader moa.clusterers.Clusterer.getModelContext ()
Implemented in moa.clusterers.AbstractClusterer.
Measurement [] moa.clusterers.Clusterer.getModelMeasurements ()
Implemented in moa.clusterers.AbstractClusterer.
Referenced by moa.evaluation.LearningEvaluation.LearningEvaluation().
Clusterer [] moa.clusterers.Clusterer.getSubClusterers ()
Implemented in moa.clusterers.AbstractClusterer.
double [] moa.clusterers.Clusterer.getVotesForInstance (Instance inst)
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
boolean moa.clusterers.Clusterer.implementsMicroClusterer ()
Implemented in moa.clusterers.AbstractClusterer, moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.denstream.WithDBSCAN, and moa.clusterers.outliers.MyBaseOutlierDetector.
boolean moa.clusterers.Clusterer.isRandomizable ()
Implemented in moa.clusterers.ClusterGenerator, moa.clusterers.clustream.Clustream, moa.clusterers.clustream.WithKmeans, moa.clusterers.clustree.ClusTree, moa.clusterers.CobWeb, moa.clusterers.denstream.WithDBSCAN, moa.clusterers.outliers.MyBaseOutlierDetector, moa.clusterers.streamkm.StreamKM, and moa.clusterers.WekaClusteringAlgorithm.
Referenced by moa.clusterers.AbstractClusterer.AbstractClusterer(), and moa.clusterers.AbstractClusterer.resetLearning().
boolean moa.clusterers.Clusterer.keepClassLabel ()
Implemented in moa.clusterers.AbstractClusterer, moa.clusterers.ClusterGenerator, moa.clusterers.outliers.MyBaseOutlierDetector, and moa.clusterers.WekaClusteringAlgorithm.
void moa.clusterers.Clusterer.resetLearning ()
Implemented in moa.clusterers.AbstractClusterer, and moa.clusterers.outliers.AnyOut.AnyOutCore.
void moa.clusterers.Clusterer.setModelContext (InstancesHeader ih)
Implemented in moa.clusterers.AbstractClusterer.
void moa.clusterers.Clusterer.setRandomSeed (int s)
Implemented in moa.clusterers.AbstractClusterer.
boolean moa.clusterers.Clusterer.trainingHasStarted ()
Implemented in moa.clusterers.AbstractClusterer.
double moa.clusterers.Clusterer.trainingWeightSeenByModel ()
Implemented in moa.clusterers.AbstractClusterer.
void moa.clusterers.Clusterer.trainOnInstance (Instance inst)
Implemented in moa.clusterers.AbstractClusterer.
The documentation for this interface was generated from the following file:
main/java/moa/clusterers/Clusterer.java