MOA: moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg Interface Reference
moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg Interface Reference
Public Member Functions
void print (String s)
void println (String s)
void printf (String fmt, Object...args)
Detailed Description
Definition at line 316 of file MyBaseOutlierDetector.java.
Member Function Documentation
void moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.print (String s)
Implemented in moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg, and moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Print().
void moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.printf (String fmt, Object... args)
Implemented in moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg, and moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Printf().
void moa.clusterers.outliers.MyBaseOutlierDetector.PrintMsg.println (String s)
Implemented in moa.clusterers.outliers.MyBaseOutlierDetector.StdPrintMsg, and moa.gui.visualization.RunOutlierVisualizer.LogPanelPrintMsg.
Referenced by moa.clusterers.outliers.MyBaseOutlierDetector.Println(), and moa.clusterers.outliers.MyBaseOutlierDetector.MyProgressInfo.ShowProgress().
The documentation for this interface was generated from the following file:
main/java/moa/clusterers/outliers/MyBaseOutlierDetector.java