MOA: moa.options.Option Interface Reference
moa.options.Option Interface Reference
Interface representing an option or parameter.
Public Member Functions
String getName ()
Gets the name of this option.
char getCLIChar ()
Gets the Command Line Interface text of this option.
String getPurpose ()
Gets the purpose of this option.
String getDefaultCLIString ()
Gets the Command Line Interface text.
void setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
String getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
void resetToDefault ()
Resets this option to the default value.
String getStateString ()
Gets the state of this option in human readable form.
Option copy ()
Gets a copy of this option.
JComponent getEditComponent ()
Gets the GUI component to edit.
Detailed Description
Interface representing an option or parameter.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file Option.java.
Member Function Documentation
Option moa.options.Option.copy ()
Gets a copy of this option.
Returns:
the copy of this option
Implements moa.MOAObject.
Implemented in moa.options.AbstractOption.
Referenced by moa.options.ListOption.cliStringToOptionArray(), moa.options.AbstractOption.copy(), and moa.options.ListOption.setList().
char moa.options.Option.getCLIChar ()
Gets the Command Line Interface text of this option.
Returns:
the Command Line Interface text
Implemented in moa.options.AbstractOption.
Referenced by moa.options.Options.addOption().
String moa.options.Option.getDefaultCLIString ()
Gets the Command Line Interface text.
Returns:
the Command Line Interface text
Implemented in moa.options.AbstractClassOption, moa.options.FlagOption, moa.options.FloatOption, moa.options.IntOption, moa.options.ListOption, moa.options.MultiChoiceOption, and moa.options.StringOption.
Referenced by moa.options.AbstractOption.resetToDefault().
JComponent moa.options.Option.getEditComponent ()
Gets the GUI component to edit.
Returns:
the component to edit
Implemented in moa.options.AbstractClassOption, moa.options.AbstractOption, moa.options.ClassOption, moa.options.ClassOptionWithNames, moa.options.FileOption, moa.options.FlagOption, moa.options.FloatOption, moa.options.IntOption, moa.options.MultiChoiceOption, and moa.options.WEKAClassOption.
Referenced by moa.gui.OptionsConfigurationPanel.createLabelledOptionComponentListPanel().
String moa.options.Option.getName ()
Gets the name of this option.
Returns:
the name of this option
Implemented in moa.options.AbstractOption.
Referenced by moa.options.Options.addOption().
String moa.options.Option.getPurpose ()
Gets the purpose of this option.
Returns:
the purpose of this option
Implemented in moa.options.AbstractOption.
String moa.options.Option.getStateString ()
Gets the state of this option in human readable form.
Returns:
the string with state of this option in human readable form
Implemented in moa.options.AbstractOption, and moa.options.FlagOption.
String moa.options.Option.getValueAsCLIString ()
Gets the value of a Command Line Interface text as a string.
Returns:
the string with the value of the Command Line Interface text
Implemented in moa.options.AbstractClassOption, moa.options.ClassOption, moa.options.ClassOptionWithNames, moa.options.FlagOption, moa.options.FloatOption, moa.options.IntOption, moa.options.ListOption, moa.options.MultiChoiceOption, moa.options.StringOption, and moa.options.WEKAClassOption.
Referenced by moa.options.AbstractOption.getStateString(), and moa.gui.StringOptionEditComponent.StringOptionEditComponent().
void moa.options.Option.resetToDefault ()
Resets this option to the default value.
Implemented in moa.options.AbstractOption.
void moa.options.Option.setValueViaCLIString (String s)
Sets value of this option via the Command Line Interface text.
Parameters:
s the Command Line Interface text
Implemented in moa.options.AbstractClassOption, moa.options.ClassOption, moa.options.ClassOptionWithNames, moa.options.FlagOption, moa.options.FloatOption, moa.options.IntOption, moa.options.ListOption, moa.options.MultiChoiceOption, moa.options.StringOption, and moa.options.WEKAClassOption.
Referenced by moa.gui.StringOptionEditComponent.applyState(), moa.options.ListOption.cliStringToOptionArray(), moa.options.AbstractOption.resetToDefault(), moa.options.ListOption.setList(), and moa.options.Options.setViaCLIString().
The documentation for this interface was generated from the following file:
main/java/moa/options/Option.java