MOA: moa.recommender.dataset.Dataset Interface Reference
moa.recommender.dataset.Dataset Interface Reference
Public Member Functions
boolean next ()
int curUserID ()
int curItemID ()
double curRating ()
void reset ()
Detailed Description
Definition at line 23 of file Dataset.java.
Member Function Documentation
int moa.recommender.dataset.Dataset.curItemID ()
Implemented in moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
double moa.recommender.dataset.Dataset.curRating ()
Implemented in moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
int moa.recommender.dataset.Dataset.curUserID ()
Implemented in moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
boolean moa.recommender.dataset.Dataset.next ()
Implemented in moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
void moa.recommender.dataset.Dataset.reset ()
Implemented in moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, and moa.recommender.dataset.impl.MovielensDataset.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
The documentation for this interface was generated from the following file:
main/java/moa/recommender/dataset/Dataset.java