MOA: moa.tasks.Task Interface Reference
moa.tasks.Task Interface Reference
Interface representing a task.
Public Member Functions
Class<?> getTaskResultType ()
Gets the result type of this task.
Object doTask ()
This method performs this task, when TaskMonitor and ObjectRepository are no needed.
Object doTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
Detailed Description
Interface representing a task.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 31 of file Task.java.
Member Function Documentation
Object moa.tasks.Task.doTask (TaskMonitor monitor, ObjectRepository repository)
This method performs this task.
AbstractTask implements this method so all its extensions only need to implement doTaskImpl
Parameters:
monitor the TaskMonitor to use
repository the ObjectRepository to use
Returns:
an object with the result of this task
Implemented in moa.tasks.AbstractTask.
Object moa.tasks.Task.doTask ()
This method performs this task, when TaskMonitor and ObjectRepository are no needed.
Returns:
an object with the result of this task
Implemented in moa.tasks.AbstractTask.
Referenced by moa.tasks.RunTasks.doMainTask(), moa.tasks.RunStreamTasks.doMainTask(), moa.integration.SimpleClusterTest.doTask(), moa.DoTask.main(), moa.options.AbstractClassOption.materializeObject(), and moa.tasks.TaskThread.run().
Class<?> moa.tasks.Task.getTaskResultType ()
Gets the result type of this task.
Tasks can return LearningCurve, LearningEvaluation, Classifier, String, Instances..
Returns:
a class object of the result of this task
Implemented in moa.tasks.CacheShuffledStream, moa.tasks.EvaluateClustering, moa.tasks.EvaluateConceptDrift, moa.tasks.EvaluateInterleavedChunks, moa.tasks.EvaluateInterleavedTestThenTrain, moa.tasks.EvaluateModel, moa.tasks.EvaluateModelRegression, moa.tasks.EvaluateOnlineRecommender, moa.tasks.EvaluatePeriodicHeldOutTest, moa.tasks.EvaluatePrequential, moa.tasks.EvaluatePrequentialRegression, moa.tasks.LearnModel, moa.tasks.LearnModelRegression, moa.tasks.MeasureStreamSpeed, moa.tasks.Plot, moa.tasks.RunStreamTasks, moa.tasks.RunTasks, and moa.tasks.WriteStreamToARFFFile.
Referenced by moa.gui.ClassOptionWithNamesSelectionPanel.findSuitableClasses(), moa.gui.ClassOptionSelectionPanel.findSuitableClasses(), moa.tasks.RunTasks.getTaskResultType(), and moa.tasks.RunStreamTasks.getTaskResultType().
The documentation for this interface was generated from the following file:
main/java/moa/tasks/Task.java