MOA: moa.classifiers.lazy.neighboursearch.DistanceFunction Interface Reference
moa.classifiers.lazy.neighboursearch.DistanceFunction Interface Reference
Interface for any class that can compute and return distances between two instances.
Public Member Functions
void setInstances (Instances insts)
Sets the instances.
Instances getInstances ()
returns the instances currently set.
void setAttributeIndices (String value)
Sets the range of attributes to use in the calculation of the distance.
String getAttributeIndices ()
Gets the range of attributes used in the calculation of the distance.
void setInvertSelection (boolean value)
Sets whether the matching sense of attribute indices is inverted or not.
boolean getInvertSelection ()
Gets whether the matching sense of attribute indices is inverted or not.
double distance (Instance first, Instance second)
Calculates the distance between two instances.
double distance (Instance first, Instance second, double cutOffValue)
Calculates the distance between two instances.
void postProcessDistances (double distances[])
Does post processing of the distances (if necessary) returned by distance(distance(Instance first, Instance second, double cutOffValue).
void update (Instance ins)
Update the distance function (if necessary) for the newly added instance.
Detailed Description
Interface for any class that can compute and return distances between two instances.
Author:
Ashraf M. Kibriya (amk14@cs.waikato.ac.nz)
Version:
Revision
8034
Definition at line 34 of file DistanceFunction.java.
Member Function Documentation
double moa.classifiers.lazy.neighboursearch.DistanceFunction.distance (Instance first, Instance second, double cutOffValue)
Calculates the distance between two instances.
Offers speed up (if the distance function class in use supports it) in nearest neighbour search by taking into account the cutOff or maximum distance. Depending on the distance function class, post processing of the distances by postProcessDistances(double []) may be required if this function is used.
Parameters:
first the first instance
second the second instance
cutOffValue If the distance being calculated becomes larger than cutOffValue then the rest of the calculation is discarded.
Returns:
the distance between the two given instances or Double.POSITIVE_INFINITY if the distance being calculated becomes larger than cutOffValue.
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
double moa.classifiers.lazy.neighboursearch.DistanceFunction.distance (Instance first, Instance second)
Calculates the distance between two instances.
Parameters:
first the first instance
second the second instance
Returns:
the distance between the two given instances
Implemented in moa.classifiers.lazy.neighboursearch.EuclideanDistance, and moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours().
String moa.classifiers.lazy.neighboursearch.DistanceFunction.getAttributeIndices ()
Gets the range of attributes used in the calculation of the distance.
Returns:
the attribute index range
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Instances moa.classifiers.lazy.neighboursearch.DistanceFunction.getInstances ()
returns the instances currently set.
Returns:
the current instances
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
boolean moa.classifiers.lazy.neighboursearch.DistanceFunction.getInvertSelection ()
Gets whether the matching sense of attribute indices is inverted or not.
Returns:
true if the matching sense is inverted
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
void moa.classifiers.lazy.neighboursearch.DistanceFunction.postProcessDistances (double distances[])
Does post processing of the distances (if necessary) returned by distance(distance(Instance first, Instance second, double cutOffValue).
It may be necessary, depending on the distance function, to do post processing to set the distances on the correct scale. Some distance function classes may not return correct distances using the cutOffValue distance function to minimize the inaccuracies resulting from floating point comparison and manipulation.
Parameters:
distances the distances to post-process
Implemented in moa.classifiers.lazy.neighboursearch.EuclideanDistance.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.kNearestNeighbours(), and moa.classifiers.lazy.neighboursearch.KDTree.kNearestNeighbours().
void moa.classifiers.lazy.neighboursearch.DistanceFunction.setAttributeIndices (String value)
Sets the range of attributes to use in the calculation of the distance.
The indices start from 1, 'first' and 'last' are valid as well. E.g.: first-3,5,6-last
Parameters:
value the new attribute index range
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
void moa.classifiers.lazy.neighboursearch.DistanceFunction.setInstances (Instances insts)
Sets the instances.
Parameters:
insts the instances to use
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.LinearNNSearch(), and moa.classifiers.lazy.neighboursearch.LinearNNSearch.setInstances().
void moa.classifiers.lazy.neighboursearch.DistanceFunction.setInvertSelection (boolean value)
Sets whether the matching sense of attribute indices is inverted or not.
Parameters:
value if true the matching sense is inverted
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
void moa.classifiers.lazy.neighboursearch.DistanceFunction.update (Instance ins)
Update the distance function (if necessary) for the newly added instance.
Parameters:
ins the instance to add
Implemented in moa.classifiers.lazy.neighboursearch.NormalizableDistance.
Referenced by moa.classifiers.lazy.neighboursearch.LinearNNSearch.update().
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/lazy/neighboursearch/DistanceFunction.java