MOA: moa.recommender.rc.utils.Updatable Interface Reference
moa.recommender.rc.utils.Updatable Interface Reference
Public Member Functions
void updateNewUser (int userID, List< Integer > ratedItems, List< Double > ratings)
void updateNewItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
void updateRemoveUser (int userID)
void updateRemoveItem (int itemID)
void updateSetRating (int userID, int itemID, double rating)
void updateRemoveRating (int userID, int itemID)
Detailed Description
Definition at line 25 of file Updatable.java.
Member Function Documentation
void moa.recommender.rc.utils.Updatable.updateNewItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.addItem().
void moa.recommender.rc.utils.Updatable.updateNewUser (int userID, List< Integer > ratedItems, List< Double > ratings)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.addUser().
void moa.recommender.rc.utils.Updatable.updateRemoveItem (int itemID)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.removeItem().
void moa.recommender.rc.utils.Updatable.updateRemoveRating (int userID, int itemID)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.removeRating().
void moa.recommender.rc.utils.Updatable.updateRemoveUser (int userID)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.removeUser().
void moa.recommender.rc.utils.Updatable.updateSetRating (int userID, int itemID, double rating)
Implemented in moa.recommender.rc.predictor.impl.BRISMFPredictor.
Referenced by moa.recommender.rc.data.AbstractRecommenderData.setRating().
The documentation for this interface was generated from the following file:
main/java/moa/recommender/rc/utils/Updatable.java