MOA: moa.classifiers.rules.core.voting.ErrorWeightedVote Interface Reference
moa.classifiers.rules.core.voting.ErrorWeightedVote Interface Reference
ErrorWeightedVote interface for weighted votes based on estimates of errors.
Public Member Functions
void addVote (double[] vote, double error)
Adds a vote and the corresponding error for the computation of the weighted vote and respective weighted error.
double[] computeWeightedVote ()
Computes the weighted vote.
double getWeightedError ()
Returns the weighted error.
double[] getWeights ()
Return the weights error.
int getNumberVotes ()
The number of votes added so far.
MOAObject copy ()
Creates a copy of the object.
Detailed Description
ErrorWeightedVote interface for weighted votes based on estimates of errors.
Author:
João Duarte (jmduarte@inescporto.pt)
Version:
Revision
1
Definition at line 31 of file ErrorWeightedVote.java.
Member Function Documentation
void moa.classifiers.rules.core.voting.ErrorWeightedVote.addVote (double[] vote, double error)
Adds a vote and the corresponding error for the computation of the weighted vote and respective weighted error.
Parameters:
vote a vote returned by a classifier
error the error associated to the vote
Implemented in moa.classifiers.rules.core.voting.AbstractErrorWeightedVote.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
double [] moa.classifiers.rules.core.voting.ErrorWeightedVote.computeWeightedVote ()
Computes the weighted vote.
Also updates the weights of the votes.
Returns:
the weighted vote
Implemented in moa.classifiers.rules.core.voting.AbstractErrorWeightedVote, moa.classifiers.rules.core.voting.InverseErrorWeightedVote, and moa.classifiers.rules.core.voting.UniformWeightedVote.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
MOAObject moa.classifiers.rules.core.voting.ErrorWeightedVote.copy ()
Creates a copy of the object.
Returns:
copy of the object
int moa.classifiers.rules.core.voting.ErrorWeightedVote.getNumberVotes ()
The number of votes added so far.
Returns:
the number of votes
Implemented in moa.classifiers.rules.core.voting.AbstractErrorWeightedVote.
double moa.classifiers.rules.core.voting.ErrorWeightedVote.getWeightedError ()
Returns the weighted error.
Precondition:
computeWeightedVote()
Returns:
the weighted error
Implemented in moa.classifiers.rules.core.voting.AbstractErrorWeightedVote.
Referenced by moa.classifiers.rules.AbstractAMRules.getVotesForInstance().
double [] moa.classifiers.rules.core.voting.ErrorWeightedVote.getWeights ()
Return the weights error.
Precondition:
computeWeightedVote()
Returns:
the weights
Implemented in moa.classifiers.rules.core.voting.AbstractErrorWeightedVote.
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/rules/core/voting/ErrorWeightedVote.java