MOA: moa.recommender.rc.data.RecommenderData Interface Reference
moa.recommender.rc.data.RecommenderData Interface Reference
Public Member Functions
void addUser (int userID, List< Integer > ratedItems, List< Double > ratings)
void removeUser (int userID)
void addItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
void removeItem (int itemID)
void setRating (int userID, int itemID, double rating)
void removeRating (int userID, int itemID)
SparseVector getRatingsUser (int userID)
SparseVector getRatingsItem (int itemID)
double getRating (int userID, int itemID)
int getNumItems ()
int getNumUsers ()
int getNumRatings ()
double getAvgRatingUser (int userID)
double getAvgRatingItem (int itemID)
double getMinRating ()
double getMaxRating ()
Set< Integer > getUsers ()
Set< Integer > getItems ()
double getGlobalMean ()
void attachUpdatable (Updatable obj)
void disableUpdates (boolean disable)
int countRatingsUser (int userID)
int countRatingsItem (int itemID)
Iterator< Rating > ratingIterator ()
boolean userExists (int userID)
boolean itemExists (int itemID)
void clear ()
void close ()
Detailed Description
Definition at line 32 of file RecommenderData.java.
Member Function Documentation
void moa.recommender.rc.data.RecommenderData.addItem (int itemID, List< Integer > ratingUsers, List< Double > ratings)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
void moa.recommender.rc.data.RecommenderData.addUser (int userID, List< Integer > ratedItems, List< Double > ratings)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
void moa.recommender.rc.data.RecommenderData.attachUpdatable (Updatable obj)
Implemented in moa.recommender.rc.data.AbstractRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.BRISMFPredictor().
void moa.recommender.rc.data.RecommenderData.clear ()
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
void moa.recommender.rc.data.RecommenderData.close ()
Implemented in moa.recommender.rc.data.AbstractRecommenderData.
int moa.recommender.rc.data.RecommenderData.countRatingsItem (int itemID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
int moa.recommender.rc.data.RecommenderData.countRatingsUser (int userID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
void moa.recommender.rc.data.RecommenderData.disableUpdates (boolean disable)
Implemented in moa.recommender.rc.data.AbstractRecommenderData.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
double moa.recommender.rc.data.RecommenderData.getAvgRatingItem (int itemID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
double moa.recommender.rc.data.RecommenderData.getAvgRatingUser (int userID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
double moa.recommender.rc.data.RecommenderData.getGlobalMean ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), and moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
Set<Integer> moa.recommender.rc.data.RecommenderData.getItems ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train().
double moa.recommender.rc.data.RecommenderData.getMaxRating ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), and moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
double moa.recommender.rc.data.RecommenderData.getMinRating ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.predictRating(), and moa.recommender.rc.predictor.impl.BaselinePredictor.predictRatings().
int moa.recommender.rc.data.RecommenderData.getNumItems ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
int moa.recommender.rc.data.RecommenderData.getNumRatings ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train().
int moa.recommender.rc.data.RecommenderData.getNumUsers ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
double moa.recommender.rc.data.RecommenderData.getRating (int userID, int itemID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
SparseVector moa.recommender.rc.data.RecommenderData.getRatingsItem (int itemID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainItem(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
SparseVector moa.recommender.rc.data.RecommenderData.getRatingsUser (int userID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.trainUser(), and moa.recommender.rc.predictor.impl.BRISMFPredictor.updateSetRating().
Set<Integer> moa.recommender.rc.data.RecommenderData.getUsers ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train().
boolean moa.recommender.rc.data.RecommenderData.itemExists (int itemID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Iterator<Rating> moa.recommender.rc.data.RecommenderData.ratingIterator ()
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.recommender.rc.predictor.impl.BRISMFPredictor.train().
void moa.recommender.rc.data.RecommenderData.removeItem (int itemID)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
void moa.recommender.rc.data.RecommenderData.removeRating (int userID, int itemID)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
void moa.recommender.rc.data.RecommenderData.removeUser (int userID)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
void moa.recommender.rc.data.RecommenderData.setRating (int userID, int itemID, double rating)
Implemented in moa.recommender.rc.data.AbstractRecommenderData, and moa.recommender.rc.data.impl.MemRecommenderData.
Referenced by moa.tasks.EvaluateOnlineRecommender.doMainTask().
boolean moa.recommender.rc.data.RecommenderData.userExists (int userID)
Implemented in moa.recommender.rc.data.impl.MemRecommenderData.
The documentation for this interface was generated from the following file:
main/java/moa/recommender/rc/data/RecommenderData.java