MOA: moa.MOAObject Interface Reference
moa.MOAObject Interface Reference
Interface implemented by classes in MOA, so that all are serializable, can produce copies of their objects, and can measure its memory size.
Public Member Functions
int measureByteSize ()
Gets the memory size of this object.
MOAObject copy ()
This method produces a copy of this object.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Detailed Description
Interface implemented by classes in MOA, so that all are serializable, can produce copies of their objects, and can measure its memory size.
They also give a string description.
Author:
Richard Kirkby (rkirkby@cs.waikato.ac.nz)
Version:
Revision
7
Definition at line 32 of file MOAObject.java.
Member Function Documentation
MOAObject moa.MOAObject.copy ()
This method produces a copy of this object.
Returns:
a copy of this object
Implemented in moa.AbstractMOAObject, moa.classifiers.AbstractClassifier, moa.classifiers.Classifier, moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ChangeDetector, moa.clusterers.AbstractClusterer, moa.clusterers.Clusterer, moa.clusterers.denstream.MicroCluster, moa.core.AutoExpandVector< T >, moa.options.AbstractOption, moa.options.AbstractOptionHandler, moa.options.Option, and moa.options.OptionHandler.
Referenced by moa.core.AutoExpandVector< T >.copy(), moa.classifiers.AbstractMultipleRegressorTestCase.getRegressionEvaluatorSetups(), and moa.classifiers.AbstractMultipleClassifierTestCase.getRegressionEvaluatorSetups().
void moa.MOAObject.getDescription (StringBuilder sb, int indent)
Returns a string representation of this object.
Used in AbstractMOAObject.toString to give a string representation of the object.
Parameters:
sb the stringbuilder to add the description
indent the number of characters to indent
Implemented in moa.classifiers.AbstractClassifier, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.BinaryTreeNumericAttributeClassObserverRegression, moa.classifiers.core.attributeclassobservers.FIMTDDNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GaussianNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.GreenwaldKhannaNumericAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NominalAttributeClassObserver, moa.classifiers.core.attributeclassobservers.NullAttributeClassObserver, moa.classifiers.core.attributeclassobservers.VFMLNumericAttributeClassObserver, moa.classifiers.core.AttributeSplitSuggestion, moa.classifiers.core.conditionaltests.NominalAttributeBinaryTest, moa.classifiers.core.conditionaltests.NominalAttributeMultiwayTest, moa.classifiers.core.conditionaltests.NumericAttributeBinaryTest, moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ADWIN.List, moa.classifiers.core.driftdetection.ADWIN.ListItem, moa.classifiers.core.driftdetection.ADWIN, moa.classifiers.core.driftdetection.ADWINChangeDetector, moa.classifiers.core.driftdetection.ChangeDetector, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_A_Test, moa.classifiers.core.driftdetection.HDDM_W_Test, moa.classifiers.core.driftdetection.PageHinkleyDM, moa.classifiers.core.splitcriteria.GiniSplitCriterion, moa.classifiers.core.splitcriteria.InfoGainSplitCriterion, moa.classifiers.core.splitcriteria.VarianceReductionSplitCriterion, moa.classifiers.rules.core.conditionaltests.NumericAttributeBinaryRulePredicate, moa.classifiers.rules.core.Rule, moa.classifiers.rules.core.voting.InverseErrorWeightedVote, moa.classifiers.rules.core.voting.UniformWeightedVote, moa.classifiers.rules.Predicates, moa.classifiers.rules.RuleClassification, moa.classifiers.trees.FIMTDD.FIMTDDPerceptron, moa.classifiers.trees.HoeffdingOptionTree.Node, moa.classifiers.trees.HoeffdingTree.Node, moa.classifiers.trees.ORTO.Node, moa.classifiers.trees.ORTO.ORTOPerceptron, moa.cluster.Cluster, moa.cluster.Clustering, moa.clusterers.AbstractClusterer, moa.clusterers.denstream.Timestamp, moa.core.AutoExpandVector< T >, moa.core.DoubleVector, moa.core.GaussianEstimator, moa.core.GreenwaldKhannaQuantileSummary, moa.core.Measurement, moa.core.utils.Converter, moa.evaluation.BasicClassificationPerformanceEvaluator, moa.evaluation.BasicClusteringPerformanceEvaluator, moa.evaluation.BasicConceptDriftPerformanceEvaluator, moa.evaluation.BasicRegressionPerformanceEvaluator, moa.evaluation.EWMAClassificationPerformanceEvaluator, moa.evaluation.FadingFactorClassificationPerformanceEvaluator, moa.evaluation.LearningCurve, moa.evaluation.LearningEvaluation, moa.evaluation.MeasureCollection, moa.evaluation.MultilabelWindowClassificationPerformanceEvaluator, moa.evaluation.WindowClassificationPerformanceEvaluator, moa.evaluation.WindowRegressionPerformanceEvaluator, moa.options.AbstractOption, moa.options.Options, moa.recommender.data.MemRecommenderData, moa.recommender.dataset.impl.FlixsterDataset, moa.recommender.dataset.impl.JesterDataset, moa.recommender.dataset.impl.MovielensDataset, moa.recommender.predictor.BaselinePredictor, moa.recommender.predictor.BRISMFPredictor, moa.streams.ArffFileStream, moa.streams.CachedInstancesStream, moa.streams.clustering.FileStream, moa.streams.clustering.RandomRBFGeneratorEvents, moa.streams.ConceptDriftRealStream, moa.streams.ConceptDriftStream, moa.streams.FilteredStream, moa.streams.filters.AddNoiseFilter, moa.streams.filters.CacheFilter, moa.streams.filters.ReplacingMissingValuesFilter, moa.streams.generators.AgrawalGenerator, moa.streams.generators.cd.AbstractConceptDriftGenerator, moa.streams.generators.HyperplaneGenerator, moa.streams.generators.LEDGenerator, moa.streams.generators.LEDGeneratorDrift, moa.streams.generators.multilabel.MetaMultilabelGenerator, moa.streams.generators.RandomRBFGenerator, moa.streams.generators.RandomRBFGeneratorDrift, moa.streams.generators.RandomTreeGenerator, moa.streams.generators.SEAGenerator, moa.streams.generators.STAGGERGenerator, moa.streams.generators.WaveformGenerator, moa.streams.generators.WaveformGeneratorDrift, moa.streams.MultiFilteredStream, moa.tasks.AbstractTask, and moa.tasks.FailedTaskReport.
Referenced by moa.integration.SimpleClusterTest.doTask(), weka.classifiers.meta.MOA.toString(), and moa.AbstractMOAObject.toString().
int moa.MOAObject.measureByteSize ()
Gets the memory size of this object.
Returns:
the memory size of this object
Implemented in moa.AbstractMOAObject, moa.classifiers.trees.HoeffdingOptionTree, moa.classifiers.trees.HoeffdingTree, and moa.core.AutoExpandVector< T >.
Referenced by moa.tasks.EvaluatePrequentialRegression.doMainTask(), moa.tasks.EvaluatePrequential.doMainTask(), moa.tasks.EvaluateInterleavedTestThenTrain.doMainTask(), moa.tasks.EvaluateInterleavedChunks.doMainTask(), and moa.classifiers.meta.AccuracyWeightedEnsemble.removePoorestModelBytes().
The documentation for this interface was generated from the following file:
main/java/moa/MOAObject.java