MOA: moa.classifiers.core.driftdetection.ChangeDetector Interface Reference
moa.classifiers.core.driftdetection.ChangeDetector Interface Reference
Change Detector interface to implement methods that detects change.
Public Member Functions
void resetLearning ()
Resets this change detector.
void input (double inputValue)
Adding a numeric value to the change detector<br>
.
boolean getChange ()
Gets whether there is change detected.
boolean getWarningZone ()
Gets whether the change detector is in the warning zone, after a warning alert and before a change alert.
double getEstimation ()
Gets the prediction of next values.
double getDelay ()
Gets the length of the delay in the change detected.
double[] getOutput ()
Gets the output state of the change detection.
void getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
ChangeDetector copy ()
Produces a copy of this drift detection method.
Detailed Description
Change Detector interface to implement methods that detects change.
Author:
Albert Bifet (abifet at cs dot waikato dot ac dot nz)
Version:
Revision
7
Definition at line 29 of file ChangeDetector.java.
Member Function Documentation
ChangeDetector moa.classifiers.core.driftdetection.ChangeDetector.copy ()
Produces a copy of this drift detection method.
Returns:
the copy of this drift detection method
Implements moa.options.OptionHandler.
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector.
Referenced by moa.classifiers.core.driftdetection.AbstractChangeDetector.copy().
boolean moa.classifiers.core.driftdetection.ChangeDetector.getChange ()
Gets whether there is change detected.
Returns:
true if there is change
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
double moa.classifiers.core.driftdetection.ChangeDetector.getDelay ()
Gets the length of the delay in the change detected.
Returns:
he length of the delay in the change detected
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector.
void moa.classifiers.core.driftdetection.ChangeDetector.getDescription (StringBuilder sb, int indent)
Returns a string representation of the model.
Parameters:
out the stringbuilder to add the description
indent the number of characters to indent
Implements moa.MOAObject.
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ADWINChangeDetector, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_A_Test, moa.classifiers.core.driftdetection.HDDM_W_Test, and moa.classifiers.core.driftdetection.PageHinkleyDM.
double moa.classifiers.core.driftdetection.ChangeDetector.getEstimation ()
Gets the prediction of next values.
Returns:
a prediction of the next value
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector, and moa.classifiers.core.driftdetection.HDDM_A_Test.
double [] moa.classifiers.core.driftdetection.ChangeDetector.getOutput ()
Gets the output state of the change detection.
Returns:
an array with the number of change detections, number of warnings, delay, and estimation.
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector.
Referenced by moa.learners.ChangeDetectorLearner.getVotesForInstance().
boolean moa.classifiers.core.driftdetection.ChangeDetector.getWarningZone ()
Gets whether the change detector is in the warning zone, after a warning alert and before a change alert.
Returns:
true if the change detector is in the warning zone
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector.
Referenced by moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
void moa.classifiers.core.driftdetection.ChangeDetector.input (double inputValue)
Adding a numeric value to the change detector<br>
.
The output of the change detector is modified after the insertion of a new item inside.
Parameters:
inputValue the number to insert into the change detector
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ADWINChangeDetector, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_A_Test, moa.classifiers.core.driftdetection.HDDM_W_Test, and moa.classifiers.core.driftdetection.PageHinkleyDM.
Referenced by moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods.input(), moa.learners.ChangeDetectorLearner.trainOnInstanceImpl(), and moa.classifiers.drift.DriftDetectionMethodClassifier.trainOnInstanceImpl().
void moa.classifiers.core.driftdetection.ChangeDetector.resetLearning ()
Resets this change detector.
It must be similar to starting a new change detector from scratch.
Implemented in moa.classifiers.core.driftdetection.AbstractChangeDetector, moa.classifiers.core.driftdetection.ADWINChangeDetector, moa.classifiers.core.driftdetection.CusumDM, moa.classifiers.core.driftdetection.DDM, moa.classifiers.core.driftdetection.EDDM, moa.classifiers.core.driftdetection.EnsembleDriftDetectionMethods, moa.classifiers.core.driftdetection.EWMAChartDM, moa.classifiers.core.driftdetection.GeometricMovingAverageDM, moa.classifiers.core.driftdetection.HDDM_A_Test, moa.classifiers.core.driftdetection.HDDM_W_Test, and moa.classifiers.core.driftdetection.PageHinkleyDM.
The documentation for this interface was generated from the following file:
main/java/moa/classifiers/core/driftdetection/ChangeDetector.java